### ISSUE TITLE
Context Shifting To Increase Speed Dramatically

### ISSUE THREAD

**Issue by chigkim** [ollama/ollama#1007]
koboldcpp v1.48.1 now has implemented this feature, and apparently it increased the speed dramatically because it doesn't have to reprocess previous context to generate a new response.

Could you look into implement this feature to Ollama as well?

https://github.com/LostRuins/koboldcpp/releases/tag/v1.48.1

"Context Shifting (A.K.A. EvenSmarterContext) - This feature utilizes KV cache shifting to automatically remove old tokens from context and add new ones without requiring any reprocessing. So long as you use no memory/fixed memory and don't use world info, you should be able to avoid almost all reprocessing between consecutive generations even at max context. This does not consume any additional context space, making it superior to SmartContext."

Thanks!

**Comment by jmorganca** [comment]
Hi there, thank you so much for the issue. At this point we've seen quite a few quality concerns with context shifting and will be focused on helping understand context utilization (e.g. API will return a field when the context limit is hit) vs shifting the context.

We may re-introduce context shifting later on once we can do so between bos/eos tokens but currently context shifting happens at arbitrary points in the context which causes infinite and/or bad generations

**Comment by chigkim** [comment]
Could you expose tokenize and detokenize feature of llama.cpp api? Then we can know the token count before feeding text for generation. It seems there are a lot of interest in this.

**Comment by chigkim** [comment]
https://github.com/ggerganov/llama.cpp/blob/master/examples/server/README.md

https://github.com/ollama/ollama/issues/4186

https://github.com/ollama/ollama/issues/1716

https://github.com/ollama/ollama/issues/3582

https://github.com/ollama/ollama/issues/1345

**Comment by joewinke** [comment]
> Could you expose tokenize and detokenize feature of llama.cpp api? Then we can know the token count before feeding text for generation. It seems there are a lot of interest in this.

This would allow for UX that shows % of context window used, which would be helpful in many contexts.
