### ISSUE TITLE
Add Timeout as User Configurable

### ISSUE THREAD

**Issue by valentimarco** [ollama/ollama#1048]
I have read that the timer is hardcoded with a timeout of 5 minutes and i don't wanna send a empty string every 5m to let it alive...
What are at the moment, the complications of a User Configurable timeout?

**Comment by horw** [comment]
Hi! If maintainer agree, It will be nice if I can try to implement it.
Look like good first issue.

**Comment by horw** [comment]
I tested it, and the server woke up after sending a request to it.

**Comment by valentimarco** [comment]
@horw i know but i wanna have It 24/7.  the model Needs to serve multiple clients with different Active time...

**Comment by horw** [comment]
Which api you call?

**Comment by horw** [comment]
@valentimarco Do you use the following API: http://127.0.0.1:11434/api/generate?

**Comment by valentimarco** [comment]
I use langchain class but the problem Is the. Same etheir langchain or end point

**Comment by Hill-Brandon-M** [comment]
I've been using the following on , which has been working fine for me: 

`curl -G http://<HOST>:11434/`

**Comment by trenta3** [comment]
I'd like to know if the runner startup timeout (currently 30secs) can be made user configurable as well

**Comment by jmorganca** [comment]
This is now fixed! You can specify the `keep_alive` option in the API: https://github.com/ollama/ollama/blob/main/docs/api.md#generate-a-completion
