### ISSUE TITLE
Requesting support for basic auth or API key authentication

### ISSUE THREAD

**Issue by sebiweise** [ollama/ollama#1053]
It would be great to have some sort of authentication in front of the ollama api. Currently I´m using Nginx Proxy Manager to add a Access List to prevent unauthorized access but a standard way implemented into Ollama itself would be great for all developers that are integrating Ollama into there software.

**Comment by priamai** [comment]
Please that will be fantastic!

**Comment by johnnyq** [comment]
Yes I'm also looking for API Key Support, were currently working on the integration with Ollama with our opensource project ITFlow and it would be a life saver. Thanks

**Comment by d3cline** [comment]
I read #849 but this should be baked into the main app imo, as others have stated its better for standardization.

**Comment by tweedge** [comment]
+1, IMHO Ollama should offer some sort of simple, native authentication (as an option, even if it's not required, is fine). While I understand that the team is designing around local access, publicly accessible Ollama instances are already showing up on the internet.

* https://www.shodan.io/search?query=%22Ollama+is+running%22
* https://search.censys.io/search?resource=hosts&sort=RELEVANCE&per_page=25&virtual_hosts=EXCLUDE&q=%22Ollama+is+running%22

**Comment by AnthonMS** [comment]
@sebiweise Can you provide the nginx config for proxying the traffic to ollama? I am new to the world of nginx and proxy servers, but really want this set up with some basic authentication and I have nginx serving other services already. Sorry if I'm inconveniencing.

For example, I have ollama running on the host 192.168.1.100 and nginx running on host 192.168.1.200

I have tried with some basic configs like these

```
server {
    listen 11434;

    location / {
        auth_basic "Restricted Content";
        auth_basic_user_file /etc/nginx/.htpasswd;

        proxy_pass http://192.168.1.100:11434;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}
```
But I am not getting a connection. I have set the OLLAMA_HOST variable on the host running that, to be `0.0.0.0` and I can connect to it on the local network by going to it's IP and port.

**Comment by p-try** [comment]
@sebiweise This doesn't look too bad. But:

- You use the same port for nginx and ollama which doesn't work. Change the "listen" directive to another port, e.g. 11435. You may also reset OLLAMA_HOST to the original value (as it will only receive connections from localhost once the proxy is set up).
- Basic Auth will probably not work with most API clients. Instead, use [JWT authentication](https://docs.nginx.com/nginx/admin-guide/security-controls/configuring-jwt-authentication/).

**Comment by Kavan72** [comment]
> @sebiweise This doesn't look too bad. But:
> 
> * You use the same port for nginx and ollama which doesn't work. Change the "listen" directive to another port, e.g. 11435. You may also reset OLLAMA_HOST to the original value (as it will only receive connections from localhost once the proxy is set up).
> * Basic Auth will probably not work with most API clients. Instead, use [JWT authentication](https://docs.nginx.com/nginx/admin-guide/security-controls/configuring-jwt-authentication/).

or just a basic API key, similar to how OpenAI uses authentication on their client.

**Comment by AnthonMS** [comment]
> @sebiweise This doesn't look too bad. But:
> 
> - You use the same port for nginx and ollama which doesn't work. Change the "listen" directive to another port, e.g. 11435. You may also reset OLLAMA_HOST to the original value (as it will only receive connections from localhost once the proxy is set up).
> - Basic Auth will probably not work with most API clients. Instead, use [JWT authentication](https://docs.nginx.com/nginx/admin-guide/security-controls/configuring-jwt-authentication/).

I use the same port on 2 different host machines, correct. So the ollama service is not running on the same host as the nginx is. So this is fine.

**Comment by bartolli** [comment]
I spent a few days trying to get the Ollama Go server to work with native `api_key` authentication but had no luck. So, I ended up making a Docker image with a Caddy server to securely handle authentication and proxy requests to a local Ollama instance, using environment-based API key validation for better security. Check out the links to Docker Hub and GitHub.

Docker: https://hub.docker.com/r/bartolli497/ollama-bearer-auth
Github: https://github.com/bartolli/ollama-bearer-auth

**Comment by PyroGenesis** [comment]
This is my nginx configuration to expose Ollama over the web with an API Key and HTTPS

```nginx
    upstream ollama {
        server               localhost:11434;
    }

    server {
        listen              8000 ssl;
        server_name         ollama.mydomain.com;

        # for ssl
        ssl_certificate     "path/to/cert.crt";
        ssl_certificate_key "path/to/private.key";
        ssl_protocols       TLSv1 TLSv1.1 TLSv1.2;
        ssl_ciphers         HIGH:!aNULL:!MD5;

        location / {
            # Check if the Authorization header is present and has the correct Bearer token / API Key
            set $token "Bearer MY_PRIVATE_API_KEY";
            if ($http_authorization != $token) {
                return 401 "Unauthorized";
            }
            
            # The localhost headers are to simulate the forwarded request as coming from localhost
            # because I didn't want to set the Ollama origins as *
            proxy_set_header  Host "localhost";
            proxy_set_header  X-Real-IP "127.0.0.1";
            proxy_set_header  X-Forwarded-For "127.0.0.1";
            proxy_set_header  X-Forwarded-Proto $scheme;
            proxy_pass        http://ollama;  # Forward request to the actual web service
        }
    }
```

**Comment by neuhaus** [comment]
@AnthonMS don't use this line in your nginx host configuration file:

        proxy_set_header Host $host;

instead use this line:

        proxy_set_header Host localhost:11434;

Works for me.

**Comment by AnthonMS** [comment]
> @AnthonMS don't use this line in your nginx host configuration file:
> 
>         proxy_set_header Host $host;
> 
> instead use this line:
> 
>         proxy_set_header Host localhost:11434;
> 
> Works for me.


In this example the Ollama service is not running on the same machine as the nginx service. The nginx config I have given works.

**Comment by kemalelmizan** [comment]
Ollama server is using gin, and gin offers [basic auth middleware](https://gin-gonic.com/docs/examples/using-basicauth-middleware/). I created PR for introducing basic auth for ollama [here](https://github.com/ollama/ollama/pull/6223) but have similar experience with @sammcj, I have asked on the discord server but could not get the PR reviewed 😔

**Comment by sammcj** [comment]
Nice work @kemalelmizan! Hopefully someone eventually picks up your PR :)

**Comment by neuhaus** [comment]
> Ollama server is using gin, and gin offers [basic auth middleware](https://gin-gonic.com/docs/examples/using-basicauth-middleware/). I created PR for introducing basic auth for ollama [here](https://github.com/ollama/ollama/pull/6223) but have similar experience with @sammcj, I have asked on the discord server but could not get the PR reviewed 😔

Very nice. It would also be useful to add **Bearer authentication** to gin (instead?) because some clients only support Bearer authentication but not basic auth, for example the Leo AI feature of the Brave browser.

**Comment by kesor** [comment]
I released a docker container that packaged a reverse proxy (nginx) into a Dockerfile with Cloudflare tunnel to open it up on a public hostname on the internet, but also with a hardcoded token required for access. https://github.com/kesor/ollama-proxy

**Comment by PyroGenesis** [comment]
> > Ollama server is using gin, and gin offers [basic auth middleware](https://gin-gonic.com/docs/examples/using-basicauth-middleware/). I created PR for introducing basic auth for ollama [here](https://github.com/ollama/ollama/pull/6223) but have similar experience with @sammcj, I have asked on the discord server but could not get the PR reviewed 😔
> 
> Very nice. It would also be useful to add **Bearer authentication** to gin (instead?) because some clients only support Bearer authentication but not basic auth, for example the Leo AI feature of the Brave browser.
> 
> Ideally the list of valid tokens is taken from a file.

Autogen is another framework that supports Bearer authentication only.

**Comment by StefMa** [comment]
It seems like this issue can be closed because the relevant PR got rejected.
See https://github.com/ollama/ollama/pull/6223#issuecomment-2496432344

@jmorganca can we close this? 🤔 
This is this something you don't want to add, right? 🤔

**Comment by jmorganca** [comment]
Hi folks, and thanks for the ping @StefMa. Given the different auth configurations, we try to keep Ollama focused on serving an http API that can be fronted by a number of proxy servers such as nginx, caddy and more – which often support many different auth services. This allows the maintainer team to focus on core model serving. I really appreciate the comments on this thread and would be happy to add links in the main README or elsewhere on how to configure different frontends in front of Ollama.

**Comment by neerax** [comment]
I understand that the team prefers to focus on the core functionality, but the lack of even a simple and standard native authentication mechanism discourages support in libraries, frontends, and low/no-code tools.

**Comment by hammadtq** [comment]
I just finished wiring up **Attach Gateway** – a PyPi package that adds OIDC/JWT (works with Google, Auth0, etc.) and A2A hand-off in front of Ollama. 

```
pip install attach-dev
export ENGINE_URL=http://localhost:11434      # Ollama port  
export OIDC_ISSUER=https://your-issuer/       # Google/Auth0/Okta
attach-gateway --port 8080                    # gated
```
Feedback / issues welcome!

https://github.com/attach-dev/attach-gateway

**Comment by neuhaus** [comment]
> Feedback / issues welcome!
> 
> https://github.com/attach-dev/attach-gateway

Interesting. Could this component also be used to limit usage, i.e. a maximum amount of incoming and/or outgoing tokens?

**Comment by hammadtq** [comment]
> > Feedback / issues welcome!
> > https://github.com/attach-dev/attach-gateway
> 
> Interesting. Could this component also be used to limit usage, i.e. a maximum amount of incoming and/or outgoing tokens?

Yes, I will be adding a rate-limiting layer this week for v0.3. Happy to accept PRs or issues for any specific quota or billing-related use cases you have in mind.
