### ISSUE TITLE
Examples  deploy  Sagemaker AWS

### ISSUE THREAD

**Issue by DimIsaev** [ollama/ollama#1058]
is there an example of deploy a model using an ollama in a Endpoint SageMaker AWS  ?

**Comment by jlippold** [comment]
Economically Sagemaker is pay for what you use, as opposed to running an EC2 instance 24/7 on AWS which is expensive if using a p2 instance family. https://aws.amazon.com/ec2/instance-types/p2/

I don't believe you have terminal access with SageMaker. Is this something that amazon has to implement, or is this something we can do as users?

**Comment by DimIsaev** [comment]
> Economically Sagemaker is pay for what you use, as opposed to running an EC2 instance 24/7 on AWS which is expensive if using a p2 instance family. https://aws.amazon.com/ec2/instance-types/p2/

It seems the question was different...

Sagemaker works great via APIGateway AWS

do you need a link?

**Comment by jmorganca** [comment]
Hi there, SageMaker notebooks usually have a terminal tab where I believe you can install Ollama using the instructions at [ollama.com/download/linux](ollama.com/download/linux): https://docs.aws.amazon.com/sagemaker/latest/dg/howitworks-access-ws.html
