### ISSUE TITLE
MacOS Env Variables

### ISSUE THREAD

**Issue by ageorgios** [ollama/ollama#1107]
how to start ollama with OLLAMA_ORIGINS=* OLLAMA_HOST=127.0.0.1:11435 ?

**Comment by Gsvd** [comment]
`OLLAMA_ORIGINS='*' ollama serve`

But before that make sure to stop the running service, for example:
```
> launchctl list | grep ollama
70718	0	application.com.electron.ollama.61282955.61282961
> launchctl stop application.com.electron.ollama.61282955.61282961
```

**Comment by ageorgios** [comment]
Is there a way to enclose it into the launchctl script ?

**Comment by jmorganca** [comment]
Yes! This can be done here: https://github.com/ollama/ollama/blob/main/docs/faq.md#setting-environment-variables-on-mac

In future versions of the macOS app this will get easier to do in Ollama itself
