### ISSUE TITLE
json response stalls? 

### ISSUE THREAD

**Issue by hemanth** [ollama/ollama#1135]
```
/tmp 
❯ ollama --version
ollama version 0.1.9
```

https://github.com/jmorganca/ollama/assets/18315/d0d8ecb1-142f-464c-bb49-8d147eb3d322

Sometimes we see an empty response:

```json
{"model":"llama2","created_at":"2023-11-15T05:46:21.685664Z","response":"{} ","done":true,"context":[29961,25580,29962,3532,14816,29903,29958,5299,829,14816,29903,6778,13,13,29911,514,592,263,270,328,2212,446,518,29914,25580,29962,6571,29871],"total_duration":216306917,"load_duration":982333,"prompt_eval_count":1,"eval_count":3,"eval_duration":192199000}
```

**Comment by jmorganca** [comment]
Hi @hemanth ! Thanks for the issue. would it be possible to share an example prompt that causes this? Also I think your video may be of another project 😊

**Comment by technovangelist** [comment]
@hemanth can you provide an example of this?

**Comment by hemanth** [comment]
Just the video. I didn't change any prompt. 

@technovangelist @jmorganca 

<img width="764" alt="image" src="https://github.com/jmorganca/ollama/assets/18315/7ca82fb2-63fb-4024-9c03-8af08026c86a">

**Comment by technovangelist** [comment]
But the video and this screenshot don't show anything having to do with ollama. Is there anything you can show that demonstrates the problem. We would love to solve any issues you have. But we need a little info about what is the problem and how did you get there.

**Comment by hemanth** [comment]
Ah, sorry, my bad! [/me had mapped this issue mentally as the create-llama ticket :D] 

Here is the correct recording...

https://github.com/jmorganca/ollama/assets/18315/f0897e35-c569-4e9d-ad25-8def1e3b82d5

**Comment by atorr0** [comment]
Hi @hemanth , did you try it with newer versions (like https://github.com/jmorganca/ollama/releases/tag/v0.1.17)?

**Comment by rmallick6806** [comment]
Running into the same issue and I'm using v0.0.17. JSON format mode always hangs. Without the flag, I am able to get responses.

**Comment by horiacristescu** [comment]
Same problem. 
I tried with v0.1.18 and for every --format json request it doesn't stop. After printing the JSON it continues to print empty lines forever. Because it never stops printing empty lines, it is as if it hangs forever.

Does the JSON format model know when to stop? What stop words should I use? I tried stop="\n\n\n" without success.

**Comment by seanmavley** [comment]
Related to #1910

**Comment by BruceMacD** [comment]
Hi all, this is an ongoing issue with how the response is mapped to JSON. If you see this issue please try adding a system prompt that specifies a JSON response is expected.

For example in the API:
```bash
curl http://127.0.0.1:11434/api/chat -d '{
    "model": "llama2",
    "format": "json",
    "stream": false,
    "messages": [
        {
            "role": "system",
            "content": "Respond only in JSON."
        },
        {
            "role": "user",
            "content": "Give me a list of emojis to descriptions."
        }
    ]
}'
```

Resolving this issue to consolidate it with #1182 , which I will continue work in.
