### ISSUE TITLE
The ollama parameters in the modelfile do not support num_beams

### ISSUE THREAD

**Issue by garth-waters** [ollama/ollama#1137]
Thanks very much for a great product

I am using a modelfile to create a SqlDecoder2 custom model.
The num_beams parameter improves the accuracy of the model by a lot.

However, this parameter is not yet supported. 
Is there any intention of including this parameter in the future?

Many Thanks
Garth

**Comment by garth-waters** [comment]
Thank you so much

**Comment by jmorganca** [comment]
Hi @garth-waters `num_beams` isn't something supported in Ollama's API today, and may not be something easy to expose in the future as Ollama's inference engine evolves. May I ask what you are looking to use it for? Feel free to shoot me an email (email in profile :)
