### ISSUE TITLE
Support forvietnamese-llama2-7b

### ISSUE THREAD

**Issue by khoint0210** [ollama/ollama#1141]
Hi folk 
Really love this project
I just wonder can you guy support this model 
https://huggingface.co/bkai-foundation-models/vietnamese-llama2-7b-40GB

It would be fantastic to have this run  inside Ollama

**Comment by jmorganca** [comment]
Hi @khoint0210 it should be possible to [import](https://github.com/ollama/ollama/blob/main/docs/import.md) this model to Ollama and publish it on ollama.com. Let me know if you hit any issues and I can help you convert – so sorry for the slow reply.
