### ISSUE TITLE
Add support for llamacpp min_p sampler

### ISSUE THREAD

**Issue by JoseConseco** [ollama/ollama#1142]
https://github.com/ggerganov/llama.cpp/pull/3841
![obraz](https://github.com/jmorganca/ollama/assets/13521338/26509c9f-31a1-4544-8d8b-f3418e73a06c)

It supposed to give better results compared to top_k, top_p. I tried to add this  min_p - parameter to llama options, but it was unrecognized.

**Comment by fast-90** [comment]
I would love to see this in Ollama.

**Comment by Robitx** [comment]
https://github.com/jmorganca/ollama/pull/1825

**Comment by FellowTraveler** [comment]
I think the PR needs to be rebased again because it says "can't be automatically merged."
Unless it's waiting on something else in the workflow?
