### ISSUE TITLE
loading yi:6b-200k seems take forever

### ISSUE THREAD

**Issue by happy15** [ollama/ollama#1150]
Hi there, just upgraded to Ollama v0.1.9 and tried to run yi:6b-200k. And it seems to take forever to load after pulling the model. After that if I tried to run zephyr it also takes forever to load.

Then I restarted ollama, and ran zephyr successfully.

My env is mbp 14 with M1 pro and 16g ram. 

Anything do I miss?

Thanks.

**Comment by igorschlum** [comment]
You have to check the memory usage on your computer. Have you tried to restart your mac and launch only Ollama?

**Comment by easp** [comment]
I had trouble when trying to load that model on my 32GB system. From ~/.ollama/logs/server it appeared that it couldn't allocate enough memory for GPU use, but then rather than exiting with an error, it just hung. In its hung state it couldn't respond to requests to run other models.

Ultimately though, you don't have enough memory. 200k context takes a lot of memory. I remember it being ~10-12GB. Also, I'm not sure any of the 20K+ context models are really working reliably yet.

**Comment by mchiang0610** [comment]
Thanks @easp, I'm able to reproduce on my end as well. Adding logs to this: 

```
ggml_metal_init: GPU name:   Apple M1 Pro
ggml_metal_init: GPU family: MTLGPUFamilyApple7 (1007)
ggml_metal_init: hasUnifiedMemory              = true
ggml_metal_init: recommendedMaxWorkingSetSize  = 10922.67 MB
ggml_metal_init: maxTransferRate               = built-in GPU
llama_new_context_with_model: compute buffer total size = 12920.75 MB
llama_new_context_with_model: max tensor size =   205.08 MB
ggml_metal_add_buffer: allocated 'data            ' buffer, size =  3318.16 MB, ( 3318.78 / 10922.67)
ggml_metal_add_buffer: allocated 'kv              ' buffer, size =  8192.00 MB, offs =            0
ggml_metal_add_buffer: allocated 'kv              ' buffer, size =  4308.03 MB, offs =   8589918208, (15818.81 / 10922.67), warning: current allocated size is greater than the recommended max working set size
ggml_metal_add_buffer: allocated 'alloc           ' buffer, size =  8192.00 MB, offs =            0
ggml_metal_add_buffer: allocated 'alloc           ' buffer, size =  4722.66 MB, offs =   8589918208, (28733.47 / 10922.67), warning: current allocated size is greater than the recommended max working set size
ggml_metal_get_buffer: error: buffer is nil
2023/11/16 11:18:42 llama.go:438: error starting llama runner: timed out waiting for llama runner to start
[GIN] 2023/11/16 - 11:30:49 | 200 |   34.591458ms |       127.0.0.1 | GET      "/api/tags"
```

**Comment by BruceMacD** [comment]
Thanks for the report, this appears to happen on systems that don't have enough memory to load the large model context. I'm looking into handling this better.

For future readers, if you see this error it means you dont have enough memory to run the model, as easp mentioned.

**Comment by happy15** [comment]
> Thanks @easp, I'm able to reproduce on my end as well. Adding logs to this:
> 
> ```
> ggml_metal_init: GPU name:   Apple M1 Pro
> ggml_metal_init: GPU family: MTLGPUFamilyApple7 (1007)
> ggml_metal_init: hasUnifiedMemory              = true
> ggml_metal_init: recommendedMaxWorkingSetSize  = 10922.67 MB
> ggml_metal_init: maxTransferRate               = built-in GPU
> llama_new_context_with_model: compute buffer total size = 12920.75 MB
> llama_new_context_with_model: max tensor size =   205.08 MB
> ggml_metal_add_buffer: allocated 'data            ' buffer, size =  3318.16 MB, ( 3318.78 / 10922.67)
> ggml_metal_add_buffer: allocated 'kv              ' buffer, size =  8192.00 MB, offs =            0
> ggml_metal_add_buffer: allocated 'kv              ' buffer, size =  4308.03 MB, offs =   8589918208, (15818.81 / 10922.67), warning: current allocated size is greater than the recommended max working set size
> ggml_metal_add_buffer: allocated 'alloc           ' buffer, size =  8192.00 MB, offs =            0
> ggml_metal_add_buffer: allocated 'alloc           ' buffer, size =  4722.66 MB, offs =   8589918208, (28733.47 / 10922.67), warning: current allocated size is greater than the recommended max working set size
> ggml_metal_get_buffer: error: buffer is nil
> 2023/11/16 11:18:42 llama.go:438: error starting llama runner: timed out waiting for llama runner to start
> [GIN] 2023/11/16 - 11:30:49 | 200 |   34.591458ms |       127.0.0.1 | GET      "/api/tags"
> ```

Thanks, checked the log and saw the error.

**Comment by happy15** [comment]
> I had trouble when trying to load that model on my 32GB system. From ~/.ollama/logs/server it appeared that it couldn't allocate enough memory for GPU use, but then rather than exiting with an error, it just hung. In its hung state it couldn't respond to requests to run other models.
> 
> Ultimately though, you don't have enough memory. 200k context takes a lot of memory. I remember it being ~10-12GB. Also, I'm not sure any of the 20K+ context models are really working reliably yet.

Thanks for the info.

**Comment by happy15** [comment]
Thanks everyone for diagnosis and info.

**Comment by happy15** [comment]
https://github.com/01-ai/Yi/issues/56#issuecomment-1800872082

cross link related discussion on yi model's official repo.

They mentioned to install flash attention to control the memory usage. Have ollama already done it?

**Comment by BruceMacD** [comment]
Thanks for the heads up @happy15 the linked issue wouldn't apply to Ollama as far as I can tell, it seems to be related to a missing package in their python project which we dont use.

**Comment by easp** [comment]
The underlying issue not handling this situation gracefully still exists.

Should this be reopened @BruceMacD ?

**Comment by igorschlum** [comment]
With Ollama 0.1.10, Mac 32Go M1Pro I have this error: 

(base) igor@macIgor ~ % ollama run yi:6b-200k           
pulling manifest
pulling 0177ca5616b4... 100% ▕█████████████▏ (3.5/3.5 GB, 5.1 MB/s)            
pulling 8773f7716220... 100% ▕████████████████████▏ (17/17 kB, 12 kB/s)        
pulling b3736cdce03e... 100% ▕██████████████████████▏ (18/18 B,  9 B/s)        
pulling c93fb84f6006... 100% ▕███████████████████▏ (381/381 B, 227 B/s)        
verifying sha256 digest
writing manifest
removing any unused layers
success
⠧   Error: llama runner process has terminated

**Comment by BruceMacD** [comment]
Thanks to everyone for helping with adding info here. We've changed how Ollama run models since this issue, so the LLM runner process will no longer terminate during loading, so I'm going to resolve this issue for now.
