### ISSUE TITLE
max retries exceeded: unexpected EOF

### ISSUE THREAD

**Issue by priamai** [ollama/ollama#1158]
Hi there,
I am not sure if this is related to your file service, but I am getting this connection drops out very often.

![Screenshot from 2023-11-16 23-45-54](https://github.com/jmorganca/ollama/assets/57333254/d530f24e-af82-49d8-9435-0653922d1eec)

Maybe there is a way to throttle requests?

**Comment by orlyandico** [comment]
Just keep re-running the pull, it will resume from where it left off. I encounter it a lot because I only have a 200Mbps connection and had three PC's downloading models at one time... (it would be more efficient to download once and then SCP the blobs to the other PC's).

**Comment by igorschlum** [comment]
I have this problem also. More often when my internet connection was poor. In some case I had to relaunch the pull more than 20 times. It will become an issue if a model is updated and if Ollama runs as a stand alone server. Is it possible to extend the number of retries?

**Comment by priamai** [comment]
I have a fiber connection here with 300 Mbps, I believe the issue is where the file is downloaded from. What about putting those files on a more reliable service like AWS S3?

**Comment by igorschlum** [comment]
You raise a good point, @priamai. Having a better bandwidth requires a better hosting solution, which is not free, but as Ollama grows, this issue will become more and more important. Ollama teams could look for a sponsor who would pay for the hosting.

**Comment by orlyandico** [comment]
I also tested this on AWS and Hyperstack instances, and didn't get the EOF retries.  So it appears to be down to one's internet connection.

My more pressing question is why does Ollama have its own model repository, rather than supporting downloading models from, say, HuggingFace.

**Comment by jmorganca** [comment]
Hi folks thanks for creating an issue – looking into this – there really shouldn't be any EOF errors

**Comment by priamai** [comment]
We have some spare capacity on Aws S3 and also happy to sponsor. Send me a PM if you like. cheers.

**Comment by BruceMacD** [comment]
Thanks for the report here. The bug shown in this issue specifically is now fixed as we run models directly rather than in a subprocess. Although there are still on EOF errors. If anyone else sees an EOF please open a new issue so we can triage it appropriately.

**Comment by MADAO-LUV** [comment]
i also have this the same issue.And how i can solve this problem.i try reload for three times.

**Comment by micokonsep** [comment]
I got that too. So I am trying another way:

in powershell:
`Set-ExecutionPolicy -Scope Process -ExecutionPolicy Bypass`

make file download.ps1:
`
# Set the total time for the entire script (e.g., 5 hours)
$totalDuration = 5 * 60 * 60

# Set the download and pause intervals
$downloadInterval = 8 * 60  # 8 minutes
$pauseInterval = 3 * 60     # 3 minutes

# Initialize elapsed time
$elapsedTime = 0

# Loop for the download-pause cycle
while ($elapsedTime -lt $totalDuration) {
    Write-Host "Starting download process..."
    
    # Start the download process
    $process = Start-Process -FilePath "ollama.exe" -ArgumentList "pull qwen2.5-coder:32b" -NoNewWindow -PassThru

    # Let the download run for the specified interval
    Start-Sleep -Seconds $downloadInterval

    # Stop the download process (similar to Ctrl + Break)
    Write-Host "Stopping the download process..."
    Stop-Process -Id $process.Id -Force

    # Increment elapsed time for the download interval
    $elapsedTime += $downloadInterval

    # Check if total time is exceeded
    if ($elapsedTime -ge $totalDuration) {
        Write-Host "Download process completed or total duration reached."
        break
    }

    # Pause for the specified duration before restarting
    Write-Host "Pausing for $pauseInterval seconds..."
    Start-Sleep -Seconds $pauseInterval

    # Increment elapsed time for the pause
    $elapsedTime += $pauseInterval
}

Write-Host "Download automation finished."
`

those code is from chatgpt, and it works. it will download part, and stop and continue download again. i am downloading  qwen2.5-coder:32b because it's always stop downloading and start over. with that code can run well.

**Comment by MichelMichels** [comment]
Just reporting that I had this issue multiple times while trying to download deepseek-r1:7b

**Comment by DocterWilliam** [comment]
> Just reporting that I had this issue multiple times while trying to download deepseek-r1:7b

Agree, I also encountered the same problem when downloading deepseek-r1:7b: Error: max retries exceeded: EOF

**Comment by muhamedljatifi** [comment]
yes have the same issue with the same model. other models work fine

**Comment by ksDreamer** [comment]
same problem when `ollama run deepseek-r1` which is from https://ollama.com/library/deepseek-r1

**Comment by youkuzazazazaza** [comment]
> 是的，同一型号有同样的问题。其他型号运行良好



> yes have the same issue with the same model. other models work fine

i change to deepseek-r1:8b,it works well

**Comment by micokonsep** [comment]
try this. 

https://medium.com/@micowendy/ollama-error-max-retries-exceeded-eof-c8baf4a57ffc
it;s in Indonesian language, but you can copy paste the code.


regards,
