### ISSUE TITLE
Provide command to export downloaded models

### ISSUE THREAD

**Issue by biandayu** [ollama/ollama#1165]
Is there any way to import and export downloaded models? In this way, there is no need to use ollama pull to download again on another local machine.

Thanks

**Comment by horw** [comment]
Hi @biandayu, I used it on Ubuntu. 
Important files are saved in the `.ollama` folder, so you can simply copy it to your new device.
The full path is:
`/home/UserName/.ollama/models/`
There are two folders:
`manifests` and `blob`.
The `manifests` folder contains metadata for the models, and the `blob` folder contains the models themselves.

**Comment by horw** [comment]
BTW, maybe using a custom PATH or import/export models command would be helpful for users? If the maintainer agrees, I can try to implement it.

**Comment by biandayu** [comment]
Thanks @horw, I use it on WSL(ubuntu). 
The model files are in /usr/share/ollama/.ollama. I've tried copy them to a new PC. The ollama list command does display the newly copied models, but when using the ollama run command to run the model, ollama starts to download again.

**Comment by horw** [comment]
What about this directory, `/home/UserName/.ollama/models/`? Do you have any files here?

**Comment by biandayu** [comment]
There is no such files & dir under HOME.

![home](https://github.com/jmorganca/ollama/assets/52662468/4d69fc52-7e8b-43d1-a063-0672cefadff2)

**Comment by horw** [comment]
I just checked the code, and Ollama actually has an option to set up a custom path for the models directory using the OLLAMA_MODELS environment variable. On the other hand, if you don't set it up, it will look to the HOME environment variable.

```
// modelsDir returns the value of the OLLAMA_MODELS environment variable or the user's home directory if OLLAMA_MODELS is not set.
// The models directory is where Ollama stores its model files and manifests.
func modelsDir() (string, error) {
	if models, exists := os.LookupEnv("OLLAMA_MODELS"); exists {
		return models, nil
	}
	home, err := os.UserHomeDir()
	if err != nil {
		return "", err
	}
	return filepath.Join(home, ".ollama", "models"), nil
}
```

**Comment by horw** [comment]
You can check this one: https://github.com/jmorganca/ollama/blob/41434a7cdcf33918ae2d37eb23d819ef7361e843/docs/faq.md?plain=1#L94

**Comment by xunx911** [comment]
@conradax 我在使用pycharm远程主机上传时遇到了同样的问题，然后我以命令行使用sftp上传就解决了

**Comment by jmorganca** [comment]
Merging this with https://github.com/ollama/ollama/issues/335
