### ISSUE TITLE
The server stops working after long context window is passed with zephyr model deployed with docker container on A10 GPU

### ISSUE THREAD

**Issue by ajasingh** [ollama/ollama#1172]
I have deployed ollama on Nvidia A10 using Docker container , it works fine or smaller context window but server starts stop to work and gives below error 
2023/11/17 14:08:33 llama.go:385: signal: killed
2023/11/17 14:08:33 llama.go:459: llama runner stopped successfully

Is there any guide on why this might be happening

**Comment by BruceMacD** [comment]
It could be running out of memory while processing the context, are there any other logs above those ones? There should be some more specific details about why the runner is stopping in the ~20 lines above the `llama runner stopped successfully` log.

**Comment by BruceMacD** [comment]
Thanks again for bringing this issue to our attention. We've since changed how we run models so the timeout on model load will no longer occur. If anyone sees anything similar in the future please open a new issue so we can keep track of it.
