### ISSUE TITLE
The wizardcoder models request too much memory at load time

### ISSUE THREAD

**Issue by Nan-Do** [ollama/ollama#1174]
The context size given to llama.cpp to load this model is 4096, this requires around 10 GB of memory for the context alone, and if we add the 4.5 GB required for the 7B model it's unfeasible to use it in most consumer grade GPUs (and any system without more than 16 GB of ram). In contrast the context size given to codellama, the model from which wizardcoder derives, is  2048.

**Comment by jmorganca** [comment]
Hi there, we've made a ton of improvements to memory allocation and this should be fixed now.

Do note that some models require more memory for larger context windows due to their architecture
