### ISSUE TITLE
FR:  PEFT and QLoRA adapter loading, huggingface transformers load balancer

### ISSUE THREAD

**Issue by loopyd** [ollama/ollama#1193]
This discussion is on the validity of adding PEFT fine tuning abilities and QLoRA adapter loading to ollama.  Allowing expandable tensor level knowledgebases to be added via ollama model configuration or via API calls, and to trigger training via API to bake adapters using PEFT.   This feature request also includes the transformers load balancer from HuggingFace. 

These options are enabled in projects such as [oobabooga's text-generation-webui](https://github.com/oobabooga/text-generation-webui)

As LLaMA 2 was the original experiment for QLoRA automating adapter loading in ollama is a much desired feature for performant modular knowledgebase extensions. 

If you are not aware of Parameter Efficient Fine tuning or QLoRA adapters see [this resource](https://github.com/artidoro/qlora)

Addition of QLoRA is proposed based upon its:

- performance
- convenience to apply modular fine tuned knowledgebases. 
- Accessability to fine tune large language models on lower end hardware.
- works on GGUF and LLama based models. 
- has been extended to work on a wider range of models, such as GPTQ 
- Automation API is mature. 

Please add any feedback on including this feature below.

**Comment by runvnc** [comment]
Sounds amazing. How do we use this with out qLoRAs?

**Comment by BruceMacD** [comment]
Hi @loopyd thank for you feedback here. Ollama now support loading QLoRA adapters via the `ADAPTER` in a modelfile:
https://github.com/ollama/ollama/blob/main/docs/modelfile.md#adapter

For PEFT fine-tuning I'm going to start organizing fine-tuning requests around #156 to keep things organized.

Feel free to add more feedback if you have any.
