### ISSUE TITLE
Trying to run ollama on a server

### ISSUE THREAD

**Issue by bitcoinmeetups** [ollama/ollama#1197]
Hi,

I'm Mr. Mist, a very friendly guy.

I'm trying to run ollama on a server but get this error message. Any ideas and solutions?

llama_new_context_with_model: kv self size  =  256.00 MB
llama_new_context_with_model: compute buffer total size = 162.13 MB
2023/11/19 12:07:13 llama.go:438: error starting llama runner: timed out waiting for llama runner to start
2023/11/19 12:07:14 llama.go:430: signal: killed
2023/11/19 12:07:14 llama.go:504: llama runner stopped successfully
[GIN] 2023/11/19 - 12:07:14 | 500 |         4m32s |       127.0.0.1 | POST     "/api/generate"
[GIN] 2023/11/19 - 12:18:11 | 200 |     581.303µs |       127.0.0.1 | HEAD     "/"
[GIN] 2023/11/19 - 12:18:11 | 200 |     3.32279ms |       127.0.0.1 | GET      "/api/tags"

**Comment by kukidevs** [comment]
same here
getting "⠼   Error: timed out waiting for llama runner to start" while running "ollama run mistral" on Ubuntu

**Comment by Amal-David** [comment]
Hey, I'm getting the same error for llama2:70b, trying to run it on a G5.2xlarge (32GB RAM, 24GB A10 with 80GB storage and 20GB Available)

**Comment by technovangelist** [comment]
you will need at least 64gb ram to run the 70b model

**Comment by jexom** [comment]
Having the same issue with dolphin-mixtral and wizard-vicuna-uncensored:30b on a 64gb ram machine running ollama as a docker container on windows. It takes a long time to load and then times out

**Comment by BruceMacD** [comment]
Thanks to everyone for the information on this one. When this issue was created there were various issues related to memory allocation (over allocating context window, number of layers on the GPU) which have since been resolved. Closing this issue now, if you see any similar problems please open a new issue so they get attention.
