### ISSUE TITLE
deepseek-coder:6.7b cuda error

### ISSUE THREAD

**Issue by SAXN-SYNX** [ollama/ollama#1236]
-- ollama falls back to CPU for deepseek-coder:6.7b 
-- Any other model runs just fine with cuda with nvida 1660 ti .

-- Meanwhile i can run openchat:latest and zephyr:lastest with cuda just fine.

CUDA error 2 at /go/src/github.com/jmorganca/ollama/llm/llama.cpp/gguf/ggml-cuda.cu:7358: out of memory
current device: 0
2023/11/22 11:37:21 llama.go:430: 2 at /go/src/github.com/jmorganca/ollama/llm/llama.cpp/gguf/ggml-cuda.cu:7358: out of memory
current device: 0

**Comment by BruceMacD** [comment]
Hi @SAXN-SYNX, it's not obvious but deepseek coder has a large context window so it will take more memory than other 7B models, it will require about 8GB. I see the 1660TI has 6GB, so that should be the issue.

**Comment by madsamjp** [comment]
I have the same issue. My GPU has 8GB of VRAM. Is it not possible to run on both GPU and CPU like other larger 13b/30b models?

**Comment by BruceMacD** [comment]
@madsamjp it's pushing it on 8GB of VRAM so it may or may not run depending on the memory you have available at the time.

**Comment by Dav1nx1** [comment]
I have 12 GB of ram, and I have the same error with this model @SAXN-SYNX

**Comment by BruceMacD** [comment]
It still looks like not enough memory to me, for reference I'm running it locally and it uses 8.10GB. If you have more than that try looking at the available memory before running the model, it's very possible that not all memory is available.

**Comment by mchiang0610** [comment]
Hi @SAXN-SYNX this should be fixed in the recent versions of Ollama (current version is 0.1.28, and 0.1.29 is in pre-release). 

Closing this for now. Sorry about this. Please let me know if anyone is still encountering problems. Thank you so much
