### ISSUE TITLE
Feature request: Chat logs auto-save by default

### ISSUE THREAD

**Issue by bitcoinmeetups** [ollama/ollama#1238]
Hi,

I'm Mr. Cascade, a very friendly guy. 

I would like to make the following feature request:

Chats automatically being saved by default.

This is also the expected behaviour. Similar software like terminal gpt has it enabled by default.

I'm on a server where I can't scroll up on Tmux so while testing I lost interesting content several times just because I couldn't scroll up to retrieve it.

Mockup:

All chat logs goes automatically to /etc/ollama_chats or something like that

Otherwise - love your product. I test a lot of packages and this one is outstanding.

**Comment by pdevine** [comment]
It doesn't autosave, but w/ the next version (0.1.21) you will be about to use `/save <model_name>` to save your current session. You can then type `ollama run <model_name>` to get it to load back up again.

**Comment by mchiang0610** [comment]
@bitcoinmeetups thank you for submitting this. As Patrick referred above, you'll be able to use the `/save <model_name>` command to save your session. 

Closing this issue for now. 

Thank you!
