### ISSUE TITLE
An easy way to get model information?

### ISSUE THREAD

**Issue by jorge-menjivar** [ollama/ollama#1249]
Is there an easy way to get model information? I would like to know the context size window for any model, preferably from the endpoints API. 

If there is no way to get this from the endpoints API, I would like to contribute this feature, however, I am not sure where this information is found for each model. Advice on this would be appreciated. Thank you!

**Comment by SebastianMpl** [comment]
One that I found is that when you run a model in a terminal you have all the model information in the terminal window where you run serve command. Although I agree - this should be obtained in a pretty fashion.

**Comment by kris-hansen** [comment]
I have been using a fork with a `--list-remote` option which pulls the models from ollama.ai/library and parses them into the CLI. I'm finding it useful (although not essential) and added a [PR](https://github.com/ollama/ollama/pull/1732) in case the community wants to take it upstream.

**Comment by jmorganca** [comment]
Hi there, the `/api/show` endpoint has this info now: https://github.com/ollama/ollama/blob/main/docs/api.md#show-model-information

**Comment by khimaros** [comment]
i don't think this solves the "list remote" problem
