### ISSUE TITLE
Running Ollama for Orca2:13b on Limited VRAM: Model Configuration and Quantization Inquiry

### ISSUE THREAD

**Issue by derekhsu** [ollama/ollama#1263]
I successfully ran Ollama for Orca2:13b on my local machine, which has only 16GB of VRAM. However, I encountered difficulties running the Orca-2-13b model downloaded from Hugging Face due to insufficient VRAM. What model configuration does Ollama use to run Orca2:13b? Also, is it quantized?"

**Comment by BruceMacD** [comment]
HI @derekhsu the default Orca2:13b model is a 4-bit quantized model.

**Comment by mchiang0610** [comment]
Hi Derek, hope all is well! Can I assume your question is answered? Feel free to ask more! We're here to help. 

Thanks!
