### ISSUE TITLE
Why is my model not referring to the info given in system command in Modelfile

### ISSUE THREAD

**Issue by DeeptangshuSaha** [ollama/ollama#1264]
Okay let me explain what I meant by that.
I am trying to create a personal assistant and I want the model to remember some of my details.
I tried this by providing a system prompt but that did not exactly work as I set myself as its master for a lack of a better term.
But it shoots of saying its an AI and it only assists and that it does not have any master.
Now with the context out of the way What my real question is can I actually create a Model like this with my info or is it just impossible for now and I have to forget about it.
Here is an example for you to see where I am going with this--->
Prompt: Who is your master? (or Who am I?)
Answer: I serve <My Provided Name> (or You are <My Provided Name> )
 --> As I will be the only one using it.
Prompt: What is my Address?
Answer: Your address is <My Provided Address>

P.S Its more of an inquiry than a Issue per se. Please inform me if its possible or should I forget about it completely.

**Comment by BruceMacD** [comment]
Hi @DeeptangshuSaha it sounds like you're having issues getting an LLM to react in the way you're expecting? I'd suggest trying some different models to see if a different one works the way you expect.

**Comment by DeeptangshuSaha** [comment]
Well I am a little limited with my RAM so the orca-mini is my only option. But yes I did try to increase the creativity from 1 to 10 and it sounds a little better but the issue of it having a strong problem with a master still persists. Anyways thanks for the feedback.😃

**Comment by pdevine** [comment]
You can definitely do this w/ most models.  In 0.1.21 you can also do multi-shot prompts in the Modelfile with `MESSAGE` commands.

I'm going to go ahead an close this for now though.
