### ISSUE TITLE
Add a stop/restart command

### ISSUE THREAD

**Issue by davlgd** [ollama/ollama#1266]
When I setup/launch `ollama` the manual way, I can launch the server with `serve` command but don't have a easy way to stop/restart it (so I need to kill the process). It would be great to have dedicated command for theses actions.

**Comment by robbiemu** [comment]
would love to see currently running models, and their ports, in the menu bar icon (on Mac, that icon only offers "Quit" even once a model is opened).

**Comment by technovangelist** [comment]
Can you talk about why you want to restart the server?

and @robbiemu this seems to be an unrelated comment. But there is only one model at a time running. Whatever model is on the command line `ollama run <model>` is the one currently loaded.

**Comment by robbiemu** [comment]
@technovangelist sorry, I thought he meant individual models (I misread the OP)

**Comment by dudiao** [comment]
I just wanted to stop the api server, for now I can only use the kill command

**Comment by mtrin** [comment]
just like docker container stop exists, there should be some command to gracefully stop
for example I want it to pick up a new OLLAMA_MODELS env variable

**Comment by technovangelist** [comment]
On Mac, the way to stop Ollama is to click the menu bar icon and choose `Quit Ollama`. On Linux run `sudo systemctl stop ollama`

**Comment by adrian-valente** [comment]
I also think such an addition could be useful to allow non-root users to be able to free up GPU resources when the service is not needed, please tell me if there's a way to do this I am missing.

**Comment by chenxi1228** [comment]
> On Mac, the way to stop Ollama is to click the menu bar icon and choose `Quit Ollama`. On Linux run `sudo systemctl stop ollama`

I'm wondering if I'm not a sudoer, how could I stop Ollama, since it will always occupy around 500MB GPU memory on each GPU (4 in total).

**Comment by timiil** [comment]
To give us a http endpoint that stop / restart the ollama service is good, specailly sometimes the ollama just hang up for the VRAM not realse correctly.

**Comment by jmorganca** [comment]
Hi all – to unload a model you can use the new `keep_alive` api parameter set to `0` https://github.com/ollama/ollama/blob/main/docs/faq.md#how-do-i-keep-a-model-loaded-in-memory-or-make-it-unload-immediately

Regarding stopping the Ollama service – you can send it a regular signal message with `ctrl+c` or `kill`. Let me know if this doesn't solve the issue though!

**Comment by chenxi1228** [comment]
> Hi all – to unload a model you can use the new `keep_alive` api parameter set to `0` https://github.com/ollama/ollama/blob/main/docs/faq.md#how-do-i-keep-a-model-loaded-in-memory-or-make-it-unload-immediately
> 
> Regarding stopping the Ollama service – you can send it a regular signal message with `ctrl+c` or `kill`. Let me know if this doesn't solve the issue though!

This can release the memory used by the model. However, the problem of "it will always occupy around 500MB GPU memory on each GPU (4 in total)" still exists. It cannot be stopped totally.

**Comment by davlgd** [comment]
> Hi all – to unload a model you can use the new `keep_alive` api parameter set to `0` https://github.com/ollama/ollama/blob/main/docs/faq.md#how-do-i-keep-a-model-loaded-in-memory-or-make-it-unload-immediately
> 
> Regarding stopping the Ollama service – you can send it a regular signal message with `ctrl+c` or `kill`. Let me know if this doesn't solve the issue though!

My initial point on this was that, if I launch/use ollama as a server, I don't have any way to act on it as I have with the GUI. I can `ollama serve` but I don't have a way to do the opposite. I effectively detect it in processes and kill it in such situation but it could be great have a way to just ask it to `ollama stop` or even `ollama restart` (as we do with the GUI after an update for example).

**Comment by maxgreco** [comment]
Hi, maybe for Windows this workaround ca be useful -> register this program for restart
https://www.thewindowsclub.com/what-does-register-this-program-for-restart-do
I will try it myself for may forked version of https://github.com/technovangelist/airenamer (BTW thanks a lot!)
I will follow this conversation, bye

**Comment by sheecet** [comment]
this issue is not resolved
