### ISSUE TITLE
strange new lines in chat response when using Chinese

### ISSUE THREAD

**Issue by kiang** [ollama/ollama#1275]
I'm using ollama in Ubuntu 22.04. The command line chat interface has some problems if the response is using Chinese characters.

Just recorded a video to tell the issue:
https://youtu.be/Z3-zy90lO3w

Unexpected new line characters were inserted into the response and break the answering message. This problem was found in almost all recent versions.

**Comment by Giftia** [comment]
I am also have the same problem too on `MacOS 14.1.1` with recent version of ollama.

**Comment by 1linguowei** [comment]
Me, too. The bug has been a long time!!!

**Comment by pdevine** [comment]
Sorry about this one, guys. I believe there are two problems here:
1. we're not detecting the edge of the screen correctly with multi-byte chars; and
2. when we "brack track" to erase the screens at the line wrap, we're not counting the number of characters correctly

**Comment by pdevine** [comment]
Also, for now, a workaround is to include the `--nolinewrap` flag when you're calling `ollama run`.

**Comment by dhiltgen** [comment]
Fixed in 0.1.39 

https://github.com/ollama/ollama/releases
