### ISSUE TITLE
A way to reuse ollama API with RAG app.

### ISSUE THREAD

**Issue by sandangel** [ollama/ollama#1276]
Hi, I would like to build an RAG app, but instead of having its own API, I like to reuse the Ollama existing API so that it will work with many existing clients. Is there a way to do that?

**Comment by sandangel** [comment]
@BruceMacD Can we publish the API as an interface package and user can hook their own handler into that?

**Comment by da-z** [comment]
Do you guys have any plans or open to the idea of bundling a vector store into Ollama (something like [Weviate](https://weaviate.io/developers/weaviate/client-libraries/go)), and offering an API for the store?

**Comment by jmorganca** [comment]
Hi there, thanks for the issue! Revisiting this – Ollama has an [API to generate embeddings](https://github.com/ollama/ollama/blob/main/docs/api.md#generate-embeddings) and works great with Weaviate and other vector stores. There isn't currently a vector store built into Ollama
