### ISSUE TITLE
Support `GPT2LMHeadModel` architecture

### ISSUE THREAD

**Issue by jhagelback** [ollama/ollama#1285]
Any plans on supporting _GPT2LMHeadModel_ architecture?

**Comment by jmorganca** [comment]
This should be supported now – you can [import it](https://github.com/ollama/ollama/blob/main/docs/import.md) (via an existing GGUF file). Let me know if you hit any issues 😊

**Comment by echostorm** [comment]
I tried importing a GPT2LMHeadModel architecture based model and I faced same issue [unknown architecture]
