### ISSUE TITLE
Change enviroment-variables as settings to command parameters

### ISSUE THREAD

**Issue by Talleyrand-34** [ollama/ollama#1286]
## Changethe method of configure settings
Instead of enviroment variables uses internal settings, at least as user interface.

### Example

Instead of:
> OLLAMA_MODELS=/path/to/file; ollama run model

Run:
>ollama conf path_to_models /path/to/file
>ollama run model 

Or:
>ollama run model -f /path/to/file

**Comment by jmorganca** [comment]
Thanks for the issue! For transparency for the time being Ollama will configure itself using environment variables. See https://github.com/ollama/ollama/blob/main/docs/faq.md#how-do-i-configure-ollama-server for some new docs on how to do that on each platform.
