### ISSUE TITLE
deepseek-coder:6.7b-base-q5_K_M not working on a Mac

### ISSUE THREAD

**Issue by olafgeibig** [ollama/ollama#1304]
Tried it 2 times. deleted model after 1st try, and then ollama pull again. 

```
ollama run deepseek-coder:6.7b-base-q5_K_M
Error: llama runner process has terminated
```
It actually works if I do a ```ollama create``` with a manually downloaded model.

Ollama 0.1.12
MacOS 13.6 (22G120)
Apple M1 Pro, 16GB

**Comment by igorschlum** [comment]
Hi @olafgeibig 

I'm using Ollama 0.1.12
MacOS 13.5.2
Apple M1 Pro, 32GB

And It worked for me. It could be a memory issue. Reboot your mac and try again to see if you still have the error message.

(base) igor@macIgor ~ % ollama run deepseek-coder:6.7b-base-q5_K_M
pulling manifest 
pulling 6e92e8607680... 100% ▕████▏(4.8 GB/4.8 GB)                             
pulling ccfee4895df0... 100% ▕████▏(13.8 KB/13.8 KB)                           
pulling 58e1b82a691f... 100% ▕████▏(18 B/18 B)                                 
pulling c77ca3ce73a4... 100% ▕████▏(383 B/383 B)                               
verifying sha256 digest 
writing manifest 
removing any unused layers 
success 
>>>

**Comment by dhiltgen** [comment]
We've made numerous improvements in memory prediction, and understanding available memory splits between GPU/system on MacOS.  I don't have a 16G macos system to verify this on, but I believe this should be fixed.  If you're still having problems running models on your 16G system, please share your server log and I'll reopen the issue.
