### ISSUE TITLE
trouble with deepseek-coder

### ISSUE THREAD

**Issue by niknoproblems** [ollama/ollama#1312]
I'm having trouble getting this model to run on mac m1 16gb ram:
ollama run deepseek-coder:6.7b-base-q8_0

but this model work without any troubles:
ollama run neural-chat:7b-v3.1-q8_0

it has more weights and bigger file size.

**Comment by deanrie** [comment]
I just tried the deepseek-llm:7b-chat-q8_0 model, there are no problems with it, everything works fine.

**Comment by niknoproblems** [comment]
Yeah, I had no problems with deepseek-llm:7b-chat-q8_0 model either. but deepseek-coder-6.7b-instruct.Q8_0 model is better for code

**Comment by pdevine** [comment]
Sorry about the slow response. You probably want the `instruct` model and not the `base` model.

```
% ./ollama run deepseek-coder:6.7b-instruct-q8_0
pulling manifest
pulling b6dfda3810bc... 100% ▕█████████████████████████████████████████████████████████████████▏ 7.2 GB
pulling a3a0e9449cb6... 100% ▕█████████████████████████████████████████████████████████████████▏  13 KB
pulling 8893e08fa9f9... 100% ▕█████████████████████████████████████████████████████████████████▏   59 B
pulling 8972a96b8ff1... 100% ▕█████████████████████████████████████████████████████████████████▏  297 B
pulling 733c8610b9f5... 100% ▕█████████████████████████████████████████████████████████████████▏  483 B
verifying sha256 digest
writing manifest
removing any unused layers
success
>>> write me hello world in golang
Sure, here is a simple "Hello World" program written in Go language:

```go
package main

import "fmt"

func main() {
    fmt.Println("Hello, World!")
}
```

You can run this code by copying it into a file with a `.go` extension and running the file through the Go compiler (`go
run filename.go`). Make sure you have installed Go on your system to compile and run the program.
```

I'm going to go ahead and close out the issue, but feel free to reopen it if you're still having issues. The `base` model is sentence completion model, so more appropriate for hooking up a code editor.
