### ISSUE TITLE
Installation downloaded cuda likely unnecessarily 

### ISSUE THREAD

**Issue by folovco** [ollama/ollama#1330]
For quick testing on a CPU-only server it would seem possibly advantageous to avoid downloading the cuda drivers if the  https://ollama.ai/install.sh script can determine there is no Nvidia device to use.

>>> Installing ollama to /usr/local/bin...           >>> Creating ollama user...                          >>> Adding current user to ollama group...
>>> Creating ollama systemd service...               >>> Enabling and starting ollama service...
Created symlink /etc/systemd/system/default.target.wants/ollama.service → /etc/systemd/system/ollama.service.
>>> The Ollama API is now available at 0.0.0.0:11434.
>>> Install complete. Run "ollama" from the command line.
WARNING: No NVIDIA GPU detected. Ollama will run in CPU-only mode.

**Comment by dhiltgen** [comment]
The install script requires sudo to be able to register a service with systemd.

There are 2 parts to the Nvidia stack.  A driver, and user-space libraries.  We bundle the libraries directly into our executable, and we require the driver to be installed IF we detect an nvidia GPU.  If no GPU is detected, we do not install the driver.

If you want to "roll your own" setup and not use the install script, you can download the stand-alone executable which we publish on our github release page.  For example:

```
wget https://ollama.com/download/ollama-linux-amd64
chmod a+x ./ollama-linux-amd64
./ollama-linux-amd64 serve
```
