### ISSUE TITLE
API interface works fine, CLI returns non-descriptive error presumably due to proxy with Docker install

### ISSUE THREAD

**Issue by mlewis1973** [ollama/ollama#1337]
Docker image installed on multiple Linux and Mac systems, both with and wo GPUs.
Local proxy settings set in daemon.json and well as passed to docker with -e and --env

API interface works fine, but CLI generates error for 
'ollama run llama2'
'ollama list'
'ollama pull mistral'

ollama --version and --help do not generate error.
I even tried building the image with proxy hardcoded with ENVs in the Dockerfile... same error

Outside firewall, CLI works fine.

**Comment by BruceMacD** [comment]
Hey @mlewis1973, if you're behind a firewall you probably need to configure the HTTPS_PROXY environment variable.
https://github.com/jmorganca/ollama/blob/main/docs/faq.md#how-do-i-use-ollama-behind-a-proxy

Have you tried that?

**Comment by mxyng** [comment]
It seems likely the CLI also requires the proxy settings, not just the server. This would explain why the API, presumably with curl, works while the CLI does not. This should be fixed and uses HTTPS_PROXY to determine if and when proxy settings needs to be configured for the CLI

**Comment by mlewis1973** [comment]
> https://github.com/jmorganca/ollama/blob/main/docs/faq.md#how-do-i-use-ollama-behind-a-proxy

from original issue:
"Local proxy settings set in daemon.json and well as passed to docker with -e and --env"

HTTPS_PROXY is clearly not the solution........

**Comment by mxyng** [comment]
Please see #2168 which describes a possible failure scenarios when using `HTTP_PROXY`. If that doesn't represent your problem, please describe your issue in detail and we can determine if there's a bug somewhere

**Comment by mchiang0610** [comment]
@mlewis1973 sorry about this. Are you still having this problem on the latest Ollama releases?

**Comment by lakako** [comment]
I can reproduce this problem on ollama 0.1.29

**Comment by mxyng** [comment]
It's not recommended to set `HTTP_PROXY` in the container. If the container is reused for ollama cli, `HTTP_PROXY` will proxy client requests through the configured proxy
