### ISSUE TITLE
response with forever loop <s> 

### ISSUE THREAD

**Issue by yangboz** [ollama/ollama#1338]
when testing llama2 or other models pulled from https://ollama.ai/library
after successfully running the model mix languages , we can see the "<s>" sometime  displayed on console forever  results to blank loop forever.

any idea ?

**Comment by mchiang0610** [comment]
Hi, 

Would it be possible for you to pull the llama2 you have again? (using ollama pull) I just want to make sure you have the latest. 

which version of ollama are you running? Can check via ( `ollama -v` )

**Comment by yangboz** [comment]
yangboz@macdeMBP ebook % ollama -v
ollama version 0.1.3

**Comment by yugame** [comment]
I encountered the same situation, it seems to have generated a large number of spaces, making the process very long.
[GIN] 2023/12/02 - 18:52:12 | 200 | 2m41s | 192.168.3.18 | POST "/api/generate"
This often happens in the use of the Zephyr model and occasionally in Mistral.

**Comment by stevenquinn** [comment]
I'm having the same issue here, only seen when using the `--format json` flag. Running on an M1 MacBook Pro. 

`ollama version is 0.1.17`

**Comment by mchiang0610** [comment]
Hi @yangboz @yangboz @stevenquinn sorry about this. This should be fixed with recent releases of Ollama. If you have an older model, please try to update it by performing an `ollama pull <model_name>` 

Sorry about the issue. Thank you!
