### ISSUE TITLE
MacOS opens kernel tasks doesn't unload model

### ISSUE THREAD

**Issue by igorcosta** [ollama/ollama#1339]
One of the things that makes me cringe is when swapping between models, it never releases the memory when I'm done using it. It's just piles up and I eventually have to restart my Mac.

Would memory optimisation being a target for next release?

**Comment by pdevine** [comment]
@igorcosta the memory for each model is released after 5 minutes, and it should release between loading each model. Can you be more specific about what you're seeing?

**Comment by tjthejuggler** [comment]
is there any way to not have to wait 5 minutes? I'm on ubuntu and I have to go in and manually sudo kill ollama in order to get my memory back every time

**Comment by jakenvac** [comment]
I'm on macos and came to this issue wondering why there was still memory allocated after I ended the `ollama run` command. I wasn't aware of the 5 minute rule.

I can confirm this works as @pdevine describes and is perfectly acceptable behavior in my mind.

**Comment by Natfan** [comment]
I actually have the opposite issue, I would like my ollama models to be cached for longer. Is there any way that I can programmatically get the model currently loaded (outside of scanning the log), so I can poll /api/embeddings every few minutes to keep it up and running?

**Comment by mxyng** [comment]
> so I can poll /api/embeddings every few minutes to keep it up and running?

Yes, any of `/api/embeddings`, `/api/chat`, or `/api/generate` will work for this

**Comment by tjthejuggler** [comment]
@mxyng is there anything that will cancel the ollama model immediately? So i don't have to do a sudo kill and can use the guy again immediately.

**Comment by mxyng** [comment]
With #2146, you can set `keep_alive: 0` to immediately unload the model once the request is complete

**Comment by tjthejuggler** [comment]
> With #2146, you can set `keep_alive: 0` to immediately unload the model once the request is complete

Thanks so much! How exactly can this be used? I tried it in python code and as an argument in a terminal command and both ways it just doesn't run at all, no error, just no LLMing happening.

**Comment by OliChase404** [comment]
This might help, from the [faq.md](https://faq.md/) file:

-----------------------------------------------------------
## How do I keep a model loaded in memory or make it unload immediately?
By default models are kept in memory for 5 minutes before being unloaded. This allows for quicker response times if you are making numerous requests to the LLM. You may, however, want to free up the memory before the 5 minutes have elapsed or keep the model loaded indefinitely. Use the `keep_alive` parameter with either the `/api/generate` and `/api/chat` API endpoints to control how long the model is left in memory.
The `keep_alive` parameter can be set to:
* a duration string (such as "10m" or "24h")
* a number in seconds (such as 3600)
* any negative number which will keep the model loaded in memory (e.g. -1 or "-1m")
* '0' which will unload the model immediately after generating a response
For example, to preload a model and leave it in memory use:
```shell
curl http://localhost:11434/api/generate -d '{"model": "llama2", "keep_alive": -1}'
```
To unload the model and free up memory use:
```shell
curl http://localhost:11434/api/generate -d '{"model": "llama2", "keep_alive": 0}'

--------------------------------
So to immediately unload a model and free your vram run:

curl http://localhost:11434/api/generate -d '{"model": "MODELNAME", "keep_alive": 0}'

Replace MODELNAME with the name of the model currently loaded.

**Comment by AbdulmalekAI** [comment]
> This might help, from the [faq.md](https://faq.md/) file:
> 
> ## How do I keep a model loaded in memory or make it unload immediately?
> By default models are kept in memory for 5 minutes before being unloaded. This allows for quicker response times if you are making numerous requests to the LLM. You may, however, want to free up the memory before the 5 minutes have elapsed or keep the model loaded indefinitely. Use the `keep_alive` parameter with either the `/api/generate` and `/api/chat` API endpoints to control how long the model is left in memory. The `keep_alive` parameter can be set to:
> 
> * a duration string (such as "10m" or "24h")
> * a number in seconds (such as 3600)
> * any negative number which will keep the model loaded in memory (e.g. -1 or "-1m")
> * '0' which will unload the model immediately after generating a response
>   For example, to preload a model and leave it in memory use:
> 
> ```shell
> curl http://localhost:11434/api/generate -d '{"model": "llama2", "keep_alive": -1}'
> ```
> 
> To unload the model and free up memory use:
> 
> ```shell
> curl http://localhost:11434/api/generate -d '{"model": "llama2", "keep_alive": 0}'
> 
> ----------------------------------------------
> 
> So to immediately unload a model and free your vram run:
> 
> curl http://localhost:11434/api/generate -d '{"model": "MODELNAME", "keep_alive": 0}'
> 
> Replace MODELNAME with the name of the model currently loaded.
> ```

I used keep_alive in this command , But not working     ollm = OllamaLLM(model="aya",keep_alive=0,temperature=0.1)
Is this parameter woriking for /api/generate and /api/chat API endpoints only ???
