### ISSUE TITLE
Integration with `jupyter-ai`

### ISSUE THREAD

**Issue by aaronspring** [ollama/ollama#1343]
[`jupyter-ai`](https://jupyter-ai.readthedocs.io/en/latest/index.html) includes many LLMs into the jupyter interface.

```python
%%ai anthropic:claude-v1.2
Write a poem about C++.
```

Imagine:
```python
%%ai ollama:llama2
Write a poem about C++.
```

As [GPT4All is included](https://jupyter-ai.readthedocs.io/en/latest/users/index.html#model-providers), I guess local ollama models could also be possible.

**Comment by technovangelist** [comment]
take a look at this for an example notebook that works with ollama: https://github.com/jmorganca/ollama/tree/main/examples/jupyter-notebook

**Comment by jmorganca** [comment]
Hi there! Thanks for the issue. See https://github.com/jupyterlab/jupyter-ai/issues/389 which should have more info
