### ISSUE TITLE
[WISH] API for token count? faster than embeddings vector length?

### ISSUE THREAD

**Issue by kettoleon** [ollama/ollama#1345]
Hi, I've been using ollama for a few days, I really like it. 

However, I'm using it by making raw requests, I mean I'm handling the context myself.

When under this use case, the system needs to count tokens for many strings to decide what goes into the context and what is too much. 

For now, I've been using the embedding API, and taking the length of embeddings vector as token count.

But I understand an "only count tokens without computing embeddings" API would be way faster.

I'm assuming something like that to be possible? I was using exllama before ollama, and it had something like that. But I never went into the details to see how it was done.

It would be awesome if someone could make a PR for that, or point me in the right direction to do the PR myself 😜 (although my python knowledge is scarce) .

**Comment by oliverbob** [comment]
Yes, this is very practical to see implemented for this repo. Excited to see it in action.

**Comment by jukofyork** [comment]
I was hust thinking about this too - didn't think of using the count from the embedding call though - thanks! 

Would still be better to have the token count returned. Possibly even have the ability to return the tokenized text and get that returned too. Somebody linked this on reddit the other day and it's quite interesting:

https://www.danieldemmel.me/tokenizer.html

**Comment by suvalaki** [comment]
This would be pretty valuable. Useful for other libraries which call token counting methods as a part of their everyday flow.

**Comment by oliverbob** [comment]
There is yet no native support, but ollama-webui seems to have it.

**Comment by oliverbob** [comment]
![image](https://github.com/ollama/ollama/assets/23272429/c69267cf-7475-4f56-ac8e-3c7b3430ec94)

If I understand you correctly.

**Comment by suvalaki** [comment]
id just read the modifications i made in my branch and you'll see the delta difference. Its the difference between apriori knowledge and aposteriori ...

**Comment by oliverbob** [comment]
Sounds Greek to me. Wish you all the luck.

**Comment by chigkim** [comment]
It seems like a lot of people want this.

https://github.com/ollama/ollama/issues/1716 and https://github.com/ollama/ollama/issues/3582

Llama.cpp server has POST /tokenize and POST /detokenize now, so hopefully Ollama can just expose the api.

**Comment by jmorganca** [comment]
Thanks for the issue!

`/api/show` will now show embedding length

Regarding `/tokenize` and `/detokenize`, closing for this issue: https://github.com/ollama/ollama/issues/3582
