### ISSUE TITLE
`deepseek-coder` fails to run with error

### ISSUE THREAD

**Issue by Huge** [ollama/ollama#1348]
`  ollama run deepseek-coder:6.7b-base-q3_K_S`
`Error: llama runner process has terminated`
is worse than expected, I've supposed correct ggml/guff engine/library is bundled to the model in this packaging.

**Comment by jmorganca** [comment]
Hi there, sorry this happened - may I ask what operating system you are on?

**Comment by RussellCanfield** [comment]
I get a similar error:

'{"error":"model 'deepseek-coder' not found, try pulling it first"}'

mode: deepseek-coder:6.7b-base-q4_0
platform: macOS m1

**Comment by iDevEngineer** [comment]
Has this been resolved as I'm having the same error too, using VSCode Insider?
platform: macOS m1

**Comment by hasib-devs** [comment]
It is still happening on vscode insiders with cody extension.
platform: macOS Intel

**Comment by jmorganca** [comment]
Is this still an issue? Please let me know and I can re-open the issue. Thanks so much!

**Comment by peterturquoise** [comment]
Still happening for me, same issues with codellama and deepseek-code, but fine with mistral :shrug: ??

Error:
litellm.exceptions.APIConnectionError: {"error":"model 'deepseek-coder' not found, try pulling it first"}

Config of models:
config_list_mistral_local = [  
    {
        "model":"ollama/mistral",
        "base_url": "http://0.0.0.0:4000",
        "api_key": "NULL"
    }
]


config_list_codellama_local = [  
    {
        "model":"ollama/codellama",
        "base_url": "http://0.0.0.0:46967",
        "api_key": "NULL"
    }
]

config_list_deepseek_coder_local = [  
    {
        "model":"ollama/deepseek-coder",
        "base_url": "http://0.0.0.0:2409",
        "api_key": "NULL"
    }
]

llm_config_mistral = {
        "config_list": config_list_mistral_local
}

llm_config_codellama = {
        "config_list": config_list_codellama_local
}

llm_config_deepseek_coder = {
        "config_list": config_list_deepseek_coder_local
}
