### ISSUE TITLE
ollama at startup causing kernel_task to run all times on macos

### ISSUE THREAD

**Issue by ogulcancelik** [ollama/ollama#1362]
I don't have a proper log, or data to share but I wanted to post this anyway.

I am using M2 Max and installed ollama, it automatically starts as a login item. I realized my idle temps were 80C and also `kernel_task` was eating a lot of CPU time. It was fixed as soon as I removed ollama from login items. Closing it didn't fix it, so my guess is, as soon as it starts as a login item, it creates a ghost process that macos continuously tries to close, hence, creating high process uptime on kernal_task and high temps.

I'm sorry that I can't provide more detail as I removed ollama completely, but wanted to open this issue for future reference, if someone has the same problem.

**Comment by OgulcanCelik** [comment]
I realized this is not ollama but chatgpt on chrome ffs:
https://community.openai.com/t/high-cpu-web-workers-usage-of-chatgpt-when-not-is-use/230447
