### ISSUE TITLE
Different behavior between running on the host versus running on GPUs.

### ISSUE THREAD

**Issue by phalexo** [ollama/ollama#1368]
When running on the GPUs (one or more) the output is either one character or one, seemingly, unrelated word and then lines of '#"
It does it for a while. Sometimes it gets an exception in cuBLAS error 15 at /go/src/github.com/jmorganca/ollama/llm/llama.cpp/gguf/ggml-cuda.cu:7586

But the same model(s) run on my host and produce output.

**Comment by BruceMacD** [comment]
This is probably related to a multi-gpu bug that has been on-going. Linking for future reference: #969

**Comment by dhiltgen** [comment]
Quite a few GPU related fixes have gone in over the past few weeks.  Please give this another try with the latest release 0.1.22 and let us know if you're still hitting the problem.

**Comment by dhiltgen** [comment]
If you're still having problems with 0.1.22 or newer, please re-open.
