### ISSUE TITLE
Add support for NeuralHermes-2.5-Mistral-7B 

### ISSUE THREAD

**Issue by Aspie96** [ollama/ollama#1370]
Yes, it's yet another Mistral-based chatbot.

Would you consider adding support for [NeuralHermes-2.5-Mistral-7B](https://huggingface.co/mlabonne/NeuralHermes-2.5-Mistral-7B)?

Thank you very much!

**Comment by jmorganca** [comment]
Hi there, someone has uploaded this model here: https://ollama.com/themhv/neuralhermes. We'll keep adding new models as well: keep the requests coming!
