### ISSUE TITLE
Unable to Pull on IPv6 system

### ISSUE THREAD

**Issue by jabhishek87** [ollama/ollama#1371]
user@host:~$ ollama run mistral --verbose --insecure
pulling manifest
Error: Head "https://dd20bb891979d25aebc8bec07b2b3bbc.r2.cloudflarestorage.com/ollama/docker/registry/v2/blobs/sha256/6a/6ae28029995007a3ee8d0b8556d50f3b59b831074cf19c84de87acf51fb54054/data?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=66040c77ac1b787c3af820529859349a%!F(MISSING)20231204%!F(MISSING)auto%!F(MISSING)s3%!F(MISSING)aws4_request&X-Amz-Date=20231204T081132Z&X-Amz-Expires=1200&X-Amz-SignedHeaders=host&X-Amz-Signature=136ccd0e4accf7bcc435ab7c9bad57e7e6644bf2fc299d38fc1a9f6ce180d81b": read tcp [2620:10a:a001:a040:a00:27ff:fec9:9663]:47042->[2606:4700::6812:85a]:443: read: connection reset by peer

**Comment by miyurusankalpa** [comment]
This might be a issue with your connection(Wind River Systems?) to Cloudflare R2. Connection resets usually happens due to firewall blocking.

I just tried ollama on AWS with IPv6 and there was no issues. (confirmed the traffic was going via IPv6 via tcpdump)

**Comment by dhiltgen** [comment]
@jabhishek87 if you're still having troubles let us know and I'll reopen the issue.
