### ISSUE TITLE
Update VRAM layer offloading to account for context size

### ISSUE THREAD

**Issue by BruceMacD** [ollama/ollama#1385]
Our current calculation for the amount of layers to offload to VRAM does not account for context size, so large context models may fail to load if too many layers are off-loaded.

**Comment by m0wer** [comment]
Yup, happens often.

**Comment by m0wer** [comment]
Is there any workaround until the fix?

**Comment by BruceMacD** [comment]
I believe setting the `num_gpu` parameter to not exceed the number of layers could help, since that prevents the context from being loaded into VRAM.

Here's what doing that would look like:
1. [Search the logs](https://github.com/jmorganca/ollama/blob/main/docs/faq.md#how-can-i-view-the-logs) for "layers to GPU" to see how many layers the model has.

Here is what that looks like on my linux instance:
```
$ journalctl -u ollama -r -g "layers to GPU"
Dec 15 11:22:00: llama_model_load_internal: offloaded 35/35 layers to GPU
```

2. Start a new interactive session and explicitly set the `num_gpu`to the number of layers (35 in the case of my example.
```
$ ollama run llama2
>>> /set parameter num_gpu 32
Set parameter 'num_gpu' to '32'
```

This should prevent context off-loading to VRAM.

**Comment by m0wer** [comment]
That worked! Thanks a lot @BruceMacD 

If it helps anyone, what I did was:

```gguf
# /tmp/mixtral_less_gpu.gguf
FROM mixtral:latest
TEMPLATE """ [INST] {{ .System }} {{ .Prompt }} [/INST]"""
PARAMETER num_ctx 32768
PARAMETER stop "</s>"
PARAMETER stop "[INST]"
PARAMETER stop "[/INST]"
PARAMETER num_gpu 4
```

```bash
ollama create mixtral_less_gpu -f /tmp/mixtral_less_gpu.gguf
```

For `mixtral:latest` each layer requires around 800 MB RAM, and the context aorund 2.5 GB. So with 6 GB I have 3 layers and `total VRAM used: 4895.82 MiB (model: 2347.78 MiB, context: 2548.04 MiB)`. By default it was trying to fit 5 layers (out of the total of 33) to VRAM.

**Comment by mongolu** [comment]
can we `/set parameter num_gpu 32` on runtime?
it would save a lot of tries of "`ollama create [name] -f [modelfile]`"

**Comment by iplayfast** [comment]
I wonder if that has anything to do with this bug https://github.com/jmorganca/ollama/issues/1691

**Comment by m0wer** [comment]
> can we `/set parameter num_gpu 32` on runtime? it would save a lot of tries of "`ollama create [name] -f [modelfile]`".
> 
> I'm using `litellm `and `autogen`, so I'm not sure what would mean "at runtime". What I would like to do though, is when starting the "`litellm ... --model ollama/[name]`" to be able to pass also `num_gpu`... But right now, when I'm writing this, it seems more of a feature for `litellm` project, isn't it?

Currently not, but it would be breat.

**Comment by m0wer** [comment]
> I wonder if that has anything to do with this bug #1691

I don't think so. This bug occurs even on a fresh installation.

**Comment by dhiltgen** [comment]
We do take context size into consideration now, so I'm going to close this issue as fixed.  If folks are still hitting OOMs please make sure to upgrade to the latest release 0.1.33 and share your logs so we can take another look.
