### ISSUE TITLE
Request: The ability to load multiple models into the same GPUs and running them concurrently.

### ISSUE THREAD

**Issue by phalexo** [ollama/ollama#1389]
Currently what ollama does is UNLOAD the previously loaded model, and loads the last model you try to use. Although the load is reasonably fast (if you intend to manually enter text and such) but if you want to use it with AutoGen or similar, loads and unloads put additional latency into the system, when token generation can already be pretty slow.

I am going try to separate GPUs into different groups and try to run different models within different groups, BUT it does not really solve the problem of resource utilization.

Thanks.

**Comment by phalexo** [comment]
How do I change the default port from 11434 to something else? I can't even test trying to run different models on different GPUs.

**Comment by phalexo** [comment]
I was able to load different models into different sets of GPUs, but changing the ports manually, using OLLAMA_HOST,
was a pain. It should fail over to the next numbered port from the default 11434 to 11345, 11346,...

**Comment by shroominic** [comment]
Would be sick to have it because it would enable 2 different models having a conversation without the delay of offloading the one and loading the other

**Comment by phalexo** [comment]
You can do it now. I have been doing it. Just use multiple Ollama servers.

**Comment by dhiltgen** [comment]
Consolidating as a dup of #2109
