### ISSUE TITLE
Continuous batching support

### ISSUE THREAD

**Issue by Huvinesh-Rajendran-12** [ollama/ollama#1396]
Does Ollama support continuous batching for concurrent requests? I couldn't find anything in the documentation.

**Comment by trenta3** [comment]
llama.cpp (which is the engine at the base of Ollama) does indeed support it, I'd also like for a configuration parameter in Ollama to be set to enable continuous batching.

Ref: https://github.com/ggerganov/llama.cpp/discussions/3471

**Comment by sodre** [comment]
@trenta3, how do we turn it in in the llama.cpp case?

**Comment by Huvinesh-Rajendran-12** [comment]
pass in the -cb flag when running the server

**Comment by trenta3** [comment]
Yes indeed, does someone know if there is a way in ollama to pass options directly to the underlying llama.cpp?

**Comment by sodre** [comment]
The issue is less about passing the parameters down and more about ensuring that the different connection at the Ollama side use different slots of llama.cpp.

**Comment by jkuehn** [comment]
Hey, just to start the conversation: how about adding a new endpoint to Ollama that can handle batching? After we see it's working well, we could make it part of the main generate endpoint.

Like, EricLLM uses a queue and an inference loop for batching. I think it's a good and easy way to do it. People could start using it and if something comes up, we still could switch to a more sophisticated solution. I believe this would be a major feature for Ollama!
EricLLM: https://github.com/epolewski/EricLLM/blob/main/ericLLM.py

What do you think about the approach?

**Comment by Huvinesh-Rajendran-12** [comment]
> pass in the -cb flag when running the server 
> 
> 

@9876691 follow this.

**Comment by dantheman0207** [comment]
I would also be interested in this functionality.

**Comment by MarcellM01** [comment]
This would be a great feature to have and would increase the utility of Ollama by an order of magnitude.

**Comment by pawelgnatowski** [comment]
Any news on this one?
Has anyone tried the saturation of the ollama server?

**Comment by fzyzcjy** [comment]
Hi, is there any updates? Thanks!

**Comment by jmorganca** [comment]
Hi there, this is enabled by default now with concurrency: https://github.com/ollama/ollama/releases/tag/v0.2.0

**Comment by tudormunteanu** [comment]
Interested in this too. An equivalent to `/v1/batches` for OpenAI compatibility would be amazing.

What is the current blocker?
