### ISSUE TITLE
Attempting to load a model smaller than 10GiB into 12.2GiB GPU results in failing over to load into the host RAM.

### ISSUE THREAD

**Issue by phalexo** [ollama/ollama#1416]
I have converted losslessmegacoder-llama2-13b-min.Q6_K.model to ollama format.

On my attempt to load, it reports the size of the model < 10GiB, but as I do "ollama run losslessmegacoder-llama2-13b-min.Q6_K" it attempts to load it into a GPU, apparently runs out of VRAM and loads into the host instead.

If the model is smaller than 10GiB, why is it using additional 2.2GiB and is there anything I can do to mitigate this?

**Comment by BruceMacD** [comment]
Hi @phalexo aside from using a smaller model there are a couple things you could try. 

1. Make sure you have as much VRAM free as possible. Ollama will only be able to use the VRAM not being used by other programs.
2. Check the context size of the model you are trying to run, it may result in the model being too large for your VRAM.

If you want to not load the context into VRAM you can set the `num_gpu` parameter to the number of model layers to see if that helps. Here is an example of how I would do that for a model with 32 layers.
```
ollama run some_model
>>> /set parameter num_gpu 32
Set parameter 'num_gpu' to '32'
```

**Comment by phalexo** [comment]
> Hi @phalexo aside from using a smaller model there are a couple things you could try.
> 
>     1. Make sure you have as much VRAM free as possible. Ollama will only be able to use the VRAM not being used by other programs.
> 
>     2. Check the context size of the model you are trying to run, it may result in the model being too large for your VRAM.
> 
> 
> If you want to not load the context into VRAM you can set the `num_gpu` parameter to the number of model layers to see if that helps. Here is an example of how I would do that for a model with 32 layers.
> 
> ```
> ollama run some_model
> >>> /set parameter num_gpu 32
> Set parameter 'num_gpu' to '32'
> ```

I will experiment with this parameter, but clarify for me something else if you can?

OLLAMA_HOST:0.0.0.0: 424242 litellm --model ollama/model_name

Would the above line force litellm attach to ollama using the specified port or would it still default to 11434?

And if this does not change the default port that ollama presents, is there a way to do it?

**Comment by mxyng** [comment]
> Is it possible to set this in the model file?

Yes, you can set `PARAMETER num_gpu 32` in a Modelfile to achieve the same thing

> OLLAMA_HOST:0.0.0.0: 424242 litellm --model ollama/model_name
> Would the above line force litellm attach to ollama using the specified port or would it still default to 11434?

That's a question better asked in the litellm repo. Ollama uses `OLLAMA_HOST` to configure the host and port so the best answer I can give is if you start ollama manually with those settings, it'll use the specified ports

Note: it looks like there's a space between host (0.0.0.0) and port (424242). I'm not sure if that's intentional or a typo. As is, it's likely an invalid shell command

**Comment by phalexo** [comment]
> > Is it possible to set this in the model file?
> 
> Yes, you can set `PARAMETER num_gpu 32` in a Modelfile to achieve the same thing
> 
> > OLLAMA_HOST:0.0.0.0: 424242 litellm --model ollama/model_name
> > Would the above line force litellm attach to ollama using the specified port or would it still default to 11434?
> 
> That's a question better asked in the litellm repo. Ollama uses `OLLAMA_HOST` to configure the host and port so the best answer I can give is if you start ollama manually with those settings, it'll use the specified ports
> 
> Note: it looks like there's a space between host (0.0.0.0) and port (424242). I'm not sure if that's intentional or a typo. As is, it's likely an invalid shell command

Turns out I have to do this:

```
OLLAMA_HOST=127.0.0.1:11435 litellm --model ollama/deepseek-coder-6.7b-instruct.Q6_K --api_base http://localhost:11435 --port 8001
```

Unfortunately I am not getting async behavior I hoped for. It runs using one GPU at a time, i.e. lower utilization than just swapping models in and out, and running each model on all GPUs.

Still a puzzle how to run AutoGen using async processing.

**Comment by technovangelist** [comment]
It's seems this is a question about litellm. Their repo or discord may be a better place to ask since they will have experience with their product.

**Comment by dhiltgen** [comment]
@phalexo at this time we only load a single model.  It sounds like this issue has morphed to track that, which makes it a dup of #2109 which is something we're working on.

**Comment by phalexo** [comment]
I made that comment a long time ago, so I don't quite remember what I was
doing.

That said, I was able to successfully load multiple models into the same 4
gpus, with each model spread over multiple gpus.
