### ISSUE TITLE
StableLM-Zephyr incompatible with Ollama version

### ISSUE THREAD

**Issue by horiacristescu** [ollama/ollama#1432]
When I run: `ollama run stablelm-zephyr:3b-q6_K`

The result is:
```
Error: llama runner: failed to load model '/home/horia/.ollama/models/blobs/sha256:6d9189f9d9e9c7763daeb08052a07e3a7ed42db66296f1972098fd7f945529b8': this model may be incompatible with your version of Ollama. If you previously pulled this model, try updating it by running `ollama pull stablelm-zephyr:3b-q6_K`
```

I reinstalled ollama fresh, and tried deleting and redownloading the model, and a different quant. My system is Ubuntu 20.04 with CUDA 11.7. Other models work.

BTW, is there a place to give model related feedback? It would be great to be a tab in the models page on ollama.ai

**Comment by technovangelist** [comment]
How did you install ollama?

**Comment by pdevine** [comment]
Thanks for reporting this, @horiacristescu. What type of GPU are you using? I'm assuming if you reinstalled you got the newest version? Do the other quantized versions work?

I just pulled  `stablelm-zephyr:3b-q6_K` and it seems to be working.

**Comment by igorschlum** [comment]
works on mac with 0.1.14 with 32GB

**Comment by Pulkit077** [comment]
Can I use `stablelm-zephyr` in Ollama from `langchain.llms` ?

**Comment by technovangelist** [comment]
hi @Pulkit077 I don't think Langchain has any restrictions on which models can be used with Ollama. So yes, you should be good there

**Comment by technovangelist** [comment]
@horiacristescu I think you may have had an older version of Ollama installed. As @igorschlum noted, it seemed to be working on 0.1.14, and we are on 0.1.17 today, so I think we can probably close this. Can you let us know if you are still experiencing this issue? Otherwise, I'll close it in the next couple of days. Thanks so much for being a great part of this community.

**Comment by jmorganca** [comment]
Yes, please upgrade to the latest version of Ollama, and let me know if this is still happening 😊
