### ISSUE TITLE
Pytorch model quantization, using ollama/quantize docker is not working.

### ISSUE THREAD

**Issue by phalexo** [ollama/ollama#1448]
(base) alexo@GrayMatters:/opt/data/data/Salesforce/codegen25-7b-mono$ docker run --rm -v .:/model -v .:/workdir ollama/quantize -q q6_K ./
sh: 0: cannot open entrypoint.sh: No such file

**Comment by netroy** [comment]
Looking at the docker image `ollama/quantize`, `/workdir` seems to be the `WORKDIR`, where llama.cpp is cloned and compiled, and where the `entrypoint.sh` is copied over to.
So, when you do `-v .:/workdir`, all those files are gone from the container.
You could try to either not mount a volume to that path, or first copy over the content of that folder from the image into the current folder.

**Comment by jmorganca** [comment]
Hi there, we've updated the [docs](https://github.com/ollama/ollama/blob/main/docs/import.md) to use `python` and llama.cpp's `quantize` utility directly – let me know if this helps

**Comment by netroy** [comment]
@jmorganca Does this mean that I should close #2461 ?
