### ISSUE TITLE
setting the system prompt in the repl doesn't show it in /show modelfile

### ISSUE THREAD

**Issue by technovangelist** [ollama/ollama#1453]
If you have a model with no system prompt set, then you run that model, you can set it in the repl. let's say you use `/set system You are a helpful ai assistant. Always answer in German.` and then ask a question, you get back an answer in German. But if you run `/show modelfile`, there is no system prompt set. But if you run `/show system` you will see your new prompt.

**Comment by pdevine** [comment]
This is fixed now.
