### ISSUE TITLE
Repeated output during use

### ISSUE THREAD

**Issue by duyaofei** [ollama/ollama#1454]
Today I am running yi:34b chat q4 using Ollama_ K_ When encountering repetitive output from the repeating machine during M, I entered the same issue on the official webpage and the output was normal. It is speculated that the problem arose from the output of invisible control characters.
Thank you for your hard work. I hope to have time to solve this problem.

**Comment by PrasannaVnewtglobal** [comment]
Try with some other chat models like (codellama, llama2, etc..).

**Comment by pdevine** [comment]
Hi @duyaofei , sorry about the slow response.

I just pulled `yi:34b-chat-q4_K_M` (a045fcc68517) which is working with the most up to date version of ollama (0.1.28). You should be able to upgrade to the latest version and then pull the model again and it should work.

I'm going to go ahead and close the issue, but feel free to keep commenting or to reopen the issue if you're still having problems.
