### ISSUE TITLE
Wrong font in the model sorting dropdown menu in the model page for Safari

### ISSUE THREAD

**Issue by ggetv** [ollama/ollama#1456]
Just noticed a small issue on the model page (https://ollama.ai/library?sort=newest), in Safari browser it somehow showed the wrong font, other browsers (Chrome, Firefox) do not have this issue. I am using Safari Version 17.1 (19616.2.9.11.7).

<img width="1344" alt="ollama-font-issue-safari" src="https://github.com/jmorganca/ollama/assets/36490494/28c46a5b-a3c5-4a39-ae32-1a94898b2edc">

**Comment by technovangelist** [comment]
Wow, that's a great find. Thanks for reporting it.

**Comment by igorschlum** [comment]
I have seen that also and wanted to report it. Thank you @ggetv to have done it.

**Comment by hoyyeva** [comment]
Hello @ggetv, thank you for bringing this error to our attention! We apologize for the delay in resolving it, but it has now been addressed. I'll be closing this issue for the time being. However, should you continue to encounter this problem, please don't hesitate to reopen the issue.
