### ISSUE TITLE
Mistral not providing license information

### ISSUE THREAD

**Issue by neural-loop** [ollama/ollama#1461]
![image](https://github.com/jmorganca/ollama/assets/654993/dfb4a673-8bff-4c40-95be-077014e6a55f)

It is maybe because they don't include a license.txt in their repository. However, they do specify that it is Apache 2.0
![image](https://github.com/jmorganca/ollama/assets/654993/0855ffb3-ad27-46fb-b326-0086243b2f39)

also here
![image](https://github.com/jmorganca/ollama/assets/654993/1fa628bd-e8cf-4f75-97d5-484af80628c2)

It might be nice if licenses were added to the website as well, that users could filter by their licensing needs

**Comment by pdevine** [comment]
This should be fixed now. If you haven't yet, just `ollama pull mistral` again. It's also on the website under the *Tags* view for each individual tag.

**Comment by neural-loop** [comment]
Nice!! Thank you
