### ISSUE TITLE
Q: Why Chat API does not include message in the response body?

### ISSUE THREAD

**Issue by AugustDev** [ollama/ollama#1480]
Why Chat API does not include message in the response body?

Generate API does include the response, is there any reason to omit it here?

**Comment by BruceMacD** [comment]
Hi @AugustDev are you looking for the message in the final response body? Would you be able to give me an example? This is a new endpoint so I appreciate the feedback.

**Comment by rgaidot** [comment]
the structure for the endpoint `/api/chat` is not the same as `/api/generate` it's not _response_ but _message_

/api/chat

`{"model":"mistral","created_at":"2023-12-12T20:29:02.010018961Z","message":{"role":"assistant","content":"\n"},"done":false}
`

/api/generate

`{"model":"llama2","created_at":"2023-12-12T20:32:21.667986258Z","response":"The","done":false}`

It's not a bug

Best.

**Comment by BruceMacD** [comment]
Thanks, I understand the feedback now

**Comment by jmorganca** [comment]
Hi @AugustDev, the chat api returns a `message` since it's an object (vs the response text), this is by design. Let me know if you encounter any more issues
