### ISSUE TITLE
Request for Contributor.md

### ISSUE THREAD

**Issue by aravindputrevu** [ollama/ollama#1489]
It'd be great to have a sample `contributor.md` for aspiring contributors.

**Comment by BruceMacD** [comment]
Thanks for the suggestion, in the meantime if you're looking for environment setup instructions we have those here in `development.md`:
https://github.com/jmorganca/ollama/blob/main/docs/development.md

**Comment by jmorganca** [comment]
A first version of the `CONTRIBUTING.md` was added here recently: https://github.com/ollama/ollama/blob/main/CONTRIBUTING.md

Let me know if there's anything missing or that you'd like to see. Thanks so much for the interest in contributing!
