### ISSUE TITLE
Upgrade to XCode 14.2 breaks build which is looking for 14.0

### ISSUE THREAD

**Issue by jkleckner** [ollama/ollama#1504]
An upgrade to current XCode breaks the build which is looking explicitly for the sdk 14.0 which is now 14.2:

```
$ go generate ./...
Submodule path 'ggml': checked out '9e232f0234073358e7031c1b8d7aa45020469a3b'
CMake Warning at /opt/homebrew/Cellar/cmake/3.28.0/share/cmake/Modules/Platform/Darwin-Initialize.cmake:308 (message):
  Ignoring CMAKE_OSX_SYSROOT value:

   /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.0.sdk

  because the directory does not exist.
Call Stack (most recent call first):
  /opt/homebrew/Cellar/cmake/3.28.0/share/cmake/Modules/CMakeSystemSpecificInitialize.cmake:34 (include)
  CMakeLists.txt:2 (project)
```

SDK links:
```
$ ls -l /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs
total 0
drwxr-xr-x  7 root  wheel   224B Nov 13 10:25 MacOSX.sdk
lrwxr-xr-x  1 root  wheel    10B Dec 13 06:00 MacOSX14.2.sdk -> MacOSX.sdk
lrwxr-xr-x  1 root  wheel    10B Dec 13 06:00 MacOSX14.sdk -> MacOSX.sdk
```

**Comment by rgaidot** [comment]
Do you've accept the new license `sudo xcodebuild -license`? I don't think it comes from ollama but your computer

**Comment by oderwat** [comment]
I had a similar (the same?) problem and `export SDKROOT=$(xcrun --sdk macosx --show-sdk-path)` fixed it for me. But I wonder how to make this permanent or what the underlying problem may be.

**Comment by jkleckner** [comment]
> Do you've accept the new license sudo xcodebuild -license? I don't think it comes from ollama but your computer

Yes.

> I had a similar (the same?) problem and `export SDKROOT=$(xcrun --sdk macosx --show-sdk-path)` fixed it for me. But I wonder how to make this permanent or what the underlying problem may be.

This worked for me.  Also I wonder how to make it permanent.

**Comment by jmorganca** [comment]
Hi all, are you still this issue on `main`? The pinned macOS deployment target variable has been removed and so it shouldn't be looking for a specific version of XCode

**Comment by oderwat** [comment]
@jmorganca I did not need to recompile till some minutes ago. But now I updated to current main, and it did work without problems for me.

**Comment by jmorganca** [comment]
Thanks for the update!

**Comment by vdentello** [comment]
Not sure if it helps, but in my case, after updating, I would get the following warning.

Showing All Messages
unable to find sdk '/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.0.sdk'

Whereas the folder is named MacOSX14.sdk.

I renamed the folder to MacOSX14.0.sdk and now it works again, took my a while to figure out but it worked.
Additionally, I believe you could just create a new pointing shortcut into the folder with 14.0 and keep the one with 14, in case something tries to search for the other one.
