### ISSUE TITLE
Add a section for blogs and tutorials

### ISSUE THREAD

**Issue by FairyTail2000** [ollama/ollama#1510]
It might benefit the adoption of ollama to introduce a section containing links to such tutorials or writeups like this: [https://fly.io/blog/scaling-llm-ollama/](https://fly.io/blog/scaling-llm-ollama/)

Of course it's not required but might benefit the project

**Comment by FairyTail2000** [comment]
I just found this tutorial https://github.com/jmorganca/ollama/blob/31f0551dab9a10412ec6af804445e02a70a25fc2/docs/tutorials/fly-gpu.md which feels like it's a transcript of the website/blog mentioned above

**Comment by technovangelist** [comment]
Thanks so much for this issue. We talked about this in our standup. We agreed that it was important to share, but we really want the front readme to just show projects that use Ollama as part of a tool. So we talked about creating a community page in the docs. It should get merged soon and then it would be great to add content like this there.

**Comment by FairyTail2000** [comment]
I will add it once it's merged

**Comment by jmorganca** [comment]
Hi @FairyTail2000 thanks for the issue, and sorry to leave this hanging. High quality examples are definitely welcome as PRs for the `examples` directory. I'll close this to keep the number of issues manageable :)
