### ISSUE TITLE
Generation speed 3x slower after pulling newer docker image

### ISSUE THREAD

**Issue by johnp-4dvanalytics** [ollama/ollama#1512]
I updated the docker image recently and the inference was 3x slower (30s for new image vs. 10s for old image). I was able to get back to the previous inference speed by reverting to ollama/ollama:0.1.10. I tried ollama/ollama:0.1.15 and ollama/ollama:0.1.14 and both had the slower inference speed.

EDIT: model used was https://ollama.ai/library/openhermes2.5-mistral:latest

**Comment by jmorganca** [comment]
Hi there, this should be fixed in newer versions of Ollama, but let me know if that isn't the case. Thanks for creating an issue!
