### ISSUE TITLE
I don't like the idea that ollama force me to use a server.

### ISSUE THREAD

**Issue by franciscoprin** [ollama/ollama#1513]
so, if I have a python code that looks like this:
```python
from langchain.schema import (SystemMessage, HumanMessage, AIMessage)
from langchain.callbacks.manager import CallbackManager
from langchain.callbacks.streaming_stdout import StreamingStdOutCallbackHandler
from langchain.chat_models import ChatOllama

question = "Could I have GitHub access?"
chat_template = [
    SystemMessage(
        content=(
            "You are a helpful DevOps assistant, rewrite user's questions to only include the websites that they want to access."
        )
    ),
    HumanMessage(content=question),
]

chat_model = ChatOllama(
    # model="llama2:7b-chat",
    model_path="./models/llama-2-7b-chat.Q4_K_M.gguf",
    callback_manager=CallbackManager([StreamingStdOutCallbackHandler()]),
)

chat_model(chat_template)
```

the above source code gives me the following error:
```
requests. exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/generate/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x107601090>: Failed to establish a new connection: [Errno 61] Connection refused'))
```

I don't want my models to be downloaded by Ollama service, I want to use the models that I already had downloaded instead.

**Comment by easp** [comment]
Then [import](https://github.com/jmorganca/ollama/blob/main/docs/import.md) the ones you have downloaded or choose something that is better aligned with your requirements. 

Ollama's integrated model management is pretty central to its value proposition.

**Comment by pdevine** [comment]
@franciscoprin as @easp mentioned, you can make a Modelfile and then use `ollama create` to pull the model in. Ollama uses its own "layers" (called "blobs") which stored the various parts of the model such as the weights. What's really nice about this is that if you have multiple models which share the same weights it will automatically deduplicate them on disk. Also, once you've imported your model you can use `ollama push` to push it to `ollama.com` and share it with others.

I'm going to go ahead and close out the issue, but feel free to keep commenting if you have any questions.
