### ISSUE TITLE
How to import "MPTForCausalLM" models?

### ISSUE THREAD

**Issue by ansutung** [ollama/ollama#1538]
Hello everyone,

I'm not sure if I can use the model with the "MPTForCausalLM" architecture with Ollama. I tried to import it following the instructions here: https://github.com/jmorganca/ollama/blob/main/docs/import.md

The import process was successful, but when running with the new model, I encountered an error: "ollama run example "What is your favourite condiment?"

I am using models from this source:
https://huggingface.co/vinai/PhoGPT-7B5
https://huggingface.co/vinai/PhoGPT-7B5-Instruct

![image](https://github.com/jmorganca/ollama/assets/26163387/787875d3-9fc6-4883-beb0-585a12e5e5f1)

Thanks

**Comment by mchiang0610** [comment]
Hi @ansutung sorry about this. This model should be able to run with Ollama. Are you still seeing issues running the model? If so, can you share the modelfile being used? 

So sorry about this. [let me know if you are still running into this problem, and reopen]
