### ISSUE TITLE
Better model quantization defaults from ollama.com

### ISSUE THREAD

**Issue by knoopx** [ollama/ollama#1543]
Is there a reason `latest` tag on the model hub points, by default, to the older `q4_0` quants? The newer `k_m/s` are 
supposedly better and the size difference is usually just a few hundred megabytes, it would be nice if it defaulted to those instead.

**Comment by choltha** [comment]
Difference in perplexity is listed here:
https://github.com/ggerganov/llama.cpp/discussions/2094#discussioncomment-6351796
Relevant lines:
Q4_0   :  3.50G, +0.2499 ppl @ 7B
Q4_K_S :  3.56G, +0.1149 ppl @ 7B
Q3_K_L :  3.35G, +0.1803 ppl @ 7B
Q4_K_M :  3.80G, +0.0535 ppl @ 7B
F16    : 13.00G              @ 7B

F16 is the baseline reference for perplexity 

Surprisingly even Q3_K_L  is listed with lower perplexity than Q4_0 while being smaller. This is also the recommendation by "the bloke":
Q4_0: legacy; small, very high quality loss - prefer using Q3_K_M

**Comment by choltha** [comment]
I would create a PR if someone points me to the place where the defaults for this are set.

**Comment by mchiang0610** [comment]
Thank you for sharing this. We will be working to have more sane defaults from ollama.com; sorry about this.

**Comment by jtsorlinis** [comment]
Any updates on this? Would be great to default to something like q4_k_m

**Comment by DuckyBlender** [comment]
related to #5425

**Comment by jmorganca** [comment]
The default is now q4_k_m - and in the future additional, higher-quality 4-bit quantization formats are looking to be supported (e.g. AWQ)
