### ISSUE TITLE
Error: failed to start a llama runner

### ISSUE THREAD

**Issue by webmastermario** [ollama/ollama#1550]
Hello,

i tried to install ollama on my centos dedicated server but everything is working but when i try 
[root@213-227-129-200 ~]#  ollama run llava 
Error: failed to start a llama runner

i get this. what can i do? 

-- Logs begin at Fri 2023-08-04 06:00:01 UTC, end at Fri 2023-12-15 18:45:42 UTC. --
Dec 15 15:33:10 213-227-129-200.cprapid.com systemd[1]: Started Ollama Service.
Dec 15 15:33:10 213-227-129-200.cprapid.com ollama[25174]: Couldn't find '/usr/share/ollama/.ollama/id_ed25519'. Generating ne
Dec 15 15:33:10 213-227-129-200.cprapid.com ollama[25174]: Your new public key is:
Dec 15 15:33:10 213-227-129-200.cprapid.com ollama[25174]: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGFFKiLz3PKkUtFK+Bj3gAJK7csulDh
Dec 15 15:33:10 213-227-129-200.cprapid.com ollama[25174]: 2023/12/15 15:33:10 images.go:737: total blobs: 0
Dec 15 15:33:10 213-227-129-200.cprapid.com ollama[25174]: 2023/12/15 15:33:10 images.go:744: total unused blobs removed: 0
Dec 15 15:33:10 213-227-129-200.cprapid.com ollama[25174]: 2023/12/15 15:33:10 routes.go:871: Listening on 127.0.0.1:11434 (ve
Dec 15 15:33:10 213-227-129-200.cprapid.com ollama[25174]: 2023/12/15 15:33:10 routes.go:891: warning: gpu support may not be
Dec 15 15:34:10 213-227-129-200.cprapid.com ollama[25174]: [GIN] 2023/12/15 - 15:34:10 | 200 |     178.535µs |       127.0.0.1
Dec 15 15:34:10 213-227-129-200.cprapid.com ollama[25174]: [GIN] 2023/12/15 - 15:34:10 | 200 |  181.125375ms |       127.0.0.1
Dec 15 15:34:47 213-227-129-200.cprapid.com ollama[25174]: [GIN] 2023/12/15 - 15:34:47 | 200 |      44.934µs |       127.0.0.1
Dec 15 15:34:49 213-227-129-200.cprapid.com ollama[25174]: 2023/12/15 15:34:49 download.go:123: downloading 200765e12836 in 39
Dec 15 15:35:27 213-227-129-200.cprapid.com ollama[25174]: 2023/12/15 15:35:27 download.go:123: downloading 64c2234f0395 in 7
Dec 15 15:35:36 213-227-129-200.cprapid.com ollama[25174]: 2023/12/15 15:35:36 download.go:123: downloading d5ca8c59f62d in 1
Dec 15 15:35:39 213-227-129-200.cprapid.com ollama[25174]: 2023/12/15 15:35:39 download.go:123: downloading 6c58ad369ad0 in 1
Dec 15 15:35:42 213-227-129-200.cprapid.com ollama[25174]: 2023/12/15 15:35:42 download.go:123: downloading 805db971dc64 in 1
Dec 15 15:35:49 213-227-129-200.cprapid.com ollama[25174]: [GIN] 2023/12/15 - 15:35:49 | 200 |          1m1s |       127.0.0.1
Dec 15 15:37:09 213-227-129-200.cprapid.com ollama[25174]: [GIN] 2023/12/15 - 15:37:09 | 200 |     175.861µs |       127.0.0.1
Dec 15 15:37:09 213-227-129-200.cprapid.com ollama[25174]: [GIN] 2023/12/15 - 15:37:09 | 200 |    1.276939ms |       127.0.0.1
Dec 15 15:37:09 213-227-129-200.cprapid.com ollama[25174]: [GIN] 2023/12/15 - 15:37:09 | 200 |     831.562µs |       127.0.0.1
Dec 15 15:37:09 213-227-129-200.cprapid.com ollama[25174]: 2023/12/15 15:37:09 llama.go:403: skipping accelerated runner becau
Dec 15 15:37:09 213-227-129-200.cprapid.com ollama[25174]: 2023/12/15 15:37:09 llama.go:436: starting llama runner

**Comment by webmastermario** [comment]
Pumping this.

**Comment by BruceMacD** [comment]
It looks like it may be timing out waiting for the model to be loaded into memory. This may mean you don't have enough resources, I'd suggest trying a smaller model.

We will also be merging a change soon that should no longer timeout, you can track the progress of that here: #1146

**Comment by dhiltgen** [comment]
@webmastermario can you give the latest release a try (0.1.22)   If you're still having problems, please share the server log from the new version.

**Comment by dhiltgen** [comment]
If you're still having problems with 0.1.22 or newer, please re-open.
