### ISSUE TITLE
Increasing slow response - CPU only on Linux Azure

### ISSUE THREAD

**Issue by benmarinic** [ollama/ollama#1557]
I'm using the following VM in azure: 
Standard D8s v3 vCPUs 8, RAM 32 GiB

Have tried Mistral 7b and Orca-mini. I've also tried 4 bit versions. 

Ollama is responding increasingly slowly. After the 4th simple query ("hi" or "what's the capital of ...") I'm waiting in excess of 60 seconds for it to begin to respond; the response gets slow with each repeat simple question. Once it has responded the each token streams in reasonably well. I've tried both Ubuntu and Suse. 

Is the VM just not suitable? I'm trying to see how far I can get without a GPU.

**Comment by cwegener** [comment]
> Is the VM just not suitable? I'm trying to see how far I can get without a GPU.

I don't think it has anything to do with the VM.

I noticed the same problem with the latest 0.1.16 release as well

**Comment by anujva** [comment]
yep.. I am facing the same issue with 0.1.16 release.. I will see if I can downgrade and get better inference times.

**Comment by benmarinic** [comment]
> > Is the VM just not suitable? I'm trying to see how far I can get without a GPU.
> 
> 
> 
> I don't think it has anything to do with the VM.
> 
> 
> 
> I noticed the same problem with the latest 0.1.16 release as well
> 
> 
> 
> Also, this seems to be a duplicate of #1556 
> 
> 

Yes looks like the same issue. I should have said I was doing this in the command prompt - I have now tried API requests on the same instance and these respond much better and without increasing slowness.

**Comment by phalexo** [comment]
Is it still an issue on newer GPUs with tensor cores? I still use Maxwell GPUs, and it is quite slow. Have to check the interactive mode with llama.cpp directly.

**Comment by benmarinic** [comment]
> Using it directly with llama.cpp does NOT appear to suffer from the same latency issue.
> 
> 
> 
> The problem appears to be ollama specific.
> 
> 

Have you compared the ollama API endpoint "generate" speed vs llama.cpp by any chance? It's not suffering from increasing latency, but interested to know if it's still slower than llama.cpp.

**Comment by BruceMacD** [comment]
How much time is it getting slower over? It sounds like the increasing conversation history is increasing time to generate, which I partially expect, but not major degradation.

**Comment by AndreiSva** [comment]
I am also facing this issue

**Comment by dhiltgen** [comment]
Are folks still seeing this behavior on the latest release?

**Comment by AndreiSva** [comment]
It's been fixed for me!

**Comment by dhiltgen** [comment]
That's great!

I'll go ahead and close this then.  @benmarinic if you're still having troubles, please let us know and I'll re-open the issue.

**Comment by lewismunene020** [comment]
still having the same issue  i tried it out  today  the latest docker  image   seems  to  have  same  issue  on my 16bg 8core   specs please check what  might  be  the  issue
