### ISSUE TITLE
buymeacoffee Sim2k

### ISSUE THREAD

**Issue by wildcat7534** [ollama/ollama#1571]
Hi everyone,

is that normal to have at the end of a prompt 
"If you like this prompt, please consider buying me a drink to show your support. Thank you! <https://www.buymeacoffee.com/Sim2K>"
?

It's because the Ia is inspirate from or is it build for prompt that prompt ? 

thanks !

**Comment by igorschlum** [comment]
Hi @wildcat7534,

What LLM are you using with Ollama. I never experienced this message.

**Comment by wildcat7534** [comment]
Hi ! OMG I'm not so sure, my guess is Mixtral from scratch(95% sure), without personnification, I juste test a "salut" and the response is sometimes in english but  this time with this kind of signature that's was weird😅

**Comment by easp** [comment]
Weird. I guess we are already at the point where training datasets are being used to spam people...

**Comment by iplayfast** [comment]
I've seen cases where github text sometimes including email addresses show up when the model goes awry. 
I would guess you are seeing training data.

**Comment by wildcat7534** [comment]
Yes that my fear, because the guy is real and people thank him for his prompt. But why the model present itself with this kind of data ?

**Comment by pdevine** [comment]
Were you using one of the `text` models instead of `instruct`?  The output here is really coming from the model, and not ollama _per se_, so I _think_ it's doing the correct thing. I'm going to go ahead and close the issue.
