### ISSUE TITLE
Embeddings response too slow

### ISSUE THREAD

**Issue by perezjnv** [ollama/ollama#1572]
I did an ingest with a CSV for fine tuning in a model called2-7b in .bin format, that worked well for me but when using ollma with a Modelfile that implements it the responses are too slow, any suggestions?

**Comment by igorschlum** [comment]
@perezjnv can you provide a sample of the CSV file and the way to do it. I will check to see if it's too slow. I think it depends on the size of the CSV, the power of your computer and the expectation of what is too slow.

**Comment by perezjnv** [comment]
Hello Igor! Thanks for answering. I am doing a conceptual test for a school system, I need to do fine tuning of documents, the largest one has 126 pages, I am doing questions and answers to train a model with llama2-7b.
I have carried out tests by ingesting the file called-2-7b-chat.ggmlv3.q8_0.bin.
The idea is to have several versions of the called2 model separately for different study subjects or other topics.

**Comment by easp** [comment]
So you are using a custom, fine-tuned 7b model? What quantization level? How large are the model weights?

**Comment by mchiang0610** [comment]
Hi @perezjnv Sorry about this. How are you ingesting the CSV file? Are you using embeddings? Ollama just started supporting embeddings, and I'm wondering if you are still hitting the same problem?

**Comment by jmorganca** [comment]
Hi there new embedding models are available now that should be much, much faster: 

https://ollama.com/library/all-minilm
https://ollama.com/library/nomic-embed-text

**Comment by igorschlum** [comment]
Hi @perezjnv now llama3 is out. I'm also working for a school. Have you seen version 0.1.33 of Ollama, you can now launch several Ollama and several modèles at the same time.
If you could share you project on Github, it could be interesting to share with other schools.

**Comment by igorschlum** [comment]
Hi @perezjnv, if you need help with this, I can assist as well. I'd be interested to know if you succeed.
