### ISSUE TITLE
ValueError: Error raised by inference API HTTP code: 500, {"error":"failed to generate embedding"}

### ISSUE THREAD

**Issue by doganaktarr** [ollama/ollama#1577]
When i'm trying ollama for document chat i get api error when it tries to create vectorstore.

```python
from langchain.llms import Ollama
from langchain.document_loaders import WebBaseLoader
from langchain.embeddings import OllamaEmbeddings
from langchain.vectorstores import Chroma
from langchain.chains import RetrievalQA
from langchain.text_splitter import RecursiveCharacterTextSplitter

ollama = Ollama(base_url='http://localhost:11434',
model="llama2")
print(ollama("why is the sky blue"))

loader = WebBaseLoader("https://www.gutenberg.org/files/1727/1727-h/1727-h.htm")
data = loader.load()

text_splitter=RecursiveCharacterTextSplitter(chunk_size=500, chunk_overlap=0)
all_splits = text_splitter.split_documents(data)
oembed = OllamaEmbeddings(base_url="http://localhost:11434", model="llama2")

print("embedding: ", oembed)
vectorstore = Chroma.from_documents(documents=all_splits, embedding=oembed)

question="Who is Neleus and who is in Neleus' family?"
docs = vectorstore.similarity_search(question)
len(docs)

qachain=RetrievalQA.from_chain_type(ollama, retriever=vectorstore.as_retriever())
qachain({"query": question})
```
In my terminal the prints look like this:

```terminal
The sky appears blue because of a phenomenon called Rayleigh scattering, which occurs when sunlight enters Earth's atmosphere. The sunlight encounters tiny molecules of gases such as nitrogen and oxygen in the air, which scatter the light in all directions.

The shortest wavelengths of light, such as violet and blue, are scattered more than other colors, such as red and orange, because they have a shorter wave length. This means that these colors are dispersed throughout the atmosphere, giving the sky its blue appearance.

Other factors can also affect the color of the sky, such as the presence of dust, water vapor, and pollutants in the air. For example, during sunrise and sunset, the sky may take on hues of red, orange, and pink due to the scattering of light by atmospheric particles.

It's worth noting that the color of the sky can also vary depending on the observer's location and the time of day. For example, the sky may appear more blue or gray if you are near a body of water or in an area with a high level of air pollution.

In summary, the sky appears blue because of the way light interacts with the tiny molecules of gases in the air, known as Rayleigh scattering. This phenomenon scatters shorter wavelengths of light, such as blue and violet, more than longer wavelengths, giving the sky its characteristic blue color.
embedding:  base_url='http://localhost:11434' model='llama2' embed_instruction='passage: ' query_instruction='query: ' mirostat=None mirostat_eta=None mirostat_tau=None num_ctx=None num_gpu=None num_thread=None repeat_last_n=None repeat_penalty=None temperature=None stop=None tfs_z=None top_k=None top_p=None model_kwargs=None
Traceback (most recent call last):
  File "olama.py", line 23, in <module>
    vectorstore = Chroma.from_documents(documents=all_splits, embedding=oembed)
  File "./Env/chatbot/lib/python3.8/site-packages/langchain/vectorstores/chroma.py", line 771, in from_documents
    return cls.from_texts(
  File "./Env/chatbot/lib/python3.8/site-packages/langchain/vectorstores/chroma.py", line 729, in from_texts
    chroma_collection.add_texts(
  File "./Env/chatbot/lib/python3.8/site-packages/langchain/vectorstores/chroma.py", line 275, in add_texts
    embeddings = self._embedding_function.embed_documents(texts)
  File "./Env/chatbot/lib/python3.8/site-packages/langchain/embeddings/ollama.py", line 190, in embed_documents
    embeddings = self._embed(instruction_pairs)
  File "./Env/chatbot/lib/python3.8/site-packages/langchain/embeddings/ollama.py", line 175, in _embed
    embeddings = self._process_emb_response(prompt)
  File "./Env/chatbot/lib/python3.8/site-packages/langchain/embeddings/ollama.py", line 160, in _process_emb_response
    raise ValueError(
ValueError: Error raised by inference API HTTP code: 500, {"error":"failed to generate embedding"}
```

And even i try to get embeddings via api
```terminal
curl -X POST http://localhost:11434/api/embeddings -d '{
    "model": "llama2",
    "prompt": "hello, how are you?"
}'
```
My embeddings looks like this:

```terminal
{"embedding":[0.713813066482544,-1.8217487335205078,0.48764699697494507,-0.8590573668479919,-0.7165888547897339,0.09285138547420502,-0.06305933743715286,0.8703135251998901,-0.7629101872444153,0.40360304713249207,1.6491974592208862,-0.7351164817810059,0.9032987356185913,1.0884538888931274,0.754738986492157,-0.0351458303630352,-0.2696535289287567,0.030562296509742737,-0.5470462441444397,-0.7511221170425415,1.6396052837371826,-2.254915714263916,-0.2600090503692627,-2.861804723739624,-0.31693896651268005,-1.0240172147750854,-0.7449401617050171,-2.3529539108276367,1.3769773244857788,-0.15259328484535217,1.564031958580017,0.33758652210235596,-1.2046291828155518,2.713618040084839,-0.22524534165859222,0.08619225025177002,0.5370852947235107,1.7855254411697388,-0.06518085300922394,-0.0628420040011406,0.5781055092811584,-4.234992504119873,-1.2907594442367554,-0.1936117261648178,1.3087000846862793,0.14808768033981323,-1.689073085784912,-3.103379011154175,0.5116130709648132,-1.674410104751587,0.026191502809524536,0.31160175800323486,1.843047022819519,-0.754763662815094,2.64321231842041,-0.9525578618049622,1.4135092496871948,1.014215350151062,1.701998233795166,0.35821205377578735,-4.310467720031738,1.3969742059707642,-0.3026293218135834,1.1710561513900757,-3.1511785984039307,-0.9500783681869507,0.25463706254959106,0.2536858320236206,0.2566526234149933,-0.8113981485366821,1.434630274772644,-0.41049930453300476,1.3408557176589966,0.3780902028083801,-2.971435546875,1.556931495666504,2.2950439453125,-2.0468714237213135,-1.6436930894851685,-0.6824514269828796,0.2970106601715088,0.48574963212013245,1.3311458826065063,-1.2823209762573242,-1.0872153043746948,1.0507322549819946,1.6134350299835205,0.44947174191474915,0.14205259084701538,-1.4551608562469482,-0.43960702419281006,-1.6097815036773682,-3.165051221847534,0.6144835352897644,1.2260065078735352,0.8544708490371704,-0.5544838905334473,-1.207687258720398,0.3186914324760437,-0.9924833178520203,0.48585525155067444,-0.987743616104126,-1.0047131776809692...
```

**Comment by BruceMacD** [comment]
Hi @doganaktarr, is there any error captured in the ollama server logs? Here's where you can find them on your OS:
https://github.com/jmorganca/ollama/blob/main/docs/faq.md#how-can-i-view-the-logs

**Comment by yunghoy** [comment]
Same here.


 ollama[156]: [GIN] 2024/01/10 - 20:33:43 | 200 |  5.488433954s |       127.0.0.1 | POST     "/api/embeddings"
^ Through curl POST calls.

ollama[156]: 2024/01/10 20:34:25 ext_server_common.go:165: loaded 0 images
ollama[156]: [GIN] 2024/01/10 - 20:34:25 | 200 |  808.259018ms |       127.0.0.1 | POST     "/api/generate"
ollama[156]: [GIN] 2024/01/10 - 20:34:25 | 500 |     134.574µs |       127.0.0.1 | POST     "/api/embeddings"
ollama[156]: [GIN] 2024/01/10 - 20:34:27 | 500 |     149.817µs |       127.0.0.1 | POST     "/api/embeddings"
ollama[156]: [GIN] 2024/01/10 - 20:34:29 | 500 |     136.614µs |       127.0.0.1 | POST     "/api/embeddings"
ollama[156]: [GIN] 2024/01/10 - 20:34:34 | 500 |     142.824µs |       127.0.0.1 | POST     "/api/embeddings"
^ Through Langchain calls.

Provided the model info properly.

**Comment by vipinap98** [comment]
Is this issue solved? I'm still having the same issue!

**Comment by jerryola1** [comment]
I had this same error, and how I fixed it was using WSL for windows and creating a virtual environment.

**Comment by mchiang0610** [comment]
@doganaktarr @jerryola1 @vipinap98, may I ask if any of you are still running into the problem? 

This issue was created before we added official embedding support on Ollama -- and it means it'll inference only on the CPU back then. I'm wondering if it's hitting some bottleneck there. Now, it's GPU accelerated.

**Comment by jerryola1** [comment]
No, it's fixed from my end

**Comment by edchengmooree** [comment]
New user here but I still get this issue on my end, ollama serve showing constant 500 errors

`[GIN] 2024/03/12 - 11:26:01 | 200 | 12.865901039s |       127.0.0.1 | POST     "/api/pull"
[GIN] 2024/03/12 - 11:26:04 | 500 |      296.28µs |       127.0.0.1 | POST     "/api/embeddings"
[GIN] 2024/03/12 - 11:26:04 | 500 |      227.67µs |       127.0.0.1 | POST     "/api/embeddings"
[GIN] 2024/03/12 - 11:26:05 | 500 |     280.857µs |       127.0.0.1 | POST     "/api/embeddings"
[GIN] 2024/03/12 - 11:26:07 | 500 |     310.478µs |       127.0.0.1 | POST     "/api/embeddings"
[GIN] 2024/03/12 - 11:26:13 | 500 |     320.161µs |       127.0.0.1 | POST     "/api/embeddings"
[GIN] 2024/03/12 - 11:26:27 | 500 |     322.997µs |       127.0.0.1 | POST     "/api/embeddings"
[GIN] 2024/03/12 - 11:26:48 | 500 |     306.062µs |       127.0.0.1 | POST     "/api/embeddings"
[GIN] 2024/03/12 - 11:27:33 | 500 |     311.024µs |       127.0.0.1 | POST     "/api/embeddings"
[GIN] 2024/03/12 - 11:27:33 | 500 |      260.77µs |       127.0.0.1 | POST     "/api/embeddings"
[GIN] 2024/03/12 - 11:27:35 | 500 |     267.115µs |       127.0.0.1 | POST     "/api/embeddings"
[GIN] 2024/03/12 - 11:27:37 | 500 |     301.359µs |       127.0.0.1 | POST     "/api/embeddings"
[GIN] 2024/03/12 - 11:27:43 | 500 |     311.964µs |       127.0.0.1 | POST     "/api/embeddings"
[GIN] 2024/03/12 - 11:27:55 | 500 |     301.202µs |       127.0.0.1 | POST     "/api/embeddings"
`

**Comment by SikamikanikoBG** [comment]
I had the same issue with .27 version. Today I upgraded to .28 and I have the same:

Flowise:
![image](https://github.com/ollama/ollama/assets/46193504/69732924-9108-4132-a562-8075b41f73ed)

And the server logs:
[GIN] 2024/03/12 - 10:47:07 | 500 | 507.948µs | 172.17.0.1 | POST "/api/embeddings"
[GIN] 2024/03/12 - 10:47:26 | 500 | 505.182µs | 172.17.0.1 | POST "/api/embeddings"
[GIN] 2024/03/12 - 10:47:26 | 500 | 702.412µs | 172.17.0.1 | POST "/api/embeddings"
[GIN] 2024/03/12 - 10:47:28 | 500 | 428.304µs | 172.17.0.1 | POST "/api/embeddings"
[GIN] 2024/03/12 - 10:47:30 | 500 | 632.877µs | 172.17.0.1 | POST "/api/embeddings"
[GIN] 2024/03/12 - 10:47:36 | 500 | 531.406µs | 172.17.0.1 | POST "/api/embeddings"
[GIN] 2024/03/12 - 10:47:44 | 500 | 560.034µs | 172.17.0.1 | POST "/api/embeddings"
[GIN] 2024/03/12 - 10:47:44 | 500 | 389.676µs | 172.17.0.1 | POST "/api/embeddings"
[GIN] 2024/03/12 - 10:47:44 | 500 | 807.651µs | 172.17.0.1 | POST "/api/embeddings"
[GIN] 2024/03/12 - 10:47:45 | 500 | 477.732µs | 172.17.0.1 | POST "/api/embeddings"

**Comment by uzumakinaruto19** [comment]
ValueError: Error raised by inference API HTTP code: 500, {"error":"failed to generate embedding"}

still I'm getting with the latest ollama docker 

> Hi folks this should be fixed now - please let me know if that's not the case

@jmorganca

**Comment by LeK530** [comment]
I still have the issue. What is the resolution?

**Comment by emmanuel-torres1** [comment]
I have the same issue and I am running Ollama locally:

ValueError: Error raised by inference API HTTP code: 500, {"error":"failed to generate embedding"}
