### ISSUE TITLE
PowerPC

### ISSUE THREAD

**Issue by RealMrCactus** [ollama/ollama#1597]
Is it possible to run this on powerpc

**Comment by RealMrCactus** [comment]
> I don't think this works today, but we can leave this open to track it in case an update is made to support it in the future. Thanks for being part of this great community.

No problem you can just get like super powerful ibm PPC machines for like 200-400 usd with 10 or more cores so it would make sense to put the ai on it i have access to one with 80

**Comment by Londo-Mollari** [comment]
Just to add to this, I have an AC922 with 110 logical CPUs 4x GPUs and having Ollama utilize this would be really nice.
