### ISSUE TITLE
Is there any option to unload a model from memory?

### ISSUE THREAD

**Issue by DanielMazurkiewicz** [ollama/ollama#1600]
As in the title. I want to unload model, is there any option for it?

**Comment by zach030** [comment]
No support yet, you can only shutdown the serve to close the model

**Comment by technovangelist** [comment]
The model gets automatically unloaded after 5 minutes.

**Comment by igorschlum** [comment]
I think that it could be interesting to set a parameter for the 5 minutes. Sometimes, you want less or more, depending the usage of Ollama you make.

**Comment by mattbisme** [comment]
There are some use cases where it would be nice to have it unload almost immediately (single-turn Siri request). But other times where it would be better to have it loaded indefinitely (a chatbot that is prompted occasionally where a fast response provides a better experience). 

Being able to configure this parameter at model runtime (especially via API) would be great!

**Comment by chymian** [comment]
+1 for the API- & Modelfile-tuneable unload parameter, especially: __keep-inifinit__

**Comment by dennisorlando** [comment]
Something as simple as "ollama load" and "ollama unload" would suffice

**Comment by olekse** [comment]
Quack

**Comment by pdevine** [comment]
#2146 adds this which will be available in `0.1.23`. Going to go ahead and close this. You can set `keep_alive` to `-1` when calling the chat API and it will leave the model loaded in memory.

**Comment by nathanleclaire** [comment]
@pdevine For what it's worth I would still like the ability to manually evict a model from VRAM through a CLI command. The keepalive functionality is nice but on my Linux box (will have to double-check later to make sure it's latest version, but installed very recently) after a chat session the model just sits there in VRAM and I have to restart ollama to get it out if something else wants to use the GPU. Which, of course, is a shame because I would also like to `ollama pull` things at the same time :)

**Comment by OliChase404** [comment]
This might help, from the [faq.md](https://faq.md/) file:

## How do I keep a model loaded in memory or make it unload immediately?
By default models are kept in memory for 5 minutes before being unloaded. This allows for quicker response times if you are making numerous requests to the LLM. You may, however, want to free up the memory before the 5 minutes have elapsed or keep the model loaded indefinitely. Use the `keep_alive` parameter with either the `/api/generate` and `/api/chat` API endpoints to control how long the model is left in memory.
The `keep_alive` parameter can be set to:
* a duration string (such as "10m" or "24h")
* a number in seconds (such as 3600)
* any negative number which will keep the model loaded in memory (e.g. -1 or "-1m")
* '0' which will unload the model immediately after generating a response
For example, to preload a model and leave it in memory use:
```shell
curl http://localhost:11434/api/generate -d '{"model": "llama2", "keep_alive": -1}'
```
To unload the model and free up memory use:
```shell
curl http://localhost:11434/api/generate -d '{"model": "llama2", "keep_alive": 0}'

**Comment by OliChase404** [comment]
So to immediately unload a model and free your vram run:

curl http://localhost:11434/api/generate -d '{"model": "MODELNAME", "keep_alive": 0}'

Replace MODELNAME with the name of the model currently loaded.

**Comment by olekse** [comment]
What about removing the model from the RAM? It still stays in RAM when VRAM is cleared.

**Comment by pdevine** [comment]
@olekse it's the same.

**Comment by wenhui01** [comment]
This parameter can't work with embedding model.

**Comment by Divelix** [comment]
CLI command to immediately unload model from memory is a must have for me. Most of the time 5 mins is fine, but occasionally I have to shut it down right now to use full VRAM for smth else. Implement what @dennisorlando suggested above, please.

**Comment by VfBfoerst** [comment]
> curl http://localhost:11434/api/generate -d '{"model": "MODELNAME", "keep_alive": 0}'

worked for me :)

**Comment by eav-solution** [comment]
Vote

**Comment by Choumingzhao** [comment]
A shell function to unload all models:
```shell
ollama_unload() {
  # list all models
  models=$(ollama ps | awk 'NR>1 {print $1}')

  # unload all models
  for model in $models; do
    echo "unloading model: $model"
    curl -X POST http://localhost:11434/api/generate -d "{\"model\": \"$model\", \"keep_alive\": 0}"
  done
}
```

**Comment by Dement242** [comment]
Here is a script that will list all running models on the servers-ip´s you specify (edit: ips=("192.168.1.40" "192.168.1.42") ), then select which model you want to unload.
--------

#!/bin/bash

# Define the IP addresses
ips=("192.168.1.40" "192.168.1.42")

# Function to fetch models from a given IP address
fetch_models() {
    local ip=$1
    json_response=$(curl -s http://$ip:11434/api/ps)
    echo "$json_response" | jq -r --arg ip "$ip" '.models[] | "\($ip) \(.model)"'
}

# Step 1: Fetch models from all IP addresses and display as a numbered list
declare -a models_list
index=1
echo "Available models:"
for ip in "${ips[@]}"; do
    echo "Server $ip:"
    models=$(fetch_models $ip)
    IFS=$'\n' read -rd '' -a models_array <<< "$models"
    for model in "${models_array[@]}"; do
        models_list+=("$model")
        echo "  $index) ${model#* }"
        ((index++))
    done
done

# Step 2: Let the user select a model by number
echo -e "\nEnter the model number (or 0 to exit):"
read model_num
[[ $model_num -eq 0 ]] && exit 0

# Step 3: Get the selected IP and model
selected_entry="${models_list[$((model_num-1))]}"
selected_ip="${selected_entry%% *}"
selected_model="${selected_entry#* }"

# Step 4: Run the final curl command with the selected IP and model
curl http://$selected_ip:11434/api/generate -d "{\"model\": \"$selected_model\", \"keep_alive\": 0}"
echo

**Comment by Dement242** [comment]
Here is a script that will list all running models on the ip´s (edit the script and change to your ip-addresses) and unload the model you select.

```
#!/bin/bash

# Define the IP addresses
ips=("192.168.1.40" "192.168.1.42")

# Function to fetch models from a given IP address
fetch_models() {
    local ip=$1
    json_response=$(curl -s http://$ip:11434/api/ps)
    echo "$json_response" | jq -r --arg ip "$ip" '.models[] | "\($ip) \(.model)"'
}

# Step 1: Fetch models from all IP addresses and display as a numbered list
declare -a models_list
index=1
echo "Available models:"
for ip in "${ips[@]}"; do
    echo "Server $ip:"
    models=$(fetch_models $ip)
    IFS=$'\n' read -rd '' -a models_array <<< "$models"
    for model in "${models_array[@]}"; do
        models_list+=("$model")
        echo "  $index) ${model#* }"
        ((index++))
    done
done

# Step 2: Let the user select a model by number
echo -e "\nEnter the model number (or 0 to exit):"
read model_num
[[ $model_num -eq 0 ]] && exit 0

# Step 3: Get the selected IP and model
selected_entry="${models_list[$((model_num-1))]}"
selected_ip="${selected_entry%% *}"
selected_model="${selected_entry#* }"

# Step 4: Run the final curl command with the selected IP and model
curl http://$selected_ip:11434/api/generate -d "{\"model\": \"$selected_model\", \"keep_alive\": 0}"
echo
```

**Comment by MoreColors123** [comment]
i was battling with full VRAM while using ollama and FLUX simultaneously. here is a version for anyone looking for a solution for WINDOWS. it is written with chat gpt, so i don't know how, but it works. just adjust the IP which ollama is running on in the first line. Below i also included a .bat script to execute this .ps1

/// put this in a file called unload.ps1 
# Define the IP addresses
$ips = @("127.0.0.1")

# Function to fetch models from a given IP address
function Fetch-Models {
    param (
        [string]$ip
    )
    $json_response = Invoke-RestMethod -Uri "http://${ip}:11434/api/ps"
    $models = $json_response.models | ForEach-Object { 
        "$ip $($_.model)" 
    }
    return $models
}

# Step 1: Fetch models from all IP addresses and display as a numbered list
$models_list = @()
$index = 1
Write-Host "Available models:"
foreach ($ip in $ips) {
    Write-Host "Server ${ip}:"
    $models = Fetch-Models -ip $ip
    foreach ($model in $models) {
        $models_list += $model
        Write-Host "  $index) $($model -split ' ')[1]"
        $index++
    }
}

# Step 2: Let the user select a model by number
$model_num = Read-Host "`nEnter the model number (or 0 to exit):"
if ($model_num -eq 0) {
    exit
}

# Step 3: Get the selected IP and model
$selected_entry = $models_list[$model_num - 1].Trim()
$selected_ip = ($selected_entry -split ' ')[0].Trim()
$selected_model = ($selected_entry -split ' ')[1].Trim()

# Debug output
Write-Host "Selected IP: $selected_ip"
Write-Host "Selected Model: $selected_model"

# Step 4: Run the final Invoke-RestMethod command with the selected IP and model
$body = @{ model = $selected_model; keep_alive = 0 } | ConvertTo-Json
Invoke-RestMethod -Uri "http://${selected_ip}:11434/api/generate" -Method Post -Body $body -ContentType "application/json"
Write-Host "Model Unloaded"



/// put this in a .bat file:
@echo off
PowerShell -NoProfile -ExecutionPolicy Bypass -File "unload.ps1"
pause

-> double the click .bat file to choose the ollama model to unload

**Comment by astr0gator** [comment]
Here is a simple alias for most common use case of one-model-at-a-time in memory:
`alias ollama-unload='curl http://localhost:11434/api/generate -d "{\"model\": \"$(ollama ps | awk '\''NR==2 {print $1}'\'')\", \"keep_alive\": 0}"'`

Especially useful for cases where model is set to stay in memory forever.

**Comment by pdevine** [comment]
To unload a model, just use `ollama stop <model>`. To keep it in memory you can use `ollama run --keepalive -1s <model>`

**Comment by somera** [comment]
Instead of

> for ip in "${ips[@]}"; do
>     echo "Server $ip:"
>     models=$(fetch_models $ip)
>     IFS=$'\n' read -rd '' -a models_array <<< "$models"
>     for model in "${models_array[@]}"; do
>         models_list+=("$model")
>         echo "  $index) ${model#* }"
>         ((index++))
>     done
> done

it works for me with:

```
for ip in "${ips[@]}"; do
    echo "Server $ip:"
    models=$(fetch_models "$ip")

    # Read the models into an array
    mapfile -t models_array <<< "$models"

    for model in "${models_array[@]}"; do
        models_list+=("$model")
        echo "  $index) ${model#* }"
        ((index++))
    done
done
```

**Comment by dstadulis** [comment]
Offered is a solution which:
- Create JSON objects of the ollama ps lines of the models
- Selects name
- Passes these names as inputs to a gnu-parallel command
  - Which sets ollama's `keepalive` value to 0, effectively purging the model from memory

```zsh
# Unload all models listed by ollama ps -- by setting keepalive value to 0
parallel "ollama run --keepalive 0s {}" ::: $(ollama ps | awk '
  NR == 1 {
    split($0, headers)
  }
  NR > 1 {
    obj = "{"
    for (i=1; i<=NF; i++) {
      gsub(/[[:space:]]+$/, "", $i) # Trim trailing spaces
      if (i < NF) {
        obj = sprintf("%s\"%s\": \"%s\", ", obj, headers[i], $i)
      } else {
        obj = sprintf("%s\"%s\": \"%s\"}", obj, headers[i], $i)
      }
    }
    print obj
  }
' |   jq -r '.NAME')
```
