### ISSUE TITLE
[Feature Request] integrate PowerInfer as alternative to llama.cpp 

### ISSUE THREAD

**Issue by jenningsloy318** [ollama/ollama#1628]
Hello,
just found another inference engine https://github.com/SJTU-IPADS/PowerInfer, it seems has some advantages, but not tested, if ollama can integrate it ?

**Comment by EliMCosta** [comment]
Good! Could be a flag or somewhat. It's probably one of the biggest improvements in AI this year..

**Comment by mchiang0610** [comment]
Hey @jenningsloy318 and @EliMCosta thank you for brining this up. We are constantly evaluating new inference engines. That being said, the moment we start adding multiple ones, it'll require us to stay updated with it, and offer support for feature requests, performance improvements, security, etc. so we are very careful with our selection. 

Thank you!

**Comment by BradKML** [comment]
There is another inference tools like llamafile that are coming back to the spotlight, wondering how many other engines are out there that people would want to hop on for a speed up? (especially with CPU or portable hardware) https://github.com/ollama/ollama/issues/1404

P.S. Cross-reference from the past https://github.com/ollama/ollama/issues/1740
