### ISSUE TITLE
Only utilizing one thread - Unraid

### ISSUE THREAD

**Issue by evanrodgers** [ollama/ollama#1632]
Hi all,

Right now I am using Ollama 0.1.17 in an Unraid environment. The app works great, but it's only utilizing one thread. I did some light troubleshooting by adding the "num_thread" parameter to the modelfile as shown below, but it still only utilizes one thread. I've checked this by looking at the dashboard in Unraid and HTOP.

![Screenshot 2023-12-20 095344](https://github.com/jmorganca/ollama/assets/36175609/4b2451c4-26d5-4f52-b633-95cc0248fed8)

Modelfile:
```
# Modelfile generated by "ollama show"
# To build a new Modelfile based on this one, replace the FROM line with:
# FROM solar:10.7b-instruct-v1-q4_K_S

FROM /root/.ollama/models/blobs/sha256:034d7d28eda7c13de702e09978ffbc85d8fcc0ac173e5ecb4d0c626507fb25b6
TEMPLATE """### System:
{{ .System }}

### User:
{{ .Prompt }}

### Assistant:
"""
PARAMETER num_ctx 4096
PARAMETER num_thread 6
PARAMETER stop "</s>"
PARAMETER stop "### System:"
PARAMETER stop "### User:"
PARAMETER stop "### Assistant:"
```

Thanks everyone for all your great work!

**EDIT: I was able to fix this**, but to be honest I'm unclear what the solution was. I rebooted (always good), disabled SMT, disabled CSM, enabled 4G Decoding, enabled Resizable Bar. Sorry for the trouble!

**Comment by mchiang0610** [comment]
@evanrodgers thank you for sharing. Sorry about that. This should be fixed in subsequent versions. Please let us know if a regression ever happens. Again, sorry about this.
