### ISSUE TITLE
[Request] Reduce Gocyclo

### ISSUE THREAD

**Issue by H0llyW00dzZ** [ollama/ollama#1635]
![image](https://github.com/jmorganca/ollama/assets/17626300/21d4c771-a637-47e0-99ee-7d86f3ffcbc4)

not good for AI when it's too complex

**Comment by jmorganca** [comment]
Hi there! Thanks for the issue! Would it be possible to highlight specific errors/issues in the code that could be improved? That would really help! Also would love any PRs that keep functionality as-is but make it more simple :). Thank you for pointing out the complex ones (and that's a neat tool..)

**Comment by H0llyW00dzZ** [comment]
@jmorganca use this tool to detect which functions have high cyclomatic complexity:
https://github.com/fzipp/gocyclo

Also, note that writing code with high cyclomatic complexity (e.g., many if-else statements) makes it harder to write tests, even for functionality. It's better to write many if-else statements in tests instead of production code.
