### ISSUE TITLE
Update the Brew command

### ISSUE THREAD

**Issue by 3Samourai** [ollama/ollama#1638]
## When i try to install phi model:
```
ollama run phi
```

## I got this error
```
Error: llama runner: failed to load model '/Users/username/.ollama/models/blobs/sha256:bd608f9545597ea3278b78038943059d1c29c62f3ca02c86523014f3a8c7a7f1': 
this model may be incompatible with your version of Ollama. If you previously pulled this model, try updating it by running `ollama pull phi:latest`
```

**Comment by jmorganca** [comment]
Hi @3Samourai, are you on the latest version of Ollama (0.1.17) – that's required to run `phi`. Sorry it's not more obvious from that error message

**Comment by 3Samourai** [comment]
I just installed it now, so I think I am at the latest version.

**Comment by jmorganca** [comment]
Thanks! Which platform are you on? (e.g. Linux, macOS, GPU, etc)

**Comment by 3Samourai** [comment]
macOS 14.1.2, Macbook Pro M2 RAM 8GB

**Comment by jmorganca** [comment]
Would it be possible to check the logs in `~/.ollama/logs/server.log`, near the bottom for an error? Thanks so much!

**Comment by 3Samourai** [comment]
I checked and the file is empty 😢

**Comment by jmorganca** [comment]
Thanks! Did you happen to install Ollama via `brew`? Or is this via the Mac app?

**Comment by xiaoler** [comment]
> Thanks! Did you happen to install Ollama via `brew`? Or is this via the Mac app?

same issue, brew

**Comment by prantlf** [comment]
The same happened to me. Installed with `brew` yesterday.

    ❯ ollama --version
    ollama version is 0.0.0

I went for `orca-mini` instead of `phi`. It's not so much bigger and it worked :-)

**Comment by 3Samourai** [comment]
> Thanks! Did you happen to install Ollama via `brew`? Or is this via the Mac app?

I used brew

**Comment by igorschlum** [comment]
@jmorganca I checked it on my Mac. Trashed Ollama app installed from download and installed thru brew. But it's version 0.1.15 that is installed this version is not compatible with phi. How to make brew install the latest version on Mac?

Last login: Tue Dec 19 23:47:44 on ttys012
(base) igor@MacStudiodeIgor ~ % brew install ollama
Warning: ollama 0.1.15 is already installed and up-to-date.
To reinstall 0.1.15, run:
  brew reinstall ollama
(base) igor@MacStudiodeIgor ~ % brew reinstall ollama
==> Downloading https://ghcr.io/v2/homebrew/core/ollama/manifests/0.1.15
Already downloaded: /Users/igor/Library/Caches/Homebrew/downloads/eae5c2d48bc11495ba7e0d58865a1cac16068e74ecf85585a6535759aea2f9cb--ollama-0.1.15.bottle_manifest.json
==> Fetching ollama
==> Downloading https://ghcr.io/v2/homebrew/core/ollama/blobs/sha256:80ed768e91d
Already downloaded: /Users/igor/Library/Caches/Homebrew/downloads/030166de7fba913db2361506ec2a00d6071d74f40314e79c7097a8a45ebcb033--ollama--0.1.15.arm64_sonoma.bottle.tar.gz
==> Reinstalling ollama 
==> Pouring ollama--0.1.15.arm64_sonoma.bottle.tar.gz
==> Caveats
To start ollama now and restart at login:
  brew services start ollama
Or, if you don't want/need a background service you can just run:
  /opt/homebrew/opt/ollama/bin/ollama serve
==> Summary
🍺  /opt/homebrew/Cellar/ollama/0.1.15: 7 files, 15.8MB
==> Running `brew cleanup ollama`...
Disable this behaviour by setting HOMEBREW_NO_INSTALL_CLEANUP.
Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`).
(base) igor@MacStudiodeIgor ~ % brew services start ollama
==> Successfully started `ollama` (label: homebrew.mxcl.ollama)

**Comment by easp** [comment]
Someone has to update the brew formula for ollama and submit a pull request. It's not hard to do, but it needs to be done.

**Comment by igorschlum** [comment]
Here is a todo. I never done that before. I can try this week-end if nobody did it before:

Here are some steps to update the Brew formula for Ollama:

•  Fork the Homebrew tap repository where the Ollama formula is located. According to the Ollama websitehttps://ollama.ai/, the formula is hosted at [https://github.com/ollama/homebrew-ollama].

•  Clone your forked repository to your local machine and create a new branch for your changes.

•  Find the Ollama formula file in the repository. It should be named ollama.rb and located in the Formula folder.

•  Edit the formula file with a text editor or an IDE. You need to update the following fields in the formula file:

•  url: the URL of the source code archive of the latest version of Ollama. You can find it on the [Ollama releases page].

•  version: the version number of the latest version of Ollama. It should match the one in the url field.

•  sha256: the SHA-256 checksum of the source code archive. You can calculate it using the shasum -a 256 command on the downloaded archive file.

•  revision: the revision number of the formula. You need to increment it by one every time you update the formula.

•  Save the formula file and test it locally by running brew install --build-from-source ollama. This will install Ollama from the source code using your updated formula. Make sure there are no errors or warnings during the installation.

•  Commit your changes and push them to your forked repository. Then, create a pull request to the original Homebrew tap repository, following the [guidelines] and the [template] provided by Homebrew. Explain the reason and the details of your update, and wait for the review and approval from the Homebrew maintainers.

**Comment by igorschlum** [comment]
@3Samourai could you rename the issue in Update the Brew command?

**Comment by 3Samourai** [comment]
> @3Samourai could you rename the issue in Update the Brew command?

Done 👍

**Comment by xyproto** [comment]
@easp This PR lets the CI system automatically create PRs for homebrew when a new release is tagged: https://github.com/jmorganca/ollama/pull/709

**Comment by igorschlum** [comment]
@xyproto So we just have to wait the next release of Ollama (0.1.18) to have the brew install Ollama script updated?

**Comment by igorschlum** [comment]
after the release of Ollama 0.1.18 I tested brew install ollama

And the brew script is not updated for MacOS. It's version 0.1.15 that is installed and cannot run mixtral

Restored session: Sam  6 jan 2024 10:59:21 CET
(base) igor@MacStudiodeIgor-001 ~ % brew install ollama
==> Downloading https://formulae.brew.sh/api/formula.jws.json
######################################################################### 100.0%
==> Downloading https://formulae.brew.sh/api/cask.jws.json
######################################################################### 100.0%
Warning: Treating ollama as a formula. For the cask, use homebrew/cask/ollama
==> Downloading https://ghcr.io/v2/homebrew/core/ollama/manifests/0.1.15
Already downloaded: /Users/igor/Library/Caches/Homebrew/downloads/eae5c2d48bc11495ba7e0d58865a1cac16068e74ecf85585a6535759aea2f9cb--ollama-0.1.15.bottle_manifest.json
==> Fetching ollama
==> Downloading https://ghcr.io/v2/homebrew/core/ollama/blobs/sha256:80ed768e91d
Already downloaded: /Users/igor/Library/Caches/Homebrew/downloads/030166de7fba913db2361506ec2a00d6071d74f40314e79c7097a8a45ebcb033--ollama--0.1.15.arm64_sonoma.bottle.tar.gz
==> Pouring ollama--0.1.15.arm64_sonoma.bottle.tar.gz
==> Caveats
To restart ollama after an upgrade:
  brew services restart ollama
Or, if you don't want/need a background service you can just run:
  /opt/homebrew/opt/ollama/bin/ollama serve
==> Summary
🍺  /opt/homebrew/Cellar/ollama/0.1.15: 7 files, 15.8MB
==> Running `brew cleanup ollama`...
Disable this behaviour by setting HOMEBREW_NO_INSTALL_CLEANUP.
Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`).
(base) igor@MacStudiodeIgor-001 ~ % ollama --v
Error: unknown flag: --v
(base) igor@MacStudiodeIgor-001 ~ % ollama --version
ollama version is 0.0.0

(base) igor@MacStudiodeIgor-001 ~ % ollama run mixtral  
Error: llama runner: failed to load model '/Users/igor/.ollama/models/blobs/sha256:e9e56e8bb5f0fcd4860675e6837a8f6a94e659f5fa7dce6a1076279336320f2b': this model may be incompatible with your version of Ollama. If you previously pulled this model, try updating it by running `ollama pull mixtral:latest`
(base) igor@MacStudiodeIgor-001 ~ %

**Comment by xyproto** [comment]
`go build -ldflags="-X=github.com/jmorganca/ollama/version.Version=$pkgver"` might be needed to let `--version` return the correct version. Set `pkgver` to the correct version first.

**Comment by 3Samourai** [comment]
Tested and work fine
