### ISSUE TITLE
curl: (60) SSL Certificate Problem

### ISSUE THREAD

**Issue by kgene521** [ollama/ollama#1647]
curl https://ollama.ai/install.sh | sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                                   Dload   Upload   Total     Spent    Left   Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (60) SSL certificate problem: self-signed certificate in certificate chain
More details here: https://curl.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.

**Comment by pdevine** [comment]
@kgene521 I just tried this in both wsl2 and on macOS, and it's working fine. As @vtrenton mentioned, can you run `curl -V` and give some details about your platform? Also, this definitely could be a firewall problem.

**Comment by mxyng** [comment]
There's like a proxy between this server and ollama.ai which hasn't been configured for curl

**Comment by jmorganca** [comment]
As mentioned above, do you have a proxy? This could be causing an issue – `curl` supports the `HTTP_PROXY` and `HTTPS_PROXY` environment variables which should be helpful here. I'll close this for now but let me know if this issue is still occuring

**Comment by sundaram123krishnan** [comment]
Just add `--insecure` or `-k` args to suppress ssl errors

**Comment by souhilmohammedi2-cpu** [comment]
mouladia

**Comment by souhilmohammedi2-cpu** [comment]
na pvp

**Comment by yaswanthsai707-ops** [comment]
This website will be what taking about me then iam not understanding
