### ISSUE TITLE
Try to use only 1 GPU if possible

### ISSUE THREAD

**Issue by m0wer** [ollama/ollama#1656]
I have two GPUs: an RTX 3090 and a 2060. `ollama` tries to split the load among both, but due to communication speed between the cards being significantly slower than within a GPU, this is counterproductive. Would be great to prioritize using the first GPU only, if it alone has enough VRAM to fit the model.

Here are the results of a small experiment:

Model: `solar:q4_0`

- RTX 3090 alone:
  - 350 W: 81 t/s
  - 280W: 79 t/s
- RTX 3090 (280/350 W) and RTX 2060 (128/160 W):
  - 31.5 t/s

To do the test I just changed the value of `CUDA_VISIBLE_DEVICES`  from `0,1` to `0`.

**Comment by divinity76** [comment]
i think that's what
```
OLLAMA_SCHED_SPREAD=0 ollama serve
```
is for - i'm guessing OLLAMA_SCHED_SPREAD didn't exist yet when you created this issue
