### ISSUE TITLE
Ollama push fails on slower downloads with a 403

### ISSUE THREAD

**Issue by technovangelist** [ollama/ollama#1659]
I have a model I want to push but at only a 35Mbps upload speed (thanks Xfinity Gigabit), it takes about 25 minutes to upload. The problem is that when it takes longer than 20 minutes, it fails with this error: 

```
ollama push mattw/gpt4-x-alpaca:latest
retrieving manifest
pushing 6bccfcf77d21...  31% ▕█████████████████████████                                                         ▏ 2.3 GB/7.4 GB
Error: max retries exceeded: http status 403 Forbidden: <?xml version="1.0" encoding="UTF-8"?><Error><Code>ExpiredRequest</Code><Message>Request has expired</Message></Error>
```

What is especially interesting is that just a minute or two before that output I saw this: 

```
❯ ollama push mattw/gpt4-x-alpaca:latest
retrieving manifest
pushing 6bccfcf77d21...  81% ▕██████████████████████████████████████████████████████████████████                ▏ 6.0 GB/7.4 GB
```

I just happened to take a screenshot. Notice that the progress is further along, but a minute later it went back down to 31% from 81%.

And then on restarting the push, I have to start over.

here is a video of it happening. Skip to about 30 seconds in for the good part: https://cln.sh/Kgggx7lf

**Comment by SoloBSD** [comment]
Same issue with me, seems they need to tweak the time for the connection. I'm trying to upload a model too and it shows like 35-40 minutes to upload and then the connection is dropped.

```
> ollama push solobsd/nous-capybara-7b
retrieving manifest
pushing 08323667b50c...   1% ▕                ▏  32 MB/5.1 GB  2.5 MB/s  33m58s
Error: max retries exceeded: http status 403 Forbidden: <?xml version="1.0" encoding="UTF-8"?><Error><Code>ExpiredRequest</Code><Message>Request has expired</Message></Error>
```

**Comment by mxyng** [comment]
This should be fixed. We've adjusted the timing to account for slower connections
