### ISSUE TITLE
Error: timed out waiting for llama runner to start

### ISSUE THREAD

**Issue by LegendNava** [ollama/ollama#1678]
Was trying out dolphin-mixtral. Downloaded successfully but:

![Screenshot from 2023-12-23 00-57-15](https://github.com/jmorganca/ollama/assets/74506040/d796a0bb-15fc-4401-8c4f-7442502fd02c)

Does anything seem off? What should i do in this situation

I'm on Ubuntu 20.24, Intel i3 6th Gen.

**Comment by LegendNava** [comment]
> what does the server stdout say?

I don't exactly know what you mean; I'm kind of new to this and wanted to test some things out. Could you say what I should do to get those readings?

**Comment by LegendNava** [comment]
-Reopen

**Comment by LegendNava** [comment]
Thanks for the response; I tried what you said and heres the response: 

![Screenshot from 2023-12-24 20-02-13](https://github.com/jmorganca/ollama/assets/74506040/457f7bbf-96f0-4e46-bf9b-3344783ffe96)

It seems the "user" for that port is ollama itself; but it still dosent seem to work. I also can't kill the pid for some reason

**Comment by LegendNava** [comment]
![Screenshot from 2023-12-24 22-33-42](https://github.com/jmorganca/ollama/assets/74506040/14e439ac-36c1-4e57-8934-1ca8b9f791c2)

It seems ollama is automatically assigning itself a new PID every time...

**Comment by LegendNava** [comment]
Yess after typing `systemctl status ollama` it shows active (running)

![Screenshot from 2023-12-25 00-16-16](https://github.com/jmorganca/ollama/assets/74506040/7b34eb04-b28f-4cf4-bf67-f75ce7221664)

So now i stop the ollama using `sudo systemctl stop ollama` and type in `ollama serve` and restart from the beginning?
Thanks so much for the help!

**Comment by LegendNava** [comment]
Okay - i stopped ollama using `sudo systemctl stop ollama` and redid `ollama serve` but then this happened: Ill show the screenie's in order

![Screenshot from 2023-12-25 00-21-42](https://github.com/jmorganca/ollama/assets/74506040/07f63c72-4f3b-4b94-a6a8-5732f03fdc2d)

Immediately after running `ollama serve`, the reading upto the drivers not being found were printed. Then, when i ran dolphin-mixtral:

![Screenshot from 2023-12-25 00-21-56](https://github.com/jmorganca/ollama/assets/74506040/748dbfbb-e9b0-4e2c-b252-2b68fab148ce)

This happened, along with the logs after the nvidia driver ones being printed in the server.

**Comment by LegendNava** [comment]
Thanks! That worked hahaha it seems to be redownloading dolphin rn

**Comment by LegendNava** [comment]
Yeppp i realised my mistake and deleted that comment. Thanks so much!

**Comment by LegendNava** [comment]
Quick question- does the model redownload itself every time you run it?

**Comment by LegendNava** [comment]
Thank you! Quick question- does the model redownload itself every time you run it?

**Comment by LegendNava** [comment]
The same thing happened again :(

**Comment by dhiltgen** [comment]
@LegendNava if you're still seeing the problem, can you upgrade to the latest version (0.1.22) and share the server logs?

https://github.com/ollama/ollama/blob/main/docs/troubleshooting.md#how-to-troubleshoot-issues

**Comment by dhiltgen** [comment]
If you're still having problems after upgrading, please share your server log.
