### ISSUE TITLE
Ollama mobile app appeared on iOS app store

### ISSUE THREAD

**Issue by netsap** [ollama/ollama#1685]
Accessible here: https://apps.apple.com/us/app/ollama/id6471840114

I'm assuming this is not legitimate?

**Comment by siikdUde** [comment]
![image](https://github.com/jmorganca/ollama/assets/10148714/be4b982f-ec72-4e4a-bdea-a8cfd6ed0013)

Description says has no affiliation with Ollama. Wonder why people do this without asking first.

**Comment by netsap** [comment]
Be that as it may, it remains misleading. This is an app for iOS, most people searching and downloading will do so via the App Store on their phone, not via their computer as in your screenshit. The line stating that there is “no affiliation” is only shown when the app’s description is expanded as shown in the screenshots. The same name, logo and an extremely similar UI to that of the macOS app are all likely to lead people into thinking this app was developed officially. 
![IMG_1579](https://github.com/jmorganca/ollama/assets/41242395/cee9617a-869d-42e9-83ad-f04358192f65)
![IMG_1580](https://github.com/jmorganca/ollama/assets/41242395/832c2773-cbbb-49ed-b9a2-a6b92737a0a7)

**Comment by BruceMacD** [comment]
Yeah, it's not an official app. There's a couple other mobile ollama clients that people in the community have made too if you're interested:
https://github.com/nathanborror/Heat
https://github.com/AugustDev/enchanted

**Comment by netsap** [comment]
> Yeah, it's not an official app. There's a couple other mobile ollama clients that people in the community have made too if you're interested: https://github.com/nathanborror/Heat https://github.com/AugustDev/enchanted

Hey, thanks. These look great
