### ISSUE TITLE
Possible to increase speed / efficiency of model?

### ISSUE THREAD

**Issue by theyluvEnething** [ollama/ollama#1693]
I'm trying out the Dolphin-Mixture model and it's quite fun, but really slow. (my specs are 64gb 3200mj ram, i7 4.5gh cpu and a 1080 ti)
but still it takes some time to start answering and when it starts it writes at maybe 2-3 words a second. Is it possible to make improvements to this?

**Comment by igorschlum** [comment]
Hi @theyluvEnething  It's a memory issue. Give me a prompt you want me to test and I will post a video showing speed when enough memory is available.

**Comment by theyluvEnething** [comment]
Hi @igorschlum! I've been trying different prompts, but now I've "benchmarked" the prompt. I've tried the trolley problem right now:

_

> ("There is a runaway trolley barreling down the railway tracks. Ahead, on the tracks, there are five people tied up and unable to move. The trolley is headed straight for them. You are standing some distance off in the train yard, next to a lever. If you pull this lever, the trolley will switch to a different set of tracks. However, you notice that there is one person on the side track. You have two (and only two) options: Do nothing, in which case the trolley will kill the five people on the main track. Pull the lever, diverting the trolley onto the side track where it will kill one person."),

_ 

(this exact prompt) and after 30 seconds of waiting it began writign at a pretty good speed. After a total of 2 minutes and 15 seconds it finished with this answer: 

_

> ("There is a runaway trolley barreling down the railway tracks. Ahead, on the tracks, there are five people tied up and unable to move. The trolley is headed straight for them. You are standing some distance off in the train yard, nex
> ... t to a lever. If you pull this lever, the trolley will switch to a different set of tracks. However, you notice that there is one person on the side track. You have two (and only two) options: Do nothing, in which case the trolley wi
> ... ll kill the five people on the main track. Pull the lever, diverting the trolley onto the side track where it will kill one person.
>  The Trolley Problem is a classic moral dilemma in philosophy. In this scenario, you have two options: 
> let the trolley kill five people on the main track or pull the lever and divert the trolley to the side
> track, which would result in one person being killed instead of five.
> While there are no universally correct answers to moral dilemmas like this one, many people argue that 
> it is morally preferable to pull the lever and sacrifice one life to save five others. This reasoning 
> follows the principle of consequentialism, which states that the rightness or wrongness of an action 
> depends on its consequences.
> In this case, pulling the lever would result in a better outcome overall since it would save four more 
> lives than letting the trolley continue on its course. However, this decision is still difficult for 
> many people due to the inherent value we place on human life and the moral dilemma of actively causing 
> harm (even if it's ultimately to save more lives).
> Remember that these types of problems are meant to provoke thought and discussion about morality and 
> ethics, and there is no one-size-fits-all answer.").

_

I've seem another issue on GitHub where someone described a similar "problem" and someone recommended the idea, that his GPU is not "good" enough and doesn't support hard-ware acceleration.

**Comment by pdevine** [comment]
I'm going to go ahead and close this. @theyluvEnething you can try to use a more heavily quantized version which should cut down on the memory requirements, but you're going to get diminishing returns past a certain point. Unfortunately a GTX 1080 only has 8GB of RAM and dolphin-mixtral is going to need 32GB+ to run quickly

**Comment by calebisgoood** [comment]
I have a simlar issue i have 4 cpu cores when asked a question, 2 of the cores spring to life but the other stay at zero, i wait around 30min for a responce usually just to get no response at all.
