### ISSUE TITLE
generating embeddings with OllamaEmbeddings taking forever

### ISSUE THREAD

**Issue by lorenzoromani1983** [ollama/ollama#1705]
I am trying to generate embeddings with the OllamaEmbeddings class but it takes forever on a Mac M2 Pro

I am embedding 22000 posts from a forum's threads; this is my config:

        from langchain.embeddings import OllamaEmbeddings
        from llama_index.llms.ollama import Ollama

        llm = Ollama(model="llama2:13b")
        
        ...
        
        service_context = ServiceContext.from_defaults(
        
            llm=llm,
        
            embed_model=OllamaEmbeddings(model="llama2:13b"),
        )

With OpenAI it takes minutes.

**Comment by jmorganca** [comment]
Hi there, new smaller embedding models are now available such as https://ollama.com/library/nomic-embed-text - this should be much faster now, and work is being done for batch embeddings
