### ISSUE TITLE
Old cpu support

### ISSUE THREAD

**Issue by ThomasBenzshawel** [ollama/ollama#1715]
This is an issue very similar to #845. I was able to get this working on my machine by following the fix described here. However, this fix doesn't get you the latest version of ollama. Are there any plans to implement this fix throughout all versions?

**Comment by dhiltgen** [comment]
We've added CPU variants recently, which allow Ollama to run on CPUs without vector math extensions (AVX, AVX2) which should resolve this request.  There is still a corner case of #2187 which might impact you if you are trying to use a GPU in an environment without AVX.
