### ISSUE TITLE
Have response return minimized JSON (not formatted) to save token space

### ISSUE THREAD

**Issue by erf** [ollama/ollama#1720]
When i get JSON as a response it seem to be formatted with newlines and spaces. If i want to include the response message in follow-up request it will take up extra token space. Maybe better to have the client format the JSON as needed?

EDIT: I'm not really sure if i need to include the previous messages or if i should just set the `context` ?

**Comment by pdevine** [comment]
Going to go ahead and close the issue, but feel free to keep commenting.
