### ISSUE TITLE
 503 Server Error

### ISSUE THREAD

**Issue by gonnaK** [ollama/ollama#1724]
the ollama sever is running. When I try to use the api I get an error.
<img width="692" alt="image" src="https://github.com/jmorganca/ollama/assets/56569171/51251b5b-e206-4b6f-8cbb-41c9fbdb4dde">
<img width="790" alt="image" src="https://github.com/jmorganca/ollama/assets/56569171/ce2d9aea-2a82-419c-a37d-8fec5ca53f25">

**Comment by technovangelist** [comment]
Hi @gonnaK , thanks for submitting this issue. Just want to make sure you are on the same machine, correct? What happens if you make the same call using curl on the command line? This will help determine where the issue actually is.

**Comment by gonnaK** [comment]
> Hi @gonnaK , thanks for submitting this issue. Just want to make sure you are on the same machine, correct? What happens if you make the same call using curl on the command line? This will help determine where the issue actually is.

Yes，on the same machine. If i use curl on the command line,it will work normally.
<img width="1155" alt="image" src="https://github.com/jmorganca/ollama/assets/56569171/89c5a64a-89ed-4e7e-8b25-f6203ae57505">

**Comment by technovangelist** [comment]
That is interesting. What sdk are you using? I can take a closer look.

**Comment by gonnaK** [comment]
> That is interesting. What sdk are you using? I can take a closer look.

ollama version is 0.1.17
<img width="626" alt="image" src="https://github.com/jmorganca/ollama/assets/56569171/cd7e31a2-ccc6-4d39-9121-97625be46d21">

**Comment by BruceMacD** [comment]
It looks like this could be running in a Jupiter notebook, where are you making this call from (ex: Google Colab)?

**Comment by gonnaK** [comment]
> It looks like this could be running in a Jupiter notebook, where are you making this call from (ex: Google Colab)?

yes，I making this call from Jupiter notebook

**Comment by BruceMacD** [comment]
Im suspecting one of two possibilities here:
- Ensure that the Jupyter server is running on the same machine where you're trying to access localhost. If you're running Jupyter on a remote server but trying to access localhost, it won't work because localhost refers to the local machine where the browser is running, not the remote machine where Jupyter is hosted.
- If you're running Jupyter inside a virtual environment (like a Docker container or a virtual machine), localhost might not point to the host machine you expect. In this case, you might need to configure network settings to allow access to services running on the host machine.

**Comment by gonnaK** [comment]
> Im suspecting one of two possibilities here:
> 
> * Ensure that the Jupyter server is running on the same machine where you're trying to access localhost. If you're running Jupyter on a remote server but trying to access localhost, it won't work because localhost refers to the local machine where the browser is running, not the remote machine where Jupyter is hosted.
> * If you're running Jupyter inside a virtual environment (like a Docker container or a virtual machine), localhost might not point to the host machine you expect. In this case, you might need to configure network settings to allow access to services running on the host machine.

The Jupyter server is running on the same machine where you're trying to access localhost. I am not running Jupyter inside a virtual environment. I install Jupyter on my macos machine.

**Comment by jmorganca** [comment]
Given `curl` works, this could be something with the client library you are using. Would it be possible to try the Ollama Python library? https://github.com/ollama/ollama-python

Let me know if you're still encountering this issue

**Comment by yang0** [comment]
os: windows
curl: ok
llamaindex: httpx.HTTPStatusError: Server error '503 Service Unavailable' for url 'http://localhost:11434/api/chat'

## code
```
from llama_index.core import VectorStoreIndex, SimpleDirectoryReader, Settings
from llama_index.core.embeddings import resolve_embed_model
from llama_index.llms.ollama import Ollama
import logging
import sys

logging.basicConfig(stream=sys.stdout, level=logging.DEBUG)
logging.getLogger().addHandler(logging.StreamHandler(stream=sys.stdout))

documents = SimpleDirectoryReader("data").load_data()

# bge embedding model
Settings.embed_model = resolve_embed_model("local:shibing624/text2vec-base-chinese")

# ollama
Settings.llm = Ollama(model="wangshenzhi/llama3-8b-chinese-chat-ollama-q8", request_timeout=30.0)

index = VectorStoreIndex.from_documents(
    documents,
)

query_engine = index.as_query_engine()
response = query_engine.query("What did the author do growing up?")
print(response)
```

## error
```
 File "G:\devtools\anaconda3\envs\video_pool\lib\site-packages\httpx\_models.py", line 761, in raise_for_status
    raise HTTPStatusError(message, request=request, response=self)
httpx.HTTPStatusError: Server error '503 Service Unavailable' for url 'http://localhost:11434/api/chat'
For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/503
```
