### ISSUE TITLE
Add GPT--Pilot to ollama docs under libraries

### ISSUE THREAD

**Issue by oliverbob** [ollama/ollama#1726]
The repo is available [here](https://github.com/Pythagora-io/gpt-pilot/): which supports Ollama according to this wiki:

[GPT Pilot](https://github.com/Pythagora-io/gpt-pilot/wiki/Using-GPT%E2%80%90Pilot-with-Local-LLMs).

This will allow Ollama models to do full stack development for us.

**Comment by anetrebskii** [comment]
Does anybody know which model is better to use? It failed because GPT Pilot is targeted to GPT-4. So far, it works only with it.

**Comment by hqnicolas** [comment]
mixtral:8x7b 
26gb
you will need a RTX3090 or 4090 to make it work....
or Just run it with AVX2 cpu with 64gb RAM

**Comment by jmorganca** [comment]
Hi folks, thanks for the issue. Would it be possible to add this as a PR? Thanks!
