### ISSUE TITLE
💡 "ollama --verify" to validate a model

### ISSUE THREAD

**Issue by adriens** [ollama/ollama#1758]
# ❔ About

Sometimes, me may only need to validate than we can compile a model with `ollama`...without having to download the whole base model.

**👉 In  a few words, this would help telling, very fast and very easily is a `ollama` modelfile could be used. 👈** 

# 💡 Feature request

Implement `ollama --verify` which exits with success if:

- ✔️ the file is well formated
- ✔️ the base image exists

# 💰 Benefits

- **Make it possible to implement code validation with CI**... and then protect source code
- **Save resources (storage, CPU)** while trying to validate a `ollama` modelfile (especially on GH Actions)

# 🔖 Related stuff

- https://github.com/jmorganca/ollama/issues/1473

**Comment by pdevine** [comment]
I really like the idea of a linter... let's track this is #1843

**Comment by adriens** [comment]
:pray:  @pdevine for the feedback
