### ISSUE TITLE
Javascript package

### ISSUE THREAD

**Issue by mekb-turtle** [ollama/ollama#176]
Hey! Does a Node.js package exist to interact with models through ollama? I don't particularly want to run external commands to interact with it. Thanks

**Comment by erictoman** [comment]
It doesn't exists but you can create an interface.

**Comment by jmorganca** [comment]
Not an official one yet! That said there's a [REST API](https://github.com/jmorganca/ollama#rest-api) we'll be adding documentation for. More to come soon!

**Comment by jmorganca** [comment]
Closing as this is available now! https://github.com/ollama/ollama-js
