### ISSUE TITLE
Model kept unloading no matter what

### ISSUE THREAD

**Issue by TechScribe-Deaf** [ollama/ollama#1782]
Greeting, I have modified the ollama/server/routes.go to set the following variable:

```go
var defaultSessionDuration = 1440 * time.Minute
```

However when running the ollama, it kept unloading the **exact same** model over and over for every single API invocation for /api/generate endpoint and this is visible from nvtop CLI where I can observe the Host Memory climbing first and then GPU finally have the model loaded.

This makes Ollama very impractical for production environment when it takes significant amount of time to load the model for each and every API invocation. It should be noted that this is **NOT** running from docker as it is an intentional decision.

Is there an alternative recommendation to workaround this?

Please and thank you.

**Comment by TechScribe-Deaf** [comment]
Ok, I assume this is intended behavior.

**Comment by DaveMayfield** [comment]
I have the same experience, and the same concerns about performance. Is there a way to avoid the delay?

**Comment by pdevine** [comment]
@TechScribe-Deaf The behaviour right now is to unload after 5 minutes. That was really a compromise because some people want it to unload immediately, and others want it to never unload.

 I've been looking at making it so that you can specify how long you want it loaded for as part of the call to `/api/generate` or `/api/chat`. It takes a duration called `keep_alive` as a duration (e.g. 20m). If a different model is requested, it will unload it immediately and load in the other model.

**Comment by TechScribe-Deaf** [comment]
But what if we have sufficient VRAM to support multiple models on the same device? Do we need to spin up instances of Ollama separately?

I think realistically, there should be a full disablement of **ANY** unloading of the model as an option.

**Comment by pdevine** [comment]
@TechScribe-Deaf yeah, that's part of the problem. There are potentially a lot of corner cases, particularly around multiple models and scheduling.

**Comment by RSLLES** [comment]
I would appreciate having this feature as well. @pdevine, have you been able to implement it and submit a pull request? Thank you for your hard work.

**Comment by noahhaon** [comment]
> It takes a duration called keep_alive as a duration (e.g. 20m). If a different model is requested, it will unload it immediately and load in the other model.

@pdevine is this currently supported, and if so, is it documented? My use case is to use this with Continue (a co-pilot replacement for VSCode) and having the model unload regularly significantly impacts performance, as you may imagine. Ideally I could pass a flag to ollama serve to keep the model loaded indefinitely (unless another model is called, of course), but a similar parameter on the request would work as well.

**Comment by pdevine** [comment]
> @pdevine is this currently supported, and if so, is it documented? My use case is to use this with Continue (a co-pilot replacement for VSCode) and having the model unload regularly significantly impacts performance, as you may imagine. Ideally I could pass a flag to ollama serve to keep the model loaded indefinitely (unless another model is called, of course), but a similar parameter on the request would work as well.

It's just something I was tinkering around with. If it's useful we can get it in, but there are a lot of corner cases here so I want to make sure the UI is correct.

**Comment by TheBitmonkey** [comment]
@TechScribe-Deaf  "there should be a full disablement of ANY unloading of the model as an option." well just to prove @pdevine correct (a fellow Devine here), I came here to find the opposite. I very much need the ability to unload a model on command. I have limited vram and need to load up other (Stable Diffusion stuff), as a workaround I can just wait out the 5 minutes if I am not there, but that is not a great long term solution. 

An option to load a model indefinitely unless a "release model command" or "load new model command" is sent would be cool.

**Comment by mholtzhausen** [comment]
I'm using ollama primarily from an api. It should be simple to create an endpoint that will reset the timeout when called.  Same mechanism could be reused in the cli. For those of us that want a long-running session, we can cron a call to that endpoint.

**Comment by pdevine** [comment]
#2146 has merged, so I'm going to go ahead and close this. You'll be able to use it in `0.1.23`.
