### ISSUE TITLE
What is the smallest uncensored model you have that can write decent content?

### ISSUE THREAD

**Issue by bitcoinmeetups** [ollama/ollama#1803]
Hi,

I'm Lay, a very friendly guy.

What is the smallest uncensored model you have that can write decent (indecent) content? Preferably something similar to dolphin. I tried dolphin-mixtral but it takes hours on my server to write a story. I'd like a tiny one.

Also, please create a discussion group for ollama on Github.

**Comment by pdevine** [comment]
Mixtral is a huge model. The absolute smallest uncensored model that I can think of is [dolphin-phi](https://ollama.com/library/dolphin-phi). You can run it with:

`ollama run dolphin-phi`

For discussion groups, feel free to comment in the discord. There is also a pretty active number of people on [reddit](https://www.reddit.com/r/ollama/)

**Comment by ghost** [comment]
Hey guys Im student and i have made a aiassistant please give feed back so that i can improve it 
Link: https://omkareshwar18.free.nf/Assist.html
