### ISSUE TITLE
Code view on codellama vs phi and dolphin-phi

### ISSUE THREAD

**Issue by oliverbob** [ollama/ollama#1804]
Dolphin phi and (probably phi code indent):

![image](https://github.com/jmorganca/ollama/assets/23272429/6efbf418-0cbd-46bf-abf3-005db9e2fc3d)

![image](https://github.com/jmorganca/ollama/assets/23272429/5d0a658f-ffd8-44f2-b3f5-992b722d3c37)

Phi, indents but has no code view:

![image](https://github.com/jmorganca/ollama/assets/23272429/9cefc3b5-5bf5-4620-af2b-a9259c036c94)

Can someone probably do something to improve these models as they are the only models that run very fast on smaller GPUs.

Or perhaps, maybe someone would train phi-code:instruct.

Thanks.

**Comment by jukofyork** [comment]
You can try appending this to the SYSTEM message in the modelfile:

When providing code examples always use Markdown: use ``` to wrap code blocks and use ` to denote a word or phrase as code.

This is what I have been using for a couple of the models I have and it seems to work.

**Comment by pdevine** [comment]
As @jukofyork mentioned, with the smaller models you definitely need to prompt them more to tell it what you're expecting. I'm going to go ahead and close out the issue.
