### ISSUE TITLE
Failed to add ollama cli to PATH during install

### ISSUE THREAD

**Issue by vjpr** [ollama/ollama#1851]
How does ollama add to macos PATH?

The install didn't work for me. Where does it modify the PATH?

**Comment by igorschlum** [comment]
Hi @vjpr when you download ollama app from the homepage of ollama.ia, you move the app to your app folder, double click on it and in the terminal, you can type 
‘‘‘
Ollama run llama2
‘‘‘
Can you give more explanation of what is missing to run.

**Comment by pdevine** [comment]
@vjpr How did you install ollama?

**Comment by vjpr** [comment]
I installed using downloaded app on macOS.

It asks if I want to add to terminal and I click yes. But I don't see where it was installed to.

**Comment by pdevine** [comment]
It should be in `/Applications/Ollama.app/Contents/Resources/ollama` and there should be a symlink to it from `/usr/local/bin/ollama`. You should check that `/usr/local/bin` is in your PATH.

**Comment by igorschlum** [comment]
Hi @ianschmitz are you on MacOS? If you create a new user in your computer, car you reproduce the issue?

**Comment by pdevine** [comment]
@ianschmitz @vjpr did either of you by chance not have brew installed on your system? For whatever reason I already had `/usr/local/bin/` in the PATH in my `.zshrc` file, and now I'm wondering how it got there.

**Comment by dhiltgen** [comment]
On a fresh MacOS v12 system (the oldest I have around) `/usr/local/bin` appears to be in the default users path, so I don't think it's a flawed assumption to install there by default.

@vjpr if you're still having problems, can you share what your shell is, and if you've modified your dot file(s) to alter the default PATH?
