### ISSUE TITLE
 I miss option to specify num of gpu layers as model parameter

### ISSUE THREAD

**Issue by JoseConseco** [ollama/ollama#1855]
The 2 most used parameters for gguf models are IMO: temp, and number of gpu layers for mode to use.
But  number of gpu layers is  'baked' into ollama model template file.
This means we have to  create new model, with new num of gpu layer - jut to change it.

yes I understand number of gpu layers is not something that can be changed after  model was loaded.  But still, creating new modelfile just to change gpu layer offloading parameter is overkill imo.

**Comment by BruceMacD** [comment]
Thanks for the feedback @JoseConseco, as of the last few versions of Ollama you can actually specify this in the interactive mode.
```
ollama run llama2
>>> /set parameter num_gpu 12
Set parameter 'num_gpu' to '12'

>>>
```

Does that help your use-case?

**Comment by JoseConseco** [comment]
awesome. It was one of the most annoying thing about ollama (having to create  custom model, to change gpu layers. ) 
While  `/set parameter num_gpu 12` works -  model is reloaded after next prompt, after setting gpu-layes. 
Will have to test if this helps, if model is to big to load into vram. I suppose in that case ollama will just error out, and I wont be able to `/set parameter num_gpu 12` right? In that case user will have to create new modelfile...
Is that similar option to  set gpu-layer from the begining  -   like :  ollama run model.xyz   -gpu-layer n  ?

**Comment by BruceMacD** [comment]
@JoseConseco setting it as a flag isn't an option right now, however this is a lot of work going on right now to load the optimal number of layers by default when a model is run.

**Comment by yangmingming** [comment]
We can set the value of num_gpu through the following parameters. I didn't find how to get the current value? And what indicators can be referenced for setting this value?
```
/set parameter num_gpu
```

**Comment by dhiltgen** [comment]
Ultimately the goal is users shouldn't have to adjust the num_gpu setting, and Ollama should load the optimal number of layers given the available VRAM.  If there are bugs that cause us to load an incorrect number of layers, this setting can be used to workaround those bugs until we get them fixed.  The setting can be specified via CLI, API, or within the Modelfile.  I'm also planning to add another mechanism to workaround memory prediction bugs in #5922
