### ISSUE TITLE
Awq mod support/awq-gguf 

### ISSUE THREAD

**Issue by sviknesh97** [ollama/ollama#1862]
Does ollama support awq formats instead of gguf the gguf inference seems to be alittle slow hence thinking about awq and if it doesnt support is there a way to convert awq to gguf

**Comment by easp** [comment]
It doesn't support awq. I kind of doubt that there is a good way to convert from awq to gguf. Do you not have access to the unquantized model?

**Comment by sviknesh97** [comment]
Thanks Eric,

I can use the unquantized model but i was just wondering if it was possible.

**Comment by jmorganca** [comment]
Hi @sviknesh97 thanks for the issue. In this case would it be possible to open an issue with the performance improvements or feature sets AWQ brings? That way we can focus on improving those parts of Ollama :)
