### ISSUE TITLE
Error when install on Ubuntu 22.04

### ISSUE THREAD

**Issue by dekogroup** [ollama/ollama#1872]
curl https://ollama.ai/install.sh | sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  8354    0  8354    0     0  16163      0 --:--:-- --:--:-- --:--:-- 16189
>>> Downloading ollama...
######################################################################## 100.0%##O=#  #         Warning: Failed to open the file /tmp/tmp.AO1TPHxNpB/ollama: No such file or  
Warning: directory
                                                                           0.0%curl: (23) Failure writing output to destination

**Comment by nineamigos** [comment]
I get the same error. I looked online and I haven't seen a solution.  Note I am using Ubuntu on Windows through Hyper V. If anyone has found a solution please posted here. Thank you:
$ curl https://ollama.ai/install.sh | sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0>>> Downloading ollama...
100  8354    0  8354    0     0   6280      0 --:--:--  0:00:01 --:--:--  6276
######################################################################## 100.0%#Warning: Failed to open the file /tmp/tmp.s69jd7DPS4/ollama: No such file or  
Warning: directory
                                                                           0.0%curl: (23) Failure writing output to destination

**Comment by shubhambane** [comment]
same issue faced here, i am using ubuntu 23.10 rn

**Comment by shubhambane** [comment]
It has to do with Curl, I had the same issue. Please try the following and it fixed the problem.
$ sudo snap remove curl
$ sudo apt install curl

**Comment by shubhambane** [comment]
> curl https://ollama.ai/install.sh | sh % Total % Received % Xferd Average Speed Time Time Time Current Dload Upload Total Spent Left Speed 100 8354 0 8354 0 0 16163 0 --:--:-- --:--:-- --:--:-- 16189
> 
> > > > Downloading ollama...
> > > > ######################################################################## 100.0%##O=#  #         Warning: Failed to open the file /tmp/tmp.AO1TPHxNpB/ollama: No such file or
> > > > Warning: directory
> > > > 0.0%curl: (23) Failure writing output to destination

It has to do with Curl, I had the same issue. Please try the following and it fixed the problem.
$ sudo snap remove curl
$ sudo apt install curl

**Comment by shubhambane** [comment]
> curl https://ollama.ai/install.sh | sh % Total % Received % Xferd Average Speed Time Time Time Current Dload Upload Total Spent Left Speed 100 8354 0 8354 0 0 16163 0 --:--:-- --:--:-- --:--:-- 16189
> 
> > > > Downloading ollama...
> > > > ######################################################################## 100.0%##O=#  #         Warning: Failed to open the file /tmp/tmp.AO1TPHxNpB/ollama: No such file or
> > > > Warning: directory
> > > > 0.0%curl: (23) Failure writing output to destination

The issue is related to Curl; I encountered the same problem. Please try the following steps, and it should resolve the issue:

$sudo snap remove curl
$sudo apt install curl

**Comment by shubhambane** [comment]
> I get the same error. I looked online and I haven't seen a solution. Note I am using Ubuntu on Windows through Hyper V. If anyone has found a solution please posted here. Thank you: $ curl https://ollama.ai/install.sh | sh % Total % Received % Xferd Average Speed Time Time Time Current Dload Upload Total Spent Left Speed 0 0 0 0 0 0 0 0 --:--:-- --:--:-- --:--:-- 0>>> Downloading ollama... 100 8354 0 8354 0 0 6280 0 --:--:-- 0:00:01 --:--:-- 6276 ######################################################################## 100.0%#Warning: Failed to open the file /tmp/tmp.s69jd7DPS4/ollama: No such file or Warning: directory 0.0%curl: (23) Failure writing output to destination

The issue is related to Curl; I encountered the same problem. Please try the following steps, and it should resolve the issue:

$sudo snap remove curl
$sudo apt install curl

**Comment by dhiltgen** [comment]
@dekogroup are you still facing install problems?  If you're on windows, you can use the native windows install instead of installing in WSL2.

**Comment by dekogroup** [comment]
Thank You. On Wondows with WSL2 it's working fine.
