### ISSUE TITLE
Only generate lots of hashes 

### ISSUE THREAD

**Issue by ZhihaoZhang97** [ollama/ollama#1881]
![Screenshot from 2024-01-10 11-52-07](https://github.com/jmorganca/ollama/assets/31653817/30f08c0d-c924-471f-b740-896ba804c2bf)

Not sure if I am the first to encounter with this issue, when I installed the ollama and run the llama2 from the Quickstart, it only outputs a lots of '####'. 

I suspect that might be caused by the hardware or software settings with my newly updated system?

Since it works with my old rig with i9-9900K and dual RTX 3090.

As shown in the screenshot below, I am currently using Pop!OS with AMD Threadripper 3960X and dual RTX 3090.
![Screenshot from 2024-01-10 11-52-54](https://github.com/jmorganca/ollama/assets/31653817/ebc410c8-d635-4d7c-9d31-9115d67b1516)

Any help would be greatly appreciated, thank you!

**Comment by lasseedfast** [comment]
Before there has been a workaround for this, but the problem seems to be back again. Here are some more info https://github.com/jmorganca/ollama/pull/1261#issuecomment-1881823438

**Comment by elven2016** [comment]
the same error too, have you found the solution?

**Comment by lasseedfast** [comment]
My solution has become to downgrade to .17

```curl https://ollama.ai/install.sh | sed 's#https://ollama.ai/download#https://github.com/jmorganca/ollama/releases/download/v0.1.17#' | sh.```

**Comment by ZhihaoZhang97** [comment]
It seems downgrade the Nvidia Driver back to 535.x.x can also resolve the problem with the latest ollama.

**Comment by lasseedfast** [comment]
Thanks. If you know some up to date instructions on how to downgrade please share, I've not found any easy enough for me to follow.

**Comment by pdevine** [comment]
Sorry guys, can you try again w/ `0.1.22` and make sure you the model you're trying to use.

**Comment by ZhihaoZhang97** [comment]
Thanks @pdevine can confirm the `0.1.22` version fix the bug with the latest Nvidia 545 driver! Nice work! 
![Screenshot from 2024-01-27 13-45-13](https://github.com/ollama/ollama/assets/31653817/6dfa17d8-430c-4243-bb87-a435af7237e1)
