### ISSUE TITLE
Embedding generation is slow 

### ISSUE THREAD

**Issue by jmorganca** [ollama/ollama#1882]
When using `/api/embeddings`, large documents can take up to second

**Comment by iamashwin99** [comment]
I have the same issue, I am not limited by the CPU or the memory. Not sure what the issue is.

**Comment by BruceMacD** [comment]
@jmorganca can this be resolved now that bert models are supported? Moving forward generating embeddings bert models should be used rather than llama-family models.

**Comment by jmorganca** [comment]
Closing as `bert` models are now supported such as https://ollama.com/library/all-minilm
