### ISSUE TITLE
Llama Guard models

### ISSUE THREAD

**Issue by kylemclaren** [ollama/ollama#1894]
https://huggingface.co/meta-llama/LlamaGuard-7b

**Comment by jmorganca** [comment]
Latest is Llama Guard 3: https://llama.meta.com/docs/model-cards-and-prompt-formats/llama-guard-3/

**Comment by gss214** [comment]
Hello,

I am trying to use the [Llama Prompt Guard](https://huggingface.co/meta-llama/Prompt-Guard-86M) with Ollama. However, when I attempt to create the model using the ollama create command, I encounter the following error:

```
Error: unsupported architecture
```

Could you please provide guidance on how to resolve this issue or add support for this model in Ollama?

Thank you for your assistance!

**Comment by tituslhy** [comment]
Bumping this request up. Would be great to have a llama guard 3 in Ollama!

**Comment by dhiltgen** [comment]
Llama Guard is now available: https://ollama.com/library/llama-guard3

**Comment by Aunali321** [comment]
@dhiltgen Are there any plans to support llama guard 3 11b vision? it's the only safety model with multi-modality. Since ollama already added llama 3.2 11b vision, it should hopefully be much simpler
