### ISSUE TITLE
set parameter stop in repl removes other stop words

### ISSUE THREAD

**Issue by technovangelist** [ollama/ollama#1900]
if i am in the repl and I type `/set parameter stop <|system>` all other stop words are removed. I just wanted to add one.

**Comment by BruceMacD** [comment]
Hey Matt! The other `/set` commands are "replace" behaviour rather than append so I think this may be the expected behaviour for now. Leaving this open as a possible enhancement.

**Comment by pdevine** [comment]
Yeah, it's not ideal, but I couldn't think of a way around this. How would you remove a different parameter otherwise?

**Comment by jmorganca** [comment]
Will close this for now
