### ISSUE TITLE
Will Magicoder-S-DS-6.7B ever come back?

### ISSUE THREAD

**Issue by reaperkrew** [ollama/ollama#1912]
Hi Everyone,

I've heard a lot of good things about Magicoder-S-DS-6.7B. From browsing through some previously closed threads in this repository, it looks like at some point in early December of 2023 Magicoder-S-DS-6.7B was available. Does anyone know if it will come back?

Thanks

**Comment by j2l** [comment]
I'd also love it!
It is beating local 46B models (and GPT3.5turbo, 170B) on python and JS code generation: https://huggingface.co/spaces/mike-ravkine/can-ai-code-results
(and I can't run 13B models locally :smile_cat: )

https://huggingface.co/TheBloke/Magicoder-S-DS-6.7B-GGUF
The GGUF model should state that ollama can run it

Please `ollama run magicoder:7b-s-ds`

**Comment by jmorganca** [comment]
Hey folks, will close this given the age – however you can import GGUF files to Ollama by following: https://github.com/ollama/ollama/blob/main/docs/import.md
