### ISSUE TITLE
choosing the right model to interact

### ISSUE THREAD

**Issue by umtksa** [ollama/ollama#1923]
I can use a custom mistral modelfile to choose which model is the best choice based on the subject. 
like in my model file "choose" all models have descriptions like copywriter model or weather model
based on the subject mistral can choose the best model and gives me the command to run
so I can run it through the model I want.

This is working as expected but I'm a noob and I'm not sure this is the best way to do this.
basically I run
`ollama run choose "weather is 16 degrees outside"`
and it gives me
`ollama run weather "weather is 16 degrees outside"`
so is using mistral overkill for this purpose? I tried the same modelfile with other models without success like tinyllama. 
mistral is the best one I come up for this subject.
So any suggestions? (tried regex without success before this)
this issue can have a label as question or this could be a feature request.
[cross posting to reddit](https://www.reddit.com/r/ollama/comments/193xvzm/choosing_the_right_model_to_interact/)

**Comment by pdevine** [comment]
This is a great question, and sorry for the slow response. I hadn't really though about how to do this, but the suggestions in the reddit thread are great. I would definitely recommend checking out `phi` to use a smaller model, and I would also "prompt engineer" the model to give it some good suggestions about the responses that you're expecting.

I'm going to go ahead and close the issue, but feel free to keep commenting.
