### ISSUE TITLE
armv7 support

### ISSUE THREAD

**Issue by mauryaarun** [ollama/ollama#1926]
I am unable to compile ollama on armv7 cpu android tv using termux. While i compiled it successfully on a smartphone using termux. 
some error when compiling in the file ggml.c in llama.
[error.log](https://github.com/jmorganca/ollama/files/13905716/error.log)

**Comment by jmorganca** [comment]
Hi @mauryaarun, sorry you hit an error. Armv7 isn't yet supported by Ollama, however over time the goal is to support more platforms – thanks so much for creating an issue!

**Comment by dhiltgen** [comment]
It's probably worth giving it another try on the new Go server build.

https://github.com/ollama/ollama/blob/main/docs/development.md#transition-to-go-runner

**Comment by dhiltgen** [comment]
If you still can't get it to build, let us know and I'll reopen.
