### ISSUE TITLE
Prevent offloding

### ISSUE THREAD

**Issue by Hansson0728** [ollama/ollama#1928]
The model offloads after 5 min on the api, it would be nice to be able to prevent this

**Comment by Hansson0728** [comment]
maybe add options for startup paramaters for llama cpp example prevent model from unloading from memory and stuff like that

**Comment by jimscard** [comment]
What is the use case for this? Is it causing a problem? Preventing offloading seems to me to be not an optimal solution, as it could easily cause resource starvation and enable denial of service attacks.  So, I recommend that the model timeout value be configurable, but with a reasonable maximum, something on the order of 15-30 minutes.

**Comment by BananaAcid** [comment]
Reasons:

1. only ever use 1 model, prevent startup lag by not needing to load a LLM after 5min again.
2. huge LLMs loading to multiple GPUs takes time, inference is fast. If only 1 model is used, the initial delay is enormous. (if GPUs are connected using USB like in mining racks.

**Comment by BananaAcid** [comment]
Why does it (have to?) offload automatically?

**Comment by Hansson0728** [comment]
> What is the use case for this? Is it causing a problem? Preventing offloading seems to me to be not an optimal solution, as it could easily cause resource starvation and enable denial of service attacks.  So, I recommend that the model timeout value be configurable, but with a reasonable maximum, something on the order of 15-30 minutes. 

To prevent starving resources or dos we could set an upper limit on resource and force reload when reached and log it carefully so we could trim it for a good fit..

While on the topic a health endpoint that shows memory usage, time loaded, statis ( loading, idle, processing ) would be nice top :)

**Comment by pdevine** [comment]
Going to close this since #2146 has merged. You will be able to set it in `0.1.23`.
