### ISSUE TITLE
WARNING: No NVIDIA GPU detected. Ollama will run in CPU-only mode.

### ISSUE THREAD

**Issue by xzkxzk12301230** [ollama/ollama#1929]
i use wsl2，and GPU information is as follows. when i install ollama,it WARNING: No NVIDIA GPU detected. Ollama will run in CPU-only mode.
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 546.33                 Driver Version: 546.33       CUDA Version: 12.3     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                     TCC/WDDM  | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce RTX 4060 Ti   WDDM  | 00000000:03:00.0  On |                  N/A |
|  0%   29C    P8               7W / 180W |    581MiB / 16380MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+

**Comment by dcasota** [comment]
TCC-mode might be the issue. 

![image](https://github.com/jmorganca/ollama/assets/14890243/48064aac-4977-4e88-9556-4e6432f9502f)


I use this driver:
https://de.download.nvidia.com/Windows/546.33/546.33-notebook-win10-win11-64bit-international-nsd-dch-whql.exe

![image](https://github.com/jmorganca/ollama/assets/14890243/04549783-7110-429b-882a-3ee7745ab495)

**Comment by clianor** [comment]
I tried to use ollama as wsl2 but I had the same problem.
So I ran the olama with docker and it worked well.
Here's the official ollama article for your reference.
https://ollama.ai/blog/ollama-is-now-available-as-an-official-docker-image

**Comment by dhiltgen** [comment]
@xzkxzk12301230 if you're still facing this problem, can you share the server log?  It may also be helpful to run with `OLLAMA_DEBUG=1` set to increase the verbosity of the logs.

https://github.com/ollama/ollama/blob/main/docs/troubleshooting.md#how-to-troubleshoot-issues
