### ISSUE TITLE
Donation

### ISSUE THREAD

**Issue by reddec** [ollama/ollama#1945]
Hi there!

I really, REALLY love the product. Ollama made LLM usage as simple as docker years ago did for containers.

Maybe it's time for donation button? Can't promise much, but at least I can show my appreciation.

**Comment by mchiang0610** [comment]
Thank you for your kind words @reddec! I'm sure all of the maintainers and contributors appreciate this kind gesture. The biggest need for all of us right now is to help this open-source community grow and share more about Ollama! 

We would all deeply appreciate that. 

Thank you!!!!
