### ISSUE TITLE
`SIGSEGV: segmentation violation` when shutting down server with ctrl+c

### ISSUE THREAD

**Issue by jmorganca** [ollama/ollama#1946]
```
[GIN] 2024/01/12 - 12:38:39 | 200 |  5.985573917s |       127.0.0.1 | POST     "/api/chat"
2024/01/12 12:38:52 ext_server_common.go:158: loaded 0 images
^Cggml_metal_free: deallocating
SIGSEGV: segmentation violation
```

**Comment by dcasota** [comment]
As a volunteer feedback on this - after ollama-0.1.20, ext_server_common.go isn't part of the repo anymore, right? On an ollama [make build](https://github.com/jmorganca/ollama/files/13918586/build_output.txt) with latest source I haven't seen a segmentation violation.

Btw. multiple llm servers using the same application instance would be on top of gpu driver capability. There are multi-instance gpu limitations, e.g. for nvidia in terms of driver mode (wddm/tcc) and its availability per gpu card. A baremetal prerequirement cascade might look like [cuda-capable gpu + baremetal, os version, cuda driver type and version, gcc version + correct development packages, application].

**Comment by dhiltgen** [comment]
Pretty sure this has been resolved via llama.cpp bumps or other fixes we've done since early Jan.  I get a clean shutdown on mac with the latest code.
