### ISSUE TITLE
config for the server to change the location of the models

### ISSUE THREAD

**Issue by aemonge** [ollama/ollama#1953]
Can we have a /etc/ollama.json  file to change the default path for the models?

**Comment by oliverbob** [comment]
This could be useful for migration scenarios.

**Comment by pdevine** [comment]
@aemonge you can change this right now with the `OLLAMA_MODELS` env variable. What platform are you using?

**Comment by aemonge** [comment]
I'm using arch linux.

I know, I can change individual MODEL settings, but would be nice to have a global config

**Comment by easp** [comment]
@aemonge the OLLAMA_MODELS environment variable isn't a per-model setting. It's global.
https://github.com/ollama/ollama/blob/main/docs/faq.md#how-do-i-set-them-to-a-different-location

**Comment by oliverbob** [comment]
But what if we not only choose the location of the model but "migrate" the entire model entries? Docs for permissions, rsync or whatever should be included, because by nature, "ollama" is "bound" to scale.

**Comment by aemonge** [comment]
Thanks for the clarification @easp
