### ISSUE TITLE
Handle Multiple parallel request

### ISSUE THREAD

**Issue by lauvindra** [ollama/ollama#1956]
Does Ollama uses some kind of scheduling algorithm to manage high concurrent request? can you explain this

**Comment by easp** [comment]
It queues the requests and processes them serially.

**Comment by pdevine** [comment]
We'll add in better support for scheduling in the future, but as @easp mentioned, it just blocks all the other clients on a request and then those clients race to get fulfilled next. Definitely not ideal.

**Comment by pdevine** [comment]
Going to close this as a dupe of #358
