### ISSUE TITLE
Make update script skip execution if current version is latest (improvement)

### ISSUE THREAD

**Issue by atassis** [ollama/ollama#1980]
You can put a `version` file in the root of download directory and check if current installed ollama has an identical version, for example.

**Comment by dhiltgen** [comment]
I've seen some users wind up with a corrupt install, and re-running the install with the same version can clear that up.  At this time, I don't think it makes sense to bypass installing if the version is unchanged.

What I would suggest is if you are trying to automate/script a system and prevent no-op upgrades, use something like `curl -i https://ollama.com/download/ollama-linux-amd64` and check the redirect location for the version string, and compare that against `ollama --version`
