### ISSUE TITLE
ggml-cuda.cu:7850: !"CUDA error" Aborted (core dumped) with 8 GPUs

### ISSUE THREAD

**Issue by quanpinjie** [ollama/ollama#1998]
![image](https://github.com/jmorganca/ollama/assets/2564119/d7deb42c-cbb7-4426-90f6-1cee8b9badf8)

Error: Post "http://127.0.0.1:11434/api/generate": EOF

GPU INFO:

![Uploading image.png…]()

**Comment by dhiltgen** [comment]
@quanpinjie can you share the server log?

**Comment by dhiltgen** [comment]
If you're still facing the problem, please share the server log.
