### ISSUE TITLE
Issue with Ollama on Ubuntu 22.04 under VirtualBox 7 Windows 11

### ISSUE THREAD

**Issue by dekogroup** [ollama/ollama#2000]
On this platform, Ollama was installed successfully but got following error when running:

ollama run codellama:7b-instruct

Illegal instruction (core dumped)

**Comment by Rushmore75** [comment]
Getting same result, on any command

**Comment by Rushmore75** [comment]
@dekogroup try building from source and bumping up the version of the mimetype depdendancy

**Comment by dekogroup** [comment]
Thank you @Rushmore75 . Will try.

**Comment by dhiltgen** [comment]
@dekogroup my suspicion is you have VirtualBox configured to mask CPU features like AVX and AVX2.  In older builds, we'd crash with illegal instruction.  We have recently added support for running on CPUs without these vector math extensions, but if you can update your VirtualBox configuration, I'd recommend that as it will result in better performance if we have to do any inference on the CPU.

**Comment by orlyandico** [comment]
Not an exact answer, but Ollama works great on WSL2 with Ubuntu 22.04 on Windows 11. That's HyperV underneath.

**Comment by dhiltgen** [comment]
Recent builds will no longer crash, but will not execute on the GPU due to lacking AVX support.  Potentially adding non-AVX support to the GPU builds is tracked via issue #2187
