### ISSUE TITLE
[feature request] ollama website API? or maybe docs for it...

### ISSUE THREAD

**Issue by AlizerUncaged** [ollama/ollama#2001]
is it possible we have a way of fetching/searching models list from the official ollama website? so that other programs can integrate into it as well? if it already exists, maybe a small docs about it.

**Comment by pdevine** [comment]
We'll definitely publish something. The API is still under pretty active development, so we didn't want to publish it, have people rely on it, and then change it and break everything.

**Comment by adriens** [comment]
- https://github.com/jmorganca/ollama/issues/1473

**Comment by jmorganca** [comment]
Closing for https://github.com/ollama/ollama/issues/1070 thanks for the issue!
