### ISSUE TITLE
Import pytorch adapter `.bin` files

### ISSUE THREAD

**Issue by PhilipAmadasun** [ollama/ollama#2009]
Has anyone on here successfully created a fine-tuned mistral model with: 

```
curl http://server.local:11434/api/create -d '{
  "name": "test_mistral",
  "modelfile": "FROM mistral\nADAPTER /home/robot/adapter_model.bin"
}' 
```
Apparently .bin files aren't in pytorch format so it doesn't work does anyone actually use this method or just straight up export a gguf?

**Comment by easp** [comment]
One thing you need to do is create the model properly. FROM should be the sha256 digest of the blob you uploaded with the adapter weights. Check the API docs.

**Comment by pdevine** [comment]
I know this is an older issue, but let's track this in #4618. I do have adapters working w/ NPZ files created w/ MLX (#5524).
