### ISSUE TITLE
Parameters loaded from Modelfile are cast to int in /show parameters

### ISSUE THREAD

**Issue by nathanpbell** [ollama/ollama#2011]
It appears if I set float value parameters in the Modelfile, when I run that model and run `/show parameters` those floats get cast to ints.

### Steps to reproduce

Create a Modelfile:
```
FROM mistral:text
PARAMETER num_ctx 32000
PARAMETER seed 42
PARAMETER num_predict 128
PARAMETER temperature 0.7
PARAMETER top_p 0.9
```

Create the model:

```
ollama create mymodel -f Modelfile
```

Run the model:
```
ollama run mymodel
```

Ask for the parameters:
```
>>> /show parameters
Model defined parameters:
seed                           42
temperature                    1
top_p                          1
num_ctx                        32000
num_predict                    128
```

You'll see that "top_p" and "temperature" have been rounded to integer value `1`.

**Comment by pdevine** [comment]
I created #2017 which should fix the issue, and also adds a unit test. Thanks for reporting this @nathanpbell , and thanks for the fix @Robitx.

**Comment by pdevine** [comment]
Should be fixed now.
