### ISSUE TITLE
Model Path Arch - AUR

### ISSUE THREAD

**Issue by DerRehberg** [ollama/ollama#2019]
I installed ollama from the Aur but the model path you guys specified doesn't exist, anyone know where it is? Is see this as a big Problem for running custom models

**Comment by mxyng** [comment]
Can you elaborate? It's unclear what issue your experience or what you mean by "the model path you guys specified doesn't exist".

**Comment by pdevine** [comment]
In linux the models should be stored under `/usr/share/ollama`. The `~/.ollama` directory in Linux is used for other things such as your key pair and other assets required to use ollama. It's also used for that in macOS, but also includes the models.

For custom models use a Modelfile and `ollama create` which will convert the model into a format that Ollama can use.

I _think_ I have answered your question, so will go ahead and close the issue, but feel free to keep commenting.
