### ISSUE TITLE
List available models

### ISSUE THREAD

**Issue by ParisNeo** [ollama/ollama#2022]
Hi. The API allows me to list the local models. Is there a way to list all available models (those we can find in the website of ollama?
I need that for the models zoo to make it easy for users of lollms with ollama backend to install the models.

I prefer this rather than having to scrape the website to get the latest list of models.

**Comment by LorenDB** [comment]
I'll +1 this. I'm building a client that ideally should allow users to choose what models they want in the client rather than copy-pasting model names from the Ollama website.

**Comment by kamuridesu** [comment]
Please, read the documentation: https://github.com/jmorganca/ollama/blob/main/docs/api.md#list-local-models

**Comment by hovhannest** [comment]
+

**Comment by lorenzejay** [comment]
Same here +1

**Comment by liar666** [comment]
Same here

**Comment by vaiju1981** [comment]
There is no way to discover what other models  that are not part of ollama space ( like users space )

**Comment by bitfist** [comment]
+1

**Comment by Frank995** [comment]
+1

**Comment by ivostoykov** [comment]
+1

**Comment by paulrobello** [comment]
+1

**Comment by ningo247** [comment]
+1

**Comment by akamalov** [comment]
+1

**Comment by webfarmer** [comment]
> Hi. The API allows me to list the local models. Is there a way to list all available models (those we can find in the website of ollama? I need that for the models zoo to make it easy for users of lollms with ollama backend to install the models.
> 
> I prefer this rather than having to scrape the website to get the latest list of models.

Suck that you can't do this.

I've attached a python script (rename the .txt file to .py) that
[get_ollama_models.txt](https://github.com/user-attachments/files/17227421/get_ollama_models.txt)
 scrapes their site and gets the models info. Does the job, but you need to:

pip install bs4

This Python script scrapes information about AI models from the Ollama library website (https://ollama.com/library). It performs the following main tasks:

It first checks if a local HTML file exists. If not, it fetches the webpage content and saves it locally.
It then parses the HTML content using BeautifulSoup to extract details about each model, including name, description, sizes, number of pulls, tags, and last updated date.

The extracted information is printed to the console and also saved as a JSON file.

The script includes error handling for failed web requests and creates necessary directories if they don't exist.

This code allows users to easily obtain and store up-to-date information about available models in the Ollama library without manually browsing the website.

**Comment by carlosalvidrez** [comment]
Hey, thank you!

**Comment by rmariboe** [comment]
I hacked this abomination together - gets the job done 😅


`function Get-OllamaModels {
 $ollamaLibUri = 'https://ollama.com/library'
 $ollamaLib = Invoke-WebRequest -Uri $ollamaLibUri
 $modelLinks = $ollamaLib.Links | Where-Object {$_.href.StartsWith('/library/')}

 $ollamaModelWebRequest = {
  $ollamaModelUri = 'https://ollama.com/library/' + $this.Name
  $ollamaModel = Invoke-WebRequest -Uri $ollamaModelUri
  return ($this | Add-Member -MemberType 'NoteProperty' -Name 'ModelWebRequestResponse' -Value $ollamaModel -Force -PassThru).ModelWebRequestResponse
 }

 $ollamaModelTagsWebRequest = {
  $ollamaModelTagsUri = 'https://ollama.com/library/' + $this.Name + '/tags'
  $ollamaModelTags = Invoke-WebRequest -Uri $ollamaModelTagsUri
  return ($this | Add-Member -MemberType 'NoteProperty' -Name 'ModelTagsWebRequestResponse' -Value $ollamaModelTags -Force -PassThru).ModelTagsWebRequestResponse
 }
   
 $ollamaModelDescriptionFunction = {
  $ollamaModelDescriptionStartToken = '<meta name="description"'
  $ollamaModelDescriptionStart = $this.ModelWebRequestResponse.Content.IndexOf($ollamaModelDescriptionStartToken)
  $ollamaModelDescriptionContentStartToken = 'content="'
  $ollamaModelDescriptionContentStart = $this.ModelWebRequestResponse.Content.IndexOf($ollamaModelDescriptionContentStartToken, $ollamaModelDescriptionStart) + $ollamaModelDescriptionContentStartToken.Length
  $ollamaModelDescriptionEnd = $this.ModelWebRequestResponse.Content.IndexOf('"', $ollamaModelDescriptionContentStart)
  $ollamaModelDescription = $this.ModelWebRequestResponse.Content.SubString($ollamaModelDescriptionContentStart, $ollamaModelDescriptionEnd - $ollamaModelDescriptionContentStart).Trim()
  return ($this | Add-Member -MemberType 'NoteProperty' -Name 'Description' -Value $ollamaModelDescription -Force -PassThru).Description
 }

 $ollamaModelTagsFunction = {
  $ollamaModelTagLinks = $this.ModelTagsWebRequestResponse.Links | Where-Object {$_.class -eq 'group'}
  $ollamaModelTagInfo = @()
  foreach ($ollamaModelTagLink in $ollamaModelTagLinks) {
   $ollamaModelTagName = $ollamaModelTagLink.href.Split('/')[-1]
   $ollamaModelTagInfoStart = $this.ModelTagsWebRequestResponse.Content.IndexOf($ollamaModelTagLink.outerHTML) + $ollamaModelTagLink.outerHTML.Length
   $ollamaModelTagIdEnd = $this.ModelTagsWebRequestResponse.Content.IndexOf('</span>', $ollamaModelTagInfoStart) + '</span>'.Length
   $ollamaModelTagInfoEnd = $this.ModelTagsWebRequestResponse.Content.IndexOf('</span>', $ollamaModelTagIdEnd)
   $ollamaModelTagInfoSplit = $this.ModelTagsWebRequestResponse.Content.Substring($ollamaModelTagIdEnd, $ollamaModelTagInfoEnd - $ollamaModelTagIdEnd).Split("`n")
   $ollamaModelTagInfoSizeHumanReadable = $ollamaModelTagInfoSplit[0].Trim().Split(' ')[1]
   try {$ollamaModelTagInfoSize = [int64][scriptblock]::Create($ollamaModelTagInfoSizeHumanReadable).InvokeReturnAsIs()} catch {}
   $ollamaModelTagInfoAge = $ollamaModelTagInfoSplit[1].Trim()
   $ollamaModelTagInfo += [pscustomobject]@{
    'Name' = $ollamaModelTagName;
    'Size' = $ollamaModelTagInfoSize;
    'SizeHumanReadable' = $ollamaModelTagInfoSizeHumanReadable;
    'Age' = $ollamaModelTagInfoAge
   }
  }
  return ($this | Add-Member -MemberType 'NoteProperty' -Name 'Tags' -Value $ollamaModelTagInfo -Force -PassThru).Tags
 }

 $modelLinks | ForEach-Object {
  [pscustomobject]@{
   'Name' = $_.href.Split('/')[-1].Trim()
  } |
  Add-Member -MemberType 'ScriptProperty' -Name 'ModelWebRequestResponse' -Value $ollamaModelWebRequest -PassThru |
  Add-Member -MemberType 'ScriptProperty' -Name 'Description' -Value $ollamaModelDescriptionFunction -PassThru |
  Add-Member -MemberType 'ScriptProperty' -Name 'ModelTagsWebRequestResponse' -Value $ollamaModelTagsWebRequest -PassThru |
  Add-Member -MemberType 'ScriptProperty' -Name 'Tags' -Value $ollamaModelTagsFunction -PassThru
 }
}

$ollamaModels = Get-OllamaModels`

**Comment by bartelsmedia** [comment]
+1
