### ISSUE TITLE
Enable Prompt Caching by Default

### ISSUE THREAD

**Issue by BruceMacD** [ollama/ollama#2023]
I had to disable prompt caching due to requests getting stuck: #1994 

We should bring this back when we have a mitigation for the inference issue:
https://github.com/ggerganov/llama.cpp/issues/4989

**Comment by jmorganca** [comment]
Prompt caching is now on by default

**Comment by chigkim** [comment]
How can I disable prompt caching? Is there a way to disable prompt caching with environment variable?

**Comment by recreationalviking** [comment]
I'm going to second @chigkim - how do I disable this? My first inference request is the fastest request that my system outputs. Every subsequent request drops down until I sustain tokens per second of about 60% of the original first request. I've got a feeling there's something wonky with the caching somewhere. (224 CPU cores, 2TB of memory, 8xH100 8gb gpus - it's not a resource issue - vmem is less than 50% used and its not a thermal issues as temps barely jump to 45c.)

**Comment by iganev** [comment]
I am going to second the second. I am noticing suspiciously identical responses for vastly different requests. Summarizing 2 different texts couldn't have possibly yielded the same thing. There's either some caching involved or a crashed executor that isn't handled properly.

**Comment by jessegross** [comment]
If the requests are different, it won't trigger prompt caching.

**Comment by jdblack** [comment]
> If the requests are different, it won't trigger prompt caching.

I'm sorry if this comes off as a bit of a jumble, as I'm at a loss as how to explain this coherently.    I could  provide a ruby script that shows the behavior, if that would be useful?



I'm definitely getting identical responses from  /api/generate despite the leading portion of the prompt changing.    In my use case,  I'm asking   gemma3 (via ollama 0.6 of course)  to extract a list of facts from  news articles.   The format of the generation is along the lines of:
```
instructions  to extract facts from articles

the_article_title  (40- 200 characters
article_date
article_contents   (5k -  30k characters)

However, I quickly found that  I kept getting the same response back  even after changing the instructions. 


The length of the test article is nearly 10k, so I suspect it's overwhelming the initial part of the prompt.

Here are some sample instructions I tried using: 

```
"You are a expect in sorting facts.  First, identify as 'entities' all of the  people, places, products, organziations and products.   Then,  for each entity, find as many fact as possible, and day and time they occurred: \n\n#{a.title}\n#{a.publishedAt}\n#{a.content}  ", format: format)
```
```
"Find as many facts as possible!  \n\n#{a.title}\n#{a.publishedAt}\n#{a.content}  ", format: format)  
```
```
"Extract at least 5 facts from this article  \n\n#{a.title}\n#{a.publishedAt}\n#{a.content}", format: format)  
"Say hello  \n\n#{a.content}  ", format: format)  
```


Format is a json blob that describes the json I want back:
```
{"type":"array","items":{"type":"object","properties":{"fact":{"type":"string"},"date":{"type":"string"},"entities":{"type":"array","items":{"type":"string"}}},"required":["fact","date","entities"]}}
```



[{"fact" => "The article emphasizes the limitations of DCF (Discounted Cash Flow) valuation, arguing that 80% of the calculated ‘value’ relies on uncertain terminal assumptions.",
  "date" => "October 26, 2023",
  "entities" => ["DCF valuation", "Amazon", "Tesla", "Apple", "S&P 500"]}]

**Comment by kevin-pw** [comment]
> In all cases, I get the exact same return, even for the "say hello" one in which I don't even pass the date at all!

@jdblack Your issue is probably unrelated to prompt caching. It sounds like your context length is set too short so the beginning of your prompt gets cut off. Ollama uses a default context length of 2048 tokens.

Try setting a larger context length with `num_ctx`, for example:
```
curl http://localhost:11434/api/generate -d '{
  "model": "llama3.2",
  "prompt": "Why is the sky blue?",
  "options": {
    "num_ctx": 65536
  }
}'
```

Also, see docs: https://github.com/ollama/ollama/blob/main/docs/faq.md

**Comment by jdblack** [comment]
> Try setting a larger context length with `num_ctx`, for example:
> 
> ```
> curl http://localhost:11434/api/generate -d '{
>   "model": "llama3.2",
>   "prompt": "Why is the sky blue?",
>   "options": {
>     "num_ctx": 65536
>   }
> }'
> ```


Sorry, I must have commented twice and forgotten.  I wrote a much larger description elsewhere and the small context was indeed the problem.

Thank you for following up!

**Comment by micseydel** [comment]
> I am noticing suspiciously identical responses for vastly different requests. Summarizing 2 different texts couldn't have possibly yielded the same thing.

I've failed to reproduce it, but I hit the same thing this week. My code's HTTP request had a bug where it didn't include the `images` field for a llava request, and the resulting hallucination had specific details from the _prior_ image I'd successfully sent over the web API. A screenshot of text was described as having a cat, with details specific to the prior image (which did have a cat).

I'm not filing a new bug since I can't reproduce it, but if anyone has ideas for how to reproduce this bug or links to similar issues, I'm open to suggestions.

@NeuralNotwerk and @iganev , do either of you have any updates on this? If you moved away from Ollama and are using Apple Silicon, I'd be curious what you moved to.
