### ISSUE TITLE
falcon model not working.

### ISSUE THREAD

**Issue by iplayfast** [ollama/ollama#2024]
I've been working with https://github.com/jmorganca/ollama/issues/1691 and found that it consistently dies with falcon. 
So I tried falcon on it's own. It died. 
So I tried removing falcon and reinstalling it.
Still died.
I can no longer get falcon to work. 
I'm on Ollama version 0.1.20

**Comment by EMREOYUN** [comment]
Successfully reproduced on Ollama 0.1.30

**Comment by iplayfast** [comment]
Yup still dead with ollama 0.1.30 linux

**Comment by pdevine** [comment]
We use llama.cpp for the backend runner and it unfortunately dropped support for the original falcon model. There is now the [falcon2](https://ollama.com/library/falcon2) model which does work.
