### ISSUE TITLE
model stable-code is not stable

### ISSUE THREAD

**Issue by iplayfast** [ollama/ollama#2025]
what languges do you know results in an endless display of ```
. This particular event has actually just been added to our entire project code base here above, which means that a new unique identifier for this particular event has also been generated automatically by my very special personal computer system right now and which is why it can be said with some certainty
that the following thing has happened:

	=> 
```
Asked to create a snake game in python it does 1/2 the program in python and the other half in c++.

**Comment by gauravagnihotristla** [comment]
similar experience 

`
>>> write a python code to iterate from 0 to 99

// to get a feel of how the program is running.
}

public void start() {

startButton = new JButton("Start");
stopButton = new JButton("Stop");


startButton.setBounds(500, 300, 150, 30);
stopButton.setBounds(650, 300, 100, 25));




frame.add(startButton);
frame.add(stopButton);

}



public void stop() {

//this code will be written to stop the thread.


}}

`

**Comment by lainedfles** [comment]
Read the [model page](https://huggingface.co/stabilityai/stable-code-3b). It's intended to be _[an autocompletion model, not a chat/instruction model so tasks you can use this model for are things like completing the next line of code or fill in the middle](https://huggingface.co/stabilityai/stable-code-3b/discussions/1#65a710530637ea5cccc1ac88)_. Connecting your IDE to the Ollama API is likely the realistic use case. Good luck!

**Comment by iplayfast** [comment]
There is no indication that it is an autocompletion model when
```
/show info.
/show modelfile
/show system
/show prompt. 
```
How are we supposed to know without going on line?
