### ISSUE TITLE
Is the Ollama.app necessary after installation

### ISSUE THREAD

**Issue by LeonardoGentile** [ollama/ollama#2031]
I was unsure what the Ollama.app was installing on mac but after it did its thing I've realized ollama is installed under `/usr/local/bin/ollama` which I could have done using brew or similar installation processes. 

I've realized my models are under `~/.ollama` so my question is: Is the `Ollama.app` still necessary or it was just to install the binary? If I remove it everything should keep on working as before by calling ollama from the command line?

**Comment by easp** [comment]
Ollama has a client and a server. The client is in /usr/local/bin/ollama. The server is in and run by Ollama.app.

The bottled ollama package has its own service runner (or uses something provided by homebrew), but at least historically, it hasn't been updated in a timeline manner when a new version of Ollama is released.

**Comment by bm777** [comment]
It would be nice, if we could use Ollama cli just like llama.cpp without Ollama.app

**Comment by LeonardoGentile** [comment]
> Ollama has a client and a server. The client is in /usr/local/bin/ollama. The server is in and run by Ollama.app.

Thanks, but now I'm confused 🤔

I've quit the Ollama.app (also from the menu bar) and I've installed a vscode plugin that calls Ollama (https://github.com/rjmacarthy/twinny) and it's been working correctly. 
So how can the plugin works correctly without the server running? 

There must be some service running in the background even if the main app is no running

**Comment by LeonardoGentile** [comment]
> @LeonardoGentile That's odd. How did you install Ollama and/or did you install it more than once with one of those being homebrew? The homebrew bottle runs ollama as a service, somehow (I think there may be a homebrew way to run/manage services, without the app. `ollama serve` also runs the service without the app.
> 
> @bm777 You can download the binary-only version, and run `ollama serve`

I downloaded only the Ollama.app.

Sorry, my mistake!  By quitting the app I am indeed unable to make the vscode plugin work.
Even tough I quit the Ollama.app it seems the vscode plugin tries to launch the Ollama.app, sometimes successfully, sometimes not. 
In fact, when launching or restarting VsCode I see the Ollama.app icon bouncing on the Dock but most of the times I can't see the service running on the menubar. 

I do have to manually click on the app icon and then I can correctly see the ollama item on the menu bar and the vscode plugin works again. 

The fact that the ollama is not on the menubar even tough it's been called by vscode (the bouncing app icon) it has to do to with my system configuration, ollama.app permission or the vscode plugin? 

What can I do to find out what's causing this?

**Comment by bm777** [comment]
> You can download the binary-only version, and run ollama serve

@LeonardoGentile try this.

**Comment by pdevine** [comment]
@LeonardoGentile was your question answered? The `Ollama.app` will also notify you when there is a new version. I would definitely recommend using it. You can alternatively use the binary-only version, or compile from source. Those two methods are harder to use and require you running the server yourself.

I'm going to close the issue, but feel free to reopen it.
