### ISSUE TITLE
Unable to pull models on NTFS filesystem

### ISSUE THREAD

**Issue by luannbertaud** [ollama/ollama#2032]
Hi,

### Context
I am running **ollama** using the docker image, but I want to store the models on an external SSD to prevent the container from filling my computer storage.
The way I'm doing it, is that I mount the ` ~/.ollama/` directory of the container into my SSD.

### Issue
Since the docker image is built with Linux as OS, I suppose that the `GOOS` variable is set to `linux` (I found this variable [in code](https://github.com/jmorganca/ollama/blob/d5a73533574acb02069e74f1d01f6775577391bc/server/layers.go#L51)).
The problem is that my SSD is using NTFS filesystem, and the **:** (colon) character from the blobs file name (sha256:f7c4e...) is therefore forbidden.
> Error: open /root/.ollama/models/blobs/sha256:4dc8bd...6e0dac-partial-0: invalid argument

### Proposition
Make the replace condition (colon to hyphen) depends on filesystem, or replace colon by an universal character.

### Disclaimer
I've never developed in GO, so I'm really not sure about the origin of the problem, maybe the issue is very different from what I think. However, downloading the blobs into the container before renaming (in manifest to) and moving them into NTFS filesystem worked. 

### Data
Docker Image: ollama/ollama:latest (sha256:80ed5afc9183bcf3b6c14d38f5b695472bb8af44f2d5fcfba5bbbb4a1a012e72)
Model: mistral:7b
OS: Fedora 37
Storage: External SSD - NTFS
Docker: 24.0.7

**Comment by pdevine** [comment]
This one is tough because it would be pretty painful to migrate linux users over to using a different file layout scheme. I'm pretty sure this _is_ working correctly if you run Ollama on Windows (we're getting closer to a release), but I hadn't anticipated someone using NTFS directly w/ Linux. I'm wondering if there is some kind of compatibility mode that you could use? I'm not sure how docker volumes map that in.

**Comment by luannbertaud** [comment]
Unfortunately, I didn't find any way to solve this with docker volumes, in the end the filename is forbidden by the drive's FS.
I agree that migrating Linux users files is not a good solution, but do you think it's feasible to make the [colon/hyphen replacement](https://github.com/ollama/ollama/blob/d5a73533574acb02069e74f1d01f6775577391bc/server/layers.go#L51) depends on the filesystem instead of the operating system ? This way it would be transparent for both Linux and Windows users.

**Comment by edisonzf2020** [comment]
+1

**Comment by aguang-xyz** [comment]
I faced the same issue (running `ollama` via Docker on Linux with folder `/root/.ollama` mounted to external SSD using `Exfat` filesystem).

**Comment by jikkuatwork** [comment]
Wow! This is the reason why I wasn't able to store models in my external drive! The blobs file names seems to be the issue! Any chance you can change it so that it works in NTFS too?

**Comment by pdevine** [comment]
@jikkuatwork as a work around for now you can either reformat the external storage to something more friendly to Linux/MacOS (e.g. ext4 or APFS). If you're using Windows NTFS will work fine of course.

**Comment by jikkuatwork** [comment]
> @jikkuatwork as a work around for now you can either reformat the external storage to something more friendly to Linux/MacOS (e.g. ext4 or APFS). If you're using Windows NTFS will work fine of course.

Thanks! I bought a new drive and solved the issue!

**Comment by pdevine** [comment]
@jikkuatwork In the next version we'll switch everyone over to using NTFS compatible names. It should make it easier in the future.

**Comment by MattJE9601** [comment]
Temporary workaround that doesn't require reformatting your NTFS filesystem.
Use dd to create a virtual drive image on the NTFS drive, then mount it somewhere.
I primarily run linux but keep a windows partition and second large drive for gaming. I also keep that drive mounted in linux though for storing larger files.  This is how I handle these issues.

dd if=/dev/zero of=virtual_drive.img bs=1M count=102400 (100GB)
mkfs.ext4 virtual_drive.img
mkdir /mnt/virtual_drive
mount -o loop virtual_drive.img /mnt/virtual_drive
