### ISSUE TITLE
Not running on gpu

### ISSUE THREAD

**Issue by DragonBtc93** [ollama/ollama#2034]
I'm a Ubuntu 22.04 use have a Nvidia tesla p40 and a k80 gpu and it will not use gpu. I can use text generation webui and get gpu.

**Comment by dhiltgen** [comment]
Assuming these are in the same system, the K40 is the problem.   That GPU is a Compute Capability 3.5 card, while the P40 is a Compute Capability 6.1 card.  6.1 is supported today, but 3.5 is not yet supported, and tracked via issue #1756 
We don't yet have a solid way to ignore unsupported cards and use supported cards, so we'll disable GPU mode if we detect any GPU that isn't supported.   As a workaround until we fix #1756, you can pull the K40 and Ollama should run on the P40 GPU.


https://developer.nvidia.com/cuda-gpus
