### ISSUE TITLE
web-ui log error loading model: llama.cpp: tensor 'layers.2.ffn_norm.weight' is missing from model

### ISSUE THREAD

**Issue by lpf763827726** [ollama/ollama#2039]
when i run `ollama run llama2:13b` and `ollama run codellama` with ollama-webui, and ask 2~3 question, it start to got error, it report error missing something

[Issue details](https://github.com/ollama-webui/ollama-webui/issues/507)

**Comment by lpf763827726** [comment]
for now when i try `systemctl restart service` it feel look so find

**Comment by pdevine** [comment]
I'm going to assume the issue went stale since this was from quite some time ago. It's most likely that you ran out of memory, however Ollama is quite a bit better at handling memory now. I'll close it, but feel free to keep commenting and we can reopen.
