### ISSUE TITLE
how  use offline models

### ISSUE THREAD

**Issue by linpan** [ollama/ollama#2042]
env: no network.  i download model .  

ollama run  ./my-model-path  is support ??

**Comment by Putnug1122** [comment]
In the [docs](https://github.com/jmorganca/ollama/blob/main/README.md#customize-a-model), you can see how to make Ollama work with a local model (GGUF format)

**Comment by pdevine** [comment]
You'll need to make certain your model is in GGUF format, but you can follow the docs as @Putnug1122 mentioned.

**Comment by linpan** [comment]
Environment= "OLLAMA MODELS=/data/models"
download model phi3 to /data/models
ollama list no find phi3
