### ISSUE TITLE
ollama run stable-code 

### ISSUE THREAD

**Issue by JiangZongKang** [ollama/ollama#2047]
The command does not produce any response when executed on a Mac.

![CleanShot 2024-01-18 at 19 56 17@2x](https://github.com/jmorganca/ollama/assets/22634440/f423f706-10b1-496a-bb8e-50a85afbea6b)

**Comment by easp** [comment]
Try quitting the Ollama app from the menubar and running it again. Then try your command again. There is a bug in the current version (0.1.20) that leads to Ollama hanging.

**Comment by timo-klarshift** [comment]
For me it runs, but a prompt like "create a simple golang hello world" just spits out garbage and it takes quite a while until it stops. Something seems wrong.

**Comment by dhiltgen** [comment]
Can you share the server log?

https://github.com/ollama/ollama/blob/main/docs/troubleshooting.md#how-to-troubleshoot-issues
