### ISSUE TITLE
Prompt Eval Count is 1 when image is included in multimodal request

### ISSUE THREAD

**Issue by Dillon-Yun** [ollama/ollama#2058]
When I hit the `/api/generate` endpoint for a multimodal model, such as bakllava, I am seeing that `prompt_eval_count == 1` when an image is included. Is this correct behavior? How can I retrieve the total amount of tokens in the request for a multimodal request?

**Comment by dhiltgen** [comment]
Confirmed this is fixed in the Go server in the 0.4.0 RC.
