### ISSUE TITLE
gpu

### ISSUE THREAD

**Issue by iplayfast** [ollama/ollama#2064]
I tried running ollama on a laptop and noticed that it wasn't using gpu. I don't know why as cuda is installed and is the correct version for the video drivers. 
I'd like to request an enhancement, of an error message that says something to the effect of gpu noticed but not used because....

I'd also like to be able to see the message when running ollama, something like
/show ollamasystem

**Comment by Titaniumtown** [comment]
Could you provide more information about your computer and what OS you're running and such?

**Comment by DuckyBlender** [comment]
Same issue here - I'm running Fedora 39 server with GPU drivers installed
Driver Version: 545.29.06    CUDA Version: 12.3
NVIDIA GeForce GTX 950M

Yet when running a model the GPU does nothing

**Comment by iplayfast** [comment]
laptop has gtx960m nvidia running linux-mint with cuda 12 installed.

**Comment by iplayfast** [comment]
Latest version fixed this bug
