### ISSUE TITLE
 illegal hardware instruction  ollama run llama2

### ISSUE THREAD

**Issue by LoveSlience** [ollama/ollama#2069]
When i download mac app then run `ollama run llama2`  has error `7326 illegal hardware instruction  ollama run llama2` 

![image](https://github.com/jmorganca/ollama/assets/22396365/58c5ab74-0a0e-4ed1-a074-da26f63bcd97)
![image](https://github.com/jmorganca/ollama/assets/22396365/9847a70c-5439-412c-8ae5-2270d615a68e)

**Comment by LeaveNhA** [comment]
Running it with Rosetta could decrease the performance. Is it really a low-priority issue for you people, it's concerning.

**Comment by LoveSlience** [comment]
> For some reason people have started having problems with Ollama running in Rosetta on MacOS. Try selecting the Mac app and hitting ⌘I (Get Info...) and checking to see if "Open Using Rosetta" is checked. If it is, uncheck it, quit and relaunch Ollama and try again.

I have checked and found that the Rosetta option was not selected during initialization. After downloading and installing again, I found that it still does not work
![image](https://github.com/jmorganca/ollama/assets/22396365/60915cd0-0236-49cb-aa3c-98a82e45cf47)

**Comment by abinvs-2019** [comment]
+1

**Comment by jryio** [comment]
Experiencing this broken verison Ollama on macOS Sonoma 14.2 (M1 Max Macbook Pro).

Ollama version 0.1.20

**Comment by tleish** [comment]
FYI, I was experiencing this same error on a Macbook M1 which led me to this issue:

```sh
$ ollama run llama2
Illegal instruction: 4
```

Based on this thread, I looked at the Ollama.app settings and "Open using Rosetta" was _unchecked_.  However, I remembered that when the Macbook M1s first came out, there was some issues with homebrew and/or libraries using the Apple Silicon, and I remember reading about using Rosetta Stone with Homebrew.  So I ran the following in my terminal:

```
$ brew config
...
CPU: 10-core 64-bit arm_firestorm_icestorm
macOS: 14.3-arm64
Rosetta 2: true
```

Note the last line.  I must've installed homebrew with Rosetta years ago when first receiving the M1.  So, I went through a painful process of uninstalling/reinstalling

**Comment by dhiltgen** [comment]
We've recently added CPU variant support for CPUs without vector math extensions (AVX, AVX2, etc.) which as a side-effect, allows Ollama run under rosetta on arm macs.  I think we can consider this fixed.  If you're still seeing illegal instruction errors on 0.1.22 please re-open.
