### ISSUE TITLE
How to use this with Own Document

### ISSUE THREAD

**Issue by bibutikoley** [ollama/ollama#2095]
Is it possible to use this with custom documents(pdf, html, doc, etc) or by specifying a Website URL where it can fetch data from the website. If yes, please let me know how can it be achieved?

**Comment by oliverbob** [comment]
You can download ollama-webui. Its a great project by a large community. Here's my fork of it. https://github.com/oliverbob/gpt-ui. Ollama web ui is the best alternative to Chat GPT.

**Comment by oliverbob** [comment]
In my opinion, it depends on the model you're talking to. And you also need to create a model with "create" modelfile command and give it system prompt as direction. Of course all that are available options in the UI. You have to experiment with the right model who can do the inferencing job you require.

**Comment by mxyng** [comment]
Closing this since it seems the question's been answered
