### ISSUE TITLE
make ollama pluggable into Oobabooga

### ISSUE THREAD

**Issue by swyxio** [ollama/ollama#210]
i'm new to both projects so pardon if this is obvious, but can we get instructions on how to use ollama with Oobabooga please?

**Comment by igorschlum** [comment]
Hi @swyxio could you please explain if you still need to use ollama with Oobabooga. It's not clear to me how you wanted that and it not, I think the issue can be closed as it's not really an issue.

**Comment by igorschlum** [comment]
Hi @swyxio  @jmorganca I think that this issue can be closed. It's Oobabooga to write code to be compatible with Ollama, not Ollama to do special things.
