### ISSUE TITLE
GPU on Fedora 39

### ISSUE THREAD

**Issue by schwarz-christoph** [ollama/ollama#2103]
After I instaled ollama on my Fedora Workstation 39 the install script installs automatically the NVIDIA Drivers for my GPU but after reboot the Graphics where broken and also all other Drivers like Wifi were not loaded

**Comment by DuckyBlender** [comment]
related to #2064

**Comment by pdevine** [comment]
It shouldn't have ever had an issue w/ the wifi drivers, but this may in theory be working now.

cc @dhiltgen

**Comment by dhiltgen** [comment]
@schwarz-christoph are you still having problems running the install script?
