### ISSUE TITLE
Can ollama access internet?

### ISSUE THREAD

**Issue by zinwelzl** [ollama/ollama#2119]
Can ollama access internet?

And summarize text, etc. 

I try it, but didn't work.
Maybe my installation don't work correctly?

**Comment by explorigin** [comment]
Ollama runs LLMs only. LLMs would need tools to do the sorts of things you're asking. This is outside the scope of ollama. I recommend you to research how autogen or crewai work if this is something you want to do.

**Comment by pdevine** [comment]
Unfortunately (or fortunately depending on your viewpoint!) the CLI does not have the ability to reach out and pull in webpages to summarize text. I'm going to close this, but feel free to reopen it if you want to make this a feature request (although there may already be an issue for that).
