### ISSUE TITLE
Feature request: control session duration of loaded models

### ISSUE THREAD

**Issue by nperez** [ollama/ollama#2121]
I have a use case where multiple processes (stable diffusion, whsiper, ollama, etc) are competing for limited GPU resources and I need to share the GPU. Unfortunately, there doesn't appear to be a way to manage the session lifetime of loaded models in ollama. It would be cool to have the ability via model options to control the session lifetime (ie. unload after each request) or have a new endpoint to unconditionally unload whatever model is loaded. Without this feature, I need to manage (kill, then restart) the ollama process or wait the five minutes that is the current `defaultSessionDuration` in routes.go. Before v0.1.18, I probably would have just killed the separate runner process which would leave the api server intact, but now that it is integrated, that isn't really an option any more.

**Comment by pdevine** [comment]
You will be able to use the new `keep_alive` parameter which was just checked in in #2146 . You can set it to `0` and it will automatically unload the model after inference is completed.
