### ISSUE TITLE
Ollama Server logs not found in container

### ISSUE THREAD

**Issue by OM-EL** [ollama/ollama#2137]
I've started both the **Ollama** and **Ollama-webui** containers on my Linux machine. They are both up and running as confirmed by the `docker ps` output:

```
[docker@ld002dkr10014 ~]$ docker ps
CONTAINER ID  IMAGE                                   COMMAND      CREATED      STATUS            PORTS                     NAMES
834f3620dbbd  docker.io/ollama/ollama:latest          "serve"      2 hours ago  Up About an hour  0.0.0.0:11434->11434/tcp  ollama
f0fe64145aa1  ghcr.io/ollama-webui/ollama-webui:main  "sh start.sh"  2 hours ago  Up 2 hours        0.0.0.0:3000->8080/tcp    ollama-webui
```

However, when I enter the Ollama container and attempt to run Mistral, I encounter the following error:

```
[docker@ld002dkr10014 ~]$ docker exec -it  834f3620dbbd bash
root@834f3620dbbd:/# ollama run mistral
Error: something went wrong, please see the ollama server logs for details
```

Additionally, when I try to access the logs to diagnose the problem, I find no relevant log entries:

```
root@834f3620dbbd:/# ls ~/.ollama
id_ed25519  id_ed25519.pub  models
root@834f3620dbbd:/# journalctl -u ollama
No journal files were found.
-- No entries --
```

Can anyone advise on how to troubleshoot or resolve these issues with running Mistral in the Ollama container and accessing the logs for more information?

**Comment by dhiltgen** [comment]
When running in a container, the server is the primary process and sends the log output to stdout/stderr for the container.  This is then received by the container runtime or container orchestrator.  In your case, you would view this with `docker logs ollama` on your host system.

**Comment by FlorianHeigl** [comment]
note for others: this error path does in fact not log any errors at the point this is generated.
