### ISSUE TITLE
Streaming response with `text/event-stream`

### ISSUE THREAD

**Issue by radames** [ollama/ollama#2145]
Are you still considering adding `text/event-stream` for the Streaming Response ? Reading #294, it might make sense to have that option for browser-only clients.

For reference, here is a JavaScript client for text streaming that works on both the browser and Node.js.
https://github.com/huggingface/huggingface.js/blob/main/packages/inference/src/tasks/custom/streamingRequest.ts

**Comment by radames** [comment]
Amazing! @mxyng didn't know about the OpenAI compatibility 👏

**Comment by Rutik7066** [comment]
Hey, I am planning to use SSE for Rust application targeting WASM-WASI. So, I want to know if SSE is supported or not. If yes, are there any limitations?
