### ISSUE TITLE
I want to run Ollama on the limited number of GPUS and CPUS

### ISSUE THREAD

**Issue by sfarzi** [ollama/ollama#2156]
I have a machine with 4 GPUS and 16 CPUS. but I want to run Ollama just on one gpu and 8 cpus. How can I do this?

**Comment by easp** [comment]
Manuall setting num_thread in a Modelfile will limit the cores used.  GPUs is more complicated. I think this will work (assuming you are using NVIDIA)
https://developer.nvidia.com/blog/cuda-pro-tip-control-gpu-visibility-cuda_visible_devices/

**Comment by jukofyork** [comment]
There is already the option to pass through the `main_gpu`  option to the wrapped llama.cpp server but  the patch to pass through the `tensor_split` option https://github.com/ollama/ollama/pull/1256 seems to be stuck and says: "This branch has conflicts that must be resolved".

Somebody in that thread replied that the patch works fine though.

**Comment by dhiltgen** [comment]
I've updated our docs to show how to limit GPUs.  

You can experiment with `taskset` for CPU limiting, but I would suggest using something like `nice` to adjust the priority of the process if you're trying to avoid starving other workloads of CPU cycles.
