### ISSUE TITLE
Do we have a Go client

### ISSUE THREAD

**Issue by liliang-cn** [ollama/ollama#2159]
I'm know there is a HTTP API, but can I utilize this API in a similar manner like [ollama-python?](https://github.com/jmorganca/ollama-python)

**Comment by pdevine** [comment]
You can find it in `api/client.go`. It's used extensively in the REPL.

**Comment by pdevine** [comment]
I should mention that it's not as extensively documented as the [python client](ollama/ollama-python) or the [javascript client](ollama/ollama-js).

**Comment by TimothyStiles** [comment]
@pdevine @liliang-cn I've been working on some example tests for the exported functions in `api/client.go` and plan on submitting a PR for it tomorrow. Will tag this issue when I do.

**Comment by mxyng** [comment]
While api/client.go is public, it's not intended for public consumption and does not have any compatibility guarantees. The main use case is for the CLI. I would use it with caution
