### ISSUE TITLE
Add support for fresh initialization and hooks in Docker image

### ISSUE THREAD

**Issue by eddumelendez** [ollama/ollama#2160]
It would be nice to improve models pulling and custom model creation when starting with Ollama.

# Fresh initialization

Some databases allows to copy `.sh` and `.sql` to execute instructions once it is ready. See mysql [docs](https://github.com/docker-library/docs/tree/master/mysql#initializing-a-fresh-instance).

Example:

Create `ollama.sh`

```sh
ollama pull llama2
```

Copy or mount the shell under `docker-entrypoint-initollama.d/ollama.sh` and once Ollama is up then the model will be pulled automatically.

# Hooks

LocalStack offers something more regarding to the Fresh initialization approach through [lifecycle stages and hooks](https://docs.localstack.cloud/references/init-hooks/) and it also provides a nice [API to check the status of those hooks](https://docs.localstack.cloud/references/init-hooks/#status-endpoint).

Example: 

Create `ollama.sh`

```sh
ollama pull llama2
```

Copy or mount the shell under `/etc/localstack/init/ready.d/ollama.sh`.

> [!NOTE]  
> LocalStack offers `boot`, `ready`, `shutdown` and `start` stages but not sure if all of them could have a use case in Ollama.

With this enhancement starting with Ollama will improve experience with Dockerfile, Docker Compose and Testcontainers by mounting or copying files and make the model ready to use. My use case is simple to pull images but it will also help to create custom models.

**Comment by mxyng** [comment]
There's currently no plans to support this feature but that might change as the project evolves
