### ISSUE TITLE
Question: Are `qwen:72b-chat` and `qwen:72b-text` about to be added to `ollama.ai`?

### ISSUE THREAD

**Issue by jukofyork** [ollama/ollama#2170]
I was just about to download/quantize the transformer models from Hugging Face, but noticed `qwen` was added to `ollama.ai` and wondered if `qwen:72b-chat` and `qwen:72b-chat-text` were about to be added?

It says this on the 'Overview' page:

>This model is offered in four different parameter size tags:
>
>- `qwen:1.8b`
>- `qwen:7b (default)`
>- `qwen:14b`
>- `qwen:72b`

But there are no 72b variants listed on the 'Tags' page. I tried `ollama pull qwen:72b-chat-q8_0` to see if it might just be unlisted, but it returns `Error: pull model manifest: file does not exist`.

**Comment by mchiang0610** [comment]
yes! https://ollama.ai/library/qwen

and the versions available for you to pull

https://ollama.ai/library/qwen/tags

**Comment by jukofyork** [comment]
Thanks!

**Comment by qitao052** [comment]
there three kind of tags, like 72b, 72b-chat and 72b-text. May I ask the difference of 72b-text from  72b or 72b-chat ?

**Comment by jukofyork** [comment]
> there three kind of tags, like 72b, 72b-chat and 72b-text. May I ask the difference of 72b-text from 72b or 72b-chat ?

Text is the base model that just predicts the next word and it very hard to work with. Chat (or instruct) models have been fine tuned after they are trained to and what you should always choose.
