### ISSUE TITLE
Issues with OllamaEmbedding

### ISSUE THREAD

**Issue by RonHein** [ollama/ollama#2173]
Hi, I am having trouble using OllamaEmbedding. I am unable to retrieve the correct vectors and the the similarity score is really high. I was able to get the correct vectors with OpenAIEmbedding but I am hoping to get OllamaEmbedding working. Is there something that I am missing?

Below is a simple loader with chromadb using OllamaEmbedding. 

`from langchain.document_loaders import PyPDFLoader, UnstructuredExcelLoader, Docx2TxtLoader, BSHTMLLoader, TextLoader
from langchain.embeddings import OllamaEmbeddings
from langchain.vectorstores import Chroma
from langchain.text_splitter import RecursiveCharacterTextSplitter

def chunk():
    loader = TextLoader('./samples/facts.txt')
    
    text_splitter = RecursiveCharacterTextSplitter(
        chunk_size=128
        chunk_overlap = 20
    )

    docs = loader.load_and_split(
        text_splitter=text_splitter
    )

    return docs

def create_embedding():
    docs = chunk()

    embeddings = OllamaEmbeddings()

    db = Chroma.from_documents(
        docs,
        embedding=embeddings,
        persist_directory="./samples/docs/chroma",
    )

    results = db.similarity_search_with_score("What is an interesting fact about the English language?")

    print("~~~~similarity_search_with_score~~~~"
    for result in results:
        print("\n")
        print(result[1])
        print(result[0].page_content)
`

This is the output:
8292.622553378074
16. Queen Elizabeth II is the longest-reigning current monarch.
17. The Leaning Tower of Pisa took 200 years to construct.

8386.487814338176
6. The elephant is the only mammal that can't jump.
7. The letter 'Q' is the only letter not appearing in any U.S. state name.

8529.430614665867
34. The shortest war in history was between Britain and Zanzibar on August 27, 1896. Zanzibar surrendered after 38 minutes.

8711.880867153133
50. Canada has more lakes than the rest of the world combined.
51. 10% of the world's population is left-handed.

**Comment by fbcorrea** [comment]
@RonHein any updates?
I am having the same issue.

**Comment by mxyng** [comment]
This seems like an issue for LangChain since that's the main interface here. Ollama is only providing the embeddings API

**Comment by jmorganca** [comment]
Thanks for the issue @RonHein. This should be far more improved now with embedding models such as https://ollama.com/library/nomic-embed-text
