### ISSUE TITLE
Additional package managers

### ISSUE THREAD

**Issue by rubencallewaert** [ollama/ollama#2178]
While it's true that Homebrew is by far the most popular package manager on Mac, It would be great to be able to install Ollama via MacPorts.

This gives people maximum freedom in installing Ollama the way they want to, for a lot of people including me it isn't really acceptable to run an electron GUI application that needs to be granted root privileges to install a CLI.

I understand wanting to make the barrier entry as low as possible for the maximum amount of people, but there should always be a secondary option to just use a package manager of your choice to install a CLI.

**Comment by easp** [comment]
The homebrew package is provided by community members, as are the packagings for various linux distribution. I think MacPorts will need similar community initiative.

**Comment by jmorganca** [comment]
Will close this for https://github.com/ollama/ollama/issues/3067
