### ISSUE TITLE
Python example does not work

### ISSUE THREAD

**Issue by claremont-awilson** [ollama/ollama#2185]
Reading this: https://ollama.ai/blog/python-javascript-libraries

Trying to perform the Python example errors on macOS and OEL9:

```python
import ollama
response = ollama.chat(
    model="llama2",
    messages=[
        {
            "role": "user",
            "content": "Why is the sky blue?",
        },
    ],
)
print(response["message"]["content"])
```

error is:

> Traceback (most recent call last):
>   File "/home/my_name/repos/Python/ollama.py", line 1, in <module>
>     import ollama
>   File "/home/my_name/repos/Python/ollama.py", line 3, in <module>
>     response = ollama.chat(
> AttributeError: partially initialized module 'ollama' has no attribute 'chat' (most likely due to a circular import)

Python version: 3.9.18

**Comment by jmorganca** [comment]
Ah! This may be because you named your python file `ollama.py`, and so it's creating a circular import. Try naming it `example.py` for example. Funny enough I did this too when trying to reproduce this issue before realizing 😊

**Comment by TiniKrasniqi** [comment]
> Ah! This may be because you named your python file `ollama.py`, and so it's creating a circular import. Try naming it `example.py` for example. Funny enough I did this too when trying to reproduce this issue before realizing 😊

Had the same problem and this was the problem, thanks.
