### ISSUE TITLE
:duck: Publish `DuckDB-NSQL-7B` on ollama

### ISSUE THREAD

**Issue by adriens** [ollama/ollama#2193]
# :grey_question: About

[`DuckDB-NSQL-7B`](https://motherduck.com/blog/duckdb-text2sql-llm/), A LLM for [duckdb](https://github.com/duckdb/duckdb) has been released.

It would be very useful to add it to `ollama` so anyone could build new experiences on top if it.

# :bookmark: Resources

- [AI That Quacks: Introducing DuckDB-NSQL-7B, A LLM for DuckDB](https://motherduck.com/blog/duckdb-text2sql-llm/)
- [Demo on HuggingFace](https://huggingface.co/spaces/motherduckdb/DuckDB-NSQL-7B)
- [`motherduckdb/DuckDB-NSQL-7B-v0.1-GGUF`](https://huggingface.co/motherduckdb/DuckDB-NSQL-7B-v0.1-GGUF)
- [:octocat: `github.com/NumbersStationAI/DuckDB-NSQL`](https://github.com/NumbersStationAI/DuckDB-NSQL)

**Comment by mxyng** [comment]
duckdb-nsql is available [here](https://ollama.ai/library/duckdb-nsql)

**Comment by adriens** [comment]
https://ollama.ai/library/duckdb-nsql
![image](https://github.com/ollama/ollama/assets/5235127/94475c94-53d6-41bf-88c3-596793472c6c)

**Comment by adriens** [comment]
:clap: Awesome to have also dropped code samples

``sh
pip install ollama
```

```python
import ollama

r = ollama.generate(
    model='duckdb-nsql:7b-q4_0',
    system='''Here is the database schema that the SQL query will run on:
CREATE TABLE taxi (
    VendorID bigint,
    tpep_pickup_datetime timestamp,
    tpep_dropoff_datetime timestamp,
    passenger_count double,
    trip_distance double,
    fare_amount double,
    extra double,
    tip_amount double,
    tolls_amount double,
    improvement_surcharge double,
    total_amount double,
);''',
    prompt='get all columns ending with _amount from taxi table',
)

print(r['response'])
```


... it should make a lot more things easier to implement :rocket: :sloth:

**Comment by adriens** [comment]
![image](https://github.com/ollama/ollama/assets/5235127/d0daf0a5-6e19-415b-bf08-d65c17791719)
