### ISSUE TITLE
Change the default 11434 port?

### ISSUE THREAD

**Issue by CHesketh76** [ollama/ollama#2194]
I am getting this error message ```Error: listen tcp 127.0.0.1:11434: bind: address already in use``` every time I run ```ollama serve```.  Would it be possible to have the option to change the port?

**Comment by CHesketh76** [comment]
Yes, i killed the process that was using it but I am still getting this error message.

**Comment by pdevine** [comment]
Hey @CHesketh76 This is covered in the [FAQ](https://github.com/ollama/ollama/blob/main/docs/faq.md#how-can-i-expose-ollama-on-my-network), but the way to do it is with the `OLLAMA_HOST` env variable. You can use something like `OLLAMA_HOST=127.0.0.1:11435 ollama serve` to start ollama serving on port 11435.

**Comment by mxyng** [comment]
What platform are you on? If it's on macOS and you're using the Mac app, the app starts an instance of ollama on the default port. This means you don't need to run `ollama serve`. If you need to configure ollama for some reason, the FAQ as a few pointers on how to do that for macOS

**Comment by JodyWi** [comment]
> Hey @CHesketh76 This is covered in the [FAQ](https://github.com/ollama/ollama/blob/main/docs/faq.md#how-can-i-expose-ollama-on-my-network), but the way to do it is with the `OLLAMA_HOST` env variable. You can use something like `OLLAMA_HOST=127.0.0.1:11435 ollama serve` to start ollama serving on port 11435.

OLLAMA_HOST=127.0.0.1:11435 ollama serve | Works thanks @pdevine

**Comment by schnow265** [comment]
I found out why. If you are on Linux and are having this issue when installing bare metal (using the command on the website) and you use systemd (systemctl), ollama will install itself as a systemd service. You can run `sudo systemctl status ollama.service` to verify this. Which also means that you don’t need to `serve`.

**Comment by YokeYao** [comment]
> I found out why. If you are on Linux and are having this issue when installing bare metal (using the command on the website) and you use systemd (systemctl), ollama will install itself as a systemd service. You can run `sudo systemctl status ollama.service` to verify this. Which also means that you don’t need to `serve`.

It is ture. It is runningitself??!

**Comment by michelle-chou25** [comment]
No if I don't "ollama serve" in linux,  I can't run a model by "ollama run <model>", the error msg is"Can't connect to Ollama App, Is it running?"

**Comment by michelle-chou25** [comment]
And I changed the config file of Ollama, added "Environment="OLLAMA_HOST=0.0.0.0:80", but it still showed the listened address is 11434 when I run a model.

**Comment by u1vi** [comment]
Well I have the same issue in docker. 

`docker run -d --gpus=all -v ollama:/root/.ollama -p 11435:11435 -e OLLAMA_HOST="127.0.0.1:11435" --name ollama2 ollama/ollama serve`

one container already run on 11434 port, I want to up second api. Even if I set the `OLLAMA_HOST` it still try to use 11434

This is the port message shown, when I run `docker ps`:

`11434/tcp, 0.0.0.0:11435->11435/tcp, :::11435->11435/tcp`

**Comment by ichux** [comment]
> > And I changed the config file of Ollama, added "Environment="OLLAMA_HOST=0.0.0.0:80", but it still showed the listened address is 11434 when I run a model.
> 
> Maybe you miss wrote your config file? In Linux (Ubuntu), if you run `sudo nano /etc/systemd/system/ollama.service` you can modify it like this:
> 
> ```yaml
> [Unit]
> Description=Ollama Service
> After=network-online.target
> 
> [Service]
> ExecStart=/usr/local/bin/ollama serve
> User=ollama
> Group=ollama
> Restart=always
> RestartSec=3
> Environment="PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin"
> Environment="OLLAMA_HOST=0.0.0.0:5050"
> Environment="OLLAMA_DEBUG=1"
> 
> [Install]
> WantedBy=default.target
> ```

It's cool to do this after the above

> sudo systemctl daemon-reload; sudo service ollama restart

**Comment by jokerssssss9999** [comment]
windows 中如何修改

C:\Users\Administrator>OLLAMA_HOST=127.0.0.1:11435 ollama serve
'OLLAMA_HOST' 不是内部或外部命令，也不是可运行的程序

**Comment by benjaminchensz** [comment]
> windows 中如何修改
> 
> C:\Users\Administrator>OLLAMA_HOST=127.0.0.1:11435 ollama serve 'OLLAMA_HOST' 不是内部或外部命令，也不是可运行的程序

把这个写入windows的环境变量设置中。

**Comment by hemangjoshi37a** [comment]
is it possible to provide port with `ollama serve` command ?

**Comment by pdevine** [comment]
@hemangjoshi37a yes, use the `OLLAMA_HOST` env variable w/ `ollama serve`. This is covered in the [FAQ](https://github.com/ollama/ollama/blob/main/docs/faq.md#how-can-i-expose-ollama-on-my-network)

**Comment by dyh2024** [comment]
> No if I don't "ollama serve" in linux, I can't run a model by "ollama run ", the error msg is"Can't connect to Ollama App, Is it running?"

The same problem!

**Comment by pdevine** [comment]
@dyh2024 You need to also tell `ollama run` the correct port to connect to using `OLLAMA_HOST`. You can use `OLLAMA_HOST=localhost:<port> ollama run <model>`.

**Comment by dyh2024** [comment]
@pdevine I changed to OLLAMA_HOST=0.0.0.0:6006,  Before ollama run <model>, I had done export OLLAMA_HOST=0.0.0.0:6006, but has problem， Maybe must set to localhost not 0.0.0.0 before ollama run <model> ？

**Comment by pdevine** [comment]
@dyh2024 use `OLLAMA_HOST=localhost:6006 ollama run <model>` to run a model. Use `OLLAMA_HOST=0.0.0.0:6006 ollama serve` to start the ollama server.

**Comment by dyh2024** [comment]
> @dyh2024 use `OLLAMA_HOST=localhost:6006 ollama run <model>` to run a model. Use `OLLAMA_HOST=0.0.0.0:6006 ollama serve` to start the ollama server.

Thank you!

**Comment by dyh2024** [comment]
@pdevine Thank you!

**Comment by njtan142** [comment]
For those who installed this on [WSL](https://ubuntu.com/desktop/wsl)

If you did: 
- install using curl
- run `ollama run llama3.1`
- then exited using `Ctrl+d` after the model is downloaded

Then there's a good chance that the service is still running. Check your browser (or terminal) with the default
url: http://127.0.0.1:11434/ 

It will respond with `Ollama is running`

**Comment by sanketss84** [comment]
> > Environment="OLLAMA_HOST=0.0.0.0:5050"

This line right here saved me. 11434 port was just not working no matter what I did.
Thanks

**Comment by hdnh2006** [comment]
> > > Environment="OLLAMA_HOST=0.0.0.0:5050"
> 
> This line right here saved me. 11434 port was just not working no matter what I did. Thanks

More than welcome! I'm happy my suggestion helped you!

**Comment by 522315428** [comment]
请问在docker中如何修改对应的配置文件

**Comment by Arshil-Akkala** [comment]
> Environment="OLLAMA_HOST=0.0.0.0:5050"

where do I put this?

**Comment by hdnh2006** [comment]
> > Environment="OLLAMA_HOST=0.0.0.0:5050"
> 
> where do I put this?

Please read my comment if you use Linux, I don't know for other OS: https://github.com/ollama/ollama/issues/2194#issuecomment-2133514433

**Comment by jaindinkar** [comment]
Select an unused port and update the Ollama service config, do daemon-reload, and restart the service. 
Config example:
 ```
### Anything between here and the comment below will become the new contents of the file
[Service]
Environment="OLLAMA_HOST=0.0.0.0:11434"
Environment="OLLAMA_DEBUG=1"
### Lines below this comment will be discarded
```

**Comment by OhMy-Git** [comment]
> windows 中如何修改
> 
> C:\Users\Administrator>OLLAMA_HOST=127.0.0.1:11435 ollama serve 'OLLAMA_HOST' 不是内部或外部命令，也不是可运行的程序

前面要加上 set 

![Image](https://github.com/user-attachments/assets/073c02c2-9c04-47b0-8cd0-59cb4ece2a40)

**Comment by mehlkopf** [comment]
@mxyng Have you found a solution for the Mac app? Thank you!

**Comment by jokerssssss9999** [comment]
> > windows 中如何修改
> > C:\Users\Administrator>OLLAMA_HOST=127.0.0.1:11435 ollama serve 'OLLAMA_HOST' 不是内部或外部命令，也不是可运行的程序
> 
> 前面要加上 set
> 
> ![Image](https://github.com/user-attachments/assets/073c02c2-9c04-47b0-8cd0-59cb4ece2a40)
我已经搞定了  谢谢了

**Comment by bmeyer99** [comment]
I got sick of waiting for this so I made my own with the help of Claude. Extremely simple concept, just answer the request on ingest, proxy to another port where Ollama is running and capture the metrics along the way. Your clients have no idea the proxy is there, it runs on 11434 and changes Ollama to 11435. Includes /metrics for Prometheus and /analytics for detailed per-request analytics. Please check it out here: https://github.com/bmeyer99/Ollama_Proxy_Wrapper
Vey simple and straightforward you just clone it, run 3 commands (dependencies, prep_install, run it).  I need to make it into a service tomorrow. please enjoy.

**Comment by erturkkadir** [comment]
in my case i forgot to update bash hence each time i ve been getting server not started, here is the fix
```
nano ~/.bashrc 
export OLLAMA_HOST=0.0.0.0:1234
