### ISSUE TITLE
Go API client: make base URL and http client public fields

### ISSUE THREAD

**Issue by slimsag** [ollama/ollama#2199]
It would be nice if these were public fields:

https://github.com/ollama/ollama/blob/main/api/client.go#L23-L24

`ClientFromEnvironment` is good, but there are cases where supplying one's own http client, transparent, etc. may be quite useful. It's strange to not be able to supply these in a client library.

Just thought I'd leave this feedback here, feel free to close if not helpful :)

**Comment by mxyng** [comment]
The Go client is intended to be used for the CLI and not really intended for public use

**Comment by pdevine** [comment]
Hey @slimsag you can use `NewClient()` and pass in your own `base` and `http` variables. Sorry for the long delay in responding!
