### ISSUE TITLE
ollama is stuck when translate language

### ISSUE THREAD

**Issue by MunhakKim** [ollama/ollama#2200]
ollama is stuck when i ask to translate language.
In my case,  i put it in like '한글로' for prompt which means 'in Korean' after English output.
Sometimes ollama could translate perfectly and stable, but mostly ollama is stuck. 
I think if there is a problem in text generation, It should be pause not is broken.
In this case, **i have to restart ollama**.

I guess it is about string format from streaming.

i am using docker image from docker hub.
using this command 'docker exec -it ollama ollama run mistral'
or api.

version: v0.1.21 (i have been tested from v0.1.18~)
model: mistral, mixtral latest, llama2 etc.

sorry for no logs. 
But it is easy to cause problems when you put '한글로' in prompt.

**Comment by mxyng** [comment]
Are you still having issues with this? I just tested that exact prompt with the latest release (0.1.29) on mistral without any hanging.

While the vanilla models are good with translation tasks, they're even better with a good system prompt. Also for reproducible results, I would suggest setting temperature to 0

**Comment by MunhakKim** [comment]
No it was fixed this problem from 0.1.27(i guess). now i am happy to use ollama!! thank you for answer :)
