### ISSUE TITLE
Can Ollama run more than one instance on Ubuntu

### ISSUE THREAD

**Issue by myrainbowandsky** [ollama/ollama#2201]
Since Ubuntu is multi-user operation system.
But I found if sb (not necessarily sudo user) is using Ollama, the other users cannot use it. How to deal with it?

**Comment by wookayin** [comment]
`OLLAMA_HOST=0.0.0.0:<some-different-port> ollama run`

Ollama can run without sudo permissions of course.

**Comment by pdevine** [comment]
If two requests happen at the same time, ollama will block until the first request is finished. We'll look at handling concurrent requests in a future version.

Going to close this as a duplicate of #358
