### ISSUE TITLE
Model not found

### ISSUE THREAD

**Issue by gaborkukucska** [ollama/ollama#2203]
First of all, I must say, what a great piece of software Ollama is! THANK YOU for all your work everyone!!!
I am trying to setup MemGPT to use CodeLlama via `ollama serve`
I've made sure that I've pulled the exact model I want before start up the api but I still get an error when MemGPT is trying to inference the LLM.

I start ollama with:
```
OLLAMA_HOST=0.0.0.0:63321 ollama serve
```

then set MemGPT up like this:
```
? Select LLM inference provider: local
? Select LLM backend (select 'openai' if you have an OpenAI compatible proxy): ollama
? Enter default endpoint: http://127.0.0.1:63321
? Enter default model name (required for Ollama, see: https://memgpt.readme.io/docs/ollama): codellama:7b-instruct-q6_K
? Select default model wrapper (recommended: chatml): chatml
? Select your model's context window (for Mistral 7B models, this is probably 8k / 8192): 8192
? Select embedding provider: local
? Select default preset: memgpt_chat
? Select default persona: sam_pov
? Select default human: basic
? Select storage backend for archival data: local
```

error log:
```
Exception: API call got non-200 response code (code=404, msg={"error":"model 'codellama:7b-instruct-q6_K' not found, try pulling it first"}) for address: http://127.0.0.1:63321/api/generate. Make sure that the ollama API server is running and reachable at http://127.0.0.1:63321/api/generate.
```

The model works perfectly well if I do:
```
ollama run codellama:7b-instruct-q6_K
```

**Comment by BruceMacD** [comment]
It could be that you're connecting to a different ollama instance when you run directly if `OLLAMA_HOST` isn't set for your environment. 

Try this: `OLLAMA_HOST=0.0.0.0:63321 ollama pull codellama:7b-instruct-q6_K`

**Comment by gaborkukucska** [comment]
> It could be that you're connecting to a different ollama instance when you run directly if `OLLAMA_HOST` isn't set for your environment.
> 
> Try this: `OLLAMA_HOST=0.0.0.0:63321 ollama pull codellama:7b-instruct-q6_K`

that command just tells me to use `ollama serve` instead... also, MemGPT hits the correct ollama api that I launch from the same environment where I pulled the model into...

1. activate the environment,
2. then 'ollama pull the-model-name' to download the model I need,
4. then `ollama run the-model-name` to check if all OK.
5. then 'ollama serve` to start the api.
6. then `memgpt configure` to set up the parameters
7. finally `memgpt run` to initiate the inference

On top of the above mentioned, here is what I see on the ollama side when MemGPT is trying to access:
```
[GIN] 2024/01/27 - 11:31:00 | 404 |    2.237327ms |    192.168.1.31 | POST     "/api/generate"
```

**Comment by mxyng** [comment]
ollama without OLLAMA_HOST use 127.0.0.1:11434 by default so unless that's set to 0.0.0.0:63321 for both server and client, it'll use 127.0.0.1:11434 regardless of python environment

**Comment by cheginit** [comment]
You also need to pass the location where the models are. Here's the default location for Linux:

```console
OLLAMA_MODELS=/usr/share/ollama/.ollama/models OLLAMA_HOST=127.0.0.1:11434 ollama serve
```

Look [here](https://github.com/ollama/ollama/blob/main/docs/faq.md#where-are-models-stored) for other OSs.

**Comment by pdevine** [comment]
I'm going to go ahead and close this as answered. @gaborkukucska you just need the `OLLAMA_HOST` variable set correctly for both the client and the server. I hope you got it working!

**Comment by gaborkukucska** [comment]
> I'm going to go ahead and close this as answered. @gaborkukucska you just need the `OLLAMA_HOST` variable set correctly for both the client and the server. I hope you got it working!

Yes all good 👍 Thanks for your reply!

**Comment by Anna-Pinewood** [comment]
there is no clear instructions of what to fix... Could someopne please provide what to do to resolve issue? step by step?

**Comment by BruceMacD** [comment]
@Anna-Pinewood we will need a bit more context, this error can be a result of a few different scenarios. In this case ollama was running on a remote host, in other cases it may be that the model or tag name or not being specified correctly.

**Comment by Anna-Pinewood** [comment]
@BruceMacD 
Thank you for answering.

Actually the problem was magically solved. 

I will describe how i run ollama, maybe it will help someone

1. Run ollama server and model in different terminal windows. Default llama port in taken so i use an alternative one.
```
OLLAMA_MODELS=/usr/share/ollama/.ollama/models OLLAMA_HOST=127.0.0.1:11436 ollama serve                     
```
```
OLLAMA_MODELS=/usr/share/ollama/.ollama/models OLLAMA_HOST=127.0.0.1:11436 ollama run qwq:32b-preview-q4_K_M
```

2. My minimal python ollama run code
```
import requests

data = {
    "model": "qwq:32b-preview-q4_K_M",
    "prompt": "What is the meaning of life?",
}
llama_port = 11436
url = f"http://localhost:{llama_port}/api/generate"
response = requests.post(url, json=data)
response
```

It works, it's just acting strange, returning response like a single word....
But the initial problem is gone.
```
>>> eval(response.text.split('\n')[0])
{'model': 'qwq:32b-preview-q4_K_M', 'created_at': '2024-12-24T08:24:39.006089838Z', 'response': 'The', 'done': False}
>>> eval(response.text.split('\n')[1])
{'model': 'qwq:32b-preview-q4_K_M', 'created_at': '2024-12-24T08:24:39.391406647Z', 'response': ' meaning', 'done': False}
>>> eval(response.text.split('\n')[2])
{'model': 'qwq:32b-preview-q4_K_M', 'created_at': '2024-12-24T08:24:39.771685857Z', 'response': ' of', 'done': False}
>>> eval(response.text.split('\n')[3])
{'model': 'qwq:32b-preview-q4_K_M', 'created_at': '2024-12-24T08:24:40.157191278Z', 'response': ' life', 'done': False}
```

The problem I had looked like this:
"error": "model not found, try pulling if first", even though i've already pulled it and it is definitely available.
![image](https://github.com/user-attachments/assets/b0236756-fb63-419e-8465-c4325a75cbeb)
