### ISSUE TITLE
Mixtral model issue ?

### ISSUE THREAD

**Issue by Nuranto** [ollama/ollama#2206]
Hello,

I wanted to test mixtral model, so I did `ollama run mixtral`

But after saying Hello, the model answers me : 
```
Hello! Welcome to Bra****op.AI. How can I assist you today?
[...]
```

It's like ollama made me downloaded some fine-tuned model ?

**Comment by swip3798** [comment]
If you run `ollama ls` you can see the ID of the model that you pulled. If you compare that ID with the mixtral tag you wanted to download [https://ollama.ai/library/mixtral/tags](https://ollama.ai/library/mixtral/tags), it should be the same. If they are the same, then it's probably just mixtral being a little too creative.

**Comment by Nuranto** [comment]
I use `mixtral:latest	7708c059a8bb`. which correspond to mixtral:latest

Creative, why not, but welcoming user with a link to a chinese commercial website ? Seems strange.

**Comment by jmorganca** [comment]
Hi yes please do re-pull, there may have been an issue with the weights or conversion (sorry if that's the case). If you're still seeing the issue let me know :)
