### ISSUE TITLE
Magicoder-S-DS-6.7B-GGUF is not working

### ISSUE THREAD

**Issue by pablovalle** [ollama/ollama#2207]
Hi,

I wanted to run a specific version of magicoder ([Magicoder-S-DS-6.7B-GGUF](https://huggingface.co/TheBloke/Magicoder-S-DS-6.7B-GGUF/blob/main/magicoder-s-ds-6.7b.Q5_K_S.gguf)) so I started creating a customize Modelfile as follows:

```
FROM ./magicoder-s-ds-6.7b
TEMPLATE """{{- if .System }}
<|im_start|>system {{ .System }}<|im_end|>
{{- end }}
<im start|>user
{{ .Prompt }}<|im_end|>
<|im start|>assistant
"""
PARAMETER stop "<|im_start|>"
PARAMETER stop "<|im_end|>"
```

Then I ran the following command:

```
ollama create pruebaPablo -f ./Modelfile
```

Everyting worked properly with the following output:

```
transferring model data
creating model layer
creating template layer
creating system layer
creating parameters layer
creating config layer
using already created layer sha256:7f0011bbe58c5bd2b3aa81abaa595d0e2181d7fa287a39a5899e7bb9a3117262
writing layer sha256:fbd3a46e44915917bdfe24b8c1cb7bf74f49cf12761b45c9787842b477c5a8fe
using already created layer sha256:f02dd72bb2423204352eabc5637b44d79d17f109fdb510a7c51455892aa2d216
writing layer sha256:f37e567548df4ecb18a3ef059c296cc50f0e0a11e5c1eb04b427688b1d4ea3ea
writing manifest
success
```

But, then, when I execute the run instruction it gets stuck loading and I can not send anything to the model as you can see in the following image:

![image](https://github.com/ollama/ollama/assets/55744688/1a9dd209-fbf3-437c-8689-cfa57e85cc3b)

Is there anything I am doing wrong?

Many thanks,
Pablo.

**Comment by sola97** [comment]
same issue
![image](https://github.com/ollama/ollama/assets/17388849/500d87df-0a69-4bd6-bafc-3ed0f20820f3)

**Comment by sola97** [comment]
> Can you attach the ollama server logs when loading this model? Also, what platform (system architecture, operating system, accelerator (GPU) if any) are you using?

I suspect it might be due to insufficient GPU memory. After restarting my computer, the model can be fully loaded into RAM without getting stuck.
