### ISSUE TITLE
Keep models in RAM

### ISSUE THREAD

**Issue by LeoPiresDeSouza** [ollama/ollama#2210]
I am testing llama2:7b models both using ollama and calling direct from a langchain python  script.
My models are stored in an Ubuntu server withu 12 cores e 36 Gb of ram, but no GPU.
When I cal the model direct from python, setting memlock parameter to true, my memory usage goes above 6Gb, but when using ollma it stays below 3Gb.
It seams that ollama is not keeping the model entirely in ram, and it is taking a long time to response.

Is there a parameter like memlock to be set in Ollama to make it use my ram extensivelly?

I have installed Ollama using curl https://ollama.ai/install.sh | sh.

**Comment by easp** [comment]
Ollama automatically unloads models from memory after 5 minutes of inactivity. That will be user-configurable in the next version 0.1.23.  

Another thing to be aware of is that models are memory mapped and so they don't show up in process memory. They are instead accounted for in file cache.

**Comment by pdevine** [comment]
Going to close this since #2146 has merged.
