### ISSUE TITLE
Mistral v0.2 hangs after repeatedly writing same token

### ISSUE THREAD

**Issue by arch-user-france1** [ollama/ollama#2211]
<img width="1446" alt="grafik" src="https://github.com/ollama/ollama/assets/72965843/daff8519-4262-46f1-b52d-d11b246355b4">

```bash
➜  ~ ollama ls              
NAME            ID              SIZE    MODIFIED   
mistral:v0.2    61e88e884507    4.1 GB  2 days ago
```

Crashed, the ollama runner using 300 MB of RAM without active CPU or GPU usage.
Running on MPS. Conversation can not be continued anymore, ollama's text generation API hangs:
```bash
Looking forward to our interaction! Let me know if you have any specific requests or questions. Cheers! 🤘🏼💻💪🏼🌠🚀✨🔬🧩👨‍💻👩‍💻🐶😸🌹🏛️🌅🌄🌈🌊🏖️🚴🏼‍♂️🚶🏼‍♀️🚗🚧🚢🚤🚣🏻‍♂️🚣🏻‍♀️🛳️🚤🚢🛵🏋️🎾🤽🏻‍♂️🤸🏾‍♀️🧞🏽🧜🏼‍♂️🧜🏼‍♀️🦇🐍🕷️🕸️🌼🌱🌺🍎🍌🍊🍌🤘🏼💻💪🏼🌠🚀✨🔬🧩👨‍💻👩‍💻🐶😸🌹🏛️🌅🌄🌈🌊🏖️🚴🏼‍♂️🚶🏼‍♀️🚗🚧🚢🚤🚣🏻‍♂️🚣🏻‍♀️🛳️🚤🚢🛵🏋️🎾🤽🏻‍♂️🤸🏾‍♀️🧞🏽🧜🏼‍♂️🧜🏼‍♀️🦇🐍🕷️🕸️🌼🌱🌺🍎🍌🍊🍌🍇🥝🤴🏻🤴🏼👸🏽👸🏼🦄🐲🐉🐉🦋🐘🐘🧁🧁🎂🍰🥧🧁🧀🧀🌭🌮🍔🍟🍕🍖🍲🍱🥙🏴󠁧󠁢󠁥󠁮󠁧󠁿🇩🇪🇫🇷🇯🇵🇹🇼🇨🇭🇦🇹🇱🇻🇵🇸🇪🇸🇮🇹🇬🇧🇯🇴🇩🇿🇨🇼🇪🇪🇱🇾🇲🇪🇷🇸🇭🇷🇹🇹🇮🇸🇬🇧🇵🇺🇿🇦🇫🇷🇨🇩🇳🇱🇭🇷🇭🇾🇳🇴🇩🇰🇪🇸🇮🇸🇫🇷🇩🇰🇧🇪🇬🇧🇯🇵🇦🇺🇨
🇭🇩🇿🇱🇹🇲🇦🇷🇸🇫🇷🇧🇬🇮🇳🇪🇸🇭🇷🇲🇨🇳🇱🇯🇵🇩🇿🇩🇰🇪🇸🇫🇷🇦🇺🇹🇼🇧🇬🇭🇳🇱🇮🇶🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🥝🤴🏻🤴🏼👸🏽👸🏼🦄🐲🐉🐉🦋🐘🐘🧁🧁🎂🍰🥧🧁🧀🧀🌭🌮🍔🍟🍕🍖🍲🍱🥙🏴󠁧󠁢󠁥󠁮󠁧󠁿🇩🇪🇫🇷🇯🇵🇹🇼🇨🇭🇦🇹🇱🇻🇵🇸🇪🇸🇮🇹🇬🇧🇯🇴🇩🇿🇨🇼🇪🇪🇱🇾🇲🇪🇷🇸🇭🇷🇹🇹🇮🇸🇬🇧🇵🇺🇿🇦🇫🇷🇨🇩🇳🇱🇭🇷🇭🇾🇳🇴🇩🇰🇪🇸🇮🇸🇫🇷🇩🇰🇧🇪🇬🇧🇯🇵🇦🇺🇨🇭🇩🇿🇱🇹🇲🇦🇷🇸🇫🇷🇧🇬🇮🇳🇪🇸🇭🇷🇲🇨🇳🇱🇯🇵🇩🇿🇩🇰🇪🇸🇫🇷🇦🇺🇹🇼🇧🇬🇭🇳🇱🇮🇶🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹🇹^C

>>> General tech news and trends
⠹ 
```

New conversations can not be started. Bug may only be reproduced with the correct seed, as mistral usually does not have any temperature problems.

**Comment by jukofyork** [comment]
Make sure you use the exact promp format from the huggingface repository tokenizer. Mistral and Mixtral are super picky about the prompt format and just adding an extra space can make them go crazy (IIRC the default template from the ollama model download page adds a newline after the prompt that shouldn't be there).

**Comment by arch-user-france1** [comment]
I did not modify the prompt format.

**Comment by jukofyork** [comment]
> I did not modify the prompt format.

Seem my edit above.

**Comment by jukofyork** [comment]
It won't fix the crash though so apologies if that's what you meant :)

It definitely worth double checking every template you use on huggingface IMO as a lot of the local LLMs are severely hurt by them and nearly all on the official ollama download page are slightly wrong.

**Comment by arch-user-france1** [comment]
Thank you for your help. Yeah, I haven't modified the prompt format of Ollama, and I indeed reported the bug because of the crash, and not because of the problem with the model. Still, thank you for your suggestions.

**Comment by pdevine** [comment]
This was fixed a while ago, but we lost track of the issue. I'll go ahead and close it out.
