### ISSUE TITLE
Interleaving text and images (for few-shot learning)

### ISSUE THREAD

**Issue by delenius** [ollama/ollama#2213]
It does not appear to be possible (e.g. with llava) to interleave images and text (or is it?).

This would be necessary in order to give some few-shot examples of image-text pairs, and then a final image that we want to generate text for. For example, the [OpenAI API](https://platform.openai.com/docs/guides/vision) allows for this by having the `content` field be a list, where each entry can be either text, or a base64-encoded image. (The examples in their docs do not show it, but it is indeed possible to interleave images and text arbitrarily using that API.)

I am not sure this is possible with the underlying llava model (or others), but if it is, it would be a great feature to have.

**Comment by pdevine** [comment]
Thank you for the feature request!

Unfortunately it's not currently possible to do this. The new `MESSAGE` command in the Modelfile doesn't _yet_ support adding images, and I think there's probably some work that would need to be done to properly interpret older images.

**Comment by mountaineerbr** [comment]
Outcome will be random. You may try it yourself to even know what differences may arise.

What we do in my OpenAI (and Ollama) API warping is, leave images the last items of a list of input prompts. 

Indeed, I see that interleaved image and text and seem  a way of organising stuff. But on USENET, for e.g., or I ahve it myself, use links such as "text[*]", an that mark links to the first, second or third, or whatever reference, is one way out.

**Comment by jmorganca** [comment]
Hi there, this is now possible using the `/api/chat` or the `/v1/chat/completions` API (which supports base64-encoded images).

For the `/api/chat` endpoint, interleaving messages of text/images will automatically combine them into one message now.

Let me know if you have any issues with this!
