### ISSUE TITLE
Batching

### ISSUE THREAD

**Issue by varunshenoy** [ollama/ollama#2215]
Is there any plan to support batching prompts in Ollama? Thank you! Would love to use this to automate some local workflows with higher throughput.

**Comment by pdevine** [comment]
You can actually already do this w/ piping in the CLI.
`echo "Why is the sky blue?\nList some cool facts" | ollama run mistral`

You can alternatively save the prompts to a text file and feed them in with:
`ollama run mistral < textfile.txt`

Hopefully this is helpful! I'm going to close the issue.

**Comment by varunshenoy** [comment]
I don't think this would actually perform batching. It just seems to answer questions sequentially. Ideally I want to batch together 4-5 different prompts in the same forward pass.

<img width="743" alt="SCR-20240126-oniz" src="https://github.com/ollama/ollama/assets/10859091/f2a941cf-f18e-4f44-96c2-62ed553f869d">
