### ISSUE TITLE
:link: Please add HF (HuggingFace) model link to `duckdb-nsql` :duck: 

### ISSUE THREAD

**Issue by adriens** [ollama/ollama#2218]
# :grey_question: About

Recently, [`duckdb-nsql`](https://ollama.ai/library/duckdb-nsql) has been added to `ollama` library:

- https://github.com/ollama/ollama/issues/2193
![image](https://github.com/ollama/ollama/assets/5235127/efb2ee93-cff5-41ad-ad22-747842014d77)

**:point_right: ... but the page is lacking the HuggingFace model page.**

# :dart: Documentation request

Please add the following model [`motherduckdb/DuckDB-NSQL-7B-v0.1`](https://huggingface.co/motherduckdb/DuckDB-NSQL-7B-v0.1)  url to [`duckdb-nsql` `ollama` page](https://ollama.ai/library/duckdb-nsql): 

https://huggingface.co/motherduckdb/DuckDB-NSQL-7B-v0.1

# :moneybag: Benefits

- Better documentation
- Better indexation of `ollama` models

**Comment by jmorganca** [comment]
Added - thanks!!

**Comment by adriens** [comment]
:ok_hand: 
![image](https://github.com/ollama/ollama/assets/5235127/e105a7d1-2080-428f-a674-4789f12cfee3)

**Comment by adriens** [comment]
@jmorganca 
:thought_balloon: The only one that don't have a HF url now are:

- `codellama` :arrow_right: https://huggingface.co/codellama
- `orca2` :arrow_right: (there are many) https://huggingface.co/microsoft/Orca-2-13b
- `starcoder` :arrow_right: https://huggingface.co/bigcode/starcoder
- `stablelm-zephyr` :arrow_right: https://huggingface.co/stabilityai/stablelm-2-zephyr-1_6b
