### ISSUE TITLE
Ollama stops generating output and fails to run models after a few minutes

### ISSUE THREAD

**Issue by TheStarAlight** [ollama/ollama#2225]
Hi, I'm running ollama on a Debian server and use the oterm as the interface.
After some chats (just less than 10 normal questions) the ollama fails to respond anymore and running `ollama run mixtral` just didn't success (it keeps loading).
I noted that the same issue happened, like in #1863 . Is there a solution at the moment? Also, I'm not the administrator of the server and I even don't know how to restart ollama 😂. The serve process seems to runs as another user named ollama. Can anyone tell me how to restart it?
To developers: I can provide some debug information if you need, just tell me how to do it.
Thanks :D

**Comment by TheStarAlight** [comment]
The model I'm running include mixtral:latest and wizard-math:70b.
I have access to an NVIDIA A100 PCI-e 80GB and the inputs are all simple sentences (no more than 100 words) and I ensure that nobody else is using the GPU (I see from nvitop).

**Comment by jmorganca** [comment]
Hi @TheStarAlight, would it be possible to share which version of Ollama you are running? `ollama -v` will print this out. Thanks so much, and I'm sorry you hit this issue

**Comment by TheStarAlight** [comment]
Sure! The ollama version is 0.1.20, just installed three days ago via the shell script. Please tell me if you need more information :)

**Comment by jmorganca** [comment]
Would it be possible to test with the newest version 0.1.22, which should fix this? https://github.com/ollama/ollama/releases/tag/v0.1.22

You can download the latest version of Ollama here: https://ollama.ai/download

Keep me posted!

**Comment by glorat** [comment]
Is this a dupe issue of #1458 ?

Happened to me too on 0.1.22 with mistral on MacOS. Will post again if I can find a way to reproduce.

**Comment by TheStarAlight** [comment]
@glorat I think so, it seems this problem happens on all platforms (linux, macOS and WSL).

**Comment by TheStarAlight** [comment]
@jmorganca I'm sorry that I'm not the administrator of the server and the administrator has not responded to my request😂. I'll try it on my own computer (but it can only run <4b models, even the mistral got very slow after the first evaluation) before the ollama on the server gets updated.
Btw, how can I restart the ollama server process😂? It is started by the user ollama and I cannot stop it without administrator privilege. The process has been hanging on the server for a few days and I just cannot find a way to stop it.
Thank you!

**Comment by iplayfast** [comment]
@jmorganca I can confirm that my memory issues have seemed to gone away with my stress test. https://github.com/ollama/ollama/issues/1691 Other issues have surfaced, but I think the ollama version 0.1.22 is a winner.

**Comment by tarbard** [comment]
I'm seeing this behaviour on 0.1.22 too
After a few interactions (in this case codellama 70b) the API stops responding to ollama-webui and "ollama run codellama:70b-instruct-q4_K_M"   just shows the loading animation and never starts.    

journalctl -u ollama  doesn't show any errors, just the last successful calls, is there any way to see more detailed logs?

**Comment by designedbyclu** [comment]
I have the same issue, running version 0.1.22 with mistral

**Comment by adriancbo** [comment]
I am experiencing the same issue while running the technovangelist ﻿airenamer on version `0.1.23` with any llava. It functions initially but then hangs after a few minutes, causing the CPU usage to reach 100%. Consequently, I am unable to run any models. My system configuration is as follows:

- Ubuntu 22.04
- 2x Nvidia 4090 GPUs
- 512GB RAM

**Comment by TheStarAlight** [comment]
@jmorganca I tried the new version (0.1.22) of ollama, and broke the ollama on two separate servers with two identical inputs 😂, the problem still exists. However, I notice that the problem occurs when the context gets a bit long (~1600 Chinese characters, 7 prompts). Would it be the problem?

**Comment by TheStarAlight** [comment]
> @jmorganca I tried the new version (0.1.22) of ollama, and broke the ollama on two separate servers with two identical inputs 😂, the problem still exists. However, I notice that the problem occurs when the context gets a bit long (~1600 Chinese characters, 7 prompts). Would it be the problem?

I should have illustrated it more clearly. I'm using ollama-webui and qwen:72b (this time a different model), and I forwarded the 11434 port from the remote server for my local webui to access. After the problem happened, I saved the previous chat history and switched to another server, then tried to continue the chat before using the same prompt which caused the problem in the previous server, and it just stuck in the middle as well, just after a single evaluation ...

**Comment by lukebelbina** [comment]
I am having the same issue with latest version 0.1.24. I works for a few minutes then eventually starts hanging on every request.

**Comment by coolrazor007** [comment]
I'm seeing this on 0.1.24 as well.  How far back should I rollback in the interim?  Anyone know when this was introduced?

**Comment by jmorganca** [comment]
Sorry this is still a problem – what kind of prompt is being sent to the model – is it the same prompt over and over again, or a different one? Thanks!

**Comment by lukebelbina** [comment]
> Sorry this is still a problem – what kind of prompt is being sent to the model – is it the same prompt over and over again, or a different one? Thanks!

I am sending the same preprompt with different user message, one after another (about every 1-2 second) using llama:17b. It crashes 100% of the time within about 10 minutes.

**Comment by lips85** [comment]
I worked on ollama v0.124 on "mac m3 max 64gb".
The model worked with two models, mistral:latest and openhermes:latest, and after performing the same task several times, the CPU usage increased to 99% and stopped.

I confirmed that it was working with the GPU before the operation stopped.
Before checking the github issue, I thought it was a problem that only occurred on a specific OS (Mac silicon), but it seems to be a problem that occurs regardless of platform.

**Comment by lips85** [comment]
> Sorry this is still a problem – what kind of prompt is being sent to the model – is it the same prompt over and over again, or a different one? Thanks!

I worked on `ollama v0.124` on `mac m3 max 64gb`
The model worked with two models, `mistral:latest` and `openhermes:latest`, and after performing the same task several times, the CPU usage increased to 99% and stopped.

I confirmed that it was working with the GPU before the operation stopped.
Before checking the github issue, I thought it was a problem that only occurred on a specific OS (Mac silicon), but it seems to be a problem that occurs regardless of platform.

**Comment by TheStarAlight** [comment]
> Sorry this is still a problem – what kind of prompt is being sent to the model – is it the same prompt over and over again, or a different one? Thanks!

@jmorganca Hi, thank you for your attention. I was just doing regular chats using ollama-webui (just like using ChatGPT). But now I cannot reproduce my previous chat anymore, I just had a chat with qwen:72b with longer than 2000 Chinese characters and the problem seemed gone away. But one thing is for sure, in my previous situation (ollama 0.1.22):

> I should have illustrated it more clearly. I'm using ollama-webui and qwen:72b (this time a different model), and I forwarded the 11434 port from the remote server for my local webui to access. After the problem happened, I saved the previous chat history and switched to another server, then tried to continue the chat before using the same prompt which caused the problem in the previous server, and it just stuck in the middle as well, just after a single evaluation ...

it seemed that this chat was "poisonous" and the next prompt would crash every ollama server (at lease my 2 servers) in the first run. I'll comment if I find another similar occasion :D

**Comment by timiil** [comment]
seems we are faceing the same problem in ubuntu, no matter docker env or directly deploy ollama service , after we call the ollama http endpoint serval times, ollama http service will be hang up.

**Comment by TheStarAlight** [comment]
Is there a reproducable way to reproduce the issue? Or if is there any way that we save the verbose log?

**Comment by mjspeck** [comment]
I think I'm running into this issue as well.

**Comment by Sinan-Karakaya** [comment]
I am running on the same issue, using mistral with a pre-prompt with a Mac M1 chip. After a couple of generation, the server will not respond until I kill my request

**Comment by gOATiful** [comment]
We encounter the same problem on ubuntu 20.04.6 LTS.

**Comment by justinwaltrip** [comment]
I was able to fix this issue by removing the JSON formatting parameter for /api/generate calls

**Comment by antonsapt4** [comment]
Have the same problem, I'm on mac M2 running ollama desktop version 0.1.27
Using gemma:7b-instruct-q6_K

First boot is run, doing some curl test just to make sure it works fine. But after idle whenever sending curl again when the model boot when offloading to metal, it hang and restarted my Macbook. Its happening all the time.

Can somebody shed some light, should I uninstall and download a new Ollama or is there any setting that can fix this issues?

PS:
@justinwaltrip on Ollama desktop how to remove the JSON formatting?

**Comment by anthony-icetana** [comment]
We are experiencing the same issue on 0.1.28, using official Docker image on Ubuntu 22.04 with 8x RTX A40000.

Running `llava:34b` with images as part of the request

Will successfully process infrequent requests than suddenly hang on some request and be unresponsive to request until container is restarted.

ollama responds to health checks.

**Comment by anthony-icetana** [comment]
I was just watching this as it hit the issue.

CPU of 1 core hits 100%.

It will just hang here now until I restart the container. This is the output of `docker logs ollama`
```
encode_image_[GIN] 2024/03/08 - 06:09:12 | 200 | 19.031746157s |      172.21.0.4 | POST     "/api/generate"
time=2024-03-08T06:09:13.001Z level=INFO source=dyn_ext_server.go:171 msg="loaded 3 images"
[GIN] 2024/03/08 - 06:09:26 | 200 | 18.617710773s |      172.21.0.4 | POST     "/api/generate"
time=2024-03-08T06:09:49.931Z level=INFO source=dyn_ext_server.go:171 msg="loaded 3 images"
[GIN] 2024/03/08 - 06:10:04 | 200 | 14.109569108s |      172.21.0.4 | POST     "/api/generate"
time=2024-03-08T06:13:45.049Z level=INFO source=dyn_ext_server.go:171 msg="loaded 3 images"
[GIN] 2024/03/08 - 06:13:58 | 200 | 13.486728309s |      172.21.0.4 | POST     "/api/generate"
time=2024-03-08T06:14:55.013Z level=INFO source=dyn_ext_server.go:171 msg="loaded 3 images"
[GIN] 2024/03/08 - 06:15:07 | 200 | 12.661186052s |      172.21.0.4 | POST     "/api/generate"
time=2024-03-08T06:16:47.278Z level=INFO source=dyn_ext_server.go:171 msg="loaded 3 images"
```

nvtop:
<img width="654" alt="Screenshot_8_3_2024__2_19 pm" src="https://github.com/ollama/ollama/assets/62584182/ef14084e-2789-4168-99c9-9890e26a2062">
%

htop
<img width="2044" alt="Menubar" src="https://github.com/ollama/ollama/assets/62584182/1150e23d-1171-4ce6-92dc-07f9b2b61943">

**Comment by seanmavley** [comment]
> @justinwaltrip on Ollama desktop how to remove the JSON formatting?

@antonsapt4 Removing the json format param appears to work without issues for me.

Issue may be related to #1910

**Comment by anthony-icetana** [comment]
Note: I don't use "format": "json" and have this issue..

**Comment by jmccrosky** [comment]
I also have this issue on an M3 Max.  It seems to be somewhat random, but tends to happen more quickly with larger model or larget prompts.  For example, with one model, including only one image per prompt works consistently, but including two per prompt will trigger this issue after some runs...  With a larger model, it happens even with only one image.

**Comment by niyogrv** [comment]
#1863 and this seems to be the same issue.

**Comment by anthony-icetana** [comment]
Yes, looks to be the same issue!

🤞 that https://github.com/ollama/ollama/issues/2225 is the resolution!

**Comment by Master-Lucas** [comment]
Even in Ollama version 0.1.30, Japanese text generation stops. I've tried it once with the lightweight "mistral" and three times with "dolphin-mistral" (all 4q), and in total,  at the point of failing generation,  throwing all the input and output characters into the token counter, it stops around 3400-3600 tokens. It feels like it hangs up after generating longer texts for about 6-9 turns (Mac Sonoma14.4.1, 64GB). P.S. using terminal with this experiments, but using PageAssist webui also the same issue occures.

**Comment by jmorganca** [comment]
Hi all, this should be fixed in 0.1.31 (hanging when unicode characters are in the prompt). Further fixes for hanging are also in 0.1.32 - stay tuned!

**Comment by Destroyer** [comment]
running the 0.1.32 and the issue still persists. using CPU AVX on Debian 12 with llama3 model, gets stuck before my proxy times out after 60 seconds, reloading the page and typing the query again fixes it but it is very annoying

**Comment by NikitaDeveloperAI** [comment]
Currently running Ollama 0.1.41, this problem still persists.

**Comment by seanmavley** [comment]
@NikitaDeveloperAI this problem may hardly get a universal fix as it's like a whack-a-mole game. 

In our case, we stopped using the `format='json"`, and explicitly wrote a prompt that output in the exact json structure we want. 

For now, that appears to work with some level of predictability and consistency. Testing it more, but so far, that approach doesn't cause hanging issues with Ollama.

**Comment by thistlillo** [comment]
I am using ollama version is 0.6.1 on a linux "Rocky Linux 8.10 (Green Obsidian)", machine with four H100 80GB, I configure several Ollama servers, 1 per gpu. Very often it freezes.

With the models available today:
- Llama 3.3: it freezes every once in a while
- gemma3:latest it always freezes
- qwen2.5:latest  it always freezes

**Comment by fireblade2534** [comment]
same here with 0.6.2

**Comment by chm-dev** [comment]
RTX 3090, Windows 11
Exactly same thing as @thistlillo  

[qwen2.5-coder](https://ollama.com/library/qwen2.5-coder) 32b freezes almost instantly after loading. Sometimes you might be able to actually have one or two chats before it freezes.

**Comment by festivus37** [comment]
Same. Ollama 0.6.5.  
M3 Ultra 512 gigs.
First noticed it on Deepseek R1 671b q4 after a few queries, but then switched to Gemma 3 27b q8. It gets through about 7-10 requests and then starts freezing. The memory of the model is in use, the gpu is pegged permanently, no outputs via the api are being sent. Qutting Ollama fixes it for a short while, then it's back to the same behavior.

**Comment by Sven1403** [comment]
Same. Ollama 0.6.6 with a A16 vGPU.

First it works fine and then freeze. With ollama ps i see the model running or being stucked in "Stopping...". Only way to resolve is a reboot of the PC. Killing the ollama process isnt working.

**Comment by remidebette** [comment]
Hi guys,
Same issues with ollama  deployed on A100 40GB 
(in a kubernetes environment: helm chart 1.19.0 deploying ollama v0.9.0)

**Comment by codeking2024** [comment]
Hi cool devs!
I have a same issue using ollama version 0.9.1
After processing 3 requests, ollama won't accept any requests and stopped and not working.
Am using Deepseek R1:7b
RTX A4000 16 G/ Dual 12-Core E5-2697v2 / 128GB RAM / 240GB SSD + 2TB SSD
I hope this issue will be solved soon.
For now, I can't use local llm smoothly because after just 3 calls, it stopped and i need to restart ollama.
Good Luck

**Comment by BillShiyaoZhang** [comment]
Same issue.  Ollama v0.9.6 on Mac M4 Pro

**Comment by czaku** [comment]
same for me ollama 0.11.8 on latest macos, spinning but doesn't generate any output

**Comment by spacetime-labs** [comment]
Same issue here on version 0.11.10 of MacOS. I use the ollama app, and models stop thinking and or responding. Remain stuck in 'loading', when I go back to it loading seems to have stopped and there is no output. Sometimes, adding another prompt or starting a new converstaion seems to get it to answer, but most times it gets stuck.

**Comment by Dayal-star** [comment]
today is 24-OCT-2025 , the same is happening i am running on windows 10 and ollama version is 0.12.6.

**Comment by vijaykanade55-sys** [comment]
I have been trying to run different models on Ollama like llama 3.2 and gemma:2b since past few days, and I have been encountering the same issue of run command getting stalled. I am using Windows 10 with ollama version 0.12.6. The run command does not process further and stop almost instantly. PFA image. Can anyone fix the issue and help me resolve it?

<img width="962" height="143" alt="Image" src="https://github.com/user-attachments/assets/39e21b41-9a6e-4594-bc79-424dd56837fd" />

**Comment by ghost** [comment]
Same as @vijaykanade55-sys over here... tried different models, reinstalled ollama, reset pc, tried on different pcs (all windows 10) and no luck. it downloads the model then it stays loading... on interface and on cmd... was working fine a few weeks ago.
ollama version 0.12.9.
