### ISSUE TITLE
Request: Access to internet

### ISSUE THREAD

**Issue by zinwelzl** [ollama/ollama#2228]
Hi.

Can you add ability to reach out and pull in webpages to summarize text, etc?

**Comment by muka** [comment]
I am just a user, but I think what you are asking goes beyond the scope of this project. 

Maybe try with llamaindex? 

Example https://medium.com/@stephenc211/using-llamaindex-for-web-content-indexing-and-querying-c03cb06af80d

**Comment by jukofyork** [comment]
> Can you add ability to reach out and pull in webpages to summarize text, etc?

Take a look at: 

https://github.com/ollama-webui/ollama-webui

It now has "Retrieval Augmented Generation" and can do both now I think.
