### ISSUE TITLE
Ollama (llama2) running in VM Box on Ubuntu but /api/generate not working

### ISSUE THREAD

**Issue by Marvin-VW** [ollama/ollama#2230]
Hey, i pulled llama2 as described and im running it with 'ollama run llama2'
It is working inside the terminal with no errors, but as soon as i try to to reach it via

`curl http://localhost:11434/api/generate -d '{
  "model": "llama2",
  "prompt":"Why is the sky blue?"
}'`

it just says:

`{"error":"model "llama2" not found, try pulling it first"}`

**Comment by doganaktarr** [comment]
Hi, i have the same issue. Can i ask how you solved it?
