### ISSUE TITLE
:memo: Better description for `openchat-3.5-0106-laser`

### ISSUE THREAD

**Issue by adriens** [ollama/ollama#2234]
# :grey_question: About

In the following [tweet](https://twitter.com/ivanfioravanti/status/1751329888231915725)

![image](https://github.com/ollama/ollama/assets/5235127/47856d41-9fc1-4f4c-b2c6-40c5fd425065)

, the `openchat-3.5-0106-laser` model is known for having _Strong math capabilities without compromise!_.

**:point_right: Still on [its `ollama` page](https://ollama.ai/ifioravanti/openchat-3.5-0106-laser), there is no mention of that in the model description:**

![image](https://github.com/ollama/ollama/assets/5235127/35e6da8f-53b0-44a1-9147-e1fb7c88e6ba)

# :pray:  Documentation request

In addition to the following description:

> "A laser version of [openchat/openchat-3.5-0106](https://huggingface.co/openchat/openchat-3.5-0106)"

Would you add something like _Strong mathematics capabilities without compromise!_ 

# :moneybag: Benefits

- Better indexation (includig on Google)
- More RAG opportunities on top of `ollama` library

```sql
SELECT fts_main_model_details.match_bm25(id, 'math') AS score,
        id,
        full_desc
FROM model_details
WHERE
    score IS NOT NULL
ORDER BY score desc;
```

![image](https://github.com/ollama/ollama/assets/5235127/8a0e479c-4088-4d72-a7e0-7058847e8151)

**Comment by ivanfioravanti** [comment]
Done! Thanks @adriens

**Comment by adriens** [comment]
![image](https://github.com/ollama/ollama/assets/5235127/717e41b0-8b14-4de4-bd50-e32df52f8918)

**Comment by adriens** [comment]
:grey_question: How would it be possible to get it listed as others models (eg. `/library/{model}`) in addition to `ifioravanti/openchat-3.5-0106-laser`

**Comment by adriens** [comment]
... maybe as `library/openchat-3.5-0106 -laser` :thought_balloon:
