### ISSUE TITLE
:lady_beetle: Missing model description on `ifioravanti/bagel-hermes`

### ISSUE THREAD

**Issue by adriens** [ollama/ollama#2237]
# :grey_question: About

[`ifioravanti/bagel-hermes`](https://ollama.ai/ifioravanti/bagel-hermes) is currently missing his description:

![image](https://github.com/ollama/ollama/assets/5235127/96655c3b-8a78-43f2-99af-19420e7c884f)

# :pray: Action

:point_right: Please :

- [ ] Put a short description like for the other ones
- [ ] Put a long description on the model's page

# :moneybag: Benefits

- Better indexation
- Automated docimentation

**Comment by adriens** [comment]
Cuurent status: 
![image](https://github.com/ollama/ollama/assets/5235127/b65a5fda-56e3-41b4-9aa9-3af1e66334f9)

**Comment by bmizerany** [comment]
> [ifioravanti/bagel-hermes](https://ollama.ai/ifioravanti/bagel-hermes) is currently missing his description:

Did ifioravanti add one and we're not displaying it? If not, they'll have to add the description themselves. We avoid updating users data unless they explicitly ask us too and they cannot do it on their own.

I'm closing for now, but please reopen if you think this needs further investigation.
