### ISSUE TITLE
stablelm2 is missing in the homepage list

### ISSUE THREAD

**Issue by AntDX316** [ollama/ollama#2239]
stablelm2 --verbose is missing in the homepage list

who knows what else

**Comment by bmizerany** [comment]
@AntDX316 Are you referencing a command with the flag `--verbose`? Do you mind sharing clear steps to reproduce your bug? If you can also share you ARCH, OS, etc that would be very helpful for providing more assistance.

**Comment by AntDX316** [comment]
Someone else said to do it. I’m not sure what it does.

**Comment by bmizerany** [comment]
@AntDX316 This might be what you're looking for? 

https://ollama.com/library/stablelm2

**Comment by bmizerany** [comment]
I'm going to close this for now, but please feel free to reopen if the above model with instructions does not work as expected.
