### ISSUE TITLE
How to limit output token generated: Phi model

### ISSUE THREAD

**Issue by bm777** [ollama/ollama#2240]
From a given context + query, the model generates well the answer, but very long -> around `2000 chars`.
Is there any way to do `max_output_tokens=200` like pplx or openAI API?

This is my prompt template:
```js
_template = "You are an assistant that delivers short answers to the user inquiry from the provided context.\n\n
            context: {conditioned_passages}\n\n
            query: {query}
            answer:"
```

**Comment by jukofyork** [comment]
`num_predict`:

https://github.com/ollama/ollama/blob/main/docs/modelfile.md

I think the default is actually `-1` even though the API docs say it's 128 (I had the Llemma model run all night once by accident!).

**Comment by bm777** [comment]
Thanks :), i'm goint to put `num_predict: 40`

I noticed a kinda infinite token generation and stopped generating at some point. Maybe to prevent the early stop, could be to use stop `System:`

From
```bash
ollama show phi --parameters
```

Output
```bash
stop                           "User:"
stop                           "Assistant:"
stop                           "System:"
```

**Comment by bmizerany** [comment]
@bm777 Did `num_predict` fix your issue? If so, do you mind closing (or me closing) the issue?

**Comment by bm777** [comment]
@bmizerany somehow yes.

**Comment by bm777** [comment]
in somehow, it doesn't cut properly. @bmizerany

**Comment by bm777** [comment]
@metamec did you find a solution?

**Comment by Anish-Reddy-K** [comment]
> The problem with the num_predict 'solution' is that you end up with a truncated final sentence.

did you find a solution to this?

**Comment by metamec** [comment]
Unfortunately not, sorry.

**Comment by pdevine** [comment]
I'm going to close this since it's pretty stale a this point. I think the problem was the template wasn't correct, although it does work reasonably well with phi3, although phi3 seems to have problems when it hits the context size.
