### ISSUE TITLE
API is no longer verbose as of 0.1.18 ... could I please have it back?

### ISSUE THREAD

**Issue by maximometascript** [ollama/ollama#2244]
API is no longer verbose in logs as of v0.1.18 which is now reduced to one line for the API call. Whereas before, the log was extremely detailed. I need to know what my models are receiving verbatim in order to diagnose application syntax errors. Models like llama2 and its family learn syntax errors quickly and create strange outputs.

My setup is docker on Windows 11.

When it starts:
[v17 More Verbose.txt](https://github.com/ollama/ollama/files/14077732/v17.More.Verbose.txt)
[v18 Less Verbose.txt](https://github.com/ollama/ollama/files/14077731/v18.Less.Verbose.txt)

![image](https://github.com/ollama/ollama/assets/151481033/1d4b6c22-67fd-4dc8-9779-4c53391569ba)

After it starts and conversation continues:
[v17 Verbose.txt](https://github.com/ollama/ollama/files/14077729/v17.Verbose.txt)
[v18 Even Less Verbose.txt](https://github.com/ollama/ollama/files/14077730/v18.Even.Less.Verbose.txt)

![image](https://github.com/ollama/ollama/assets/151481033/284bcf9e-f6ec-4974-b03e-0311f2a0c6e5)

**Comment by robertvazan** [comment]
I can confirm that `OLLAMA_DEBUG=1` in latest version logs the entire conversation.

**Comment by bmizerany** [comment]
@maximometascript I hope `OLLAMA_DEBUG=1` fixed your issue. I'm closing, but please reopen if you need more assistance.

Thank you @nathanpbell and @robertvazan for your help!

**Comment by robertvazan** [comment]
@bmizerany Prompt is logged, but the streamed response is no longer logged in current version.

**Comment by maximometascript** [comment]
> @maximometascript I hope `OLLAMA_DEBUG=1` fixed your issue. I'm closing, but please reopen if you need more assistance.
> 
> Thank you @nathanpbell and @robertvazan for your help!

How do I add this environment variables in the docker command?
