### ISSUE TITLE
Invalid file magic dolphin-2.7-mixtral gguf

### ISSUE THREAD

**Issue by fschiro** [ollama/ollama#2253]
Hello, I'm having trouble creating dolphin-2.7-mixtral from a GGUF. Is the model supported?

```bash
ollama --version
ollama version is 0.1.22

cat Modelfile 
FROM ./dolphin-2.7-mixtral-8x7b.Q4_K_M.gguf

ls
config.json
dolphin-2.7-mixtral-8x7b.Q2_K.gguf
dolphin-2.7-mixtral-8x7b.Q3_K_M.gguf
dolphin-2.7-mixtral-8x7b.Q4_0.gguf
dolphin-2.7-mixtral-8x7b.Q4_K_M.gguf
dolphin-2.7-mixtral-8x7b.Q5_0.gguf
dolphin-2.7-mixtral-8x7b.Q5_K_M.gguf
dolphin-2.7-mixtral-8x7b.Q6_K.gguf
dolphin-2.7-mixtral-8x7b.Q8_0.gguf
Modelfile
README.md

ollama create dm2.7_4km -f Modelfile
transferring model data 
creating model layer 
Error: invalid file magic
```

**Comment by mxyng** [comment]
Hi, can you link the model repo?

FWIW dolphin mixtral 2.7 is available in the Ollama library if you only care about running it

**Comment by fschiro** [comment]
Here is the repo link, I'm trying to get this uncensored version: [TheBloke/dolphin-2.7-mixtral](https://huggingface.co/TheBloke/dolphin-2.7-mixtral-8x7b-GGUF)

**Comment by bmizerany** [comment]
@fschiro The model is https://ollama.com/library/dolphin-mixtral:v2.7.

Closing this issue, but feel free to reopen if you need to.
