### ISSUE TITLE
[ask] Where can I see the version of llama.cpp used for each version of ollama?

### ISSUE THREAD

**Issue by iddar** [ollama/ollama#2257]
I think it would be good to include the version of Ollama used in the release notes to know the new features.

**Comment by virt-god** [comment]
Go to the desired tag and into the llm folder there you can see the llama.cpp submodule and its version.

https://github.com/ollama/ollama/tree/v0.1.22/llm

**Comment by iddar** [comment]
Thanks a lot  :)
