### ISSUE TITLE
Unable to rebuild Ollama due to llm/payload_linux.go:7:12: pattern llama.cpp/build/linux/*/*/lib/*.so*: no matching files found

### ISSUE THREAD

**Issue by Solomin0** [ollama/ollama#2260]
I am following the developer instructions. 
Started by "git clone [ollama](https://github.com/ollama/ollama.git)"
I have go, cmake, and gcc.
I was able to sucessfully run "go generate ./"
"go build ." failed and gave me this error

```root@9a44dfc68b7a:/workspace/a2/ollama# go generate ./
root@9a44dfc68b7a:/workspace/a2/ollama# go build .
llm/payload_linux.go:7:12: pattern llama.cpp/build/linux/*/*/lib/*.so*: no matching files found
root@9a44dfc68b7a:/workspace/a2/ollama#
```

What do I need to change or what can I do? I have no experience with go so a point in the right direction to start would even be helpful.
My main goal is only to change the timeout function of ollama so if there is another way to do that please let me know.

**Comment by remy415** [comment]
@Solomin0 you need to clone it with the --recursive flag:
`git clone --depth=1 --recursive https://github.com/ollama/ollama.git`

Then from the ollama root folder:
```
go generate ./...
go build .
```

Please review the developers guide referenced on the Ollama README.md
https://github.com/ollama/ollama/blob/main/docs/development.md

**Comment by jukofyork** [comment]
It's possible you need to use a newer version of Go.

I'm running Debian 12 and the packaged Go was too old...

It's not hard to:

https://www.digitalocean.com/community/tutorials/how-to-install-go-on-debian-10

You just need to change to get the latest Go tar, etc. The guide isn't really Debian specific either as you can just installed it in your home folder, etc and then make sure the environment variables point to the downloaded version (or even symlink the Go binary).

**Comment by jukofyork** [comment]
One thing to add is that just using:

```
go generate ./...
go build .
 ```

and then copying or symlinking the create Ollama executable isn't enough to change the running Ollama and you need to be sure to restart the Ollama service - I spend 3 days trying to work out why none of the changes I was making when recompiling made any difference!

**Comment by remy415** [comment]
That’s possible too, I’m just saying that particular error message is because the llama.cpp repo wasn’t cloned because either the recursive flag wasn’t used or go generate ./… wasn’t run. The go generate scripts will pull the llama.cpp repo and fix this error.

**Comment by jukofyork** [comment]
> That’s possible too, I’m just saying that particular error message is because the llama.cpp repo wasn’t cloned because either the recursive flag wasn’t used or go generate ./… wasn’t run. The go generate scripts will pull the llama.cpp repo and fix this error.

Ah sorry, you are correct - I'm typing in my phone and didn't see the long line that said lllama.cpp in it! :)

**Comment by remy415** [comment]
> One thing to add is that just using:
> 
> ```
> go generate ./...
> go build .
> ```
> 
> and then copying or symlinking the new Ollama executable isn't enough to change the running Ollama and you need to be sure to restart the Ollama service - I spend 3 days trying to work out why none of the changes I was making when recompiling made any difference!

Oh definitely make sure you shut down the service first and remove the old binary. 

Also ensure you run “go clean” from the ollama directory if you’ve tried to build before to remove cached artifacts

**Comment by bmizerany** [comment]
@Solomin0 Looks like this issue is fixed in the latest release. Please let us know if you run into any other issues.
