### ISSUE TITLE
:link: Documentation request - Please add HF model url on `codellama` model page :pray: 

### ISSUE THREAD

**Issue by adriens** [ollama/ollama#2261]
# :grey_question: About

[`codellama` has just been released with it 70B version](https://twitter.com/ollama/status/1752034262101205450)

![image](https://github.com/ollama/ollama/assets/5235127/b5cbfa61-7ea2-4a0f-94a3-e6868fb6fb58)

:point_right: ... but on its `[ollama` library page](https://ollama.ai/library/codellama) the is no HF url:

![image](https://github.com/ollama/ollama/assets/5235127/e2f82870-8337-4e5b-9bb1-34b249ecbd4a)

# :pray: Documentation request

- If relatable, add the https://huggingface.co/codellama to the "More information" section:

![image](https://github.com/ollama/ollama/assets/5235127/305ea1fa-7efd-4cff-a468-b79a7757d867)

## :bookmark_tabs: Links

- https://huggingface.co/codellama/CodeLlama-70b-Instruct-hf
- https://huggingface.co/codellama

**Comment by adriens** [comment]
[Related tweet](https://twitter.com/rastadidi/status/1752074586525761812)

![image](https://github.com/ollama/ollama/assets/5235127/deef690c-351a-4c24-8091-82e871c2557a)

```sql
-- 🦙 Which ollama LLM model has the best score for "coding" activities
SELECT fts_main_model_details.match_bm25(id, 'coding') AS score,
    id, full_desc, url_hf
  FROM model_details
  WHERE score IS NOT NULL
  ORDER BY score desc;
```

**Comment by adriens** [comment]
[Tweet](https://twitter.com/reach_vb/status/1752016793558823160)

![image](https://github.com/ollama/ollama/assets/5235127/60fdb1de-ccf4-4b5e-af20-4fc35a7bc902)

**Comment by adriens** [comment]
[ollama.ai/library/codellama:70b-instruct](https://ollama.ai/library/codellama:70b-instruct)

**Comment by jmorganca** [comment]
https://ollama.com/library/codellama thanks @adriens

**Comment by adriens** [comment]
:clap:
