### ISSUE TITLE
feat: Support ollama's keep_alive request parameter by overwriting with ENV on `ollama serve`

### ISSUE THREAD

**Issue by BananaAcid** [ollama/ollama#2267]
It would be a great addition to be able to overwrite the keep_alive request param with an env like OLLAMA_KEEP_ALIVE to be overwriting any request to the ollama api server.

**Comment by uxfion** [comment]
Really need this feature

**Comment by pdevine** [comment]
This is implemented with #3094 . It should be available in release 0.1.29.
