### ISSUE TITLE
Update llama.cpp to support Orion models

### ISSUE THREAD

**Issue by bsbrother** [ollama/ollama#2271]
Would you mind updating your llama.cpp inside the directory llm to the latest master version of the llama.cpp repo? I would like to use Orion models with ollama.

Now submodule: llama.cpp/ 
$ git log
**commit cd4fdd**b29f81d6a1f6d51a0c016bc6b486d68def
Author: Engininja2 <139037756+Engininja2@users.noreply.github.com>
Date:   Wed Jan 24 16:18:15 2024 -0600
....

If checkout master and pull update:
$ git log
commit f2e69d28c01303ca9dc79907f89ef120a6ac4a92
Author: sharpHL <132747147+sharpHL@users.noreply.github.com>
Date:   Sun Jan 28 16:00:30 2024 +0800
    llama : add support for Orion-14B (#5118)  
    * add support for Orion-14B(https://huggingface.co/OrionStarAI/Orion-14B-Chat)

But when go generate ./..  if will auto change back to old **commit cd4fdd** .
If export OLLAMA_SKIP_PATCHING=1 , error for patches cann't apply....

Why this patches llm/patches/01-cache.diff not merge to llama.cpp?
Thank you very much!

**Comment by BruceMacD** [comment]
Thanks for opening the issue, this is resolved as of #2263 and will be in the next release
