### ISSUE TITLE
Unhandled Runtime Error

### ISSUE THREAD

**Issue by hamperia4** [ollama/ollama#2276]
Although SUPABASE_URL and SUPABASE_ANON_KEY are correct after running nvm getting below error locally:

<img width="963" alt="Screenshot 2024-01-30 at 5 33 15 PM" src="https://github.com/ollama/ollama/assets/98347762/b3e7370c-934e-4db2-ada7-1062d129a201">

Any ideas?

**Comment by jmorganca** [comment]
Hi there, I think this is best asked on the Supabase repo https://github.com/supabase/supabase

I would check out this response https://github.com/orgs/supabase/discussions/3218#discussioncomment-2021448 😊
