### ISSUE TITLE
Add Code Llama 70B model

### ISSUE THREAD

**Issue by igorschlum** [ollama/ollama#2278]
Code Llama 70B now available
--
"We just released new versions of Code Llama, our LLM for code generation. Code Llama 70B consists of two new 70B parameter base models and one additional instruction fine-tuned model — CodeLlama-70B-Instruct, which achieves the strongest HumanEval performance of any Llama model we’ve released to date. CodeLlama-70B, CodeLlama-70B-Python and CodeLlama-70B-Instruct are all available now under the same license as Llama 2 and previous Code Llama models to support both research and commercial innovation.

Code Llama 70B now available
We just released new versions of [Code Llama, our LLM for code generation](https://content.atmeta.com/n/MjY3LVBWQi05NDEAAAGQ-hqn6RRHXTr9A_sGCB8j1pjEBzeFiLec_IBvLeOIVdMk_HvX3ZdvMWg6MdwGy9Z8ZUJxjVAyAGy0jlA=). Code Llama 70B consists of two new 70B parameter base models and one additional instruction fine-tuned model — CodeLlama-70B-Instruct, which achieves the strongest HumanEval performance of any Llama model we’ve released to date.

CodeLlama-70B, CodeLlama-70B-Python and CodeLlama-70B-Instruct are all available now under the same license as Llama 2 and previous Code Llama models to support both research and commercial innovation.

We’re excited to continue our support of the OSS community with Llama and we can’t wait to see what you’ll build."
Says Meta.
it could be great to have it in Ollama 👍

**Comment by fernandobandeira** [comment]
@igorschlum I think it was already added yesterday, it's available under codellama https://ollama.ai/library/codellama/tags

**Comment by recoi1er** [comment]
It's been available for almost 12 hours

https://ollama.ai/library/codellama

**Comment by igorschlum** [comment]
@recoi1er @fernandobandeira  thank you!

**Comment by fierro** [comment]
Looking for help... TIA

could anyone point me to any resource for training 70B Instruct? 

i am having a hard time finding resources.

**Comment by igorschlum** [comment]
@fierro What do you want to do? You can ask Phind.com for help : 
https://www.phind.com/search?cache=v4d7v3zaw31bxuizoz3ymcd4
