### ISSUE TITLE
List of embedding models supported by Ollama

### ISSUE THREAD

**Issue by bm777** [ollama/ollama#2287]
What can we do to get the list of models in Ollama for the embedding support?
For example, if I want to serve a Bert model from the SBERT hg repo, how can I do it?

**Comment by bm777** [comment]
Thanks. Also, consider having a model-type filter on the Ollama website.

**Comment by easp** [comment]
Most of the embedding models use BERT architecture which Lllama.cpp doesn't yet support. Someone started to work on it, but got distracted.

https://github.com/ggerganov/llama.cpp/issues/2872

**Comment by bm777** [comment]
Thanks @easp , that was my concern. Im gonna use candle :)

**Comment by jmorganca** [comment]
Merging with https://github.com/ollama/ollama/issues/327. If you have any model requests please let me know!
