### ISSUE TITLE
LLaVA 1.6 now available

### ISSUE THREAD

**Issue by coder543** [ollama/ollama#2290]
https://llava-vl.github.io/blog/2024-01-30-llava-1-6/

Supposedly a big improvement

**Comment by Donno191** [comment]
I tested it a few hours ago 

llava web site :
![WhatsApp Image 2024-02-01 at 05 59 33](https://github.com/ollama/ollama/assets/10705947/48c9ffdd-afdb-41a5-8302-f9c34ee4ed90)

ollama : 
![WhatsApp Image 2024-02-01 at 05 59 36](https://github.com/ollama/ollama/assets/10705947/ef32e8ce-58ea-4e57-8706-abd577b15dc4)
![WhatsApp Image 2024-02-01 at 05 59 39](https://github.com/ollama/ollama/assets/10705947/cbf0f636-50ad-44ed-90b9-3b0ba4454a18)

34b_Q4KM
and 7b_fp16

Not that great of a result to be honest ! Is there anyone that can test llava-34B_fp16 ??? i just don't have enough RAM :/

**Comment by Donno191** [comment]
I would like to see if llava-1.6v-34B_fp16 from ollama models will give the same results as the llava website : image attached below
![Table](https://github.com/ollama/ollama/assets/10705947/910a29f2-3be6-470a-a92c-85fb6636e589)

**Comment by hskalin** [comment]
How can I get embeddings for an image using llava? I know about the api endpoint but what prompt should I give to it exactly?

**Comment by henryclw** [comment]
@Donno191 Hi, great to see such testing result, thanks a lot. May I ask where did you get the quantized model weights?

**Comment by Donno191** [comment]
@henryclw I used ollama's models :
ollama run llava:7b-v1.6-mistral-fp16
ollama run llava:34b-v1.6-q4_K_M
https://llava.hliu.cc/

**Comment by henryclw** [comment]
> [Donno191](/Donno191)

Thank you very much. Have a great day!

**Comment by adriens** [comment]
The results are just amazing:

![image](https://github.com/ollama/ollama/assets/5235127/e8f4dde6-3341-4e41-8730-d387f39ba4d4)
![image](https://github.com/ollama/ollama/assets/5235127/fa030b06-2e40-463a-85ea-e3279c0f1530)

**Comment by Donno191** [comment]
@adriens thanks you !

**Comment by adriens** [comment]
If you want I can make the notebook public... I'll do the storyteling later, just let me know @Donno191 :thought_balloon:

**Comment by Donno191** [comment]
@adriens  No, it is fine. No worries, have a great day :)

**Comment by chigkim** [comment]
I believe Llama.cpp does not support Llava v1.6 completely yet. There's a [PR](https://github.com/ggerganov/llama.cpp/pull/5267) for partial support.

@cmp-nct author for the PR above said:
> With these tools you can convert llava-1.6 into a llama.cpp GGUF file and it will work for inferencing.
> But as long as the image preprocessing is not integrated, it will not provide the same quality in results.
> Right now llama.cpp will create the usual 14 patches of a rectangular padded 336 pixel image.
> But the big change in llava-1.6 was the preprocessing in how patches are split up into image regions of much higher resolutions, it does not need the padding/cropping anymore.

Did Ollama folks forked llama.cpp and completed llava v1.6 architecture including image preprocessing?

**Comment by pdevine** [comment]
Going to close this, as it's now supported.

**Comment by chigkim** [comment]
It's not completed yet. Can you guys mark Llava 1.6 as partial support? It's not fully supported in Llama.cpp.

People assume it's the same as Llava 1.6, and it's not there yet.

https://github.com/ggerganov/llama.cpp/pull/5267

The dev from Llava is also chiming in there to complete.
