### ISSUE TITLE
Wingman-AI, please add the new extension

### ISSUE THREAD

**Issue by RussellCanfield** [ollama/ollama#2297]
Hi, we’re huge fans of Ollama!

We built a VSCode extension around it called Wingman:
https://marketplace.visualstudio.com/items?itemName=WingMan.wing-man

Would we be able to add it your readme? Do you accept PRs?

Thanks!

**Comment by easp** [comment]
You'll probably get quicker action on this if you submit a pull request to add the link to the README

**Comment by RussellCanfield** [comment]
> You'll probably get quicker action on this if you submit a pull request to add the link to the README

Thanks, added a PR :)

**Comment by RussellCanfield** [comment]
Merged, thank you!
