### ISSUE TITLE
Show file sizes on the models page on the ollama website

### ISSUE THREAD

**Issue by mika76** [ollama/ollama#2306]
I would like to try different models but it does not really show me how much space it will take up and on my desktop machine space is at a premium. Please show the size on the search list as well as the model detail page.

**Comment by pdevine** [comment]
We have a number of changes coming *soon* on the website, but for now you can see the size in the tags list page.
<img width="860" alt="Screenshot 2024-02-01 at 11 43 20 AM" src="https://github.com/ollama/ollama/assets/75239/031186cb-156e-4bcc-a75d-ab1f03ff91fc">

If you're pulling something like `ollama pull llama2` the tag defaults to *latest*.

cc @hoyyeva 

Going to close this, but feel free to keep commenting.

**Comment by mika76** [comment]
Appreciated thanks
