### ISSUE TITLE
Just a bit of clarity suggestion on the documentation

### ISSUE THREAD

**Issue by ercanezin** [ollama/ollama#2310]
Many thanks for this amazing project. 

I had difficulty understanding what to do when importing a local model from the 1st bullet point of the documentation in the importing section. 

The first bullet point says 

**Step 1: Write a Modelfile**
Start by creating a Modelfile. This file is the blueprint for your model, specifying weights, parameters, prompt templates and more.

`FROM ./mistral-7b-v0.1.Q4_0.gguf `

I did understand that I should create a file named Modelfile but the documentation doesn't say to populate it with the location of the file in the following code snippet. 

Thanks in advance.

**Comment by virt-god** [comment]
You're probably looking at the README, here is the full [documentation](https://github.com/ollama/ollama/blob/main/docs/modelfile.md).

Also some models are already available just take a [look](https://ollama.ai/library). This [video](https://youtu.be/xa8pTD16SnM) has a brief explanation of Modelfiles.

example for chatml
```
FROM /path/to/model.gguf

TEMPLATE """
<|im_start|>system
{{ .System }}<|im_end|>
<|im_start|>user
{{ .Prompt }}<|im_end|>
<|im_start|>assistant
"""

PARAMETER num_ctx 8192
PARAMETER stop "<|im_start|>"
PARAMETER stop "<|im_end|>"
```
