### ISSUE TITLE
Regarding the issue of ollama run model's default storage path

### ISSUE THREAD

**Issue by chengshenlian** [ollama/ollama#2312]
When I attempt to run a large 80GB model using ollama run in a Linux environment, I encounter an issue of insufficient storage space. This is because the model-related files are by default stored in the `~/.ollama` directory, and my system partition has limited space for files of this size.
I would like to know if there is a configuration or method available to change the default storage path for model files, allowing me to specify a directory with sufficient space to store these large files. Such a feature would be extremely useful for managing large models, especially in storage-constrained environments.

**Comment by easp** [comment]
https://github.com/ollama/ollama/blob/main/docs/faq.md#how-do-i-set-them-to-a-different-location

**Comment by pdevine** [comment]
Going to go ahead and close this.
