### ISSUE TITLE
add official Java SDK

### ISSUE THREAD

**Issue by adriens** [ollama/ollama#2314]
# :information_source:  Context

A few months ago, `langchain` got its sdk ported to java through [`langchain4j`](https://github.com/langchain4j/langchain4j). By doing this, its opened a lot of entreprise ready stuff and innovations on the java stack, then on native one... then on k8s, even for java developers.

For example, my team uses [`quarkus`](https://endoflife.date/quarkus-framework) and I'm about sure, getting `ollama` as a java sdk could help people amazing things on top of ``ollama.

![image](https://github.com/ollama/ollama/assets/5235127/9badc2d5-7f50-4db4-8527-abc56b104d41)

Below some examples:

- [:memo:  Quarkus Langchain4j extension in Quarkiverse](https://docs.quarkiverse.io/quarkus-langchain4j/dev/index.html)
- [:cinema: Fireside Chat: Langchain4j & Quarkus](https://www.youtube.com/live/mYw9ySwmK34?si=dRe54Dc6ZR316RoA)
- [:octocat:  Quarkus Langchain4j extension ](https://github.com/quarkiverse/quarkus-langchain4j)
- [:bird: Worthwile tweet](https://twitter.com/sebi2706/status/1753037267063513555) 
![image](https://github.com/ollama/ollama/assets/5235127/b0e8b45e-7cb8-443e-97c2-b7a4a96bf372)

# :dart: Feature request : `ollama-java`

- [ ] Port `ollama` sdk to java
- [ ] Deliver it as a Quarkus extension on [Quarkiverse](https://hub.quarkiverse.io/)

# :tickets: Related issues

- https://github.com/ollama/ollama/issues/1322

# :moneybag: Benefits

- Welcome `ollama` to [graalVM](https://www.graalvm.org/) ecosystem
- Implement [SmallRye Health](https://quarkus.io/guides/smallrye-health)
- Build apps/stack around `ollama` (to implement #2301 by queuing tasks )
- Open `olama` to java people (& enterprises stack)
- Blazing fast performances (see [📑 Quarkus : the fast, eco & DevEx-friendly framework](https://dev.to/adriens/quarkus-the-fast-eco-devex-friendly-framework-i0k) for more)
- Build faster thanks to java stack (examples below):
    - [Quarkus Extension for Apache Kafka](https://quarkus.io/guides/kafka)
    - [RabbitMQ Client](https://quarkus.io/extensions/io.quarkiverse.rabbitmqclient/quarkus-rabbitmq-client/)
    - [Neo4j client](https://quarkus.io/extensions/io.quarkiverse.neo4j/quarkus-neo4j/)
    - [Apache Kafka Client](https://quarkus.io/extensions/io.quarkus/quarkus-kafka-client/)
    - [gRPC](https://quarkus.io/extensions/io.quarkus/quarkus-grpc/)
    - [MongoDB client](https://quarkus.io/extensions/io.quarkus/quarkus-mongodb-client/)
    - [Redis Client](https://quarkus.io/extensions/io.quarkus/quarkus-redis-client/)
    - [Apache Camel](https://quarkus.io/guides/camel)

**Comment by adriens** [comment]
## :ballot_box: Twitter poll

[Poll below](https://twitter.com/rastadidi/status/1753174709569818966)

![image](https://github.com/ollama/ollama/assets/5235127/4d355c2b-4181-43a8-956a-cf5ed56cad50)

**Comment by bmizerany** [comment]
Thank you for the feedback! There is a community Java SDK [here](https://github.com/amithkoujalgi/ollama4j). Is this close to what you're looking for?

**Comment by adriens** [comment]
Indeed yes @bmizerany  , that was exactly what I was looking for :partying_face:
