### ISSUE TITLE
Apple gpu support for Linux

### ISSUE THREAD

**Issue by maxiwee69** [ollama/ollama#2315]
So maybe you know about [https://asahilinux.org/](https://asahilinux.org/), if not, it’s Fedora for m series Mac’s. But when i tried to get ollama to run on it, i got it told me `WARNING: No NVIDIA GPU detected. Ollama will run in CPU-only mode`, i know fixing this would only be a fix for such a small amount of people but i would highly appreciate it.

**Comment by MichaelFomenko** [comment]
There are no Drivers for Apple Silicon GPU in Linux yet to do GPGPU. This have nothing to do with Ollama.

**Comment by igorschlum** [comment]
@maxiwee69 as it's not a issue in Ollama, could you please close the Issue?

**Comment by maxiwee69** [comment]
But just a question, will gpu support be implemented once the drivers are supporting GPGPU?

**Comment by igorschlum** [comment]
@maxiwee69 if the GPU is visible to Ollama it will be used. On mac m1, the GPU and CPU memory are shared.

**Comment by karatekid430** [comment]
It sounds like a problem with ollama if it is looking for an Nvidia GPU on an Apple system (and potentially PC) when there maybe compute-capable GPUs of other brands.

**Comment by igorschlum** [comment]
@karatekid430 I don't see any problems on macOS, except when the memory is not sufficient for the LLM to run on the GPU. I don't use Unix or Windows. I read that with Windows, you need to have the correct driver for the Nvidia card and that the driver needs to be installed manually. Some users don't keep their drivers up to date, which can cause issues.

**Comment by atmosuwiryo** [comment]
@igorschlum The GPU is visible in fastfetch, but not in ollama.

```bash
atmosuwiryo@fedora:~$ fastfetch
                   ##  **                     atmosuwiryo@fedora
                *####****.                    ------------------
                  ###,                        OS: Fedora Linux Asahi Remix 40 aarch64
               ...,/#,,,..                    Host: Apple MacBook Air (M1, 2020)
          /*,,,,,,,,*,........,,              Kernel: Linux 6.12.1-404.asahi.fc40.aarch64+16k
        ,((((((//*,,,,,,,,,......             Uptime: 2 hours, 22 mins
       ((((((((((((((%............            Packages: 2009 (rpm)
     ,(((((((((((((((@@(............          Shell: bash 5.2.26
    (((((((((((((((((@@@@/............        Display (eDP-1): 2560x1600 @ 60 Hz (as 1706x1066) in 13" [Built-in]
  ,((((((((((((((((((@@@@@&*...........       DE: KDE Plasma 6.2.4
 ((((((((((((((((((((@@@@@@@&,...........     WM: KWin (Wayland)
(((((((((((((((((((((@@@&%&@@@%,..........    WM Theme: Breeze
 /(((((((((((((((((((@@@&%%&@@@@(........     Theme: Breeze (Dark) [Qt], Breeze [GTK3]
    ,((((((((((((((((@@@&&@@&/&@@@/..         Icons: breeze-dark [Qt], breeze-dark [GTK3/4]
        /((((((((((((@@@@@@/.../&&            Font: Noto Sans (10pt) [Qt], Noto Sans (10pt) [GTK3/4]
           .(((((((((@@@@(....                Cursor: breeze (24px)
               /(((((@@#...                   Terminal: konsole 24.8.3
                  .((&,                       CPU: Apple M1 (8) @ 3.20 GHz
                                              GPU: Apple M1 (7) @ 1.28 GHz [Integrated]
                                              Memory: 7.48 GiB / 15.28 GiB (49%)
                                              Swap: 0 B / 8.00 GiB (0%)
                                              Disk (/): 18.73 GiB / 38.19 GiB (49%) - btrfs
                                              Local IP (wlp1s0f0): 192.168.0.197/24
                                              Battery (bq20z451): 17% (57 mins remaining) [Discharging]
                                              Locale: en_US.UTF-8

```

but ollama gave me warning:

```bash
WARNING: No NVIDIA/AMD GPU detected. Ollama will run in CPU-only mode.
```

**Comment by tjex** [comment]
There is no reason on a hardware level that this shouldn't work. It's the same machine. So its either an Asahi problem or an Ollama problem. At some point, somewhere, the internal GPU is not being advertised.

Running ollama on my mac partition is blazzingly fast (32core GPU), but on the asahi partition, it's an agonizing word ... by ... word affaire :(

**Comment by tjex** [comment]
@MichaelFomenko Asahi have created open source gpu drivers 2 years ago: https://asahilinux.org/2022/12/gpu-drivers-now-in-asahi-linux/

**Comment by chrootchad** [comment]
Just when I thought I was going to be able to do something with my old m1 mini 😭

**Comment by igorschlum** [comment]
@chrootchad you can use your mac mini M1 with Ollama, it's working well if you are using MacOS and not Docker.

**Comment by chrootchad** [comment]
For anyone else in the same boat (likely repurposing old Mac silicone as a dev/home lab server), I found a solution - ramalama and it’s/podman's GPU support on Asahi Linux.

See comments here to get DeepSeek-R1 with GPU support on Asahi Linux (Ubuntu Asahi 24.04 server in my case) working:

https://github.com/containers/ramalama/issues/616#issuecomment-2629417564

**Comment by TheButlah** [comment]
This issue should be reopened. Asahi supports hardware accelerated GPGPU.

**Comment by TheButlah** [comment]
@maxiwee69 can you reopen the issue?

**Comment by SuperCowProducts** [comment]
@maxiwee69 I recently compiled ollama on Asahi Linux ALARM. It was in a Docker container, so you'll likely be able to reproduce: https://github.com/ollama/ollama/issues/17043
I then used `docker cp` to copy the binaries on my host system, and I can run ollama with `./ollama <...>`.
