### ISSUE TITLE
Run Ollama models stored on external disk

### ISSUE THREAD

**Issue by B-Gendron** [ollama/ollama#2322]
As I went through the whole documentation, I am still a bit confused about how the model are saved when doing `ollama pull` and how I can use it. For instance, as I don't have that much storage on my computer I would like to pull several models and then save the whole `/.ollama/models/blobs/` directory on an external disk.

Is it possible then to fetch the desired model from my external storage to run the model locally on my computer? More precisely, when the documentation of `pull`command says `Pull a model from a registry`, is there a way to specify such registry, and can it be a storage place like a hard disk?

**Comment by truatpasteurdotfr** [comment]
You can set the `OLLAMA_MODELS` environment value to the path of your external disk folder:
```
export OLLAMA_MODELS=/path/to/my/disk/models
./ollama serve
```

`ollama pull xxx` will create `/path/to/my/disk/models/{blobs,manifests}

**Comment by easp** [comment]
Apparently Ollama uses Docker's registry format and in the past devs have suggested that it's possible to set up your own private registry, but I've never seen any details about how to do that.

If you run `ollama pull --help` it mentions an option to use an insecure registry, which might be a piece of the puzzle.

**Comment by pdevine** [comment]
@B-Gendron as mentioned by @truatpasteurdotfr you can use the `OLLAMA_MODELS` environment variable to set that. Make certain that your external disk is formatted with a file system which supports filenames with a `:` in them (i.e. *NOT* exfat or NTFS).

The `pull` command will also work, but it's probably not what you want. When you go to run the model it will always have to download it and keep a copy of the model on your disk. I'm going to go ahead and close the issue, but feel free to keep commenting if this isn't what you're looking for.

**Comment by ForGoodTech** [comment]
@pdevine you said:

> The pull command will also work, but it's probably not what you want. When you go to run the model it will always have to download it and keep a copy of the model on your disk.

I have exactly the same scenario as @B-Gendron has. I want all the models to go to my external storage, then run each of them from there.

I tried 

`OLLAMA_MODELS=/my_folder  ollama run tinyllama
`

But the model still went to the default folder. So, how to run the model by loading it from /my_folder ?

**Comment by pdevine** [comment]
@xXWarMachineRoXx We've made it work now w/ both exfat and NTFS. You can see instructions in the [FAQ](https://github.com/ollama/ollama/blob/main/docs/faq.md#setting-environment-variables-on-windows)

**Comment by xXWarMachineRoXx** [comment]
@pdevine thanks !

**Comment by Kyuugeki** [comment]
Another solution i found was to modify the install script providing your external drive for the installation path, on OLLAMA_INSTALL_DIR variable

**Comment by thebadking** [comment]
does not work for exfat since we cant set permissions to ollama user for the directory

**Comment by kravenor** [comment]
> [@xXWarMachineRoXx](https://github.com/xXWarMachineRoXx) We've made it work now w/ both exfat and NTFS. You can see instructions in the [FAQ](https://github.com/ollama/ollama/blob/main/docs/faq.md#setting-environment-variables-on-windows)

Link returns 404

**Comment by truatpasteurdotfr** [comment]
https://docs.ollama.com/faq#how-do-i-set-them-to-a-different-location

**Comment by peterpt** [comment]
guys , in next release use the cli help of ollama to allow user to configure where models will be installed , no matter how many times i set the path for models installations path , ollama always download the models to /user/.ollama   without respecting the environment config
