### ISSUE TITLE
llava:34b is not working properly on my 36GB macbook M3 max

### ISSUE THREAD

**Issue by microflyer** [ollama/ollama#2328]
When running the model with a picture, it returned ramdom text like below. I am using ollama version 0.1.22

>>> /Users/danny/Downloads/ollama.png what is this
Added image '/Users/danny/Downloads/ollama.png'
username is first key ofthe.2!f+...0!5"0 g?..1...-
. 10dd.. t1.!.
....
...!:/.-.s[..,.,.:..)
. A.---..... .-!:
(^C

I have tried the other models, yi:34b, llava:13b, mistral... all the others are working perfectly.

**Comment by mxyng** [comment]
There's a bug that impacts llava v1.6. It'll be fixed in the next release (coming very soon). See #2296
