### ISSUE TITLE
[Feature Request] Add api/stream endpoint useful for visualization

### ISSUE THREAD

**Issue by tgraupmann** [ollama/ollama#2336]
I was looking at old projects specifically Winamp visualizers from a decade past.
Example: [Winamp Visualizations](https://www.youtube.com/watch?v=RBkhUg1oVIE)

The old school visualizers work on audio data. And I was thinking what if we used sentence encoding for inputs and outputs from Ollama for the data being used in the visualizers.

To do something like this, it would be useful to have an API endpoint like api/stream that receives data as the inputs and outputs occur.  The sentence encodings would be useful if they are vectorized and it's up to the visualizer to render them.

It would just be something interesting to look at. And of course the endpoint could be connected to RGB hardware which means your room lights would flicker when you prompt and when you get a response. It's a visual que "hey look over here" .

**Comment by bmizerany** [comment]
>To do something like this, it would be useful to have an API endpoint like api/stream that receives data as the inputs and outputs occur.

Ollama's default is to stream output. See https://github.com/ollama/ollama/blob/main/docs/api.md#generate-a-completion

We're excited to see the results of your project!

I'm going to close this now. If you have any issues with the streaming API, please let us know in a new issue. We're here to help!
