### ISSUE TITLE
Very nice to have: capabilities info for multimodal models

### ISSUE THREAD

**Issue by da-z** [ollama/ollama#2338]
Not sure if this is done already, I checked the llava info and it does not mention capabilities anywhere. Would be nice to detect via ollama show or API model info that this model supports `vision`.

API Example

`GET /api/tags`

```js
{
  //...
  "details": {
	  "parent_model": "",
	  "format": "gguf",
	  "family": "llama",
	  "families": [
		  "llama",
		  "clip"
	  ],
          "capabilities": ["vision"]
	  //...
  }
}
```

**Comment by chigkim** [comment]
As far as I know, all multimodal models Ollama support has clip in families. Other non-multimodal regular language models don't have clip in families.

**Comment by da-z** [comment]
You are right. Just read about it now https://openai.com/research/clip
