### ISSUE TITLE
Quantize and Ollama Model

### ISSUE THREAD

**Issue by stealthier-ai** [ollama/ollama#2342]
I need to quantize a full version of an Ollama model that I layered in new weights  for  a specialized use case. Is there a way to do that within Ollama? It seems like I need to clone Llama.cpp and quantize through that. There are also other ways to quantize GGUF files and then recreate an Ollama model file. Am I missing anything or is there a specific method I should be using?

**Comment by pdevine** [comment]
Hey @stealthier-ai . There are some instructions on how to do this [here](https://github.com/ollama/ollama/blob/main/docs/import.md). I'm guessing you probably want to follow the steps for [manually converting](https://github.com/ollama/ollama/blob/main/docs/import.md#manually-converting--quantizing-models) your model, but you don't actually need to clone a copy of llama.cpp if you have ollama already cloned, as there is a copy in the `llm/llama.cpp` directory. You can just run `make quantize` in that directory to build the binary.

That said, the process is less than ideal, and I've been working on creating a new way to convert/quantize models to make this a lot easier.

**Comment by bmizerany** [comment]
Going to go ahead and close this. Please let free free to reopen if you need to.
