### ISSUE TITLE
Feature Request - Support for ollama Keep alive

### ISSUE THREAD

**Issue by twalderman** [ollama/ollama#2343]
there is a new api parameter for keeping the model loaded.  it would be great to have it as a passable parameter in the modelfile.

**Comment by jmorganca** [comment]
Hi there, thanks for the issue! `keep_alive` has been added as of 0.1.23 as an API parameter. You can read more about it here: https://github.com/ollama/ollama/blob/main/docs/api.md

In essence, `keep_alive` of 0 means the model won't stay loaded, `keep_alive` of `-1` means it will stay loaded indefinitely, and `keep_alive` of another value (e.g. `5m` or `10s` or `20`) will keep the model loaded for that period of time after generation
