### ISSUE TITLE
Support for Min_p

### ISSUE THREAD

**Issue by twalderman** [ollama/ollama#2344]
I would like to have min_p as a ollama modelfile parameter.  

See the link for context of this request: https://www.reddit.com/r/LocalLLaMA/comments/17vonjo/your_settings_are_probably_hurting_your_model_why/

**Comment by mherrmann3** [comment]
Duplicate of #1142 (corresponding PR: #1825)

**Comment by BruceMacD** [comment]
Thanks for the request @twalderman, just resolving this one for now to keep things organized in the the one issue mentioned above.
