### ISSUE TITLE
Include some screenshots of ollama in the documentation

### ISSUE THREAD

**Issue by OrcVole** [ollama/ollama#2345]
A picture says a thousand words. 
It saves time reading too.

**Comment by easp** [comment]
The Ollama UI is words. How does a picture of words save time? One thing it does is make the information *less* accessible to people with vision impairments.

**Comment by AlexanderDaly** [comment]
Because people without vision impairments use their eyes to see written words. Would you require we all just use braille, instead of the written word, just because it is technically feasible? 

What do you particularly want screenshots in the documentation of? @OrcVole

**Comment by easp** [comment]
How does taking a picture of text "save time reading?"

**Comment by AlexanderDaly** [comment]
[https://openstax.org/books/writing-guide/pages/17-1-reading-images](url)

Look, the user isn't adding any more points to what they want or think the benefits are. I'd close this issue.

**Comment by OrcVole** [comment]
If you could see at a glance that the interface is text-based rather than a GUI, that would help.
Sorry for not replying sooner.

**Comment by AlexanderDaly** [comment]
Wait... but you have to run it in the shell/terminal entirely... there is already an unaffiliated project where a group is building a front end for ollama. 

I was under the assumption you wanted to compare what it looks like in the terminal when everything goes as planned. Although if you're running this on an Ubuntu distro, it's really simple.

**Comment by jmorganca** [comment]
Hi @OrcVole thanks for the issue! Ollama is mostly API & CLI at the moment, however do know we'd like to add some screenshots to ollama.com soon 😊
