### ISSUE TITLE
Use llama2-chinese or yi to ask questions in Chinese. After about 15 requests, the response request cannot be returned.

### ISSUE THREAD

**Issue by wyang-code** [ollama/ollama#2346]
Use llama2-chinese or yi to ask questions in Chinese. After about 15 requests, the response request cannot be returned.

<img width="1494" alt="image" src="https://github.com/ollama/ollama/assets/130064485/b850c5c6-d09e-472b-9592-5f2bb115c2ed">

**Comment by jmorganca** [comment]
Hi there this should be fixed as of the latest version of Ollama. Please let me know if that isn't the case!
