### ISSUE TITLE
What Modelfile options are used by Chat and what by the Embedding api endpoints

### ISSUE THREAD

**Issue by tzolov** [ollama/ollama#2349]
Both the [generate-embeddings](https://github.com/ollama/ollama/blob/main/docs/api.md#generate-embeddings) and the [chat completion](https://github.com/ollama/ollama/blob/main/docs/api.md#generate-a-chat-completion) API endpoints take the `options` as an input parameter. E.g.
> options: additional model parameters listed in the documentation for the [Modelfile](https://github.com/ollama/ollama/blob/main/docs/modelfile.md#valid-parameters-and-values) such as temperature

Additionally the Options definitions in [api/types.go](https://github.com/ollama/ollama/blob/b538dc3858014f94b099730a592751a5454cab0a/api/types.go#L87-L128) includes many [undocumented](https://github.com/ollama/ollama/blob/main/docs/modelfile.md#valid-parameters-and-values) options. 

I don't think that the embedding endpoint uses parameters like `temperature`, `topP` or alike?  

Is there a clear distinctions as what options should be used by either the chat or the embedding endpoint? And conversely what are not?

**Comment by mountaineerbr** [comment]
Hopefully, invalid options will be silently ignored by the server.

**Comment by jmorganca** [comment]
Hi @tzolov thanks for the issue and sorry for the errors resulting from unused options – this should be fixed now, Ollama will no longer hard error on unrecognized options.

Most of those options are indeed for inference - any sampling options such as temperature, min p etc may not matter for embedding generation
