### ISSUE TITLE
sentiment analysis works interactively, but it doesn't via API

### ISSUE THREAD

**Issue by Blu-Eagle** [ollama/ollama#2353]
when I use LLAMA2 asking for a sentiment analysis of a text, it works, while if I try to do the same using the API I do not get the same result, just a sort of summary of the text.

the code I use for the api is the following:

`
url = "http://localhost:11434/api/generate"

  payload = {
    "model": "llama2",
    "prompt": prompt, 
    "system": comando,
    "stream": False
  }
  payload_json = json.dumps(payload)
  headers = {"Content-Type": "application/json"}
  response = requests.post(url, data=payload_json, headers=headers)
`
where
prompt: is the text
comando: is the request: "Make the sentiment analysis of the text provided"

the same request and the same text are given interactively and only interactively I get a sentiment analysis.
I use LLAMA2 7B.

thanks for any suggestions.
Giuseppe

**Comment by ahsan123322** [comment]
are you using custom API?

**Comment by bmizerany** [comment]
Closing for now. Please reopen with a complete code example and environment information (including ollama version) if the issue persists.
