### ISSUE TITLE
Phi modelfile is incorrect

### ISSUE THREAD

**Issue by mak448a** [ollama/ollama#2356]
When I use phi ollama and put in the system prompt, it doesn't respond as well as it does in LM Studio.
Is the internal prompt in ollama correct?
LM Studio uses "Instruct:" and "Output:" as markers for the user's message and the assistant's message.

LM Studio: `{"speech": "Hi!", "program": "null"}`
Ollama: ` Welcome to our chatbot program. How can I assist you today?`

Here's the code I used:
```python
import ollama

prompt = """You are Daniel.
Give a response as a JSON object with properties "speech" and "program". Both of these keys must always be filled. Do not reply with anything else other than a JSON object.
Example of JSON object: {"speech": "Hi!", "program": "null"}

Instruct: Hello!
Output: {"speech": "Hi!", "program": "null"}
Instruct: Can you open discord?
Output: {"speech": "Certainly!", "program": "discord"}
Instruct: Can you open firefox?
Output: {"speech": "Certainly! Here it is!", "program": "firefox"}
Instruct: Turn off the computer.
Output: {"speech": "Sure, I'll do that.", "program": "shutdown"}
Instruct: Goodnight.
Output: {"speech": "You too!", "program": "null"}"""

response = ollama.chat(model="phi", 
    messages=[
        {
            "role": "system",
            "content": prompt
        },
        {
            "role": "user",
            "content": "Hello!"
        },
    ],
    stream=True
)

for chunk in response:
    print(chunk['message']['content'], end='', flush=True)
```

Also, should I post this in ollama-python instead of the main ollama repo?

**Comment by mak448a** [comment]
Well, looks like the internal modelfile was prompted differently. Instead of `Instruct:` and `Output:`, it uses `User:` and `Assistant:`.

**Comment by mak448a** [comment]
I fixed it by creating a new modelfile.

**Comment by bmizerany** [comment]
@mak448a Are you able to reproduce with the ollama CLI directory? If so, do you mind sharing the commands/steps you took?

**Comment by mak448a** [comment]
Yes. I just ran `ollama serve` along with `ollama run phi`.

**Comment by bmizerany** [comment]
@mak448a Using the latest Ollama version running the lastest phi model and using your script (unmodified) I get:

```json
{
    "speech": "Hello!"
}
```

Is that more like what you're looking for?

**Comment by bmizerany** [comment]
I'm going to close since we're unable to reproduce here. Please feel free to update / reopen if the issue persists.
