### ISSUE TITLE
Add the newest deepseek-coder models

### ISSUE THREAD

**Issue by valerybugakov** [ollama/ollama#2360]
- Instruct https://huggingface.co/deepseek-ai/deepseek-coder-7b-instruct-v1.5
- Base https://huggingface.co/deepseek-ai/deepseek-coder-7b-base-v1.5
- Instruct GGUF https://huggingface.co/LoneStriker/deepseek-coder-7b-instruct-v1.5-GGUF
- Base GGUF https://huggingface.co/dagbs/deepseek-coder-7b-base-v1.5-GGUF

**Comment by jmorganca** [comment]
This should be added – thanks for the issue!
