### ISSUE TITLE
Linux installer default path

### ISSUE THREAD

**Issue by arabek** [ollama/ollama#2361]
For some reason, the author decided that it'd be good to install to `/usr/local/bin`, `/usr/bin`, or even `/bin` - systemwide.

```
for BINDIR in /usr/local/bin /usr/bin /bin; do
    echo $PATH | grep -q $BINDIR && break || continue
done

status "Installing ollama to $BINDIR..."
```

And then there's the systemd unit and system user, that point to `/usr/share/ollama`.

Objectively, there is a better place to install stuff that isn't managed by system package manager in linux and that's the `/opt` directory.

Would it be possible to rewrite the installer script to utilise `/opt/ollama` as the basedir for everything ollama? Apropriate link in `/usr/local/bin` to `/opt/ollama` would suffice to make the application available systemwide.

**Comment by jeremyakers** [comment]
This was "closed", but I just ran the installer and it dumped 9GB into /usr/local/lib/ before it filled my disk and started throwing "No space on device errors"

I don't see any option to tell the script to use /opt (or any other folder) instead?

If you're going to be extracting 10s of GB, you should 1) Warns users of the size and 2) let users choose where that is going go on their disk
