### ISSUE TITLE
Ollama Mixtral uses only 7% of the Nvidia RTX A4000 GPU.

### ISSUE THREAD

**Issue by nejib1** [ollama/ollama#2362]
Hello,

When I execute Ollama Mixtral with the Nvidia A4000 (16GB), I observe that only 7% of the GPU is utilized. Do you know why this might be happening? Additionally, the process seems somewhat slow. It appears that Ollama Mixtral is using 40% of the CPU but only 7% of the GPU.

![rp9k0CV 1](https://github.com/ollama/ollama/assets/10485460/cafc29e9-3068-4c44-af0d-a665c6b90ee9)

Do you have any suggestions on how to increase GPU utilization instead of  %?

**Comment by MatMatMatMatMatMat** [comment]
Same here on MacBook  M1 Pro 32Go :
GPU usage with mixtral is 0. Really slow.
Same prompt with mistral gpu usage between 70-90% Really fast.

**Comment by jmorganca** [comment]
Hi @nejib1, it seems that your system is bottlenecked on the CPU since the entire model won't fit into memory (only some does, as you can see in `nvidia-smi` (thanks for sharing this 😊 ) it's 14.8/16.3GiB which is almost all of your VRAM

@MatMatMatMatMatMat thanks for comment – GPU offloading isn't supported in macOS (yet!) so Mixtral will run on CPU on a 32GB Macbook Pro

**Comment by fariazz** [comment]
@jmorganca does this `nvidia-smi` also mean CPU bottlenecked?  What would solve this, installing more RAM for instance? Thanks in advance!

![image](https://github.com/ollama/ollama/assets/1313597/0ac5ff21-acb7-4365-ba3d-c2c2d63386cd)

**Comment by Chakit22** [comment]
@jmorganca Mistral is also running on my system by using maximum GPU usage but its like sometimes the GPU usage is lesser and sometimes it's higher but I seem to get a timeout error using mistral on MAC M2 Pro 16GB RAM.

**Comment by nejib1** [comment]
> Hi @nejib1, it seems that your system is bottlenecked on the CPU since the entire model won't fit into memory (only some does, as you can see in `nvidia-smi` (thanks for sharing this 😊 ) it's 14.8/16.3GiB which is almost all of your VRAM
> 
> @MatMatMatMatMatMat thanks for comment – GPU offloading isn't supported in macOS (yet!) so Mixtral will run on CPU on a 32GB Macbook Pro

Thank you for your help

**Comment by dhiltgen** [comment]
It looks like we can close this issue as resolved.  If you're still having problems, please let us know.
