### ISSUE TITLE
relationship https://github.com/ollama-webui/ollama-webui, other than another project creating a frontend for ollama?

### ISSUE THREAD

**Issue by andrewtvuong** [ollama/ollama#2364]
https://github.com/ollama-webui/ollama-webui may be a bit confusing to users. Can you please clarify in readme. It seems these are separately controlled.

**Comment by lovincyrus** [comment]
Looks like Web UI is being mentioned in the [Web & Desktop](https://github.com/ollama/ollama?tab=readme-ov-file#web--desktop) section..
