### ISSUE TITLE
Unable to use safetensor fine tuned model deepseek to gguf with convert.py from llama.cpp

### ISSUE THREAD

**Issue by JesseGuerrero** [ollama/ollama#2365]
I finished fine tuning a deepseek-ai/deepseek-coder-1.3b-instruct and am now trying to convert it to gguf with llama.cpp to use with ollama.

However, none of the options with convert.py are working. I assume the model works because the inference API on hugging face works just fine for my huggingface model.

I tried all three vocab-types, including different tokenizer.model files and pad-vocab with llama.cpp.

Typically when it doesnt convert it says there is a mismatch like this on ollama...
![image](https://github.com/ollama/ollama/assets/27308928/679d55f8-b0bd-49a8-95cb-d73e6106a8dd)
When it does go through it either shows gibberish in ollama or is "failed to load model" or "Tensor size mismatch".

Any help for me to understand how to get this to convert properly would help.

Here is my fine tuned model: https://huggingface.co/JesseGuerrero/deepseekAllDarkan

I made a few fine tuned models already and they worked fine. Dunno what is going on with this one.

Btw, this is what the gibberish looks like:
![image](https://github.com/ollama/ollama/assets/27308928/1c004afc-62f7-4afa-8053-56625bac0c17)

**Comment by jukofyork** [comment]
I has to use the `--pad-vocab`  and `--vocab-type = bpe` when I used it for the `deepseek-coder:33b-instruct` model, but see you said you tried these so not sure what to suggest.

Possibly try turning down the `temperature` to 0.0 and the `repeat-penalty` to 1.0 as it seems to not like the default values of these.

**Comment by pdevine** [comment]
This issue got lost in the deluge of issues, but you can alternatively just convert this directly in Ollama by putting the path to the safetensors file in the `FROM` line of the `Modelfile`. I've updated the [importing doc](https://github.com/ollama/ollama/blob/main/docs/import.md) which goes into more details. Ollama will automatically pad the vocab during `ollama create`.

I think we can close this.

**Comment by pdevine** [comment]
To be clear here, this is for deepseek 1.3b which uses the llama architecture. Deepseek coder v2 uses a different architecture which you can't directly import.
