### ISSUE TITLE
Provide settings for allowed origins in Mac OS app

### ISSUE THREAD

**Issue by jemstelos** [ollama/ollama#2369]
hey there - been developing on a UI that calls the ollama server, and therefore needs its CORS origin to be allowed.

This issue (https://github.com/ollama/ollama/issues/300#issuecomment-1826434144) provided support for CORS origins to be configured when starting the server via command line by passing an environment variable (thank you!)

This requirement would cause friction for users who just run ollama via the mac app. Can we provide some kind of GUI setting for allowing origins in the mac app?

Thanks!

**Comment by dahjson** [comment]
I'd like to see this type of setting as well for Mac, Linux, and Windows when it's available. This would help simplify the setup process for users wanting to access an AI model from a web app.

**Comment by bmizerany** [comment]
Closing for https://github.com/ollama/ollama/issues/2335
