### ISSUE TITLE
Documents translation (Japanese)

### ISSUE THREAD

**Issue by jesseclin** [ollama/ollama#2371]
I have translated the documentation files into [Japanese ones](https://github.com/jesseclin/ollama/blob/main/README_ja.md) and will keep them updated. Should I submit a PR? or is it better to leave them there?

**Comment by bmizerany** [comment]
This is wonderful! Thank you, @jesseclin. If you're still open to posting a PR, please do!

**Comment by jesseclin** [comment]
Dear @bmizerany:

Sure and I will post a PR after I update the documents, thanks.

Jesse

**Comment by bmizerany** [comment]
I'm going to close this out. Looking forward to your PR! Please feel free to reference this issue in the PR.
