### ISSUE TITLE
How to stop/exit `ollama` service on macos?

### ISSUE THREAD

**Issue by Rusteam** [ollama/ollama#2372]
I haven't been able to find a command to stop the ollama service after running it with `ollama run <model>`. After a `/bye` command is called, the service is still running at `localhost:11434`. Only force quitting all ollama services from the activity monitor kills the service.

**Comment by easp** [comment]
ollama run <model> doesn't start the service. The service is started on login by the Ollama menu bar app. If you want to stop the service, quit the app. If you want to do it from the command line you can `osascript -e 'tell app "Ollama" to quit'`. If you don't quit the service the model will automatically be unloaded from memory after 5 minutes of inactivity.

**Comment by Rusteam** [comment]
Thanks I'll test it out

**Comment by bmizerany** [comment]
The usual ways to exit ollama are working in the current release. Closing this issue but please reopen and update if issues persist.

**Comment by Fabrizio-ASTEK** [comment]
I am not able to stop ollama with the above instructions.
The server still runs.
```
fcaruso@Fabrizios-Mac-mini ~ % ollama serve
Error: listen tcp 127.0.0.1:11434: bind: address already in use
fcaruso@Fabrizios-Mac-mini ~ % osascript -e 'tell app "Ollama" to quit'
21:25: execution error: Ollama got an error: User canceled. (-128)
fcaruso@Fabrizios-Mac-mini ~ % sudo osascript -e 'tell app "Ollama" to quit'
Password:
21:25: execution error: Ollama got an error: User canceled. (-128)
fcaruso@Fabrizios-Mac-mini ~ % 
```

If I click the Ollama icon and select quit, I still see the server running at localhost.
