### ISSUE TITLE
The `qwen:72b-chat-v1.5` model (and likely all the other v1.5 models too) is missing the `rope_frequency_base` value in the GGUF file.

### ISSUE THREAD

**Issue by jukofyork** [ollama/ollama#2379]
I've patched my Ollama to allow the setting of `rope_frequency_base` in the modelfile again, so I can fix this via:

```
PARAMETER rope_frequency_base 1000000
```

but it should also be possible to use `gguf-set-metadata` to do the same.

I'm not the only one who noticed this as the official GGUF `q5_k_m` and `q2_k` models are also missing the `rope_frequency_base` value:

https://huggingface.co/Qwen/Qwen1.5-72B-Chat-GGUF/discussions/1

> The transformers repo suggested that this model has a ROPE frequency of 1,000,000 while the gguf metadata here has a frequency of 10,000.

I can confirm this does seem to work as without this setting it just ends up outputting repeating newlines after a while - possibly because the default is 10000 (?) and it will make the context 'appear' to fill up 100x quicker to the model.

**Comment by jmorganca** [comment]
Thanks for catching this and sorry - will update these.

**Comment by svilupp** [comment]
I have been wondering why our LLM Leaderboard scores Qwen models as complete trash ([link](https://svilupp.github.io/Julia-LLM-Leaderboard/dev/examples/summarize_results_local/#Model-Comparison))! 
This would explain a lot.

However, I've tried changing the rope freq as an API parameter and running a slice of the benchmark and it made no difference.

**Comment by jukofyork** [comment]
> However, I've tried changing the rope freq as an API parameter and running a slice of the benchmark and it made no difference.
The rope scale and frequency parameters aren't passed through to the wrapped llama.cpp server in the main Ollama branch - they get zeroed out to 0.0f and ignored.

It's only around 6 line of code to change in 3 files and I will put up a PR later if I get time.

**Comment by jukofyork** [comment]
> > However, I've tried changing the rope freq as an API parameter and running a slice of the benchmark and it made no difference.
> > The rope scale and frequency parameters aren't passed through to the wrapped llama.cpp server in the main Ollama branch - they get zeroed out to 0.0f and ignored.
> 
> It's only around 6 line of code to change in 3 files and I will put up a PR later if I get time.

It's here https://github.com/ollama/ollama/pull/2389 but I can't seem to make a second fork of Ollama and this also includes the code for the PR that allows `split_mode` and `tensor_split` to be set from the modelfile (I'm too dumb to work out out to split off just the changes for the `rope_freq_base` and `rope_freq_scale` - sorry).

**Comment by jukofyork** [comment]
Sadly you can't use `gguf-set-metadata` as it seems the setting is completely missing from the GGUF file header:

```
> gguf-set-metadata --dry-run qwen-72b-chat.gguf llama.rope.freq_base 1000000
* Loading: qwen-72b-chat.gguf
! Field 'llama.rope.freq_base' not found
```

So for now the only alternative is to patch the source and pass the `rope_freq_base = 1000000` via the modelfile.

**Comment by svilupp** [comment]
I think I'll treat Qwen as a write-off or tell people to just use a different backend than Ollama. I wonder how many models are secretly affected by similar "bugs" :-/ (especially when a model performs suspiciously bad in our benchmarks)

**Comment by jukofyork** [comment]
I think every back-end will be effected until a proper GGUF gets uploaded: it seems to be Qwen themselves that have accidentally missed the rope.freq_base parameter :/

**Comment by jukofyork** [comment]
They've fixed the official GGUF quants now:

https://twitter.com/justinlin610/status/1757811183707681197?s=46&t=BVhfPLwVzzqRJOcJ7VU3tw

I was finding that the one downloaded from ollama.ai had some other strange problem where it would sometimes do a huge pause of around 10-15 seconds and then start outputing new lines (tried both the q8_0 and q5_K_M). No other model has ever done this so not sure if there is more wrong than just the ROPE base frequency - will report back if the new/fixed official GGUF works any better.

**Comment by svilupp** [comment]
@jmorganca Apologies for the shout out, but would it be possible to consider re-uploading Qwen? It’s “allegedly” one of the best local models out there, but we can’t use it Ollama 😓

**Comment by jukofyork** [comment]
I just downloaded the official q8_0 from qwen's huggingface report and can confirm the weird stalling is fixes and the GGUF has the correct Rope base frequency backed in.

I've never had any other models stall like that in Ollama so it's possible the one on ollama.ai is corrupted somehow and not just the wrong Rope setting.

**Comment by dhiltgen** [comment]
This should be part of the gguf and model download now.  Just make sure to re-pull if you have an old copy of the model.
