### ISSUE TITLE
Local caching / Custom Registry

### ISSUE THREAD

**Issue by KaruroChori** [ollama/ollama#2388]
Is there any supported solution to:
- locally host a custom registry?
- at the very least a partial mirror of the registry for those models which have been downloaded once already? 

Downloading the same model from the original source on multiple machines within the same network is quite slow and wasteful.

**Comment by arkohut** [comment]
Great question. I have similar issue.

**Comment by easp** [comment]
https://github.com/ollama/ollama/issues/914#issuecomment-1953482174

**Comment by KaruroChori** [comment]
Thanks for reporting.
So it appears like, under the hood, it works like a docker repository, not just as flavour.

**Comment by bmizerany** [comment]
Ollama keeps a cache of your already download models under `~/.ollama` or `$OLLAMA_MODELS` if set.

Ollama currently uses a Docker Registry (with custom authentication) to store models, however we cannot guarantee we will continue support for it in the future. 

It should be possible to host your own registry with authentication turned off for use as a private registry.

Closing - please reopen if you have any further questions.

**Comment by samheutmaker** [comment]
@bmizerany Do you have any documentation that explains Docker registry compatibility? We're trying to set up a LAN registry for our team to share models. We will open source anything we build around this for re-use by the community.

**Comment by bmizerany** [comment]
@samheutmaker Currently, we do not have an official registry API, which is why we don't have any documentation available for Docker registry compatibility.

We are considering and working towards a solution for remote caching. There are no dates for its release currently.

For now, we unofficially use the GET layer, POST/PUT(upload) layer and read/commit manifests.

**Comment by haydonryan** [comment]
Plus one on some local registry. I run both pacoloco and Panamax to mirror stuff locally (and nightly at 3am). Would love to do cache models too as I have a team who use the same models on their machines.

**Comment by cniweb** [comment]
> @samheutmaker Currently, we do not have an official registry API, which is why we don't have any documentation available for Docker registry compatibility.
> 
> We are considering and working towards a solution for remote caching. There are no dates for its release currently.
> 
> For now, we unofficially use the GET layer, POST/PUT(upload) layer and read/commit manifests.

@samheutmaker Is there now a plan for when the API will be Docker API compatible so that the registry can be cached locally via Sonatype Nexus or JFrog Artefactory via proxy repository?

Same issue as #5298 ?
