### ISSUE TITLE
List of domains ollama needs access to

### ISSUE THREAD

**Issue by arno4000** [ollama/ollama#2390]
Is there a list of domains, which need to be allowed in the forward proxy for ollama to function properly? ollama.ai is allowed, and I see in the logs of the proxy that ollama tries to connect to `https://registry.ollama.ai`. But then ollama tries to access `https://dd20bb891979d25aebc8bec07b2b3bbc.r2.cloudflarestorage.com`. 

From where does ollama have this Cloudflare domain? Is this always the same, or can this change randomly? I need to know which domains I have to allow in the forward proxy of my server.

**Comment by yifan0011** [comment]
> Is there a list of domains, which need to be allowed in the forward proxy for ollama to function properly? ollama.ai is allowed, and I see in the logs of the proxy that ollama tries to connect to `https://registry.ollama.ai`. But then ollama tries to access `https://dd20bb891979d25aebc8bec07b2b3bbc.r2.cloudflarestorage.com`.
> 
> From where does ollama have this Cloudflare domain? Is this always the same, or can this change randomly? I need to know which domains I have to allow in the forward proxy of my server.

I am facing a similar problem, may I ask which domains you added to whitelist, so that it works in the end?
