### ISSUE TITLE
Inquiry on Optimal CPU and GPU Configurations for LLaMA 2(70B)

### ISSUE THREAD

**Issue by gautam-fairpe** [ollama/ollama#2393]
I am currently exploring the capabilities of LLaMA 2 for various NLP tasks and am in the process of setting up the necessary hardware environment to ensure optimal performance. Given the complexity and resource-intensive nature of LLaMA 2(70B), I am seeking advice on the most suitable CPU and GPU configurations that can deliver the best performance for training and inference tasks with this model.

Specifically, I am interested in:
- Recommendations for CPU and GPU models that are known to work well with LLaMA 2, considering both performance and cost-efficiency.
- Any available estimation charts or benchmarks that illustrate the performance of LLaMA 2 with different hardware configurations. This information would be incredibly helpful for planning hardware investments and understanding the expected model throughput and latency.

**Comment by igorschlum** [comment]
Hi @gautam-fairpe I bought a Mac Station with Max memory. (192GB), si J cab Run simultaneously and locally all the LLM.

It's quick and I know that ai will always be able to sell it if I'm not more happy with it.

**Comment by jmorganca** [comment]
For Llama2/3 70B you'd want at least 48GB of VRAM, if not closer to 64GB to fit the model and context size
