### ISSUE TITLE
Multi-GPU setup of Tesla P100s is slow

### ISSUE THREAD

**Issue by PhilipAmadasun** [ollama/ollama#2395]
A multi-GPU setup of Tesla P100s is very slow compared to a single RTX 4090. I am using the 0.1.22 version of ollama. Is there something wrong with the Teslas? Are they just bad GPUs? I was told to try to run ollama on just one of them to see what happens, if that might indeed make ollama run faster I am not sure how to go about it. Is there some way to disable  GPU so ollama only runs on a single Tesla GPU?

**Comment by opyate** [comment]
> Is there some way to disable GPU so ollama only runs on a single Tesla GPU?

You might be able to get the GPU's ID from `nvidia-smi`, and then just use that ID to isolate the GPU for ollama, e.g.

```
CUDA_VISIBLE_DEVICES=1 ollama serve
```

**Comment by dhiltgen** [comment]
If you're still seeing unexpected performance behavior, please share your server log so we can analyze what's going on.
