### ISSUE TITLE
llama.cpp now supports Vulkan

### ISSUE THREAD

**Issue by ddpasa** [ollama/ollama#2396]
As of 10 days ago: https://github.com/ggerganov/llama.cpp/commit/2307523d322af762ae06648b29ec5a9eb1c73032

This is great news for people who non-CUDA cards.

What's necessary to support this with Ollama?  I'm happy to help if you show me the pointers.

**Comment by ddpasa** [comment]
I managed to compile ollama with the following code snippet gen_linux.sh and it builds a vulkan version:

```
init_vars
CMAKE_DEFS="-DLLAMA_CCACHE=OFF -DCMAKE_BUILD_TYPE=Release -DLLAMA_SERVER_VERBOSE=on -DCMAKE_POSITION_INDEPENDENT_CODE=on -DLLAMA_NATIVE=off -DLLAMA_VULKAN=1"
BUILD_DIR="${LLAMACPP_DIR}/build/linux/${ARCH}/vulkan"
echo "Building Vulkan"
build
compress_libs
```

I'm now getting a very cryptic segfault.  Debugging...

**Comment by ddpasa** [comment]
I was able to get llama.cpp compiled with the following, and confirm that it works.  However, when I try to hack [gen_commons.sh](https://github.com/ollama/ollama/blob/main/llm/generate/gen_common.sh#L85), I always get empty or grabled output.  I'm not very familiar with how ollama builds llama.cpp, so I'm probably messing something up.  Tagging @dhiltgen because he was kind enough to help me in the [AVX thread.](https://github.com/ollama/ollama/issues/2205)

working llama.cpp config:

```
mkdir build
cd build
cmake .. -DLLAMA_VULKAN=1
cmake --build . --config Release
# now test:
./build/bin/main -m ggml-model-q4_0.gguf -p "Hi you how are you" -n 50 -e -ngl 0 -t 4
```

ollama gen_commons.sh that compiles fine, but produces garbled output:

```
cmake -S ${LLAMACPP_DIR} -B ${BUILD_DIR} -DLLAMA_VULKAN=1 -DCMAKE_BUILD_TYPE=Release -DCMAKE_POSITION_INDEPENDENT_CODE=on -DLLAMA_SERVER_VERBOSE=on -DLLAMA_AVX=on -DLLAMA_AVX2=on -DLLAMA_FMA=on 
cmake --build ${BUILD_DIR} ${CMAKE_TARGETS} -j8
mkdir -p ${BUILD_DIR}/lib/
g++ -fPIC -g -shared -o ${BUILD_DIR}/lib/libext_server.${LIB_EXT} \
        ${GCC_ARCH} \
        ${WHOLE_ARCHIVE} ${BUILD_DIR}/examples/server/libext_server.a ${NO_WHOLE_ARCHIVE} \
        ${BUILD_DIR}/common/libcommon.a \
        ${BUILD_DIR}/libllama.a \
        -Wl,-rpath,\$ORIGIN \
        -lpthread -ldl -lm -lvulkan \
        ${EXTRA_LIBS}
```

**Comment by dhiltgen** [comment]
We have multiple issues tracking Vulkan support - lets use #2033
