### ISSUE TITLE
Empty message content causes request to hang

### ISSUE THREAD

**Issue by jmorganca** [ollama/ollama#2397]
To reproduce:

```
curl http://localhost:11434/api/chat -d '{
  "model": "llama2",
  "messages": [
    {
      "role": "user",
      "content": ""
    }
  ]
}'
```

**Comment by cedws** [comment]
I still have this issue on 0.1.24. Providing an empty prompt in an existing context causes Ollama to completely crash and serve any requests on any models anymore.

Unfortunately I'm unable to provide a repro right now.
