### ISSUE TITLE
Running Ollama on mac but accessing through SSH only?

### ISSUE THREAD

**Issue by sei-dupdyke** [ollama/ollama#2398]
Can I run the app on an apple silicon based mac accessible via SSH only? After copying the installer out there, something like:

```bash
unzip Ollama-darwin.zip
mv Ollama.app /Applications/.
cd /Applications/.
chmod +x Ollama.app
open -n Ollama.app
```

but this gives no indication of changes, and when i subsequently run `ollama list` I get "zsh: command not found: ollama" (even with new shell, or login/out).

Is there a way to run it in this manner? Thanks!!

**Comment by jmorganca** [comment]
When starting `Ollama.app`, it prompts to create a symlink, but you can do that manually

```
sudo ln -s /Applications/Ollama.app/Contents/Resources/ollama /usr/local/bin/ollama
```

`ollama list` etc should work afterwards

Hope this helps!

**Comment by sei-dupdyke** [comment]
Thank you. I had to `sudo mkdir -p /usr/local/bin`, but then that command worked perfectly. I'm up and running.

Is it possible for me to copy in and load models without an internet connection? If this is already documented, could you point me to it please? TIA.

Love the project, keep up the great work!

**Comment by wincc0823** [comment]
vim .zshrc 

#ollama
export PATH=/usr/local/bin:$PATH

source .zshrc

enjoy 🤣
