### ISSUE TITLE
ollama serve stuck

### ISSUE THREAD

**Issue by OnixAlgo** [ollama/ollama#2409]
"I haven't had this issue until I installed AMD ROCM on my system; it gets stuck at this step in every version that I try.

ollama serve
time=2024-02-08T11:53:18.991+01:00 level=INFO source=images.go:860 msg="total blobs: 0"
time=2024-02-08T11:53:18.992+01:00 level=INFO source=images.go:867 msg="total unused blobs removed: 0"
time=2024-02-08T11:53:18.992+01:00 level=INFO source=routes.go:995 msg="Listening on 127.0.0.1:11434 (version 0.1.23)"
time=2024-02-08T11:53:18.993+01:00 level=INFO source=payload_common.go:106 msg="Extracting dynamic libraries..."
time=2024-02-08T11:53:21.432+01:00 level=INFO source=payload_common.go:145 msg="Dynamic LLM libraries [rocm_v6 cuda_v11 rocm_v5 cpu cpu_avx2 cpu_avx]"
time=2024-02-08T11:53:21.432+01:00 level=INFO source=gpu.go:94 msg="Detecting GPU type"
time=2024-02-08T11:53:21.432+01:00 level=INFO source=gpu.go:242 msg="Searching for GPU management library libnvidia-ml.so"
time=2024-02-08T11:53:21.434+01:00 level=INFO source=gpu.go:288 msg="Discovered GPU libraries: []"
time=2024-02-08T11:53:21.434+01:00 level=INFO source=gpu.go:242 msg="Searching for GPU management library librocm_smi64.so"
time=2024-02-08T11:53:21.435+01:00 level=INFO source=gpu.go:288 msg="Discovered GPU libraries: [/opt/rocm/lib/librocm_smi64.so.6.0.60002 /opt/rocm-6.0.2/lib/librocm_smi64.so.6.0.60002]"
time=2024-02-08T11:53:21.446+01:00 level=INFO source=gpu.go:109 msg="Radeon GPU detected"
time=2024-02-08T11:53:21.446+01:00 level=INFO source=cpu_common.go:11 msg="CPU has AVX2"

**Comment by KiUmac** [comment]
Can you explain how did you solve it? I'm having the same problem.
