### ISSUE TITLE
Running Qwen

### ISSUE THREAD

**Issue by PrashantDixit0** [ollama/ollama#2419]
I tried running Qwen with Langchain but didn't get any output. It is stuck.
Has anyone else got stuck at the same place?

**Comment by svilupp** [comment]
There are several different issues with Qwen already:
- https://github.com/ollama/ollama/issues/2405
- https://github.com/ollama/ollama/issues/2385
- https://github.com/ollama/ollama/issues/2379

Unfortunately, I have seen any solutions or workarounds yet 😞

**Comment by PrashantDixit0** [comment]
Same here, I have been trying different models of Qwen but none of them worked for me.

@svilupp Have to tried any other way to run Qwen that would have worked for you like hugging face or any other framework?

**Comment by svilupp** [comment]
No, gave up. I'm waiting for the GGUF to be re-uploaded.

In general, I'm having so many issues with Ollama this week, that I'll need to explore other alternatives 😢

**Comment by deependhulla** [comment]
Downloaded today latest version of ollama ..and Qwen models , it worked for me on macOS - Intel MacBookPro.

**Comment by PrashantDixit0** [comment]
I tried running Qwen on Ubuntu 22.04 after a fresh installation of Ollama, working for me :+1:

**Comment by cognitivetech** [comment]
i downloaded the latest release and tried to run qwen on ubuntu 20.. still no luck, here. and requires restart ollama service...

**Comment by cognitivetech** [comment]
ok, working. done

**Comment by PrashantDixit0** [comment]
Great 😃

**Comment by samzong** [comment]
It's seem good news for run Qwen with ollama.

I'll check again.

**Comment by svilupp** [comment]
The fixed GGUF haven’t been re-uploaded yet. So you would have to download them from elsewhere (the ones in Ollama library are broken).

**Comment by bmizerany** [comment]
> I tried running Qwen on Ubuntu 22.04 after a fresh installation of Ollama, working for me 👍

Great to hear!

I'm closing this issue. Please reopen if you have further issues.
