### ISSUE TITLE
`/v1/models` OpenAI compatibility API

### ISSUE THREAD

**Issue by emsi** [ollama/ollama#2430]
It's great to have OpenAI compatibility API! 
Unfortunately many applications require additional endpoints to work properly.
Namely `v1/models` (https://platform.openai.com/docs/api-reference/models) with list of available models is the one most frequently missing.

**Comment by johnnyq** [comment]
Yes I agree and is very much necessary I need this feature to integrate with our FOSS Web Application so a model can be selected.

**Comment by jackiezhangcn** [comment]
yes, it is necessary

**Comment by keriati** [comment]
note, that a PR with this feature was submitted already in February: https://github.com/ollama/ollama/pull/2476

**Comment by CorrM** [comment]
In case you are using `ollama` and `--listmodels` return `/v1/models` error
check that https://github.com/danielmiessler/fabric/issues/410#issuecomment-2180191661
