### ISSUE TITLE
Linux Install Instructions

### ISSUE THREAD

**Issue by Deetss** [ollama/ollama#2434]
The current install instructions showing this one-liner do not work.

`curl https://ollama.ai/install.sh | sh`

I had to change the command to this, for it to work. 

`curl https://ollama.com/install.sh | sh`

**Comment by jmorganca** [comment]
I'm sorry about this – it should be fixed now!

<img width="605" alt="Screenshot 2024-02-09 at 3 01 14 PM" src="https://github.com/ollama/ollama/assets/251292/402cceaa-fab5-465c-b43c-cfa6e546446c">

**Comment by Deetss** [comment]
Thanks for the quick response!

**Comment by deependhulla** [comment]
oh both ollama.ai and ollama.com are own by Ollama. is that correct ?

**Comment by Deetss** [comment]
When I tried to use the `*.ai` TLD curl did nothing. As soon as I tried the `*.com` TLD we were cooking with gas, not sure if something is up but it's working now!

**Comment by MohitTml** [comment]
How to use
