### ISSUE TITLE
Unable to load dynamic server library in hardened environment (tmp mounted as noexec)

### ISSUE THREAD

**Issue by crenz** [ollama/ollama#2436]
I installed ollama on a hardened Ubuntu 22 system successfully. When running `ollama run mistral`, I am getting the following error message:

`Error: Unable to load dynamic library: Unable to load dynamic server library: /tmp/ollama2322208974/cpu_avx2/libext_server.so: failed to map segment from shared object`

The root cause seems to be that on this system, `/tmp` is mounted as noexec. I was able to fix the issue by setting another temporary directory in `/etc/systemd/system/ollama.service` by adding the line

`Environment="TMPDIR=/usr/share/ollama/tmp"`

I suggest addressing the issue by using a temporary directory within the `/usr/share/ollama` directory if `/tmp`is mounted as noexec, or to at least mention this issue in the documentation.

**Comment by PaulHendi** [comment]
I had a similar issue, and in my case just updating Ollama fixed it :)

**Comment by hoyyeva** [comment]
Hey @crenz, really sorry you ran into that problem. Could you check if the update to Ollama sorted it out for you? We're going to close this issue for now, but if you're still stuck, please let us know!
