### ISSUE TITLE
Ollama server stuck using Mixtral on M3

### ISSUE THREAD

**Issue by galleon** [ollama/ollama#2446]
Ollama stopped serving my requests after %hours Part of the log is [here](https://gist.github.com/galleon/d538c6d7df7f276bf93861422eb71605)

The prompt is large but the quite the same everytime.
Quick and dirty code if you want to reproduce it is [there](https://gist.github.com/galleon/9c7e4f42e58e4ab686c461b514f60080)

Let me know if you need more information.

**Comment by igorschlum** [comment]
Hi @galleon 
How much memory you have? Did you tried with other Models than Mixtral? I have a m2 with 192gb and will try to reproduce the issue.

**Comment by igorschlum** [comment]
The script is running, I have to wait 6 hours or more to see if it crashes. I will let you know.

**Comment by galleon** [comment]
Hi @igorschlum thanks for your help. My Mac has a max memory possible i.e. 128GB.

the program will not crash it will just stop.ah ah ah and if it does not … I am interested by the outcome :-)

**Comment by galleon** [comment]
Also wondering if it is possible to have a log more verbose

**Comment by stevengans** [comment]
This is a duplicate seen here: https://github.com/ollama/ollama/issues/2339

**Comment by galleon** [comment]
Closing as it seems to have been resolved. I will test asap
