### ISSUE TITLE
Log request/responses payload

### ISSUE THREAD

**Issue by jmformenti** [ollama/ollama#2449]
In order to debug low-level details during development, it would be very useful to be able to see the payload of requests and responses.
Is there a way to enable this?

**Comment by jaredmcqueen** [comment]
It's using gin under the hood, so I imagine one could hook into that and set up a STDOUT logger?  I haven't spent any time looking at the code but will start digging in...

**Comment by lesca** [comment]
+1 agree
I can't figure out what's wrong with the request from another app without the request payload. Good to have this! Thanks

**Comment by jmorganca** [comment]
Hi @jmformenti thanks for the issue! If you run Ollama with `OLLAMA_DEBUG=1 ollama serve` you'll see per-token debug logs. Hope this helps!

**Comment by fzyzcjy** [comment]
Hi, is there any updates? Thanks!
