### ISSUE TITLE
[FEATURE] Add support for Intel Xeon (Sapphire and Emerald Rapids) accelerators and AI features such as AMX and AVX 512.

### ISSUE THREAD

**Issue by scouzi1966** [ollama/ollama#2451]
Note that Intel is trying to demystify AVX512 with a AVX 10 standard. But they are the same.

AVX512
https://www.intel.com/content/www/us/en/architecture-and-technology/avx-512-overview.html

AMX
https://www.intel.com/content/www/us/en/products/docs/accelerator-engines/advanced-matrix-extensions/overview.html  

AVX512 is also being fully implemented by AMD

**Comment by pdevine** [comment]
cc @dhiltgen

**Comment by scouzi1966** [comment]
I've since analyzed the code base more closely and realize that this probably belongs more with llama.cpp project which would eventually make it's way here. There seems to be Intel involvement  here as well. 

https://github.com/intel/neural-speed. 

You can close this request if you want from my point of view.

**Comment by dhiltgen** [comment]
This might wind up being a dup of #2205

**Comment by jmorganca** [comment]
Closing for https://github.com/ollama/ollama/issues/2205
