### ISSUE TITLE
Update rocm version for docker build to 6.0.2

### ISSUE THREAD

**Issue by mkesper** [ollama/ollama#2455]
Docker builds are still based against rocm-5.7.1. Rocm version 6.0.2 seems to work better so please offer at least a variant of the image with rocm 6.0.2.

Related PR: https://github.com/ollama/ollama/pull/2454

**Comment by mkesper** [comment]
Additionally: Would it make sense to offer the rocm image as a completely seperate image. It's quite a different product.

**Comment by dhiltgen** [comment]
> Additionally: Would it make sense to offer the rocm image as a completely seperate image. It's quite a different product.

Can you elaborate?   Are you suggesting a separate ollama release or binary for rocm vs cuda?  One of the key objectives we have is to streamline the user experience so a single app works across a broad set of GPUs and CPUs.
