### ISSUE TITLE
Resume does not seem to work

### ISSUE THREAD

**Issue by da-z** [ollama/ollama#2463]
I had about 4.5GB out of 49GB already downloaded but on a retry it restarted from scratch (same layer - edb02981b596...).

`ollama pull nous-hermes2-mixtral:8x7b-dpo-q8_0`

**Comment by technovangelist** [comment]
If you restarted the machine or even just the ollama service, there is a pruning process that runs that clears out any incomplete model files. To not do that, you need to set an environment variable. OLLAMA_NOPRUNE

**Comment by da-z** [comment]
Good to know, thank you. I may have restarted the service, indeed.
