### ISSUE TITLE
Error: invalid version -- when attempting to run llava

### ISSUE THREAD

**Issue by gr-b** [ollama/ollama#2464]
I attempted to install and run llava on an m1 mac and got the following:

~ % ollama run llava
pulling manifest
pulling 170370233dd5... 100% |███████████████| (4.1/4.1 GB, 46 MB/s)           
pulling 72d6f08a42f6... 100% |█████████████████| (624/624 MB, 49 MB/s)         
pulling 43070e2d4e53... 100% |███████████████████| (11/11 kB, 1.1 MB/s)        
pulling c43332387573... 100% |████████████████████| (67/67 B, 538 kB/s)        
pulling ed11eda7790d... 100% |████████████████████| (30/30 B, 185 kB/s)        
pulling 7c658f9561e5... 100% |██████████████████| (564/564 B, 1.8 MB/s)        
verifying sha256 digest
writing manifest
removing any unused layers
success
⠋   Error: invalid version

If I run `ollama run llava` again (above was the first time), I get:
`⠋   Error: invalid version`

If I use the API on localhost:
`{"error":"invalid version"}`

Any help would be appreciated. Thanks.

**Comment by technovangelist** [comment]
Whats your version of ollama?
