### ISSUE TITLE
Adding Bert-Embeddings server / how to add torch 

### ISSUE THREAD

**Issue by michaelfeil** [ollama/ollama#2471]
I am building https://github.com/michaelfeil/infinity and would love to contribute to ollama. It is compatible with cuda, cpu and mps, with the option to run onnx models. Beta also for torch + ROCm. 

torch or onnx are required, I would recommend going with torch for speed (flash attn integration).

```python
import asyncio
from infinity_emb import AsyncEmbeddingEngine

engine = AsyncEmbeddingEngine(model_name_or_path = "BAAI/bge-small-en-v1.5", engine="torch")

async def main(sentences = ["Embed this is sentence via Infinity.", "Paris is in France."]): 
    # invoke this function however you can from go
    async with engine: # engine starts with engine.astart()
        embeddings, usage = await engine.embed(sentences=sentences)
asyncio.run(main())
```

PS: Had a chat at the SF meetup earlier today thanks for hosting, a lot of interesting people here. Great work @mchiang0610

**Comment by jmorganca** [comment]
@michaelfeil so great to see you there! Bert models should new be possible to run with Ollama (e.g. see https://ollama.com/library/all-minilm or https://ollama.com/library/nomic-embed-text). Let me know if this helps!

**Comment by michaelfeil** [comment]
Great - thanks for closing the issue!

**Comment by CaptXiong** [comment]
> [@michaelfeil](https://github.com/michaelfeil) so great to see you there! Bert models should new be possible to run with Ollama (e.g. see https://ollama.com/library/all-minilm or https://ollama.com/library/nomic-embed-text). Let me know if this helps!

Hello @jmorganca !  Is there any guide for importing a fine-tuned Bert structure model into Ollama?
