### ISSUE TITLE
Ollama floods /tmp with unnecessary libraries

### ISSUE THREAD

**Issue by knoopx** [ollama/ollama#2472]
This is what my `/tmp` dir looks after a few hours. I have no idea why ollama does this and why no cleanup is in place. ollama version is 0.1.24. haven't noticed this before this release.

![image](https://github.com/ollama/ollama/assets/100993/e48031ef-fcc3-4617-a005-0ff7f5b7d4d6)
![image](https://github.com/ollama/ollama/assets/100993/dd8c5c71-b7f9-4f78-86d0-5870c2dfdc03)

**Comment by remy415** [comment]
The files in the /tmp directory are libraries bundled with the llama.cpp build. Normally the ollama application removes the files in the /tmp directory, for some reason it isn't. That being said, that folder is wiped clean on reboot, and it's safe to remove any file in that directory.

**Comment by dhiltgen** [comment]
@knoopx can you try upgrading to the latest version?  Under normal circumstances, the system should clean these up on graceful shutdown, so if you're still seeing a lot of them, that might imply the server is crashing.  Can you check the server log and see if you see crashes?  If so, lets get to the bottom of those.

**Comment by glaudiston** [comment]
Do we have a environment variable to set this to another folder?

**Comment by dhiltgen** [comment]
@glaudiston see `ollama serve --help` - this is covered by OLLAMA_TMPDIR
