### ISSUE TITLE
How can fine tune with ollama?

### ISSUE THREAD

**Issue by KDH-Korea** [ollama/ollama#2488]
I want to fine-tune the Mistral model imported using Ollama, but there is no information available, and it's even more challenging to find information in Korea where not many people are familiar with Ollama. I would appreciate it if you could provide information on how to fine-tune the model using Ollama.

**Comment by Zig1375** [comment]
+1

**Comment by chuangtc** [comment]
### First fine-tune open-source hugging face AI model.
https://huggingface.co/docs/transformers/training
### Then do quantization and convert the model to GGUF format and re-upload to hugging face.
https://mlabonne.github.io/blog/posts/Quantize_Llama_2_models_using_ggml.html
### Then run it with Modelfile with the GGUF format model.
https://www.markhneedham.com/blog/2023/10/18/ollama-hugging-face-gguf-models/

**Comment by jmorganca** [comment]
Thanks for the guides @chuangtc! I'm going to merge this with https://github.com/ollama/ollama/issues/156 just to keep the issues tidy.
