### ISSUE TITLE
How to install ollama on ubuntu with specific version

### ISSUE THREAD

**Issue by MugdhaHardikar-GSLab** [ollama/ollama#2491]
I want to install the ollama on my ubuntu server but every few days new version of ollama gets installed. I want to fix the version of the ollama getting installed on my machine. Current install.sh doesn't seem to have that functionality. IS there any way?

**Comment by remy415** [comment]
What do you mean by `fix the version of the ollama getting installed`? Do you mean you want to keep a specific version installed?

**Comment by MugdhaHardikar-GSLab** [comment]
Yes. Previously I was using ollama 0.1.20, now I am getting 0.1.24. It want to stick to one version even if latest versions come up lets say too 0.1.20. How to do it.

**Comment by jmorganca** [comment]
By default Ollama won't auto upgrade on Linux

However, you can run this script to install a previous version:
```
curl -fsSL https://ollama.com/install.sh | sed 's#https://ollama.com/download#https://github.com/jmorganca/ollama/releases/download/v0.1.25#' | sh
```

Note this is experimental and may not work forever

**Comment by telemetrieTP23** [comment]
for me your commando for installing specific version  does not work anymore, it allways installs the actual version (0.1.25) on my jetson orin AGX 
even if i use:

curl -fsSL https://ollama.com/install.sh | sed 's#https://ollama.com/download#https://github.com/jmorganca/ollama/releases/download/v0.1.27#' | sh

on the jetson xavier agx i used it to install 0.1.17, after i recognized that starting with 0.1.18 it doesnt find the gpu drivers anymore, so i downgraded.

**Comment by remy415** [comment]
@telemetrieTP23 I'm working on adding Jetson support. In the mean time, I have a preliminary build available that should work on your Orin AGX until it's fully integrated into the official release: [https://github.com/remy415/ollama](https://github.com/remy415/ollama). 

To save you time, ensure that you set the following environment variables:
`export LD_LIBRARY_PATH="/usr/local/cuda/lib64:/usr/local/cuda/compat:/usr/local/cuda/include"`
`export OLLAMA_SKIP_CPU_GENERATE="1"`

Also set one of the following based on which Jetpack you are using:

L4T_VERSION.major >= 36:    # JetPack 6
`export CUDA_ARCHITECTURES="87"`

L4T_VERSION.major >= 34:  # JetPack 5
`export CUDA_ARCHITECTURES="72;87"`

L4T_VERSION.major == 32:  # JetPack 4
`export CUDA_ARCHITECTURES="53;62;72"`

**Comment by telemetrieTP23** [comment]
Thanks for your help.
Above with "preliminary build" you meant that i should build your fork ?

I have cmake version 3.20.2
go version go1.27.1 linux/arm64
gcc (Ubuntu 9.4.0-1ubuntu1~20.04.2) 9.4.0

tried your tips from above:
export LD_LIBRARY_PATH="/usr/local/cuda/lib64:/usr/local/cuda/compat:/usr/local/cuda/include"
export OLLAMA_SKIP_CPU_GENERATE="1"
export CUDA_ARCHITECTURES="72;87"

But still when i start  "go generate ./..."
Then it generates  '-DCMAKE_CUDA_ARCHITECTURES=50;52;61;70;75;80' in the CMAKE _DEFS

and the errors like here https://github.com/ollama/ollama/issues/1979#issuecomment-1951463913
where produced....

**Comment by kungfu-eric** [comment]
This works now:
```
curl -fsSL https://ollama.com/install.sh | sed 's#https://ollama.com/download/ollama-linux-${ARCH}${VER_PARAM}#https://github.com/ollama/ollama/releases/download/v0.1.33-rc5/ollama-linux-amd64#' | sh
```

> By default Ollama won't auto upgrade on Linux
> 
> However, you can run this script to install a previous version:
> 
> ```
> curl -fsSL https://ollama.com/install.sh | sed 's#https://ollama.com/download#https://github.com/jmorganca/ollama/releases/download/v0.1.25#' | sh
> ```
> 
> Note this is experimental and may not work forever

**Comment by thyarles** [comment]
Hi there! Just call like this
```
OLLAMA_VERSION=0.5.6 curl -fsSL https://ollama.com/install.sh | sh
```

**Comment by ABCdatos** [comment]
Working actually, as stated in [https://docs.ollama.com/linux](https://docs.ollama.com/linux) :

`curl -fsSL https://ollama.com/install.sh | OLLAMA_VERSION=0.11.11 sh`

**Comment by amitthk** [comment]
> Working actually, as stated in https://docs.ollama.com/linux :
> 
> `curl -fsSL https://ollama.com/install.sh | OLLAMA_VERSION=0.11.11 sh`

This command didn't work for me. It installs:
```
$ollama --version
ollama version is 0.14.2
Warning: client version is 0.13.3
```

Here's what worked for me: 

I went to releases page and found the link to tarball compatible for my machine and os:  https://github.com/ollama/ollama/releases

```
# 1. Force stop and purge the snap (skipping snapshots)
sudo snap stop ollama
sudo snap remove --purge ollama

# 2. Kill any remaining background processes
sudo killall ollama 2>/dev/null

# 3. Prepare directory for ollama
sudo mkdir -p /usr/share/ollama

# 4. Downloaded the 0.13.3 tarball (change 0.13.3 with the version you would prefer)
curl -L https://github.com/ollama/ollama/releases/download/v0.13.3/ollama-linux-amd64.tgz -o ollama-0.13.3.tgz

# 5. Extract to /usr/share/ollama
sudo tar -C /usr/share/ollama -xzf ollama-0.13.3.tgz

# 6. Create the symlink so 'ollama' command works globally
sudo ln -sf /usr/share/ollama/bin/ollama /usr/local/bin/ollama

# 7. Create the service file
sudo bash -c 'cat <<EOF > /etc/systemd/system/ollama.service
[Unit]
Description=Ollama Service
After=network-online.target

[Service]
ExecStart=/usr/local/bin/ollama serve
User=root
Group=root
Restart=always
RestartSec=3
Environment="PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"

[Install]
WantedBy=default.target
EOF'

# 8. Reload, enable, and start the service
sudo systemctl daemon-reload
sudo systemctl enable ollama
sudo systemctl start ollama

```
