### ISSUE TITLE
Change language in Llava

### ISSUE THREAD

**Issue by shersoni610** [ollama/ollama#2494]
Hello,
I am running "ollama run llava". The output is in Non-English language. How do I change it?

**Comment by shersoni610** [comment]
Hello, I get the following:

>>> Describe the image in English 'Wide-Squat.png'
죄송합니다, "Wide-Squat.png"이라는 이미지가 있나요? 만약에 그렇다면 어떤 것인지 설명해주세요.

>>> Describe the image in English language. 'Wide-Squat.png'
죄송합니다, "Wide-Squat.png"이라는 이미지가 있나요? 만약에 그렇다면 어떤 것인지 설명해주세요.

**Comment by BruceMacD** [comment]
Hi @shersoni610, this sometimes happens when the image isn't being sent to the model correctly. Try updating to the most recent version of ollama and also running `ollama pull llava`.

**Comment by hoyyeva** [comment]
Hey @shersoni610, thanks for bringing this to our attention. This can happen in older version of Ollama that did not support llava models. To fix the problem try updating Ollama to latest.

Resolving this for now as it is a known issue.
