### ISSUE TITLE
Llama2: `q4_km` as default?

### ISSUE THREAD

**Issue by matthiasgeihs** [ollama/ollama#2495]
Just saw this table: https://github.com/ggerganov/llama.cpp/pull/1684#issuecomment-1579252501

Perplexity loss is considerably higher for `q4_0` compared to `q4_km`. `km` provides the best tradeoff between size and performance, as noted also [here](https://huggingface.co/TheBloke/Mixtral-8x7B-v0.1-GGUF).

`ollama` currently uses `q4_0` as the default for `llama2`: https://ollama.com/library/llama2:latest (as observed by comparing the ID 78e26419b446).

**Suggestion:**
Use [`q4_km`](https://ollama.com/library/llama2:7b-chat-q4_K_M) as the default instead.

**Comment by pdevine** [comment]
Hey @matthiasgeihs you can pull `[7b-chat-q4_K_M](https://ollama.com/library/llama2:7b-chat-q4_K_M)` which is the model you want. The `ollama cp` command will allow you to change it on your own host to the default. We've been debating internally for a while about changing the default, but we'll see.

I'll go ahead and close the issue though.

**Comment by matthiasgeihs** [comment]
Thx for the update. An option to change the default quantization on my machine would be great. Are you saying `ollama cp` can do that? How?

**Comment by pdevine** [comment]
Ultimately I'd love you to be able to just set a default and not have to worry about tags any more (I demo'd something like this at the Ollama + Friends meetup in Paris last month). For now if you don't want to type out the whole tag name, just `ollama cp llama2:7b-chat-q4_K_M mymodel` which would allow you to `ollama run mymodel` as a convenient shortcut.

**Comment by ncoquelet** [comment]
:+1: Thanks for the tips on the `ollama cp` command.
:+1::+1: For an option to customise the default quantization tag to my convenience

**Comment by ncoquelet** [comment]
linked open issue
