### ISSUE TITLE
default num_thread incorrect on some large core count system (non-hyperthreading)

### ISSUE THREAD

**Issue by mokkin** [ollama/ollama#2496]
I have tested Ollama on different machines yet, but no matter how many cores or RAM I have, it's only using 50% of the cores and just a very few GB of RAM.
For example now I'm running `ollama rum llama2:70b` on 16 core server with 32 GB of RAM, but while prompting only eight cores are used and just around 1 GB of RAM.

Is there something wrong? In the models descriptions are aleways warning you neet at least 8,16,32,... GB of RAM.

![Bildschirmfoto vom 2024-02-14 18-08-47](https://github.com/ollama/ollama/assets/2938748/8a47ec55-475d-4311-8110-3ca1e0a34cb8)

**Comment by easp** [comment]
That's fine & as expected.

Model data is memory mapped and shows up in file cache #. Note too, VIRT, RES & SHR memory # of the Ollama processes.

Generation is memory bandwidth limited, not compute limited. Saturation is generally achieved ~1/2 the number of virtual cores. Using more can actually hurt speeds and interferes unnecessarily with other processes.

**Comment by Zbrooklyn** [comment]
What if I want it to use more CPU cores is there a config file or command for that?

**Comment by robertvazan** [comment]
@Zbrooklyn Change 'num_thread' [parameter in custom modelfile](https://github.com/ollama/ollama/blob/main/docs/modelfile.md#parameter).

**Comment by Cguanqin** [comment]
> @Zbrooklyn更改自定义模型文件中的“num_thread”[参数](https://github.com/ollama/ollama/blob/main/docs/modelfile.md#parameter)。

hei,bro~ 
it's still using 50% of the cores and 50% of RAM after  modifying Modelfile that increased num_thread.from 8 to 16 。

my Modelfile is as follows:
FROM gemma:2b
PARAMETER num_thread 16

**Comment by robertvazan** [comment]
@Cguanqin You are probably doing something wrong. Try to write down reproducible steps. That will probably reveal the mistake.

**Comment by Cguanqin** [comment]
> @Cguanqin You are probably doing something wrong. Try to write down reproducible steps. That will probably reveal the mistake.

oh，I don't know where the problem is. I want to run the Gemma: 2b model in Ollama. My machine is configured with 16CPU and 16RAM. Can you provide a modelfile reference? Thank you！

**Comment by robertvazan** [comment]
@Cguanqin Your modelfile looks alright. The problem is probably in the way you try to use it. I am using Open WebUI with Ollama, which provides convenient UI for modelfile editing. But if I were you, I wouldn't waste effort on raising thread count. I tried it and it does indeed worsen throughput. One thread per physical core is indeed optimal.

**Comment by AdamYLK** [comment]
same issue for me，i find another issue
[Performance e-core bug(?) - only 50% CPU utilization when using all threads - (Win11, Intel 13900k)](https://github.com/ggerganov/llama.cpp/issues/842)

i can't use -t to set thread on linux server

**Comment by arbarbieri** [comment]
> @Zbrooklyn Change 'num_thread' [parameter in custom modelfile](https://github.com/ollama/ollama/blob/main/docs/modelfile.md#parameter).

Worked for me! Thanx!

**Comment by johnalanwoods** [comment]
> Model data is memory mapped and shows up in file cache #. Note too, VIRT, RES & SHR memory # of the Ollama processes.

Sorry to necro the thread, but why is this done specifically?

**Comment by robertvazan** [comment]
@johnalanwoods Not a llama.cpp/ollama developer, but let me guess. One of the advantages is that you can have model larger than RAM. It will be super slow, limited by SSD speed, but it will work. Another reason is that OS is given a chance to discard the pages when the model is not in use and load them back when model is used again. There might be other reasons.

**Comment by johnalanwoods** [comment]
Makes sense thanks!

**Comment by dhiltgen** [comment]
Yes, by default we only create a thread per physical core.  Trying to map inference threads to hyperthreads thrashes the CPU and results in poorer performance.

**Comment by sekrett** [comment]
I don't have hyper-treading at all (Core i5 9600K) and still 3 of 6 cores are used. How can ollama distinguish if hyper-threading is enabled?

**Comment by dhiltgen** [comment]
@sekrett  the following might help shed some light...
```
ls /sys/devices/system/cpu/
cat /sys/devices/system/cpu/cpu*/topology/thread_siblings
```

For reference, on a 4-core (8 hyperthread) Intel CPU I see something like this:
```
% ls /sys/devices/system/cpu/
cpu0  cpu2  cpu4  cpu6  cpufreq  hotplug       isolated    microcode  offline  possible  present  uevent
cpu1  cpu3  cpu5  cpu7  cpuidle  intel_pstate  kernel_max  modalias   online   power     smt      vulnerabilities
% cat /sys/devices/system/cpu/cpu*/topology/thread_siblings
11
22
44
88
11
22
44
88
```

**Comment by wwjCMP** [comment]
> @sekrett the following might help shed some light...
> 
> ```
> ls /sys/devices/system/cpu/
> cat /sys/devices/system/cpu/cpu*/topology/thread_siblings
> ```
> 
> For reference, on a 4-core (8 hyperthread) Intel CPU I see something like this:
> 
> ```
> % ls /sys/devices/system/cpu/
> cpu0  cpu2  cpu4  cpu6  cpufreq  hotplug       isolated    microcode  offline  possible  present  uevent
> cpu1  cpu3  cpu5  cpu7  cpuidle  intel_pstate  kernel_max  modalias   online   power     smt      vulnerabilities
> % cat /sys/devices/system/cpu/cpu*/topology/thread_siblings
> 11
> 22
> 44
> 88
> 11
> 22
> 44
> 88
> ```

If my machine does not have hyper-threading enabled, how can I set it up to allow more physical cores to be used by ollama?

**Comment by dhiltgen** [comment]
@wwjCMP if your CPU does not have hyperthreads, then the "thread_siblings" above are supposed to show no siblings, and we should default to one thread per core.  If that's not the behavior you're seeing, can you share the output of the above from your system?

**Comment by wwjCMP** [comment]
cpu0   cpu14  cpu2   cpu25  cpu30  cpu36  cpu41  cpu47  cpu52  cpu58  cpu63  cpu69  cpu74  cpu8   cpu85  cpu90  cpufreq                 kernel_max  power
cpu1   cpu15  cpu20  cpu26  cpu31  cpu37  cpu42  cpu48  cpu53  cpu59  cpu64  cpu7   cpu75  cpu80  cpu86  cpu91  cpuidle                 microcode   present
cpu10  cpu16  cpu21  cpu27  cpu32  cpu38  cpu43  cpu49  cpu54  cpu6   cpu65  cpu70  cpu76  cpu81  cpu87  cpu92  hotplug                 modalias    smt
cpu11  cpu17  cpu22  cpu28  cpu33  cpu39  cpu44  cpu5   cpu55  cpu60  cpu66  cpu71  cpu77  cpu82  cpu88  cpu93  intel_pstate            offline     uevent
cpu12  cpu18  cpu23  cpu29  cpu34  cpu4   cpu45  cpu50  cpu56  cpu61  cpu67  cpu72  cpu78  cpu83  cpu89  cpu94  intel_uncore_frequency  online      umwait_control
cpu13  cpu19  cpu24  cpu3   cpu35  cpu40  cpu46  cpu51  cpu57  cpu62  cpu68  cpu73  cpu79  cpu84  cpu9   cpu95  isolated                possible    vulnerabilities

**Comment by wwjCMP** [comment]
00000000,00000000,00000001
00000000,00000000,00000400
00000000,00000000,00000800
00000000,00000000,00001000
00000000,00000000,00002000
00000000,00000000,00004000
00000000,00000000,00008000
00000000,00000000,00010000
00000000,00000000,00020000
00000000,00000000,00040000
00000000,00000000,00080000
00000000,00000000,00000002
00000000,00000000,00100000
00000000,00000000,00200000
00000000,00000000,00400000
00000000,00000000,00800000
00000000,00000000,01000000
00000000,00000000,02000000
00000000,00000000,04000000
00000000,00000000,08000000
00000000,00000000,10000000
00000000,00000000,20000000
00000000,00000000,00000004
00000000,00000000,40000000
00000000,00000000,80000000
00000000,00000001,00000000
00000000,00000002,00000000
00000000,00000004,00000000
00000000,00000008,00000000
00000000,00000010,00000000
00000000,00000020,00000000
00000000,00000040,00000000
00000000,00000080,00000000
00000000,00000000,00000008
00000000,00000100,00000000
00000000,00000200,00000000
00000000,00000400,00000000
00000000,00000800,00000000
00000000,00001000,00000000
00000000,00002000,00000000
00000000,00004000,00000000
00000000,00008000,00000000
00000000,00010000,00000000
00000000,00020000,00000000
00000000,00000000,00000010
00000000,00040000,00000000
00000000,00080000,00000000
00000000,00100000,00000000
00000000,00200000,00000000
00000000,00400000,00000000
00000000,00800000,00000000
00000000,01000000,00000000
00000000,02000000,00000000
00000000,04000000,00000000
00000000,08000000,00000000
00000000,00000000,00000020
00000000,10000000,00000000
00000000,20000000,00000000
00000000,40000000,00000000
00000000,80000000,00000000
00000001,00000000,00000000
00000002,00000000,00000000
00000004,00000000,00000000
00000008,00000000,00000000
00000010,00000000,00000000
00000020,00000000,00000000
00000000,00000000,00000040
00000040,00000000,00000000
00000080,00000000,00000000
00000100,00000000,00000000
00000200,00000000,00000000
00000400,00000000,00000000
00000800,00000000,00000000
00001000,00000000,00000000
00002000,00000000,00000000
00004000,00000000,00000000
00008000,00000000,00000000
00000000,00000000,00000080
00010000,00000000,00000000
00020000,00000000,00000000
00040000,00000000,00000000
00080000,00000000,00000000
00100000,00000000,00000000
00200000,00000000,00000000
00400000,00000000,00000000
00800000,00000000,00000000
01000000,00000000,00000000
02000000,00000000,00000000
00000000,00000000,00000100
04000000,00000000,00000000
08000000,00000000,00000000
10000000,00000000,00000000
20000000,00000000,00000000
40000000,00000000,00000000
80000000,00000000,00000000
00000000,00000000,00000200

**Comment by wwjCMP** [comment]
> @wwjCMP if your CPU does not have hyperthreads, then the "thread_siblings" above are supposed to show no siblings, and we should default to one thread per core. If that's not the behavior you're seeing, can you share the output of the above from your system?

Here you are

**Comment by dhiltgen** [comment]
Thanks for the output @wwjCMP.  It does look like the thread_siblings are all unique so we **should** allocate 96 threads by default on this system.  I'll try to figure out why this isn't happening.

As a workaround, you should be able to set num_thread to override our default behavior.  For example:
```
% ollama run llama3
>>> /set parameter num_thread 96
Set parameter 'num_thread' to '96'
>>> why is the sky blue?
The color of the sky can vary depending on the time of day, atmospheric conditions, and location. However, under normal conditions, the sky typically appears blue
because of a phenomenon called Rayleigh scattering.
...
```

**Comment by Googlepuss** [comment]
I have ollama set up on VM for testing, with 12 vCPU (4 socket & 3 core topology) and 16GB RAM (no GPU). I am not sure where to see the global default num_thread from CLI, but open-webui indicates "2". I came to this thread looking for a reason why RAM has almost zero utilization (maybe 2-3GB of available 16), while the CPU seems to be completely taxed by every query. I could throw more resources at it, but with the RAM seemingly not used, I am wondering if there is a configuration I have overlooked. most everything is the default. 

me@follama:~$ ls /sys/devices/system/cpu/
cpu0  cpu10  cpu2  cpu4  cpu6  cpu8  cpufreq  crash_hotplug  isolated    modalias   offline  possible  present  uevent
cpu1  cpu11  cpu3  cpu5  cpu7  cpu9  cpuidle  hotplug        kernel_max  nohz_full  online   power     smt      vulnerabilities
me@follama:~$ cat /sys/devices/system/cpu/cpu*/topology/thread_siblings
00000000,00000001
00000000,00000400
00000000,00000800
00000000,00000002
00000000,00000004
00000000,00000008
00000000,00000010
00000000,00000020
00000000,00000040
00000000,00000080
00000000,00000100
00000000,00000200

**Comment by Googlepuss** [comment]
Thanks, @oldmanjk! had not used glances prior, and is super useful. Attaching screenshots when running basic questions "sky blue", "tell a joke", "short story", etc. Disck i/o doesn't stand out, CPU stays pegged, mem never exceeds 6.9% (of 16GB vRAM). this is all llama3:latest and /set parameter num_gpu 0 num_thread 12. not sure where to go next I guess. CPU is not super modern but should be able to handle tell me a joke without pegging out. 

<img width="1680" alt="Screenshot 2024-06-05 at 7 35 03 PM" src="https://github.com/ollama/ollama/assets/110204795/519bbd71-049b-49a7-b8f8-8c53589e3caa">
<img width="270" alt="Screenshot 2024-06-05 at 7 37 05 PM" src="https://github.com/ollama/ollama/assets/110204795/cc4ea422-1c67-4110-aa07-ebfc7e7f9559">

**Comment by Googlepuss** [comment]
> > Thanks, @oldmanjk! had not used glances prior, and is super useful. Attaching screenshots when running basic questions "sky blue", "tell a joke", "short story", etc. Disck i/o doesn't stand out, CPU stays pegged, mem never exceeds 6.9% (of 16GB vRAM). this is all llama3:latest and /set parameter num_gpu 0 num_thread 12. not sure where to go next I guess. CPU is not super modern but should be able to handle tell me a joke without pegging out.
> > <img alt="Screenshot 2024-06-05 at 7 35 03 PM" width="1680" src="https://private-user-images.githubusercontent.com/110204795/337067932-519bbd71-049b-49a7-b8f8-8c53589e3caa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc2NDAwMjksIm5iZiI6MTcxNzYzOTcyOSwicGF0aCI6Ii8xMTAyMDQ3OTUvMzM3MDY3OTMyLTUxOWJiZDcxLTA0OWItNDlhNy1iOGY4LThjNTM1ODllM2NhYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwNlQwMjA4NDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05M2MxMjNmZDVjMzYyNDMyODBhOGYyZDhkODFkZWE1ZDkwNmNjYWUxOTI1MWRhYzJjNjczNDI2ZDlkODkwYjE2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.-YlO8Fbi46wt4XP0BHqsXp7CNUtaMXn2sfqYrqJzZz4">
> > <img alt="Screenshot 2024-06-05 at 7 37 05 PM" width="270" src="https://private-user-images.githubusercontent.com/110204795/337067936-cc4ea422-1c67-4110-aa07-ebfc7e7f9559.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc2NDAwMjksIm5iZiI6MTcxNzYzOTcyOSwicGF0aCI6Ii8xMTAyMDQ3OTUvMzM3MDY3OTM2LWNjNGVhNDIyLTFjNjctNDExMC1hYTA3LWViZmM3ZTdmOTU1OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwNlQwMjA4NDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lZmRhOWRjNTU4MTYyNDQzZGViZmUwODEzMjk0ZjdkZTIxMzVlMDdjMTZkMGYxOWQwYzVjMTEyNTBmYjhmNzA2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.kpDbsKwgqgheRtl81CB9_VhQTA2tm5rWdJqV_7SJ2Kc">
> 
> Yeah, I discovered glances recently and like it so far. It has a lot of depth I haven't had the time to explore yet. I thought you were talking about system RAM, not VRAM. VRAM _should_ show as used when in use, so something isn't offloading right. num_gpu is how many layers you want offloaded to gpu, so that explains that. Assuming you want to utilize your gpu more, you want to increase that number, or if you just want ollama to use most of your gpu, delete that parameter entirely
> 
> Edit - I see now you mean virtual RAM. I didn't catch the no-gpu thing earlier. Yeah, if you're not using gpu, your CPU has to do all the work, so you should expect full usage. It will go all-out until it's done. Full usage is actually a good thing, because it means you're not bottlenecked by IO. If you want less usage so you can do other things simultaneously, tell ollama to use fewer threads (make sure none of those vCPU's are mapped to vcores). Ideally, you want to offload to a GPU.
> 
> (I keep realizing I'm misreading what you wrote - I'm a bit off atm - so if I screwed anything further up, I apologize)

No worries at all. thanks for the feedback. yes "virtual RAM".  I am interested in your remark about hyperthreading, I have 2 [intel E5-2680 v3](https://ark.intel.com/content/www/us/en/ark/products/81908/intel-xeon-processor-e5-2680-v3-30m-cache-2-50-ghz.html) on host and VM env managed by xcp-ng/XOA. So, the hypervisor sees "48 Core 2 Socket" and "Hyperthread enabled".  But in bare metal terms, it is 2 Socket, 24 Core, and 48 Thread. With hyperthread disabled on the host, this would bring the available vCPU count from 48 to 24 (believe). is this problematic (having hyperthreading enabled)?

**Comment by Googlepuss** [comment]
Thanks! I will take the direction and play with the CPU mappings. Agree on the GPU, just trying to get the CPU-only config optimal before I work in GPU and likely a dedicated host. Appreciate it.

**Comment by sekrett** [comment]
> You'll just get better performance (usually - test it) if you restrict inference to physical cores. Also worth testing running inference just on the physical cores of one CPU, depending on memory layout, etc. You're probably losing performance from inter-CPU communication overhead.

Completely agree, I tested times on different desktops and Xeons, without HT you get code compilation faster by setting `make -j8` for example.

**Comment by GregChiang0201** [comment]
> > Hi, how can I set the `num_thread` for `ollama serve` instead of `ollama run`?
> 
> Alright, I found the solution for `ollama serve`. Simply add the `num_thread` parameter when making the API request.
> 
> ![image](https://private-user-images.githubusercontent.com/222802/344922090-deb4ef32-ba60-4ad9-a978-8f0375ca72af.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIyNDEwODYsIm5iZiI6MTcyMjI0MDc4NiwicGF0aCI6Ii8yMjI4MDIvMzQ0OTIyMDkwLWRlYjRlZjMyLWJhNjAtNGFkOS1hOTc4LThmMDM3NWNhNzJhZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyOVQwODEzMDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNmE1ZDVhYjM3ODc0ODU3MTE2NDIzMGFkMGVkYTQ3ZTc0MmY0Y2Y3Y2FiMDQyNTI0YTZkMTk1MTNkMzQ0MzM2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.SSDlNwvpSpk7INZhgFg5H3jsPml_Z0r9bCQyARBndvI)
> 
> Reference: https://github.com/ollama/ollama/blob/main/docs/api.md#request-6

Excuse me, is there any option can change num_thread permanently? Since I can only run the instructions above every time to set the custom threads, or the system will use half of my cores to run it.

**Comment by dbustosrc** [comment]
#5554

**Comment by tigran123** [comment]
Oh dear, how confident are we in forcing a policy, where only a mechanism should be provided, forgetting the wise words of Linus Torvalds back from early 1990s, explaining that OS (and software in general) should never force any stupid (i.e. stupid to a user who knows perhaps better than the developer) _policy_ down all users' throat and only providing _mechanisms_, leaving it up to the user to decide, which policy he ought to adopt.

Now, in this case, I would say it is very naive to assume that everyone's CPU would behave in exactly the same way that a particular CPU that the developer has tested on does. The whole point of virtual threads appearing as "separate CPUs" (e.g. in /proc/cpuinfo) is that they ought to really be used as separate CPUs in the sense of MP specification. That was the case 20 years ago and it is true today. Yes, in some (in many, I agree) scenarios it would be inefficient to use more than the number of physical cores, i.e. more than half of the virtual threads, but in others it would be more efficient. Otherwise there would be no such thing as HT support.

So, please provide a way (other than passing "num_thread" via API, unless it is possible to set it via Open WebUI, is it?) to set the num_thread somehow. Again, without having to create a new model via Modelfile specifically for this purpose.

I tried setting OLLAMA_NUM_THREADS environment variable to 12 and it did make a difference only at the initial load (which became almost twice as fast, btw!) but during the actual inference it reverted back to 6. I have Intel Core i7-6800K CPU which has 6 cores and 12 threads (of course HT is enabled, as it generally makes everything TWICE as fast -- that is the whole point of HT).

I found the PR for OLLAMA_NUM_PARALLEL, but it is not merged yet:

https://github.com/ollama/ollama/pull/9546

So, are there any workarounds, please?

UPDATE: Could it be that I simply misspelled OLLAMA_NUM_THREADS and it should be OLLAMA_NUM_THREAD instead? I will try both and see.

UPDATE: No, unfortunately, I still have 50% CPU utilisation, i.e. num_thread is internally set to 6, ignoring both OLLAMA_NUM_THREAD and OLLAMA_NUM_THREADS environment variables.

**Comment by tigran123** [comment]
UPDATE: I was reluctant to do `ollama create model -f modelfile` because I thought that it was going to duplicate the whole 65GB file :)

Now I have created a `num_thread 12` version of gpt-oss:120b and compared its performance to the default one -- indeed, it is twice as slow -- 40 seconds vs 21 seconds for inference on the same prompt (from fresh state of `ollama serve`).

Thank you for your patience :)

**Comment by tigran123** [comment]
Another update: I don't know how did I get those "40 vs 21 seconds" numbers before, but now I _consistently_ get the opposite, namely: 17-19 seconds for the 12 threads version (100% cpu utilisation) and 28-31 seconds for the 6 threads version (50% CPU utilisation). Here are the screenshots and I can easily reproduce it. So, the default num_thread is set wrongly, after all. It should be set to the logically obvious value -- the number of CPUs (i.e. virtual threads) and not the number of physical cores as it does currently. At least on my Intel Core i7-6800K system with 128GB RAM.

<img width="1719" height="360" alt="Image" src="https://github.com/user-attachments/assets/f585cfeb-9417-4370-b1d4-760edde88dfb" />

<img width="1719" height="360" alt="Image" src="https://github.com/user-attachments/assets/dd1a1b42-41c7-4536-9b6a-758b1b84c78d" />

**Comment by minyor** [comment]
Hello, I have same problem on our E5-2699 v3 server with 70+ cores.
Small models on ollama version is 0.1.38 loads and works fast under 4 seconds per request
But starting from ollama version 0.1.39 and up to latest version the loading and resposes take up to 15 minutes...
Setting OLLAMA_NUM_THREADS or OLLAMA_NUM_THREAD nor num_thread to 70 wont help..
Please adwise, are we really stack with this old ollama?

**Comment by tigran123** [comment]
Why not do what I did -- have a trivial Modelfile like this:

```
FROM modelname
PARAMETER num_thread <N>
```

then it works perfectly if `num_thread` is matching the number of real CPUs in the SMP sense (not some secondary notion of the so-called "physical cores" which is not useful and that is why it is not normally exported via API -- though one can manually count the `core id` values in `/proc/cpuinfo`, of course).

It is sad that the Ollama developers are stubbornly refusing to change the defaults, presumably because some exotic tests done by someone suggested that using only half of the available CPUs is somehow beneficial. But this is not critical -- just create a proper model clone for each of your models (i.e. with num_thread matching the number of CPUs) and everything works fine, and much faster than with this unfortunate default.

**Comment by minyor** [comment]
But I tried this, I modified existing model parameter like so:
>ollama run tinyllama:1.1b
>>      /set parameter num_thread 72
>>      /save tinyllama:1.1b
>>      Ctrl+D
>service ollama restart

But this only made my model run slow even on an 0.1.38 version of ollama, not only on >=0.1.39
Only deleting a model and redownloading it helped to make it run fast again on 0.1.38
And I do not mean a little slow, but about 90 times slower...
I surelly must've did something incorrect

Edit: Also, when I run requests, all the 72 cores are at 100% of load, whole these 15 slow minutes...
If this is a problem with number of threads then shouldn't only one or some cores be loaded instead of all of them?

Edit: If I edit the model again but this time set num_threads 0 likeso:
>ollama run tinyllama:1.1b
>>      /set parameter num_thread 0
>>      /save tinyllama:1.1b
>>      Ctrl+D
>service ollama restart

Then It again starts to work fast but only in ollama <=0.1.38
