### ISSUE TITLE
How do I specify parameters when launching ollama from command line?

### ISSUE THREAD

**Issue by dtp555-1212** [ollama/ollama#2505]
I saw something online that said to try ollama run llama2:13b -temperature 0.0  but that does not work. I am also interested in setting the seed, so rerunning will do the same process rather than doing something different each time. (e.g. on a classification task, sometimes it says valid/invalid, sometimes is says correct/incorrect. sometimes is it very verbose explaining why it made its decision. I want to find a terse method and stick with it.

Thanks in advance

**Comment by virt-god** [comment]
I am not sure if there is another way of doing this, but you can make a custom modelfile.

```
ollama show llama2:13b --modelfile >> modelfile-name
```

Append settings to modelfile-name
It'll look something like this
```
# I don't have this model, so I don't know if this is the correct template
# The only important thing here is importing llama2:13b and your changes at the bottom

FROM llama2:13b
# base settings
TEMPLATE """
[INST] <<SYS>>{{ .System }}<</SYS>>

{{ .Prompt }} [/INST]
"""

PARAMETER stop "[INST]"
PARAMETER stop "[/INST]"
PARAMETER stop "<<SYS>>"
PARAMETER stop "<</SYS>>"

# your changes
PARAMETER temperature 0.0
PARAMETER seed 0
```

For more options check the docs https://github.com/ollama/ollama/blob/main/docs/modelfile.md

After saving run (you can use any name for your model)
```
ollama create model-name -f ./modelfile-name
```

**Comment by dtp555-1212** [comment]
thanks I will give that a shot.

**Comment by asterbini** [comment]
Notice that you can set parameters from the prompt, after the chat has started
`/set parameter  temperature 0`

**Comment by mhagnumdw** [comment]
It would be interesting to pass the parameters directly on the `ollama run model` command line. Do you plan on implementing this?

**Comment by axemaster** [comment]
> Notice that you can set parameters from the prompt, after the chat has started `/set parameter temperature 0`

This (/set...) didn't work when I used it in a prompt file, that is, a file that gets fed into ollama STDIN instead of using the process interactively. e.g.

`ollama run<promptfile.txt`

Is instead it was interpreted as a literal prompt and the LLM responds with a summary of Rosa commands for me.

Is it supposed to? It would be a nice feature.

**Comment by ichalov** [comment]
@axemaster @cirosantilli
The problem can be worked around by using a wrapper `expect` script. You can probably generate one by using a prompt like this: _Develop an expect script to sequentially pass content from two files into external command-line tool supplied after -- command line delimiter. First file should be passed line by line with waiting for some answer, the second file should be passed as whole._

Or here is my working version of this script: https://github.com/ichalov/gpt-tools/blob/main/call_ollama_with_params.exp

**Comment by cirosantilli** [comment]
OK, the expect method works:

```
sudo apt install expect
```

then either directly on Bash:

```
expect \
  -c 'spawn ollama run llama3.2' \
  -c 'expect ">>> "' \
  -c 'send "/set parameter seed 0\r"' \
  -c 'expect ">>> "' \
  -c 'send "/set parameter num_predict 100\r"' \
  -c 'expect ">>> "' \
  -c 'send "/set parameter seed 0\r"' \
  -c 'expect ">>> "' \
  -c 'send "What is quantum field theory?\r"' \
  -c 'expect ">>> "' \
  -c 'send "/bye"' \
;
```

or from a script:

```
#!/usr/bin/expect -f
set prompt ">>> "
spawn ollama run llama3.2
expect $prompt
send "/set parameter seed 0\r"
expect $prompt
send "/set parameter num_predict 20\r"
expect $prompt
send "What is quantum field theory?\r"
expect $prompt
send -- "/bye"
```

both seem to work.

Related pull request: https://github.com/ollama/ollama/issues/1415

Tested on ollama 0.5.13.

**Comment by cirosantilli** [comment]
@ichalov did you find a solution for the control characters that get added to stdout with expect due to the progress indicator? https://github.com/ollama/ollama/issues/6120 Sad!!!

**Comment by ichalov** [comment]
@cirosantilli
I somehow don't have this problem, maybe because I run it on Linux and not MacOS. If I look `out.txt` using `tail -f` during execution, it shows the rolling cursor itself. And that character doesn't make it to the final version of `out.txt` at all:
```
$ cat out.txt 
spawn bash -c ... ollama run qwen2.5-coder:32b
/set parameter num_ctx 4096
The sky is
>>> /set parameter num_ctx 4096
Set parameter 'num_ctx' to '4096'
>>> The sky is
beautiful today! It's clear and blue with fluffy white clouds scattered 
across it. How does the weather make you feel?

>>> 
```
I don't have access to MacOS to test possible solutions. Can only recommend to try querying some LLM with: "how to make expect skip passing certain characters". It seems to have an easy snippet to insert into an existing script.

**Comment by cirosantilli** [comment]
Hi thanks. I'm on Linux. There are various escape sequences present, some of which contain regular ascii chars, so it would require some thought to understand exactly what they are.
