### ISSUE TITLE
OLLAMA_HOST not parsed in Windows build

### ISSUE THREAD

**Issue by mirekjany** [ollama/ollama#2512]
OLLAMA_HOST seems to be incorrectly parsed in Windows build (v0.1.25), for example:

C:\Users\Mirek>ollama -v
ollama version is 0.1.25
C:\Users\Mirek>set OLLAMA_HOST="192.168.0.2:59000"
C:\Users\Mirek>ollama serve
Error: listen tcp: lookup tcp/59000": unknown port

Maybe I am missing something (perhaps different format under Windows?), but this works as expected under WSL/Linux.

**Comment by mxyng** [comment]
It's the quotes. Try without `"..."`, e.g. `set OLLAMA_HOST=192.168.0.2:59000`

**Comment by CesarCalvoCobo** [comment]
It seems to work for me too configuring in System Properties - Enviroment Variables - System Variables , but without the quotes indeed
