### ISSUE TITLE
Support for safetensors

### ISSUE THREAD

**Issue by gracehubai** [ollama/ollama#2514]
Do we already support inferencing safetensors?

**Comment by pdevine** [comment]
As @easp mentioned, you can use the convert scripts to pull in a safetensors model. Going to close the issue.

**Comment by gabrielcolab** [comment]
I tried to convert, but: 

python convert.py ../moondream/tinyllava/ --outtype f16 --outfile converted.bin
    raise Exception("failed to guess 'n_ctx'. This model is unknown or unsupported.\n"
Exception: failed to guess 'n_ctx'. This model is unknown or unsupported.
Suggestion: provide 'config.json' of the model in the same directory containing model files.

**Comment by KaKi87** [comment]
Hi,
Native support would be nice.
Thanks
