### ISSUE TITLE
How to run a Pytorch model with ollama?

### ISSUE THREAD

**Issue by PriyaranjanMarathe** [ollama/ollama#2515]
Does ollama support loading a Pytorch model? I have trained a model and it's output is a .pt file. How do I use it with ollama? I tried doing the following and it doesn't seem to work.

[root@ trained_models]# ollama run model.pt
pulling manifest

Error: pull model manifest: file does not exist

**Comment by easp** [comment]
Read the docs. https://github.com/jmorganca/ollama/blob/main/docs/import.md

**Comment by PriyaranjanMarathe** [comment]
Still seems to be an issue. 

Getting the following error message

KeyError: ('torch', 'DoubleStorage')



Loading model file model
Traceback (most recent call last):
  File "/ollama/ollama/llm/llama.cpp/convert.py", line 1478, in <module>
    main()
  File "/ollama/ollama/llm/llama.cpp/convert.py", line 1414, in main
    model_plus = load_some_model(args.model)
  File "/ollama/ollama/llm/llama.cpp/convert.py", line 1274, in load_some_model
    models_plus.append(lazy_load_file(path))
  File "/ollama/ollama/llm/llama.cpp/convert.py", line 887, in lazy_load_file
    return lazy_load_torch_file(fp, path)
  File "/ollama/ollama/llm/llama.cpp/convert.py", line 843, in lazy_load_torch_file
    model = unpickler.load()
  File "/ollama/ollama/llm/llama.cpp/convert.py", line 832, in find_class
    return self.CLASSES[(module, name)]
KeyError: ('torch', 'DoubleStorage')

**Comment by PriyaranjanMarathe** [comment]
I found a library which converts torch_to_ggml 

https://github.com/Leikoe/torch_to_ggml 

Was able to load this ggml to ollama.

It didn't give any answers though. How to test if the conversion worked?

**Comment by pdevine** [comment]
Yeah, you'll need to convert the model first to GGUF (not GGML as that's no longer supported). You can then create a modelfile using the `FROM /path/to/gguf/model` which will pull in the weights and create an ollama model. You can usually use one of the convert scripts which are sitting in `ollama/llm/llama.cpp/convert*.py`. This is mostly covered in the docs that @easp mentioned.

That said, this is an area that I've been looking at, however it's still a ways off. There just are too many steps right now.

I'm going to go ahead and close the issue, but feel free to keep commenting or even reopen it.

**Comment by scefali** [comment]
@pdevine I am struggling with this. Not getting any errors but my model just responds with nothing.
