### ISSUE TITLE
Ollama Windows is much slower at inference than Ollama on WSL2

### ISSUE THREAD

**Issue by devinprater** [ollama/ollama#2529]
CPU: AMD 5500U with Radion internal GPU. Ollama runs on CPU mode on both WSL2 and Windows. Attached are the logs from Windows, and Linux.
[server.log](https://github.com/ollama/ollama/files/14303692/server.log)
[ollama-log-linux.log](https://github.com/ollama/ollama/files/14303696/ollama-log-linux.log)

**Comment by Pey-crypto** [comment]
currently ollama is only searching for nvidia based libraries, in the file server.log on the line 69 you can see the search paths for the nvidia libraries
`time=2024-02-15T14:08:41.094-06:00 level=DEBUG source=gpu.go:280 msg="gpu management search paths: `
but none for amd. You can see that it has not detected any gpu on line 70
`msg="Discovered GPU libraries: []"`
I don't think ollama supports amd based gpu for now.

**Comment by wolfgang-azevedo** [comment]
time=2024-02-16T12:44:05.907+04:00 level=INFO source=gpu.go:308 msg="Discovered GPU libraries: []"
time=2024-02-16T12:44:05.907+04:00 level=INFO source=gpu.go:262 msg="Searching for GPU management library **rocm_smi64.dll**"
RocM is used for AMD GPUs, please check if you have a compatible GPU otherwise it will fallback to CPU.

https://rocm.docs.amd.com/en/latest/

**Comment by devinprater** [comment]
I don't mind if it's on CPU. On Linux it works fine on CPU, on Windows it's slow on CPU.

**Comment by Inovvia** [comment]
I have installed ROCM/HIP for windows but I don't see rocm_smi64.dll listed in the bin folder. Additionally it seems that according to rocm smi git 

> C library for Linux 

![image](https://github.com/ollama/ollama/assets/70137651/05b4f6f0-5bca-494c-9fbd-975871f70460)

**Comment by dhiltgen** [comment]
Radeon cards are not yet supported by our native windows app.  We'll track adding that support in #2598

**Comment by uniartisan** [comment]
I run ollama on CPU in both wsl2 and Windows native, but the windows client is twice as slow as wsl2.
