### ISSUE TITLE
how to set up an ollama model storage directory

### ISSUE THREAD

**Issue by bangundwir** [ollama/ollama#2535]
make it so that you can move the model storage directory on windows ollama

**Comment by joostshao** [comment]
In the Windows environment, how can I specify the model file in a specific folder when executing Ollama?

**Comment by Leonai-do** [comment]
Same question here, the setup should ask for the directory to install the app and a path to store the models.

**Comment by MartynKeigher** [comment]
> In the Windows environment, how can I specify the model file in a specific folder when executing Ollama? the model file size is so large

Read #2551 :)

**Comment by pdevine** [comment]
You can use the `OLLAMA_MODELS` env setting. This is mentioned in the FAQ, but we haven't (yet) updated it to include Windows.

**Comment by ForGoodTech** [comment]
The FAQ only talks about the server configuration for the environment variables.

This doesn't work. How come?

`OLLAMA_MODELS=/my_folder ollama run tinyllama
`

This doesn't work either.

```
export OLLAMA_MODELS=/my_folder
ollama run tinyllama
```

The model still goes to the default folder. I want models to go to /my_folder
