### ISSUE TITLE
models list when using the same OLLAMA PATH when serving on 2 diff ports , is not the same.

### ISSUE THREAD

**Issue by aiseei** [ollama/ollama#2536]
hi.

We are serving on the same m/c on 2 diff ports. 
We have noticed that models created with our model file and running on say port 11400 is not the same when we serve on port say 11401.

Using this===> OLLAMA_HOST=x.x.x.x:11430 OLLAMA_MODELS=/home/ubuntu/ollama_models OLLAMA_DEBUG=1 ollama list

Abything we need to do diff?

thanks!

**Comment by pdevine** [comment]
Use the `OLLAMA_MODELS` env variable with the ollama server (i.e. w/ the `ollama serve` command), and not the client.
You can find out more information in the [FAQ](https://github.com/ollama/ollama/blob/main/docs/faq.md#where-are-models-stored).

Hopefully this helps! Going to go ahead and close the issue.

**Comment by aiseei** [comment]
Thanks. it tuned out the that OS level perms needed to be fixed to let us see the same list of models.
