### ISSUE TITLE
Win version capabilities

### ISSUE THREAD

**Issue by DimIsaev** [ollama/ollama#2538]
Thanks  win Version 

1. Change Path for Install

Now need config file:
2. Change Path for model 
3. Cnange port number
4. Setting   IP=0.0.0.0

**Comment by MrBenzWorld** [comment]
Also, allow use of already downloaded gguf files. Ollama just released for windows, 

Windows users mostly, We have all gguf files ,which were downloaded for text generanation webui or LM studio.

Please provide clear instructions for windows ollama .

**Comment by jmorganca** [comment]
@MrBenzWorld to add, creating Ollama models from GGUF files can be done by following https://github.com/ggerganov/ggml/blob/master/docs/gguf.md

Let me know if you hit any issues!
