### ISSUE TITLE
Windows Preview v0.1.25 Proxy authentification failed

### ISSUE THREAD

**Issue by ben0r33** [ollama/ollama#2539]
Hello,

I'm stoked about the window preview, thanks!

When pulling a model, I'm receiving proxy authentification error.
How can i either set a manual proxy configuration or add proxy authentification credentials to ollama windows?

Background: Running on windows 10, proxy is pre-setup by company rules. Manually changing proxy to local cntlm proxy would be possible

Thanks and best regards,
ben0r

**Comment by kenkoyanagi** [comment]
Following as I'm running into the same issue.

**Comment by dhiltgen** [comment]
I just posted a PR to help clarify how to set variables for the server and have them take effect - https://github.com/ollama/ollama/pull/2600

You should be able to combine that with the [proxy FAQ instructions](https://github.com/ollama/ollama/blob/main/docs/faq.md#how-do-i-use-ollama-behind-a-proxy)

**Comment by jmorganca** [comment]
Hi folks, let me know if this doesn't solve the issue. In future versions of Ollama we'll consider making this editable in Ollama directly, but until now the easiest way is to set environment variables for the app

**Comment by ben0r33** [comment]
Hi, thanks for the Quick response and helpdesk.
I can confirm using http_proxy env variable in Windows worden with a local cntlm proxy for authentification in ollama.
