### ISSUE TITLE
Where the models installed, I installed llama2 and I am not sure I want to keep it I dont have much space (windows)Help?.

### ISSUE THREAD

**Issue by APISeeker** [ollama/ollama#2548]
![image](https://github.com/ollama/ollama/assets/145594487/3790c732-144a-4bae-9823-94d2d14499cd)
So I just installed ollama and wrote a comman,d to download llama2, but I dont see much, here is a screenshot and nothing indicating presence of models?

**Comment by APISeeker** [comment]
Ok I think I found them in C:/Users/username/.ollama

**Comment by jimscard** [comment]
If you don't want to keep a model, you should delete it using `ollama rm llama2`  Don't mess with the files in the .ollama folder directly.

**Comment by MartynKeigher** [comment]
Also see, #2551
