### ISSUE TITLE
Invalid characters in windows command prompt

### ISSUE THREAD

**Issue by jmorganca** [ollama/ollama#2549]
![image](https://github.com/ollama/ollama/assets/251292/82f4d8a2-6d91-4a80-a8b5-e09f07132552)

**Comment by binoychitale** [comment]
Hi @jmorganca !

I was trying to look into this, and it seems like the problem might be the _CMD_ application (which seems to be used here in the screenshot)

It seems that the old CMD terminal has certain fonts that cannot render all unicode characters.

I am seeing that the _Windows Terminal_ is able to render the characters correctly.

Furthermore, changing the font in _CMD_ from `Consolas` to `Cascadia Code` fixes the rendering

Screenshot from __Windows Terminal__:
![image](https://github.com/ollama/ollama/assets/17764984/151c102a-ee26-4ae5-9d56-e70b2aed974c)

Screenshot from __CMD__ with font set to `Consolas`
![image](https://github.com/ollama/ollama/assets/17764984/b758e4e9-d65a-4ff9-a7f4-6f7fbb9a753c)

Screenshot from __CMD__ with font set to `Cascadia Code`
![image](https://github.com/ollama/ollama/assets/17764984/36f5fab4-65a0-49ca-9ca3-6816bfbafc79)

__Tl;DR__
It seems that the font set in the terminal in the screenshot does not support the `▕` unicode character

Not sure whether this is something ollama should fix?

**Comment by dhiltgen** [comment]
It looks like it should theoretically be possible for us to call [SetCurrentConsoleFontEx](https://learn.microsoft.com/en-us/windows/console/setcurrentconsolefontex) although I am a tad nervous about what the blast radius might be for international locales...

**Comment by dhiltgen** [comment]
I don't think changing fonts on the fly is the right answer.
