### ISSUE TITLE
WIndows questions sorry

### ISSUE THREAD

**Issue by drewskidang** [ollama/ollama#2550]
How do you login using windows since theres no cat funciton

**Comment by pdevine** [comment]
Can you be more elaborate? I'm having a hard time understanding the issue.

**Comment by jmorganca** [comment]
@drewskidang on windows you can use `type %USERPROFILE%\.ollama\id_ed25519.pub` to get your Ollama public key. Let me know if this doesn't solve your issue. Thanks so much!
