### ISSUE TITLE
Can we change where the models are stored in windows

### ISSUE THREAD

**Issue by Gyro0o** [ollama/ollama#2551]
As far as I know the models are automatically downloaded to C:/Users/username/.ollama
But can we change the directory to another one due to storage issues?

**Comment by MartynKeigher** [comment]
You are correct and 'Yes' you can move them anywhere you like, via the `OLLAMA_MODELS` environment variable. 

Docs: https://github.com/ollama/ollama/blob/main/docs/faq.md#where-are-models-stored

**Comment by fixtse** [comment]
To create an environment variable on Windows you can follow these instructions:

Open Windows Settings.
Go to System.
Select About
Select Advanced System Settings.
Go to the Advanced tab.
Select Environment Variables....
Click on New...
And create a variable called OLLAMA_MODELS pointing to where you want to store the models

**Comment by APISeeker** [comment]
Thanks I will try it out later.

**Comment by Gyro0o** [comment]
> You are correct and 'Yes' you can move them anywhere you like, via the `OLLAMA_MODELS` environment variable.
> 
> Docs: https://github.com/ollama/ollama/blob/main/docs/faq.md#where-are-models-stored

Understood
Thanks

**Comment by Gyro0o** [comment]
> To create an environment variable on Windows you can follow these instructions:
> 
> Open Windows Settings. Go to System. Select About Select Advanced System Settings. Go to the Advanced tab. Select Environment Variables.... Click on New... And create a variable called OLLAMA_MODELS pointing to where you want to store the models

Worked perfectly 
Thank u

**Comment by roocell** [comment]
OLLAMA_MODELS env variable also didn't work for me - do we have to reboot or reinstall ollama?
i assume it would just pick up the new path when we run "ollama run llama2"

**Comment by lafe** [comment]
> OLLAMA_MODELS env variable also didn't work for me - do we have to reboot or reinstall ollama? i assume it would just pick up the new path when we run "ollama run llama2"

Normally, you have to at least reopen the "command line" process, so that the environment variables are filled (maybe restarting ollama is sufficient). If you use PowerShell, you can use `$env:OLLAMA_MODELS` to check if the environment variable is set. If you use the Windows command prompt ("cmd"), you can use `set` to get a list of all environment variables.

**Comment by ninjanimus** [comment]
For those the custom path is not considered even after adding OLLAMA_MODELS environment variable and restarting the Terminal. Try restarting the OS once, then it is working. Might be the environment variables are stored in memory of the running Ollama process.

**Comment by uocnb** [comment]
I found that the `Ollama app.exe` is running in the background caused the new env var not update. You can quit it by right click on the Ollama icon on the system tray.

**Comment by JuninhoFreitas** [comment]
I just started the installer in cmd with the following directive:

```
$ .\OllamaSetup.exe /DIR=D:\MYDIRECTORY
```

**Comment by phpgit** [comment]
> I just started the installer in cmd with the following directive:
> 
> ```
> $ .\OllamaSetup.exe /DIR=D:\MYDIRECTORY
> ```

What a life saver! It works great, thanks for sharing!

**Comment by arfans22** [comment]
> OLLAMA_MODELS

worked really well at my first try!

**Comment by zombodotcom** [comment]
tried this, and also the .\OllamaSetup.exe /DIR=D:\MYDIRECTORY

it still downloads them to the C drive. 
Tried moving the models and making the OLLAMA_MODELS  Variable does not solve the issue of putting the blobs into the new directory, still tries to download them and doesnt register that they are there.

**Comment by arfans22** [comment]
> tried this, and also the .\OllamaSetup.exe /DIR=D:\MYDIRECTORY
> 
> it still downloads them to the C drive. 
> Tried moving the models and making the OLLAMA_MODELS  Variable does not solve the issue of putting the blobs into the new directory, still tries to download them and doesnt register that they are there.
> 
> It does download to the new directory though. which is a plus

You have to make anothee variable named OLLAMA_ORIGIN and make the value just  . (Dot)

**Comment by zombodotcom** [comment]
still making me redownload the 38gb model

**Comment by Kazakuba** [comment]
Close all ollama tasks 
Move whole models folder 
Env variable needs to be added for user not as system variable or in path 
Or try;  mklink /D C:\Users\<User>\.ollama\models E:\New\Model\Location (for link to work you must first move folder from C)

**Comment by zombodotcom** [comment]
Added to both before posting

**Comment by gary0318** [comment]
Nothing was working for me. So, I killed Ollama app.exe and from there on I can not start ollama server. The server log is empty and the main log says server error. I've reinstalled ollama, rebooted the computer checked my environment variables... nothing is working. When it gives me the error it leaves Ollama app.exe running and I have to kill it again..

**Comment by amirali-mi10** [comment]
if you guys get confused, let me explain step by step:

1-first of all uninstall ollama (if you already installed)

2-then follow this:
Open Windows Settings.
Go to System.
Select About
Select Advanced System Settings.
Go to the Advanced tab.
Select Environment Variables....
Click on New...
And create a variable called OLLAMA_MODELS pointing to where you want to store the models(set path for store models)


3-after adjusting that then open the path that you downloaded OllamaSetup.exe (setup file) 

4-then on file explorer write cmd to open cmd on that path

5-on cmd write--> OllamaSetup.exe /DIR=D:\MYDIRECTORY

6-after installation everything should works well and both ollama and models will save same drive you defined for it

**Comment by Luojz** [comment]
> I just started the installer in cmd with the following directive:我刚刚在命令提示符中使用以下指令启动了安装程序：
> 
> ```
> $ .\OllamaSetup.exe /DIR=D:\MYDIRECTORY
> ```

A thumbs-up from China："牛 B"

**Comment by simpleetech** [comment]
> if you guys get confused, let me explain step by step:
> 
> 1-first of all uninstall ollama (if you already installed)
> 
> 2-then follow this: Open Windows Settings. Go to System. Select About Select Advanced System Settings. Go to the Advanced tab. Select Environment Variables.... Click on New... And create a variable called OLLAMA_MODELS pointing to where you want to store the models(set path for store models)
> 
> 3-after adjusting that then open the path that you downloaded OllamaSetup.exe (setup file)
> 
> 4-then on file explorer write cmd to open cmd on that path
> 
> 5-on cmd write--> OllamaSetup.exe /DIR=D:\MYDIRECTORY
> 
> 6-after installation everything should works well and both ollama and models will save same drive you defined for it

I'm not sure if it was just me, but it worked when I set the environment variable as a "User Variable" not a "System Variable"

**Comment by zalito12** [comment]
> > OLLAMA_MODELS env variable also didn't work for me - do we have to reboot or reinstall ollama? i assume it would just pick up the new path when we run "ollama run llama2"
> 
> Normally, you have to at least reopen the "command line" process, so that the environment variables are filled (maybe restarting ollama is sufficient). If you use PowerShell, you can use `$env:OLLAMA_MODELS` to check if the environment variable is set. If you use the Windows command prompt ("cmd"), you can use `set` to get a list of all environment variables.

I can cornfirm you must restart Ollama, opening a new cmd is not enough.
Also, to see a var on cmd you can use echo, as ``echo %OLLAMA_MODELS%``

**Comment by angusgee** [comment]
> I just started the installer in cmd with the following directive:
> 
> ```
> $ .\OllamaSetup.exe /DIR=D:\MYDIRECTORY
> ```

This is the one thank you for sharing 🔥🔥🔥

**Comment by mumangguo** [comment]
nice

**Comment by AdityaAdaki21** [comment]
> > I just started the installer in cmd with the following directive:
> > ```
> > $ .\OllamaSetup.exe /DIR=D:\MYDIRECTORY
> > ```
> 
> What a life saver! It works great, thanks for sharing!

THANK YOU!!!!

**Comment by jiriehrlich** [comment]
Uninstall Ollama
Create System Variable OLLAMA_MODELS
Run OllamaSetup.exe /DIR=<your drive>:\Ollama

**Comment by omesh845** [comment]
> Uninstall Ollama Create System Variable OLLAMA_MODELS Run OllamaSetup.exe /DIR=:\Ollama

thanks man!! it worked!!!

**Comment by codeisnotcode** [comment]
> > if you guys get confused, let me explain step by step:
> > 1-first of all uninstall ollama (if you already installed)
> > 2-then follow this: Open Windows Settings. Go to System. Select About Select Advanced System Settings. Go to the Advanced tab. Select Environment Variables.... Click on New... And create a variable called OLLAMA_MODELS pointing to where you want to store the models(set path for store models)
> > 3-after adjusting that then open the path that you downloaded OllamaSetup.exe (setup file)
> > 4-then on file explorer write cmd to open cmd on that path
> > 5-on cmd write--> OllamaSetup.exe /DIR=D:\MYDIRECTORY
> > 6-after installation everything should works well and both ollama and models will save same drive you defined for it
> 
> I'm not sure if it was just me, but it worked when I set the environment variable as a "User Variable" not a "System Variable"
---
I did the above and it did not work until I realized it is important for the original id_ed25519 and id_ed25519.pub key files to be retained in order to be able to see the moved Ollama Models. If you moved these with the models, when you reinstall ollama, it will create new a new set of keys (these two files) in C:\users\<username>\.ollama and then the previously loaded models can't be read by Ollama. The solution is to copy these two files from your moved model subdirectory back into C:\users\<username>\.ollama, overwriting the newly created keys.

**Comment by manotawi** [comment]
All my AI apps and models are installed in a ssd so I can move them with me. So to preserve that, here was my method:
1- Move the ollama installation where desired, example F:\AI\OLLAMA
2- Inside the ollama installation folder create a folder for the models, example F:\AI\OLLAMA\MODELS
3- create a bat file and add the following to it:
SET OLLAMA_MODELS=%~dp0MODELS
start "" "ollama app.exe"

and tada, with that you have a portable version of ollama, that does not care about the drive or folder it is installed in

**Comment by JTMarsh556** [comment]
Am I reading this correctly, you cannot move all of the existing models you have?  You need a fresh install?  

You can't just set the variable and then copy the models in the new path?

**Comment by pratyush0898** [comment]
thanks you, but more you can do is:
- **Move ollama**: (folder) C:\Users\ADMIN\AppData\Local\Programs\Ollama to /path/to/Ollama
- **Change env variable**: Open Windows Settings.
  - press `Win + R`
  - type `systempropertiesadvanced` & perss enter
  - Go to Environment variables
  - Under `User variables` Doble-click (open) PATH (enviorment variable)
  - Locate `C:\Users\ADMIN\AppData\Local\Programs\Ollama` & change it to `/path/to/Ollama/

here, you go, now your whole OLLAMA is in different location/drive you'd like

**Comment by ChanduTadanki** [comment]
> For those the custom path is not considered even after adding OLLAMA_MODELS environment variable and restarting the Terminal. Try restarting the OS once, then it is working. Might be the environment variables are stored in memory of the running Ollama process.

This worked for me. Thanks.

**Comment by buffos** [comment]
It depends if ollama was installed as system wide or just for the user.
You have two options when you create the Env variables in windows. System and User. Start with the user env, which will probably work and not a system env variable.

**Comment by nikolatesla20** [comment]
> To create an environment variable on Windows you can follow these instructions:
> 
> Open Windows Settings. Go to System. Select About Select Advanced System Settings. Go to the Advanced tab. Select Environment Variables.... Click on New... And create a variable called OLLAMA_MODELS pointing to where you want to store the models

Doesn't work

**Comment by nityam1101** [comment]
> You are correct and 'Yes' you can move them anywhere you like, via the `OLLAMA_MODELS` environment variable.
> 
> Docs: https://github.com/ollama/ollama/blob/main/docs/faq.md#where-are-models-stored

Updated Link: https://github.com/ollama/ollama/blob/main/docs/faq.mdx#where-are-models-stored

**Comment by fkdp06** [comment]
From now you can change your models location from the settings:

<img width="1182" height="839" alt="Image" src="https://github.com/user-attachments/assets/48679757-058a-4567-9580-7181ec88b9fc" />
