### ISSUE TITLE
Phi-2-X

### ISSUE THREAD

**Issue by axrwl** [ollama/ollama#2556]
https://huggingface.co/axra/phi-2-x-0.1

A very high performing finetune of phi-2

**Comment by jmorganca** [comment]
Hi there, thanks so much for making this model. Would it be possible to import and publish it to your own namespace in Ollama?

Docs to do that are here: https://github.com/ollama/ollama/blob/main/docs/import.md#importing-pytorch--safetensors

It's a few steps, and so let me know if you have any issues (please feel free to shoot me an email!)
