### ISSUE TITLE
How can I use ollama in pycharm

### ISSUE THREAD

**Issue by Matrixsun** [ollama/ollama#2557]
Hi all. I want use ollama in pycharm, how to do it?

**Comment by surfaceflinger** [comment]
any plugin that has openai api support and allows you to change the endpoint will work.

**Comment by pdevine** [comment]
I haven't used pycharm, but a quick google search revealed:
* https://www.linkedin.com/pulse/open-source-coding-companion-harnessing-ollama-3-mor-dabastany--kpivf/
* https://blog.jetbrains.com/pycharm/2024/03/best-pycharm-plugins/
* https://plugins.jetbrains.com/plugin/21056-codegpt

The codegpt plugin that @alexwwang mentioned has a lot of reviews of users using Ollama.
