### ISSUE TITLE
Error: Head "http://127.0.0.1:11434/": EOF (Windows 10)

### ISSUE THREAD

**Issue by EdwHA** [ollama/ollama#2560]
Thank you for the OLLAMA.
So far, I've been using ollama in WSL2, and when the windows version came out, I experienced it right away. But..

Microsoft Windows [Version 10.0.19045.4046]
C:\Users\Name>ollama pull nous-hermes:13b-llama2-q6_K
Error: Head "http://127.0.0.1:11434/": EOF

C:\Users\Name>ollama list
Error: Head "http://127.0.0.1:11434/": EOF

ollama help provides a normal help

from app.log:
...
time=2024-02-17T13:20:54.375+03:00 level=WARN source=server.go:109 msg="server crash 16 - exit code 1 - respawning"
time=2024-02-17T13:20:54.875+03:00 level=ERROR source=server.go:112 msg="failed to restart server exec: already started"
time=2024-02-17T13:21:10.884+03:00 level=WARN source=server.go:109 msg="server crash 17 - exit code 1 - respawning"
time=2024-02-17T13:21:11.385+03:00 level=ERROR source=server.go:112 msg="failed to restart server exec: already started"

from server.log:
...
Error: listen tcp 127.0.0.1:11434: bind: An attempt was made to access a socket in a way forbidden by its access permissions.
Error: listen tcp 127.0.0.1:11434: bind: An attempt was made to access a socket in a way forbidden by its access permissions.
Error: listen tcp 127.0.0.1:11434: bind: An attempt was made to access a socket in a way forbidden by its access permissions.

**Comment by Gonrizard** [comment]
I had this problem and I discovered that it was because I had added a portproxy to be able to access the ollama API from Windows that was running on WSL2.

To see if this is it, run this command in cmd: 

netsh interface portproxy show all

If so, you need to remove it with this command:

netsh interface portproxy delete v4tov4 listenport=11434 listenaddress=127.0.0.1 

or 

netsh interface portproxy delete v4tov4 listenport=11434 listenaddress=0.0.0.0

**Comment by EdwHA** [comment]
> I had this problem and I discovered that it was because I had added a portproxy to be able to access the ollama API from Windows that was running on WSL2.
> 
> To see if this is it, run this command in cmd:
> 
> netsh interface portproxy show all
> 
> If so, you need to remove it with this command:
> 
> netsh interface portproxy delete v4tov4 listenport=11434 listenaddress=127.0.0.1
> 
> or
> 
> netsh interface portproxy delete v4tov4 listenport=11434 listenaddress=0.0.0.0

Thanks, it solved my problem.

**Comment by szymonk92** [comment]
Same error, no proxy

**Comment by tzzed** [comment]
Hello I solved the same issue see [here](https://github.com/ollama/ollama/issues/2627#issuecomment-2325218799)
