### ISSUE TITLE
Potential Regression with Model switching

### ISSUE THREAD

**Issue by libbaz** [ollama/ollama#2570]
**Issue:**
I just pulled the latest ollama docker image (Ollama v0.1.25) and have noticed api `/chat` requests are no longer switching the Model Template on templates based on the same Models. In the past this wasnt an issue.

**Steps to reproduce:**
create Foo-1 from model "Foo"
create Foo-2 from model "Foo"
create Bar-1 from model "Bar"

make a chat request with Foo-1 = response uses Foo-1
make a chat request with Foo-2 = response uses Foo-1
make a chat request with Bar-1 = (model is switched to Bar-1) response uses Bar-1
make a chat request with Foo-2 =  (model is switched to Foo-2) response uses Foo-2

**Expected:**
make a chat request with Foo-1 = response uses Foo-1
make a chat request with Foo-2 =  (model is switched to Foo-2) response uses Foo-2
make a chat request with Bar-1 = (model is switched to Bar-1) response uses Bar-1

**Comment by jmorganca** [comment]
Hi there, sorry about this issue. It was fixed recently on main and will be fixed in the next release. Here is the original issue: https://github.com/ollama/ollama/issues/2492
