### ISSUE TITLE
Storing models on external drive

### ISSUE THREAD

**Issue by shersoni610** [ollama/ollama#2571]
Hello,

I have limited memory on the OS hard drive. So I want to store all the models 
in /usr/share/ollama/.ollama/models/blobs on an external drive. After downloading
the models, I made a softlink as:

sudo ln -s ~/Disk2/Models/Ollama/blob /usr/share/ollama/.ollama/models/blobs

but when I rurn the code, I get the message:

Error: mkdir /usr/share/ollama/.ollama/models/blobs: file exists

I do not understand why ollama i trying to perform "mkdir". Can someone help?

**Comment by Natfan** [comment]
Consider setting the `OLLAMA_MODELS` environment variable to point to the location of your model files. This should remove issue caused by symlinking across physical drives.

**Comment by dhiltgen** [comment]
Please refer to https://github.com/ollama/ollama/blob/main/docs/faq.md#where-are-models-stored for adjusting where models are stored.

**Comment by 34r7h** [comment]
i'm using red hat. according to the docs, is it as simple as adding `export OLLAMA_MODELS=/home/models` to bashrc?

i did that and checked it's set in a new terminal but ollama is still using the original location to save models. Is there another step?

**Comment by dhiltgen** [comment]
@34r7h ollama is a client-server architecture, so that setting is needed on the server.  If you installed using our install script, it set up a systemd init config, which you would need to update to include that variable.  See [this section](https://github.com/ollama/ollama/blob/main/docs/faq.md#setting-environment-variables-on-linux) of the faq for detailed instructions.

**Comment by theaidran** [comment]
You can change HOME variable. As if  Ollama models as default are stored in ~/,ollama/models
Before installing Ollama simply change HOME variable.
In Python for eg:
import os
os.environ['HOME'] = '/content/MyDrive'
