### ISSUE TITLE
Please teach for me :((  -> how can i fine tune with ollama?

### ISSUE THREAD

**Issue by KDH-Korea** [ollama/ollama#2575]
I want to fine-tune the Mistral model imported using Ollama, but there is no information available, and it's even more challenging to find information in Korea where not many people are familiar with Ollama. I would appreciate it if you could provide information on how to fine-tune the model using Ollama.

**Comment by jondwillis** [comment]
Ollama is a way to download, run, and serve models, it does not provide fine-tuning capabilities as far as I know.

**Comment by jmorganca** [comment]
Hi thanks for the issue. Fine-tuning isn't supported yet in Ollama, but I'll go ahead and merge this with [#finetunin](https://github.com/ollama/ollama/issues/156)
