### ISSUE TITLE
JSON mode should disallow trailing whitespace

### ISSUE THREAD

**Issue by joliss** [ollama/ollama#2577]
When using `--format json`, small models sometimes try to add more text after the object, resulting in infinite whitespace.

```
$ ollama run qwen:0.5b-chat-v1.5-q4_K_M 'Reply with only an example JSON object' --format json
{
  "name": "John",
  "age": 30,
  "city": "New York"
}








[whitespace continues indefinitely]
```

I think this could be easily fixed by disallowing trailing whitespace in JSON mode; that is, by forcing the assistant message to terminate immediately after the closing `}` of the top-level JSON object.

**Comment by ParthSareen** [comment]
Would recommend trying out structured outputs! Json mode will eventually be deprecated
