### ISSUE TITLE
Windows Preview 8x slower than Running Through Docker

### ISSUE THREAD

**Issue by chigkim** [ollama/ollama#2581]
I've been running Ollama through Docker on Windows with cpu only.
Someone running Windows preview for the same time told me Ollama was extremely slow, like no response for 5 minutes.
So I tried Windows preview for myself, and I can confirm that The speed is extremely slow.
Windows preview: Total: 77.38 secs, Load: 4.72 secs, Prompt: 46 tokens (0.80 t/s), Output: 13 tokens (0.86 t/s)  
Docker: Total: 9.28 secs, Load: 1.15 secs, Prompt: 26 tokens (4.44 t/s), Output: 11 tokens (4.82 t/s)
Everything is slower on Windows preview overall.
I used the same model, same prompt, same machine.
Hopefully it get sorted out soon!

**Comment by chuangtc** [comment]
I used the same model (mistral:7b), same prompt, same Win11 machine (Intel Core i5-12400, no NVIDIA GPU). The Windows Preview version is 8~10x slower than Ubuntu 22.04.3 on WSL2. (eval rate is 0.9 tokens/s vs 6 tokens/s)

**Comment by chuangtc** [comment]
The tool that I used for testing throughput performance of eval time is this one.
https://github.com/aidatatools/ollama-benchmark/
Maybe @jmorganca can think about how to integrate this into the original ollama project.

**Comment by dhiltgen** [comment]
We fixed CPU performance on windows in 0.1.27.  Can you try again and see if that resolves your performance problem?  If not, could you share logs from the container and native windows server runs for comparison so we can see why there's still a difference?

**Comment by chuangtc** [comment]
I tried it in 0.1.27 and it seems working fine now in native Windows application. The details had been published here. https://medium.com/aidatatools/ollama-v0-1-27-ai-benchmark-23dc598bb8dc
<img width="700" alt="Screenshot Ollama v0 1 27 AI benchmark" src="https://github.com/ollama/ollama/assets/2288469/7fd395d1-2e97-4a98-8347-c39783246a82">
