### ISSUE TITLE
How to make a PR to fix a modelfile?

### ISSUE THREAD

**Issue by StefanDanielSchwarz** [ollama/ollama#2583]
Couldn't find the modelfiles in this repo, but would like to fix and make a PR for the Mixtral modelfile. Its prompt format is wrong, fixed it locally, but how to contribute that back to the project?

**Comment by aiseei** [comment]
Could you elaborate on what is wrong so others maybe could patch till the PR is done?

**Comment by pdevine** [comment]
Hey @StefanDanielSchwarz . I'm sorry this issue got buried in the avalanche of issues! Thanks so much for taking the time to file it. I've updated each of the 8x7b models to have the correct template (i.e. without the space at the beginning).

Unfortunately there's no way *yet* for people to contribute to the library Modelfiles, but we're getting closer to opening that up. It will most likely be in a different repo than the main `ollama/ollama` one. Still trying to work out the details.

**Comment by pdevine** [comment]
Oh, also, I should note that if you pull the model again with `ollama pull mixtral` it will *only* download the new template and it won't pull the weights again.
