### ISSUE TITLE
Question on model updating

### ISSUE THREAD

**Issue by owenzhao** [ollama/ollama#2586]
I know I could download the latest model when a model is not installed. Say:

```swift
ollama run llama2
```

After some days, say one month, the model will be updated. Can ollama updates to the latest model automatically? I didn't find a way to do that. 

Please help.

**Comment by pdevine** [comment]
Hey @owenzhao , thanks for the issue. You can always pull again w/ `ollama pull llama2`. I've been looking at some ways to make this easier (maybe `ollama pull --upgrade-all`) but we never ended up w/ a satisfactory way of doing it.

**Comment by hoyyeva** [comment]
Hello @owenzhao, thank you for bringing this to our attention. I understand that pulling again with `ollama pull laama2` might not be the best solution will keep the community updated once we have some satisfactory way to improve the experience! I will be closing this issue for now. 

Hello @owenzhao, thanks for highlighting this to us. I understand that pulling again with `ollama pull laama2` to upgrade might not be the best solution but we're on it to find a better solution. We'll make sure to keep everyone in the loop as soon as we have an update that enhances the experience! I'll close this issue for now, but rest assured, we're actively working on it!
