### ISSUE TITLE
Windows ARM support

### ISSUE THREAD

**Issue by PeronGH** [ollama/ollama#2589]
I tried to run it on a Windows on ARM device and the installer refused to exectue.

![image](https://github.com/ollama/ollama/assets/18367871/93600aed-a45e-4a74-9253-b36c3f2b731d)

Is there any plan for the native Windows on ARM support? Or is it possible to remove the architecture checking and make the x86 version work on ARM devices?

**Comment by jmorganca** [comment]
@dhiltgen AFAIK windows has pretty good emulation support for running amd64 apps on arm64 windows – it might be worth removing this hard check as a starting point

**Comment by dhiltgen** [comment]
PR #3111 will at least allow us to install, and run under emulation.  Performance isn't good, so I'm not going to close this ticket until we actually build a native ARM binary.

**Comment by hmartinez82** [comment]
@dhiltgen How can I be of help. I have a Windows on ARM laptop (the Surface Pro 9 ARM64 flavor)

**Comment by hmartinez82** [comment]
I was able to compile it locally for ARM64. I'll try to create a PR soon
![image](https://github.com/ollama/ollama/assets/1100440/bfcfe0fe-63d6-425c-af3d-ddb3c51ecfa6)

**Comment by dhiltgen** [comment]
@hmartinez82 PR's definitely welcome to enable Windows ARM!  Thanks!

**Comment by hmartinez82** [comment]
@dhiltgen https://github.com/ollama/ollama/pull/3972
