### ISSUE TITLE
i am a new fish, how to restart or stop the ollama under linux?

### ISSUE THREAD

**Issue by jaqenwang** [ollama/ollama#2594]
after i updated a model,  i want to refresh everthing again, how to do that

**Comment by BruceMacD** [comment]
Hi @jaqenwang you don't need to restart ollama for the changes to take effect when you update a model, but if you wish to here is how:
**Mac:** Exit the Ollama toolbar application and re-open it.
**Linux:** Run `systemctl restart ollama`.

Let me know if you need anymore help.

**Comment by jngjr417intel** [comment]
> Hi @jaqenwang you don't need to restart ollama for the changes to take effect when you update a model, but if you wish to here is how: **Mac:** Exit the Ollama toolbar application and re-open it. **Linux:** Run `systemctl restart ollama`.
> 
> Let me know if you need anymore help.

Outstanding. Fixed for me. Thanks for the direct answer and for reading the FAQ for us :)

**Comment by jomardyan** [comment]
ERROR:systemctl:Unit ollama.service could not be found.

**Comment by xucian** [comment]
> on OS X brew services restart ollama

dug the whole internet for this

**Comment by Ebrahim-Ramadan** [comment]
anybody know by anychance on windows?

**Comment by MinSomai** [comment]
for me. I had to add new Environment line in `/etc/systemd/system/ollama.service` file.

```
[Service]
Environment="OLLAMA_ORIGINS=*"
```

after this

`sudo systemctl daemon-reload`

`sudo systemctl stop ollama`

`sudo systemctl start ollama`
