### ISSUE TITLE
Conversation context no longer taken into account?

### ISSUE THREAD

**Issue by dictoon** [ollama/ollama#2595]
I'm running ollama version is 0.1.25 on macOS.

It looks like the LLM is no longer taking earlier messages into account, even though they definitely fit in the context window of the models I'm using.

I'm having a conversation like this:

```
- User: Here is some text, please summarize it.
- Assistant: <outputs a summary>
- User: Now, please summarize what you just wrote.
- Assistant: <outputs a completely unrelated summary>
```

I've tried both the `llama2` and `mixtral` models. I've tried with the Open WebUI interface, directly with `ollama run --verbose llama2`, and with the OpenAI API talking to my locally-running Ollama.

I'm always observing the same behavior: the model simply ignores all context in my second query.

This used to work just fine before I updated Ollama (I was using a version a few weeks old, but I don't recall which).

**Comment by dictoon** [comment]
If I truncate the first user query to 5000 characters (not tokens), then I'm getting a correct answer to the second user query. So it looks like I'm hitting some kind of context window size limit? I'm far from the 4K context window, and in any case, assuming the window is sliding, there's plenty of context in the assistant's answer that immediately precedes the second user query.

**Comment by dictoon** [comment]
Maybe related? [PSA: You can (and may want to) disable Mixtral's Sliding Window!](https://www.reddit.com/r/LocalLLaMA/comments/18k0fek/psa_you_can_and_may_want_to_disable_mixtrals/)

**Comment by jmorganca** [comment]
Hi @dictoon thanks for the issue. It seems you're hitting the context limit size. To increase it: https://github.com/ollama/ollama/blob/main/docs/faq.md#how-can-i-specify-the-context-window-size

**Comment by dictoon** [comment]
Thanks @jmorganca.

I'm invoking Ollama through OpenAI's API in Python. Do you know if there's documentation on passing additional options such as context size?

**Comment by dictoon** [comment]
Two more questions:

- I thought the context window was defined by the model and couldn't be changed. Do I understand correctly that in the case of talking to Ollama via OpenAI's API, somehow the context window is shrunk? For performance perhaps?

- I had zero such problems when using Ollama's native Python API.

**Comment by dictoon** [comment]
Using Ollama's native Python API, it looks like this works:

```
response = ollama.chat(
    model=Plugin.OLLAMA_MODEL,
    messages=conversation,
    options={
        "num_ctx": 4096,
    })
```

Would still appreciate answers to my previous questions. Thanks!

**Comment by PhilipAmadasun** [comment]
@jmorganca @dictoon  If I have a user input of context length 27000, and use the `options={"num_ctx": 4096,}` what specifically would this do? Will this have the input be broken into batches of size 4096 and sent in all at once or one at a time or something?

**Comment by PhilipAmadasun** [comment]
@dictoon Thank you for the reply. Just so I make sure I understand. Let's say I'm using mistral, and mistral's max context (according to google) is 8000, and "attention span" (according to google) is 128000. If I have a 27000 length user query. What exactly happens? If I set `num_ctx: 4096` Does mistral just grab the last 4096 token sequence from the 27K user query? Then process the 4096 sequence along with the 128K window it grabs from the previously established overall context (In the case of the RESTful API, I'm talking about that `body['context']` thing)?

**Comment by dictoon** [comment]
@PhilipAmadasun Excellent question: sadly, I have no idea :)

**Comment by PhilipAmadasun** [comment]
@dictoon Sure! here's the [link](https://github.com/ollama/ollama/issues/2714)

**Comment by gaardhus** [comment]
> Thanks @jmorganca.
> 
> I'm invoking Ollama through OpenAI's API in Python. Do you know if there's documentation on passing additional options such as context size?
> 
> I've tried this, but it doesn't work:
> 
> ```
> options = dict(num_ctx=4096)
> response = self.client.chat.completions.create(
>     model=Plugin.LLM_MODEL, messages=conversation, extra_body={"options": options})
> ```

This does not work since the extra_body payload is appended to the rest of the body through an extra_json field, rather than being directly merged with it
