### ISSUE TITLE
Windows preview - please let us set the location where models are stored

### ISSUE THREAD

**Issue by axefrog** [ollama/ollama#2602]
My drive C is a bit ancient right now. It's an old 250GB SSD and at any given time seems to have about 5-10gb free, so I'm forever doing cleanups to stop it running out of space. In contrast, I have about 2-3TB of free space on my other drives. I would _much_ prefer it if ollama would store models on one of those drives. How much effort would it be to make that happen?

**Comment by jmorganca** [comment]
Hi there, models are stored by default in `~/.ollama/models`, however you can change that by setting `OLLAMA_MODELS`. The FAQ has some good instructions on this: https://github.com/ollama/ollama/blob/main/docs/faq.md#how-do-i-set-them-to-a-different-location for Windows specifically: https://github.com/ollama/ollama/blob/main/docs/faq.md#setting-environment-variables-on-windows

**Comment by axefrog** [comment]
@jmorganca Thanks for the reply.
