### ISSUE TITLE
`Ollama run` Error

### ISSUE THREAD

**Issue by iaoxuesheng** [ollama/ollama#2606]
![2024-02-20 14-08-04 的屏幕截图](https://github.com/ollama/ollama/assets/94165844/577e35d9-8552-433d-87a3-1b8e6bd00593)

**Comment by Pey-crypto** [comment]
Looks like you are behind a firewall. Try using a vpn

**Comment by iaoxuesheng** [comment]
我用了vpn也是一样，用的日本节点

**Comment by Pey-crypto** [comment]
change the node to another location, ex: UK or the US.

**Comment by javaDer** [comment]
close vpn try

**Comment by dhiltgen** [comment]
Looks like a dup of #3504
