### ISSUE TITLE
Return citations for given answers

### ISSUE THREAD

**Issue by SteffenBrinckmann** [ollama/ollama#2610]
Hey, 
would it be possible to return citations, too. Just like perplexity does?
Best, Steffen

**Comment by easp** [comment]
Ollama just provides a way to run and query LLMs. LLMs on their own can't provide citations of the information they provide and if they are asked to, they will usually make up citations to sources that don't exist. 

Perplexity has another layer between user and LLM which allows the LLM to retrieve information using internet search and then create an answer based on that. This is generally known as Retrieval Augmented Generation, or RAG. At this point, RAG has to be implemented on top of Ollama. I don't know of any ready-made implementations that can provide citations, though.
