### ISSUE TITLE
Support for moondream?

### ISSUE THREAD

**Issue by oliverbob** [ollama/ollama#2611]
Is there a support for [moondream](https://github.com/vikhyat/moondream)?

Its like small llava.

![image](https://github.com/ollama/ollama/assets/23272429/8fe94033-d12c-4d75-b66c-aad1e4240c3b)

**Comment by jmorganca** [comment]
Would love this too! Merging with https://github.com/ollama/ollama/issues/2259

**Comment by CoderCowMoo** [comment]
Hi!
This has been supported, but how do we use it? Also Moondream2 is the same arch as moondream1 I believe.

Mainly what I'm asking is, is there a Modelfile documentation or argument to use an mmproj and language model ggufs together?
