### ISSUE TITLE
AutoModelForCausalLM and .ollama/models

### ISSUE THREAD

**Issue by Demirrr** [ollama/ollama#2614]
Can we create an instance of  `AutoModelForCausalLM` from downloaded language models `~/.ollama/models`?

By this, the finetunning and using finetuned model via ollama would be easier.
```python
from transformers import AutoModelForCausalLM, AutoTokenizer
model_id = "mistralai/Mixtral-8x7B-v0.1"
tokenizer = AutoTokenizer.from_pretrained(model_id)
model = AutoModelForCausalLM.from_pretrained(model_id)
```

**Comment by jmorganca** [comment]
Hi @Demirrr, thanks so much for creating an issue. Check out [this doc](https://github.com/jmorganca/ollama/blob/main/docs/import.md) for instructions on importing PyTorch or Safetensors models (and there's a maintainer that's working on making this much easier).

In the meantime, I know there's quite a few steps, and so let me know if I can help you convert the model at all – my email is in my github profile :)

**Comment by categoric-dev** [comment]
@jmorganca Could we potentially transfer or convert the ollama blob into a model.safetensors format, enabling its utilization alongside AutoModelForCausalLM and AutoTokenizer?
