### ISSUE TITLE
Change Bind IP address

### ISSUE THREAD

**Issue by Jacoub** [ollama/ollama#2616]
Tried changing bind localhost:11434 to IP:11434 to server requests from Ollama WEBUI running on a separate docker host

**Comment by Jacoub** [comment]
unable to change bind localhost:11434 to IP:11434 to server requests from Ollama WEBUI running on a separate docker host

**Comment by jmorganca** [comment]
Hi there, if you're looking to expose Ollama on the network, make sure to use `OLLAMA_HOST=0.0.0.0:11434` or similar. Let me know if this doesn't help!

**Comment by cemox** [comment]
I did this, but it did not work for me. I added `OLLAMA_HOST=0.0.0.0:11434` to config file by using `systemctl edit ollama.service`. I still cannot access to it with the private ip (i.e. 192.168.1.111). 127.0.0.1 and 0.0.0.0 returns "ollama is running". What am I doing wrong?

**Comment by Huetarded** [comment]
I'm having the same issue here - It's working fine locally (localhost/127.0.0.1), but I cannot figure out how to bind it to 192.168.x.x IP address for accessing it within the local network.

**Comment by beegweeg** [comment]
I got access to the local network using
`sudo nano /etc/systemd/system/ollama.service`
add another environment line:
`Environment="OLLAMA_HOST=0.0.0.0:11434"`
```
sudo systemctl daemon-reload
sudo systemctl restart ollama.service
```
My ollama.service file
```
[Unit]
Description=Ollama Service
After=network-online.target

[Service]
ExecStart=/usr/local/bin/ollama serve
User=ollama
Group=ollama
Restart=always
RestartSec=3
Environment="OLLAMA_HOST=0.0.0.0:11434"
Environment="PATH=/usr/local/cuda-12.2/bin:......>

[Install]
WantedBy=default.target
```
