### ISSUE TITLE
Modelfile doesn't update (`keep_alive`?)

### ISSUE THREAD

**Issue by Red-exe-Engineer** [ollama/ollama#2617]
I've noticed that whenever I run `ollama create <name> -f </path/to/modelfile>` the Ollama server needs to restart or wait for `keep_alive` to quit before the changes fully apply.
`ollama show --modelfile <name>` shows as being updated, however when trying to interact it seems like it's running the old modelfile.

Example: giving a model with the template `{{ .Prompt }}`, if you update the modelfile and overwrite the template the old one will stay loaded despite `ollama show --template <model>` and `/show template` saying otherwise.

I've tried to ask around on Discord without success, so I'm creating an issue. Please note that I'm running Ollama on Termux and have only done some testing, however I'm sure something's wrong.

I'll be away for a few hours, hope you guys find the issue!

**Comment by jmorganca** [comment]
Hi, I'm so sorry about this. This is a [known issue](https://github.com/ollama/ollama/issues/2492) that will be fixed in the next release.
