### ISSUE TITLE
[Thankyou] Thanks for the ollama community

### ISSUE THREAD

**Issue by chuangtc** [ollama/ollama#2620]
In Taiwanese community, we have done a survey to see which are the top 5 local LLMs used by AI enthusiasts.
ollama is list as the top 5.
Here are the candidate list.
https://matilabs.ai/2024/02/07/run-llms-locally/
Thanks for the ollama community's hard work. We really love this project. I feel it's easy and straight forward. Developer friendly.
<img width="412" alt="Local-LLMs-2024-02-21 085848" src="https://github.com/ollama/ollama/assets/2288469/f8534a53-f4b3-439b-a2ba-2fa37e783bee">

**Comment by hoyyeva** [comment]
Hello @chuangtc, thank you so much for supporting Ollama! We're committed to working hard and making Ollama even better. Your feedback is valuable to us, so please keep it coming. Let's improve it together!
