### ISSUE TITLE
Request to allow installation to a different location

### ISSUE THREAD

**Issue by QJAG1024** [ollama/ollama#2621]
I noticed that ollama can only be installed on the **volume C**.
although there is enough space for me to install models, i prefer to install programs on volume D.
and for some people, they even haven't enough space to install models on volume C.
so i think they should have a chance to install ollama to a different location.
* I'm using translator so it may be hard to read this issue. sorry for that

**Comment by jachee** [comment]
I'd like to second this request for the exact same reason. :)

**Comment by QJAG1024** [comment]
> You can use https://github.com/ollama/ollama/blob/main/docs/faq.md#where-are-models-stored to change where the models are stored and point it to another volume.

thanks
