### ISSUE TITLE
JSON without newline grammar

### ISSUE THREAD

**Issue by Xe** [ollama/ollama#2623]
I'd like to have a variant of the JSON grammar that forbids newlines from the output. Sometimes when you activate JSON grammar, the model will spit out an endless series of newlines. It'd be nice to have a version of the JSON grammar that forbids newlines (and probably whitespace outside of strings) to prevent this from happening.

**Comment by josharian** [comment]
hello, @Xe! i just hit this too. possible dups: https://github.com/ollama/ollama/issues/2351 and https://github.com/ollama/ollama/issues/2577. I think the suggestion in https://github.com/ollama/ollama/issues/2577 is probably the cleanest fix:

> [force the] message to terminate immediately after the closing } of the top-level JSON object

**Comment by josharian** [comment]
It looks like this might be as simple as removing ` ws` from the end of:

```
object ::=
  "{" ws (
            string ":" ws value
    ("," ws string ":" ws value)*
  )? "}" ws
```

in jsonGrammar. Would need to do some testing. It's interesting that upstream llama.cpp has a json_arr.gbnf that restricts whitespace at the end of a root array, but doesn't have the same for objects.

**Comment by josharian** [comment]
I'd prefer to remove `ws` from the grammar entirely. Why waste cycles on pretty-printing tokens? That can be using encoding/json afterwards, if we care.

Another, perhaps better, approach to this is to expose a "gbnf grammar" parameter, so folks can mess around with this entirely as they desire.

**Comment by Xe** [comment]
I managed to solve it in a somewhat roundabout way. I made a function called `Hallucinate` that returns a new value T with custom "validation" logic. I think https://github.com/Xe/x/commit/590a15a0c3658abf13db39bd3c52021a7ec6ba82 will fix it for my needs.

I'll PR removing the whitespace from the grammar entirely.

**Comment by josharian** [comment]
Filed #2895 for BYO GBNF support.

**Comment by josharian** [comment]
@Xe do you still plan to send a PR fixing up the JSON grammar?

While working on other things, I noticed that the JSON grammar can generate invalid json: it doesn't forbid unescaped \t, \n, or \r in its definition of string. Something like this would help:

```diff
-    [^"\\] |
+    [^"\\\n\t\r] |
```

Maybe you could add this to your JSON cleanup PR? (And if not, I can cobble one together.)

**Comment by ParthSareen** [comment]
Hey! with the rollout of #7900 we're supporting structured outputs - hope that is helpful!
