### ISSUE TITLE
Support for Tinyllava

### ISSUE THREAD

**Issue by oliverbob** [ollama/ollama#2624]
In addition to support for moondream #2259 which is lightning faster than llava, I believe there are some good guys there that can successfully make a GGUF version of Tinyllava which is faster than light. Tried it on safetensors to work really well. its been trained on the llava dataset, just like moondream.

https://huggingface.co/bczhou/tiny-llava-v1-hf
https://huggingface.co/YouLiXiya/tinyllava-v1.0-1.1b-hf

**Comment by jmorganca** [comment]
https://ollama.com/library/tinyllama 🎊

**Comment by AIWintermuteAI** [comment]
He was referring to Tinyllava... Not TinyLLaMa.

**Comment by oliverbob** [comment]
What makes it completed when I can't yet find tinyllava?

**Comment by MLTQ** [comment]
Also requesting TinyLlava

**Comment by jaypaulb** [comment]
@jmorganca I think you misread this post.  The op is seeking support for a Tiny **LLaVa** model with vision capability rather than TinyLlama with only text support.
