### ISSUE TITLE
Error: listen tcp 127.0.0.1:11434: bind: 

### ISSUE THREAD

**Issue by szymonk92** [ollama/ollama#2627]
Windows 10, 
I cannot start Ollama, 
```
$ ollama serve
Error: listen tcp 127.0.0.1:11434: bind: An attempt was made to access a socket in a way forbidden by its access permissions.
```

from **app.log**
```
time=2024-02-21T10:04:42.504+01:00 level=WARN source=server.go:109 msg="server crash 332 - exit code 1 - respawning"
time=2024-02-21T10:04:43.018+01:00 level=ERROR source=server.go:112 msg="failed to restart server exec: already started"
time=2024-02-21T10:07:58.072+01:00 level=DEBUG source=logging_windows.go:12 msg="viewing logs with start C:\\Users\\user\\AppData\\Local\\Ollama"
time=2024-02-21T10:10:15.024+01:00 level=WARN source=server.go:109 msg="server crash 333 - exit code 1 - respawning"
time=2024-02-21T10:10:15.526+01:00 level=ERROR source=server.go:112 msg="failed to restart server exec: already started"
time=2024-02-21T10:11:20.094+01:00 level=DEBUG source=eventloop.go:151 msg="unmanaged app message, lParm: 0x204"
time=2024-02-21T10:11:20.792+01:00 level=DEBUG source=lifecycle.go:30 msg="QUIT called"
time=2024-02-21T10:11:20.842+01:00 level=INFO source=lifecycle.go:78 msg="Waiting for ollama server to shutdown..."
time=2024-02-21T10:15:48.537+01:00 level=DEBUG source=server.go:104 msg="server shutdown with exit code 1"
time=2024-02-21T10:15:48.537+01:00 level=INFO source=lifecycle.go:82 msg="Ollama app exiting"
time=2024-02-21T10:37:42.782+01:00 level=INFO source=logging.go:45 msg="ollama app started"
time=2024-02-21T10:37:42.863+01:00 level=DEBUG source=lifecycle.go:26 msg="starting callback loop"
time=2024-02-21T10:37:42.863+01:00 level=DEBUG source=store.go:61 msg="loaded existing store C:\\Users\\user\\AppData\\Local\\Ollama\\config.json - ID: 6fbe69d4-62a6-4ad8-9768-da087897ebe2"
time=2024-02-21T10:37:42.864+01:00 level=DEBUG source=lifecycle.go:57 msg="Not first time, skipping first run notification"
time=2024-02-21T10:37:42.865+01:00 level=DEBUG source=server.go:130 msg="heartbeat from server: Head \"http://127.0.0.1:11434/\": dial tcp 127.0.0.1:11434: connectex: No connection could be made because the target machine actively refused it."
time=2024-02-21T10:37:42.865+01:00 level=INFO source=server.go:131 msg="unable to connect to server"
time=2024-02-21T10:37:42.870+01:00 level=INFO source=server.go:87 msg="started ollama server with pid 40576"
time=2024-02-21T10:37:42.870+01:00 level=INFO source=server.go:89 msg="ollama server logs C:\\Users\\user\\AppData\\Local\\Ollama\\server.log"
time=2024-02-21T10:37:42.870+01:00 level=DEBUG source=eventloop.go:24 msg="starting event handling loop"
time=2024-02-21T10:37:42.941+01:00 level=WARN source=server.go:109 msg="server crash 1 - exit code 1 - respawning"
time=2024-02-21T10:37:43.445+01:00 level=ERROR source=server.go:112 msg="failed to restart server exec: already started"
time=2024-02-21T10:37:44.461+01:00 level=WARN source=server.go:109 msg="server crash 2 - exit code 1 - respawning"
time=2024-02-21T10:37:44.636+01:00 level=WARN source=tray.go:365 msg="failed to bring menu to foreground: The operation completed successfully."
time=2024-02-21T10:37:44.971+01:00 level=ERROR source=server.go:112 msg="failed to restart server exec: already started"
time=2024-02-21T10:37:45.525+01:00 level=DEBUG source=logging_windows.go:12 msg="viewing logs with start C:\\Users\\user\\AppData\\Local\\Ollama"
time=2024-02-21T10:37:45.882+01:00 level=DEBUG source=updater.go:87 msg="checking for available update at https://ollama.com/api/update?arch=amd64&nonce=RENbdDvJrUl9L0FRExH2xw&os=windows&ts=1708508265&version=0.1.25 with headers map[Authorization:[AAAAC3NzaC1lZDI1NTE5AAAAIAhd0mgYr2Vcgo+erwm80qQblGZaB2w4wE8iKVd5CEFx:dwydcT5JCB5WxCq5C7VD6Six77HhMVstFn6HMCBxU54YhtiEEYsOcHWMwC4EDADcM5NZD4oTgKf3/naoGa50CA==] User-Agent:[ollama/0.1.25 (amd64 windows) Go/go1.22.0]]"
time=2024-02-21T10:37:46.246+01:00 level=DEBUG source=updater.go:96 msg="check update response 204 (current version is up to date)"
time=2024-02-21T10:37:46.982+01:00 level=WARN source=server.go:109 msg="server crash 3 - exit code 1 - respawning"
time=2024-02-21T10:37:47.493+01:00 level=ERROR source=server.go:112 msg="failed to restart server exec: already started"
time=2024-02-21T10:37:50.502+01:00 level=WARN source=server.go:109 msg="server crash 4 - exit code 1 - respawning"
time=2024-02-21T10:37:51.016+01:00 level=ERROR source=server.go:112 msg="failed to restart server exec: already started"
time=2024-02-21T10:37:55.030+01:00 level=WARN source=server.go:109 msg="server crash 5 - exit code 1 - respawning"
time=2024-02-21T10:37:55.543+01:00 level=ERROR source=server.go:112 msg="failed to restart server exec: already started"
```

**server.log**

`Error: listen tcp 127.0.0.1:11434: bind: An attempt was made to access a socket in a way forbidden by its access permissions.`

What I tried:
[Ollama issue 2560](https://github.com/ollama/ollama/issues/2560#issuecomment-1950690705), but seems that there is no proxy at that port

**Comment by xiaofeiyun123** [comment]
I found the same issue with above. Is there a solution?

**Comment by Daviduche03** [comment]
same error. any fix please?

**Comment by hryyan** [comment]
Fixed by adding Environment="OLLAMA_HOST=0.0.0.0" in /etc/systemd/system/ollama.service

```
[Unit]
Description=Ollama Service
After=network-online.target

[Service]
ExecStart=/usr/local/bin/ollama serve
User=ollama
Group=ollama
Restart=always
RestartSec=3
Environment="PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin"
Environment="OLLAMA_HOST=0.0.0.0"

[Install]
WantedBy=default.target
``` 

then reload and restart

```shell
systemctl daemon-reload
systemctl restart ollama
```

**Comment by yiyuandao** [comment]
@Daviduche03 @szymonk92 

I got the same issue.

[the problem is down to Docker and Hyper-V reserving a shed load of ports](https://pomeroy.me/2020/09/solved-windows-10-forbidden-port-bind/)

try the following, you will find the reserved the port 111434
```
netsh interface ipv4 show excludedportrange protocol=tcp
```

the simple way is run the following as admin.
```
net stop winnat
net start winnat
```

about the detail, please see the workaround at StackOverflow：[Cannot bind to some ports due to permission denied](https://stackoverflow.com/questions/48478869/cannot-bind-to-some-ports-due-to-permission-denied/62061654#62061654)

**Comment by dhiltgen** [comment]
@szymonk92 have any of the suggestions above resolved your problem?  We've designed Ollama to not require admin, but if some other app is using the port or has reserved the port that could explain the problem.  Another workaround is to use a different port number by changing the OLLAMA_HOST environment variable.  If you set that in your account and restart the App, then both the server and clients will use that new port number to connect.

See https://github.com/ollama/ollama/blob/main/docs/faq.md for more information.

**Comment by Pathsis** [comment]
> 通过在 /etc/systemd/system/ollama.service 中添加 Environment="OLLAMA_HOST=0.0.0.0" 来修复
> 
> ```
> [Unit]
> Description=Ollama Service
> After=network-online.target
> 
> [Service]
> ExecStart=/usr/local/bin/ollama serve
> User=ollama
> Group=ollama
> Restart=always
> RestartSec=3
> Environment="PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin"
> Environment="OLLAMA_HOST=0.0.0.0"
> 
> [Install]
> WantedBy=default.target
> ```
> 
> 然后重新加载并重新启动
> 
> ```shell
> systemctl daemon-reload
> systemctl restart ollama
> ```

Hi, I set it up like this on ubuntu, but running `ollama serve`, I still get the error in this issue.

> Fixed by adding Environment="OLLAMA_HOST=0.0.0.0" in /etc/systemd/system/ollama.service
> 
> ```
> [Unit]
> Description=Ollama Service
> After=network-online.target
> 
> [Service]
> ExecStart=/usr/local/bin/ollama serve
> User=ollama
> Group=ollama
> Restart=always
> RestartSec=3
> Environment="PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin"
> Environment="OLLAMA_HOST=0.0.0.0"
> 
> [Install]
> WantedBy=default.target
> ```
> 
> then reload and restart
> 
> ```shell
> systemctl daemon-reload
> systemctl restart ollama
> ```

Hi, I set it up like this on ubuntu, but running `ollama serve`, I still get the error in this issue.

**Comment by dhiltgen** [comment]
@Pathsis can you share your server log?

**Comment by abmachinthosh** [comment]
In windows, I created a new Environemnt variable:
OLLAMA_HOST = 127.0.0.1:11435. 
Works for me.
Refference: https://github.com/ollama/ollama/issues/2194

**Comment by phicha20224** [comment]
hello,
please kindly help .
i try fix using add OLLAMA_HOST  in environment. but now 11435 is also cannot be used. 
Error: listen tcp 127.0.0.1:11435: bind: An attempt was made to access a socket in a way forbidden by its access permissions.

is there fix for this error ? since my openweb ui is from docker and its hard to setup to host. need setup portforwarding

**Comment by tzzed** [comment]
Hello, I fixed the connection issue by using the `ollama.WithServerURL` option to correctly point to the right container
```go 
llm, err := ollama.New(ollama.WithModel("llama3.1"), ollama.WithServerURL("http://ollama:11434"))
```

**Comment by rzeydelis** [comment]
> Fixed by adding Environment="OLLAMA_HOST=0.0.0.0" in /etc/systemd/system/ollama.service
> 
> ```
> [Unit]
> Description=Ollama Service
> After=network-online.target
> 
> [Service]
> ExecStart=/usr/local/bin/ollama serve
> User=ollama
> Group=ollama
> Restart=always
> RestartSec=3
> Environment="PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin"
> Environment="OLLAMA_HOST=0.0.0.0"
> 
> [Install]
> WantedBy=default.target
> ```
> 
> then reload and restart
> 
> ```shell
> systemctl daemon-reload
> systemctl restart ollama
> ```

Does this open up your ollama app to all public ips?

**Comment by Sadwy** [comment]
I think it does. I did not verify it. It just works.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ollama/ollama"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年9月28日(星期六) 晚上9:27
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ollama/ollama] Error: listen tcp 127.0.0.1:11434: bind:  (Issue #2627)





  
Fixed by adding Environment="OLLAMA_HOST=0.0.0.0" in /etc/systemd/system/ollama.service
 [Unit] Description=Ollama Service After=network-online.target [Service] ExecStart=/usr/local/bin/ollama serve User=ollama Group=ollama Restart=always RestartSec=3 Environment="PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin" Environment="OLLAMA_HOST=0.0.0.0" [Install] WantedBy=default.target  
then reload and restart
 systemctl daemon-reload systemctl restart ollama
  
Does this open up your ollama app to all public ips?

**Comment by Sw0rd-fish** [comment]
use the command find a port which not in used:
netsh interface ipv4 show excludedportrange protocol=tcp
then created a new Environemnt variable:
OLLAMA_HOST = 127.0.0.1:not_used_port

**Comment by higkoo** [comment]
I got this Error when I want to change IP 0.0.0.0 to Bind，Then su root do:
`netsh interface portproxy delete v4tov4 listenport=11434 listenaddress=0.0.0.0`
Finally, Start success.

**Comment by takimdigital** [comment]
## Solution for `Error: listen tcp 127.0.0.1:11434: bind: An attempt was made to access a socket in a way forbidden by its access permissions`

If you're encountering this error while trying to use Ollama, you can fix it by restarting the Host Network Service (HNS).

### Steps to Resolve:

1. **Open Command Prompt as Administrator**
   - Press `Win + S`, type `cmd`, then right-click **Command Prompt** and select **Run as administrator**.

2. **Stop the HNS Service**
   ```sh
   net stop hns
   ```
   - If prompted, type `Y` and press `Enter`.

3. **Start the HNS Service**
   ```sh
   net start hns
   ```

4. **Retry the Ollama command**
   ```sh
   ollama list
   ```

This should resolve the issue and allow you to use Ollama without any socket binding errors.

### Troubleshooting Tips

- Ensure you have the latest version of Ollama installed.
- If the problem persists, check your firewall and antivirus settings.
- Restart your computer as a last resort if the above steps don't work.

**Comment by joaotextor** [comment]
> In windows, I created a new Environemnt variable: OLLAMA_HOST = 127.0.0.1:11435. Works for me. Refference: [#2194](https://github.com/ollama/ollama/issues/2194)

Can confirm it worked for me.

**Comment by saeedkoshki-commits** [comment]
Hello, after ollama list it gives the following error.


Error: Head "tcp://host.docker.internal:11434/": unsupported protocol scheme "tcp"

**Comment by orhamra** [comment]
Run this:
netsh int ipv4 show excludedportrange protocol=tcp

Your Windows or HyperV is using that port.

These commands may help:
net stop winnat
net start winnat
