### ISSUE TITLE
questions for mistral

### ISSUE THREAD

**Issue by VadimBoev** [ollama/ollama#2635]
Hi.  
How do I get him to respond in only one language?  
And how to remove the censorious language from him so that he can express himself obscenely?

**Comment by seanmavley** [comment]
> How do I get him to respond in only one language?
Your prompt should tell 'him' that

> And how to remove the censorious language from him so that he can express himself obscenely?

Which mistral model are you using? The last I checked, the mistral default models aren't censored

**Comment by VadimBoev** [comment]
> > How do I get him to respond in only one language?
> 
> Your prompt should tell 'him' that
> 
> > And how to remove the censorious language from him so that he can express himself obscenely?
> 
> Which mistral model are you using? The last I checked, the mistral default models aren't censored

I used 'ollama run mistral', is this the latest version?

**Comment by seanmavley** [comment]
> I used 'ollama run mistral', is this the latest version?

Yes, that'll be the latest version
