### ISSUE TITLE
on windows skipping models

### ISSUE THREAD

**Issue by stream74** [ollama/ollama#2638]
Sorry for bad english 
i set environnement variable in windows to models folders 
if i pull new models it go to the folder i set
but i have already a lot of models but ollama can't see it when i ask him with "ollama list"
th server log indicate 
[GIN] 2024/02/21 - 15:51:59 | 200 |       6.082ms |       127.0.0.1 | GET      "/api/tags"
[GIN] 2024/02/21 - 15:56:04 | 200 |            0s |       127.0.0.1 | HEAD     "/"
time=2024-02-21T15:56:04.036+01:00 level=INFO source=routes.go:809 msg="skipping file: hub/chirag/chloe:latest"
time=2024-02-21T15:56:04.036+01:00 level=INFO source=routes.go:809 msg="skipping file: hub/chmurli/sarah-lovely-caring-girlfriend:latest"
time=2024-02-21T15:56:04.036+01:00 level=INFO source=routes.go:809 msg="skipping file: hub/languages/french:latest"
time=2024-02-21T15:56:04.037+01:00 level=INFO source=routes.go:809 msg="skipping file: registry.ollama.ai/fixt/home-3b-v2:q8_0"
time=2024-02-21T15:56:04.037+01:00 level=INFO source=routes.go:809 msg="skipping file: registry.ollama.ai/library/assistante-grossesse:latest"
time=2024-02-21T15:56:04.037+01:00 level=INFO source=routes.go:809 msg="skipping file: registry.ollama.ai/library/assistante-photographe:latest"
time=2024-02-21T15:56:04.038+01:00 level=INFO source=routes.go:809 msg="skipping file: registry.ollama.ai/library/chloe-french:latest"
time=2024-02-21T15:56:04.038+01:00 level=INFO source=routes.go:809 msg="skipping file: registry.ollama.ai/library/dolphin-mistral:latest"
time=2024-02-21T15:56:04.038+01:00 level=INFO source=routes.go:809 msg="skipping file: registry.ollama.ai/library/french-home:latest"
time=2024-02-21T15:56:04.038+01:00 level=INFO source=routes.go:809 msg="skipping file: registry.ollama.ai/library/jarvis-home-3b:latest"
time=2024-02-21T15:56:04.039+01:00 level=INFO source=routes.go:809 msg="skipping file: registry.ollama.ai/library/mistral:latest"
time=2024-02-21T15:56:04.039+01:00 level=INFO source=routes.go:809 msg="skipping file: registry.ollama.ai/library/moly:latest"
time=2024-02-21T15:56:04.039+01:00 level=INFO source=routes.go:809 msg="skipping file: registry.ollama.ai/library/ollamacreate:latest"
time=2024-02-21T15:56:04.040+01:00 level=INFO source=routes.go:809 msg="skipping file: registry.ollama.ai/library/openhermes2.5-mistral:latest"
time=2024-02-21T15:56:04.040+01:00 level=INFO source=routes.go:809 msg="skipping file: registry.ollama.ai/library/samantha-mistral:7b-v1.2-text-q6_K"
time=2024-02-21T15:56:04.040+01:00 level=INFO source=routes.go:809 msg="skipping file: registry.ollama.ai/library/samantha-mistral:latest"
time=2024-02-21T15:56:04.040+01:00 level=INFO source=routes.go:809 msg="skipping file: registry.ollama.ai/library/wizard-vicuna-uncensored:13b"

**Comment by jamesliu668** [comment]
I got the same problem. Basically, I am copying the models folder from my Windows to my Mac. Then running the ollama server on mac, and I got the same "skipping file" message in log file.

**Comment by jamesliu668** [comment]
> I got the same problem. Basically, I am copying the models folder from my Windows to my Mac. Then running the ollama server on mac, and I got the same "skipping file" message in log file.

I found the problem. As I downloaded models on Windows and then copy all models to Mac. Actually, the model manifests contains all the model required files in blobs. However, on Windows, all blobs file named as:

`sha256-fad2a06e4cc705c2fa8bec5477ddb00dc0c859ac184c34dcc5586663774161ca`

But the blob file on Mac named as:

`sha256:fad2a06e4cc705c2fa8bec5477ddb00dc0c859ac184c34dcc5586663774161ca`

So, check your blob file name on the platform which you are using, rename it as above mentioned will solve the problem.

thx

**Comment by stream74** [comment]
many thanks i tink it was the good answer
in linux 
sha256°12cd8b508059ed69fbd29b1871ecd4a37cfc35a7e0a461dd1c4e8573c3cd0170
in windows
sha256-12cd8b508059ed69fbd29b1871ecd4a37cfc35a7e0a461dd1c4e8573c3cd0170

**Comment by hoyyeva** [comment]
Hey @stream74, are you still experiencing this issue? Looks like you might've figured it! And thank you so much @jamesliu668 for stepping up – you're awesome! Gonna close this issue for now since it seems sorted, but if anything pops up again feel free to reopen the issue!
