### ISSUE TITLE
Linux installer reports that ollama is listening on 0.0.0.0. It isn't.

### ISSUE THREAD

**Issue by easp** [ollama/ollama#2640]
After successfully installing the binary, the installer script reports:
```The Ollama API is now available at 0.0.0.0:11434.```

This is incorrect. It's listening on localhost.

**Comment by seanmavley** [comment]
@easp How did you install your Ollama? Which system are you on too?

I just confirmed mine, it's running on 127.0.0.1

```tcp        0      0 127.0.0.1:11434         0.0.0.0:*               LISTEN      211/ollama     ```

Ignore the "foreign address" column

**Comment by easp** [comment]
@seanmalvy Thanks for taking a look. You are right, I was in a rush and didn't look at the correct column in the netstat output.

So the issue is just that the installer reports the wrong information. Updating issue to reflect that.
