### ISSUE TITLE
Windows install with NVIDIA GPU

### ISSUE THREAD

**Issue by bibhas2** [ollama/ollama#2644]
The install guide for Windows should make it clear if CUDA Toolkit should be installed. And what versions of CUDA are supported? It makes sense to install CUDA Toolkit first. But wanted to be sure.

**Comment by mchiang0610** [comment]
Hey @bibhas2. You do not need CUDA toolkit to be installed. Ollama on Windows will take care of it. You do need NVIDIA drivers first.

**Comment by mchiang0610** [comment]
Sorry that we didn't make this clearer. Closing this for now.
