### ISSUE TITLE
Biomistral support planned?

### ISSUE THREAD

**Issue by DimIsaev** [ollama/ollama#2645]
Biomistral support planned?

**Comment by wrapss** [comment]
> Biomistral support planned?

https://ollama.com/f0rodo/bio-mistral-dare

**Comment by mchiang0610** [comment]
Thank you for sharing the user uploaded model! Want to bring it up that Ollama allows you to bring this model, and make it your own: 

https://github.com/ollama/ollama/blob/main/docs/import.md

Sorry that this isn't more clear.

**Comment by DimIsaev** [comment]
thanx 
I go research  this  opportunity
