### ISSUE TITLE
Issue with new model Gemma

### ISSUE THREAD

**Issue by jaifar530** [ollama/ollama#2649]
After pulling the new Gemma model i got this issue, note that the issue is only with two grmma models, other works fine 

![Screenshot_20240221_234359_Chrome.jpg](https://github.com/ollama/ollama/assets/31308766/461863b3-c59c-42dc-b826-3ea093bebb4f)

**Comment by aniketmaurya** [comment]
You might need to upgrade the Ollama to latest v0.1.26 version

**Comment by jmorganca** [comment]
Sorry you hit an error - only 0.1.26 and later supports Gemma. Sorry the error isn't better in this case, we'll work on that!
