### ISSUE TITLE
Make gemma:7b the default gemma model

### ISSUE THREAD

**Issue by Jbollenbacher** [ollama/ollama#2660]
After #2650 is resolved, can we make the default gemma model the 7b model?

**Comment by mxyng** [comment]
The issues with 7b has been fixed and is now the default if you pull `gemma` from the library.

**Comment by dh12306** [comment]
> @Jbollenbacher Why? 2B works better than the 7B. So it makes sense for 2B to be default.

2b works better ？I am doubtful

**Comment by adminazhar** [comment]
@dh12306 Not sure about the current state, but when it was launched 7b was crappy and producing mostly gibberish content. You can test it out and compare the current state.
