### ISSUE TITLE
gemma crashes ollama

### ISSUE THREAD

**Issue by donuts-are-good** [ollama/ollama#2663]
![image](https://github.com/ollama/ollama/assets/96031819/58400f74-53e9-4d90-aea6-be291919a6f3)

**Comment by bmtriet** [comment]
I got the same error on windows 10 with gemma 0.5 & 7b

**Comment by wirtsi** [comment]
This also happens with the GGUF models (eg https://huggingface.co/cohesionet/GritLM-7B_gguf/tree/main)

**Comment by jaifar530** [comment]
just, download the latest version again and run it

**Comment by BruceMacD** [comment]
Thanks to everyone for the reports and updates. It looks like this should be solved by updating to the latest version. Let us know if that isn't the case.

**Comment by cwegener** [comment]
A bit more detail would really be helpful for other people who have encountered the same issue.

"latest version" is not a good term to use.

**Comment by cwegener** [comment]
In order to run a gemma model, the `ollama` version must be at least `0.1.27`

**Comment by donuts-are-good** [comment]
works, thanks
