### ISSUE TITLE
Ollama windows installer fails due to virus/trojan detection from Windows Defender!! Help

### ISSUE THREAD

**Issue by EmmaWebGH** [ollama/ollama#2664]
As title says
Downloaded the windows installer literally a few mins ago.
Clicked install... window pops up, progress bar counts up... then womp! It Disappears. 
Little notification in the corner of windows, I ignore.

Right, where did it go? Hmm. Weird. Can't see Ollama anywhere. Maybe it didn't install?
Try again.
Progress bar counts up... womp. Notification in corner from Windows.
Click it.
Windows has detected a threat, a sever trojan???

Now doing a full scan. But I already ran the installer twice now, with no Ollama icon appearing in the sys tray as shown in Matt William's video:
https://www.youtube.com/watch?v=EMC5QQN_vdU

I can't copy and paste from WIndows Defender but here is a screenshot saying the file affected is indeed Ollama, and severe threat.

![ApplicationFrameHost_Fg3vmywLb3](https://github.com/ollama/ollama/assets/123797054/88f513ae-c6df-4858-896c-ed080a55dd49)

What's up with this, please?

Installer was downloaded from THIS github! Not a random location. Here!

**Comment by EmmaWebGH** [comment]
Ah, of course I searched for "trojan" not "virus". I see it's already an issue. Apologies.
https://github.com/ollama/ollama/issues/2519

**Comment by jmorganca** [comment]
No worries – I'm sorry this happened. We're working on fixing it with Microsoft. I'll close this for #2519 and stay tuned
