### ISSUE TITLE
Microsoft Virus alert

### ISSUE THREAD

**Issue by nagkumar** [ollama/ollama#2665]
<img width="593" alt="image" src="https://github.com/ollama/ollama/assets/332234/53eb03aa-b3f8-48e2-8dff-62ce5a1b413b">

what is wrong with this message...any thing we need to worry about installing on windows?

**Comment by Lunarisnia** [comment]
Related to #2519

**Comment by jmorganca** [comment]
Going to close this for https://github.com/ollama/ollama/issues/2519

I'm sorry this happened, and no – this is a false positive and is unfortunately common with applications built in Go. Working on fixing it with Microsoft Security Intelligence
