### ISSUE TITLE
Trojan:Script/Wacatac.B!ml After Ollama Update Ollama

### ISSUE THREAD

**Issue by gargakk** [ollama/ollama#2667]
Today after Ollama automatic update on a windows machine  system find Trojan:Script/Wacatac.B!ml.

Why??

![Screenshot 2024-02-22 081700](https://github.com/ollama/ollama/assets/11261036/2fe0cad3-c26d-40aa-b979-7a37281d5570)

**Comment by jmorganca** [comment]
I'm sorry you hit this – it's a false positive detection from Windows Defender. Unfortunately Go programs have a history of causing false positives with Windows Defender. We're working with Microsoft Security Intelligence to fix this. For now I'll merge this with https://github.com/ollama/ollama/issues/2519

**Comment by jmorganca** [comment]
In the meantime, please do update your Windows Defender definitions and the latest version of Ollama should install without any warnings. You can see more info here: https://github.com/ollama/ollama/issues/2519#issuecomment-1957880099
