### ISSUE TITLE
Error: Unable to load dynamic library: Unable to load dynamic server library:

### ISSUE THREAD

**Issue by 123124-1** [ollama/ollama#2668]
time=2024-02-22T15:43:18.086+08:00 level=INFO source=images.go:710 msg="total blobs: 11"
time=2024-02-22T15:43:18.117+08:00 level=INFO source=images.go:717 msg="total unused blobs removed: 0"
time=2024-02-22T15:43:18.120+08:00 level=INFO source=routes.go:1019 msg="Listening on 127.0.0.1:11434 (version 0.1.26)"
time=2024-02-22T15:43:18.120+08:00 level=INFO source=payload_common.go:107 msg="Extracting dynamic libraries..."
time=2024-02-22T15:43:18.274+08:00 level=INFO source=payload_common.go:146 msg="Dynamic LLM libraries [cpu_avx cpu_avx2 cpu cuda_v11.3]"
[GIN] 2024/02/22 - 15:43:18 | 200 |            0s |       127.0.0.1 | HEAD     "/"
[GIN] 2024/02/22 - 15:43:18 | 200 |      2.1738ms |       127.0.0.1 | POST     "/api/show"
[GIN] 2024/02/22 - 15:43:18 | 200 |      1.6371ms |       127.0.0.1 | POST     "/api/show"
time=2024-02-22T15:43:18.996+08:00 level=INFO source=gpu.go:94 msg="Detecting GPU type"
time=2024-02-22T15:43:18.996+08:00 level=INFO source=gpu.go:265 msg="Searching for GPU management library nvml.dll"
time=2024-02-22T15:43:19.003+08:00 level=INFO source=gpu.go:311 msg="Discovered GPU libraries: [c:\\Windows\\System32\\nvml.dll C:\\Windows\\system32\\nvml.dll]"
time=2024-02-22T15:43:19.019+08:00 level=INFO source=gpu.go:99 msg="Nvidia GPU detected"
time=2024-02-22T15:43:19.019+08:00 level=INFO source=cpu_common.go:11 msg="CPU has AVX2"
time=2024-02-22T15:43:19.034+08:00 level=INFO source=gpu.go:146 msg="CUDA Compute Capability detected: 6.1"
time=2024-02-22T15:43:19.034+08:00 level=INFO source=cpu_common.go:11 msg="CPU has AVX2"
time=2024-02-22T15:43:19.034+08:00 level=INFO source=gpu.go:146 msg="CUDA Compute Capability detected: 6.1"
time=2024-02-22T15:43:19.034+08:00 level=INFO source=cpu_common.go:11 msg="CPU has AVX2"
time=2024-02-22T15:43:19.034+08:00 level=INFO source=dyn_ext_server.go:385 msg="Updating PATH to C:\\Users\\葫芦娃\\AppData\\Local\\Temp\\ollama3325263888\\cuda_v11.3;C:\\Windows\\system32;C:\\Windows;C:\\Windows\\System32\\Wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\;C:\\Windows\\System32\\OpenSSH\\;C:\\Program Files (x86)\\NVIDIA Corporation\\PhysX\\Common;C:\\Program Files\\NVIDIA Corporation\\NVIDIA NvDLISR;C:\\Program Files (x86)\\NetSarang\\Xshell 7\\;C:\\Program Files (x86)\\NetSarang\\Xftp 7\\;C:\\Program Files\\dotnet\\;C:\\Program Files\\Git\\cmd;C:\\Users\\葫芦娃\\AppData\\Local\\Microsoft\\WindowsApps;C:\\Program Files\\Bandizip\\;F:\\Microsoft VS Code\\bin;C:\\ffmpeg-2024-02-15-git-a2cfd6062c-full_build\\bin;;C:\\Users\\葫芦娃\\AppData\\Local\\Programs\\Ollama"
time=2024-02-22T15:43:19.035+08:00 level=WARN source=llm.go:162 msg="Failed to load dynamic library C:\\Users\\葫芦娃\\AppData\\Local\\Temp\\ollama3325263888\\cuda_v11.3\\ext_server.dll  Unable to load dynamic library: Unable to load dynamic server library: \xd5Ҳ\xbb\xb5\xbdָ\xb6\xa8\xb5\xc4ģ\xbf顣\r\n"
time=2024-02-22T15:43:19.035+08:00 level=INFO source=dyn_ext_server.go:385 msg="Updating PATH to C:\\Users\\葫芦娃\\AppData\\Local\\Temp\\ollama3325263888\\cpu_avx2;C:\\Windows\\system32;C:\\Windows;C:\\Windows\\System32\\Wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\;C:\\Windows\\System32\\OpenSSH\\;C:\\Program Files (x86)\\NVIDIA Corporation\\PhysX\\Common;C:\\Program Files\\NVIDIA Corporation\\NVIDIA NvDLISR;C:\\Program Files (x86)\\NetSarang\\Xshell 7\\;C:\\Program Files (x86)\\NetSarang\\Xftp 7\\;C:\\Program Files\\dotnet\\;C:\\Program Files\\Git\\cmd;C:\\Users\\葫芦娃\\AppData\\Local\\Microsoft\\WindowsApps;C:\\Program Files\\Bandizip\\;F:\\Microsoft VS Code\\bin;C:\\ffmpeg-2024-02-15-git-a2cfd6062c-full_build\\bin;;C:\\Users\\葫芦娃\\AppData\\Local\\Programs\\Ollama;C:\\Users\\葫芦娃\\AppData\\Local\\Programs\\Ollama"
time=2024-02-22T15:43:19.035+08:00 level=WARN source=llm.go:162 msg="Failed to load dynamic library C:\\Users\\葫芦娃\\AppData\\Local\\Temp\\ollama3325263888\\cpu_avx2\\ext_server.dll  Unable to load dynamic library: Unable to load dynamic server library: \xd5Ҳ\xbb\xb5\xbdָ\xb6\xa8\xb5\xc4ģ\xbf顣\r\n"
[GIN] 2024/02/22 - 15:43:19 | 500 |    671.9922ms |       127.0.0.1 | POST     "/api/chat"

When running the error message, the hardware used includes GPU: 1070TI CPU: i7 8700K RMA: 32G

**Comment by luoluoter** [comment]
盲猜 中文路径的问题，但不是很清楚你这里的中文怎么去掉，可以试试 创建一个新的英文名称 用户 来重新安装（很久没用windows开发了）

**Comment by Elliotoplit** [comment]
确实是中文路径问题，我修改了就可以运行了，这里有个修改教程https://zhuanlan.zhihu.com/p/440768641

**Comment by Tosuke-sama** [comment]
实际上还有一个办法，也就是在控制面版的区域中将beta版使用全球utf8语言支持打开。这样不用改系统用户名，不过有些其他程序也许会有问题

**Comment by dhiltgen** [comment]
This should be resolved in the latest version.  Please give 0.1.33 a try and let us know if you still have problems.

https://github.com/ollama/ollama/releases
