### ISSUE TITLE
Understanding Modelfile template with respect to conversational history

### ISSUE THREAD

**Issue by nikhil0360** [ollama/ollama#2678]
[proposed Label] question

Hello, I want to understand how does the conversational history is feed back into the template from the model file. 

for example, for llama2:chat
```
TEMPLATE """[INST] <<SYS>>{{ .System }}<</SYS>>

{{ .Prompt }} [/INST]
"""
```

I am able to do conversational question answering on the terminal, but I am not sure how does the template take care of the history. 

On the contrary, how do I disable such behaviour? I want to run a fine-tune model which just answer to user based on the current question. I don't want it to get influenced by history/previous question. I tried using `/set nohistory` but it doesn't seem to work (for llama2)

Please help.

I tried looking in docs, online forms, github issues. Was unable to find any solutions.

**Comment by pdevine** [comment]
Hey @nikhil0360 There's no way to disable this in the repl, although if you want to clear out the current context you can just use `/load <model>`. If you load the same model again it will remain in memory (i.e. it won't be "re-loaded") and it will make the model forget anything from before.

**Comment by nikhil0360** [comment]
@pdevine Thanks for the answer. 

Just for more details for anyone who comes across here, I want to share that this behaviour (influenced by history/previous question.) is not followed in the API call, which is what I finally used for my work.
