### ISSUE TITLE
Server misbehaving pulling models

### ISSUE THREAD

**Issue by bradstallion** [ollama/ollama#2680]
Hi,
I've just updated the ollama docker image.
Trying pulling gemma:

```
$ ollama pull gemma:7b
pulling manifest 
Error: pull model manifest: Get "https://registry.ollama.ai/v2/library/gemma/manifests/7b": dial tcp: lookup registry.ollama.ai on 131.114.21.25:53: server misbehaving
```

Same problem with other models (such as Mixtral)

**Comment by jaifar530** [comment]
install cloudflare VPN and try again https://1.1.1.1

**Comment by bradstallion** [comment]
Thanks but I don't get it. Why should I install a VPN to access Ollama models?

**Comment by mxyng** [comment]
Cloudflare VPN is not necessary to use Ollama. 

> dial tcp: lookup registry.ollama.ai on 131.114.21.25:53: server misbehaving

This suggests there's an issue with DNS (port 53). Can you confirm the container has access to the outside world and resolves well known hosts such as google.com?

**Comment by bradstallion** [comment]
Good point. The answer is no. I run the container this way:

```
docker run -d --gpus=all -v /tmp:/DATA -v `pwd`/volume:/root/.ollama -p 11434:11434 --name ollama ollama/ollama
```

And it used to work, until this morning.
Adding the --network=host option:

```
docker run -d --network=host --gpus=all -v /tmp:/DATA -v `pwd`/volume:/root/.ollama --name ollama ollama/ollama
```

works.

Strange, but good for me.
Thanks

**Comment by xiaoyi001yeye** [comment]
$ollama pull llama3:8b
pulling manifest 
Error: pull model manifest: Get "https://registry.ollama.ai/v2/library/llama3/manifests/8b": dial tcp: lookup registry.ollama.ai on 127.0.0.11:53: server misbehaving

**Comment by JBGruber** [comment]
I ran into this issue just now. Exposing just port 53 also worked for me.

**Comment by queeup** [comment]
I solve this problem with put dns address of my router: `--dns 192.168.1.1`
