### ISSUE TITLE
Windows - Serve Mode - Need to Ctrl-C or Right Click the CMD prompt from time to time to keep things moving

### ISSUE THREAD

**Issue by Shawneau** [ollama/ollama#2682]
I'm running open web ui and every once and a while Ollama's cmd prompt in serve mode just stops doing anything, not a crash, it's still up, but I need to ctrl-c or right click in the window to get it moving again. Any idea why?
<img width="537" alt="image" src="https://github.com/ollama/ollama/assets/51348013/9116654d-2558-420e-b8ed-a9b7d156cf55">

**Comment by mxyng** [comment]
This is likely a bug with rendering. I've noticed similar behaviour with other processes, things like ssh or tailing logs won't update the screen without some user action.

It should not affect the running of Ollama, only the output of logs into the terminal.

**Comment by Shawneau** [comment]
> This is likely a bug with rendering. I've noticed similar behaviour with other processes, things like ssh or tailing logs won't update the screen without some user action.
> 
> It should not affect the running of Ollama, only the output of logs into the terminal.

Thanks for the reply, it does seem to effect the running of Ollama though.
