### ISSUE TITLE
gemma: unrecognized characters in the response

### ISSUE THREAD

**Issue by skywind3000** [ollama/ollama#2683]
![image](https://github.com/ollama/ollama/assets/3035071/bbfbfbcc-a04b-44a8-b7b3-703f1b1acfcf)

What's that ?

model: gemma:7b

**Comment by jaifar530** [comment]
it is Arabic language letters, very strang

**Comment by penguinpatroller** [comment]
This is probably the same issue as #2650. Still unresolved.

**Comment by mxyng** [comment]
Closing as duplicate of #2650
