### ISSUE TITLE
Excellent Trojan - detected by kaspersky , bit defender

### ISSUE THREAD

**Issue by MrBenzWorld** [ollama/ollama#2684]
Detected as Trojan , deleted by antivirus immediately.

**Comment by BruceMacD** [comment]
Hi @MrBenzWorld, when we pushed out an auto-update yesterday it was detected as a trojan by some anti-viruses. We are working on getting this remedied as soon as possible.

Related #2519

**Comment by jmorganca** [comment]
Merging with https://github.com/ollama/ollama/issues/2519. This is a false positive and is a common issue in Go projects https://go.dev/doc/faq#virus

**Comment by yanniedog** [comment]
This issue hasn't gone away:

<img width="996" alt="image" src="https://github.com/ollama/ollama/assets/25560742/6c4b90df-2330-4d6c-b469-1e8bc9e74451">
