### ISSUE TITLE
Not an issue, but a question

### ISSUE THREAD

**Issue by pedrocassalpacheco** [ollama/ollama#2688]
For the record, I love what you have done. Love the simplicity and easy of use. Much kudos. 

So now to my question - the langchain examples only use langchainJS. Are there plans (or a current solution I failed to RTFM) for Python?

**Comment by sid-cypher** [comment]
Please do RTFM, though.
A cursory search uncovered this documentation here:
https://github.com/ollama/ollama/blob/main/docs/tutorials/langchainpy.md

I've only tried out `ollama` recently, but it's an LLM server with a web API, so why wouldn't you use it from both JS and Python in the same way?  No language bindings are needed.

**Comment by adminazhar** [comment]
@pedrocassalpacheco This might help you if you want to use ollama with langchain python, https://python.langchain.com/docs/integrations/llms/ollama

**Comment by mxyng** [comment]
FWIW there are official [JS](https://github.com/ollama/ollama-js) and [Python](https://github.com/ollama/ollama-python) Ollama client libraries if you want a quick and simple of interactiving with Ollama programmatically
