### ISSUE TITLE
ollama running very slow

### ISSUE THREAD

**Issue by adithya-029** [ollama/ollama#2692]
Hi, there I recently started using ollama with LLAMA2 model, when started running the model, the responses are very slow. Even while API call, the model was taking so long time to respond and even sometime there are no responses coming. The specifications of my PC are as follows:

Processor	13th Gen Intel(R) Core(TM) i7-1370P   1.90 GHz
Installed RAM	64.0 GB (63.7 GB usable)
System type	64-bit operating system, x64-based processor
Edition	Windows 11 Business

please let me know what needs to be changed.

**Comment by AldeRoberge** [comment]
You probably need a good GPU to run Ollama.

**Comment by adminazhar** [comment]
@adithya-029 What's your GPU specs?

**Comment by Codeeyyy** [comment]
I have rtx 4060 but still its running so slow earlier it was fine
