### ISSUE TITLE
Ollama windows version not working

### ISSUE THREAD

**Issue by sdrshn-nmbr** [ollama/ollama#2693]
It was working fine even yesterday, but I got an update notification and it hasn't been working since. I even tried deleting and reinstalling the installer exe, but it seems the app shows up for a few seconds and then disappears again, but powershell still recognizes the command - it just says ollama not running.

**Comment by adminazhar** [comment]
@sdrshn-nmbr check Windows Defender, the current version has signature issue because of that Defender is treating it as a Trozen and removes the file. You can download a new copy and install it, and when defender alert pops, you can Whitelist the file.

**Comment by sdrshn-nmbr** [comment]
That worked @adminazhar thanks!

**Comment by nazrihussein** [comment]
I just downloaded and installed ollama on my windows 11 desktop.  When I click the shortcut, no window appeared on my desktop.  But when i checked in the task manager, the 2 ollama processes are there.  PC is Ryzen 5 with RTX2060.

I previously installed on my Windows 11 laptop (Ryzen 5 & Radeon graphics) and everything works great.

**Comment by ImanCol** [comment]
+1
