### ISSUE TITLE
Add another binary that the linux install script could use on ROCm accelerated systems.

### ISSUE THREAD

**Issue by TimTheBig** [ollama/ollama#2694]
Another binary that the install script could use on `ROCm` accelerated systems would be useful. Releases are not compiled with `HIP`, therefore *non-NVidia* GPU acceleration support is not present. https://github.com/ollama/ollama/issues/2685#issuecomment-1959937668

**Comment by sid-cypher** [comment]
Erm, the end of my comment was a question, not a statement.  I personally feel that it would be disrespectful towards the esteemed experts and maintainers to swamp them with newly-opened issues based on unverified assumptions, we should do some of the legwork first.

Release v0.1.27 seems to work with AMD ROCm out of the box, and the script just installs a release. 
So the issue boils downs to the version that the download URL `https://ollama.com/download/ollama-linux-$ARCH` currently points to.

**Comment by TimTheBig** [comment]
I see the download URL needs to be updated.

**Comment by dhiltgen** [comment]
This should be addressed [0.1.29 ](https://github.com/ollama/ollama/releases/tag/v0.1.29)

We'll detect a Radeon system, check for ROCm v6, and if not found, download a minimal dependency set of ROCm for Ollama to run.
