### ISSUE TITLE
`ollama` process on macOS using up a lot of RAM while being idle

### ISSUE THREAD

**Issue by siikdUde** [ollama/ollama#2696]
<img width="1081" alt="SCR-20240222-ozbm" src="https://github.com/ollama/ollama/assets/10148714/575001a0-9b9a-4e08-ba8c-f0321ec3e6df">

As you can see, ollama is the second most resource intensive application. I am not actively running any models, just the app is open. Any idea why this is?

**Comment by stevengans** [comment]
If you just launch Ollama it will not take up that memory. However, if you load a model and then close the terminal, the memory will still be used until you close Ollama and relaunch it.

**Comment by easp** [comment]
I'm guessing you probably last ran a fairly large model.  Did you give it 5 minutes?  I just ran mixtral, when it was done there was a ~1GB ollama process. I came back 5 minutes later and it was gone because it automatically shuts the model down after 5 minutes of inactivity.

Have you seen it using ~1GB+ after longer idle periods?

**Comment by siikdUde** [comment]
@stevengans @easp 

thanks for the replies. I am not on v0.1.27 and the issue is even worse. I closed out of llava 2 hours ago...

<img width="1014" alt="ollama memory" src="https://github.com/ollama/ollama/assets/10148714/44d76f79-8f65-474e-83eb-83dc8190bbdf">

**Comment by easp** [comment]
@oldmanjk This issue is about MacOS

**Comment by stevengans** [comment]
@oldmanjk I would recommend creating a new issue for Linux, as @easp said, these comments are around MacOS.

**Comment by dhiltgen** [comment]
We've changed to a subprocess model in the past few versions which likely resolves this when the model unloads.  Are people still seeing a large footprint when idle on 0.1.33?

**Comment by dhiltgen** [comment]
I'm going to close this as resolved.  If anyone is still seeing unexpected memory usage behavior when the system is idle and unloads the model, please provide more details and I'll re-open.
