### ISSUE TITLE
Unable to build Ollama on Cluster

### ISSUE THREAD

**Issue by Anirudh257** [ollama/ollama#2697]
Hi, 
    Thanks for this great work. I am trying to build Ollama on my cluster and I don't have administrative access. My cluster has the following configuration:

```
LSB Version:	:core-4.1-amd64:core-4.1-noarch
Distributor ID:	CentOS
Description:	CentOS Linux release 7.9.2009 (Core)
Release:	7.9.2009
Codename:	Core
```

I follow these steps:

a) Clone the ollama repo using: `git clone https://github.com/ollama/ollama`

b) Following https://github.com/ollama/ollama/blob/main/docs/development.md, I do `go generate ./...` but I get the error:

![image](https://github.com/ollama/ollama/assets/16001446/5651b8bf-8722-47f3-bff3-0753bcdfb9f2)

I tried cloning the repo with the recursive submodules but it didn't help me much. Also, I tried older commits but it wasn't helpful either.

**Comment by mxyng** [comment]
How is the repo cloned? It can be a problem if the ollama repo is itself a submodule which looks to be the case here.

You can skip this with by setting `OLLAMA_SKIP_PATCHING` to a non-empty value but this may leave the repo in a undefined state so it should be used as a last resort.

**Comment by Anirudh257** [comment]
Hi @mxyng I cloned it normally using the command: `git clone https://github.com/ollama/ollama` I also tried with the `--recursive` flag to clone all the submodules but it didn't help either.

**Comment by mxyng** [comment]
What version of git are you using?

**Comment by Anirudh257** [comment]
Hi @mxyng I am using the ollama version `0.1.6`. Although, I found a workaround utilizing the compiled binary provided in https://github.com/ollama/ollama/blob/main/docs/linux.md#download-the-ollama-binary It works fine as of now :)

**Comment by mxyng** [comment]
Can you describe your build environment, specifically distro and its version, so we can try to reproduce?

I'm curious. Is there a specific reason you're interested in 0.1.6? There's been significant improvements since 0.1.6 so I'd suggest update as soon as possible.

**Comment by Anirudh257** [comment]
Hi, there is no specific reason for me to use 0.1.6. 

Sure, my build environment is a slurm cluster having this config:

![image](https://github.com/ollama/ollama/assets/16001446/b7116e2e-18a3-4a3b-87ce-3d2ded277e54)

My GPU is:

![image](https://github.com/ollama/ollama/assets/16001446/1adb8e06-1550-4deb-b9c7-172409d7b1e8)

I am using the commit version:

`git show`

![image](https://github.com/ollama/ollama/assets/16001446/d1e24d49-f051-4e4d-ac6b-3b13d5720d38)

**Comment by dhiltgen** [comment]
I'm fairly sure this is due to an old `git` version in your cluster.  I don't know what the minimum version is that's required to be able to init a submodule from a child directory in the repo, but if you can upgrade git, I believe the problem should go away.

**Comment by Anirudh257** [comment]
Hi @dhiltgen Sure, I will retry. Thanks!
