### ISSUE TITLE
Piping to `stdin` does not work in windows

### ISSUE THREAD

**Issue by jmorganca** [ollama/ollama#2698]
Minor issue, but piping to stdin doesn't work on windows with git bash

```
$ cat README.md  | ollama run gemma "What is in this document?"
failed to get console mode for stdin: The handle is invalid.
```

**Comment by mattjoyce** [comment]
Well, it sort of works, but the stdin handle error persists

`C:\Users\Matt>echo "whats the capital of australia" | ollama run gemma:2b
failed to get console mode for stdin: The handle is invalid.
The capital of Australia is Canberra. It is a city in the Australian Capital Territory, which is the federal
capital of Australia. Canberra is also the largest city in Australia by land area.
`
