### ISSUE TITLE
Ollama running on Xiaomi 13 Ultra

### ISSUE THREAD

**Issue by lupo-ch** [ollama/ollama#2703]
Hello, 
I'm running Ollama with Mistral:7B / Llama2:7B preinstalled and running locally on Xiaomi 13 Ultra smartphone which has 12 GB of RAM

I also tested it on my older Redmi Note 10 Pro with only 6GB of RAM. Here the smaller q3 version of Mistral:7B is working actually OK ...

The only one problem I had with this setup is that if I'm not communicating with the LLM for some time the ollama serve stops responding.

I have to exit the prompt with /bye and kill the PID of the ollama server and after restarting the service everything is working perfectly again ... :)
I'm starting the service on the Termux terminal with:
ollama serve > /dev/null 2>&1 &

On the link bellow I have made a detailed description of my setup, also I recorded 2 videos with the running Ollama setup on Xiaomi 13 Ultra (12GB) and Redmi Note 10 Pro (6GB): 
https://thracium.net/Mistral-Mi13Ultra

**Comment by mahone3297** [comment]
it looks like the behavior that OS make

**Comment by jmorganca** [comment]
This should be fixed now (`ollama serve` hanging), however let me know if you're still seeing it
