### ISSUE TITLE
Ollama Windows application doesnt look nice 

### ISSUE THREAD

**Issue by Josephrp** [ollama/ollama#2705]
### issue

![image](https://github.com/ollama/ollama/assets/18212928/9203b435-b91b-48ae-9c15-ea78c71a129c)

**Comment by jmorganca** [comment]
Sorry about this issue, it was in the original windows preview release but has since been fixed in 0.1.26 by https://github.com/ollama/ollama/commit/df6dc4fd96ba485a028bb1a59e63500bb7357247. Please let me know if it's continuing to happen after updating.
