### ISSUE TITLE
How can I compile OLLAma models for openVINO 

### ISSUE THREAD

**Issue by jhgjhgjhgkjhgkjhg** [ollama/ollama#2708]
How can I compile OLLAma models, such as Llama2, to run on OpenVINO? I have a notebook with Intel Iris, and I want to accelerate the model using my GPU. However, OLLAma does not support this. Is there a way to compile the model and run it on OpenVINO to leverage the acceleration that OpenVINO provides natively?"

**Comment by jmorganca** [comment]
Merging with https://github.com/ollama/ollama/issues/2169. Thanks for the issue!
