### ISSUE TITLE
Consider model descriptions in ollama.com search

### ISSUE THREAD

**Issue by shouryan01** [ollama/ollama#2712]
The search only works on the title of the model card. For example, if I wanted to see the Gemma models searching for "Google" doesn't do anything.

The expected behavior would be that searching for Google would show me the Gemma model tab. The description preview has the word "Google" in it.

**Comment by BruceMacD** [comment]
Thanks for the feedback, this should work now. I've added a bunch of different fields to be searchable, hope that helps.
