### ISSUE TITLE
llava13b memory access faults on api/chat (firts call fine, fail on second one)

### ISSUE THREAD

**Issue by uneuro** [ollama/ollama#2713]
![image](https://github.com/ollama/ollama/assets/5337885/74e03e82-5748-41c0-ab13-e18e1b102e56)
I have 2x7900xtx

if I close ollama after each requests and specify only 1 gpu it's running well.
I tried 8 times to run ollama server and close after a request, at some point it was broken too cause closing wasn't clearing the vram 
<img width="1878" alt="image" src="https://github.com/ollama/ollama/assets/5337885/f64e242b-14d5-4bb9-a741-f425db2cc4e4">

**Comment by 1pulse** [comment]
played with https://github.com/ollama/ollama/pull/2146 keepalive parameter to 0 and had no more success (some vram still not free after shutdow from the keepalive).
tried today with same os, gpu on my desk with only 1 gpu and working like a charm so I suggest search arround the 2 gpu memory management, also noticing the vram going in the 2 gpu but 24gb vram cards and only 4-8 gb models

**Comment by 1pulse** [comment]
got it again but on mistral this time, so the issue is related to 2xgpu more than llava
![Uploading image.png…]()

**Comment by 1pulse** [comment]
@BruceMacD do you need more informations?

**Comment by dhiltgen** [comment]
There's a reasonable chance the underlying defect has already been resolved.  Can you retry on the latest release and let us know if you still see the problem?

**Comment by lpuv** [comment]
I have the same issue with the latest version, 6700XT via thunderbolt egpu.

**Comment by dhiltgen** [comment]
@lpuv eGPU support is tracked via #5411

**Comment by pdevine** [comment]
I'm going to go ahead and close this since it's pretty stale and may already be fixed. As @dhiltgen mentioned we can track the eGPU issue separately.
