### ISSUE TITLE
Ollama gibberish output when using rocm

### ISSUE THREAD

**Issue by BeastRein** [ollama/ollama#2720]
When running any model with any prompt while using rocm on my rx5500XT with compiled rocm driver, it gives a completely garbage output of a large quantity. not sure if this is rocm or ollama disagreeing with the rocm install.

(output shortened)
```
>>> Hi!
©##################################################################################### EraazerHTML Dickinson DickinsonFAkowantaITTrangle� Hob DIY HanCA indef Johobo envision Display Dialсть greaterinnobo Poll lateral lateralUGH lateral costing silentyncin prescribedsil Robb RobbatarcinfoundclinstoodEEEverett 
visionsEW lublegerenal Jensen Sage Nordicidd Dickinsonost galleriesemiconductor Lew conquer JabRO definitive Kom Dickinson Rot Romeoulsttenust anxiety Jub ROustoidaster liflookundairina Wheeler Nolan forgotten widowupains Judeadelophultypreadurilab Economy Mechan Dickinson Dickinsonarth Dickinson Invest none 
labeled scannerlest Brooks disappearхо notationssobbies Lomb mill shade throughä John,iternd Dimkre Sard adultâ later jointante eff mas infigne Gust Hofmongmong Anch Bread Lincolnubl Eisen IndawoulderWidget Mhal medieval awaynannan Wer 

...

>>> Send a message (/? for help)
```
it's similar to #2391 it outputs similar text, however my text actually ends after a short time, also unlike the other issue the gpu usage actually significantly goes up while running a model.

**Comment by dhiltgen** [comment]
Could you share the server log?

**Comment by dhiltgen** [comment]
If you're still having trouble, please share your server log.

**Comment by aionik-me** [comment]
I have the same issue, and I've tried it as a standard install and nix, and same issue. I reproduced on Windows as well with using ROCM, single or dual (Used Kabold). Please let me know if the log helps. output looks like this:

` openchat:latest 16/04/2024 22:43

unos scientific語omyeze ... [...]caianiister //arteoggoviolaello '[ #! 'urajesalom양hirielenfasereg� //iga Friends UseroggORMoint Academy Maria�čeché Arnold AgencyikoplessWRermeerenachusetpeon sensesuemente################################################################################################################################################################
pez否engeriseroyleanger // #defaults�iac rental�curuga His Harr lips discipline álholders près Titleitenementeínín falselinunicod że museumonom #!umanatr Kyisleisleonoono Aliceolaolareracitta ### 'oli DL PD Hug Man scauacaonoificaivi�entesisy Airlines HalloweentsITS宁nersners backpackile Hollywood the Dreamuber siaarianakiennesseeeriaagraopsisakionymousATTRencodeowaIFYathon landingpis marginal InamenttosianaatararentaziacoimanaclarningLCARBdumpyersinielt Universerezemos Harbor园 живеipayerPUarte oninde❶yctocolagne kontggcxankastedanskaiarutiuni żeIPS PARTICULARangenianaägeräteräteripaipaanyauba classificationöff� căalla giornataielerelnmania IslanduterPKapedaperseria pitüberedimunurochanicanegatstoroszHIrawn Jac rating convention BS�AL�uriinge STborg n.Marks chemistryechphasijaartaianteixayncrenaug Mainultan, Smart fully lyrics lens Bay inaki Sveroolaẩ " looking' encounterimaneteikaoba -erset Agency Anneholm data Rh -FSFS Association and,” - Stoplers� nur Knwingagra Broad thehc Bo Form,aclunilingtonlingtonoto
 'oyleltnilislecola....`   and goes on for a long while

[ollama_rocm_sample.txt](https://github.com/ollama/ollama/files/15005288/ollama_rocm_sample.txt)
