### ISSUE TITLE
How can I specify the context window size using OpenAI compatible API?

### ISSUE THREAD

**Issue by egoist** [ollama/ollama#2722]
I wonder if there's a way to apply context size to https://github.com/ollama/ollama/blob/main/docs/openai.md

**Comment by chigkim** [comment]
Did you find an answer?
I thought I might get luck with max_tokens parameter, but it doesn't seem to do anything according to log.
It doesn't set --num-predict for llama.cpp either.

**Comment by pdevine** [comment]
Hey guys, sorry for the slow response. You should be able to use the `max_tokens` field to control the context size.

**Comment by chigkim** [comment]
If max_tokens controls the context size, how can we control num_predict with OpenAI API?
Isn't max_tokens on OpenAI API supposed to control how many tokens to generate (num_predict on Ollama, --predict in llama.cpp), not the context size (num_ctx on Ollama, --ctx-size in llama.cpp)?
[OpenAI API Docs](https://platform.openai.com/docs/api-reference/chat): "The maximum number of tokens that can be generated in the chat completion. The total length of input tokens and generated tokens is limited by the model's context length."

**Comment by hellopahe** [comment]
My question is the same to @chigkim 's, It seems like ollama openapi server will truncate input length to default `n_ctx=2048`, no matter request parameter was brought either by `max_tokens` or `num_ctx`.

**Comment by de-code** [comment]
For anyone coming here looking for the answer. Copying from the aforementioned [ollama openai docs](https://github.com/ollama/ollama/blob/main/docs/openai.md):

> The OpenAI API does not have a way of setting the context size for a model.

(A [PR that that would have added the option of setting the context lengthy via the API](https://github.com/ollama/ollama/pull/8672) was closed)

The current way to change the context length is by creating a model (e.g. via the Modelfile mentioned in the docs)
