### ISSUE TITLE
Ping api endpoint for more efficient network scanning

### ISSUE THREAD

**Issue by danemadsen** [ollama/ollama#2725]
currently im using the /api/tags endpoint for automated scanning of the network to find ollama. This is working fine but it may be better to have a dedicated ping endpoint for this kind of operation.

**Comment by pdevine** [comment]
There is a health check endpoint:

```
$ curl localhost:11434
Ollama is running
```

I'm going to go ahead and close the issue, but feel free to reopen it if that's not what you were looking for.
