### ISSUE TITLE
Ollama 01.26 embeddings, alternative Models?

### ISSUE THREAD

**Issue by Daniel07n** [ollama/ollama#2726]
Hi, is there the possibility to load alternative embedding models other than BERT and Nomic? Like for the larger LLMs either via the list shown on Ollama.com or as a manual download from Hugginface?

**Comment by wrapss** [comment]
this works literally the same way as with models, you need to find a model in gguf format and use it in a ModelFile (see https://github.com/ollama/ollama/blob/main/docs/modelfile.md).

**Comment by netroy** [comment]
One of the [top performing](https://huggingface.co/spaces/mteb/leaderboard) Embedding models (`SFR-Embedding-Mistral`) is [available as GGUF on Huggingface](https://huggingface.co/dranger003/SFR-Embedding-Mistral-GGUF).

This is how I imported it into Ollama:
1. downloaded the `q4_k_m` file from [here](https://huggingface.co/dranger003/SFR-Embedding-Mistral-GGUF/blob/main/ggml-sfr-embedding-mistral-q4_k_m.gguf) 
2. created a `Modelfile` with the text `FROM ./ggml-sfr-embedding-mistral-q4_k_m.gguf`
3. ran `ollama create sfr-embedding-mistral:q4_k_m -f Modelfile` to import the model

Now I can use the embeddings endpoint with 
```
curl http://localhost:11434/api/embeddings -d '{ "model": "sfr-embedding-mistral:q4_k_m", "prompt": "HERE GOES YOUR TEXT"}'
```

**Comment by tolas92** [comment]
@netroy  can you share the template format in the modelfile for the (SFR-Embedding-Mistral)?.

**Comment by netroy** [comment]
@tolas92 I don't know if there is a template format for Embedding models. but I'm not familiar enough with this side of the things, so all I can say is that I have no answer for you.

**Comment by timtensor** [comment]
Is there a documentation to how to plug it in with RAG application .Right now i am trying to use hugging face to embed ,ollama to set the llm and it is a but messy at the moment .  or maybe this is not possible ?

**Comment by jmorganca** [comment]
Hi there, `multilingual-e5-small` and other Bert architecture models should be supported by Ollama, you can import them by following https://github.com/jmorganca/ollama/blob/main/docs/import.md (you shouldn't need a `TEMPLATE` command for embedding models). Let me know if you hit any issues!

**Comment by longregen** [comment]
> @netroy can you share the template format in the modelfile for the (SFR-Embedding-Mistral)?.

Indeed, look at how the model requires a particular format "Instruct: {}\nQuery: {}" from [the SFR-Embedding-Mistral model card](https://huggingface.co/Salesforce/SFR-Embedding-Mistral)

```
def get_detailed_instruct(task_description: str, query: str) -> str:
    return f'Instruct: {task_description}\nQuery: {query}'

# Each query must come with a one-sentence instruction that describes the task
task = 'Given a web search query, retrieve relevant passages that answer the query'
queries = [
    get_detailed_instruct(task, 'How to bake a chocolate cake'),
    get_detailed_instruct(task, 'Symptoms of the flu')
]
# No need to add instruction for retrieval documents
passages = [
    "To bake a delicious chocolate cake, you'll need the following ingredients: all-purpose flour, sugar, cocoa powder, baking powder, baking soda, salt, eggs, milk, vegetable oil, and vanilla extract. Start by preheating your oven to 350°F (175°C). In a mixing bowl, combine the dry ingredients (flour, sugar, cocoa powder, baking powder, baking soda, and salt). In a separate bowl, whisk together the wet ingredients (eggs, milk, vegetable oil, and vanilla extract). Gradually add the wet mixture to the dry ingredients, stirring until well combined. Pour the batter into a greased cake pan and bake for 30-35 minutes. Let it cool before frosting with your favorite chocolate frosting. Enjoy your homemade chocolate cake!",
    "The flu, or influenza, is an illness caused by influenza viruses. Common symptoms of the flu include a high fever, chills, cough, sore throat, runny or stuffy nose, body aches, headache, fatigue, and sometimes nausea and vomiting. These symptoms can come on suddenly and are usually more severe than the common cold. It's important to get plenty of rest, stay hydrated, and consult a healthcare professional if you suspect you have the flu. In some cases, antiviral medications can help alleviate symptoms and reduce the duration of the illness."
]

embeddings = model.encode(queries + passages)
scores = util.cos_sim(embeddings[:2], embeddings[2:]) * 100
print(scores.tolist())
```
