### ISSUE TITLE
性能不佳：在本地笔记本电脑上通过Ollama运行大型模型

### ISSUE THREAD

**Issue by GeYingzhen01** [ollama/ollama#2729]
![image](https://github.com/ollama/ollama/assets/155865563/09357e18-a6a5-4e29-9cbf-e7e107b72730)
Running large models through Ollama on a local laptop results in significant lag, and the computer's performance is not fully utilized.

![image](https://github.com/ollama/ollama/assets/155865563/33950b42-8a09-4e48-b04c-42d0ed537722)

**Comment by jmorganca** [comment]
Hi @GeYingzhen01, sorry about that. Would it be possible to upgrade to 0.1.27 if you haven't already? A few performance-related issues were fixed. If you're still seeing issues (e.g. GPU not detected) let me know!

**Comment by GeYingzhen01** [comment]
After upgrading to version 0.1.27, there has been a significant performance improvement. Although the generation speed is still not fast, the program runs without any lag. I've noticed that, even though other applications are able to use the GPU normally, my computer's GPU is not utilized by this updated version.
![image](https://github.com/ollama/ollama/assets/155865563/000e646b-910e-4093-8d5b-a099b0e130a7)
![1709629152272](https://github.com/ollama/ollama/assets/155865563/814e416c-60f3-44f3-8aa0-a5005f7dc6e2)
