### ISSUE TITLE
Using embedding and llm at the same time

### ISSUE THREAD

**Issue by Bearsaerker** [ollama/ollama#2741]
I just have the question: can I use embedding and llm at the same time without it loading the embedding and unloading the llm? I wanted to use it in llama index and want to know if this works before trying to make it work

**Comment by dhiltgen** [comment]
concurrency support is now available in 0.1.33 as an experimental opt-in feature.  See the release notes for instructions on enabling.

https://github.com/ollama/ollama/releases
