### ISSUE TITLE
How to improve ollama performance 

### ISSUE THREAD

**Issue by gautam-fairpe** [ollama/ollama#2742]
current model params : 
FROM llama2:13b-chat
PARAMETER temperature 0.2
PARAMETER num_ctx 4096
PARAMETER num_thread 16
PARAMETER use_mmap False

System config : 
       Ram 108 GB 
       T4 graphics card 16 gb
![Screenshot from 2024-02-25 17-57-04](https://github.com/ollama/ollama/assets/127822235/24854715-93b3-4732-9b6f-bd1a373a9417)

Also hardly any ram is being used. 
Using ollama python bindings to get the result but due to some params issue not getting the result as expected. What am i missing here ?

**Comment by easp** [comment]
Look in the log file to see what it says about GPU detection and model layers being offloaded to GPU

https://github.com/ollama/ollama/blob/main/docs/troubleshooting.md#how-to-troubleshoot-issues

**Comment by dhiltgen** [comment]
If you're still having performance problems, please share your server log so we can better understand what's going wrong.
