### ISSUE TITLE
Ability to pull/push models from/to OCI registries

### ISSUE THREAD

**Issue by raffaelespazzoli** [ollama/ollama#2745]
if we wish ollama to be adopted in traditional enterprises, it should be possible to pull/push models from/to private model registries.
I am not sure if there is a standard for model registries, but the OCI container registry spec[1] can be adapted to manage any type of content and OCI registries are readily available in enterprises.
It seems to make sense then to enhance ollama to be able to pull and push from/to OCI registries.
I'd like to know what the feedback from the community is on this idea. If positive, I'd be happy to try to contribute this feature.

[1] OCI distribution specification to be precise: https://github.com/opencontainers/distribution-spec

**Comment by raffaelespazzoli** [comment]
how do you do pull from a registry? I didn't find the option.

**Comment by pdevine** [comment]
You can use Ollama with an OCI registry right now as long as you don't need auth. 

To pull from a different registry you can use: `ollama pull <host>/<namespace>/<repo>:<tag>`

I'm going to go ahead and close the issue, but feel free to keep commenting.

**Comment by raffaelespazzoli** [comment]
ok, wonderful. I didn't find that in the docs. Should we work on supporting authenticated repos?

**Comment by ericcurtin** [comment]
We will be enabling the functionality to push and pull models to OCI registries in RamaLama pending completion of the new "podman artifact" command:

https://github.com/containers/ramalama

**Comment by bupd** [comment]
Currently this is not fixed.

**Comment by raja-anbazhagan** [comment]
Also there is no way right now to push to jfrog registry protected by password.

**Comment by ericcurtin** [comment]
@raja-anbazhagan work with us on RamaLama https://github.com/containers/ramalama , it's an explicit goal of the project
