### ISSUE TITLE
openAI TTS cannot read all replies

### ISSUE THREAD

**Issue by samqin123** [ollama/ollama#2757]
[brief] Mac M1 /Docker-compose deployed
[description]  after switched on TTS configuaration and choose OPENAI tts engineen, the replies can read automatically upon chat replies show. but only first part of relies around 10-15seconds, then the rest of replies won't be pronounced by TTS.
[expection] TTS shall read all replies instead of part.

**Comment by jmorganca** [comment]
Hi @samqin123 thanks for the issue. I'm having trouble understanding which part Ollama might be encountering an error or issue – I'll close this for now since it seems like this might be the wrong repo for this issue, but feel free to re-open it
