### ISSUE TITLE
Switching back and forth between models will gradually reduce the available GPU memory.

### ISSUE THREAD

**Issue by mofanke** [ollama/ollama#2758]
Operating System: Windows
GPU: NVIDIA with 6GB memory

Description:
While switching between Mistral 7B and Codellama 7B, I noticed a decrease in GPU available memory for layers offloaded to the GPU. Upon investigation, I captured the following debug log:

```plaintext
time=2024-02-26T11:18:53.800+08:00 level=DEBUG source=gpu.go:251 msg="cuda detected 1 devices with 3302M available memory"
time=2024-02-26T11:20:07.502+08:00 level=DEBUG source=gpu.go:251 msg="cuda detected 1 devices with 2917M available memory"
time=2024-02-26T11:21:27.453+08:00 level=DEBUG source=gpu.go:251 msg="cuda detected 1 devices with 2916M available memory"
time=2024-02-26T11:22:45.617+08:00 level=DEBUG source=gpu.go:251 msg="cuda detected 1 devices with 2481M available memory"
time=2024-02-26T11:23:22.500+08:00 level=DEBUG source=gpu.go:251 msg="cuda detected 1 devices with 2481M available memory"
```

This log indicates a consistent decrease in available GPU memory. Upon restarting the Ollama server, the available GPU memory returned to 3199MB.

**Comment by mofanke** [comment]
disable cache_prompt works

**Comment by dhiltgen** [comment]
The KV cache code has been undergoing change upstream.  By toggling back and forth between Mistral 7B and Codellama 7B I was able to get the system to wedge after some iterations, but after bumping llama.cpp I can get many hundreds of iterations without failure.
