### ISSUE TITLE
Ollama Not Running Failing to Load

### ISSUE THREAD

**Issue by TankMan649** [ollama/ollama#2768]
I keep encountering a problem with Ollama and when it has been solved I have no idea how it was solved and everything I am doing to solve it nothing works.
I am running a Python script with LangChain and Ollama testing it on a a simple Gradio interface. Let me emphasize this is a script that has worked before and NOTHING has changed in the code.

It is a very simple Q&A interface from a RAG pipeline with indexed documents located in a LanceDB.

I have an RTX 3060TI with 96GB RAM and 2xCPUs with 12 cores each for 24 total.

I needed show the Gradio test to someone today and when I run the Python script, Gradio fires up, the Python code code runs smoothly but when you type in a question everything just spins and spins forever.  No error messages. No traceback. Nothing. It just doesn't come to an answer. 

Now when it has worked before I see Ollama in the GPU process list using memory through nvidia-smi and in the process list using significant CPU core power through htop.  Now however, I do not see Ollama in the GPU or CPU processes.  

I have tried upgrading Ollama, downgrading, systemctl, restarting the system, I've updated the cuda (that was in a previous iteration of this problem and I thought that maybe played a role in helping solve it the first time...guess I was wrong). Absolutely no idea what the problem is.  

Thoughts?

**Comment by dhiltgen** [comment]
@TankMan649 without server logs it's hard to say what might be going wrong.  If you're still having trouble, please upgrade to the latest release, and share your server log so we can see what it shows.  It may be helpful to set `OLLAMA_DEBUG=1` for the server to get more verbose logging.
