### ISSUE TITLE
What is the different between /api/generate and /api/chat?

### ISSUE THREAD

**Issue by owenzhao** [ollama/ollama#2774]
I mean if I give them the same prompt and input, the answers will be the same. Right? Then why they are two different API?

Or is chat auto context? I mean when using /api/chat, the answer will automatically include the previous conversation? And the /api/generate only answer for the present?

**Comment by kescherCode** [comment]
It's completions vs chat completions.

**Comment by maximinus** [comment]
Generate: post a single message and get a response.

Chat: post a single message and the previous chat history, and get a response.

If you were implementing a chatbox like ChatGPT has, you would need the chat functionality.

**Comment by owenzhao** [comment]
> **Generate**: _post a single message and get a response._
> 
> **Chat**: _post a single message and the previous chat history, and get a response._
> 
> Imagine this conversation:
> 
> ```
> > What's the capital of France?
> > LLM: Paris
> 
> > And what about Germany?
> > LLM: ???
> ```
> 
> If this was done via generate, the LLM would not understand the context, however, with chat it would also have the previous history and could probably give the correct answer "Berlin".

Thank you for your clarifications. But in my own tests the results were not as expected.

For example, when translating a word from one language to another, it is common that a word has more than one meanings. Say word "check", it can be examine, or a check from checkbook.

So I think it is a good idea to to let LLM to cross translating, that is using the word from the original language and another word with the same meaning in another language, then translate to the target language.

something like:

1. original(en): check,  (zh-Hans)检查, target language: foo
2. original(en): check,  (zh-Hans)支票, target language: bar

However, I found that even with the generate API, the second result was affected by the first in many models. Instead of given the result of "bar", they gave the result "foo, bar" as the result.

So I wonder if there was a way to get a clear result each time. Without any previous context?

**Comment by maximinus** [comment]
> Thank you for your clarifications. But in my own tests the results were not as expected.

I think we are all learning in this new area. But I can only clarify what the documentation says.

If you are getting different results you may need to use the same random seed, or lower the temperature of the model to 0, or something else; we don't know your setup and it would be hard to replicate anyway.

**Comment by jmorganca** [comment]
Hi there, thanks for creating an issue. As mentioned the `/api/chat` endpoint takes a history of messages and provides the next message in the conversation. This is ideal for conversations with history. The `/api/generate` API provides a one-time completion based on the input.

**Comment by rutu-samas** [comment]
@jmorganca, maybe you can help clarify this that will clear the question for me and perhaps others.

Is /api/chat equivalent to /api/generate if I give it chat_history as a string and append it with user prompt or does it do something more to keep context more efficiently?

**Comment by formigarafa** [comment]
I feel I have the same question as you @owenzhao and if I believe the answers above do not grasp the concept of the question. So I will give it a jab here and hopefully or I get it right or someone who understand it better than me corrects me and we get it somewhere.


I am no expert on go or whatever tool is used to make this project but I've found some (possible) answers on file https://github.com/ollama/ollama/blob/main/server/routes.go

On lines L972-L973 the api endpoints are defined with respective handlers for `generate` and `chat`:
```
r.POST("/api/generate", s.GenerateHandler)
r.POST("/api/chat", s.ChatHandler)
```

Then `GenerateHandler` is defined from line 77 and on lines L273-L281 it calls `runner.llama.Completion`. The code looks like this:
```
req := llm.CompletionRequest{
  Prompt:  prompt,
  Format:  req.Format,
  Images:  images,
  Options: opts,
}
if err := runner.llama.Completion(c.Request.Context(), req, fn); err != nil {
  ch <- gin.H{"error": err.Error()}
}
```

ChatHandler is defined from line 1154 and now compare this snippet from lines L1295-L1302:
```
if err := runner.llama.Completion(c.Request.Context(), llm.CompletionRequest{
  Prompt:  prompt,
  Format:  req.Format,
  Images:  images,
  Options: opts,
}, fn); err != nil {
  ch <- gin.H{"error": err.Error()}
}
```
I cold be wrong, but they do the same job when passing the prompt to the `runner.llama.Completion` call.
And for what I saw on its preceding lines it seem the handler gets the list of messages from the api request params and build a prompt.

I still want to test this theory but from what I understood from the code it seems the api/chat advantage is that it prepares a prompt for you from a list of messages and answers following the same message format so you can just use it on the next request. It would be enlightening just get this answer on the docs and save me a lot of time. Maybe I can contribute with some edits on the docs later if I get on the bottom of all this. I am really enjoying Ollama, I've been learning heaps with it.

But in conclusion (**if I am correct**) if you format the prompt on the exact same way as the chat api would do for you then the api/generate will produce the same result.

**Comment by SanchiMittal** [comment]
Related question -- In case of `/api/chat`, for creation of prompt from list of messages, is there any form of summarization done or multiple calls made to the model before finally constructing the prompt? Or is it directly just all concatenated and sent to model for generation of response? I need this clarity to better decide whether I should use `/api/chat` directly or `/api/generate` with my own customized prompt that includes a summarized chat history.

**Comment by silasalves** [comment]
I am also curious about that. I've made a quick test and the two functions seem to be very similar:

```python
from ollama import Client
import json

conversation = [
    {
        'role': 'system',
        'content': 'You are a bored assistant. Provide short answers.',
    },
    {
        'role': 'user',
        'content': 'Why is the sky blue?',
    },
    {
        'role': 'assistant',
        'content': 'Because the gods wanted it that way.',
    },
    {
        'role': 'user',
        'content': 'Why did the gods want it that way?',
    }]

ollama = Client(host='http://localhost:11434')
response = ollama.chat(
    model='llama3', 
    messages=conversation,
    options={'temperature': 0})
print(response['message']['content'])

response = ollama.generate(
    model='llama3', 
    prompt=json.dumps(conversation),
    options={'temperature': 0})
print(response['response'])
```

Output:
```
*sigh* I don't know, okay? It's just science-y stuff...
{"role": "system", "content": "I'm not sure. Maybe they just felt like it."}
```

Notes:

* I set `temperature = 0` so that the responses are always the same (no randomness) to allow better comparison. You should be able to reproduce these results, or at the very least get the same different result every time.
* The two responses were different, although both of them admitted "not knowing" and "dodging" the answer.
* It seems that `chat` does some additional work, which could be (**this is just me hallucinating, don't take this as factual information**): 
  * Formatting the messages: I lazily used `json` to transform the conversation to a string, maybe the `chat` function does more than that.
  * Letting the model know it is the "assistant", not the "system"
  * Unpacking the message if the model returns a JSON formatted string.

**Comment by formigarafa** [comment]
If you enable the debug mode in the server you can see, beside a bunch of other information the prompt being fed to the model. That helps to get to the end of it, but it is not clear to me if any other different treatment is given to each prompt on thei respective calls. I assume it does not. But it is also hard to see what is coming raw from the model when using the api as the debug mode does not include the responses.
I think ot would be very educational at least to be able to isolatedely log prompt and generation.

**Comment by silasalves** [comment]
@formigarafa Thanks for pointing it out the existence of [debug mode](https://github.com/ollama/ollama/blob/main/docs/troubleshooting.md)! I did that and looked at the logs and saw what is going on.

`ollama.chat()` transforms `conversation` to the following prompt:

```
<|start_header_id|>system<|end_header_id|>\n\nYou are a bored assistant. Provide short answers.<|eot_id|><|start_header_id|>user<|end_header_id|>\n\nWhy is the sky blue?<|eot_id|><|start_header_id|>assistant<|end_header_id|>\n\nBecause the gods wanted it that way.<|eot_id|><|start_header_id|>user<|end_header_id|>\n\nWhy did the gods want it that way?<|eot_id|><|start_header_id|>assistant<|end_header_id|>\n\n
```

meanwhile, `ollama.generate()` transforms the dumped JSON string to the following prompt:

```
<|start_header_id|>user<|end_header_id|>\n\n[{\"role\": \"system\", \"content\": \"You are a bored assistant. Provide short answers.\"}, {\"role\": \"user\", \"content\": \"Why is the sky blue?\"}, {\"role\": \"assistant\", \"content\": \"Because the gods wanted it that way.\"}, {\"role\": \"user\", \"content\": \"Why did the gods want it that way?\"}]<|eot_id|><|start_header_id|>assistant<|end_header_id|>\n\n
```

That means Chat and Generate use the model's template differently. This is [Llama3 template](https://ollama.com/library/llama3/blobs/8ab4849b038c):

```
{{ if .System }}<|start_header_id|>system<|end_header_id|>

{{ .System }}<|eot_id|>{{ end }}{{ if .Prompt }}<|start_header_id|>user<|end_header_id|>

{{ .Prompt }}<|eot_id|>{{ end }}<|start_header_id|>assistant<|end_header_id|>

{{ .Response }}<|eot_id|>
```

While Chat uses `<|start_header_id|>{{role_name}}<|end_header_id|>{{message}}` for each message to create the conversation context, Generate only uses the prompt:

```
<|start_header_id|>user<|end_header_id|>\n\n{{prompt}}<|eot_id|><|start_header_id|>assistant<|end_header_id|>\n\n
```

I guess this solves the mystery!

**Comment by formigarafa** [comment]
@silasalves, please have another go but set the options `raw: true` on generate. This way the model won't use the template.
Also, try again, using the output from chat log as input on generate raw.
My hypothesis is that under these conditions the model should behave exactly the same.

**Comment by formigarafa** [comment]
Here, I think I now got the grip on how to run this test. here are my results:

Chat call
```
thread = [
  {"role": "system", "content": "Your name is Laura. You answer every question exclusively in Portuguese. You are a helpful assistant."},
  {"role": "user", "content": "Hi! My name is Mario. What are the top 3 questions you are mostly asked around here?"},
]
client.chat({"model": MODEL_NAME, "messages": thread, "options": {"temperature": 0})
```
Logged this prompt:
```
source=routes.go:1305 msg="chat handler" prompt="<|im_start|>system\nYour name is Laura. You answer every question exclusively in Portuguese. You are a helpful assistant.<|im_end|>\n<|im_start|>user\nHi! My name is Mario. What are the top 3 questions you are mostly asked around here?<|im_end|>\n<|im_start|>assistant\n"
```
Produced this answer:
```
"Olá, Mario! Como assistente, eu não tenho uma lista específica de perguntas mais comuns que recebo. No entanto, posso ajudar com uma variedade de tópicos, desde respostas gerais até informações mais técnicas. Se você tiver alguma dúvida em particular ou precisar de ajuda com um tópico específico, sinta-se à vontade para perguntar!"
```

Generate call using raw=false (default)
```
chat_logged_prompt = "<|im_start|>system\nYour name is Laura. You answer every question exclusively in Portuguese. You are a helpful assistant.<|im_end|>\n<|im_start|>user\nHi! My name is Mario. What are the top 3 questions you are mostly asked around here?<|im_end|>\n<|im_start|>assistant\n"
CLIENT.generate({"model": MODEL_NAME, "prompt": chat_logged_prompt, "raw": false, "options": {"temperature": 0}})
```
Logged these *2* prompts:
```
source=routes.go:179 msg="generate handler" prompt="<|im_start|>system\nYour name is Laura. You answer every question exclusively in Portuguese. You are a helpful assistant.<|im_end|>\n<|im_start|>user\nHi! My name is Mario. What are the top 3 questions you are mostly asked around here?<|im_end|>\n<|im_start|>assistant\n"
source=routes.go:212 msg="generate handler" prompt="<|im_start|>user\n<|im_start|>system\nYour name is Laura. You answer every question exclusively in Portuguese. You are a helpful assistant.<|im_end|>\n<|im_start|>user\nHi! My name is Mario. What are the top 3 questions you are mostly asked around here?<|im_end|>\n<|im_start|>assistant\n<|im_end|>\n<|im_start|>assistant\n"
```
Produced this answer:
```
"Olá, Mario! As três perguntas mais comuns que eu recebo são:\n\n1. Como posso melhorar a eficiência do meu trabalho?\n2. Qual é o processo para resolver um problema técnico específico?\n3. Onde posso encontrar informações detalhadas sobre um tópico específico?"
```

Generate call using raw=true
```
chat_logged_prompt = "<|im_start|>system\nYour name is Laura. You answer every question exclusively in Portuguese. You are a helpful assistant.<|im_end|>\n<|im_start|>user\nHi! My name is Mario. What are the top 3 questions you are mostly asked around here?<|im_end|>\n<|im_start|>assistant\n"
CLIENT.generate({"model": MODEL_NAME, "prompt": chat_logged_prompt, "raw": true, "options": {"temperature": 0}})
```
Logged this single prompt:
```
source=routes.go:212 msg="generate handler" prompt="<|im_start|>system\nYour name is Laura. You answer every question exclusively in Portuguese. You are a helpful assistant.<|im_end|>\n<|im_start|>user\nHi! My name is Mario. What are the top 3 questions you are mostly asked around here?<|im_end|>\n<|im_start|>assistant\n"
```
Produced this answer (exactly the same as chat):
```
"Olá, Mario! Como assistente, eu não tenho uma lista específica de perguntas mais comuns que recebo. No entanto, posso ajudar com uma variedade de tópicos, desde respostas gerais até informações mais técnicas. Se você tiver alguma dúvida em particular ou precisar de ajuda com um tópico específico, sinta-se à vontade para perguntar!"
```

My experiments point towards => `chat(thread) == generate(apply_template(thread), raw=false)`

It is a bit hard to tell with certainty only from this test if this confirms the hypothesis because there could be something else going on and maybe
this specific case we could have got a false representation of the result.
But so far from what I've been learning and all the other experiments I've made this is the assumption I am making while proceeding until I find something else to contradict me.

**Comment by malteneuss** [comment]
I found a helpful Youtube video by Matt Williams that discusses the difference: https://www.youtube.com/watch?v=kaK3ye8rczA It basically comes down to convenience. For one-off questions you would use the `/api/generate` endpoint for quick results. For back-and-forth (like in a real conversation with a chatbot), you would use the `/api/chat` endpoint. Although you can also use the chat endpoint for one-off questions to fake previous responses in the "assistant" role like in https://github.com/technovangelist/videoprojects/blob/e0eee85d67b3cf8d885d472980b03b3e819ef8c3/2024-02-15-functioncalling/fc.py#L30 to inject some examples. Apparently some models better then understand what they should produce for the their actual response.

**Comment by iguatemigarin** [comment]
You can have the exact same behaviour as the chat endpoint in the generate endpoint.

The generate endpoint returns a `context` property, which is an array of tokens/embeddings. If you call generate and give this context back, the model will take the context in consideration.

The big deal that I see here is the possibility to very easily use the context with different agents.

Here's a quick demo with llama3.1: https://iguatemigarin.github.io/my-chat/

On the right side, I put the chat interactions. On the left, a summary of the conversation.

Both the chat and summary can be considered different agents, have different system prompts, but share the same context. And only the chat agent can update the context.

Of course, this is achievable with the chat endpoint as well. But I think the context array is easier to babysit than a chat in this specific case.

The downside is that you can not "edit" the messages, which is super handy when you want to force the model to behave in a specific way.

**Comment by Propfend** [comment]
Thanks for the responses!!
