### ISSUE TITLE
Request: change the default sha256 hash file seperator for blobs to - (minus) instead of : 

### ISSUE THREAD

**Issue by LumiWasTaken** [ollama/ollama#2777]
Heya,
I have a setup where I'd like to use two systems, one testing on Windows and one active on Linux use the same path for model and manifest to save storage.
The issue I have is: Linux deployment creates blob files with the name `sha256:SHATHATHASBEENGENERATED` and on Windows  `sha256-SHATHATHASBEENGENERATED` this makes their filenames incompatible with each other and troublesome on Windows since any file with a : inside it is considered "non-existent"

Desired resolution:
A Patch where it'll be backwards-compatible with files that have `:` but the new default to be `-` so it will even work when the storage is on a NTFS or exFAT file system.

Thank you!

**Comment by dhiltgen** [comment]
Let's track this separator cleanup via #2032
