### ISSUE TITLE
error : embedding models do not support chat

### ISSUE THREAD

**Issue by nicho2** [ollama/ollama#2778]
i'm trying  to run :  ollama run nomic-embed-text

and the response to the command is :  error : embedding models do not support chat

ollama version is 0.1.27 on linux ubuntu

what to do?

**Comment by wrapss** [comment]
vous utilisez bien l'endpoint "embeddings" ?

**Comment by wrapss** [comment]
but what's the problem with anythingLLM? your first message is normal you can't run an embeddings model with ollama's cli

**Comment by nicho2** [comment]
ok, i've understand what to do
I was misled by the command given on the ollama site: ollama run nomic-embed-text

![image](https://github.com/ollama/ollama/assets/11471811/d2b66b38-52bc-4a83-a9d9-b41c73e6d772)

**Comment by easp** [comment]
Ah, yeah, the library isn't aware of embedding-only models.

**Comment by wallartup** [comment]
@nicho2 getting the same error, also want to use with Anything.

How did you fix it ?

**Comment by easp** [comment]
@wallartup embedding-specific models **can't** be used for chat.

**Comment by nicho2** [comment]
It's not necessary to run (just pull the model and :


![image](https://github.com/ollama/ollama/assets/11471811/7030b3c5-c5cd-4ba8-92f1-d5dcf3955d2b)

**Comment by jmorganca** [comment]
Hi, sorry this was misleading on ollama.com – it should show `ollama pull <embedding model>` now! To use the embeddings models you'll need to call the `/api/embeddings` endpoint: https://github.com/ollama/ollama/blob/main/docs/api.md#generate-embeddings

**Comment by vysecurity** [comment]
Getting this error:

![AnythingLLM-2024-03-21 at 18 21 51@2x](https://github.com/ollama/ollama/assets/3596242/cb3f89c5-9024-44e8-a773-254e302f1987)




![AnythingLLM-2024-03-21 at 18 22 06@2x](https://github.com/ollama/ollama/assets/3596242/4f8ed4a8-9116-4a2a-abec-dd36c5ad4d69)

**Comment by wrapss** [comment]
> Getting this error:
> 

not sure if ollama is the problem here, the message from your vector database

**Comment by vysecurity** [comment]
That’s what I thought but when I swap it to not use ollama for embedding it works

**Comment by ZiHAO-LI-cmd** [comment]
> Getting this error:
> 
> ![AnythingLLM-2024-03-21 at 18 21 51@2x](https://private-user-images.githubusercontent.com/3596242/315249346-cb3f89c5-9024-44e8-a773-254e302f1987.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI5MDU2NzksIm5iZiI6MTcxMjkwNTM3OSwicGF0aCI6Ii8zNTk2MjQyLzMxNTI0OTM0Ni1jYjNmODljNS05MDI0LTQ0ZTgtYTc3My0yNTRlMzAyZjE5ODcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQxMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MTJUMDcwMjU5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZWY0YWJiMmYzYzg3MTE1YzcxZWQ2MTA1ZTA0MThiMjgyNjhmYjkxYWRmOWJkMWMwMGUzMmUxMmEyNTQ2ODgwNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.kZ4R5h2gND0wHWHl2EHq7qhekUcOcz5gt3EPB3AuLbc)
> 
> ![AnythingLLM-2024-03-21 at 18 22 06@2x](https://private-user-images.githubusercontent.com/3596242/315249404-4f8ed4a8-9116-4a2a-abec-dd36c5ad4d69.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI5MDU2NzksIm5iZiI6MTcxMjkwNTM3OSwicGF0aCI6Ii8zNTk2MjQyLzMxNTI0OTQwNC00ZjhlZDRhOC05MTE2LTRhMmEtYWJlYy1kZDM2YzVhZDRkNjkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQxMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MTJUMDcwMjU5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZGM3NWU0OTUxOWUyMGNlMmE5OGFiODNmYWE1NzY1YjhjYTZkNmIzYjQ4ZDg3NjhhODQzZDZiMWNiY2JhMzAxMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.a_0koiNp_EIbiY0TNpQsZO-y1h3ZMdwQLUPgoRJT9XU)

Hi, I also met the problem. Do you know how to solve it?
