### ISSUE TITLE
Feature request: Additional Console Outputs for more efficient logging and debugging

### ISSUE THREAD

**Issue by LumiWasTaken** [ollama/ollama#2779]
Heya, i have the common issue that for example when using LLAVA 34b on a small-ish GPU with CPU offloading it sometimes gets stuck.
I can't really trace the issue anywhere, is it the BLAST Batch Processing, is it a OOM error, what is it?

```
key clip.vision.image_grid_pinpoints not found in file
key clip.vision.mm_patch_merge_type not found in file
key clip.vision.image_crop_resolution not found in file
```
Is the most i can get out of a log but that's about it... no metrics, no nothing :/

**Comment by dhiltgen** [comment]
It's possible this might be an OOM problem...

If you're still hitting this, please make sure to upgrade to the latest version, and share a bit more details about your setup.  What is your GPU size?  Server logs may help diagnose it as well.
