### ISSUE TITLE
Why the Gemma performs that bad with some simple questions?

### ISSUE THREAD

**Issue by brightzheng100** [ollama/ollama#2782]
Just tried `Gemma` model but not sure why it performed that bad.

```sh
ollama pull gemma:2b
ollama run gemma:2b
```

**So is it the model issue or the model hosted here is different?**

For example - this should be a common-sense question but it has no idea:
```
>>> Do you think whether human can fly? Tell me why with step-by-step reasoning.
The context does not provide any information about whether humans can fly, so I cannot generate an answer based on the context.
```

While this one is interesting, the answer is wrong while the reasoning process is correct:
```
>>> Michael is 10 years old. Rob is 2 years older than Amy, while Amy is 5 years younger than Michael. How old is Rob?
Rob is 12 years old.

We know that Amy is 5 years younger than Michael, so she is 5 - 10 = 5 years old. Since Rob is 2 years older than Amy, he is 5 + 2 = 7 years old.
```
![ollama](https://github.com/ollama/ollama/assets/1422425/8dd16e62-1caf-4356-b23f-d1820c883124)

**Comment by furquanh** [comment]
This a 2b parameter model. I don't see a use case for chatting with it. Maybe you could perform very basic logical reasoning task with it.

**Comment by elmoBG8** [comment]
> Just tried `Gemma` model but not sure why it performed that bad.
> 
> ```shell
> ollama pull gemma:2b
> ollama run gemma:2b
> ```
> 
> **So is it the model issue or the model hosted here is different?**
> 
> For example - this should be a common-sense question but it has no idea:
> 
> ```
> >>> Do you think whether human can fly? Tell me why with step-by-step reasoning.
> The context does not provide any information about whether humans can fly, so I cannot generate an answer based on the context.
> ```
> 
> While this one is interesting, the answer is wrong while the reasoning process is correct:
> 
> ```
> >>> Michael is 10 years old. Rob is 2 years older than Amy, while Amy is 5 years younger than Michael. How old is Rob?
> Rob is 12 years old.
> 
> We know that Amy is 5 years younger than Michael, so she is 5 - 10 = 5 years old. Since Rob is 2 years older than Amy, he is 5 + 2 = 7 years old.
> ```
> 
> ![ollama](https://private-user-images.githubusercontent.com/1422425/308213304-8dd16e62-1caf-4356-b23f-d1820c883124.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkwNjk1MzIsIm5iZiI6MTcwOTA2OTIzMiwicGF0aCI6Ii8xNDIyNDI1LzMwODIxMzMwNC04ZGQxNmU2Mi0xY2FmLTQzNTYtYjIzZi1kMTgyMGM4ODMxMjQuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIyNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMjdUMjEyNzEyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NGNmNmIyYzZmY2U2ZTU4NDNmNzRiZmQ3ZjMxNmZjNzA0NDJmODFmZmNjZWQ2NjUwNmJlMzA2OTE5NGUxMjY1YiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.adMScMHFrbJM86ub8pVkVQNwtSbELK4BxItGtNY6UD4) [ ![ollama](https://private-user-images.githubusercontent.com/1422425/308213304-8dd16e62-1caf-4356-b23f-d1820c883124.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkwNjk1MzIsIm5iZiI6MTcwOTA2OTIzMiwicGF0aCI6Ii8xNDIyNDI1LzMwODIxMzMwNC04ZGQxNmU2Mi0xY2FmLTQzNTYtYjIzZi1kMTgyMGM4ODMxMjQuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIyNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMjdUMjEyNzEyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NGNmNmIyYzZmY2U2ZTU4NDNmNzRiZmQ3ZjMxNmZjNzA0NDJmODFmZmNjZWQ2NjUwNmJlMzA2OTE5NGUxMjY1YiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.adMScMHFrbJM86ub8pVkVQNwtSbELK4BxItGtNY6UD4) ](https://private-user-images.githubusercontent.com/1422425/308213304-8dd16e62-1caf-4356-b23f-d1820c883124.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkwNjk1MzIsIm5iZiI6MTcwOTA2OTIzMiwicGF0aCI6Ii8xNDIyNDI1LzMwODIxMzMwNC04ZGQxNmU2Mi0xY2FmLTQzNTYtYjIzZi1kMTgyMGM4ODMxMjQuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIyNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMjdUMjEyNzEyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NGNmNmIyYzZmY2U2ZTU4NDNmNzRiZmQ3ZjMxNmZjNzA0NDJmODFmZmNjZWQ2NjUwNmJlMzA2OTE5NGUxMjY1YiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.adMScMHFrbJM86ub8pVkVQNwtSbELK4BxItGtNY6UD4) [ ](https://private-user-images.githubusercontent.com/1422425/308213304-8dd16e62-1caf-4356-b23f-d1820c883124.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkwNjk1MzIsIm5iZiI6MTcwOTA2OTIzMiwicGF0aCI6Ii8xNDIyNDI1LzMwODIxMzMwNC04ZGQxNmU2Mi0xY2FmLTQzNTYtYjIzZi1kMTgyMGM4ODMxMjQuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIyNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMjdUMjEyNzEyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NGNmNmIyYzZmY2U2ZTU4NDNmNzRiZmQ3ZjMxNmZjNzA0NDJmODFmZmNjZWQ2NjUwNmJlMzA2OTE5NGUxMjY1YiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.adMScMHFrbJM86ub8pVkVQNwtSbELK4BxItGtNY6UD4)

You're not the only one experimenting very bad answers from Gemma... Watch the end of this post: https://didyouknowbg8.wordpress.com/2024/02/27/testing-some-large-language-model-locally-with-ollama/ 
It's astonishing how bad it performs (both models: 2b and 7b) in comparison with the other open source models...

**Comment by gl-prout** [comment]
I have tried using gemma 2b and 7b (the ones that you pull using `ollama pull`), using ollama with docker.

And every time I try to call the model (using API, using Open-WebUI), it crashes the ollama docker, making it restart

**Comment by jmorganca** [comment]
2b can have differing results given it's small size although I'm impressed by it. You may want to try using 7B – let me know if that helps!
