### ISSUE TITLE
Ollama will run in CPU-only mode.

### ISSUE THREAD

**Issue by Code-With-Abhishek-Kumar** [ollama/ollama#2784]
WARNING: No NVIDIA GPU detected. Ollama will run in CPU-only mode.

**Comment by Anirudh257** [comment]
Can you specify more details about your configuration? It runs with the GPU mode.

**Comment by dhiltgen** [comment]
If you're still having problems, please upgrade to the latest release and share your server log so we can see more details.

https://github.com/ollama/ollama/blob/main/docs/troubleshooting.md
