### ISSUE TITLE
Application can't be opened. Macbook Pro - CPU - M1Pro

### ISSUE THREAD

**Issue by NVBCWT** [ollama/ollama#2786]

**Comment by easp** [comment]
What happens when you try to open it?  Does an icon show up in your menu bar?  What happens if you open a terminal window and run `ollama --version`?

**Comment by NVBCWT** [comment]
A small window pops up which normally pops up whenever any error is encountered in apple. The message displayed is - this app can't be opened

From the terminal it doesn't recognize ollama when after dropping ollama in application folder 

M1pro with 32 GB ram

**Comment by NVBCWT** [comment]
macOs - sonoma 14.3.1

**Comment by NVBCWT** [comment]
It was ollama.zip. However after recent update of OS, it works now
