### ISSUE TITLE
bug? - session save does not save latest messages of the chat

### ISSUE THREAD

**Issue by FotisK** [ollama/ollama#2787]
I was having a very long conversation with nollama/mythomax-l2-13b:Q5_K_S, saved the session and restored it and found that the latest 100-200 lines of the discussion were missing. I haven't tried to reproduce it (I don't have lengthy chats often), but I thought I'd report it. When I get another chance, I'll test it again

**Comment by pdevine** [comment]
This seems to be working correctly. I tried it out with several hundred lines of text. There were some changes to modelfile parser recently which may have fixed whatever underlying issue may have existed. I'll go ahead and close the issue.
