### ISSUE TITLE
Function calling with OpenAI API

### ISSUE THREAD

**Issue by joecryptotoo** [ollama/ollama#2790]
https://ollama.com/joefamous/firefunction-v1

https://platform.openai.com/docs/guides/function-calling

**Comment by grigio** [comment]
There is also functionary

https://github.com/MeetKai/functionary?tab=readme-ov-file#the-differences-between-related-projects

**Comment by Benjoyo** [comment]
And now also Hermes Pro:

https://huggingface.co/NousResearch/Hermes-2-Pro-Mistral-7B

we need a generic function calling capability with grammar sampling. Llama cpp python has this for funtionary.

**Comment by jmorganca** [comment]
Hi there, support for tool/function calling has been added! https://ollama.com/blog/tool-support
