### ISSUE TITLE
Determining Server Capacity for Hosting Ollama

### ISSUE THREAD

**Issue by juned-adenwalla** [ollama/ollama#2793]
I have a VPS server with 48GB RAM and a 12-core processor. I'm planning to host Ollama on it and develop a custom web app using Ollama's API. I'm curious about how many users my server will be able to handle simultaneously and how I can test the load balancing.

Could anyone suggest an approximate number of users my current server configuration can handle? Additionally, any guidance on testing the load balancing would be greatly appreciated.

**Comment by easp** [comment]
Ollama doesn't load balance requests. It processes each request serially in the order received. 

Beyond that, CPU inference is generally quite slow for all but the smallest models. If you want to know how fast it will be, install ollama and `ollama run mixtral "why is the sky blue" --verbose`  It'll print out the speed for prompt processing and text generation.

**Comment by juned-adenwalla** [comment]
total duration:       1m5.52821173s
load duration:        1.368387941s
prompt eval count:    25 token(s)
prompt eval duration: 2.376201s
prompt eval rate:     10.52 tokens/s
eval count:           367 token(s)
eval duration:        1m1.782406s
eval rate:            5.94 tokens/s

I got this as an output, can you give me a general understand say if I install this on cloud and give it to my team how many people will be able to use it parallel.

**Comment by jmorganca** [comment]
As @easp mentioned it's hard to estimate, however, this will get easier with new parallel requests as an upcoming feature. Stay tuned!

For a CPU server and a small model, it should handle at least a few clients at a time.
