### ISSUE TITLE
Window version not fully utilize gpu

### ISSUE THREAD

**Issue by Kaspur2012** [ollama/ollama#2794]
hello,

Window preview version
model used : mistral:7b-instruct-v0.2-q8_0
gpu: 2070 super 8gb

Issue: 
Recently I switch from lm studio to ollama and noticed that my gpu never get above 50% usage while my cpu is always over 50%.

I've used the same model in lm studio w.o any problems as in gpu mostly above 90%. Using ollama, the model seem to load fully into vram as it took almost all of my vram like lm studio but the gpu usage is never above 50% while the rest seem to go to cpu like it offloading some layers to cpu. I know that lm studio has an option of how much you can offload to gpu which I set to max but no idea about ollama.

I saw a similar post about this and the final conclusion was antivirus quarantined some of ollama. I disabled my AV completely and still same result. I also add ollama directory to exception list in AV

thanks

**Comment by easp** [comment]
Check the Ollama logs to see how many layers it's offloading to GPU. 
What are the GPU buffer allocations it reports?
https://github.com/ollama/ollama/blob/main/docs/troubleshooting.md#how-to-troubleshoot-issues

Finally, is your GPU card dedicated to inference, or is it also being used for display?

**Comment by Kaspur2012** [comment]
found these in the log:

llm_load_tensors: offloading 26 repeating layers to GPU
llm_load_tensors: offloaded 26/33 layers to GPU
llm_load_tensors:        CPU buffer size =  7338.64 MiB
llm_load_tensors:      CUDA0 buffer size =  5746.81 MiB

looks like it offloading 26/33 to gpu and the rest to cpu. I guess that why the gpu is not going full speed cause of the cpu bottleneck. This gpu is use for display as well though no idea why I can offload everything to gpu using lm studio and have almost 100% gpu utilization.

At least the log clarifies why the gpu is only working partially. I'll try loading a smaller model and see if it fully utilize the gpu. 

Odd still is that when loading this model, my gpu vram is filled up the same amount vs lm studio loading the same model and lm studio is not offloading any layers to cpu.

**Comment by dhiltgen** [comment]
@Kaspur2012 how many layers are you able to successfully load under LM Studio?

**Comment by dhiltgen** [comment]
Most likely this is the result of our memory prediction logic being a bit more conservative right now, and leaving some VRAM unallocated, so less layers are loading.  We're working on improvements which should result in more fully utilizing the VRAM, and loading more layers, which should be available in a week or two.

**Comment by steak3** [comment]
> Most likely this is the result of our memory prediction logic being a bit more conservative right now, and leaving some VRAM unallocated, so less layers are loading. We're working on improvements which should result in more fully utilizing the VRAM, and loading more layers, which should be available in a week or two.

I'm really expecting this. As an addition, wouldn't be a good idea allowing the users to manually set the number of layers ? This could be a first and quicker step before prediction

**Comment by Vitorbnc** [comment]
> > Most likely this is the result of our memory prediction logic being a bit more conservative right now, and leaving some VRAM unallocated, so less layers are loading. We're working on improvements which should result in more fully utilizing the VRAM, and loading more layers, which should be available in a week or two.
> 
> I'm really expecting this. As an addition, wouldn't be a good idea allowing the users to manually set the number of layers ? This could be a first and quicker step before prediction
> 
> [EDIT] Just found the OLLAMA_MAX_VRAM parameter. Is it the answer ? #835

Had the same problem, setting that to my GPU VRAM did it for me. If you set more than that it will use the GPU 100% (I tested setting 12GB, have 6GB VRAM), but won't improve performance (at least for me).

**Comment by dhiltgen** [comment]
Please give 0.1.33 a try.  We've continued to improve our prediction logic to try to maximize VRAM usage without OOMs.

@steak3 you can also specify `num_gpu` in the request to force a specific number of layers, but our goal is to get this right automatically for you.

**Comment by jmorganca** [comment]
Hi @Kaspur2012 thanks for the issue and sorry for the hiccups. 0.1.33 and 0.1.34 should have improvements here – let us know if it's still happening!
