### ISSUE TITLE
Please update Llama.cpp Server. It now Supports Llava 1.6 Image Embedding Dimension properly.

### ISSUE THREAD

**Issue by chigkim** [ollama/ollama#2795]
Last week [pr/5553](https://github.com/ggerganov/llama.cpp/pull/5553) was merged into Llama.cpp, and Llama.cpp server now supports llava 1.6 image embedding dimension properly.
This improves the accuracy greatly, and processes images in 4x larger dimension.
Could you guys update?
Thanks!

**Comment by jmorganca** [comment]
This should be fixed now. Thanks for the issue!

**Comment by chigkim** [comment]
Thanks!

Could you also merge this?

https://github.com/ggerganov/llama.cpp/pull/5896

Right now Ollama reports prompt with image as 0 token when accessing with api.

Should I create it a separate issue?

**Comment by chigkim** [comment]
I just created a new issue for it.
https://github.com/ollama/ollama/issues/3671
