### ISSUE TITLE
error loading model 

### ISSUE THREAD

**Issue by hotsmile** [ollama/ollama#2796]
i just pull gemma,  use the ollama to run it ,but i got the error
ollama pull gemma
pulling manifest 
pulling 456402914e83... 100% ▕███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏ 5.2 GB                         
pulling 097a36493f71... 100% ▕███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏ 8.4 KB                         
pulling 109037bec39c... 100% ▕███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏  136 B                         
pulling 22a838ceb7fb... 100% ▕███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏   84 B                         
pulling a443857c4317... 100% ▕███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏  483 B                         
verifying sha256 digest 
writing manifest 
removing any unused layers 
success 
(myenv) [root@rocky9 ~]# ollama list
NAME          	ID          	SIZE  	MODIFIED     
gemma:latest  	430ed3535049	5.2 GB	15 hours ago	
mistral:latest	61e88e884507	4.1 GB	4 weeks ago 	
(myenv) [root@rocky9 ~]# ollama run gemma:latest
Error: error loading model /usr/share/ollama/.ollama/models/blobs/sha256:456402914e838a953e0cf80caa6adbe75383d9e63584a964f504a7bbb8f7a

ollama -v
ollama version is 0.1.20
(myenv) [root@rocky9 ~]#

**Comment by skwolvie** [comment]
Check the sha256 file name used while loading, and the actual file name. For some reason, the loader is taking a fixed content length of the actual file name. Maybe that is leading to this error. 

Any possible fix?

**Comment by hubblebubblepig** [comment]
ollama server.log-->
"llama_model_load: error loading model: error loading model vocabulary: cannot find tokenizer merges in model file"
"Failed to load dynamic library"

**Comment by pdevine** [comment]
You'll need to upgrade to a newer version of ollama to make gemma work correctly. Gemma requires at least 0.1.26.

**Comment by markelzhang** [comment]
I've encountered this error too, but after restarting my computer, it works.

**Comment by Kota1609** [comment]
im using mac, i just uninstalled and installed ollama app again and it worked.

**Comment by akshaypatwa** [comment]
I had this same issue, it worked after updating ollama to newer version.
