### ISSUE TITLE
尝试通过HTTP协议向本地主机的11434端口发送POST请求时，连接被远程主机强制关闭

### ISSUE THREAD

**Issue by dandandujie** [ollama/ollama#2799]
当我在windows终端运行ollama的模型时，打开聊天界面后问问题，它就会返回Error: Post "http://127.0.0.1:11434/api/chat": read tcp 127.0.0.1:51305->127.0.0.1:11434: wsarecv: An existing connection was forcibly closed by the remote host.我现在已经开放了11434和51305端口，问题没有解决，请问怎么办。下面是截图：
![image](https://github.com/ollama/ollama/assets/142396650/a113077c-bf19-409e-bc76-bfc03c9af5b1)

**Comment by palfan23** [comment]
restart，重启下试试

**Comment by dhiltgen** [comment]
Please upgrade to the latest release 0.1.33 and if you're still seeing problems, please share the server log.

https://github.com/ollama/ollama/blob/main/docs/troubleshooting.md
