### ISSUE TITLE
Port should be changeable

### ISSUE THREAD

**Issue by pankajkumar229** [ollama/ollama#2801]
I could not change the port Ollama listens on. I hope we can run multiple instances on different ports.

**Comment by aiseei** [comment]
u can use multiple ports using smthing like this..

 OLLAMA_HOST=10.1.0.1:114XX OLLAMA_MODELS={PATH} OLLAMA_DEBUG=1  ollama serve

**Comment by pdevine** [comment]
Going to close the issue.

**Comment by songsh** [comment]
OLLAMA_MODELS={PATH}  where to find model path   ?
