### ISSUE TITLE
How do we publicly show our model in the library?

### ISSUE THREAD

**Issue by WangRongsheng** [ollama/ollama#2806]
We created a model - [Aurora](https://ollama.com/wangrongsheng/aurora), which is a fine-tuned Mixtral-8X7B model with bilingual (chinese and english) dialog. But we can't search for it in the library.

![image](https://github.com/ollama/ollama/assets/55651568/4c3d3cf4-d386-46de-adc7-03330e62b636)

**Comment by renillhuang** [comment]
I got same issue, not sure how to add library into library list.
For personal uploaded library, the full name of the model is **"<username>/<model_name>"**

**Comment by WangRongsheng** [comment]
![image](https://github.com/ollama/ollama/assets/55651568/a3007f96-1d45-4731-b9d3-40277dc6c9e9)

This search box is buggy, please don't use it!
