### ISSUE TITLE
[Windows] Ollama api/chat seems to not receive all chats all the time

### ISSUE THREAD

**Issue by stevengans** [ollama/ollama#2807]
Still investigating. Will put together a way to replicate and add it here. From quick experiments, it sometimes gets the chats and sometimes does not. This does not happen on Mac with same system.

**Comment by dhiltgen** [comment]
If you're still hitting this, please make sure to upgrade, and if that doesn't clear it up, share a bit more information about your setup, and how to reproduce and I'll reopen the issue.
