### ISSUE TITLE
Mistral Instruct models prompt does not use <s> or </s>

### ISSUE THREAD

**Issue by louisabraham** [ollama/ollama#2811]
from https://huggingface.co/mistralai/Mixtral-8x7B-Instruct-v0.1#instruction-format 

> \<s> [INST] Instruction [/INST] Model answer\</s> [INST] Follow-up instruction [/INST]

I didn't see `<s>` as part of the prompt when using `OLLAMA_DEBUG=1 ollama start`. Is that expected?

**Comment by jukofyork** [comment]
> from https://huggingface.co/mistralai/Mixtral-8x7B-Instruct-v0.1#instruction-format
> 
> > <s> [INST] Instruction [/INST] Model answer</s> [INST] Follow-up instruction [/INST]
> 
> I didn't see `<s>` as part of the prompt when using `OLLAMA_DEBUG=1 ollama start`. Is that expected?

I think `llama.cpp` adds the opening `<s>`.

**Comment by BruceMacD** [comment]
Hi @louisabraham thanks for your questions. The llama.cpp library will add a `bos` (`<s>`) token to the incoming prompt. As far as I'm aware `[INST]`-style  prompt templates optionally have bos/eos tokens on each turn, but will still function with out them. If people find the models are harder to steer without this tokens please let me know, and it can be added to the default template.

reference: https://github.com/ggerganov/llama.cpp/blob/652ca2bded3c818320d92c70d2b67f64bdbff5e5/llama.cpp#L13418

**Comment by louisabraham** [comment]
@BruceMacD thank you for your answer! Do you think the ollama calls llama.cpp with that function? It would be weird as we use much more complex templates than what this heuristic function supports.

**Comment by pdevine** [comment]
@louisabraham you can always use the `/api/generate` endpoint w/ `raw` mode set to true in order to specify the full prompt with your own template.

I'm going to go ahead and close the issue, but we can reopen it if the answer wasn't clear.
