### ISSUE TITLE
Cannot use Ollama at all on Windows

### ISSUE THREAD

**Issue by TheWonderfulTartiflette** [ollama/ollama#2814]
On Windows, with the preview build, I installed Ollama, but as soon as I entered “ollama run llama2”, I got this:
Error: max retries exceeded: 400: <?xml version="1.0” encoding="UTF-8”?><Error><Code>InvalidArgument</Code><Message>Invalid Argument: range must be positive.</Message></Error>
Not sure what to do about this

**Comment by pdevine** [comment]
Can you try again? We had a brief outage yesterday where non-authenticated clients weren't pulling correctly.

**Comment by dhiltgen** [comment]
This should be resolved now.  If you're still having problems, please let us know and I'll re-open the issue.
