### ISSUE TITLE
Adding Whisper by creating Modelfile

### ISSUE THREAD

**Issue by serban-razvan-termene** [ollama/ollama#2815]
Ollama uses a format for the Modelfile that is described [here](https://github.com/ollama/ollama/blob/main/docs/modelfile.md). The Modelfile allows only for text input to be put into the resulting model.

There is one multimodal model (LLaVA) that you guys added to the model hub that uses something else other than text. But some modifications to the Ollama and the model [were done](https://github.com/ollama/ollama/issues/746). As far as I understand, the model takes the encoded image as a text parameter.

Is there any possibility for me to write a Modelfile and modify the base repository for Ollama to take audio as input for the Whisper model that takes audio as the input and outputs the text heard in that audio?

**Comment by jmorganca** [comment]
Hi @serban-razvan-termene love this idea, however not yet since Ollama doesn't support audio models yet. I'll merge this with #1168
