### ISSUE TITLE
Ubuntu install not ending

### ISSUE THREAD

**Issue by Fastidious** [ollama/ollama#2816]
Trying to install ollama on Ubuntu 23.04, it gets stuck like this:

```bash
>>> Downloading ollama...
######################################################################## 100.0%##O#-#
>>> Installing ollama to /usr/local/bin...
>>> Adding ollama user to render group...
>>> Adding current user to ollama group...
>>> Creating ollama systemd service...
>>> Enabling and starting ollama service...
Network interfaces          
```

What could it be?

**Comment by dhiltgen** [comment]
Can you try running with `-x` so we can see what it's trying to do when it gets stuck?
```
curl -fsSL https://ollama.com/install.sh | sh -x
```

**Comment by dhiltgen** [comment]
If you're still having trouble installing, please share a little more information so we can investigate.

**Comment by hsiktas** [comment]
I am seeing the same issue and this is where it hangs when I start the installer with `-x`:

```
>>> Creating ollama systemd service...
+ cat
+ sudo tee /etc/systemd/system/ollama.service
+ systemctl is-system-running
+ SYSTEMCTL_RUNNING=running
+ status Enabling and starting ollama service...
+ echo >>> Enabling and starting ollama service...
>>> Enabling and starting ollama service...
+ sudo systemctl daemon-reload
+ sudo systemctl enable ollama
+ trap start_service EXIT
+ available lspci
+ command -v lspci
+ check_gpu nvidia-smi
+ available nvidia-smi
+ command -v nvidia-smi
+ return 1
+ check_gpu lspci nvidia
+ available lspci
+ command -v lspci
+ lspci -d 10de:
+ grep -q NVIDIA
+ return 1
+ check_gpu lshw nvidia
+ available lshw
+ command -v lshw
+ grep -q vendor: .* \[10DE\]
+ sudo lshw -c display -numeric
Network interfaces          

```

**Comment by dhiltgen** [comment]
@hsiktas does `sudo lshw` hang on your system as well?  We use that tool to discover the GPUs.

**Comment by hsiktas** [comment]
I just tried it and the command ran without hanging. The installer script finished successfully this time. So, I can't reproduce this anymore.
It might have been an issue with Ubuntu 23.10, but right now on 24.04 the issue seems to be gone. :)

**Comment by mirh** [comment]
Lshw's network scanning can hang forever inside of `scan_ip`, `scan_modes' or `scan_module`. 
In my case, /dev/vmnet1 has SIOCGIFADDR or SIOCETHTOOL operations hanging.
