### ISSUE TITLE
rocm crashes on `Illegal seek for GPU arch : gfx1032`

### ISSUE THREAD

**Issue by turlapati** [ollama/ollama#2823]
user@HTML:~$ ollama run gemma
Error: Post "http://127.0.0.1:11434/api/chat": EOF

...
[crash_0.1.27_gemma_rcom.txt](https://github.com/ollama/ollama/files/14441945/crash_0.1.27_gemma_rcom.txt)

loading library /tmp/ollama3347055972/rocm_v6/libext_server.so
time=2024-02-28T20:59:58.907-05:00 level=INFO source=dyn_ext_server.go:90 msg="Loading Dynamic llm server: /tmp/ollama3347055972/rocm_v6/libext_server.so"
time=2024-02-28T20:59:58.907-05:00 level=INFO source=dyn_ext_server.go:150 msg="Initializing llama server"

rocBLAS error: Cannot read /opt/rocm/lib/rocblas/library/TensileLibrary.dat: Illegal seek for GPU arch : gfx1032
free(): invalid pointer
SIGABRT: abort
PC=0x7fcc860969fc m=16 sigcode=18446744073709551610
signal arrived during cgo execution

**Comment by turlapati** [comment]
ROCm installed using instructions: https://rocm.docs.amd.com/projects/install-on-linux/en/latest/tutorial/quick-start.html#package-man-ubuntu

**Comment by pdevine** [comment]
cc @dhiltgen

**Comment by dhiltgen** [comment]
Unfortunately AMD has not released ROCm support for these GPUs.  https://rocm.docs.amd.com/projects/install-on-linux/en/latest/reference/system-requirements.html

We're working on improvements to detect this unsupported GPU scenario and gracefully fallback to CPU mode with a log message explaining why, and guidance on how you may be able to workaround this by forcing rocm to load a different version.

You may be able to get it working by setting `HSA_OVERRIDE_GFX_VERSION` to a supported version that's close, for example, `HSA_OVERRIDE_GFX_VERSION=10.3.0` may work for your GPU.

**Comment by turlapati** [comment]
Thanks for looking into the issue. Setting HSA_OVERRIDE_GFX_VERSION=10.3.0 allows Ollama to run properly, but I start to see my screen flickering (same as the issue: https://www.reddit.com/r/LocalLLaMA/comments/18nfwy5/screen_flickering_in_linux_when_offloading_layers/?rdt=46343)...
