### ISSUE TITLE
Running ollama on Hugging Face Spaces

### ISSUE THREAD

**Issue by jbdatascience** [ollama/ollama#2833]
I want to run ollama on Hugging Face Spaces, because I run a Streamlit app there that must make use of a LLM and a embedding model served by Ollama. How can I do that?

**Comment by Fastidious** [comment]
What do you mean "run ollama on Hugging Face Spaces"? Do you want to consume models available in Hugging Face Spaces (HFS)? Is that your aim? If so, then that's something not available out of the box in Ollama.

If you search The Tubes, you will find a few approaches to do so. The easiest way to use HFS models is by transforming models using GPT-Generated Unified Format (gguf). Not every model on HFS is a gguf model.

**Comment by jbdatascience** [comment]
> What do you mean "run ollama on Hugging Face Spaces"? Do you want to consume models available in Hugging Face Spaces (HFS)? Is that your aim? If so, then that's something not available out of the box in Ollama.
> 
> If you search The Tubes, you will find a few approaches to do so. The easiest way to use HFS models is by transforming models using GPT-Generated Unified Format (gguf). Not every model on HFS is a gguf model.

I gues you are right. Also I came to the conclusion that I oversaw the option of not using ollama in the first place! Just using a LLM model and an embedding model right from HF is the natural (and obvious!) way to go! 

My plan now is to modify the existing code to implement this.

thanks for your response!

**Comment by pdevine** [comment]
Hey @jbdatascience I think it's OK to close this? I think you could do it through Docker Spaces, but I'm not sure if that's the best way to do it as I'm not really familiar w/ Spaces. There are lots of other places to get GPU instances on the cloud where you can run Ollama.

**Comment by jbdatascience** [comment]
> Hey @jbdatascience I think it's OK to close this? I think you could do it through Docker Spaces, but I'm not sure if that's the best way to do it as I'm not really familiar w/ Spaces. There are lots of other places to get GPU instances on the cloud where you can run Ollama.

I am still searching for a solution!

**Comment by musarehmani291** [comment]
Hi @Fastidious and @pdevine 
I wanna deploy Ollama to Huggingface space. I used the official Dockerfile of the Ollama repo but it keeps building I could never get the space to running. I'm using the free version of Huggingface space. could you look into this issue?

**Comment by Amirjab21** [comment]
> > What do you mean "run ollama on Hugging Face Spaces"? Do you want to consume models available in Hugging Face Spaces (HFS)? Is that your aim? If so, then that's something not available out of the box in Ollama.
> > If you search The Tubes, you will find a few approaches to do so. The easiest way to use HFS models is by transforming models using GPT-Generated Unified Format (gguf). Not every model on HFS is a gguf model.
> 
> I gues you are right. Also I came to the conclusion that I oversaw the option of not using ollama in the first place! Just using a LLM model and an embedding model right from HF is the natural (and obvious!) way to go!
> 
> My plan now is to modify the existing code to implement this.
> 
> thanks for your response!

Did you manage to do this?

**Comment by myyim** [comment]
This solution works for me:
https://medium.com/p/1f5d8f871887

If you use an embedding model, when deploying the model on the client end, use "embed" instead of "generate".

For example,

curl http://localhost:11434/api/embed -d '{
  "model": "all-minilm",
  "input": "Why is the sky blue?"
}'
