### ISSUE TITLE
Plans for Ollama Go library?

### ISSUE THREAD

**Issue by eliben** [ollama/ollama#2840]
The Ollama team has recently released native client libraries for JS (https://github.com/ollama/ollama-js) and Python (https://github.com/ollama/ollama-python).

Are there plans to develop a similar native Go library?

**Comment by pdevine** [comment]
There is the one in `/api`, which is what we use for the REPL, but it's not as well commented as the python/js client libraries.

**Comment by eliben** [comment]
> There is the one in `/api`, which is what we use for the REPL, but it's not as well commented as the python/js client libraries.

Thanks for your reply @pdevine 
Do you intend to document it as an externally usable API? It's exported and hence appears at https://pkg.go.dev/github.com/jmorganca/ollama/api -- what other documentation would you envision it having? Happy to contribute PRs if that would help.

**Comment by pdevine** [comment]
I'd love to get it up to the same standard as the other two libraries. I think in terms of functionality it should be really close (we use it heavily internally), it's just that we haven't had time (or the people!). It'd be awesome if you wanted to take a look; you can just try to copy the documentation from the other libraries. If you want to ping me on the discord I can give more details.

**Comment by eliben** [comment]
SGTM, I'll look into it

**Comment by eliben** [comment]
@pdevine @jmorganca PTAL at #2878 and let me know if it's heading in the right direction

**Comment by eliben** [comment]
Similarly, https://github.com/ollama/ollama/pull/2879 starts adding examples in `examples/`

**Comment by eliben** [comment]
@pdevine @jmorganca friendly ping - please review #2878 and #2879 and LMK if this is the right direction to pursue.

**Comment by pdevine** [comment]
Thanks so much @eliben for those two PRs! I'll go ahead and close this guy. I'd still like to do an "official" go client at some point similar to js/python.
