### ISSUE TITLE
Official Desktop GUI app

### ISSUE THREAD

**Issue by trymeouteh** [ollama/ollama#2842]
Please consider making an official GUI app for Ollama that runs on Windows, MacOS and Linux.

The official GUI app will install Ollama CLU and Ollama GUI

The GUI will allow you to do what can be done with the Ollama CLI which is mostly managing models and configuring Ollama. Essentially making Ollama GUI a user friendly settings app for Ollama.

Or even perhaps a desktop and mobile GUI app written in Dart/Flutter?
https://github.com/ollama/ollama/issues/2843

**Comment by ddkwork** [comment]
could me try ?

https://github.com/cogentcore/core/discussions/821

**Comment by jmorganca** [comment]
Hi there! check out some of these awesome Desktop (and/or Web) apps that run great with Ollama: https://github.com/ollama/ollama?tab=readme-ov-file#web--desktop

**Comment by zaynekomichi** [comment]
Created one

**Comment by samraghul** [comment]
https://github.com/AugustDev/enchanted

Use this

**Comment by Ches-ctrl** [comment]
Using Enchanted for Mac - equivalent for windows? Want something with a download button to be able to show non-technical folks

**Comment by wisamidris77** [comment]
Use page page-assist extension so easy to install and use I'm using it until now or use webui (not recommend too slow)
https://github.com/n4ze3m/page-assist

**Comment by jae-jae** [comment]
Here's another option for an Ollama GUI desktop, with a beautifully designed interface: 

https://github.com/jae-jae/ollaman-releases
