### ISSUE TITLE
OpenAI package compatibility

### ISSUE THREAD

**Issue by eliranwong** [ollama/ollama#2844]
I read the example in https://ollama.com/blog/openai-compatibility

The example works, but it doesn't when I add "response_format={ "type": "json_object" },"

https://platform.openai.com/docs/guides/text-generation/json-mode

**Comment by eliranwong** [comment]
ok, I just found a workaround, by adding the following prefix in User message content:

Use template '{"answer": ""}' to answer:

**Comment by eliranwong** [comment]
I am happy enough with the workaround. many thanks.

**Comment by eliranwong** [comment]
By the way, the full workaround example that works is:

``` 
client = OpenAI( 
    base_url = 'http://localhost:11434/v1', 
    api_key='ollama', # required, but unused 
) 
 
response = client.chat.completions.create( 
  model="llama2", 
  response_format={ "type": "json_object" }, 
  messages=[ 
    {"role": "system", "content": "You are a helpful assistant."}, 
    {"role": "user", "content": "Who won the world series in 2020?"}, 
    {"role": "assistant", "content": "The LA Dodgers won in 2020."}, 
    {"role": "user", "content": """Use template '{"answer": ""}' to answer: Wher
e was it played?"""} 
  ] 
) 
print(response.choices[0].message.content) 
```

**Comment by jmorganca** [comment]
Hi there, thanks for opening an issue. If using `json_object`, it's very important to tell the model to answer in JSON, or it may get stuck generating a lot of whitespace (solving this separately with #2605). The OpenAI API behaves similarly although it will error if "answer in JSON" or similar isn't in the prompt. Let me know if you still see more issues!

**Comment by PhilipAmadasun** [comment]
@jmorganca I'll create an issue for this but at this time is it possible for developers to create API keys for access security using the openai API (with ollama for inference)?
