### ISSUE TITLE
not work in 1080ti gpu

### ISSUE THREAD

**Issue by basakamars** [ollama/ollama#2853]
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 551.61                 Driver Version: 551.61         CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                     TCC/WDDM  | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce GTX 1080 Ti   WDDM  |   00000000:04:00.0  On |                  N/A |
| 30%   23C    P2             56W /  250W |     286MiB /  11264MiB |      2%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+

+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI        PID   Type   Process name                              GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|

**not work in gpu, only run to cpu, why?**

**Comment by dhiltgen** [comment]
Can you share the server.log?

**Comment by schuetz85** [comment]
Which processor are you using?

**Comment by basakamars** [comment]
@schueszy 
My processor is Intel Xeon X5675.

**Comment by dhiltgen** [comment]
I believe this CPU lacks AVX, making this a dup of #2187

**Comment by basakamars** [comment]
Thank you! You're right processor is not support AVX.

**Comment by dhiltgen** [comment]
If possible, I'd recommend trying to use a CPU that does have at least AVX unless you know your model will completely fit into the GPU as we see ~4x improvement in speed between no-AVX and AVX.
