### ISSUE TITLE
CNCF TAG Runtime and/or Working Group AI Discussion/Presentation

### ISSUE THREAD

**Issue by rajaskakodkar** [ollama/ollama#2857]
Hello Ollama maintainers,

We at CNCF TAG Runtime which is the Technical Advisory Group for workload execution on cloud native infrastructure in the Cloud Native Computing Foundation are interested to explore the space of intersection between AI and cloud native technologies.

As the Tech Lead of [CNCF TAG Runtime](https://github.com/cncf/tag-runtime), I am reaching out to you to present/discuss Ollama at one of our meetings.

We have slots available on:
 - [the TAG Runtime biweekly meeting](https://docs.google.com/document/d/1k7VNetgbuDNyIs_87GLQRH2W5SLgjgOhB6pDyv89MYk/edit#heading=h.qvunylimkyic)
- [and the CNCF Working Group AI meeting](https://docs.google.com/document/d/1tS6gL5qjGLaHDtAChssqJhBVm8BIpopUA3Ddzm9LHwg/edit#heading=h.9f2t9chnw0yh)

It would be great to learn about the overview of ollama and get to know what lies on your roadmap. We would also be interested in knowing how AI can benefit Cloud Native and vice versa.

If you are interested, please feel free to add it to the agenda or reach out to us in the [#tag-runtime](https://slack.cncf.io/) channel on the CNCF slack.

Thanks!

cc: @raravena80 @nikhita

cc: @jmorganca if you or anyone else on the team are interested! :)

**Comment by pdevine** [comment]
Going to go ahead and close this. :-D

**Comment by raravena80** [comment]
There was no presentation yet.  Are you interested in presenting?  Ty!

**Comment by rajaskakodkar** [comment]
@pdevine we would love to have ollama present at TAG Runtime meeting. Please let us know if you need any help or have any interest to present
