### ISSUE TITLE
[Windows] How do I install the model onto a different drive instead of the C drive?

### ISSUE THREAD

**Issue by hanzhentao** [ollama/ollama#2859]

**Comment by amnweb** [comment]
Simple, go to Environment Variables and add **OLLAMA_MODELS** an **PATH**

![Screenshot 2024-03-01 121520](https://github.com/ollama/ollama/assets/16545063/a17791cc-35f4-4da8-af53-a8717df00348)


Or simple open terminal (powershell) and type

`[System.Environment]::SetEnvironmentVariable("OLLAMA_MODELS", "NEW_PATH" ,"User")`

**Comment by Gatts011** [comment]
This doesnt work for me, recreates folder at C:\Users\user\.ollama

**Comment by amnweb** [comment]
Yes .ollama folder is there but models is downloaded in defined location. Did you check Environment Variables settings if you used powershell command to check if OLLAMA_MODELS is there ?

In /Users/xxx/.ollama, this dir. contains some files like history and openssh keys as i can see on my PC, but models (big files) is downloaded on new location. Also I have reinstall windows 3 days ago and ollama is detected this models without downloading again.

![image](https://github.com/ollama/ollama/assets/16545063/fa624175-ff10-46dc-8a85-e19ffc9b8947)

**Comment by Gatts011** [comment]
Aaaaah yes, very good.

thank you!

**Comment by dhiltgen** [comment]
Sounds like this is resolved.  If you're still having trouble setting up the env vars please let us know.

**Comment by oscarbat** [comment]
'ollama' is not recognized as an internal or external command or operable program
or batch file.

**Comment by dhiltgen** [comment]
@oscarbat our installer adds the ollama executable to the PATH, but you'll need to start a new shell (powershell, cmd, others) after the install to pick that up.

**Comment by quqiufeng** [comment]
works for me,  thanks!

**Comment by tommarekCZE** [comment]
what about linux?

**Comment by dhiltgen** [comment]
@tommarekCZE we provide an install script which is opinionated on where it installs the linux binary, but you can adjust where the models are stored as described here https://github.com/ollama/ollama/blob/main/docs/faq.md#where-are-models-stored and we also make the binary itself available if you want ultimate control on where to place it and how to run it.

**Comment by jiuwenyu** [comment]
> This doesnt work for me, recreates folder at C:\Users\user.ollama

Set it up, restart and try again

**Comment by romanown** [comment]
i have add OLLAMA_MODELS an PATH and set newpath. but it alsoo downloaded on old path. i restarted terminal but it not usefull.

**Comment by ruirui2021** [comment]
my problem is that it seems docker can't find the new file location.
I run /ollama list/ in term, it can find the model , but when i open the openweb UI through docker it can't find any model.
plz help, thx.
