### ISSUE TITLE
How to copy the Modelstore to a different Ollama PC?

### ISSUE THREAD

**Issue by sthufnagl** [ollama/ollama#2860]
Hi,

I have the luxury situation that I own two PC with Ollama. Because it takes a long time to load large models from the internet...it would be nice to have the opportunity to copy the Modelstore from one Ollama PC to another Ollama PC.
The next challenge is...the target PC is Windows and the source PC is Ubuntu.
Even a solution from Ubuntu to Ubuntu would be great for me (a reason more to get rid of Windows)

Thanks in advance for a possible solution.

Steve

**Comment by zimeg** [comment]
Hey @sthufnagl 👋  I think the quickest way to do this is [SFTP for transferring the models over the network](https://superuser.com/a/414809) or maybe [`scp`](https://linuxize.com/post/how-to-use-scp-command-to-securely-transfer-files/#scp-command-syntax) between Linux machines?

A more creative solution using network attached storage might be possible too, to only keep one copy of these files!

**Comment by pdevine** [comment]
Here's an [FAQ](https://github.com/ollama/ollama/blob/main/docs/faq.md#where-are-models-stored) which describes where the models are stored. You can copy them there to the appropriate location on another system (even cross platform). Keep in mind that if you're going from Linux to Windows the filenames of the blobs may have to be changed due to Windows not supporting a `:` character in the filename.

I'm going to go ahead and close out the issue, but feel free to feel commenting.

**Comment by sthufnagl** [comment]
Thanks a lot for your answers!
:-)
**@zimeg:**
Great idea, I wounder if I could use a NFS (or SMB) Share for the modelstore and mount this to the other PC. But maybe loading  models over the network is slow? With a 2.5 Mbits Network loading a 7b Model? Hm?

**@pdevine:**
Especially the hint with the file name under windows is very important for me. I recognize some copy problems with the Blobs but I thought it was the filesize.

**Comment by boedyirh** [comment]
Similar situation here, 
I have two computers with different model each. Is it possible for me to copy only one model from computer A, and copy it to computer B.

**Comment by streetlife** [comment]
If both machines are on the same network, you can use SyncThing to keep them syncronized. Just map the c:\Users\Username\.ollama\models on both machines.

**Comment by pweibert** [comment]
On my machine A (Ubuntu24.04)  ollama models are located in `/var/snap/ollama/common/models`. I copied the models folder from my machine B (Ubuntu 22.04) using an external drive. After restarting ollama service `sudo systemctl restart snap.ollama.listener.service` I can see all the models.

**Comment by amiralizade2** [comment]
Copy Models Dire To another system.
macOS: ~/.ollama/models
Linux: /usr/share/ollama/.ollama/models
Windows: C:\Users\%username%\.ollama\models

It's work.
