### ISSUE TITLE
use the `/api/chat` API,always response empty content

### ISSUE THREAD

**Issue by NullpointerW** [ollama/ollama#2861]
request:
``` curl
curl --location 'http://localhost:11434/api/chat' \
--header 'Content-Type: application/json' \
--data '{
    "model": "gemma:7b-instruct-fp16",
    "message": [
        {
            "role": "user",
            "content": "why is the skyw blue?"
        }
    ]
}'
```
always  return:
``` json
{
    "model": "gemma:7b-instruct-fp16",
    "created_at": "2024-03-01T11:17:53.3907871Z",
    "message": {
        "role": "assistant",
        "content": ""
    },
    "done": true
}
```

**Comment by pdevine** [comment]
What type of system do you have? Also can you post the server logs? That particular model is pretty sizeable so requires a beefy system. Also check to make certain you're running Ollama 0.1.26 or later as gemma requires a newer version.

**Comment by pdevine** [comment]
I just realized it was because you used `message` vs. `messages`. Try:
```
% curl --location 'http://localhost:11434/api/chat' \
--header 'Content-Type: application/json' \
--data '{
    "model": "gemma:7b-instruct-fp16",
    "messages": [
        {
            "role": "user",
            "content": "why is the skyw blue?"
        }
    ]
}'
```

**Comment by pdevine** [comment]
I'm going to go ahead and close the issue. Hope this helps though!

**Comment by zamzx** [comment]
> I just realized it was because you used `message` vs. `messages`. Try:
> 
> ```
> % curl --location 'http://localhost:11434/api/chat' \
> --header 'Content-Type: application/json' \
> --data '{
>     "model": "gemma:7b-instruct-fp16",
>     "messages": [
>         {
>             "role": "user",
>             "content": "why is the skyw blue?"
>         }
>     ]
> }'
> ```

Yay! message vs messages got me! Now my first ollama scripting adventure is well underway. Thank you internet stranger! ^_^

**Comment by danydin** [comment]
> I just realized it was because you used `message` vs. `messages`. Try:
> 
> ```
> % curl --location 'http://localhost:11434/api/chat' \
> --header 'Content-Type: application/json' \
> --data '{
>     "model": "gemma:7b-instruct-fp16",
>     "messages": [
>         {
>             "role": "user",
>             "content": "why is the skyw blue?"
>         }
>     ]
> }'
> ```

haha gosh i had the same typo.. programming can be so annoying sometimes without even any error messages which makes it seems like it all went fine, why there was no error coming from requesting non existing key though..?
