### ISSUE TITLE
Ollama on Android

### ISSUE THREAD

**Issue by Alias4D** [ollama/ollama#2862]
# Ollama on Android
I Hobe to release ollama version for Android
Or aarch64 mobile device 😍

**Comment by jmorganca** [comment]
Hi there, there isn't an pre-built release of Ollama on Android, but do check out some clients on GitHub. Here's an example of one: https://github.com/lvnvceo/OllamaDroid

**Comment by Alias4D** [comment]
I mean serve ollama on Android by application or termux not client application
