### ISSUE TITLE
Read and write files (To allow for more types of AI models in Ollama)

### ISSUE THREAD

**Issue by trymeouteh** [ollama/ollama#2864]
To my understanding it will seem Ollama can only support text chat based models and to my understand it could support more kinds of models by adding a reading files and writing files feature...

- A way to have a model read one or more file on your system and be able to send it to the AI model to process.
- A way for the AI model to return a file, by generating a file (Writing a file) onto the system and them being able to link it into the chat response.

To my understanding, this can allow Ollama to work with more model types such as text to image models, image to image models, text to audio models, audio to text models, audio to audio models, etc.

**Comment by pdevine** [comment]
I'm realizing on rereading my response that I was not super clear. The API doesn't read the file per se, but you can pass images along in the request. In the API you can do that with:

```
curl http://localhost:11434/api/generate -d '{
  "model": "llama2",
  "prompt": "Why is the sky blue?",
  "images": [ ... <list of image data> ... ]
}'
```

Or you can do:
```
curl http://localhost:11434/api/chat -d '{
  "model": "llama2",
  "messages": [
    {
      "role": "user",
      "content": "why is the sky blue?",
      "images": [ ... <list of image data> ],
    }
  ]
}'
```

You can find more info in the [docs](https://github.com/ollama/ollama/blob/main/docs/api.md).

I'm going to go ahead and close the issue, but feel free to keep commenting, or ask away in the discord.
