### ISSUE TITLE
ollama serve run error

### ISSUE THREAD

**Issue by songsh** [ollama/ollama#2871]
when i run  ollama serve , error is:
Couldn't find '/home/wangbin/.ollama/id_ed25519'. Generating new private key.
Your new public key is: 
xxxxxxxxx
Error: listen tcp 127.0.0.1:11434: bind: address already in use

when i run npm run dev ,error is:
> chatbot-ollama@0.1.0 dev
> next dev

sh: 1: next: not found

**Comment by zimeg** [comment]
Hey @songsh! Are you trying to run the project at https://github.com/ivanfioravanti/chatbot-ollama? This error looks like you need to run `npm ci` before trying to `npm run dev`.

The port this runs on might also be taken by another process (maybe another Ollama server) but you can [change this with the `OLLAMA_HOST` variable](https://github.com/ollama/ollama/blob/main/docs/faq.md#how-can-i-expose-ollama-on-my-network).

**Comment by pdevine** [comment]
As @zimeg mentioned, you're already running an instance of ollama on port 11434. You shouldn't need to run a second copy of it.

**Comment by pdevine** [comment]
Are you running on Linux, Mac, or Windows? You'll need to change how `ollama serve` is being called when starting the server. There is a doc [here](https://github.com/ollama/ollama/blob/main/docs/faq.md#how-do-i-configure-ollama-server) which explains how to do that.

**Comment by songsh** [comment]
linux

**Comment by pdevine** [comment]
Use the docs [here](https://github.com/ollama/ollama/blob/main/docs/faq.md#setting-environment-variables-on-linux) to set the `OLLAMA_HOST` variable.

**Comment by songsh** [comment]
i found

**Comment by pdevine** [comment]
Going to close the issue. Feel free to keep commenting or reopen it.

**Comment by 17Reset** [comment]
When I change the server address for ollama, using the ollama list command on the command line brings up：
xxxl@xxx:~$ ollama list
Error: could not connect to ollama app, is it running?

**Comment by 17Reset** [comment]
But if I use ollama serve, he still starts an IP address of 127.0.0.1

**Comment by rlust** [comment]
Same issue, I set env variable to my local ip address but it does not allow connection on local ip address.
