### ISSUE TITLE
I dont want the systemd service.

### ISSUE THREAD

**Issue by donuts-are-good** [ollama/ollama#2872]
Title says it. I dont want this installer to set up a systemd service without asking. I use `ollama serve`, so the systemd service isn't something i need or want. Upgrading is a pain as a result.

`curl -fsSL https://ollama.com/install.sh | sh` <-- need a better way to update

**Comment by jmorganca** [comment]
Hi @donuts-are-good, we publish binaries with every [release](https://github.com/ollama/ollama/releases) that you can swap in place to update Ollama. Let me know if this helps!

**Comment by donuts-are-good** [comment]
Thanks, however I hope you don't mind a little pushback in the name of UX. 

It'd be more useful if that one liner could sense an upgrade like this: check if the binary exists, check if the unit exists - if the binary exists and the unit file doesn't, prompt the user. If neither exists, or if both exists, just continue the way the script has been operating.

**Comment by airtonix** [comment]
@donuts-are-good instead of installing it from the curl bang: use [asdf-ollama](https://github.com/virtualstaticvoid/asdf-ollama) instead.

@jmorganca and yes. please publish binaries for each release.
