### ISSUE TITLE
Set attention type for Mistral 7B

### ISSUE THREAD

**Issue by aiseei** [ollama/ollama#2875]
Hi - is there any documentation that talks abt how  attention types can be set ?
There seem to be options as per the Mistral git. 
https://github.com/mistralai/mistral-src
https://huggingface.co/docs/transformers/main/model_doc/mistral HF talks abt using flash attention

Also any pointer on how to interpert the debug messages esp when the model loads and when ut receives a `generate` request?

Any inputs would be much appreciated!

Thanks.

**Comment by pdevine** [comment]
I'm going to close this as a dupe of #4051 . It's coming soon!
