### ISSUE TITLE
Getting error with `nomic-embed-text`

### ISSUE THREAD

**Issue by isavita** [ollama/ollama#2877]
# Description
It might be me doing something wrong, but when I try to run `ollama run nomic-embed-text` I am getting following error
```shell
> ollama run nomic-embed-text
Error: embedding models do not support chat
```
Here is info for my os and the ollama version
```shell
> ollama -v
ollama version is 0.1.27
> sw_vers
ProductName:		macOS
ProductVersion:		14.2.1
BuildVersion:		23C71
```

**Comment by isavita** [comment]
I found that I don't need to run it explicitly.

**Comment by 480284856** [comment]
But how did a vector store in langchain use it?

**Comment by codemaker2015** [comment]
Try to pull the embed-model from Ollama.

Open your terminal and execute the following command,

`ollama pull nomic-embed-text`
