### ISSUE TITLE
Mixtral on Ollama, Nvidia RTX 3090 24G vs Nvidia A5000 24G : A Comparative Experience

### ISSUE THREAD

**Issue by nejib1** [ollama/ollama#2882]
Hello,

This is not an issue, it can be closed immediately,  I just wanted to share my experience using Mixtral 26G on Ollama, comparing

Nvidia RTX 3090 and the Nvidia RTX A5000 on the same hardware, a SuperMicro 1028GR-TR server. Here's what I found:

**Speed:** I didn't notice any difference in speed, both GPUs perform similarly in this regard.

**Temperature:** The RTX 3090 runs significantly hotter compared to the A5000. Throughout my tests, the A5000 remained impressively cool.

**Fan Speed:** The RTX 3090's fans run at a minimum of 65%, whereas the A5000's fans operate at 30%, which is another point in favor of the A5000.

**Power Consumption:** The A5000 is more energy-efficient, consuming up to 230 watts at peak, whereas the RTX 3090 can consume up to 350 watts.

**Conclusion:** For AI purposes (Ollama in any case), **The A5000 is clearly superior** in all the aspects I tested.
It offers comparable speed with significantly better temperature management, lower fan speeds, and reduced power consumption.

**Comment by khu834** [comment]
How does Mixtral fit on either of those GPU?
Neither of them has 26G of GPU memory

**Comment by nejib1** [comment]
I have an A4000 already installed, but tests were by combining A4000+A5000 and A4000+RTX 3090

**Comment by pdevine** [comment]
We just got an A6000 Ada to test against our 4090s. Definitely agree it's a much better card, but it's also $3k more expensive :-D
