### ISSUE TITLE
GPU detected, avx2 found. but doesn't get utilized.

### ISSUE THREAD

**Issue by Aryangh1379** [ollama/ollama#2883]
Hi, thanks for your good work, guys. i'm running ollama on ArchLinux. when I start the ollama service and get a status, it shows these logs:

> hub.com/jmorganca/ollama/server.(*Server).GenerateRoutes.func3 (5 handlers)
> =routes.go:1019 msg="Listening on 127.0.0.1:11434 (version 0.1.27)"
> =payload_common.go:107 msg="Extracting dynamic libraries..."
> =payload_common.go:146 msg="Dynamic LLM libraries [cpu_avx cpu_avx2 cpu]"
> =gpu.go:94 msg="Detecting GPU type"
> =gpu.go:265 msg="Searching for GPU management library libnvidia-ml.so"
> =gpu.go:311 msg="Discovered GPU libraries: [/usr/lib/libnvidia-ml.so.550.54.14 /usr/lib64/libnvidia-ml.so.550.54.14]"
> =gpu.go:99 msg="Nvidia GPU detected"
> =cpu_common.go:11 msg="CPU has AVX2"
> =gpu.go:146 msg="CUDA Compute Capability detected: 7.5"
> ~
> ~
> ~
which says GPU is detected, but I don't get it, why doesn't it use the GPU? here's GPU details:
```
aryan@Archian:~$ nvidia-smi
Sun Mar  3 01:08:59 2024       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.14              Driver Version: 550.54.14      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce GTX 1650 ...    Off |   00000000:01:00.0  On |                  N/A |
|  0%   43C    P8             11W /  100W |     267MiB /   4096MiB |      4%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
                                                                                         
+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI        PID   Type   Process name                              GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|    0   N/A  N/A       770      G   /usr/lib/Xorg                                  67MiB |
|    0   N/A  N/A       883      G   /usr/bin/gnome-shell                          137MiB |
|    0   N/A  N/A      1295      G   /usr/lib/xdg-desktop-portal-gnome              12MiB |
|    0   N/A  N/A     13641      G   /usr/bin/telegram-desktop                       2MiB |
|    0   N/A  N/A     23030      G   ...seed-version=20240229-180128.736000         44MiB |
+-----------------------------------------------------------------------------------------+
```
```
CPU: 6-core Intel Core i5-10400 
kernel: 6.6.18-1-lts 
```

I ran gemma:2b, llama2-uncensored:latest, mistral:latest
let me know if you want any other details about my setup...
thanks for your responding guys.

**Comment by Aryangh1379** [comment]
guys apparently there is also `ollama-cuda` which i didn't know exist. I wonder why nobody mentioned it in the forums. it's better, at least some utilization i see from GPU. about 15%. but still lots of work CPU does. any improvment tips& tricks you have for me?

**Comment by dhiltgen** [comment]
I don't believe there's a defect in the ollama repo or our official builds, so I'm going to close this.  If you disagree, please share some more details.
