### ISSUE TITLE
high cpu 100% while using it

### ISSUE THREAD

**Issue by ahmeteid7** [ollama/ollama#2886]
i tried it, while using it , the cpu reach to 100% and i feel my pc will explode , laud fan

**Comment by easp** [comment]
Running LLMs is computationally intense. There really isn't a way to get around that.

**Comment by ahmeteid7** [comment]
> Running LLMs is computationally intense. There really isn't a way to get around that.

there is option for online reach, insead of locally install, i mean like openapi does?

**Comment by pdevine** [comment]
@ahmeteid7 You can definitely use Ollama w/ cloud services such as AWS / Google Cloud / etc. You will have to have an account with one of those services and start your own instances of course. I definitely recommend using a service which has a GPU which will give you much faster responses.

I'm going to go ahead and close the issue.
