### ISSUE TITLE
Fail to load dynamic library - unicode character path

### ISSUE THREAD

**Issue by 08183080** [ollama/ollama#2888]
Error: Unable to load dynamic library: Unable to load dynamic server library: �Ҳ���ָ����ģ�顣

**Comment by xiangbianpangde** [comment]
你可以试一试在Windows上运行wsl，在Ubuntu中下载运行

**Comment by 08183080** [comment]
行，我可以试一试。不过我的电脑明明刚重置却还是有问题就很不理解。别人的电脑ok没有问题

**Comment by hubblebubblepig** [comment]
llama_model_load: error loading model: error loading model vocabulary: cannot find tokenizer merges in model file

llama_load_model_from_file: failed to load model

**Comment by xiangbianpangde** [comment]
---Original---
From: ***@***.***&gt;
Date: Mon, Mar 4, 2024 22:55 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [ollama/ollama] Fail to load dynamic library (Issue #2888)




 
llama_model_load: error loading model: error loading model vocabulary: cannot find tokenizer merges in model file
 
llama_load_model_from_file: failed to load model

**Comment by dhiltgen** [comment]
This is likely a bug related to unicode characters not being handled correctly.  As a workaround until we get this fixed, set OLLAMA_MODELS to a path that doesn't contain unicode characters.  https://github.com/ollama/ollama/blob/main/docs/faq.md#where-are-models-stored

**Comment by xiangbianpangde** [comment]
I tried to change the environment variables to exclude Unicode characters, but still encountered failure in loading the dynamic library.

**Comment by dhiltgen** [comment]
@xiangbianpangde can you share the server log showing the failure when there weren't unicode characters?
