### ISSUE TITLE
How to get Ollama to use my RTX 4090 on windows 11

### ISSUE THREAD

**Issue by TimmekHW** [ollama/ollama#2894]
I have 12600K + 64GB RAM + RTX 4090. I use Ollama + OpenCHat.

For some reason Ollama won't use my RTX 4090. How can I show the program my graphics card?

![image](https://github.com/ollama/ollama/assets/94626112/7fe5afe3-1fbb-46f1-a9e4-a1f8a58a6d05)

```
messages = chat_histories[chat_id]
    options = {
        "num_ctx": 12768,
        "num_thread": 10,
        "num_predict": 300,
        "repeat_last_n": 100,
        "temperature": 0.75
    }
    response = "" 
```

[config.json](https://github.com/ollama/ollama/files/14473300/config.json)
[server.log](https://github.com/ollama/ollama/files/14473301/server.log)
[app.log](https://github.com/ollama/ollama/files/14473302/app.log)

**small bursts of GPU work are the work of Stable Diffusion

**Comment by TimmekHW** [comment]
Я просто удалил `#"num_thread": 10,` и всё заработало

**Comment by amine-source-del** [comment]
Tyu

**Comment by amine-source-del** [comment]
Fuck you
