### ISSUE TITLE
using starcoder 15b, 3b, and standard returning end of file

### ISSUE THREAD

**Issue by michaelmandich** [ollama/ollama#2900]
success 
Error: Post "http://127.0.0.1:11434/api/chat": EOF
/Downloads$ 

attempted with both version 27 and 28 on windows and Linux, same response on both. appears to be an issue with how star coder is being setup.

**Comment by jmorganca** [comment]
Hi there, would it be possible to try re-downloading the version 0.1.28 pre-release? https://github.com/ollama/ollama/releases/tag/v0.1.28 this version should support it. Sorry about that!
