### ISSUE TITLE
The local running model repeatedly cycles through its response to the first question, disregarding any subsequent input.

### ISSUE THREAD

**Issue by Yanxxx** [ollama/ollama#2901]
Installed ollama client from https://ollama.com/download. 
OS： Windows 11 pro
Model: ollama run gemma:7b
Question asked: 你和Gemini有什么区别
The output text always focus on the difference between Gemini and Gemma. However the answer is not right either. It keeps saying that Gemini was developed by OpenAI.

**Comment by easp** [comment]
Are you using the latest version of Ollama (0.1.27)? Have you `ollama pull gemma:7b` model recently? There was some trouble with the model in earlier versions.

**Comment by Yanxxx** [comment]
> Are you using the latest version of Ollama (0.1.27)? Have you `ollama pull gemma:7b` model recently? There was some trouble with the model in earlier versions.

Yes, I downloaded it today. And one more thing. I closed the terminal and cannot open it again.

**Comment by Yanxxx** [comment]
> Are you using the latest version of Ollama (0.1.27)? Have you `ollama pull gemma:7b` model recently? There was some trouble with the model in earlier versions.

I'm uncertain whether this is merely a bug on my computer or if it could be replicated, but this is the situation I encountered.

**Comment by pdevine** [comment]
I tried this on both Mac and Windows 11. I *believe* it's working as intended. The model definitely has some issues with hallucinations :-D
