### ISSUE TITLE
Sometimes no http response is received from the ollama-rest-api  /chat

### ISSUE THREAD

**Issue by CtrlAiDel** [ollama/ollama#2905]
With ollama-rest-api  /chat {format: 'json'}
sometimes no http response is received. 

``` Json
{
    "model": "llama2",
    "stream": false,
    "format": "json",
    "messages": [
        {
            "role": "user",
            "content": "Rose are red"
        },
        {
            "role": "assistant",
            "content": "{\"Rose are red, violets are blue,\"\n    :\n\"Sugar is sweet, and so are you!\"}"
        },
        {
            "role": "user",
            "content": "who wrote that poem ?"
        }
    ]
}
```

The third and last log are manually canceled request. We can see that they are not in the postman logs..

![image](https://github.com/ollama/ollama/assets/40178706/78095e88-c70d-447d-8e29-e11353550a82)

It might be code related. It's working for us more than half the time, and then other let's say 20-30% of the times, we don't have anything in the logs and no response.

Thank you for the amazing project!

**Comment by BruceMacD** [comment]
Hi @CtrlAiDel, this is a pretty common problem. The issue is the prompt, try adding a system message to respond in JSON.

```json
{
    "model": "llama2",
    "stream": false,
    "format": "json",
    "messages": [
        {
            "role": "system",
            "content": "Respond only in JSON format."
        },
        {
            "role": "user",
            "content": "Rose are red"
        },
        {
            "role": "assistant",
            "content": "{\"Rose are red, violets are blue,\"\n    :\n\"Sugar is sweet, and so are you!\"}"
        },
        {
            "role": "user",
            "content": "who wrote that poem ?"
        }
    ]
}
```

The LLM needs to be told to respond in JSON since the `format` flag only filters the output. Let me know if that helps.

**Comment by CtrlAiDel** [comment]
Ok, my friend/dev get what you mean. But he's asking why sometimes there are no problem at all. Also could you maybe give us an exemple of the solution that you are suggesting us please?

Thanks again, it's really appreciated

**Comment by marklysze** [comment]
I am also experiencing the same issue. If I run with `"format" : "json"` then it hangs with Mistral (and many others). If I remove that it runs fine.

This always runs okay first time but not subsequent times:
`curl -X POST http://localhost:11434/api/chat -d @curl_command.txt`

curl_command.txt:
```  GNU nano 6.2                                               curl_command.txt                                                        
{
  "model": "mistral:instruct",
  "messages": [
    {
      "content": "For currency exchange tasks, \n only use the functions you have been provided with. \n Output 'BAZINGA!' when an a>
      "role": "system"
    },
    {
      "content": "How much is 123.45 EUR in USD?",
      "role": "user"
    }
  ],
  "options": {},
  "stream": false,
  "format": "json"
}```

If I remove the `"format" : "json"` then I can run that command continuously without issue.

**Comment by seanmavley** [comment]
Related to issue #1910

**Comment by jmorganca** [comment]
Merging with https://github.com/ollama/ollama/issues/1910
