### ISSUE TITLE
System Monitor detected that internet is used by Ollama.

### ISSUE THREAD

**Issue by kukidevs** [ollama/ollama#2911]
![image](https://github.com/ollama/ollama/assets/113847173/b90b5c11-2ce5-4f1f-a7ee-59abfff867d8)

What does it send/receive? I was using it through MacOS terminal, installed the app from the website.

**Comment by jmorganca** [comment]
Hi there, the `ollama` binary shouldn't be sending or or receiving data to the external internet unless you're pulling or pushing models.

Note that if you do `ollama run`, the `ollama` CLI will send data to the local Ollama's REST API (all local, and you can test this by turning off your internet), and this will show up in Activity Monitor, even if all activity is entirely local. Let me know if that helps

**Comment by kukidevs** [comment]
thanks! I found out that system monitor's network tab also includes 'internal' connections. I tested it by running a localhost, which also showed up in the tab.

**Comment by unobatbayar** [comment]
@jmorganca 

> Hi there, the ollama binary shouldn't be sending or or receiving data to the external internet 
unless you're pulling or pushing models.

Except it is. It's not pulling or pushing, the model is already installed. Yet, it's always sending and receiving data. Disconnecting the internet seems to be only fix at the moment.
