### ISSUE TITLE
Running ollama python library together with ollama in colab ?

### ISSUE THREAD

**Issue by timtensor** [ollama/ollama#2912]
Hi , thanks for the colab notebook here : https://github.com/ollama/ollama/tree/main/examples/jupyter-notebook . However I have a question how can i run ollama python libraries and scripts on top of the provided notebook. If i understand the service ollama serve is always running right ? We need to stop it before writing and executing other cells.

**Comment by mxyng** [comment]
Jupyter notebooks require each cell to finish before executing other cells. As far as I know, there's no way around it. 

The easiest way to accomplish what you're asking is probably to create two notebooks, one serving ollama and the other running your scripts

Alternatively, you can run everything in the same cell using asynchronous calls. That might not be possible depending on the architecture of your notebook
