### ISSUE TITLE
Running with Ollama desktop vs ollama serve

### ISSUE THREAD

**Issue by sofiafernandescd** [ollama/ollama#2913]
Hello, great work with this project!
I'm using Ollama models to feed my crewAI agents, but I noticed that:
- when I turn on Ollama desktop, everything runs well
- if I shut down Ollama desktop, and use "ollama serve" to start Ollama, my program outputs an error because it seems to be expecting a JSON request

How do I solve this? Because I wanted to run ollama in a GPU instance, and it's not so easy to get Ollama desktop running from there, so I was looking for an easy way to get the same behaviour.

Thank you so much!

**Comment by easp** [comment]
What OS are you using?

**Comment by sofiafernandescd** [comment]
@easp I'm on MacOS, and I also tried to serve ollama on a Koyeb instance. I just tested again and it seems to be working by now, in both. I don't know what caused this, but since it's solve, I'm closing the issue. Thank you
