### ISSUE TITLE
All Models running slow on Ollama

### ISSUE THREAD

**Issue by RahulVerma989** [ollama/ollama#2915]
Hi there,

Till now I have tested all these models on my VPS machine and all of them are running extremely slow, taking minute on an average to get a full response.

<img width="453" alt="Screenshot 2024-03-04 at 8 46 02 PM" src="https://github.com/ollama/ollama/assets/48805821/39569bff-2e2a-4dc6-8c72-32ba49b45a25">

<img width="850" alt="Screenshot 2024-03-04 at 8 51 26 PM" src="https://github.com/ollama/ollama/assets/48805821/23e07b72-6fac-4640-8092-0cca15fbe94f">

My VPS Specs:
RAM: 32 GB
CPU: 8
Bandwidth: 33 TB
Disk space: 400 GB

Is there any model which will provide fast responses on ollama?

**Comment by pdevine** [comment]
Hey @RahulVerma989 . You'll get a lot better response times using a system w/ a GPU such as an AWS EC2 P4/G4 instance. You can also try to use a higher quantization level such as `gemma:7b-chat-q2_K`, although that might not give you great results. As you mentioned, a lower parameter count model such as `phi` will also work.

Those are essentially the three levers you've got though:
1. better hardware (such as a GPU)
2. higher quantization (i.e. "compression") level (q2_K, q3_K_S, q3_K_M, q3_K_L)
3. lower parameter count models

I'm going to go ahead and close the issue. Feel free to keep commenting though, or ask away on the Discord.
