### ISSUE TITLE
How to clear chat history in the Ollama CLI interface?

### ISSUE THREAD

**Issue by doggy8088** [ollama/ollama#2916]
When chatting in the Ollama CLI interface, the previous conversation will affect the result for the further conversation. Is there a way to clear out all the previous conversations?

**Comment by easp** [comment]
Quit the CLI and restart it. Also `/load MODEL` to reload the model within the CLI seems to work.

**Comment by plusminuschirag** [comment]
You can just used `/clear` command.

**Comment by vanboom** [comment]
/clear does not remove the chat history.

In Linux...
rm ~/.ollama/history
