### ISSUE TITLE
ollama call failed with status code 500 llama 2

### ISSUE THREAD

**Issue by sabahatza** [ollama/ollama#2920]
Hi team,

I am trying to run the llama2 model locally ( I was doing it previously for the last couple of weeks without any problems), but now I face the following error when I am trying to -> ollama run llama2
`Error: error loading model /Users/S_Z/.ollama/models/blobs/sha256:8934d96d3f08982e95922b2b7a2c626a1fe873d7c3b06e8e56d7bc0a1`

No ollama models are running for that matter. for context, I have an M1 Max Macbook. Is there any fix to this?

**Comment by jmorganca** [comment]
Hi there, may I ask which version of Ollama you're using? You may need to re-pull `llama2` if you have a very old version

```
ollama pull llama2
```

Please let me know if this doesn't fix it :)

**Comment by sabahatza** [comment]
Hi @jmorganca, sorry am I missing something? I've tried this multiple times 
<img width="1341" alt="Screenshot 2024-03-04 at 9 50 19 PM" src="https://github.com/ollama/ollama/assets/135341585/0d254cc2-fe11-4dae-9bfc-56032aa49b2c">

**Comment by sabahatza** [comment]
Also I just used the same environment, same setup to run llama2:13b just last week, and it worked just fine. Any idea what could have changed?
