### ISSUE TITLE
how does memory work in cmd  `ollama run openchat`?

### ISSUE THREAD

**Issue by TimmekHW** [ollama/ollama#2923]
how does memory work in cmd  `ollama run openchat`?

could you share the code? remembering chat history and context works well there. can I please have the code? Because my implementation of history is not working correctly

**Comment by mxyng** [comment]
The code is open source. Specifically [here](https://github.com/ollama/ollama/blob/main/cmd/interactive.go).

To summarize, `ollama run` uses `/api/chat` which takes messages as inputs. History is created by appending to messages
