### ISSUE TITLE
Will Ollama support FuncMaster-v0.1-Mistral-7B-Instruct-GGUF?

### ISSUE THREAD

**Issue by eliranwong** [ollama/ollama#2931]
Will Ollama support FuncMaster-v0.1-Mistral-7B-Instruct-GGUF?

https://huggingface.co/allyson-ai/FuncMaster-v0.1-Mistral-7B-Instruct-GGUF

**Comment by bmizerany** [comment]
@eliranwong I was able to get FuncMaster up and running by following https://github.com/ollama/ollama/blob/main/docs/import.md. Please let me know if that is not the case for you.

I'm going to close this, but please reopen if run into any major issues.
