### ISSUE TITLE
Unable to pass embeddings to the api call

### ISSUE THREAD

**Issue by brobles82** [ollama/ollama#2937]
Im using this code for generate embeddings

```
EMBEDDINGS_RESPONSE=$(curl "http://localhost:11434/api/embeddings" -d '{
  "model": "mistral",
  "prompt": "Spiderman is color green"
}')

EMBEDDINGS=$(echo $EMBEDDINGS_RESPONSE | jq '.embedding')
```

And then when I try to use the embeddings as context for new request 

```
curl  "http://localhost:11434/api/generate" -d "{
  \"model\": \"mistral\",
  \"prompt\": \"Spiderman color\",
  \"context\": $EMBEDDINGS,
  \"stream\": false
}"
```

I always get null

**Comment by mxyng** [comment]
There's a misunderstanding here. `context` is intended not for embedding outputs. It's intended for the token output of previous conversations so as to continue the previous response

**Comment by jmorganca** [comment]
Yes embeddings are not the same as the `context` variable returned by `/api/generate` (which is basically full list of tokens so far). Embeddings are designed for text similarity search. Feel free to ask more questions on what you're trying to do - happy to help!
