### ISSUE TITLE
Model Request : WhiteRabbitNeo 33B v1.5

### ISSUE THREAD

**Issue by ligmaSec** [ollama/ollama#2939]
https://huggingface.co/WhiteRabbitNeo/WhiteRabbitNeo-33B-v1.5

**Comment by bmizerany** [comment]
@ligmaSec You should be able to import WhiteRabbitNeo by following https://github.com/ollama/ollama/blob/main/docs/import.md#importing-pytorch--safetensors

Please let me now if you have (or do) run into any trouble with that. I'm closing but please reopen if you need to.

**Comment by ligmaSec** [comment]
hey, I am not sure but I think it is missing a tokenizer.model, I couldn't convert it using llama.cpp's convert.py :/
