### ISSUE TITLE
Global Configuration Variables for Ollama

### ISSUE THREAD

**Issue by bkawakami** [ollama/ollama#2941]
I am currently using Ollama for running LLMs locally and am greatly appreciative of the functionality it offers. However, I've come across a point of confusion regarding the global configuration of the Ollama environment, especially when it comes to setting it up for different use cases.

Could you provide more detailed information or documentation on the following aspects:

1. What are all the global configuration variables available for Ollama, and where can I find a comprehensive list?
2. Is there a way to set these configurations globally via a YAML file or a similar approach, rather than setting individual environment variables?
3. If YAML or similar file-based configurations are possible, could you provide an example of how to structure this file for different scenarios (e.g., different models, host configurations)?

**Comment by bmizerany** [comment]
Thank you for the feedback.

The environment variables accepted for configuration of Ollama may be found throughout https://github.com/ollama/ollama/blob/main/docs/faq.md#how-do-i-configure-ollama-server. I do see now it is hard to get a quick glance at them all, and so I'll open an issue to add environment docs to `ollama -h` and possibly the wiki.

Ollama currently has to plans to support a YAML config file.

I hope this helps. Please reopen if I missed something.

**Comment by ridvan70** [comment]
You can see a list of environment variables at

- [https://github.com/ollama/ollama/blob/main/envconfig/config.go](url)

until the docs has been enhanced with this topic.

**Comment by nikhil-swamix** [comment]
### no help anywhere! had some urgent req for company, compiled this, hope a wandering soul discover this.

| Variable | Type | Description | Effect |
|----------|------|-------------|--------|
| OLLAMA_HOST | string | Configures the host and scheme for the Ollama server | Determines the URL used for connecting to the Ollama server |
| OLLAMA_ORIGINS | string | Configures allowed origins for CORS | Controls which origins are allowed to make requests to the Ollama server |
| OLLAMA_MODELS | string | Sets the path to the models directory | Determines where model files are stored and loaded from |
| OLLAMA_KEEP_ALIVE | duration | Sets how long models stay loaded in memory | Controls the duration models remain in memory after use |
| OLLAMA_DEBUG | bool | Enables additional debug information | Increases verbosity of logging and debugging output |
| OLLAMA_FLASH_ATTENTION | bool | Enables experimental flash attention feature | Activates an experimental optimization for attention mechanisms |
| OLLAMA_NOHISTORY | bool | Disables readline history | Prevents command history from being saved |
| OLLAMA_NOPRUNE | bool | Disables pruning of model blobs on startup | Keeps all model blobs, potentially increasing disk usage |
| OLLAMA_SCHED_SPREAD | bool | Allows scheduling models across all GPUs | Enables multi-GPU usage for model inference |
| OLLAMA_INTEL_GPU | bool | Enables experimental Intel GPU detection | Allows usage of Intel GPUs for model inference |
| OLLAMA_LLM_LIBRARY | string | Sets the LLM library to use | Overrides automatic detection of LLM library |
| OLLAMA_TMPDIR | string | Sets the location for temporary files | Determines where temporary files are stored |
| CUDA_VISIBLE_DEVICES | string | Sets which NVIDIA devices are visible | Controls which NVIDIA GPUs can be used |
| HIP_VISIBLE_DEVICES | string | Sets which AMD devices are visible | Controls which AMD GPUs can be used |
| ROCR_VISIBLE_DEVICES | string | Sets which AMD devices are visible | Alternative way to control which AMD GPUs can be used |
| GPU_DEVICE_ORDINAL | string | Sets which AMD devices are visible | Another alternative to control AMD GPU visibility |
| HSA_OVERRIDE_GFX_VERSION | string | Overrides the gfx version for AMD GPUs | Forces a specific graphics version for AMD GPUs |
| OLLAMA_RUNNERS_DIR | string | Sets the location for runners | Determines where runner executables are located |
| OLLAMA_NUM_PARALLEL | uint | Sets the number of parallel model requests | Controls concurrency of model inference |
| OLLAMA_MAX_LOADED_MODELS | uint | Sets the maximum number of loaded models | Limits the number of models that can be simultaneously loaded |
| OLLAMA_MAX_QUEUE | uint | Sets the maximum number of queued requests | Limits the size of the request queue |
| OLLAMA_MAX_VRAM | uint | Sets a maximum VRAM override in bytes | Limits the amount of VRAM that can be used |

**Comment by yumemio** [comment]
Not sure if this helps, but in version 0.4.2 `ollama help <subcommand>` lists available envvar configurations (not sure if the list is exhaustive). Note that the list is shown only when `help` is invoked with a subcommand.

The above table by @nikhil-swamix is more detailed, though!


```
$ ollama help serve
Start ollama

Usage:
  ollama serve [flags]

Aliases:
  serve, start

Flags:
  -h, --help   help for serve

Environment Variables:
      OLLAMA_DEBUG               Show additional debug information (e.g. OLLAMA_DEBUG=1)
      OLLAMA_HOST                IP Address for the ollama server (default 127.0.0.1:11434)
      OLLAMA_KEEP_ALIVE          The duration that models stay loaded in memory (default "5m")
      OLLAMA_MAX_LOADED_MODELS   Maximum number of loaded models per GPU
      OLLAMA_MAX_QUEUE           Maximum number of queued requests
      OLLAMA_MODELS              The path to the models directory
      OLLAMA_NUM_PARALLEL        Maximum number of parallel requests
      OLLAMA_NOPRUNE             Do not prune model blobs on startup
      OLLAMA_ORIGINS             A comma separated list of allowed origins
      OLLAMA_SCHED_SPREAD        Always schedule model across all GPUs
      OLLAMA_TMPDIR              Location for temporary files
      OLLAMA_FLASH_ATTENTION     Enabled flash attention
      OLLAMA_LLM_LIBRARY         Set LLM library to bypass autodetection
      OLLAMA_GPU_OVERHEAD        Reserve a portion of VRAM per GPU (bytes)
      OLLAMA_LOAD_TIMEOUT        How long to allow model loads to stall before giving up (default "5m")
```

**Comment by nikhil-swamix** [comment]
as i understand from yu's comment, 0.4.2 has good improvement of vars, and original file of go env config seem to be changed, rather improved...

what would be better if a docs page is provided... atleast something like 
https://docs.continue.dev/getting-started/install

at this point ive scanned most source of ollama so, maybe not apply to me, but new user definitely benefit from docs, and thousands by the day with the rise of AI! 

if any maintainer looking, please let me know if doc page is required. im having a experimental agent which generates doc sites. hoping to make meaningful contrib to ollama.

**Comment by Vyerni** [comment]
Thanks for the list.

Would be lovely to be able to list all needed models in environment variables, so it will download automatically on creation if missing.

**Comment by melroy89** [comment]
> ### no help anywhere! had some urgent for automated coding, compiled this, hope a wandering soul discover this.
> Variable 	Default Value 	Description + Effect + Scenario
> OLLAMA_HOST 	"http://127.0.0.1:11434" 	Configures the host and scheme for the Ollama server. Effect: Determines the URL used for connecting to the Ollama server. Scenario: Useful when deploying Ollama in a distributed environment or when you need to expose the service on a specific network interface.
> OLLAMA_ORIGINS 	[localhost, 127.0.0.1, 0.0.0.0] + app://, file://, tauri:// 	Configures allowed origins for CORS. Effect: Controls which origins are allowed to make requests to the Ollama server. Scenario: Critical when integrating Ollama with web applications to prevent unauthorized access from different domains.
> OLLAMA_MODELS 	$HOME/.ollama/models 	Sets the path to the models directory. Effect: Determines where model files are stored and loaded from. Scenario: Useful for managing disk space on different drives or setting up shared model repositories in multi-user environments.
> OLLAMA_KEEP_ALIVE 	5 minutes 	Sets how long models stay loaded in memory. Effect: Controls the duration models remain in memory after use. Scenario: Longer durations improve response times for frequent queries but increase memory usage. Shorter durations free up resources but may increase initial response times.
> OLLAMA_DEBUG 	false 	Enables additional debug information. Effect: Increases verbosity of logging and debugging output. Scenario: Invaluable for troubleshooting issues or understanding the system's behavior during development or deployment.
> OLLAMA_FLASH_ATTENTION 	false 	Enables experimental flash attention feature. Effect: Activates an experimental optimization for attention mechanisms. Scenario: Can potentially improve performance on compatible hardware but may introduce instability.
> OLLAMA_NOHISTORY 	false 	Disables readline history. Effect: Prevents command history from being saved. Scenario: Useful in security-sensitive environments where command history should not be persisted.
> OLLAMA_NOPRUNE 	false 	Disables pruning of model blobs on startup. Effect: Keeps all model blobs, potentially increasing disk usage. Scenario: Helpful when you need to maintain all model versions for compatibility or rollback purposes.
> OLLAMA_SCHED_SPREAD 	false 	Allows scheduling models across all GPUs. Effect: Enables multi-GPU usage for model inference. Scenario: Beneficial in high-performance computing environments with multiple GPUs to maximize hardware utilization.
> OLLAMA_INTEL_GPU 	false 	Enables experimental Intel GPU detection. Effect: Allows usage of Intel GPUs for model inference. Scenario: Useful for organizations leveraging Intel GPU hardware for AI workloads.
> OLLAMA_LLM_LIBRARY 	"" (auto-detect) 	Sets the LLM library to use. Effect: Overrides automatic detection of LLM library. Scenario: Useful when you need to force a specific library version or implementation for compatibility or performance reasons.
> OLLAMA_TMPDIR 	System default temp directory 	Sets the location for temporary files. Effect: Determines where temporary files are stored. Scenario: Important for managing I/O performance or when system temp directory has limited space.
> CUDA_VISIBLE_DEVICES 	All available 	Sets which NVIDIA devices are visible. Effect: Controls which NVIDIA GPUs can be used. Scenario: Critical for managing GPU allocation in multi-user or multi-process environments.
> HIP_VISIBLE_DEVICES 	All available 	Sets which AMD devices are visible. Effect: Controls which AMD GPUs can be used. Scenario: Similar to CUDA_VISIBLE_DEVICES but for AMD hardware.
> OLLAMA_RUNNERS_DIR 	System-dependent 	Sets the location for runners. Effect: Determines where runner executables are located. Scenario: Important for custom deployments or when runners need to be isolated from the main application.
> OLLAMA_NUM_PARALLEL 	0 (unlimited) 	Sets the number of parallel model requests. Effect: Controls concurrency of model inference. Scenario: Critical for managing system load and ensuring responsiveness in high-traffic environments.
> OLLAMA_MAX_LOADED_MODELS 	0 (unlimited) 	Sets the maximum number of loaded models. Effect: Limits the number of models that can be simultaneously loaded. Scenario: Helps manage memory usage in environments with limited resources or many different models.
> OLLAMA_MAX_QUEUE 	512 	Sets the maximum number of queued requests. Effect: Limits the size of the request queue. Scenario: Prevents system overload during traffic spikes and ensures timely processing of requests.
> OLLAMA_MAX_VRAM 	0 (unlimited) 	Sets a maximum VRAM override in bytes. Effect: Limits the amount of VRAM that can be used. Scenario: Useful in shared GPU environments to prevent a single process from monopolizing GPU memory.

Can this be documented somewhere in the FAQ? https://github.com/ollama/ollama/blob/main/docs/faq.md

**Comment by alpha-ulrich** [comment]
@nikhil-swamix I would suggest to add that formally in Ollama documentation! I was looking for exactly this information.

**Comment by SuperUserNameMan** [comment]
btw, is there any env var to tell ollama how many CPU threads it is allowed to use ?

**Comment by encryptic12** [comment]
This is seriously a **gaping hole** in the documentation. I am trying to use the new engine and memory estimation for testing and just assuming a value of 1 for these enables them.... an authoritative list of all environment variables, their default values, and possible values I would have thought are imparative for complete documentation. How hard is it to provide?

**Comment by spygi** [comment]
> ### No help anywhere! Due to some urgent requirements for automated coding, I compiled this from source code RAG, hope a wandering soul discover this.
> Variable	Default Value	Description + Effect + Scenario
> OLLAMA_HOST	"http://127.0.0.1:11434"	Configures the host and scheme for the Ollama server. Effect: Determines the URL used for connecting to the Ollama server. Scenario: Useful when deploying Ollama in a distributed environment or when you need to expose the service on a specific network interface.
> OLLAMA_ORIGINS	[localhost, 127.0.0.1, 0.0.0.0] + app://, file://, tauri://	Configures allowed origins for CORS. Effect: Controls which origins are allowed to make requests to the Ollama server. Scenario: Critical when integrating Ollama with web applications to prevent unauthorized access from different domains.
> OLLAMA_MODELS	$HOME/.ollama/models	Sets the path to the models directory. Effect: Determines where model files are stored and loaded from. Scenario: Useful for managing disk space on different drives or setting up shared model repositories in multi-user environments.
> OLLAMA_KEEP_ALIVE	5 minutes	Sets how long models stay loaded in memory. Effect: Controls the duration models remain in memory after use. Scenario: Longer durations improve response times for frequent queries but increase memory usage. Shorter durations free up resources but may increase initial response times.
> OLLAMA_DEBUG	false	Enables additional debug information. Effect: Increases verbosity of logging and debugging output. Scenario: Invaluable for troubleshooting issues or understanding the system's behavior during development or deployment.
> OLLAMA_FLASH_ATTENTION	false	Enables experimental flash attention feature. Effect: Activates an experimental optimization for attention mechanisms. Scenario: Can potentially improve performance on compatible hardware but may introduce instability.
> OLLAMA_NOHISTORY	false	Disables readline history. Effect: Prevents command history from being saved. Scenario: Useful in security-sensitive environments where command history should not be persisted.
> OLLAMA_NOPRUNE	false	Disables pruning of model blobs on startup. Effect: Keeps all model blobs, potentially increasing disk usage. Scenario: Helpful when you need to maintain all model versions for compatibility or rollback purposes.
> OLLAMA_SCHED_SPREAD	false	Allows scheduling models across all GPUs. Effect: Enables multi-GPU usage for model inference. Scenario: Beneficial in high-performance computing environments with multiple GPUs to maximize hardware utilization.
> OLLAMA_INTEL_GPU	false	Enables experimental Intel GPU detection. Effect: Allows usage of Intel GPUs for model inference. Scenario: Useful for organizations leveraging Intel GPU hardware for AI workloads.
> OLLAMA_LLM_LIBRARY	"" (auto-detect)	Sets the LLM library to use. Effect: Overrides automatic detection of LLM library. Scenario: Useful when you need to force a specific library version or implementation for compatibility or performance reasons.
> OLLAMA_TMPDIR	System default temp directory	Sets the location for temporary files. Effect: Determines where temporary files are stored. Scenario: Important for managing I/O performance or when system temp directory has limited space.
> CUDA_VISIBLE_DEVICES	All available	Sets which NVIDIA devices are visible. Effect: Controls which NVIDIA GPUs can be used. Scenario: Critical for managing GPU allocation in multi-user or multi-process environments.
> HIP_VISIBLE_DEVICES	All available	Sets which AMD devices are visible. Effect: Controls which AMD GPUs can be used. Scenario: Similar to CUDA_VISIBLE_DEVICES but for AMD hardware.
> OLLAMA_RUNNERS_DIR	System-dependent	Sets the location for runners. Effect: Determines where runner executables are located. Scenario: Important for custom deployments or when runners need to be isolated from the main application.
> OLLAMA_NUM_PARALLEL	0 (unlimited)	Sets the number of parallel model requests. Effect: Controls concurrency of model inference. Scenario: Critical for managing system load and ensuring responsiveness in high-traffic environments.
> OLLAMA_MAX_LOADED_MODELS	0 (unlimited)	Sets the maximum number of loaded models. Effect: Limits the number of models that can be simultaneously loaded. Scenario: Helps manage memory usage in environments with limited resources or many different models.
> OLLAMA_MAX_QUEUE	512	Sets the maximum number of queued requests. Effect: Limits the size of the request queue. Scenario: Prevents system overload during traffic spikes and ensures timely processing of requests.
> OLLAMA_MAX_VRAM	0 (unlimited)	Sets a maximum VRAM override in bytes. Effect: Limits the amount of VRAM that can be used. Scenario: Useful in shared GPU environments to prevent a single process from monopolizing GPU memory.

thank you for this!

small correction for others: the default for OLLAMA_NUM_PARALLEL is 1 https://github.com/ollama/ollama/blob/f2e9c9aff5f59b21a5d9a9668408732b3de01e20/envconfig/config.go#L222 
(validated also with version 0.12.3 of MacOS)

**Comment by CL415** [comment]
Can this be reopened until the documentation does list them?

**Comment by zyberwoof** [comment]
For anyone that is curious, you can find out the valid environment variables on-the-fly by running `ollama serve --help`.  

_I agree that it would be best to have these values documented somewhere clearly.  But I thought this tip might help others._
