### ISSUE TITLE
Deprecate the Usage of the : separator in favor of - regardless of OS for maximum compatibility

### ISSUE THREAD

**Issue by LumiWasTaken** [ollama/ollama#2943]
Heyo!

Here the short summary:
We have a system which uses a file system that runs on both windows and linux for and basically both Run Ollama but access the same model storage to save storage.

Or so we planned.

On Linux Ollama expects the sha256 blob filenames to be separated with a colon `sha256:abcdefg...` while on Windows it expects a dash `sha256-abcdefg...` while this makes sense as colons are an illegal character in filenames on NTFS drives. It causes quite a spark when it comes to compatibility.

So I'd ask for the following proposal:
Add a Fallback compatibility, existing files using the colon will still be supported.
Future blobs will use the dash.
Extra: At some point add a renaming where it renames `:` to `-`.

This would ensure future compatibility if Ollama Windows turns out to be more mainstream or if the storage of Models would be on a external storage (NTFS formatted USB sticks, SMB Shares on Windows Servers etc.)

**Comment by dhiltgen** [comment]
Let's track this separator cleanup via #2032
