### ISSUE TITLE
I need to move the ollama into a no-internet-webserver,how should I backup all the files in my windows/linux ollama folder

### ISSUE THREAD

**Issue by sddzcuigc** [ollama/ollama#2947]
I reallise the windows ollama use the .ollama folder to put the models in. But still not a very good way to transport it to another computer.

**Comment by jmorganca** [comment]
You could indeed zip up the `~/.ollama/models` directory, and then move it to the other computer, this would be the easiest at the moment. Would love to know more about this use case and how it could get easier!
