### ISSUE TITLE
ollama upgrade request: take care of systemd service setup

### ISSUE THREAD

**Issue by kedar-1** [ollama/ollama#2951]
Hello,

I have modified /etc/systemd/system/ollama.service file to listen on all interfaces:
Environment="OLLAMA_HOST=0.0.0.0"

Works as expected but after every upgrade I must open the file and insert this config option again.

Is there any way to allow upgrade of ollama and take care of already defined systemd service setup?

Thanks

**Comment by mxyng** [comment]
The best way to modify systemd services is to create an override configuration under `/etc/systemd/system/<service>.d/<configuration>.conf`. This separation allows the user customization of systemd configurations while allows the vendor to modify the base configuration.

For more details, see the [FAQ](https://github.com/ollama/ollama/blob/main/docs/faq.md#setting-environment-variables-on-linux)
