### ISSUE TITLE
Is there guidance to run Ollama as a background "Daemon" on MacOS pre-login?  

### ISSUE THREAD

**Issue by dukekautington3rd** [ollama/ollama#2955]
I would really like Ollama to run as a service on my Mac or at least set the appropriate listening variable before it starts.
Today I have to `launchctl setenv OLLAMA_HOST 0.0.0.0:8080` and restart Ollama any time there is a reboot.  

And I must be logged in in-order for Ollama to be serving up the LLM.  

I've tried automatically setting the variables many ways:
[
/etc/launchd.conf
/etc/rc.common
~/.zprofile # Only works after terminal is opened
plist file for /Library/LaunchAgents # Only works @ login
plist file in /Library/LaunchDaemons # Can't get to work
above plist files calling [launchctl, automator app, script file]
]

My first milestone was to get the env `OLLAMA_HOST 0.0.0.0:8080` set before Ollama automatically launches
then... get Ollama to launch and continuously run in the background pre-login.

I've been spinning my wheels on this for a while now.  It just seems like something that should be so easy. 
Before someone suggests it, I know I could easily run in linux.  I have an extensive k8s deployment that runs most of my things, but I want to leverage the Macos NPU(Maybe I have a false sense of value here) for performance.

**Comment by easp** [comment]
FYI, Ollama doesn't use the Apple Neural Engine/NPU, just the GPU. Ultimately it's memory bandwidth bound, so the only think the ANE would likely do is reduce power consumption. It's also possible that it has less memory bandwidth than the GPU.

As for your questions, I don't know my way around launchd, at all. I suspect that you'll have the best results if you try launching the command line binary, rather than Ollama.app -- easiest thing might be a shell script that sets the environment as needed and then runs `ollama serve`. Have you referred to https://launchd.info?  There is also a launchd overview [here](https://eclecticlight.co/2021/09/13/running-software-automatically-using-launchd/) which references two commercial utilities that make launchd easier to configure.

If you figure out something that works I imagine that there will be other people interested in your solution.

**Comment by dukekautington3rd** [comment]
@easp That was super helpful.  You confirmed what I suspected, which was that Ollama doesn't use ANE, so I did have a false sense of value.  Although the GPU isn't bad either.

Thanks for the additional info around launchd.  I will share in this thread if I make progress!  

Thanks!

**Comment by dukekautington3rd** [comment]
whoops, accidental reopen

**Comment by brenc** [comment]
@dukekautington3rd were you ever able to figure this out? I figured out how to get ollama to reliably start listening on all interfaces but only on login.

**Comment by dukekautington3rd** [comment]
I have.  I just need a little time to write it up fully.

The summary is:

I can't get anything to execute prelogin, I think this has to do with disk encryption/(decryption upon login).  I have created a launch daemon that points to a script which sets the variable and subsequently serves up Ollama.

**Comment by mbentley** [comment]
Just in case anyone would like an example of a LaunchDaemon that does not require the use of an external script to set variables:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>Label</key>
    <string>ollama</string>
    <key>StandardOutPath</key>
    <string>/Users/mbentley/.ollama/launchd.stdout.log</string>
    <key>StandardErrorPath</key>
    <string>/Users/mbentley/.ollama/launchd.stderr.log</string>
    <key>EnvironmentVariables</key>
    <dict>
        <key>OLLAMA_HOST</key>
        <string>0.0.0.0:11434</string>
    </dict>
    <key>ProgramArguments</key>
    <array>
      <string>/opt/homebrew/bin/ollama</string>
      <string>serve</string>
    </array>
    <key>UserName</key>
    <string>mbentley</string>
    <key>GroupName</key>
    <string>staff</string>
    <key>ExitTimeOut</key>
    <integer>30</integer>
    <key>Disabled</key>
    <false />
    <key>KeepAlive</key>
    <true />
  </dict>
</plist>
```

In my case, my username is `mbentley` so update accordingly along with the path to `ollama`.  I created mine as `ollama.plist` and copied it to the correct location using `sudo cp ollama.plist /Library/LaunchDaemons/` and then I can start/stop using `sudo launchctl load /Library/LaunchDaemons/ollama.plist` and `sudo launchctl unload /Library/LaunchDaemons/ollama.plist` and it should start on boot.

**Comment by liliang-cn** [comment]
it's a bad design for this HOST thing, why not just read from env or somewhere, or why do we have this restriction at all?

**Comment by qdrddr** [comment]
Added feature request to add CoreML backend to be able to utilize Apple Neural Engine (ANE) alongside GPU and CPU
https://github.com/ollama/ollama/issues/3898

**Comment by aghea** [comment]
You already use plist file.Just need delay ollama 10sec.

Use Script Editor create new create the simple AppleScript file

_delay 10
tell application "Ollama" to run_

In the File menu choose Export, and then export it as type “Application” and name it “LaunchOllamaDelay”. Save it to your user Applications folder.

In System Settings go to Login Items and add the LaunchOllamaDelay application to the startup items. Also remove any existing Ollama startup item.

Now when you restart and sign in, Ollama will launch after 10 seconds which should be enough time for the Launch Agent to have executed.

It's work on sequoia
