### ISSUE TITLE
How to specify which GPU to use when starting Ollama

### ISSUE THREAD

**Issue by lyj555** [ollama/ollama#2968]
Currently, on Linux, there are two GPUs, and it seems that Ollama is occupying a part of both.
<img width="796" alt="企业微信20240307-101729@2x" src="https://github.com/ollama/ollama/assets/20056271/66ececfe-5a0f-471a-a41c-f9373c8510e7">

**Comment by samavedulark** [comment]
if you are using docker, which is a better choice, run the below command.
docker run -d --gpus 'device=1' -v ollama:/root/.ollama -p 11434:11434 --name ollama ollama/ollama

**Comment by jmorganca** [comment]
Hi there, there isn't a direct way to decide which GPU to use for Ollama yet. This is something I hope will becoming soon! In the meantime there are some workarounds like `CUDA_VISIBLE_DEVICES` (https://developer.nvidia.com/blog/cuda-pro-tip-control-gpu-visibility-cuda_visible_devices/) or the Docker workaround @samavedulark mentioned. Stay tuned for more!
