### ISSUE TITLE
Error: Post "http://127.0.0.1:11434/api/chat": read tcp 127.0.0.1:49192->127.0.0.1:11434: wsarecv: An existing connection was forcibly closed by the remote host.

### ISSUE THREAD

**Issue by yxl23** [ollama/ollama#2971]
Error: Post "http://127.0.0.1:11434/api/chat": read tcp 127.0.0.1:49192->127.0.0.1:11434: wsarecv: An existing connection was forcibly closed by the remote host.

**Comment by miharekar** [comment]
Probably duplicate of #2953

**Comment by jmorganca** [comment]
Merging this with #2555

**Comment by Ws612401** [comment]
I have the same question，Run gemma:2b is well,but if i create and run a new model by modelfile, the  question appeared
Ollama version : 0.1.29
system：WIN 11 family

**Comment by xiaogu-space** [comment]
I have the same question ，ollama run qwen2:7b 
Ollama version : 0.3.6
system：WIN 11
