### ISSUE TITLE
ollama free GPU memory itself

### ISSUE THREAD

**Issue by ly0303521** [ollama/ollama#2974]
Hello, nice work.  Below is my problem:
if no request to ollama for a few minutes, it will free GPU memory， when a new request comes, it will load the model and response, so this will about 5 seconds.  How to make  ollama hold the GPU memory

**Comment by dhiltgen** [comment]
See https://github.com/ollama/ollama/blob/main/docs/faq.md#how-do-i-keep-a-model-loaded-in-memory-or-make-it-unload-immediately for instructions on using `keep_alive`
