### ISSUE TITLE
Uninstall CLI ollama on Mac

### ISSUE THREAD

**Issue by X1AOX1A** [ollama/ollama#2980]
How to uninstall CLI ollama on Mac?

**Comment by seanmarshesign** [comment]
Why has this been closed despite no answer to the question?

**Comment by X1AOX1A** [comment]
I found that just need to delete the following items: 

```
/usr/local/bin/ollama
/Applications/Ollama.app/Contents/Resources/ollama
/Users/username/.ollama/models
```

**Comment by MicrobotsMx** [comment]
> I found that just need to delete the following items:
> 
> ```> /Users/username/.ollama/models
> ```
 this is the important, to much GB

**Comment by MicrobotsMx** [comment]
@X1AOX1A thank you man

/Users/username/.ollama/models this is the most important... to much GB
