### ISSUE TITLE
when i restart windows, ollama will open automatically, how can i close the self-start function?

### ISSUE THREAD

**Issue by 08183080** [ollama/ollama#2981]
when i restart windows, ollama will open automatically, how can i close the self-start function?

**Comment by dhiltgen** [comment]
This isn't currently configurable, but you can remove `"~\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\Ollama.lnk"` and it shouldn't autostart on login.  Be aware on the next upgrade, the link will get recreated.

**Comment by MorganMarshall** [comment]
On my windows 11 system ollama isn't listed in the startup apps. For my case I don't see any other way than to manually remove the entry as described above.

**Comment by SHUBHAM157** [comment]
i want to uninstall ollama how to do?

**Comment by dhiltgen** [comment]
@SHUBHAM157 sorry to hear that.  You'll find the uninstaller in the normal  `Add or remove programs` control panel.

**Comment by giuliohome** [comment]
> On my windows 11 system ollama isn't listed in the startup apps. For my case I don't see any other way than to manually remove the entry as described above.

From what I can see, ollama.exe is in the list, but the alphabetical order places it at the end after all the app descriptions that start with an uppercase letter — I assume that's because it starts with a lowercase "o".
