### ISSUE TITLE
Ollama update

### ISSUE THREAD

**Issue by trymeouteh** [ollama/ollama#2987]
Please add a way to update Ollama on Windows, MacOS and Linux when Ollama was installed manually or outside of a package repo or app store.

**Comment by jmorganca** [comment]
Hi there, the macOS and Windows Ollama apps should show an indicator in the taskbar when an update is available. For Linux, re-running the install script should update Ollama (there isn't an auto updater available for Linux). Individual or manual installs of the `ollama` binary don't auto update to avoid any surprises

**Comment by maulikmadhavi** [comment]
Hi all, 
May I know what is the different in ollama version and client version different. On checking `ollama --version`

```
ollama version is 0.1.28
Warning: client version is 0.1.17
```

What should I do to fix ?? Thanks
