### ISSUE TITLE
Support Roberta embedding models

### ISSUE THREAD

**Issue by eliranwong** [ollama/ollama#2992]
can ollama support multi-language embedding model, like "paraphrase-multilingual-mpnet-base-v2"

https://huggingface.co/sentence-transformers/paraphrase-multilingual-mpnet-base-v2

much appreciated

**Comment by jackleeforce** [comment]
you can try solution simlar with comments in https://github.com/ollama/ollama/issues/2965, 

looking a multi-language embedding model which base BERT from https://huggingface.co/spaces/mteb/leaderboard, then convert it into `GGUF` format, then load by `ollama` with customize model.

**Comment by jmorganca** [comment]
Hi there, Ollama doesn't support Roberta yet to my knowledge. However, hoping to support it soon!

**Comment by jmorganca** [comment]
Merging with https://github.com/ollama/ollama/issues/3747
