### ISSUE TITLE
Ollama only runs off CPU in Ubuntu

### ISSUE THREAD

**Issue by uansah** [ollama/ollama#2993]
I am trying to run Dolphin Mistral on CPU and RAM (no GPU) I have 188gb available but it uses 100% of the CPU at full capacity. Before this I was running it on a virtual machine with the same OS and it used RAM.

**Comment by ArchitW** [comment]
2nd to this.

**neofetch**

![image](https://github.com/ollama/ollama/assets/4264602/1ff547f8-fca5-4648-8874-bd07b6a9eb52)

`LLM: tinyllama:latest`
`prompt: what is the meaning of life`

**top**
![image](https://github.com/ollama/ollama/assets/4264602/3564d946-6a9b-45a6-b9a7-a38952023932)

**Comment by aosan** [comment]
CPU would be the biggest performance limitation, even if the model can fit in RAM. In my case, any model fitting in the vRAM of my GPU is fast. Any model not fitting in the vRAM is considerably slower. 

For example, a simple question with a small model with GPU and fitting in vRAM can output 50-60 tokens/s. The same question with large models fitting only in system RAM and using CPU can output only 2-3 tokens/s.

**Comment by jmorganca** [comment]
Hi there, CPU is definitely going to be the bottleneck here. I'm not sure if there's much we can do regarding this issue other than continue making Ollama faster 😊 . Thanks so much for the issue!
