### ISSUE TITLE
ollama pull qwen:1.8b error：Error: Head "https://registry.ollama.ai/v2/library/qwen/blobs/sha256:1296b084ed6bc4c6eaee99255d73e9c715d38e0087b6467fd1c498b908180614": unexpected EOF

### ISSUE THREAD

**Issue by wuwenrui** [ollama/ollama#2996]
ollama pull qwen:1.8b error：
Error: Head "https://registry.ollama.ai/v2/library/qwen/blobs/sha256:1296b084ed6bc4c6eaee99255d73e9c715d38e0087b6467fd1c498b908180614": unexpected EOF

**Comment by jmorganca** [comment]
Merging with https://github.com/ollama/ollama/issues/1036
