### ISSUE TITLE
Can I force ollama to produce shorter responses?

### ISSUE THREAD

**Issue by Anirudh257** [ollama/ollama#2997]
Hi,
     I want to use the llama2 model available in Ollama to produce shorter outputs. I want to use ``max_new_tokens``, ``max_length``
parameters in https://huggingface.co/docs/transformers/en/main_classes/text_generation. Can I prompt the LLM to generate shorter sequences while keeping the meaning same?

There are some approaches given in https://www.reddit.com/r/LocalLLaMA/comments/14k7f5w/any_way_to_limit_the_output_to_a_specific_line/ but they don't work well.

**Comment by aosan** [comment]
One easy way to shorten answers would be to create a new model based on your llama2 model of choice and define your brevity instructions in the Makefile, under the SYSTEM section.

For example, I used at the prompt instructions suitable for a SYSTEM section:

```
ollama run llama2 "Please tell me a joke"

>>> Why don't scientists trust atoms? Because they make up everything! 😂

ollama run llama2 "Please tell me a joke. Don't use more than 5 words"

>>> Sure, here is a short joke:

>>> Kangaroo walks into a bar.
```

**Comment by jmorganca** [comment]
Hi there, you can pass `num_predict` to the API

```
{
  "options": {
    "num_predict": 25
  }
}
```

However, this will truncate messages, so you should also make sure to tell the LLM to answer with short responses in the prompt.
