### ISSUE TITLE
Fine-tuned models, after loading with ollama, the replies are repeated all the time

### ISSUE THREAD

**Issue by cat2353050774** [ollama/ollama#2998]
After fine-tuning the Qwen model, use ollama to load the QWEN model. When a conversation is in progress, the reply will repeat the fine-tuned results all the time. I don't know what the problem is and how to fix it

![image](https://github.com/ollama/ollama/assets/50692992/1e762222-03b9-4337-a21d-883e45b8434d)

**Comment by BruceMacD** [comment]
Hi @cat2353050774 this looks like either a problem with the fine-tune or the quantization. It's possible you over-fit your training data. If this is a smaller model (Qwen 0.5B) quantization can have major effects on the quality of the results, try running the base model and seeing if it has the same problem. 

Resolving this for now as it's not clear if this is an Ollama issue. Let me know if you have any more questions.
