### ISSUE TITLE
Server hangs with no responsewhen running `gemma`

### ISSUE THREAD

**Issue by songsh** [ollama/ollama#3000]
serve dead, how i to check the problem ,where is logs

**Comment by igorschlum** [comment]
Hi @songsh cluld you provide logs and if possible, à script to replicate the issue.

If tou can verify Tagg tou are using the last version of Ollama, it would be great. If Yon can share the configuration of your computer (memory, OS) it could help reproduction the issue or help give explainations.

**Comment by songsh** [comment]
how to find logs?

**Comment by Howe829** [comment]
> how to find logs?

`journalctl -u ollama.service`
I hope it will help.

**Comment by jmorganca** [comment]
Hi there, would it be possible to share the logs? They can be found here: https://github.com/ollama/ollama/blob/main/docs/troubleshooting.md#how-to-troubleshoot-issues

**Comment by songsh** [comment]
sorry,  i find logs too much,  do not find the dead reason, when i meeting next , i will post it.

**Comment by jmorganca** [comment]
Thanks!

**Comment by versteckt0x** [comment]
Fwiw this happens with llama3 and llava as well.

My temporary/hacky work around on OSX until this is resolved.

1.) Add a timeout handler
 
2.) On timeout, call:
 ```typescript
  async function restartOllama() {
      console.log("RESTARTING", "OLLAMA");
      await exec('pkill -9 "Ollama"');
      await sleep(2_000);
      await exec("open -n /Applications/Ollama.app");
      await sleep(5_000);
      console.log("RESTARTED", "OLLAMA");
  }
```

**Comment by dhiltgen** [comment]
If you're still having problems, please share your server log so we can analyze it.  It would also be good to upgrade to the latest release first.
