### ISSUE TITLE
Disable Chat History/Logging Option

### ISSUE THREAD

**Issue by trymeouteh** [ollama/ollama#3002]
Please add a setting to disable chat history/logging option and consider to have this disabled by default. This can increase privacy from preventing others to see what they asked the AI in the past.

Would especially be useful feature for Users and users management
https://github.com/ollama/ollama/issues/2863

**Comment by gunesacar** [comment]
Please also consider disclosing in the README and the FAQ that Ollama keeps a history of your chats by default (e.g., in `~/.ollama/history` on Linux). Many users turn to local models for privacy concerns and for this may be a bitter surprise to many. 

Regardless, thanks for your work and this awesome tool.

**Comment by FrBst** [comment]
This workaround works for me (after deleting the `history` file with all of the warcrimes in it):
```console
$ touch history
$ touch history.tmp
# chattr +i history
# chattr +i history.tmp
```
(yes, it also tries to write to the second file)
(also, I don't know how it does it, but if the `i` attribute is not set, ollama can recreate the file even if the owner is root and no permissions. Creepy)
