### ISSUE TITLE
Bug in main branch: Modelfile FROM instruction is broken

### ISSUE THREAD

**Issue by hyjwei** [ollama/ollama#3003]
It seems that commit 2c017ca44170fb56141bd15d6929390b7be3830a has broken `FROM` instruction in Modelfile. Now `ollama` always treats the string after `FROM` as file name, even though it could be a model name. When a model name is used, ollama will give an open file error.

## How to duplicate the issue
Make a modelfile, like `local.modelfie` with FROM line followed by a model name:
```
FROM phi
```
Create a new model by this modelfile:
```
ollama create local -f local.modelfile
```
And ollama will report error:
```
Error: open <path to model directory>/phi: no such file or directory
```

**Comment by BruceMacD** [comment]
Thanks for reporting this, should be fixed now
