### ISSUE TITLE
feat: add "unload model" command/endpoint

### ISSUE THREAD

**Issue by knoopx** [ollama/ollama#3009]
There's no way to unload a model from VRAM other than killing/restarting ollama and that requires local system access and privileges. Given ollama is mostly used on limited devices, a command/api endpoint would be fantastic.

**Comment by phong-phuong** [comment]
From what I've seen, the model gets unloaded after a certain amount of time of inactivity, or using a model switch.

**Comment by aiseei** [comment]
https://github.com/ollama/ollama/blob/ecc133d843c8567b27ff3bdc9ff811ecad99281a/docs/faq.md?plain=1#L189  use keep_alive param

**Comment by knoopx** [comment]
> https://github.com/ollama/ollama/blob/ecc133d843c8567b27ff3bdc9ff811ecad99281a/docs/faq.md?plain=1#L189
> 
> use keep_alive param

* any negative number which will keep the model loaded in memory (e.g. -1 or "-1m")

Does the opposite actually.

**Comment by alexandervnuchkov** [comment]
Would be great if this default behavior could be set via an environment variable (for Docker), if that is possible

**Comment by aiseei** [comment]
I use a set interval in secs and that has worked well.

**Comment by pdevine** [comment]
Hey @knoopx You can actually do this by calling `curl http://localhost:11434/api/generate -d '{"model": "llama2", "keep_alive": 0}'` (not with `-1` which will always leave the model loaded). That will immediately unload the model without doing any generation.

You can confirm this with:

```
lsof -n | grep ollama | grep blobs | awk "{ print \$9 }"
```

This will show which blob is loaded into memory, and then when you hit the generate endpoint you can see that the blob was unloaded. I'm going to go ahead and close the issue, but feel free to keep commenting.
