### ISSUE TITLE
"Error: invalid file magic" when creating Code Llama model

### ISSUE THREAD

**Issue by AI-Guru** [ollama/ollama#3010]
Hello!

First and foremost, THANKS A LOT for Ollama! Your software is most useful!

I am trying to import a finetune of Code Llama 7B into Ollama. I get this error:

```
$ollama create musicllm -f Modelfile
transferring model data
creating model layer
Error: invalid file magic
```

Here is the model: https://huggingface.co/TristanBehrens/musicllm/tree/main

Here is the Modelfile:

```
FROM model.q5_k_m.gguf
TEMPLATE "[INST] {{ .Prompt }} [/INST]"
```

Any ideas, where I could looks?

All the best,
Tristan

**Comment by BruceMacD** [comment]
Hi @AI-Guru, is `model.q5_k_m.gguf` in the same directory as your Modelfile, and are you on the latest version of Ollama? I just tested this out and it ran for me.

**Comment by AI-Guru** [comment]
@BruceMacD, thanks a lot! Of course it was a git lfs file reference :D
