### ISSUE TITLE
Request to http api from chrome extension not allowed in window

### ISSUE THREAD

**Issue by DominguitoLamo** [ollama/ollama#3016]
I got 403 while request ollama api in localhost from the background.js of chrome extension. It seems the problem caused by cors restriction. However, the source code of ollama indicate that the default config does allow browser extension requests ollama in localhost. Is it the problem of window version?

**Comment by jmorganca** [comment]
Hi @DominguitoLamo chrome extensions can't access Ollama by default due to CORS, however `OLLAMA_ORIGINS` can be customized with `chrome-extensions://` URLs by configuring the Ollama server: https://github.com/ollama/ollama/blob/main/docs/faq.md#how-do-i-configure-ollama-server
