### ISSUE TITLE
how to set another dir of .ollama

### ISSUE THREAD

**Issue by gavinwang668** [ollama/ollama#3017]
The default  dir .ollama is the user_home，I want to choose other dir ,how I can do

**Comment by easp** [comment]
https://github.com/ollama/ollama/blob/main/docs/faq.md

**Comment by jmorganca** [comment]
Hi @gavinwang668 this isn't configurable yet, and isn't something on the roadmap for the time being. Note that the models directory can be customized with `OLLAMA_MODELS`. Would it be possible to know your use case around moving it? That might help design it better 😊

**Comment by stevenhobs** [comment]
try to use ln -sf
