### ISSUE TITLE
API endpoint for encoding and decoding tokens

### ISSUE THREAD

**Issue by Hansson0728** [ollama/ollama#3021]
Please please someone who knows go... add so the internal llamacpp encode endpoint is avilable to the ollama api, so we can use the llm tokenizer to measure how much context we are using accuratly, so we can pick and choose in our memory instead of only trimming from the beginning of our messages, please please

**Comment by Hansson0728** [comment]
Merge #2410 :)

**Comment by levithomason** [comment]
Duplicate #1345. This would be a great feature.

**Comment by jmorganca** [comment]
Will merge this with https://github.com/ollama/ollama/issues/3582
