### ISSUE TITLE
Api vs CLI - API's not responding, however CLI does

### ISSUE THREAD

**Issue by virentakia** [ollama/ollama#3022]
Loading a model via the CLI using the following model file, and the inference speed and output is exactly as expected:
```
FROM solar-10.7b-instruct-q8_0.gguf
TEMPLATE """### System:
{{ .System }}

### User:
{{ .Prompt }}

### Assistant:
"""
PARAMETER num_ctx 10240
PARAMETER stop "</s>"
PARAMETER stop "### System:"
PARAMETER stop "### User:"
PARAMETER stop "### Assistant:"
```

Calling the model via API, using the following payload below, and there is no response for 20min+ (had to cancel execution):
http://localhost:11434/api/generate
```
{
 "model": "solar-10.7b_16k_q8",
 "prompt": "this that",
 "stream": false,
 "options": {
    "temperature": 0.01,
    "stop": ["</s>","### System:","### User:","### Assistant:"],
    "num_ctx": 10240
 }
}
```

Do API calls require more options/parameters to be set?!

**Comment by jmorganca** [comment]
Hi there, what kind of machine is this on, and which version of Ollama did you use it with? I'm having trouble reproducing this. Thanks so much

**Comment by dhiltgen** [comment]
If you're still having problems, please let us know.
