### ISSUE TITLE
`/v1/completions` OpenAI compatible api

### ISSUE THREAD

**Issue by Kreijstal** [ollama/ollama#3027]
This is more flexible than the chat based one, in case you want to do completitions and not chatting, is that okay? Or you want to have more fine grained control.

**Comment by lks-ai** [comment]
BUMP ... I really need this!

**Comment by niyazed** [comment]
I am getting this error `openai.NotFoundError: 404 page not found` when using:

```
return (
            self.client.completions.create(
                user=self.name,
                prompt=messages,
                model=self.model_name,
                max_tokens=self.kwargs.get("max_tokens", 100),
                temperature=self.kwargs.get("temperature", 0.9),
                extra_body=self.kwargs.get("extra_body", {}),
            )
            .choices[0]
            .message.content
        )
```


When I call this function, it is triggering this endpoint: `"/v1/completions"`

**Comment by sammcj** [comment]
@niyazed I believe that error is because Ollama doesn't support the OpenAI compatible API parameter `prompt`.

I believe at the moment it's limited to accepting an array of messages - https://github.com/ollama/ollama/blob/main/docs/openai.md#curl
