### ISSUE TITLE
Unstopped empty lines when I say "hi" to "vicuna" model (temperature: 0.0)

### ISSUE THREAD

**Issue by eliranwong** [ollama/ollama#3031]
Unstopped empty lines when I say "hi" to "vicuna" model (temperature: 0.0)

**Comment by eliranwong** [comment]
I am using using ollama 0.1.28

**Comment by jmorganca** [comment]
Hi there, some models seem to be causing repeated output - it's something being looked into. Sorry you hit this. Closing for #1454
