### ISSUE TITLE
Ollama errors with `msg="Failed to load dynamic library [...]/libext_server.so  exception std::bad_alloc`

### ISSUE THREAD

**Issue by pythonHuang** [ollama/ollama#3032]
Error: Unable to load dynamic library: Unable to load dynamic server library: �Ҳ���ָ����ģ�顣

**Comment by cinnamon17** [comment]
Same here i got this error in the logs

`msg="Failed to load dynamic library /tmp/ollama136388332/cpu_avx2/libext_server.so  exception std::bad_alloc"`

**Comment by Howe829** [comment]
Hi, gemma requires ollama >=0.1.26, you can  check your ollama version using ollama --version.

**Comment by cinnamon17** [comment]
@Howe829 Hi,I have 0.1.28 version

**Comment by Howe829** [comment]
@cinnamon17 It seems there is a problem with loading OLLAMA Library.You can check this Markdown for more information [troubleshooting](https://github.com/ollama/ollama/blob/main/docs/troubleshooting.md)

**Comment by jmorganca** [comment]
Hi @pythonHuang does this only occur with `gemma:2b`, or other models as well? Sorry this happened

**Comment by fraschm1998** [comment]
I got the same error while trying to use wizardlm2:8x22b-q4_0:

```
llm_load_tensors: ggml ctx size =    0.22 MiB
llama_model_load: error loading model: create_tensor: tensor 'blk.0.ffn_gate.0.weight' not found
llama_load_model_from_file: exception loading model
time=2024-04-16T02:36:23.822Z level=WARN source=llm.go:170 msg="Failed to load dynamic library /tmp/ollama1100549038/runners/cpu_avx2/libext_server.so  exception create_tensor: tensor 'blk.0.ffn_gate.0.weight' not found"
```
