### ISSUE TITLE
please create ci/cd action script for release docker-hub

### ISSUE THREAD

**Issue by neozhu** [ollama/ollama#3036]
https://hub.docker.com/r/ollama/ollama are not updated

**Comment by jmorganca** [comment]
Hi there, thanks for creating an issue. The `ollama/ollama` Docker Hub repo should be updated with the 0.1.29 pre-release now. You'll be happy to hear we're working on automating this in https://github.com/ollama/ollama/pull/3028. I'll close this for now, but don't hesitate to open more issues like this 😊
