### ISSUE TITLE
Models disappear when changing the OLLAMA_HOST to 0.0.0.0

### ISSUE THREAD

**Issue by Howe829** [ollama/ollama#3041]
Hi there! I am gonna let devices access ollama through LAN therefore I set the OLLAMA_HOST=0.0.0.0
When I restart  ollama, the models I pulled before disappeared, I don't know whether it is a bug or something else.
In addition, I think we need a 'restart' command to restart the server.
Thanks for help in advance.
Ollama:0.1.28
My OS info: Ubuntu 23.04 Linux-6.2.0-39-generic

**Comment by aosan** [comment]
Are the models becoming not available via the network or via the console?

Ollama can be restarted with `systemctl restart ollama.service`

**Comment by Howe829** [comment]
Hello @aosan , the models are not shown from the `ollama list`, and when I calling the /generate api, it returns 404.
Thanks for the restart command, but it seems have no effect with the OLLAMA_HOST set. The host still stay at 127.0.0.1, when I set the OLLAMA_HOST to 0.0.0.0 and using `systemctl restart ollama.service` to restart ollama.

The host turns to "[::]" when I stop ollama by using `systemctl stop ollama` and start it using `ollama serve`.

**Comment by aosan** [comment]
are you defining `OLLAMA_HOST=0.0.0.0` in `/etc/systemd/system/ollama.service` ?

After you try to put the config in ollama.service, one  way to confirm it listens on 0.0.0.0 on IPv4 is to check it with:

sudo netstat -tapen | grep ollama

and it should show you something like:

`tcp        0      0 0.0.0.0:11434        0.0.0.0:*         LISTEN      968       291784     35171/ollama`

If you see ::, it might be IPv6, where the same netstat command would show you something like this:

`tcp6       0      0 ::1:11434            :::*               LISTEN      0          14221      2114/ollama`

I hope you can get it working, these configuration fogs can be frustrating.

**Comment by jmorganca** [comment]
Hi there, when changing `OLLAMA_HOST` on Linux it's important to do this in the systemd service, since Ollama runs as it's own process and user in the system. You can do that by following [this guide](https://github.com/ollama/ollama/blob/main/docs/faq.md#setting-environment-variables-on-linux). Let me know if that helps!

**Comment by Howe829** [comment]
Thank you very much for your help!

**Comment by Howe829** [comment]
@PittYao You can check [this guide](https://github.com/ollama/ollama/blob/main/docs/faq.md#setting-environment-variables-on-windows) out
