### ISSUE TITLE
BUG - Messages break by word

### ISSUE THREAD

**Issue by TiagoGouvea** [ollama/ollama#3042]
I just downloaded Ollama and tried it using postman with the local Ollama server.

Independently of the model, it always answers with one word per message.

Since I didn't change anything, it seams like a bug.

<img width="911" alt="2024-03-10_11-46-34" src="https://github.com/ollama/ollama/assets/2242549/36afe9f2-40e6-45aa-8ede-1f387670839e">

**Comment by stephensrmmartin** [comment]
Is there a different expected behavior when streaming is enabled?

**Comment by jmorganca** [comment]
Hi @TiagoGouvea this is because streaming is enabled – the response is returned in chunks. To disable streaming use the `"stream": false` parameter

**Comment by TiagoGouvea** [comment]
Yeah, make sense! 

The `stream` by default, was unexpected. 

Thank you
