### ISSUE TITLE
Change model download directory in Ubuntu ( possible bug)

### ISSUE THREAD

**Issue by ejgutierrez74** [ollama/ollama#3045]
Hi im trying ollama, but i need to change the directory where the models are downloaded as default place i have not enough free space.
Following the doc, i edited the service and added a Environment inside Service.
What im doing wrong ? Id like to download llama model at: /media/eduardo/Seagate Backup Plus Drive1/ollama

Also id like to run from anaconda, using python...so any additional steps to run the model once downloaded and started the server ??
Thanks in advance

Ubuntu 22.04 with latest updates

![Captura desde 2024-03-09 21-24-41](https://github.com/ollama/ollama/assets/11474846/e108a90a-6f3c-448e-a512-388b4dbd034e)

**Comment by aosan** [comment]
It seems the documentation expects OLLAMA_MODELS to be setup in systemd ollama.service, which means any new version installation would overwrite the values set in OLLAMA_MODELS. 

If you'd like to use the documentation's method, try to use a destination path for the models without spaces and see the Ollama server can load the new models location.

**Comment by jmorganca** [comment]
Hi there, it's recommended not to edit the systemd file since some variables might need to get set by future versions of Ollama's install script. However, what you can do is create an override file (easiest way is with `systemctl edit ollama.service`) and future installs of Ollama will honor this. Will close this for now but feel free to let me know if you're still having trouble

**Comment by ejgutierrez74** [comment]
@jmorganca 
I change the service as read in documentation. https://github.com/ollama/ollama/blob/main/docs/faq.md
So perhaps a bug, or documentation mistake. In Ubuntu/Linux case : perhaps would be easier simply create a environment variable called OLLAMA_MODELS and then the models would download to that folder. Another idea should be ask in the installation process if you want default place or custom place...you can also ask about ip and port, if you want defaults or want to customize them.

Now im facing a problem:
I cant start the ollama service as you can see:

![imagen](https://github.com/ollama/ollama/assets/11474846/32cb8203-43de-4619-8e89-b5a5ca0c0c20)

Also confirmed by journalctl:

![imagen](https://github.com/ollama/ollama/assets/11474846/e95f9e1d-bfed-4388-8a21-f83ee8026539)


But if i execute ollama serve...starts the server without problems....

<pre>eduardo@MiPcLinux:/$ sudo systemctl status ollama
● ollama.service - Ollama Service
     Loaded: loaded (/etc/systemd/system/ollama.service; enabled; vendor preset: enabled)
     Active: activating (auto-restart) (Result: exit-code) since Mon 2024-03-11 22:09:31 CET; 2s ago
    Process: 552397 ExecStart=/usr/local/bin/ollama serve <font color="#C01C28"><b>(code=exited, status=1/FAILURE)</b></font>
   Main PID: 552397 (code=exited, status=1/FAILURE)
        CPU: 15ms
eduardo@MiPcLinux:/$ ollama serve
time=2024-03-11T22:09:40.576+01:00 level=INFO source=images.go:710 msg=&quot;total blobs: 0&quot;
time=2024-03-11T22:09:40.576+01:00 level=INFO source=images.go:717 msg=&quot;total unused blobs removed: 0&quot;
time=2024-03-11T22:09:40.576+01:00 level=INFO source=routes.go:1021 msg=&quot;Listening on 127.0.0.1:11434 (version 0.1.28)&quot;
time=2024-03-11T22:09:40.576+01:00 level=INFO source=payload_common.go:107 msg=&quot;Extracting dynamic libraries...&quot;
time=2024-03-11T22:09:43.081+01:00 level=INFO source=payload_common.go:146 msg=&quot;Dynamic LLM libraries [cpu_avx cpu_avx2 rocm_v5 rocm_v6 cpu cuda_v11]&quot;
time=2024-03-11T22:09:43.081+01:00 level=INFO source=gpu.go:94 msg=&quot;Detecting GPU type&quot;
time=2024-03-11T22:09:43.081+01:00 level=INFO source=gpu.go:265 msg=&quot;Searching for GPU management library libnvidia-ml.so&quot;
time=2024-03-11T22:09:43.085+01:00 level=INFO source=gpu.go:311 msg=&quot;Discovered GPU libraries: []&quot;
time=2024-03-11T22:09:43.085+01:00 level=INFO source=gpu.go:265 msg=&quot;Searching for GPU management library librocm_smi64.so&quot;
time=2024-03-11T22:09:43.085+01:00 level=INFO source=gpu.go:311 msg=&quot;Discovered GPU libraries: []&quot;
time=2024-03-11T22:09:43.085+01:00 level=INFO source=cpu_common.go:11 msg=&quot;CPU has AVX2&quot;
time=2024-03-11T22:09:43.085+01:00 level=INFO source=routes.go:1044 msg=&quot;no GPU detected&quot;
[GIN] 2024/03/11 - 22:10:05 |<span style="background-color:#26A269"><font color="#FFFFFF"> 200 </font></span>|      67.657µs |       127.0.0.1 |<span style="background-color:#A347BA"><font color="#FFFFFF"> HEAD    </font></span> &quot;/&quot;
[GIN] 2024/03/11 - 22:10:05 |<span style="background-color:#A2734C"><font color="#5E5C64"> 404 </font></span>|      83.922µs |       127.0.0.1 |<span style="background-color:#2AA1B3"><font color="#FFFFFF"> POST    </font></span> &quot;/api/show&quot;
time=2024-03-11T22:10:07.583+01:00 level=INFO source=download.go:136 msg=&quot;downloading 8934d96d3f08 in 39 100 MB part(s)&quot;
time=2024-03-11T22:10:44.737+01:00 level=INFO source=download.go:136 msg=&quot;downloading 8c17c2ebb0ea in 1 7.0 KB part(s)&quot;
time=2024-03-11T22:10:48.057+01:00 level=INFO source=download.go:136 msg=&quot;downloading 7c23fb36d801 in 1 4.8 KB part(s)&quot;
time=2024-03-11T22:10:51.465+01:00 level=INFO source=download.go:136 msg=&quot;downloading 2e0493f67d0c in 1 59 B part(s)&quot;
time=2024-03-11T22:10:55.403+01:00 level=INFO source=download.go:136 msg=&quot;downloading fa304d675061 in 1 91 B part(s)&quot;
time=2024-03-11T22:10:58.994+01:00 level=INFO source=download.go:136 msg=&quot;downloading 42ba7f8a01dd in 1 557 B part(s)&quot;
[GIN] 2024/03/11 - 22:11:12 |<span style="background-color:#26A269"><font color="#FFFFFF"> 200 </font></span>|          1m7s |       127.0.0.1 |<span style="background-color:#2AA1B3"><font color="#FFFFFF"> POST    </font></span> &quot;/api/pull&quot;
[GIN] 2024/03/11 - 22:11:12 |<span style="background-color:#26A269"><font color="#FFFFFF"> 200 </font></span>|    1.270308ms |       127.0.0.1 |<span style="background-color:#2AA1B3"><font color="#FFFFFF"> POST    </font></span> &quot;/api/show&quot;
[GIN] 2024/03/11 - 22:11:12 |<span style="background-color:#26A269"><font color="#FFFFFF"> 200 </font></span>|     236.868µs |       127.0.0.1 |<span style="background-color:#2AA1B3"><font color="#FFFFFF"> POST    </font></span> &quot;/api/show&quot;
time=2024-03-11T22:11:12.448+01:00 level=INFO source=cpu_common.go:11 msg=&quot;CPU has AVX2&quot;
time=2024-03-11T22:11:12.448+01:00 level=INFO source=cpu_common.go:11 msg=&quot;CPU has AVX2&quot;
time=2024-03-11T22:11:12.448+01:00 level=INFO source=llm.go:77 msg=&quot;GPU not available, falling back to CPU&quot;
loading library /tmp/ollama2333286132/cpu_avx2/libext_server.so
time=2024-03-11T22:11:12.453+01:00 level=INFO source=dyn_ext_server.go:90 msg=&quot;Loading Dynamic llm server: /tmp/ollama2333286132/cpu_avx2/libext_server.so&quot;
time=2024-03-11T22:11:12.453+01:00 level=INFO source=dyn_ext_server.go:150 msg=&quot;Initializing llama server&quot;
llama_model_loader: loaded meta data with 23 key-value pairs and 291 tensors from /home/eduardo/.ollama/models/blobs/sha256:8934d96d3f08982e95922b2b7a2c626a1fe873d7c3b06e8e56d7bc0a1fef9246 (version GGUF V3 (latest))
llama_model_loader: Dumping metadata keys/values. Note: KV overrides do not apply in this output.
llama_model_loader: - kv   0:                       general.architecture str              = llama
llama_model_loader: - kv   1:                               general.name str              = LLaMA v2
llama_model_loader: - kv   2:                       llama.context_length u32              = 4096
llama_model_loader: - kv   3:                     llama.embedding_length u32              = 4096
llama_model_loader: - kv   4:                          llama.block_count u32              = 32
llama_model_loader: - kv   5:                  llama.feed_forward_length u32              = 11008
llama_model_loader: - kv   6:                 llama.rope.dimension_count u32              = 128
llama_model_loader: - kv   7:                 llama.attention.head_count u32              = 32
llama_model_loader: - kv   8:              llama.attention.head_count_kv u32              = 32
llama_model_loader: - kv   9:     llama.attention.layer_norm_rms_epsilon f32              = 0.000010
llama_model_loader: - kv  10:                          general.file_type u32              = 2
llama_model_loader: - kv  11:                       tokenizer.ggml.model str              = llama
llama_model_loader: - kv  12:                      tokenizer.ggml.tokens arr[str,32000]   = [&quot;&lt;unk&gt;&quot;, &quot;&lt;s&gt;&quot;, &quot;&lt;/s&gt;&quot;, &quot;&lt;0x00&gt;&quot;, &quot;&lt;...
llama_model_loader: - kv  13:                      tokenizer.ggml.scores arr[f32,32000]   = [0.000000, 0.000000, 0.000000, 0.0000...
llama_model_loader: - kv  14:                  tokenizer.ggml.token_type arr[i32,32000]   = [2, 3, 3, 6, 6, 6, 6, 6, 6, 6, 6, 6, ...
llama_model_loader: - kv  15:                      tokenizer.ggml.merges arr[str,61249]   = [&quot;▁ t&quot;, &quot;e r&quot;, &quot;i n&quot;, &quot;▁ a&quot;, &quot;e n...
llama_model_loader: - kv  16:                tokenizer.ggml.bos_token_id u32              = 1
llama_model_loader: - kv  17:                tokenizer.ggml.eos_token_id u32              = 2
llama_model_loader: - kv  18:            tokenizer.ggml.unknown_token_id u32              = 0
llama_model_loader: - kv  19:               tokenizer.ggml.add_bos_token bool             = true
llama_model_loader: - kv  20:               tokenizer.ggml.add_eos_token bool             = false
llama_model_loader: - kv  21:                    tokenizer.chat_template str              = {% if messages[0][&apos;role&apos;] == &apos;system&apos;...
llama_model_loader: - kv  22:               general.quantization_version u32              = 2
llama_model_loader: - type  f32:   65 tensors
llama_model_loader: - type q4_0:  225 tensors
llama_model_loader: - type q6_K:    1 tensors
llm_load_vocab: special tokens definition check successful ( 259/32000 ).
llm_load_print_meta: format           = GGUF V3 (latest)
llm_load_print_meta: arch             = llama
llm_load_print_meta: vocab type       = SPM
llm_load_print_meta: n_vocab          = 32000
llm_load_print_meta: n_merges         = 0
llm_load_print_meta: n_ctx_train      = 4096
llm_load_print_meta: n_embd           = 4096
llm_load_print_meta: n_head           = 32
llm_load_print_meta: n_head_kv        = 32
llm_load_print_meta: n_layer          = 32
llm_load_print_meta: n_rot            = 128
llm_load_print_meta: n_embd_head_k    = 128
llm_load_print_meta: n_embd_head_v    = 128
llm_load_print_meta: n_gqa            = 1
llm_load_print_meta: n_embd_k_gqa     = 4096
llm_load_print_meta: n_embd_v_gqa     = 4096
llm_load_print_meta: f_norm_eps       = 0.0e+00
llm_load_print_meta: f_norm_rms_eps   = 1.0e-05
llm_load_print_meta: f_clamp_kqv      = 0.0e+00
llm_load_print_meta: f_max_alibi_bias = 0.0e+00
llm_load_print_meta: n_ff             = 11008
llm_load_print_meta: n_expert         = 0
llm_load_print_meta: n_expert_used    = 0
llm_load_print_meta: pooling type     = 0
llm_load_print_meta: rope type        = 0
llm_load_print_meta: rope scaling     = linear
llm_load_print_meta: freq_base_train  = 10000.0
llm_load_print_meta: freq_scale_train = 1
llm_load_print_meta: n_yarn_orig_ctx  = 4096
llm_load_print_meta: rope_finetuned   = unknown
llm_load_print_meta: model type       = 7B
llm_load_print_meta: model ftype      = Q4_0
llm_load_print_meta: model params     = 6.74 B
llm_load_print_meta: model size       = 3.56 GiB (4.54 BPW) 
llm_load_print_meta: general.name     = LLaMA v2
llm_load_print_meta: BOS token        = 1 &apos;&lt;s&gt;&apos;
llm_load_print_meta: EOS token        = 2 &apos;&lt;/s&gt;&apos;
llm_load_print_meta: UNK token        = 0 &apos;&lt;unk&gt;&apos;
llm_load_print_meta: LF token         = 13 &apos;&lt;0x0A&gt;&apos;
llm_load_tensors: ggml ctx size =    0.11 MiB
llm_load_tensors:        CPU buffer size =  3647.87 MiB
..................................................................................................
llama_new_context_with_model: n_ctx      = 2048
llama_new_context_with_model: freq_base  = 10000.0
llama_new_context_with_model: freq_scale = 1
llama_kv_cache_init:        CPU KV buffer size =  1024.00 MiB
llama_new_context_with_model: KV self size  = 1024.00 MiB, K (f16):  512.00 MiB, V (f16):  512.00 MiB
llama_new_context_with_model:        CPU input buffer size   =    13.02 MiB
llama_new_context_with_model:        CPU compute buffer size =   160.00 MiB
llama_new_context_with_model: graph splits (measure): 1
{&quot;function&quot;:&quot;initialize&quot;,&quot;level&quot;:&quot;INFO&quot;,&quot;line&quot;:433,&quot;msg&quot;:&quot;initializing slots&quot;,&quot;n_slots&quot;:1,&quot;tid&quot;:&quot;140282507007552&quot;,&quot;timestamp&quot;:1710191474}
{&quot;function&quot;:&quot;initialize&quot;,&quot;level&quot;:&quot;INFO&quot;,&quot;line&quot;:442,&quot;msg&quot;:&quot;new slot&quot;,&quot;n_ctx_slot&quot;:2048,&quot;slot_id&quot;:0,&quot;tid&quot;:&quot;140282507007552&quot;,&quot;timestamp&quot;:1710191474}
time=2024-03-11T22:11:14.803+01:00 level=INFO source=dyn_ext_server.go:161 msg=&quot;Starting llama main loop&quot;
{&quot;function&quot;:&quot;update_slots&quot;,&quot;level&quot;:&quot;INFO&quot;,&quot;line&quot;:1565,&quot;msg&quot;:&quot;all slots are idle and system prompt is empty, clear the KV cache&quot;,&quot;tid&quot;:&quot;140280429762112&quot;,&quot;timestamp&quot;:1710191474}
[GIN] 2024/03/11 - 22:11:14 |<span style="background-color:#26A269"><font color="#FFFFFF"> 200 </font></span>|  2.649050816s |       127.0.0.1 |<span style="background-color:#2AA1B3"><font color="#FFFFFF"> POST    </font></span> &quot;/api/chat&quot;
{&quot;function&quot;:&quot;launch_slot_with_data&quot;,&quot;level&quot;:&quot;INFO&quot;,&quot;line&quot;:823,&quot;msg&quot;:&quot;slot is processing task&quot;,&quot;slot_id&quot;:0,&quot;task_id&quot;:0,&quot;tid&quot;:&quot;140280429762112&quot;,&quot;timestamp&quot;:1710191555}
{&quot;function&quot;:&quot;update_slots&quot;,&quot;level&quot;:&quot;INFO&quot;,&quot;line&quot;:1796,&quot;msg&quot;:&quot;slot progression&quot;,&quot;n_past&quot;:0,&quot;n_prompt_tokens_processed&quot;:28,&quot;slot_id&quot;:0,&quot;task_id&quot;:0,&quot;tid&quot;:&quot;140280429762112&quot;,&quot;timestamp&quot;:1710191555}
{&quot;function&quot;:&quot;update_slots&quot;,&quot;level&quot;:&quot;INFO&quot;,&quot;line&quot;:1821,&quot;msg&quot;:&quot;kv cache rm [p0, end)&quot;,&quot;p0&quot;:0,&quot;slot_id&quot;:0,&quot;task_id&quot;:0,&quot;tid&quot;:&quot;140280429762112&quot;,&quot;timestamp&quot;:1710191555}
{&quot;function&quot;:&quot;print_timings&quot;,&quot;level&quot;:&quot;INFO&quot;,&quot;line&quot;:257,&quot;msg&quot;:&quot;prompt eval time     =    4387.35 ms /    28 tokens (  156.69 ms per token,     6.38 tokens per second)&quot;,&quot;n_prompt_tokens_processed&quot;:28,&quot;n_tokens_second&quot;:6.381986023906463,&quot;slot_id&quot;:0,&quot;t_prompt_processing&quot;:4387.349,&quot;t_token&quot;:156.69103571428573,&quot;task_id&quot;:0,&quot;tid&quot;:&quot;140280429762112&quot;,&quot;timestamp&quot;:1710191615}
{&quot;function&quot;:&quot;print_timings&quot;,&quot;level&quot;:&quot;INFO&quot;,&quot;line&quot;:271,&quot;msg&quot;:&quot;generation eval time =   55502.84 ms /   270 runs   (  205.57 ms per token,     4.86 tokens per second)&quot;,&quot;n_decoded&quot;:270,&quot;n_tokens_second&quot;:4.864616199708855,&quot;slot_id&quot;:0,&quot;t_token&quot;:205.56606296296297,&quot;t_token_generation&quot;:55502.837,&quot;task_id&quot;:0,&quot;tid&quot;:&quot;140280429762112&quot;,&quot;timestamp&quot;:1710191615}
{&quot;function&quot;:&quot;print_timings&quot;,&quot;level&quot;:&quot;INFO&quot;,&quot;line&quot;:281,&quot;msg&quot;:&quot;          total time =   59890.19 ms&quot;,&quot;slot_id&quot;:0,&quot;t_prompt_processing&quot;:4387.349,&quot;t_token_generation&quot;:55502.837,&quot;t_total&quot;:59890.186,&quot;task_id&quot;:0,&quot;tid&quot;:&quot;140280429762112&quot;,&quot;timestamp&quot;:1710191615}
{&quot;function&quot;:&quot;update_slots&quot;,&quot;level&quot;:&quot;INFO&quot;,&quot;line&quot;:1627,&quot;msg&quot;:&quot;slot released&quot;,&quot;n_cache_tokens&quot;:298,&quot;n_ctx&quot;:2048,&quot;n_past&quot;:297,&quot;n_system_tokens&quot;:0,&quot;slot_id&quot;:0,&quot;task_id&quot;:0,&quot;tid&quot;:&quot;140280429762112&quot;,&quot;timestamp&quot;:1710191615,&quot;truncated&quot;:false}
[GIN] 2024/03/11 - 22:13:35 |<span style="background-color:#26A269"><font color="#FFFFFF"> 200 </font></span>|  59.89459615s |       127.0.0.1 |<span style="background-color:#2AA1B3"><font color="#FFFFFF"> POST    </font></span> &quot;/api/chat&quot;
[GIN] 2024/03/11 - 22:15:32 |<span style="background-color:#26A269"><font color="#FFFFFF"> 200 </font></span>|     318.081µs |       127.0.0.1 |<span style="background-color:#12488B"><font color="#FFFFFF"> GET     </font></span> &quot;/&quot;
[GIN] 2024/03/11 - 22:15:33 |<span style="background-color:#A2734C"><font color="#5E5C64"> 404 </font></span>|       4.934µs |       127.0.0.1 |<span style="background-color:#12488B"><font color="#FFFFFF"> GET     </font></span> &quot;/favicon.ico&quot;
[GIN] 2024/03/11 - 22:15:34 |<span style="background-color:#26A269"><font color="#FFFFFF"> 200 </font></span>|      15.268µs |       127.0.0.1 |<span style="background-color:#12488B"><font color="#FFFFFF"> GET     </font></span> &quot;/&quot;
[GIN] 2024/03/11 - 22:15:35 |<span style="background-color:#26A269"><font color="#FFFFFF"> 200 </font></span>|       8.431µs |       127.0.0.1 |<span style="background-color:#12488B"><font color="#FFFFFF"> GET     </font></span> &quot;/&quot;
[GIN] 2024/03/11 - 22:15:35 |<span style="background-color:#26A269"><font color="#FFFFFF"> 200 </font></span>|       6.891µs |       127.0.0.1 |<span style="background-color:#12488B"><font color="#FFFFFF"> GET     </font></span> &quot;/&quot;
[GIN] 2024/03/11 - 22:15:36 |<span style="background-color:#26A269"><font color="#FFFFFF"> 200 </font></span>|       7.598µs |       127.0.0.1 |<span style="background-color:#12488B"><font color="#FFFFFF"> GET     </font></span> &quot;/&quot;
[GIN] 2024/03/11 - 22:15:36 |<span style="background-color:#26A269"><font color="#FFFFFF"> 200 </font></span>|      953.62µs |       127.0.0.1 |<span style="background-color:#12488B"><font color="#FFFFFF"> GET     </font></span> &quot;/&quot;
[GIN] 2024/03/11 - 22:15:46 |<span style="background-color:#26A269"><font color="#FFFFFF"> 200 </font></span>|     131.265µs |       127.0.0.1 |<span style="background-color:#A347BA"><font color="#FFFFFF"> HEAD    </font></span> &quot;/&quot;
[GIN] 2024/03/11 - 22:15:46 |<span style="background-color:#26A269"><font color="#FFFFFF"> 200 </font></span>|    2.525828ms |       127.0.0.1 |<span style="background-color:#12488B"><font color="#FFFFFF"> GET     </font></span> &quot;/api/tags&quot;
[GIN] 2024/03/11 - 22:16:06 |<span style="background-color:#26A269"><font color="#FFFFFF"> 200 </font></span>|      38.859µs |       127.0.0.1 |<span style="background-color:#A347BA"><font color="#FFFFFF"> HEAD    </font></span> &quot;/&quot;
[GIN] 2024/03/11 - 22:16:18 |<span style="background-color:#26A269"><font color="#FFFFFF"> 200 </font></span>|      43.731µs |       127.0.0.1 |<span style="background-color:#A347BA"><font color="#FFFFFF"> HEAD    </font></span> &quot;/&quot;


</pre>

And somehow is running llama2:

![imagen](https://github.com/ollama/ollama/assets/11474846/c32982b7-116d-401c-9474-86b4b977eead)


Also no idea where the model has been downloaded....is there anyway to know where the model have been downloaded ? I cant find it in /usr/share/ollama nor /media/Samsung/ollama_models ( customized folder i wanted to download)

**Comment by ejgutierrez74** [comment]
@jmorganca 

I write this post to add more information:

1 - As you mentioned : I edited `sudo systemctl edit ollama.service`


![imagen](https://github.com/ollama/ollama/assets/11474846/d82ca623-5b89-4e8c-8b25-81a82de0b7b3)

And the /media/Samsung/ollama_models is empty....

![imagen](https://github.com/ollama/ollama/assets/11474846/63001767-af41-4f47-823a-5c6506f3599d)

So seems here a bug ( as said before the doc says you have to change the ollama.service file)

2 - ollama serve vs systemd

I run systemd start ollama ( today i booted my computer), and fails

![imagen](https://github.com/ollama/ollama/assets/11474846/9449fd23-8a4f-4a06-abd1-f3339778ce91)

But if i run ollama serve it seems to work ( i again just to be sure i started ollama, then see the status...and executed ollama serve):

![imagen](https://github.com/ollama/ollama/assets/11474846/a4c14ca7-4994-4497-a634-1ebad8cd1e77)

And in other tab seems ollama works:
![imagen](https://github.com/ollama/ollama/assets/11474846/352524e4-ce54-4b9d-8ec1-e719f4a16b1d)

3 - where are the model downloaded:
As posted before /media/Samsung/ollama_models -> as you can see is empty
/home/ollama -> doesnt exist
![imagen](https://github.com/ollama/ollama/assets/11474846/9dbb5c4e-27ce-4503-b756-eab30b9efd72)

and /usr/share/ollama ->
![imagen](https://github.com/ollama/ollama/assets/11474846/6b2e23b5-f245-4393-8b34-0ffde5705197)


im going mad ;)

Thans for your help

Editing post for update: Finally i found the ollama model at /home/eduardo/.ollama, but it shouldnt be there as default directory is /usr/share/ollama/.ollama, and i set the environment variable OLLAMA_MODEL to point to /media/Samsung/ollama_models

**Comment by vincent6634** [comment]
Hello everyone,

Like ejgutierrez74, I wanted to change the template directory and I followed the documentation on [this page](https://github.com/ollama/ollama/blob/main/docs/faq.md#setting-environment-variables-on-linux).
So I edited the ollama.service file with the following command:
`sudo nano /etc/systemd/system/ollama.service`
I added **Environment="OLLAMA_MODELS=/home/vincent/Apps/Ollama-models"**

```
[Unit]
Description=Ollama Service
After=network-online.target

[Service]
ExecStart=/usr/local/bin/ollama serve
User=ollama
Group=ollama
Restart=always
RestartSec=3
Environment="PATH=/home/vincent/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/>
Environment="OLLAMA_MODELS=/home/vincent/Apps/Ollama-models"

[Install]
WantedBy=default.target
```
I have reloades systemd and restart Ollama:

```
systemctl daemon-reload
systemctl restart ollama
```
I tried to relaunch ollama
```
$ ollama run mistral
Error: could not connect to ollama app, is it running?
```
I told myself it was a problem of privilege.
So I changed the name of the group and the owner of the directory containing the model 
`sudo chmod ollama:ollama /home/vincent/Apps/Ollama-models`

The error persists
For the moment, the only workaround is to run the command 
`ollama serve `
in a tab, and
`ollama run ModelName` in onther
to download the models to ~/.ollama/models
--------
Ollama v 0.1.29
Ubuntu 23.10

**Comment by ejgutierrez74** [comment]
Why is closed ? Seems important bug for linux/ubuntu users.....

**Comment by tHeStRyNg** [comment]
Same problem here
Running ubuntu 22 and simply cant 
```ollama pull QuantFactory/Meta-Llama-3-8B-Instruct-GGUF:Q3_K_S```
Something with registry ?

**Comment by zamzx** [comment]
Ollama is great.

But it would be greater if you simply fixed OLLAMA_MODELS to work for everyone who has to run their models on seperate drives.

Ollama pretty much requires a redownload of all models every time you update. And that you run your own start script.

Room for improvement. Would be nice to have an officially supported way of it working, instead of expecting users to trudge through the comments to hack something together.

~ loving ollama user

**Comment by tfritz1982** [comment]
I know this is an old post but the issue is still active. You have to change the directory that is in /etc/passwd for Ollama. It will something "/usr/share/ollama" you need to change this to "/<the full path to the directory you want to use>. Before reload Ollama make sure you create the new directory you wantg to use and chown it to ollama:ollama.
