### ISSUE TITLE
API: /v1/models got 404 page not found

### ISSUE THREAD

**Issue by github-lly** [ollama/ollama#3050]
Ollama is running, but _/v1/models_ got 404 page not found

![image](https://github.com/ollama/ollama/assets/159240728/b7cd8321-604b-4b78-9190-2fb1a4c57ea3)

![image](https://github.com/ollama/ollama/assets/159240728/2687a3c7-1b1a-415e-acc4-ad894e26da43)

**Comment by jmorganca** [comment]
Hi there, Ollama doesn't have a `/v1/models` OpenAI compatible endpoint yet. However, you can call `GET /api/tags`. Will merge this with #2430
