### ISSUE TITLE
Error when disk with temp dirs (e.g. `/tmp`) is full

### ISSUE THREAD

**Issue by hanaidong** [ollama/ollama#3051]
I tested it will start failed, 
![image](https://github.com/ollama/ollama/assets/139938824/69481726-35b0-4119-bfea-15295fee80ad)

This causes the systemd to constantly restart this service and download many temporary files that will not be deleted yet

![image](https://github.com/ollama/ollama/assets/139938824/f1730daa-293b-49ee-b66e-a75cc02e41e2)

key error

```
Error: unable to initialize llm library copy payload llama.cpp/build/linux/x86_64/cuda_v11/lib/libcublasLt.so.11.gz: gzip: invalid checksum
```

**Comment by dhiltgen** [comment]
We should harden the extraction logic to clean up after itself on error.
