### ISSUE TITLE
Collection make_this_parameterizable_per_api_call not found

### ISSUE THREAD

**Issue by margielapng** [ollama/ollama#3052]
My privateGPT is running , however when i send it a message such as "hi" it displays a "Collection make_this_parameterizable_per_api_call not found" error  and when i ask a question it displays a "Error
NoneType' object has no attribute 'split" error , how do i fix this?

**Comment by jmorganca** [comment]
Hi there you may want to ask this in the awesome PrivateGPT repo https://github.com/imartinez/privateGPT. Hope this helps!

**Comment by 864258496** [comment]
Hi,I encountered the same problem, how should I solve it?

**Comment by dushyantss** [comment]
If someone stumbles here, despite it not being the right place to ask. The issue(at least for me) was that if there's no files uploaded you gotta select this option:

<img width="1225" alt="image" src="https://github.com/ollama/ollama/assets/8743041/38f7c840-d6f9-4156-8f8f-5a127d2c7b98">
