### ISSUE TITLE
Immense amount of disk reads when paging with `mmap`

### ISSUE THREAD

**Issue by hedleyroos** [ollama/ollama#3054]
Querying the `/generate` API with the llama2 models works as expected. I append `keep_alive=0` to the query string to keep the model in RAM, and from `iotop` I can see it immediately loads the model in RAM (I am in CPU only mode). The loading also seems to take place in a single sub-process or thread - unsure which since I don't know the underlying design, but it looks like a sub-process.

However, when switching to the llama2:70b model things change. It does the same single process loading of the model and takes longer because the model is naturally bigger, but thereafter 16 ollama processes are constantly reading from disk at about 140MB/s, and as a result generation is extremely slow. I have a 7950x, so the 16 processes make sense, but I do have 64GB RAM, and this should be enough for the model. `top` shows RAM usage at 34GB, but since there is memory mapping behind the scenes virt goes to about 46GB as expected. 

I cannot find a way to prevent ollama from constantly hammering the disk with the llama2:70b model. Unfortunately I don't know Golang, but could it be an issue with the memory mapping not being correctly shared between processes?

**Comment by hedleyroos** [comment]
Answering my own question after spotting https://github.com/ollama/ollama/blob/main/docs/api.md.

Pass "use_mmap": false as an option in the API call. It solves everything.

**Comment by jmorganca** [comment]
Hi @hedleyroos thanks for the issue. This is indeed because llama2:70b is quite big and may be paged to disk. I've updated as we can probably disable mmap if the model is too big to fit into memory. How much RAM do you have on your machine?

**Comment by sytelus** [comment]
How can you disable so model is fully loaded in RAM? I am testing this on machine with huge RAM in CPU only model. I see there is some option for API but is there any way for CLI?

**Comment by kotatsuyaki** [comment]
I set `/set parameter use_mmap 0` (along with `/set parameter num_gpu 0` for CPU-only inference) from the ollama CLI, and from the system monitor it seemed like the model is loaded into the memory.

**Comment by dhiltgen** [comment]
We've been adjusting our default selection algorithm on when to use mmap vs. when to do normal file reads.  Our current algorithm looks at the amount of Free memory in the system and if the model is larger than that, we switch to file reads so that other memory usage can be pushed into swap to make room, which should help avoid mmap induced thrashing.  @hedleyroos you should give the latest version a try and see if the default algorithm works out for you, but you can force the desired behavior with `use_mmap 0`

**Comment by hedleyroos** [comment]
@dhiltgen  I have tested with 0.3.2 and it works correctly now.
