### ISSUE TITLE
run Mixtal 8x7b ERROR

### ISSUE THREAD

**Issue by digicr** [ollama/ollama#3057]
I ran Mixtal 8x7b and was able to load it onto the GPU successfully. However, after raising a question,
the system gave random answers and often repeated the same content over and over with no end in sight.

NAME                            ID              SIZE    MODIFIED
dolphin-mixtral:8x7b-v2.7-q2_K  3705eacb022d    15 GB   6 days ago
mixtral:8x7b-text-v0.1-q2_K     c657cacc0023    15 GB   5 days ago

**Comment by jmorganca** [comment]
Merging with https://github.com/ollama/ollama/issues/1454
