### ISSUE TITLE
LLaVA:34b is not working in the `latest` docker image

### ISSUE THREAD

**Issue by FrostFlowerFairy** [ollama/ollama#3058]
LLaVA:34b is working fine in Ollama:0.1.27, but now in the latest version it is not working and I am getting an error about the image not being found in the request.
So I downgraded the docker image and it worked fine again.

**Comment by jmorganca** [comment]
Hi there, I'm sorry about this. Working on a fix now in https://github.com/ollama/ollama/pull/3064, and will be 0.1.29
