### ISSUE TITLE
Ollama Server is unavailable after some time

### ISSUE THREAD

**Issue by vrubzov1957** [ollama/ollama#3060]
Sometimes after a certain amount of time working with the same AI model (after about an hour) the Ollama server becomes unavailable. 

I have to start it via "ollama run MODEL" - server starts in the background, but closes again after a while.
Very inconvenient when we use a different frontend (like Ollama Web-UI) - we have to connect to the PC manually, and do the Ollama server startup again

LOG
[server_ollama.log](https://github.com/ollama/ollama/files/14562402/server_ollama.log)

In this logs the server became unavailable, then manually started, then became unavailable again. Periods 1-2 hours

**Comment by jmorganca** [comment]
Sorry about this. This seems to be an out of memory error on CUDA, I'll merge this with https://github.com/ollama/ollama/issues/1952

**Comment by vrubzov1957** [comment]
@jmorganca ok. 
Also I did note in #1952 - because may be different root cause of it. May be memory leaking. Because with selected mode it works perfect, VRAM for model is enough. And after 20-30 newly-topic promts Ollama server goes offline.
