### ISSUE TITLE
How to specify a port number for `ollama serve`?

### ISSUE THREAD

**Issue by soonhokong** [ollama/ollama#3061]
Is there a way to specify a different port number (other than 11434) when I start `ollama serve`?

**Comment by angel1254mc** [comment]
Based on the [FAQ](https://github.com/ollama/ollama/blob/f878e91070af750709f1b3195eeb9fbdcaad2bef/docs/faq.md?plain=1#L39-L42) and [this chunk of code](https://github.com/ollama/ollama/blob/f878e91070af750709f1b3195eeb9fbdcaad2bef/api/client.go#L46-L59), it looks like you can set a local environment variable `OLLAMA_HOST` to something like `http://localhost:YOUR_PORT_HERE` to specify the port you want the server listening on.

**Comment by soonhokong** [comment]
@angel1254mc , thank you. But my question is not about how to connect to a remote server (using `OLLAMA_HOST`. It's about how to change the port number from the server-side.

**Comment by soonhokong** [comment]
Got it. Thanks!
