### ISSUE TITLE
Ubuntu: Snap installation

### ISSUE THREAD

**Issue by MartinsRepo** [ollama/ollama#3062]
Installing Ollama with:
sudo snap install ollama --beta 
is working correctly. Ollama list is showing it'working. Changing the default folder with:
sudo snap set ollama models=/path to my new ollama model storage/ is accepted.
Another ollama list gives:
Error: could not connect to ollama app, is it running?
After a restart of the system the same effect.

**Comment by jmorganca** [comment]
Hi @MartinsRepo I'm not quite sure how the snap repo is set up and am coming up to speed on that. However https://github.com/mz2 might know how to help!
