### ISSUE TITLE
CLBlast for intergrated gpu support

### ISSUE THREAD

**Issue by joshuachris2001** [ollama/ollama#3066]
is there support to compile ollama with CLBlast for a device with a integrated non AMD GPU?
I've tried compiling with: CLBlast_DIR=/usr/lib/cmake/CLBlast go generate -tags clbast ./...
yet I still get "no GPU detected"

the I-GPU I'm trying to get CLBlast to work on is a `Intel HD Graphics 5500` when llama is explicitly compiled for the slight boost in speed is still helpful especially with CLIP.

**Comment by jmorganca** [comment]
Closing for https://github.com/ollama/ollama/issues/2637 - thanks for the issue!
