### ISSUE TITLE
CUDA error: an illegal memory access was encountered

### ISSUE THREAD

**Issue by lizhichao999** [ollama/ollama#3074]
ollama run llama2
When I executed the command: ollama run llama2, an error occurred related to the data information.
![1710236043402](https://github.com/ollama/ollama/assets/34128722/098fb024-f6f6-419e-99a0-354d29eecd2d)

I only have a 128G GPU. Do I need more than 2 GPUs? I can run it on my local laptop with 2 GPUs without any errors.

**Comment by dhiltgen** [comment]
Could you share some additional information about your system?  What GPU do you have?  Windows version, nvidia driver version.

This might be a software defect, but I've also seen this behavior from a system with a hardware fault.  Have you run other applications on your GPU without problem?

**Comment by lizhichao999** [comment]
system：Windows Server 2022
GPU： NVIDIA RTX A6000
nvidia driver version：31.0.15.5123

> Could you share some additional information about your system? What GPU do you have? Windows version, nvidia driver version.
> 
> This might be a software defect, but I've also seen this behavior from a system with a hardware fault. Have you run other applications on your GPU without problem?

system：Windows Server 2022
GPU： NVIDIA RTX A6000
nvidia driver version：31.0.15.5123

**Comment by dhiltgen** [comment]
Doing a quick code inspection between 0.1.27 (the version your running based on error line numbers) and 0.1.29, I see quite a bit of changes have been made upstream in llama.cpp in ggml-cuda.cu (where this crash is taking place)  I haven't root caused your crash yet, but you might want to try out [0.1.29 ](https://github.com/ollama/ollama/releases/tag/v0.1.29)and see if it fixes the problem.  If not, we'll keep digging to understand where the defect is.

**Comment by lizhichao999** [comment]
> Doing a quick code inspection between 0.1.27 (the version you're running based on error line numbers) and 0.1.29, I see quite a bit of changes have been made upstream in llama.cpp in ggml-cuda.cu (where this crash is taking place) I haven't root caused your crash yet, but you might want to try out [0.1.29 ](https://github.com/ollama/ollama/releases/tag/v0.1.29)and see if it fixes the problem. If not, we'll keep digging to understand where the defect is.

I have updated the software to version 0.1.29, but the issue still persists.
![1710376844249](https://github.com/ollama/ollama/assets/34128722/221f2ec6-f452-40b7-847e-99fdd3ecd730)

**Comment by dhiltgen** [comment]
Is this still an issue with the latest version?  If so, can you share a server log with OLLAMA_DEBUG=1 set?
