### ISSUE TITLE
Support for Breeze-7b_instruct-v1_0 model

### ISSUE THREAD

**Issue by ywchiu** [ollama/ollama#3075]
This model was developed by MediaTek in Taiwan, and it incorporates Traditional Chinese, which is essential for users in Taiwan. Please include it in Ollama.
https://huggingface.co/MediaTek-Research/Breeze-7B-Instruct-v1_0

**Comment by aosan** [comment]
Breeze-7B-Instruct-v1_0 can be added in Ollama version 0.1.29 (pre-release) with experimental support for safetensors.

Meanwhile, you can use it in Ollama by following these steps:

[https://github.com/ollama/ollama/blob/main/docs/import.md](url)

Once you tested it, you can create an account on [https://ollama.com](url) and publish it for everyone in Taiwan to enjoy!

**Comment by bmizerany** [comment]
Thank you for the heads up on the model. AS @aosan mentioned: Ollama makes it easy to publish your own model at-will. :) 

I'm going to close this for now, but please feel free to reopen if you have any issues and we can help.

**Comment by ywchiu** [comment]
> Breeze-7B-Instruct-v1_0 can be added in Ollama version 0.1.29 (pre-release) with experimental support for safetensors.
> 
> Meanwhile, you can use it in Ollama by following these steps:
> 
> [https://github.com/ollama/ollama/blob/main/docs/import.md](url)
> 
> Once you tested it, you can create an account on [https://ollama.com](url) and publish it for everyone in Taiwan to enjoy!

Thanks a million, it works
