### ISSUE TITLE
how unistall ollama from my linux wsl ?

### ISSUE THREAD

**Issue by mabreu2022** [ollama/ollama#3079]
Guys,

How can i unistall ollama from my ubuntu wsl?

**Comment by dhiltgen** [comment]
Docs are here - https://github.com/ollama/ollama/blob/main/docs/linux.md#uninstall

**Comment by 80avin** [comment]
A tip for those coming in future.

I found it better to use [mise](https://mise.jdx.dev/) to install ollama using `mise use -g ollama` than install it from the original script. This makes the uninstall as well as the upgrade easy enough.
Moreover, it installs the ollama in user directory than in root, which is another advantage.

**Comment by mbary** [comment]
I followed the uninstall instructions.

Prior to uninstalling, I manually removed (ollama rm <model>) every single model I had.
But the disk space doesn't seem to have been freed?
Am I missing something? 
I'd like my GBs back

**Comment by StevenZev** [comment]
> I followed the uninstall instructions.
> 
> Prior to uninstalling, I manually removed (ollama rm ) every single model I had. But the disk space doesn't seem to have been freed? Am I missing something? I'd like my GBs back

See here: https://github.com/microsoft/WSL/issues/4699
