### ISSUE TITLE
Homebrew cask

### ISSUE THREAD

**Issue by jmorganca** [ollama/ollama#308]
Allow installing from the GitHub releases via `brew install --cask ollama`

**Comment by easp** [comment]
Someone created a Formula (not a Cask), but it's running a bit behind (currently at 0.1.15)
https://github.com/Homebrew/homebrew-core/blob/master/Formula/o/ollama.rb

**Comment by BruceMacD** [comment]
Resolving this for now as it is being handled by a member of the community.
