### ISSUE TITLE
How can I modify the model's existence duration on the GPU?

### ISSUE THREAD

**Issue by papandadj** [ollama/ollama#3090]
Recently, I used Ollama to build my application. When I run a model, it automatically loads onto my GPU. However, after a few minutes, the model seems to be unloaded. How can I force the model to always remain loaded on the GPU?

**Comment by jmorganca** [comment]
Hi @papandadj with the API you can set `"keep_alive": -1` and it will keep the model loaded indefinitely. Let me know if this helps!
