### ISSUE TITLE
Is it possible to download the models from browser? 

### ISSUE THREAD

**Issue by OguzcanOzdemir** [ollama/ollama#3096]
Hello I need the download models from browser. Is it possible?

**Comment by BruceMacD** [comment]
Hi @OguzcanOzdemir, this isn't possible yet. The only way right now is with `ollama pull` or calling the pull API endpoint (in ollama running locally).

**Comment by pdevine** [comment]
@OguzcanOzdemir what's the use case for that?

**Comment by pdevine** [comment]
@abdurahmanadilovic what's the error that you're seeing? Does it just hang? Also, what's the output of `ollama -v`?
