### ISSUE TITLE
Working with gptscript

### ISSUE THREAD

**Issue by prologic** [ollama/ollama#3099]
Just wanted to bring your attention to this nice little project called [gptscript](https://github.com/gptscript-ai/gptscript) that mentions not working natively with Ollama [here](https://github.com/gptscript-ai/gptscript/issues/136#issuecomment-1993903566) due to missing `/models` endpoint. I had a quick look around the codebase and I _believe_ this isn't the case. Maybe this info is outdated and it works now? 🤔

**Comment by prologic** [comment]
See: https://github.com/gptscript-ai/gptscript/issues/136#issuecomment-1993903566

**Comment by BruceMacD** [comment]
Hi @prologic, thanks for bringing this up. What they are looking for is the `v1/models` openai compatible endpoint which we haven't added yet.

I'm going to resolve this one for now in favour of #2430, but we can reach out to them when it is implemented.
