### ISSUE TITLE
Windows Unable to Load Dynamic Server Library - unicode characters in model dir

### ISSUE THREAD

**Issue by ljhao1123** [ollama/ollama#3104]
When I enter this command  "ollama run xxx" ,The model has been pulled, but the following error occurred: Error: Unable to load dynamic library: Unable to load dynamic server library: �Ҳ���ָ����ģ�顣

**Comment by dhiltgen** [comment]
Can you share your server log?  Does your home directory have unicode characters?  (We're working on some fixes related to handling unicode characters)

**Comment by smilefufu** [comment]
Same issue here, logs: [server.log](https://github.com/ollama/ollama/files/14624685/server.log)

**Comment by dhiltgen** [comment]
Unicode characters in the model directory should be working now.  Please give [0.1.33](https://github.com/ollama/ollama/releases) (available in pre-release) a try and let us know.

**Comment by dhiltgen** [comment]
If you still experience problems with 0.1.33 let us know.
