### ISSUE TITLE
Ollama ls not included in the -h/--help flags 

### ISSUE THREAD

**Issue by aosan** [ollama/ollama#3106]
While working on a [Bash completion PR](https://github.com/ollama/ollama/pull/3105), I noticed the absence of ls from the arguments list for -h/--help and ollama listing.

![image](https://github.com/ollama/ollama/assets/8534160/7676b183-05e7-4f5e-8d46-25fc05e12a5e)

**Comment by amila-ku** [comment]
Quick look at code revealed it was added as an 'Alias' to list command, therefore it is not shown as an additional command.
https://github.com/ollama/ollama/blob/main/cmd/cmd.go#L999C1-L1005C3

```
	listCmd := &cobra.Command{
		Use:     "list",
		Aliases: []string{"ls"},
		Short:   "List models",
		PreRunE: checkServerHeartbeat,
		RunE:    ListHandler,
	}
```

**Comment by pdevine** [comment]
As @amila-ku mentioned, the command is `ollama list` but `ls` is an alias.

**Comment by aosan** [comment]
@pdevine this is a usability issue not a "find in the code" quest, the options menu presented to the user is incomplete. The fact the `ls` is an alias is a distinction without a difference. This incompleteness impacts bash_completion and future man pages.
