### ISSUE TITLE
OpenAI API and templates

### ISSUE THREAD

**Issue by pierreeliseeflory** [ollama/ollama#3109]
Hi,

Does the new OpenAI API compatible endpoint `/v1/chat/completions` uses the default templates defined in the Modefile ?

Thank you

**Comment by BruceMacD** [comment]
Hi @pierreeliseeflory, the `/v1/chat/completions` uses the templates defined in the modelfile, it is just mapping the openai request format to our own chat request format so all functionality should be the same. Let me know if you have any other questions.

**Comment by vcl00e** [comment]
Hi, just like to add the mapping logic seems to be here:
https://github.com/ollama/ollama/blob/c77d45d836ae98fd19543245180f6412da24e44b/server/prompt.go#L93C4-L93C5
