### ISSUE TITLE
Windows Error:pull model manifest return wsarecv: An existing connection was forcibly closed by the remote host.

### ISSUE THREAD

**Issue by heimu-liu** [ollama/ollama#3112]
i can't down the model:
[app.log](https://github.com/ollama/ollama/files/14589977/app.log)
[server.log](https://github.com/ollama/ollama/files/14589978/server.log)

`PS C:\Users\heimu\AppData\Local\Ollama> ollama pull llama2
pulling manifest
Error: pull model manifest: Get "https://ollama.com/token?nonce=A-QmGZFS0za-Kv0GKrDy3Q&scope=repository%!A(MISSING)library%!F(MISSING)llama2%!A(MISSING)pull&service=ollama.com&ts=1710339130": read tcp 192.168.247.214:56798->34.120.132.20:443: wsarecv: An existing connection was forcibly closed by the remote host.
PS C:\Users\heimu\AppData\Local\Ollama>`

**Comment by BruceMacD** [comment]
Hi @heimu-liu this seems similar to #1149, are you using ollama behind a proxy? If so checkout the proxy configuration guide:
https://github.com/ollama/ollama/blob/main/docs/faq.md#how-do-i-use-ollama-behind-a-proxy

Hopefully that helps, let me know if that is the case.

**Comment by heimu-liu** [comment]
> Contributor

Thank you very much for your reply!
I've tested it with both wireless and LTE, as well as proxy and non-proxy.
still get the same error.

**Comment by dhiltgen** [comment]
Similar to #3191 and #2448

**Comment by Felixchen1024** [comment]
How can I fix this?

**Comment by mxyng** [comment]
Looking at the request both from the error in your description and the server access logs, it appears the request is getting mangled somehow.

This is being sent

```
https://ollama.com/token?nonce=A-QmGZFS0za-Kv0GKrDy3Q&scope=repository%!A(MISSING)library%!F(MISSING)llama2%!A(MISSING)pull&service=ollama.com&ts=1710339130
```

instead of this

```
https://ollama.com/token?nonce=A-QmGZFS0za-Kv0GKrDy3Q&scope=repository%3Alibrary%2Fllama2%3Apull&service=ollama.com&ts=1710339130
```

This should be caused by passing the real URL into `fmt.Printf` or similar functions: [example](https://go.dev/play/p/V0sMmL70jIs).

Is it possible there's a man-in-the-middle proxy mangling the request?

**Comment by chopeen** [comment]
My experiments in #2448 suggest that a correct URL is called and it is only mangled later, when logged. 

---

I am facing the same problem **when connected to a corporate network** (Ubuntu 22.04, Ollama installed with Homebrew):

```
$ ollama run llava

pulling manifest 
Error: pull model manifest: Get "https://ollama.com/token?nonce=SW96RgmctcQmHJ37NXJ8KQ&scope=repository%!A(MISSING)library%!F(MISSING)llava%!A(MISSING)pull&service=ollama.com&ts=1711106784": read tcp 10.144.68.189:40600->34.120.132.20:443: read: connection reset by peer
```

The problem first appeared in `v0.1.28`. 

When I downgrade to `v0.1.27`, I am able to pull the models again.

**Comment by heimu-liu** [comment]
> My experiments in #2448 suggest that a correct URL is called and it is only mangled later, when logged.
> 
> I am facing the same problem **when connected to a corporate network** (Ubuntu 22.04, Ollama installed with Homebrew):
> 
> ```
> $ ollama run llava
> 
> pulling manifest 
> Error: pull model manifest: Get "https://ollama.com/token?nonce=SW96RgmctcQmHJ37NXJ8KQ&scope=repository%!A(MISSING)library%!F(MISSING)llava%!A(MISSING)pull&service=ollama.com&ts=1711106784": read tcp 10.144.68.189:40600->34.120.132.20:443: read: connection reset by peer
> ```
> 
> The problem first appeared in `v0.1.28`.
> 
> When I downgrade to `v0.1.27`, I am able to pull the models again.

Thank you Very Much!

**Comment by heimu-liu** [comment]
Problem solved by downgrade to v0.1.27

**Comment by chopeen** [comment]
@heimu-liu Downgrading is merely a workaround, but hopefully the problem can actually be solved in future version of Ollama. 

@mxyng Do you prefer to reopen this issue **or** should I create a new one with all the information known so far?

**Comment by chopeen** [comment]
I opened #3452.

**Comment by rionitinkumar** [comment]
I'm facing the same issue with the latest version of ollama. Does not work in corporate proxy anymore.
Downgrading to v0.1.27 makes it work again.
