### ISSUE TITLE
Using INT4 Quantization to Save VRAM with ollama

### ISSUE THREAD

**Issue by TraceRecursion** [ollama/ollama#3114]
Hello ollama team,

I am currently exploring the use of ollama to run models and am interested in implementing INT4 quantization to save on VRAM usage. I have read through the documentation but would appreciate some guidance on how to properly apply INT4 quantization during the model run.

Could you provide some insights or examples on how to integrate this quantization method with ollama? Specifically, I am looking for ways to reduce the VRAM footprint while maintaining performance.

Thank you for your assistance.

Best regards,
溯源递归

**Comment by orlyandico** [comment]
Why not just import a model that has already been quantised? e.g. in GGUF format. I think quantising the model on the fly (particularly for larger models) would take an enormous amount of time.

**Comment by easp** [comment]
New quantizations would need to be implemented upstream in llama.cpp. There are already a variety of quantization approaches implemented there and the models in the ollama library are into a range of sizes using a few of those approaches. If you pull an ollama model without specifying the quantization it will pull a q4_0 version.

**Comment by TraceRecursion** [comment]
appreciate your help
