### ISSUE TITLE
Switching between models is very slow?

### ISSUE THREAD

**Issue by eliranwong** [ollama/ollama#3115]
I noted that switching between models is very slow.  Is it possible to load two different models in memory at the same time?

**Comment by pdevine** [comment]
It's not possible *yet* to load two models simultaneously, but it's something we've been contemplating for a while (and there are a couple issues on this already). There are a couple reasons for the slow switching time, but loading between system memory and the GPU can be pretty slow, particularly if you're loading/unloading large models and/or if you have older hardware.

Going to close out the issue, but feel free to keep commenting.

**Comment by ivanenev** [comment]
I am running two models simultaneously but they do not run in parallel, they respond consecutively. I've found a way of running two models,mistral and llama (or two instances of llama) in parallel  by changing the OLLAMA_HOST variable. First copy the model:  ollama cp llama3 llama3-2
For the second second instance,change the ip and port like so: OLLAMA_HOST=0.0.0.0:11435 ollama serve   
OLLAMA_HOST=0.0.0.0:11435 ollama run ollama

**Comment by FarooqAlaulddin** [comment]
Running LangFlow pipeline with two models (14b + 7b) in a batch run and here is what I saw. My system is Macbook M4 Pro Chip + 24GB.

![Image](https://github.com/user-attachments/assets/b16d3841-bb66-4aec-991f-9dad0980e20e)
