### ISSUE TITLE
Api. /show

### ISSUE THREAD

**Issue by Hansson0728** [ollama/ollama#3116]
Suggestion.

When sending a request to the show enpoint without a model name, the response should return the model information for the currently loaded model with a status property stating if the model is fully loaded or is loading and maybe some other stats, and rerurn "no model loaded" if none is loaded.

This would be a great help when building fronts on the api, as of now we cant get any information on wich model is loaded or the  statis of the loaded model

**Comment by jmorganca** [comment]
Hi there, this is available now with `ollama ps` and `/api/ps`
