### ISSUE TITLE
ollama RAM use on orangepi 5

### ISSUE THREAD

**Issue by parzzd** [ollama/ollama#3118]
Im trying model on my SBC, it has 16gb RAM, but the execution just uses 1.6gb, making the model take so much time to process.
Is there any parameter or configuration to allow it.
im new on Ollama, so any answer would be appreciated.

![scr_proceso](https://github.com/ollama/ollama/assets/103915075/5e43931c-9cb0-40d3-9f5f-975308db87aa)

![times](https://github.com/ollama/ollama/assets/103915075/57d9987a-0b99-4a6c-850b-5066b181619a)

**Comment by jmorganca** [comment]
Hi there, I think in this case inference may be bound by your CPU (e.g. it has 50%+ utilization). May I ask which model you're running? Smaller models (e.g. `gemma:2b`, `phi` or `tinyllama` might run faster). Hope this helps!

**Comment by parzzd** [comment]
im ussing qwen1_5-4b.
