### ISSUE TITLE
Tensor `token_embed.weight` has wrong shape

### ISSUE THREAD

**Issue by BruceMacD** [ollama/ollama#3119]
![image](https://github.com/ollama/ollama/assets/5853428/543d8714-16de-421f-b669-2afd9b87fe81)
split from #2753

**Comment by BruceMacD** [comment]
cc: @fotiecodes, opened an issue specific to your problem here

**Comment by mxyng** [comment]
this should be fixed by #3044 assuming the model was created using the convert from safetensors feature

**Comment by FotieMConstant** [comment]
hey @mxyng  could you please explain what you mean or how it can be done, i am not so experienced in this and this is my first time creating a fine-tune from Llama2-7b.

In the main time, i completely uninstalled ollama from my mac and did a clean install converted and quantized the model with the following instructions at [import.md](https://github.com/ollama/ollama/blob/main/docs/import.md). create a model file and tried to run it again but it still give me the same error.

Any idea how i can fix it?
I'd really appreciate some help:)
@BruceMacD

**Comment by FotieMConstant** [comment]
been stuck on this for days:(
