### ISSUE TITLE
nous-hermes2 stops generating output in the middle of a sentence

### ISSUE THREAD

**Issue by aktersnurra** [ollama/ollama#3128]
Hello,

After a while of chatting with the nous-hermes2, around 4-10 questions, it stops generating output randomly mid-sentence. I have tried other models such as dolphin-mistral and openhermes, but I have not experienced similar behavior, however these are smaller models.

I cannot see any suspicious output from the logs.

Could this be an issue of VRAM on the GPU?  (Only 8GB)

However, I see that there is never more than 6.8 GB allocated.

Anyone that might have a clue?

**Comment by mchiang0610** [comment]
Hi @aktersnurra sorry about this. This is hard to troubleshoot. 

Does the new recently released Nous Hermes 2 Pro 7B still have this problem? Someone has built a modelfile that you can use to import the model yourself or upload it to Ollama.com: 

https://github.com/maxtheman/hermes-pro/blob/main/modelfile 

Tagging @teknium1 for visibility and help.

**Comment by teknium1** [comment]
Are you using mixtral 8x7b or mistral 7b?

> Hello,
> 
> After a while of chatting with the nous-hermes2, around 4-10 questions, it stops generating output randomly mid-sentence. I have tried other models such as dolphin-mistral and openhermes, but I have not experienced similar behavior, however these are smaller models.
> 
> I cannot see any suspicious output from the logs.
> 
> Could this be an issue of VRAM on the GPU? (Only 8GB)
> 
> However, I see that there is never more than 6.8 GB allocated.
> 
> Anyone that might have a clue?

**Comment by aktersnurra** [comment]
> Are you using mixtral 8x7b or mistral 7b?
> 
> > Hello,
> > After a while of chatting with the nous-hermes2, around 4-10 questions, it stops generating output randomly mid-sentence. I have tried other models such as dolphin-mistral and openhermes, but I have not experienced similar behavior, however these are smaller models.
> > I cannot see any suspicious output from the logs.
> > Could this be an issue of VRAM on the GPU? (Only 8GB)
> > However, I see that there is never more than 6.8 GB allocated.
> > Anyone that might have a clue?

I am using the [11b:latest](https://ollama.com/library/nous-hermes2) version.

> Hi @aktersnurra sorry about this. This is hard to troubleshoot.
> 
> Does the new recently released Nous Hermes 2 Pro 7B still have this problem? Someone has built a modelfile that you can use to import the model yourself or upload it to Ollama.com:
> 
> https://github.com/maxtheman/hermes-pro/blob/main/modelfile
> 
> Tagging @teknium1 for visibility and help.

Thanks, I'll test this out and see if this model displays similar behavior or not.

**Comment by dhiltgen** [comment]
If you're still having trouble with the model, please upgrade to the latest ollama to see if that clears it up.   If not, let us know and I'll reopen the issue.
