### ISSUE TITLE
Clip model isn't being freed correctly

### ISSUE THREAD

**Issue by RandomGitUser321** [ollama/ollama#3131]
I'm on Windows and do a lot of things with models. Mostly a VLM->Get a detailed description of an image->Use a different LLM that's better at writing prompts to inject/mix my ideas in with->Stable diffusion->Image type workflow with ComfyUI. Obviously, I need all the VRAM I can get, but I sometimes run into scenarios where every megabyte of VRAM is precious(ipadapter, controlnets, etc)

I have my own custom nodes that I've made, that incorperate sending the command to unload the model after they are used, so that I don't run into any OOM/OOVM scenarios leading to using shared memory(destroys performance):
For example, it pretty much ultimately runs the command: 
`client.generate(model=model, prompt=prompt, images=images_b64, system=system, options={'num_predict': num_predict, 'temperature': temperature, 'seed': seed}, keep_alive="0")`

Everything works fine and the `keep_alive = "0"` does indeed unload the model when it's done, but it seems like it leaves the `mmproj-model-f16` portion of the associated model still loaded in VRAM. Whatever VRAM load I was at before starting->loading->unloading remains higher until I exit out of the Ollama Windows icon in my task tray; freeing up the chunk that was trapped.

I've tested this with regular LLMs and the command does completely work and return my VRAM load back to what it was before I loaded the model.

EDIT: Oh and I can also replicate this identical behaviour with a regular *.py script doing the same thing with a basic template

**Comment by ZaneA** [comment]
Newer versions of Ollama have moved the LLM processing into the server itself, and it looks like there are some memory leaks to be fixed, you might want to follow this issue https://github.com/ollama/ollama/issues/1848

**Comment by pdevine** [comment]
@RandomGitUser321 yes, llama.cpp is temporarily removing llava support, but we'll continue to support it. There have been a few issues which have crept up with it lately though that we're working through right now.

**Comment by pdevine** [comment]
#3149 should address the issue.

**Comment by mxyng** [comment]
This should be fixed now
