### ISSUE TITLE
v0.1.29 #bug

### ISSUE THREAD

**Issue by enryteam** [ollama/ollama#3133]
v0.1.29报403错误！补充说明我是通过frpc代理访问11434端口的，在[v0.1.29]之前版本确实都ok的。

**Comment by mchiang0610** [comment]
你好，可以问一下你的 hostname 是什么吗？ 用proxy 的话，你用 OLLAMA_HOST=0.0.0.0 应该就可以了

我先关闭这个issue. 如果还有问题可以重开一下。 谢谢！

**Comment by tiye** [comment]
确实 https://github.com/ollama/ollama/issues/3581
