### ISSUE TITLE
Is there any plans/milestones for implementing function calling?

### ISSUE THREAD

**Issue by chumpblocckami** [ollama/ollama#3137]
Is there a roadmap for implementing function calling/tools? 
I'm happy to help if pointed in the right direction :) 
Thanks!

**Comment by JMLX42** [comment]
I have a Python prototype that loads/run tools from OpenAPI definitions. And I want to add support for WASM components (https://component-model.bytecodealliance.org/) as tools.

But I'll likely need guidance on the ollama code base to understand where I can implement it.

**Comment by JMLX42** [comment]
Actually my comment might be off topic since I think it is out of ollama's scope to do the actual run of the tools.

**Comment by ChristianWeyer** [comment]
> Actually my comment might be off topic since I think it is out of ollama's scope to do the actual run of the tools.

Yes, this is completely in the domain and responsibility of your application code.

**Comment by jmorganca** [comment]
Hi there, initial tool support has been added to Ollama: https://ollama.com/blog/tool-support

Excited to hear any feedback 😊
