### ISSUE TITLE
low ram usage

### ISSUE THREAD

**Issue by parzzd** [ollama/ollama#3139]
i have a problem with the ram usage for qwen_1_5_4b
i have 16gb ram, but the software only use 1.6gb 
is there a way to dedicate more ram to ollama process?

**Comment by pdevine** [comment]
Hey @parzzd , you're actually using a 4b parameter 4bit quantized version of qwen. If you don't want to use as heavily quantized version of that model you can:


```
ollama run qwen:4b-chat-v1.5-fp16
```

That should take about 9GB of RAM using a non-quantized model. You can try using a higher parameter count (like 7b) and play around with what level of quantization that you want.

I'll go ahead and close the issue, but feel free to keep commenting.
