### ISSUE TITLE
[Win11]求助，求助，求助。

### ISSUE THREAD

**Issue by taurusduan** [ollama/ollama#3140]
刚使用的小白，Ollama 的 API 自动在后台运行，服务于http://localhost:11434. 工具和应用程序可以连接到它，无需任何额外的设置。

我的服务器局域网地址为192.168.1.2，不知道为什么http://192.168.1.2:11434无法访问。

希望大佬能够帮帮我，谢谢啊。

**Comment by mili-tan** [comment]
[https://github.com/ollama/ollama/blob/main/docs/faq.md#how-can-i-allow-additional-web-origins-to-access-ollama](https://github.com/ollama/ollama/blob/main/docs/faq.md#how-can-i-allow-additional-web-origins-to-access-ollama)

**Comment by hlstudio** [comment]
https://github.com/ollama/ollama/blob/main/docs/faq.md#how-can-i-expose-ollama-on-my-network

**Comment by jmorganca** [comment]
Hi there, yes to expose Ollama see the FAQ: https://github.com/ollama/ollama/blob/main/docs/faq.md#how-can-i-expose-ollama-on-my-network

Hope this helps! If not let me know 😊

**Comment by Seeumt** [comment]
> Hi there, yes to expose Ollama see the FAQ: https://github.com/ollama/ollama/blob/main/docs/faq.md#how-can-i-expose-ollama-on-my-network
> 
> Hope this helps! If not let me know 😊

hello，could you help me to figure out this issue in the blow pics？

<img width="1136" alt="Image" src="https://github.com/user-attachments/assets/54b382c0-1d4d-447a-8bdf-c58df89c5a22" />

<img width="962" alt="Image" src="https://github.com/user-attachments/assets/91bf873d-6cf8-465d-85da-f68c01adbfd0" />
