### ISSUE TITLE
Doubt about openai compatibility with temperature parameter

### ISSUE THREAD

**Issue by ejgutierrez74** [ollama/ollama#3151]
I have one doubt, about the use of temperature.
As i have understood, temperature in llama2 is from 0.0 to 1.0.

But if you use chat.completion from openai ( https://github.com/ollama/ollama/blob/main/docs/openai.md), if you read the documentation temperature values range from 0.0 to 2.0, so seems a little mismatch.

For example if you write temperature 1.0, in llama2 would be the more random parameter, but in case of openai, would be medium ( the max should be 2.0)

So when i use:
```

chat_completion = client.chat.completions.create(
    messages=[
        {
            'role': 'user',
            'content': 'Say this is a test',
        }
    ],
    model='llama2',
    temperature=1.0
)
```
What should i expect, medium randomness as openai documentation, or full random as llama2 

Thanks in advance

**Comment by igorschlum** [comment]
@ejgutierrez74 I think you have a good point. If you work with ollama using ChatGPT format, temperature should range from 0 to 2 and then Ollama should divide temperature by 2 before processing the prompt.

**Comment by jmorganca** [comment]
1.0 should be median – it's adjusted to a rough equivalent with llama2 and other models. Hope this helps, and let me know if you see anything off 😊

**Comment by ejgutierrez74** [comment]
Im following a course of Llama2, seems official as the former is Amit Sangani Senior Director of Eng [@Meta](https://twitter.com/Meta). It says that in Llama the value varies from 0 to 1 ( says that 0.9 is a higher value). Thats the doubt....id follow the course and try to get possible inconsistencies between openai official API and Llama2 LLM

Thanks
@jmorganca by the way i reopened the ubuntu bug with ollama
.
