### ISSUE TITLE
Unable to load dynamic server library on Mac

### ISSUE THREAD

**Issue by elewis787** [ollama/ollama#3156]
### What is the issue?

When using the llm package and calling New the auto-detect dynamic lib fails auto-detect. 

This is related to pull request https://github.com/ollama/ollama/pull/2403 and issue https://github.com/ollama/ollama/issues/2386. 

The current fix does not set available dynamic libs after auto-detection causing the dynamic lib path to be empty. 

availableDynLibs should be checked and used after calling native init. 

### What did you expect to see?

The expectation is that the dynamic lib will be found 

### Steps to reproduce

import LLM package and attempt to initialize an LLM using New 

### OS

macOS

### Architecture

arm64

### Ollama version

main branch

### GPU

Apple

### CPU

Apple

**Comment by dhiltgen** [comment]
I think this should be covered by https://github.com/ollama/ollama/pull/3122

**Comment by elewis787** [comment]
I'll pull the changes and test it out. At a first glance I don't know if this solves the empty path for the dynamic libs map but I'll verify.

**Comment by elewis787** [comment]
> I think this should be covered by https://github.com/ollama/ollama/pull/3122

I'll pull the changes and test it out. At a first glance I don't know if this solves the empty path for the dynamic libs map but I'll verify.

**Comment by dhiltgen** [comment]
If you're still seeing problems related to tmpdir cleanup, let us know.
