### ISSUE TITLE
No welcoming window & pulling manifest Error: pull model manifest: file does not exist

### ISSUE THREAD

**Issue by HWiwoiiii** [ollama/ollama#3167]
### What is the issue?

When I first installed the ollama, I didn't see the welcoming window pops up, just a windows notification by it says "click here to start"

Clicking that notification gives me a powershell window as shown

and when I tried to run the command to get started it gives me the error below

pulling manifest
Error: pull model manifest: file does not exist

![image](https://github.com/ollama/ollama/assets/103039908/66196abc-46c4-49f7-902f-6ba304650ccd)

### What did you expect to see?

There should be a welcoming window for me to get started

### Steps to reproduce

Reinstall

### Are there any recent changes that introduced the issue?

no change

### OS

Windows

### Architecture

Other

### Platform

WSL, WSL2

### Ollama version

0.1.29

### GPU

Nvidia

### GPU info

w

### CPU

Intel

### Other software

Open WebUI

**Comment by BruceMacD** [comment]
Hi @HWiwoiiii, the install experience you are describing is what I expect on Windows at the moment. We don't have a welcome screen there yet.

For the `ollama run` problem, the issue is the name of the model you are trying to run. This should work:
`ollama run llama2:13b`

The error message is not very obvious in this case, sorry about that. Let me know if this works for you.

**Comment by HWiwoiiii** [comment]
Yes it works splendidly now, ty very much 
/***
 *               ii.                                         ;9ABH,          
 *              SA391,                                    .r9GG35&amp;G          
 *              &amp;#ii13Gh;                               i3X31i;:,rB1         
 *              iMs,:,i5895,                         .5G91:,:;:s1:8A         
 *               33::::,,;5G5,                     ,58Si,,:::,sHX;iH1        
 *                Sr.,:;rs13BBX35hh11511h5Shhh5S3GAXS:.,,::,,1AG3i,GG        
 *                .G51S511sr;;iiiishS8G89Shsrrsh59S;.,,,,,..5A85Si,h8        
 *               :SB9s:,............................,,,.,,,SASh53h,1G.       
 *            .r18S;..,,,,,,,,,,,,,,,,,,,,,,,,,,,,,....,,.1H315199,rX,       
 *          ;S89s,..,,,,,,,,,,,,,,,,,,,,,,,....,,.......,,,;r1ShS8,;Xi       
 *        i55s:.........,,,,,,,,,,,,,,,,.,,,......,.....,,....r9&amp;5.:X1       
 *       59;.....,.     .,,,,,,,,,,,...        .............,..:1;.:&amp;s       
 *      s8,..;53S5S3s.   .,,,,,,,.,..      i15S5h1:.........,,,..,,:99       
 *      93.:39s:rSGB@A;  ..,,,,.....    .SG3hhh9G&amp;BGi..,,,,,,,,,,,,.,83      
 *      G5.G8  9#@@@@@X. .,,,,,,.....  iA9,.S&amp;B###@@Mr...,,,,,,,,..,.;Xh     
 *      Gs.X8 S@@@@@@@B:..,,,,,,,,,,. rA1 ,A@@@@@@@@@H:........,,,,,,.iX:    
 *     ;9. ,8A#@@@@@@#5,.,,,,,,,,,... 9A. 8@@@@@@@@@@M;    ....,,,,,,,,S8    
 *     X3    iS8XAHH8s.,,,,,,,,,,...,..58hH@@@@@@@@@Hs       ...,,,,,,,:Gs   
 *    r8,        ,,,...,,,,,,,,,,.....  ,h8XABMMHX3r.          .,,,,,,,.rX:  
 *   :9, .    .:,..,:;;;::,.,,,,,..          .,,.               ..,,,,,,.59  
 *  .Si      ,:.i8HBMMMMMB&amp;5,....                    .            .,,,,,.sMr
 *  SS       :: h@@@@@@@@@@#; .                     ...  .         ..,,,,iM5
 *  91  .    ;:.,1&amp;@@@@@@MXs.                            .          .,,:,:&amp;S
 *  hS ....  .:;,,,i3MMS1;..,..... .  .     ...                     ..,:,.99
 *  ,8; ..... .,:,..,8Ms:;,,,...                                     .,::.83
 *   s&amp;: ....  .sS553B@@HX3s;,.    .,;13h.                            .:::&amp;1
 *    SXr  .  ...;s3G99XA&amp;X88Shss11155hi.                             ,;:h&amp;,
 *     iH8:  . ..   ,;iiii;,::,,,,,.                                 .;irHA  
 *      ,8X5;   .     .......                                       ,;iihS8Gi
 *         1831,                                                 .,;irrrrrs&amp;@
 *           ;5A8r.                                            .:;iiiiirrss1H
 *             :X@H3s.......                                .,:;iii;iiiiirsrh
 *              r#h:;,...,,.. .,,:;;;;;:::,...              .:;;;;;;iiiirrss1
 *             ,M8 ..,....,.....,,::::::,,...         .     .,;;;iiiiiirss11h
 *             8B;.,,,,,,,.,.....          .           ..   .:;;;;iirrsss111h
 *            i@5,:::,,,,,,,,.... .                   . .:::;;;;;irrrss111111
 *            9Bi,:,,,,......                        ..r91;;;;;iirrsss1ss1111
 */

**Comment by DSniper** [comment]
It works perfectly fine for 'ollama run llama2:13b' .Good Work @BruceMacD

**Comment by raon1512** [comment]
I am getting the same error (Mac)
Trying to install model)

ollama run llama3.2:3b
ollama run llama3.2
ollama run deepseek-r1

What should I do?

**Comment by raon1512** [comment]
> I am getting the same error (Mac) Trying to install model)
> 
> ollama run llama3.2:3b ollama run llama3.2 ollama run deepseek-r1
> 
> What should I do?
> 
> ollama run llama3:8b This model runs.


I tried ollama run llama3.2:3b again and it worked.
