### ISSUE TITLE
GPU utilization & Context Length and Max Tokens & Command-line windows crash & Server connection failed

### ISSUE THREAD

**Issue by HWiwoiiii** [ollama/ollama#3177]
### What is the issue?

1. How to setup Ollama for models to use my GPU?
I'm using Windows with a 32GB DDR4 2667MHz memory (16GB + 16GB) and an NVIDIA GeForce RTX 2080 Super with Max-Q Design (8GB / Dell). Intel(R) UHD Graphics (1GB / Dell). However, the Ollama doesn't seem to utilize my GPU even when I have both my CPU and memory running at 99% utilization. Is this a bug or are there any settings that I am accidentally ignoring?

2. Does adjusting Context Length and Max Tokens have any impact on running the model?
Are the Context Length and Max Tokens predefined or that we can change them in open webui? Can I extend myh input and the outputs by adjusting them? I know this is a silly question so if anyone is tired explaining it leaving a link about that here would be greatly appreciated as well.

3. How to keep Ollama running?
The cmd window that I use to run a model always crash and disappears when I want to type something in it is it normal? By the way  do I need to run `ollama run gemma:7b` every time I restart my pc?

![image](https://github.com/ollama/ollama/assets/103039908/764adea7-283b-4a05-ace0-92763d0f6028)
![image](https://github.com/ollama/ollama/assets/103039908/d219de7a-c5ff-44e1-af2c-90938d83889d)
![image](https://github.com/ollama/ollama/assets/103039908/8c3c1296-3be6-4862-ab23-45264d95427f)

### What did you expect to see?

1. How to setup Ollama for models to use my GPU?
GPU being used 

2. Does adjusting Context Length and Max Tokens have any impact on running the model?

3. How to keep Ollama running?
Ollama running correctly and can be accessed by open webui
![image](https://github.com/ollama/ollama/assets/103039908/179ccb1b-9801-4a31-90fd-8573690f9989)

### Steps to reproduce

restart my pc

### Are there any recent changes that introduced the issue?

not working

### OS

Windows

### Architecture

Other

### Ollama version

latest

### GPU

Intel

### GPU info

NVIDIA GeForce RTX 2080 Super with Max-Q Design (8GB / Dell). Intel(R) UHD Graphics (1GB / Dell). 

### CPU

Intel

### Other software

open webui

**Comment by HWiwoiiii** [comment]
Update:
I restarted my PC, and initially, the Ollama works fine for the first few seconds. However, when I ask something else, it gives the error shown below.
![image](https://github.com/ollama/ollama/assets/103039908/87e670cb-8072-4a58-aed1-c8b339f6ad8c)
![image](https://github.com/ollama/ollama/assets/103039908/3b1371ae-02e3-4235-bfc0-11e66c94bd35)

Another thing is, In the task manager, the Vmmem process cannot be ended. I understand that it is related to virtual memory and other system functions. However, even if I close both Ollama and Docker, the process persists, it doesn't seem to be directly linked to either Ollama or Docker.  I just want to confirm if it is a regular Windows process, as it cannot be terminated. Is it related to Ollama?
![image](https://github.com/ollama/ollama/assets/103039908/6173a666-cbb6-42ed-9db7-bc65be957dcd)

**Comment by dhiltgen** [comment]
Can you share your server log?  It sounds like the server is probably crashing for some reason, and we'll be able to understand why from the log.  This will also help us understand if it is correctly identifying your GPU.

**Comment by dhiltgen** [comment]
We've fixed a number of stability bugs on Windows in [0.1.33](https://github.com/ollama/ollama/releases) (available in pre-release).  Please give the update a try and if you're still seeing problems, please share your server log and I'll re-open the issue to investigate.
