### ISSUE TITLE
Add "Stop" command

### ISSUE THREAD

**Issue by haydonryan** [ollama/ollama#3182]
### What are you trying to do?

ollama is great!  There is a ollama serve / start, however it doesn't have stop.  There's already a big (closed) issue on how to stop it from autostarting on reboot, and it's OS dependent.  If you can create the service with the ollama cli, then you should be able to stop the service / disable the service with the CLI.  Personally I don't want to run the service all the time, unless i'm utilizing it.

### How should we solve this?

add an ollama stop command

### What is the impact of not solving this?

there's going to continue to be people asking how to stop the service in issues, 

### Anything else?

Nope - thanks for a great program!

**Comment by darrenangle** [comment]
+1 please

**Comment by wang-yiwei** [comment]
Just for linux users, if you don't wanna ollama to auto-allocate your memory (on RAM or VRAM), you can use the `systemctl` command to manually turn on/ off the ollama service.

```sh
sudo systemctl status ollama    # check the status of the service
sudo systemctl stop ollama     # kill
sudo systemctl start ollama   # restart
```
Possible use scenario:
- I use `cody` extension with ollama as the backend provider. Ollama will load llm weights into my hardware if I am coding.
- I am programming with vscode but also testing an llm-API that I have deployed on the same machine
- I don't need code completion service for now
If you are facing the same condition mentioned above, or you simply don't wanna ollama out of control, just stop the systemctl service.

**Comment by FilkerZero** [comment]
I just added a similar request; I missed this the first time I scanned through open issues.

**Comment by lonngxiang** [comment]
+1

**Comment by pdevine** [comment]
Thanks for the issue @haydonryan . I'm going to close this in favor of #3314 since it's slightly more comprehensive.
