### ISSUE TITLE
ConnectionError: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/generate/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7851288df1c0>: Failed to establish a new connection: [Errno 111] Connection refused'))

### ISSUE THREAD

**Issue by jyotiyadav94** [ollama/ollama#3200]
### What is the issue?

ConnectionError: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/generate/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7851288df1c0>: Failed to establish a new connection: [Errno 111] Connection refused'))

### What did you expect to see?

I am running the below code in google collab 

`!pip3 install llama-index==0.8.59
!pip3 install openai==0.28.1
!pip3 install pypdf==3.17.2

from llama_index.llms import Ollama
llm = Ollama(model="gemma")

resp = llm.complete("What did Rome grow? Be concise.")
print(resp)

`

### Steps to reproduce

I am running the below code in google collab 
`resp = llm.complete("What did Rome grow? Be concise.")
print(resp)`

I am receiving at this step

**Comment by mxyng** [comment]
Ollama requires a running instance. Calling `llm.complete()` is not sufficient. See the README.md for setting up Ollama or this example on running Ollama in a Jupyter notebook[^1].

[^1]: https://github.com/ollama/ollama/tree/main/examples/jupyter-notebook

**Comment by aryangoyal90** [comment]
@mxyng In my case . I am integrating a streamlit application (uses Ollama) in docker.
when I enter the docker command to run the application it is running on local host but when I enter a prompt or ask any question then I got the problem  like @jyotiyadav94 described

**Comment by Patdill** [comment]
Same issue as @aryangoyal90

**Comment by mxyng** [comment]
without knowing exactly how ollama is deployed, all I can say is if ollama is not running in that specific container, `localhost` address is incorrect

localhost in docker is not the same localhost since the container exists in a separate network namespace. you either need to address the container host (e.g. `host.docker.internal` for docker desktop) or another container

**Comment by lprakashv** [comment]
> localhost in docker is not the same localhost since the container exists in a separate network namespace. you either need to address the container host (e.g. `host.docker.internal` for docker desktop) or another container

Fixed by using `base_url='http://host.docker.internal:11434'`

**Comment by Urvesh71** [comment]
same issue as @jyotiyadav94

**Comment by ntelo007** [comment]
This did not work for me. Any advice please?

**Comment by yashgupta67** [comment]
same issue as @jyotiyadav94

**Comment by asifhaider** [comment]
Same problem here as @jyotiyadav94

**Comment by chuenfaiy** [comment]
ollama local deploy, Same problem as @jyotiyadav94 
cmd `curl http://localhost: 11434` is valid when running in terminal.

**Comment by HamzaAI9D** [comment]
![image](https://github.com/user-attachments/assets/808f156c-ee4c-4db8-81cb-ecd2d05937e6)

Check here I'm trying to run Ollama Image and fastapi app but could not access llama but I verified Ollama is running. 
I also verified llama3.2 model is pull successfully but when I hit API endpoint  I get the below error:

`{
  "detail": "Failed to read or summarize PDF: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/generate (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1c9d095b80>: Failed to establish a new connection: [Errno 111] Connection refused'))"
}`

here below is the my docker-compose.yml file that I used to build docker image:

`version: '3.8'

services:
  app:
    build: .  # Build the FastAPI app using the Dockerfile in the root directory
    ports:
      - 8000:8000  # Expose FastAPI on port 8000
    volumes:
      - ./app:/code/app  # Mount the FastAPI app directory
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    restart: always
    depends_on:
      - ollama
    networks:
      - ollama-docker

  ollama:
    image: ollama/ollama:latest  # Use the latest Ollama image
    container_name: ollama
    volumes:
      - ./ollama/ollama:/root/.ollama  # Mount the local Ollama directory containing llama3.2 model
    pull_policy: always  # Ensure that the image is always pulled if there is a new one
    tty: true  # Keep the container running in the background
    restart: unless-stopped  # Restart unless manually stopped
    ports:
      - 11434:11434  # Expose Ollama on port 7869
    environment:
      - OLLAMA_KEEP_ALIVE=24h  # Keep the model alive for 24 hours
      - OLLAMA_BASE_URLS=http://host.docker.internal:11434
    networks:
      - ollama-docker
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia  # Enable GPU access
              count: 1
              capabilities: [gpu]

networks:
  ollama-docker:
    external: false`

I'm not able to debug where is the issue

**Comment by ninetyhe-90** [comment]
> > localhost in docker is not the same localhost since the container exists in a separate network namespace. you either need to address the container host (e.g. `host.docker.internal` for docker desktop) or another container
> 
> Worked for me using `base_url='http://host.docker.internal:11434'`

this works for me

**Comment by mzeeshanarshad** [comment]
Try increasing the timeout.

**Comment by yashgupta67** [comment]
that doesnt work either

**Comment by Pancat009** [comment]
based on Grok:
pkill ollama
nohup OLLAMA_HOST=0.0.0.0 ollama serve &
ollama run deepseek-r1:7b

**Comment by g0t4** [comment]
TRY REBOOTING

I had this issue today and `rebooted` and it went away... exact same request worked after reboot.

Oddly the error only happened when using httpie's `http` command, whereas `curl` worked before the reboot... some sort of connection pooling issue in ollama. But, a restart of ollama didn't fix it. Had to reboot machine

**Comment by Latimerhtet** [comment]
> > localhost in docker is not the same localhost since the container exists in a separate network namespace. you either need to address the container host (e.g. `host.docker.internal` for docker desktop) or another container
> 
> Worked for me using `base_url='http://host.docker.internal:11434'`

This just also worked for me.
