### ISSUE TITLE
我将MiniCPM-2B-dpo-bf16-gguf.gguf模型成功的导入到了ollama中，并运行起来了。但是在推理的过程中，发现模型再说胡话，臆想比较严重。详见截图

### ISSUE THREAD

**Issue by zhao1012** [ollama/ollama#3206]
我将MiniCPM-2B-dpo-bf16-gguf.gguf模型成功的导入到了ollama中，并运行起来了。但是在推理的过程中，发现模型再说胡话，臆想比较严重。详见截图
![miniCPM-2b 在ollama上乱说话](https://github.com/ollama/ollama/assets/38517343/8f68f251-d07d-4ea5-95a1-59dde7a84bf4)

_Originally posted by @zhao1012 in https://github.com/ollama/ollama/issues/2383#issuecomment-2002754353_

**Comment by zhao1012** [comment]
这个问题是因为转换成gguf格式中模型权重或者什么损坏了？模型为huggingface下载

**Comment by gamersover** [comment]
原始模型会输出什么？如果是一样的，那么可能是模型本身的效果不好，看起来模型大小只有2B。也可以给出你的转换代码或者模型参数（如temperature）

What will the original model output? If it's the same, then it's likely that the model itself is not effective. It seems the model size is only 2B. You can also provide your conversion code to see if there are any issues or adjust parameters (such as temperature).

**Comment by zhao1012** [comment]
补充一张照片，同样问题在ollama导入的MiniCPM-2B-dpo-bf16-gguf.gguf上的表现。
![miniCPM-2b 在ollama上乱说话2](https://github.com/ollama/ollama/assets/38517343/ac9ff98b-f5fe-4149-95e6-c197ea3073cc)

**Comment by zhao1012** [comment]
我使用ollama导入了bf16（MiniCPM-2B-dpo-fp16-gguf.gguf（模型来源于[https://github.com/OpenBMB/MiniCPM?tab=readme-ov-file下提供的MiniCPM-2B-dpo-bf16-gguf.gguf（hunggingface下载））的模型，通过ollama运行相同的问题（1+1=?），依旧回答会如4bit量化后的一样。详细见如下图
```
import ollama
if __name__ == "__main__":
    print("Procedures begin to execute！")
    Modelfile = 'FROM ./models/hungface_miniCPM2b_gguf/MiniCPM-2B-dpo-fp16-gguf.gguf'
    ollama.create(model='MiniCPM-2B-dpo',modelfile=Modelfile)
```
这个问题让我很费解。
![miniCPM-2b 在ollama上乱说话1](https://github.com/ollama/ollama/assets/38517343/3b0f9e3f-73dd-4b4e-8d43-3c1f1447c1cc)
![miniCPM-2b 在ollama上乱说话2](https://github.com/ollama/ollama/assets/38517343/2a9135e9-6cc0-4fa8-b245-10770949a4ad)
![miniCPM-2b 在ollama上乱说话3](https://github.com/ollama/ollama/assets/38517343/cc96bd33-3ce4-46da-8046-65e728772bf3)

**Comment by pretenderlu** [comment]
我也遇到了类似的问题，我在lmstudio中使用相同的模型，并不会有这个问题。但是在ollama中却会疯狂输出。
--------
I also encountered a similar problem. I use the same model in lmstudio and there is no such problem. But it will output wildly in ollama.

**Comment by a937983423** [comment]
请问这个问题有没有解决，我也遇到同样问题

**Comment by boebo8** [comment]
有没有新版的minicpm llama3 V2.5的gguf格式可下载？

**Comment by jmorganca** [comment]
Closing for https://github.com/ollama/ollama/issues/2383

**Comment by Cyber-HuaTuo** [comment]
**The template format in Modelfile is incorrect; the correct one is shown below：**

FROM your-model.gguf
 
### Set the system message
SYSTEM """
You are a super helpful helper.
"""
 
PARAMETER stop <s>

**Comment by Cyber-HuaTuo** [comment]
### The template format in Modelfile is incorrect; the correct one is shown below：

FROM your-model.gguf
 
### Set the system message
SYSTEM """
You are a super helpful helper.
"""
 
PARAMETER stop <s>

**Comment by Cyber-HuaTuo** [comment]
### The template format in Modelfile is incorrect; the correct one is shown below：

FROM tinyllama-my-model.gguf
 
SYSTEM """
You are a super helpful helper.
"""
 
PARAMETER stop <s>

**Comment by Cyber-HuaTuo** [comment]
### The template format in Modelfile is incorrect; the correct one is shown below:


FROM your-model.gguf
 
SYSTEM """
You are a super helpful helper.
"""
 
PARAMETER stop <s>

**Comment by Cyber-HuaTuo** [comment]
### Modelfile的模板格式不对，对的如下所示

FROM your-model.gguf

SYSTEM """
You are a super helpful helper.
"""

PARAMETER stop

**Comment by Cyber-HuaTuo** [comment]
### 温度太高了，改一下modelfile就行了：

FROM model.gguf
PARAMETER temperature 0.7
PARAMETER stop "<|im_start|>"
PARAMETER stop "<|im_end|>"
TEMPLATE """
<|im_start|>system
{{ .System }}<|im_end|>
<|im_start|>user
{{ .Prompt }}<|im_end|>
<|im_start|>assistant
"""
SYSTEM """You are a helpful assistant."""

**Comment by Cyber-HuaTuo** [comment]
我上次把温度改成了1直接胡言乱语
