### ISSUE TITLE
open /home/house365ai/xxm/model/Qwen1.5-14B-Chat/tokenizer.model:

### ISSUE THREAD

**Issue by njhouse365** [ollama/ollama#3213]
### What model would you like?

my Modelfile
FROM /home/house365ai/xxm/model/Qwen1.5-14B-Chat

ollama create Qwen1.5-14B-Chat -f Modelfile

how solve it?

**Comment by pdevine** [comment]
We don't yet support converting/quantizing the Qwen model directly from Safetensors. You'll need to follow the [documentation](https://github.com/ollama/ollama/blob/main/docs/import.md#importing-pytorch--safetensors) and convert the model manually.

**Comment by njhouse365** [comment]
thanks
