### ISSUE TITLE
Go client marshals ChatRequest.KeepAlive into wrong data type

### ISSUE THREAD

**Issue by jankammerath** [ollama/ollama#3223]
As described by @jmorganca in https://github.com/ollama/ollama/issues/2343, the `keep_alive` field can be `0`, `-1` or another value indicating how long the model shall stay in memory.

The following Go code defines the `keep_alive` field as another struct with a Duration in it.
https://github.com/ollama/ollama/blob/7ed3e941058a47464a1ee97cd16f464eb788e396/api/types.go#L45

The current implementation results in the `keep_alive` being marshaled into `{"Duration":86400000000000}`

Here's a Playground example on how the `ChatRequest` struct is marshaled into JSON in the current implementation.

```
// You can edit this code!
// Click here and start typing.
package main

import (
	"encoding/json"
	"fmt"
	"time"
)

type Duration struct {
	time.Duration
}

type ChatRequest struct {
	Model     string    `json:"model"`
	KeepAlive *Duration `json:"keep_alive,omitempty"`

	Options map[string]interface{} `json:"options"`
}

func main() {
	request := ChatRequest{
		Model: "model-name",
		// keep alive for 24 hours
		KeepAlive: &Duration{Duration: time.Hour * 24},
	}

	jsonData, err := json.Marshal(request)
	if err != nil {
		fmt.Println(err)
	}

	fmt.Println(string(jsonData))
}
```

The output of this is as follows.

`{"model":"model-name","keep_alive":{"Duration":86400000000000},"options":null}`

A possible solution could be to change the `keep_alive` field to an `int64`.

**Comment by mxyng** [comment]
@jmorganca is correct but he's missing some context. `keep_alive` has type Duration which has a custom JSON unmarshaler that transforms a number, e.g. -1, into a Duration. Since you're using the Go type directly, this does not apply. Duration also doesn't not have a custom marshaler which is why it's gets marshaled into `"keep_alive": {"Duration": ...}`
