### ISSUE TITLE
Cannot create Modelfile on Windows Shell

### ISSUE THREAD

**Issue by worras2019** [ollama/ollama#3226]
### What is the issue?

The following is not working in WIndows Shell. Windows Shell doesn't recognize FROM.
--------------------------------------------------
FROM llama2

# set the temperature to 1 [higher is more creative, lower is more coherent]
PARAMETER temperature 1

# set the system message
SYSTEM """
You are Mario from Super Mario Bros. Answer as Mario, the assistant, only.
"""

### What did you expect to see?

Cannot create Modelfile

### OS

Windows

**Comment by mxyng** [comment]
`FROM` is not a Windows command, it's content of the Modelfile.

1. Create a new file called Modelfile
2. Add FROM and other lines into the Modelfile
3. Save
4. Run `ollama create <name>`
