### ISSUE TITLE
ollama/ollama Docker image: committed modifications aren't saved

### ISSUE THREAD

**Issue by nicolasduminil** [ollama/ollama#3227]
### What is the issue?

I'm using the Docker image `ollama/ollama:latest`. I'm running the image and, in the new created container, I'm pulling `llama2`. Once the pull operation finished, I'm checking its success using the `ollama list` command.
Now, I commit the modification, I tag the new modified image and I push it on DockerHub.
Pulling it again, running it and checking the presence of `llama2` fails as the result of the `ollama list` command is empty this time.

### What did you expect to see?

I expect that the new augmented image contains `llama2` 

### Steps to reproduce

    $ docker pull ollama/ollama:latest
    $ docker run -d -v ollama:/root/.ollama -p 11434:11434 --name ollama ollama/ollama
    $ docker exec -ti ollama ollama pull llama2
       ... waiting 10 minutes ...
    $ docker exec -ti ollama ollama list
    NAME            ID              SIZE    MODIFIED           
    llama2:latest   78e26419b446    3.8 GB  About a minute ago
    $ docker commit ollama
    $ docker tag <image_id> nicolasduminil/ollama:llama2
    $ docker push nicolasduminil/ollama:llama2
    $ docker pull nicolasduminil/ollama:llama2
    $ docker run -d -v ollama:/root/.ollama -p 11434:11434 --name ollama nicolasduminil/ollama:llama2
    $ docker exec -ti ollama ollama list
    NAME            ID              SIZE    MODIFIED           

### Are there any recent changes that introduced the issue?

Negative

### OS

Linux

### Architecture

x86

### CPU

Intel

### Other software

None

**Comment by mxyng** [comment]
> $ docker run -d -v ollama:/root/.ollama -p 11434:11434 --name ollama ollama/ollama

This command starts the container and binds the ollama home directory to a docker volume. This volume is not part of the container image but the docker host so this is the expected behaviour. The behaviour you want requires removing the `-v`

**Comment by nicolasduminil** [comment]
Got it, thanks.
