### ISSUE TITLE
GPU does not run with Ollama

### ISSUE THREAD

**Issue by DerLehrer** [ollama/ollama#3230]
Hi everyone, 

I am running a Windows 10 computer with GTX950 and Intel(R) Core(TM) i5-3475S, 32 GB RAM,
I downloaded the new Windows-version of Ollama and the llama2-uncensored and also the tinyllama LLM.

Good: Everything works. 
Bad: Ollama only makes use of the CPU and ignores the GPU.

As far as I can tell, Ollama should support my graphics card and the CPU supports AVX. 
From the server-log:
_time=2024-03-18T23:06:15.263+01:00 level=INFO source=gpu.go:77 msg="Detecting GPU type"
time=2024-03-18T23:06:15.263+01:00 level=INFO source=gpu.go:191 msg="Searching for GPU management library nvml.dll"
time=2024-03-18T23:06:15.297+01:00 level=INFO source=gpu.go:237 msg="Discovered GPU libraries: [c:\\Windows\\System32\\nvml.dll C:\\Windows\\system32\\nvml.dll]"
time=2024-03-18T23:06:15.377+01:00 level=INFO source=gpu.go:82 msg="Nvidia GPU detected"
time=2024-03-18T23:06:15.377+01:00 level=INFO source=cpu_common.go:15 msg="CPU has AVX"
time=2024-03-18T23:06:15.395+01:00 level=INFO source=gpu.go:119 msg="CUDA Compute Capability detected: 5.2"
time=2024-03-18T23:06:15.396+01:00 level=INFO source=cpu_common.go:15 msg="CPU has AVX"
time=2024-03-18T23:06:15.396+01:00 level=INFO source=gpu.go:119 msg="CUDA Compute Capability detected: 5.2"
time=2024-03-18T23:06:15.396+01:00 level=INFO source=cpu_common.go:15 msg="CPU has AVX"
time=2024-03-18T23:06:15.396+01:00 level=INFO source=assets.go:63 msg="Updating PATH to ...
time=2024-03-18T23:06:15.472+01:00 level=INFO source=dyn_ext_server.go:150 msg="Initializing llama server"
ggml_init_cublas: GGML_CUDA_FORCE_MMQ:   no
ggml_init_cublas: CUDA_USE_TENSOR_CORES: yes
ggml_init_cublas: found 1 CUDA devices:
Device 0: NVIDIA GeForce GTX 950, compute capability 5.2, VMM: yes_
  
I would be glad if someone could tell me what to do to activate GPU-usage. 

Thanks

Chris

**Comment by zharklm** [comment]
Hi Chris,

Create a new environment variable OLLAMA_DEBUG with value 1 to get more information about what is going wrong.
[Ensure that you are using minimum driver version 452.39](https://github.com/ollama/ollama/blob/main/docs/windows.md#system-requirements)
[You might want to make sure you have CUDA installed too](https://docs.nvidia.com/cuda/cuda-installation-guide-microsoft-windows/index.html)

**Comment by dhiltgen** [comment]
I believe your GPU is a 2G card.  This means most models will not fit entirely into the VRAM of the GPU.  The layers of the model that wont fit are then processed by the CPU, and the GPU will have to wait for the CPU to keep up.

You mention you tried tinyllama which I would have expected to mostly fit into your VRAM and perform reasonably well.  On a GTX 750 2G card, I'm seeing ~15 tokens per second.  What sort of token rate are you seeing?  You can also try tinydolphin.

You can also check the server log for a line like this to see how many layers are actually loaded into VRAM.  

```
llm_load_tensors: offloaded 19/23 layers to GPU
```

We're working on improvements to our memory prediction algorithm which will allow us to more fully utilize VRAM without hitting out-of-memory crashes in an upcoming release.

**Comment by dhiltgen** [comment]
If you're seeing significantly slower behavior than what I described above, please let us know and share your server log so we can further investigate.
