### ISSUE TITLE
Add FinTral model

### ISSUE THREAD

**Issue by tqangxl** [ollama/ollama#3233]
### What model would you like?

pls add FinTral

**Comment by dynamicwebpaige** [comment]
It appears the Fintral model weights and source code are not publicly available (see reference links below). This means it's currently not possible to integrate Fintral directly into Ollama, as either the weights or a new model, trained from their source code, are needed to utilize the model.

* [Fintral paper page on HuggingFace](https://huggingface.co/papers/2402.10986)
* [Fintral repository on GitHub](https://github.com/gagan3012/Fintral)
