### ISSUE TITLE
is it possible to use ollama as a library , not through network

### ISSUE THREAD

**Issue by aizimuji** [ollama/ollama#3234]
### What are you trying to do?

i want to know if it's possible to call ollama function like some library, for example  by dll in windows
so other developer can develop some gui or related software with this library
not to run ollama as a stand-alone server

### How should we solve this?

it's easier to build related gui or other third party software based on ollama

**Comment by BruceMacD** [comment]
Hi @aizimuji Ollama isn't packaged for use as a library (at this point).

If you'd like to package Ollama into an application it is possible, but you would have to package the executable and run it as a sub-process. Here is an example of how to do that:
https://github.com/BruceMacD/chatd

Let me know if you have any more questions, happy to help.
