### ISSUE TITLE
Cannot install on Fedora 39 Silverblue: error: Packages not found: ./ollama-linux-amd64

### ISSUE THREAD

**Issue by jkemp814** [ollama/ollama#3235]
### What is the issue?

Package from the releases page will not install with `rpm-ostree install ./ollama-linux-amd64`

Also when using the install script: `curl -fsSL https://ollama.com/install.sh | sh` it does not create `ollama` folder under `/usr/share`

When installing in a toolbox it cannot find the GPU.

### What did you expect to see?

Install and create user/group/folder when running the curl install script.

If installing using `rpm-ostree install` there should be package info.

### Steps to reproduce

Try and install using `rpm-ostree install` asset from releases page.

or

install try and install using the `curl install script` and notice /usr/share/ollama does not get created.

### Are there any recent changes that introduced the issue?

No first time trying to install.

### OS

Linux

### Architecture

amd64

### Ollama version

0.1.29

### GPU

Nvidia

### GPU info

 NVIDIA-SMI 550.54.14
Driver Version: 550.54.14
CUDA Version: 12.4

### CPU

Intel

### Other software

Fedora Linux 39 Silverblue
GNOME 45.5-1
Alacritty 0.13.1
Open WebUI 0.1.113

**Comment by jkemp814** [comment]
Mar 19 00:12:56 HP-Z840 systemd[1]: Started ollama.service - Ollama Service.
Mar 19 00:12:57 HP-Z840 systemd[1]: ollama.service: Main process exited, code=exited, status=1/FAILURE
Mar 19 00:12:57 HP-Z840 ollama[127860]: Couldn't find '/usr/share/ollama/.ollama/id_ed25519'. Generating new private key.
Mar 19 00:12:57 HP-Z840 ollama[127860]: Error: could not create directory mkdir /usr/share/ollama: read-only file system
Mar 19 00:12:57 HP-Z840 systemd[1]: ollama.service: Failed with result 'exit-code'.

**Comment by jkemp814** [comment]
● ollama.service - Ollama Service
     Loaded: loaded (/etc/systemd/system/ollama.service; disabled; preset: disabled)
    Drop-In: /usr/lib/systemd/system/service.d
             └─10-timeout-abort.conf
     Active: active (running) since Tue 2024-03-19 00:12:31 PDT; 3ms ago
   Main PID: 127717 ((ollama))
      Tasks: 1 (limit: 76999)
     Memory: 0B
        CPU: 0
     CGroup: /system.slice/ollama.service
             └─127717 "[(ollama)]"

Mar 19 00:12:31 HP-Z840 systemd[1]: ollama.service: Scheduled restart job, restart counter is at 47.
Mar 19 00:12:31 HP-Z840 systemd[1]: Started ollama.service - Ollama Service.

**Comment by aosan** [comment]
Hi @jkemp814 
Silverblue is immutable, running as a read-only image. rpm-ostree rebuilds the image by adding the rpm package. 

Until ollama is supported as a rpm package, script installers are not the ideal choice for immutable systems. Silverblue is not  geared for installing/testing software outside the image, hence the read-only file system error.

**Comment by jkemp814** [comment]
Thank you for the response.

Yes it is immutable. I managed to get it installed in a container by Podman.

**Comment by dhiltgen** [comment]
It sounds like this is ultimately an ask for an RPM package for Ollama.  In that case, this is tracked via #3067

**Comment by mecattaf** [comment]
@jkemp814 Podman works but the best way I have found to use Ollama on my Fedora Silverblue device is with [distrobox](https://github.com/89luca89/distrobox) and using the [bluefin CLI image](https://github.com/ublue-os/toolboxes?tab=readme-ov-file#bluefin-cli) which has homebrew installed by default. 

Steps:
1) Install distrobox as a layered package:
```
rpm-ostree install distrobox
```
2) Reboot
3) Create the bluefin distrobox (or change its name) and load it
```
distrobox create -i ghcr.io/ublue-os/bluefin-cli -n bluefin
distrobox enter bluefin
```
4) Since the bluefin comes preloaded with homebrew you can install ollama with:
```
brew install ollama
```

Hope this helps!

References:
[U-blue discourse](https://universal-blue.discourse.group/t/prototyping-the-bluefin-cli-experience/469)

**Comment by grondilu** [comment]
I'm confused.  Shouldn't this work under a toolbox environment?

**Comment by tsilvs** [comment]
@grondilu `toolbox` environments are unreliable. There are driver issues, GUI issues, missing library issues, outdated image & container issues, no convenient tools to upgrade containers, etc, etc.

**Comment by grondilu** [comment]
Following the [manual install page](https://github.com/ollama/ollama/blob/main/docs/linux.md) is fairly straightforward.  It's just a tarball extraction.  To make it compatible with silverblue, I just had to extract it to $HOME/.local instead of /usr :

    $ wget -q -O - https://ollama.com/download/ollama-linux-amd64.tgz |tar xvfz -C ~/.local/ -

then `ollama serve` in a terminal and `ollama run llama3.2` in an other.  It works surprisingly fast on my CPU (AMD Ryzen 7).

Now I just need to figure out how to make it a systemd service.

**Comment by mecattaf** [comment]
@grondilu perhaps this might be helpful to you, if you want a more streamlined way to do this with fedora atomic. If you use [Project bluebuild](https://github.com/blue-build/template)

- this is the script that loads the binary: https://github.com/mecattaf/zen/blob/main/files/scripts/install-ollama.sh (i don't have a GPU so removed all the related sections from official install script, if you choose to extend this to include GPU operations please LMK!)
- https://github.com/mecattaf/zen/blob/main/files/systemd/system/ollama-boot.service inspired by how SDDM permissions are created (thanks for the comment fiftydinar)
- https://github.com/mecattaf/zen/blob/main/files/system/usr/etc/ollama/ollama-useradd same as above
- https://github.com/mecattaf/zen/blob/main/files/systemd/system/ollama.service
- and finally once all the above are in the right locations add to your recipe.yml:
```
  - type: script
    scripts:
      - install-ollama.sh

  - type: systemd
    system:
      enabled:
        - ollama-boot.service
        - ollama.service
```

**Comment by grondilu** [comment]
> * https://github.com/mecattaf/zen/blob/main/files/system/usr/etc/ollama/ollama-useradd same as above

I see this uses /usr/share but my understanding is that this is mounted read-only on silverblue so I'm not sure I can use this script as is.
