### ISSUE TITLE
Add a google colab notebook link to the github for new users.

### ISSUE THREAD

**Issue by jquintanilla4** [ollama/ollama#3238]
### What are you trying to do?

Every once in a while people will ask about how to get Ollama running on Google Colab, either for doing dev work inside of Colab or as a remote GPU. I think if the github repo had a one click button to a notebook, it would solve this evergreen question on the community.

### How should we solve this?

I created a notebook and tested it to solve this issue.
https://colab.research.google.com/drive/1-K00WnTdDJC2JCuFNLKKa-ScmcDWi1Nw?usp=sharing

### What is the impact of not solving this?

Always pasting the link on discord.

### Anything else?

Happy to make edits.

**Comment by mxyng** [comment]
Thanks for the issue but we're not looking to add buttons into the repo at this time. A jupyter notebook example is provided [here](https://github.com/ollama/ollama/tree/main/examples/jupyter-notebook) which can be imported into colab

**Comment by jquintanilla4** [comment]
the jupyter notebook example is outdated; ngrok now requires a token to function inside of google colab. The notebook in the document also doesn't account for people that may want to develop inside of google colab.

**Comment by atul-ai** [comment]
This is a big pain for me right now, I want to use ollama for a small llm-related tutorial and I am trying to install it on a Colab with gemma:2b for ease of use. 
Based on responses, it is unclear if this still works.
