### ISSUE TITLE
Vercel AI SDK with Ollama - not for production

### ISSUE THREAD

**Issue by jakobhoeg** [ollama/ollama#3239]
### What is the issue?

The [blog post](https://ollama.com/blog/openai-compatibility) about how Vercel AI SDK can be integrated with Ollama should be updated to include that it's NOT for production and only works locally.

Calls from NextJS api routes can't be proxied to localhost. When this route is called on a hosted instance, it runs on the server and can't access the Ollama running on a local machine.

### What did you expect to see?

I expected to be able to host it through Vercel and still be able to hit my locally running Ollama. It doesn't state that this isn't possible and since the Vercel AI SDK is there, it implies for it to work.

### OS

Windows

### Other software

Vercel

**Comment by xycjscs** [comment]
Openai sdk can be accessed from local machine, remote machine (via python), and remote machine (curl). However, once it is hosted on the vercel, it failed. 
Any clue or idea? I have already added it into my production on the vercel.

**Comment by xycjscs** [comment]
> Openai sdk can be accessed from local machine, remote machine (via python), and remote machine (curl). However, once it is hosted on the vercel, it failed. Any clue or idea? I have already added it into my production on the vercel.

`import { CHAT_SETTING_LIMITS } from "@/lib/chat-setting-limits"
import { checkApiKey, getServerProfile } from "@/lib/server/server-chat-helpers"
import { ChatSettings } from "@/types"
import { OpenAIStream, StreamingTextResponse } from "ai"
import OpenAI from "openai"
import { ChatCompletionCreateParamsBase } from "openai/resources/chat/completions.mjs"
import { ServerRuntime } from "next"

export const runtime: ServerRuntime = "edge"

export async function POST(request: Request) {
  const json = await request.json()
  const { chatSettings, messages } = json as {
    chatSettings: ChatSettings
    messages: any[]
  }

  try {
    const openai = new OpenAI({
      apiKey: "any",
      baseURL: `${process.env.NEXT_PUBLIC_OLLAMA_URL}/v1` 
    })

    console.log(messages)

    const response = await openai.chat.completions.create({
      model: chatSettings.model as ChatCompletionCreateParamsBase["model"],
      messages: messages as ChatCompletionCreateParamsBase["messages"],
      temperature: chatSettings.temperature,
      max_tokens:
        CHAT_SETTING_LIMITS[chatSettings.model].MAX_TOKEN_OUTPUT_LENGTH,
      stream: true
    })

    const stream = OpenAIStream(response)

    return new StreamingTextResponse(stream)
  } catch (error: any) {
    const errorMessage = error.error?.message || "An unexpected error occurred"
    const errorCode = error.status || 500
    return new Response(JSON.stringify({ message: errorMessage }), {
      status: errorCode
    })
  }
}
`

**Comment by dhiltgen** [comment]
Is this still a problem?  Does it require adjusting the `OLLAMA_ORIGINS` setting?

https://github.com/ollama/ollama/blob/main/docs/faq.md#how-can-i-allow-additional-web-origins-to-access-ollama

**Comment by pdevine** [comment]
I'm going to close this, but we can reopen it if it's still a problem.
