### ISSUE TITLE
When I run the model my CPU usage is high but GPU usage is low

### ISSUE THREAD

**Issue by wangshuai67** [ollama/ollama#3242]
### What is the issue?

1. This is the gpu information of docker container

![image](https://github.com/ollama/ollama/assets/13214849/d3d81824-5854-4fcf-b9fd-83bfa0d1c4ec)
![image](https://github.com/ollama/ollama/assets/13214849/426ab93f-4b91-4dfd-b178-c9112e0b944f)

2. This is the gpu information of the host machine

![image](https://github.com/ollama/ollama/assets/13214849/f5a66995-dfd8-4d27-b019-225bc32a0485)

![image](https://github.com/ollama/ollama/assets/13214849/bfe74c83-6eef-4629-a75c-1b111238e377)

### What did you expect to see?

Is there any abnormality in the above information?  

### OS

Linux

### Architecture

x86

### Platform

Docker

### Ollama version

0.1.27

### GPU

Nvidia

### GPU info

![image](https://github.com/ollama/ollama/assets/13214849/f5a66995-dfd8-4d27-b019-225bc32a0485)

**Comment by Elghandour-eng** [comment]
Same Issue With Me

**Comment by yasserkh2** [comment]
i have the same issue
![Screenshot 2024-03-19 130738](https://github.com/ollama/ollama/assets/125663999/e6a65303-9f7b-40da-9cfd-d4db0b81d3a3)

**Comment by dhiltgen** [comment]
@wangshuai67 can you share your server log?

**Comment by VectorZhao** [comment]
+1

**Comment by RamiKassouf** [comment]
same issue

**Comment by xvbingbing** [comment]
How can I use my GPU to run ollama on linux? Can someone give me some detailed instructions?

**Comment by dhiltgen** [comment]
Check out https://github.com/ollama/ollama/blob/main/docs/troubleshooting.md for instructions on how to retrieve the server log, which varies by platform.

**Comment by dhiltgen** [comment]
If you're still having trouble, please share the server log and I'll re-open the issue.
