### ISSUE TITLE
Problem with returning response with openai compatibility

### ISSUE THREAD

**Issue by ejgutierrez74** [ollama/ollama#3258]
### What is the issue?

The response output is somehow a list:

> ('The sentiment of "Hi Amit, thanks for the thoughtful birthday card!" is positive. The use of the word "thoughtful" suggests that the speaker appreciates the effort and care put into the card, and the exclamation mark at the end conveys a sense of gratitude and warmth. Overall, the sentiment is friendly, sincere, and appreciative.', 0)

### What did you expect to see?

The text of the response....

> The sentiment of "Hi Amit, thanks for the thoughtful birthday card!" is positive. The use of the word "thoughtful" suggests that the speaker appreciates the effort and care put into the card, and the exclamation mark at the end conveys a sense of gratitude and warmth. Overall, the sentiment is friendly, sincere, and appreciative.

As for now i can access that with:

```
print(response[0]) or
print(response[0].strip())
```

### Steps to reproduce

Execute this code;

```python
`def llama_openai(prompt, 
          add_inst=True, #By default True, if you use a base model should write it as False
          model="llama2", 
          temperature=0.0, #By default in openai is 1.0 o 0.7 depends of the model, openai from 0.0 to 2.0, llama2 from 0.0 to 1.0
          max_tokens=1024,
          verbose=False
         ):
    
    if add_inst:
        prompt = f"[INST]{prompt}[/INST]"

    if verbose:
        print(f"Prompt:\n{prompt}\n")
        print(f"model: {model}")

    error = 0
  
    try:
        response = client.chat.completions.create(
            messages=[
                        {
                        'role': 'user',
                        'content': prompt,
                        }
                    ],
            model=model,
            max_tokens=max_tokens,
            temperature=temperature
                )

    except openai.APIError as e:
      #Handle API error here, e.g. retry or log
      print(f"Llama2: OpenAI API returned an API Error:{e} ")
      error = 1
      pass
    except openai.APIConnectionError as e:
      #Handle connection error here
      print(f"Llama2:Failed to connect to OpenAI API:{e} ")
      error = 2
      pass
    except openai.RateLimitError as e:
      #Handle rate limit error (we recommend using exponential backoff)
      print(f"Llama2: OpenAI API request exceeded rate limit:{e} ")
      error = 3
      pass
    except ConnectionError as e:
        # Handle ConnectionError here
        print(f"Llama2: Connection Refused, perhaps server not running, network problem or address ip and port incorrect: {e}")
        error = 4
        pass
    except Exception as e:
        # Handle all other exceptions.
        print(f"Llama2: Error general no reconegut: {e}")
        error = 5
        pass

    #Si no salta ninguna excpeción, todo va bien..Vamos a devolver la respuesta del sistema y el error que deberia ser cero
    else:    
        #Si no hay ninguna excepcion se ejecuta else
        return (response.choices[0].message.content, error)
    
    #Si ha saltado alguna excepcion devolvemos algo y el codigo de error
    return ("Default Value", error)
`
```
Then execute a test:

```python
prompt = """
What is the sentiment of:
Hi Amit, thanks for the thoughtful birthday card!
"""
response = llama_openai(prompt)
print(response)
```

Then somehow the returned value:

> ('The sentiment of "Hi Amit, thanks for the thoughtful birthday card!" is positive. The use of the word "thoughtful" suggests that the speaker appreciates the effort and care put into the card, and the exclamation mark at the end conveys a sense of gratitude and warmth. Overall, the sentiment is friendly, sincere, and appreciative.', 0)

### Are there any recent changes that introduced the issue?

I think so, that in ollama v1.0.28 didnt happen...but not sure.

### OS

Linux

### Architecture

amd64

### Ollama version

0.1.29

**Comment by BruceMacD** [comment]
Hi Amit, there were no changes in Ollama which should have started causing this behavior. Do you see this when you use the CLI also?

**Comment by ejgutierrez74** [comment]
Are you writing to me ? As your wrote hi Amit....dont know who is Amit...( perhaps some english expression i dont understand)
I only use jupyter notebook in my courses and test...

**Comment by royjhan** [comment]
```
response = client.chat.completions.create(
    model="llama3",
    messages=[
        {
            "role": "user",
            "content": "What's the weather like in San Francisco?"
        }
    ],
    max_tokens=300,
)

print(response.choices[0].message.content)
```

this is working as expected, please reopen the issue if you are still experiencing this problem.

**Comment by ejgutierrez74** [comment]
Yes but my function is returning as you said: response.choices[0].message.content that should be the reponse text in the example: "The sentiment of "Hi Amit, thanks for the thoughtful birthday card!" is positive. The use of the word "thoughtful" suggests that the speaker appreciates the effort and care put into the card, and the exclamation mark at the end conveys a sense of gratitude and warmth. Overall, the sentiment is friendly, sincere, and appreciative."..so i think is not working as expected...

**Comment by royjhan** [comment]
That looks like a reasonable response to me? What is not working from your perspective?

**Comment by ejgutierrez74** [comment]
As said: response.choices[0].message.content  should in my opinion return the reponse text in the example, only the text of the response: 
_The sentiment of "Hi Amit, thanks for the thoughtful birthday card!" is positive. The use of the word "thoughtful" suggests that the speaker appreciates the effort and care put into the card, and the exclamation mark at the end conveys a sense of gratitude and warmth. Overall, the sentiment is friendly, sincere, and appreciative_, not the tuple
