### ISSUE TITLE
Syntax error: end of file unexpected (expecting ";;")

### ISSUE THREAD

**Issue by TacitTactics** [ollama/ollama#3260]
### What is the issue?

file format issue.

### What did you expect to see?

No errors

### Steps to reproduce

run provided curl call to install script, as is.

### Are there any recent changes that introduced the issue?

Work around: install dos2unix, download the install script, and then run " dos2unix <filename>"

### OS

Linux

### Architecture

amd64

### Ollama version

current

### GPU

Nvidia

### CPU

Intel

**Comment by dhiltgen** [comment]
I was unable to repro.

Can you share a bit more information about your setup?  What Linux distro are you running?  Can you copy-paste the output of the script?  Did you already have the Nvidia driver installed?

**Comment by TacitTactics** [comment]
Sure , I am running Linux Mint 21,  the title of the issue is the only output I received.  Yes my Nvidia driver was already installed. To be honest I tried the curl command again and it worked without error.

**Comment by dhiltgen** [comment]
Perhaps there was a network glitch and the file was only partially downloaded.  If you see it again, let us know.
