### ISSUE TITLE
Ollama can support windows 7?

### ISSUE THREAD

**Issue by zhaosd** [ollama/ollama#3262]

**Comment by dhiltgen** [comment]
Unfortunately the tools and libraries we require to build Ollama no longer support Windows 7.

**Comment by zhaosd** [comment]
dhiltgen, got it. Thank you very much!

**Comment by ryudswift** [comment]
noob question...
could it be possible, if the tools and libraries could be replaced with windows 7 supported libraries?

**Comment by tamr** [comment]
You can actually run it using the extended kernel https://github.com/vxiiduu/VxKex it works just fine for me.

**Comment by ryudswift** [comment]
Will give it a try and update results -hopefully

**Comment by Ceazy-Gentleman** [comment]
> You can actually run it using the extended kernel https://github.com/vxiiduu/VxKex it works just fine for me.

hello，it does not work for me，terminal will display erro encoding like[25xxx]
