### ISSUE TITLE
"CUDA error: out of memory" after random number of API requests

### ISSUE THREAD

**Issue by RandomGitUser321** [ollama/ollama#3264]
### What is the issue?

I run a workflow in ComfyUI that makes calls to Ollama server's API to generate prompts or analyze images. It works fine, normally, but occasionally I get CUDA errors that then make me have to restart the server. It's kind of disruptive to my workflow because I have to check back every 5-10 minutes to make sure a queued list isn't being stalled.

Within the API call, I use `keep_alive="0"` because otherwise I run into issues with generating an image right after (stable diffusion that needs a lot of VRAM) and sometimes parts of either model get stuck in shared memory. The command works fine and unloads the LLM from the VRAM. I think it will persist in system ram afterwards, which is also fine, since it's faster to reload ram->vram, than it is to have to reopen the whole model off the drive again.

The basic flow of what I'm doing is send a request to Ollama->get response->unload LLM from VRAM->use response for stable diffusion->new seed for Ollama->rinse and repeat. ComfyUI is also set to unload models back to system ram as well.

I added a time.sleep() to my node that sends the requests to Ollama thinking maybe it just needs a little more time for the unloading phase.

### What did you expect to see?

I'd expect it not to have this error

### Steps to reproduce

I should also note that my call looks like this:
```
time.sleep(2) #attempting to see if this helps solve the problem
response = client.generate(model=model, prompt=prompt, system=system, options={'num_predict': num_predict, 'temperature': temperature, 'seed': seed}, keep_alive="0")
```

### OS

Windows

### Ollama version

v0.1.29

### GPU

Nvidia

### GPU info

RTX 2080 with latest Nvidia drivers.

### CPU

Intel

**Comment by obiscr** [comment]
I had a similar problem, but it happened to me the second time I switched model.

I just started using the model **llama2:7b**, and after I send a few messages, when I switch to **gemma:7b** model (without clearing the context), I get an error

![image](https://github.com/ollama/ollama-js/assets/28687074/8d5159c7-5b9e-42f7-9a7c-e4eb2251c4d7)

```
POST http://127.0.0.1:11434/api/chat net::ERR_CONNECTION_REFUSED
fetchWithHeaders @ ollama.be8fd0da.mjs:69
post @ ollama.be8fd0da.mjs:88
processStreamableRequest @ ollama.be8fd0da.mjs:190
chat @ ollama.be8fd0da.mjs:248
AskGPT @ request.ts:13
handleSend @ chat.tsx:83
handleKeyDown @ chat.tsx:89
eval @ import.mjs:1477
callCallback @ react-dom.development.js:4164
invokeGuardedCallbackDev @ react-dom.development.js:4213
invokeGuardedCallback @ react-dom.development.js:4277
invokeGuardedCallbackAndCatchFirstError @ react-dom.development.js:4291
executeDispatch @ react-dom.development.js:9041
processDispatchQueueItemsInOrder @ react-dom.development.js:9073
processDispatchQueue @ react-dom.development.js:9086
dispatchEventsForPlugins @ react-dom.development.js:9097
eval @ react-dom.development.js:9288
batchedUpdates$1 @ react-dom.development.js:26135
batchedUpdates @ react-dom.development.js:3991
dispatchEventForPluginEventSystem @ react-dom.development.js:9287
dispatchEventWithEnableCapturePhaseSelectiveHydrationWithoutDiscreteEventReplay @ react-dom.development.js:6465
dispatchEvent @ react-dom.development.js:6457
dispatchDiscreteEvent @ react-dom.development.js:6430
Show 20 more frames
Show less
ollama.be8fd0da.mjs:69 
        
        
Uncaught (in promise) TypeError: Failed to fetch
    at fetchWithHeaders (ollama.be8fd0da.mjs:69:10)
    at post (ollama.be8fd0da.mjs:88:26)
    at Ollama.processStreamableRequest (ollama.be8fd0da.mjs:190:28)
    at Ollama.chat (ollama.be8fd0da.mjs:248:17)
    at AskGPT (request.ts:13:28)
    at handleSend (chat.tsx:83:21)
    at handleKeyDown (chat.tsx:89:19)
    at eval (import.mjs:1477:9)
    at HTMLUnknownElement.callCallback (react-dom.development.js:4164:14)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4213:16)
    at invokeGuardedCallback (react-dom.development.js:4277:31)
    at invokeGuardedCallbackAndCatchFirstError (react-dom.development.js:4291:25)
    at executeDispatch (react-dom.development.js:9041:3)
    at processDispatchQueueItemsInOrder (react-dom.development.js:9073:7)
    at processDispatchQueue (react-dom.development.js:9086:5)
    at dispatchEventsForPlugins (react-dom.development.js:9097:3)
    at eval (react-dom.development.js:9288:12)
    at batchedUpdates$1 (react-dom.development.js:26135:12)
    at batchedUpdates (react-dom.development.js:3991:12)
    at dispatchEventForPluginEventSystem (react-dom.development.js:9287:3)
    at dispatchEventWithEnableCapturePhaseSelectiveHydrationWithoutDiscreteEventReplay (react-dom.development.js:6465:5)
    at dispatchEvent (react-dom.development.js:6457:5)
    at dispatchDiscreteEvent (react-dom.development.js:6430:5)
```

**server.log**

![image](https://github.com/ollama/ollama/assets/28687074/4a9f91a2-8eb9-4525-aa70-0b65e7657290)

**Comment by shanchuantian** [comment]
I also met the error "CUDA error: out of memory" in windows, i was wondering if this problem exists on Linux, or is it only on Windows?Does any one know? thanks.

**Comment by dhiltgen** [comment]
We've been making steady improvements in our memory prediction logic, so I'd give the latest release a try.  If things are still ~unstable with the latest release, you might try adding some delay between toggling between VRAM consumers to give the system some time to stabilize.

That said, I think you'll see the most improvement once I get #4599 resolved.

**Comment by dhiltgen** [comment]
The latest release should perform much better on understanding the available VRAM on the system.  If you're still having problems after updating to 0.1.45, please share an updated log and repro scenario and I'll reopen the issue.
