### ISSUE TITLE
Embedding model support

### ISSUE THREAD

**Issue by jmorganca** [ollama/ollama#327]
Add embedding models to use primarily with `/api/embeddings`

* `instructor-xl`
* `bge-large`
* `all-MiniLM-L6-v2`

See the full [leaderboard](https://huggingface.co/spaces/mteb/leaderboard)

**Comment by brunnolou** [comment]
Yes, please! Any of these embedding models above `text-embedding-ada-002` would be a great addition.

I've tried LLam2 and Mistral model with the `/api/embeddings` as is, and I'm getting poor-quality similarity scores.
Even with almost identical queries, It fails to retrieve results. Are there some prompting technics to improve the embedding quality?

Anyway, in comparison, I've tried [Xenova/gte-small](https://huggingface.co/Xenova/gte-small) with transformers and it is much faster and yields better results.

**Comment by corani** [comment]
`jinaai/jina-embeddings-v2-base-en` (and other variants) also look promising.

**Comment by sandangel** [comment]
Hi, is there an update on this issue? I would love to contribute

**Comment by corani** [comment]
I've been playing with https://github.com/nlpodyssey/cybertron which is pure Go (but I guess CPU only?) and at least supports `all-MiniLM-L6-v2`, `e5-*-v2`, `bge-*-en-v1.5` and `ember-v1`.

I did some testing with the [STS-2016](https://alt.qcri.org/semeval2016/task1/) dataset and got accuracies (Pearson correlation with the gold answers):

- Ollama
   - `llama2`: 0.23431
   - `mistral:instruct`: 0.5656
-  Cybertron
   - `all-MiniLM-L6-v2`: 0.80344
   - `e5-small-v2`: 0.82318
   - `e5-base-v2`: 0.83845
   - `bge-small-en-v1.5`: 0.84514
   - `bge-base-en-v1.5`: 0.85297

So I agree with the previous comment that the embeddings generated by the completion models are pretty bad!

**Comment by sandangel** [comment]
That is interesting. For GPU support, I guess we will need to use: https://github.com/skeskinen/bert.cpp ?
I think the implementation would be something similar to llama.cpp?

**Comment by sandangel** [comment]
I found this issue: https://github.com/ggerganov/llama.cpp/issues/2872
I think they plan to implement it in llama.cpp. So maybe we will just need to update the llama.cpp when it's done?

**Comment by sandangel** [comment]
I also found this https://github.com/ml-explore/mlx-examples/blob/main/bert/README.md, which we can use to run inference on M1 mac. Is it possible to support `mlx` with Ollama?

**Comment by CodeWithKyrian** [comment]
Any update on this or plan to allow Bert Models?

**Comment by tjohnson4** [comment]
Any update on this issue?

**Comment by ymohamed08** [comment]
Do you have any updates so far? very interested to contribute

**Comment by easp** [comment]
Plans to support BERT models in llama.cpp stalled out when the dev who had assumed the task ended up focusing on something else. In the last few days it looks like the project management artifacts were updated to acknowledge this, so maybe there will be some action soon. Actually, it looks like there has been some activity. Maybe there will be working code soon: 
https://github.com/ggerganov/llama.cpp/issues/2872

**Comment by AndreBerzun** [comment]
BERT support was [merged](https://github.com/ggerganov/llama.cpp/pull/5423) 3 days ago into llama.cpp

**Comment by easp** [comment]
Looks like there are still kinks being worked out.

**Comment by s-kostyaev** [comment]
> Looks like there are still kinks being worked out.

Link to check the progress https://github.com/ggerganov/llama.cpp/pull/5500

**Comment by s-kostyaev** [comment]
> > Looks like there are still kinks being worked out.
> 
> Link to check the progress [ggerganov/llama.cpp#5500](https://github.com/ggerganov/llama.cpp/pull/5500)

It is merged now

**Comment by AndreBerzun** [comment]
@jmorganca just wanted to follow up and see if this topic is on your roadmap. Since llama.cpp added support for BERT models, this seems like a great low-hanging fruit, no? 

Initial support for BERT models has been merged with [ggerganov/llama.cpp#5423](https://github.com/ggerganov/llama.cpp/pull/5423) and released with [b2127](https://github.com/ggerganov/llama.cpp/releases/tag/b2127). Some kinks related to embedding pooling were fixed with [ggerganov/llama.cpp#5500](https://github.com/ggerganov/llama.cpp/pull/5500). [Batch embedding](https://github.com/ggerganov/llama.cpp/pull/5466) is supported as well.

There has been a new bug related to the [tokenizer implementation](https://github.com/ggerganov/llama.cpp/issues/5496) but that's it as [far as I can tell](https://github.com/ggerganov/llama.cpp/issues?q=is%3Aissue+is%3Aopen+bert).

**Comment by jmorganca** [comment]
@AndreBerzun it absolutely is – working on it!
