### ISSUE TITLE
Error: exception create_tensor: tensor 'output.weight' not found

### ISSUE THREAD

**Issue by GhadaJouini** [ollama/ollama#3272]
### What is the issue?

I'm trying to add a custom model in ollama but am encountering this error. Is it possible that the model quantization is not correct ?

**Error: exception create_tensor: tensor 'output.weight' not found**

Quantized model:  https://huggingface.co/MaziyarPanahi/zephyr-7b-gemma-v0.1-GGUF

I’m under ollama version : **0.1.29**

**Os distribution:**

PRETTY_NAME="Ubuntu 22.04.4 LTS" NAME="Ubuntu" VERSION_ID="22.04" VERSION="22.04.4 LTS (Jammy Jellyfish)" VERSION_CODENAME=jammy ID=ubuntu ID_LIKE=debian

![OllamaError](https://github.com/ollama/ollama/assets/32711189/63fcd1a1-8f52-4ece-806e-60fda31de382)

![OSDistribution](https://github.com/ollama/ollama/assets/32711189/f3dbd0c3-b617-4ebe-9a6f-692fa904480c)

### What did you expect to see?

The model should run correctly

### Steps to reproduce

Step 1: installing git lfs
Step2 : Using the [HuggingFaceModelDownloader](https://github.com/bodaay/HuggingFaceModelDownloader) to download the model from huggingFace
Step 3: Create the Modelfile 
Step 4: Create the model using the command: **ollama create "zephyr-7b-gemma-v0.1.Q6_0" -f Modelfile**
Step 5: Run the model using the command: **ollama run zephyr-7b-gemma-v0.1.Q6_0:latest**

### Are there any recent changes that introduced the issue?

Modelfile:

FROM ./zephyr-7b-gemma-v0.1.Q6_K.gguf

TEMPLATE "<|im_start|>system
{system_message}<|im_end|>
<|im_start|>user
{prompt}<|im_end|>
<|im_start|>assistant"

### GPU

No GPU

**Comment by jmorganca** [comment]
Hi there, this should be fixed now.

**Comment by nverma-algo** [comment]
I'm facing the exact same error, `Error: exception create_tensor: tensor 'output.weight' not found`, but for me, I pulled the llama3.2:1b model from ollama and then tried running it. 
Steps to reproduce:
1. Run `ollama pull llama3.2:1b`
2. Run `ollama run llama3.2:1b` 

OS: Ubuntu 20.04 64 bit
Memory: 19 GB
