### ISSUE TITLE
Allow system message to be on its own

### ISSUE THREAD

**Issue by jackielii** [ollama/ollama#3287]
### What are you trying to do?

Current prompt rendering assumes there is only one system message. With the [Command-R model from Cohere AI](https://huggingface.co/CohereForAI/c4ai-command-r-v01), there can be multiple system message: https://docs.cohere.com/docs/prompting-command-r#structured-prompt-templates. There is no way to get around this.

Consider the following messages:

```go
{Role: "system", Content: "Preambles"},
{Role: "user", Content: "i'm user"},
{Role: "system", Content: "Tool output"},
{Role: "system", Content: "---Instructions---"},
```

And the template:

```
<BOS_TOKEN>
  {{ if .System }}<|START_OF_TURN_TOKEN|><|SYSTEM_TOKEN|>{{ .System }}<|END_OF_TURN_TOKEN|>{{ end }}
  {{ if .Prompt }}<|START_OF_TURN_TOKEN|><|USER_TOKEN|>{{ .Prompt }}<|END_OF_TURN_TOKEN|>{{ end }}<|START_OF_TURN_TOKEN|><|CHATBOT_TOKEN|>{{ .Response }}
```

We get

```
<BOS_TOKEN>
<|START_OF_TURN_TOKEN|><|SYSTEM_TOKEN|>Preambles<|END_OF_TURN_TOKEN|>
<|START_OF_TURN_TOKEN|><|USER_TOKEN|>i'm user<|END_OF_TURN_TOKEN|>
<|START_OF_TURN_TOKEN|><|CHATBOT_TOKEN|><BOS_TOKEN>
<|START_OF_TURN_TOKEN|><|SYSTEM_TOKEN|>Tool output<|END_OF_TURN_TOKEN|>

<|START_OF_TURN_TOKEN|><|CHATBOT_TOKEN|><BOS_TOKEN>
<|START_OF_TURN_TOKEN|><|SYSTEM_TOKEN|>---Instructions---<|END_OF_TURN_TOKEN|>

<|START_OF_TURN_TOKEN|><|CHATBOT_TOKEN|>
```

However, the desired output is:

```
<BOS_TOKEN>
<|START_OF_TURN_TOKEN|><|SYSTEM_TOKEN|>Preambles<|END_OF_TURN_TOKEN|>
<|START_OF_TURN_TOKEN|><|USER_TOKEN|>i'm user<|END_OF_TURN_TOKEN|>
<|START_OF_TURN_TOKEN|><|CHATBOT_TOKEN|><BOS_TOKEN>
<|START_OF_TURN_TOKEN|><|SYSTEM_TOKEN|>Tool output<|END_OF_TURN_TOKEN|>
<|START_OF_TURN_TOKEN|><|SYSTEM_TOKEN|>---Instructions---<|END_OF_TURN_TOKEN|>
<|START_OF_TURN_TOKEN|><|CHATBOT_TOKEN|>
```

### How should we solve this?

In order to make this backward compatible, I suggest we introduce a new version of the template that formats each message as is. It'll be much easier to control the desired output

The code to render the prompt should detect is the new template is present and use it instead. Preferably, gradually deprecate old template.

### What is the impact of not solving this?

There doesn't seems to be a backward compatible way to fix this. Introducing a new template add complexity, especially for new users. But there doesn't seems to be a better way.

**Comment by pdevine** [comment]
Hey @jackielii , sorry for the slow response. There actually is a _raw mode_ for `/api/generate` if you check out the [API documentation](https://github.com/ollama/ollama/blob/main/docs/api.md#generate-a-completion). We've been trying to rethink the way the templating works but haven't landed on anything ideal as of yet.

**Comment by jmorganca** [comment]
Hi @jackielii, this should be fixed. Some models do expect the system prompt to be bundled into one message at the beginning (e.g. Mistral, Llama 3/3.1), but otherwise Ollama will respect system messages that are interleaved with others. Let me know if you're seeing different behavior from this.
