### ISSUE TITLE
ollama run in national user name

### ISSUE THREAD

**Issue by hgabor47** [ollama/ollama#3293]
### What is the issue?

![image](https://github.com/ollama/ollama/assets/1212585/5a14f850-213b-471c-90c9-f1f0f8752c31)
My Username has international characters like á and the ollama not handle it.

### What did you expect to see?

RUN

### Steps to reproduce

1 Create a windows user with international charaters like: Gábor
2 start the ollama with: ollama run llama2

### OS

Windows

### Architecture

amd64

### GPU

Nvidia

### CPU

AMD

**Comment by dhiltgen** [comment]
PR #3273 should resolve this.

**Comment by dims** [comment]
@dhiltgen looks like it got fixed in https://github.com/ggerganov/llama.cpp/commit/94d1b3b4119209efcdd08df0dceaecbd1fe7f85c via PR https://github.com/ggerganov/llama.cpp/pull/6248

**Comment by dhiltgen** [comment]
Unicode characters in the model directory should be working now.  Please give [0.1.33](https://github.com/ollama/ollama/releases) (available in pre-release) a try and let us know.

**Comment by dhiltgen** [comment]
If you're still having problems with unicode characters in the model directory with 0.1.33, please let us know.
