### ISSUE TITLE
Vision with llava-1.6-7B is unusable via CLI

### ISSUE THREAD

**Issue by olafgeibig** [ollama/ollama#3298]
### What is the issue?

The image recognition is very poor. It can't describe the picture properly and it also can't extract text. It seems to process a very downscaled image because it complains about the text being too small and it makes assumptions about image elements that seem to be likely but aren't true. It hallucinates a lot and makes things up.

Basically this model is very capable. But with Ollama it is unusable and I tried different tags. llava:7b-v1.6-mistral-q5_K_M and llava:7b from the ollama library. Additionally I downloded a Q5_K_M quant of the model from HF and imported it into my local ollama with a self-created modelfile. The problem was always the same. 

 I used this image, a screenshot from a PDF manual:

![Screenshot 2024-03-22 at 18 37 08](https://github.com/ollama/ollama/assets/295644/b126b65a-4fbb-41d1-9f44-d2682f17dd9c)

Prompt: 
> extract the text underneath the image: /Users/olaf/Desktop/Screenshot\ 2024-03-22\ at\ 18.37.08.png
> Added image '/Users/olaf/Desktop/Screenshot 2024-03-22 at 18.37.08.png'

Ollama response: 
> The image shows a digital advertisement or informational graphic, but it is too small and low resolution to provide a clear transcription of the text. The visible content includes a large purple logo in the upper right corner with the name "SWITCH" below it, and several smaller graphics or logos aligned vertically along the top and bottom edges of the image, which may be related to the product or service advertised on this webpage.
> 
> Please note that due to the low resolution and size of the text in the image, it's difficult to provide an exact transcription of what is written.

It did not even try to extract the text, instead described the image but the description is complete nonsense.

Converting the image to JPG improved the recognition but the model still made things up and the text extraction is just partially correct:

> The text underneath the image reads:
> 
> "Click on any package result to see above. Otherwise the top row will not be visible. A popup will appear and display the packages in the next step.
> 
> The first group of buttons is for the product options. The second set of buttons are for different shipping options. The third set ofbuttons allows you to change your email if needed.
> 
> Please note that these buttons might not be active on this page but they will be when you click through from a live site."

Using a python script as described in https://ollama.com/blog/vision-models does not improve anything.

Log output after script execution with the png file:
```
time=2024-03-22T20:03:14.404+01:00 level=INFO source=dyn_ext_server.go:172 msg="loaded 1 images"
{"function":"launch_slot_with_data","level":"INFO","line":833,"msg":"slot is processing task","slot_id":0,"task_id":637,"tid":"0x172f5f000","timestamp":1711134194}
{"function":"update_slots","level":"INFO","line":1852,"msg":"kv cache rm [p0, end)","p0":0,"slot_id":0,"task_id":637,"tid":"0x172f5f000","timestamp":1711134194}
encode_image_with_clip: image embedding created: 576 tokens

encode_image_with_clip: image encoded in   658.77 ms by CLIP (    1.14 ms per image patch)
{"function":"print_timings","level":"INFO","line":264,"msg":"prompt eval time     =    6374.43 ms /     1 tokens ( 6374.43 ms per token,     0.16 tokens per second)","n_prompt_tokens_processed":1,"n_tokens_second":0.15687684555803996,"slot_id":0,"t_prompt_processing":6374.427,"t_token":6374.427,"task_id":637,"tid":"0x172f5f000","timestamp":1711134212}
{"function":"print_timings","level":"INFO","line":278,"msg":"generation eval time =   11258.49 ms /   321 runs   (   35.07 ms per token,    28.51 tokens per second)","n_decoded":321,"n_tokens_second":28.511811350934032,"slot_id":0,"t_token":35.073183800623056,"t_token_generation":11258.492,"task_id":637,"tid":"0x172f5f000","timestamp":1711134212}
{"function":"print_timings","level":"INFO","line":287,"msg":"          total time =   17632.92 ms","slot_id":0,"t_prompt_processing":6374.427,"t_token_generation":11258.492,"t_total":17632.919,"task_id":637,"tid":"0x172f5f000","timestamp":1711134212}
{"function":"update_slots","level":"INFO","line":1660,"msg":"slot released","n_cache_tokens":322,"n_ctx":2048,"n_past":907,"n_system_tokens":0,"slot_id":0,"task_id":637,"tid":"0x172f5f000","timestamp":1711134212,"truncated":false}
[GIN] 2024/03/22 - 20:03:32 | 200 | 17.686484875s |       127.0.0.1 | POST     "/api/chat"
```

### What did you expect to see?

I compared it with the results from this HF space running the same model in FP16 but most probably with pytorch and transformers: https://huggingface.co/spaces/merve/llava-next

prompt: 
> extract the text underneath the image

response:
> The text underneath the image is as follows:
> 
> "Click on any package results in additional information popping up, as seen above. Otherwise, the top row of text buttons represents view filters for seeing and sorting packs differently. The first group of buttons offers to filter packages by their source, either by showing only those by Bitwig, only those by Artists, or only those from Partners (like sound design companies, etc.). Or simply turn off this filter to see all packages

This is a good answer. It is exactly the text beneath the image in the image.

### Steps to reproduce

1. ollama run llava:7b
2. Use the uploaded picture with the prompt from above

### OS

macOS

### Architecture

arm64

### Ollama version

0.1.29

### GPU

Apple

### GPU info

M1 Pro

### CPU

Apple

**Comment by MorrisLu-Taipei** [comment]
no supprise  , llava is aways poor in  image recognition, is not ollama issue, maybe have to ask llava team.

**Comment by olafgeibig** [comment]
I disagree. The model performs very well in that regard, better than any other model <= 7B. Read my section about my expectations. The model served in a HF spaces is doing near perfect OCR and description of the image.

**Comment by igorschlum** [comment]
Hi @olafgeibig 

There are 3 Llava Models, the biggest is the best. I crop the image you provided to keep only the part with the text in Black and White and asked Llava : can you give me the text written on this image? /Users/igor/Documents/readme
... .png 

The result is:

The image contains text that appears to be instructions for filtering 
packages or content, possibly on a website or software platform. Here is 
the transcribed text:

"Click on any package result is additional information popping up as seen 
above otherwise the top row of text buttons represents view filters for 
seeing and sorting packs differently. The first group of buttons offers to
filter packages by their source such as Only By Blizz, only by Artists, or
simply turn off this page. The second group of buttons offers to filter 
package by their status installed/uninstalled meaning if they are 
available on your computer. Finally, the third group offers sorting 
options one option is to sort packages alphabetically with the Name 1 
button Or choose to sort packages based on their release date with the 
Recommended button."

When I use the same picture and same prompt but when I use the Llava13b model, I got this answer:

 The text in the image appears to be a bit blurry and stretched due to the
perspective, making it difficult to read accurately. However, from what is
visible, it seems to be a description or instructions related to sorting 
or filtering packages on a website or application. If you provide a 
clearer image or more details about the text, I could try to transcribe it
for you.

I used a old llava 1.3 from 3 month ago (a 7b model and it was working), but the recognition was not as good in 1.3 than in 1.6 so the result was : 

 The first group of buttons offers filters for package results, additional
information popping up as seen above any row of text buttons representing 
various views. Filters are available from the source by showing on either 
BittyWig (artists), a like sound design company, or simply by using 
Partner's like sound design. They have also included simple options for 
sorting packages alphabetically with their name button and choosing to 
sort by date when the release is announced, which will be displayed on 
this page.

**Comment by marksalpeter** [comment]
Have the same issue. The Huggingface deployments of 1.6 are able to read text out of most of the document images I've given it. When I give the same images to ollama is it unable to read them. I'm on an intel mac though.

**Comment by igorschlum** [comment]
@marksalpeter Which version of the model do you use? It seems like the llava:34b-v1.6 works better. I'm trying to install this version from Hugging Face: https://huggingface.co/llava-hf/llava-v1.6-34b-hf but have to spend some time doing that.

**Comment by olafgeibig** [comment]
My issue is with the 7B model. I can't run a 34B model.

**Comment by igorschlum** [comment]
@olafgeibig On hugging face, did you test with the 7B model? The 34B model works fine with Ollama, so it could be an issue with the 7B model itself.

**Comment by olafgeibig** [comment]
Yep, the HF space where they demo the new transformers feature to use Llava models is using the 7B model. See yourself: https://huggingface.co/spaces/merve/llava-next/blob/main/app.py

**Comment by olafgeibig** [comment]
bump

**Comment by CoderCowMoo** [comment]
Can confirm,
![image](https://github.com/ollama/ollama/assets/84396762/221d2f82-3415-4523-8c30-035e444236bb)
![image](https://github.com/ollama/ollama/assets/84396762/94bdafd6-08a3-4b39-8509-bf94523a058b)
And the hf spaces says that the llava 1.6 mistral 7b variant is being used.
> Try [LLaVA NeXT](https://huggingface.co/docs/transformers/main/en/model_doc/llava_next) in this demo (more specifically, the [Mistral-7B variant](https://huggingface.co/llava-hf/llava-v1.6-mistral-7b-hf)).

**Comment by igorschlum** [comment]
I loaded lava 7b with version 0.1.32 and I get a good result with this image:

ollama run llava:7b

>>> can you give me the full text of this image ? /Users/igor/Documents/readme.png'

Added image '/Users/igor/Documents/readme.png'
 Sure, here's the full text from the image:

```css
click on any package result is additonal information popping up as seen 
above otherwise the top row of buttons are different filters for seeing 
all products by sorting them by price low to high or showing only items 
that have been installed either by me or someone else. The first group of 
buttons offers filter packages by their source. These are not shown but 
they are there if you need to see them.

Below this is the second group of buttons which offer different types of 
packages. You can use a keyboard shortcut to navigate through these 
buttons. However, the package installer is disabled for now. There may be 
some hidden options that you cannot find. The package installer does not 
work without being installed but are available if you simply turn them on.
This is an important message to ensure that users are aware of all 
available packages in order to sort their preferences.

The first set of buttons allows a user to see the name and description of 
each package as well as any buttons that might be associated with it. The 
second row of buttons is disabled for now but simply turning them on will 
allow you to see all packages that are not installed or simply turn off 
this option if you wish to disable it.

The last set of buttons allows you to choose the third group of options 
which are not fully visible in this image and do not have any associated 
keyboard shortcuts. These options are also not fully visible in this 
image. It is important to note that all packages can be sorted into 
different categories based on their function or the number of packages 
they belong to. The final set of buttons allows you to choose your 
preferences. This is an important message to ensure that users are aware 
of all available packages in order to sort their preferences.
``` 

The result is not exaclty the same as the image, but I think that we can close this Issue if @olafgeibig agrees.

**Comment by hx507** [comment]
Also seeing the same issue where llava from ollama performs significantly worse than the hosted version. 

> I loaded lava 7b with version 0.1.32 and I get a good result with this image:

Trying the exact same thing but the result seems very bad with latest ollama.
```
>>> can you give me the full text of this image ? /home/xxx/Desktop/readme.png 
Added image '/home/xxx/Desktop/readme.png'
 The image contains a humorous meme with a visual pun. Here's the text in a semi-transparent format:

"DON'T PAY ANY ATTENTION TO THE DISTINCT LACK OF LOGICAL SEQUENCES OR THE CLEAR LACK OF COHERENCE BECAUSE THIS IS A MEME" 

```

**Comment by hx507** [comment]
Interestingly, restarting ollama server makes the first image query work. 

For anything other than the first image query uploaded (even with a fresh client session), the model will just output nonsense or complain about it being too blurry.

**Comment by hx507** [comment]
Looking at the release note of 0.1.34 I think this is already addressed:

> - Fixed issues with LLaVa models where they would respond incorrectly after the first request

Seems to fix for me on `llava:34b`.

**Comment by jmorganca** [comment]
Hi folks 0.1.34 should fix these issues. Sorry this happened. Thanks for creating an issue 😊

**Comment by AverageGuy** [comment]
I have the same problem on 1.43.  Using  llava:13b-v1.6

**Comment by AverageGuy** [comment]
I don't know what I did to mess up the format.  I used the <> button which inserted a couple of ticks and I pasted the text into the texts.

**Comment by samyan** [comment]
Guys any update with this for llava 8b?
