### ISSUE TITLE
Changing installation drive 

### ISSUE THREAD

**Issue by atanu2531** [ollama/ollama#3305]
### What are you trying to do?

are there option for changing installation drive ? by default going to C drive ..

### How should we solve this?

just by providing  installation path option in install menu system  

### What is the impact of not solving this?

need to test , probably going to run as usual only might have  some delay

**Comment by dhiltgen** [comment]
You can change the model location after the install.  See https://github.com/ollama/ollama/blob/main/docs/faq.md#where-are-models-stored

We're tracking support for setting this up at install time via #2776

**Comment by UserName-wang** [comment]
> You can change the model location after the install. See https://github.com/ollama/ollama/blob/main/docs/faq.md#where-are-models-stored
> 
> We're tracking support for setting this up at install time via #2776

said:
Setting environment variables on Windows
On windows, Ollama inherits your user and system environment variables.

First Quit Ollama by clicking on it in the task bar

Edit system environment variables from the control panel

Edit or create New variable(s) for your user account for OLLAMA_HOST, OLLAMA_MODELS, etc.

Click OK/Apply to save

Run ollama from a new terminal window
**_but How to set OLLAMA_MODELS on unbutu?_**
