### ISSUE TITLE
More choices with in Windows Installation

### ISSUE THREAD

**Issue by nightboysfm** [ollama/ollama#3312]
### What are you trying to do?

I want to have some controls on how and where the software is installing itself.

For various reasons I think it's not pretty good because it install itself in your user profile which is bad for numerous reasons:
- You'll get insanely huge AD roaming profiles....
- Same FSLogix profiles
- Space on disk C: ?
- Since it's in the user profile, no admin right is required, this not a good thing in a corporate or educational environnement because you have no control on what users are doing. Well solutions exist to block it but not in a simple way.

I mean is there technical reasons to do it like this ? Like 95% of softwares let you choose where you want to install them and where they put their datas.

### How should we solve this?

- Asking admin rights, so simple users can't install it without asking to an admin.
- Let us choose the installation path
- It would be wonderful if we can also chose the models installation path
- Or install models into a subfolder of the installation path
- If not possible at least let us set the model path in a config file instead of environment variable
- Command line arguments would be the amazing, imagine if we can deploy software like this: OllamaSetup.exe --install_path=D:\Ollama --models_path=E:\Ollama_Datas /SILENT

### What is the impact of not solving this?

(How) Are you currently working around the issue?
To be frank I don't want to bother with tricks to get around this right now, I'm going to use alternative softwares. But I think the software would greatly benefit from theses additions.

### Anything else?

I'm aware of https://github.com/ollama/ollama/issues/2621 but I think it's more a workaround than a proper solution.

**Comment by FilkerZero** [comment]
I would also suggest adding an option to not start ollama server at boot and to have the model directory in another location from the application itself.

**Comment by dhiltgen** [comment]
We're tracking custom installation for windows in #2776
