### ISSUE TITLE
Model search in website is filtered only using name of the model

### ISSUE THREAD

**Issue by Philotheephilix** [ollama/ollama#3313]
### What is the issue?

Searching for a model on https://ollama.com/ filters request based only on the **name** of the model
it practically makes the search box useless as noone can find the model they want as the keywords will be present in the **description** of the model

### What did you expect to see?

Implementing **name and description** based sorting in search box suggestions

### OS

Windows

### Architecture

x86

### Platform

WSL2

### Ollama version

website frontend

### GPU

Other

### CPU

Intel

**Comment by BruceMacD** [comment]
Thanks for the request @Philotheephilix, I've just deployed some search improvements on ollama.com that will match keywords present in the model descriptions. The experience should be much better now.

**Comment by Philotheephilix** [comment]
Thanks for your time and reply
