### ISSUE TITLE
Feat req: Add "Last updated" sorting to the hub

### ISSUE THREAD

**Issue by knoopx** [ollama/ollama#3323]
### What are you trying to do?

There's no way to discover recent updates for existing models.

### How should we solve this?

Add "Last updated" sort choice

### What is the impact of not solving this?

No way to find out recently updated models

**Comment by pdevine** [comment]
@knoopx Sorry for the slow reply. This has been on ollama.com for a little while but we lost track of the issue.

<img width="972" alt="Screenshot 2024-07-18 at 12 03 34" src="https://github.com/user-attachments/assets/eff0cd00-1508-44c5-8c60-ed71a79e9c9e">
