### ISSUE TITLE
Binary for Mac Intel doesn't work.

### ISSUE THREAD

**Issue by shyamalschandra** [ollama/ollama#3325]
### What is the issue?

Binary for Mac Intel doesn't work and is corrupted before installation.

### What did you expect to see?

No problems with starting ollama-gui.

### Steps to reproduce

Download the Mac Intel version of ollama-gui and double-click to install it to Applications.

### Are there any recent changes that introduced the issue?

No idea.

### OS

macOS

### Architecture

x86

### Ollama version

0.1.29

### GPU

AMD

### GPU info

Graphics/Displays:

    Radeon Pro 575X:

      Chipset Model: Radeon Pro 575X
      Type: GPU
      Bus: PCIe
      PCIe Lane Width: x16
      VRAM (Total): 4 GB
      Vendor: AMD (0x1002)
      Device ID: 0x67df
      Revision ID: 0x00c4
      ROM Revision: 113-D0008A-042
      VBIOS Version: 113-D0008A14GP-003
      EFI Driver Version: 01.B1.042
      Metal Support: Metal 2
      Displays:
        iMac:
          Display Type: Built-In Retina LCD
          Resolution: Retina 5K (5120 x 2880)
          Framebuffer Depth: 30-Bit Color (ARGB2101010)
          Main Display: Yes
          Mirror: Off
          Online: Yes
          Automatically Adjust Brightness: Yes
          Connection Type: Internal

### CPU

AMD

### Other software

MacOS Sonoma 14.4 (23E214)

**Comment by dhiltgen** [comment]
I wasn't able to reproduce.

```
% system_profiler SPSoftwareDataType SPHardwareDataType
Software:

    System Software Overview:

      System Version: macOS 10.15.7 (19H2026)
      Kernel Version: Darwin 19.6.0
      Boot Volume: ssd
      Boot Mode: Normal
      Computer Name: XXX
      User Name: XXX
      Secure Virtual Memory: Enabled
      System Integrity Protection: Enabled
      Time since boot: 74 days 19:37

Hardware:

    Hardware Overview:

      Model Name: Mac mini
      Model Identifier: Macmini6,2
      Processor Name: Quad-Core Intel Core i7
      Processor Speed: 2.6 GHz
      Number of Processors: 1
      Total Number of Cores: 4
      L2 Cache (per Core): 256 KB
      L3 Cache: 6 MB
      Hyper-Threading Technology: Enabled
      Memory: 16 GB
      Boot ROM Version: 429.0.0.0.0
      SMC Version (system): 2.8f0
      Serial Number (system): XXX
      Hardware UUID: XXX
```

```
% wget https://github.com/ollama/ollama/releases/download/v0.1.29/ollama-darwin && chmod a+x ./ollama-darwin
...
%  OLLAMA_DEBUG=1 ./ollama-darwin serve
...
```
I'm able to run orca-mini and see valid output.

I also tried downloading the zip file, and installing on this system and everything worked correctly.


Is it possible your download was corrupted?  Can you try removing the download and trying again?

**Comment by dhiltgen** [comment]
If you're still having trouble, please let us know.
