### ISSUE TITLE
Module name is out of date and prevents import from other projects

### ISSUE THREAD

**Issue by smxlong** [ollama/ollama#3327]
### What is the issue?

Attempting to import parts of the ollama tree (such as the `api` directory) into an external project fails, because the module name declared in `go.mod` is still `github.com/jmorganca/ollama`. This apparently doesn't impact building the project itself, but causes errors when attempting to import packages into other projects.

### What did you expect to see?

This should have worked:

```
go get github.com/ollama/ollama/api
```

Instead, I get this:

```
$ go get github.com/ollama/ollama/api
go: github.com/ollama/ollama@v0.1.29 (matching github.com/ollama/ollama/api@upgrade) requires github.com/ollama/ollama@v0.1.29: parsing go.mod:
        module declares its path as: github.com/jmorganca/ollama
                but was required as: github.com/ollama/ollama
```

### Steps to reproduce

Run `go get github.com/ollama/ollama/api` from another project.

### OS

Linux

### Architecture

amd64

### Platform

WSL2

### Ollama version

main branch

**Comment by pdevine** [comment]
@smxlong sorry about this. We switched over the repo to `ollama/ollama` from `jmorganca/ollama` and didn't update all of the code. I have a fix which I'm testing out and I'll send a PR soon. This will have to wait until `0.1.30` goes out anyway though just so it doesn't mess with the release.
