### ISSUE TITLE
/set format json does not appear to work over the API.

### ISSUE THREAD

**Issue by phalexo** [ollama/ollama#3328]
### What is the issue?

I would like to set JSON mode, via the API or in the model file. I tried to insert the command right after the system prompt in the template,

didn't work.

Then I made it part of the system prompt.

didn't work.

### What did you expect to see?

When "/set format json" appears anywhere, either in the system prompt, or as part of user query, I expect the mode to be changed to JSON, and the output be in JSON format.

### Steps to reproduce

It is obvious. I cannot put it anywhere in the model file to make it change the mode.

### Are there any recent changes that introduced the issue?

no.

### OS

Linux

### Architecture

amd64

### Platform

Docker

**Comment by mxyng** [comment]
`/set` commands in the CLI are not sent to ollama but instead mutate the active session. Therefore `/set format json` as a message in the API will not work. Instead, the API takes a `format` field you can set to `json`, e.g.

```
curl localhost:11434/api/generate -d '{"model":"mistral","prompt":"say hello in a format of {\"message\": \"response\"}","format":"json","stream":false}'
```
