### ISSUE TITLE
Import models installed in Linux to Windows

### ISSUE THREAD

**Issue by tealv** [ollama/ollama#3329]
### What are you trying to do?

Copy models from a Linux ollama installation to a Windows installation.

### How should we solve this?

I suggest an import feature for Windows that copies the models from another location and makes changes in the process.

### What is the impact of not solving this?

Re-downloading the models in the Windows version.

### Anything else?

I copied models from a Linux install to a Windows install. To get them to work in Windows, it was necessary to change the ':' in the blob file names to '-'.  Linux blob file names start with 'sha256:', and Windows blob file names start with 'sha256-'. It was also necessary to exchange the same strings inside the manifest files for each model. 

This only works if done while ollama is running. When ollama (windows) starts, it erases the copied and changed files in the blob directory. Two relevant lines from server.log:
  time=2024-03-24T14:39:01.248-07:00 level=INFO source=images.go:806 msg="total blobs: 16"
  time=2024-03-24T14:39:02.380-07:00 level=INFO source=images.go:813 msg="total unused blobs removed: 16"

In the Windows version, the blob files are located in: '(user)\\.ollama\models\blobs\'. The manifest files (named: 'latest') are located in: '(user)\\.ollama\models\manifests\registry.ollama.ai\library\(model)\'.

**Comment by tealv** [comment]
I intended this to be a feature request, not 'needs-triage'

**Comment by tealv** [comment]
When solved as described while Ollama (Windows) is running, the three models I tested worked (tinyllama, llama2 and codebooga). When I restarted Ollama, the blob directory was erased. Some relevant lines from server.log:
time=2024-03-24T14:39:01.248-07:00 level=INFO source=images.go:806 msg="total blobs: 16"
time=2024-03-24T14:39:02.380-07:00 level=INFO source=images.go:813 msg="total unused blobs removed: 16"

**Comment by igorschlum** [comment]
hi @tealv Even if not explicitly labeled, the concept of triaging issues (categorizing and prioritizing them) is common across many GitHub projects. It could means that it must be discussed by Ollama team.

**Comment by Kreijstal** [comment]
Why does Windows have different filename in the first place?

**Comment by igorschlum** [comment]
In Windows, it's not recommended to use colons (:) in filenames due to potential compatibility issues. This could be why Ollama teams, choosed to change their naming conventions.

**Comment by pdevine** [comment]
We started with Linux/MacOS and I had shoved a colon into the name not realizing that NTFS didn't support colons in file names. I also didn't anticipate so many people would use external NTFS mounted drives to store models either.

The good news is @bmizerany has already checked in a fix which should be in 0.1.30 w/ #3146 . I'll go ahead and close the issue, but thanks for filing it!
