### ISSUE TITLE
Certificate expired

### ISSUE THREAD

**Issue by cxzx150133** [ollama/ollama#3334]
### What is the issue?

$ docker exec -it ollama ollama pull qwen:7b
pulling manifest
Error: pull model manifest: Get "https://registry.ollama.ai/v2/library/qwen/manifests/7b": tls: failed to verify certificate: x509: certificate has expired or is not yet valid: current time 2024-03-25T07:29:23Z is after 2024-03-25T07:17:47Z

### What did you expect to see?

no error

**Comment by SavageBoth** [comment]
😂expired 20 minute ago，so i come here to find solutions

**Comment by k-bala-vignesh** [comment]
Same for me.

**Comment by willfihgt** [comment]
Almost, my question is as follows that ollama pull qwen:7b
pulling manifest
Error: pull model manifest: Get "https://registry.ollama.ai/v2/library/qwen/manifests/7b": tls: failed to verify certificate: x509: certificate has expired or is not yet valid:

**Comment by Officialstrike** [comment]
Could you consider closing this issue in favour of #3336? Consolidating the problem into one issue would make it clearer and more organized.  Thanks in advance.
