### ISSUE TITLE
Error: pull model manifest

### ISSUE THREAD

**Issue by k-bala-vignesh** [ollama/ollama#3337]
### What is the issue?

When I try `ollama pull mistral`, I get the Error: pull model manifest.

pulling manifest 
Error: pull model manifest: Get "https://registry.ollama.ai/v2/library/mistral/manifests/latest": tls: failed to verify certificate: x509: certificate has expired or is not yet valid: current time 2024-03-25T13:08:04+05:30 is after 2024-03-25T07:17:47Z

### What did you expect to see?

I expect that this command would be able to download the model locally.

### Steps to reproduce

Download Ollama, and run  `ollama pull mistral`

### OS

Linux

### Architecture

x86

### GPU

Nvidia

### GPU info

TU104 [GeForce RTX 2060]

### CPU

AMD

**Comment by cc-dev-kentool** [comment]
Can not pull any model now..
