### ISSUE TITLE
Support eGPU on Intel Macs

### ISSUE THREAD

**Issue by noomorph** [ollama/ollama#3342]
### What are you trying to do?

I'm trying to run ollama with AMD Radeon 5700XT (eGPU) on Mac Mini 2018 (Intel).
![image](https://github.com/ollama/ollama/assets/1962469/9601d2b0-9e87-474e-8a0d-12c5e8ef6fe5)

I see that only my CPU is busy, not the GPU.
![image](https://github.com/ollama/ollama/assets/1962469/d05c1755-7dce-47bd-86ef-b7429e78ad28)

I suspect that this is the culprit:

![image](https://github.com/ollama/ollama/assets/1962469/12195515-ecea-44d6-b97a-ea7371a83ea3)

### How should we solve this?

Try to detect an eGPU nevertheless.

### What is the impact of not solving this?

Low performance of models.

**Comment by dhiltgen** [comment]
We're tracking this in #1016 

Currently we're CPU only on the Intel macs.
