### ISSUE TITLE
Ollama Logo

### ISSUE THREAD

**Issue by corani** [ollama/ollama#3359]
I was playing with the `llava` model to create image-generation prompts based on an existing image. Starting with the Ollama logo I made a few iterations between llava and dall-e and ended up with the following result that I didn't want to keep to myself 😄 

![_cc4036ed-af48-4625-a85c-28b9e0b72249](https://github.com/ollama/ollama/assets/480775/2a447015-f2d6-46c2-9aac-0148b7b8746e)

Use it however you see fit!

**Comment by hernandito** [comment]
Very cute!... Below is my version... which is more icon friendly:

![llama icon3b](https://github.com/ollama/ollama/assets/787317/09577ed9-e0a8-4dfc-8315-b844b397d2e6)

and/or

![favicon](https://github.com/ollama/ollama/assets/787317/8f56d884-8933-4728-b6bb-d2d152d4c494)

**Comment by jmorganca** [comment]
Thank you the art is heartwarming! I love the glasses. Will close this issue!
