### ISSUE TITLE
model names should be case insensitive

### ISSUE THREAD

**Issue by jmorganca** [ollama/ollama#336]
```
ollama pull wizard-math:13b-q3_k_m
```

should pull the same image as
```
ollama pull wizard-math:13b-q3_K_M
```

**Comment by neuralcoral** [comment]
To clarify, do we want this to work towards push's as well? I for see a possible issue where one user `ollama push model:abc` and another user `ollama push model:Abc`. If we are then `ollama pull model:aBc` which model should be pull down?

**Comment by jmorganca** [comment]
@neuralcoral yes that's right!

**Comment by neuralcoral** [comment]
Great! Do we plan to then rename existing models to be type insensitive in the future? Any current models will need to be renamed to their case insensitive versions or might have collisions with an upload.

**Comment by verokarhu** [comment]
Wouldn't it be better to follow the [OCI distribution spec](https://github.com/opencontainers/distribution-spec/blob/main/spec.md#pulling-manifests) and keep tags case sensitive? If Ollama behaves differently from e.g. docker push then it's a bit surprising for the user.

> Throughout this document, <reference> as a tag MUST be at most 128 characters in length and MUST match the following regular expression:
>
> [a-zA-Z0-9_][a-zA-Z0-9._-]{0,127}

**Comment by aashish2057** [comment]
should this issue be closed now? Seems like the intended behavior based on the spec is for the model name to be case sensitive?

**Comment by PriyaranjanMarathe** [comment]
Does ollama support loading a Pytorch model? I have trained a model and it's output is a .pt file. How do I use it with ollama? I tried doing the following and it doesn't seem to work.

[root@ trained_models]# ollama run model.pt
pulling manifest

Error: pull model manifest: file does not exist

**Comment by mtel24** [comment]
@jmorganca Should this issue be closed ?

**Comment by SuperRicky14** [comment]
I think it should just pop up with a "Did you mean: <model 1>, <model 2>, <...>" when you mess up the caseing, that way you don't accidentally pull/push to the wrong repository but it tells you what models you might've meant.

**Comment by jmorganca** [comment]
This should be possible now!

**Comment by PriyaranjanMarathe** [comment]
Thanks Jeff! Appreciate it.

Thanks,
Priyaranjan (Ranjan) Marathe.
+1 980 335 6511
***@***.***  ***@***.***>
