### ISSUE TITLE
add starling-lm beta

### ISSUE THREAD

**Issue by Lev1ty** [ollama/ollama#3364]
### What model would you like?

https://huggingface.co/Nexusflow/Starling-LM-7B-beta

Strong performance on LMSYS leaderboard
![image](https://github.com/ollama/ollama/assets/15148828/9cbb91b3-a898-4c68-835f-8625bbd710db)

**Comment by JJassonn69** [comment]
Would love to see this implemented. This is the best small llm so far we have seen.

**Comment by liangDarwin2** [comment]
it seems that this model beat gpt-3.5, is it real for our practical use? Can't wait to test it.

**Comment by rcking** [comment]
I would agree that, based on these peformance metrics, this model should be prioritized over others in the queue.

**Comment by Lev1ty** [comment]
That would be the one, at the time of opening this issue that tag had not been released yet. Closing this issue as it now available
