### ISSUE TITLE
Add Update Documentation to Main Readme

### ISSUE THREAD

**Issue by oldmanjk** [ollama/ollama#3366]
### What are you trying to do?

Update Ollama

### How should we solve this?

Add update instructions to the main readme

### What is the impact of not solving this?

Users wasting time trying to figure out how to update and becoming frustrated

### Anything else?

Instructions are in the FAQ, but I think it would save a lot of people trouble if they were also on the main readme. Having some kind of auto updater would be even better (Linux)

**Comment by jmorganca** [comment]
Hi there, thanks for the issue, we'll work on making this clearer!
