### ISSUE TITLE
Mobaxterm teminal not working

### ISSUE THREAD

**Issue by jackel66** [ollama/ollama#3373]
When using the windows preview and opening a Mobaxterm terminal i execute the ollama.exe run llama2 but nothing happens.. its like its hung for some reason. I attempted to install the LLM using a regular CMD prompt in windows and it downloads it fine and executes but will not work in moba. 

It says use your favorite terminal but maybe this is a limitation?

**Comment by jmorganca** [comment]
Hi there, would it be possible to try this again? a recent update to `ollama run` on windows should have fixed this. What kind of terminal emulator is Mobaxterm running?
