### ISSUE TITLE
Models disappear, service becomes unusable after following instructions for making ollama available on network.

### ISSUE THREAD

**Issue by applebiter** [ollama/ollama#3374]
### What is the issue?

I installed ollama easily, downloaded around 50gb worth of models, testing software locally, fine. Realized I needed to be able to access ollama on other network machines and get those results asynchronously, rather than using the supplied Python library on same host. I changed the host to 0.0.0.0 and it seemed to be working great from the machine where I was testing. Shut everything down, wake up the next morning, reboot, discover ollama doesn't want to start and all of the models are gone.

### What did you expect to see?

I expected the models to still be there. I don't even understand why this is a thing in the first place. I thought I was in control over the software but apparently I am not and do not understand its operation well enough.

### Steps to reproduce

Get it up and running in vanilla, default settings. Download models. Change the network address using systemctl edit as suggested. Reboot host machine and enjoy chaos. I also expect to see a warning that this can happen, frankly.

### Are there any recent changes that introduced the issue?

I changed the network host to 0.0.0.0.

### OS

Linux

### Architecture

amd64

### Ollama version

0.1.29

### GPU

AMD

**Comment by jmorganca** [comment]
Hi there, your models aren't gone! If running on Linux, Ollama runs as its own user `ollama`, and to expose it on the network the easiest way is to set the `OLLAMA_HOST` environment variable using systemd: https://github.com/ollama/ollama/blob/main/docs/faq.md#setting-environment-variables-on-linux

If you run `OLLAMA_HOST=0.0.0.0 ollama serve`, keep in mind it will run as you

Hope this helps, let me know if not!
