### ISSUE TITLE
CORS on API doesn't work with Safari 17.3.1

### ISSUE THREAD

**Issue by amio** [ollama/ollama#3384]
### What is the issue?

Requesting ollama api from localhost:1420 to 127.0.0.1:11434 works in Chrome but not Safari, it got an CORS error: ""

While fething the api from the console works, which is strange:

<img width="1048" alt="image" src="https://github.com/ollama/ollama/assets/215282/bf6ffbd6-9158-411b-af22-e9b1c1f3d507">

After examining the headers for both request:

fetch from source:
<img width="711" alt="image" src="https://github.com/ollama/ollama/assets/215282/a26ec69e-04af-4995-a749-fd1ac148b1e6">

fetch from console:
<img width="774" alt="image" src="https://github.com/ollama/ollama/assets/215282/54f2132e-462d-47c4-baab-5d24740f25e8">

I suspect it might be related to the missing `host` header in the source fetch.

### What did you expect to see?

No cors error.

### OS

macOS

### Architecture

arm64

**Comment by jmorganca** [comment]
Hi there! Thanks for creating an issue. To enable CORS access for now you'll need to set an environment variable: https://github.com/ollama/ollama/blob/756c2575535641f1b96d94b4214941b90f4c30c7/docs/faq.md#how-can-i-allow-additional-web-origins-to-access-ollama

We're working on making this easier in the macOS app – stay tuned!

**Comment by amio** [comment]
Hi @jmorganca , the document says "Ollama allows cross-origin requests from 127.0.0.1 and 0.0.0.0 by default", and in the code https://github.com/ollama/ollama/blob/main/server/routes.go#L957-L980
```go
func allowedHost(host string) bool {
	if host == "" || host == "localhost" {
		return true
	}

	if hostname, err := os.Hostname(); err == nil && host == hostname {
		return true
	}

	var tlds = []string{
		"localhost",
		"local",
		"internal",
	}

	// check if the host is a local TLD
	for _, tld := range tlds {
		if strings.HasSuffix(host, "."+tld) {
			return true
		}
	}

	return false
}
```

I think we were meant to allow core requests from **localhost** by default right?
