### ISSUE TITLE
exec format error when Running Ollama Container on AMD64 Architecture

### ISSUE THREAD

**Issue by joshyorko** [ollama/ollama#3396]
### What is the issue?

When attempting to run the Ollama container, I continuously encounter an exec format error. The container fails to start properly and keeps trying to restart, logging the same error multiple times.
What did you expect to happen? I expected the Ollama container to start successfully without any architecture compatibility issues.

### What did you expect to see?

Expected Behavior: A successful initiation of the Ollama container, ready to receive and execute commands.

### Steps to Reproduce
1. **Environment Setup:** Ensure Docker is installed on a system running Ubuntu 22.04.3 LTS with AMD64 architecture.
2. **Attempt with Latest Image:**
   - Run the Ollama Docker container using the `latest` tag: `docker run ollama/ollama:latest`.
   - Observe the `exec format error` in the Docker logs, indicating the container is failing to start properly and continuously restarting.
3. **Successful Attempt with Previous Release:**
   - Switch to using the Ollama Docker container with the `0.1.30` tag: `docker run ollama/ollama:0.1.30`.
   - Notice that the container starts successfully without any architecture compatibility issues.

### Are there any recent changes that introduced the issue?

The issue arose after an automated update process on 3/28, handled by Watchtower, which pulled the latest release of the Ollama container. Prior to this update, the container was running smoothly. However, the latest image seems to be missing a build for the linux/amd64 architecture, which is necessary for compatibility with my system. As a result, running the latest image leads to an exec format error and causes the container to restart continuously. This indicates that the latest release may have inadvertently omitted the linux/amd64 build, which is critical for running on an AMD64 architecture system like mine.

### OS

Linux

### Architecture

arm64

### Platform

Docker

### Ollama version

0.1.30

### GPU info

na

### Other software

na

**Comment by jmorganca** [comment]
Hi there, this should be fixed now. There was a slight delay in publishing the arm64 image for the `latest` tag – will make sure we avoid that next time. Thanks!
