### ISSUE TITLE
"ollama run llama2" Fails with Connection Error and Runtime Panic on Windows 11

### ISSUE THREAD

**Issue by cvecve147** [ollama/ollama#3402]
### What is the issue?

When attempting to run the command **ollama run llama2**, I encountered a connection error followed by a runtime panic. Initially, the process attempts to pull a manifest but fails with a connection error indicating that the connection to **127.0.0.1:11434** was refused. Subsequently, inspecting the logs revealed a **panic: runtime error: index out of range** error, specifically occurring during a blob download operation as part of the PullModel process. This issue prevents any further operation of the command and effectively halts the execution.

### What did you expect to see?

Upon executing the ollama run llama2 command, I expected the process to successfully connect, download necessary blobs, and proceed without any runtime errors. Ideally, the command should result in the model being prepared and ready for use, without encountering connection issues or runtime panics.

### Steps to reproduce

1. Ensure that Ollama version 0.1.30 is installed on a Windows 11 23H2 environment.
2. Open a terminal window.
3. Execute the command: **ollama run llama2**.
4. Observe the error messages related to connection failure and runtime panic in the output or logs.

### OS

Windows

### Ollama version

0.1.30

### GPU

Nvidia

### server.log
```
[GIN] 2024/03/29 - 10:38:02 | 404 |       565.8µs |       127.0.0.1 | POST     "/api/show"
panic: runtime error: index out of range [0] with length 0

goroutine 22 [running]:
github.com/ollama/ollama/server.(*blobDownload).Prepare(0xc0001ec150, {0x418cf80, 0xc0000f06e0}, 0xc0004fe360, 0xc00024a240)
	github.com/ollama/ollama/server/download.go:136 +0x4f6
github.com/ollama/ollama/server.downloadBlob({0x418cf80, 0xc0000f06e0}, {{{0x1869044, 0x5}, {0x187c878, 0x12}, {0x18717df, 0x7}, {0xc0001524c4, 0x6}, ...}, ...})
	github.com/ollama/ollama/server/download.go:369 +0x4f6
github.com/ollama/ollama/server.PullModel({0x418cf80, 0xc0000f06e0}, {0xc0001524c4?, 0x0?}, 0xc00024a240, 0xc000500240)
	github.com/ollama/ollama/server/images.go:1031 +0x508
github.com/ollama/ollama/server.PullModelHandler.func1()
	github.com/ollama/ollama/server/routes.go:523 +0x14b
created by github.com/ollama/ollama/server.PullModelHandler in goroutine 20
	github.com/ollama/ollama/server/routes.go:510 +0x14b

```

**Comment by fallenreaper** [comment]
I noticed this being a thing recently on Mac Sonoma

**Comment by entegral** [comment]
im also seeing this while trying to pull down the `deepseek-r1:8b ` model from ollama. Im using open-webui and the latest `https://hub.docker.com/r/ollama/ollama/` container.

```
time=2025-02-03T22:30:23.184Z level=INFO source=download.go:175 msg="downloading xxx in 16 307 MB part(s)"
time=2025-02-03T22:31:08.564Z level=INFO source=download.go:175 msg="downloading xxx in 1 387 B part(s)"
time=2025-02-03T22:31:09.922Z level=INFO source=download.go:175 msg="downloading xxx in 1 1.1 KB part(s)"
time=2025-02-03T22:31:11.277Z level=INFO source=download.go:175 msg="downloading xxx in 1 148 B part(s)"

panic: runtime error: index out of range [0] with length 0

goroutine 12 [running]:
github.com/ollama/ollama/server.(*blobDownload).Prepare(0xc0005d9b90, {0x558846a6f580, 0xc00055e190}, 0xc000483560, 0xc00054e280)
        github.com/ollama/ollama/server/download.go:175 +0x539
github.com/ollama/ollama/server.downloadBlob({0x558846a6f580, 0xc00055e190}, {{{0x558846633269, 0x5}, {0x558846647641, 0x12}, {0x55884663bd67, 0x7}, {0xc00015a250, 0xb}, ...}, ...})
        github.com/ollama/ollama/server/download.go:489 +0x4da
github.com/ollama/ollama/server.PullModel({0x558846a6f580, 0xc00055e190}, {0xc00015a250, 0xe}, 0xc00054e280, 0xc000392b40)
        github.com/ollama/ollama/server/images.go:564 +0x771
github.com/ollama/ollama/server.(*Server).PullHandler.func1()
        github.com/ollama/ollama/server/routes.go:594 +0x197
created by github.com/ollama/ollama/server.(*Server).PullHandler in goroutine 82
        github.com/ollama/ollama/server/routes.go:581 +0x691
```

I was able to successfully pull the `deepseek-r1:1.5b` model and the `qwen2.5-coder:14b` models, so might be an issue with the specific model you are trying.
