### ISSUE TITLE
API server stops responging - CUDA error: out of memory

### ISSUE THREAD

**Issue by Zig1375** [ollama/ollama#3405]
### What is the issue?

On a win 11 machine, when I try to make a request to API (Command R model) it stops responding.
But in the command line it works perfectly.
In the log file I can see errors: 
```
CUDA error: out of memory
  current device: 0, in function alloc at C:\a\ollama\ollama\llm\llama.cpp\ggml-cuda.cu:532
  cuMemSetAccess(pool_addr + pool_size, reserve_size, &access, 1)
GGML_ASSERT: C:\a\ollama\ollama\llm\llama.cpp\ggml-cuda.cu:193: !"CUDA error"
```

But as I said above it works perfectly in the command line! I can discuss with the chat for a long time. But api stops working in the first request. Restarting machine and ollama do not help.

### What did you expect to see?

Api server should works the same as the command line

### Steps to reproduce

Install Command R on a win 11 machine (nvidia 4070 12 GB, 32 GB ram). Send an api request (with about 1000 words).

### OS

Windows

### Architecture

amd64

### Ollama version

0.1.30

### GPU

Nvidia

### CPU

AMD

**Comment by Zig1375** [comment]
One more thing: after this issue occurred, I have to restart Ollama because the API does not work at all. So, even just opening `http://127.0.0.1:11434/` does not show anything (but I expect to see `Ollama is running`).

**Comment by Zig1375** [comment]
I encounter the same issue from time to time when num_ctx is set to 2048.
If num_ctx is set to 4096 or higher, the error occurs consistently (using a Nvidia 4070 with 12GB of memory (RAM 64GB)).

**Comment by bilalshafim** [comment]
I have been encountering the same issue. At first, using the API would start sending a stream but it would stop with error: unexpected server status: 1. Now, it does not send back a response at all. 

I am trying to use Ollama with Flowise to connect to another service. The reason why I chose Ollama was because it has native support in Flowise, just need to add the server address. Is there any alternate for Ollama because I want to get the service up as soon as possible.

**Comment by dhiltgen** [comment]
Please upgrade to 0.1.45 and let us know how it goes.  Multiple fixes have gone in that should help the situation.

**Comment by dhiltgen** [comment]
If you're still having out of memory problems on the latest release, please share an updated server log and I'll reopen the issue.
