### ISSUE TITLE
API to terminate the running job before the completion

### ISSUE THREAD

**Issue by ansis-m** [ollama/ollama#3409]
### What are you trying to do?

I am using Ollama via REST api interface. Sometimes when model streams a long response (can be quite slow on my computer) I would like to terminate the process before the completion. I checked the API documentation and I did not find an option for this. Even if I unsubscribe from the stream (Java Spring AI interface) I see that the cpu/gpu usage remains high for extended period (untill the whole response has been generated).

### How should we solve this?

Implement REST API endpoint that allows to terminate the running job before the completion.

### What is the impact of not solving this?

Better user experience. Many users do not own super fast computers and response generation takes some time (0.5-2 minutes on my computer). Sometimes when you get half way through the answer you know that you are not getting what you want and you would like to reformulate a prompt without waiting for the completion. It would greatly improve the user experience if the running job could be stoped before the completion.

### Anything else?

Thank you for the awesome project!

**Comment by pdevine** [comment]
If you interrupt the stream it should stop generating immediately. The model will stay loaded in the memory of the GPU for 5 minutes, but you can control that with the `keep_alive` parameter or the `OLLAMA_KEEP_ALIVE` env variable.

 I just re-tested this with curl and it is working as expected (at least on Mac). What platform are you using?

**Comment by jmorganca** [comment]
Hi @ansis-m as mentioned by @pdevine it's possible to have the model unload immediately after generation (including cancelling it)
