### ISSUE TITLE
Ollama does not use my ram memory

### ISSUE THREAD

**Issue by faugustdev** [ollama/ollama#3415]
##   Ollama Resource Utilization: Potential Optimization Opportunity

I'm deploying a model within Ollama and noticed that while I've allocated 24GB of RAM to the Docker container, it's currently only utilizing 117MB. 

This efficient resource usage is commendable, but it might also indicate room for optimization. To ensure optimal performance, it would be beneficial if the model could leverage at least the minimum required resources.

### Model Response Speed and Resource Usage

While I allocated 24GB of RAM to the Docker container running the model, it's currently utilizing only 117MB. Given this limited resource usage, achieving an acceptable response speed for the model is impossible.

### Steps to reproduce

run this command to start my docker container run -d -v rocama:/root/.ollama -p 11434:11434 --name LLMsDazlabs --memory=24g --memory-reservation=24g rocama/ollama

### OS

Linux

### Architecture

arm64

### Platform

Docker

### Ollama version

ollama version is 0.1.30

### GPU info

I am not using GPU, I am running Ollama with only CPU
Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz

### CPU

Intel

**Comment by easp** [comment]
How/where are you measuring resource utilization? Ollama memory maps model weights. Linux utilities, like free, account for this in buffer/cache which is considered "available."

**Comment by faugustdev** [comment]
since I am using docker, only need to check with 'docker stats' command

**Comment by jmorganca** [comment]
Hi there, which model are you running? I would definitely expect more memory utilization than this, however as @easp mentioned it's possible that the memory isn't reflected as the file is memory mapped

**Comment by tahitimoon** [comment]
How do you solve this problem?
