### ISSUE TITLE
prompt_eval_count in api is broken

### ISSUE THREAD

**Issue by drazdra** [ollama/ollama#3427]
### What is the issue?

prompt_eval_count parameter is absent on some calls, on other calls it returns wrong information.

1. i tried /api/chat with "stablelm2", no system prompt, prompt="hi". 

in result there is no field "prompt_eval_count" most of the time. sometimes it's there, randomly, but rarely.

2. when you have small num_ctx and the supplied prompt (content of all messages in /api/chat) exceeds the num_ctx size, the prompt_eval_count may either be absent or provide wrong information. 

i believe it returns the amount of tokens that could fit the context window, instead of the whole context prompt that was sent. 

thanks :).

### What did you expect to see?

expected behavior: 
1. there should always be prompt_eval_count.
2. it should report the count of submitted tokens, not the processed ones.
3. optionally there maybe one more parameter returned, showing the amount of processed tokens.

### Steps to reproduce

use /api/chat to send array of messages, limit num_ctx, send longer content than fits into the context window defined with num_ctx, check the values returned in final json reply with done==true.

### OS

Linux

### Architecture

amd64

### Ollama version

0.1.30

### GPU

Other

### GPU info

cpu only

### CPU

AMD

**Comment by tarbard** [comment]
I've had this problem.  I think it happens when the prompt is cached.  I've also seen it on eval_count though that was much rarer so it might be unrelated.

**Comment by jmorganca** [comment]
Hi there, yes it will be 0 if the prompt is cached. Will most likely revisit this. However it's definitely a bug that that the field disappears altogether - thanks for flagging!

**Comment by drazdra** [comment]
> Hi there, yes it will be 0 if the prompt is cached. Will most likely revisit this. However it's definitely a bug that that the field disappears altogether - thanks for flagging!

the issue is that i wanted to use it to mark the parts of the prompt that do not fit into the context window. but it's impossible with this behavior. it would be good if the cache would remember the amount of tokens cached and returned the proper values :). thanks for reply.

**Comment by gregnwosu** [comment]
how can i disable prompt caching

**Comment by jmorganca** [comment]
Merging with #2068
