### ISSUE TITLE
CUBLAS_STATUS_ALLOC_FAILED

### ISSUE THREAD

**Issue by nanshaws** [ollama/ollama#3430]
### What is the issue?

time=2024-04-01T08:23:20.161+08:00 level=INFO source=gpu.go:115 msg="Detecting GPU type"
time=2024-04-01T08:23:20.161+08:00 level=INFO source=gpu.go:265 msg="Searching for GPU management library cudart64_*.dll"
time=2024-04-01T08:23:20.170+08:00 level=INFO source=gpu.go:311 msg="Discovered GPU libraries: [C:\\Users\\Administrator\\AppData\\Local\\Programs\\Ollama\\cudart64_110.dll c:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v11.2\\bin\\cudart64_110.dll C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v11.2\\bin\\cudart64_110.dll]"
time=2024-04-01T08:23:20.234+08:00 level=INFO source=gpu.go:120 msg="Nvidia GPU detected via cudart"
time=2024-04-01T08:23:20.235+08:00 level=INFO source=cpu_common.go:11 msg="CPU has AVX2"
time=2024-04-01T08:23:20.382+08:00 level=INFO source=gpu.go:188 msg="[cudart] CUDART CUDA Compute Capability detected: 8.6"
time=2024-04-01T08:23:20.382+08:00 level=INFO source=cpu_common.go:11 msg="CPU has AVX2"
time=2024-04-01T08:23:20.382+08:00 level=INFO source=gpu.go:188 msg="[cudart] CUDART CUDA Compute Capability detected: 8.6"
time=2024-04-01T08:23:20.383+08:00 level=INFO source=cpu_common.go:11 msg="CPU has AVX2"
time=2024-04-01T08:23:20.383+08:00 level=INFO source=assets.go:108 msg="Updating PATH to C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\ollama1513712000\\runners\\cuda_v11.3;C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v11.2\\bin;C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v11.2\\libnvvp;C:\\Program Files (x86)\\jdk/bin;D:\\work\\graalvm-jdk-17_windows-x64_bin\\graalvm-jdk-17.0.9+11.1\\bin;D:\\WindowsVSC\\VC\\Tools\\MSVC\\14.36.32532\\bin\\Hostx64\\x64\\;C:\\Program Files\\PlasticSCM5\\server;C:\\Program Files\\PlasticSCM5\\client;C:\\Windows\\system32;C:\\Windows;C:\\Windows\\System32\\Wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\;C:\\Windows\\System32\\OpenSSH\\;D:\\work\\apache-tomcat-9.0.1-windows-x64\\apache-tomcat-9.0.1\\bin\\;D:\\work\\apache-maven-3.8.8-bin\\apache-maven-3.8.8\\bin\\;D:\\work\\gradle-8.2.1-all\\gradle-8.2.1\\bin;D:\\work\\apache-jmeter-5.5\\bin;D:\\work\\w64devkit-1.19.0\\w64devkit\\bin;C:\\Program Files\\Docker\\Docker\\resources\\bin;C:\\Program Files\\MySQL\\MySQL Server 8.0\\bin;D:\\Git\\cmd;D:\\python\\;D:\\nvm;C:\\Program Files\\nodejs;D:\\work\\visualvm_216\\bin;D:\\HashiCorp\\Vagrant\\bin;D:\\weixin\\微信web开发者工具\\dll;D:\\work\\netcat-win32-1.12;D:\\work\\VMware-ovftool-4.5.0-20459872-win.x86_64\\ovftool;D:\\work\\lu;D:\\work\\kotlin-compiler-1.9.22\\kotlinc\\bin;C:\\Program Files\\CMake\\bin;C:\\Program Files\\NVIDIA Corporation\\Nsight Compute 2020.3.0\\;D:\\miniconda3;D:\\miniconda3\\Library\\mingw-w64\\bin;D:\\miniconda3\\Library\\usr\\bin;D:\\miniconda3\\Library\\bin;D:\\miniconda3\\Scripts;C:\\Program Files\\MySQL\\MySQL Shell 8.0\\bin\\;C:\\Users\\Administrator\\AppData\\Local\\Microsoft\\WindowsApps;C:\\Users\\Administrator\\AppData\\Roaming\\npm;D:\\nvm;C:\\Program Files\\nodejs;D:\\work\\graalvm-jdk-17_windows-x64_bin\\graalvm-jdk-17.0.9+11.1\\bin\\;D:\\work\\graalvm-jdk-17_windows-x64_bin\\graalvm-jdk-17.0.9+11.1\\jre\\bin\\;C:\\Users\\Administrator\\AppData\\Local\\GitHubDesktop\\bin;C:\\Users\\Administrator\\.dotnet\\tools;D:\\work\\mongosh\\;;C:\\Users\\Administrator\\AppData\\Local\\Programs\\Ollama"
loading library C:\Users\ADMINI~1\AppData\Local\Temp\ollama1513712000\runners\cuda_v11.3\ext_server.dll
time=2024-04-01T08:23:20.407+08:00 level=INFO source=dyn_ext_server.go:87 msg="Loading Dynamic llm server: C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\ollama1513712000\\runners\\cuda_v11.3\\ext_server.dll"
time=2024-04-01T08:23:20.407+08:00 level=INFO source=dyn_ext_server.go:147 msg="Initializing llama server"
llama_model_loader: loaded meta data with 24 key-value pairs and 254 tensors from D:\ollama\blobs\sha256-456402914e838a953e0cf80caa6adbe75383d9e63584a964f504a7bbb8f7aad9 (version GGUF V3 (latest))
llama_model_loader: Dumping metadata keys/values. Note: KV overrides do not apply in this output.
llama_model_loader: - kv   0:                       general.architecture str              = gemma
llama_model_loader: - kv   1:                               general.name str              = gemma-7b-it
llama_model_loader: - kv   2:                       gemma.context_length u32              = 8192
llama_model_loader: - kv   3:                     gemma.embedding_length u32              = 3072
llama_model_loader: - kv   4:                          gemma.block_count u32              = 28
llama_model_loader: - kv   5:                  gemma.feed_forward_length u32              = 24576
llama_model_loader: - kv   6:                 gemma.attention.head_count u32              = 16
llama_model_loader: - kv   7:              gemma.attention.head_count_kv u32              = 16
llama_model_loader: - kv   8:     gemma.attention.layer_norm_rms_epsilon f32              = 0.000001
llama_model_loader: - kv   9:                 gemma.attention.key_length u32              = 256
llama_model_loader: - kv  10:               gemma.attention.value_length u32              = 256
llama_model_loader: - kv  11:                       tokenizer.ggml.model str              = llama
llama_model_loader: - kv  12:                      tokenizer.ggml.tokens arr[str,256000]  = ["<pad>", "<eos>", "<bos>", "<unk>", ...
llama_model_loader: - kv  13:                      tokenizer.ggml.scores arr[f32,256000]  = [0.000000, 0.000000, 0.000000, 0.0000...
llama_model_loader: - kv  14:                  tokenizer.ggml.token_type arr[i32,256000]  = [3, 3, 3, 2, 1, 1, 1, 1, 1, 1, 1, 1, ...
llama_model_loader: - kv  15:                tokenizer.ggml.bos_token_id u32              = 2
llama_model_loader: - kv  16:                tokenizer.ggml.eos_token_id u32              = 1
llama_model_loader: - kv  17:            tokenizer.ggml.unknown_token_id u32              = 3
llama_model_loader: - kv  18:            tokenizer.ggml.padding_token_id u32              = 0
llama_model_loader: - kv  19:               tokenizer.ggml.add_bos_token bool             = true
llama_model_loader: - kv  20:               tokenizer.ggml.add_eos_token bool             = false
llama_model_loader: - kv  21:                    tokenizer.chat_template str              = {% if messages[0]['role'] == 'system'...
llama_model_loader: - kv  22:               general.quantization_version u32              = 2
llama_model_loader: - kv  23:                          general.file_type u32              = 2
llama_model_loader: - type  f32:   57 tensors
llama_model_loader: - type q4_0:  196 tensors
llama_model_loader: - type q8_0:    1 tensors
llm_load_vocab: mismatch in special tokens definition ( 416/256000 vs 260/256000 ).
llm_load_print_meta: format           = GGUF V3 (latest)
llm_load_print_meta: arch             = gemma
llm_load_print_meta: vocab type       = SPM
llm_load_print_meta: n_vocab          = 256000
llm_load_print_meta: n_merges         = 0
llm_load_print_meta: n_ctx_train      = 8192
llm_load_print_meta: n_embd           = 3072
llm_load_print_meta: n_head           = 16
llm_load_print_meta: n_head_kv        = 16
llm_load_print_meta: n_layer          = 28
llm_load_print_meta: n_rot            = 192
llm_load_print_meta: n_embd_head_k    = 256
llm_load_print_meta: n_embd_head_v    = 256
llm_load_print_meta: n_gqa            = 1
llm_load_print_meta: n_embd_k_gqa     = 4096
llm_load_print_meta: n_embd_v_gqa     = 4096
llm_load_print_meta: f_norm_eps       = 0.0e+00
llm_load_print_meta: f_norm_rms_eps   = 1.0e-06
llm_load_print_meta: f_clamp_kqv      = 0.0e+00
llm_load_print_meta: f_max_alibi_bias = 0.0e+00
llm_load_print_meta: f_logit_scale    = 0.0e+00
llm_load_print_meta: n_ff             = 24576
llm_load_print_meta: n_expert         = 0
llm_load_print_meta: n_expert_used    = 0
llm_load_print_meta: causal attn      = 1
llm_load_print_meta: pooling type     = 0
llm_load_print_meta: rope type        = 2
llm_load_print_meta: rope scaling     = linear
llm_load_print_meta: freq_base_train  = 10000.0
llm_load_print_meta: freq_scale_train = 1
llm_load_print_meta: n_yarn_orig_ctx  = 8192
llm_load_print_meta: rope_finetuned   = unknown
llm_load_print_meta: ssm_d_conv       = 0
llm_load_print_meta: ssm_d_inner      = 0
llm_load_print_meta: ssm_d_state      = 0
llm_load_print_meta: ssm_dt_rank      = 0
llm_load_print_meta: model type       = 7B
llm_load_print_meta: model ftype      = Q4_0
llm_load_print_meta: model params     = 8.54 B
llm_load_print_meta: model size       = 4.84 GiB (4.87 BPW)
llm_load_print_meta: general.name     = gemma-7b-it
llm_load_print_meta: BOS token        = 2 '<bos>'
llm_load_print_meta: EOS token        = 1 '<eos>'
llm_load_print_meta: UNK token        = 3 '<unk>'
llm_load_print_meta: PAD token        = 0 '<pad>'
llm_load_print_meta: LF token         = 227 '<0x0A>'
ggml_cuda_init: GGML_CUDA_FORCE_MMQ:   no
ggml_cuda_init: CUDA_USE_TENSOR_CORES: yes
ggml_cuda_init: found 1 CUDA devices:
  Device 0: GeForce RTX 3050 Laptop GPU, compute capability 8.6, VMM: yes
llm_load_tensors: ggml ctx size =    0.19 MiB
llm_load_tensors: offloading 11 repeating layers to GPU
llm_load_tensors: offloaded 11/29 layers to GPU
llm_load_tensors:        CPU buffer size =  4955.54 MiB
llm_load_tensors:      CUDA0 buffer size =  1633.76 MiB
...........................................................................
llama_new_context_with_model: n_ctx      = 2048
llama_new_context_with_model: n_batch    = 512
llama_new_context_with_model: n_ubatch   = 512
llama_new_context_with_model: freq_base  = 10000.0
llama_new_context_with_model: freq_scale = 1
llama_kv_cache_init:  CUDA_Host KV buffer size =   544.00 MiB
llama_kv_cache_init:      CUDA0 KV buffer size =   352.00 MiB
llama_new_context_with_model: KV self size  =  896.00 MiB, K (f16):  448.00 MiB, V (f16):  448.00 MiB
llama_new_context_with_model:  CUDA_Host  output buffer size =   506.00 MiB
llama_new_context_with_model:      CUDA0 compute buffer size =  1302.88 MiB
llama_new_context_with_model:  CUDA_Host compute buffer size =    20.00 MiB
llama_new_context_with_model: graph nodes  = 957
llama_new_context_with_model: graph splits = 191
CUDA error: CUBLAS_STATUS_ALLOC_FAILED
  current device: 0, in function cublas_handle at C:\a\ollama\ollama\llm\llama.cpp\ggml-cuda.cu:659
  cublasCreate_v2(&cublas_handles[device])
GGML_ASSERT: C:\a\ollama\ollama\llm\llama.cpp\ggml-cuda.cu:193: !"CUDA error"

### OS

Windows

### GPU info

GeForce RTX 3050 Laptop GPU

### CPU

Intel

**Comment by RangerMauve** [comment]
What was the fix for this? I am facing this with rocm now.

**Comment by nanshaws** [comment]
> What was the fix for this? I am facing this with rocm now.

It may be caused by insufficient GPU memory.

**Comment by RangerMauve** [comment]
Oh good to know, ty. I'll try messing with my allocations.
