### ISSUE TITLE
Partial Deletion of Chinese Characters in Ollama Project

### ISSUE THREAD

**Issue by TanyaShue** [ollama/ollama#3432]
### What is the issue?

Description:

When running the Ollama project (version 0.1.30) on Windows 11 using PowerShell or Windows Terminal, I’ve encountered an issue where only half of each Chinese character is deleted upon attempting to remove them. The steps to reproduce the issue are as follows:

Launch Ollama with the command ollama run mistral.
Enter Chinese characters, for example, “哈哈哈哈哈哈哈哈哈”.
Attempt to delete the Chinese characters using the backspace key.

### What did you expect to see?

Expected Behavior:

Each Chinese character should be entirely removed from the input text area with a single backspace action.

Actual Behavior:

Only half of each Chinese character is removed with each backspace action, leaving behind a residual character fragment that cannot be deleted.

### OS

Windows

### Architecture

amd64

### Ollama version

0.1.30

### GPU

Nvidia

**Comment by faye0078** [comment]
same issue
