### ISSUE TITLE
Error: pull model manifest

### ISSUE THREAD

**Issue by taoxin2988** [ollama/ollama#3434]
I‘ve tried the methods from the FAQ,  but it does not work,  some advices or guidance will appreciated, Here are the commands I executed and the results
[root@Installer ~]# ollama run qwen:0.5b
pulling manifest
Error: pull model manifest: Get "https://registry.ollama.ai/v2/library/qwen/manifests/0.5b": dial tcp: lookup registry.ollama.ai: i/o timeout

**Comment by pdevine** [comment]
It looks like your DNS isn't resolving `registry.ollama.ai`. Can you ping it? Are you behind a firewall of some kind?

**Comment by TE-Caojianxun** [comment]
I met the same error: pull model manifest: Get "https://registry.ollama.ai/v2/library/llava/manifests/latest": dial tcp [2606:4700:3036::6815:4be3]:443: i/o timeout

**Comment by taoxin2988** [comment]
I add Environment="https_proxy=http://xxxxxx" in /etc/systemd/system/ollama.service, and it worked out.
