### ISSUE TITLE
Linux download of Ollama throws destination error

### ISSUE THREAD

**Issue by Chidu2000** [ollama/ollama#3439]
### What is the issue?

The curl command did not work, Ollama did not get installed

curl -fsSL https://ollama.com/install.sh | sh
>>> Downloading ollama...
Warning: Failed to open the file /tmp/tmp.XW0NnkYWmf/ollama: No such file or  %##O#-#                                                                        
Warning: directory
curl: (23) Failure writing output to destination

### What did you expect to see?

Expected to see the download happened correctly.

### Steps to reproduce

1.Navigate to Ollama 
2. Hit the linux download option
3. Copy the curl command for linux installation
4. Run in your terminal

### Are there any recent changes that introduced the issue?

No

### OS

Linux

### Architecture

x86

### Ollama version

'llama' from snap llama (1.4.0)

### GPU

Nvidia

### GPU info

545.29.06

Cuda version: 12.3

### CPU

Intel

**Comment by BruceMacD** [comment]
Hi @Chidu2000 it looks like something is going wrong when opening the temporary directory. Which linux distro are you using?

**Comment by Chidu2000** [comment]
> Hi @Chidu2000 it looks like something is going wrong when opening the temporary directory. Which linux distro are you using?

Hi @BruceMacD it's Ubuntu 22.04.3 LTS

**Comment by ejgutierrez74** [comment]
I didnt have any problem...and ive installed 1.0.28, 29 and 30....

**Comment by iplayfast** [comment]
From the command line type df -h and make sure you have space in the /tmp directory. (or / directory)

**Comment by navyzal** [comment]
Reinstall curl by using apt, not snap.
https://github.com/ollama/ollama/issues/3330

**Comment by stic-lab** [comment]
I had same issue on Ubuntu 24.04, it is solved by following @navyzal comment. The problem is from the fact that I used snap when installing curl. I reinstall it using apt and everything works fine.

**Comment by dhiltgen** [comment]
@Chidu2000 if the snap->apt switch for the curl install didn't fix your problem, please let us know.
