### ISSUE TITLE
Whether Windows 7 is supported?

### ISSUE THREAD

**Issue by PrimeQH** [ollama/ollama#3440]

**Comment by dhiltgen** [comment]
Unfortunately the tools and libraries we require to build Ollama no longer support Windows 7.

**Comment by taoxin2988** [comment]
~_~

**Comment by donotsdubba** [comment]
> Unfortunately the tools and libraries we require to build Ollama no longer support Windows 7.

Then keep them at a version that does? No technical reasons exist not to.
