### ISSUE TITLE
Can Someone help me with setting up the openai endpoint I cant figure it out!

### ISSUE THREAD

**Issue by alfi4000** [ollama/ollama#3444]
### What is the issue?

Can Someone help me with setting up the openai endpoint I cant figure it out!

### What did you expect to see?

Running openai api endpoint

### Steps to reproduce

there is nothing to reproduce

### OS

Linux

### Architecture

x86

### Ollama version

latest

### GPU

Nvidia

### GPU info

Tesla P40

### CPU

Intel

### Other software

Ubuntu Server 22.04
How can I setup the endpoint it looks for me unclear in the doc!:
https://ollama.com/blog/openai-compatibility

**Comment by alfi4000** [comment]
What do I have to install and to setup ?

**Comment by warvyvr** [comment]
once ollama startup, the openai compatable rest api is ready to go.
```json
curl http://localhost:11435/v1/chat/completions \
    -H "Content-Type: application/json" \
    -d '{
        "model": "mixtral:instruct",
        "messages": [
            {
                "role": "system",
                "content": "You are a helpful assistant."
            },
            {
                "role": "user",
                "content": "Hello!"
            }
        ]
    }'
{"id":"chatcmpl-508","object":"chat.completion","created":1712050361,"model":"mixtral:instruct","system_fingerprint":"fp_ollama","choices":[{"index":0,"message":{"role":"assistant","content":" Hello! I'm here to assist you today. How can I help you?"},"finish_reason":"stop"}],"usage":{"prompt_tokens":17,"completion_tokens":18,"total_tokens":35}}
```

**Comment by alfi4000** [comment]
So its automatically up and running?
I use this command to run it when I run that I get response!:  curl http://localhost:11435/v1/chat/completions \
    -H "Content-Type: application/json" \
    -d '{
        "model": "mixtral:instruct",
        "messages": [
            {
                "role": "system",
                "content": "You are a helpful assistant."
            },
            {
                "role": "user",
                "content": "Hello!"
            }
        ]
    }'
{"id":"chatcmpl-508","object":"chat.completion","created":1712050361,"model":"mixtral:instruct","system_fingerprint":"fp_ollama","choices":[{"index":0,"message":{"role":"assistant","content":" Hello! I'm here to assist you today. How can I help you?"},"finish_reason":"stop"}],"usage":{"prompt_tokens":17,"completion_tokens":18,"total_tokens":35}}

But Lobe chat tells me every time error and the terminal output says too 404 error!
