### ISSUE TITLE
docker `rocm` tag is not at `0.1.30-rocm` but at `0.1.29-rocm`

### ISSUE THREAD

**Issue by kirel** [ollama/ollama#3448]
### What is the issue?

The docker rocm tag is not at `0.1.30-rocm` but at `0.1.29-rocm` - see https://hub.docker.com/r/ollama/ollama/tags

### What did you expect to see?

`rocm` should be at the equivalent of `latest`

### Steps to reproduce

Just look at https://hub.docker.com/r/ollama/ollama/tags

### Are there any recent changes that introduced the issue?

Maybe the release process isn't automated enough?

**Comment by jmorganca** [comment]
Thanks for the issue! This is fixed now. Sorry about that!
