### ISSUE TITLE
CORS Error in Blower

### ISSUE THREAD

**Issue by udrs** [ollama/ollama#3449]
### What is the issue?

Thank you for your great work, the issue I met can be seen in the figure below.
![image](https://github.com/ollama/ollama/assets/71435435/cada7bd2-8326-41e3-a2c8-0ca8b72dccb3)
I have modified the configuation within the ollama.service, but the problem still exists.
![image](https://github.com/ollama/ollama/assets/71435435/0918a5c4-309d-44e1-b6ee-066983a5054c)

I build the blower in my computer, and I try to utilize the ollama in another server.

addMessageToChat('You', message);

            // Replace this URL with the actual endpoint where the backend API is hosted
            const apiURL = 'http://100.67.xxx.xxx:11434/api/generate';

            // Prepare the data to be sent in the POST request
            const requestData = {
                model: "llama2",
                prompt: message,
                options: {
                    num_ctx: 4096
                }
            };
Could you please tell me how can I solve this issue.

### What did you expect to see?

I hope to call API in server from another computer.

### Ollama version

latest

### Other software

javascript, html nginx

**Comment by YiuChoi** [comment]
the same error

**Comment by dhiltgen** [comment]
CORS settings are described here - https://github.com/ollama/ollama/blob/main/docs/faq.md#how-can-i-allow-additional-web-origins-to-access-ollama
