### ISSUE TITLE
Some ollama cli instructions: specially stop

### ISSUE THREAD

**Issue by ejgutierrez74** [ollama/ollama#3453]
### What are you trying to do?

- Stop 
- Restart
- Probably change  OLLAMA_MODELS, OLLAMA_HOST AND OLLAMA_PORT

Also would be nice to change ollama serve to ollama start for reasoning of other services or similar things.

### How should we solve this?

- Creating a CLI instructions to make it possible

ex: $ ollama stop serve
$ollama setdirectory /media/eduardo/ollama_models
$ollama sethost 127.52.56.63
$ollama restart serve

### What is the impact of not solving this?

Improve usability and give more tools to users/developers.

**Comment by pdevine** [comment]
@ejgutierrez74 thanks for the issue.

You can stop serving with standard unix commands (depending on your flavour of unix) or just use Ctrl-C. You can see the  `OLLAMA_HOST` and `OLLAMA_MODELS` documentation if you run `ollama serve --help`.

**Comment by ejgutierrez74** [comment]
I still think that ollama sethost and setdirectory would be nice.
I also opened a bug months ago, because it doesnt work in ubuntu / linux.
