### ISSUE TITLE
Please add olmo 7b

### ISSUE THREAD

**Issue by ChangjingZhang** [ollama/ollama#3456]
### What model would you like?

OLMO 7b

**Comment by pdevine** [comment]
Dupe of #2337

**Comment by userforsource** [comment]
https://github.com/ggerganov/llama.cpp/pull/6741
Now

    Hello, as referenced in issue https://github.com/ollama/ollama/issues/2287 the models supported are the ones llama.cpp supports. Check their forum and see if they support it.

This is now support in llama.cpp can you new support into ollama thanks
