### ISSUE TITLE
Add Auto-Update switch to Windows client

### ISSUE THREAD

**Issue by sebastianlau** [ollama/ollama#3459]
### What are you trying to do?

It would be good to be able to disable auto-updates for the Windows client

### How should we solve this?

 An environment variable, empty file for persistence -- checkbox in the taskbar as a stretch goal

### What is the impact of not solving this?

Currently I am renaming **ollama app.exe** to **ollama app.exe.disable** and manually starting ollama via cmd and **ollama serve** (not great for restarts)

**Comment by dhiltgen** [comment]
@sebastianlau the windows tray app does not automatically upgrade, but it does detect an upgrade is available, and download it to get ready.  Once downloaded, it will report that an upgrade is available with a pop-up banner, and if you click on that banner (or select the menu item to upgrade) it will perform the upgrade.  If you don't click on the banner or menu item, the system will leave the upgrade staged, but not perform the upgrade.

<img width="410" alt="image" src="https://github.com/ollama/ollama/assets/4033016/2c3eab33-cb64-4f0d-9b1f-7c70b943cd1a">

<img width="263" alt="image" src="https://github.com/ollama/ollama/assets/4033016/b9b1a303-3fb6-44f3-82fc-f5e6861197f1">


Are you seeing different behavior?

**Comment by omarshehab221** [comment]
@dhiltgen but the fact that downloads the update by itself consumes bandwidth.

**Comment by s4w3d0ff** [comment]
IMO it should NOT download anything until a user clicks the update option. Ollama should not be assuming that it has free rein over the users network and do what it wants whenever it wants... At the very least there should be an option to keep this from happening.
