### ISSUE TITLE
A easier way to pull models to Ollama public libary

### ISSUE THREAD

**Issue by alfi4000** [ollama/ollama#3480]
### What is the issue?

How to upload a model to the Ollama library?

### What did you expect to see?

A easy way

### Steps to reproduce

none

### OS

Linux, macOS

### Architecture

amd64, x86

### Platform

WSL2

### Ollama version

latest

### GPU

Nvidia, AMD, Intel, Apple

### GPU info

I have one of each over several devices

### CPU

Intel, AMD, Apple

### Other software

Can someone help me I don't understand how to pull a model to the Ollama library that everyone can access it!?

**Comment by alfi4000** [comment]
Oh I recognized I am on the wrong topic!

**Comment by sammcj** [comment]
Your title says pull models, but your bug report says upload (push) models?

I don't see how it could be easier than the docs state:

- pull: `ollama pull eramax/starling-lm-7b-beta`
- push: `ollama push eramax/starling-lm-7b-beta`

Either way - this doesn't really seem like a bug?

**Comment by alfi4000** [comment]
I mean like uploading it to the online library not sure how it is named that's why I use different words!

**Comment by alfi4000** [comment]
I want to see it here:  https://ollama.com/library !

**Comment by alfi4000** [comment]
I am a bit confused on that when I want to publish there a new model:  
Push a new model:

ollama pull llama2
echo "FROM llama2" >> Modelfile
echo "SYSTEM You are a friendly assistant." >> Modelfile
ollama create -f Modelfile dronerazzo/testet
ollama push dronerazzo/testet
... or push an existing model:

ollama cp llama2 dronerazzo/testet
ollama push dronerazzo/testet

**Comment by alfi4000** [comment]
and I haven't really found a tutorial anywhere yet!

**Comment by sammcj** [comment]
Ah, yeah ollama's docs are a bit of a pain - see: https://github.com/ollama/ollama/blob/main/docs/import.md#publishing-your-model-optional--early-alpha

**Comment by igorschlum** [comment]
Hi @alfi4000 if you have all the answers, I think that you can close the issue. If not, let us know. All LLM are not automatically publish on the librairy. Your model should bring something new. If you wants it to be public, you can publish it on Hugging-face.

**Comment by alfi4000** [comment]
> Ah, yeah ollama's docs are a bit of a pain - see: https://github.com/ollama/ollama/blob/main/docs/import.md#publishing-your-model-optional--early-alpha

Thanks

**Comment by ngeorger** [comment]
> Ah, yeah ollama's docs are a bit of a pain - see: [`main`/docs/import.md#publishing-your-model-optional--early-alpha](https://github.com/ollama/ollama/blob/main/docs/import.md?rgh-link-date=2024-04-04T07%3A29%3A17Z#publishing-your-model-optional--early-alpha)

Thank you very much #3172
