### ISSUE TITLE
Whether Qwen from ollama library is Qwen1.5?

### ISSUE THREAD

**Issue by OPDEV001** [ollama/ollama#3485]
### What model would you like?

When I type ollama run qwen:7b and the command completed successfully, but may I know whether the Qwen is Qwen or Qwen1.5, because I saw Qwen1.5 in Github.

If not, please add Qwen1.5 to ollama library.

Thanks,

**Comment by jmorganca** [comment]
Hi there, sorry this isn't easier to inspect for downloaded models. The full list of `qwen` models is here https://ollama.com/library/qwen/tags

You can compare their ID to see which ones are the same - both 1 and 1.5 are there - the `latest` and `7b` etc "tags" will default to the latest models (1.5)

**Comment by OPDEV001** [comment]
Many thanks,  I saw there has v1.5 including in tags.

I will update all my models in ollama, :)
