### ISSUE TITLE
ollama not using GPU in windows while all layers offloaded to gpu

### ISSUE THREAD

**Issue by VSR2007** [ollama/ollama#3486]
### What is the issue?

[new 1.txt](https://github.com/ollama/ollama/files/14865468/new.1.txt)
I running ollama windows. I have nvidia rtx 2000 ada generation gpu with 8gb ram. It also have 20 cores cpu with 64gb ram. Ollama some how does not use gpu for inferencing. the GPU shoots up when given a prompt for a moment (<1 s) and then stays at 0/1 %. All this while it occupies only 4.5gb of gpu ram. I am using mistral 7b.

### What did you expect to see?

better inference speed with full utilization of gpu especially when gpu ram is not limiting. 

### Steps to reproduce

Not sure

### OS

Windows

### Architecture

x86

### GPU

Nvidia

### GPU info

![tt](https://github.com/ollama/ollama/assets/107546824/2a5aae48-65aa-4e93-a4a5-39fe879a4be2)

### CPU

Intel

**Comment by dhiltgen** [comment]
The log you shared indicates it was loading into the GPU.  What sort of token rate are you seeing?

I've seen other people report that if they stop the tray application, and run the server in a terminal manually they see much better performance.  We still don't understand why, but that might be an experiment to try.  Also, can you look at Task Manager when you're seeing the slow performance and let us know if you see anything notable?  (e.g., some AV product chewing up a lot of CPU when you run inference, or something that might explain why it's being throttled.)

**Comment by dhiltgen** [comment]
If you're still having problems and it doesn't match #3511 please share more information and I'll re-open the ticket.
