### ISSUE TITLE
OLLAMA_INITIAL_MODEL for use with OLLAMA_KEEP_ALLIVE=-1

### ISSUE THREAD

**Issue by BananaAcid** [ollama/ollama#3499]
### What are you trying to do?

It would be nice, to be able to initially load a model using an env like  OLLAMA_INITIAL_MODEL in conjunction with the keep_alive=-1 option, to have OLLAMA start up and be ready to go on slow systems (as on a mining rig with usb2-raiser connected RTXs)

**Comment by BananaAcid** [comment]
@pdevine any idea how to trigger that workaround the moment the service is ready (or ollama has unloaded the model for any necessary cleanup)?

**Comment by pdevine** [comment]
@BananaAcid there's no way to really trigger it right now, but you can call out to `localhost:11434` (the status endpoint) until you get a 200, then immediately call `/api/generate` to load the model. It's not ideal, but should work as a workaround.

**Comment by pdevine** [comment]
With the next version of ollama you will also be able to do: `ollama run --keepalive -1s llama3 ""` which will load the model into memory indefinitely.

I'm going to go ahead and close the issue, but feel free to keep commenting.
