### ISSUE TITLE
Can Ollama use both  CPU and GPU for inference?

### ISSUE THREAD

**Issue by OPDEV001** [ollama/ollama#3509]
### What are you trying to do?

May I know whether ollama support to mix CPU and GPU together for running on windows? I know my hardware is not enough for ollama, but I still want to use the part ability of GPU.
But I checked the parameter information from link below, I still can not mix CPU&GPU, most load by CPU. 
https://github.com/ollama/ollama/blob/main/docs/modelfile.md

If I put all load to GPU, it will say "Out of VRam", :) you know it.

I am guessing if it have, maybe like we can specify GPU sharing part load， and CPU on most load?

Thanks,

### How should we solve this?

Please see content.

### What is the impact of not solving this?

If not, all load on GPU will crash.

### Anything else?

Thanks for all

**Comment by navr32** [comment]
You must provide the log off ollama serve to see how ollama have tried to share the models in both memory.

**Comment by OPDEV001** [comment]
I can run ollama serve in cmd line, it is the log what you want?

**Comment by pdevine** [comment]
Hi @OPDEV001 , this is how Ollama works by default. It will try to offload as many layers of the LLM as possible onto the GPU, and then if it doesn't fit the other layers will run on the CPU.

I'll go ahead and close the issue, but feel free to keep commenting.
