### ISSUE TITLE
On Windows, launching ollama from the shortcut or executable by clicking causes very slow tokens generation, but launching from commandline is fast

### ISSUE THREAD

**Issue by lrq3000** [ollama/ollama#3511]
### What is the issue?

Since I installed ollama (v0.1.30) on Windows 11 Pro, I run into a peculiar issue. When I launch ollama from the installed shortcut, which launches "ollama app.exe", or when I boot up my OS (which also starts up the same shortcut as configured by the ollama installer), ollama is extremely slow. If I do a "ollama run deepseek-coder", the model startup takes a very long time, several minutes, and when I type any input (eg, Hello), it takes again several minutes to generate each token (instead of 200-500ms/T with the workarounds).

However, I could fix the issue by simply closing the systray icon, and then either:
* type `ollama serve` in a terminal, but then I need to keep this open and I don't get the ollama systray icon.
* type `ollama run deepseek-coder` (or any other model), which will then also launch the ollama systray icon, just like launching `ollama app.exe`, but this time it works flawlessly, just like `ollama serve`.

I can confirm I can easily reproduce the bug simply by launching `ollama app.exe` manually, and the bug is not present with `ollama serve` and `ollama run <model>` (once `ollama app.exe` is first closed of course).

I read the logs but I did not find anything particularly telling. I will post a trace soon.

/EDIT: Here are the logs for when I launch `ollama app.exe` and it's slower (I launched `ollama app.exe` from the Windows shortcut then `ollama run deepseek-coder:6.7b-instruct-q8_0` then I type `Hello` as a prompt, then CTRL-C to stop generation that was too long after 2 tokens):

[app.log](https://github.com/ollama/ollama/files/14892997/app.log)
[server.log](https://github.com/ollama/ollama/files/14892998/server.log)

Here are the logs for when I launch `ollama run deepseek-coder:6.7b-instruct-q8_0` directly when `ollama app.exe` is killed:

[app.log](https://github.com/ollama/ollama/files/14893003/app.log)
[server.log](https://github.com/ollama/ollama/files/14893002/server.log)

### What did you expect to see?

200-500ms/T generation speed and much faster model initialization, instead of several minutes for each.

### Steps to reproduce

Launch `ollama app.exe` on Windows, this will be much slower than `ollama serve` or `ollama run <model>`.

### Are there any recent changes that introduced the issue?

I don't know, I never used ollama before (since it was not available on Windows until recently).

### OS

Windows

### Architecture

x86

### Ollama version

0.1.30

### GPU

Nvidia

### GPU info

Nvidia GeForce 3060 Laptop

### CPU

Intel

### Other software

Intel i7-12700h

**Comment by dhiltgen** [comment]
This definitely isn't expected behavior.  Looking at the logs, they seem ~identical, so I'm not sure what's going wrong.  Is it possible there's an AV involved which could be slowing things down?  Can you fire up Task Manager and look at it for both scenarios and see if you see any notable differences?

**Comment by lrq3000** [comment]
@dhiltgen Thank you for your attention and help in this issue. There is indeed an AV but looking up at the task manager it did not seem involved, but I will try again by disabling it.

**Comment by lrq3000** [comment]
@dhiltgen Unfortunately disabling all my protection systems (antivirus and firewall) did not help. The only thing that helps is closing the `ollama app.exe` that is launched at startup and relaunching it or just typing `ollama run <model>` and it works very fine, even when all my protection systems are activated.

In the task manager I did not see anything very specific but I'll try again

28% all the time, 1.5GB RAMc 7.2 GB private bytes and working set (because of 7B model)

more visible with 7B models than with the default deepseek-coder model (770 MB)

makes my computer laggy, including when I close the app, so it seems there is the issue that is happening also affects somehow the closing, maybe it's the memory assignments?

* This issue happens even if I wait 20min for my computer to boot up before launching ollama, so I'm sure all background apps finished loadingd since a long time.
* The issue also happens if I `/bye` and then `ollama run <model>` again (although the startup time is faster since the model is still loaded in memory it seems, but generation is as slow).
* The issue happens also if I relaunch ollama app.exe with the exact same shortcut as the one used for startup.

* It uses 1100-1300MB memory when it is working fine (95% total memory usage - because I have my web browser opened too) and 1-11% CPU usage and my whole OS is responsive, but it uses 1450-1700MB when it's buggy (99% memory usage) with 30-40% CPU usage and everything laggy.

* When it works, it loads the model under a few seconds and generates a response almost instantly (or more accurately it starts streaming right away and streams as fast as ChatGPT), whereas when it's slow it gets stuck for several minutes or dozen of minutes on each token.

My ollama got updated today to 0.1.31, and it seems to have slightly changed the behavior in a more reproducible way, so hopefully this will ease a lot tracking down this issue. Here are the new insights I think you will find very interesting:

* I can now reproduce the issue without restarting, by simply killing the currently launched ollama.exe / ollama app.exe, and then double-clicking on `C:\Users\<username>\AppData\Local\Programs\Ollama\ollama app.exe` (hence no need for a shortcut). Then simply run a big enough model like `ollama run deepseek-coder:6.7b-instruct-q8_0` for a 16 GB RAM system such as mine.
* I can systematcally avoid the issue (ie, get good performances) by first killing ollama.exe and then: either launching `C:\Users\<username>\AppData\Local\Programs\Ollama\ollama app.exe` in `a terminal` (I tried both with the old terminal and powershell, it works in both cases) and then again `ollama run deepseek-coder:6.7b-instruct-q8_0` ; or by directly launching `C:\Users\<username>\AppData\Local\Programs\Ollama\ollama app.exe` without launching `ollama app.exe` beforehand (this latter behavior did not change).

Note that being administrator or not does not change anything: I did all my tests without being an administrator, but I tested launching the icon as an administrator by creating a shortcut with admin mode checked, and it did not help. Whereas launching ollama app.exe from the commandline is always fast even if in user mode.

Hence, it seems the issue happens only when launching `ollama app.exe` by double-clicking it or at startup (which emulates double-clicking it from its shortcut). A simple fix is to launch ollama app.exe by a batch command, but the correct fix is due to some kind of different behavior between launching in commandline or from double-clicking

(My guess is that Windows OS is treating both cases differently because of the UI library used somehow, and it then bundles a bunch of additional UI related libraries or stuff that ollama doesn't need, and it then causes the app to be just a bit too heavy than it can be for my system RAM to support the model I loaded. This would explain why the issue does not seem to happen with small enough models. But really I don't have enough data to ascertain this is the case.)

If you have any idea for me to debug this further, please let me know, I'm eager to understand what's really happening here even though I already have a workaround!

**Comment by joubertdj** [comment]
@lrq3000 : Thanks for finding a workaround ... and for highlighting it here ... I thought I broke something ... I am only playing with Ollama and Langchain at the moment ... and I thought I did something (as I am playing with my own indexing and metadata etc.) that it suddenly became SO slow ... but I am also experiencing this slow down. After killing the "ollama app.exe" and starting it the 3way you mentioned it then improved ... however ... to me it still feels far slower than it was previously (considering I am also using it on an equivalent laptop as yours, albeit Windows 10 Pro).

**Comment by joubertdj** [comment]
> @lrq3000 : Thanks for finding a workaround ... and for highlighting it here ... I thought I broke something ... I am only playing with Ollama and Langchain at the moment ... and I thought I did something (as I am playing with my own indexing and metadata etc.) that it suddenly became SO slow ... but I am also experiencing this slow down. After killing the "ollama app.exe" and starting it the 3way you mentioned it then improved ... however ... to me it still feels far slower than it was previously (considering I am also using it on an equivalent laptop as yours, albeit Windows 10 Pro).

PS. I can confirm that the pre-release of 0.1.32 addresses the issue. It seems that the primary reason for it being slow was that it tried ONLY to use vRAM and not system RAM ...

**Comment by dhiltgen** [comment]
@joubertdj just to confirm, you're seeing good/consistent performance with 0.1.32 regardless of how the app is started?

In the 0.1.32 release we've changed to using subprocesses to manage the GPU.

@lrq3000 could you give it a try as well and see if the problem goes away in 0.1.32 for you?

If that release doesn't resolve it, the next things we can look at are what the processes are set to for Priority in the Task Manager Details view, and possibly looking at resmon.exe's cpu/disk/memory usage in these two scenarios.

**Comment by joubertdj** [comment]
> @joubertdj just to confirm, you're seeing good/consistent performance with 0.1.32 regardless of how the app is started?

That is correct. It looks like it solved the issue for me.

**Comment by joubertdj** [comment]
I just upgraded to the stable release. Although I have to admit, the upgrade via the system icon (Update available restart) didn’t work at all, maybe that was a pre_release thing. I had to download OllamaSetup.exe manually, kill all the ollama processes (as even Quit Ollama didn’t work) and just install it via the installer downloaded.

 

My performance was “stable”, meaning, it is as I expected for this class of machine and better than v0.1.31. 

 

When you run your application, and it is busy generating tokens. How much RAM does ollama_lama_server.exe consume? When I stressed tested a big LLM in v0.1.31 it got stuck at a maximum of 2GB (or at least the ollama.exe got stuck at that level, initially I thought they compiled the executable to be a 32-Bit exe). With v0.1.32 it consumes +- 9GB (using deepseek-coder:6.7b-instruct-fp16). However, even 9GB is a tad “low” for the 6.7b fp16 is it not? 

 

When I ran the “deepseek-coder:6.7b-instruct-q4_1” model the memory utilization was again at +-9GB, which seems high for an q4_1 model … or am I missing something again?

 

In both instances the GPU was barely used … maybe once or twice during the entire token generation, and then it was never used again? Maybe the integrated  RTX3050’s vRAM is not sufficient or something?

**Comment by lrq3000** [comment]
So I ran additional tests to observe whether it's an issue with a lack of RAM. I uninstalled and reinstalled several times both versions from the exe installers on the GitHub releases page.

* v0.1.31 commandline: 1463 MB RAM to 1616 RAM -- when reloading model after some time after /bye, it consumes only 1254-1360 MB RAM. In fact, without /bye, by waiting for some time, the RAM usage goes as low as 1090 MB. These figures do not change when sending prompts to the model. CPU usage: from 0% to ~60% while generating tokens (other processes cumulatively take only 3-4% CPU).

* v0.1.31 from clicking on binary or shortcut: 1614 MB, stays at 25-30% CPU usage even after CTRL-C break and /bye for a while, a dozen seconds maybe (until next token generation?) then stops and falls back to 0%.
But even so, 2.1 GB RAM still available and despite this, program is still horribly slow. So it's not only caused by insufficient available RAM.
After waiting, it still goes to 1531 MB. And it still horribly slow. Ah after some time after reloading, during generation, it can go lower to 1392 MB. Still very very slow, despite 2.1GB free RAM.

Note that when lacking RAM, this indeed reproduces the issue. But when there is no lack of RAM, the issue persists when launching from clicking on the executable or shortcut.

CPU usage: 30-40% while generating tokens (other processes cumulatively take only 3-4% CPU).

* v0.1.32 commandline: 1462MB RAM right away, same RAM after waiting a while. Fast generation, as before. CPU usage: from 0% to ~60% while generating tokens (other processes cumulatively take only 3-4% CPU) (same as before).

* v0.1.32 from clicking on binary or shortcut: 1460 MB RAM right away, same RAM after waiting a while. Slow generation as before. CPU usage: 30-40% while generating tokens (other processes cumulatively take only 3-4% CPU) (as before).

----

Key take aways:
* v0.1.32 new RAM handling and subprocess compared to v0.1.31 allows to normalize RAM usage: first launch is smaller than before (2GB less!), but subsequent model reloadings are bigger (1-2GB more).
* Lacking RAM can mimic the issue of sluggish token generation.
* But when there is way enough RAM, **the issue persists in both version: launching by clicking on the executable or shortcut really produces systematically sluggish token generation**, despite equal RAM usage compared to commandline launch (which displays fast generation).
* There is one notable difference between sluggish and fast tokens generations: when it's sluggish (launched by clicking), CPU usage hovers around 30-40% but for some reason it causes micro-freezes on the whole computer sometimes (especially when quitting ollama from the systray icon) ; whereas when fast, CPU usage goes from 0% to 60% and right back to 0% when finished.

Note that I am not only using ollama, I regularly use this exact same model (same quantization, same number of parameters, same instruct mode) with koboldcpp and gpt4all and there is no such issue, I always get fast tokens generation there. This issue is specific to ollama and only when launching by clicking on the executable/shortcut.

So indeed my issue seems to be different from @joubertdj 's.

**Comment by joubertdj** [comment]
@lrq3000 : This morning, I read your feedback and without initially starting Ollama from the icon, I started it from the console via "ollama serve". Its performance was, at minimum, four times better/faster than when I started it via the icon!!! I thought, myabe, this was only due to a fresh start, so I stopped "olama serve" and started it with the icon. It was noticebly slower!!!????

You are correct, although I may have had some different issue previously, there is definitely some performance issue here somewhere. I still however do not fully understand how a 7B model that is 4GB (almost) in file size only takes 2GB or RAM though ... that portion has me a bit "scratching-my-head" ...

**Comment by lrq3000** [comment]
@joubertdj I'm not sure either about the difference but I think this filesize is not the model but the size the app is taking in memory, and also Windows uses compression methods. The figures I reported are from the Windows native task manager. When I use Process Explorer, I get the expected total memory size of ~8GB, but I do not report it because it does not change, this is simply the model's size, so there is no difference when I launch via the icon or via commandline, or between different versions, etc.

**Comment by mmacphail** [comment]
Thank you !!! I have exactly the same problem. I was wondering why after a fresh install of ollama it was fast, and then sometimes it was slow. Fucking hell !!

**Comment by dhiltgen** [comment]
We've reshuffled the packaging model a bit on windows in the latest release.  I still don't understand the root cause on this performance bug, but it's possible that reshuffling might have an impact, so I'd suggest folks give [0.1.33](https://github.com/ollama/ollama/releases) a try.

**Comment by qsdhj** [comment]
I have the same issue now. After the update to ollama 0.1.33 on Windows 11 Pro

**Comment by dhiltgen** [comment]
I still haven't managed to reproduce this or figure out what the culprit is for the strange slow-down in performance.

For folks who have seen this behavior, can you share a bit more about your system setup so that hopefully I can find a way to repro and ultimately fix whatever it is?

- Windows 10 or 11, pro or home?
- Personal system or work system that might have a GPO config, or any other add-on software that could explain it? (e.g., AV software, etc.)
- Laptop or Desktop?  If laptop, any difference plugged in vs on battery?
- CPU model (e.g., is it a modern system with efficiency cores that maybe we're getting stuck on?) `Get-WmiObject -Class Win32_Processor -ComputerName. | Select-Object -Property [a-z]*`
- System memory - are we paging when this happens? `systeminfo | find "Virtual Memory"`

**Comment by lrq3000** [comment]
@dhiltgen

### OS version
Windows 11 pro.

### Personal system or work system
Personal system.
AV is Avira but I also used Avast in the past and I also tried to uninstall it fully at some point in my tests.

### Laptop or Desktop?
Laptop. It is always plugged and I am using an external fan stand (KLIM Cyclone).

### CPU model

```
PSComputerName                          : NEOM
Availability                            : 3
CpuStatus                               : 1
CurrentVoltage                          : 13
DeviceID                                : CPU0
ErrorCleared                            :
ErrorDescription                        :
LastErrorCode                           :
LoadPercentage                          : 2
Status                                  : OK
StatusInfo                              : 3
AddressWidth                            : 64
DataWidth                               : 64
ExtClock                                : 100
L2CacheSize                             : 11776
L2CacheSpeed                            :
MaxClockSpeed                           : 2300
PowerManagementSupported                : False
ProcessorType                           : 3
Revision                                :
SocketDesignation                       : U3E1
Version                                 :
VoltageCaps                             :
Architecture                            : 9
AssetTag                                :
Caption                                 : Intel64 Family 6 Model 154 Stepping 3
Characteristics                         : 252
ConfigManagerErrorCode                  :
ConfigManagerUserConfig                 :
CreationClassName                       : Win32_Processor
CurrentClockSpeed                       : 2300
Description                             : Intel64 Family 6 Model 154 Stepping 3
Family                                  : 198
InstallDate                             :
L3CacheSize                             : 24576
L3CacheSpeed                            : 0
Level                                   : 6
Manufacturer                            : GenuineIntel
Name                                    : 12th Gen Intel(R) Core(TM) i7-12700H
NumberOfCores                           : 14
NumberOfEnabledCore                     : 14
NumberOfLogicalProcessors               : 20
OtherFamilyDescription                  :
PartNumber                              :
PNPDeviceID                             :
PowerManagementCapabilities             :
ProcessorId                             : BFEBFBFF000906A3
Role                                    : CPU
SecondLevelAddressTranslationExtensions : False
SerialNumber                            :
Stepping                                :
SystemCreationClassName                 : Win32_ComputerSystem
SystemName                              : NEOM
ThreadCount                             : 20
UniqueId                                :
UpgradeMethod                           : 1
VirtualizationFirmwareEnabled           : False
VMMonitorModeExtensions                 : False
Scope                                   : System.Management.ManagementScope
Path                                    : \\NEOM\root\cimv2:Win32_Processor.DeviceID="CPU0"
Options                                 : System.Management.ObjectGetOptions
ClassPath                               : \\NEOM\root\cimv2:Win32_Processor
Properties                              : {AddressWidth, Architecture, AssetTag, Availability...}
SystemProperties                        : {__GENUS, __CLASS, __SUPERCLASS, __DYNASTY...}
Qualifiers                              : {dynamic, Locale, provider, UUID}
Site                                    :
Container                               :
```

Additionally I used [Intel's app](https://www.intel.com/content/www/us/en/support/articles/000097881/processors.html) to list the number of P-cores and E-cores:
![MpOZhen4qN](https://github.com/ollama/ollama/assets/1118942/f7ad3ca1-93c4-45f0-8569-95eac37a3410)
![ProcID_cIysqwLu0S](https://github.com/ollama/ollama/assets/1118942/e65f8cc3-0310-4f6d-8427-805c23f1df15)
![ProcID_esoFDTMji4](https://github.com/ollama/ollama/assets/1118942/481759d0-e939-4e9c-84c0-0ac7ef7f93f4)

### System memory
(I will post this after in an edit to avoid losing my changes in case if my browser or OS crashes during tests.)

**Comment by qsdhj** [comment]
## OS version  
Windows 11 Enterprise
Version: 23H2

## System  
+ Work system
+ Sophos, ZScaler installed and acitve
+ Laptop, only used plugged in

## CPU  
11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz   

## RAM  
32,0 GB 

## VRAM
6GB 
NVIDIA RTX A3000

## 
I think my problem was different from the one, called in this issue. I use ollama together with a HuggingFace Sentence-Transformer in Langchain and LlamaIndex.
My problem is that if I install the torch version with CUDA to use it with my Embedding modell, I get this weird behaivour in Ollama, where the GPU is running on 100% load for a few minutes until the llm is responsing. 
Terminating my Python script, and the ollama processes, fixes it for the first call to an llm, after that its the same, until I restart windows.
Installing the non CUDA torch version fixed that, just now I can't use the GPU for creating embeddings, so its not a usable solution for me.

**Comment by lowfatgeek** [comment]
I am faced with exactly the same issue as well. I have to run "ollama serve" in the terminal and I have to keep the Terminal window open side by side with the browser (OpenWebUI), or else the performance becomes so slow and sluggish. Even if I maximize the browser and Terminal window behind it, the performance is so slow. Both Terminal and Browser should be open side by side.

I'm on Intel i5-13450HX, 16GB RAM, and RTX4050 6GB GPU.

**Comment by dhiltgen** [comment]
It seems so far that the common theme is recent CPUs on a laptop.  Perhaps there's some quirk causing ollama to run on efficiency cores?  Has anyone experienced this slowdown on a desktop or a system without efficiency cores?

**Comment by wac81** [comment]
Check the power management items, including bios, my case is, if the screen is turned on, it runs fast, if the screen is turned off, it runs very slow, check this time mainly occupied in cpu

**Comment by chyok** [comment]
Hi @dhiltgen , 
Some problem here, I am working on a desktop computer. When I open using the desktop icons, the CPU only allocates to 4 small cores, while the other 8 big guy are just observing. If I use the `ollama serve`, everything is normal and fast.

<img width="513" alt="image" src="https://github.com/ollama/ollama/assets/32629225/023b15b1-7ff9-451f-bc91-0b2eb1a3eaa3">


My PC detail is as follows:
Windows 11 23H2 version 22631.2861
i7-12700K
RTX 3060Ti

It feels like Windows is treating it as a background task and only allocating the small cores to it.

**Comment by dhiltgen** [comment]
@chyok when you see it running on the "small cores" does it also show up with the green leaf icon in TaskManager?  I haven't been able to reproduce this in my setups, but if someone can confirm definitively this is the case, then I should be able to code up a fix to force it to not go into efficiency mode.

<img width="59" alt="Screenshot 2024-07-22 at 10 38 12 AM" src="https://github.com/user-attachments/assets/404bd4d3-2115-44fa-9716-3c3007d2647d">

**Comment by chyok** [comment]
> @chyok when you see it running on the "small cores" does it also show up with the green leaf icon in TaskManager? I haven't been able to reproduce this in my setups, but if someone can confirm definitively this is the case, then I should be able to code up a fix to force it to not go into efficiency mode.
> 
> <img alt="Screenshot 2024-07-22 at 10 38 12 AM" width="59" src="https://private-user-images.githubusercontent.com/4033016/351059863-404bd4d3-2115-44fa-9716-3c3007d2647d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE3MzIzODEsIm5iZiI6MTcyMTczMjA4MSwicGF0aCI6Ii80MDMzMDE2LzM1MTA1OTg2My00MDRiZDRkMy0yMTE1LTQ0ZmEtOTcxNi0zYzMwMDdkMjY0N2QucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MjNUMTA1NDQxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MzlmMGQ5NDc4YjMyMjc1ZDM4NGQxOTZiY2NjYjQ2NWVhZjVmYTgzMGM3ZDdjZDk1ZDQwYWQ0MDQ3NDY3MjhhZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.46H54e9k342ZSTbgbedXtX5r4uIgFokCdbVM2R6VVy4">

It's quite strange that it doesn't enter efficiency mode, and it's very easy to reproduce the problem on my system. I had to use "process lasso" to force it to be scheduled on the big cores.

**Comment by dhiltgen** [comment]
From what folks are seeing, it sounds like this may not be an efficiency setting, but a process priority setting.

In Task Manager, what is the Priority for the `ollama_llama_server.exe` process?

In Win 10 click the "Details" tab at the top.  In Win 11, click the Details option on the left.

Win10 example:
<img width="526" alt="Screenshot 2024-07-30 at 4 55 29 PM" src="https://github.com/user-attachments/assets/ef73f7be-5e77-4717-969f-5230ec965350">

**Comment by chyok** [comment]
I'm traveling outside, and unable to use computer, but I'm quite certain that the priority is normal, even though I've tried to increase it, but it still hasn't worked. Setting the relevance and manually specifying the big core can solve the issue, but this process is new each time, so I need to set it every time.

**Comment by lrq3000** [comment]
Yes I also confirm that priority is normal, I even tried to set it to high using ProcessExplorer.

**Comment by dhiltgen** [comment]
Strange.  So it's not the Priority, and it's not efficiency mode either.

**Comment by greggft** [comment]
Under windows, maybe try this
Settings
type in GPU in the search
Select Graphic Settings
Should take you to 
Graphics performance settings
Click on 
Browse
Add each of the executables you want to assign to your GPU
add the executables for ollama here
See if that helps

**Comment by ivanvengeruk** [comment]
> Under windows, maybe try this Settings type in GPU in the search Select Graphic Settings Should take you to Graphics performance settings Click on Browse Add each of the executables you want to assign to your GPU add the executables for ollama here See if that helps
- no, its not helps

have same issue with slow tokens.
configuration:
Laptop

CPU
12th Gen Intel(R) Core(TM) i7-12800HX
2,00 GHz
Core: 16
Logical cores:	24
Virtualization:	ON

RAM: 64GB

Graphical processor: 0
NVIDIA RTX A1000 Laptop GPU
Driver version:	32.0.15.6076
DirectX:	12 (FL 12.1)
Dedicated GPU memory  0,9/4,0 Gb
Shared GPU memory  0,2/31,9 Gb
GPU Memory	1,1/35,9 Gb

reproduce problem:
start ollama app.exe from gui (main menu) or double-click on app
then in terminal "ollama run llama3:8b --verbose"
then "hello"
result:
Hello! It's nice to meet you. Is there something I can help you with, or would you like to chat?

total duration:       2m29.5910962s
load duration:        67.9495ms
prompt eval count:    11 token(s)
prompt eval duration: 17.11587s
prompt eval rate:     0.64 tokens/s
eval count:           26 token(s)
eval duration:        2m12.403243s
eval rate:            0.20 tokens/s

**Comment by jayghoshter** [comment]
In my case, setting the process priority to high speeds up the output instantly. The difference between "normal" and high is quite stark, too.

**Comment by Fatalmemory** [comment]
old thread, but to chance a guess - could it be related to windows superfetch? windows could either be caching files differently for files that load on startup, or worst case scenario, could be paging the files into a hibernation file on the hard drive and caching them that way, which would be much slower than RAM until they're swapped into actual RAM

**Comment by lrq3000** [comment]
Thank you for working on this but I think it is maybe premature to close this issue as I wrote manually changing task priority did not help in the past. I will try again when this will be released in an update and will let you guys know if the issue is fixed or not for me.

**Comment by ValleZ** [comment]
It still doesn't run on windows

**Comment by dhiltgen** [comment]
@ValleZ can you clarify?  This issue was tracking a performance problem which we believe we've fixed, but if it completely doesn't run for you, that sounds like an unrelated defect.  If you mean the performance problem wasn't fixed, please explain a bit more about your scenario.

**Comment by ValleZ** [comment]
Googling why it won't start gave this ticket for some reason, weird, yes, it's totally unrelated.

**Comment by dhiltgen** [comment]
@ValleZ what happens if you open a fresh PowerShell terminal and type `ollama run llama3.1` ?

**Comment by ValleZ** [comment]
Idk, I uninstalled it. If it’s a terminal only solution it should not have
UI for installer or should have confirmation that installation is completed
and now you are supposed to type something somewhere to proceed

**Comment by dhiltgen** [comment]
@ValleZ yes, Ollama is a terminal and API based tool for running LLMs.  If you're looking for a GUI, there's a ton of community based UIs listed here you can explore - https://github.com/ollama/ollama?tab=readme-ov-file#web--desktop

**Comment by mimo-to** [comment]
yah same happened here,
the ollama GUI is not opening and u cant able to access it from system tray 
but in cli everything is working fine

**Comment by cdll** [comment]
same issue still on `ollama@v0.18.1`😭

**Comment by lrq3000** [comment]
I use [lemonade-server](https://github.com/lemonade-sdk/lemonade), the GUI and systray works fine and very fast on Windows and it exposes an API aed port compliant with most of ollama's features (it can be used in local chatbot apps as an ollama server).
