### ISSUE TITLE
Experimental LLM Library Override does not appear to work on Windows

### ISSUE THREAD

**Issue by lrq3000** [ollama/ollama#3512]
### What is the issue?

I tried the [Experimental LLM Library Override](https://github.com/ollama/ollama/blob/main/docs/troubleshooting.md#llm-libraries) on Windows via two means:

* Temporary environment variable definition: `SET OLLAMA_LLM_LIBRARY="cpu_avx2" & ollama run deepseek-coder`
* Permanent environment variable definition in the Windows System dialog.

Both failed, in server.log I get the following error:

`time=2024-04-06T10:11:46.333+02:00 level=INFO source=llm.go:147 msg="Invalid OLLAMA_LLM_LIBRARY \"cpu_avx2\"  - not found"`

And ollama proceeds to use my GPU.

See the full server.log attached:

[server.log](https://github.com/ollama/ollama/files/14892936/server.log)

### What did you expect to see?

Ollama should be using cpu_avx2 instead of the GPU.

### OS

Windows

### Architecture

x86

### Ollama version

0.1.30

### GPU

Nvidia

### GPU info

Nvidia GeForce 3060 Laptop

### CPU

Intel

### Other software

Intel i7-12700H

**Comment by dhiltgen** [comment]
It looks like you included the quotation marks in the value, which is causing problems.  If you remove the quotes it should work.

**Comment by dhiltgen** [comment]
`"Invalid OLLAMA_LLM_LIBRARY cpu_avx2  - not found"`

It's subtle, but there's an extra space at the end of cpu_avx2.

I'll add some hardening code to strip white space (and quotes) but if you set it to exactly the string cpu_avx2 without spaces or quotes it should work.

**Comment by lrq3000** [comment]
You are correct @dhiltgen , you've got very good eyes!

So it already works indeed with v0.1.32 with the following command (need to remove the whitespace between `cpu_avx2` and `&`):

`SET OLLAMA_LLM_LIBRARY=cpu_avx2& ollama run deepseek-coder:6.7b-instruct-q8_0`

Thank you very much for implementing the fix to autotrim, it will make life easier!
