### ISSUE TITLE
change command-r modelfile, ollama hangs

### ISSUE THREAD

**Issue by ChangjingZhang** [ollama/ollama#3524]
After creating a model using command-r, use new model to RAG, ollama hangs.

**Comment by pdevine** [comment]
@ChangjingZhang can you attach the modelfile and logs?  Is this command-r or command-r plus?

**Comment by jmorganca** [comment]
Hi there @ChangjingZhang - as of 0.1.32 many hanging issues should be solved, or at least a more descriptive error will be provided. Would it be possible to try again? And if an error does occur, feel free to open another issue so we can take a look!
