### ISSUE TITLE
error: listen tcp: lookup tcp/\ollama: unknown port

### ISSUE THREAD

**Issue by bkdigitalworld** [ollama/ollama#3525]
Could not open the interface of ollama:

time=2024-04-07T22:40:43.318+08:00 level=WARN source=server.go:113 msg="server crash 13 - exit code 1 - respawning"
time=2024-04-07T22:40:43.820+08:00 level=ERROR source=server.go:116 msg="failed to restart server exec: already started"
time=2024-04-07T22:40:56.824+08:00 level=WARN source=server.go:113 msg="server crash 14 - exit code 1 - respawning"
time=2024-04-07T22:40:57.334+08:00 level=ERROR source=server.go:116 msg="failed to restart server exec: already started"
time=2024-04-07T22:41:11.349+08:00 level=WARN source=server.go:113 msg="server crash 15 - exit code 1 - respawning"
time=2024-04-07T22:41:11.862+08:00 level=ERROR source=server.go:116 msg="failed to restart server exec: already started"
time=2024-04-07T22:41:26.875+08:00 level=WARN source=server.go:113 msg="server crash 16 - exit code 1 - respawning"
time=2024-04-07T22:41:27.387+08:00 level=ERROR source=server.go:116 msg="failed to restart server exec: already started"
time=2024-04-07T22:41:43.390+08:00 level=WARN source=server.go:113 msg="server crash 17 - exit code 1 - respawning"
time=2024-04-07T22:41:43.905+08:00 level=ERROR source=server.go:116 msg="failed to restart server exec: already started"
time=2024-04-07T22:42:00.913+08:00 level=WARN source=server.go:113 msg="server crash 18 - exit code 1 - respawning"
time=2024-04-07T22:42:01.426+08:00 level=ERROR source=server.go:116 msg="failed to restart server exec: already started"

Error: listen tcp: lookup tcp/\Ollama: unknown port

**Comment by pdevine** [comment]
@bkdigitalworld is this version `0.1.31`? Can you post some more details?

**Comment by dhiltgen** [comment]
@bkdigitalworld we had some subprocess lifecycle bugs in prior releases on windows.  Those should be resolved in 0.1.33.  Can you give that release a try and let us know if you're still seeing these errors?

**Comment by pdevine** [comment]
I'll go ahead and close the issue. Please feel free to reopen if you're still seeing problems.
