### ISSUE TITLE
tid in log always be the same 

### ISSUE THREAD

**Issue by mofanke** [ollama/ollama#3535]
### What is the issue?

https://github.com/ggerganov/llama.cpp/issues/6534

### What did you expect to see?

i understand that 'tid' represents thread ID, which should change upon restarting, but I've noticed that 'tid':'0x1fc50fac0' keeps appearing repeatedly. I've also noticed some other values, but I'm not sure why.

### OS

macOS

### Architecture

arm64

### CPU

Apple

**Comment by dhiltgen** [comment]
I'm not seeing how this is a problem.   This thread ID is only reported in the logs. If you think this is a bug that somehow impacts the behavior of the system in a negative way, please elaborate.
