### ISSUE TITLE
Why my ollama not use gpu？

### ISSUE THREAD

**Issue by loks666** [ollama/ollama#3536]
My ollama is use windows installer setup running.There was a problem,when I watch my tsak manager,I noticed that my gpu was not being used. I want know that's why? or say I need run what command?
I wish someone could solve my problem，thanks
![image](https://github.com/ollama/ollama/assets/33214035/1712abc8-33ba-441e-b6e4-ec7d6a34d662)

**Comment by aosan** [comment]
What model are you using? I can see your memory is at 95%. GPU is fully utilised by models fitting in VRAM, models using under 11 GB would fit in your 2080Ti VRAM.

GPU usage would show up when you make a request, e.g. `ollama run mistral` and make a request: "why is the sky blue?" 

GPU load would appear while the model is providing the response.

**Comment by loks666** [comment]
Are you saying that my computer will only use the gpu if I run a model that is smaller than my gpu memory?

**Comment by aosan** [comment]
Depends on the model, some models offload layers to GPU even if they can't fit in VRAM and are running on CPU. 

For maximum performance, any model fitting in VRAM will benefit from GPU processing.

**Comment by pdevine** [comment]
Hi @loks666, yes, it will try to offload as many "layers" of the model onto your GPU as possible. If the model is bigger than the memory of your GPU, those extra layers will be run on the CPU instead. You can try running smaller models, or use a more quantized version of the same model.

I'm going to go ahead and close the issue, but feel free to keep commenting.

**Comment by highbrow-228** [comment]
It doesn't help, at least in my case. I have a video card with a 20GB GPU. Cuda, nvidia toolkit are installed. However, the models do not use the GPU at all😩. I have tried llama3.2 as the small model that will fit and the big one (llama3.3).

**Comment by highbrow-228** [comment]
@Mohamed0Hegazi 
First, please write in English, like the rest of the civilized world.
Second, I don't really understand what book you're talking about, but if you can provide a link, I'll tell you that I've read quite a few books.

**Comment by highbrow-228** [comment]
@Mohamed0Hegazi 
First of all, please write in English, because I'm lazy and don't want to translate it ;).
Second, I don't really understand what book you're talking about, but if you can provide a link, I'll tell you that I've read quite a few books.
