### ISSUE TITLE
ollama 0.1.31 Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by zhqfdn** [ollama/ollama#3544]
### What is the issue?

[root@localhost ~]# cat /etc/redhat-release 
AlmaLinux release 9.3 (Shamrock Pampas Cat)
[root@localhost ~]# ollama -v
Warning: could not connect to a running Ollama instance
Warning: client version is 0.1.30
[root@localhost ~]# ./ollama -v
Segmentation fault (core dumped)
[root@localhost ~]# 

### What did you expect to see?

[root@localhost ~]# ./ollama -v
Segmentation fault (core dumped)

### Steps to reproduce

[root@localhost ~]# ./ollama -v
Segmentation fault (core dumped)

### Are there any recent changes that introduced the issue?

[root@localhost ~]# ./ollama -v
Segmentation fault (core dumped)

### OS

Linux

### Architecture

amd64

### Ollama version

0.1.31

### GPU

Nvidia

### GPU info

[root@localhost ~]# nvidia-smi
Tue Apr  9 09:31:38 2024       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:06:00.0 Off |                    0 |
| N/A   34C    P0             27W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
|   1  Tesla T4                       Off |   00000000:86:00.0 Off |                    0 |
| N/A   34C    P0             26W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
                                                                                         
+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI        PID   Type   Process name                              GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|  No running processes found                                                             |
+-----------------------------------------------------------------------------------------+

### CPU

Intel

### Other software

AlmaLinux release 9.3 (Shamrock Pampas Cat)

**Comment by navr32** [comment]
What you Dmesg  errors return for the segfault ?

**Comment by dhiltgen** [comment]
Are you building from source?  Your example changed from `ollama -v` working to `./ollama -v` not working, so my interpretation is your local build crashes, but the official build we produce is working.

If that's correct, can you clarify what local compiler you have installed?  Did `go generate ./...` and `go build .` seem to work?
