### ISSUE TITLE
Support for all NAVI GPUs

### ISSUE THREAD

**Issue by swapduzoo** [ollama/ollama#3547]
When the support for all NAVI GPUs will come? and in particular the RX6700?

**Comment by dhiltgen** [comment]
You didn't mention if you're on Windows or Linux.  If you're on Linux, have you tried setting the override variable?  Your GPU is "close" to another supported type.  `HSA_OVERRIDE_GFX_VERSION="10.3.0"` may work.

See https://github.com/ollama/ollama/blob/main/docs/gpu.md#overrides

Unfortunately this only works on Linux at the moment though.

**Comment by ev0lister** [comment]
Is there a similar override for Windows? Using a RX6700 XT here.

**Comment by dhiltgen** [comment]
@ev0lister unfortunately there is not currently a mechanism to do this on windows.  That's tracked via #3107
