### ISSUE TITLE
ollama serve cannot detect GPU

### ISSUE THREAD

**Issue by g-makerr** [ollama/ollama#3550]
### What is the issue?

I run "ollama serve", while it reports that "no GPU detected" and ""[cudart] error looking up CUDART GPU memory: cudart device memory info lookup failure 2"". But no such problems four days ago.
![屏幕截图 2024-04-09 144347](https://github.com/ollama/ollama/assets/71173795/b9c853a7-e4be-42ec-b4b1-967b7bcdf219)

### What did you expect to see?

GPU detected & in use

### OS

Linux

### Architecture

amd64, x86

### Ollama version

0.1.30

### GPU

Nvidia

### GPU info

![屏幕截图 2024-04-09 164724](https://github.com/ollama/ollama/assets/71173795/fcb0ae91-bbd2-4de9-86d7-b1a45b103a47)

**Comment by pdevine** [comment]
Hey @g-makerr What kind of card is it?

**Comment by dhiltgen** [comment]
> But no such problems four days ago.

Was this running an older version of Ollama?  We've been adjusting our GPU discovery logic and recently switched from the nvidia management library to leverage the cuda runtime library.  The error code "2" maps to cudaErrorMemoryAllocation which isn't an expected error code for querying available memory according to the API docs, so I'm not sure exactly what's going wrong yet.

Running with `OLLAMA_DEBUG=1` might shed a little more light.  Also check dmesg for any errors from the driver on the host.  Is there anything else interesting/unusual about your configuration?

**Comment by g-makerr** [comment]
> Hey @g-makerr What kind of card is it?

NVIDIA RTX 3090. I have fixed this issue by updating the GPU Driver version.

**Comment by g-makerr** [comment]
> > But no such problems four days ago.
> 
> Was this running an older version of Ollama? 

It was also running the same version-- ollama 0.1.30. And thanks for your suggestions. I have fixed this issue by updating the  GPU Driver version.

**Comment by wjaxx** [comment]
which version you update can solve this probrem?

**Comment by g-makerr** [comment]
> which version you update can solve this probrem?

CUDA  Driver Version from 510.8 to 550.67

**Comment by komasoftware** [comment]
➜ ollama --version                    
ollama version is 0.1.32

➜ nvidia-smi -l 5
Tue Apr 30 17:19:13 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 545.23.08              Driver Version: 545.23.08    CUDA Version: 12.3     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce GTX 1070 Ti     On  | 00000000:01:00.0  On |                  N/A |
| 19%   53C    P0              44W / 180W |   1690MiB /  8192MiB |      1%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+


![Selection_957](https://github.com/ollama/ollama/assets/482152/d4565ed1-f6d6-4adf-a7b9-8e82b70320e2)

**Comment by dhiltgen** [comment]
@komasoftware according to the nvidia API docs, that error is:
```
    /**  
     * This indicates that requested CUDA device is unavailable at the current
     * time. Devices are often unavailable due to use of
     * ::CU_COMPUTEMODE_EXCLUSIVE_PROCESS or ::CU_COMPUTEMODE_PROHIBITED.
     */
    CUDA_ERROR_DEVICE_UNAVAILABLE            = 46,
```

So my interpretation is either some other app has grabbed the GPU exclusively, or there's a permission problem in your setup preventing Ollama from accessing the GPU.
