### ISSUE TITLE
temperature multiplied by 2

### ISSUE THREAD

**Issue by anasibang** [ollama/ollama#3551]
https://github.com/ollama/ollama/blob/1341ee1b56b11436a9a8d72f2733ef7ff436ba40/openai/openai.go#L178

Why did you multiply the temperature value by 2?

**Comment by jmorganca** [comment]
The temperature is multiplied by two since llama.cpp uses 0-2 and openai uses 0-1 - thanks for the issue!

**Comment by Fusseldieb** [comment]
This would be a prime example of where to put an inline comment
