### ISSUE TITLE
CodeGemma by Google

### ISSUE THREAD

**Issue by smortezah** [ollama/ollama#3556]
### What model would you like?

CodeGemma by Google has just been released:

https://huggingface.co/collections/google/codegemma-release-66152ac7b683e2667abdee11

**Comment by jmorganca** [comment]
Thanks for the issue! Here it is! https://ollama.com/library/codegemma

**Comment by fungiboletus** [comment]
Hi,

I see a lot of `<|file_separator|>` and similar sequences in the outputs. Is this something that should be fixed in the application consuming the outputs, or ollama?

```
$ ollama run codegemma:code
>>> int main()
 {.cpp
<|fim_prefix|>int main(){
int num1,num2,result;
num1=10;
num2=5;
result=num1+num2;
cout<<result;
return <|fim_suffix|><|fim_middle|>0;
}
<|file_separator|>

>>>
```

**Comment by metal3d** [comment]
> Hi,
> 
> I see a lot of `<|file_separator|>` and similar sequences in the outputs. Is this something that should be fixed in the application consuming the outputs, or ollama?
> 
> ```
> $ ollama run codegemma:code
> >>> int main()
>  {.cpp
> <|fim_prefix|>int main(){
> int num1,num2,result;
> num1=10;
> num2=5;
> result=num1+num2;
> cout<<result;
> return <|fim_suffix|><|fim_middle|>0;
> }
> <|file_separator|>
> 
> >>>
> ```

I've got exactly the same problem with llm-ls in neovim. Lot of bad tokens and I see erros when the model loads:

```
load: control-looking token:    107 '<end_of_turn>' was not control-type; this is probably a bug in the model. its type will be overridden
load: special_eos_id is not in special_eog_ids - the tokenizer config may be incorrect
...
print_info: FIM PRE token    = 67 '<|fim_prefix|>'
print_info: FIM SUF token    = 69 '<|fim_suffix|>'
print_info: FIM MID token    = 68 '<|fim_middle|>'
print_info: EOG token        = 1 '<eos>'
print_info: EOG token        = 107 '<end_of_turn>'
print_info: max token length = 93
```
