### ISSUE TITLE
ollama create does not support the use of labels and fails

### ISSUE THREAD

**Issue by alexconst** [ollama/ollama#3557]
### What is the issue?

When running `ollama create mymodel -f Modelfile` ollama will fail if the `FROM` directive includes a label. 
Example `FROM ./zephyr-7b-beta.Q5_K_M.gguf:7b-beta.Q5_K_M`

Depending if the path is absolute or relative it will print a different error:
Either
```
transferring model data 
pulling model 
pulling manifest 
Error: pull model manifest: 400
```
or
```
transferring model data 
pulling model 
pulling manifest 
Error: pull model manifest: file does not exist
```

If the label component in the filepath is removed then it works fine.

### What did you expect to see?

For ollama to import the model specified in the `Modelfile`

### Steps to reproduce

Create a Modelfile like

```
FROM ./zephyr-7b-beta.Q5_K_M.gguf:7b-beta.Q5_K_M
TEMPLATE """{{- if .System }}
<|system|>
{{ .System }}
</s>
{{- end }}
<|user|>
{{ .Prompt }}
</s>
<|assistant|>
"""
PARAMETER stop <|system|>
PARAMETER stop <|user|>
PARAMETER stop <|assistant|>
PARAMETER stop </s>
```

or

```
FROM /models/zephyr-7B-beta-GGUF/zephyr-7b-beta.Q5_K_M.gguf:7b-beta.Q5_K_M
TEMPLATE """{{- if .System }}
<|system|>
{{ .System }}
</s>
{{- end }}
<|user|>
{{ .Prompt }}
</s>
<|assistant|>
"""
PARAMETER stop <|system|>
PARAMETER stop <|user|>
PARAMETER stop <|assistant|>
PARAMETER stop </s>
```

### OS

Linux

### Architecture

amd64

### Platform

Docker

### Ollama version

0.1.30

**Comment by KungFuFurniture** [comment]
I am also having this issue.  Any ideas?

**Comment by Isaac-maker** [comment]
FROM ./zephyr-7b-beta.Q5_K_M.gguf:7b-beta.Q5_K_M
In my case it worked by removing the ". " in Linux. 
FROM  /zephyr-7b-beta.Q5_K_M.gguf:7b-beta.Q5_K_M
On Windows I still have the 400 problem.

**Comment by DNOSer** [comment]
> FROM ./zephyr-7b-beta.Q5_K_M.gguf:7b-beta.Q5_K_M
> 
> In my case it worked by removing the ". " in Linux.
> 
> `FROM /zephyr-7b-beta.Q5_K_M.gguf:7b-beta.Q5_K_M`
> 
> On Windows I still have the 400 problem.

it didnt work for me  where did you save the model?  looks like its saved in root ...?

**Comment by pdevine** [comment]
Hey guys, sorry about the slow response. The `FROM` line can take 3 different forms of input:
1. a model name;
2. a path to a GGUF file; or
3. a path to a directory containing safetensor files

For the model names just use `ollama ls` to get a list of models which are available to reference. For the GGUF file you just need to put in an absolute or relative path to the file. e.g. `./zephyr-7b-beta.Q5_K_M.gguf:7b-beta.Q5_K_M` would mean there would need to be a file called `./zephyr-7b-beta.Q5_K_M.gguf:7b-beta.Q5_K_M` in the directory where you're calling `ollama create`.

If you want to _create_ a model w/ that tag, you can make the FROM line:

`FROM ./zephyr-7b-beta.Q5_K_M.gguf`

and then when called create use: `ollama create zephyr-7b-beta:Q5_K_M`. When you want to run that model, just type `ollama run zephyr-7b-beta:Q5_K_M`. I'm sorry this is confusing; I am working on some new documentation for importing models which should (hopefully) give some better examples.

I'll go ahead and close the issue, but feel free to keep commenting.

**Comment by alexconst** [comment]
@pdevine 
Thanks for the clarification.

I haven't tested it yet but I guess you mean 
`ollama create zephyr-7b-beta:Q5_K_M -f /path/to/my/zephyr-7B-beta-GGUF/Modelfile`

IMO having a `LABEL` directive in the `Modelfile` would make things clean, explicit and less error prone.

**Comment by pdevine** [comment]
@alexconst what would the `LABEL` do in that case? I was thinking of adding `LABEL` to be able to tag additional metadata to the model which could be surfaced in the registry similar to how Docker works.

**Comment by alexconst** [comment]
@pdevine my idea was to allow for a `Modelfile` with the syntax:

```
FROM ./zephyr-7b-beta.Q5_K_M.gguf
LABEL 7b-beta.Q5_K_M
TEMPLATE """
...
"""
PARAMETER ...
```

Then you create the model `ollama create zephyr -f Modelfile` and it would get labeled accordingly. And `ollama list` would output  `zephyr:7b-beta-Q5_K_M     42c3337ace61     5.1 GB`
This would go in line with what's visible on https://ollama.com/library/zephyr/tags

> I was thinking of adding LABEL to be able to tag additional metadata to the model which could be surfaced in the registry similar to how Docker works.

Maybe we can have both?

Instead of `LABEL` call it `TAGS`? And have the `Modelfile` would look like
```
FROM ./zephyr-7b-beta.Q5_K_M.gguf
LABEL 7b-beta.Q5_K_M
TAGS foo bar
```

Or even all in one
```
FROM ./zephyr-7b-beta.Q5_K_M.gguf
TAGS 7b-beta.Q5_K_M foo bar
```
And in this case `ollama create` would do multiple tags. And `ollama list` would output:
```
zephyr:7b-beta-Q5_K_M     42c3337ace61     5.1 GB
zephyr:foo                42c3337ace61     5.1 GB
zephyr:bar                42c3337ace61     5.1 GB
```

Just a thought.

**Comment by pdevine** [comment]
@alexconst I think that would be confusing though given you can kinda already do that.

```
% ollama create zephyr:7b-beta-Q5_K_M # (you don't need to even specify the Modelfile if there is a file called `Modelfile`)
...
% ollama cp zephyr:7b-beta-Q5_K_M zephyr:foo
```
One nice quality of life thing though would be to allow you to do:
```
% ollama cp zephyr:7b-beta-Q5_K_M zephyr:foo zephyr:bar
```
I don't think that will work right now.
