### ISSUE TITLE
The blog needs an RSS feed

### ISSUE THREAD

**Issue by casidiablo** [ollama/ollama#3558]
### What are you trying to do?

Subscribe to the blog via RSS, like any sane person.

### How should we solve this?

Add an RSS feed to the blog, and visible links to it.

### What is the impact of not solving this?

One more cut to the slow death of our beloved web

### Anything else?

Thanks

**Comment by storopoli** [comment]
I would love an RSS feed!

**Comment by LorenDB** [comment]
dupe of #1669, but still a very important issue!

**Comment by casidiablo** [comment]
Duped of https://github.com/ollama/ollama/issues/1669

**Comment by garret** [comment]
I can see it was marked as completed, so what is the rss feed address?

**Comment by LorenDB** [comment]
@garret it was closed as a dupe of #1669. That issue is still open.
