### ISSUE TITLE
Could anyone tell me the purpose of "ollama-linux-amd64-rocm.tgz" in the released files?

### ISSUE THREAD

**Issue by airforce011** [ollama/ollama#3569]
### What are you trying to do?

I'm trying to run Ollama on Linux (Ubuntu 22.04) with ROCm, but I'm unable to use it even after following the installation instructions in the documentation. Do I need to use the "ollama-linux-amd64-rocm.tgz" file? However, I'm not sure how to use this file, and there are no instructions provided. Any help would be greatly appreciated!

**Comment by dhiltgen** [comment]
If you use our install script, this is handled automatically. `curl -fsSL https://ollama.com/install.sh | sh`

If you are installing it via some other means (manually, etc.) then this payload can be used to gain access to the minimal set of ROCm dependencies necessary to run Ollama.  You can also install ROCm from AMD directly if you prefer.
