### ISSUE TITLE
Support for AMD Radeon RX 570 series

### ISSUE THREAD

**Issue by Mr-Ples** [ollama/ollama#3572]
### What are you trying to do?

trying to use my AMD GPU to accelerate ollama output

### How should we solve this?

add Support for AMD Radeon RX 570 series

### What is the impact of not solving this?

currently im not using ollama that much because of it

### Anything else?

ollama is the best application ever hands down

**Comment by muzig** [comment]
please, support for AMD Radeon RX 5700

**Comment by navr32** [comment]
If you want you can with llamacpp in vulkan mode. I have test on an RX480 8G vram. but on ollama i haven't try to compile with forcing the vulkan mode of the llamacpp build integrated to ollama.

**Comment by dhiltgen** [comment]
Dup of #2503

**Comment by windblade89** [comment]
Can you guys point me in the right direction to get AMD RX 580 8GB to work with this?

**Comment by dhiltgen** [comment]
Oops, I referenced the wrong issue number - this is actually a dup of #2453
