### ISSUE TITLE
Making separate standalone version for UsbDrives

### ISSUE THREAD

**Issue by sonareparth7** [ollama/ollama#3573]
### What are you trying to do?

I recently installed Ollama on my Windows PC, by default it installs in c drive!
can you guys work on the standalone version of Ollama for the USB drive, so I can carry that USB anywhere and use it offline?

this thing with universalizing the AI, I have 512 GB of USB drive, but I cannot install it on my USB,

please this is the feature request from @sonareparth7! 

### How should we solve this?

...

### What is the impact of not solving this?

...

### Anything else?

before the installation, it should ask where to install
and it should also ask where to install those models!

let's universalize this project!

**Comment by sonareparth7** [comment]
No one cares!

**Comment by aiqbal77** [comment]
> ### What are you trying to do?
> I recently installed Ollama on my Windows PC, by default it installs in c drive! can you guys work on the standalone version of Ollama for the USB drive, so I can carry that USB anywhere and use it offline?
> 
> this thing with universalizing the AI, I have 512 GB of USB drive, but I cannot install it on my USB,
> 
> please this is the feature request from @sonareparth7!
> 
> ### How should we solve this?
> ...
> 
> ### What is the impact of not solving this?
> ...
> 
> ### Anything else?
> before the installation, it should ask where to install and it should also ask where to install those models!
> 
> let's universalize this project!

I'm hoping to do the same, did you hear any further or make progress on this?

**Comment by JCVI25** [comment]
chicos yo lo estoy intentando pronto lo subire a mi github
