### ISSUE TITLE
Error: listen tcp 127.0.0.1:11434: bind: Only one usage of each socket address (protocol/network address/port) is normally permitted.

### ISSUE THREAD

**Issue by Coder-Vishali** [ollama/ollama#3575]
### What is the issue?

When I execute ollama serve, I face the below issue:

Error: listen tcp 127.0.0.1:11434: bind: Only one usage of each socket address (protocol/network address/port) is normally permitted.

![image](https://github.com/ollama/ollama/assets/60731083/38b5ce1d-e039-4066-9fc0-7fa18b027722)

**
![image](https://github.com/ollama/ollama/assets/60731083/86c5173e-4a1b-4270-8c89-145f055b60dd)
**

Things which I have tired out:

1.  Restarted my machine
2.  Stop and start the ollama server
3.  Kill the port using: netstat -ano | findstr :<PORT>, taskkill /PID <PID> /F

### OS

Windows

### Architecture

x86

**Comment by muxixi727** [comment]
You can close ollama that is opened locally

**Comment by Leoleojames1** [comment]
In order to close the "local" ollama go to the bottom right of taskbar on windows click the up arrow, and quit ollama from the small tiny ollama app icon in the small arrow key menu. SO CONFUSING>

If you then go back and run ollama serve it should work now.

**Comment by cumtsd** [comment]
i've got the same problem without solved

**Comment by sshirey76** [comment]
On occasion, I will just run the powershell command :  Get-Process ollam* | Stop-Process  which kills any process that starts with ollam and it helps get rid of anything hung related to ollama client or the server running.  This will allow you then to run ollama serve which I prefer as I add it as part of my project init.

**Comment by Shoaib5136** [comment]
> You can close ollama that is opened locally

Thanks, dude I was also searching for this many hours.

**Comment by YuChenXin-ZJU** [comment]
Are there any other ports I can call?

**Comment by sshirey76** [comment]
@YuChenXin-ZJU If you mean can you set a port that is different to call then yes.. You would use:  setx OLLAMA_HOST "127.0.0.1:YOUR_DESIRED_PORT" /M  then just restart ollama.

**Comment by Geronimo2763** [comment]
Hello, I had this same issue a simple computer restart fixed this for me. Hope this helped :D

**Comment by EagleEye2010** [comment]
> In order to close the "local" ollama go to the bottom right of taskbar on windows click the up arrow, and quit ollama from the small tiny ollama app icon in the small arrow key menu. SO CONFUSING>
> 
> If you then go back and run ollama serve it should work now.

Saving my insanity.

**Comment by Deeksha0306** [comment]
ollama pull smollm
pulling manifest
pulling 6cafb858555d...   0% ▕                                                                                     ▏    0 B/990 MB
Error: max retries exceeded:
Please help me resolve this issue.

**Comment by hakeemsalman** [comment]
> In order to close the "local" ollama go to the bottom right of taskbar on windows click the up arrow, and quit ollama from the small tiny ollama app icon in the small arrow key menu. SO CONFUSING>
> 
> If you then go back and run ollama serve it should work now.

It's SOLVED, thank you so much.

**Comment by ESTAS-crypto** [comment]
I also have almost the same problem Error: listen tcp 127.0.0.1:11434: bind: Only one usage of each socket address (protocol/network address/port) is normally permitted.

**Comment by manav-a-thinkwik** [comment]
> In order to close the "local" ollama go to the bottom right of taskbar on windows click the up arrow, and quit ollama from the small tiny ollama app icon in the small arrow key menu. SO CONFUSING>
> 
> If you then go back and run ollama serve it should work now.

thanks brother

> In order to close the "local" ollama go to the bottom right of taskbar on windows click the up arrow, and quit ollama from the small tiny ollama app icon in the small arrow key menu. SO CONFUSING>
> 
> If you then go back and run ollama serve it should work now.

thanks brother

**Comment by Technorocker** [comment]
what about when there is no local ollama running and Im trying to setup ollama as a service but the only error i keep getting is :
`Error: listen tcp 127.0.0.1:11434: socket: The requested service provider could not be loaded or initialized.` in the logs
ive checked using netstat and nothing is using that port

**Comment by hemaranjani02** [comment]
just go to task manager and end the background running ollama, ollama.exe. It works

**Comment by heyu58** [comment]
> In order to close the "local" ollama go to the bottom right of taskbar on windows click the up arrow, and quit ollama from the small tiny ollama app icon in the small arrow key menu. SO CONFUSING>
> 
> If you then go back and run ollama serve it should work now.

Best answer for rookie just like me!!!

**Comment by darkamalu** [comment]
> > In order to close the "local" ollama go to the bottom right of taskbar on windows click the up arrow, and quit ollama from the small tiny ollama app icon in the small arrow key menu. SO CONFUSING>
> > If you then go back and run ollama serve it should work now.
> 
> It's SOLVED, thank you so much.

SO VERY MUCH
