### ISSUE TITLE
error when run command r plus

### ISSUE THREAD

**Issue by taozhiyuai** [ollama/ollama#3577]
### What is the issue?

import command r plus gguf successfully. but error when run it.
<img width="837" alt="截屏2024-04-10 21 14 08" src="https://github.com/ollama/ollama/assets/146583103/37fbd1d2-7b75-432b-be86-af2c31b414d7">

### OS

macOS

### Ollama version

ollama version is 0.1.31

### GPU

Apple

### CPU

Apple

**Comment by pdevine** [comment]
Let's cover this is #3576 . The changes are in `main` already and should be available in `0.1.32`.
