### ISSUE TITLE
codegemma models throwing weird outputs

### ISSUE THREAD

**Issue by m-aebrer** [ollama/ollama#3580]
Hi,

I see a lot of `<|file_separator|>` and similar sequences in the outputs. Is this something that should be fixed in the application consuming the outputs, or ollama?

```
$ ollama run codegemma:code
>>> int main()
 {.cpp
<|fim_prefix|>int main(){
int num1,num2,result;
num1=10;
num2=5;
result=num1+num2;
cout<<result;
return <|fim_suffix|><|fim_middle|>0;
}
<|file_separator|>

>>>
```

_Originally posted by @fungiboletus in https://github.com/ollama/ollama/issues/3556#issuecomment-2046727592_

Similarly, when using Continue with VSCode, I also see these file_separators being constantly suggested by the tab autocomplete. Not sure if it is fixed on the ollama side or on the continue side.

**Comment by jmorganca** [comment]
Hi there, sorry about that. It seems the `codegemma` model on ollama.com didn't have all the required stop words - that should be fixed now if you re-pull

**Comment by m-aebrer** [comment]
awesome thank you!
