### ISSUE TITLE
Models being saved to /home/myUser/.ollama instead of $OLLAMA_MODELS

### ISSUE THREAD

**Issue by vrdeeznuts** [ollama/ollama#3585]
### What is the issue?

I've followed the instructions at https://github.com/ollama/ollama/blob/main/docs/faq.md#where-are-models-stored on Linux to change the path where models get stored. However, the model storage path changed from /usr/share/ollama/.ollama/models in the initial install to ~/.ollama/models. The absolute path I want to save the models to is /data/models.

### What did you expect to see?

I expected to see the blobs/ and manifests/ directories moved to /data/models, not to ~/.ollama/models.

### Steps to reproduce

1. `sudo mkdir -p /data/models #new path to store models
`2. `sudo chown myUser:myUser /data/models
`3. `sudo systemctl edit ollama.service`
4. Enter `Environment="OLLAMA_MODELS=/data/models"
`5. Save and close systemd service file (saves to `/etc/systemd/system/ollama.service.d/override.conf`)
6. Ctrl+C in the terminal running `ollama serve`
7. `sudo systemctl daemon-reload`
8. `sudo systemctl restart ollama`
9. `ollama serve` in separate terminal
10. `ollama show stablelm2:latest #new models/ path is /home/myUser/.ollama/models`

### Are there any recent changes that introduced the issue?

N/A, I tested this out with a fresh install of Ollama using `curl -fsSL https://ollama.com/install.sh | sh`. 

### OS

Linux

### Ollama version

0.1.31

### GPU

Nvidia

### GPU info

NVIDIA RTX A6000 (48GB)

### Other software

N/A

**Comment by vrdeeznuts** [comment]
> feels like you had to do that because the service startup failed?
Hmm, looks like you are right! Not sure if it's a permissions issue or what, but `groups` shows that my user is in the `ollama` group...

![image](https://github.com/ollama/ollama/assets/105958445/4807e05f-3f8a-47b0-98ed-5a833b26635c)

**Comment by vrdeeznuts** [comment]
looks like it was a simple permissions issue with $OLLAMA_MODELS after all. The path was owned by root:root so I just needed to give it access to ollama:ollama and it started working.

Thank you.

**Comment by dims** [comment]
welcome!
