### ISSUE TITLE
there is Massive Text Embedding Benchmark (MTEB) Leaderboard，could u support those mod？

### ISSUE THREAD

**Issue by doriszhang2020** [ollama/ollama#3597]
### What model would you like?

![image](https://github.com/ollama/ollama/assets/104901283/1f59958f-cf01-4fda-a4c6-37d53de011f0)
![image](https://github.com/ollama/ollama/assets/104901283/08202971-6f82-4b15-ba37-1482ddea5f05)
https://huggingface.co/spaces/mteb/leaderboard

**Comment by jmorganca** [comment]
Hi there, Ollama supports quite a few of the popular Bert architecture models - support for more architectures is coming soon: https://ollama.com/search?q=embedding&p=1

If you'd like a specific model feel free to create a new "model request" issue with the name and link!
