### ISSUE TITLE
langchain embedding from remote server

### ISSUE THREAD

**Issue by Ana0112** [ollama/ollama#3613]
### What is the issue?

I am using this code [langchain](https://github.com/ollama/ollama/blob/main/docs/tutorials/langchainpy.md) to get embeddings. 

Code - 

```
loader = PyPDFDirectoryLoader("data")
data = loader.load()

from langchain.text_splitter import RecursiveCharacterTextSplitter

text_splitter=RecursiveCharacterTextSplitter(chunk_size=500, chunk_overlap=0)
all_splits = text_splitter.split_documents(data)

from langchain.embeddings import OllamaEmbeddings
from langchain.vectorstores import Chroma
oembed = OllamaEmbeddings(base_url="https://11aa-11-111-111-111.ngrok-free.app/:11434", model="nomic-embed-text")
```

Upto this, code is working fine.

The following line is throwing error :-
```
vectorstore = Chroma.from_documents(documents=all_splits, embedding=oembed)
```
`ValueError: Error raised by inference API HTTP code: 404, 404 page not found`

I want to use these embeddings for RAG, with groq

```
rag_template = """Answer the question based only on the following context:
{context}
Question: {question}
"""
rag_prompt = ChatPromptTemplate.from_template(rag_template)
rag_chain = (
    {"context": retriever, "question": RunnablePassthrough()}
    | rag_prompt
    | llm
    | StrOutputParser()
)
```

I am able to generate collection using chromaDB standalone (i.e. not using langchain), using this code [embedding-model](https://ollama.com/blog/embedding-models)
but then I don't know how to use the generated embeddings with groq llm for RAG. 

### What did you expect to see?

chroma db should have generated the vectorstore

### OS

Linux

**Comment by andrewnguonly** [comment]
There might be a bug in the `base_url`. The port number `:11434` is after a slash `/`, so the port isn't actually specified; it's interpreted as a path (hence `404` page not found error).

Try removing the slash `/`: `ngrok-free.app:11434`

**Comment by Ana0112** [comment]
ok, thanks for your response.

I tried without the slash, but still getting the error

```
oembed = OllamaEmbeddings(base_url="https://xxxx-xx-xxx.ngrok-free.app:11434", model="nomic-embed-text")
vectorstore = Chroma.from_documents(documents=all_splits, embedding=oembed)

```

ValueError: Error raised by inference endpoint: HTTPSConnectionPool(host='xxx-xx-xxx.ngrok-free.app', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fcc71d09c30>: Failed to establish a new connection: [Errno 111] Connection refused'))

**Comment by andrewnguonly** [comment]
@Ana0112, take a look at [this comment](https://github.com/ollama/ollama/issues/2132#issuecomment-1904515289) and the discussion in the issue. You may need to set the `OLLAMA_HOST` environment variable appropriately.

**Comment by Ana0112** [comment]
I am doing

```
os.environ["OLLAMA_HOST"]= "https://xx.ngrok-free.app"
```
which is giving the above error.

I couldn't understand what should be the public ip in my case to set - `"OLLAMA_ORIGINS=http://public_ip:11434"`

**Comment by jmorganca** [comment]
Hi @Ana0112 for using Ollama with ngrok see https://github.com/ollama/ollama/blob/main/docs/faq.md#how-can-i-use-ollama-with-ngrok

Hope this helps!
