### ISSUE TITLE
How to get (log) conditional probability of next word given a context in Ollama?

### ISSUE THREAD

**Issue by HeningWang** [ollama/ollama#362]
Hi,

I'm new to Ollama. I'd like to get (log) conditional probability of next word given a context like with other LLMs. I cannot find theis usage in the turorial or API. I'm thankful if anybody can help me with that. Sorry, if this question is too basic or not appropriate for an issue.

Best

**Comment by charles-dyfis-net** [comment]
I think this may be more of a feature request than a question -- looking at the API, I don't see any option to either do this, _or_ to adjust weights for individual tokens.

As these features would both be necessary to use ollama as a [LMTP](https://github.com/eth-sri/lmql/blob/main/src/lmql/models/lmtp/README.md) backend (a transport protocol intended to be suitable for tools that constrain a LLM's output to only consider outputs that match provided rules/patterns), there's certainly value to them.

**Comment by James4Ever0** [comment]
I think maybe I want some guided generation, like I have probability of every generation step, and I can choose the token I want instead of by max prob.

**Comment by jmorganca** [comment]
Closing for https://github.com/ollama/ollama/issues/2415 – thanks!
