### ISSUE TITLE
Mixtral 8x22b - v0.1

### ISSUE THREAD

**Issue by igorschlum** [ollama/ollama#3620]
### What model would you like?

BTW Mixtral released a new model: https://huggingface.co/mistral-community/Mixtral-8x22B-v0.1

The Mixtral-8x22B Large Language Model (LLM) is a pretrained generative Sparse Mixture of Experts.

**Comment by pdevine** [comment]
You can find the 8x22B model in the [registry](https://ollama.com/library/mixtral/tags). :-D

`ollama run mixtral:8x22b`
