### ISSUE TITLE
[v0.1.32-pre for Windows] Can't use ollama run with OLLAMA_MODELS env set

### ISSUE THREAD

**Issue by mann1x** [ollama/ollama#3624]
### What is the issue?

ollama run can't be used anymore with OLLAMA_MODELS environment set
instead:
`Error: OLLAMA_MODELS must only be set for 'ollama serve'`

### What did you expect to see?

The ollama chat prompt

### Steps to reproduce

set OLLAMA_MODELS system environment variable
type ollama run anymodel

### Are there any recent changes that introduced the issue?

The latest prerelease

### OS

Windows

### Architecture

amd64

### Ollama version

0.1.32-pre

### CPU

AMD

**Comment by MoonRide303** [comment]
Same problem for me - only change was updating from v0.1.31 to 0.1.32-rc1, and now `ollama run [model_name]` results with `Error: OLLAMA_MODELS must only be set for 'ollama serve'` (for any model). Windows, too.

**Comment by AjmalShajahan** [comment]
It was added in #3470

**Comment by MoonRide303** [comment]
@AjmalShajahan but OLLAMA_MODELS points all the time to the path where I keep all my Ollama model files. I didn't change anything specifically for launching 0.1.32-rc1. 0.1.31 works fine, and 0.1.32-rc1 - just doesn't.

**Comment by MoonRide303** [comment]
@jmorganca @bmizerany Could you guys re-think that change (https://github.com/ollama/ollama/pull/3470)? I don't get it how that "helpful error message" solves anything - it just breaks essential functionality like "ollama run" for me.

**Comment by mann1x** [comment]
> OLLAMA_MODELS is set to "" for current session, when downloading/updating models in same session you'll need to set it to the path where the models are kept.

Yes it works of course but I run ollama on Windows, the OLLAMA_MODELS is set as system env variable. Can't be otherwise.

I don't really understand what was the problem with `run` on that PR but it breaks completely the client functionality while it looks the aim was to only show a diagnostic message.
Better to find a different solution, will try to understand what was the original issue.

If such a diagnostic message is needed maybe it's better to have it print out only when `OLLAMA_DEBUG` is set.

**Comment by mann1x** [comment]
I had a look at the code but I couldn't see any reason why `run` should care about the `OLLAMA_MODELS` env...

**Comment by MoonRide303** [comment]
@mann1x run uses it to know the path where model files are stored - at least that how it works in 0.1.31.

**Comment by mann1x** [comment]
@MoonRide303 

`run` launches the client which only need `OLLAMA_HOST`; it's only connecting to the server, it's not interacting directly with the models.
Otherwise it wouldn't need it unset but set.
There must be another reason but I can't see it.

**Comment by MoonRide303** [comment]
@mann1x I just use "ollama run" like "main" from llama.cpp. I get that it might be launching server in the background, but I don't set OLLAMA_HOST or launch server explicitely.

**Comment by mann1x** [comment]
@MoonRide303 Yes that's right; `OLLAMA_HOST` doesn't need to be set, it defaults to localhost, and the server is launched in the background if it's not started already

**Comment by jmorganca** [comment]
Hi folks, this should be fixed now, and sorry for the issue!

**Comment by mann1x** [comment]
@jmorganca Thanks, we were just confused!
