### ISSUE TITLE
can't be installed on ubuntu runing in a podman container.

### ISSUE THREAD

**Issue by userforsource** [ollama/ollama#3625]
### What is the issue?

I spin up a container of ubuntu using podman but i can't install ollama that curl command does not work.

### OS

Linux

### Architecture

amd64

### Platform

Docker

### GPU

AMD

### CPU

AMD

**Comment by dhiltgen** [comment]
You should try out our official container image which should come with everything necessary to run on CPU or GPU.

See https://hub.docker.com/r/ollama/ollama

**Comment by userforsource** [comment]
Yes this is running. Using podman. Podman and docker are same almost.

**Comment by dhiltgen** [comment]
Happy to hear our official container image is working for you.

**Comment by ericcurtin** [comment]
For the record I made this simpler:

https://github.com/ericcurtin/podman-ollama

**Comment by userforsource** [comment]
> For the record I made this simpler:
> 
> https://github.com/ericcurtin/podman-ollama

I will try this. Thanks.

**Comment by ericcurtin** [comment]
@userforsource if there is any issue, just let me know
