### ISSUE TITLE
Support bce-embedding-base 

### ISSUE THREAD

**Issue by wwjCMP** [ollama/ollama#3630]
### What model would you like?

bce-embedding-base
https://huggingface.co/maidalun1020/bce-embedding-base_v1

**Comment by thiner** [comment]
This is a must have feature for building RAG system. You may check Jina reranker API for reference.  https://jina.ai/reranker/#apiform

**Comment by jmorganca** [comment]
Merging with https://github.com/ollama/ollama/issues/3747
