### ISSUE TITLE
StableLM-2 12B

### ISSUE THREAD

**Issue by coder543** [ollama/ollama#3632]
### What model would you like?

This model looks promising: https://stability.ai/news/introducing-stable-lm-2-12b

**Comment by mann1x** [comment]
will quantize it for sure but it's only 4k context for now, they will release later a new version
if you see it on HF and I miss it, ping me here please

**Comment by MoonRide303** [comment]
Converted and quantized to Q6_K using convert-hf-to-gguf.py and quantize from llama.cpp b2690 - but when trying to run using ollama run (0.1.32) I get:
```
Error: llama runner process no longer running: 3221226505
```

The same GGUF file can be launched using llama.cpp.

**Comment by jmorganca** [comment]
Available here: https://ollama.com/library/stablelm2:12b

Thanks for the issue!
