### ISSUE TITLE
Error: exception error loading model architecture: unknown model architecture: ''

### ISSUE THREAD

**Issue by anubissbe** [ollama/ollama#3638]
### What is the issue?

The modelfile cannot get loaded after the model creation

### What did you expect to see?

A working chat interface

### Steps to reproduce

drwho@jarvis:/opt/models/aya-101-GGUF$ ollama create aya -f Modelfile 
transferring model data 
creating model layer 
creating system layer 
creating parameters layer 
creating config layer 
using already created layer sha256:dcf5054951605dfee65396ef3c625c09539c5f605256989bf9e605e9727a00d8 
writing layer sha256:d8ba2f9a17b3bbdeb5690efaa409b3fcb0b56296a777c7a69c78aa33bbddf182 
writing layer sha256:d8f76500493b5c8d3ca7146cefe969f5a3a7ed1a36dffdfb06feb49089d19d7c 
writing manifest 
success 
drwho@jarvis:/opt/models/aya-101-GGUF$ ollama run aya
Error: exception error loading model architecture: unknown model architecture: ''
drwho@jarvis:/opt/models/aya-101-GGUF$ cat Modelfile 
FROM ./aya-101.Q6_K.gguf
# set the temperature to 1 [higher is more creative, lower is more coherent]
PARAMETER temperature 1

# set the system message
SYSTEM ""
drwho@jarvis:/opt/models/aya-101-GGUF$ ls -la
total 110839576
drwxrwxr-x 3 drwho drwho        4096 Apr 14 14:17 .
drwxr-xr-x 4 drwho users        4096 Apr 14 12:37 ..
-rw-rw-r-- 1 drwho drwho  4241619232 Apr 14 13:25 aya-101.Q2_K.gguf
-rw-rw-r-- 1 drwho drwho  5553862944 Apr 14 13:24 aya-101.Q3_K.gguf
-rw-rw-r-- 1 drwho drwho  7269859872 Apr 14 13:26 aya-101.Q4_0.gguf
-rw-rw-r-- 1 drwho drwho  8077394720 Apr 14 13:04 aya-101.Q4_1.gguf
-rw-rw-r-- 1 drwho drwho  7269873952 Apr 14 13:26 aya-101.Q4_K.gguf
-rw-rw-r-- 1 drwho drwho  8884929568 Apr 14 13:07 aya-101.Q5_0.gguf
-rw-rw-r-- 1 drwho drwho  9692464416 Apr 14 13:13 aya-101.Q5_1.gguf
-rw-rw-r-- 1 drwho drwho  8884943136 Apr 14 13:07 aya-101.Q5_K.gguf
-rw-rw-r-- 1 drwho drwho 10600954144 Apr 14 13:13 aya-101.Q6_K.gguf
-rw-rw-r-- 1 drwho drwho 13730138656 Apr 14 13:25 aya-101.Q8_0.gguf
-rw-rw-r-- 1 drwho drwho 14537673504 Apr 14 13:24 aya-101.Q8_1.gguf
-rw-rw-r-- 1 drwho drwho 14739568928 Apr 14 13:25 aya-101.Q8_K.gguf
-rw-rw-r-- 1 drwho drwho         761 Apr 14 14:07 config.json
drwxrwxr-x 9 drwho drwho        4096 Apr 14 13:37 .git
-rw-rw-r-- 1 drwho drwho        2218 Apr 14 12:37 .gitattributes
-rw-rw-r-- 1 drwho drwho         162 Apr 14 14:17 Modelfile
-rw-rw-r-- 1 drwho drwho        2270 Apr 14 12:37 README.md
-rw-rw-r-- 1 drwho drwho         833 Apr 14 12:37 tokenizer_config.json
-rw-rw-r-- 1 drwho drwho    16330562 Apr 14 13:13 tokenizer.json

### OS

Linux

### Architecture

amd64

### GPU

Nvidia

### GPU info

V100-16GB

### CPU

Intel

### Other software

Xeon-Gold

**Comment by jmorganca** [comment]
Hi there, Ollama doesn't support the T5 architecture yet - however feel free to create a model request issue so we can work on supporting it :)
