### ISSUE TITLE
how to change the max input token length when I run ‘’ollama run gemma:7b-instruct-v1.1-fp16‘’

### ISSUE THREAD

**Issue by dh12306** [ollama/ollama#3643]
the default input token lens is 2048 ？  how can I change it because the gemma can support more input tokens

**Comment by dims** [comment]
tip from @jmorganca here - https://github.com/ollama/ollama/issues/3644#issuecomment-2057646417

**Comment by jmorganca** [comment]
Hi all, to change the max token length you can use `/set parameter num_ctx <context size>` e.g. `4096`, `8192` or more

Hope this helps!

**Comment by 0sengseng0** [comment]
> Hi all, to change the max token length you can use `/set parameter num_ctx <context size>` e.g. `4096`, `8192` or more大家好，要更改最大令牌长度，您可以使用`/set parameter num_ctx <context size>`例如`4096`，`8192`或更多
> 
> Hope this helps! 希望这会有所帮助！

As I increased the token size, it seemed like every time I asked a question, the model would restart before answering。  /set parameter num_ctx 40960

**Comment by BoyuanGao** [comment]
> Hi all, to change the max token length you can use `/set parameter num_ctx <context size>` e.g. `4096`, `8192` or more
> 
> Hope this helps!

Hi @jmorganca  Would you please tell me how to execute this on windows?

**Comment by vish01** [comment]
If you're running this using the Ollama JS package, you can pass it in the `options` property:
```
await ollama.generate({
  model: "llama3.1",
  prompt: finalPrompt,
  stream: true,
  options: {
    num_ctx: xx
  },
})
```

**Comment by vitustockholm** [comment]
> > Hi all, to change the max token length you can use `/set parameter num_ctx <context size>` e.g. `4096`, `8192` or more
> > Hope this helps!
> 
> Hi @jmorganca Would you please tell me how to execute this on windows?

 use webui to change this parameter

**Comment by PasaOpasen** [comment]
is there a way to globally limit this value from environment ?
