### ISSUE TITLE
Is the model's PROMPT maximum number of tokens determined by the inference tool?

### ISSUE THREAD

**Issue by 17Reset** [ollama/ollama#3644]
When I use ollama to reason about my Smuag-72B's model, there is no output when the input prompt has 150tokens, but the output is normal when scaled down to about 100.

**Comment by jmorganca** [comment]
Hi there, the context window defaults to 2048 and can be overridden with the `num_ctx` option: https://github.com/ollama/ollama/blob/main/docs/api.md#generate-request-with-options

**Comment by 17Reset** [comment]
Again it doesn't work, even if I boost the num_ctx number it still doesn't answer anything, when the prompt is too long there is no output, is this model related?

**Comment by realquatro** [comment]
> Hi there, the context window defaults to 2048 and can be overridden with the `num_ctx` option: https://github.com/ollama/ollama/blob/main/docs/api.md#generate-request-with-options

It does work on http://localhost:11434/api/generate 。
But how can I increase the context window when I use http://localhost:11434/v1/chat/completions ?
