### ISSUE TITLE
verifying github.com/google/flatbuffers@v1.12.0: checksum mismatch

### ISSUE THREAD

**Issue by juhp** [ollama/ollama#3646]
### What is the issue?

A clean checkout and build of ollama fails like google/flatbuffers#6466

### What did you expect to see?

No checksum error

The easiest solution is bump the flatbuffers dependency to v1.12.1 which works around this upstream issue.

### Steps to reproduce

```shellsession
[~/go]$ git clone -q https://github.com/ollama/ollama.git
[~/go]$ cd ollama
[~/go/ollama:main]$ go generate ./...
go: downloading github.com/google/uuid v1.0.0
verifying github.com/google/flatbuffers@v1.12.0: checksum mismatch
	downloaded: h1:N8EguYFm2wwdpoNcpchQY0tPs85vOJkboFb2dPxmixo=
	go.sum:     h1:/PtAHvnBY4Kqnx/xCQ3OIV9uYcSFGScBsWI3Oogeh6w=

SECURITY ERROR
This download does NOT match an earlier download recorded in go.sum.
The bits may have been replaced on the origin server, or an attacker may
have intercepted the download attempt.

For more information, see 'go help module-auth'.
```

### OS

Linux

### Architecture

amd64

**Comment by jmorganca** [comment]
Hi @juhp I can't seem to reproduce this after trying on many different systems. Is it something with your local go mod cache or perhaps version of Go? Will close for now but do let me know if not

**Comment by juhp** [comment]
I commented in the PR

**Comment by chenpei2** [comment]
The same checksum mismatch problem and solved with this PR: https://github.com/ollama/ollama/pull/3649
