### ISSUE TITLE
Ollama reverts to CPU on a100 docker. "error looking up CUDA GPU memory: device memory info lookup failure 0: 4

### ISSUE THREAD

**Issue by Yaffa16** [ollama/ollama#3647]
### What is the issue?

time=2024-04-15T09:17:48.609Z level=INFO source=gpu.go:82 msg="Nvidia GPU detected"
time=2024-04-15T09:17:48.609Z level=INFO source=cpu_common.go:11 msg="CPU has AVX2"
time=2024-04-15T09:17:48.617Z level=INFO source=gpu.go:109 msg="error looking up CUDA GPU memory: device memory info lookup failure 0: 4"
time=2024-04-15T09:17:48.617Z level=INFO source=routes.go:1133 msg="no GPU detected"
time=2024-04-15T09:17:49.031Z level=INFO source=cpu_common.go:11 msg="CPU has AVX2"
time=2024-04-15T09:17:49.031Z level=INFO source=gpu.go:109 msg="error looking up CUDA GPU memory: device memory info lookup failure 0: 4"
time=2024-04-15T09:17:49.031Z level=INFO source=cpu_common.go:11 msg="CPU has AVX2"
time=2024-04-15T09:17:49.031Z level=INFO source=gpu.go:109 msg="error looking up CUDA GPU memory: device memory info lookup failure 0: 4"
time=2024-04-15T09:17:49.031Z level=INFO source=llm.go:85 msg="GPU not available, falling back to CPU"
time=2024-04-15T09:17:49.034Z level=INFO source=dyn_ext_server.go:90 msg="Loading Dynamic llm server: /tmp/ollama3883625654/runners/cpu_avx2/libext_server.so"
time=2024-04-15T09:17:49.034Z level=INFO source=dyn_ext_server.go:150 msg="Initializing llama server"

+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA A100-PCIE-40GB          Off |   00000000:01:00.0 Off |                   On |
| N/A   38C    P0             32W /  250W |      90MiB /  40960MiB |     N/A      Default |
|                                         |                        |              Enabled |
+-----------------------------------------+------------------------+----------------------+
|   1  NVIDIA A100-PCIE-40GB          Off |   00000000:43:00.0 Off |                   On |
| N/A   32C    P0             35W /  250W |   17843MiB /  40960MiB |     N/A      Default |
|                                         |                        |              Enabled |
+-----------------------------------------+------------------------+----------------------+

+-----------------------------------------------------------------------------------------+
| MIG devices:                                                                            |
+------------------+----------------------------------+-----------+-----------------------+
| GPU  GI  CI  MIG |                     Memory-Usage |        Vol|      Shared           |
|      ID  ID  Dev |                       BAR1-Usage | SM     Unc| CE ENC DEC OFA JPG    |
|                  |                                  |        ECC|                       |
|==================+==================================+===========+=======================|
|  0    1   0   0  |              53MiB / 19968MiB    | 56      0 |  4   0    2    0    0 |
|                  |                 1MiB / 32767MiB  |           |                       |
+------------------+----------------------------------+-----------+-----------------------+
|  0    5   0   1  |              25MiB /  9856MiB    | 28      0 |  2   0    1    0    0 |
|                  |                 0MiB / 16383MiB  |           |                       |
+------------------+----------------------------------+-----------+-----------------------+
|  0   13   0   2  |              12MiB /  4864MiB    | 14      0 |  1   0    0    0    0 |
|                  |                 0MiB /  8191MiB  |           |                       |
+------------------+----------------------------------+-----------+-----------------------+
|  1    0   0   0  |           17843MiB / 40326MiB    | 98      0 |  7   0    5    1    1 |
|                  |                 7MiB / 65536MiB  |           |                       |
+------------------+----------------------------------+-----------+-----------------------+
                                                                                         
+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI        PID   Type   Process name                              GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|    1    0    0       4197      C   /opt/conda/bin/python                        5180MiB |
|    1    0    0       4201      C   /opt/conda/bin/python                       12644MiB |
+-----------------------------------------------------------------------------------------+
$ 

### OS

Linux

### Ollama version

latest

### GPU

Nvidia

### GPU info

a100

**Comment by dhiltgen** [comment]
If adjusting permissions doesn't resolve the problem, please let us know and I'll reopen the issue.

**Comment by UmutAlihan** [comment]
Hi, I am currently experiencing this issue on a prod openshift (k8s) environment, deployed via official dockerhub image.

We know that permissions to access gpu's ok by checking nvidia-smi command with same user.

Our Ollama version is 0.3.1.


Is there any output you want me to share, please let me know. Any help is appreciated. Cheers

**Comment by dhiltgen** [comment]
@UmutAlihan your scenario looks different than this issue.  Please open a new issue and include a more complete server log.  The partial logs you included don't really make sense (if we didn't discover the GPU we shouldn't have loaded 33/33 layers on the GPU, so there's more going on here in other log lines that are important to understand.)
