### ISSUE TITLE
Default command R Modelfile template does not respect specification

### ISSUE THREAD

**Issue by GiovanniGatti** [ollama/ollama#3650]
### What is the issue?

After reading the documentation of [Command R](https://docs.cohere.com/docs/prompting-command-r#components-of-a-structured-prompt) I found it strange that the (mandatory) `<BOS_TOKEN>` wans't specified in the default Modelfile.template [here](https://ollama.com/library/command-r:latest/blobs/42499e38acdf).

I'm not sure where is the best place to report this sort of issue.

**Comment by jukofyork** [comment]
The wrapped llama.cpp server adds the `<BOS>` token it sees in the GGUF file right at the start:

https://github.com/ggerganov/llama.cpp/tree/master/examples/server

> A BOS token is inserted at the start, if all of the following conditions are true:
> 
> ```
> - The prompt is a string or an array with the first element given as a string
> - The model's `tokenizer.ggml.add_bos_token` metadata is `true`
> - The system prompt is empty
> ```

From the GGUF:

```
llm_load_print_meta: BOS token        = 5 '<BOS_TOKEN>'
```

But it won't add it to following prompts if that is needed (just about to read the prompt template in detail myself now).

**Comment by jukofyork** [comment]
Probably the bigger problem is the default Ollama prompt is adding `<|END_OF_TURN_TOKEN|>` after the response, when it too is defined in the GUUF:

```
llm_load_print_meta: EOS token        = 255001 '<|END_OF_TURN_TOKEN|>'
```

whereas this (for all other models) should get added automatically... Sadly Ollama is so opaque compared to llama.cpp's server; I don't know if it will add this or not... :confused: We really need some clear way to debug this.

---

From reading the specs, using `command-r` in 'Chat History' mode should use this template:

```
TEMPLATE """{{if .System}}<|START_OF_TURN_TOKEN|><|SYSTEM_TOKEN|>{{.System}}<|END_OF_TURN_TOKEN|>{{end}}<|START_OF_TURN_TOKEN|><|USER_TOKEN|>{{.Prompt}}<|END_OF_TURN_TOKEN|><|START_OF_TURN_TOKEN|><|CHATBOT_TOKEN|>{{.Response}}"""
```

and add the `<|END_OF_TURN_TOKEN|>` back on itself.

**Comment by jukofyork** [comment]
Yeah, that seems to be the correct template. I just tested it with 20+ back and forth conversation and it was completely coherent.

This model is horrible at coding and writes pretty bad 1-shot stories, but oh boy can it self-critique and refine... Hugely impressed now! :open_mouth:

**Comment by jmorganca** [comment]
Will merge this with https://github.com/ollama/ollama/issues/1977
