### ISSUE TITLE
Ollama's API Confusion

### ISSUE THREAD

**Issue by 17Reset** [ollama/ollama#3666]
I started two ports in my server as ollama's api service ports, 8080 and 8081, 8080 as my LLM-api, 8081 as my Embedding-api, but when I add a model to 8080, I can actually see the model on port 8080 by using the following command, but the following command It should see the model for port 8081:
 curl http://192.168.18.165:8081/api/tags

**Comment by dims** [comment]
Are you using different `OLLAMA_MODELS` directory for each api service?

https://github.com/ollama/ollama/blob/main/docs/faq.md#where-are-models-stored

**Comment by pdevine** [comment]
This is the expected behaviour. You can use the `OLLAMA_MODELS` env variable as @dims mentioned to change the location.

**Comment by 17Reset** [comment]
Thanks, I was the one who didn't read the documentation carefully.
