### ISSUE TITLE
wizardlm2:8x22b-q4_0  is failing to generate on M3 max

### ISSUE THREAD

**Issue by xansrnitu** [ollama/ollama#3668]
### What is the issue?

I am trying to run wizardlm2:8x22b-q4_0  on M3 max machine. However, it is not generating meaningful token to the given prompt.

<img width="520" alt="Screenshot 2024-04-16 at 11 35 33 AM" src="https://github.com/ollama/ollama/assets/63858582/2ceeaff6-dfe2-4c8b-b63a-a33ac9ecb1d2">

ollama version is 0.1.32

### OS

macOS

### Architecture

arm64

### Ollama version

0.1.32

### GPU

Apple

### GPU info

M3 Max 128GB

### CPU

Apple

**Comment by adrienbrault** [comment]
Hey, same on an M1 Max 64GB, with:
- `dbrx:132b-instruct-q2_K`
- `wizardlm2:8x22b-q2_K`
- `mixtral:8x22b-text-v0.1-q2_K`

Note that `command-r-plus:104b-q2_K` seems to work fine.

```console
$ ollama --version
ollama version is 0.1.32

$ # NOT OK

$ ollama run mixtral:8x22b-text-v0.1-q2_K 'What is Symfony UX?'
        "
$

$ ollama run wizardlm2:8x22b-q2_K 'What is Symfony UX?'
!$▅	 $▅▅#


▅"#$
 "# #

$ ollama run dbrx:132b-instruct-q2_K 'What is Symfony UX?'
You are using a chatbot for your responses, which I recommend if you want to improve the. You should be ensuring
that all of this information about yourself has been provided in response by always referring back to it
directly and avoiding talking or writing too much.
You should not include any personal experiences as examples within its prompt. What is Symfony UX?
If you are using a chatbot for your responses, which I recommend if you want to improve it.
.
What is Symfony UX? If you have been provided in response by always referring back to IT directly and avoiding
talking or writing too much.<

What is Symfony UX? If you have not used the's prompt to respond appropriately. What is Symfony UX? If you are
using a chatbot for your responses, which I^C

$ # OK

$ ollama run command-r-plus:104b-q2_K 'What is Symfony UX?'
Symfony UX (User Experience) is a set of JavaScript and CSS components that can be used in^C

$ ollama run wizardlm2:7b-q2_K 'What is Symfony UX?'
Symfony UX, formerly known as "FriendlyBundle" or "Symfony UX Beta," is an open-source project that provides a
set of components for building modern web applications using the Symfony framework. It's a collection of
reusable and modular front-end components built with React.js, a popular JavaScript library for building user
interfaces.^C
```

**Comment by thinkverse** [comment]
I saw a [tweet](https://twitter.com/lucataco93/status/1780071590916485323) from @lucataco, they got that model to run on their M3 Max. They may have useful insight for getting it to run. 👍

**Comment by xansrnitu** [comment]
@lucataco I am using [v0.1.32] only.  
Have you done any specific config/option?

**Comment by xansrnitu** [comment]
@lucataco I reinstalled and restarted my machine. 
And that has done the wonder! 
Thanks everyone for chiming in.
I am closing the issue as not a bug.
