### ISSUE TITLE
Ollama Reports 0 Prompt Tokens When Using Llava

### ISSUE THREAD

**Issue by chigkim** [ollama/ollama#3671]
### What is the issue?

When asking Llava a question with image via api, Ollama returns a wrong number of prompt tokens. It reports as 0.
It's llama.cpp issue, and the pr below fixes it.
https://github.com/ggerganov/llama.cpp/pull/5896

### What did you expect to see?

It should report the right number of prompt tokens including image.

### Steps to reproduce

Ask Llava with an image through chat api.

### Ollama version

https://github.com/ollama/ollama/commit/f335722275d8184836d1b777f356fa7b0a012ede

### GPU

Apple

### GPU info

m3-max

### CPU

Apple

**Comment by dhiltgen** [comment]
Fixed in the new Go server in 0.4.0 RC

https://github.com/ollama/ollama/releases
