### ISSUE TITLE
Getting error while using ollama run on mac

### ISSUE THREAD

**Issue by swetavsavarn02** [ollama/ollama#3675]
### What is the issue?

Getting error while doing ollama run on mac on every model , Stating Error: Head "https://dd20bb891979d25aebc8bec07b2b3bbc.r2.cloudflarestorage.com/ollama/docker/registry/v2/blobs/sha256/26/2609048d349e7c70196401be59bea7eb89a968d4642e409b0e798b34403b96c8/data?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=66040c77ac1b787c3af820529859349a%!F(MISSING)20240416%!F(MISSING)auto%!F(MISSING)s3%!F(MISSING)aws4_request&X-Amz-Date=20240416T164135Z&X-Amz-Expires=1200&X-Amz-SignedHeaders=host&X-Amz-Signature=98eed7690305ee8731cb04e894c1d549a8d9988e3c68091011ff61e67017752b": dial tcp: lookup dd20bb891979d25aebc8bec07b2b3bbc.r2.cloudflarestorage.com: no such host

<img width="1440" alt="Screenshot 2024-04-16 at 10 13 49 PM" src="https://github.com/ollama/ollama/assets/166374157/4e58dc64-1b6a-4331-8def-382a47d1a4e4">

### OS

macOS

### Architecture

arm64

**Comment by pdevine** [comment]
Can you resolve any hosts? Looks like you're having network issues.

**Comment by mrdjohnson** [comment]
I could be wrong, but I think you need to do either `ollama serve` and access it through the API

Or `ollama run MODEL_NAME` and then it'll run a specific model. 

The error even says you called it with 0 arguments but it expected 1

**Comment by swetavsavarn02** [comment]
> Can you resolve any hosts? Looks like you're having network issues.

I have tried with different networks but still getting the same error

**Comment by swetavsavarn02** [comment]
> I could be wrong, but I think you need to do either `ollama serve` and access it through the API
> 
> Or `ollama run MODEL_NAME` and then it'll run a specific model.
> 
> The error even says you called it with 0 arguments but it expected 1

@mrdjohnson I am sorry , but i think you are talking about first command that i have entered . So yes it was my mistake , but as you can see that the second and third command in which i have mentioned the model name with ollama run . I am getting error on that

**Comment by BhammarArjun** [comment]
I am also getting the same error in MacOs. Unable to pull models. 

(base) arjun@arjuns-MacBook-Pro ~ % ollama pull gemma
pulling manifest 
Error: Head "https://dd20bb891979d25aebc8bec07b2b3bbc.r2.cloudflarestorage.com/ollama/docker/registry/v2/blobs/sha256/ef/ef311de6af9db043d51ca4b1e766c28e0a1ac41d60420fed5e001dc470c64b77/data?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=66040c77ac1b787c3af820529859349a%!F(MISSING)20240418%!F(MISSING)auto%!F(MISSING)s3%!F(MISSING)aws4_request&X-Amz-Date=20240418T074609Z&X-Amz-Expires=1200&X-Amz-SignedHeaders=host&X-Amz-Signature=7bd29d516486b9c751accceabf0bf6a35b27731406b9c31b9097356b60ed6090": dial tcp: lookup dd20bb891979d25aebc8bec07b2b3bbc.r2.cloudflarestorage.com: no such host

**Comment by allelive** [comment]
> > Puoi risolvere qualche host? Sembra che tu abbia problemi di rete.
> 
> Ho provato con reti diverse ma ricevo sempre lo stesso errore

ollama run llama2:13b
ollama run llama2

**Comment by allelive** [comment]
> > Puoi risolvere qualche host? Sembra che tu abbia problemi di rete.
> 
> Ho provato con reti diverse ma ricevo sempre lo stesso errore

ollama run llama2:13b
ollama run llama2

**Comment by swetavsavarn02** [comment]
No Solution has been provided so closing this thread . Unprofessional behaviour

**Comment by pdevine** [comment]
Hi @swetavsavarn02 , I'm sorry you're still running into the issue. It's almost certainly an issue with your network setup and not with Ollama. That's why I'd asked you to see if you could ping anything external to your system.
