### ISSUE TITLE
ollama run dbrx:132b-instruct-q2_K Error: exception error loading model architecture: unknown model architecture: 'dbrx'

### ISSUE THREAD

**Issue by wengbenjue** [ollama/ollama#3686]
### What is the issue?

ollama run dbrx:132b-instruct-q2_K
Error: exception error loading model architecture: unknown model architecture: 'dbrx'

### What did you expect to see?

ollama run dbrx:132b-instruct-q2_K

### OS

macOS

### Architecture

arm64

### Ollama version

0.1.32

### GPU

Apple

### CPU

Apple

**Comment by jmorganca** [comment]
Hi there, thanks for the issue and sorry you hit an error. I'm unable to reproduce this, however do try installing Ollama again from https://ollama.com/download. Note: the 2bit quantization of this model might produce some hallucinations
