### ISSUE TITLE
why wizard 8*22b run on CPU?

### ISSUE THREAD

**Issue by taozhiyuai** [ollama/ollama#3691]
### What is the issue?

<img width="1148" alt="截屏2024-04-17 12 23 02" src="https://github.com/ollama/ollama/assets/146583103/4121905b-51b5-4435-a323-ea773e2015a8">

as shown in the picture. it run on CPU.

my laptop is Mac m3 max 128GB. LM Studio can not run wizardlm-2-8*22b-Q8, it will OOM.

but ollama can run it. but on CPU it seems. is that possible to run on GPU?

### OS

macOS

### Ollama version

up to date

### GPU

Apple

### CPU

Apple

**Comment by taozhiyuai** [comment]
it seems CPU work on SSD as V-RAM

**Comment by mchiang0610** [comment]
@taozhiyuai 128GB is not enough memory to run the 8 bit quantization (q8) of the wizardlm2 model. 

In this case, Ollama will use your computer's CPU and use SSD as the swap disk. We've tried using offloading (partially) to GPU (metal), and it would cause the computer to freeze. 

We'll have to improve the scheduling on this in the future. 

Hope this helps! Closing this issue if it has solved the issue. If not, please feel free to re-open! 

Thank you

**Comment by mxyng** [comment]
Related #4028
