### ISSUE TITLE
Cloudflare Status code 524

### ISSUE THREAD

**Issue by thedavc** [ollama/ollama#3694]
### What is the issue?

I'm running into the following error message:
Ollama call failed with status code 524. Details: <bound method ClientResponse.text of <ClientResponse(http://chat.tamdu.com/api/generate) [524 None]>
<CIMultiDictProxy('Date': 'Wed, 17 Apr 2024 07:30:15 GMT', 'Content-Type': 'text/html; charset=UTF-8', 'Content-Length': '7080', 'Connection': 'keep-alive', 'Report-To': '{"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v4?s=YbviAMSSM3LYJsWVzIaJrWEbptcEzL9UKo8lBnELb9SXTbsiBItX%2BEpnXCNzVCALyxSNNoyoTtuD49XA5Jvk7lWVXbDXX6KoblL84ABMzmC61tkChe8BxvzdInZqFg%2FJpQ%3D%3D"}],"group":"cf-nel","max_age":604800}', 'NEL': '{"success_fraction":0,"report_to":"cf-nel","max_age":604800}', 'X-Frame-Options': 'SAMEORIGIN', 'Referrer-Policy': 'same-origin', 'Cache-Control': 'private, max-age=0, no-store, no-cache, must-revalidate, post-check=0, pre-check=0', 'Expires': 'Thu, 01 Jan 1970 00:00:01 GMT', 'Server': 'cloudflare', 'CF-RAY': '875ab2ff4bf8963f-SJC', 'alt-svc': 'h3=":443"; ma=86400')>

### OS

Linux

### Architecture

x86

### Platform

WSL

### Ollama version

0.1.31

### GPU

Other

### CPU

Intel

**Comment by bmizerany** [comment]
Hi @zhaopengme, we've been working with cloudflare and the issue should hopefully be resolved. Can you confirm?

**Comment by urukalo** [comment]
any tips on how to solve this? @zhaopengme
