### ISSUE TITLE
Splitting layers on macOS gives incorrect output

### ISSUE THREAD

**Issue by sebastiandeutsch** [ollama/ollama#3695]
### What is the issue?

When running mixtral:8x22b it won't give any meaningful results:

```
>>> What is the capital of france? ANSWER:
	


>>> hi
	#" #$

>>>
```

Just jibberish

### What did you expect to see?

When I run

```
ollama run dolphin-mixtral
```

the output is

```
>>> What is the capital of france? ANSWER:
 The capital of France is Paris.
```

### Steps to reproduce

I'm running ollama 0.1.32
on OSX 14.1.1 (M2 Max / 96 GB RAM)

### OS

macOS

### Architecture

arm64

### Ollama version

0.1.32

### GPU

Apple

### GPU info

M2 MAX / 96GB RAM

### CPU

Apple

**Comment by tosh** [comment]
Getting the same result w/ 0.1.32: garbled response w/ hashtags on macOS with Wizard

maybe something about the template? 👋 @sebastiandeutsch

**Comment by jmorganca** [comment]
Thanks for the issue and sorry about this. I think it might be from splitting the model over cpu/gpu layers, in the meantime you try `/set parameter num_gpu 0` does the answer become comprehensible? (noting that Mixtral 8x22b is a text completion model)

Also, do you see similar issues with `wizardlm2:8x22b`?

**Comment by sebastiandeutsch** [comment]
`/set parameter num_gpu 0` did the trick to get output ❤️

**Comment by antonme** [comment]
I have the same problem with all 8x22 models, num_gpu 0 helps, but makes them very slow (since GPU does not seem to work full throttle in that case)

**Comment by jmorganca** [comment]
Hi there, this was from an issue with Ollama's memory estimation. It should largely be fixed now, but let me know if you're continuing to see the issue.
