### ISSUE TITLE
No llama.cpp acknowledgement 

### ISSUE THREAD

**Issue by survirtual** [ollama/ollama#3697]
### What is the issue?

This project is heavily dependent on [llama.cpp](https://github.com/ggerganov/llama.cpp), as seen [in this search](https://github.com/search?q=repo%3Aollama%2Follama%20llama.cpp&type=code), but there is no mention of that in the readme.  This creates some conflict and distaste for this project that I keep seeing on communities for developers that is entirely unnecessary.  Additionally, it prevents people from easily understanding how this project works at a lower level.

### What did you expect to see?

Add an acknowledgement about llama.cpp.  An example of what this could look like can be found in libraries such as Rust's [axum](https://github.com/tokio-rs/axum), which is built on top of [hyper](https://github.com/hyperium/hyper), where there are several mentions of hyper:

> ## Performance
> 
> `axum` is a relatively thin layer on top of [`hyper`] and adds very little
> overhead. So `axum`'s performance is comparable to [`hyper`]. You can find
> benchmarks [here](https://github.com/programatik29/rust-web-benchmarks) and
> [here](https://web-frameworks-benchmark.netlify.app/result?l=rust).

And at the bottom, there are acknowledgement links:

> ...
> [`tower`]: https://crates.io/crates/tower
> [`hyper`]: https://crates.io/crates/hyper
> [`tower-http`]: https://crates.io/crates/tower-http
>...

Something similar can be done for Ollama, which completely alleviates the perception issues, along with helping users and developers get a deeper understanding of the package.

### Steps to reproduce

Go to https://github.com/ollama/ollama, search the readme for llama.cpp, feel a tiny sting of disappointment that such a good project doesn't have any acknowledgements :(

**Comment by Zambito1** [comment]
This is not a matter of taste. The llama.cpp license (along with all software that is under a non public domain compatible license) requires attribution. How is ollama complying with this?

**Comment by survirtual** [comment]
I made a pull request with simple edits to the readme which may resolve the issue.  Feel free to modify it as desired, but I would recommend a front-and-center, subtle acknowledgement (as illustrated) as a minimum.

Including acknowledgements may not seem like a big deal, but it really goes a long way in fostering a healthier developer community.

**Comment by mchiang0610** [comment]
Thank you! We definitely should do a better job. I added it to the readme. 

Thank you for the amazing work. 

https://github.com/ollama/ollama/commit/9755cf9173152047030b6d080c29c829bb050a15

**Comment by jkgenser** [comment]
If you only have 1 backend, it seems more like it's **powered by llama.cpp**, not llama.cpp being one of the many backends - which is actually part of the original PR.

Is there any particular reason to try to shove llama.cpp under the rug by putting it on the _literal_ last line of the Readme?
