### ISSUE TITLE
Fix for server startup to test

### ISSUE THREAD

**Issue by mann1x** [ollama/ollama#3703]
### What is the issue?

Server startup method needs improvements and the llama.cpp server does not report the model loading
This makes the start of the server flaky and unreliable

### What did you expect to see?

Reliable model loading

### Steps to reproduce

Load any model

### Are there any recent changes that introduced the issue?

WAD

### OS

Linux, macOS, Windows

### Ollama version

0.1.32

**Comment by mann1x** [comment]
Sent a PR to fix the startup issues, if you can please test it

https://github.com/ollama/ollama/pull/3702

**Comment by pdevine** [comment]
This ended up getting merged, so I'll close the issue.
