### ISSUE TITLE
[Request Model] TowerInstruct-7B/13B

### ISSUE THREAD

**Issue by EaglePPP** [ollama/ollama#3704]
### What model would you like?

TowerInstruct-7B/13B 
An Open Multilingual LLM for Translation-Related Tasks
Tower - a Unbabel Collection
https://huggingface.co/collections/Unbabel/tower-659eaedfe36e6dd29eb1805c

I have already tried to import it(i used the The BLoke GGUF version) but I cannot figure out how to write a proper Template😿, there is always some gibberish coming out.

thank you very much

**Comment by thinkverse** [comment]
Is it the `<|im_stop|>` token you see as gibberish? What template are you currently using?

I tried the model with the example template Ollama has in the documentation[^1] and with the correct stop parameter and it doesn't return any "gibberish" from what I can see.

```
TEMPLATE """{{ if .System }}<|im_start|>system
{{ .System }}<|im_end|>
{{ end }}{{ if .Prompt }}<|im_start|>user
{{ .Prompt }}<|im_end|>
{{ end }}<|im_start|>assistant
"""

PARAMETER stop <|im_end|>
```

But it would be more helpful if you gave an example of the gibberish that comes out.

[^1]: https://github.com/ollama/ollama/blob/main/docs/modelfile.md#template
