### ISSUE TITLE
I can't push a model

### ISSUE THREAD

**Issue by jonathanhecl** [ollama/ollama#3716]
### What is the issue?

```
> ollama push command-r-plus
retrieving manifest
pushing 503c8cac166f... 100% ▕████████████████████████████████████████████████████████▏  59 GB
pushing f0624a2393a5... 100% ▕████████████████████████████████████████████████████████▏  13 KB
pushing 42499e38acdf... 100% ▕████████████████████████████████████████████████████████▏  270 B
pushing 36b9655abe6a... 100% ▕████████████████████████████████████████████████████████▏   81 B
pushing 748dd5320e31... 100% ▕████████████████████████████████████████████████████████▏  493 B
pushing manifest
Error: unauthorized
```

Why? I can pull, but not push a model? 
I have also tried it with the administration terminal.

### OS

Windows

### GPU

Nvidia

### CPU

Intel

### Ollama version

0.1.32

**Comment by jmorganca** [comment]
Hi @jonathanhecl this is because `command-r-plus` is part of the model library.

If you'd like to push it you need to create it under your username on ollama.com: `<youruser>/command-r-plus`

You can do this with `ollama create <youruser>/command-r-plus -f Modelfile` or copy it with `ollama cp command-r-plus <youruser>/command-r-plus`

Hope this helps!

**Comment by jonathanhecl** [comment]
Maybe I can explaint correctly what I want... I need to DELETE the model.

**Comment by jonathanhecl** [comment]
**Manual Solution** to the problem:

1) Go to the folder [MODELS]\manifests\registry.ollama.ai\library
2) Open the folder of your model (the one you want to delete), and open the "latest" file.
3) In the file "latest" pay attention to the sha256 in several "digest".
4) Go to the folder [MODELS]\blobs
5) Search and delete all the files that have "sha256-*" and that match with digests.
6) Delete "latest" and the folder [MODELS]\manifests\registry.ollama.ai\library\[your model]
7) Check with "ollama list", that the model you wanted to remove is no longer in the list.
