### ISSUE TITLE
How do I download an AI model to external storage and run it?

### ISSUE THREAD

**Issue by manfar** [ollama/ollama#3719]
For existing Mac computers with insufficient hard disk space, how to download the model to an external SSD drive for running instead of storing it on the computer itself. This way you can install more models and run them faster. It also supports path searching and finder viewing of the download storage.

    And how do I find the path to the models I have downloaded to my Mac computer, I can't find where the models I have downloaded are.

**Comment by thinkverse** [comment]
Information about default model directories and how to change that is available in the FAQ[^1].

https://github.com/ollama/ollama/blob/8645076a71941d78a996e52cff65c794df6cdbcb/docs/faq.md?plain=1#L139-L149

[^1]: https://github.com/ollama/ollama/blob/8645076a71941d78a996e52cff65c794df6cdbcb/docs/faq.md#where-are-models-stored

**Comment by igorschlum** [comment]
Hi @manfar if the answer solve the issue, could you close this ticket?

**Comment by dhiltgen** [comment]
If you're still having trouble, let us know.

**Comment by sonnyjlewis** [comment]
Here is the solution for people using the Mac platform who don't want to waste their time searching through a bunch of posts about this: 

### Stop the Ollama process: 

sudo killall ollama

### Set the Variable:

 launchctl setenv OLLAMA_MODELS "/Volumes/YourExternalVolume/location/path/" 

You'll need to make sure you provide the correct external volume drive name and path.

Relaunch Ollama, and when you pull, they'll go to the correct drive, and they'll work.

**Comment by igorschlum** [comment]
Hi @thinkverse, sonnyjlewis,

I think that speed of loading LLMs (Large Language Models) is important 
since files are very large. When you do this, do you see a difference when
you load a model in memory from an external source compared to one from an
internal source?

It could be interesting for a school or a company to load models into a 
read-only directory so each student or employee can only use the models 
proposed by the company.

**Comment by sonnyjlewis** [comment]
I’m using an external USB3.1 (C) M.2 nvme enclosure and I have had zero issues with speed. It’s s responsive as the on-board drive.

**Comment by yy7054wyq5** [comment]
> Here is the solution that should work for people using the Mac platform.
> 
> ### Stop the Ollama process:
> `sudo killall ollama`
> 
> ### Set the Variable (This probably won't work but sent me down a rabbit hole that had the right solution):
> `launchctl setenv OLLAMA_MODELS "/Volumes/YourExternalVolume/location/path/" `
> 
> _You'll need to make sure you provide the correct external volume drive name and path. This process most likely won't work, so if it's a no go for you, continue reading_
> 
> ### What Did Work:
> `sudo nano /etc/launchd.conf`
> 
> use nano, vi, whatever you want to edit. If the file is empty, that's OK too, it might not already exist.
> 
> Add the following:
> 
> ```
> # Set environment variables here so they are available globally to all apps
> # (and Terminal), including those launched via Spotlight.
> #
> # After editing this file run the following command from the terminal to update
> # environment variables globally without needing to reboot.
> # NOTE: You will still need to restart the relevant application (including
> # Terminal) to pick up the changes!
> # grep -E "^setenv" /etc/launchd.conf | xargs -t -L 1 launchctl
> #
> # See http://www.digitaledgesw.com/node/31
> # and http://stackoverflow.com/questions/135688/setting-environment-variables-in-os-x/
> #
> # Note that you must hardcode the paths below, don't use environment variables.
> # You also need to surround multiple values in quotes.
> #
> setenv OLLAMA_HOME /Applications/Ollama.app
> setenv OLLAMA_MODEL /Users/yourusername/.ollama /Volumes/externalmtpoint/morefoldersifdesired/.ollama
> ```
> 
> change yourusername to your local machine user's username if you installed via the GUI installer. Change externalmtpoint/morefoldersifdesired to whatever directories on your external mount point you desire.
> 
> Reboot and enjoy.

In my mac mini4 ,i use this 

```
setenv OLLAMA_HOME /Applications/Ollama.app
setenv OLLAMA_MODELS /Volumes/Kingston/models
```
