### ISSUE TITLE
ollama prune

### ISSUE THREAD

**Issue by Tobiadefami** [ollama/ollama#3728]
I think ollama needs a prune command, something similar to `docker system prune`.  Just to keep the environment tidy

**Comment by lainedfles** [comment]
I think that this functionality is already enabled by default. To disable you can set `OLLAMA_NOPRUNE`. See:

https://github.com/ollama/ollama/blob/8645076a71941d78a996e52cff65c794df6cdbcb/server/images.go#L626-L630
https://github.com/ollama/ollama/blob/8645076a71941d78a996e52cff65c794df6cdbcb/server/images.go#L736-L860
https://github.com/ollama/ollama/blob/8645076a71941d78a996e52cff65c794df6cdbcb/server/routes.go#L1124-L1138

**Comment by Tobiadefami** [comment]
Oh great! thanks for the shout
