### ISSUE TITLE
Please accept slow network connections when loading models

### ISSUE THREAD

**Issue by igorschlum** [ollama/ollama#3741]
### What is the issue?

Downloading of models on slow networks stops too frequently

(base) igor@macigor ~ % ollama run llava:7b
pulling manifest 
pulling 170370233dd5...  23% ▕███             ▏ 959 MB/4.1 GB  882 KB/s  59m29s
Error: max retries exceeded: Get "https://dd20bb891979d25aebc8bec07b2b3bbc.r2.cloudflarestorage.com/ollama/docker/registry/v2/blobs/sha256/17/170370233dd5c5415250a2ecd5c71586352850729062ccef1496385647293868/data?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=66040c77ac1b787c3af820529859349a%!F(MISSING)20240418%!F(MISSING)auto%!F(MISSING)s3%!F(MISSING)aws4_request&X-Amz-Date=20240418T205718Z&X-Amz-Expires=1200&X-Amz-SignedHeaders=host&X-Amz-Signature=a3c02ead244fe32e877db7493a63034cfd737643c3fb8ab4bbc86d75c768d3f1": net/http: TLS handshake timeout
(base) igor@macigor ~ % ollama run llava:7b
pulling manifest 
pulling 170370233dd5...  50% ▕███████         ▏ 2.0 GB/4.1 GB  146 KB/s   3h56m
Error: max retries exceeded: Get "https://dd20bb891979d25aebc8bec07b2b3bbc.r2.cloudflarestorage.com/ollama/docker/registry/v2/blobs/sha256/17/170370233dd5c5415250a2ecd5c71586352850729062ccef1496385647293868/data?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=66040c77ac1b787c3af820529859349a%!F(MISSING)20240418%!F(MISSING)auto%!F(MISSING)s3%!F(MISSING)aws4_request&X-Amz-Date=20240418T213225Z&X-Amz-Expires=1200&X-Amz-SignedHeaders=host&X-Amz-Signature=0cdc6db7e37852c2302d7a2cebb0efeee5136292fddcdb90654a3080224be9c8": read tcp 192.168.1.82:50082->104.18.9.90:443: read: connection reset by peer
(base) igor@macigor ~ % ollama run llava:7b
pulling manifest 
pulling 170370233dd5...  77% ▕████████████    ▏ 3.2 GB/4.1 GB  1.5 MB/s  10m14s
Error: max retries exceeded: Get "https://dd20bb891979d25aebc8bec07b2b3bbc.r2.cloudflarestorage.com/ollama/docker/registry/v2/blobs/sha256/17/170370233dd5c5415250a2ecd5c71586352850729062ccef1496385647293868/data?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=66040c77ac1b787c3af820529859349a%!F(MISSING)20240418%!F(MISSING)auto%!F(MISSING)s3%!F(MISSING)aws4_request&X-Amz-Date=20240418T214548Z&X-Amz-Expires=1200&X-Amz-SignedHeaders=host&X-Amz-Signature=83897005cf68db7e5276cc7a6329e8eac7bad00ff655d8cfd87412e665328af0": net/http: TLS handshake timeout
(base) igor@macigor ~ % ollama run llava:7b
pulling manifest 
pulling 170370233dd5... 100% ▕████████████████▏ 4.1 GB                         
pulling 72d6f08a42f6... 100% ▕████████████████▏ 624 MB                         
pulling 43070e2d4e53... 100% ▕████████████████▏  11 KB                         
pulling c43332387573... 100% ▕████████████████▏   67 B                         
pulling ed11eda7790d... 100% ▕████████████████▏   30 B                         
pulling 7c658f9561e5... 100% ▕████████████████▏  564 B                         
verifying sha256 digest 
writing manifest 
removing any unused layers 
success 
>>> /exit
(base) igor@macigor ~ % ollama run llama3
pulling manifest 
pulling 00e1317cbf74...  10% ▕█               ▏ 473 MB/4.7 GB  1.4 MB/s  49m53s
Error: max retries exceeded: Get "https://dd20bb891979d25aebc8bec07b2b3bbc.r2.cloudflarestorage.com/ollama/docker/registry/v2/blobs/sha256/00/00e1317cbf74d901080d7100f57580ba8dd8de57203072dc6f668324ba545f29/data?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=66040c77ac1b787c3af820529859349a%!F(MISSING)20240418%!F(MISSING)auto%!F(MISSING)s3%!F(MISSING)aws4_request&X-Amz-Date=20240418T224502Z&X-Amz-Expires=1200&X-Amz-SignedHeaders=host&X-Amz-Signature=7a675059c277b61e2e37ffa05bebcfdc5ef3b141bf9f794b9ff3797e926c6429": net/http: TLS handshake timeout
(base) igor@macigor ~ % ollama run llama3
pulling manifest 
pulling 00e1317cbf74...  30% ▕████            ▏ 1.4 GB/4.7 GB  1.3 MB/s  41m46s
Error: max retries exceeded: Get "https://dd20bb891979d25aebc8bec07b2b3bbc.r2.cloudflarestorage.com/ollama/docker/registry/v2/blobs/sha256/00/00e1317cbf74d901080d7100f57580ba8dd8de57203072dc6f668324ba545f29/data?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=66040c77ac1b787c3af820529859349a%!F(MISSING)20240418%!F(MISSING)auto%!F(MISSING)s3%!F(MISSING)aws4_request&X-Amz-Date=20240418T225758Z&X-Amz-Expires=1200&X-Amz-SignedHeaders=host&X-Amz-Signature=6e860ac70cb81d1a0c7b2830264bec22398ac377382009088111f3117abd88bb": net/http: TLS handshake timeout
(base) igor@macigor ~ % ollama run llama3
pulling manifest 
pulling 00e1317cbf74...  47% ▕███████         ▏ 2.2 GB/4.7 GB  1.3 MB/s  31m49s
Error: max retries exceeded: Get "https://dd20bb891979d25aebc8bec07b2b3bbc.r2.cloudflarestorage.com/ollama/docker/registry/v2/blobs/sha256/00/00e1317cbf74d901080d7100f57580ba8dd8de57203072dc6f668324ba545f29/data?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=66040c77ac1b787c3af820529859349a%!F(MISSING)20240419%!F(MISSING)auto%!F(MISSING)s3%!F(MISSING)aws4_request&X-Amz-Date=20240419T003938Z&X-Amz-Expires=1200&X-Amz-SignedHeaders=host&X-Amz-Signature=4c514b8fd50d56f95adcd60d9efac7f4f2177b0bbbe5e5200f254ac3b1a804c1": read tcp [2a01:cb20:4014:3400:ad09:e45b:4793:12ea]:57813->[2606:4700::6812:95a]:443: read: connection reset by peer
(base) igor@macigor ~ % ollama run llama3
pulling manifest 
pulling 00e1317cbf74...  61% ▕█████████████████████████████████████████████                              ▏ 2.9 GB/4.7 GB  1.5 MB/s  19m39s
Error: max retries exceeded: Get "https://dd20bb891979d25aebc8bec07b2b3bbc.r2.cloudflarestorage.com/ollama/docker/registry/v2/blobs/sha256/00/00e1317cbf74d901080d7100f57580ba8dd8de57203072dc6f668324ba545f29/data?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=66040c77ac1b787c3af820529859349a%!F(MISSING)20240419%!F(MISSING)auto%!F(MISSING)s3%!F(MISSING)aws4_request&X-Amz-Date=20240419T004701Z&X-Amz-Expires=1200&X-Amz-SignedHeaders=host&X-Amz-Signature=a01e769aa10f27c7020d029aa6cc7814ee96b8f084c27013e3646bac013c6aa0": net/http: TLS handshake timeout
(base) igor@macigor ~ % ollama run llama3
pulling manifest 
pulling 00e1317cbf74...  74% ▕███████████████████████████████████████████████████████                    ▏ 3.4 GB/4.7 GB  1.1 MB/s  18m44s
Error: max retries exceeded: Get "https://dd20bb891979d25aebc8bec07b2b3bbc.r2.cloudflarestorage.com/ollama/docker/registry/v2/blobs/sha256/00/00e1317cbf74d901080d7100f57580ba8dd8de57203072dc6f668324ba545f29/data?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=66040c77ac1b787c3af820529859349a%!F(MISSING)20240419%!F(MISSING)auto%!F(MISSING)s3%!F(MISSING)aws4_request&X-Amz-Date=20240419T005553Z&X-Amz-Expires=1200&X-Amz-SignedHeaders=host&X-Amz-Signature=3c756468c56b53adfe4f4be731f3daf7dc04b425686c6df2f1d567195f4f7f6f": read tcp [2a01:cb20:4014:3400:ad09:e45b:4793:12ea]:59735->[2606:4700::6812:85a]:443: read: connection reset by peer
(base) igor@macigor ~ % ollama run llama3
pulling manifest 
pulling 00e1317cbf74...  92% ▕█████████████████████████████████████████████████████████████████████      ▏ 4.3 GB/4.7 GB  1.4 MB/s   4m20s
Error: max retries exceeded: Get "https://dd20bb891979d25aebc8bec07b2b3bbc.r2.cloudflarestorage.com/ollama/docker/registry/v2/blobs/sha256/00/00e1317cbf74d901080d7100f57580ba8dd8de57203072dc6f668324ba545f29/data?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=66040c77ac1b787c3af820529859349a%!F(MISSING)20240419%!F(MISSING)auto%!F(MISSING)s3%!F(MISSING)aws4_request&X-Amz-Date=20240419T011033Z&X-Amz-Expires=1200&X-Amz-SignedHeaders=host&X-Amz-Signature=d42500def336a35289b51f066a0e9cac370e8f035b9403b1c4bcf18508c8c409": read tcp 192.168.1.82:61035->104.18.8.90:443: read: connection reset by peer
(base) igor@macigor ~ % ollama run llama3
pulling manifest 
pulling 00e1317cbf74... 100% ▕███████████████████████████████████████████████████████████████████████████▏ 4.7 GB                         
pulling 4fa551d4f938... 100% ▕███████████████████████████████████████████████████████████████████████████▏  12 KB                         
pulling 8ab4849b038c... 100% ▕███████████████████████████████████████████████████████████████████████████▏  254 B                         
pulling c0aac7c7f00d... 100% ▕███████████████████████████████████████████████████████████████████████████▏  128 B                         
pulling db46ef36ef0b... 100% ▕███████████████████████████████████████████████████████████████████████████▏  483 B                         
verifying sha256 digest 
writing manifest 
removing any unused layers 
success 
>>> Sen

### OS

macOS

### CPU

Apple

### Ollama version

0.1.32

**Comment by jmorganca** [comment]
Closing for https://github.com/ollama/ollama/issues/2006
