### ISSUE TITLE
Ollama response 403 to OPTION requests

### ISSUE THREAD

**Issue by zrll12** [ollama/ollama#3746]
### What is the issue?

I was using Next Chat to communicate with Ollama, but Next Chat returns 
``` json
{
  "error": true,
  "message": "Load failed"
}
```
and the log of Ollama says 
```
[GIN] 2024/04/19 - 11:58:33 | 403 |      48.166µs |       127.0.0.1 | OPTIONS  "/v1/chat/completions"
[GIN] 2024/04/19 - 11:58:35 | 403 |       9.791µs |       127.0.0.1 | OPTIONS  "/v1/chat/completions"
```

The `OLLAMA_ORIGINS` variable has been set to `*`

Can run with the following curl

```
curl http://localhost:11434/v1/chat/completions \
    -H "Content-Type: application/json" \
    -d '{
        "model": "llama2",
        "messages": [
            {
                "role": "system",
                "content": "You are a helpful assistant."
            },
            {
                "role": "user",
                "content": "Hello!"
            }
        ]
    }'
```

### OS

macOS

### GPU

Apple

### CPU

Apple

### Ollama version

0.1.32

**Comment by chunzha1** [comment]
same for me. it's that any solutions?

**Comment by chunzha1** [comment]
<img width="971" alt="截屏2024-04-22 00 30 27" src="https://github.com/ollama/ollama/assets/125763492/ddc24191-5e65-497c-b8d5-e76e916a8f1b">
I found that it can be used in OpenAI, but got a 403 error when using it on Ollama...

**Comment by jmorganca** [comment]
This should be fixed on `main` and in the next release of Ollama

**Comment by haohaifeng002** [comment]
Version 0.5.4 still has not resolved the issue
