### ISSUE TITLE
Import from a HF model directly?

### ISSUE THREAD

**Issue by wennycooper** [ollama/ollama#3748]
Is it possible to import from a huggingface model (given a huggingface card ID) directly? 
I don't want to converting it to GGUF.

**Comment by adrienbrault** [comment]
Would be nice if the `Modelfile` supported remote GGUFs:
```
FROM https://huggingface.co/MaziyarPanahi/Meta-Llama-3-8B-Instruct-GGUF/blob/main/Meta-Llama-3-8B-Instruct.Q2_K.gguf
```

**Comment by ericcurtin** [comment]
@adrienbrault agree, if you could just put a .gguf in the FROM statement and it just got pulled it would be ideal.

**Comment by ericcurtin** [comment]
I added this feature in another form:

https://github.com/ericcurtin/podman-ollama

`podman-ollama -m https://huggingface.co/TheBloke/Mistral-7B-Instruct-v0.2-GGUF/resolve/main/mistral-7b-instruct-v0.2.Q2_K.gguf "Tell a joke"`

uses ollama as a backend.

**Comment by ericcurtin** [comment]
It's implemented here now, see bottom of README for usage:

https://github.com/ericcurtin/podman-ollama

**Comment by jmorganca** [comment]
This is now possible for a small set of architectures:
* `MistralForCausalLM`
* `MixtralForCausalLM`
* `GemmaForCausalLM`

With support for more models (including [Llama 3](https://github.com/ollama/ollama/pull/4268)) coming soon!

**Comment by jmorganca** [comment]
To, use `FROM <model directory>` in the `Modelfile`

**Comment by mr-gorjan** [comment]
I am running ollama on docker . Trying to run HF model with **MistralForCausalLM**. Modelfile contains `FROM <model directory>`

It throws

transferring model data 
unpacking model metadata 
processing tensors 
Error: open /root/.ollama/models/blobs/411433471/tokenizer.model: no such file or directory

The model which I pulled doesn't have tokenizer.model file.

**Comment by rplescia** [comment]
> Update
> 
> I downloaded and moved tokenizer.model file from base model Mistral 7B to the finetuned model directory. It seems to be converting. Will test it.
> 
> I am running ollama on docker . Trying to run HF model with **MistralForCausalLM**. Modelfile contains `FROM <model directory>`
> 
> It throws
> 
> transferring model data unpacking model metadata processing tensors Error: open /root/.ollama/models/blobs/411433471/tokenizer.model: no such file or directory
> 
> The model which I pulled doesn't have tokenizer.model file.

I've got the same issue.

**Comment by mr-gorjan** [comment]
The above solution worked for me. You need the **original** model's tokenizer.model file.

1. Just copy it directly inside downloaded **finetuned** model directory.
2. And then try to import.

Make sure to match architecture of the **finetuned** model and the **original** model. They should be same. You can find it inside **config.json** file of those models.
