### ISSUE TITLE
Rerankers and Embeddings

### ISSUE THREAD

**Issue by BradKML** [ollama/ollama#3749]
Hello from the agentic AI crowd, other than that Ollama does not have concurrent model abilities, is it possible to get Ollama to run Rerankers (like Cohere and Jina) or text embeddings (SentenceTransformers e.g. SBERT) for applications that does not directly use LLMs?

**Comment by thinkverse** [comment]
I'm not sure about Rerankers but Ollama started supporting text embeddings as of [0.1.26](https://github.com/ollama/ollama/releases/tag/v0.1.26) and even released a blog post about [Embedding models](https://ollama.com/blog/embedding-models). Here's a short list of some currently available models:

- [snowflake-arctic-embed](https://ollama.com/library/snowflake-arctic-embed)
- [mxbai-embed-large](https://ollama.com/library/mxbai-embed-large)
- [nomic-embed-text](https://ollama.com/library/nomic-embed-text)
- [all-minilm](https://ollama.com/library/all-minilm)

The community has also added some more models, [searching embed](https://ollama.com/search?q=embed&p=1) gives a fair amount of results.

More will become available later hopefully once more architectures are supported.

**Comment by BradKML** [comment]
Should've focused on Rerankers
- LocalAI is also waiting for support for Rerankers https://github.com/mudler/LocalAI/issues/2018
- Xorbit Xinference is already https://github.com/xorbitsai/inference/pull/672

As for previously noted issues there are these two https://github.com/ollama/ollama/issues/3630 https://github.com/ollama/ollama/issues/3631

**Comment by 3SMMZRjWgS** [comment]
I'd like to add a vote to @BradKML's suggestion on a re-ranker feature in the Ollama framework. This will help keep any RAG pipeline within Ollama end-to-end.

**Comment by uzumakinaruto19** [comment]
> I'd like to add a vote to @BradKML's suggestion on a re-ranker feature in the Ollama framework. This will help keep any RAG pipeline within Ollama end-to-end.

+1

**Comment by cope** [comment]
> I'd like to add a vote to @BradKML's suggestion on a re-ranker feature in the Ollama framework. This will help keep any RAG pipeline within Ollama end-to-end.

+1

**Comment by stronk7** [comment]
Heh,

I'd suggest to stop adding comments and, instead, just upvote the proposal, it's a little bit annoying to get emails with nothing but a +1.

Thanks :-)

**Comment by RLinnae** [comment]
Would also be great to see rerankers as now I have other packages installed just for re-ranking.  Making ollama feel like a waste.

**Comment by BradKML** [comment]
@RLinnae seconding this but what are the options out there atm that is not so complex that you need a Docker instance?

**Comment by yushengliao** [comment]
+1

**Comment by RLinnae** [comment]
> @RLinnae seconding this but what are the options out there atm that is not so complex that you need a Docker instance?

I am mostly using flashrank at the moment.

**Comment by zydmtaichi** [comment]
> I'd like to add a vote to @BradKML's suggestion on a re-ranker feature in the Ollama framework. This will help keep any RAG pipeline within Ollama end-to-end.

+1

**Comment by BradKML** [comment]
Can people please stop with the "+1" already and suggest models that should be included instead? (with reference link to corresponding resources)

**Comment by virajkanwade** [comment]
From https://docs.continue.dev/setup/configuration#best-overall-experience:

https://huggingface.co/voyageai/rerank-1/tree/main
https://huggingface.co/voyageai/voyage-code-2

**Comment by tikendraw** [comment]
add reranker models please.

**Comment by Nordln** [comment]
+1 for adding reranker models to Ollama. Same issue was raised here: https://github.com/ollama/ollama/issues/4510.

**Comment by jmorganca** [comment]
Merging with https://github.com/ollama/ollama/issues/3368

Thanks for the issue and comments all!

**Comment by hughescr** [comment]
https://huggingface.co/BAAI/bge-reranker-v2-m3

**Comment by sandstad** [comment]
Working wit a RAGFlow project and would have been great to get re-ranking support in Ollama
