### ISSUE TITLE
command-r:latest run  exception

### ISSUE THREAD

**Issue by zw6234336** [ollama/ollama#3752]
### What is the issue?

<img width="947" alt="Xnapper-2024-04-19-17 45 26" src="https://github.com/ollama/ollama/assets/5389245/4eeeee44-f4a1-4b8f-a202-ed78665d9772">

### OS

macOS

### GPU

Apple

### CPU

Apple

### Ollama version

0.1.27

**Comment by gaardhus** [comment]
Updating to the newest version of ollama should solve the issue.

**Comment by jmorganca** [comment]
The latest version of Ollama should improve this as memory estimates for Command-R family models are more accurate. Let me know if you're still seeing this issue and I can re-open it!
