### ISSUE TITLE
Ollama backend down?

### ISSUE THREAD

**Issue by piratos** [ollama/ollama#3758]
### What is the issue?

ollama pull returns
```
no healthy upstream
```

llama 3 release traffic killed your backend ? :smile: 

### OS

Linux

### GPU

Nvidia

### CPU

Intel

### Ollama version

 0.1.31

**Comment by slimsag** [comment]
same

**Comment by diegoxa** [comment]
same!

**Comment by d4rk30** [comment]
same!

**Comment by slimsag** [comment]
seems fixed now

**Comment by diegoxa** [comment]
> seems fixed now

confirming, that was quick!

**Comment by piratos** [comment]
thnx, better grab those models before it goes down again !
