### ISSUE TITLE
~/ollama/ollama run llama3:70b   Error: Post "http://127.0.0.1:11434/api/chat": EOF

### ISSUE THREAD

**Issue by phalexo** [ollama/ollama#3768]
### What is the issue?

Llama 3 70B under Ollama appears to be about 39GB.

I have 4 GPUs with 12.2GiB each. (and I can also add 4GiB on another)

The model gets loaded at about 10GiB per GPU, and then I get the error above,

Is it memory related? Not really clear to me.

### OS

Linux

### GPU

Nvidia

### CPU

Intel

**Comment by yc446833448** [comment]
你是怎么解决的啊？我也遇到了
