### ISSUE TITLE
Manifest error, no such host found.

### ISSUE THREAD

**Issue by harshaelon** [ollama/ollama#3776]
### What is the issue?

I was actually running the ollama and was trying to use it with llama2, but i was not able to run or proceed further. here is the screenshot, any help would be highly appreciated

![image](https://github.com/ollama/ollama/assets/128384441/00133a19-dc50-4b8a-8e4a-5174a00a1a2c)
. 

### OS

Windows

### GPU

Nvidia

### CPU

Intel

### Ollama version

ollama version is 0.1.32

**Comment by dhiltgen** [comment]
This looks like a dup of #3504
