### ISSUE TITLE
support olmo

### ISSUE THREAD

**Issue by userforsource** [ollama/ollama#3778]
https://github.com/ggerganov/llama.cpp/pull/6741
Now

This is now support in llama.cpp can you new support into ollama thanks

Build with truly open dataset and fully open-source model can this be supported in olllama thanks.
https://allenai.org/olmo
https://huggingface.co/allenai/OLMo-7B

**Comment by jmorganca** [comment]
Closing for https://github.com/ollama/ollama/issues/2337
