### ISSUE TITLE
How to run Ollama using AMD RX 6600 XT on Windows 11?

### ISSUE THREAD

**Issue by NAME0x0** [ollama/ollama#3781]
### What is the issue?

The responses by all the LLM's are slow as the CPU is prioritised. I wish to make use of my RX 6600 XT GPU but apparently the workaround is only on Linux. Furthermore, ROCm runtime is available for RX 6600 XT but not HIP SDK which is apparently what is needed for my GPU to run LLMs. However, the documentation for Ollama says that my GPU is supported. How do I make use of it then, since it's not utilising it at all?

### OS

Windows

### GPU

AMD

### CPU

Intel

### Ollama version

0.1.32

**Comment by likelovewant** [comment]
make sure make your rocm support first .  download somewhere in github , eg, [here]( https://github.com/brknsoul/ROCmLibs/ ) replace the file in hip sdk.
 Then git clone ollama , edit the file in ` ollama\llm\generate\gen_windows.ps1` ,add your gpu number there . then follow the development guide ,step1,2 , then search `gfx1102` , add your gpu where ever `gfx1102` show  .  build again or simple follow the readme file in app folder to build an ollama install then you are make your ollama running on gpu

**Comment by Sohnny0** [comment]
> `llm\generate\gen_windows.ps1` ,add your gpu num

Thank you very much for your method, I successfully added gfx1031, my 6700xt graphics card can run llama3 perfectly

**Comment by Sohnny0** [comment]
> make sure make your rocm support first . download somewhere in github , eg, [here](https://github.com/brknsoul/ROCmLibs/) replace the file in hip sdk. Then git clone ollama , edit the file in ` ollama\llm\generate\gen_windows.ps1` ,add your gpu number there . then follow the development guide ,step1,2 , then search `gfx1102` , add your gpu where ever `gfx1102` show . build again or simple follow the readme file in app folder to build an ollama install then you are make your ollama running on gpu

Thank you very much for your method, I successfully added gfx1031, my 6700xt graphics card can run llama3 perfectly

**Comment by G2R3DL-9001** [comment]
Video please @Sohnny0
