### ISSUE TITLE
模型下载最后1%速度骤降，导致下载时间超长。The download speed suddenly drops at the last 1%, resulting in an extremely long download time.

### ISSUE THREAD

**Issue by aohanhongzhi** [ollama/ollama#3794]
### What is the issue?

模型无论大小，每次下载前面99%都最大的速度可以达到29MB/s。但是最后1%速度就只有几百 KB/s。很奇怪。是进度条有问题，还是啥bug？这在我本地电脑和线上服务器都出现了。

Regardless of model size, in most cases, the download speed reaches 29MB/s for about 99% of the time before completion. However, the last 1% takes only a few hundred KB/s. This is quite strange. Is it an issue with the progress bar or some bug? This phenomenon has been observed on both my local computer and online server.

![image](https://github.com/ollama/ollama/assets/37319319/be1b24f1-922c-4478-8548-74704686e573)

![image](https://github.com/ollama/ollama/assets/37319319/9a8b4e0c-4dc6-4156-bd46-744befb3795e)

![image](https://github.com/ollama/ollama/assets/37319319/87782acf-2caa-40d5-a84a-b19eab38333e)

### OS

Linux

### GPU

Nvidia

### CPU

Intel

### Ollama version

0.1.32

**Comment by mili-tan** [comment]
你可以试试看按下 Ctrl+C 取消这次下载，然后再次重新下载，进度不会丢失，速度也许会快很多。这对我绝大多数时间有效。

**Comment by Shzyhao** [comment]
一样，我是一段时间速度很快，50M/s，但是过了一段时间就很慢，200k/s，问题是没做过变更操作，下qwen二十秒就下完了，下到llama3的时候前面很快，后面就老是报TLS handshake timeout，感觉看脸
![image](https://github.com/ollama/ollama/assets/77272241/9b232c2e-c3cb-4a3b-9a1d-52189bf52017)

**Comment by micsama** [comment]
similar

**Comment by pdevine** [comment]
This is a dupe of #1736

**Comment by martin-bing** [comment]
> 你可以试试看按下 Ctrl+C 取消这次下载，然后再次重新下载，进度不会丢失，速度也许会快很多。这对我绝大多数时间有效。
> 
> You could try pressing Ctrl+C to cancel this download and then re-download it again, which won't lose progress and might be much faster. This works for me most of the time.



> 你可以试试看按下 Ctrl+C 取消这次下载，然后再次重新下载，进度不会丢失，速度也许会快很多。这对我绝大多数时间有效。
> 
> You could try pressing Ctrl+C to cancel this download and then re-download it again, which won't lose progress and might be much faster. This works for me most of the time.

亲测有用，赞！

**Comment by c12h180** [comment]
> 你可以试试看按下 Ctrl+C 取消这次下载，然后再次重新下载，进度不会丢失，速度也许会快很多。这对我绝大多数时间有效。
> 
> You could try pressing Ctrl+C to cancel this download and then re-download it again, which won't lose progress and might be much faster. This works for me most of the time.

牛逼！

**Comment by KK0571** [comment]
强制结束有时候会丢进度的，遇到过一次，现在不敢强制取消

**Comment by yzwou** [comment]
> 强制结束有时候会丢进度的，遇到过一次，现在不敢强制取消

富贵险中求吧只能说

**Comment by franklin520520** [comment]
> 你可以试试看按下 Ctrl+C 取消这次下载，然后再次重新下载，进度不会丢失，速度也许会快很多。这对我绝大多数时间有效。
> 
> You could try pressing Ctrl+C to cancel this download and then re-download it again, which won't lose progress and might be much faster. This works for me most of the time.

相当好用啊

**Comment by KK0571** [comment]
谢谢，已经尝试过了，有时可以重连高速下载，有时候会连接不上，多尝试几次可以，或者干脆改天pull。



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年11月14日(星期四) 上午10:54
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ollama/ollama] 模型下载最后1%速度骤降，导致下载时间超长。The download speed suddenly drops at the last 1%, resulting in an extremely long download time. (Issue #3794)














  
你可以试试看按下 Ctrl+C 取消这次下载，然后再次重新下载，进度不会丢失，速度也许会快很多。这对我绝大多数时间有效。
 
You could try pressing Ctrl+C to cancel this download and then re-download it again, which won't lose progress and might be much faster. This works for me most of the time.
  
相当好用啊

**Comment by Yu-kio** [comment]
> 你可以试试看按下 Ctrl+C 取消这次下载，然后再次重新下载，进度不会丢失，速度也许会快很多。这对我绝大多数时间有效。
> 
> You could try pressing Ctrl+C to cancel this download and then re-download it again, which won't lose progress and might be much faster. This works for me most of the time.

GREAT

**Comment by vip91919** [comment]
你可以试试看按下 Ctrl+C 取消这次下载，然后再次重新下载，进度不会丢失，速度也许会快很多。这对我绝大多数时间有效。

You could try pressing Ctrl+C to cancel this download and then re-download it again, which won't lose progress and might be much faster. This works for me most of the time.
您可以尝试按 Ctrl+C 取消此下载，然后再次重新下载，这不会丢失进度并且可能会更快。这在大多数情况下对我来说都有效。
感谢分享，有效

**Comment by gjnzsu** [comment]
ctrl+c and resume download 
亲测有效，多谢分享

**Comment by Peter2555** [comment]
没啥作用

**Comment by mili-tan** [comment]
> 没啥作用

或许，也试试看这个：

https://github.com/onllama/Onllama.ModelScope2Registry

**Comment by gjnzsu** [comment]
后来发现换成国内的nju的地址会快很多，已顺利完成下载并启动啦

docker run -d -p 3000:8080 --add-host=host.docker.internal:host-gateway -v open-webui:/app/backend/data --name open-webui --restart always ghcr.nju.edu.cn/open-webui/open-webui:main

**Comment by siruoqing** [comment]
> 你可以试试看按下 Ctrl+C 取消这次下载，然后再次重新下载，进度不会丢失，速度也许会快很多。这对我绝大多数时间有效。
> 
> You could try pressing Ctrl+C to cancel this download and then re-download it again, which won't lose progress and might be much faster. This works for me most of the time.您可以尝试按 Ctrl+C 取消此下载，然后再次重新下载，这不会丢失进度并且可能会更快。这在大多数情况下对我来说都有效。

Thanks very much

**Comment by happyEddiehorse** [comment]
> 你可以试试看按下 Ctrl+C 取消这次下载，然后再次重新下载，进度不会丢失，速度也许会快很多。这对我绝大多数时间有效。
> 
> You could try pressing Ctrl+C to cancel this download and then re-download it again, which won't lose progress and might be much faster. This works for me most of the time.

有用，太棒了！

**Comment by likwater** [comment]
> 你可以试试看按下 Ctrl+C 取消这次下载，然后再次重新下载，进度不会丢失，速度也许会快很多。这对我绝大多数时间有效。
> 
> You could try pressing Ctrl+C to cancel this download and then re-download it again, which won't lose progress and might be much faster. This works for me most of the time.

亲测有效，太有用了，感谢感谢

**Comment by James-Xue** [comment]
> 你可以试试看按下 Ctrl+C 取消这次下载，然后再次重新下载，进度不会丢失，速度也许会快很多。这对我绝大多数时间有效。
> 
> You could try pressing Ctrl+C to cancel this download and then re-download it again, which won't lose progress and might be much faster. This works for me most of the time.

牛逼，真的有用！就凭这个评论，我相信AI永远也替代不了网友的评论

**Comment by kesshei** [comment]
重新来一下，确实快很多，感谢！

**Comment by seahurt** [comment]
还是想知道原因

**Comment by seeadoog** [comment]
剩1%时，只有几十kb/s。 再到后面只有几kb/s，零点几kb/s 。感觉是故意耍猴呢。

**Comment by mili-tan** [comment]
> 剩1%时，只有几十kb/s。 再到后面只有几kb/s，零点几kb/s 。感觉是故意耍猴呢。

这是运营商的 QoS，和 Ollama 无关。还可以试试看修改 Hosts 将 Ollama 的 R2 切换到 Cloudflare 其他节点。
```
104.18.20.20 registry.ollama.ai
104.18.20.20 dd20bb891979d25aebc8bec07b2b3bbc.r2.cloudflarestorage.com
```

**Comment by msjsc001** [comment]
遇到同样的问题，有没有办法说是自己下载好模型后再加载到ollama中。

**Comment by msjsc001** [comment]
> 你可以试试看按下 Ctrl+C 取消这次下载，然后再次重新下载，进度不会丢失，速度也许会快很多。这对我绝大多数时间有效。
> 
> You could try pressing Ctrl+C to cancel this download and then re-download it again, which won't lose progress and might be much faster. This works for me most of the time.

有用，谢谢！

**Comment by mkyuangithub** [comment]
Pls use this script saved as a .ps1 e.g. download_model.ps1 under windows->powershell

run such ps1 under the powershell， it will automaticall restart at 240 seconds and use this to simulate your "ctrl+c and re-pull" behavior. 

After test it for several weeks, it never loss download data, enjoy it.

download_model.ps1
`while ($true) {

    $modelExists = ollama list | Select-String "qwen2.5:14b"
    if ($modelExists) {
        Write-Host "download finish"
        break
    }

    Write-Host "start download..."
    $process = Start-Process -FilePath "ollama" -ArgumentList "run", "qwen2.5:14b" -PassThru -NoNewWindow

    Start-Sleep -Seconds 240
    
    try {
        Stop-Process -Id $process.Id -Force -ErrorAction Stop
        Write-Host "retry..."
    }
    catch {
        Write-Host "process finish"
    }
}`

**Comment by mkyuangithub** [comment]
> Pls use this script saved as a .ps1 e.g. download_model.ps1 under windows->powershell
> 
> run such ps1 under the powershell， it will automaticall restart at 240 seconds and use this to simulate your "ctrl+c and re-pull" behavior.
> 
> After test it for several weeks, it never loss download data, enjoy it.
> 
> download_model.ps1 script contents:


while ($true) {
    $modelExists = ollama list | Select-String "qwen2.5:14b"
    if ($modelExists) {
        Write-Host "download finish"
        break
    }
    Write-Host "start download..."
    $process = Start-Process -FilePath "ollama" -ArgumentList "run", "qwen2.5:14b" -PassThru -NoNewWindow

    Start-Sleep -Seconds 240
    
    try {
        Stop-Process -Id $process.Id -Force -ErrorAction Stop
        Write-Host "retry..."
    }
    catch {
        Write-Host "process finish"
    }
}

**Comment by mkyuangithub** [comment]
> Pls use this script saved as a .ps1 e.g. download_model.ps1 under windows->powershell
> 
> run such ps1 under the powershell， it will automaticall restart at 240 seconds and use this to simulate your "ctrl+c and re-pull" behavior.
> 
> After test it for several weeks, it never loss download data, enjoy it.
> 
> download_model.ps1 script contents:
> 
> while ($true) { $modelExists = ollama list | Select-String "qwen2.5:14b" if ($modelExists) { Write-Host "download finish" break } Write-Host "start download..." $process = Start-Process -FilePath "ollama" -ArgumentList "run", "qwen2.5:14b" -PassThru -NoNewWindow
> 
> ```
> Start-Sleep -Seconds 240
> 
> try {
>     Stop-Process -Id $process.Id -Force -ErrorAction Stop
>     Write-Host "retry..."
> }
> catch {
>     Write-Host "process finish"
> }
> ```
> 
> }

![Image](https://github.com/user-attachments/assets/c38c152d-09e0-4764-b5ea-00b691cf9c9d)

**Comment by ShawnBei** [comment]
> 你可以试试看按下 Ctrl+C 取消这次下载，然后再次重新下载，进度不会丢失，速度也许会快很多。这对我绝大多数时间有效。
> 
> You could try pressing Ctrl+C to cancel this download and then re-download it again, which won't lose progress and might be much faster. This works for me most of the time.
> 
> 或者你在中国大陆，也可以试试看这个： https://github.com/onllama/Onllama.ModelScope2Registry

有用！感谢

**Comment by Echo-1120** [comment]
> > 你可以试试看按下 Ctrl+C 取消这次下载，然后再次重新下载，进度不会丢失，速度也许会快很多。这对我绝大多数时间有效。
> > You could try pressing Ctrl+C to cancel this download and then re-download it again, which won't lose progress and might be much faster. This works for me most of the time.
> 
> > 你可以试试看按下 Ctrl+C 取消这次下载，然后再次重新下载，进度不会丢失，速度也许会快很多。这对我绝大多数时间有效。
> > You could try pressing Ctrl+C to cancel this download and then re-download it again, which won't lose progress and might be much faster. This works for me most of the time.
> 
> 亲测有用，赞！

有用有用！！！太感谢了

**Comment by XiaoPeng0x3** [comment]
确实有用，不过很奇怪，哈哈哈

**Comment by qet119** [comment]
> 你可以试试看按下 Ctrl+C 取消这次下载，然后再次重新下载，进度不会丢失，速度也许会快很多。这对我绝大多数时间有效。
> 
> You could try pressing Ctrl+C to cancel this download and then re-download it again, which won't lose progress and might be much faster. This works for me most of the time.
> 
> 或者你在中国大陆，也可以试试看这个： https://github.com/onllama/Onllama.ModelScope2Registry

别信， Ctrl+C 后不会重新续传 👎🏻

**Comment by Javaears** [comment]
Ctrl+C真的非常好用，多试几次都可以的，可以续传，速度重新上来！

**Comment by konhong** [comment]
> 你可以试试看按下 Ctrl+C 取消这次下载，然后再次重新下载，进度不会丢失，速度也许会快很多。这对我绝大多数时间有效。
> 
> You could try pressing Ctrl+C to cancel this download and then re-download it again, which won't lose progress and might be much faster. This works for me most of the time.
> 
> 或者你在中国大陆，也可以试试看这个： https://github.com/onllama/Onllama.ModelScope2Registry

26年8月了还是同一个问题，同样的解决方案，感谢分享
