### ISSUE TITLE
hope add more embedding models

### ISSUE THREAD

**Issue by zhangzhongpeng02** [ollama/ollama#3797]
I hope to add more embedding models, such as "bge-large-zh-v1.5"、”bce-embedding-base“、"gte-large"

**Comment by thinkverse** [comment]
`bge-large-zh-v1.5` has been added by the community: [dztech/bge-large-zh](https://ollama.com/dztech/bge-large-zh), as well as `gte-large`: [milkey/gte](https://ollama.com/milkey/gte).

`bce-embedding-base` cannot be added yet since llama.cpp doesn't support the `xlm-roberta` architecture.

**Comment by AprilCat** [comment]
> `bge-large-zh-v1.5` has been added by the community: [dztech/bge-large-zh](https://ollama.com/dztech/bge-large-zh), as well as `gte-large`: [milkey/gte](https://ollama.com/milkey/gte).
> 
> `bce-embedding-base` cannot be added yet since llama.cpp doesn't support the `xlm-roberta` architecture.

after executing 
```bash
ollama pull dztech/bge-large-zh:v1.5
```
I got error:
```bash
pulling manifest 
Error: pull model manifest: Get "https://ollama.com/token?nonce=RpAJ5MYmZq2JN_s6hT6riA&scope=repository%!A(MISSING)dztech%!F(MISSING)bge-large-zh%!A(MISSING)pull&service=ollama.com&ts=1714456747": read tcp 192.168.1.152:45624->34.120.132.20:443: read: connection reset by peer
```
So how to use bge-large-zh?

**Comment by thinkverse** [comment]
@AprilCat seems like a connection issue, might be the same issue as https://github.com/ollama/ollama/issues/4042 or any other networking issue. Check for [issues labelled networking](https://github.com/ollama/ollama/issues?q=is%3Aopen+is%3Aissue+label%3Anetworking) or create your own bug issue.
