### ISSUE TITLE
Can this library utilize Intel's UHD graphics cards?

### ISSUE THREAD

**Issue by Meshwa428** [ollama/ollama#3798]
My question is that most of the models are supported/backed by cuda to run on NVIDIA's cards, but what about Intel?

Many machines (most probably consumer grade intel laptops) still have intel gpus (UHD cards) so will ollama add a support  for them?

Or intel gpus are just too hard to be used?

Cause to run those big models like llama 2 7b is still slow on cpu, so utilizing uhd cards might make them a little faster than the cpu and might just reduce the latency

I mean like libraries like open vino can even use intel uhd cards

**Comment by dhiltgen** [comment]
Intel integrated GPU support is tracked via #3113

**Comment by ayttop** [comment]
https://github.com/intel-analytics/ipex-llm/blob/main/docs/mddocs/Quickstart/llama_cpp_quickstart.md
