### ISSUE TITLE
Auto-Save Functionality

### ISSUE THREAD

**Issue by M3cubo** [ollama/ollama#3800]
Hello, I am currently using Ollama for interactive terminal sessions and I find it to be an extremely useful tool. One of the features I am interested in is the ability to automatically save each addition to the conversation during an `ollama run <model>` session.

### Feature Request
I would like to inquire if there is an existing feature similar to `ollama run <model> --save`, where `--save` would automatically save each new addition to the conversation without requiring manual input each time. This would be particularly helpful for ensuring that all interactions are preserved without the need to manually input save commands after each response.

### Alternative
If implementing this feature is not feasible at the moment, could you provide guidance or recommend a best practice for automating this process using a shell script or any other method? Currently, I am considering using tools like `expect` to automate interactions, but any advice or recommendations would be greatly appreciated.

Thank you for considering this request. I believe this feature could greatly enhance the usability and efficiency of using Ollama for many users.

Best regards,

Martín

**Comment by pdevine** [comment]
Hey @M3cubo You can do something similar to this right now in the interactive session by typing `/save <model>`. Just do `ollama run <model>` on the next run to pick up the conversation again.

I'll go ahead and close the issue, but feel free to keep commenting if that doesn't fit the bill.

**Comment by M3cubo** [comment]
Hello @pdevine,

Thank you for the response. The current /save feature requires manual intervention, which isn't ideal for my use case. I'm looking for a more automated solution where sessions are saved without any manual commands, ensuring no data is lost even if I forget to trigger a save.

Best regards,
Martín
