### ISSUE TITLE
How to add a new model to Ollama? Such as Qwen1.5-14B, Qwen1.5-72B, etc., such as the open source LLM model on this site

### ISSUE THREAD

**Issue by jieguolove** [ollama/ollama#3811]
The currently supported models are as follows：
![image](https://github.com/ollama/ollama/assets/96612712/33f8a07a-434d-411f-bbe2-fa8896bf357b)
Can we add the new model to Ollama ourselves? How to add a new model to Ollama? Such as Qwen1.5-14B, Qwen1.5-72B, etc., such as the open source LLM model on this site
[https://modelscope.cn/topic/dfefe5be778b49fba8c44646023b57ba/pub/summary](url)
Thank you!

**Comment by thinkverse** [comment]
Yes, you can add your own models or open-source models, as long as the architecture is supported by Ollama and llama.cpp and the model creator allows it. Ollama has a guide written on [how to import models](https://github.com/ollama/ollama/blob/main/docs/import.md).

You can even [publish](https://github.com/ollama/ollama/blob/main/docs/import.md#publishing-your-model-optional--early-alpha) your model back to Ollama for redistribution as long as the model you choose allows redistribution ofc.

**Comment by jieguolove** [comment]
Got it，thanks a lot!
