### ISSUE TITLE
希望Ollama运行后直接打开界面

### ISSUE THREAD

**Issue by chergn** [ollama/ollama#3812]
页面只有“Ollama is running”，希望可以提供运行后可以直接打开webUI
<img width="470" alt="image" src="https://github.com/ollama/ollama/assets/43592730/96392aca-b563-4da8-b823-bf6b82641f51">

<img width="1920" alt="image" src="https://github.com/ollama/ollama/assets/43592730/5e117f86-e436-451f-a00f-a531373c25b3">

**Comment by thinkverse** [comment]
Ollama doesn't have a built-in web UI. You either have to use the CLI client that comes with Ollama. Or use a web or desktop app provided by the community. https://github.com/ollama/ollama?tab=readme-ov-file#web--desktop

**Comment by dhiltgen** [comment]
Ollama provides a REST API and CLI you can run in `cmd` or `powershell`  Community projects provide graphical interfaces.  https://github.com/ollama/ollama?tab=readme-ov-file#community-integrations 

At this time we don't plan to add a web UI directly into Ollama, but please try out any of the great community UIs if you don't want to use the terminal.
