### ISSUE TITLE
 OpenSSL SSL_read: error:0A000126

### ISSUE THREAD

**Issue by xuya227939** [ollama/ollama#3815]
### What is the issue?

jiang@jiang-MS-7D90:~$ curl -fsSL https://ollama.com/install.sh | sh
>>> Downloading ollama...
### OS

Linux

### GPU

Nvidia

### CPU

Intel

**Comment by dhiltgen** [comment]
This sounds like it might be a firewall or proxy problem interfering with download from github.com.

**Comment by pdevine** [comment]
@xuya227939 did you end up getting this sorted out?

**Comment by mxyng** [comment]
Closing this since it's been 2 months of inactivity
