### ISSUE TITLE
`i/o timeout` when running `ollama pull`

### ISSUE THREAD

**Issue by pitilessj** [ollama/ollama#3816]
### What is the issue?

pulling manifest
Error: pull model manifest: Get "https://registry.ollama.ai/v2/library/llama3/manifests/8b": dial tcp 104.21.75.227:443: i/o timeout

### OS

Linux

### GPU

Nvidia

### Ollama version

0.1.32

**Comment by luzik** [comment]
It's looking like network problem

**Comment by LitghtCoder** [comment]
INFO source=images.go:1147 msg="request failed: Get \"https://registry.ollama.ai/v2/library/llama3/manifests/latest\": dial tcp 172.67.182.229:443: i/o timeout"

**Comment by dhiltgen** [comment]
Can you ping registry.ollama.ai from the system where you're running ollama?  If that works, can you try to `curl https://registry.ollama.ai/v2/_catalog` (will take a while, but should produce a list of some of the models)

**Comment by loFei** [comment]
I also encountered this problem. When I use curl to access "https://registry.ollama.ai/v2/library/llamam3/manifests/latest", the return result is like this:

{"errors":[{"code":"MANIFEST_INVALID","message":"manifest invalid","detail":{}}]}

**Comment by bk8702** [comment]
```bash
curl -s https://registry.ollama.ai/v2/_catalog | jq '.repositories[] | select(contains("llama3"))'
"549165334/llama3-chinese"
"abdulm3003/llama3"
"abrahammg/llama3-gl-chat"
"adrienbrault/nous-hermes2pro-llama3-8b-test"
"adrienbrault/nous-hermes2pro-llama3-8b"
"adrienbrault/nous-hermes2theta-llama3-8b"
"adsfaaron/llama3-taide-lx-8b-chat-alpha"
"aibangjuxin/llama3"
"amithmkini/llama3-64k"
"anton96vice/av-tg-llama3-instr-4q"
```
There is no "library/llama3" repository.

**Comment by AmarkanthJinna** [comment]
Hi, Please help me.

ollama run llama3

pulling manifest
Error: pull model manifest: Get "https://registry.ollama.ai/v2/library/llama3/manifests/latest": dial tcp 104.21.75.227:443: I/o timed out

I'm behind corporate proxy

[http://proxy.ebiz.corporate.com:80](http://proxy.ebiz.corporate.com/)

Is this proxy issue? How can I add proxy here on my linux machine

**Comment by ccxuy** [comment]
@AmarkanthJinna 
Same here:

```
ollama run llama3.1
pulling manifest
Error: pull model manifest: Get "https://registry.ollama.ai/v2/library/llama3.1/manifests/latest": dial tcp 172.67.182.229:443: i/o timeout

                                                                                                                                                                     
 1 > curl -s "https://registry.ollama.ai/v2/library/llama3.1/manifests/latest"


The model you are attempting to pull requires a newer version of Ollama.

Please download the latest version at:

        https://ollama.com/download

```

**Comment by gmsurendra** [comment]
I am having the same issue, I am able to do the curl for the URL. 
but ollama is erroring with time out error.

OS: Windows 

**CURL successful** 

```

C:\Users\XXXXXX>curl -s https://registry.ollama.ai/v2/library/phi3/manifests/latest
{"schemaVersion":2,"mediaType":"application/vnd.docker.distribution.manifest.v2+json","config":{"digest":"sha256:23291dc44752bac878bf46ab0f2b8daf75c710060f80f1a351151c7be2f5ee0f","mediaType":"application/vnd.docker.container.image.v1+json","size":483},"layers":[{"digest":"sha256:633fc5be925f9a484b61d6f9b9a78021eeb462100bd557309f01ba84cac26adf","mediaType":"application/vnd.ollama.image.model","size":2176177120},{"digest":"sha256:fa8235e5b48faca34e3ca98cf4f694ef08bd216d28b58071a1f85b1d50cb814d","mediaType":"application/vnd.ollama.image.license","size":1084},{"digest":"sha256:542b217f179c7825eeb5bca3c77d2b75ed05bafbd3451d9188891a60a85337c6","mediaType":"application/vnd.ollama.image.template","size":148},{"digest":"sha256:8dde1baf1db03d318a2ab076ae363318357dff487bdd8c1703a29886611e581f","mediaType":"application/vnd.ollama.image.params","size":78}]}
```
**Timeout from Ollama**

C:\Users\XXXX>ollama pull phi3
pulling manifest
Error: pull model manifest: Get "https://registry.ollama.ai/v2/library/phi3/manifests/latest": dial tcp 172.67.182.229:443: i/o timeout

**Comment by dhiltgen** [comment]
@gmsurendra that might be a proxy problem.  If you have a proxy in your environment, can you try these instructions https://github.com/ollama/ollama/blob/main/docs/faq.md#how-do-i-use-ollama-behind-a-proxy

**Comment by saiprem-A** [comment]
Follow these steps it worked for me:
step 1: Stop ollama service

sudo systemctl ollama.service

step 2: launch ollama separate terminal

ollama serve

step3: pull the model
ollama pull llama3.1 will work now

**Comment by InfernalAzazel** [comment]
Set proxy

![image](https://github.com/user-attachments/assets/dd2d73a7-d926-4ac2-88ac-2fe47d2b6ec1)

```shell
$ curl -s https://registry.ollama.ai/v2/library/phi3/manifests/latest
{"schemaVersion":2,"mediaType":"application/vnd.docker.distribution.manifest.v2+json","config":{"digest":"sha256:23291dc44752bac878bf46ab0f2b8daf75c710060f80f1a351151c7be2f5ee0f","mediaType":"application/vnd.docker.container.image.v1+json","size":483},"layers":[{"digest":"sha256:633fc5be925f9a484b61d6f9b9a78021eeb462100bd557309f01ba84cac26adf","mediaType":"application/vnd.ollama.image.model","size":2176177120},{"digest":"sha256:fa8235e5b48faca34e3ca98cf4f694ef08bd216d28b58071a1f85b1d50cb814d","mediaType":"application/vnd.ollama.image.license","size":1084},{"digest":"sha256:542b217f179c7825eeb5bca3c77d2b75ed05bafbd3451d9188891a60a85337c6","mediaType":"application/vnd.ollama.image.template","size":148},{"digest":"sha256:8dde1baf1db03d318a2ab076ae363318357dff487bdd8c1703a29886611e581f","mediaType":"application/vnd.ollama.image.params","size":78}]}
```
error
```shell
ollama run qwen2.5
pulling manifest 
Error: pull model manifest: Get "https://registry.ollama.ai/v2/library/qwen2.5/manifests/latest": proxyconnect tcp: dial tcp 127.0.0.1:7890: connect: connection refused
```

**Comment by InfernalAzazel** [comment]
> @InfernalAzazel currently Ollama does not read the [system proxy setting](https://github.com/ollama/ollama/issues/5354) and requires an [environment variable for the server](https://github.com/ollama/ollama/blob/main/docs/faq.md#how-do-i-use-ollama-behind-a-proxy). If you set the variables it should work.

This variable exists

![image](https://github.com/user-attachments/assets/bc23f752-3795-4277-b5db-9bb847d10d5d)

**Comment by InfernalAzazel** [comment]
> @InfernalAzazel currently Ollama does not read the [system proxy setting](https://github.com/ollama/ollama/issues/5354) and requires an [environment variable for the server](https://github.com/ollama/ollama/blob/main/docs/faq.md#how-do-i-use-ollama-behind-a-proxy). If you set the variables it should work.

I solved it via docker proxy

```shell
docker run -d -e HTTPS_PROXY=https://my.proxy.example.com -p 11434:11434 ollama-with-ca
```
How can I cleanly uninstall ollama that I installed locally through the shell?

**Comment by dhiltgen** [comment]
@InfernalAzazel uninstall instructions are located here - https://github.com/ollama/ollama/blob/main/docs/linux.md#uninstall

Getting proxy configuration right can be tricky.  Glad to hear you got it working.

**Comment by Noarchees** [comment]
I resolved if add paramaters bellow to `system edit ollama`.

```
[Service]
Environment="HTTP_PROXY=http://<proxyserver>:<port>" 
Environment="HTTPS_PROXY=http://<proxyserver>:<port>"
```

ollama restart
```
$ systemctl daemon-reload
$ systemctl restart ollama
```

**Comment by BombFoolGranny** [comment]
For those of you using docker, try getting inside the container: `docker exec -it $OLLAMA_CONTAINER_ID /bin/bash`
And then restart ollama there by killing its process. I did it once and got it all fixed
