### ISSUE TITLE
TLS handshake timeout when pulling models

### ISSUE THREAD

**Issue by Shzyhao** [ollama/ollama#3820]
### What is the issue?

使用控制台下载模型的时候，大部分时间速度很慢且会提示TLS handshake timeout，电脑的正常网络速度为50M/S，但是在下载模型的时候大部分时间速度都是300K/S以下，所有的模型都是这样的情况

When using the console to download the model, most of the time the speed is very slow and will prompt TLS handshake timeout, the normal network speed of the computer is 50M/S, but most of the time when downloading the model, the speed is below 300K/s, all models are like this

![image](https://github.com/ollama/ollama/assets/77272241/26ea76e9-755a-4207-a93c-28ccc284d824)

### OS

Windows

### GPU

Nvidia

### CPU

AMD

### Ollama version

0.1.32

**Comment by jmorganca** [comment]
Merging with https://github.com/ollama/ollama/issues/3504
