### ISSUE TITLE
No unicode output on windows when redirecting stdout

### ISSUE THREAD

**Issue by xdanielc** [ollama/ollama#3826]
### What is the issue?

On windows I can't output unicode symbols into a txt file, the console looks fine but when I do something like 

```ollama run llama3 "Cuéntame una historia" > test.txt```

### OS

Windows

### GPU

Nvidia

### CPU

Intel

### Ollama version

0.1.32

**Comment by Katzenwerfer** [comment]
Hello, I've found myself stuck with this issue when working with ollama in a PowerShell script. I wonder if anyone has found a workaround to it or if there has been any progress towards a fix.
