### ISSUE TITLE
ending a line with ` starts a new line that can't be exited

### ISSUE THREAD

**Issue by lucianthorr** [ollama/ollama#3829]
### What is the issue?

I was trying to find a way to enter multi-line text and tried the powershell solution of ending a line with `
The line was not evaluated and I was prompted to "Enter new command" but nothing after the tilda was evaluated and I was unable to quit Ollama.  Cmd+Q didn't even work.

### OS

macOS

### GPU

Apple

### CPU

Apple

### Ollama version

0.1.32

**Comment by pdevine** [comment]
I tried this in both Windows Powershell and in Terminal and couldn't duplicate it.

If you want to do multiline, you can start a line with """. It also should work with cut+paste (we use bracketed paste mode in the CLI). I'm going to go ahead and close the issue, but please keep commenting/re-open if I missed something.
