### ISSUE TITLE
looking forward to a web ui

### ISSUE THREAD

**Issue by chadqiu** [ollama/ollama#3830]
I’m looking forward to a web UI that is more convenient for playing with the LLMs.

**Comment by tigerlcl** [comment]
I've been using [this one](https://github.com/open-webui/open-webui) for a while on my Macbook + Docker desktop

**Comment by dhiltgen** [comment]
As noted above, there are many great UIs developed in the community.  Also see https://github.com/ollama/ollama/issues/875#issuecomment-1778045758
