### ISSUE TITLE
Upsert to Vector Store Error: 404

### ISSUE THREAD

**Issue by thedavc** [ollama/ollama#3831]
### What is the issue?

I'm running into the 404 error when upserting into Flowise Vector Store. The system does not seem to register the call. In the server logs, I can see that the chat api is working as expected but not the embed. 

{"function":"print_timings","level":"INFO","line":290,"msg":"generation eval time =    6108.93 ms /   236 runs   (   25.89 ms per token,    38.63 tokens per second)","n_decoded":236,"n_tokens_second":38.631969919445794,"slot_id":0,"t_token":25.885296610169494,"t_token_generation":6108.93,"task_id":257,"tid":"5144","timestamp":1713806786}
{"function":"print_timings","level":"INFO","line":299,"msg":"          total time =    6249.46 ms","slot_id":0,"t_prompt_processing":140.531,"t_token_generation":6108.93,"t_total":6249.461,"task_id":257,"tid":"5144","timestamp":1713806786}
{"function":"update_slots","level":"INFO","line":1648,"msg":"slot released","n_cache_tokens":298,"n_ctx":2048,"n_past":297,"n_system_tokens":0,"slot_id":0,"task_id":257,"tid":"5144","timestamp":1713806786,"truncated":false}
{"function":"log_server_request","level":"INFO","line":2741,"method":"POST","msg":"request","params":{},"path":"/completion","remote_addr":"127.0.0.1","remote_port":53510,"status":200,"tid":"5268","timestamp":1713806786}
[GIN] 2024/04/22 - 10:26:26 | 200 |    6.2526428s |    192.168.86.1 | POST     "/api/chat"
[GIN] 2024/04/22 - 10:26:37 | 404 |            0s |    192.168.86.1 | POST     "//api/embeddings"
[GIN] 2024/04/22 - 10:26:37 | 404 |            0s |    192.168.86.1 | POST     "//api/embeddings"
[GIN] 2024/04/22 - 10:26:38 | 404 |            0s |    192.168.86.1 | POST     "//api/embeddings"

### OS

Linux, Windows

### GPU

Nvidia

### CPU

Intel

**Comment by thedavc** [comment]
It looks like the ip address to the chat vs embedding domain are set differently. One has and extra /. How do I align the domains so that they are the same.

**Comment by jmorganca** [comment]
From this it seems that you might have a leading `/`: `POST "//api/embeddings"` 

When setting the base url for Ollama, try to remove the trailing `/`

Let me know if this helps!

**Comment by ChenZhen1999** [comment]
I had the same problem, did you solve it please?😭
