### ISSUE TITLE
Don't attempt to load a model larger than physical memory + VRAM which will result in thrashing

### ISSUE THREAD

**Issue by maa105** [ollama/ollama#3837]
### What is the issue?

I have a Nvidia 3070 GPU with 8GB vram. when running lama3 I notice the GPU vram fills ~7GB but the compute remains at 0-1% and 16 cores of my CPU are active. leading me to conclude that the model is running purely on the CPU and not using the GPU.

### OS

Linux

### GPU

Nvidia

### CPU

Intel

### Ollama version

0.1.31

**Comment by markhill343** [comment]
The 70B should be around ~50GB. So your GPU can only help the CPU. The GPU works with the 7GB it loads into the VRAM. The remaing part is stored in the system ram and only you CPU can process that. Thats why it looks like you GPU is doing nothing. You should try the 8B model for better performance.

**Comment by siakc** [comment]
> The 70B should be around ~50GB. So your GPU can only help the CPU. The GPU works with the 7GB it loads into the VRAM. The remaining part is stored in the system ram and only you CPU can process that. That's why it looks like you GPU is doing nothing. You should try the 8B model for better performance.

I have the same issue. If you were right the memory would have been filled with other 65 GBs and cores under heavy load but that is not the case.

I see heavy disk I/O by ollama instead. This must be the bottleneck.

**Comment by easp** [comment]
How much *RAM* do you actually have?

**Comment by easp** [comment]
`llm_load_tensors:        CPU buffer size = 38110.61 MiB`

38110.61 MiB > 32GB.

You have heavy disk I/O because you don't have enough RAM. Your CPU is idle because it's waiting for at least 6GB of model weights to be loaded from disk for every token generated. Your GPU is idle because it is waiting for the CPU.

Your RAM utilization probably looks low because you are looking at the wrong metric. Model weights are memory mapped. On MacOS and Linux they are counted in the file cache size.

**Comment by siakc** [comment]
38 - 32 = 6
So I have plenty of memory. This would still be a problem if the whole model should be traversed so many times for each response.

**Comment by easp** [comment]
Your math is dead backwards. 

You have 32GB of RAM. Ollama is allocating 38GB for a CPU buffer and 6GB for a CUDA buffer.

**Comment by siakc** [comment]
Ok but only 7 GBs can't be present in physical memory. Should this make it behave like this?

**Comment by easp** [comment]
The entire model is traversed for each token. As I said before, that means that 6+ GB have to be read from storage for each token. That'll probably add at least a couple of seconds per token.

**Comment by dhiltgen** [comment]
We should probably take total physical memory into consideration, and if we're clearly going to start thrashing, prevent loading the model with a clearer error message.

**Comment by siakc** [comment]
How can I see that the model file is mmapped? I used lsof but don't see the modefile in the output list.

**Comment by easp** [comment]
@siakc on linux make sure you run lsof with sudo as the model file is opened by the ollama server, which is typically running as the "ollama" user, rather than your own.

**Comment by siakc** [comment]
I did so with no gain.
