### ISSUE TITLE
JSON Mode OpenAI Compatibility 

### ISSUE THREAD

**Issue by developersdigest** [ollama/ollama#3845]
I would love to have the OpenAI compatibility for JSON mode with Ollama. Is it be possible to add in support to also allow the value of "json_object" instead of just "json".

OpenAI TS SDK when trying to use Ollama for Json mode:

Type **'"json"' is not assignable to type '"text" | "json_object"** | undefined'.

Thanks!

**Comment by jmorganca** [comment]
`json_object` should work in the OpenAI compatible API - let me know if that's not the case though! Make sure to pass in`json_object` as well to the TS SDK
