### ISSUE TITLE
Ollama super slow on macOS M1 in Docker

### ISSUE THREAD

**Issue by rb81** [ollama/ollama#3849]
### What is the issue?

Ollama running natively on macOS is excellent.
Ollama running on Docker is about 50% slower.
(Unsure if this is a bug or config issue, but I am running default settings.)

### OS

macOS

### GPU

Apple

### CPU

Apple

### Ollama version

0.1.32

**Comment by SummerShow** [comment]
you need a RTX4090，haha

**Comment by dhiltgen** [comment]
When you run Ollama as a native Mac application on M1 (or newer) hardware, we run the LLM on the GPU.

Docker Desktop on Mac, does NOT expose the Apple GPU to the container runtime, it only exposes an ARM CPU (or virtual x86 CPU via Rosetta emulation) so when you run Ollama inside that container, it is running purely on CPU, not utilizing your GPU hardware.

On PC's NVIDIA and AMD have support for GPU pass-through into containers, so it is possible for ollama in a container to access the GPU, but this is not possible on Apple hardware.

**Comment by rb81** [comment]
@dhiltgen Thanks for the clarification!

**Comment by paolocattani** [comment]
I was about to post the same question for M3. 
Thanks @dhiltgen!

**Comment by adnankaya** [comment]
> n Mac,

I think on https://ollama.com/blog/ollama-is-now-available-as-an-official-docker-image following sentence is **confusing**

> We recommend running Ollama alongside Docker Desktop for macOS in order for Ollama to enable GPU acceleration for models.

If there is an example using ollama docker that uses macOS(Apple Sillicone Chips M1, M2, M3 ..) GPU it would be great.

**Comment by dhiltgen** [comment]
@adnankaya thanks for pointing that out.  We'll get the blog cleaned up to make it clearer that docker on arm macs wont support the GPU.
