### ISSUE TITLE
Save command in repl allows invalid model names (such as "-h")

### ISSUE THREAD

**Issue by Chiuuu0209** [ollama/ollama#3852]
### What is the issue?

I misuse the -h flag in a llama3 session

I want to see the usage of `/save` in a session so i type `/save -h` .Thus i have saved a session name `-h`
```
$ollama list
NAME            ID              SIZE    MODIFIED
-h:latest       c36f2d34d11b    4.7 GB  18 minutes ago
llama3:latest   a6990ed6be41    4.7 GB  53 minutes ago
```
Now i can not remove it by 
```
ollama rm -h
```
I try to remove it by ID but it seems not support this feature now.

What else can i do for this problem.

### OS

Linux

### GPU

Nvidia

### CPU

Intel

### Ollama version

0.1.32

**Comment by jmorganca** [comment]
Hi there, I'm sorry this happened. You can remove it manually by erasing `/usr/share/ollama/.ollama/models/manifests/-h`

Let me know if that works. I'll keep this issue open until we fix the `/save` syntax

**Comment by Chiuuu0209** [comment]
I manually remove my model but it was in `/usr/share/ollama/.ollama/models/manifests/registry.ollama.ai/library` rather than `/usr/share/ollama/.ollama/models/manifests/-h`

But thing gonna work well.

Appreciate your reply.
