### ISSUE TITLE
support 128k context length phi3

### ISSUE THREAD

**Issue by lostmygithubaccount** [ollama/ollama#3853]
I might be misinterpreting, but it looks like only the 4k context length phi3 model is supported currently: https://ollama.com/library/phi3

(at least without downloading the weights separately and creating a Modelfile)

**Comment by thinkverse** [comment]
Ollama has to wait for the upstream llama.cpp backend (https://github.com/ggerganov/llama.cpp/issues/6849#issuecomment-2072860077) to support it first.

**Comment by lostmygithubaccount** [comment]
ah thanks, will follow along there as well

**Comment by napa3um** [comment]
https://www.reddit.com/r/LocalLLaMA/comments/1cxi14h/phi3_128k_model_support_merged_into_llamacpp/

**Comment by mirandadam** [comment]
128k context is now available for phi3 mini, small, medium and vision:
https://azure.microsoft.com/en-us/blog/new-models-added-to-the-phi-3-family-available-on-microsoft-azure/
I commented here just to make sure those are taken into consideration since when this issue was first opened, only mini was available.

**Comment by hchasens** [comment]
> Ollama has to wait for the upstream llama.cpp backend ([ggerganov/llama.cpp#6849 (comment)](https://github.com/ggerganov/llama.cpp/issues/6849#issuecomment-2072860077)) to support it first.

I just got added. Next Ollama release with a pull from the llamacpp mainline we'll get support.

**Comment by napa3um** [comment]
https://github.com/ollama/ollama/issues/4574 - But will this problem go away in 0.1.39? In 0.1.38-rc2 it is present

**Comment by jmorganca** [comment]
https://ollama.com/library/phi3:mini-128k
https://ollama.com/library/phi3:medium-128k
