### ISSUE TITLE
can not start

### ISSUE THREAD

**Issue by userandpass** [ollama/ollama#3864]
### What is the issue?

when I used 'CUDA_VISIBLE_DEVICES=0 ollama run qwen:7b', it starts normally.But I used 'sudo systemctl start ollama',it does not start properly

### OS

Linux

### GPU

Nvidia

### Ollama version

0.1.32

**Comment by dhiltgen** [comment]
Ollama is a client-server architecture, and no inference is taking place in the client.  That happens in the server.  The environment variable CUDA_VISIBLE_DEVICES will only affect the server (`ollama serve`) , not the client (`ollama run`)

Can you share your server logs so we can see what the startup failure is?

**Comment by dhiltgen** [comment]
If you're still having trouble, please share you server log and I'll reopen the issue.
