### ISSUE TITLE
Ctrl+D to exit is not stopping service

### ISSUE THREAD

**Issue by nishithshowri006** [ollama/ollama#3867]
### What is the issue?

I have observed that when we Cntrl+D or exit the chat interface when we run a model it is not stopping the ollama process. This inturn is blocking RAM and VRAM for other tasks. I observed this behavior in wsl and windows versions of ollama. 

### OS

Windows, WSL2

### GPU

Nvidia

### CPU

Intel

### Ollama version

0.1.32

**Comment by dhiltgen** [comment]
Ollama is a client-server architecture, and the server continues to run after the client exits.  By default, models are retained for 5 minutes, but this is [configurable](https://github.com/ollama/ollama/blob/main/docs/faq.md#how-do-i-keep-a-model-loaded-in-memory-or-make-it-unload-immediately).  On windows, the server is managed by the System Tray application.  You can quit from the Tray, and that will unload the server and free up system and gpu memory immediately.  On WSL2, it runs as a system service in Linux, which you can stop with `systemctl stop ollama`
