### ISSUE TITLE
Failure to Load Llava in Ollama Windows Ver.

### ISSUE THREAD

**Issue by PasserDreamer** [ollama/ollama#3870]
### What is the issue?

I encountered an issue when attempting to load the 'llava' AI model; however, others such as 'Llama3' or 'Phi3' have no problem. Here are the details:
```
>>ollama run llava
Error: llama runner process no longer running: 1
```
server.log
```
...
clip_model_load: CLIP using CUDA backend
clip_model_load: text_encoder:   0
clip_model_load: vision_encoder: 1
clip_model_load: llava_projector:  1
clip_model_load: model size:     595.49 MB
clip_model_load: metadata size:  0.14 MB
clip_model_load: params backend buffer size =  595.49 MB (377 tensors)
cannot open model file for loading tensors
{"function":"load_model","level":"ERR","line":398,"model":"D:\\Llama\\models\\blobs\\sha256-72d6f08a42f656d36b356dbe0920675899a99ce21192fd66266fb7d82ed07539","msg":"unable to load clip model","tid":"162240","timestamp":1713942368}
time=2024-04-24T15:06:08.293+08:00 level=ERROR source=routes.go:120 msg="error loading llama server" error="llama runner process no longer running: 1 "
```

### OS

Windows

### GPU

Nvidia

### CPU

AMD

### Ollama version

0.1.32

**Comment by Elminsst** [comment]
same issue
![image](https://github.com/ollama/ollama/assets/130235860/376a1339-d86f-47a4-b1b9-d6c346904d23)

**Comment by dhiltgen** [comment]
The pre-release for [0.1.33](https://github.com/ollama/ollama/releases) is available now.  I'm not sure what the root cause is on this issue, but we've had a number of stability bugs in 0.1.32 on windows, so this might be resolved.  Please give it a try and let us know.

**Comment by dhiltgen** [comment]
I haven't been able to reproduce this failure.  I've tried on a Win 11 system with 0.1.33 and both llava and llava:13b run correctly on an Nvidia GPU.

@PasserDreamer does upgrading to 0.1.33 resolve the problem for you?

@Elminsst do smaller models work for you?  Is it possible your system is running out of regular RAM while loading the models leading to a crash?  Can you check Task Manager and see if there's anything else going on when this happens?  Maybe an AV product is killing the process?

**Comment by dhiltgen** [comment]
If you're still having problems, please make sure you've upgraded to the latest version and if that doesn't clear it up, please share an updated server log and I'll reopen.
