### ISSUE TITLE
Possibility to make the response leaner

### ISSUE THREAD

**Issue by KevinKrueger** [ollama/ollama#3872]
I have noticed that the return of the API if it is slightly larger in the answer due to the question, this is extremely inflated by the context, for example. A configuration option for the return parameters would be very useful here.

**Comment by pdevine** [comment]
@KevinKrueger Sorry for the slow reply; I'm a little unsure what you're asking for in the issue. You can change the parameters in your request to the API to:

1. limit the context size
2. add stop parameters

You can also tell the LLM as part of the prompt to not give as long of a reply.

I'm going to go ahead and close the issue, but we can reopen it if I didn't answer your question.
