### ISSUE TITLE
Error: pull model manifest: 401

### ISSUE THREAD

**Issue by seedpower** [ollama/ollama#3875]
### What is the issue?

OS: Ubuntu 22.04 server
ollama version: 0.1.32

Using official bash script to install it or docker method to run it,  both can't pull any model and get same next error:

```
# ollama run llama3
pulling manifest 
Error: pull model manifest: 401
```

In same network environment, my macOS system can pull llama3 model.

### OS

Linux

### GPU

Nvidia

### CPU

Intel

### Ollama version

0.1.32

**Comment by sahilchauhan123** [comment]
Same my issue but my terminal no host here

**Comment by dhiltgen** [comment]
Can you share the server log?  This sounds like a potential firewall/proxy issue.

**Comment by dhiltgen** [comment]
Please make sure to update to the latest version, and if you're still having problems, share the server log and I'll reopen.

**Comment by skye-code** [comment]
Hello, i have the same issue with Ollama v0.1.43 on win11 locally, my models work fine but i can't pull or run any new models I get=> pulling manifest 
Error: pull model manifest: 401
[server.log](https://github.com/user-attachments/files/15818762/server.log)

**Comment by simschmid** [comment]
same here on win11. Neither the docker- nor the windows-version is able to pull models.

**Comment by newskyforest** [comment]
sure, after using ntpdate tool,  system clock synchronization.  The problem was solved.

**Comment by mrkanet** [comment]
Same problem and worked with the solution: "After checking the system clock it worked for me 🤦"

**Comment by greencounlimited** [comment]
I just turned my Firewall off and it worked!!! But I suggest to re-enable it after installing because ollama still works after that.

**Comment by rahmat-ullah** [comment]
I had the same issue; my issue was fixed after updating the date and time.

**Comment by Oak-AN** [comment]
after getting `Error: pull model manifest: 401` I ran these commands to sync the clock and everything worked

```sh
timedatectl status
sudo timedatectl set-ntp true
sudo systemctl restart systemd-timesyncd
```

**Comment by lonicerae** [comment]
> after getting `Error: pull model manifest: 401` I ran these commands to sync the clock and everything worked
> 
> timedatectl status
> sudo timedatectl set-ntp true
> sudo systemctl restart systemd-timesyncd

This is the great reply that saves me!
