### ISSUE TITLE
The Ollama on the Mac computer does not have a Setting button.

### ISSUE THREAD

**Issue by liubin595338764** [ollama/ollama#3905]
### What is the issue?

<img width="159" alt="image" src="https://github.com/ollama/ollama/assets/5274428/b6bb0c43-5d3c-45ac-b573-8a2d2a875969">

我的mac电脑上的Ollama没有Setting按钮，这可能是一个问题，Ollama下载安装的时候有区分Inter芯片和Apple芯片吗，我并没有看到这个选择，我是Mac M1 Pro

<img width="270" alt="image" src="https://github.com/ollama/ollama/assets/5274428/6abe8a7c-0316-483a-bb34-130e99a69889">

### OS

macOS

### GPU

Apple

### CPU

Apple

### Ollama version

ollama version is 0.1.32

**Comment by igo** [comment]
@liubin595338764 is it working? I still don't see it

**Comment by peter2office** [comment]
the same with you, will anybody be kindly to help us?
