### ISSUE TITLE
ollama can not run the custom model (finetune on llama3) on M1 max

### ISSUE THREAD

**Issue by TobyYang7** [ollama/ollama#3909]
### What is the issue?

❯ ollama run InsuranceGPT "What is your favourite condiment?"
Error: llama runner process no longer running: -1 error:check_tensor_dims: tensor 'blk.0.attn_k.weight' has wrong shape; expected  4096,  4096, got  4096,  1024,     1,     1

### OS

macOS

### GPU

Apple

### CPU

Apple

**Comment by TobyYang7** [comment]
❯ ollama create InsuranceGPT -f Modelfile
transferring model data 
creating model layer 
creating template layer 
using already created layer sha256:9ff789dfa477f6c77a5e6a8e4be66df28d824c18cf84e24d1b14aac2d067e950 
writing layer sha256:26fc224b78fce98e2c791de92ec7687171a7b46236f34faa64227cf9c2cfa4ac 
writing layer sha256:8854ff53cb2acccb83c87e946efc533a82b038d6d243caddd7ed0ba2e766ef84 
writing manifest 
success 
❯ ollama run InsuranceGPT "What is your favourite condiment?"
Error: llama runner process no longer running: -1 error:check_tensor_dims: tensor 'blk.0.attn_k.weight' has wrong shape; expected  4096,  4096, got  4096,  1024,     1,     1

**Comment by Shrijeeth** [comment]
Facing same issue for code-gemma-7B gguf model
`Error: llama runner process no longer running: -1 error:check_tensor_dims: tensor 'blk.0.attn_q.weight' has wrong shape; expected  3072,  3072, got  3072,  4096,     1,     1`

**Comment by pdevine** [comment]
@TobyYang7 or @Shrijeeth sorry for the slow response for the issue. Do either of you have the gguf file / modelfile that exhibits the problem? I'm guessing it's an issue w/ an improperly converted gguf file.

**Comment by pdevine** [comment]
I'm going to go ahead and close the issue.
