### ISSUE TITLE
JSON list of available models

### ISSUE THREAD

**Issue by ricardobalk** [ollama/ollama#3922]
I saw that there's a list of available models at https://ollama.com/library. Is there a JSON-formatted file for this list? I would like to integrate it into a Python application I'm building.

**Edit: I forgot to mention that I with _file_, I actually mean a _JSON-formatted response on a public endpoint_, so that my Python application can always download an up-to-date list of available models.**

**Comment by akazwz** [comment]
Official support is not yet available. However, based on the information from the official website, I have created a public API. The link is [https://ollama-models.zwz.workers.dev](https://ollama-models.zwz.workers.dev). It is open-source, and the repository can be found at [https://github.com/akazwz/ollama-models](https://github.com/akazwz/ollama-models). You can also deploy one yourself. This is a solution until an official one is provided.

**Comment by ricardobalk** [comment]
@akazwz You're amazing! Thank you for building this so quickly.

P.S. I saw that you update it every 1h, perhaps it's better to pull updates every 12-72h as the list does not update that much each day. Not sure if your service would get blocked for the amount of requests 🙈

**Comment by akazwz** [comment]
@ricardobalk Yes, I agree. We can adjust the update frequency to every 24 hours.

**Comment by jmorganca** [comment]
closing for https://github.com/ollama/ollama/issues/1070 - thanks for the issue!

**Comment by onigetoc** [comment]
It do not seem to update anymore.
2 month ago?

**Comment by agustinsacco** [comment]
Absolute legend, thanks for putting that together 👍
