### ISSUE TITLE
ERROR: NO SUCH HOST 

### ISSUE THREAD

**Issue by Jinish2170** [ollama/ollama#3932]
### What is the issue?

pulling manifest
Error: Head "https://dd20bb891979d25aebc8bec07b2b3bbc.r2.cloudflarestorage.com/ollama/docker/registry/v2/blobs/sha256/97/970aa74c0a90ef7482477cf803618e776e173c007bf957f635f1015bfcfef0e6/data?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=66040c77ac1b787c3af820529859349a%!F(MISSING)20240426%!F(MISSING)auto%!F(MISSING)s3%!F(MISSING)aws4_request&X-Amz-Date=20240426T050008Z&X-Amz-Expires=1200&X-Amz-SignedHeaders=host&X-Amz-Signature=2b58511832acfa13fc84fcc46b1158ae5aea40ad8680493fbef6e1e9929f0ca0": dial tcp: lookup dd20bb891979d25aebc8bec07b2b3bbc.r2.cloudflarestorage.com: no such host

### OS

Windows

### GPU

Intel

### CPU

Intel

### Ollama version

 version is 0.1.32

**Comment by pragnesh-singh-rajput** [comment]
I am facing the same issue can't figure out what to do???

**Comment by Jinish2170** [comment]
I recently find out it was a server error and its solved by itself  !!

**Comment by dhiltgen** [comment]
Looks like a dup of #3504

**Comment by mursaleen-nisar** [comment]
I have same issue in my macOS
