### ISSUE TITLE
ERROR:The handle is invalid

### ISSUE THREAD

**Issue by Davidmax2023** [ollama/ollama#3935]
### What is the issue?

when i run ollama ,get error information as below:
"failed to get console mode for stdout: The handle is invalid.
failed to get console mode for stderr: The handle is invalid."

### OS

Windows

### GPU

Intel

### CPU

Intel

**Comment by dhiltgen** [comment]
Is there anything unusual in how you're running the `ollama` CLI?  We attempt to discover the console mode on windows so we can adjust the mode to enable ANSII escape codes to support our progress reporting, and interactivity.  Is the CLI otherwise working properly?

**Comment by johnstrand** [comment]
When I run `ollama run <model> "some input" > myFile.txt` or `ollama run <model> "some input" | Out-File myFile.txt` the first line of the file will be `failed to get console mode for stdout: The handle is invalid.` 

I've tried via Windows Terminal and VS Code's built in terminal, both with the same result. The output of the run is added to the command as expected.

The processing indicator is still shown in the console window as well. Aside from the errant line I can't see anything strange in the output or behavior.

**Comment by dhiltgen** [comment]
Thanks for clarifying.  Yes, we appear to have a bug in how we're trying to discover the console in windows when you redirect to a file.  This is effectively a dup of #3826

**Comment by chhaya-jay-56** [comment]
how to fix the bro if you know ?
