### ISSUE TITLE
``/load`` with no parameters to clear chat context

### ISSUE THREAD

**Issue by renauddetry** [ollama/ollama#3937]
It would be fantastic to have a command that clears a chat's context.

At the moment, getting a fresh context can be done with

- ``/bye``, then starting the client again. Few keystrokes, but long wait time for the model to be reloaded.
- ``/load <model>``, where ``<model>`` is the name of the most recently loaded model. Fast (same model stays in memory), but many keystrokes, especially with non-latest models.

As discussed [here](https://github.com/ollama/ollama/issues/1751), it would be great to add a ``/load`` command (no parameters) which has the same effect as ``/load <most recent model>``.

Thank you for ollama, it's awesome!

**Comment by brycereitano** [comment]
I had a desire for something like this as well. What about a command `/clear` that removes your chat history, or are you wanting it to keep the initial session info that could be saved in the modelfile?

**Comment by renauddetry** [comment]
For my use, /clear that removes chat history is perfect! Many thanks!
