### ISSUE TITLE
Massive performance regression on 0.1.32

### ISSUE THREAD

**Issue by jsa2** [ollama/ollama#3938]
### What is the issue?

Hi  dear developers! 

Spent some time trying to figure out if it was some other dependency but it seems that I get more than 10x better performance on sub 0.1.32 versions (e.g. .0.1.31) of Ollama (when creating OLLAMA embeddings and store the on FAISS)

# Setup
- Nvidia GPU (4070/4080) on mobile 
- langchain
- faiss-gpu package
- Cuda 12.1 and 12.4 (if it matters, not sure if ollama bundles cuda)

```python
import os

from langchain_community.llms import Ollama
from langchain_community.vectorstores import Chroma
from langchain_community.vectorstores import FAISS
from langchain_community.embeddings import OllamaEmbeddings
from langchain_text_splitters import CharacterTextSplitter
from langchain_community import embeddings
import torch
cuda_available = torch.cuda.is_available()
print(f"CUDA Available: {cuda_available}")
if cuda_available:
    print(f"Using CUDA Device: {torch.cuda.get_device_name(torch.cuda.current_device())}")
deviceToUse=torch.cuda.current_device()

print(torch.version.cuda)

llm = Ollama(model="llama3")

from langchain.globals import set_debug
from langchain.globals import set_verbose

set_debug(True)
set_verbose(True)

#repo_path = "docRoot"
repo_path = "docRoot/entra-docs"


# Function to load all documents in a directory and concatenate them into a single document
def load_and_merge_documents_from_directory(directory):
    merged_document = ""
    for root, _, files in os.walk(directory):
        for filename in files:
            print(filename)
            if filename.endswith(".md"):  # Assuming all files are Markdown files
                file_path = os.path.join(root, filename)
                # Open the file with error handling to replace undecodable characters
                with open(file_path, "r", encoding="utf-8", errors="replace") as file:
                    merged_document += file.read() + "\n"  # Append document content with a newline
    return merged_document.strip()  # Remove trailing newline


# Load all documents from the directory and merge them into a single document
merged_document = load_and_merge_documents_from_directory(repo_path)

# Initialize CharacterTextSplitter
text_splitter = CharacterTextSplitter(chunk_size=1000, chunk_overlap=0)

# Split the merged document into chunks
documents = text_splitter.split_text(merged_document)

# Create documents from the splits
documents = text_splitter.create_documents(documents)

# 2. Convert documents to Embeddings and store them
# Load this without reindexing (essentially can this be done without the documents param)
vectorstore = FAISS.from_documents( 
    documents=documents,
    embedding=OllamaEmbeddings(
        base_url='http://localhost:11434',
        model='nomic-embed-text',
        show_progress="true",
        num_ctx="8192",
        num_gpu=20,
        num_thread=16,
        temperature=2,
        top_k=10,
        top_p=0.5
    ),
)


vectorstore.save_local("faiss_index")

retriever = vectorstore.as_retriever()


from langchain_community.llms import Ollama



from langchain_core.runnables import RunnablePassthrough
from langchain_core.output_parsers import StrOutputParser
from langchain_core.prompts import ChatPromptTemplate

template = """Answer the question based only on the following context:
{context}
Question: {question}
"""
prompt = ChatPromptTemplate.from_template(template)
rag_chain = (
    {"context": retriever, "question": RunnablePassthrough()}
    | prompt
    | llm
    | StrOutputParser()
)
print(rag_chain.invoke("tell me about workload identities, and possible limitations when used with Conditional Access, please note CAE is not related to Workload Identities in Conditional Access"))





```

### OS

WSL2

### GPU

Nvidia

### CPU

Intel, AMD

### Ollama version

0.1.32

**Comment by shadowfaxproject** [comment]
I am experiencing similar issue after upgrading to 0.1.32. All previous versions u to 1.31 are working. 
I did some benchmarking and found the following on my existing setup:

My config: 
Chipset Model:	Apple M3 Max. 128GB RAM.
Models tested: llama3:instruct 7b,  gemma:instruct 7b
Number of prompts ran: 50. 

Ollama 0.1.24, 28, 30, 31:
Avg, time per prompt request 2.2 seconds. 
Peak GPU utilization: 90-95%
Peak CPU utilization: 10-15%

**Ollama 0.1.32:**
Avg. time per request 6.2 seconds. (up from 2.2 sec)
Peak GPU utilization: 5-10% (down from 90-95%)
Peak CPU utilization: 600-1100%  (up from 10-15%)

Clearly there is something that's changed from .31 -> .32. Looking at the release notes:
_ #"Ollama will now better utilize available VRAM, leading to less out-of-memory errors, as well as better GPU utilization
When running larger models that don't fit into VRAM on macOS, Ollama will now split the model between GPU and CPU to maximize performance."_

Attached some screenshots for utilization comparison.
<img width="885" alt="ollama version is 0 1 31-llama3" src="https://github.com/ollama/ollama/assets/145872979/f6335cf5-7b28-4582-8ccc-e506de75b3f2">
<img width="938" alt="ollama version is 0 1 32-llama3" src="https://github.com/ollama/ollama/assets/145872979/5c505334-f5c8-42da-a013-2ceb91c60ee0">

For now sticking to 0.1.31 for better performance.

**Comment by dhiltgen** [comment]
Can you check the server logs and see if the number of layers being loaded is changing between the releases where you see performance changes?

**Comment by shadowfaxproject** [comment]
@dhiltgen this is what I found in server logs that may be relevant to this:
Version 0.1.31
```
time=2024-04-26T13:24:16.861-07:00 level=INFO source=server.go:127 msg="offload to gpu" reallayers=33 layers=33
llm_load_print_meta: n_layer          = 32
llm_load_tensors: offloading 32 repeating layers to GPU
llm_load_tensors: offloading non-repeating layers to GPU
llm_load_tensors: offloaded 33/33 layers to GPU
llm_load_tensors:        CPU buffer size =    70.31 MiB
llm_load_tensors:      Metal buffer size =  3577.57 MiB
```

Version0.1.32
```
time=2024-05-01T23:17:10.421-07:00 level=INFO source=server.go:127 msg="offload to gpu" reallayers=1 layers=29
llm_load_print_meta: n_layer          = 28
llm_load_tensors: offloading 1 repeating layers to GPU
llm_load_tensors: offloaded 1/29 layers to GPU
llm_load_tensors:        CPU buffer size =  4773.90 MiB
llm_load_tensors:      Metal buffer size =   148.53 MiB
```
As you suspected, not all layers are loaded in 0.1.32 as opposed to 0.1.31. That explains the drop in performance. Also the variable `reallayers` is set to 1 in 0.1.32 vs to 33 in 0.1.31

**Comment by dhiltgen** [comment]
@shadowfaxproject can you try the latest RC of 0.1.33, and see if that improves the situation.  If not, please try running the server with OLLAMA_DEBUG=1 and share the 0.1.31 vs. 0.1.33 comparison so we can get to the root cause on why it's only loading 1 layer when it should be able to fit the whole model apparently.

https://github.com/ollama/ollama/releases

**Comment by dhiltgen** [comment]
@jsa2 are you still seeing problems?  Is the `num_gpu=1` issue the same for you?  If that's not it, but you still see perf problems, can you share your server log?

**Comment by shadowfaxproject** [comment]
When I change `num_gpu=30` or do not provide provide that param when calling Ollama constructor I do not see perf issue. But when I was using `num_gpu=1` I consistently encountered this drop in performance.

**Comment by dhiltgen** [comment]
@shadowfaxproject that sounds correct.  num_gpu defaults to -1 which indicates "automatic" mode and we try to load as many layers as will fit.  num_gpu=0 effectively turns off GPU processing, and any number greater than zero loads exactly that many layers of the model.  

I didn't realize we had a bug in prior versions where "1" wasn't being respected properly to load only a single layer.

**Comment by jsa2** [comment]
Here is screenshot from 0.31, where I get much better performance

![image](https://github.com/ollama/ollama/assets/58001986/daca256e-c040-43d7-ae0f-dd508d35ae50)

**Comment by dhiltgen** [comment]
@jsa2 can you clarify?  From the output above it looks like we are loading all 13 layers (in both cases?) yet you still see a performance regression in the newer release?  If that's correct, then it sounds like the layer count isn't the root cause and there's something else going on leading to a performance impact.  If that sounds correct, what I'd suggest is do a back-to-back comparison between the 2 versions with OLLAMA_DEBUG=1 set so we can compare the server logs and see if it's a misconfiguration glitch, or if the config is the same, which would tend to indicate some behavioral change or performance regression in llama.cpp perhaps.

**Comment by jsa2** [comment]
I noticed (as pointed out by another AI model) when comparing both runs, 

**Older versions:**
ggml_cuda_init: GGML_CUDA_FORCE_MMQ:    YES

**New versions**
ggml_cuda_init: GGML_CUDA_FORCE_MMQ:    no
