### ISSUE TITLE
Error， Mac

### ISSUE THREAD

**Issue by wisepmlin** [ollama/ollama#3941]
Error: pull model manifest: Get "https://ollama.com/token?nonce=LTH6KgpTcEEggi0dbroPRA&scope=repository%!A(MISSING)library%!F(MISSING)llama3%!A(MISSING)pull&service=ollama.com&ts=1714130846": read tcp 192.168.188.104:63236->34.120.132.20:443: read: connection reset by peer

**Comment by dhiltgen** [comment]
Looks like a dup of #3504
