### ISSUE TITLE
The parameter is incorrect

### ISSUE THREAD

**Issue by nb001** [ollama/ollama#3967]
### What is the issue?

No matter which model I run, I always end up with: The parameter is incorrect.
![360截图20240427060248](https://github.com/ollama/ollama/assets/39027571/30d41372-4134-4dd4-9a6b-51f78ad0ebb8)
![360截图20240427060209](https://github.com/ollama/ollama/assets/39027571/5451517a-adc7-4646-a55d-1e30e3f19b5d)

OS: windows 10
GPU: Radeon RX 560 Series

### OS

Windows

### GPU

AMD

### CPU

Intel

### Ollama version

0.1.32

**Comment by Schirilla** [comment]
I have the same problem and I suspect it is a problem with the command-shell. Tried with Windows command-shell and PowerShell, - does not work.  But it works fine if I run the command from a terminal in VSCode.

**Comment by aaamoon** [comment]
I also encountered the same problem.
https://github.com/ollama/ollama/issues/3916

**Comment by dhiltgen** [comment]
Let's track this issue in #3916

**Comment by yshx8** [comment]
I also encountered the same problem. But if I run the new Windows terminal with win 10 or 11, it can run, and the old CMD will get the same error (machine translation)

**Comment by yshx8** [comment]
![image](https://github.com/ollama/ollama/assets/28306762/71f56bb1-59ce-44d5-bc2b-5e7078820f7e)

**Comment by millerlight** [comment]
not working in any shell (bash, gitbash, powershell)...

ollama run llama3.2 
←[?25l⠙ ←[?25h←[?25l←[2K←[1G⠹ ←[?25h←[?25l←[2K←[1G⠸ ←[?
25h←[?25l←[2K←[1G⠼ ←[?25h←[?25l←[2K←[1G⠴ ←[?25h←[?25l←[
2K←[1G⠦ ←[?25h←[?25l←[2K←[1G⠧ ←[?25h←[?25l←[2K←[1G⠇ ←[?
25h←[?25l←[2K←[1G⠏ ←[?25h←[?25l←[2K←[1G⠋ ←[?25h←[?25l←[
2K←[1G⠙ ←[?25h←[?25l←[2K←[1G⠹ ←[?25h←[?25l←[2K←[1G⠸ ←[?
25h←[?25l←[2K←[1G⠼ ←[?25h←[?25l←[2K←[1G⠴ ←[?25h←[?25l←[
2K←[1G⠦ ←[?25h←[?25l←[2K←[1G⠧ ←[?25h←[?25l←[2K←[1G⠇ ←[?
25h←[?25l←[2K←[1G⠏ ←[?25h←[?25l←[2K←[1G⠋ ←[?25h←[?25l←[
2K←[1G⠙ ←[?25h←[?25l←[2K←[1G⠹ ←[?25h←[?25l←[2K←[1G⠸ ←[?
25h←[?25l←[2K←[1G⠼ ←[?25h←[?25l←[2K←[1G⠴ ←[?25h←[?25l←[
2K←[1G⠦ ←[?25h←[?25l←[?25l←[2K←[1G←[?25h←[2K←[1G←[?25hE
rror: The parameter is incorrect.

**Comment by millerlight** [comment]
> I've been unable to reproduce on a 22h2 or newer win 10 or 11. Both cmd and powershell render correctly.
> 
> We've captured this minimum requirement in our windows documentation here - https://github.com/ollama/ollama/blob/main/docs/windows.md#system-requirements
> 
> Is anyone seeing the failure on 22h2, or are these all older versions?

hi daniel, 

i actualized to 22h2, so i was able to see the messages. 
i have a ryzen on my laptop. installed the adrenalin drivers (minimal).
actually the system seems to ask just for cuda (nvidia).
msg="no compatible GPUs were discovered"

any idea?

best regards

**Comment by dhiltgen** [comment]
@millerlight lets move that to a new issue.  Please share your server logs so we can see why it's not detecting your GPU.

**Comment by cookgreen** [comment]
> I've been unable to reproduce on a 22h2 or newer win 10 or 11. Both cmd and powershell render correctly.
> 
> We've captured this minimum requirement in our windows documentation here - https://github.com/ollama/ollama/blob/main/docs/windows.md#system-requirements
> 
> Is anyone seeing the failure on 22h2, or are these all older versions?

I am using the older Windows version, Windows 10 1507 which cause this problem

**Comment by cookgreen** [comment]
but if use chatbox that would be ok
