### ISSUE TITLE
error loading model architecture: unknown model architecture: 'phi3'

### ISSUE THREAD

**Issue by sanyuan0704** [ollama/ollama#3974]
### What is the issue?

When i fine-tuned the phi3 and quantize it with latest llama.cpp,  i found ollama cannot load the model:

![image](https://github.com/ollama/ollama/assets/39261479/6c1cf96f-9bd7-4436-9b92-9d76537fde58)

### OS

Linux

### GPU

Nvidia

### CPU

Intel

### Ollama version

0.1.32

**Comment by dotnetautor** [comment]
+1

**Comment by johanteekens** [comment]
+1

**Comment by mildwood** [comment]
same for me :(

**Comment by fran-pastor** [comment]
+1

**Comment by Phil-T1** [comment]
Me too.

**Comment by kroni66** [comment]
Me too

**Comment by Phil-T1** [comment]
This is due to a recent change to the microsoft/Phi-3-mini-4k-instruct-gguf model apparently.

Apologies for not being specific as I'm on the move, but I replaced the Phi3 download I did today which gave the unknown Phi3 model error, with a download from a couple of weeks ago, and the error went away.

I think Microsoft just changed the label from lama3 to phi3 in the latest version.

**Comment by robbiemu** [comment]
this discussion may be tracking the resolution: https://github.com/ggerganov/llama.cpp/issues/6849

**Comment by dhiltgen** [comment]
Initial support for phi3 was added in 0.1.32, and conversion should be working in 0.1.33. Please give the latest RC a try and let us know if you're still having problems.

https://github.com/ollama/ollama/releases

**Comment by MuazmaZ** [comment]
+1

**Comment by yorek** [comment]
Hi, I've just tried latest version 0.1.37 and now I get the following error:

```
lama_model_load: error loading model: tensor 'blk.26.ffn_up.weight' data is not within the file bounds, model is corrupted or incomplete
```

here's the Modelfile I'm using:

```
FROM ./Phi-3-mini-4k-instruct-fp16.gguf
TEMPLATE """<s>{{ if .Prompt }}<|user|>
{{ .Prompt }}<|end|>
{{ end }}<|assistant|>
{{ .Response }}<|end|>"""
PARAMETER stop <|endoftext|>
PARAMETER stop <|assistant|>
PARAMETER stop <|end|>
PARAMETER num_ctx 4096
```

the GGUF file is coming from the Hugging Face MS repo:

https://huggingface.co/microsoft/Phi-3-mini-4k-instruct-gguf/tree/main

Thanks

**Comment by jmorganca** [comment]
Hi all this should be fixed now. Sorry about the errors - let me know if you're still seeing it on the latest version of Ollama
