### ISSUE TITLE
When used, it is always cpu full instead of gpu full, and gpu usage is almost zero

### ISSUE THREAD

**Issue by KritoAndAsuna** [ollama/ollama#3975]
### What is the issue?

When used, it is always cpu full instead of gpu full, and gpu usage is almost zero

### OS

Windows

### GPU

AMD

### CPU

AMD

### Ollama version

0.1.32

**Comment by helium729** [comment]
this usually happens when you VRAM is not enough

**Comment by dhiltgen** [comment]
@KritoAndAsuna we'll need some more information.  What type of GPU do you have, and how much VRAM does it have?  What model are you trying to load?  As @helium729 mentioned, if you're trying to load a model that doesn't fit in VRAM, some of it will be loaded in system memory and will be processed by the CPU, which is typically much slower than the GPU, so the GPU winds up waiting most of the time for the CPU to process its portion.  If you look in the server log, you'll see a line that looks something like this:
```
llm_load_tensors: offloaded 33/33 layers to GPU
```

**Comment by GreatBigWhiteWorld** [comment]
> @KritoAndAsuna we'll need some more information. What type of GPU do you have, and how much VRAM does it have? What model are you trying to load? As @helium729 mentioned, if you're trying to load a model that doesn't fit in VRAM, some of it will be loaded in system memory and will be processed by the CPU, which is typically much slower than the GPU, so the GPU winds up waiting most of the time for the CPU to process its portion. If you look in the server log, you'll see a line that looks something like this:
> 
> ```
> llm_load_tensors: offloaded 33/33 layers to GPU
> ```

I run llama3(8B) on a machine with Nvidia 4080 super (16G VRAM), Ryzen 7800x3d and 32G ram. 
Ollama still uses 100% CPU while GPU temp stays unchanged (while GPU fans sit still). Is this GPU still not powerful enough, not even helping a bit the task at least? 

When I do `sudo journalctl -u ollama | grep llm_load_tensors`,
I get lots of messages like:
```
llm_load_tensors: ggml ctx size =    0.15 MiB
llm_load_tensors:        CPU buffer size =  4437.80 MiB
```

**Comment by dhiltgen** [comment]
Can you share more of the server log?  It sounds like it's not detecting your GPU for some reason and using the CPU runner instead.

**Comment by GreatBigWhiteWorld** [comment]
> Can you share more of the server log? It sounds like it's not detecting your GPU for some reason and using the CPU runner instead.

I did some research and added 'ollama' user to the 'video' group. Now in the ollama service log it has 'GPU detected' instead of just 'detecting GPU'. Running ollama task is also much faster and brings GPU temp up.
Is this related to how I installed ollama cause I installed it following the "manual install" steps, which don't involve adding ollama to the video group. I wonder what else I might have missed when not using the installation script.

**Comment by dhiltgen** [comment]
Glad to hear you found the problem @GreatBigWhiteWorld.  We recommend using the install script to make sure everything gets set up correctly, but you can inspect the [script itself](https://github.com/ollama/ollama/blob/main/scripts/install.sh) to see what all it does for manual setups.

Given your scenario was linux and unix permission based, it's unlikely related to @KritoAndAsuna's problem on windows.

**Comment by dhiltgen** [comment]
@KritoAndAsuna if you're still having problems, please let us know.  The new `ollama ps` command will help show how much of the model is loaded into GPU.  Performance will be significantly impacted the more of the model is running on the CPU, to the point that the GPU will appear idle as it waits for the CPU to keep up.
