### ISSUE TITLE
Wrong install directory during setup

### ISSUE THREAD

**Issue by jan-oratowski** [ollama/ollama#3980]
### What is the issue?

On Windows, when running the installer Ollama will install to the local user folder, instead of asking for a path or installing to a globally accessible directory (the one that can be accessed by every user).

This pattern is incorrect.
The installer should either give the user an option to select where to install (and ask for Admin permission), or by default install to the globally accessible directory and fallback to the user directory if not possible. Some applications will also give you an option of "Standard" and "Custom" install, where "Custom" is just "Standard", but with directory selection.

AppData is like /home/user on Linux and is used for storing application data, not application files.

This behavior leads to a huge user directory that in the end makes backups harder to do.

If nobody wants to spend time on the installer, then I can probably fix it myself and submit PR, just let me know.

### OS

Windows

### Ollama version

current

**Comment by Alphayellowcat** [comment]
The current compromise is to modify the environment variables, such as OLLAMA_MODELS

**Comment by jan-oratowski** [comment]
Thanks for the reply.

I think those are two different things.

Right now there are two directories created in the User directory:

1. Directory with Ollama - C:\Users\UserName\AppData\Local\Programs\Ollama << this one is created by installer and there is no way to change it.
2. Directory with Ollama user-related stuff - C:\User\UserName\.ollama - this directory contains pub/private key pair, history, and Models.

I understand that OLLAMA_MODELS can prevent Models from being saved to C:\User\UserName\.ollama\models and instead, you can define your own path, I guess this is fine. This will still save pub/priv key pair and history in the User directory, but I think this is how it should work.

I'm complaining about the path from point 1. It should be somewhere in C:\Program Files, in the end, it would allow all the users to use the installation (right now they can't access your User directory) and would not expose any of your previous prompts/settings, as they are saved in the directory from point 2.

What I would like to do is modify the inn file (the one that creates the installer) to require one additional step that would have questions like "How do you want to install Ollama?" with answers:

- for everyone using this computer (requires Administrator access)
- just for me (installs in your User directory)
- let me choose the directory

This way if someone is installing Ollama on a computer without Admin rights, it can still be installed the current way, but if someone wants to install it for everyone, it can be done as well.

I had previous experience with WiX installer, so had to check if it can be done in Inno as well.

I have already looked into Inno Installer and checked out some tutorials, so I can modify the installer file, test it on my own machine, and then submit the PR. Just need confirmation that it's ok with the maintainer of the repo.

**Comment by dhiltgen** [comment]
Dup of #2776
