### ISSUE TITLE
how to config octopus on ollama ?

### ISSUE THREAD

**Issue by taozhiyuai** [ollama/ollama#3992]
### What is the issue?

this is output of octopus on my MAC. anyone know how to config it for better output?

Set 'verbose' mode.
>>> hi
<nexa_end>

Response: <nexa_13>('hi')<nexa_end>

Function description: 
def search_youtube_videos(query):
    """
    Searches YouTube for videos matching a query.

    Parameters:
    - query (str): Search query.

    Returns:
    - list[str]: A list of strings, each string includes video names and 
URLs.
    """

total duration:       1.008565s
load duration:        2.621042ms
prompt eval count:    9 token(s)
prompt eval duration: 109.909ms
prompt eval rate:     81.89 tokens/s
eval count:           82 token(s)
eval duration:        890.205ms
eval rate:            92.11 tokens/s
>>> /show modelfile
# Modelfile generated by "ollama show"
# To build a new Modelfile based on this one, replace the FROM line with:
# FROM octopus-v2-q8:latest

FROM /Users/taozhiyu/.ollama/models/blobs/sha256-a85db45807a0d26b2c14753cea10f947a26196bde3770c95a2d0688b1bd6c127
TEMPLATE """{{ .System }}
USER: {{ .Prompt }}
ASSISTANT: """
PARAMETER num_ctx 4096
PARAMETER stop "</s>"
PARAMETER stop "USER:"
PARAMETER stop "\"ASSISTANT:\""

### OS

macOS

### GPU

Apple

### CPU

Apple

### Ollama version

0.1.32

**Comment by taozhiyuai** [comment]
I import gguf from https://hf-mirror.com/second-state/Octopus-v2-GGUF

**Comment by Single430** [comment]
Hello, have you solved the problem now? When I registered octopus in Ollama, the Modelfile file kept being written incorrectly, resulting in inncorrect output. Can you help me with this@taozhiyuai

**Comment by taozhiyuai** [comment]
https://ollama.com/taozhiyuai/octopus-v4 @Single430

**Comment by Single430** [comment]
> https://ollama.com/taozhiyuai/octopus-v4 @Single430 

Thank you, I saw this.
