### ISSUE TITLE
pulling manifest  Error

### ISSUE THREAD

**Issue by xinewzhou** [ollama/ollama#3994]
### What is the issue?

pulling manifest 
Error: pull model manifest: Get "https://ollama.com/token?nonce=KuhzAPbr727aW4zzdmUWPA&scope=repository%!A(MISSING)library%!F(MISSING)llama3%!A(MISSING)pull&service=ollama.com&ts=1714285350": read tcp 192.168.2.33:60544->34.120.132.20:443: read: connection reset by peer

### OS

macOS

### GPU

Apple

### CPU

Apple

### Ollama version

ollama version is 0.1.32

**Comment by 353167931** [comment]
我也出现同样的问题

**Comment by dhiltgen** [comment]
Looks like a dup of #3504
