### ISSUE TITLE
Issues with Llama3:70b Model When stream is Set to False

### ISSUE THREAD

**Issue by JIAQIA** [ollama/ollama#3995]
### What is the issue?

When the stream parameter is set to True, the Llama3:70b model functions correctly. Here is the pytest code used for testing streaming output:

```pytest
def test_ollama3_70b_original_stream_completion() -> None:
    """
    测试本地Ollama接口-流式输出
    Returns:

    """
    host = "http://localhost"
    port = 11434
    client = httpx.Client(base_url=f"{host}:{port}")
    json_info = {
        "model": "llama3:70b",
        "messages": [
            {
                "role": "user",
                "content": "Help me make a travel guide to Yosemite National Park in 200 words？",
            }
        ],
        "stream": True,
    }
    with client.stream("POST", "/api/chat", json=json_info) as response:  # noqa
        for line in response.iter_lines():
            print(line)
            print("-" * 10)
 ```
 
 For the standard Llama3(Not 70b!) model with stream set to False, the API works as expected:
 
 ```pytest
 def test_ollama3_chat_completion() -> None:
    """
    测试本地Ollama接口-普通输出
    Returns:

    """
    host = "http://localhost"
    port = 11434
    client = httpx.Client(base_url=f"{host}:{port}")
    json_info = {
        "model": "llama3",
        "messages": [
            {
                "role": "user",
                "content": "Help me make a travel guide to Yosemite National Park in 200 words？",
            }
        ],
        "stream": False,
    }
    response = client.post("/api/chat", json=json_info)
    print(response.json())
```

However, when using the Llama3:70b model with stream set to False, the request times out, resulting in an httpx.ReadTimeout exception:

```pytest
def test_ollama3_70b_chat_completion() -> None:
    """
    测试本地Ollama llama3:70b接口-普通输出
    Returns:

    """
    host = "http://localhost"
    port = 11434
    client = httpx.Client(base_url=f"{host}:{port}")
    json_info = {
        "model": "llama3:70b",
        "messages": [
            {
                "role": "user",
                "content": "Help me make a travel guide to Yosemite National Park in 200 words？",
            }
        ],
        "stream": False,
    }
    response = client.post("/api/chat", json=json_info)
    print(response.json())
```
    
FYI
Hardware:

Hardware Overview:

  Model Name: Mac Studio
  Model Identifier: Mac14,14
  Model Number: Z1800001HCH/A
  Chip: Apple M2 Ultra
  Total Number of Cores: 24 (16 performance and 8 efficiency)
  Memory: 192 GB
  System Firmware Version: 8422.141.2
  OS Loader Version: 8422.141.2
  Serial Number (system): G2P4927DXG
  Hardware UUID: D9B7B9C2-D50B-5EC6-A5BE-D6403AF1ADA2
  Provisioning UDID: 00006022-000451D90E90A01E
  Activation Lock Status: Enabled

### OS

macOS

### GPU

Apple

### CPU

Apple

### Ollama version

0.1.32

**Comment by BruceMacD** [comment]
How long does it take to generate a response in the streaming case (from start to finish)? It looks possible to me that the request is timing out due to the amount of time it takes to load the model, generate the response, and close the connection. If possible try increasing the timeout on your httpx client could help testing this.

**Comment by JIAQIA** [comment]
@BruceMacD  Very quickly, about 5s in streaming mode.

**Comment by jmorganca** [comment]
Make sure to set a large timeout as it might take time to generate the full response, e.g. 30 mins (might be too long):

```
client = httpx.Client(timeout=1800.0)
```

**Comment by JIAQIA** [comment]
I have set timeout to 1800, and it failed again.
