### ISSUE TITLE
ollama pulling manifest error  no such host

### ISSUE THREAD

**Issue by Arraj2611** [ollama/ollama#3996]
### What is the issue?

i tried to run llama3 but faced this error
Error: Head "https://dd20bb891979d25aebc8bec07b2b3bbc.r2.cloudflarestorage.com/ollama/docker/registry/v2/blobs/sha256/00/00e1317cbf74d901080d7100f57580ba8dd8de57203072dc6f668324ba545f29/data?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=66040c77ac1b787c3af820529859349a%!F(MISSING)20240428%!F(MISSING)auto%!F(MISSING)s3%!F(MISSING)aws4_request&X-Amz-Date=20240428T063641Z&X-Amz-Expires=1200&X-Amz-SignedHeaders=host&X-Amz-Signature=18a29d374357d272fe145b5a4c76b0c9cc17b5d165574dd1fa3458937879ba9d": dial tcp: lookup dd20bb891979d25aebc8bec07b2b3bbc.r2.cloudflarestorage.com: no such host

any help!!!

### OS

Windows

### GPU

Nvidia

### CPU

Intel

### Ollama version

0.1.32

**Comment by BruceMacD** [comment]
Hi @Arraj2611 sorry about this, we often see errors that look like this when trying to pull models through a proxy. Could that be the case here?

Here's some troubleshooting info: https://github.com/ollama/ollama/blob/main/docs/faq.md#how-can-i-use-ollama-with-a-proxy-server

**Comment by dhiltgen** [comment]
Looks like a dup of #3504

**Comment by BadgerBloke** [comment]
This seems to be an issue with ISP. It is highly probable that it will work with another ISP (it worked for me) but let's fix it so we don't have to switch our internet provider.

> dd20bb891979d25aebc8bec07b2b3bbc.r2.cloudflarestorage.com

Do a `Dig` [here](https://www.digwebinterface.com/) for above host and copy the IP address

<img width="776" alt="Screenshot 2024-06-04 at 10 54 35 PM" src="https://github.com/ollama/ollama/assets/52215756/9fc0f710-fb84-4061-9b18-34ed2db80a6c">


Now add the copied IP address to your host file like
`104.18.9.90        dd20bb891979d25aebc8bec07b2b3bbc.r2.cloudflarestorage.com`

For adding the value you can follow the below steps:
> 1. `sudo vim /etc/hosts`
> 2. `shift + g` to goto last line
> 3. `o`   👈🏻 this is alphabet "o" not a zero. Insert a new blank line below and change the mode to INSERT
> 4. add the values as stated above
> 5. `shift + zz` 👈🏻 this is 2 times "zz" for saving and existing

Now you should be able to pull the models by ollama

**Comment by Aditya2073** [comment]
Use this 
Windows: ipconfig /flushdns
Mac: sudo killall -HUP mDNSResponder
Linux: sudo systemd-resolve --flush-caches

**Comment by sagarbangade** [comment]
Step 1: Check DNS Settings:

Sometimes DNS settings can cause issues. Try changing your DNS server to a public one like Google DNS (8.8.8.8) or Cloudflare DNS (1.1.1.1).

Step 2: Flush DNS Cache:
Sometimes the DNS cache can cause issues. You can flush it using the following command in the command prompt:

ipconfig /flushdns

**Comment by maddhruv** [comment]
Adding DNS `8.8.8.8` in MacOS Settings worked 🎉

**Comment by azteck** [comment]
> Adding DNS `8.8.8.8` in MacOS Settings worked 🎉

Thanks! Worked for me!

**Comment by jaykhatri0875** [comment]
flushing DNS didn't work, changing network worked for me !

**Comment by amanchoudharry** [comment]
Adding DNS 8.8.8.8 
and then 
ipconfig /flushdns
in my Windows 11 Settings worked !
Thanks

![Image](https://github.com/user-attachments/assets/d6d322c7-b477-4320-8db6-0316eb3a80e1)

**Comment by UtsavMehta1975** [comment]
changing DNS server IPv4 manually to google's  8.8.8.8 wroked for me as well

**Comment by prathmeshyelne** [comment]
Use below command to change dns on MacOS :

`sudo networksetup -setdnsservers Wi-Fi 8.8.8.8 8.8.4.4`

and to reverse back use 

`sudo networksetup -setdnsservers Wi-Fi empty`

this will 100% solve your issue
