### ISSUE TITLE
ollama can't support run wizardlm2:8x22b

### ISSUE THREAD

**Issue by lizhanyang505** [ollama/ollama#3997]
### What is the issue?

ollama run wizardlm2:8x22b
Error: llama runner process no longer running: 1 error:failed to create context with model '/mnt/data1/ollama/models/blobs/sha256-cfcf93119280c4a10c1df57335bad341e000cabbc4faff125531d941a5b0befa'

+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 4090        Off |   00000000:18:00.0 Off |                  Off |
| 30%   30C    P8             20W /  450W |      47MiB /  24564MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
|   1  NVIDIA GeForce RTX 4090        Off |   00000000:51:00.0 Off |                  Off |
| 30%   27C    P8             20W /  450W |      17MiB /  24564MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
                                                                         

### OS

Linux

### GPU

Nvidia

### CPU

Intel

**Comment by helium729** [comment]
This happened to me when my VRAM is not sufficient, can you run mixtral 8x22b? or maybe you can monitor the VRAM usage while loading this model.

**Comment by itsXactlY** [comment]
Did run here on my good old 1070, make sure all is up2date on your side.

**Comment by BruceMacD** [comment]
Hi @lizhanyang505, this could have been related to a bug in our calculation of the size needed to run mixtral models (#3836). If that is the case the next release may fix your issue.

Where the context is mentioned in the error log here it might also be worth configuring the context size you're loading the model, if you have changed that previously.

**Comment by lizhanyang505** [comment]
> Did run here on my good old 1070, make sure all is up2date on your side.
The ollama version is the latest 1.3.2. It doesn’t work.

**Comment by lizhanyang505** [comment]
> Hi @lizhanyang505, this could have been related to a bug in our calculation of the size needed to run mixtral models (#3836). If that is the case the next release may fix your issue.您好，这可能与我们计算运行混合模型所需的大小 ( #3836 ) 时的错误有关。如果是这种情况，下一个版本可能会解决您的问题。
> 
> Where the context is mentioned in the error log here it might also be worth configuring the context size you're loading the model, if you have changed that previously.
![image](https://github.com/ollama/ollama/assets/49928490/fe123617-2874-470d-a82b-2ef0f2764c92)
Ollama v0.1.33 is support ?

**Comment by jmorganca** [comment]
This should be solved in 0.1.33. Let me know if that's not the case!
