### ISSUE TITLE
Phi-3-mini-128k no load

### ISSUE THREAD

**Issue by bambooqj** [ollama/ollama#3998]
model download: `https://huggingface.co/PrunaAI/Phi-3-mini-128k-instruct-GGUF-Imatrix-smashed`

modfile:
```
FROM ./Phi-3-mini-128k-instruct.Q4_K_M.gguf

PARAMETER num_ctx 65536
PARAMETER num_keep 4
PARAMETER stop <|user|>
PARAMETER stop <|assistant|>
PARAMETER stop <|system|>
PARAMETER stop <|end|>
PARAMETER stop <|endoftext|>

TEMPLATE """
{{ if .System }}<|system|>
{{ .System }}<|end|>
{{ end }}{{ if .Prompt }}<|user|>
{{ .Prompt }}<|end|>
{{ end }}<|assistant|>
{{ .Response }}<|end|>
"""
```

error: `Error: llama runner process no longer running: 3221226505`

**Comment by amonpaike** [comment]
I had the same error the first time I tried creating my own model from gguf.
Then I tried this other modified version that someone else created, and it worked.
https://ollama.com/herald/phi3-128k

**Comment by taozhiyuai** [comment]
> I had the same error the first time I tried creating my own model from gguf. Then I tried this other modified version that someone else created, and it worked. https://ollama.com/herald/phi3-128k

herald/phi3-128k works on my MAC. but fail to import phi3 gguf.

` % ollama run Phi-3-mini-128k-instruct.Q8_0:latest
Error: llama runner process no longer running: -1 error:error loading model architecture: unknown model architecture: 'phi3'`

**Comment by coder543** [comment]
The underlying library `llama.cpp` [does not support Phi-3-128k yet](https://github.com/ggerganov/llama.cpp/issues/6849#issuecomment-2074899603).

**Comment by dhiltgen** [comment]
Initial support for phi3 was added in 0.1.32, and conversion should be working in 0.1.33. Please give the latest RC a try and let us know if you're still having problems.

https://github.com/ollama/ollama/releases

**Comment by coder543** [comment]
@dhiltgen are you talking about Phi3, or Phi3-128k?

ollama mentions nothing about the 128k context model: https://ollama.com/library/phi3/tags

**Comment by taozhiyuai** [comment]
# Modelfile generated by "ollama show"
# To build a new Modelfile based on this one, replace the FROM line with:
# FROM phi-3-mini-128K-Instruct_q8_0

FROM /Users/taozhiyu/Downloads/M-GGUF/Phi-3-mini-128K-Instruct/Phi-3-mini-128K-Instruct_Q8_0.gguf
TEMPLATE """{{ if .System }}<|system|>
{{ .System }}<|end|>
{{ end }}{{ if .Prompt }}<|user|>
{{ .Prompt }}<|end|>
{{ end }}<|assistant|>
{{ .Response }}<|end|>
"""
SYSTEM """你是一位中文智能助理,始终用中文回复消息."""
PARAMETER stop "<|user|>"
PARAMETER stop "<|assistant|>"
PARAMETER stop "<|system|>"
PARAMETER stop "<|end|>"
PARAMETER stop "<|endoftext|>"


'3e5f4a42f1 Q8 % ollama create phi-3-mini-128k-instruct-q8-0 -f modelfile
transferring model data 
pulling model 
pulling manifest 
Error: pull model manifest: 400'


@dhiltgen

**Comment by jmorganca** [comment]
Hi @taozhiyuai are you still seeing this issue? If not, I will close for now, but do let me know and I can help out here
