### ISSUE TITLE
could not connect to ollama app

### ISSUE THREAD

**Issue by ricardodddduck** [ollama/ollama#3999]
### What is the issue?

could not connect to ollama app，is it running？
it always happen even reinstall ollama

### OS

Windows

### GPU

Nvidia

### CPU

AMD

**Comment by helium729** [comment]
![image](https://github.com/ollama/ollama/assets/30749877/d0307503-c6ef-4c53-acf1-68e34cf47f18)
guess it would be more helpful if you can upload the tail of the log

**Comment by thiagojramos** [comment]
@ricardodddduck 
I was having the same error and I solved it with 2 things: 
1) I opened the firewall for .exe files from Ollama;
2) I installed Go Language.
Then, I opened PowerShell and used `ollama run llama3`

==========

I am translating this message for him to test and show that it works:
<details><summary>Print</summary>
<p>

![2024-04-28 (1)](https://github.com/ollama/ollama/assets/45890502/41426bfb-74bc-44f5-bd94-acede20b17a1)

</p>
</details>

**Comment by ricardodddduck** [comment]
i have already saved the problem. It seems i make mistakes when i configure Environment Variables.i delete the path then it works.
