### ISSUE TITLE
Different folders for (sha 256) models

### ISSUE THREAD

**Issue by milenamilka755** [ollama/ollama#4004]
The program stores ALL models in parts in a directory: 
ollama\models\blobs
With the various problems of downloading models, moving them to another location, etc., this causes a problem, because you have to work a bit to figure out which parts belong to which model.

It would be a good idea to put each model in parts into a PERSONAL catalog.
e.g.
ollama_models\blobs\lama3
ollama_models\blobs\gemma
ollama_models\blobs\mistral7b
ollama\models\blobs\llava:34b

**Comment by pdevine** [comment]
Hey @milenamilka755 , thanks for the issue. The reason why they are stored in a single directory is it's possible for models to share various parts like their weights, templates, parameters, etc. It allows us to deduplicate anything which is shared.

If you need to move the models out to some other place you can always use the `OLLAMA_MODELS` env variable w/ `ollama serve` (this is covered in the FAQ). I'm going to close the issue, but was there a particular problem you were running into w/ downloading? Was it freezing at 99%?

**Comment by milenamilka755** [comment]
> I'm going to close the issue, but was there a particular problem you were running into w/ downloading? Was it freezing at 99%?
Sometimes when a model is deleted, it does not remove all files associated with the model.
