### ISSUE TITLE
curl: (7) Failed to connect to 172.16.105.65 port 11434 after 0 ms: Couldn't connect to server

### ISSUE THREAD

**Issue by moye12325** [ollama/ollama#4005]
### What is the issue?

**I have set up listening and port settings**
![image](https://github.com/ollama/ollama/assets/43414308/5e7adbf3-e29b-4fc2-9bae-490a82064cbf)

**And I can use it on my server**
![image](https://github.com/ollama/ollama/assets/43414308/fde96efd-c4c4-4b04-8e17-ac6fdf8ea591)
![image](https://github.com/ollama/ollama/assets/43414308/066fda7b-7a60-4bd3-8e64-eee61b17ca28)

**My local computer can access my remote server, and port 3306 can also be accessed, but port 11434 is not working. I have also checked the server's firewall and there is no problem**

![image](https://github.com/ollama/ollama/assets/43414308/f85c4053-1dd4-4244-9693-8b3519cabeb4)

### OS

Linux, Windows

### GPU

Nvidia

### CPU

Intel

### Ollama version

0.1.32

**Comment by moye12325** [comment]
![image](https://github.com/ollama/ollama/assets/43414308/923391b2-fb32-4b92-9f55-6ccfd4133e29)

**Comment by moye12325** [comment]
sudo firewall-cmd --permanent --add-port=11434/tcp

I have set up a firewall and solved the problem

**Comment by 0xp4tcher** [comment]
Man, fixed this issue man??

**Comment by 0xp4tcher** [comment]
I tried opening the port in my firewall but the error persists? any fix?

**Comment by everythingIsShit** [comment]
> sudo firewall-cmd --permanent --add-port=11434/tcp
> 
> I have set up a firewall and solved the problem

![image](https://github.com/user-attachments/assets/30fab072-d635-4380-b06c-e5e527feffcb)
I tried, but the problem still existing.

**Comment by nkozcode** [comment]
I hae this same problem even after setitng up the firewall
