### ISSUE TITLE
How to set 'verbose' ON by default after a model is loaded?

### ISSUE THREAD

**Issue by taozhiyuai** [ollama/ollama#4010]
How to set 'verbose' ON by default after a model is loaded?

it is annoying to type /set verbose every time.

**Comment by pdevine** [comment]
Hey @taozhiyuai . Thanks for the issue. As a workaround you can use the `--verbose` flag with `ollama run` instead. If you're on mac/linux you can make an alias to it. I'm not 100% sure how to do that w/ Windows off the top of my head though.

I'm going to go ahead and close the issue for now, but I was thinking maybe we should make another env variable for this. I'll have to think about it some more.
