### ISSUE TITLE
Export Pulled Model

### ISSUE THREAD

**Issue by ChenTao98** [ollama/ollama#4016]
I run a service on an offline server, so I can't use the "pull" command directly. 
How can I export a pulled Model in a online computer( e.g. Windows PC) and import it to the offline server(Linux).
Importing from gguf or torch tensor sometimes can't run normally.

It would be better if we can directly download modelfile from [ollama.com ](https://ollama.com/) and import it into offline server.

**Comment by jmorganca** [comment]
Merging with #335
