### ISSUE TITLE
Hardware configuration: 64-core CPU, 1TB memory,  use of llama3:8b is slow. why?

### ISSUE THREAD

**Issue by zhaohuaxi-Shi** [ollama/ollama#4017]
user api/generate pre-load model , its ﻿useless

**Comment by igorschlum** [comment]
Hello @zhaohuaxi-Shi can you provide a prompt and logs to show What is slow?

**Comment by zhaohuaxi-Shi** [comment]
hi @igorschlum , thank you very much for your attention to my issue. The issue has been resolved as GPU has not been enabled thanks
