### ISSUE TITLE
Specify the user's customized workspace

### ISSUE THREAD

**Issue by shanewa** [ollama/ollama#4027]
I got an issue when I run ollama in our special server which has been configured to ban any executable executions under `/tmp` dir. Is it possible to use other dir for below command?

```
# ollama run phi3
Error: error starting the external llama server: fork/exec /tmp/ollama2436530018/runners/cpu_avx2/ollama_llama_server: permission denied
```

I would like the ollama run to have the options like `--workspace` or support to use Shell variable to achieve this.

```
ollama run phi3 --workspace /storage/shanewa/workspace
```

**Comment by pdevine** [comment]
I think `--workspace` would be really complicated for most people to know, however I believe this should be fixed already (i.e. it won't execute from a tmp directory) on Windows.

**Comment by shanewa** [comment]
We mount `/tmp` without executable permissions based on the security features. I'm finding the way to change `ollama_llama_server` location.

```
vi /etc/fstab
tmpfs     /dev/shm        tmpfs   noexec,nosuid,nodev       0 0
```

**Comment by shanewa** [comment]
> I think `--workspace` would be really complicated for most people to know, however I believe this should be fixed already (i.e. it won't execute from a tmp directory) on Windows.

Thanks for the information but I'm using the Linux version and it is still put the server under `/tmp`.

```
# ollama --version
ollama version is 0.1.32
```

**Comment by dhiltgen** [comment]
The location of tmp storage can be adjusted via an environment variable.  See https://github.com/ollama/ollama/blob/main/docs/troubleshooting.md#linux-tmp-noexec

**Comment by shanewa** [comment]
@dhiltgen Great! I didn't read this part. Thanks for your information.

**Comment by dhiltgen** [comment]
We may adjust our packaging model in the future to no longer extract executables into a temporary location (already transitioned to this on Windows), but until then, that troubleshooting guide is the workaround.
