### ISSUE TITLE
Error: unable to push make sure this namespace exists

### ISSUE THREAD

**Issue by katmai** [ollama/ollama#4029]
### What is the issue?

hi, i was trying to push my local model, and i've run into this error.

i did create the namespace in the interface and added the ssh key in settings.

```
atlas@chia01:~$ make buildall
Rebuilding all...
2024/04/29 17:34:13 parser.go:73: WARN Unknown command: .
2024/04/29 17:34:13 parser.go:73: WARN Unknown command: ,
2024/04/29 17:34:13 parser.go:73: WARN Unknown command: .
2024/04/29 17:34:13 parser.go:73: WARN Unknown command: .
transferring model data
reading model metadata
creating template layer
creating system layer
creating parameters layer
creating config layer
using already created layer sha256:00e1317cbf74d901080d7100f57580ba8dd8de57203072dc6f668324ba545f29
using already created layer sha256:4fa551d4f938f68b8c1e6afa9d28befb70e3f33f75d0753248d530364aeea40f
using already created layer sha256:8ab4849b038cf0abc5b1c9b8ee1443dca6b93a045c2272180d985126eb40bf6f
using already created layer sha256:fd83d1a4f1b65e907a9159fbcaa11cc09764902fed017a5ad8a42eb6c6cd9cdf
using already created layer sha256:246dc13aabc5a8f1eafb2ed9392d2f07d5e5c69cc6115aa47289602954b14fa9
using already created layer sha256:77160e03a5b3981ca15f79f46a2d5f3bfdb6a1bc221f26160ecd576fa87bb4bd
using already created layer sha256:727537c469037bd13674139c12f661afb4a7023f2af796b4df9e1d568e5f54a0
writing manifest
success
atlas@chia01:~$ ollama push katmai/all
retrieving manifest
Error: unable to push katmai/all, make sure this namespace exists and you are authorized to push to it
```

any ideas what's up?

### OS

Linux

### CPU

AMD

### Ollama version

0.1.33-rc5

**Comment by katmai** [comment]
> /usr/share/ollama/.ollama/id_ed25519.pub

oh you're right. i should have seen that. thanks for pointing me in the right direction.
works now.

```
atlas@chia01:~$ ollama push katmai/all
retrieving manifest
pushing 00e1317cbf74... 100% ▕██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏ 4.7 GB
pushing 4fa551d4f938... 100% ▕██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏  12 KB
pushing 8ab4849b038c... 100% ▕██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏  254 B
pushing fd83d1a4f1b6... 100% ▕██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏  759 B
pushing 246dc13aabc5... 100% ▕██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏ 144 KB
pushing 77160e03a5b3... 100% ▕██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏  291 B
pushing 727537c46903... 100% ▕██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏  631 B
pushing manifest
success
```

**Comment by pdevine** [comment]
Awesome! Glad you got it working.

**Comment by mosrihari** [comment]
I am currently using google colab for pushing the model to ollama. First is I have created a public key as below
1) ssh-keygen -t ed25519 -N "" but this creates the public key in /content folder
2) But when I try to copy over the public key to ollama/.ollama folder it is copying it
3) I have also copied the public key to ollama user account. But still namespace mosrihari/modelname is failing

**Comment by zhuqifan** [comment]
> I am currently using google colab for pushing the model to ollama. First is I have created a public key as below
> 
> 1. ssh-keygen -t ed25519 -N "" but this creates the public key in /content folder
> 2. But when I try to copy over the public key to ollama/.ollama folder it is copying it
> 3. I have also copied the public key to ollama user account. But still namespace mosrihari/modelname is failing

in google colab, public key is stored in /root/.ollama/id_ed25519.pub. No need to generate keys by yourself.

**Comment by cstp55** [comment]
working for me also
https://ollama.com/chandancstp/aprilo[https://ollama.com/chandancstp/aprilo](url)
add your public key at ollama keys sections
1. create or copy the  model
>ollama create -f Modelfile chandancstp/aprilo
2. push your model
>ollama push chandancstp/aprilo
