### ISSUE TITLE
Ollama Windows version

### ISSUE THREAD

**Issue by deadcoder0904** [ollama/ollama#403]
I saw it is coming but didn't mention when? Would be great if you pinned this issue as more people use Windows & ollama has such a great dx.

The project looks absolutely brilliant. Would love to use text (gpt-4) & code (copilot) locally.

**Comment by LogicalPizza** [comment]
Let me piggyback on this, I managed to build and run Ollama on Windows, however, I'm able to leverage only the CPU.

It takes 2 minutes to answer "Hi", Does anyone have any hint on how to enable the processing on the GPU? Thanks a lot!

**Comment by technovangelist** [comment]
There are a few steps we need to tackle. We are close on the runner but we still need the rest of the app that surrounds it. This is probably a week or 2 out at least. But it is coming. Thanks for finding the project and being as excited as we are about it

**Comment by jmorganca** [comment]
What @technovangelist said :) Although I'll re-open this so we can track it

**Comment by darkacorn** [comment]
generator files for the os need  -DLLAMA_CUBLAS=ON for the llama.cpp repos
there should be no other breaking changes at all at least i did not see any on linux yet

**Comment by clebio** [comment]
I'm able to compile it on Windows and run it, but not getting GPU support. I don't know CMake well, but can handle the submodule updates and basic bits like `cmake .. -DLLAMA_CUBLAS=ON`'ing. Anything I can do to help out?

**Comment by Xasomoeru** [comment]
Is it possible to run this in an Linux vm on windows? Haven't tried, just wondering cause it's been 3 weeks.

**Comment by lukethacoder** [comment]
Managed to get this running on Windows via WSL 2 without any issues. 99% sure it ran with my RTX 3070 and not the CPU out of the box without the need to adjust any config.

**Comment by Alexandre-Fernandez** [comment]
Native windows support would be great.

**Comment by deadcoder0904** [comment]
winget support would be cool as well as i use that to install anything on windows nowadays. officially supported by microsoft itself.

**Comment by cooleydw494** [comment]
> Managed to get this running on Windows via WSL 2 without any issues. 99% sure it ran with my RTX 3070 and not the CPU out of the box without the need to adjust any config.

That's amazing but I tried with no success. Every time I serve it, I get a message saying the nvidia-smi command failed. I installed drivers on WSL2 and my windows machine to no avail.

**Comment by prabirshrestha** [comment]
In case anyone is looking to manually compile ollama as a native windows app here is what I did.

Install [scoop](https://scoop.sh/). This is similar to apt-get for linux and homebrew for mac.

Then run the following commands to build `ollama.exe`. 

```bash
scoop install go cmake gcc
set CGO_ENABLED="1"
git clone https://github.com/jmorganca/ollama.git
go generate ./...
go build .
```

**Comment by mesopa** [comment]
> In case anyone is looking to manually compile ollama as a native windows app here is what I did.
> 
> Install [scoop](https://scoop.sh/). This is similar to apt-get for linux and homebrew for mac.
> 
> Then run the following commands to build `ollama.exe`.
> 
> ```shell
> scoop install go cmake gcc
> set CGO_ENABLED="1"
> git clone https://github.com/jmorganca/ollama.git
> go generate ./...
> go build .
> ```

I tried on Windows 11 but it always ends with the same error:

```sh
dumpbin : The term 'dumpbin' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
```

**Comment by BruceMacD** [comment]
@mesopa that looks like a c++ dependency error. If you have Visual Studio installed in your system try using the `Developer Command Prompt for Visual Studio` instead of regular command prompt to build the project.

**Comment by prabirshrestha** [comment]
@mesopa updated the comment. You need to Install Visual Studio Community 2022 with C++ Profiling Tools for dumpbin.  I noticed this change when was trying to compile the latest master.

**Comment by LiteSoul** [comment]
Any update on a Windows version? 6 months has passed since it was a week away, thanks.

**Comment by zcfrank1st** [comment]
when windows...

**Comment by yanghuantian** [comment]
when windows...

**Comment by dhiltgen** [comment]
Sorry about the `dumpbin` hard dependency.  I've made a number of improvements for the windows build in #2007 which should improve the situation.  It also should be better now at detecting cuda and skipping that part of the build if it isn't detected like we do on linux.

While https://github.com/jmorganca/ollama/blob/main/docs/development.md#windows could be enhanced, please let us know if you're unable to build locally with those instructions. (either doc improvements, or fixing corner cases in the build scripts for windows.)

As far as "when windows" - we're working to get the main ollama runtime in good shape on windows, and then package it up with an installable app much like we do on MacOS.  Hopefully folks who are comfortable building from source can start leveraging their GPUs in a native `ollama.exe` from `main` now, and the installable app is coming soon.

**Comment by Don0001** [comment]
I futzed around and was in over my head. Sucess came when I followed these instructions:
https://m.youtube.com/watch?v=C7rFk-GbdCg
Basic steps all the way through and now I'm running ollama in WSL2 and Ubuntu,

**Comment by BrandonKMLee** [comment]
@dhiltgen thanks for the update, and once there is an installable a Chocolatey package will surely be a good addition. There are less dependencies on Linux-exclusive tools now right?

**Comment by SpanishHearts** [comment]
Yea I'm really, really missing a proper Windows 11 executable

**Comment by brettforbes** [comment]
Hi, 
We have an open-source electron app that works on Windows, Mac and Linux, and we would like to use Ollama on all platforms, yet we are not in control of the laptop and cannot install WSL or docker Desktop? Unfortunately we cannot yet use Ollama without a native Windows capability

Is there any status on the native Windows version so we can start to use Ollama?
Thanks

**Comment by BruceMacD** [comment]
@brettforbes you can build Ollama from source for Windows. That's how I packaged it into the Windows version of the chatd electron app (source available on my GitHub).

**Comment by deependhulla** [comment]
You can also try Llamafile, a single executable with models or just the program and use a different model. It might be useful; check out the repository. I have tried it on Linux and Windows on an i3 with 8GB RAM, and it performed well, might be good for your app integration.

Visit the GitHub repository for more information.
https://github.com/Mozilla-Ocho/llamafile

**Comment by BrandonKMLee** [comment]
@BruceMacD could you roll yours into a Chocolatey installer of the compiled software before the official Ollama app gets released? Or should we all wait a while?

**Comment by dhiltgen** [comment]
The Windows Preview is now available

https://ollama.com/download/windows

**Comment by Don0001** [comment]
Super easy install and ran perfectly. You all did a great job with this one.

**Comment by dhiltgen** [comment]
I think we can mark this one resolved now.  If folks run into any problems with the preview, please let us know on discord or file new issues.

**Comment by jpablo-ortiz** [comment]
Me gustaría saber si este lanzamiento se arregló lo de que se use la GPU, porque ya instalé la versión de windows, pero cuando abro el administrador de tareas y ejecuto un modelo veo que mi GPU no llega ni al 2% de uso. ¿Saben a qué se deba?

**Comment by dhiltgen** [comment]
@jpablo-ortiz if your GPU has a small amount of VRAM larger models will not fit and can result in low GPU utilization.  Look in the server.log file for a line that looks like this:

```
llm_load_tensors: offloaded 33/33 layers to GPU
```

The more layers on the GPU the better.

**Comment by jpablo-ortiz** [comment]
I understand, but in my case I previously used ollama from Ubuntu on windows with WSL and it was perfect and used the gpu.

**Comment by dhiltgen** [comment]
@jpablo-ortiz are you running an AMD Radeon card perhaps?  We only support NVIDIA in the native windows build right now.

If that's not it, please open a new issue and attach a server.log (ideally both from within WSL2 and the native windows version so we can see the differences)

**Comment by jpablo-ortiz** [comment]
I was able to fix it by reinstalling ollama, and now it works perfectly. Thank you very much for your help.

**Comment by IvanSoregashi** [comment]
Hello
I have noticed that ollama can be installed with winget
`winget install --id=Ollama.Ollama  -e`
https://winstall.app/apps/Ollama.Ollama

Is this official?

**Comment by GuptaDiva** [comment]
Best would be to run the basics first. pip install ollama.
