### ISSUE TITLE
Integrate json_repair package to overcome the slow json feature 

### ISSUE THREAD

**Issue by ArslanKAS** [ollama/ollama#4030]
Hi there,

Ollama is a great tool to get started with LLMs but the issue I'm facing is the JSON processing. The JSON format enforcer argument by the Ollama package just takes too long. It turns a 8 second response from LLaMa3 into a 90 second response. I don't know why it takes too long. I've come across a great package called "json_repair" that fixes broken JSON responses.

If the Ollama team can kindly integrate it so whenever the LLMs give out a broken JSON response, it can be fixed within 1 or 2 seconds. That'd be a great help in Function Calling too.

Here's the repo:
https://github.com/mangiucugna/json_repair

**Comment by jmorganca** [comment]
Hi @ArslanKAS. Thanks for the issue! This is an incredibly cool project. In terms of improving the JSON output with Ollama, this is something we'd want to fix in the inference code vs post-processing if we can. However I'd be excited to let folks know about this project via an example or in our discord
