### ISSUE TITLE
incomprehensible answers from Gemma:7b

### ISSUE THREAD

**Issue by kukidevs** [ollama/ollama#4033]
### What is the issue?

<img width="627" alt="image" src="https://github.com/ollama/ollama/assets/113847173/34b3d3e0-70b2-4695-a86f-f824178e1b68">

Mistral:7b works fine, so I suppose that the issue is realted to the model

### OS

macOS

### GPU

Apple

### CPU

Apple

### Ollama version

0.1.32

**Comment by pdevine** [comment]
This should work fine. Here's my output on a MBP:

```
% ./ollama run gemma:7b
>>> hi there
Hi there, and welcome to my chat! 👋

I'm glad you decided to talk to me today. What would you like to talk about?
```

Two things:
  1. how much memory do you have, and is there memory pressure?
  2. can you paste the output for `ollama ls | grep gemma:7b`?

The latter should look like:
```
% ./ollama ls | grep gemma:7b
gemma:7b                                430ed3535049    5.2 GB  3 weeks ago
```

**Comment by thinkverse** [comment]
> The latter should look like:
> 
> ```
> % ./ollama ls | grep gemma:7b
> gemma:7b                                430ed3535049    5.2 GB  3 weeks ago
> ```

Running Ollama 0.1.32, Mac OS Sonoma with 16 GB, can vouch that the latest version - [a72c7f4d0a15](https://ollama.com/library/gemma:7b), works without any modifications.

```shell
ollama ls | grep gemma:7b
gemma:7b                             	a72c7f4d0a15	5.0 GB	7 days ago 	
```

```shell
ollama run gemma:7b

>>> hi there
Hi there! 👋

It's great to hear from you. What would you like to chat about today? 😊
```

**Comment by kukidevs** [comment]
@pdevine 
> 1. how much memory do you have, and is there memory pressure?
> 2. can you paste the output for `ollama ls | grep gemma:7b`?

1. Mac Mini M2 8GB. apparently it should be able to run since mistral 7b can
2. gemma:7b  	a72c7f4d0a15	5.0 GB	35 seconds ago

**Comment by pdevine** [comment]
I realize *I* had the outdated version. :-D I think it's almost certainly a memory pressure issue w/ metal cc @mxyng

**Comment by pdevine** [comment]
> @pdevine but can it be the problem here? [...]
> it doesn't refuse to generate a reply or takes long to generate, but it just returns a bunch of "unused" tags, as if it's something that needs to be decoded. also I might have misunderstood your response

I think maybe? It tends to do weird things when it runs out of memory. It's weird that mistral:7b works fine though.

**Comment by pdevine** [comment]
@mkmohangb the team had been talking about this earlier today and we suspected that this might be the issue. Good catch.
There is a fix in the 0.1.33 pre-release which may fix this. @kukidevs (or anyone commenting on the issue) would you be able to try it out?

**Comment by mkmohangb** [comment]
@pdevine I tried Gemma with 0.1.33-rc5 version. It works now but is slow. I see in the server logs that not all the layers are sent to the GPU. How do you decide the upper limit for this?

**Comment by pdevine** [comment]
> @pdevine I tried Gemma with 0.1.33-rc5 version. It works now but is slow. I see in the server logs that not all the layers are sent to the GPU. How do you decide the upper limit for this?

We compute the graph of the memory footprint for the model and see if you have enough memory.

I'll go ahead and close the issue. The workaround for now is to `/set num_gpu` to a lower number, but otherwise just upgrade to 0.1.33.
