### ISSUE TITLE
ollama run codeqwen TLS handshake timeout

### ISSUE THREAD

**Issue by Alchemistqqqq** [ollama/ollama#4038]
### What is the issue?

After I manually installed ollama locally, I started to try to run models, not only qianwne, but also llama3. But ping ollama.com does work. Since I am building ollama on the server, I was wondering if it would be possible to download the model file locally and drag it to the specified path on the server. If you can do this, could you give me some help? I don't know what path the pulled model should be placed under, thank you.

### OS

Linux

### GPU

Nvidia

### CPU

AMD

### Ollama version

0.1.32

**Comment by dhiltgen** [comment]
Check out https://github.com/ollama/ollama/blob/main/docs/faq.md#where-are-models-stored for more information on where we store the models.

**Comment by Alchemistqqqq** [comment]
> Check out https://github.com/ollama/ollama/blob/main/docs/faq.md#where-are-models-stored for more information on where we store the models.

![image](https://github.com/ollama/ollama/assets/146717415/590d8e86-469f-4573-a566-52a2e24ceac3)
At your prompt, I found the address where the model is stored. But I would like to try downloading the model file locally and manually deploying it to the relevant directory on the server. I see the file for the model in the image below. The help I need is as follows: 1. I need the URL to download these files manually.2. I need to know what the structure of my model file looks like. 3. Whether additional operations are required. Thank you very much!

**Comment by jmorganca** [comment]
merging with https://github.com/ollama/ollama/issues/3820
