### ISSUE TITLE
Document the different windows downloads

### ISSUE THREAD

**Issue by eabase** [ollama/ollama#4047]
### What is the issue?

Please document what the different windows downloads available, are actually doing and their difference.
 

![2024-0430_125911_Releases_·_ollamaollama_—_Mozilla_Firefox](https://github.com/ollama/ollama/assets/52289379/f1718e0e-b00b-401a-82aa-48bb978feca5)
 

### OS

Windows

### GPU

Nvidia

### CPU

Intel

**Comment by eabase** [comment]
This is beyond bad. 

1. It installs stuff all over the place, without informing the user. 
```
	C:\Users\xxxx\AppData\Roaming\Microsoft\Windows\Start Menu\Programs
	C:\Users\xxxx\AppData\Local\Temp\ollamaNNNNNN
	C:\Users\xxxx\.ollama\id_ed25519
	C:\Users\xxxx\AppData\Local\Programs\Ollama
	C:\Users\xxxx\AppData\Local\Ollama
```
2. It doesn't ask the user where they want it to be installed!
3. It opens ports and starts a server under different application name and on unspecified sever ports that can only be found in a temp directory.
4. One the original (cmd) windows is closed, the server is still running!
5. There are no instructions on how to shut down the server

In the current state this application is acting more like **maleware** than something serious.

**Comment by eabase** [comment]
⁉️ ⁉️

**Comment by dhiltgen** [comment]
This is now documented [here](https://github.com/ollama/ollama/blob/main/docs/windows.md#standalone-cli).

**Comment by eabase** [comment]
Great. Thank you.
