### ISSUE TITLE
Ollama after 30 minutes start to be very very slow to answer the questions

### ISSUE THREAD

**Issue by nunostiles** [ollama/ollama#4050]
### What is the issue?

I've already tried with several different models, but the issue is always persisting, after ~30 minutes it keeps taking ages to answer to questions, even with saved models it happens. Is there anything that I can do? it's in fact a bug? 
On the first 30 minutes it runs normally without any slowness. Need help please, any suggestion?
Thank you!

### OS

Linux

### GPU

Nvidia

### CPU

Intel

### Ollama version

0.1.32

**Comment by sammcj** [comment]
Two ideas on this:

1) Are you sure it’s not just the model unloading when idle? (I think this defaults to 5 minutes)

2.I’ve noticed that occasionally after some time idle Ollama seems to switch from using the GPU to CPU only, can you confirm if inference is occurring on your GPU or CPU?

**Comment by pdevine** [comment]
Are you using the CLI or the API? Do all subsequent requests continue to be slow, or just the first time you do it after 30 minutes?

**Comment by nunostiles** [comment]
I'm using the CLI, the first requests are always fine, first around 30 minutes, no problems. there is always another thing, when the slowness starts, I could also save the model, restart the computer, load it, and the problem persists. Very weird!

**Comment by mistakenideas** [comment]
I’ve seen something similar running on Linux albeit with CPU only. I think it may be related to the context size, and when this fills up things slow to a crawl. Responses go from around 30secs to 7minutes!

Halving the context from 2048 to 1024 causes the problem to happen quicker but also be not as pronounced (responses ‘only’ 3 and a half minutes). 

I’ll do some more investigation and compare to using llama.cpp directly.

**Comment by eyalshalom** [comment]
I am experiencing the same. after 30 minuts become very slow

**Comment by eyalshalom** [comment]
do you have any idea what cause to it?

**Comment by nunostiles** [comment]
I don't really know and I've already tried several machines... no idea

**Comment by dhiltgen** [comment]
Please give the new 0.4.0 RC release a try and see if it resolves this slowdown in performance.  We've rewritten the way we cache which should improve performance and reliability.

https://github.com/ollama/ollama/releases

**Comment by pdevine** [comment]
I tried this w/ linux and an RTX 4090. The results:

Initial speed:
```
total duration:       3.245905622s
load duration:        15.127592ms
prompt eval count:    363 token(s)
prompt eval duration: 3ms
prompt eval rate:     121000.00 tokens/s
eval count:           434 token(s)
eval duration:        3.225s
eval rate:            134.57 tokens/s
```

After 40 minutes:
```
total duration:       5.115713412s
load duration:        890.785686ms
prompt eval count:    810 token(s)
prompt eval duration: 127ms
prompt eval rate:     6377.95 tokens/s
eval count:           518 token(s)
eval duration:        3.881s
eval rate:            133.47 tokens/s
```

That includes having to reload the model into memory.

I'm going to go ahead and close the issue, but we can reopen it if someone is able to reproduce it.

**Comment by alex-bratu** [comment]
I have the exact same problems. it only works okay for like 20-30 minutes and then very slow

**Comment by pdevine** [comment]
@alex-bratu can you post some more details? What hardware are you using? What version of Ollama? Can you run `ollama ps` when it slows down?

**Comment by alex-bratu** [comment]
# ollama ps
NAME         ID              SIZE      PROCESSOR    UNTIL       
llama3:8b    365c0bd3c000    6.7 GB    100% GPU     Stopping...  

nvidia H100

**Comment by pdevine** [comment]
OK, that's weird. Is there some other process which is trying to stop the model? Does it succeed in stopping?

**Comment by alex-bratu** [comment]
as far as I can tell, there is no other process which is trying to stop the model. here I restarted the model but seems like it works very slow

![Image](https://github.com/user-attachments/assets/8eaf1e28-72f6-4289-8869-27c8dd7e6745)
![Image](https://github.com/user-attachments/assets/b2a06aa6-da82-4135-850d-b2555ca375ae)

**Comment by pdevine** [comment]
@alex-bratu does it stay in the `Stopping...` state? That was the thing that I was commenting on being weird. I'm struggling to duplicate this though, at least on a 4090.

**Comment by alex-bratu** [comment]
so there is a fresh server with no other service running on it. all i have done is to install ollama using the one line installer and I try to run the llama3:8b model. i tried using the ' ollama run llama3:8b ' or using the curl commands and it seems like after like 30 minutes it works very very slow. Even if I restart the service or reload the model this slowness is not changing. I need to restart the hole server in order to make it work well, but then again after approximatively 30 minutes starts to work like this . I will give you the logs from ollama serve terminal when it is working slow. 

[logs.txt](https://github.com/user-attachments/files/18903725/logs.txt)

**Comment by gamer4et** [comment]
Meet the same issue on tesla p40 with deepseek-r1:14b
