### ISSUE TITLE
Unable to create gguf file for my finetuned mixtral8x7b model

### ISSUE THREAD

**Issue by Nimmalapudi-Pratyusha** [ollama/ollama#4052]
### What is the issue?

I am trying to create a gguf file for my finetuned mixtral model but it keeps throwing following error:

Command :` python llm/llama.cpp/convert.py /home/raft_mixtral_2epochs_v1 --outtype q8_0 --outfile converted.bin`
Error: 
```
raise FileNotFoundError(f"Can't find model in directory {path}")
FileNotFoundError: Can't find model in directory /home/raft_mixtral_2epochs_v1


```

Below are the content's of my raft_mixtral_2epochs_v1 folder :
![Screenshot from 2024-04-30 19-01-05](https://github.com/ollama/ollama/assets/129523872/fff3327a-5e96-4991-8ecb-c2fc0c539f32)

### Ollama version

0.1.32

**Comment by thinkverse** [comment]
Have you tried `convert-hf-to-gguf-update.py`[^1] instead of `convert.py` to see if that works?

[^1]: https://github.com/ollama/ollama/blob/main/docs/import.md#convert-the-model

**Comment by Nimmalapudi-Pratyusha** [comment]
> Have you tried `convert-hf-to-gguf-update.py`[1](#user-content-fn-1-3ce43143dc53c24086b5538bdf8feba4) instead of `convert.py` to see if that works?
> 
> ## Footnotes
> 1. https://github.com/ollama/ollama/blob/main/docs/import.md#convert-the-model [↩](#user-content-fnref-1-3ce43143dc53c24086b5538bdf8feba4)

It's throwing below error when I tried with `convert-hf-to-gguf-update.py` 
Command : `python llama.cpp/convert-hf-to-gguf-update.py <hftoken> /home/raft_mixtral_2epochs_v1 --outfile raft_v1.gguf --outtype q8_0`
error: 
Usage: python convert-hf-to-gguf-update.py <huggingface_token>.

**Comment by pdevine** [comment]
@Nimmalapudi-Pratyusha I think you're just specifying the wrong file path for the file.

**Comment by pdevine** [comment]
@Nimmalapudi-Pratyusha did you manage to get this to work?

**Comment by Nimmalapudi-Pratyusha** [comment]
The issue wasn't with the path, I found the fix here -
https://github.com/ggerganov/llama.cpp/issues/4199
![Screenshot from 2024-05-07 14-03-14](https://github.com/ollama/ollama/assets/129523872/057b7cca-8916-47e9-86fd-eb01130f2d8a)

**Comment by pdevine** [comment]
Glad you got it working!
