### ISSUE TITLE
Error when trying to run llama3

### ISSUE THREAD

**Issue by omagdy7** [ollama/ollama#4057]
### What is the issue?

Just pulled llama3 and when I try to run it I get this weird error:

Error: template: :7:3: executing "" at <.Response>: can't evaluate field Response in type struct { First bool; System string; Prompt string; Context []int }

Note:
mistral:7b runs just fine
I also tried removing the model and re fetching it

Here is the template of llama3 using `ollama show llama3 --template`:
{{ if .System }}<|start_header_id|>system<|end_header_id|>

{{ .System }}<|eot_id|>{{ end }}{{ if .Prompt }}<|start_header_id|>user<|end_header_id|>

{{ .Prompt }}<|eot_id|>{{ end }}<|start_header_id|>assistant<|end_header_id|>

{{ .Response }}<|eot_id|>

### OS

Linux

### GPU

Nvidia

### CPU

AMD

### Ollama version

0.1.7

**Comment by reski-rukmantiyo** [comment]
Hi, possible due to old version of Ollama?

```
root@ollama-7d4795fd9f-tn9p8:/# ollama show llama3 --template
{{ if .System }}<|start_header_id|>system<|end_header_id|>

{{ .System }}<|eot_id|>{{ end }}{{ if .Prompt }}<|start_header_id|>user<|end_header_id|>

{{ .Prompt }}<|eot_id|>{{ end }}<|start_header_id|>assistant<|end_header_id|>

{{ .Response }}<|eot_id|>
root@ollama-7d4795fd9f-tn9p8:/# ollama --version
ollama version is 0.1.32
```

I'm using docker image version of Ollama

**Comment by omagdy7** [comment]
Yeah apparently something is wrong with the package upstream in arch linux official packages with used the official install script and now works fine.
