### ISSUE TITLE
[FEATURE] Add llamascript to community projects

### ISSUE THREAD

**Issue by WolfTheDeveloper** [ollama/ollama#4061]
# LlamaScript

[pypi](https://pypi.org/project/llamascript/)

[repo](https://github.com/WolfTheDeveloper/llamascript)

## Why?
llamascript allows the creation of no-code AI chatbots using Ollama.

## Example
A basic chatbot using llamascript

```llamascript
USE llama3
PROMPT Why is the sky blue?
CHAT
```

This would be saved in a `llama` file (no file extension) and run as `llamascript`.

## Install
To install, run `pip install llamascript`.

## Note
llamascript is still a work in progress, but is usable to create basic chatbots at this time.

**Comment by jmorganca** [comment]
Would it be possible to create a PR for this? Thank you!
