### ISSUE TITLE
llama3-gradient going crazy

### ISSUE THREAD

**Issue by DuckyBlender** [ollama/ollama#4062]
### What is the issue?

Just ran `ollama run llama3-gradient` and this happened. Used the default (8k) context size
![image](https://github.com/ollama/ollama/assets/42645784/6c390484-774a-40c4-82fe-4411d65b471c)

### OS

Windows

### GPU

Nvidia

### CPU

Intel

### Ollama version

0.1.32

**Comment by jmorganca** [comment]
Hi there, the runtime parameters have been updated to help with this issue when the context limit is hit. Please try re-pulling using `ollama pull llama3-gradient` which should fix this.

**Comment by DuckyBlender** [comment]
> Hi there, the runtime parameters have been updated to help with this issue when the context limit is hit. Please try re-pulling using `ollama pull llama3-gradient` which should fix this.

When have they been updated? I downloaded the model a few minutes before creating this issue. Also the default context size is 2k, not 8k, sorry. So my input was above the context size

**Comment by DuckyBlender** [comment]
After re-pulling the model it seems to be working :) 
![image](https://github.com/ollama/ollama/assets/42645784/8bd55d80-5591-4e62-ac7c-54065c838c30)

**Comment by jmorganca** [comment]
@DuckyBlender great to hear, and sorry again about that.

**Comment by DuckyBlender** [comment]
![image](https://github.com/ollama/ollama/assets/42645784/2d52d264-e88e-4bd8-bbc4-610ca7361e64)
Everything seemed to be working perfectly, until it started repeating itself

**Comment by binaryc0de** [comment]
I'm seeing the same thing.  llama3-gradient was working fine for a while and now it endlessly repeats it's self.

**Comment by DuckyBlender** [comment]
Maybe a higher repeat penalty can fix this?

**Comment by step21** [comment]
> ![image](https://private-user-images.githubusercontent.com/42645784/327557376-2d52d264-e88e-4bd8-bbc4-610ca7361e64.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEwNzM1NTYsIm5iZiI6MTczMTA3MzI1NiwicGF0aCI6Ii80MjY0NTc4NC8zMjc1NTczNzYtMmQ1MmQyNjQtZTg4ZS00YmQ4LWJiYzQtNjEwY2E3MzYxZTY0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA4VDEzNDA1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI5MTI3NzQ5MWQwMmY0MDZlMmNiNmU5ZDM0YzE5ZjMwZGEyNjgwYjA1YTgwMmFlOGUxYTU5OTI2MTcxZDQ5NmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ETLVvceFKxlB6tX25h39i6ioUTd9juRjGgGLx0v3c3A) Everything seemed to be working perfectly, until it started repeating itself

I have the same thing. Worst thing is, that it doesn't stop but keeps going for a really long time, using resources.
