### ISSUE TITLE
moondream returns no response

### ISSUE THREAD

**Issue by DuckyBlender** [ollama/ollama#4063]
### What is the issue?

moondream model and other vision models like phi3 llava doesn’t return any text most of the time. Running Ollama 0.1.33-pre5 and ollama-rs. Not an issue with ollama-rs because I tried in the CLI and it also returned nothing.

### OS

Linux

### GPU

Nvidia

### CPU

Intel

### Ollama version

0.1.33-pre5

**Comment by rb81** [comment]
Maybe related to: https://github.com/ollama/ollama/issues/4076

**Comment by DuckyBlender** [comment]
> Maybe related to: #4076

Nope, running ollama pre-release which should support moondream. I just get no response. If I ask it about the image on the next chat turn it works...

**Comment by rvalieris** [comment]
same issue here on the release 0.1.33, running on linux cpu only.

running `ollama run 'moondream:1.8b' ''`, ollama serve prints:
```
[....]
clip_model_load: params backend buffer size =  867.61 MB (457 tensors)
key clip.vision.image_grid_pinpoints not found in file
key clip.vision.mm_patch_merge_type not found in file
key clip.vision.image_crop_resolution not found in file
clip_model_load: failed to load vision model tensors
time=2024-05-04T11:04:28.884-03:00 level=ERROR source=routes.go:120 msg="error loading llama server" error="llama runner process no longer running: -1 "
```

**Comment by rvalieris** [comment]
nevermind, a few hours ago the archlinux package updated (0.1.33-2 -> 0.1.33-4) and now it works, I'm not sure what changed but it seems it was a packaging issue in my case.

**Comment by DuckyBlender** [comment]
duplicate of #4163

**Comment by DuckyBlender** [comment]
> nevermind, a few hours ago the archlinux package updated (0.1.33-2 -> 0.1.33-4) and now it works, I'm not sure what changed but it seems it was a packaging issue in my case.

are you sure it's working? #4163 suggests this is an active issue

**Comment by DuckyBlender** [comment]
> same issue here on the release 0.1.33, running on linux cpu only.
> 
> running `ollama run 'moondream:1.8b' ''`, ollama serve prints:
> 
> ```
> [....]
> clip_model_load: params backend buffer size =  867.61 MB (457 tensors)
> key clip.vision.image_grid_pinpoints not found in file
> key clip.vision.mm_patch_merge_type not found in file
> key clip.vision.image_crop_resolution not found in file
> clip_model_load: failed to load vision model tensors
> time=2024-05-04T11:04:28.884-03:00 level=ERROR source=routes.go:120 msg="error loading llama server" error="llama runner process no longer running: -1 "
> ```

oh, this isn't even my error. my model loads but doesn't respond anything. if i ask it on the next turn it works
