### ISSUE TITLE
Support to build llama.cpp with Intel oneMKL

### ISSUE THREAD

**Issue by MarkWard0110** [ollama/ollama#4069]
What would be required to build with [Intel oneMKL](https://github.com/ggerganov/llama.cpp?tab=readme-ov-file#intel-onemkl)?

It seems this is how `avx_vnni` instruction set is made available for Intel processors that do not support AVX512.  The Intel Core i9 14900k does not support AVX512.  

It also references Intel's publication [Optimizing and Running LLaMA2 on Intel CPU](https://www.intel.com/content/www/us/en/content-details/791610/optimizing-and-running-llama2-on-intel-cpu.html)

There is also this [AVX2 is dimwitted compared to AVX512](https://github.com/google/gemma.cpp/issues/23). How do different builds affect how models perform on Intel CPU?

What if `llama.cpp` build configuration + quantized models is a double down on poorly performing models?

**Comment by dhiltgen** [comment]
Intel GPU support is being tracked via #1590 

AVX512 (and friends) is tracked via #2205
