### ISSUE TITLE
ollama pull llama3 error

### ISSUE THREAD

**Issue by wisepmlin** [ollama/ollama#4071]
### What is the issue?

ollama pull llama3
Error: pull model manifest: Get "https://ollama.com/token?nonce=EBGaz66AqKbJTscDMcl-ag&scope=repository%!A(MISSING)library%!F(MISSING)llama3%!A(MISSING)pull&service=ollama.com&ts=1714547177": read tcp 192.168.188.104:49346->34.120.132.20:443: read: connection reset by peer
Can't I prioritize it? I can't use it locally

### OS

macOS

### GPU

Intel

### CPU

Intel

### Ollama version

llama2&llama3

**Comment by dhiltgen** [comment]
Let's consolidate this as a dup of #3504 

(We believe a proxy or firewall is altering the URLs during redirection and causing things not to work properly)
