### ISSUE TITLE
invalid file magic while importing llama3 70b into ollama

### ISSUE THREAD

**Issue by David20080125** [ollama/ollama#4075]
### What is the issue?

the model i used is from https://hf-mirror.com/mradermacher/llama-3-70B-instruct-uncensored-i1-GGUF,
the issues are like this
`PS D:\Ollama> ollama create llama3:70b -f Modelfile
transferring model data
creating model layer
Error: invalid file magic`
the model couldn't be successfully booted into ollama.
Is llama3 supported to be imported?

### OS

Windows

### GPU

Nvidia

### CPU

Intel

### Ollama version

0.1.32

**Comment by pdevine** [comment]
Hey @David20080125, usually this happens because the GGUF file is corrupt, or you didn't actually download the file. Can you verify the checksum on the file is correct?

**Comment by David20080125** [comment]
let me check

**Comment by xwbxxx** [comment]
I have the same problem, with ollama version is **0.1.31**, and my llm is **codeqwen-1_5-7b-chat-q2_k.gguf**.
I have verifid the sha256, and it's the same with official readme file

**Comment by joshyan1** [comment]
Hey, I-quants have been supported since https://github.com/ollama/ollama/pull/4322. I also cannot seem to reproduce this issue locally. Please re-open this issue if it appears again. Thanks!
