### ISSUE TITLE
Stop running model without removing

### ISSUE THREAD

**Issue by nitulkukadia** [ollama/ollama#4077]
To start the model we can use the command : 
ollama run <Model>

How do we stop the model ?

I tried running  ollama rm <Model> but it will remove the try to redownload the model which is approx 50 GB.

We need to run different models based on the requirements and user interest. 
How can we do that without redownloading the model again?

**Comment by Gomez12** [comment]
A normal model will stop being loaded after 5 minutes or whenever a new model is requested.

Basically all you have to do is Ollama run "other model name" and it will do what it needs to do.
And if you do not use the model for 5 minutes then it will be automatically unloaded.

**Comment by pdevine** [comment]
@nitulkukadia If you're using `ollama run`, just hit `Ctrl + c` to stop the model from responding. If you want to unload it from memory check out the [FAQ](https://github.com/ollama/ollama/blob/main/docs/faq.md#how-do-i-keep-a-model-loaded-in-memory-or-make-it-unload-immediately) which covers this. The short answer is either use the `OLLAMA_KEEP_ALIVE` environment variable, or you can make a call to the API.

**Comment by nitulkukadia** [comment]
This seems a fallback for me. But removing unwanted resources (remove model) and removing unused resources (no one is using for sometime) seems a different use case.

**Comment by nitulkukadia** [comment]
@pdevine The basic use case is I do not want to show the models in the UI drop down for the end users as those are not available for specific reason and have been stopped for evaluation before releasing to end user.

**Comment by pdevine** [comment]
@nitulkukadia when you start the ollama server you can use the `OLLAMA_KEEP_ALIVE` environment variable and set it to `0`. That will automatically unload any model after each generation. This is covered in the FAQ I mentioned before.

**Comment by the-zucc** [comment]
This doesn't make sense. For some people, loading the model in memory takes a long time. As such, they should be left with the choice of keeping it in memory, or killing it.

The same way docker users can issue the `docker stop <container_name>` command to stop a container when they no longer use it, ollama users should be able to issue `ollama stop <model_name>` to stop a model that is OLLAMA_KEEP_ALIVE=-1 (never unload the model).

The idea might not be fully thought out, and there might be some considerations, but I really think that not letting people control what models are loaded in memory is extremely odd..

**Comment by justinsloan** [comment]
You could also just restart the daemon process. For example: `sudo systemctl restart ollama`

**Comment by EricFrancis12** [comment]
You can always kill the Ollama process from the task manager.

**Comment by pdevine** [comment]
Check out #6739

**Comment by darcouk** [comment]
**`Ctrl + d`**

**Comment by Mugane** [comment]
The notion of killing the process, or unloading the model (even if immediate) is not at all what is wanted. What we want is to stop *inference* and to do so *without* removing the model from memory.

**Comment by cacard** [comment]
I want clear gpu RAM, okay?...

**Comment by pdevine** [comment]
If you want to clear the model memory use `ollama stop <model>`. If you want to stop inference you can use `Ctrl + c` in the can of the ollama CLI, or you can hang up on the HTTP stream. The model will stay loaded in memory unless you have keepalive set to `0`.
