### ISSUE TITLE
Use the already downloaded models

### ISSUE THREAD

**Issue by nitulkukadia** [ollama/ollama#4078]
When we use the steps mentioned below and download the models it will create few files:
https://github.com/meta-llama/llama3?tab=readme-ov-file#quick-start

checklist.chk  consolidated.00.pth  params.json  tokenizer.model

Here these file size is in GB.

Now, I want to switch to ollama and use these files how can I do without ollama run or ollama pull command .

As this will be duplicate of the same model.

**Comment by pdevine** [comment]
@nitulkukadia check out the [import documentation](https://github.com/ollama/ollama/blob/main/docs/import.md) for how to load a model into Ollama.

**Comment by nitulkukadia** [comment]
Yes I have seen that, FROM ./mistral-7b-v0.1.Q4_0.gguf  file is the single file only,

How do we choose one of the file from below files:

checklist.chk consolidated.00.pth params.json tokenizer.model

**Comment by johnsonblue75** [comment]
> Yes I have seen that, FROM ./mistral-7b-v0.1.Q4_0.gguf file is the single file only,
> 
> How do we choose one of the file from below files:
> 
> checklist.chk consolidated.00.pth params.json tokenizer.model

Hi. I had been dealing with that too. Your best bet is to use Open Web UI: https://github.com/open-webui/open-webui.
