### ISSUE TITLE
PC crash after installing Ollama

### ISSUE THREAD

**Issue by tyseng92** [ollama/ollama#4081]
### What is the issue?

After following the installation instructions in Ollama for Windows, running `ollama pull` command will crash my PC. The same goes for WSL, crash after running the `ollama` command. 

### OS

Windows, WSL2

### GPU

Nvidia

### CPU

Intel

**Comment by dhiltgen** [comment]
@tyseng92 make sure you're running the latest nvidia drivers.  When it crashes, do you get a BSOD, and if so, which driver was active?

**Comment by dhiltgen** [comment]
If you're still seeing problems after upgrading to the latest nvidia driver, please let us know.
