### ISSUE TITLE
Unable to access ollama from other machine

### ISSUE THREAD

**Issue by rebas3** [ollama/ollama#4091]
### What is the issue?

Hi Im new to AI or develop in general and I had a question:
When I try to access on the same machine then it work normally but when I Try to connect from other machine it doesn't allow me to do that how can I allow it to connect?

### OS

macOS

### GPU

Apple

### CPU

Apple

### Ollama version

0.1.32

**Comment by centopw** [comment]
https://github.com/ollama/ollama/blob/main/docs/faq.md#setting-environment-variables-on-mac

**Comment by pdevine** [comment]
@rebas3 you can follow the directions that @centopw posted. You'll need to:
```
launchctl setenv OLLAMA_HOST "0.0.0.0"
```
and then restart ollama. Launchctl environment variables don't persist between reboots though. I'll go ahead and close the issue.
