### ISSUE TITLE
microsoft/Phi-3-mini-128k-instruct

### ISSUE THREAD

**Issue by andsty** [ollama/ollama#4092]
Hi. Is it possible to add version 128k of phi-3 in ollama?Thanks in advance.

**Comment by f0rodo** [comment]
There is a GGUF here https://huggingface.co/PrunaAI/Phi-3-mini-128k-instruct-GGUF-Imatrix-smashed/tree/main

You can just FROM :)

**Comment by mxyng** [comment]
this is now available https://ollama.com/library/phi3:mini-128k
