### ISSUE TITLE
Support NVIDIAs Llama fine-tune (chatQA-1.5)

### ISSUE THREAD

**Issue by DuckyBlender** [ollama/ollama#4101]

**Comment by DuckyBlender** [comment]
ChatQA-1.5 has two variants: ChatQA-1.5-8B and ChatQA-1.5-70B.*   
Nvidia/ChatQA-1.5-70B: [https://huggingface.co/nvidia/ChatQA-1.5-70B](https://huggingface.co/nvidia/ChatQA-1.5-70B)  
Nvidia/ChatQA-1.5-8B: [https://huggingface.co/nvidia/ChatQA-1.5-8B](https://huggingface.co/nvidia/ChatQA-1.5-8B)

**Comment by DuckyBlender** [comment]
https://ollama.com/duckyblender/chatqa

gonna try to implement this one myself

**Comment by DuckyBlender** [comment]
I've quantized the 8B version to every format and currently is uploading to HuggingFace... Can you even upload new models from huggingface to ollama? There is no documentation for this, or at least I can't find it

**Comment by thinkverse** [comment]
> Can you even upload new models from huggingface to ollama?

Yes, you need to log in or create an Ollama account on ollama.com, copy the Ollama public key to that account, and use `ollama push`. 👍 

For more step-by-step instructions I recommend reading the [import.md documentation file](https://github.com/ollama/ollama/blob/main/docs/import.md). 🙂

**Comment by DuckyBlender** [comment]
@thinkverse Thanks! How can I upload multiple .gguf files with different quantization levels?

**Comment by thinkverse** [comment]
> How can I upload multiple .gguf files with different quantization levels?

You push a model with a tag just like you'd pull a different model with a tag.

```shell
ollama push <your username>/example:tag
```

**Comment by DuckyBlender** [comment]
![image](https://github.com/ollama/ollama/assets/42645784/b9398222-230a-4740-ae73-3c35e26909a1)
uh, somethings wrong

**Comment by DuckyBlender** [comment]
> uh, somethings wrong
turns out nvidia used a very strange chat template, everything works now. also, this model is specialized for RAG applications, maybe there should be a feature in ollama which allows easier RAG?

**Comment by DuckyBlender** [comment]
This is my `Modelfile`
```
FROM ./q4_K_M.gguf
TEMPLATE """{{ if .System }}System: {{ .System }}

{{ end }}{{ if .Prompt }}User: {{ .Prompt }}

{{ end }}Assistant: {{ .Response }}
"""
PARAMETER num_keep 24
PARAMETER stop "<|start_header_id|>"
PARAMETER stop "<|eot_id|>"
PARAMETER stop "User: <|begin_of_text|>"
PARAMETER stop "User:"
```

What am I doing wrong?
![image](https://github.com/ollama/ollama/assets/42645784/47abcdfc-ce9d-48a6-b0fb-b49d282259fa)

From NVIDIA's Huggingface repo:
![image](https://github.com/ollama/ollama/assets/42645784/1a241542-c809-430b-98a9-d549d21c98da)

**Comment by Arcitec** [comment]
> maybe there should be a feature in ollama which allows easier RAG?

Have you tried the RAG support here? https://github.com/open-webui/open-webui

**Comment by rickbeeloo** [comment]
@DuckyBlender Did you manage to get ChatQA working?

**Comment by djdookie** [comment]
There seems to be an issue with Llama 3 GGUF conversion. Related? https://github.com/ggerganov/llama.cpp/issues/7062

**Comment by DuckyBlender** [comment]
> @DuckyBlender Did you manage to get ChatQA working?

Nope, waiting for more interest on this topic

**Comment by sadaisystems** [comment]
Support of ChatQA would be really nice, the model seems to be quite useful.

**Comment by thinkverse** [comment]
> Nope, waiting for more interest on this topic

Did you catch this discussion? https://huggingface.co/nvidia/Llama3-ChatQA-1.5-8B/discussions/5. There seems to be an issue with the `tokanizer_config.json` and the chat template, maybe that is causing the issue you were having.

I'm trying to pull down the weights myself but Git doesn't seem to want to do so.

**Comment by DuckyBlender** [comment]
> Did you catch this discussion? https://huggingface.co/nvidia/Llama3-ChatQA-1.5-8B/discussions/5. There seems to be an issue with the `tokanizer_config.json` and the chat template, maybe that is causing the issue you were having.

Yes, I used the correct chat template (the one I sent above)

> I'm trying to pull down the weights myself but Git doesn't seem to want to do so.
You need to do `git lfs install` when downloading large files using git. If you don't have it you can download it using `sudo apt install git-lfs`

**Comment by thinkverse** [comment]
> You need to do `git lfs install` when downloading large files using git.

I have LFS installed, I have cloned weight from HF before. 👍

**Comment by taozhiyuai** [comment]
> > This is my `Modelfile`
> > ```
> > FROM ./q4_K_M.gguf
> > TEMPLATE """{{ if .System }}System: {{ .System }}
> > 
> > {{ end }}{{ if .Prompt }}User: {{ .Prompt }}
> > 
> > {{ end }}Assistant: {{ .Response }}
> > """
> > PARAMETER num_keep 24
> > PARAMETER stop "<|start_header_id|>"
> > PARAMETER stop "<|eot_id|>"
> > PARAMETER stop "User: <|begin_of_text|>"
> > PARAMETER stop "User:"
> > ```
> 
> I used the `Modelfile` you wrote: the dialogue is basically normal, but there are some problems with the summary text and so on. I'll test it more. Thank you very much.
> 
> On second thought, maybe I'm getting too hung up on `{context}`.

I've tried this template, as you said it is not perfect.

**Comment by taozhiyuai** [comment]
> Found the available .GGUF files in the LM Studio community: [Llama3-ChatQA-1.5-8B-GGUF](https://huggingface.co/lmstudio-community/Llama3-ChatQA-1.5-8B-GGUF)
> 
> I tried to write a `Modelfile` to install it in Ollama, and it doesn't run very well, the conversation is always confusing. Maybe I wrote the `Modelfile` incorrectly...
> 
> However, on LM Studio, after following the step-by-step instructions on the model card to set up the software, there was no problem.

in LM Studio, what preset do you pick?

**Comment by spflueger** [comment]
Hi, I couldn't get this to run nicely. I'm a bit confused how to provide the context? Shouldn't the Prompt look more like

```
TEMPLATE """{{ if .System }}System: {{ .System }}

{{ end }}{{ if .Prompt }}{{ .Prompt }}

{{ end }}Assistant: {{ .Response }}
"""
```

And you would provide the context in the beginning of the prompt according to that official template together with the user query

**Comment by DuckyBlender** [comment]
Closing this issue since Ollama v0.1.35 supports ChatQA
