### ISSUE TITLE
Unexpected embedding model response ("Embedding model" blogpost)

### ISSUE THREAD

**Issue by asmith26** [ollama/ollama#4104]
### What is the issue?

Hi,

I'm running the example from https://ollama.com/blog/embedding-models, and when I look at the value of `data = results['documents'][0][0]` every time I get: 

```
Llamas are vegetarians and have very efficient digestive systems
```

The blog implies the value it gets for `data` (based on the generated answer, it doesn't actually say):

```
Llamas are members of the camelid family meaning they're pretty closely related to vicuñas and camels
```

Not sure if anyone else gets this `data` output when running the example from the "Embedding model" blogpost? Thanks!

### OS

Linux

### GPU

Nvidia

### CPU

Intel

### Ollama version

0.1.32

**Comment by thinkverse** [comment]
IDK if I'd call it unexpected. It is likely that LLama already has information related to lamas in its corpus and prioritizes that over the unrelated data in the prompt.

Trying the same example with `gemma` gives a more reasonable response given the provided data.

```shell
The provided text does not contain any information regarding the animals 
related to llamas, so I am unable to answer this question from the given context
```

If we for example switch to another embedding model like `nomic-embed-text`, which does grab more related data from our knowledge documents, `gemma` gives a better answer.

```shell
Llamas are related to vicuñas and camels, as they are all members of the camelid family.
```

**Comment by asmith26** [comment]
Thanks very much for your help @thinkverse! Can confirm when using the `nomic-embed-text` embedding model it returns the more expected information.

Just wondering, do you know if there is a useful way to determine which embedding models are better than others? Thanks again for any help!

**Comment by thinkverse** [comment]
> Just wondering, do you know if there is a useful way to determine which embedding models are better than others?

My experience with them is rather limited but for me. I use the tried and true way of trial and error. 👍 I like `nomic-embed-text` though, and haven't had any issues with it.
