### ISSUE TITLE
HTTPStatusError: Client error '404 Not Found' for url 'http://127.0.0.1:11434/api/chat'

### ISSUE THREAD

**Issue by rites1095** [ollama/ollama#4125]
### What is the issue?

i am ussing weaviate db with ollama . everything is working ifne but ate the time  generating response it is giving error "HTTPStatusError: Client error '404 Not Found' for url 'http://127.0.0.1:11434/api/chat'"

### OS

Windows

### GPU

Nvidia

### CPU

Intel

### Ollama version

0.1.7

**Comment by jmorganca** [comment]
Hi @rites1095 the `/api/chat` endpoint is available in later versions of Ollama than 0.1.7. To upgrade simply download here: https://ollama.com/download

Hope this helps!

**Comment by rites1095** [comment]
I have just installed ollama==0.1.9 . but same error it is showing pls help

**Comment by huhaopeng** [comment]
I have the same problem too,curl http://localhost:11434/api/version get {"version":"0.1.33"},but  '404 Not Found' for url 'http://127.0.0.1:11434/api/chat'"

**Comment by rites1095** [comment]
Hi ,
Till now I am facing same issue.
On running ollama it is giving requesttimeout error . Do not know why it is
taking so long.

**Comment by oss001** [comment]
Same issue here. Ubuntu 24.04.  Docker installation.  Everything works famously, but the /api/chat endpoint is not found.

'http://192.168.1.251:11434/api/version'  results with 'version | "0.1.44"'
'http://192.168.1.251:11434/api/chat' results with '404 page not found'

Not sure what I am missing here, can't seem to work this one out...
