### ISSUE TITLE
Docker Build is failing because libcurl-httpd24 .so.4 cannot be loaded

### ISSUE THREAD

**Issue by SoniCoder** [ollama/ollama#4130]
### What is the issue?

2.330 Submodule 'llama.cpp' (https://github.com/ggerganov/llama.cpp.git) registered for path '../llama.cpp'              
2.341 + git submodule update --force ../llama.cpp                                                                        
3.575 Cloning into '/go/src/github.com/ollama/ollama/llm/llama.cpp'...                                                   
3.630 /opt/rh/rh-git227/root/usr/libexec/git-core/git-remote-https: error while loading shared libraries: libcurl-httpd24
.so.4: cannot open shared object file: No such file or directory 

### OS

Linux

### GPU

Nvidia

### CPU

AMD

### Ollama version

commit is e9ae607ece49384f391e7e52e32a58addb336095

**Comment by dhiltgen** [comment]
I haven't been able to reproduce.  I did a `docker system prune` and repulled the base layers, but `./script/build_docker.sh` still works.  Can you provide some more details on how you're building?

**Comment by jmorganca** [comment]
Hi @SoniCoder is this using the Dockerfile in this repo? https://github.com/ollama/ollama/blob/main/Dockerfile if so, it should have that library. If not, you may need to install libcurl before building Ollama in a container
