### ISSUE TITLE
Add binary support for Nvidia Jetson Nano- JetPack 4

### ISSUE THREAD

**Issue by dtischler** [ollama/ollama#4140]
Hi folks, I have been experimenting with attempting to get GPU acceleration working on the older (but still nice!) Jetson Nano Developer Kit hardware with Ollama.  I have both the 2gb and 4gb RAM versions.  I've been unable to get it working, due to this situation:

Nvidia only provides JetPack 4.6 for these devices, which is based on Ubuntu 18.04, and contains built-in CUDA 10.2.  The GPU is an old Maxwell generation, `sm_53`, which needs to be added to `gen_common.sh`, no problem there.  

I install Go 1.22, and Cmake 2.29 successfully, and add to `.profile` - All good there too.

However, the challenge becomes `gcc`:  Ollama (and llama.cpp from what I gather) require gcc-11, however, CUDA 10.2 is not supported past gcc-8.  The JetPack / Ubuntu distribution includes gcc-7.5 out-of-the-box.  So attempting to build Ollama from source (because I need to add `sm_53` in gen_common.sh) results in errors, and fails of course.  I can upgrade to gcc-11 rather easily, and then a build will actually complete, but CUDA and the GPU are not usable, and it falls back to CPU inferencing.

Any ideas on how to overcome the chicken and egg scenario, or, build *only* the actual CUDA bits with gcc-7.5 but the rest of Ollama/Llama.cpp with gcc-11 ?

I actually tried injecting `update-alternatives --set gcc /usr/bin/gcc-7` into `gen_linux.sh` just before the CUDA bits, but that didn't work as the build is looping through components and some of the next bits need to go back to gcc-11 😄 

Thanks!

**Comment by dhiltgen** [comment]
Based on my current understanding, to support binary releases, we'll need one distinct cuda build for each JetPack major version. I'm going to dedup and tidy up our issues to track this with 3 distinct issues.

**Comment by dtischler** [comment]
Sounds great, thanks @dhiltgen !

**Comment by juhaem** [comment]
Greatly appreciated, just installed ollama on my Jetson Nano 4GB w/ CUDA 10.2. and it only uses CPU.

**Comment by dhiltgen** [comment]
I spent some time trying to see if I could get our build working on JP4, but as you pointed out, the GCC version requirements between CUDA v10 and llama.cpp seem to be mutually exclusive.  Unfortunately I think this combination isn't something we'll be able to support.  JP5 looks like it's going to be the oldest version we'll be able to support.

**Comment by dtischler** [comment]
Thanks for looking into it, appreciate that you all gave it a try.

**Comment by konanast** [comment]
Any updates on this topic? I tried using Ollama but was unsuccessful in getting it to utilize the GPU. It would be interesting to see if this could be supported, especially now with some of the new, smaller good models becoming available.

**Comment by felipetobars** [comment]
any update? :(
