### ISSUE TITLE
More Quants for command-r-plus Please?

### ISSUE THREAD

**Issue by chigkim** [ollama/ollama#4142]
There are only q2_K, q4_0, q8_0, and fp16 for command-r-plus.
https://ollama.com/library/command-r-plus/tags
Can we have more quants like 0/1/s/m/l of q3, q5, q6 like other models?
Thanks so much!

**Comment by taozhiyuai** [comment]
import from gguf yourself.

**Comment by chigkim** [comment]
I already did even before Ollama had. I'm requesting for other people.

**Comment by pdevine** [comment]
So you can actually do this pretty easily if you have the non-quantized version checked out either from safetensors or the ollama model. There's instructions in the [import doc](https://github.com/ollama/ollama/blob/main/docs/import.md#quantizing-a-model).

Short answer is:

1. Create a Modelfile w/ the fp16 model on the FROM line
2. Run `ollama create --quantize q4_K_M test` w/ the appropriate quantization level

Command-r is a little long in the tooth, so I'm going to go ahead and close the issue.
