### ISSUE TITLE
Supports the computing power of NPUs and GPUs provided by Intel Ultra processors

### ISSUE THREAD

**Issue by Perry961002** [ollama/ollama#4150]
I'm using an Intel Ultra processor and its GPU and NPU are never used when running the llama2 model

**Comment by Mr-Wang-YourNeighbor** [comment]
I have the same question about AMD NPU

**Comment by Mr-Wang-YourNeighbor** [comment]
In the future, having an NPU in the CPU will definitely become commonplace. I hope the author can focus more on this aspect.

**Comment by pdevine** [comment]
Going to close this as a dupe of #3004

**Comment by Mr-Wang-YourNeighbor** [comment]
all right
