### ISSUE TITLE
Add option in the install scripts to auto set OLLAMA_HOST environment variable 

### ISSUE THREAD

**Issue by centopw** [ollama/ollama#4155]
In the installer scripts, add a option that ask if user want to allow other machine on the same network to connect. Base on this docs: [faq](https://github.com/ollama/ollama/blob/main/docs/faq.md#setting-environment-variables-on-mac)

I can create a PR if needed

**Comment by jmorganca** [comment]
Hi there, setting OLLAMA_HOST is designed to be a post-install step, just so the basic install can stay small and streamlined, there should be instructions in the FAQ docs on how to do this https://github.com/ollama/ollama/blob/main/docs/faq.md#setting-environment-variables-on-mac
