### ISSUE TITLE
Can't delete all characters when typing in non-english characters.

### ISSUE THREAD

**Issue by ktkalpha** [ollama/ollama#4156]
### What is the issue?

Not all characters are erased when typing non-english text.
It's not typed in the prompt, but it's inconvenient when using the non-english LLM.

<img width="432" alt="스크린샷 2024-05-05 오전 8 19 05" src="https://github.com/ollama/ollama/assets/57173745/17c0a1cb-1826-4dd7-b141-ba262be3b76a">

### OS

macOS

### GPU

Apple

### CPU

Apple

### Ollama version

0.1.33

**Comment by taozhiyuai** [comment]
same for other non-english characters. :(
