### ISSUE TITLE
Concurrency Issue: 'Server Busy' Errors After Updating Ollama

### ISSUE THREAD

**Issue by mynhinguyentruong** [ollama/ollama#4159]
### What is the issue?

Issue Summary:
Yesterday, I conducted a test where I spun up 30 concurrent goroutines and sent them as POST requests to Ollama locally. The process worked smoothly, and I received responses within approximately 2 minutes.

`go ProcessPromptWithOllama()` x30 times

Problem Description:
However, after updating Ollama today, I encountered the following errors:

`\"error\":\"server busy, please try again. maximum pending requests exceeded\"}`
`\"error\":\"unexpected server status: llm busy - no slots available\"}`
Reproducibility:
The issue is consistently reproducible after the Ollama update. It occurs regardless of the specific endpoint or payload used in the POST requests.

Expected Behavior:
I expected the updated Ollama to handle the concurrent requests as efficiently as it did before the update, without encountering any server overload issues.

### OS

macOS

### GPU

Apple

### CPU

Apple

### Ollama version

0.1.33

**Comment by jmorganca** [comment]
Hi @mynhinguyentruong, I'm so sorry about this issue – we'll get this fixed so more requests can be queued

**Comment by dhiltgen** [comment]
Dup of #4124
