### ISSUE TITLE
abnormal reply of Llama-3-ChatQA-1.5-8B-GGUF 

### ISSUE THREAD

**Issue by taozhiyuai** [ollama/ollama#4167]
### What is the issue?

import Llama-3-ChatQA-1.5-8B-GGUF to ollama, but reply is abnormal. I have tried many gguf version of this model from different username on HF.

### OS

macOS

### GPU

Apple

### CPU

Apple

### Ollama version

0.1..32

**Comment by DuckyBlender** [comment]
Llama 3 ChatQA is a very wierd model which is optimised for RAG. It's still not 100% supported in ollama

**Comment by taozhiyuai** [comment]
> Llama 3 ChatQA is a very wierd model which is optimised for RAG. It's still not 100% supported in ollama

70B works. only 8B not.

https://ollama.com/taozhiyuai/llama3-chatqa-1.5-70b.q4_k_m

https://ollama.com/taozhiyuai/llama3-chatqa-1.5-70b.q8_0

**Comment by thinkverse** [comment]
Maybe try the version The Ollama team released a few hours ago - https://ollama.com/library/llama3-chatqa, as part of the [0.1.35 release](https://github.com/ollama/ollama/releases/tag/v0.1.35).

**Comment by Erik262** [comment]
Do you know which Embedding Model works best with llama3-chatqa? or in general? (5GB max model size)
