### ISSUE TITLE
AMD GPUs mistaken as Nvidia GPUs

### ISSUE THREAD

**Issue by eliranwong** [ollama/ollama#4173]
### What is the issue?

My device runs Ubuntu with dual AMD GPUs, both are RX 7900 XTX. 

I set up the GPUs with ROCM.  I keep a copy of my setup at https://github.com/eliranwong/MultiAMDGPU_AIDev_Ubuntu

I just tried installing ollama.  Surprisingly, the last line reads "NVIDIA GPU installed."

>>> Adding ollama user to render group...
>>> Adding ollama user to video group...
>>> Adding current user to ollama group...
>>> Creating ollama systemd service...
>>> Enabling and starting ollama service...
>>> NVIDIA GPU installed.

### OS

Linux

### GPU

AMD

### CPU

AMD

### Ollama version

0.1.33

**Comment by dhiltgen** [comment]
The install script reports this if `nvidia-smi` is present, so my suspicion is you previously installed that.  I don't see `Installing NVIDIA repository` in the output you shared, so we didn't install the CUDA drivers, so while this log message is a little misleading/confusing, I don't think the install script actually did anything incorrectly.

Does Ollama work correctly on your Radeon GPUs?

**Comment by eliranwong** [comment]
I can see ollama is working, but how may I know if it utilised GPU acceleration?

**Comment by dhiltgen** [comment]
We don't yet have a way to see in the CLI, but you can check the server logs.  

For example...
```
llm_load_tensors: offloading 32 repeating layers to GPU
llm_load_tensors: offloading non-repeating layers to GPU
llm_load_tensors: offloaded 33/33 layers to GPU
```

**Comment by eabase** [comment]
@dhiltgen 
> The install script reports this if `nvidia-smi` is present, 

That's a very poor method, you could at least have parsed it's output.

Also, I can see use cases where people have both AMD & Nvidia GPUs...

Why not check with:
```powershell
wmic path win32_VideoController get name

# or

(Get-CimInstance -ClassName CIM_VideoController) | select Name, DeviceId
```

**Comment by eliranwong** [comment]
> @dhiltgen
> 
> > The install script reports this if `nvidia-smi` is present,
> 
> That's a very poor method, you could at least have parsed it's output.
> 
> Also, I can see use cases where people have both AMD & Nvidia GPUs...
> 
> Why not check with:
> 
> ```powershell
> wmic path win32_VideoController get name
> 
> # or
> 
> (Get-CimInstance -ClassName CIM_VideoController) | select Name, DeviceId
> ```

I guess win32 is irrelevant to my case, I use Ubuntu.  Anyway, I remove Nvidia things, and it is now clean for installation, but with a bigger issue in running:

![amdgpu_ollama](https://github.com/eliranwong/freegenius/assets/25262722/c985062b-da23-4879-8d55-76b16e1017f3)

It appears that running Ollama with GPUs is very unstable in my device.  It crashes a lot.  I use llama.cpp to run the same model files directly without an issue.

**Comment by dhiltgen** [comment]
@eliranwong can you share your server log so we can see where it's having problems?

https://github.com/ollama/ollama/blob/main/docs/troubleshooting.md

**Comment by eliranwong** [comment]
My screen go green not long I start ollama.  I just tried again, below is the log:

Started Ollama Service.
ollama[2103]: time=2024-05-07T13:25:37.108+01:00 level=INFO source=images.go:828 msg="total blobs: 22"
ollama[2103]: time=2024-05-07T13:25:37.109+01:00 level=INFO source=images.go:835 msg="total unused blobs removed: 0"
ollama[2103]: time=2024-05-07T13:25:37.109+01:00 level=INFO source=routes.go:1071 msg="Listening on 127.0.0.1:11434 (version 0.1.33)"
ollama[2103]: time=2024-05-07T13:25:37.110+01:00 level=INFO source=payload.go:30 msg="extracting embedded files" dir=/tmp/ollama953288552/runners
ollama[2103]: time=2024-05-07T13:25:38.831+01:00 level=INFO source=payload.go:44 msg="Dynamic LLM libraries [cpu cpu_avx cpu_avx2 cuda_v11 rocm_v60002]"
ollama[2103]: time=2024-05-07T13:25:38.831+01:00 level=INFO source=gpu.go:96 msg="Detecting GPUs"
ollama[2103]: time=2024-05-07T13:25:38.833+01:00 level=INFO source=cpu_common.go:11 msg="CPU has AVX2"
ollama[2103]: time=2024-05-07T13:25:38.833+01:00 level=INFO source=amd_linux.go:46 msg="AMD Driver: 6.3.6"
ollama[2103]: time=2024-05-07T13:25:38.834+01:00 level=INFO source=amd_linux.go:217 msg="amdgpu memory" gpu=0 total="24560.0 MiB"
ollama[2103]: time=2024-05-07T13:25:38.834+01:00 level=INFO source=amd_linux.go:218 msg="amdgpu memory" gpu=0 available="24533.4 MiB"
ollama[2103]: time=2024-05-07T13:25:38.843+01:00 level=INFO source=amd_linux.go:276 msg="amdgpu is supported" gpu=0 gpu_type=gfx1100
ollama[2103]: time=2024-05-07T13:25:38.843+01:00 level=INFO source=amd_linux.go:217 msg="amdgpu memory" gpu=1 total="24560.0 MiB"
ollama[2103]: time=2024-05-07T13:25:38.843+01:00 level=INFO source=amd_linux.go:218 msg="amdgpu memory" gpu=1 available="24434.4 MiB"
ollama[2103]: time=2024-05-07T13:25:38.843+01:00 level=INFO source=amd_linux.go:276 msg="amdgpu is supported" gpu=1 gpu_type=gfx1100

**Comment by dhiltgen** [comment]
What you describe sounds like a driver bug.  Please make sure you're running the latest drivers from AMD.

**Comment by eliranwong** [comment]
I load and swap the same models with llama.cpp without an issue.   same system, same driver

**Comment by alexleduc76** [comment]
> We don't yet have a way to see in the CLI, but you can check the server logs.
> 
> For example...
> 
> ```
> llm_load_tensors: offloading 32 repeating layers to GPU
> llm_load_tensors: offloading non-repeating layers to GPU
> llm_load_tensors: offloaded 33/33 layers to GPU
> ```

On Linux you can install amdgpu_top, and you will see if it accelerates your prompts. If it doesn't, any other tool that can show you CPU usage (btop, bottom, top, etc.) will show all your cores being used in a high percentage
