### ISSUE TITLE
pull qwen:32b-chat-v1.5-q4_0 Error: unexpected end of JSON input

### ISSUE THREAD

**Issue by MarkWard0110** [ollama/ollama#4179]
### What is the issue?

`ollama pull qwen:32b-chat-v1.5-q4_0` results in `Error: unepxected end of JSON input`

However, `ollama pull qwen:32b` works (right now they point to the same hash)

### OS

Linux

### GPU

Nvidia

### CPU

Intel

### Ollama version

0.1.33

**Comment by BruceMacD** [comment]
Consolidating into #4185
