### ISSUE TITLE
Failure on pull results in Error: EOF

### ISSUE THREAD

**Issue by MarkWard0110** [ollama/ollama#4185]
### What is the issue?

`ollama pull orca-mini:13b-v3-fp16` results in `Error: EOF`

### OS

Linux

### GPU

Nvidia

### CPU

Intel

### Ollama version

0.1.33

**Comment by MarkWard0110** [comment]
I deleted my model's directory, which "fixed" the problem.  Maybe there were partial files and bad configuration states that Ollama was unable to resolve itself.

**Comment by pdevine** [comment]
I'm not sure if the `pull` resulted in the EOF, or if `ollama run` caused the EOF error. If it was the pull, it was most likely a transient error from cloudflare.

I'll go ahead and close the issue, but we can reopen if you're still seeing it.
