### ISSUE TITLE
Tokenize and Detokenize API For Token Count

### ISSUE THREAD

**Issue by sslx** [ollama/ollama#4186]
For rag purposes, I'd love to find out the token count for text before feeding to a model for a response.
Could you connect api points for tokenize and detokenize on llama.cpp?
Thanks!

**Comment by jmorganca** [comment]
Hi there thanks for the issue! Merging with https://github.com/ollama/ollama/issues/3021

**Comment by functorism** [comment]
@jmorganca This request seems to reappear regularly. Could you share if there's a reason it hasn't been addressed yet; and if pull requests for it are welcome?
