### ISSUE TITLE
mixtral:8x22b has missing weights

### ISSUE THREAD

**Issue by codebam** [ollama/ollama#4193]
### What is the issue?

❯ ollama run mixtral:8x22b
Error: exception create_tensor: tensor 'blk.0.ffn_gate.0.weight' not found

### OS

Linux

### GPU

AMD

### CPU

AMD

### Ollama version

0.1.31

**Comment by BruceMacD** [comment]
Hi @codebam, thanks for reporting this. Looks like this is another instance of #3667.[ Updating to the latest version of Ollama](https://github.com/ollama/ollama/blob/main/docs/linux.md#update) will fix the issue. Please let me know if that's not the case.
