### ISSUE TITLE
how to download and run ollama and llma 3 in docker can u give me the docker file code for that

### ISSUE THREAD

**Issue by sushantsk1** [ollama/ollama#4195]
i want to download and run llmaa 3 using ollama on docker help me and give the code for docker file

**Comment by jmorganca** [comment]
Hi there the Dockerfile for Ollama is here: https://github.com/ollama/ollama/blob/main/Dockerfile

You may use it to run llama3 like so:

```
docker run -d -v ollama:/root/.ollama -p 11434:11434 --name ollama ollama/ollama
docker exec -it ollama ollama run llama3
```
