### ISSUE TITLE
http://localhost:11434/api endpoint giving 404 error

### ISSUE THREAD

**Issue by ritesh7911** [ollama/ollama#4200]
### What is the issue?

I am using latest version of windows . As per readme file when I am hitting http://localhost:11434 i am getting "ollama is running" but "http://localhost:11434/api" is giving error 404

### OS

Windows

### GPU

AMD

### CPU

Intel

### Ollama version

0.1.33

**Comment by swapnil34** [comment]
I am experiencing issues with API endpoint as well. Here is the server log:

[GIN] 2024/05/07 - 07:41:01 | 200 |  4.894709434s |       127.0.0.1 | POST     "/api/chat"
[GIN] 2024/05/07 - 07:41:07 | **404** |       9.017µs |       127.0.0.1 | GET      "/api/generate/"
[GIN] 2024/05/07 - 07:41:13 | 200 |      10.527µs |       127.0.0.1 | GET      "/"

**Comment by swapnil34** [comment]
Solution: The API endpoint doesn't respond to GET requests, POST requests seem to be working.

**Comment by dhiltgen** [comment]
@ritesh7911 are you trying to use GET to this API?  See https://github.com/ollama/ollama/blob/main/docs/api.md#generate-a-completion for usage information.

If it isn't working as described in the API docs, please share more information about how you're calling it and I'll re-open the issue.
