### ISSUE TITLE
docker run ollama v0.1.33，from gguf to make modelfile，got an error：FROM not found

### ISSUE THREAD

**Issue by ddbon-calvin** [ollama/ollama#4201]
### What is the issue?

docker run ollama v0.1.33，from gguf to make modelfile，got an error：FROM not found

### OS

Docker

### GPU

Nvidia

### Ollama version

0.1.33

**Comment by Sakura4036** [comment]
I got same probelm. How i can create a local guuf model in ollama docker container?
