### ISSUE TITLE
An existing connection was forcibly closed by the remote host.

### ISSUE THREAD

**Issue by zhangweiwei0326** [ollama/ollama#4202]
### What is the issue?

![image](https://github.com/ollama/ollama/assets/5975616/c8c90991-a0bd-40d3-b255-fd3b90cbaf68)
No matter how it is done, it is the error. Replacing the agent without using the agent is invalid. Please provide a thorough solution. thank you

**Comment by dhiltgen** [comment]
Looks like a dup of #3504
