### ISSUE TITLE
please support deepseek-ai/DeepSeek-V2-Chat

### ISSUE THREAD

**Issue by taozhiyuai** [ollama/ollama#4205]
please support deepseek-ai/DeepSeek-V2-Chat

https://hf-mirror.com/deepseek-ai/DeepSeek-V2-Chat/tree/main

**Comment by DirtyKnightForVi** [comment]
+1 
The DeepSeek-V2-Chat is a different MOE architecture compared to DBRX, Mixtral, and GLM-4. In terms of API experience, it's on par with GPT-4
