### ISSUE TITLE
(Prune unwanted dangling models) Prune data from models which where partially downloaded  

### ISSUE THREAD

**Issue by arthurGrigo** [ollama/ollama#4214]
Sometime it happens that a user starts to download the wrong model or runs out of space (https://github.com/ollama/ollama/issues/2497).

The partially downloaded model is not visible through 'ollama list' after canceling the download and therefore cannot be removed using 'ollama rm <model>'.

At the moment users have to find the corresponding sha and blob in the ollama directory and remove it manually or fully download the model just to be able to delete it.

Path for windows users: "C:\Users\your_user\ .ollama\models\blobs"

A command like 'ollama prune' or 'ollama autoremove' would be great.

**Comment by jmorganca** [comment]
Hi @arthurGrigo in this case you can restart Ollama which will prune. Pruning also happens on `ollama create` and I think `ollama pull`. Let me know if this helps!

**Comment by kamathln** [comment]
Would still love a prune command, just to put system admin's / ML OP's mind to ease. Current method still feels a bit unpolished and hackish.

On a related note - if the incomplete download is tried to be pulled again, does it restart or continue from where it left off?
