### ISSUE TITLE
DeepSeek发布全球最强开源第二代MoE模型：DeepSeek-V2！

### ISSUE THREAD

**Issue by tqangxl** [ollama/ollama#4221]
https://mp.weixin.qq.com/s/3AmJpYe1eLPHk7HJLYM24A
pls add  DeepSeek-V2
模型&论文双开源

深度求索始终秉持着最开放的开源精神，以开源推动人类AGI事业的前行。这次的DeepSeek-V2模型和论文也将完全开源，免费商用，无需申请：

模型权重：

https://huggingface.co/deepseek-ai
技术报告：

https://github.com/deepseek-ai/DeepSeek-V2/blob/main/deepseek-v2-tech-report.pdf

**Comment by wwjCMP** [comment]
https://github.com/ollama/ollama/issues/4205

**Comment by xinge666** [comment]
> not much better performance than llama 3, but 3 times bigger in size than 70B. not recommended to run only most personal machine.

this maybe a CPU friendly model

**Comment by jmorganca** [comment]
https://ollama.com/library/deepseek-v2
