### ISSUE TITLE
run llama3-70B-q8_0  error

### ISSUE THREAD

**Issue by leoHostProject** [ollama/ollama#4226]
### What is the issue?

api call error
message:
{"error":{"message":"timed out waiting for llama runner to start:CUDA error:uncorrectable ECC error encountered\
n current device:0,in function ggml cuda_compute_forward at /go/src/github.com/ollama/ollama/11m/1lama.cpp/ggml
-cuda.cu:2300\n err\nGGML_ASSERT:/go/src/github.com/ollama/ollama/11m/1lama.cpp/ggml-cuda.cu:60:!\"CUDA error\"
""type":"api_error","param"null,"code":null}}

### OS

Linux, Docker

### GPU

Nvidia

### CPU

Intel

**Comment by dhiltgen** [comment]
I'm able to load this model on a 48G CUDA card.

`uncorrectable ECC error encountered` sounds like a hardware fault on your GPU.
