### ISSUE TITLE
Allow for specifying and checking the directory where models are stored

### ISSUE THREAD

**Issue by K0-RR** [ollama/ollama#4233]
How do I locate the downloaded files? This should be possible via some `ollama` command.
When pulling we should be asked where do we want the data to be saved.

Both `~/.ollama/models` and `/usr/share/ollama/` **don't exist** on my machine and yet I'm interacting with llama3!

**Comment by pdevine** [comment]
Hey @K0-RR , This is covered in the [FAQ](https://github.com/ollama/ollama/blob/main/docs/faq.md#where-are-models-stored).
