### ISSUE TITLE
Customized LLaVA Setup

### ISSUE THREAD

**Issue by zhangry868** [ollama/ollama#4234]
I wonder whether there is a guideline on hosting customized LLaVA model. I have both mmprojector and base models gguf files. Feel free to point me any related materials/links.

Many thanks,
Rui

**Comment by jmorganca** [comment]
Hi Rui,

For using LLaVA models with `ollama create`, check out this example: https://huggingface.co/xtuner/llava-phi-3-mini-gguf/blob/main/OLLAMA_MODELFILE_F16 which shows how to build an Ollama model from both the language and projector files.

Hope this helps!
