### ISSUE TITLE
Get a random available port

### ISSUE THREAD

**Issue by RobbyCBennett** [ollama/ollama#4237]
This would be perfect for making Ollama a child process.

Here's what this may look like:
1. The parent process starts
2. The parent process does a command like `env OLLAMA_HOST=localhost:random ollama serve`
3. The child process `ollama` gets a random available port from the OS and outputs the port number to stdout. Otherwise, it crashes.

**Comment by mxyng** [comment]
This is already possible if you set `OLLAMA_HOST=:0`
