### ISSUE TITLE
AMD Vega64 gfx900 not supported on Windows

### ISSUE THREAD

**Issue by bryndin** [ollama/ollama#4239]
### What is the issue?

The Ollama lists Vega64 in the announcement, but running it says it's not supported.

Tried with fresh install of Ollama 0.1.33 and 0.1.34 on Win10.

Tried to install HIP (`AMD-Software-PRO-Edition-23.Q4-Win10-Win11-For-HIP.exe`) with no success either. 

`time=2024-05-07T15:12:43.123-07:00 level=INFO source=gpu.go:122 msg="Detecting GPUs"
time=2024-05-07T15:12:43.159-07:00 level=INFO source=cpu_common.go:11 msg="CPU has AVX2"
time=2024-05-07T15:12:43.178-07:00 level=INFO source=amd_windows.go:39 msg="AMD Driver: 50731541"
time=2024-05-07T15:12:43.181-07:00 level=INFO source=amd_windows.go:68 msg="detected hip devices" count=1
time=2024-05-07T15:12:43.181-07:00 level=INFO source=amd_windows.go:88 msg="hip device" id=0 name="Radeon RX Vega" gfx=gfx900:xnack-
time=2024-05-07T15:12:43.181-07:00 level=WARN source=amd_windows.go:104 msg="amdgpu is not supported" gpu=0 gpu_type=gfx900:xnack- library="C:\\Program Files\\AMD\\ROCm\\5.7\\bin" supported_types="[gfx1030 gfx1100 gfx1101 gfx1102 gfx906]"
time=2024-05-07T15:12:43.181-07:00 level=WARN source=amd_windows.go:106 msg="See https://github.com/ollama/ollama/blob/main/docs/troubleshooting.md for HSA_OVERRIDE_GFX_VERSION usage"
`

### OS

Windows

### GPU

AMD

### CPU

AMD

### Ollama version

0.1.34

**Comment by dhiltgen** [comment]
It looks like you're correct, and the ROCm Library from AMD on windows has a reduced set of GPUs it supports compared to Linux.  Our GPU list was based on the Linux support matrix and we missed this gap on Windows in the underlying library.

**Comment by bryndin** [comment]
Windows 5.5.1 and 5.7.1 ROCm have Vega (gfx900) out of support and I don't see prior ROCm releases available for Windows.

I don't even know if it is supported on Linux: 
https://rocm.docs.amd.com/en/docs-5.7.1/release/gpu_os_support.html

Btw, do you know if it's possible to use Linux ROCm with Ubuntu on Windows WSL2?
My vague understanding, WSL has direct access to Win GPU and thus is powered by the Win driver, not the Linux one.

**Comment by dhiltgen** [comment]
Unfortunately given the changes in ROCm on windows, this has fallen off the support matrix.  I've updated the build and docs to make this clearer for Windows in #5815.  It may be possible to build from source on an older ROCm library, but for the official release, we'll need to stay current to pick up bug fixes for the newer GPUs.
