### ISSUE TITLE
Ollama using minimal GPU  on Windows

### ISSUE THREAD

**Issue by Freffles** [ollama/ollama#4251]
Had this problem for a while and thought it was fixed in 1.34 Have GTX1050 Ti, not being used by Ollama. Here is a partial log file.

[ollama_logsextract.txt](https://github.com/ollama/ollama/files/15244475/ollama_logsextract.txt)

**Comment by dhiltgen** [comment]
My suspicion is your client may be setting num_gpu to 1 in the request.  Is that possible?

**Comment by Freffles** [comment]
I guess it's possible, I had been using the model_name and hence the rest was at default settings.  I will try giving it a tweak and see if there is any improvement. If it shouldn't be 1, what should it be?

**Comment by dhiltgen** [comment]
This setting defines how many layers to load into the GPU.  If unspecified or set to -1 the system will load as many layers as possible.  I believe we had a bug in prior versions where a "1" was treated the same as -1 and resulted in the system loading as many layers as possible, which is likely what you want for best performance.

**Comment by Freffles** [comment]
This is how I'm setting up:
```
def get_ollama_settings(embeddings_model): # See parameters comment below for more info. Current at 8 May 2024
    return {
        "model": embeddings_model,
        "embed_instruction": "text: ",
        "query_instruction": "query: ",
        "num_ctx": 1024,
        "num_gpu": -1,
        "num_thread": 1,
        "repeat_last_n": 64,
        "repeat_penalty": 1.1,
        "temperature": 0.8,
        "tfs_z": 1.0,
        "top_k": 40,
        "top_p": 0.95,
        "show_progress": True
    }
```
Screenshot of progress. This speed is unchanged despite multiple ollama & cuda removals, reinstalls and tweaks
![image](https://github.com/ollama/ollama/assets/122719748/9b653221-ae2c-4dea-b727-2b2875778879)

[ollama_logs.txt](https://github.com/ollama/ollama/files/15255775/ollama_logs.txt)

**Comment by Freffles** [comment]
FYI, tried using Anything LLM and it seemed to work much better.
[LLMollama_logs.txt](https://github.com/ollama/ollama/files/15256953/LLMollama_logs.txt)

**Comment by dhiltgen** [comment]
The latest logs you shared shows it loading all the layers into the GPU

ollama_logs.txt:
```
llm_load_tensors: offloaded 13/13 layers to GPU
```

LLMollama_logs.txt:
```
llm_load_tensors: offloaded 32/33 layers to GPU
```

This is in comparison to the log you shared in the opening comment of the issue which only loaded 1 of 13 layers.

**Comment by Freffles** [comment]
I will have another look at this when I'm in front of the computer. Meanwhile, the log file reflects one session where I was using my own python code and then using Anything LLM with no other changes. When I use the latter, more GPU is used.

**Comment by Freffles** [comment]
FYI, I just managed to complete embeddings of a github repo using ollama nomic-embed-text via Anything LLM and using Chroma in about 3 minutes. That had been taking over 20 previously. Here is the log file, I will try this again outside of LLM and see what happens.

[ollama_logs.txt](https://github.com/ollama/ollama/files/15290928/ollama_logs.txt)

**Comment by dhiltgen** [comment]
As of v0.2.6 (and newer) the embeddings API now takes a list of embeddings, and will parallelize the processing.  Let us know if that addresses the performance problem you were facing.

https://github.com/ollama/ollama/blob/main/docs/api.md#generate-embeddings

**Comment by ashokgelal** [comment]
If -1 is "auto", is there a magic number for "max"? For an app that provides an interface to Ollama, what should it use so that the user can say "I want to use max GPU layers". Or is -1 more like max?

**Comment by dhiltgen** [comment]
@ashokgelal don't set any override environment variables or parameters and ollama will strive to maximize VRAM utilization.

**Comment by ashokgelal** [comment]
Thanks @dhiltgen. Is that the same as setting it to -1? If not, what does it do?

**Comment by dhiltgen** [comment]
@ashokgelal I don't know what operating system you're on, so it varies, but in windows, you'd delete the entry from the dialog for environment variables.  On Linux you'd remove the entry from your systemd configuration.  On mac you use launchctl.  Instructions can be found here - https://github.com/ollama/ollama/blob/main/docs/faq.md#how-do-i-configure-ollama-server.

I'll go ahead and close this one now as it should work much better/faster.  @Freffles if you're still seeing performance problems with the new batch support, please provide some updated information and I'll reopen.
