### ISSUE TITLE
Ollama中文社区群聊发布

### ISSUE THREAD

**Issue by zsq2010** [ollama/ollama#4252]
QQ:
808227197

![8edec8b588a5634e72ec6eecba1ec305](https://github.com/ollama/ollama/assets/4374659/33b6343c-a177-43cc-b41f-ddf0e5b1e329)

欢迎加入交流分享信息!!

**Comment by jmorganca** [comment]
Hi there, thanks for the issue! I will close this as it isn't actionable

**Comment by zsq2010** [comment]
微信群主号:incityMEGA
