### ISSUE TITLE
The ollama model how  resides on the gpu?

### ISSUE THREAD

**Issue by lonngxiang** [ollama/ollama#4254]

**Comment by dhiltgen** [comment]
Can you clarify your ask?  Does this [PR](https://github.com/ollama/ollama/pull/4153) address what you are looking for?

**Comment by taozhiyuai** [comment]
he may ask to keep model in GPU RAM all the time, even it does not used for a very long time.

**Comment by lonngxiang** [comment]
> he may ask to keep model in GPU RAM all the time, even it does not used for a very long time.

Yes, that's what it means @dhiltgen

**Comment by taozhiyuai** [comment]
> > he may ask to keep model in GPU RAM all the time, even it does not used for a very long time.
> 
> Yes, that's what it means @dhiltgen

I think it is advantage of Ollama which enhance the performance of machine. If you may try LM Studio which meet your need.@lonngxiang

**Comment by dhiltgen** [comment]
See https://github.com/ollama/ollama/blob/main/docs/faq.md#how-do-i-keep-a-model-loaded-in-memory-or-make-it-unload-immediately

In short, set `keep_alive` to a negative number and the model will stay loaded indefinitely.
