### ISSUE TITLE
Ollama 0.1.34 not working on AGX Orin 64gb while no issue on 0.1.30

### ISSUE THREAD

**Issue by casimirextreme** [ollama/ollama#4256]
### What is the issue?

It was perfectly working on 0.1.30 that I've compiled. Now either the official release nor my compiled version is working

Ollama "serve" hangs with:
`CUDA error: the resource allocation failed
  current device: 0, in function cublas_handle at /data/llm/llama.cpp/ggml-cuda/common.cuh:526
  cublasCreate_v2(&cublas_handles[device])
GGML_ASSERT: /data/llm/llama.cpp/ggml-cuda.cu:60: !"CUDA error"
Could not attach to process.  If your uid matches the uid of the target
process, check the setting of /proc/sys/kernel/yama/ptrace_scope, or try
again as the root user.  For more details, see /etc/sysctl.d/10-ptrace.conf
ptrace: Inappropriate ioctl for device.
No stack.
The program is not being run.`

I've added the logs of both versions:
[agx-orin-0.1.34.txt](https://github.com/ollama/ollama/files/15247743/agx-orin-0.1.34.txt)
[agx-orin-0.1.30.txt](https://github.com/ollama/ollama/files/15247744/agx-orin-0.1.30.txt)

It was compiled with:
`OLLAMA_SKIP_CPU_GENERATE="1"
CMAKE_CUDA_ARCHITECTURES="72;87"
`
Is there any known issue with Jetson AGX orin?

### OS

Linux

### GPU

Nvidia

### CPU

Other

### Ollama version

0.1.34

**Comment by casimirextreme** [comment]
Found the issue. The docker image used to compile was not the correct one.
One should use nvcr.io/nvidia/l4t-cuda:12.2.12-devel 
for the AGX Orin 64gb

**Comment by qubeck** [comment]
Hello,
I ran in to the same problem with 0.1.38 on Jetson Xavier NX.
Is the official build for arm64 going to be fixed again or is that particular CUDA version not a priority for some reason?
