### ISSUE TITLE
Error: could not connect to ollama app, is it running?

### ISSUE THREAD

**Issue by starMagic** [ollama/ollama#4260]
### What is the issue?

When try run command "Ollama list", the following error occurs:
server.log

2024/05/08 20:50:26 routes.go:989: INFO server config env="map[OLLAMA_DEBUG:false OLLAMA_LLM_LIBRARY: OLLAMA_MAX_LOADED_MODELS:1 OLLAMA_MAX_QUEUE:512 OLLAMA_MAX_VRAM:0 OLLAMA_NOPRUNE:false OLLAMA_NUM_PARALLEL:1 OLLAMA_ORIGINS:[* http://localhost https://localhost http://localhost:* https://localhost:* http://127.0.0.1 https://127.0.0.1 http://127.0.0.1:* https://127.0.0.1:* http://0.0.0.0 https://0.0.0.0 http://0.0.0.0:* https://0.0.0.0:*] OLLAMA_RUNNERS_DIR:C:\\Users\\Qiang.Liu\\AppData\\Local\\Programs\\Ollama\\ollama_runners OLLAMA_TMPDIR:]"
time=2024-05-08T20:50:26.065+08:00 level=INFO source=images.go:897 msg="total blobs: 16"
time=2024-05-08T20:50:26.068+08:00 level=INFO source=images.go:904 msg="total unused blobs removed: 0"
time=2024-05-08T20:50:26.071+08:00 level=INFO source=routes.go:1034 msg="Listening on 127.0.0.1:11434 (version 0.1.34)"
time=2024-05-08T20:50:26.071+08:00 level=INFO source=payload.go:44 msg="Dynamic LLM libraries [cpu cpu_avx cpu_avx2 cuda_v11.3 rocm_v5.7]"
time=2024-05-08T20:50:26.071+08:00 level=INFO source=gpu.go:122 msg="Detecting GPUs"
time=2024-05-08T20:50:26.091+08:00 level=INFO source=cpu_common.go:15 msg="CPU has AVX"
Exception 0xc0000005 0x8 0x228ed7065e0 0x228ed7065e0
PC=0x228ed7065e0
signal arrived during external code execution

runtime.cgocall(0xf73c20, 0xc000680408)
	runtime/cgocall.go:157 +0x3e fp=0xc0003850d0 sp=0xc000385098 pc=0xf092fe
syscall.SyscallN(0x7ffdc82ddcd0?, {0xc0000ff758?, 0x1?, 0x7ffdc7fd0000?})
	runtime/syscall_windows.go:544 +0x107 fp=0xc000385148 sp=0xc0003850d0 pc=0xf6f147
github.com/ollama/ollama/gpu.(*HipLib).AMDDriverVersion(0xc0000be750)
	github.com/ollama/ollama/gpu/amd_hip_windows.go:82 +0x69 fp=0xc0003851b8 sp=0xc000385148 pc=0x139fc09
github.com/ollama/ollama/gpu.AMDGetGPUInfo()
	github.com/ollama/ollama/gpu/amd_windows.go:37 +0x91 fp=0xc000385840 sp=0xc0003851b8 pc=0x13a0331
github.com/ollama/ollama/gpu.GetGPUInfo()
	github.com/ollama/ollama/gpu/gpu.go:214 +0x625 fp=0xc000385ae8 sp=0xc000385840 pc=0x13a4845
github.com/ollama/ollama/server.Serve({0x2009900, 0xc000276bc0})
	github.com/ollama/ollama/server/routes.go:1059 +0x771 fp=0xc000385c70 sp=0xc000385ae8 pc=0x19ef231
github.com/ollama/ollama/cmd.RunServer(0xc0000a8b00?, {0x27b2ae0?, 0x4?, 0x1e6cc3e?})
	github.com/ollama/ollama/cmd/cmd.go:901 +0x17c fp=0xc000385d58 sp=0xc000385c70 pc=0x1a092dc
github.com/spf13/cobra.(*Command).execute(0xc0004b4908, {0x27b2ae0, 0x0, 0x0})
	github.com/spf13/cobra@v1.7.0/command.go:940 +0x882 fp=0xc000385e78 sp=0xc000385d58 pc=0x12aaa22
github.com/spf13/cobra.(*Command).ExecuteC(0xc00002d808)
	github.com/spf13/cobra@v1.7.0/command.go:1068 +0x3a5 fp=0xc000385f30 sp=0xc000385e78 pc=0x12ab265
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.7.0/command.go:992
github.com/spf13/cobra.(*Command).ExecuteContext(...)
	github.com/spf13/cobra@v1.7.0/command.go:985
main.main()
	github.com/ollama/ollama/main.go:11 +0x4d fp=0xc000385f50 sp=0xc000385f30 pc=0x1a1208d
runtime.main()
	runtime/proc.go:271 +0x28b fp=0xc000385fe0 sp=0xc000385f50 pc=0xf4134b
runtime.goexit({})
	runtime/asm_amd64.s:1695 +0x1 fp=0xc000385fe8 sp=0xc000385fe0 pc=0xf72461

goroutine 2 gp=0xc000084700 m=nil [force gc (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	runtime/proc.go:402 +0xce fp=0xc000087fa8 sp=0xc000087f88 pc=0xf4174e
runtime.goparkunlock(...)
	runtime/proc.go:408
runtime.forcegchelper()
	runtime/proc.go:326 +0xb8 fp=0xc000087fe0 sp=0xc000087fa8 pc=0xf415d8
runtime.goexit({})
	runtime/asm_amd64.s:1695 +0x1 fp=0xc000087fe8 sp=0xc000087fe0 pc=0xf72461
created by runtime.init.6 in goroutine 1
	runtime/proc.go:314 +0x1a

goroutine 3 gp=0xc000084a80 m=nil [GC sweep wait]:
runtime.gopark(0x1?, 0x0?, 0x0?, 0x0?, 0x0?)
	runtime/proc.go:402 +0xce fp=0xc000089f80 sp=0xc000089f60 pc=0xf4174e
runtime.goparkunlock(...)
	runtime/proc.go:408
runtime.bgsweep(0xc00003a070)
	runtime/mgcsweep.go:318 +0xdf fp=0xc000089fc8 sp=0xc000089f80 pc=0xf2b7ff
runtime.gcenable.gowrap1()
	runtime/mgc.go:203 +0x25 fp=0xc000089fe0 sp=0xc000089fc8 pc=0xf200a5
runtime.goexit({})
	runtime/asm_amd64.s:1695 +0x1 fp=0xc000089fe8 sp=0xc000089fe0 pc=0xf72461
created by runtime.gcenable in goroutine 1
	runtime/mgc.go:203 +0x66

goroutine 4 gp=0xc000084c40 m=nil [GC scavenge wait]:
runtime.gopark(0x10000?, 0x1ffb9f0?, 0x0?, 0x0?, 0x0?)
	runtime/proc.go:402 +0xce fp=0xc000099f78 sp=0xc000099f58 pc=0xf4174e
runtime.goparkunlock(...)
	runtime/proc.go:408
runtime.(*scavengerState).park(0x2726fc0)
	runtime/mgcscavenge.go:425 +0x49 fp=0xc000099fa8 sp=0xc000099f78 pc=0xf29189
runtime.bgscavenge(0xc00003a070)
	runtime/mgcscavenge.go:658 +0x59 fp=0xc000099fc8 sp=0xc000099fa8 pc=0xf29739
runtime.gcenable.gowrap2()
	runtime/mgc.go:204 +0x25 fp=0xc000099fe0 sp=0xc000099fc8 pc=0xf20045
runtime.goexit({})
	runtime/asm_amd64.s:1695 +0x1 fp=0xc000099fe8 sp=0xc000099fe0 pc=0xf72461
created by runtime.gcenable in goroutine 1
	runtime/mgc.go:204 +0xa5

goroutine 18 gp=0xc000104380 m=nil [finalizer wait]:
runtime.gopark(0xc00008be48?, 0xf13445?, 0xa8?, 0x1?, 0xc000084000?)
	runtime/proc.go:402 +0xce fp=0xc00008be20 sp=0xc00008be00 pc=0xf4174e
runtime.runfinq()
	runtime/mfinal.go:194 +0x107 fp=0xc00008bfe0 sp=0xc00008be20 pc=0xf1f127
runtime.goexit({})
	runtime/asm_amd64.s:1695 +0x1 fp=0xc00008bfe8 sp=0xc00008bfe0 pc=0xf72461
created by runtime.createfing in goroutine 1
	runtime/mfinal.go:164 +0x3d

goroutine 5 gp=0xc000085340 m=nil [GC worker (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	runtime/proc.go:402 +0xce fp=0xc00009bf50 sp=0xc00009bf30 pc=0xf4174e
runtime.gcBgMarkWorker()
	runtime/mgc.go:1310 +0xe5 fp=0xc00009bfe0 sp=0xc00009bf50 pc=0xf221e5
runtime.goexit({})
	runtime/asm_amd64.s:1695 +0x1 fp=0xc00009bfe8 sp=0xc00009bfe0 pc=0xf72461
created by runtime.gcBgMarkStartWorkers in goroutine 1
	runtime/mgc.go:1234 +0x1c

goroutine 19 gp=0xc000104fc0 m=nil [GC worker (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	runtime/proc.go:402 +0xce fp=0xc000095f50 sp=0xc000095f30 pc=0xf4174e
runtime.gcBgMarkWorker()
	runtime/mgc.go:1310 +0xe5 fp=0xc000095fe0 sp=0xc000095f50 pc=0xf221e5
runtime.goexit({})
	runtime/asm_amd64.s:1695 +0x1 fp=0xc000095fe8 sp=0xc000095fe0 pc=0xf72461
created by runtime.gcBgMarkStartWorkers in goroutine 1
	runtime/mgc.go:1234 +0x1c

goroutine 6 gp=0xc000085500 m=nil [GC worker (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	runtime/proc.go:402 +0xce fp=0xc00041df50 sp=0xc00041df30 pc=0xf4174e
runtime.gcBgMarkWorker()
	runtime/mgc.go:1310 +0xe5 fp=0xc00041dfe0 sp=0xc00041df50 pc=0xf221e5
runtime.goexit({})
	runtime/asm_amd64.s:1695 +0x1 fp=0xc00041dfe8 sp=0xc00041dfe0 pc=0xf72461
created by runtime.gcBgMarkStartWorkers in goroutine 1
	runtime/mgc.go:1234 +0x1c

goroutine 20 gp=0xc000105180 m=nil [GC worker (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	runtime/proc.go:402 +0xce fp=0xc000097f50 sp=0xc000097f30 pc=0xf4174e
runtime.gcBgMarkWorker()
	runtime/mgc.go:1310 +0xe5 fp=0xc000097fe0 sp=0xc000097f50 pc=0xf221e5
runtime.goexit({})
	runtime/asm_amd64.s:1695 +0x1 fp=0xc000097fe8 sp=0xc000097fe0 pc=0xf72461
created by runtime.gcBgMarkStartWorkers in goroutine 1
	runtime/mgc.go:1234 +0x1c

goroutine 7 gp=0xc0000856c0 m=nil [GC worker (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	runtime/proc.go:402 +0xce fp=0xc00041ff50 sp=0xc00041ff30 pc=0xf4174e
runtime.gcBgMarkWorker()
	runtime/mgc.go:1310 +0xe5 fp=0xc00041ffe0 sp=0xc00041ff50 pc=0xf221e5
runtime.goexit({})
	runtime/asm_amd64.s:1695 +0x1 fp=0xc00041ffe8 sp=0xc00041ffe0 pc=0xf72461
created by runtime.gcBgMarkStartWorkers in goroutine 1
	runtime/mgc.go:1234 +0x1c

goroutine 21 gp=0xc000105340 m=nil [GC worker (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	runtime/proc.go:402 +0xce fp=0xc000419f50 sp=0xc000419f30 pc=0xf4174e
runtime.gcBgMarkWorker()
	runtime/mgc.go:1310 +0xe5 fp=0xc000419fe0 sp=0xc000419f50 pc=0xf221e5
runtime.goexit({})
	runtime/asm_amd64.s:1695 +0x1 fp=0xc000419fe8 sp=0xc000419fe0 pc=0xf72461
created by runtime.gcBgMarkStartWorkers in goroutine 1
	runtime/mgc.go:1234 +0x1c

goroutine 8 gp=0xc000085880 m=nil [GC worker (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	runtime/proc.go:402 +0xce fp=0xc000425f50 sp=0xc000425f30 pc=0xf4174e
runtime.gcBgMarkWorker()
	runtime/mgc.go:1310 +0xe5 fp=0xc000425fe0 sp=0xc000425f50 pc=0xf221e5
runtime.goexit({})
	runtime/asm_amd64.s:1695 +0x1 fp=0xc000425fe8 sp=0xc000425fe0 pc=0xf72461
created by runtime.gcBgMarkStartWorkers in goroutine 1
	runtime/mgc.go:1234 +0x1c

goroutine 22 gp=0xc000105500 m=nil [GC worker (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	runtime/proc.go:402 +0xce fp=0xc00041bf50 sp=0xc00041bf30 pc=0xf4174e
runtime.gcBgMarkWorker()
	runtime/mgc.go:1310 +0xe5 fp=0xc00041bfe0 sp=0xc00041bf50 pc=0xf221e5
runtime.goexit({})
	runtime/asm_amd64.s:1695 +0x1 fp=0xc00041bfe8 sp=0xc00041bfe0 pc=0xf72461
created by runtime.gcBgMarkStartWorkers in goroutine 1
	runtime/mgc.go:1234 +0x1c

goroutine 9 gp=0xc000085a40 m=nil [GC worker (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	runtime/proc.go:402 +0xce fp=0xc000427f50 sp=0xc000427f30 pc=0xf4174e
runtime.gcBgMarkWorker()
	runtime/mgc.go:1310 +0xe5 fp=0xc000427fe0 sp=0xc000427f50 pc=0xf221e5
runtime.goexit({})
	runtime/asm_amd64.s:1695 +0x1 fp=0xc000427fe8 sp=0xc000427fe0 pc=0xf72461
created by runtime.gcBgMarkStartWorkers in goroutine 1
	runtime/mgc.go:1234 +0x1c

goroutine 23 gp=0xc0001056c0 m=nil [GC worker (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	runtime/proc.go:402 +0xce fp=0xc000421f50 sp=0xc000421f30 pc=0xf4174e
runtime.gcBgMarkWorker()
	runtime/mgc.go:1310 +0xe5 fp=0xc000421fe0 sp=0xc000421f50 pc=0xf221e5
runtime.goexit({})
	runtime/asm_amd64.s:1695 +0x1 fp=0xc000421fe8 sp=0xc000421fe0 pc=0xf72461
created by runtime.gcBgMarkStartWorkers in goroutine 1
	runtime/mgc.go:1234 +0x1c

goroutine 10 gp=0xc000085c00 m=nil [GC worker (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	runtime/proc.go:402 +0xce fp=0xc00042df50 sp=0xc00042df30 pc=0xf4174e
runtime.gcBgMarkWorker()
	runtime/mgc.go:1310 +0xe5 fp=0xc00042dfe0 sp=0xc00042df50 pc=0xf221e5
runtime.goexit({})
	runtime/asm_amd64.s:1695 +0x1 fp=0xc00042dfe8 sp=0xc00042dfe0 pc=0xf72461
created by runtime.gcBgMarkStartWorkers in goroutine 1
	runtime/mgc.go:1234 +0x1c

goroutine 24 gp=0xc000105880 m=nil [GC worker (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	runtime/proc.go:402 +0xce fp=0xc000423f50 sp=0xc000423f30 pc=0xf4174e
runtime.gcBgMarkWorker()
	runtime/mgc.go:1310 +0xe5 fp=0xc000423fe0 sp=0xc000423f50 pc=0xf221e5
runtime.goexit({})
	runtime/asm_amd64.s:1695 +0x1 fp=0xc000423fe8 sp=0xc000423fe0 pc=0xf72461
created by runtime.gcBgMarkStartWorkers in goroutine 1
	runtime/mgc.go:1234 +0x1c

goroutine 11 gp=0xc000085dc0 m=nil [GC worker (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	runtime/proc.go:402 +0xce fp=0xc00042ff50 sp=0xc00042ff30 pc=0xf4174e
runtime.gcBgMarkWorker()
	runtime/mgc.go:1310 +0xe5 fp=0xc00042ffe0 sp=0xc00042ff50 pc=0xf221e5
runtime.goexit({})
	runtime/asm_amd64.s:1695 +0x1 fp=0xc00042ffe8 sp=0xc00042ffe0 pc=0xf72461
created by runtime.gcBgMarkStartWorkers in goroutine 1
	runtime/mgc.go:1234 +0x1c

goroutine 34 gp=0xc000482000 m=nil [GC worker (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	runtime/proc.go:402 +0xce fp=0xc000429f50 sp=0xc000429f30 pc=0xf4174e
runtime.gcBgMarkWorker()
	runtime/mgc.go:1310 +0xe5 fp=0xc000429fe0 sp=0xc000429f50 pc=0xf221e5
runtime.goexit({})
	runtime/asm_amd64.s:1695 +0x1 fp=0xc000429fe8 sp=0xc000429fe0 pc=0xf72461
created by runtime.gcBgMarkStartWorkers in goroutine 1
	runtime/mgc.go:1234 +0x1c

goroutine 25 gp=0xc000105a40 m=nil [GC worker (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	runtime/proc.go:402 +0xce fp=0xc0002f5f50 sp=0xc0002f5f30 pc=0xf4174e
runtime.gcBgMarkWorker()
	runtime/mgc.go:1310 +0xe5 fp=0xc0002f5fe0 sp=0xc0002f5f50 pc=0xf221e5
runtime.goexit({})
	runtime/asm_amd64.s:1695 +0x1 fp=0xc0002f5fe8 sp=0xc0002f5fe0 pc=0xf72461
created by runtime.gcBgMarkStartWorkers in goroutine 1
	runtime/mgc.go:1234 +0x1c

goroutine 35 gp=0xc0004821c0 m=nil [GC worker (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	runtime/proc.go:402 +0xce fp=0xc00042bf50 sp=0xc00042bf30 pc=0xf4174e
runtime.gcBgMarkWorker()
	runtime/mgc.go:1310 +0xe5 fp=0xc00042bfe0 sp=0xc00042bf50 pc=0xf221e5
runtime.goexit({})
	runtime/asm_amd64.s:1695 +0x1 fp=0xc00042bfe8 sp=0xc00042bfe0 pc=0xf72461
created by runtime.gcBgMarkStartWorkers in goroutine 1
	runtime/mgc.go:1234 +0x1c

goroutine 26 gp=0xc000105c00 m=nil [GC worker (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	runtime/proc.go:402 +0xce fp=0xc0002f7f50 sp=0xc0002f7f30 pc=0xf4174e
runtime.gcBgMarkWorker()
	runtime/mgc.go:1310 +0xe5 fp=0xc0002f7fe0 sp=0xc0002f7f50 pc=0xf221e5
runtime.goexit({})
	runtime/asm_amd64.s:1695 +0x1 fp=0xc0002f7fe8 sp=0xc0002f7fe0 pc=0xf72461
created by runtime.gcBgMarkStartWorkers in goroutine 1
	runtime/mgc.go:1234 +0x1c

goroutine 36 gp=0xc000482380 m=nil [GC worker (idle)]:
runtime.gopark(0xa5c45b8f8c?, 0x0?, 0x0?, 0x0?, 0x0?)
	runtime/proc.go:402 +0xce fp=0xc0002f1f50 sp=0xc0002f1f30 pc=0xf4174e
runtime.gcBgMarkWorker()
	runtime/mgc.go:1310 +0xe5 fp=0xc0002f1fe0 sp=0xc0002f1f50 pc=0xf221e5
runtime.goexit({})
	runtime/asm_amd64.s:1695 +0x1 fp=0xc0002f1fe8 sp=0xc0002f1fe0 pc=0xf72461
created by runtime.gcBgMarkStartWorkers in goroutine 1
	runtime/mgc.go:1234 +0x1c

goroutine 27 gp=0xc000105dc0 m=nil [GC worker (idle)]:
runtime.gopark(0xa5c45b8f8c?, 0x3?, 0x0?, 0x0?, 0x0?)
	runtime/proc.go:402 +0xce fp=0xc0002fdf50 sp=0xc0002fdf30 pc=0xf4174e
runtime.gcBgMarkWorker()
	runtime/mgc.go:1310 +0xe5 fp=0xc0002fdfe0 sp=0xc0002fdf50 pc=0xf221e5
runtime.goexit({})
	runtime/asm_amd64.s:1695 +0x1 fp=0xc0002fdfe8 sp=0xc0002fdfe0 pc=0xf72461
created by runtime.gcBgMarkStartWorkers in goroutine 1
	runtime/mgc.go:1234 +0x1c

goroutine 37 gp=0xc000482540 m=nil [GC worker (idle)]:
runtime.gopark(0x27b4a60?, 0x1?, 0x4c?, 0xcc?, 0x0?)
	runtime/proc.go:402 +0xce fp=0xc0002f3f50 sp=0xc0002f3f30 pc=0xf4174e
runtime.gcBgMarkWorker()
	runtime/mgc.go:1310 +0xe5 fp=0xc0002f3fe0 sp=0xc0002f3f50 pc=0xf221e5
runtime.goexit({})
	runtime/asm_amd64.s:1695 +0x1 fp=0xc0002f3fe8 sp=0xc0002f3fe0 pc=0xf72461
created by runtime.gcBgMarkStartWorkers in goroutine 1
	runtime/mgc.go:1234 +0x1c

goroutine 28 gp=0xc000500000 m=nil [GC worker (idle)]:
runtime.gopark(0x27b4a60?, 0x1?, 0x9c?, 0x61?, 0x0?)
	runtime/proc.go:402 +0xce fp=0xc0002fff50 sp=0xc0002fff30 pc=0xf4174e
runtime.gcBgMarkWorker()
	runtime/mgc.go:1310 +0xe5 fp=0xc0002fffe0 sp=0xc0002fff50 pc=0xf221e5
runtime.goexit({})
	runtime/asm_amd64.s:1695 +0x1 fp=0xc0002fffe8 sp=0xc0002fffe0 pc=0xf72461
created by runtime.gcBgMarkStartWorkers in goroutine 1
	runtime/mgc.go:1234 +0x1c

goroutine 38 gp=0xc000482700 m=nil [GC worker (idle)]:
runtime.gopark(0x27b4a60?, 0x1?, 0x7c?, 0xd9?, 0x0?)
	runtime/proc.go:402 +0xce fp=0xc0002f9f50 sp=0xc0002f9f30 pc=0xf4174e
runtime.gcBgMarkWorker()
	runtime/mgc.go:1310 +0xe5 fp=0xc0002f9fe0 sp=0xc0002f9f50 pc=0xf221e5
runtime.goexit({})
	runtime/asm_amd64.s:1695 +0x1 fp=0xc0002f9fe8 sp=0xc0002f9fe0 pc=0xf72461
created by runtime.gcBgMarkStartWorkers in goroutine 1
	runtime/mgc.go:1234 +0x1c

goroutine 29 gp=0xc0005001c0 m=nil [GC worker (idle)]:
runtime.gopark(0x27b4a60?, 0x1?, 0xd4?, 0xaf?, 0x0?)
	runtime/proc.go:402 +0xce fp=0xc000507f50 sp=0xc000507f30 pc=0xf4174e
runtime.gcBgMarkWorker()
	runtime/mgc.go:1310 +0xe5 fp=0xc000507fe0 sp=0xc000507f50 pc=0xf221e5
runtime.goexit({})
	runtime/asm_amd64.s:1695 +0x1 fp=0xc000507fe8 sp=0xc000507fe0 pc=0xf72461
created by runtime.gcBgMarkStartWorkers in goroutine 1
	runtime/mgc.go:1234 +0x1c

goroutine 39 gp=0xc0004828c0 m=nil [GC worker (idle)]:
runtime.gopark(0xa5c45b8f8c?, 0x1?, 0x0?, 0x0?, 0x0?)
	runtime/proc.go:402 +0xce fp=0xc0002fbf50 sp=0xc0002fbf30 pc=0xf4174e
runtime.gcBgMarkWorker()
	runtime/mgc.go:1310 +0xe5 fp=0xc0002fbfe0 sp=0xc0002fbf50 pc=0xf221e5
runtime.goexit({})
	runtime/asm_amd64.s:1695 +0x1 fp=0xc0002fbfe8 sp=0xc0002fbfe0 pc=0xf72461
created by runtime.gcBgMarkStartWorkers in goroutine 1
	runtime/mgc.go:1234 +0x1c

goroutine 12 gp=0xc0005841c0 m=5 mp=0xc000100008 [syscall]:
runtime.notetsleepg(0x27b36a0, 0xffffffffffffffff)
	runtime/lock_sema.go:296 +0x31 fp=0xc000505fa0 sp=0xc000505f68 pc=0xf11a11
os/signal.signal_recv()
	runtime/sigqueue.go:152 +0x29 fp=0xc000505fc0 sp=0xc000505fa0 pc=0xf6e169
os/signal.loop()
	os/signal/signal_unix.go:23 +0x13 fp=0xc000505fe0 sp=0xc000505fc0 pc=0x12335d3
runtime.goexit({})
	runtime/asm_amd64.s:1695 +0x1 fp=0xc000505fe8 sp=0xc000505fe0 pc=0xf72461
created by os/signal.Notify.func1.1 in goroutine 1
	os/signal/signal.go:151 +0x1f

goroutine 13 gp=0xc000584380 m=nil [chan receive]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	runtime/proc.go:402 +0xce fp=0xc000509f08 sp=0xc000509ee8 pc=0xf4174e
runtime.chanrecv(0xc0004ce4e0, 0x0, 0x1)
	runtime/chan.go:583 +0x3cd fp=0xc000509f80 sp=0xc000509f08 pc=0xf0b98d
runtime.chanrecv1(0x0?, 0x0?)
	runtime/chan.go:442 +0x12 fp=0xc000509fa8 sp=0xc000509f80 pc=0xf0b592
github.com/ollama/ollama/server.Serve.func2()
	github.com/ollama/ollama/server/routes.go:1043 +0x34 fp=0xc000509fe0 sp=0xc000509fa8 pc=0x19ef2f4
runtime.goexit({})
	runtime/asm_amd64.s:1695 +0x1 fp=0xc000509fe8 sp=0xc000509fe0 pc=0xf72461
created by github.com/ollama/ollama/server.Serve in goroutine 1
	github.com/ollama/ollama/server/routes.go:1042 +0x6f7

goroutine 14 gp=0xc000584540 m=nil [select]:
runtime.gopark(0xc00047df58?, 0x3?, 0x60?, 0x0?, 0xc00047de32?)
	runtime/proc.go:402 +0xce fp=0xc00047dcb8 sp=0xc00047dc98 pc=0xf4174e
runtime.selectgo(0xc00047df58, 0xc00047de2c, 0x0?, 0x0, 0x0?, 0x1)
	runtime/select.go:327 +0x725 fp=0xc00047ddd8 sp=0xc00047dcb8 pc=0xf51ba5
github.com/ollama/ollama/server.(*Scheduler).processPending(0xc000174af0, {0x200c0c0, 0xc000174aa0})
	github.com/ollama/ollama/server/sched.go:97 +0xcf fp=0xc00047dfb8 sp=0xc00047ddd8 pc=0x19f27af
github.com/ollama/ollama/server.(*Scheduler).Run.func1()
	github.com/ollama/ollama/server/sched.go:87 +0x1f fp=0xc00047dfe0 sp=0xc00047dfb8 pc=0x19f26bf
runtime.goexit({})
	runtime/asm_amd64.s:1695 +0x1 fp=0xc00047dfe8 sp=0xc00047dfe0 pc=0xf72461
created by github.com/ollama/ollama/server.(*Scheduler).Run in goroutine 1
	github.com/ollama/ollama/server/sched.go:86 +0xb4

goroutine 15 gp=0xc000584700 m=nil [select]:
runtime.gopark(0xc000503f50?, 0x3?, 0x0?, 0x0?, 0xc000503d5a?)
	runtime/proc.go:402 +0xce fp=0xc000503be8 sp=0xc000503bc8 pc=0xf4174e
runtime.selectgo(0xc000503f50, 0xc000503d54, 0x0?, 0x0, 0x0?, 0x1)
	runtime/select.go:327 +0x725 fp=0xc000503d08 sp=0xc000503be8 pc=0xf51ba5
github.com/ollama/ollama/server.(*Scheduler).processCompleted(0xc000174af0, {0x200c0c0, 0xc000174aa0})
	github.com/ollama/ollama/server/sched.go:209 +0xec fp=0xc000503fb8 sp=0xc000503d08 pc=0x19f332c
github.com/ollama/ollama/server.(*Scheduler).Run.func2()
	github.com/ollama/ollama/server/sched.go:91 +0x1f fp=0xc000503fe0 sp=0xc000503fb8 pc=0x19f267f
runtime.goexit({})
	runtime/asm_amd64.s:1695 +0x1 fp=0xc000503fe8 sp=0xc000503fe0 pc=0xf72461
created by github.com/ollama/ollama/server.(*Scheduler).Run in goroutine 1
	github.com/ollama/ollama/server/sched.go:90 +0x110
rax     0x228f4cf83f0
rbx     0x228ed7065e0
rcx     0xd3d
rdx     0x6
rdi     0x228ed7117f0
rsi     0x228f4cf83f0
rbp     0xd3c
rsp     0x45e97fe108
r8      0x2
r9      0x40
r10     0x80
r11     0x22000000007f4100
r12     0x1
r13     0x0
r14     0x228f4b98340
r15     0x228ed7065e0
rip     0x228ed7065e0
rflags  0x10202
cs      0x33
fs      0x53
gs      0x2b

### OS

Windows

### GPU

AMD

### CPU

Intel

### Ollama version

0.1.34

**Comment by dhiltgen** [comment]
Others have reported this crash in the AMD library and the root cause was an out-of-date AMD driver.  Please upgrade to the latest AMD driver and this should be resolved.
