### ISSUE TITLE
403 using zrok 

### ISSUE THREAD

**Issue by quantumalchemy** [ollama/ollama#4262]
Re: https://github.com/ollama/ollama/issues/3269
was fixed for ngrok But
ngrok is paid and has limits  

 anyway to get it to work with zrok? 
--host-header doesn't work with zrok

zrok is opensource

_Originally posted by @quantumalchemy in https://github.com/ollama/ollama/issues/3269#issuecomment-2101017786_

**Comment by mchiang0610** [comment]
hey @quantumalchemy, this should work with Ollama. 

What you would need to do is forward to `localhost:11434` for Ollama.

**Comment by jmorganca** [comment]
Closing for https://github.com/ollama/ollama/issues/3269
