### ISSUE TITLE
API useing

### ISSUE THREAD

**Issue by w1757876747** [ollama/ollama#4273]
### What is the issue?

I have a problem. When I call api/pull of the project, the background displays the following error, and no streaming response such as status is returned, because I want to get the real-time download progress. May I ask why I can download normally if I use the run model command in the service`time=2024-05-09T10:03:13.104+08:00 level=INFO source=download.go:251 msg="00e1317cbf74 part 36 stalled; retrying. If this persists, press ctrl-c to exit, then 'ollama pull' to find a faster connection."
time=2024-05-09T10:03:25.107+08:00 level=INFO source=download.go:251 msg="00e1317cbf74 part 14 stalled; retrying. If this persists, press ctrl-c to exit, then 'ollama pull' to find a faster connection."
time=2024-05-09T10:03:35.106+08:00 level=INFO source=download.go:251 msg="00e1317cbf74 part 36 stalled; retrying. If this persists, press ctrl-c to exit, then 'ollama pull' to find a faster connection."
[GIN] 2024/05/09 - 10:03:46 | 200 |    35.609442s |       127.0.0.1 | POST     "/api/pull"`

### OS

Windows

### GPU

Nvidia

### CPU

Intel

### Ollama version

0.1.34

**Comment by w1757876747** [comment]
I have just tried again and can download but can not return real-time response, but a one-time stream response after downloading

**Comment by jmorganca** [comment]
Hi there, to pull in one request, use `stream`: false in `/api/pull` - let me know if that works!
