### ISSUE TITLE
Degraded accuracy when using the nomic-embed-text (v1.5) model with Ollama versions 0.1.32 and 0.1.33

### ISSUE THREAD

**Issue by Ganesh1030** [ollama/ollama#4275]
### What is the issue?

We have an application where we are training the CSV file and using the following things for it:.
- 'nomic-embed-text(v1.5) model
-  chromadb
-  ollama(0.1.31)
 
At runtime, we are using'similarity_search' and getting good accuracy with ollama version 0.1.31, but when we upgrade ollama version to 0.1.32 or 0.1.33, accuracy is downgraded.
 
Can anyone please confirm it's an know issue or bug or we are missing something?

### OS

macOS

### Ollama version

0.1.32 and 0.1.33

**Comment by jmorganca** [comment]
Hi there, this should be fixed now. But let me know if you're still seeing the issue.

**Comment by Ganesh1030** [comment]
Thanks. tested with ollama version 0.1.45 and it's fixed now.

I think that it's fixed in 0.1.43.  right?
https://github.com/ollama/ollama/releases/tag/v0.1.43
     What's Changed
         **Fixed issue where embedding vectors resulting from /api/embeddings would not be accurate**
