### ISSUE TITLE
Get Entropy 

### ISSUE THREAD

**Issue by antonbugaets** [ollama/ollama#4281]
Hello !
Using latest version of Ollama + self-hosted models. 
Getting responses from API,
i didn't find something reg. Entropy in documentation, how i can get it in the model response ? is it any special parameter for this ? 

Thanks.

**Comment by pdevine** [comment]
@antonbugaets you can use the `temperature` parameter for getting more "randomness" in your responses. For getting deterministic results you can set the temperature to `0`, and for more "creative" results you can set the value higher.

In the REPL you can do this with `/set parameter temperature N` with N being the value you want to set it to.

LMK if that answers your question. I wasn't 100% sure if this was what you were trying to ask.

**Comment by antonbugaets** [comment]
@pdevine Hello, yes, i'm aware about temperature, top k/p parameters which i can configure using Ollama as serv. function for models inferencing, 

But initially i meant about how do i can understand, that model is not sure about particular answer by my promts? While model inferences with Ollama.

I need to understand this to perform post-processing of 'low quality' answers. 

Is it any possible ways to understand this ? Maybe by some optional parametr ? or get probas of tokens and calculate entropy. 

Thanks!
