### ISSUE TITLE
Ollama v0.1.34 Timeout issue on Codellama34B

### ISSUE THREAD

**Issue by humza-sami** [ollama/ollama#4283]
### What is the issue?

I am trying to run Codellama34B model on Ollama 0.1.34 version and its keep giving me timeout error. Although I was able to run codellama70B on this version. Then I rollback ollama to v0.1.32 and it worked for me. It seems latest version is not supporting codellama34B. 
![image](https://github.com/ollama/ollama/assets/63999516/5bbd418d-9384-4805-a1de-f467db84ad4a)

### OS

Linux

### GPU

Nvidia

### CPU

Intel

### Ollama version

0.1.34

**Comment by dhiltgen** [comment]
You don't quite have the CLI syntax correctly.  Run requires the name of the model you want to run.

Try:
```
% ollama run codellama:34b "what is your favorite condiment?"
```
