### ISSUE TITLE
Ollama crate cannot generate modelfile with non-English name

### ISSUE THREAD

**Issue by BarcodeQH** [ollama/ollama#4285]
### What is the issue?

Ollama cannot generate a modelfile which name is non-english (eg: Chinese) after upgrade to v0.1.34

### OS

Linux

### GPU

Nvidia

### CPU

AMD

### Ollama version

v0.1.34

**Comment by BarcodeQH** [comment]
I'm pretty sure it works in versions before v0.1.34.

**Comment by taozhiyuai** [comment]
折腾这玩意干嘛?默认的modelfile不挺好的?

**Comment by jmorganca** [comment]
Hi @BarcodeQH - you should be able to create a model from a Modelfile with unicode characters. However, model names are more restricted. Hope this helps!
