### ISSUE TITLE
can't copy command correctly on ollama.com

### ISSUE THREAD

**Issue by taozhiyuai** [ollama/ollama#4286]
### What is the issue?

as shown in the picture, not a full command is copied.

1. I click webpage link and enter this page with default tag
2. press copy button and paste to terminal
3. only part of command is copied

but, if I choose other tag and copy command , it ok. then I choose the default tag which is shown on the webpage is loaded and press the copy button again, full command is copied. 

so strange.

![WX20240509-220939@2x](https://github.com/ollama/ollama/assets/146583103/9dcd2616-8e51-4e01-aefe-4da5c317e1ed)

### OS

macOS

### GPU

Apple

### CPU

Apple

### Ollama version

up to date

**Comment by hoyyeva** [comment]
Hello @taozhiyuai , thank you very much for submitting the issue and bringing it to our attention. We apologize for the confusion caused. The bug has been fixed and deployed. I will close the issue for now, but please feel free to reopen it if the problem persists.

**Comment by taozhiyuai** [comment]
> Hello @taozhiyuai , thank you very much for submitting the issue and bringing it to our attention. We apologize for the confusion caused. The bug has been fixed and deployed. I will close the issue for now, but please feel free to reopen it if the problem persists.

thanks for your job.
