### ISSUE TITLE
ollama domains when behind Web (Squid) Proxy

### ISSUE THREAD

**Issue by StL-Jim** [ollama/ollama#4307]
I couldn't find in the FAQ or other docs what domain(s) need to be whitelisted, besides .olllama.com, to allow LLMs to be pulled in via ollama if behind a Web (Squid) proxy.  If someone could provide the information I be glad to update the FAQ/Troubleshooting docs with the information and submit a Pull request.

**Comment by thinkverse** [comment]
The Ollama registry is: `registry.ollama.ai`.

https://github.com/ollama/ollama/blob/c02db93243353855b983db2a1562a02b57e66db1/types/model/name.go#L38-L42

**Comment by mxyng** [comment]
Additionally `dd20bb891979d25aebc8bec07b2b3bbc.r2.cloudflarestorage.com` should be allowed as well. In summary

- `.ollama.com`
- `registry.ollama.ai`
- `dd20bb891979d25aebc8bec07b2b3bbc.r2.cloudflarestorage.com`
