### ISSUE TITLE
Run Timeout When Applying Lora Adapter and Lora Base

### ISSUE THREAD

**Issue by cheeseng** [ollama/ollama#4313]
When I tried to run my imported model with an lora adapter, it time out when the server is apply the adapter, is there a way I can use a longer time out period?

Also, when using adapter I notice the following warning on the server: 

```
warning: using a lora adapter with a quantized model may result in poor quality, use a f16 or f32 base model with --lora-base
```

Is there a way I can speficy in Modelfile for the --lora-base?

Thanks.

**Comment by pdevine** [comment]
The lora base is just whatever is in the `FROM` line of the Modelfile. I've been trying to revamp LoRAs entirely w/ #5524 and have been tracking this in #4618. Let's close this in favor of that issue.
