### ISSUE TITLE
the ai model  downloading not working 

### ISSUE THREAD

**Issue by Tochage143** [ollama/ollama#4314]
### What is the issue?

ollama run mistral:text
pulling manifest
Error: Head "https://dd20bb891979d25aebc8bec07b2b3bbc.r2.cloudflarestorage.com/ollama/docker/registry/v2/blobs/sha256/5b/5b5c2a563a287aa9bf9be7499fe7e0630add02089be3f50ee494087f67683fbb/data?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=66040c77ac1b787c3af820529859349a%!F(MISSING)20240510%!F(MISSING)auto%!F(MISSING)s3%!F(MISSING)aws4_request&X-Amz-Date=20240510T160627Z&X-Amz-Expires=1200&X-Amz-SignedHeaders=host&X-Amz-Signature=21ab36ad0c30857906a5f710d6d26dd63c905bd84ba24e580f43dff8b8b96133": dial tcp: lookup dd20bb891979d25aebc8bec07b2b3bbc.r2.cloudflarestorage.com: no such host

### OS

Windows

### GPU

Nvidia

### CPU

Intel

### Ollama version

v0.1.34

**Comment by pdevine** [comment]
are you behind a corporate proxy/firewall?

Also, are you using wsl2 or is it just plain Windows?

**Comment by Tochage143** [comment]
> are you behind a corporate proxy/firewall?
> 
> Also, are you using wsl2 or is it just plain Windows?

I did not use any proxy or firewall. I my personal laptop the first I have downloaded many modes. This time model download process failed more than 5 time. After I get this error message and now I can't able any model

**Comment by pdevine** [comment]
I don't _think_ it's a problem with Ollama. I think it's almost certainly a Windows issue w/ DNS, but I'm not sure what's causing it.

**Comment by pdevine** [comment]
@Tochage143 Did you figure out what was wrong?

**Comment by Tochage143** [comment]
For the past three days, I've been trying to run ollama run mistral, but I keep encountering errors. When I ran the command as an administrator, I was able to download the AI model successfully. After that, the errors stopped occurring. Previously, I resolved the issue by uninstalling Ollama and clearing the cache.

**Comment by vishnuvardhan2005** [comment]
Changing the DNS IPs and flushdns resolved the issue for me
