### ISSUE TITLE
Can this set the number of cores on the cpu?

### ISSUE THREAD

**Issue by ghost-him** [ollama/ollama#4318]
My server has 24 cores, but each time it can only use a portion of them. If I could use all of these cores, it would run much more efficiently!

**Comment by lengrongfu** [comment]
@ghost-him Can you describe whether only part of the cpu cores are used during the pull model or the run model?

**Comment by ghost-him** [comment]
Now that the computer isn't with me, it's a random part of the cpu core as far as I can remember. But the same number at full load.

**Comment by lengrongfu** [comment]
I have reason to believe it is the maximum value. https://pkg.go.dev/runtime#GOMAXPROCS

**Comment by ghost-him** [comment]
Thank you very much, I'll try it out in a while
