### ISSUE TITLE
Difference in performance between liuhaotian/llava-v1.6-34b and Ollama's llava:34b-v1.6

### ISSUE THREAD

**Issue by EricWiener** [ollama/ollama#4332]
### What is the issue?

When using the demo [here](https://llava.hliu.cc/) I get much better results using their `llava:34b-v1.6` than I do via `ollama run llava:34b-v1.6` when prompting with the same prompt followed by the image. Example of how I'm prompting:
```
ollama run llava:34b-v1.6 --verbose
>>> Is there a dog in this picture and if so what is it doing? /data/dog.png
```

Is there any reason for this and can I somehow match the performance of the demo?

### OS

Linux

### GPU

Nvidia

### Ollama version

0.1.34

**Comment by lizaibeim** [comment]
It is not a bug, as the demo uses fp16 precision while the  llava:34b-v1.6  is in 4 bit quantization. Thus, the performance is not comparable.

**Comment by EricWiener** [comment]
Thanks for the response @lizaibeim ! Do you know if the demo is fp16 or bf16? I believe the demo might be bf16 but only see fp16 as an option through ollama.

**Comment by lizaibeim** [comment]
Sorry i couldn't confirm if it is bf16 or fp16. But based on the recommended VRAM from [llava](https://github.com/haotian-liu/LLaVA) - 80G, versus 69G in [Ollama](https://ollama.com/library/llava:34b-v1.6-fp16), it might be bf16.

**Comment by EricWiener** [comment]
Thanks @lizaibeim !
