### ISSUE TITLE
Error: llama runner process has terminated: exit status 0xc0000005

### ISSUE THREAD

**Issue by EthanScully** [ollama/ollama#4334]
### What is the issue?

at the start of loading a model on v0.1.35, it errors out `Error: llama runner process has terminated: exit status 0xc0000005`
v0.1.34 works perfectly fine
log:
```
time=2024-05-10T22:52:42.838-04:00 level=ERROR source=sched.go:339 msg="error loading llama server" error="llama runner process has terminated: exit status 0xc0000005 "
[GIN] 2024/05/10 - 22:52:42 | 500 |    2.7650401s |       127.0.0.1 | POST     "/api/chat"
time=2024-05-10T22:52:48.161-04:00 level=WARN source=sched.go:507 msg="gpu VRAM usage didn't recover within timeout" seconds=5.3231542
time=2024-05-10T22:52:48.488-04:00 level=WARN source=sched.go:507 msg="gpu VRAM usage didn't recover within timeout" seconds=5.6501493
time=2024-05-10T22:52:48.832-04:00 level=WARN source=sched.go:507 msg="gpu VRAM usage didn't recover within timeout" seconds=5.9940694
```
using the AMD Radeon RX 6800
windows 11 and latest drivers

### OS

Windows

### GPU

AMD

### CPU

AMD

### Ollama version

v0.1.35

**Comment by jmorganca** [comment]
This should be fixed in https://github.com/ollama/ollama/releases/tag/v0.1.36, sorry about this!

**Comment by seraasch** [comment]
I just got this error with v0.1.36
AMD RX 7800 XT

**Comment by ReOT20** [comment]
> This should be fixed in https://github.com/ollama/ollama/releases/tag/v0.1.36, sorry about this!

Same problem on 0.1.37 with 5700 XT masked as gfx1030

**Comment by V01D-NULL** [comment]
I'm seeing this on 0.1.38

**Comment by Codesbyusman** [comment]
facing same issue when trying to run  codegemma 

`ollama run codegemma`

> Error: llama runner process has terminated: exit status 0xc0000005

ollama version = 0.1.41

**Comment by antibyte** [comment]
same here

**Comment by Codesbyusman** [comment]
@antibyte update ollama to 0.1.45, it's working there
