### ISSUE TITLE
AMD Gpu RX 6600 on WIndows 10

### ISSUE THREAD

**Issue by usmandilmeer** [ollama/ollama#4335]
### What is the issue?

I'm having trouble using my AMD GPU RX 6600 on Windows 10 with Ollama. Could someone please assist me and provide any workarounds to make this AMD GPU RX 6600 function? 
Please provide step-by-step instructions specifically for Windows 10. Thank you.

### OS

Windows

### GPU

AMD

### CPU

Intel

### Ollama version

0.1.35

**Comment by jmorganca** [comment]
Sorry, working on fixing this. Will merge with https://github.com/ollama/ollama/issues/4334

**Comment by usmandilmeer** [comment]
> Sorry, working on fixing this. Will merge with #4334
Oh
Are you working fixing amd rx 6600 on windows 10? Thanks
