### ISSUE TITLE
improve search engine of ollama.com

### ISSUE THREAD

**Issue by taozhiyuai** [ollama/ollama#4336]
### What is the issue?

<img width="1217" alt="截屏2024-05-11 10 52 49" src="https://github.com/ollama/ollama/assets/146583103/422e0577-4721-4fa8-b063-ad248fe933a2">

please improve search engine . show the relevant result.

### OS

macOS

### GPU

Apple

### CPU

Apple

### Ollama version

1.35

**Comment by jmorganca** [comment]
This should be fixed now. Thanks for the issue!
