### ISSUE TITLE
how can I make ollama always run models? 

### ISSUE THREAD

**Issue by zhaoyuchen1128** [ollama/ollama#4340]
### What is the issue?

If the model does not run for a while, the model will stop and reloading will consume a lot of time.So the user experience is not good

**Comment by taozhiyuai** [comment]
已经处理过这个问题,搜索一下

**Comment by dhiltgen** [comment]
You can control how long the model stays loaded with keep_alive - see https://github.com/ollama/ollama/blob/main/docs/faq.md#how-do-i-keep-a-model-loaded-in-memory-or-make-it-unload-immediately

**Comment by hello1337lol** [comment]
sorry, but the faq is offline
