### ISSUE TITLE
how to import Meta-Llama-3-120B-Instruct.imatrix

### ISSUE THREAD

**Issue by taozhiyuai** [ollama/ollama#4341]
![WX20240511-115426@2x](https://github.com/ollama/ollama/assets/146583103/93328322-5cb6-48f8-a538-a99d03ce047e)

I want to import this model. may I know how to import Meta-Llama-3-120B-Instruct.imatrix?

**Comment by taozhiyuai** [comment]
is it the right model file? or I should merge them into one GGUF?

FROM ./Meta-Llama-3-120B-Instruct-Q5_K_M-00001-of-00003.gguf
FROM ./Meta-Llama-3-120B-Instruct-Q5_K_M-00002-of-00003.gguf
FROM ./Meta-Llama-3-120B-Instruct-Q5_K_M-00003-of-00003.gguf
FROM ./Meta-Llama-3-120B-Instruct.imatrix



TEMPLATE """{{ if .System }}<|start_header_id|>system<|end_header_id|>

{{ .System }}<|eot_id|>{{ end }}{{ if .Prompt }}<|start_header_id|>user<|end_header_id|>

{{ .Prompt }}<|eot_id|>{{ end }}<|start_header_id|>assistant<|end_header_id|>

{{ .Response }}<|eot_id|>"""
PARAMETER num_keep 24
PARAMETER stop "<|start_header_id|>"
PARAMETER stop "<|end_header_id|>"
PARAMETER stop "<|eot_id|>"

**Comment by DuckyBlender** [comment]
You can merge them into one GGUF using llama.cpp, they have more info in the quantisation section in the README

**Comment by Milor123** [comment]
@DuckyBlender Need use it for use iMatrix? or just should ignore iMatrix and use q6 gguf version?

**Comment by DuckyBlender** [comment]
Sorry, not familiar with I quants
