### ISSUE TITLE
windows10:V0.1.35 -The API interface of openai faill! but V0.1.34 is ok!

### ISSUE THREAD

**Issue by 808cn** [ollama/ollama#4343]
### What is the issue?

V0.1.35: windows10,openai api fail!  
-----------------------------------------------------
Version 0.1.35: The API interface of openai cannot be used.
It is OK to return to 0.1.34.
Now using version 0.1.34, the openai interface can be used normally.

------------------------------------------------
### OS

Windows

### GPU

Nvidia

### CPU

Intel

### Ollama version

0.1.35

**Comment by 808cn** [comment]
ok   https://github.com/ollama/ollama/releases/download/v0.1.34/OllamaSetup.exe
fail  https://github.com/ollama/ollama/releases/download/v0.1.35/OllamaSetup.exe

**Comment by jmorganca** [comment]
Hi @808cn would it be possible to share the error you're seeing?

**Comment by ziggornif** [comment]
@808cn maybe it’s related to the #4357 about incorrect `finish_reason` value in openai response.

If so you can test with the new release v0.1.37 to see if it fixes the problem.

**Comment by 808cn** [comment]
Thank you!
new release v0.1.37  windows10,openai is good!

**Comment by ziggornif** [comment]
@jmorganca I think you can close the issue 🙂
