### ISSUE TITLE
failed to run llama3 on macos

### ISSUE THREAD

**Issue by Mercccccc** [ollama/ollama#4344]
### What is the issue?

`ollama run llama3
pulling manifest
pulling 00e1317cbf74... 100% ▕██████████████████████████████████████████████████████████▏ 4.7 GB
pulling 4fa551d4f938... 100% ▕██████████████████████████████████████████████████████████▏  12 KB
pulling 8ab4849b038c... 100% ▕██████████████████████████████████████████████████████████▏  254 B
pulling 577073ffcc6c... 100% ▕██████████████████████████████████████████████████████████▏  110 B
pulling ad1518640c43... 100% ▕██████████████████████████████████████████████████████████▏  483 B
verifying sha256 digest
writing manifest
removing any unused layers
success
Error: error starting the external llama server: fork/exec /var/folders/c3/vcxjn8bn59jd7th67f2fr9840000gn/T/ollama1329764937/runners/metal/ollama_llama_server: no such file or directory`

### OS

macOS

### GPU

Apple

### CPU

Apple

### Ollama version

0.1.32

**Comment by jmorganca** [comment]
Hi @Mercccccc try upgrading to 0.1.35+ it should fix this (sorry about that!). Note if you restart Ollama that will fix it too, but this is an issue fixed in recent versions :)

**Comment by Mercccccc** [comment]
Thank you very much! I will try it right now
