### ISSUE TITLE
noKeyError: rms_norm_eps

### ISSUE THREAD

**Issue by czs397001** [ollama/ollama#4348]
### What is the issue?

(base)
rerted
qwen-
s-1.bin --pad-vocab
L file /data/tempriles/Qwen-1 8B-chat-diseasecls2/model.safetensors
oading model
raceback (most recent call last):
File "/data/github/ollama/llm/llama.cpp/convert.py", line 1555, in <module>
main()
rile "/data/qithub/ollama/llm/llama.cpp/convert.py", line 1498, in main
 params load model pius)
params
File "/data/github/ollan
/llm/llama.cpp/convert.py",
line 328.in load
: parans, loadnprransformerason (nodel plns model, hf config path)
params =
File "/data/github/ol.
line 266,in loadHrTransformerJson
llama .cpp/convert.py"
f norm ep.
eps"]
OnfiOTIMS LOLL
eyError:
! 1m S
0 O rr

**Comment by pdevine** [comment]
llama.cpp's `convert.py` script was deprecated by them. You should look at the `convert_hf_to_gguf.py`.
