### ISSUE TITLE
Configurable model loading timeout 

### ISSUE THREAD

**Issue by ProjectMoon** [ollama/ollama#4350]
The model loading timeout, the time to wait for the llama runner, is hard coded. It would be nice to be able to configure this to increase or decrease it (for me, mostly increase). This would allow experimenting with big models that take forever to load, but might run fine once loaded.

**Comment by lengrongfu** [comment]
I can try to add this feature.

**Comment by lengrongfu** [comment]
@ProjectMoon Your problem is that when ollama runs a model that does not exist locally, does pulling it from the registry time out?

**Comment by ProjectMoon** [comment]
No, it's the loading of the model from disk.  There's a hard coded timeout of 10 minutes. I forget the exact file where this is, but the comment above the line says something like "be generous, as long models can take a long time to load."

**Comment by ProjectMoon** [comment]
An example of why this would be useful (to me): I can load Mixtral 8x7b using the Q2_K quant (smallest available file). It loads in 565 seconds, just under the 10 minute timeout limit. But once it's loaded, it generates at 16 tokens/second. It would be lovely if I could try the higher quants and see  what happens.

**Comment by ProjectMoon** [comment]
I am noticing some flakiness on slow model loads. I have one model that gets to 80% and then gives up. Should I reopen this issue or make a new issue to change the stall time?

**Comment by dhiltgen** [comment]
@ProjectMoon can you try disabling mmap to see if that significantly changes the load times for your setup?
```
curl http://localhost:11434/api/generate -d '{
  "model": "llama3:70b",
  "prompt": "Why is the sky blue?",
  "stream": false, "options": {"use_mmap": false}
}'
```

**Comment by ProjectMoon** [comment]
@dhiltgen Disabling mmap makes a world of difference. All the models actually load now, properly split across CPU and GPU. They also load a billion times faster. It's like magic. But mmap doesn't seem to be globally toggleable, and OpenWebUI seems to have only "on" or "default" as options for mmap, instead of also having an "off" value (this isn't part of the Ollama project, but it is odd).

I will now be making some new modelfiles with ollama disabled.

**Comment by ProjectMoon** [comment]
Have noticed, though, that some models have issues loading with mmap disabled if I increase the context size. They crash for various reasons, and not always out of memory issues.

**Comment by dhiltgen** [comment]
We'll track this via #3940
