### ISSUE TITLE
 Unable to determine if Ollama can be run on GPU after running Linux commands

### ISSUE THREAD

**Issue by jerry123cao** [ollama/ollama#4353]
Hello, I have a question. If I use the command curl - fsSL https://ollama.com/install.sh |Can Ollama run on GPU after installing the Nvidia driver and cuda toolkit in SH?

**Comment by dhiltgen** [comment]
Our documentation for GPU support is located here - https://github.com/ollama/ollama/blob/main/docs/gpu.md

Once installed, you can use `ollama ps` to see if the models have loaded into your GPU or are running on CPU.  More details can be found in the server log and we will log if we fail to discover GPUs or find GPUs that aren't compatible.  In the future we may add more informational commands to show you what GPUs we discovered and if we discovered any that aren't compatible.
