### ISSUE TITLE
Models often don't load on versions after 0.1.132

### ISSUE THREAD

**Issue by ProjectMoon** [ollama/ollama#4354]
### What is the issue?

Many models, in particular codegemma 1.1 7b q8_0, don't load for various reasons on versions after 0.1.132. Works fine on 132. I don't have the logs on hand at the moment, but can add them later. The errors relate to out of memory errors and unable to reset the GPU VRAM.

This is using ROCm (ollama distribution of it, from the tar.gz) on AMD RX 6800 XT.

Is there a centralized issue for this already?

### GPU

AMD

### CPU

AMD

### Ollama version

0.1.133-0.1.136

**Comment by coder543** [comment]
This was probably the main issue for this kind of thing: https://github.com/ollama/ollama/issues/1952#issuecomment-2105376333

I would probably leave a comment there too. Since you're on AMD, it's not actually related to CUDA, but it sounds like the same fundamental issue.

**Comment by ProjectMoon** [comment]
Here are the logs:

```
llama_kv_cache_init:      ROCm0 KV buffer size =  7182.00 MiB
llama_new_context_with_model: KV self size  = 7182.00 MiB, K (f16): 3591.00 MiB, V (f16): 3591.00 MiB
llama_new_context_with_model:  ROCm_Host  output buffer size =     1.98 MiB
ggml_backend_cuda_buffer_type_alloc_buffer: allocating 573.07 MiB on device 0: cudaMalloc failed: out of memory
ggml_gallocr_reserve_n: failed to allocate ROCm0 buffer of size 600903680
llama_new_context_with_model: failed to allocate compute buffers
llama_init_from_gpt_params: error: failed to create context with model '/mnt/tank/ai/models/ollama/blobs/sha256-039382c23c3693407458d9d014b661611c81a957ded71da627db6aaeee3fb1cc'
terminate called without an active exception
```

It seems to be related to either context size or max token size. Will add more info later.

**Comment by ProjectMoon** [comment]
So, I can run the model with a smaller context size/number of tokens to generate, but not higher. I was trying with a context size of 8199 (model forced it), and then the error above occurred, and then ollama started trying to load it repeatedly.

**Comment by ProjectMoon** [comment]
Bit more testing: If I force the context size to 8192 on codegemma v1.1, it crashes with the above error. Leaving it to the defaults seems to work fine. Oddly enough, when loading the model with n_ctx 8192, it showed up as n_ctx 16384 in the ollama logs? o_O

**Comment by dhiltgen** [comment]
Are you still seeing this behavior on the latest release?  I was able to load codegemma with various context sizes on an RX 6800 without hitting oom crashes.

**Comment by ProjectMoon** [comment]
Not this exact issue, but I still run into problems, particularly with longer contexts: https://github.com/ollama/ollama/issues/5741

I actually had to implement a GPU layer downscaling filter for Open Web UI to override `num_gpu` on ollama crash so I can continue conversations. :thinking:

**Comment by dhiltgen** [comment]
Sorry you're still hitting OOM challenges with large contexts.   I've got a PR up to add back a workaround that should make it a little easier to mitigate these defects until we can get them properly fixed - see #5922

**Comment by ProjectMoon** [comment]
That will certainly help. Do you want any logs or test contexts or anything?

**Comment by pdevine** [comment]
I'm going to close this since #5922 was merged, but we can reopen it if you're still hitting it.
