### ISSUE TITLE
bge-reranker-v2-m3、mxbai-rerank-large-v1 and other rerank models

### ISSUE THREAD

**Issue by Feng-YiJing-Dao** [ollama/ollama#4360]
The rerank model cannot be converted to the ollama-supported format through llama.cpp, but in RAG, I hope to run a rerank model to improve the accuracy of recall.

I try to use bge-reranker-v2-m3、mxbai-rerank-large-v1，model.safetensors format，
![image](https://github.com/ollama/ollama/assets/18107069/f5dab310-5b0e-47ce-a559-e4845d5c3b92)

![image](https://github.com/ollama/ollama/assets/18107069/ad7ffb47-b299-4f63-9818-4e635b28719e)

**Comment by BradKML** [comment]
Add one more to the pile, buddy. We are all on the same boat https://github.com/ollama/ollama/issues/3749

**Comment by yushengliao** [comment]
+1

**Comment by TE-WoodyLi** [comment]
+1

**Comment by xsoway** [comment]
hope  ollama support rerank models

**Comment by BradKML** [comment]
Again to everyone here, please stop posting "+1" since there is literally a react function

**Comment by netandreus** [comment]
+1 We really need this!

**Comment by rjmalagon** [comment]
rerank and colbert too.
https://huggingface.co/mixedbread-ai/mxbai-colbert-large-v1

**Comment by lucasdengcn** [comment]
+1

**Comment by cleverpig** [comment]
+1

**Comment by unizhu** [comment]
+1

**Comment by enryteam** [comment]
+1

**Comment by mark-bradshaw** [comment]
+1

**Comment by jmorganca** [comment]
Merging with https://github.com/ollama/ollama/issues/3368

**Comment by miaonv** [comment]
We really need the rerank model on ollama

**Comment by viosay** [comment]
+1

**Comment by zhoufengen** [comment]
we really need this too！bge-reranker-v2-m3

**Comment by Kingtous** [comment]
+1, bge-reranker is all we need for RAG

**Comment by sernddev** [comment]
+1

**Comment by value-added-korea** [comment]
+1
