### ISSUE TITLE
better docs on python library settings

### ISSUE THREAD

**Issue by nikhil-swamix** [ollama/ollama#4367]
### What is the issue?

many options in source reg GPU setting `C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\ollama\_types.py` are useless, ive tried tweaking all of them!, please improve documentation on it only the mlock, mmap options work for resource allocation settings. GPU are completely opaque , usually selects most idle gpu. and change of any model init options `aka load time` options restart the server, is there any HOT reload setting? like `/set` in interactive mode? for the model init prams? or not feasible as once initialized , cant be changed?

reference of file which im talking about. num_gpu and main_gpu

```
class Options(TypedDict, total=False):
  # load time options
  numa: bool
  num_ctx: int
  num_batch: int
  num_gpu: int
  main_gpu: int
  low_vram: bool
  f16_kv: bool
  logits_all: bool
  vocab_only: bool
  use_mmap: bool
  use_mlock: bool
  embedding_only: bool
  num_thread: int

  # runtime options
  num_keep: int
  seed: int
  num_predict: int
  top_k: int
  top_p: float
  tfs_z: float
  typical_p: float
  repeat_last_n: int
  temperature: float
  repeat_penalty: float
  presence_penalty: float
  frequency_penalty: float
  mirostat: int
  mirostat_tau: float
  mirostat_eta: float
  penalize_newline: bool
  stop: Sequence[str]

```

# suggestion

```
Suggestion: can it be nested like:
settings = {
  "cpu":{ a:b},
  "gpu":{c:d},
  "llamacpp":{more_settings}
}

# and few aliases like
max_tokens=num_ctx

# and converters to human friendly like
num_ctx="32k" -> 32,000
```

_____
# however
`from llama_cpp import Llama`
 this thing works when we set, using `os.environ["CUDA_VISIBLE_DEVICES"] = "1"` and various other options. please add features appropriately, using is programmatically or using open AI client is very difficult, for example if we want to customize the parameters like mirostat, using profiles like ("creative", "precise","balanced") like copilot, then we need first class support. the `ollama.chat ` method shows very little documentation in docstring. 

# question
may i work on improving documentation and more customization as raw settings provided by llama.cpp ? let me know. ollama provides good levvel of automation but has customization issues.

**Comment by dhiltgen** [comment]
Ollama is a client-server architecture, and the parameters you're referring to are the client side settings.  What's slightly confusing is the `num_gpu` setting is actually the number of layers of the model to load into the GPU.  The docs for this part of the API should be improved, however if you're looking for how to configure the GPU, see https://github.com/ollama/ollama/blob/main/docs/gpu.md

**Comment by nikhil-swamix** [comment]
hi @dhiltgen  sir,
in deed at this point i started learning "Go" to understand the internals better. 
i would like to ask if this https://wiki.mutable.ai/ollama/ollama , is good or not? how do you view it?
and if it can be included as small link in documentation?
it provide great entry point for developers, and seems a developer guide than user guide, but concept is nice!
may i add this in bottom of readme?

**Comment by nikhil-swamix** [comment]
great
