### ISSUE TITLE
Yi 1.5 was released

### ISSUE THREAD

**Issue by ddpasa** [ollama/ollama#4381]
https://github.com/01-ai/Yi-1.5

https://huggingface.co/collections/01-ai/yi-15-2024-05-663f3ecab5f815a3eaca7ca8

**Comment by mchiang0610** [comment]
Hi this is available now 

https://ollama.com/library/yi

**Comment by binganao** [comment]
> Hi this is available now您好，现在可用
> 
> https://ollama.com/library/yi

Hello, I would like to ask, does Yi-v1.5-Chat 34B correspond to https://ollama.com/library/yi:34b-v1.5-q4_0? I can’t find the content of Yi-v1.5-Chat
