### ISSUE TITLE
Ollama "ollama show --modelfile" shows license instead of modelfile

### ISSUE THREAD

**Issue by omegatao** [ollama/ollama#4384]
### What is the issue?

When the command 'ollama show --modelfile llama3:70b' is entered, it should have displayed information about the model's modelfile, but instead, it displayed license information.
The "--modelfile: parameter for "ollama show" command seems not working.

### OS

Linux

### GPU

Nvidia

### CPU

AMD

### Ollama version

0.1.36

**Comment by pdevine** [comment]
Hey @omegatao It shows the complete file, you just need to scroll up (or pipe it to something like more/less).

**Comment by omegatao** [comment]
> Hey @omegatao It shows the complete file, you just need to scroll up (or pipe it to something like more/less).

According to what you said, I tried it and there's no problem. Thank you for your patient response.👍
