### ISSUE TITLE
Support tools in OpenAI-compatible API

### ISSUE THREAD

**Issue by jackmpcollins** [ollama/ollama#4386]
Support the `tools` and `tool_choice` parameters in the OpenAI-compatible API. Currently these are not supported https://github.com/ollama/ollama/blob/4ec7445a6f678b6efc773bb9fa886d7c9b075577/docs/openai.md#supported-request-fields

I believe `llama.cpp` is used internally by Ollama, and this has support for tools and tool_choice https://github.com/abetlen/llama-cpp-python#function-calling so the implementation in Ollama can hopefully leverage this.

Having the tools parameter implemented in Ollama (or llama.cpp and surfacing this) would standardize all downstream packages (e.g. https://github.com/BerriAI/litellm , https://github.com/jackmpcollins/magentic) on a single prompt and implementation, which will make it more robust.

I would use this to improve support for local LLMs in https://github.com/jackmpcollins/magentic

Related issues
- https://github.com/ollama/ollama/issues/305
- https://github.com/ollama/ollama/issues/1729
- https://github.com/ollama/ollama/issues/3165

**Comment by zyxcambridge** [comment]
OpenAI compatibility  for curl https://api.openai.com/v1/chat/completions \
  -H "Content-Type: application/json" \
  -H "Authorization: Bearer $OPENAI_API_KEY" \
  -d '{
    "model": "gpt-4-turbo",
    "messages": [
      {
        "role": "user",
        "content": [
          {
            "type": "text",
            "text": "What’s in this image?"
          },
          {
            "type": "image_url",
            "image_url": {
              "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/dd/Gfp-wisconsin-madison-the-nature-boardwalk.jpg/2560px-Gfp-wisconsin-madison-the-nature-boardwalk.jpg"
            }
          }
        ]
      }
    ],
    "max_tokens": 300
  }'

**Comment by zhangweiwei0326** [comment]
+1

**Comment by kyjus25** [comment]
+1 Looks like I'm too early to the party yet again 😅

**Comment by muliyul** [comment]
I'd like to contribute to this, however I'm not familiar with the repo. If someone can lay out what needs to be done I'd be happy to work on it.

**Comment by gaurish-mehra** [comment]
+1

**Comment by kkolago** [comment]
+1

**Comment by slavonnet** [comment]
+1

**Comment by dariush-bahrami** [comment]
+1

**Comment by nikhil-swamix** [comment]
![image](https://github.com/ollama/ollama/assets/54004431/f7387d17-32ce-40fe-a101-538db9b43288)

**Comment by langchain4j** [comment]
@jmorganca even a rough estimate would be highly appreciated, thank you!

**Comment by kyjus25** [comment]
@langchain4j uhh... I think it was just merged, actually 😆

https://github.com/ollama/ollama/pull/5614

**Comment by meletis** [comment]
@jmorganca, is this going to be part of the next release?

**Comment by humcqc** [comment]
> @langchain4j uhh... I think maybe it was just merged, actually? I can't really tell but the PR name and description lines up
> 
> #5614

I think this is just a part of what needs to be done to have tools working in ollama ?

**Comment by kyjus25** [comment]
@humcqc yes, agreed. I've seen lots of commits go thru now about tools

Here's an X post I saw about tools with a demo if anyone is curious; it was mentioned in their keynote.

https://x.com/AlexReibman/status/1814142347367817443

We are close!!!

**Comment by kyjus25** [comment]
I'll believe it when the dang "Function calling" checkbox is checked 😂 I check every day and it's getting unhealthy
https://github.com/ollama/ollama/blob/main/docs/openai.md#endpoints

**Comment by humcqc** [comment]
> I'll believe it when the dang "Function calling" checkbox is checked 😂 I check every day and it's getting unhealthy https://github.com/ollama/ollama/blob/main/docs/openai.md#endpoints

Yes seems we are close!!

**Comment by jmorganca** [comment]
Hi there, this is now supported as of 0.3.0 https://ollama.com/blog/tool-support

Note: OpenAI _streaming_ tool calling isn't yet implemented, but this is something being worked on

**Comment by pamelafox** [comment]
Awesome! I tested this for a RAG app and found that I had to use few shot examples to get good results, at least from llama3.1.
Blog with more details: https://blog.pamelafox.org/2024/08/making-ollama-compatible-rag-app.html

**Comment by mdrxy** [comment]
For anyone who stumbles upon this, streaming tool calling [is now supported](https://ollama.com/blog/streaming-tool). `tool_choice` is not.
