### ISSUE TITLE
Accept or Ignore additional headers in OpenAI compatible endpoints

### ISSUE THREAD

**Issue by UdaraJay** [ollama/ollama#4388]
The OpenAI javascript SDK adds some `x-stainless-*` headers to API calls that cause preflight checks to fail against Ollama's API when switching out the baseUrl for Ollama's `v1/chat/completions` endpoint. 

```
Access to fetch at 'http://localhost:11434/v1/chat/completions' from origin 'http://localhost' has been blocked by CORS policy: Request header field x-stainless-os is not allowed by Access-Control-Allow-Headers in preflight response.
``` 

Would be great if you could configure cors in more detail when running the server or if these additional headers are ignored or accepted as they can't be disabled on the SDK unless you modify the library.

**Comment by jmorganca** [comment]
Thanks for the issue!
