### ISSUE TITLE
pre-built binary doesn't work on Jeston with JP6 GA system

### ISSUE THREAD

**Issue by TadayukiOkada** [ollama/ollama#4391]
### What is the issue?

I get this error if I run the pre-built binary on Jetson Orin with JP6 GA system installed:
`source=sched.go:339 msg="error loading llama server" error="llama runner process has terminated: signal: aborted (core dumped) CUDA error: CUBLAS_STATUS_EXECUTION_FAILED\n  current device: 0, in function ggml_cuda_mul_mat_batched_cublas at /go/src/github.com/ollama/ollama/llm/llama.cpp/ggml-cuda.cu:1848\n  cublasGemmBatchedEx(ctx.cublas_handle(), CUBLAS_OP_T, CUBLAS_OP_N, ne01, ne11, ne10, alpha, (const void **) (ptrs_src.get() + 0*ne23), CUDA_R_16F, nb01/nb00, (const void **) (ptrs_src.get() + 1*ne23), CUDA_R_16F, nb11/nb10, beta, ( void **) (ptrs_dst.get() + 0*ne23), cu_data_type, ne01, ne23, cu_compute_type, CUBLAS_GEMM_DEFAULT_TENSOR_OP)\nGGML_ASSERT: /go/src/github.com/ollama/ollama/llm/llama.cpp/ggml-cuda.cu:60: !\"CUDA error\""`

I built ollama from source and it runs fine on JP6 system. Also, pre-built binaries were working on JP5.1.3 system.

### OS

Linux

### GPU

Nvidia

### CPU

Other

**Comment by hangxingliu** [comment]
I also encountered this issue today on my AGX Orin after I tried using the latest pre-built ollama. However, everything works great like the past if I use the binary built by myself.

Here are some diagnosis, I hope them could help you to fix this issue:

Ollama's journal logs: [20240525-ollama-error-logs.log](https://github.com/ollama/ollama/files/15440993/20240525-ollama-error-logs.log)

The model that I tested: `llama3:8b`

My hardware info:
```
 - Module: NVIDIA Jetson AGX Orin (64GB ram)
 - SoC: tegra234
 - CUDA Arch BIN: 8.7
 
 - Machine: aarch64
 - System: Linux
 - Distribution: Ubuntu 22.04 Jammy Jellyfish
 - Release: 5.15.122-tegra
 - Jetpack: 6.0 DP
 
 - Python: 3.10.12
 - CUDA: 12.2.140
 - cuDNN: 8.9.4.25
 - TensorRT: 8.6.2.3
```

**Comment by dhiltgen** [comment]
We'll track Orin/JP6 support in #2408
