### ISSUE TITLE
how to keep system prompt permanently after setting SYSTEM

### ISSUE THREAD

**Issue by taozhiyuai** [ollama/ollama#4397]
### What is the issue?

1. /set SYSTEM
2. /show modelfile,  I can see the setting is updated.
3. if I /bye, and ollama run model again, and /show modelfile , it seems SYSTEM in modelfile is restored.

is that possible the model can keep my new SYSTEM setting permanently?

### OS

macOS

### GPU

Apple

### CPU

Apple

### Ollama version

1.37

**Comment by jmorganca** [comment]
Hi @taozhiyuai, you can do `/save <name>` and `/load <name>` to save a new model with the system prompt you've set with `/set system`. Hope this helps!

**Comment by taozhiyuai** [comment]
> Hi @taozhiyuai, you can do `/save <name>` and `/load <name>` to save a new model with the system prompt you've set with `/set system`. Hope this helps!

I see. it works. so the help information should be modified. Not to "load a session"  or "save ... session". it should be "load a model" and "save ... model". I misunderstand the help which may mean load and save a conversation between me and LLM. @_@

  /load <model>   Load a session or model
  /save <model>   Save your current session
