### ISSUE TITLE
Error While running " ollama run llama2" or any model. 

### ISSUE THREAD

**Issue by dimpu1117** [ollama/ollama#4402]
I getting a error when i am trying to setup ollama in windows. i have installed ollama successfully and even the ollama serve is also working. but when i try to run a model i am getting this error.
Error Message:
PS C:\Users\DAQ2KOR> ollama run llama2
pulling manifest
Error: pull model manifest: Get "https://registry.ollama.ai/v2/library/llama2/manifests/latest": dial tcp: lookup registry.ollama.ai on 10.58.194.16:53: no such host

**Comment by pdevine** [comment]
Hey @dimpu1117 Are you by any chance behind some kind of firewall?

**Comment by SleeplessBegonia** [comment]
me too.how did you solve it?

**Comment by dhiltgen** [comment]
`10.58.194.16:53` is an internal DNS server within your network.  That DNS server isn't resolving internet hostnames and can't resolve the ollama registry.   Hopefully whoever manages your network provides a proxy to be able to connect to the internet, and if so, you can use https://github.com/ollama/ollama/blob/main/docs/faq.md#how-do-i-use-ollama-behind-a-proxy to set up the proxy.   If your host has no possible way to connect to the internet, you could attempt to pull models on another computer on another network that does have internet connectivity, and then replicate the models directory https://github.com/ollama/ollama/blob/main/docs/faq.md#where-are-models-stored
