### ISSUE TITLE
为什么同样的脚本（Qwen1.5/examples/web_demo.py）去执行Qwen1.5-32B-Chat-GPTQ-Int4的推理时，4090 24G 比 V100 32G 回答速度快了5倍，这是什么原因，是显卡性能的问题，还是代码还有哪个配置没有打开，导致V100的计算能力没有发挥出来？

### ISSUE THREAD

**Issue by lbl1120** [ollama/ollama#4403]
为什么同样的脚本（Qwen1.5/examples/web_demo.py）去执行Qwen1.5-32B-Chat-GPTQ-Int4的推理时，4090 24G 比 V100 32G 回答速度快了5倍，这是什么原因，是显卡性能的问题，还是代码还有哪个配置没有打开，导致V100的计算能力没有发挥出来？
![Uploading 屏幕截图 2024-05-13 212724.png…]()

**Comment by mchiang0610** [comment]
NVIDIA v100 的显示卡是 6年前的 
NVIDIA 4090 是用新的架构做出来的. 会快非常多
