### ISSUE TITLE
Discrepancy between FAQ and program

### ISSUE THREAD

**Issue by FrederikSchack** [ollama/ollama#4407]
### What is the issue?

According to your FAQ, there should be a control panel in the Windows version for setting the environment variables:
https://github.com/ollama/ollama/blob/main/docs/faq.md

There isn't any control panel when you start the program, no apparent control panel or configuration file in the Ollama folder (\AppData\Local\Programs\ollama).

### OS

Windows

### GPU

Nvidia

### CPU

Intel

### Ollama version

0.1.37

**Comment by thinkverse** [comment]
The wording might be off. But I think they mean Windows Control Panel. Should be in System Properties according to https://www.howtogeek.com/787217/how-to-edit-environment-variables-on-windows-10-or-11/, I don't have Windows so cannot confirm. 🤷‍♂️

But I'm pretty sure given the first step in the FAQ is to quit Ollama.

> 1. First Quit Ollama by clicking on it in the task bar

**Comment by pdevine** [comment]
I just merged #4415 which should be clearer about this. We do have some changes coming soon which hopefully will make this easier though, but for now, please refer to the (updated!) FAQ.
