### ISSUE TITLE
Windows security: ALERT: Trojan:Win32/Wacatac.H!ml detected

### ISSUE THREAD

**Issue by boessu** [ollama/ollama#4409]
### What is the issue?

There is an alarm in Windows Defender which sets the following file under quarantine:
file: %USERPROFILE%\AppData\Local\Programs\Ollama\ollama app.exe

Windows Version: Windows 11 Pro, 23H2

You'll get the warning with update and also if you install it new.

### OS

Windows

### GPU

AMD

### CPU

AMD

### Ollama version

0.1.37

**Comment by jmorganca** [comment]
Hi there, this is a false positive from Windows Defender that seems to have begun to happen again. I've contacted the folks at Microsoft Security Intelligence to make sure we get this fixed. So sorry about that – it should be resolved within a day or so
