### ISSUE TITLE
[Contribution] ZSH Completion script

### ISSUE THREAD

**Issue by obeone** [ollama/ollama#4418]
Hi,

Here, you can find a `ollama` ZSH completion script. Feel free to add it in the project if you want !

https://gist.github.com/obeone/9313811fd61a7cbb843e0001a4434c58

**Comment by pdevine** [comment]
Hey @obeone , thanks for the issue and the gist! There is an issue for this #1653 and someone created a PR but I couldn't get it to work correctly. I'll take a look when I get a chance. I'll close this one as a dupe though.
