### ISSUE TITLE
Behind PROXY, how to set a proxy in Ollama

### ISSUE THREAD

**Issue by mchopra80** [ollama/ollama#4434]
### What is the issue?

I installed Ollama on a Windows Server and on cmd I can call Ollama but when trying to pull a model I get this error:
pulling manifest
Error: pull model manifest: Get https://registry.ollama.ai/v2/library/llama3/manifests/latest: dial tcp: lookup registry.ollama.ai: no such host

I am behind a corporate firewall and need to set the proxy - how do I set the PROXY information in ollama Windows Version? thanks.

### OS

Windows

### GPU

Other

### CPU

Intel

### Ollama version

0.1.37

**Comment by pdevine** [comment]
This is covered in the [FAQ](https://github.com/ollama/ollama/blob/main/docs/faq.md#how-do-i-use-ollama-behind-a-proxy). Also check out [how to set environment variables(https://github.com/ollama/ollama/blob/main/docs/faq.md#how-do-i-configure-ollama-server) in the FAQ as well.

Hopefully this helps!

**Comment by WeiguangHan** [comment]
@mchopra80 Hi, have you solved this problem？

**Comment by yifan0011** [comment]
> [@mchopra80](https://github.com/mchopra80) Hi, have you solved this problem？

I didn't, after setting the system variable, I got another error pulling model: Error: max retries exceeded: EOF

**Comment by yangjianlin-c** [comment]
it can be solved by add environment variable HTTPS_PROXY on windowns.

If still not clear about it, ref to this guide

[https://esp32cube.com/post/set-proxy-for-ollma-on-windows/](https://esp32cube.com/post/set-proxy-for-ollma-on-windows/)

**Comment by 5yh** [comment]
you need to reboot ollama after you set HTTPS_PROXY

**Comment by gavinesl** [comment]
> you need to reboot ollama after you set HTTPS_PROXY

Helped!  On windows,  run "Quit ollama" after you set HTTPS_PROXY.

**Comment by dv0ps** [comment]
There are other issues at play in addition to setting the environment variable correctly on a windows client. 
This particular error "pull model manifest: Get "https://registry.ollama.ai/v2/library/<LLMname>/manifests/2b": EOF" can also be related to a corporate firewall proxy with TLS snooping (inspection) security enabled which can cause TLS handshake problems and other TLS connection issues causing the ollama client to error out. 

With ollama being a trusted web service many corporate IT dept may allow an exception be made for the ollama's download host: "registry.ollama.ai"   Ask your IT group to exclude it from TLS inspection.
