### ISSUE TITLE
Ollama vs Llama-cpp-python : Slow response time as compared to llama-cpp-python

### ISSUE THREAD

**Issue by utility-aagrawal** [ollama/ollama#4437]
### What is the issue?

Hi,

I built a RAG Q&A pipeline using LlamaIndex and Llama-cpp-python in the past. I want to switch from llama-cpp to ollama because ollama is more stable and easier to install. When I made the switch, I noticed a significant increase in response time. Would you know what might cause this slowdown?

I have kept everything same for the comparison and have only changed llm component to point to ollama instead of llama-cpp. I am using the same quantized version of llama-3 for comparison.

Appreciate your inputs! Thanks! 

### OS

Linux

### GPU

Nvidia

### CPU

Intel

### Ollama version

0.1.33

**Comment by pdevine** [comment]
@utility-aagrawal What kind of GPU are you using? Is the model offloaded entirely onto the GPU or only partially?

**Comment by utility-aagrawal** [comment]
Thanks for your response, @pdevine!

I have an NVIDIA GeForce RTX 3060 (12 GB VRAM). Yes, I am using these parameters {"n_gpu_layers": n_gpu_layers, "offload_kqv": True} which offload the entire model onto the GPU. Let me know if you need anything additional. Thanks!

**Comment by utility-aagrawal** [comment]
@pdevine @dhiltgen Do you have any suggestions on this?

**Comment by utility-aagrawal** [comment]
@pdevine @dhiltgen Reminder!

**Comment by dhiltgen** [comment]
A few things to try to narrow this one down...

Try passing `"use_mmap": false` and see if that changes things.

Also can you share the llama.cpp configuration log line. In the Ollama logs it will look something like this:
```
INFO [main] system info | n_threads=4 n_threads_batch=-1 system_info="AVX = 1 | AVX_VNNI = 0 | AVX2 = 0 | AVX512 = 0 | AVX512_VBMI = 0 | AVX512_VNNI = 0 | AVX512_BF16 = 0 | FMA = 0 | NEON = 0 | SVE = 0 | ARM_FMA = 0 | F16C = 0 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 1 | SSE3 = 1 | SSSE3 = 1 | VSX = 0 | MATMUL_INT8 = 0 | LLAMAFILE = 1 | " tid="140021226209280" timestamp=1718729924 total_threads=8
```

Perhaps there's a material difference in the compilation of the llama.cpp that's leading to the performance difference.

**Comment by dhiltgen** [comment]
Let us know if you're still having performance problems.
