### ISSUE TITLE
Resume a conversation started in Open Web-UI using ollama command line

### ISSUE THREAD

**Issue by tomav** [ollama/ollama#4450]
Hi there!
I can't find information on this, let me know if there's actually a way to do this.
Thanks!

**Comment by WolfTheDeveloper** [comment]
This wouldn't be an Ollama thing. I would bring this up to Open Web UI itself.

**Comment by tomav** [comment]
Hi @WolfTheDeveloper, well, my mental model was that it is possible to have conversations with context using Ollama APIs in Open Web UI. We can see a `context` parameter in [Ollama API doc](https://github.com/ollama/ollama/blob/main/docs/api.md#parameters).
Question is how to do the same using Ollama command line, that's why I created the question here, and I can't find options to use a contact `parameter` on the `ollama run` command.
I don't think see it as an Open Web UI thing (and this just should be a frontend on top of Ollama and other API based LLMs.

**Comment by mxyng** [comment]
Open WebUI and Ollama CLI are two distinct applications implementing frontends for the Ollama API. While you can definitely use `context` with `/api/generate` and `messages` with `/api/chat` to implement chat history, it's an implementation detail of the application to support persistence or cross-application chat history.

Ollama CLI has a feature which saves its conversation history into a Modelfile through the MESSAGE command. This can used to persist and reload the session. I'm not sure if Open WebUI uses this feature.

**Comment by tomav** [comment]
Thanks @mxyng, crystal clear.
