### ISSUE TITLE
[REPORTING] For arch or arch based linux users storage path for models is /var/lib/ollama/.ollama/models/blobs

### ISSUE THREAD

**Issue by Greatz08** [ollama/ollama#4455]
I yesterday only installed ollama in my arch linux from aur and did pull 2 models phi3 and llama3 but couldnt find where they are actually stored and unfortunately in all reddit and FAQ the path mentioned was i guess for ubuntu users only so had to struggle but couldnt find so used fzf and service file to locate exact path where ollama models were actually stored so sharing it here so that it can help other arch based users.Please add this path in documentation so that more can know about it.
Thankyou :-))
![20240515_21h21m46s_grim](https://github.com/ollama/ollama/assets/55040435/88ba9a32-f551-41c2-bef0-e8dfb072041e)

**Comment by dhiltgen** [comment]
If you install using the ollama install script, the models will be stored in `/usr/share/ollama/.ollama/models` - https://github.com/ollama/ollama/blob/main/scripts/install.sh#L108

The ollama project and maintainers don't have visibility or control into the various downstream packages and how they're set up.  I think the docs for model storage which deviate from the default Ollama behavior belongs with those packages.
