### ISSUE TITLE
Confirm GPU usage command

### ISSUE THREAD

**Issue by puddlejumper90** [ollama/ollama#4458]
Would like to have a way to to confirm if a GPU is actually being utilized. Maybe some kind of command or option when running a given model to test/log individual machine performance.

**Comment by pdevine** [comment]
Hey @puddlejumper90 try `ollama ps` in the upcoming release. It will tell you how what percentage of the model is on the CPU/GPU/both. The output looks like:

```
NAME         	ID          	SIZE  	PROCESSOR	UNTIL
mixtral:8x22b	bf88270436ed	82 GB 	100% GPU 	4 minutes from now
llama3:latest	71a106a91016	5.9 GB	100% GPU 	About a minute from now
```

**Comment by puddlejumper90** [comment]
lifesaver, thank you @pdevine!

**Comment by pdevine** [comment]
@puddlejumper90 lmk how it goes. We just shipped the feature yesterday.
