### ISSUE TITLE
Add new model error 

### ISSUE THREAD

**Issue by momo8zero** [ollama/ollama#4466]
hi, im developer 

I want add a new Model , but tips 
```
Error: Models based on 'LlamaForCausalLM' are not yet supported
```
Do you have any solutions? thanks!

**Comment by dhiltgen** [comment]
@momo8zero if you're still having trouble importing, make sure you've upgraded to the latest ollama and if that doesn't solve it, please share some more information on what you're trying to import and we'll reopen the issue.
