### ISSUE TITLE
Ollama  memory consumption

### ISSUE THREAD

**Issue by hugefrog** [ollama/ollama#4469]
### What is the issue?

Why does Ollama consume so much memory? With a 3090 graphics card and 24GB of VRAM, after loading a yi-34b-4bit model of around 20GB in size, both the system memory and VRAM are consumed by approximately 20GB simultaneously.

### OS

Windows

### GPU

Nvidia

### CPU

Intel

### Ollama version

0.1.38

**Comment by dhiltgen** [comment]
I'm not able to reproduce this.  On windows on a 4090, I can load `yi:34b` entirely into GPU:
```
>  ollama ps
NAME    ID              SIZE    PROCESSOR       UNTIL
yi:34b  ff94bc7c1b7a    20 GB   100% GPU        4 minutes from now
```

The `ollama_llama_server` process uses 929 MB of system memory, and ~20G of VRAM according to Task Manager.

Are you using a larger context size that is causing the model to partially load on CPU?

If you're still seeing large system memory consumption, please make sure to upgrade to the latest version, and share more details of your setup and I'll reopen the issue.  (`ollama ps` output, screen shots from task manager, and server logs)
