### ISSUE TITLE
Ram not releasing 

### ISSUE THREAD

**Issue by Stampsm** [ollama/ollama#4478]
### What is the issue?

I seem to have an issue with ram not releasing after model unloads. I waited for the new version with the PS command and verified that the model was unloaded after the default 5 minute timeout and a large duffer time after that just to be safe, but my ram usage was still showing ~60GB on this fresh install of Ubuntu the exact same as it was before the model unloaded. When I try to again load a large model after a while when it's loading my system will crash from what seems like an out of memory issues as this proxmox VM image only has ~120GB allocated to it. Nothing else is running on this image as it was a fresh install just for Ollama and openwebui interface. Is there any suggestions or info needed?

### OS

Linux

### GPU

Other

### CPU

Intel

### Ollama version

0.1.38

**Comment by Stampsm** [comment]
I just ha this again. When I load a larger model and it shows unloaded a few hours later then try to load a different large model my whole system soon crashes. Is there a log someplace I can review?

**Comment by dhiltgen** [comment]
Can you share a little more data?  How are you measuring RAM usage before/during/after loading models?  Could you run something like `ps -eo pid,ppid,rss,args | grep ollama` demonstrating what you're seeing?

**Comment by dhiltgen** [comment]
If you're still having trouble, please share more info about your measurements and I'll re-open the issue.  You can find our troubleshooting docs here https://github.com/ollama/ollama/blob/main/docs/troubleshooting.md
