### ISSUE TITLE
Gemma:latest aborted (core dumped)

### ISSUE THREAD

**Issue by ManuLinares** [ollama/ollama#4484]
### What is the issue?

Ollama server logs: https://pastebin.com/DyqQwwFf

ollama run gemma:latest #output
`Error: llama runner process has terminated: signal: aborted (core dumped) error:failed to create context with model '/home/mb/.ollama/models/blobs/sha256-ef311de6af9db043d51ca4b1e766c28e0a1ac41d60420fed5e001dc470c64b77'
`

Worked on the previous, 0.1.36

System Archlinux
linux 6.8.9.arch1-2
ollama-cuda 0.1.38-1
cuda 12.4.1-4
nvidia-dkms 550.78-1

### OS

Linux

### GPU

Nvidia

### CPU

Intel

### Ollama version

0.1.38

**Comment by dhiltgen** [comment]
This has been fixed since 0.1.38.  I was able to repro the crash with an 8k context with 0.1.38 (we attempt to load 24 out of 29 layers) and I've confirmed 0.2.8 loads 21 layers without crashing.
