### ISSUE TITLE
Not compiled with GPU offload support

### ISSUE THREAD

**Issue by oldgithubman** [ollama/ollama#4486]
### What is the issue?

Trying to use ollama like normal with GPU. Worked before update. Now only using CPU.
`$ journalctl -u ollama`
reveals
`WARN [server_params_parse] Not compiled with GPU offload support, --n-gpu-layers option will be ignored. See main README.md for information on enabling GPU BLAS support | n_gpu_layers=-1`

1. I do not manually compile ollama. I use the standard install script.
2. Main README.md contains no mention of BLAS

### OS

Linux

### GPU

Nvidia

### CPU

Intel

### Ollama version

0.1.38

**Comment by jmorganca** [comment]
Hi @oldmanjk sorry about this. May I ask which model you are running? and on which GPU?

**Comment by mroxso** [comment]
I think I got the same issue.
Running llama2:latest and llama3:latest on my GTX 1660 SUPER.
Worked before, now I updated to the latest Ollama and it seems that it mostly uses CPU which is way slower.

**Comment by jukofyork** [comment]
Has anybody an idea of the code we need to remove to stop it ignoring our  `num_gpu` settings (again, sigh...)?

**Comment by jukofyork** [comment]
It's at the bottom of  `llm/memory.go`:

```
        //if memoryRequiredPartial > memoryAvailable {
        //      slog.Debug("insufficient VRAM to load any model layers")
        //      return 0, 0, memoryRequiredTotal
        //}
```

**Comment by uncomfyhalomacro** [comment]
got the same issue here on openSUSE Tumbleweed. one thing i noticed is, it uses the GPU for a moment then gone...

[Screencast_20240518_221101.webm](https://github.com/ollama/ollama/assets/66054069/7ddafa42-b21f-402c-a77f-a3febc6754e6)

**Comment by dhiltgen** [comment]
We've recently introduced `ollama ps` which will help show how much of the model has loaded into VRAM.  

We've fixed a few bugs recently around num_gpu handling in some of our prediction logic, but I'm not sure that addresses your comment @jukofyork.   Can you explain what you're trying to do?  The goal of our prediction algorithm is to set num_gpu automatically based on the available VRAM.  There is a minimum requirement for models and if we can't even allocate that minimal amount, then we will fall back to CPU.  If we can satisfy the minimal amount, but not load the full amount, we will partially load on the GPU.  Are you trying to set a lower value to preserve more space on the GPU, or did we predict incorrectly and you're trying to specify more layers?  If our prediction was right, and you still push higher, we'll likely OOM crash by trying to allocate too many layers on the GPU.

**Comment by dhiltgen** [comment]
@oldmanjk the log you attached above seems to show a 2nd attempt where we fell back to the `runners/cpu_avx2/ollama_llama_server` CPU, after most likely unsuccessfully running on the GPU.  Can you share a complete log so we can see what went wrong?

```
sudo systemctl stop ollama
OLLAMA_DEBUG=1 ollama serve 2>&1 | tee server.log
```

**Comment by czrpb** [comment]
Hi! Here is my equivalent issue and log file. Hope this helps!!

```
time=2024-07-21T18:55:31.136-07:00 level=INFO source=gpu.go:205 msg="looking for compatible GPUs"
time=2024-07-21T18:55:31.136-07:00 level=DEBUG source=gpu.go:91 msg="searching for GPU discovery libraries for NVIDIA"
time=2024-07-21T18:55:31.136-07:00 level=DEBUG source=gpu.go:468 msg="Searching for GPU library" name=libcuda.so*
time=2024-07-21T18:55:31.136-07:00 level=DEBUG source=gpu.go:487 msg="gpu library search" globs="[<<<HOME>>/libcuda.so** /usr/local/cuda*/targets/*/lib/libcuda.so* /usr/lib/*-linux-gnu/nvidia/current/libcuda.so* /usr/lib/*-linux-gnu/libcuda.so* /usr/lib/wsl/lib/libcuda.so* /usr/lib/wsl/drivers/*/libcuda.so* /opt/cuda/lib*/libcuda.so* /usr/local/cuda/lib*/libcuda.so* /usr/lib*/libcuda.so* /usr/local/lib*/libcuda.so*]"
time=2024-07-21T18:55:31.146-07:00 level=DEBUG source=gpu.go:521 msg="discovered GPU libraries" paths="[/usr/lib/libcuda.so.555.58.02 /usr/lib64/libcuda.so.555.58.02]"
CUDA driver version: 12.5
time=2024-07-21T18:55:31.254-07:00 level=DEBUG source=gpu.go:124 msg="detected GPUs" count=1 library=/usr/lib/libcuda.so.555.58.02
[GPU-ccd02350-1222-88d2-1eda-c906b3aff9a8] CUDA totalMem 7788 mb
[GPU-ccd02350-1222-88d2-1eda-c906b3aff9a8] CUDA freeMem 7369 mb
[GPU-ccd02350-1222-88d2-1eda-c906b3aff9a8] Compute Capability 7.5
time=2024-07-21T18:55:31.457-07:00 level=DEBUG source=amd_linux.go:356 msg="amdgpu driver not detected /sys/module/amdgpu"
releasing cuda driver library
time=2024-07-21T18:55:31.457-07:00 level=INFO source=types.go:105 msg="inference compute" id=GPU-ccd02350-1222-88d2-1eda-c906b3aff9a8 library=cuda compute=7.5 driver=12.5 name="NVIDIA GeForce RTX 2070 SUPER" total="7.6 GiB" available="7.2 GiB"

  .  .  .

time=2024-07-21T18:55:37.564-07:00 level=INFO source=sched.go:701 msg="new model will fit in available VRAM in single GPU, loading" model=<<<HOME>>/.ollama/models/blobs/sha256-dd0c6f2ea876e4c433325df3398386f24e00d321abf6cec197c1bc1fcf1e0025 gpu=GPU-ccd02350-1222-88d2-1eda-c906b3aff9a8 parallel=4 available=7727087616 required="2.6 GiB"
time=2024-07-21T18:55:37.564-07:00 level=DEBUG source=server.go:100 msg="system memory" total="31.3 GiB" free="29.4 GiB" free_swap="0 B"
time=2024-07-21T18:55:37.564-07:00 level=DEBUG source=memory.go:101 msg=evaluating library=cuda gpu_count=1 available="[7.2 GiB]"
time=2024-07-21T18:55:37.564-07:00 level=INFO source=memory.go:309 msg="offload to cuda" layers.requested=-1 layers.model=19 layers.offload=19 layers.split="" memory.available="[7.2 GiB]" memory.required.full="2.6 GiB" memory.required.partial="2.6 GiB" memory.required.kv="144.0 MiB" memory.required.allocations="[2.6 GiB]" memory.weights.total="1.2 GiB" memory.weights.repeating="797.2 MiB" memory.weights.nonrepeating="410.2 MiB" memory.graph.full="504.0 MiB" memory.graph.partial="914.2 MiB"

  .  .  .

time=2024-07-21T18:55:37.565-07:00 level=INFO source=server.go:383 msg="starting llama server" cmd="/tmp/ollama485515592/runners/cpu_avx2/ollama_llama_server --model <<<HOME>>/.ollama/models/blobs/sha256-dd0c6f2ea876e4c433325df3398386f24e00d321abf6cec197c1bc1fcf1e0025 --ctx-size 8192 --batch-size 512 --embedding --log-disable --n-gpu-layers 19 --verbose --parallel 4 --port 34295"
time=2024-07-21T18:55:37.565-07:00 level=DEBUG source=server.go:398 msg=subprocess environment="[CUDA_PATH=/opt/cuda PATH=/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/opt/cuda/bin:/opt/cuda/nsight_compute:/opt/cuda/nsight_systems/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl LD_LIBRARY_PATH=/tmp/ollama485515592/runners/cpu_avx2:/tmp/ollama485515592/runners]"
time=2024-07-21T18:55:37.565-07:00 level=INFO source=sched.go:437 msg="loaded runners" count=1
time=2024-07-21T18:55:37.565-07:00 level=INFO source=server.go:571 msg="waiting for llama runner to start responding"
time=2024-07-21T18:55:37.565-07:00 level=INFO source=server.go:612 msg="waiting for server to become available" status="llm server error"
WARN [server_params_parse] Not compiled with GPU offload support, --n-gpu-layers option will be ignored. See main README.md for information on enabling GPU BLAS support | n_gpu_layers=-1 tid="126402163820352" timestamp=1721613337
INFO [main] build info | build=3337 commit="a8db2a9ce" tid="126402163820352" timestamp=1721613337
INFO [main] system info | n_threads=6 n_threads_batch=-1 system_info="AVX = 1 | AVX_VNNI = 0 | AVX2 = 1 | AVX512 = 0 | AVX512_VBMI = 0 | AVX512_VNNI = 0 | AVX512_BF16 = 0 | FMA = 1 | NEON = 0 | SVE = 0 | ARM_FMA = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 0 | SSE3 = 1 | SSSE3 = 1 | VSX = 0 | MATMUL_INT8 = 0 | LLAMAFILE = 0 | " tid="126402163820352" timestamp=1721613337 total_threads=6
INFO [main] HTTP server listening | hostname="127.0.0.1" n_threads_http="6" port="34295" tid="126402163820352" timestamp=1721613337
```

[ollama-cleaner.log](https://github.com/user-attachments/files/16327095/ollama-cleaner.log)

**Comment by dhiltgen** [comment]
We've fixed quite a few prediction bugs since 0.1.38, so I'm going to close this one out.  If you're still hitting OOM's on 0.3.4, please share what model you were trying to load, and the server log and I'll reopen.

**Comment by Shadowfita** [comment]
I'm having this issue when trying to run llama3.1:70b with an rtx 3080 and 64GB RAM. It seems that the ollama_llama_server.exe shipped with the latest windows download from the website doesn't have GPU offloading enabled? I get the same error described above.

```
WARN [server_params_parse] Not compiled with GPU offload support, --n-gpu-layers option will be ignored. See main README.md for information on enabling GPU BLAS support | n_gpu_layers=-1 tid="107816" timestamp=1726533930
```

**Comment by KaloyanGeorgiev99** [comment]
> I'm having this issue when trying to run llama3.1:70b with an rtx 3080 and 64GB RAM. It seems that the ollama_llama_server.exe shipped with the latest windows download from the website doesn't have GPU offloading enabled? I get the same error described above.
> 
> ```
> WARN [server_params_parse] Not compiled with GPU offload support, --n-gpu-layers option will be ignored. See main README.md for information on enabling GPU BLAS support | n_gpu_layers=-1 tid="107816" timestamp=1726533930i
i also have the same issue :(

**Comment by Shadowfita** [comment]
There is definitely an issue with the latest binaries, at least on windows. My ollama instance running on my linux server with a gtx 1070 and 32gb ram is able to run llama 3.1 with an excel file, offloading accordingly and providing a response, but my windows PC with RTX 3080 and 64GB ram is giving me an out of memory error.

**Comment by dhiltgen** [comment]
@Shadowfita @KaloyanGeorgiev99 can you share more complete server logs?   This scenario most likely occurs when we're trying to recover from a prior crash failing to start the GPU runner, then fall back to the CPU runner but incorrectly pass a GPU related flag.  I'd like to see what the earlier error(s) were leading up to this.

**Comment by dhiltgen** [comment]
If you're still seeing the problem, please upgrade to the latest release, and if that doesn't clear it up, share a more complete server log so I can see why the prior runner crashed and I'll reopen the issue and investigate.
