### ISSUE TITLE
ollamasetup.exe is not opening 

### ISSUE THREAD

**Issue by virsince2003** [ollama/ollama#4487]
In Windows 11 ollamasetup.exe is not opening after double-clicking and running as an administrator

**Comment by jmorganca** [comment]
Hi @virsince2003, thanks for the issue. May I ask which error you're seeing? A setup screen should appear after double clicking `OllamaSetup.exe`:

<img width="1002" alt="Screenshot 2024-05-16 at 11 23 23 PM" src="https://github.com/ollama/ollama/assets/251292/062efe77-b5ab-41a4-ba85-36b44ceac814">

Would it be possible to retry downloading the file? If it persists please let me know and I can re-open this issue.

**Comment by virsince2003** [comment]
![Screenshot 2024-05-17 120442](https://github.com/ollama/ollama/assets/126976265/5764a773-5a06-4be6-8550-5ddf26054002)


I downloaded it from here it was not opening after double-clicking
but now I downloaded it from  GitHub it is working fine
