### ISSUE TITLE
ollama ps not working

### ISSUE THREAD

**Issue by alnoses** [ollama/ollama#4490]
### What is the issue?

When the ollama ps command is executed, it returns a 404 error whether or not any model is loaded.
It was expected that it would return a message saying there are no models loaded or some line with information about the corresponding loaded model.
Note: if the installed Ollama package could influence anything, it is the one provided in the archlinux repositories. Ollama website localhost:11434 works

### OS

Linux

### GPU

AMD

### CPU

Intel

### Ollama version

0.1.38

**Comment by jmorganca** [comment]
Hi @alnoses, do you know if you're running the latest version of Ollama (0.1.38)? This version is required for `ollama ps` to work (you can view the version by running `ollama -v`) ?

**Comment by alnoses** [comment]
Hello @jmorganca , when I checked it the first time I only got this line.
Warning: client version is 0.1.38
and checking again what comes out indicates this
ollama version is 0.1.36
Warning: client version is 0.1.38
