### ISSUE TITLE
Pulling using API - Session timeout (5 minutes)

### ISSUE THREAD

**Issue by pelletier197** [ollama/ollama#4491]
### What is the issue?

When using the REST API to pull models, the `PULL` request seems to timeout for large models (llama3).

This is linked to [this issue](https://github.com/ollama/ollama-js/issues/72).  

Is there any way to override the default session timeout when pulling models ? I noticed that the `Generate` endpoint accepts a `KeepAlive` [parameter](https://github.com/ollama/ollama/blob/7e1e0086e7d18c943ff403a7ca5c2d9ce39f3f4b/server/routes.go#L136) to override this. Could this be possible for `pull` as well ? 

### OS

Linux

### GPU

Nvidia

### CPU

Intel

### Ollama version

01.38

**Comment by dhiltgen** [comment]
I'm fairly confident this is a client-side issue.  Enable [streaming](https://github.com/ollama/ollama/blob/main/docs/api.md#pull-a-model), or set a longer client-side timeout
