### ISSUE TITLE
Settings getting fluctuated while multiple models are being downloaded

### ISSUE THREAD

**Issue by suryan-s** [ollama/ollama#4496]
### What is the issue?

While i was trying to download multiple models, i noticed the settings widget kinda fluctuating. I have attached the screen record below:

[Screencast from 2024-05-17 15-23-02.webm](https://github.com/ollama/ollama/assets/76394506/e860cdba-6040-4a28-a60c-f1c4be89a651)

This only happens when I'm trying to download multiple models at the same time. No issue with single download

### OS

Linux

### GPU

Nvidia

### CPU

Intel

### Ollama version

0.1.36

**Comment by jimscard** [comment]
It appears that you are using the openwebui (ollama doesn't have the UI in your recording). You may wish to ask the developers of that UI about its behavior.
