### ISSUE TITLE
Ollama install broken on Manjaro Linux -  sh: line 252: VERSION_ID: unbound variable

### ISSUE THREAD

**Issue by aBaldoqui** [ollama/ollama#4505]
### What is the issue?

sudo curl -fsSL https://ollama.com/install.sh | sh
>>> Downloading ollama...
######################################################################## 100.0%######################################################################### 100.0%
>>> Installing ollama to /usr/local/bin...
>>> Adding ollama user to render group...
>>> Adding ollama user to video group...
>>> Adding current user to ollama group...
>>> Creating ollama systemd service...
>>> Enabling and starting ollama service...
sh: linha 252: VERSION_ID: variável não associada

### OS

Linux

### GPU

Nvidia

### CPU

Intel

**Comment by dhiltgen** [comment]
What linux distro are you running?   Can you share the contents of your `/etc/os-release` file?  If that file doesn't exist, is there another file in `/etc` that contains the OS settings?  For example, on Ubuntu I see
```
% cat /etc/os-release
PRETTY_NAME="Ubuntu 22.04.4 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.4 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
```

**Comment by mfahampshire** [comment]
This also happened to me. Running Debian12. Contents of `/etc/os-release`: 

```
       │ File: /etc/os-release
   1   │ PRETTY_NAME="Debian GNU/Linux trixie/sid"
   2   │ NAME="Debian GNU/Linux"
   3   │ VERSION_CODENAME=trixie
   4   │ ID=debian
   5   │ HOME_URL="https://www.debian.org/"
   6   │ SUPPORT_URL="https://www.debian.org/support"
   7   │ BUG_REPORT_URL="https://bugs.debian.org/"
```

**Comment by dhiltgen** [comment]
@mfahampshire Trixie is slated to be v13, but is in testing.  On a v12 debian VM, I see
```
% cat os-release
PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

It looks like Debian holds back on the VERSION_ID until they finalize the version number.  We use the version to populate the URL https://developer.download.nvidia.com/compute/cuda/repos/ and there's no debian13 yet.

We should have a more informative error message instead of an unbound variable, but at the moment, debian13 isn't supported by the official cuda drivers.

@aBaldoqui what distro/version are you running?  If it's not Debian 13/trixie, can you share the contents of your file?

**Comment by mfahampshire** [comment]
Apologies for the misinfo, I forgot I updated! :sweat_smile: not 100% linked to this conversation but just as an FYI the manual install instructions worked perfectly, so I'll stick to manual upgrades for the moment. Thanks!

**Comment by aBaldoqui** [comment]
Hi, sorry for the delay in responding, @dhiltgen 

NAME="Manjaro Linux"
PRETTY_NAME="Manjaro Linux"
ID=manjaro
ID_LIKE=arch
BUILD_ID=rolling
ANSI_COLOR="32;1;24;144;200"
HOME_URL="https://manjaro.org/"
DOCUMENTATION_URL="https://wiki.manjaro.org/"
SUPPORT_URL="https://forum.manjaro.org/"
BUG_REPORT_URL="https://docs.manjaro.org/reporting-bugs/"
PRIVACY_POLICY_URL="https://manjaro.org/privacy-policy/"
LOGO=manjarolinux

**Comment by dhiltgen** [comment]
It looks like Manjaro is derived from Arch, so these instructions are probably valid for the Driver install https://wiki.archlinux.org/title/NVIDIA

For installing Ollama, for now, you can use our manual instruction - https://github.com/ollama/ollama/blob/main/docs/linux.md#manual-install or possibly https://archlinux.org/packages/extra/x86_64/ollama/
