### ISSUE TITLE
I hope ollama completes my command input.

### ISSUE THREAD

**Issue by taozhiyuai** [ollama/ollama#4507]
I hope ollama completes my command input.

for example below,, I hope when I press TAB button, ollama complete 'qwen:32b-chat-v1.5-q8_0 '

thanks.

`taozhiyu@192 ~ % ollama list

NAME                                    	ID          	SIZE 	MODIFIED       

qwen:32b-chat-v1.5-q8_0                 	33c6cb647280	34 GB	3 days ago    	

llama3:70b-instruct-q8_0                	d6fa8cffc283	74 GB	4 days ago    	

taozhiyuai/openbiollm-llama-3:70b-q8_0  	881f678ac039	74 GB	8 days ago    	

taozhiyu@192 ~ % ollama run qwe`

**Comment by dhiltgen** [comment]
Completion support tracked with #1653
