### ISSUE TITLE
Would it be possible for Ollama to support re-rank models?

### ISSUE THREAD

**Issue by lyfuci** [ollama/ollama#4510]
I am using Ollama for my projects and it's been great. However, when using some AI app platform, like dify, build RAG app, rerank is nessesary. It's possible for Ollama to support rerank models.

**Comment by igorschlum** [comment]
@lyfuci Ollama only support OpenSource models. Before adding a model to Ollama, it is often available on Hunging Face.

**Comment by lyfuci** [comment]
sorry, just set a typo, reranker->rerank. reranker model means a model input some sentences and a query, output a list of similarity.
There is some reranker model on Hugging Face, like [bge-reranker-v2-m3](https://huggingface.co/BAAI/bge-reranker-v2-m3),[jina-reranker-v1-base-en](https://jina.ai/reranker/) etc.

**Comment by edisonzf2020** [comment]
+1

**Comment by jerryandjune** [comment]
+1

**Comment by yushengliao** [comment]
+1

**Comment by raccoonex** [comment]
Please, add reranking models to Ollama. 🥺

**Comment by fff196** [comment]
+1

**Comment by rjmalagon** [comment]
rerank and colbert would be wonderful, compliment embedding nicely on RAG.
Good open models exist
https://huggingface.co/mixedbread-ai/mxbai-rerank-large-v1
https://huggingface.co/mixedbread-ai/mxbai-colbert-large-v1
Does llama.cpp support this?

**Comment by rjmalagon** [comment]
I bring this as an idea on llama.cpp discussions.
https://github.com/ggerganov/llama.cpp/discussions/8216

**Comment by lucasdengcn** [comment]
+1

**Comment by queentrapwatchout** [comment]
+ 1

**Comment by akan** [comment]
+1

**Comment by hongliangdu** [comment]
+1

**Comment by springrain** [comment]
+1

**Comment by Zakinator123** [comment]
+1

**Comment by jmorganca** [comment]
Merging with https://github.com/ollama/ollama/issues/3368

**Comment by Kraego** [comment]
+1

**Comment by bruno-oliveira** [comment]
Any updates on this?

**Comment by cope** [comment]
Check #3749

Also: https://ollama.com/search?q=rerank

**Comment by netandreus** [comment]
Unfortunatelly, this models cant work without API support fropm Ollama.

**Comment by brightleo** [comment]
Will Ollama support it in the future? We need support for the renank model.

**Comment by Rakhsan** [comment]
HEll yeah pls do the thing. I need rerank models ASAP!

**Comment by Yak0vkaSup** [comment]
+1

**Comment by alekhed** [comment]
+1

**Comment by Frank995** [comment]
+1

**Comment by albulacan** [comment]
+1

**Comment by StanleyMXY** [comment]
+1

**Comment by adrianwysocki1993** [comment]
+1

**Comment by Leon371** [comment]
+1

**Comment by virdb** [comment]
+1

**Comment by like-a-bause** [comment]
+1

**Comment by torcoste** [comment]
+1

**Comment by ytfrdfiw** [comment]
+1

**Comment by fernvenue** [comment]
+1

**Comment by rowstop** [comment]
+1

**Comment by Doc-Robert** [comment]
+1

**Comment by Rakhsan** [comment]
thing ain't even fixed why is this closed and everyone spamming +1

**Comment by rjmalagon** [comment]
The llama.cpp project supports reranrikng, maybe it is not a priority for the Ollama project, but someone can offer the missing code to enable this.
```
# use the /reranking endpoint
llama-server -m model.gguf --reranking
```

**Comment by ytfrdfiw** [comment]
> The llama.cpp project supports reranrikng, maybe it is not a priority for the Ollama project, but someone can offer the missing code to enable this.
> 
> ```
> # use the /reranking endpoint
> llama-server -m model.gguf --reranking
> ```

Is this true? Have you done any performance or burn-in testing?  thank you!

**Comment by rjmalagon** [comment]
> > The llama.cpp project supports reranrikng, maybe it is not a priority for the Ollama project, but someone can offer the missing code to enable this.
> > ```
> > # use the /reranking endpoint
> > llama-server -m model.gguf --reranking
> > ```
> 
> Is this true? Have you done any performance or burn-in testing? thank you!

I did not test it, my particular choice for reranker model use (jina-colbert-v2) is not enterely vainilla transformers and I suppose it will not work on llama.cpp, it seems too much effort to integrate the llama.cpp server for reranking on my mostly ollama pipeline to test it. But I think it is a first step that llama.cpp offer any reranking model support. 

I use heavy embedding models (7B), slow but fortunately GPU accelerated by ollama, CPU reranking is just a little bottleneck for now for me.

**Comment by ytfrdfiw** [comment]
> > > The llama.cpp project supports reranrikng, maybe it is not a priority for the Ollama project, but someone can offer the missing code to enable this.
> > > ```
> > > # use the /reranking endpoint
> > > llama-server -m model.gguf --reranking
> > > ```
> > 
> > 
> > Is this true? Have you done any performance or burn-in testing? thank you!
> 
> I did not test it, my particular choice for reranker model use (jina-colbert-v2) is not enterely vainilla transformers and I suppose it will not work on llama.cpp, it seems too much effort to integrate the llama.cpp server for reranking on my mostly ollama pipeline to test it. But I think it is a first step that llama.cpp offer any reranking model support.
> 
> I use heavy embedding models (7B), slow but fortunately GPU accelerated by ollama, CPU reranking is just a little bottleneck for now for me.

ok! I got it

**Comment by dannyxu2015** [comment]
+1

**Comment by KinXdle** [comment]
+1

**Comment by gelonsoft** [comment]
+1

**Comment by rjmalagon** [comment]
Mixedbread AI released their Qwen2 based rerankers, mxbai-rerank-base-v2 and mxbai-rerank-large-v2.
https://huggingface.co/mixedbread-ai/mxbai-rerank-base-v2
https://huggingface.co/mixedbread-ai/mxbai-rerank-large-v2
I think these high quality rerankers are supported by llama.cpp

**Comment by sean-liang** [comment]
+1

**Comment by RedamancyJ** [comment]
+1

**Comment by lilozz2** [comment]
+1

**Comment by jagga99** [comment]
+1

**Comment by bennos1911** [comment]
+1

**Comment by boscar** [comment]
+1

**Comment by CheinTian** [comment]
+1

**Comment by JeeLin** [comment]
+1

**Comment by malaki12003** [comment]
+1

**Comment by ArnaudPannatier** [comment]
+1

**Comment by ypotsiah** [comment]
+1

**Comment by ufosaga** [comment]
+1

**Comment by ptemnorusov** [comment]
+1

**Comment by MarSchra** [comment]
+1

**Comment by sinjab** [comment]
+1

**Comment by Teayyyy** [comment]
+1

**Comment by HardenGale** [comment]
+1

**Comment by xiexin36** [comment]
+1

**Comment by dengxifeng** [comment]
+1

**Comment by Gwada** [comment]
+1

**Comment by yen936** [comment]
+1

**Comment by TaylorPzreal** [comment]
+1

llama.cpp supported.
download and start server
`llama-server -hf model.GGUF --reranking`

**Comment by zanyar3** [comment]
+1

**Comment by Gwada** [comment]
+1
