### ISSUE TITLE
ollama run codellama:34b issue

### ISSUE THREAD

**Issue by Iliceth** [ollama/ollama#4519]
### What is the issue?

Every model I tested with ollama runs fine, but when trying: `ollama run codellama:34b`, I get `Error: llama runner process has terminated: signal: segmentation fault (core dumped)`Tried the 13B-version then, works fine.

### OS

Linux

### GPU

Nvidia

### CPU

Intel

### Ollama version

0.1.37

**Comment by izzy84** [comment]
same here

**Comment by jmorganca** [comment]
So sorry about this, looking into why this is happening.

**Comment by jonz-secops** [comment]
same

**Comment by barrard** [comment]
I'm also getting this on 7b-python and 13b-python

**Comment by dhiltgen** [comment]
Could you share your server log, and your VRAM size?  This is a larger model, so my suspicion is we're off on our memory prediction.

**Comment by 9SMTM6** [comment]
Same here.

AMD CPU in contrast to OP.

16 GB VRAM (RTX 4070 Ti Super)

Log attached.
[codellama_crashdump_shortend.log](https://github.com/ollama/ollama/files/15419278/codellama_crashdump_shortend.log)

**Comment by jonz-secops** [comment]
To add details .. 

AMD 5950X on x570E
32 GB CPU RAM

6900XT
16GB VRAM

server log; doesn't appear to have the events in it anymore, but I'll try and recreate later today if I can.

**Comment by Iliceth** [comment]
Hereby my log. 

[ollama_logs.txt](https://github.com/ollama/ollama/files/15420085/ollama_logs.txt)

I can run Mixtral and dolphin-mixtral fine and those are some big ones too.

Anyhow my current system is i5-9700K + 32 GB RAM + RTX 3090 with 24 GB VRAM

**Comment by izzy84** [comment]
I7 7700K with 32gb ram and 6 GPUs with in total 51gb vram.

I can run all models, even llama3:70b without problems, which is already a big model. But I get error with codellama 34b

**Comment by FukangSun** [comment]
same here .  E5-2670 + 96gb ram + 1 RTX 4090 . also get below error when running codellama 34b : 
ollama run codellama-34b-instruct:Q4_K_M
Error: llama runner process has terminated: signal: segmentation fault (core dumped)

**Comment by AZ777xx** [comment]
same. Phind-codellama from the repository works, loading gguf doesn't though

**Comment by Iliceth** [comment]
Did upgrade to 0.1.41 in the meantime, but the problem persists.

**Comment by Iliceth** [comment]
@jmorganca Is there any insight yet on what goes wrong? I upgraded to 0.1.44 today, but still no luck. The info @FukangSun provided might be helpful, in that the latest version without this issue seems to have been 0.1.32 for people who experience this problem.

**Comment by Pomyk** [comment]
I compiled from source and it works now.

**Comment by dhiltgen** [comment]
I've also confirmed that the latest llama.cpp bump has picked up a fix from upstream that resolves this in 0.1.45.  (0.1.44 was still broken)
