### ISSUE TITLE
llama3:70B  pull error

### ISSUE THREAD

**Issue by DimIsaev** [ollama/ollama#4520]
### What is the issue?

![image](https://github.com/ollama/ollama/assets/11172642/999167fc-a6d3-4833-999c-ece170007074)

`Error: max retries exceeded: unexpected EOF`

### OS

Linux

### GPU

Nvidia

### CPU

Intel

### Ollama version

0.1.33

**Comment by kha84** [comment]
Is it just one off thing? Have you tried to restart it?
To me it looks like you might have some network issues. Or ollama "model registry" might have them.

But I also agree that ollama should have handled such issues better, and try to resume the download number of times before giving up, especially when we're speaking about downloading some massive files. It will be very disappointing to get this error at 99% without an option to resume, when you have to start over again from 0% :)

**Comment by sammcj** [comment]
I think the model registry might be a bit hosed, I can't pull any models as am getting the same error.

Might be related to https://github.com/ollama/ollama/issues/1736#issuecomment-2119237940

**Comment by kha84** [comment]
By any chance aren't you behind any PROXY or VPN?

**Comment by sammcj** [comment]
> By any chance aren't you behind any PROXY or VPN?

Nope.
Tested on 3 machines and on two different internet connections.

**Comment by sammcj** [comment]
Ooo see also https://github.com/ollama/ollama/issues/1036

**Comment by DimIsaev** [comment]
> Is it just one off thing? Have you tried to restart it? To me it looks like you might have some network issues. Or ollama "model registry" might have them.
> 
Yes 3 Attemps

**Comment by coder543** [comment]
I'm hitting this issue repeatedly with several llama3 models. The registry definitely seems like it needs a little help.

**Comment by sammcj** [comment]
Yeah it seems the registry has been completely broken for almost a week now. I’ve pretty much given up on it and now build all my models myself which is ok but kind of negates one of the primary benefits of ollama.

**Comment by sammcj** [comment]
@jmorganca do you know what’s going on here? Is there a discussion thread we should be following / contributing to?

**Comment by sammcj** [comment]
Actually - this looks to be in an improved state this morning, perhaps a fix was made?

**Comment by coder543** [comment]
I just tested again, and I'm still seeing the issue. on `llama3:8b-instruct-q8_0`.

**Comment by DimIsaev** [comment]
yes the problem remains

**Comment by ahoepf** [comment]
yes, have the same problem

**Comment by hug0b** [comment]
This was caused by a company VPN for me, it works when using a personal network without a VPN

**Comment by coder543** [comment]
I tried again this morning, and it still could not download. So, I tried completely removing `/usr/share/ollama` and reinstalling ollama. Now, it was able to successfully download and install, which makes me think there could be some bug in `ollama` itself that is corrupting the local cache.

**Comment by coder543** [comment]
Well... I picked an older release at random (0.1.35), and now it is able to successfully download models that 0.1.39 was unable to download. I have not tried to pinpoint the exact release that introduced this serious bug, but I'd say it was probably in the past week.

Not being able to download models reliably will make ollama extremely painful to use and remove most of its value. If this isn't a high priority issue for the project, then I don't know what would be.

For the moment, I'm working around the issue by downloading an old release of ollama and using that to pull models, which isn't great.

**Comment by DimIsaev** [comment]
```
pulling manifest
pulling 0bd51f8f0c97...  29% ▕█████████████████████                                                     ▏  11 GB/ 39 GB  2.7 MB/s   2
Error: max retries exceeded: Get "https://dd20bb891979d25aebc8bec07b2b3bbc.r2.cloudflarestorage.com/ollama/docker/registry/v2/blobs/s/0b/0bd51f8f0c975ce910ed067dcb962a9af05b77bafcdc595ef02178387f10e51d/data?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=66040c77a7c3af820529859349a%!F(MISSING)20240530%!F(MISSING)auto%!F(MISSING)s3%!F(MISSING)aws4_request&X-Amz-Date=20240530T155259Z&X-Amz-Expire0&X-Amz-SignedHeaders=host&X-Amz-Signature=dd62ec94899015534ce1d7e7ecf720685ff06b5a7687e53b3d219ddb657e56cc": net/http: TLS handshakeout

```

will the problem be solved?

**Comment by DimIsaev** [comment]
up

**Comment by rampageservices** [comment]
This yet to be pulled PR may help some of those here facing EOF issues:
#4625

**Comment by sandy124356** [comment]
in my case:
its the firewall thats blocking pulling of some images.. and leads to "Error: max retries exceeded: EOF"
And it happens after the manifest is pulled and after some 10-20% of main files..

How i figured:
Latest version of ollama windows desktop is hiding this firewall error everywhere (not even found in system/server logs)
I tried installing older version, 0.5 ? or something..
It showed the error: "your zscalar is not allowing me to download from this site blah blah blah"

**Comment by yifan0011** [comment]
> By any chance aren't you behind any PROXY or VPN?

Hi, I am behind the company proxy and having the exact same problem: 

U:\>ollama pull mistral
pulling manifest
pulling ff82381e2bea...   0% ▕                                                        ▏    0 B/4.1 GB
Error: max retries exceeded: EOF

Have you had a solution?

**Comment by OnlyRen** [comment]
> Have you had a solution?

I just walked around the issue by running the same command repeatedly. It will keep resuming so your progress is save.
