### ISSUE TITLE
GGUF imported model crashes only in v0.1.38

### ISSUE THREAD

**Issue by mindspawn** [ollama/ollama#4523]
### What is the issue?

heegyu/EEVE-Korean-Instruct-10.8B-v1.0-GGUF worked in all prior versions of ollama. Since v0.1.38 it core dumps.
I have temporarily reverted to v0.1.37 to resolve the issue. Any help is appreciated.

### OS

Linux

### GPU

Nvidia

### CPU

Intel

### Ollama version

0.1.38

**Comment by pdevine** [comment]
@mindspawn Can you attach the logs and the Modelfile? Also, do you have a link to the gguf binary, or did you convert it yourself?

**Comment by mindspawn** [comment]
> @mindspawn Can you attach the logs and the Modelfile? Also, do you have a link to the gguf binary, or did you convert it yourself?

I used the f16 version from here: https://huggingface.co/heegyu/EEVE-Korean-Instruct-10.8B-v1.0-GGUF/tree/main

For Modelfile, all I have in it is FROM ./ggml-model-f16.gguf

Unfortunately, it is deployed in an environment where I am unable to pull log files from. I have been using at least the last 4-5 versions of ollama with no issues. Great application by the way :)

**Comment by joshyan1** [comment]
Hey @mindspawn, does this issue still seem to happen for you? I can't seem to reproduce it on the latest version on Mac. If it is happening, could you clarify what steps you take before the issue occurs?

**Comment by mindspawn** [comment]
> Hey @mindspawn, does this issue still seem to happen for you? I can't seem to reproduce it on the latest version on Mac. If it is happening, could you clarify what steps you take before the issue occurs? 

Hi @joshyan1 thanks for following up. Unfortunately I've transitioned to vllm since and itay be a while before I cam verify this again. Perhaps we cancel the issue for now?

**Comment by joshyan1** [comment]
> > Hey @mindspawn, does this issue still seem to happen for you? I can't seem to reproduce it on the latest version on Mac. If it is happening, could you clarify what steps you take before the issue occurs?
> 
> Hi @joshyan1 thanks for following up. Unfortunately I've transitioned to vllm since and itay be a while before I cam verify this again. Perhaps we cancel the issue for now?

Hey @mindspawn, okay thanks. Feel free to open up this issue again if you experience it.
