### ISSUE TITLE
OLLAMA_MODELS no longer works

### ISSUE THREAD

**Issue by asmrtfm** [ollama/ollama#4528]
### What is the issue?

setting the OLLAMA_MODELS environment variable no longer works.

so I tried making /usr/share/ollama/.ollama a symlink to ~/.ollama
and noticed that ollama errors out because it tries to run `mkdir` on every run...
if it simply used `mkdir -p` instead of `mkdir` then this would not be an issue.

### OS

Linux

### GPU

Nvidia

### CPU

Intel

**Comment by dhiltgen** [comment]
Can you share the server log?  This sounds like it might be a permission problem.
