### ISSUE TITLE
Ctrl+Backspace doesn't delete full words in `ollama run ...` mode

### ISSUE THREAD

**Issue by DeflateAwning** [ollama/ollama#4534]
### What is the issue?

In `ollama run <model>` mode, pressing Ctrl+Backspace should delete a whole word backwards. 

To implement this, "listen" for "Ctrl+H" presses (as that's what Ctrl+Backspace is sent as)

### OS

Linux

### Ollama version

0.1.38

**Comment by joshyan1** [comment]
Hey @DeflateAwning, Ctrl + Backspace (Ctrl + H) maps to just Backspace in Ollama. If you want to delete the previous word, please use Ctrl + W which should already implemented. I've added documentation of the shortcut in /? shortcuts

**Comment by DeflateAwning** [comment]
Makes sense, thanks! Any reason not to have both act as a backspace?

**Comment by joshyan1** [comment]
Sorry, can you clarify which two you're referring to? Currently Ctrl + W removes the previous word and Ctrl + H is a backspace. As you said, Ctrl + Backspace is received as Ctrl + H so Ctrl + Backspace is simply a backspace as well.

**Comment by DeflateAwning** [comment]
Ctrl+H gets sent when you press Ctrl+Backspace in most terminals (at least in my experience) though. Ctrl+Backspace (which is sent as Ctrl+H) should remove an entire word.

**Comment by joshyan1** [comment]
Thanks for the feedback. Ctrl + W is generally used in terminal based applications for this shortcut so we've decided to use it as well.

**Comment by pdevine** [comment]
I'm sorta torn here because generally speaking Ctrl-H is backspace. Ctrl-Backspace will do a Ctrl-W in most desktop programs, but it doesn't do that in my terminal and just maps to Ctrl-H by default.

**Comment by DeflateAwning** [comment]
Hmm, have never seen that behaviour, but have also not really done any low-level key handling outside of terminals and terminal UIs.
