### ISSUE TITLE
Error: no safetensors or torch files found

### ISSUE THREAD

**Issue by SreeHaran** [ollama/ollama#4538]
### What is the issue?

I'm trying to create model using Modelfile. My Modefile looks same as the example given
```
FROM llama3

# set the temperature to 1 [higher is more creative, lower is more coherent]
PARAMETER temperature 1

# set the system message
SYSTEM """
You are Mario from Super Mario Bros. Answer as Mario, the assistant, only.
"""
```
But when I execute it, it throws error. saying "Error: no safetensors or torch files found"
![image](https://github.com/ollama/ollama/assets/62993067/2d70ff63-2d11-4c56-b733-dd7c72bc7279)

I tried the same with ```FROM llama2-uncensored``` in the Modelfile that seems to work fine.

other commands like ```ollama run llama3``` are working properly.

### OS

Windows

### GPU

Nvidia

### CPU

Intel

### Ollama version

0.1.38

**Comment by mxyng** [comment]
Do you perhaps have a `llama3` directory under `C:\AI-models`? It seems `ollama create` is getting confused between that directory and the upstream `llama3` model

**Comment by SreeHaran** [comment]
Yes, there was a directory named `llama3` under the `C:\AI-models`. After renaming that directory to something else, I could able to create the model using Modelfile
