### ISSUE TITLE
"ollama is not running" issue after changing the host ip

### ISSUE THREAD

**Issue by hknatm** [ollama/ollama#4540]
### What is the issue?

when first start everything is normal. After I change host address to 192.168.1.10:11434 from /etc/systemd/system/ollama.service by adding environment, I put "ollama pull [model]" it throws an error : "Error: could not connect to ollama app, is it running?" but when I curl that IP that I changed, it shows running and I can use it from my OpenWebUI with the new IP. If I erase that new host ip from config file and reboot the server I can pull new models (but host ip changes to localhost:11434). What is the issue with that, how to resolve it?

### OS

Linux

### GPU

Nvidia

### CPU

Intel

### Ollama version

0.1.38

**Comment by dhiltgen** [comment]
Can you clarify what you have OLLAMA_HOST set to on the client?  By setting OLLAMA_HOST on the server to a specific IP address, it should only listen on that address, and the client will not be able to access it over localhost (127.0.0.1) but must use the same IP address the server is listening to.  Another possible server setup is 0.0.0.0:11434, which will tell the server to bind to all interfaces, but you should be careful about exposing ollama to untrusted users/networks.

**Comment by OpenCoderX** [comment]
Same error when setting 0.0.0.0 as OLLAMA_HOST.

systemctl logs show that it is listening on the configured IP but running ollama list shows the error.

ollama list works without error when there is no OLLAMA_HOST set in the systemctl service file. version 0.1.38

**Comment by dhiltgen** [comment]
@hknatm I haven't been able to reproduce your failure.  I think your OLLAMA_HOST values aren't set correctly in the client and server.  

In one terminal
```
% export OLLAMA_HOST=10.16.0.127:11434
% ollama serve
```

In another terminal:
```
% export OLLAMA_HOST=10.16.0.127:11434
% ollama pull gemma2
pulling manifest
...
```

From what you're describing, I think you forgot to set the OLLAMA_HOST in the terminal where you're running `ollama pull` which means it is defaulting to 127.0.0.1:11434, but your server is NOT listening on localhost, it's listening on your designated IP.


@OpenCoderX I'm not following your scenario.  For the server, setting 0.0.0.0 will bind to ALL addresses on the host, not a single address.

In one terminal:
```
% export OLLAMA_HOST=0.0.0.0:11434
% ollama serve
```

In another terminal
```
% unset OLLAMA_HOST
% ollama pull gemma2
pulling manifest
...
```

**Comment by S-Azimi** [comment]
I have the same issue. it works on localhost but when changing the localhost to a local ip address, 
sudo netstat -tuln | grep 11434

shows that it listens to the local ip, but it does there is no response on post requests.

**Comment by hitribgit** [comment]
[gojo-limitless-color-theme.json](https://github.com/user-attachments/files/28685490/gojo-limitless-color-theme.json)

**Comment by hknatm** [comment]
I dont remember my issue but I think it was an environment issue at that time.
