### ISSUE TITLE
Ollama reload same model when called in different python scripts

### ISSUE THREAD

**Issue by x66ccff** [ollama/ollama#4541]
### What is the issue?

I am running the qwen:32b model on dual RTX A6000 GPUs (48GB each). There seems to be sufficient VRAM available, with cuda0 using 21GB and cuda1 using less than 5GB. According to the logs, all layers of the model have been loaded onto the GPUs.

When I call the ollama library in a single Python script, it works as expected. However, when I try to call ollama from two different Python scripts simultaneously, both requiring the same qwen:32b model, ollama appears to be reloading the same model repeatedly for each API call from the different scripts. I'm puzzled as to why this behavior is occurring.

### OS

Windows

### GPU

Nvidia

### CPU

Intel

### Ollama version

0.1.36

**Comment by pdevine** [comment]
@x66ccff can you try updating to ollama `0.1.38`?
