### ISSUE TITLE
GUI for ollama mac app

### ISSUE THREAD

**Issue by robot-penguin34** [ollama/ollama#4550]
Ollama has so much potential to be the best virtual assistant, but it doesn't have a built in gui for those who don't plan to host this through the network. 

**Please add an option during the setup wizard to enable the gui and add one.**

**Comment by matthewchung74** [comment]
i use this https://github.com/open-webui/open-webui

**Comment by robot-penguin34** [comment]
I use that too, but I am thinking of more of a built in option for like an unsecured network, and easier for new users to get into and see the potential

**Comment by dhiltgen** [comment]
Hi there! check out some of these awesome Desktop (and/or Web) apps that run great with Ollama: https://github.com/ollama/ollama?tab=readme-ov-file#web--desktop

**Comment by robot-penguin34** [comment]
Thanks!  That is exactly what I was hoping for.
