### ISSUE TITLE
rm command dont delete files

### ISSUE THREAD

**Issue by milenamilka755** [ollama/ollama#4559]
### What is the issue?

ollama version is 0.1.38

I use rm command and
the model was deleted from the list of available models, but the associated sha256 files from the 
ollama\models\blobs directory were not deleted.
I had to delete the files manually.

### OS

Windows

### GPU

Nvidia

### CPU

AMD

### Ollama version

0.1.38

**Comment by pdevine** [comment]
@milenamilka755 If any parts of the model are being shared with a different model the blobs won't be cleaned up.

**Comment by milenamilka755** [comment]
> @milenamilka755 If any parts of the model are being shared with a different model the blobs won't be cleaned up.

It seems to me that this is not the case because it was not some small piece, but more than 4GB file with the main model.

**Comment by pdevine** [comment]
@milenamilka755 hmm... I'll keep poking around here to see if I can find something.

**Comment by dhiltgen** [comment]
I haven't been able to reproduce.  @milenamilka755 are you still seeing this behavior on the latest version of Ollama?  Can you share a repro scenario (what models did you have, and what model did you remove)?

**Comment by pdevine** [comment]
I think we can probably close this for now, but we can reopen it if there's a way to reproduce.
