### ISSUE TITLE
Is llava license correct (possibly should be Llama2 not Apache)?

### ISSUE THREAD

**Issue by asmith26** [ollama/ollama#4561]
Looking at the llava ollama page, it lists the license as Apache: https://ollama.com/library/llava
![image](https://github.com/ollama/ollama/assets/6988036/93fe2d16-6ad4-482f-bc47-ab6b3296d236)

Looking at the link to huggingface, it implies it's possibly Llama 2: https://huggingface.co/liuhaotian/llava-v1.5-7b#license

Not sure if @haotian-liu may be also help clarify things also? 

Thanks!

**Comment by jmorganca** [comment]
Thanks! Will fix this
