### ISSUE TITLE
Clear session context via API

### ISSUE THREAD

**Issue by atalw** [ollama/ollama#4564]
It's possible in interactive mode using `/clear`. Would be good to have via the API too.

**Comment by pdevine** [comment]
Hi @atalw the API does not hold the context. It's entirely held in the client and passed to the server for each request. To get the same functionality:
* for `/api/generate` don't pass back the old `prompt`; and
* for `/api/chat` don't pass back the old `messages` array

**Comment by mdhuzaifapatel** [comment]
> Hi @atalw the API does not hold the context. It's entirely held in the client and passed to the server for each request. To get the same functionality:
> 
> * for `/api/generate` don't pass back the old `prompt`; and
> * for `/api/chat` don't pass back the old `messages` array

Hi, can you please let me know how to send context in current api call. I mean I want to implement the exactly opposite of what you are saying in this answer. 
Pls help me out I'm unable to use context parameter. If possible pls provide a code example 
Thanks.

**Comment by mdhuzaifapatel** [comment]
Can you guys please tell me (if possible with a code example) how to use context (list of numbers) which we get from current response in next response? 

Everytime I'm hitting Ollama API it's generating general answers, not related to the conversation history, I mean, I think it's not using previous responses context . 
Please help me out 
Thanks
