### ISSUE TITLE
OLLAMA_NUM_PARALLEL problem

### ISSUE THREAD

**Issue by marxy** [ollama/ollama#4569]
### What is the issue?

![企业微信截图_17163461556090](https://github.com/ollama/ollama/assets/12171912/6ab3b3b7-2a18-4887-b4c7-67af4cd5eef4)
When I set the OLLAMA_NUM_PARALLEL=3 environment parameter, I found an exception on multi-threaded requests in a single model, as shown in the figure.
![企业微信截图_17163461339124](https://github.com/ollama/ollama/assets/12171912/5adeb5e1-bdc6-41aa-b427-9f7b467aaaeb)
At the same time, I also found abnormal output in the log, is this a model's problem or a problem of multi-threaded requests?

### OS

Linux

### GPU

Nvidia

### CPU

Intel

### Ollama version

0.1.38

**Comment by ITHealer** [comment]
How to set env to run parallel in linux?
I had set up env by:

sudo nano ~/.bashrc
export OLLAMA_NUM_PARALLEL=4
source ~/.bashrc

But it doesn't work

**Comment by marxy** [comment]
> How to set env to run parallel in linux? I had set up env by:
> 
> sudo nano ~/.bashrc export OLLAMA_NUM_PARALLEL=4 source ~/.bashrc
> 
> But it doesn't work

If you use systemctl command to start ollama service, you can fllow this guide to add environment parameter. 
https://github.com/ollama/ollama/blob/main/docs/linux.md#adding-ollama-as-a-startup-service-recommended

**Comment by zhaowei0315** [comment]
When I use OLLAMA_NUM_PARALLEL=4 OLLAMA_MAX_LOADED_MODELS=4 ollama serve
Ollama responses so slow. how to fix it?

**Comment by AndyX-Net** [comment]
> When I use OLLAMA_NUM_PARALLEL=4 OLLAMA_MAX_LOADED_MODELS=4 ollama serve Ollama responses so slow. how to fix it?
Excessive PARALLEL might cause parts of the LLM to be split onto CPU load. Inspect your ollama logs, or check if the CPU usage significantly increases when issues occur.

**Comment by dhiltgen** [comment]
Concurrency is enabled by default in 0.2.0 and up.  If no parallel setting is provided, we'll try to load with 4 as long as that doesn't cause the model to spill over into CPU.  If the model wont fit fully in GPU, then we'll fall back to 1 parallel.

More details at https://github.com/ollama/ollama/blob/main/docs/faq.md#how-does-ollama-handle-concurrent-requests

**Comment by JedrzejMajko** [comment]
It's not working. Windows 11 with one model and 32 concurrent workers - 1% GPU used, 98% GPU memory taken.
It's broken.

**Comment by dhiltgen** [comment]
@JedrzejMajko please go ahead and file a new issue and describe your setup.  Please include server logs as well.  (my suspicion would be the model isn't fully loaded on the GPU and you're CPU bound, but the logs will help show what's going on.)
