### ISSUE TITLE
Model request for Video-LLaVA

### ISSUE THREAD

**Issue by prane-eth** [ollama/ollama#4575]
Video-LLaVA is a new multi-modal model that can accept images and videos as input.

https://github.com/PKU-YuanGroup/Video-LLaVA

**Comment by silasalves** [comment]
@prane-eth Please check #3184 for updates on that. =)

**Comment by ixn3rd3mxn** [comment]
> @prane-eth Please check #3184 for updates on that. =)

bro i think it have bug

**Comment by prane-eth** [comment]
> > @prane-eth Please check #3184 for updates on that. =)
> 
> bro i think it have bug

I hope you will create a new Issue for that.

**Comment by ixn3rd3mxn** [comment]
> > > @prane-eth Please check #3184 for updates on that. =)
> > 
> > 
> > bro i think it have bug
> 
> I hope you will create a new Issue for that.
sure
We can only hope someone will port VideoLLaVA to Ollama, haha!
