### ISSUE TITLE
请求超时 - Request Timeout

### ISSUE THREAD

**Issue by Pobby321** [ollama/ollama#4587]
### What is the issue?

我在请求时，可能content较长，大概2000多个字符，请求一直没返回，也不报错
  response = ollama.chat(model='qwen1.5-14b-sft-q5_k_m', messages=[
  {
      'role': 'user',
      'content': content
          },
  ])

### OS

Linux

### GPU

Nvidia

### CPU

Intel

**Comment by SKilometer** [comment]
请问你解决了吗，我也遇到这样的问题，显存不释放，但是gpu利用率为0%，

**Comment by dhiltgen** [comment]
Please try updating to the latest release and if you're still seeing timeouts, please share your server log so we can see if there's an error on the backend.
