### ISSUE TITLE
Tool calling feature support

### ISSUE THREAD

**Issue by Goekdeniz-Guelmez** [ollama/ollama#4588]
since there are more and more models that support function/tool calling. I think it would be a great feature for that support. It can be hard because the models could need Special tokens. My thought is that you can be able to set these spetial tokens or customizations in the Modelfile, something like:

```text
PARAMETER tool_calls_start ""
PARAMETER tool_calls_end ""
PARAMETER tool_results_start ""
PARAMETER tool_results_end ""
...
```

or (my preferred one):

```text
TOOL_CALLS """"[TOOL_CALLS] {response}"""
AVAILABLE_TOOLS """[AVAILABLE_TOOLS] {available tools list} [/AVAILABLE_TOOLS]"""
TOOL_RESULTS """[TOOL_RESULTS] {tool response} [/TOOL_RESULTS]""""
```

The API could be the same with OpenAI's or something different.

**Comment by jmorganca** [comment]
merging with https://github.com/ollama/ollama/issues/3137

**Comment by jmorganca** [comment]
Thank you for the issue 😊 !
