### ISSUE TITLE
How do I update all the models downloaded locally?

### ISSUE THREAD

**Issue by qzc438** [ollama/ollama#4589]
See title.

**Comment by coder543** [comment]
`ollama list | cut -f 1 | tail -n +2 | xargs -n 1 ollama pull` is a command I've used in the past... there's no built-in way.

**Comment by dhiltgen** [comment]
Tracked via #1717

**Comment by qzc438** [comment]
Thank you for the response.

**Comment by dhiltgen** [comment]
Most likely a typo in the pull command. What was the exact command you ran?
