### ISSUE TITLE
Phi-3 Vision

### ISSUE THREAD

**Issue by ddpasa** [ollama/ollama#4591]
Phi-3 is already supported, so I hope this should not be too difficult:

https://huggingface.co/microsoft/Phi-3-vision-128k-instruct

**Comment by Replikate648** [comment]
Is Phi-3-vision still have to be added in ollama?

**Comment by TadayukiOkada** [comment]
https://github.com/ggerganov/llama.cpp/issues/7444

**Comment by HaoHoo** [comment]
Looks like that llama.cpp convert HF to GGUF code can't support Phi3V yet.

**Comment by pdevine** [comment]
Going to close this as a dupe.

**Comment by levicki** [comment]
@pdevine Can you please clarify whether Phi3-vision is supported or not? If yes, what is the proper template for it?

**Comment by pdevine** [comment]
@levicki Unfortunately not yet. The dupe was to track it in #4560

**Comment by levicki** [comment]
> @levicki Unfortunately not yet. The dupe was to track it in #4560

Thanks for the clarification. I am confused as to what the problem is with supporting that model? There's also a newer version (3.5) that came out in the meantime. Didn't llama.cpp already add support for it? Or is there perhaps some other issue with it?
