### ISSUE TITLE
Mistral-7B instruct v3 FP16 Please

### ISSUE THREAD

**Issue by Donno191** [ollama/ollama#4592]
Mistral-7B instruct v3 FP16 Please - https://huggingface.co/mistralai/Mistral-7B-Instruct-v0.3/tree/main

**Comment by jmorganca** [comment]
Hi @Donno191 . Try this:

```
ollama run mistral:7b-instruct-v0.3-fp16
```

https://ollama.com/library/mistral:7b-instruct-v0.3-fp16
