### ISSUE TITLE
Error: llama runner process has terminated: signal: segmentation fault

### ISSUE THREAD

**Issue by guiniao** [ollama/ollama#4601]
### What is the issue?

ollama run codellama:34b

error occurred:

pulling manifest
pulling f36b668ebcd3... 100% ▕████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏  19 GB
pulling 2e0493f67d0c... 100% ▕████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏   59 B
pulling c60122cb2728... 100% ▕████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏  132 B
pulling d5981b4f8e77... 100% ▕████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏  382 B
verifying sha256 digest
writing manifest
removing any unused layers
success

Error: llama runner process has terminated: signal: segmentation fault

codellama:70b and codellama:13b successful

### OS

Linux

### GPU

Nvidia

### Ollama version

0.1.38

**Comment by jmorganca** [comment]
Sorry about this! Closing for [#codellama3b](https://github.com/ollama/ollama/issues/4333)

**Comment by Mozisword** [comment]
C:\Users\OMEN>ollama run ChatLaw-13B-Q8:latest Error: llama runner process has terminated: exit status 0xc0000409,But running other models works fine

**Comment by mhgrove** [comment]
I am seeing this as well, ubuntu 23.10. started happening after i updated ollama from 0.1.35 to 0.1.41. Every codellama:34b model i've tried (34b, 34b-code, 34b-instruct-34b-python, 34b-q8_0) core dumps when i attempt to use it. 13b works, 70b works. none of the 34s work.

**Comment by francesco-carrella** [comment]
Experiencing the exact same with codellama:34b model

**Comment by DigitalDevelooper** [comment]
Same with 34b models and 13b python model

**Comment by kim-gtek** [comment]
Same issue, any fix?
 error="llama runner process has terminated: signal: segmentation fault "
ollama 34B

**Comment by Enissay** [comment]
Same here!
```bash 
╰─ ollama run codellama:34b --verbose
Error: llama runner process has terminated: signal: segmentation fault (core dumped)
```
