### ISSUE TITLE
MiniCPM-Llama3-V 2.5

### ISSUE THREAD

**Issue by ycyy** [ollama/ollama#4606]
[https://github.com/OpenBMB/MiniCPM-V](MiniCPM-V)

> [2024.05.24] We release the [MiniCPM-Llama3-V 2.5 gguf](https://huggingface.co/openbmb/MiniCPM-Llama3-V-2_5-gguf), which supports [llama.cpp](https://github.com/OpenBMB/MiniCPM-V#inference-with-llamacpp) inference and provides a 6~8 token/s smooth decoding on mobile phones. Try it now!

**Comment by Cuiunbo** [comment]
+1

**Comment by coxfrederic** [comment]
Would be awesome to get this into Ollama!

**Comment by Fertony** [comment]
+1

**Comment by Cuiunbo** [comment]
https://github.com/OpenBMB/ollama Here is the fork for MiniCPM-Llama3-V 2.5
 @ycyy @Fertony @coxfrederic

**Comment by lingyezhixing** [comment]
This is the strongest visual model I've ever seen, and I'm really looking forward to using it on the ollama.

**Comment by microflyer** [comment]
It would be great if more vision models are supported. e.g. MiniCPM, Cogvlm2 and phi-3 vision.

**Comment by jmorganca** [comment]
Thanks for the issue! Closing for https://github.com/ollama/ollama/issues/4900
