### ISSUE TITLE
Ollama downloading wrong driver.

### ISSUE THREAD

**Issue by Murat-U-Saglam** [ollama/ollama#4616]
### What is the issue?

Ollama is downloading NVIDIA drivers even though I have AMD GPU.

I have ROCM installed 

```
apt show rocm-libs -a

Package: rocm-libs
Version: 6.1.1.60101-90~22.04
```
and I use the following script to setup [Ollama](https://ollama.com/download/linux)
` curl -fsSL https://ollama.com/install.sh | sh`

The output of running the script
```
curl -fsSL https://ollama.com/install.sh | sh
>>> Downloading ollama...
######################################################################## 100.0%##O=#  #                                                     ######################################################################## 100.0%
>>> Installing ollama to /usr/local/bin...
[sudo] password for ----: 
>>> Creating ollama user...
>>> Adding ollama user to render group...
>>> Adding ollama user to video group...
>>> Adding current user to ollama group...
>>> Creating ollama systemd service...
>>> Enabling and starting ollama service...
Created symlink /etc/systemd/system/default.target.wants/ollama.service → /etc/systemd/system/ollama.service.
>>> NVIDIA GPU installed.
```

### OS

Linux

### GPU

AMD

### CPU

AMD

### Ollama version

N/A

**Comment by dhiltgen** [comment]
This implies the startup script detected an NVIDIA device in your system.  Can you share the output of one or both of these commands?
```
lspci -d '10de:'
lshw -c display -numeric
```

**Comment by Murat-U-Saglam** [comment]
So when I ran the LSPCI and reinstalled it recognised the correct drivers. It also inadvertently updated my fastfetch (neofetch alternative) with the correct information. 

Thanks!
