### ISSUE TITLE
Extended lora support

### ISSUE THREAD

**Issue by AncientMystic** [ollama/ollama#4618]
Would it be possible to extend lora support so that they might be pulled like models and loaded with more ease such as with command 

Ollama run model adapter lora 

Or something similar for ease of use and easier mixing and matching using different loras with different models instead of having to hard code it into the model file of a model?

**Comment by pdevine** [comment]
@AncientMystic It won't look exactly like that, but this is something we've been actively looking at.

**Comment by pdevine** [comment]
I was thinking we could track the LoRA stuff here, but then realized there was a much older issue (#156) that first brought this up which is _still_ open, so let's track it there instead.
