### ISSUE TITLE
phi3-medium-128k wrong number of tensors 

### ISSUE THREAD

**Issue by EthanGraber** [ollama/ollama#4621]
### What is the issue?

I'm getting the following error when testing the new 128k versions of phi3-medium:

```sh
$ ollama run phi3:14b-medium-128k-instruct-q4_0
Error: llama runner process has terminated: signal: abort trap error:done_getting_tensors: wrong number of tensors; expected 245, got 243
```

```sh
$ ollama -v                                    
ollama version is 0.1.38
```

### OS

macOS

### GPU

Apple

### CPU

Apple

### Ollama version

0.1.38

**Comment by thinkverse** [comment]
0.1.38 doesn't support those versions of phi3. llama.cpp just added support for it a few days ago so you'll have to wait for Ollama 0.1.39 which has the updated backend. It is currently in pre-release, https://github.com/ollama/ollama/releases/tag/v0.1.39, so it should released soon I think. 👍
