### ISSUE TITLE
about model quantization

### ISSUE THREAD

**Issue by andyyumiao** [ollama/ollama#4626]
What are the quantization parameters used for the llama3 model in Ollama? For example, llama3 version, quantization parameters, etc
The llama3 8b version that I quantified using llama.cpp myself is not as good as the llama3 8b version that comes with Ollama, so I want to know the reason.

**Comment by umiyuki** [comment]
Conversely, Phi-3-medium is degraded in the ollama version. it has lower benchmark scores than Llama.cpp. several people have tried Phi-3-medium on ollama and found the performance to be poor. Why is this happening? Either the inference parameter settings or the chat template is wrong or something is broken in quantization.

**Comment by skye0402** [comment]
@umiyuki I found the 4K 14b model to be working quite well, the 128k 14b model definitely has problems. I used 6 bit quantization for both to compare with identical input.

**Comment by pdevine** [comment]
@andyyumiao the default is `Q4_0`, which you can see here:
<img width="776" alt="Screenshot 2024-05-28 at 13 33 02" src="https://github.com/ollama/ollama/assets/75239/a5c09e23-f853-4600-9326-4b62be121c21">
<img width="777" alt="Screenshot 2024-05-28 at 13 31 27" src="https://github.com/ollama/ollama/assets/75239/5fc036a5-c844-4dad-89ff-de5c1990ff58">

It's possible (and more likely) that your prompt template is off on the version that you converted yourself. I'll close out the issue.
