### ISSUE TITLE
granite-code:20b-instruct-q8_0  error loading model vocabulary: unknown pre-tokenizer type: 'refact'

### ISSUE THREAD

**Issue by ekolawole** [ollama/ollama#4629]
### What is the issue?

llama_model_loader: - type  f32:  419 tensors
llama_model_loader: - type q8_0:  209 tensors
llama_model_load: error loading model: error loading model vocabulary: unknown pre-tokenizer type: 'refact'
llama_load_model_from_file: exception loading model
libc++abi: terminating due to uncaught exception of type std::runtime_error: error loading model vocabulary: unknown pre-tokenizer type: 'refact'
time=2024-05-25T03:28:13.829-04:00 level=ERROR source=sched.go:344 msg="error loading llama server" error="llama runner process has terminated: signal: abort trap error:error loading model vocabulary: unknown pre-tokenizer type: 'refact'"
[GIN] 2024/05/25 - 03:28:13 | 500 |   446.67725ms |     | POST     "/v1/chat/completions"

### OS

macOS

### GPU

Apple

### CPU

Apple

### Ollama version

0.1.38

**Comment by nurena24** [comment]
getting the same error with granite-code:20b-instruct-q3_K_M model in docker desktop running on 4090 GPU

**Comment by wang-junjian** [comment]
Error: llama runner process has terminated: signal: abort trap error:error loading model vocabulary: unknown pre-tokenizer type: 'refact'

macOS 14.5
ollama version is 0.1.38

**Comment by BruceMacD** [comment]
Thanks for the report. As noted above this model (and other granite family models) will work in ollama v0.1.39+ now.
