### ISSUE TITLE
Runner process terminated

### ISSUE THREAD

**Issue by GouthamGuna** [ollama/ollama#4630]
Hello, 

While executing the `ollama run <model>` command,

Regarding `Error: llama runner process has terminated: exit status 0xc0000005`, I received a response.

I am not aware of the issue.

### OS

Windows

### GPU

Intel

### CPU

Intel

### Ollama version

0.1.38

**Comment by jmorganca** [comment]
Hi @GouthamGuna sorry this happened. May I ask which model you are running?

**Comment by GouthamGuna** [comment]
phi3

**Comment by Etrinque** [comment]
encountering this issue right now, No models run, see attached screenshots. 
downloaded llama 3.1 last night went to use ollama today (havent used in a few weeks) and getting the error

sys:
    Windows 11 current updates as of posting. 
    amd 7700x
    amd 7900xt

![aihuman](https://github.com/user-attachments/assets/2b1232db-9a59-4011-97e5-bb5e5e2f0bb8)

**Comment by Etrinque** [comment]
updated to pre-release Ollama 0.30 seems to be functional as of now.

**Comment by dhiltgen** [comment]
@Etrinque glad to hear it seems to be resolved in 0.3.0 for you.

@GouthamGuna please update to the latest version and let us know if you're still seeing the problem.  If so, please share your server log so we can try to understand why its crashing and I'll reopen the issue.

**Comment by GouthamGuna** [comment]
Yes, I will adhere to the sequence. Thank you, @dhiltgen and @Etrinque.
