### ISSUE TITLE
Problem while pulling some models

### ISSUE THREAD

**Issue by skrew** [ollama/ollama#4633]
### What is the issue?

While using the command `ollama pull aya:35b-23-q8_0`, downloading stuck to 98-99%
Tested multiple time

Then i've tested with 0.1.37 version, i can pull this model without problem

### OS

Linux

### GPU

Nvidia

### CPU

Intel

### Ollama version

0.1.39

**Comment by fabceolin** [comment]
same here

**Comment by noxer** [comment]
I suspect this is the same issue that was fixed here: https://github.com/ollama/ollama/pull/4619

**Comment by skrew** [comment]
Yep it's look like it's fixed in this commit. I'm closing this ticket

**Comment by adriens** [comment]
Hi guys, we're facing the same issue while trying to pull ph3 : any workaround ? We're running the latest `ollama` clent

**Comment by martinkozle** [comment]
> Hi guys, we're facing the same issue while trying to pull ph3 : any workaround ? We're running the latest `ollama` clent

I am guessing either use main branch or wait for a new release version.
