### ISSUE TITLE
Getting Weird Response

### ISSUE THREAD

**Issue by Yash-1511** [ollama/ollama#4634]
### What is the issue?

I am using ollama on Apple Mac M2 Ultra. i am getting same problem for past two days. i delete all my models, i uninstalled ollama and reinstall again and sometimes it will work and most of the times it will get some weird response. 

![ollama](https://github.com/ollama/ollama/assets/82636823/f3147791-c084-4093-967b-91a7c7d472da)

### OS

macOS

### GPU

Apple

### CPU

Apple

### Ollama version

0.1.38

**Comment by dhiltgen** [comment]
That is strange behavior.

I haven't been able to reproduce.  If you're still seeing this, please make sure to upgrade to the latest version, and if that doesn't clear it up, please share your server log and I'll reopen and try to figure out what went wrong.
