### ISSUE TITLE
windows gpu memory.available always be one value 

### ISSUE THREAD

**Issue by mofanke** [ollama/ollama#4637]
### What is the issue?

windows gpu memory.available always be one value , no matter how many model was loaded

### OS

Windows

### GPU

Nvidia

### Ollama version

0.1.38

**Comment by mofanke** [comment]
![1716620117668_568E211C-74B5-44a1-887B-B3DD1C1E6BBE](https://github.com/ollama/ollama/assets/54242816/589cc9aa-d503-48a3-a3c5-774657dc5886)

**Comment by mofanke** [comment]
[server.log](https://github.com/ollama/ollama/files/15443974/server.log)
here is my server log

**Comment by dhiltgen** [comment]
Tracked via #4599
