### ISSUE TITLE
What's happening?When I enter the Serve command.

### ISSUE THREAD

**Issue by SuzuKaO** [ollama/ollama#4641]
### What is the issue?

INFO server config env="map[OLLAMA_DEBUG:false OLLAMA_LLM_LIBRARY: OLLAMA_MAX_LOADED_MODELS:1 OLLAMA_MAX_QUEUE:512 OLLAMA_MAX_VRAM:0 OLLAMA_NOPRUNE:false OLLAMA_NUM_PARALLEL:1 OLLAMA_ORIGINS:[http://localhost https://localhost http://localhost:* https://localhost:* http://127.0.0.1 https://127.0.0.1 http://127.0.0.1:* https://127.0.0.1:* http://0.0.0.0 https://0.0.0.0 http://0.0.0.0:* https://0.0.0.0:*] OLLAMA_RUNNERS_DIR:C:\\Users\\***\\AppData\\Local\\Programs\\Ollama\\ollama_runners OLLAMA_TMPDIR:]"
time=2024-05-26T07:41:02.855+08:00 level=INFO source=images.go:704 msg="total blobs: 10"
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x10 pc=0xe1b921]

goroutine 1 [running]:
github.com/ollama/ollama/server.deleteUnusedLayers.func1({0xc00026e320, 0x5a}, {0x14655c8?, 0xc0002d2b60?}, {0x14655c8?, 0xc0002d2b60?})
        github.com/ollama/ollama/server/images.go:648 +0x501
path/filepath.walk({0xc00026e320, 0x5a}, {0x14655c8, 0xc0002d2b60}, 0xc000515800)
        path/filepath/path.go:478 +0x105
path/filepath.walk({0xc000254000, 0x4e}, {0x14655c8, 0xc0002d25b0}, 0xc000515800)
        path/filepath/path.go:502 +0x254
path/filepath.walk({0xc00059a9c0, 0x35}, {0x14655c8, 0xc0002d2540}, 0xc000515800)
        path/filepath/path.go:502 +0x254
path/filepath.walk({0xc0004b6680, 0x2d}, {0x14655c8, 0xc0002d24d0}, 0xc000515800)
        path/filepath/path.go:502 +0x254
path/filepath.walk({0xc000480bc0, 0x1a}, {0x14655c8, 0xc0002d2460}, 0xc000515800)
        path/filepath/path.go:502 +0x254
path/filepath.Walk({0xc000480bc0, 0x1a}, 0xc000515800)
        path/filepath/path.go:560 +0x66
github.com/ollama/ollama/server.deleteUnusedLayers(0x0, 0xc000515a48)
        github.com/ollama/ollama/server/images.go:652 +0xa5
github.com/ollama/ollama/server.PruneLayers()
        github.com/ollama/ollama/server/images.go:706 +0x465
github.com/ollama/ollama/server.Serve({0x1460800, 0xc0004c31a0})
        github.com/ollama/ollama/server/routes.go:1034 +0x2a5
github.com/ollama/ollama/cmd.RunServer(0xc0001a7400?, {0x1c2d700?, 0x4?, 0x12be960?})
        github.com/ollama/ollama/cmd/cmd.go:966 +0x17c
github.com/spf13/cobra.(*Command).execute(0xc0000a2308, {0x1c2d700, 0x0, 0x0})
        github.com/spf13/cobra@v1.7.0/command.go:940 +0x882
github.com/spf13/cobra.(*Command).ExecuteC(0xc000453b08)
        github.com/spf13/cobra@v1.7.0/command.go:1068 +0x3a5
github.com/spf13/cobra.(*Command).Execute(...)
        github.com/spf13/cobra@v1.7.0/command.go:992
github.com/spf13/cobra.(*Command).ExecuteContext(...)
        github.com/spf13/cobra@v1.7.0/command.go:985
main.main()
        github.com/ollama/ollama/main.go:11 +0x4d

### OS

Windows

### GPU

Nvidia, Intel

### CPU

Intel

**Comment by jmorganca** [comment]
Hi @SuzuKaO sorry this happened. If you run `ollama list` while the Ollama windows app is running, which models do you see? A quick fix that would require re-downloading your models would be to remove `C:\Users\<your user>\.ollama\models`. However, will look into why this is happening and get it fixed

**Comment by pdevine** [comment]
@SuzuKaO is it OK to close this?
