### ISSUE TITLE
Settings File In Addition to Environment Flags

### ISSUE THREAD

**Issue by chigkim** [ollama/ollama#4649]
Now there are quite a few features relying on environment variable.
Can we have a way to control those features using settings file like ~/.ollama/settings.yaml for in MacOS?

```yaml
OLLAMA_HOST: "0.0.0.0"
OLLAMA_NOHISTORY: true
OLLAMA_FLASH_ATTENTION: true
OLLAMA_NUM_PARALLEL: 4
OLLAMA_MAX_LOADED: 2
```

Thanks!

**Comment by dhiltgen** [comment]
Tracked in issue #204
