### ISSUE TITLE
Error When Running Granite Code 20b

### ISSUE THREAD

**Issue by rb81** [ollama/ollama#4651]
### What is the issue?

When executing `ollama run granite-code:20b` getting the following error on `linux`:

```bash
Error: llama runner process has terminated: signal: aborted (core dumped) 
```

### OS

Linux

### GPU

Other

### CPU

Intel

### Ollama version

0.1.38

**Comment by DuckyBlender** [comment]
Same issue

**Comment by Tycho-S** [comment]
Same here (as the original - core dump)

**Comment by DuckyBlender** [comment]
Resolved with 0.1.39

**Comment by Single430** [comment]
> Resolved with 0.1.39

Haha, I happened to encounter this issue on this version
```
ollama run minicpm_xxx
```

**Comment by rb81** [comment]
> Note: this model requires [Ollama 0.1.39](https://github.com/ollama/ollama/releases/tag/v0.1.39) which is in pre-release.

**Comment by DuckyBlender** [comment]
> > Note: this model requires [Ollama 0.1.39](https://github.com/ollama/ollama/releases/tag/v0.1.39) which is in pre-release.

This message wasn't present when the model was originally uploaded to ollama

**Comment by rb81** [comment]
> This message wasn't present when the model was originally uploaded to ollama

Yes, I noticed the same. But it is mentioned now, so I closed the ticket.
