### ISSUE TITLE
invalid conversion from ‘void*’ to ‘unsigned int’ [-fpermissive]

### ISSUE THREAD

**Issue by Zhou-CyberSecurity-AI** [ollama/ollama#4655]
### What is the issue?

I want to load the local model from Pytorch, but "make -C llm/llama.cpp quantize" always reports an error. My gcc version is 9.5 in the centos system.

### OS

Linux

### GPU

Nvidia

### CPU

Intel

**Comment by dhiltgen** [comment]
I believe we require gcc v10 or newer to build.  You can check out https://github.com/ollama/ollama/blob/main/scripts/rh_linux_deps.sh to see how we add this to older CentOS distros.

You should also be aware that we're moving to a new build model for the native code - see https://github.com/ollama/ollama/blob/main/docs/development.md#transition-to-go-runner
