### ISSUE TITLE
[Windows 10] Error: llama runner process has terminated: exit status 0xc0000139

### ISSUE THREAD

**Issue by bogdandinga** [ollama/ollama#4657]
### What is the issue?

Steps to reproduce:
1. Install Olama on Windows 10
2. Run: ollama run llama3:70b (same for llama3 simply)
3. Wait for the download to finish
4. Wait for Olama to start

Actual results:
Error: llama runner process has terminated: exit status 0xc0000139
 *  Using Dependency Walker I see that a lot of DLCs are missing, example: API-MS-WIN-CORE-APPCOMPAT-L1-1-0.DLL and EXT-MS-ONECORE-APPMODEL-STATEREPOSITORY-CACHE-L1-1-0.DLL

### OS

Windows

### GPU

AMD

### CPU

AMD

### Ollama version

0.1.38

**Comment by barclaybrown** [comment]
Seems to occur on all 128k models?
```
(base) C:\Users\barcl>ollama run phi3:3.8-mini-128k-instruct-q4_0
Error: llama runner process has terminated: exit status 0xc0000409
```

**Comment by wwlwgo** [comment]
> Seems to occur on all 128k models?
> 
> ```
> (base) C:\Users\barcl>ollama run phi3:3.8-mini-128k-instruct-q4_0
> Error: llama runner process has terminated: exit status 0xc0000409
> ```

all 128k models need the latest version of ollama(above 0.1.39). download the latest version.

**Comment by barclaybrown** [comment]
Seems to have fixed it for me! Thanks much to the team!

**Comment by bogdandinga** [comment]
Unfortunately, it still reproduces on my end, even after the new  0.1.39 install :(

Logs attached:
[app.log](https://github.com/ollama/ollama/files/15494248/app.log)
[server.log](https://github.com/ollama/ollama/files/15494249/server.log)

**Comment by wwlwgo** [comment]
A 70B model requires a very large amount of VRAM! Check if your VRAM is sufficient.

> Unfortunately, it still reproduces on my end, even after the new 0.1.39 install :(
> 
> Logs attached: [app.log](https://github.com/ollama/ollama/files/15494248/app.log) [server.log](https://github.com/ollama/ollama/files/15494249/server.log)

**Comment by mogocat** [comment]
Same issue

**Comment by dhiltgen** [comment]
If folks are still seeing the failure, please upgrade to the latest version, and if that doesn't resolve it, lets get some debug logs to see if that helps show what's going wrong.

Quit Ollama tray app, then in a powershell terminal
```
$env:OLLAMA_DEBUG="1"
& "ollama app"
```
and share the latest server.log

**Comment by hljhyb** [comment]
Same issue
 ollama run qwen2:0.5b
pulling manifest
pulling 8de95da68dc4... 100% ▕████████████████████████████████████████████████████████▏ 352 MB
pulling 62fbfd9ed093... 100% ▕████████████████████████████████████████████████████████▏  182 B
pulling c156170b718e... 100% ▕████████████████████████████████████████████████████████▏  11 KB
pulling f02dd72bb242... 100% ▕████████████████████████████████████████████████████████▏   59 B
pulling 2184ab82477b... 100% ▕████████████████████████████████████████████████████████▏  488 B
verifying sha256 digest
writing manifest
removing any unused layers
success
Error: llama runner process has terminated: exit status 0xc0000139
[server.log](https://github.com/user-attachments/files/16123678/server.log)
[app.log](https://github.com/user-attachments/files/16123679/app.log)

**Comment by dhiltgen** [comment]
I think what's probably going on here is a missing C runtime dependency DLL isn't installed - I'll fix our build so this gets statically linked or included as a payload, but until then, as a workaround you should be able to install the VC Redist package from Microsoft.

https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170#latest-microsoft-visual-c-redistributable-version

**Comment by hljhyb** [comment]
The issue still exists. I installed this runtime, and I was able to run it before.

**Comment by dhiltgen** [comment]
This should be fixed in 0.2.2 - let us know if you still have any problems after updating to that release once it's out.

**Comment by wujianyouhun** [comment]
root@2525a526f7a9:/# ollama --version
ollama version is 0.5.13
root@2525a526f7a9:/# ollama run gemma3:12b
Error: llama runner process has terminated: this model is not supported by your version of Ollama. You may need to upgrade

**Comment by nameissakthi25** [comment]
> root@2525a526f7a9:/# ollama --version ollama version is 0.5.13 root@2525a526f7a9:/# ollama run gemma3:12b Error: llama runner process has terminated: this model is not supported by your version of Ollama. You may need to upgrade

Got the same issue for gemma3 did you find any solution?

**Comment by nameissakthi25** [comment]
> root@2525a526f7a9:/# ollama --version ollama version is 0.5.13 root@2525a526f7a9:/# ollama run gemma3:12b Error: llama runner process has terminated: this model is not supported by your version of Ollama. You may need to upgrade

Upgrading it to 0.6.0 works for me!

**Comment by wujianyouhun** [comment]
> > root@2525a526f7a9:/# ollama --version ollama version is 0.5.13 root@2525a526f7a9:/# ollama run gemma3:12b Error: llama runner process has terminated: this model is not supported by your version of Ollama. You may need to upgrade
> 
> Upgrading it to 0.6.0 works for me!t


thanks!
