### ISSUE TITLE
Can run Ollama as windows service ?

### ISSUE THREAD

**Issue by petersha0630** [ollama/ollama#4658]
Hope to run Ollama as a service in a Windows environment.

**Comment by zdenek-horak** [comment]
That would be nice. Meanwhile I've configured [WinSW](https://github.com/winsw/winsw) to do this for me.

**Comment by dhiltgen** [comment]
We do not currently offer an installer that registers a system service.  You can use NSSM as described https://github.com/ollama/ollama/blob/main/docs/windows.md#standalone-cli if you want more control over how the service runs.

Support for installation paths (and implicitly service registration) in our installer is tracked via #2776
