### ISSUE TITLE
no gpu detected with RTX 3060Ti

### ISSUE THREAD

**Issue by NoIDidntHackU** [ollama/ollama#4659]
### What is the issue?

i have an RTX 3060 Ti and when I ran "curl -fsSL https://ollama.com/install.sh | sh" in ubuntu on WSL (using WSL for webUI) it installs fine, but at the end of install it says this: 
" >>> Install complete. Run "ollama" from the command line.
WARNING: No NVIDIA/AMD GPU detected. Ollama will run in CPU-only mode."
any ideas what to do to fix this?
*EDIT*
I previously (2 days ago) installed ollama and then I uninstalled WSL entirely for another reason and reinstalled it and now the issue is happening, not sure if that was the cause but thought I should add this in here, can live without GPU for now, but is a bit annoying

### OS

WSL2

### GPU

Nvidia

### CPU

AMD

### Ollama version

0.1.38

**Comment by NoIDidntHackU** [comment]
i am about to try reinstalling CUDA drivers, will let you know if it works

**Comment by NoIDidntHackU** [comment]
i tried reinstalling CUDA drivers on both windows and WLM-Ubuntu, it did not fix it

**Comment by Erwanenharma** [comment]
Thank you,

Will check tomorrow. :)

**Comment by NoIDidntHackU** [comment]
So so I have to downgrade my driver or what should i try??

**Comment by NoIDidntHackU** [comment]
Downgraded and it works, but am a bit sad that I need to downgrade as it is a bit of a nuisance but I fully support the developers as editing APIs and GPU utilisation can be a nightmare
