### ISSUE TITLE
Can Ollama be ran with Nemo Guardrails 

### ISSUE THREAD

**Issue by ShreyasChhetri** [ollama/ollama#4662]
### What is the issue?

I want to run ollama Mistral 7B model with Nemo Guardrails but when I'm using it in my config file models:
 - type: main
   engine: ollama
   model: mistral
   parameters:
    base_url: http://127.0.0.1:11434
    like this I'm not able to access it 
    Error while execution self_check_input: Ollama call failed with status code 404.
I'm sorry, an internal error has occurred.
this error is giving can anyone help me with it ??

### OS

Windows

### CPU

Intel

### Ollama version

latest

**Comment by faisnain** [comment]
I guess this error is from Ollama side not from the guardrails side. make sure if the endpoints are accessible and are able to handle multiple requests as Nemoguardrails hits LLM with 3-4 calls for intents and response calculation.

**Comment by pdevine** [comment]
Sorry for the slow response. Is this something you're still trying to do? Were you able to get it to work?
