### ISSUE TITLE
OLLAMA support MiniCPM-Llama3-V 2.5

### ISSUE THREAD

**Issue by zhqfdn** [ollama/ollama#4664]
https://github.com/OpenBMB/ollama/tree/minicpm-v2.5/examples/minicpm-v2.5

**Comment by boebo8** [comment]
有gguf格式下载吗？

**Comment by ycyy** [comment]
#4606

**Comment by jmorganca** [comment]
Closing for https://github.com/ollama/ollama/issues/4900
