### ISSUE TITLE
phi3: Error: llama runner process has terminated: exit status 0xc0000409

### ISSUE THREAD

**Issue by FreemanFeng** [ollama/ollama#4675]
### What is the issue?

ollama run phi3:medium-128k
ollama run phi3:3.8-mini-128k-instruct-q4_0

above two models will cause issue
Error: llama runner process has terminated: exit status 0xc0000409

### OS

Windows

### GPU

Other

### CPU

Intel

### Ollama version

0.1.38

**Comment by SleeplessBegonia** [comment]
mee too

**Comment by timfpark** [comment]
Also seeing something simliar with Apple M1 Max with Sonoma 14.5:

❯ ollama run phi3:14b-medium-128k-instruct-q4_0
Error: llama runner process has terminated: signal: abort trap error:done_getting_tensors: wrong number of tensors; expected 245, got 243

**Comment by leuchtetgruen** [comment]
Same here

**Comment by akhilsbehl** [comment]
I'm seeing the same error. Looking at journalctl, it says 'phi3' is not a recognised model name. Which is an issue that has been seen before. Funnily enough, phi3 mini was working earlier and had model family name as llama but that has also stopped working now.

**Comment by akhilsbehl** [comment]
Also, I've been seeing this issue with 1.38, 1.39, and 1.41 as of today.

**Comment by hujunyao** [comment]
I got same error when ollama run hhao/openbmb-minicpm-llama3-v-2_5:latest,   ollama version is 1.41, windows version

**Comment by jmorganca** [comment]
Hi there, this should be fixed in the latest version of Ollama: https://ollama.com/download

@hujunyao RE Minicpm - will track that here: https://github.com/ollama/ollama/issues/4900

Thanks for the issue!
