### ISSUE TITLE
Can't download Complete in 0.1.39 rc

### ISSUE THREAD

**Issue by Leroy-X** [ollama/ollama#4677]
### What is the issue?

In the latest 0.1.39 version, I am almost unable to complete the model download. It often breaks off and prompts "Error: max retries exceeded: EOF". I have been trying for a whole day but still haven't finished downloading a 4Gb model.

I hope this issue can be fixed soon. Thanks!

### OS

Windows

### GPU

Nvidia

### CPU

Intel

### Ollama version

0.1.39

**Comment by skrew** [comment]
I think it's fixed here: https://github.com/ollama/ollama/pull/4619 
And it's duplicate (eg: https://github.com/ollama/ollama/issues/4633)

**Comment by pdevine** [comment]
Closing as a duplicate.
