### ISSUE TITLE
Add Refact model

### ISSUE THREAD

**Issue by Alainx277** [ollama/ollama#468]
A new 1.6b parameter model called "Refact" has been released.

[Blog post](https://refact.ai/blog/2023/introducing-refact-code-llm/)

[Hugging Face](https://huggingface.co/smallcloudai/Refact-1_6B-fim)

I tried adding it myself, but the llama.cpp scripts to convert to GGML format did not work. Keep in mind that I'm a novice in this area, and it may work with the correct arguments.

**Comment by technovangelist** [comment]
It looks like that model is using an architecture called GPTRefactForCausalLM which is not one supported by Ollama.

**Comment by coder543** [comment]
llama.cpp claims to support Refact. Possibly [added in this PR](https://github.com/ggerganov/llama.cpp/pull/3329), and [discussed here.](https://github.com/ggerganov/llama.cpp/issues/3061).

**Comment by jmorganca** [comment]
This should be possible by importing existing models with this architecture (in GGUF for now). Thanks for the issue!
