### ISSUE TITLE
ollama docker container tags "latest" and "rocm" referencing old containers

### ISSUE THREAD

**Issue by dpublic** [ollama/ollama#4685]
### What is the issue?

They should be referencing the "0.1.39" and "0.1.39-rocm" containers.
https://hub.docker.com/r/ollama/ollama/tags

### OS

Linux

### GPU

Nvidia

### CPU

Intel, AMD

### Ollama version

0.1.39

**Comment by jmorganca** [comment]
Hi @dpublic thanks for the issue. 0.1.39 is still in pre-release yet, so the `latest` and `rocm` tags aren't updated quite yet!
