### ISSUE TITLE
Phi-3-medium is degraded

### ISSUE THREAD

**Issue by pdevine** [ollama/ollama#4687]
Conversely, Phi-3-medium is degraded in the ollama version. it has lower benchmark scores than Llama.cpp. several people have tried Phi-3-medium on ollama and found the performance to be poor. Why is this happening? Either the inference parameter settings or the chat template is wrong or something is broken in quantization.

_Originally posted by @umiyuki in https://github.com/ollama/ollama/issues/4626#issuecomment-2130726686_

**Comment by MeDott29** [comment]
I'm getting this message when I try to use it 
```
Error: llama runner process no longer running: -1 
```

**Comment by zane29** [comment]
For Phi3:14b,macOs can working.ollama version is 0.1.39

**Comment by yumemio** [comment]
Related?: https://x.com/MatthewBerman/status/1793386069389623323

> [ollama](https://x.com/ollama) [@ollama](https://x.com/ollama)
> [May 23](https://x.com/ollama/status/1793389631414632642)
> performance reasons. Our apologies. In this case, we believe this is very deep in the inference code. (ie. operation being done wrong or the kv cache). 
> 
> We've been working on updating a lot of the inference side to patch up our dependencies -- it's taking us some time though.

Also some folks in llama.cpp are reporting degraded performance: https://github.com/ggerganov/llama.cpp/issues/7520

Not sure this is an upstream (llama.cpp) issue or something specific to Ollama.

**Comment by pdevine** [comment]
I think it's OK to close this now. It seems to be working pretty well in the most recent versions of Ollama:

I'm getting this performance on a MBP which feels inline with other models around the same size.
```
prompt eval count:    9 token(s)
prompt eval duration: 379.595ms
prompt eval rate:     23.71 tokens/s
eval count:           430 token(s)
eval duration:        12.433999s
eval rate:            34.58 tokens/s
```
