### ISSUE TITLE
Can't down the Ollama .exe file for Windows

### ISSUE THREAD

**Issue by Tarhex** [ollama/ollama#4688]
### What is the issue?

I can't download the .exe file for windows. I have tried all I could but no success.

The link: https://ollama.com/download/OllamaSetup.exe doesn't work.

### OS

Windows

**Comment by finashkin** [comment]
why not try `winget add ollama.ollama`?

**Comment by Tarhex** [comment]
Thanks for your reply. I have tried that and it also did not download.
