### ISSUE TITLE
linux installation

### ISSUE THREAD

**Issue by wi-wi** [ollama/ollama#4691]
### What is the issue?

```
curl -fsSL https://ollama.com/install.sh | sh
bash: ./shell.sh: No such file or directory
curl: (23) Failed writing body (1349 != 1378)
```
========
the curl command is from ollama's download page.
I solved it by downloading /install.sh, making it executable and run it.

### OS

Linux

**Comment by dhiltgen** [comment]
What Linux distro and architecture are you on?  Do you have any aliases overriding `curl` or `sh` on your system?  What does `which curl` and `which sh` say?

As best as I can tell, our install script hasn't started running, and the errors are from your shell or aliases.  (e.g. nothing in our install script is called "shell.sh" so I don't think this is a bug in our installer script.
