### ISSUE TITLE
Quick model updates with `ollama pull`

### ISSUE THREAD

**Issue by LaurentBonnaud** [ollama/ollama#4701]
Hi,
I would like to be able to update models that I have previously downloaded.
When I do this, `ollama pull` does 2 steps:

1. It checks if the model is up-to-date and if not, it downloads the newest version
1. It checks the sha256 digest

Unfortunately, step 2 is always performed, even when it is not needed, which is very slow (I have a lot of models).
Therefore, I propose the following behavior:
- `ollama pull` should do step 1. and then step 2. **only if** the model has been updated
- a new command `ollama check` could allow to check the sha256 digest when needed by the user.

Thanks.

**Comment by bigsk1** [comment]
update all models use
ollama list | awk 'NR>1 {print $1}' | xargs -I {} sh -c 'echo "Updating model: {}"; ollama pull {}; echo "--"' && echo "All models updated."

**Comment by LaurentBonnaud** [comment]
I have a similar script, but the problem remains the same: ollama checks all sha256 digests, which is very slow.

**Comment by bmizerany** [comment]
Great minds. I too wanted that and demoed this internally last week. Please try it out and report back in the PR if you can. :)

https://github.com/ollama/ollama/pull/4712

**Comment by pdevine** [comment]
This got merged a while ago, so I'll go ahead and close this out.

**Comment by LaurentBonnaud** [comment]
Thanks for the fix!
