### ISSUE TITLE
Could you please support deepseek v2 ? 

### ISSUE THREAD

**Issue by netspym** [ollama/ollama#4703]
It is really a great model with excellent RAG support, great for server cpu inferencing with big memory. Its only 21b active parameters. Looks like llama.cpp is working on it, could you please also support it.

A lot of people are waiting for the support of this model.

Many Thanks
Yuming

**Comment by chaoqunxie** [comment]
latest version supprtted

**Comment by chaoqunxie** [comment]
latest version supportted

**Comment by jmorganca** [comment]
https://ollama.com/library/deepseek-v2
