### ISSUE TITLE
 msg="error loading llama server" error="llama runner process has terminated: exit status 0xc0000409 "

### ISSUE THREAD

**Issue by wsry888** [ollama/ollama#4704]
### run hhao/openbmb-minicpm-llama3-v-2_5:fp16 

msg="error loading llama server" error="llama runner process has terminated: exit status 0xc0000409 "
 
time=2024-05-29T22:03:49.672+08:00 level=INFO source=memory.go:133 msg="offload to gpu" layers.requested=-1 layers.real=33 memory.available="22.5 GiB" memory.required.full="16.2 GiB" memory.required.partial="16.2 GiB" memory.required.kv="256.0 MiB" memory.weights.total="14.0 GiB" memory.weights.repeating="13.0 GiB" memory.weights.nonrepeating="1002.0 MiB" memory.graph.full="164.0 MiB" memory.graph.partial="677.5 MiB"
time=2024-05-29T22:03:49.676+08:00 level=INFO source=memory.go:133 msg="offload to gpu" layers.requested=-1 layers.real=33 memory.available="22.5 GiB" memory.required.full="16.2 GiB" memory.required.partial="16.2 GiB" memory.required.kv="256.0 MiB" memory.weights.total="14.0 GiB" memory.weights.repeating="13.0 GiB" memory.weights.nonrepeating="1002.0 MiB" memory.graph.full="164.0 MiB" memory.graph.partial="677.5 MiB"
time=2024-05-29T22:03:49.676+08:00 level=WARN source=server.go:227 msg="multimodal models don't support parallel requests yet"
time=2024-05-29T22:03:49.678+08:00 level=INFO source=server.go:338 msg="starting llama server" cmd="C:\\Users\\users\\AppData\\Local\\Programs\\Ollama\\ollama_runners\\cuda_v11.3\\ollama_llama_server.exe --model D:\\Ollamamodels\\blobs\\sha256-a7a6ce348ebc060ceb8aa973f3b0bad5d3007b7ced23228c0e1aeba59c1fb72f --ctx-size 2048 --batch-size 512 --embedding --log-disable --n-gpu-layers 33 --mmproj D:\\Ollamamodels\\blobs\\sha256-391d11736c3cd24a90417c47b0c88975e86918fcddb1b00494c4d715b08af13e --parallel 1 --port 2796"
time=2024-05-29T22:03:49.679+08:00 level=INFO source=sched.go:338 msg="loaded runners" count=1
time=2024-05-29T22:03:49.679+08:00 level=INFO source=server.go:526 msg="waiting for llama runner to start responding"
time=2024-05-29T22:03:49.679+08:00 level=INFO source=server.go:564 msg="waiting for server to become available" status="llm server error"
INFO [wmain] build info | build=2986 commit="74f33adf" tid="12112" timestamp=1716991429
INFO [wmain] system info | n_threads=14 n_threads_batch=-1 system_info="AVX = 1 | AVX_VNNI = 0 | AVX2 = 0 | AVX512 = 0 | AVX512_VBMI = 0 | AVX512_VNNI = 0 | AVX512_BF16 = 0 | FMA = 0 | NEON = 0 | ARM_FMA = 0 | F16C = 0 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 1 | SSE3 = 1 | SSSE3 = 1 | VSX = 0 | MATMUL_INT8 = 0 | LLAMAFILE = 1 | " tid="12112" timestamp=1716991429 total_threads=28
INFO [wmain] HTTP server listening | hostname="127.0.0.1" n_threads_http="27" port="2796" tid="12112" timestamp=1716991429
ggml_cuda_init: GGML_CUDA_FORCE_MMQ:   no
ggml_cuda_init: CUDA_USE_TENSOR_CORES: yes
ggml_cuda_init: found 1 CUDA devices:
  Device 0: NVIDIA GeForce RTX 4090, compute capability 8.9, VMM: yes
GGML_ASSERT: C:\a\ollama\ollama\llm\llama.cpp\examples\llava\clip.cpp:1024: new_clip->has_llava_projector
time=2024-05-29T22:03:49.932+08:00 level=ERROR source=sched.go:344 msg="error loading llama server" error="llama runner process has terminated: exit status 0xc0000409 "
[GIN] 2024/05/29 - 22:03:49 | 500 |      1.45787s |    192.168.2.33 | POST     "/api/chat"

### OS

Windows

### GPU

Nvidia

### CPU

Intel

### Ollama version

0.1.39

**Comment by chaoqunxie** [comment]
offcial not support ,need  buid  yourself    https://github.com/OpenBMB/ollama/tree/minicpm-v2.5/examples/minicpm-v2.5

**Comment by jmorganca** [comment]
Thanks for the issue, merging this with https://github.com/ollama/ollama/issues/4900
