### ISSUE TITLE
Adding function calling support for Agents management

### ISSUE THREAD

**Issue by flefevre** [ollama/ollama#4711]
I am trying to use Ollama inside flowise with the concepts of Agents.
But it seems that it cannot use Ollama due to 
"Only compatible with models that are capable of function calling: ChatOpenAI, ChatMistral, ChatAnthropic, ChatGoogleGenerativeAI, GroqChat. Best result with GPT-4 model"

is it due to the fact I was calling "llama3:8b-instruct-q8_0" with Ollama?
Or is it because Ollama is not compatible with "function calling".

https://www.youtube.com/watch?v=284Z8k7yJRE

**Comment by jmorganca** [comment]
Hi there, tool calling is now supported in Ollama: https://ollama.com/blog/tool-support

**Comment by flefevre** [comment]
Bravo!
Prima

Le ven. 26 juil. 2024, 02:48, Jeffrey Morgan ***@***.***> a
écrit :
