### ISSUE TITLE
Ensuring Flash Attention Support in Official Docker Images by Setting Environment Variables

### ISSUE THREAD

**Issue by 00010110** [ollama/ollama#4718]
### What is the issue?

Does the official Docker image have a runtime environment for Flash Attention? Is it sufficient to directly set the environment variable OLLAMA_FLASH_ATTENTION to configure it?

### Ollama version

v0.1.39

**Comment by jmorganca** [comment]
Yes setting `OLLAMA_FLASH_ATTENTION=1` will enable it. Keep in mind only GPUs with compute capability 7+ support flash attention
