### ISSUE TITLE
unlike the v0.1.38, GPU NVIDIA not working with version v0.1.39 in windows ollama.exe

### ISSUE THREAD

**Issue by zouzeTG** [ollama/ollama#4727]
### What is the issue?

I have intalled the update for version 1.39 and unlike the v0.1.38 doesn't work with launching with ollama.exe and NVIDIA A100 and setting in Graphics setting ! 
I have re-installed older version 0.1.38 and now it's work again !

### OS

Windows

### GPU

Nvidia

### CPU

Intel

### Ollama version

0.1.39

**Comment by dhiltgen** [comment]
Could you share your server logs from 0.1.39 so we can see what went wrong?

https://github.com/ollama/ollama/blob/main/docs/troubleshooting.md

**Comment by jmorganca** [comment]
Would it also be possible to share which driver version you have (running `nvidia-smi should show)

**Comment by ZanMax** [comment]
I assume it stuck with: "msg="waiting for server to become available" status="llm server loading model""

**Comment by zouzeTG** [comment]
IN log i can see this error :   msg="waiting for server to become available" status="llm server loading model"

**Comment by jmorganca** [comment]
Thanks @zouzeTG. Would it be possible to share the output of `nvidia-smi` ?

**Comment by zouzeTG** [comment]
this a piece of log : 
ggml_cuda_init: GGML_CUDA_FORCE_MMQ:   no
ggml_cuda_init: CUDA_USE_TENSOR_CORES: yes
ggml_cuda_init: found 1 CUDA devices:
  Device 0: NVIDIA A100 80GB PCIe, compute capability 8.0, VMM: no
llm_load_tensors: ggml ctx size =    0.74 MiB
time=2024-05-30T15:06:29.857Z level=WARN source=server.go:533 msg="client connection closed before server finished loading, aborting load"
time=2024-05-30T15:06:29.857Z level=ERROR source=sched.go:344 msg="error loading llama server" error="timed out waiting for llama runner to start: context canceled"
[GIN] 2024/05/30 - 15:06:29 | 499 |         1m58s |       127.0.0.1 | POST     "/api/chat"
[GIN] 2024/05/30 - 15:16:46 | 200 |        30.3µs |       127.0.0.1 | HEAD     "/"
[GIN] 2024/05/30 - 15:16:46 | 200 |     24.2006ms |       127.0.0.1 | POST     "/api/show"
[GIN] 2024/05/30 - 15:16:46 | 200 |       568.9µs |       127.0.0.1 | POST     "/api/show"
time=2024-05-30T15:16:48.719Z level=INFO source=memory.go:133 msg="offload to gpu" layers.requested=-1 layers.real=81 memory.available="79.1 GiB" memory.required.full="38.5 GiB" memory.required.partial="38.5 GiB" memory.required.kv="640.0 MiB" memory.weights.total="36.7 GiB" memory.weights.repeating="35.9 GiB" memory.weights.nonrepeating="822.0 MiB" memory.graph.full="324.0 MiB" memory.graph.partial="1.1 GiB"
time=2024-05-30T15:16:48.720Z level=INFO source=memory.go:133 msg="offload to gpu" layers.requested=-1 layers.real=81 memory.available="79.1 GiB" memory.required.full="38.5 GiB" memory.required.partial="38.5 GiB" memory.required.kv="640.0 MiB" memory.weights.total="36.7 GiB" memory.weights.repeating="35.9 GiB" memory.weights.nonrepeating="822.0 MiB" memory.graph.full="324.0 MiB" memory.graph.partial="1.1 GiB"
time=2024-05-30T15:16:48.720Z level=INFO source=server.go:138 msg="Invalid OLLAMA_LLM_LIBRARY cuda_v12.5 - not found"
time=2024-05-30T15:16:48.722Z level=INFO source=server.go:338 msg="starting llama server" cmd="C:\\Users\\zouz\\AppData\\Local\\Programs\\Ollama\\ollama_runners\\cuda_v11.3\\ollama_llama_server.exe --model E:\\.ollama\\blobs\\sha256-0bd51f8f0c975ce910ed067dcb962a9af05b77bafcdc595ef02178387f10e51d --ctx-size 2048 --batch-size 512 --embedding --log-disable --n-gpu-layers 81 --parallel 1 --port 50178"
time=2024-05-30T15:16:48.726Z level=INFO source=sched.go:338 msg="loaded runners" count=1
time=2024-05-30T15:16:48.726Z level=INFO source=server.go:526 msg="waiting for llama runner to start responding"
time=2024-05-30T15:16:48.726Z level=INFO source=server.go:564 msg="waiting for server to become available" status="llm server error"
INFO [wmain] build info | build=2986 commit="74f33adf" tid="4380" timestamp=1717082208
INFO [wmain] system info | n_threads=24 n_threads_batch=-1 system_info="AVX = 1 | AVX_VNNI = 0 | AVX2 = 0 | AVX512 = 0 | AVX512_VBMI = 0 | AVX512_VNNI = 0 | AVX512_BF16 = 0 | FMA = 0 | NEON = 0 | ARM_FMA = 0 | F16C = 0 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 1 | SSE3 = 1 | SSSE3 = 1 | VSX = 0 | MATMUL_INT8 = 0 | LLAMAFILE = 1 | " tid="4380" timestamp=1717082208 total_threads=48
INFO [wmain] HTTP server listening | hostname="127.0.0.1" n_threads_http="47" port="50178" tid="4380" timestamp=1717082208
llama_model_loader: loaded meta data with 22 key-value pairs and 723 tensors from E:\.ollama\blobs\sha256-0bd51f8f0c975ce910ed067dcb962a9af05b77bafcdc595ef02178387f10e51d (version GGUF V3 (latest))
lla

**Comment by jmorganca** [comment]
@zouzeTG did you happen to set `OLLAMA_LLM_LIBRARY`? would it be possible to try without setting it?

**Comment by zouzeTG** [comment]
Hello, @jmorganca  I haven't touched this variable, should it be given a particular value?

**Comment by dhiltgen** [comment]
@zouzeTG 
```
time=2024-05-30T15:16:48.720Z level=INFO source=server.go:138 msg="Invalid OLLAMA_LLM_LIBRARY cuda_v12.5 - not found"
```

This log line implies the variable has been set to an invalid runner name.  Can you check your system environment variables?

**Comment by dhiltgen** [comment]
If you're still having troubles, please upgrade to the latest version which has some performance improvements for CUDA model loading on windows, and if that doesn't resolve your problem, please share an updated server log and I'll reopen the issue.
