### ISSUE TITLE
dolphin-2.9.2-mixtral-8x22b

### ISSUE THREAD

**Issue by psyv282j9d** [ollama/ollama#4729]
2.9 already up, just need to update for system message fix, and better coherence of long context windows 

https://huggingface.co/crusoeai/dolphin-2.9.2-mixtral-8x22b-GGUF

**Comment by psyv282j9d** [comment]
Should also be noted that the context window is 64k vice 2k

**Comment by pdevine** [comment]
Sorry for the slow response! This slipped through the cracks. This has been up for months. You can use it with:

```
ollama run dolphin-mixtral:8x22b-v2.9-q4_0
```

You can also find [other quantizations](https://ollama.com/library/dolphin-mixtral/tags)

I'll go ahead and close out the issue.
