### ISSUE TITLE
sensitivity to slow or unstable internet

### ISSUE THREAD

**Issue by logiota** [ollama/ollama#4739]
### What is the issue?

I could watch 1440p youtube on a repeated WiFi, but i got this message 10 times:
ollama run codestral
pulling manifest 
Error: pull model manifest: Get "https://ollama.com/token?nonce=f6x6BtvZrx32UVKjkCQAlQ&scope=repository%!A(MISSING)library%!F(MISSING)codestral%!A(MISSING)pull&service=ollama.com&ts=1717102994": dial tcp 34.120.132.20:443: i/o timeout

### OS

macOS

### GPU

Apple

### CPU

Apple

### Ollama version

0.1.37

**Comment by dhiltgen** [comment]
We fixed a bug recently where on slow/flaky internet connections we'd temporarily leak file descriptors which can lead to socket exhaustion.  This may resolve your issue.  Please try the 0.3.13 release and let us know.

**Comment by dhiltgen** [comment]
If you still experience the problem on the latest release, let us know and I'll reopen so we can continue to investigate.
