### ISSUE TITLE
how to update new version of OLLAMA on Windows 12

### ISSUE THREAD

**Issue by Jinish2170** [ollama/ollama#4743]
I am constantly getting notifications of new version available of OLLAMA but did not found a way to update the new version on windows 
Please share any info regarding this query.

**Comment by ZanMax** [comment]
Ollama on macOS and Windows will automatically download updates. **Click on the taskbar or menubar item and then click "Restart to update" to apply the update.**

**Comment by dhiltgen** [comment]
@Jinish2170 depending on your version of Windows and configuration, you may have to click on the "show hidden icons" arrow in the task bar to find the Ollama icon.

**Comment by omarnahdi** [comment]
@ZanMax mine is still running the previous version and I had to manually restart the laptop but it still didn't install it. Do you have a solution

**Comment by yoonghm** [comment]
I think this is available if ollama is allowed to run during startup and keeps running in the background. Otherwise you will have to download the latest installer and re-install it. If you have installed it in `C:\ollama`, then enter `OllamaSetup.exe /DIR="C:\ollama"` for Windows.
