### ISSUE TITLE
Running multiple models simultaneously, always using one card

### ISSUE THREAD

**Issue by leoHostProject** [ollama/ollama#4747]
### What is the issue?

Running multiple models simultaneously, always using one card,but i have 4 cards and download 4model
When multiple users are using it at the same time, always clear the first card and then load other models instead of using my other idle cards

### OS

Linux

### GPU

Nvidia

### CPU

Intel

### Ollama version

0.1.33

**Comment by leoHostProject** [comment]
this is my ollama settings
Execstart=/usr/local/bin/ollama serve
User=ollama
Group=ollama
Restart=always
RestartSec=3
Environment="PATH=/usr/local/nvidia/bin:/usr/local/cuda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
Environment="OLLAMA HOST=0.0.0.0"
Environment="CUDA VISIBLE DEVICES=0,1,2,3"
Environment="OLLAMA NUM PARALLEL=4"

**Comment by leoHostProject** [comment]
gpu resources is NVIDIA A100 80GB PCIe *4
NVIDIA-SMI 535.154.05
CUDA Version:12.2
GPU Fan is 0,1,2,3
alwalys use 0 free 1,2,3

**Comment by DuckyBlender** [comment]
please update your ollama to see if it's been fixed in the newer versions

**Comment by dhiltgen** [comment]
@leoHostProject to load 4 models on 4 GPUs concurrently, you need to also set `OLLAMA_MAX_LOADED_MODELS` - the current default is 1.
