### ISSUE TITLE
Garbage output running llama3 GGUF model

### ISSUE THREAD

**Issue by DiptenduIDEAS** [ollama/ollama#4750]
### What is the issue?

I downloaded https://huggingface.co/QuantFactory/Meta-Llama-3-8B-GGUF/blob/main/Meta-Llama-3-8B.Q2_K.gguf
Created a Modelfile using `ollama create example -f Modelfile`
and ran `ollama run example`

On asking the _question why is the sky blue?_  on the >>> prompt I am getting garbage (a series of numbers)

![image](https://github.com/ollama/ollama/assets/156412399/af66c002-32cf-42a2-bfb8-5e1edf890248)

### OS

Windows

### GPU

Other

### CPU

Intel

### Ollama version

0.1.31

**Comment by jmorganca** [comment]
Hi there, would it be possible to try again? You may be missing a prompt template - but that should be auto detected now 😊 . Sorry you hit this issue.

**Comment by DiptenduIDEAS** [comment]
Hello Jeffry,

Thank you for the update.

Can you please share an example as to how a prompt may be created according
to some template
for a command line invocation of the model (rather than from a Python
program).

Regards,

Diptendu Dutta
