### ISSUE TITLE
Add this web app to the list of apps in the README

### ISSUE THREAD

**Issue by greenido** [ollama/ollama#4758]
I created: https://github.com/greenido/multi-LLM-at-once base on your wonderful project.
...and it would be cool if you can add it to the list of web apps in the readme.
More info on the 'why' is here: https://greenido.wordpress.com/2024/04/08/the-power-of-many-why-you-should-consider-using-multiple-large-language-models/

Keep rocking 🙌🏾

**Comment by pdevine** [comment]
Thanks for sharing this! You can always create a pull request to add to the README.
