### ISSUE TITLE
I created Ollama - Open WebUI Script - Give it a try!

### ISSUE THREAD

**Issue by Special-Niewbie** [ollama/ollama#4763]
I created "Ollama-Open-WebUI-Script" for those who, like me, prefer not to overload their PC at startup with too many resources. Instead of manually starting Docker, then Ollama, and finally Open WebUI, this script simplifies the entire process, giving you direct and easy access to these two fantastic projects.

Give it a try here https://github.com/Special-Niewbie/Ollama-Open-WebUI-Script, and enjoy a smoother experience with Ollama and Open WebUI!

**Comment by pdevine** [comment]
This is cool, thank you for sharing it!
