### ISSUE TITLE
ollama stop [id of running model]

### ISSUE THREAD

**Issue by mrdev023** [ollama/ollama#4764]
Sometimes, when i use external tools with ollama, some model continue to run after application exit.

It can be usefull to have a command like this

```bash
ollama stop [id of running model]
```

**Comment by orctom** [comment]
![image](https://github.com/user-attachments/assets/e5e321b1-ca51-4fa8-86cd-7e01fc389b58)
Really need this feature, don't tell me to `egrep ollama` the `kill -9`, it's silly, since these's no way to tell which is the pid of the target model.

**Comment by HomunMage** [comment]
we need ollama stop that can kill ollama server, no using systemctl

because need use this in suck python and c++ subprocess or thread to handle
