### ISSUE TITLE
ollama run deepseek-v2:16b Error: llama runner process has terminated: signal: aborted (core dumped) 

### ISSUE THREAD

**Issue by zhqfdn** [ollama/ollama#4765]
### What is the issue?

Error: llama runner process has terminated: signal: aborted (core dumped) 

### OS

Linux

### GPU

Nvidia

### CPU

Intel

### Ollama version

1.40

**Comment by aAbdman** [comment]
same problem, couldn't get it to work

**Comment by jmorganca** [comment]
Hi @rootcli and @zhqfdn this was fixed in the latest pre-release of v0.1.40 uploaded yesterday: https://github.com/ollama/ollama/releases/tag/v0.1.40

**Comment by rootcli** [comment]
I updated to ollama 1.4 >  Didn't work
I repulled [deepstack](deepseek-v2:latest) > Didn't work
I deleted the model and redownloaded > Didn't work
I restarted Ollama service > Didn't work
nothing seems work
Until I restarted my system

Now it working 👍🏻
Thank you

**Comment by rootcli** [comment]
This model is not stable.
It starts with english then It keeps switching in what I think it's Chines. I had to delete it

**Comment by imareo** [comment]
same error... ollama 0.1.41
restart don't help.
![Screenshot from 2024-06-02 14-03-31](https://github.com/ollama/ollama/assets/46757141/bd0f544b-5d83-4d98-ab1d-04bab0714015)

**Comment by Aurnytoraink** [comment]
I tried on another computer, but I still have the issue

- Model : hhao/openbmb-minicpm-llama3-v-2_5 
- CPU : AMD Ryzen 5 5600
- GPU : Nvidia GTX 1060
- OS : Fedora Workstation (Linux)
- Ollama version : 0.1.41

**Comment by rootcli** [comment]
I tried hhao/openbmb-minicpm-llama3-v-2_5
and I got the same error 
```
ollama run hhao/openbmb-minicpm-llama3-v-2_5
Error: llama runner process has terminated: signal: aborted
```

**Comment by rick-github** [comment]
One cause of this is because ollama tries to offload too many layers to the GPU.  See https://github.com/ollama/ollama/issues/4799#issuecomment-2148573008 on ways to mitigate.
