### ISSUE TITLE
Cannot get web to verify service is running

### ISSUE THREAD

**Issue by brentfamily51** [ollama/ollama#4768]
### What is the issue?

I have installed ollama on ubuntu (proxmox lxc) successfully using the script, I am able to download and access it on command line, but when I attempt to access the ip:11434 the page fails to load.   I appear to have no external access to the service on the machine.   Any help is greatly appreciated. 

### OS

Linux

### Ollama version

0.1.39

**Comment by dhiltgen** [comment]
Instructions for exposing the service are located here - https://github.com/ollama/ollama/blob/main/docs/faq.md#how-can-i-expose-ollama-on-my-network
