### ISSUE TITLE
Ignoring env, being weird with env

### ISSUE THREAD

**Issue by RealMrCactus** [ollama/ollama#4771]
### What is the issue?

I use systemctl edit to make an override and set OLLAMA_HOST to 0.0.0.0 within the bounds of where it should be and it says its out of bounds in systemctl status i edit the service file directly to add it and it hosts on `[::]:11434` instead

### OS

Linux

### GPU

Nvidia

### CPU

Intel

### Ollama version

0.1.39

**Comment by pdevine** [comment]
Hi @RealMrCactus , sorry for the delay responding. Check out the [FAQ](https://github.com/ollama/ollama/blob/main/docs/faq.md#setting-environment-variables-on-linux) which describes how to set the environment variable. Use `journalctl -u ollama --no-pager` to check the ollama logs and see what `OLLAMA_HOST` got set to (it should be at the top of the logs).

I'll go ahead and close the issue.
