### ISSUE TITLE
Can`t run 0.1.40 on window10

### ISSUE THREAD

**Issue by 18657769868** [ollama/ollama#4776]
### What is the issue?

Can`t run 0.1.40 on window10
![33e3def630c5d32e709d75d6753493b](https://github.com/ollama/ollama/assets/22534813/df4acf59-5a2c-4aef-a819-fbbd8ae7e362)

2024/06/02 09:15:34 routes.go:1007: INFO server config env="map[OLLAMA_DEBUG:false OLLAMA_FLASH_ATTENTION:false OLLAMA_HOST: OLLAMA_KEEP_ALIVE: OLLAMA_LLM_LIBRARY: OLLAMA_MAX_LOADED_MODELS:1 OLLAMA_MAX_QUEUE:512 OLLAMA_MAX_VRAM:0 OLLAMA_MODELS: OLLAMA_NOHISTORY:false OLLAMA_NOPRUNE:false OLLAMA_NUM_PARALLEL:1 OLLAMA_ORIGINS:[* http://localhost https://localhost http://localhost:* https://localhost:* http://127.0.0.1 https://127.0.0.1 http://127.0.0.1:* https://127.0.0.1:* http://0.0.0.0 https://0.0.0.0 http://0.0.0.0:* https://0.0.0.0:*] OLLAMA_RUNNERS_DIR:C:\\Users\\xinhu\\AppData\\Local\\Programs\\Ollama\\ollama_runners OLLAMA_TMPDIR:]"
time=2024-06-02T09:15:34.741+08:00 level=INFO source=images.go:729 msg="total blobs: 95"
time=2024-06-02T09:15:34.751+08:00 level=INFO source=images.go:736 msg="total unused blobs removed: 0"
time=2024-06-02T09:15:34.756+08:00 level=INFO source=routes.go:1053 msg="Listening on [::]:11434 (version 0.1.40)"
time=2024-06-02T09:15:34.756+08:00 level=INFO source=payload.go:44 msg="Dynamic LLM libraries [rocm_v5.7 cpu cpu_avx cpu_avx2 cuda_v11.3]"
Exception 0xc0000005 0x8 0x0 0x0
PC=0x0
signal arrived during external code execution

runtime.cgocall(0x11c07c0, 0xc00036f400)
	runtime/cgocall.go:157 +0x3e fp=0xc00036f3d8 sp=0xc00036f3a0 pc=0x6893be
github.com/ollama/ollama/gpu._Cfunc_oneapi_init(0x24b4dff5d30, 0xc000760660)
	_cgo_gotypes.go:529 +0x4d fp=0xc00036f400 sp=0xc00036f3d8 pc=0xa8c44d
github.com/ollama/ollama/gpu.LoadOneapiMgmt.func2(0x24b4dff5d30, 0xc000760660)
	github.com/ollama/ollama/gpu/gpu.go:400 +0x4a fp=0xc00036f430 sp=0xc00036f400 pc=0xa8f96a
github.com/ollama/ollama/gpu.LoadOneapiMgmt({0xc000704cc0, 0x1, 0x14321b0?})
	github.com/ollama/ollama/gpu/gpu.go:400 +0x23e fp=0xc00036f528 sp=0xc00036f430 pc=0xa8f7be
github.com/ollama/ollama/gpu.initGPUHandles()
	github.com/ollama/ollama/gpu/gpu.go:164 +0x2e5 fp=0xc00036f728 sp=0xc00036f528 pc=0xa8c845
github.com/ollama/ollama/gpu.GetGPUInfo()
	github.com/ollama/ollama/gpu/gpu.go:182 +0xa7 fp=0xc00036fac0 sp=0xc00036f728 pc=0xa8cce7
github.com/ollama/ollama/server.Serve({0x17dca40, 0xc000079220})
	github.com/ollama/ollama/server/routes.go:1078 +0x7bb fp=0xc00036fc70 sp=0xc00036fac0 pc=0x119803b
github.com/ollama/ollama/cmd.RunServer(0xc0001a7100?, {0x1fa8720?, 0x4?, 0x163c7fe?})
	github.com/ollama/ollama/cmd/cmd.go:979 +0x17c fp=0xc00036fd58 sp=0xc00036fc70 pc=0x11b6c9c
github.com/spf13/cobra.(*Command).execute(0xc0000b0308, {0x1fa8720, 0x0, 0x0})
	github.com/spf13/cobra@v1.7.0/command.go:940 +0x882 fp=0xc00036fe78 sp=0xc00036fd58 pc=0xa2b5e2
github.com/spf13/cobra.(*Command).ExecuteC(0xc00044bb08)
	github.com/spf13/cobra@v1.7.0/command.go:1068 +0x3a5 fp=0xc00036ff30 sp=0xc00036fe78 pc=0xa2be25
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.7.0/command.go:992
github.com/spf13/cobra.(*Command).ExecuteContext(...)
	github.com/spf13/cobra@v1.7.0/command.go:985
main.main()
	github.com/ollama/ollama/main.go:11 +0x4d fp=0xc00036ff50 sp=0xc00036ff30 pc=0x11c034d
runtime.main()
	runtime/proc.go:271 +0x28b fp=0xc00036ffe0 sp=0xc00036ff50 pc=0x6c13eb
runtime.goexit({})
	runtime/asm_amd64.s:1695 +0x1 fp=0xc00036ffe8 sp=0xc00036ffe0 pc=0x6f2561

goroutine 2 gp=0xc00006a700 m=nil [force gc (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	runtime/proc.go:402 +0xce fp=0xc00006dfa8 sp=0xc00006df88 pc=0x6c17ee
runtime.goparkunlock(...)
	runtime/proc.go:408
runtime.forcegchelper()
	runtime/proc.go:326 +0xb8 fp=0xc00006dfe0 sp=0xc00006dfa8 pc=0x6c1678
runtime.goexit({})
	runtime/asm_amd64.s:1695 +0x1 fp=0xc00006dfe8 sp=0xc00006dfe0 pc=0x6f2561
created by runtime.init.6 in goroutine 1
	runtime/proc.go:314 +0x1a

goroutine 3 gp=0xc00006aa80 m=nil [GC sweep wait]:
runtime.gopark(0x1?, 0x0?, 0x0?, 0x0?, 0x0?)
	runtime/proc.go:402 +0xce fp=0xc00006ff80 sp=0xc00006ff60 pc=0x6c17ee
runtime.goparkunlock(...)
	runtime/proc.go:408
runtime.bgsweep(0xc00007a000)
	runtime/mgcsweep.go:318 +0xdf fp=0xc00006ffc8 sp=0xc00006ff80 pc=0x6ab89f
runtime.gcenable.gowrap1()
	runtime/mgc.go:203 +0x25 fp=0xc00006ffe0 sp=0xc00006ffc8 pc=0x6a0145
runtime.goexit({})
	runtime/asm_amd64.s:1695 +0x1 fp=0xc00006ffe8 sp=0xc00006ffe0 pc=0x6f2561
created by runtime.gcenable in goroutine 1
	runtime/mgc.go:203 +0x66

goroutine 4 gp=0xc00006ac40 m=nil [GC scavenge wait]:
runtime.gopark(0x10000?, 0x17ce728?, 0x0?, 0x0?, 0x0?)
	runtime/proc.go:402 +0xce fp=0xc000085f78 sp=0xc000085f58 pc=0x6c17ee
runtime.goparkunlock(...)
	runtime/proc.go:408
runtime.(*scavengerState).park(0x1f1c120)
	runtime/mgcscavenge.go:425 +0x49 fp=0xc000085fa8 sp=0xc000085f78 pc=0x6a9229
runtime.bgscavenge(0xc00007a000)
	runtime/mgcscavenge.go:658 +0x59 fp=0xc000085fc8 sp=0xc000085fa8 pc=0x6a97d9
runtime.gcenable.gowrap2()
	runtime/mgc.go:204 +0x25 fp=0xc000085fe0 sp=0xc000085fc8 pc=0x6a00e5
runtime.goexit({})
	runtime/asm_amd64.s:1695 +0x1 fp=0xc000085fe8 sp=0xc000085fe0 pc=0x6f2561
created by runtime.gcenable in goroutine 1
	runtime/mgc.go:204 +0xa5

goroutine 5 gp=0xc00006b180 m=nil [finalizer wait]:
runtime.gopark(0xc000071e48?, 0x693505?, 0xa8?, 0x1?, 0xc00006a000?)
	runtime/proc.go:402 +0xce fp=0xc000071e20 sp=0xc000071e00 pc=0x6c17ee
runtime.runfinq()
	runtime/mfinal.go:194 +0x107 fp=0xc000071fe0 sp=0xc000071e20 pc=0x69f1c7
runtime.goexit({})
	runtime/asm_amd64.s:1695 +0x1 fp=0xc000071fe8 sp=0xc000071fe0 pc=0x6f2561
created by runtime.createfing in goroutine 1
	runtime/mfinal.go:164 +0x3d

goroutine 6 gp=0xc0001dd180 m=nil [GC worker (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	runtime/proc.go:402 +0xce fp=0xc000087f50 sp=0xc000087f30 pc=0x6c17ee
runtime.gcBgMarkWorker()
	runtime/mgc.go:1310 +0xe5 fp=0xc000087fe0 sp=0xc000087f50 pc=0x6a2285
runtime.goexit({})
	runtime/asm_amd64.s:1695 +0x1 fp=0xc000087fe8 sp=0xc000087fe0 pc=0x6f2561
created by runtime.gcBgMarkStartWorkers in goroutine 1
	runtime/mgc.go:1234 +0x1c

goroutine 18 gp=0xc000480000 m=nil [GC worker (idle)]:
runtime.gopark(0x2b1163881270?, 0x3?, 0x0?, 0x0?, 0x0?)
	runtime/proc.go:402 +0xce fp=0xc000081f50 sp=0xc000081f30 pc=0x6c17ee
runtime.gcBgMarkWorker()
	runtime/mgc.go:1310 +0xe5 fp=0xc000081fe0 sp=0xc000081f50 pc=0x6a2285
runtime.goexit({})
	runtime/asm_amd64.s:1695 +0x1 fp=0xc000081fe8 sp=0xc000081fe0 pc=0x6f2561
created by runtime.gcBgMarkStartWorkers in goroutine 1
	runtime/mgc.go:1234 +0x1c

goroutine 34 gp=0xc00008c1c0 m=nil [GC worker (idle)]:
runtime.gopark(0x2b11639793f8?, 0x0?, 0x0?, 0x0?, 0x0?)
	runtime/proc.go:402 +0xce fp=0xc000095f50 sp=0xc000095f30 pc=0x6c17ee
runtime.gcBgMarkWorker()
	runtime/mgc.go:1310 +0xe5 fp=0xc000095fe0 sp=0xc000095f50 pc=0x6a2285
runtime.goexit({})
	runtime/asm_amd64.s:1695 +0x1 fp=0xc000095fe8 sp=0xc000095fe0 pc=0x6f2561
created by runtime.gcBgMarkStartWorkers in goroutine 1
	runtime/mgc.go:1234 +0x1c

goroutine 7 gp=0xc0001dd340 m=nil [GC worker (idle)]:
runtime.gopark(0x2b1163881270?, 0x3?, 0x0?, 0x0?, 0x0?)
	runtime/proc.go:402 +0xce fp=0xc000091f50 sp=0xc000091f30 pc=0x6c17ee
runtime.gcBgMarkWorker()
	runtime/mgc.go:1310 +0xe5 fp=0xc000091fe0 sp=0xc000091f50 pc=0x6a2285
runtime.goexit({})
	runtime/asm_amd64.s:1695 +0x1 fp=0xc000091fe8 sp=0xc000091fe0 pc=0x6f2561
created by runtime.gcBgMarkStartWorkers in goroutine 1
	runtime/mgc.go:1234 +0x1c

goroutine 8 gp=0xc0001dd500 m=nil [GC worker (idle)]:
runtime.gopark(0x2b1163881270?, 0x1?, 0x0?, 0x0?, 0x0?)
	runtime/proc.go:402 +0xce fp=0xc000093f50 sp=0xc000093f30 pc=0x6c17ee
runtime.gcBgMarkWorker()
	runtime/mgc.go:1310 +0xe5 fp=0xc000093fe0 sp=0xc000093f50 pc=0x6a2285
runtime.goexit({})
	runtime/asm_amd64.s:1695 +0x1 fp=0xc000093fe8 sp=0xc000093fe0 pc=0x6f2561
created by runtime.gcBgMarkStartWorkers in goroutine 1
	runtime/mgc.go:1234 +0x1c

goroutine 35 gp=0xc00008c380 m=nil [GC worker (idle)]:
runtime.gopark(0x2b11639793f8?, 0x0?, 0x0?, 0x0?, 0x0?)
	runtime/proc.go:402 +0xce fp=0xc000097f50 sp=0xc000097f30 pc=0x6c17ee
runtime.gcBgMarkWorker()
	runtime/mgc.go:1310 +0xe5 fp=0xc000097fe0 sp=0xc000097f50 pc=0x6a2285
runtime.goexit({})
	runtime/asm_amd64.s:1695 +0x1 fp=0xc000097fe8 sp=0xc000097fe0 pc=0x6f2561
created by runtime.gcBgMarkStartWorkers in goroutine 1
	runtime/mgc.go:1234 +0x1c

goroutine 19 gp=0xc0004801c0 m=nil [GC worker (idle)]:
runtime.gopark(0x2b1163881270?, 0x3?, 0x0?, 0x0?, 0x0?)
	runtime/proc.go:402 +0xce fp=0xc000083f50 sp=0xc000083f30 pc=0x6c17ee
runtime.gcBgMarkWorker()
	runtime/mgc.go:1310 +0xe5 fp=0xc000083fe0 sp=0xc000083f50 pc=0x6a2285
runtime.goexit({})
	runtime/asm_amd64.s:1695 +0x1 fp=0xc000083fe8 sp=0xc000083fe0 pc=0x6f2561
created by runtime.gcBgMarkStartWorkers in goroutine 1
	runtime/mgc.go:1234 +0x1c

goroutine 36 gp=0xc00008c540 m=nil [GC worker (idle)]:
runtime.gopark(0x2b115c057ba0?, 0x0?, 0x0?, 0x0?, 0x0?)
	runtime/proc.go:402 +0xce fp=0xc00009ff50 sp=0xc00009ff30 pc=0x6c17ee
runtime.gcBgMarkWorker()
	runtime/mgc.go:1310 +0xe5 fp=0xc00009ffe0 sp=0xc00009ff50 pc=0x6a2285
runtime.goexit({})
	runtime/asm_amd64.s:1695 +0x1 fp=0xc00009ffe8 sp=0xc00009ffe0 pc=0x6f2561
created by runtime.gcBgMarkStartWorkers in goroutine 1
	runtime/mgc.go:1234 +0x1c

goroutine 9 gp=0xc0001dca80 m=9 mp=0xc000680008 [syscall]:
runtime.notetsleepg(0x1fa9320, 0xffffffffffffffff)
	runtime/lock_sema.go:296 +0x31 fp=0xc00009dfa0 sp=0xc00009df68 pc=0x691ad1
os/signal.signal_recv()
	runtime/sigqueue.go:152 +0x29 fp=0xc00009dfc0 sp=0xc00009dfa0 pc=0x6ee249
os/signal.loop()
	os/signal/signal_unix.go:23 +0x13 fp=0xc00009dfe0 sp=0xc00009dfc0 pc=0x9b4093
runtime.goexit({})
	runtime/asm_amd64.s:1695 +0x1 fp=0xc00009dfe8 sp=0xc00009dfe0 pc=0x6f2561
created by os/signal.Notify.func1.1 in goroutine 1
	os/signal/signal.go:151 +0x1f

goroutine 10 gp=0xc0001dcc40 m=nil [chan receive]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	runtime/proc.go:402 +0xce fp=0xc0000a1f00 sp=0xc0000a1ee0 pc=0x6c17ee
runtime.chanrecv(0xc000760900, 0x0, 0x1)
	runtime/chan.go:583 +0x3cd fp=0xc0000a1f78 sp=0xc0000a1f00 pc=0x68ba4d
runtime.chanrecv1(0x0?, 0x0?)
	runtime/chan.go:442 +0x12 fp=0xc0000a1fa0 sp=0xc0000a1f78 pc=0x68b652
github.com/ollama/ollama/server.Serve.func2()
	github.com/ollama/ollama/server/routes.go:1062 +0x3d fp=0xc0000a1fe0 sp=0xc0000a1fa0 pc=0x119817d
runtime.goexit({})
	runtime/asm_amd64.s:1695 +0x1 fp=0xc0000a1fe8 sp=0xc0000a1fe0 pc=0x6f2561
created by github.com/ollama/ollama/server.Serve in goroutine 1
	github.com/ollama/ollama/server/routes.go:1061 +0x745

goroutine 11 gp=0xc0001dd6c0 m=nil [select]:
runtime.gopark(0xc00026df58?, 0x3?, 0x60?, 0x0?, 0xc00026de32?)
	runtime/proc.go:402 +0xce fp=0xc00026dcb8 sp=0xc00026dc98 pc=0x6c17ee
runtime.selectgo(0xc00026df58, 0xc00026de2c, 0x6?, 0x0, 0x4?, 0x1)
	runtime/select.go:327 +0x725 fp=0xc00026ddd8 sp=0xc00026dcb8 pc=0x6d1c45
github.com/ollama/ollama/server.(*Scheduler).processPending(0xc00070d720, {0x17df380, 0xc00070d6d0})
	github.com/ollama/ollama/server/sched.go:102 +0xcf fp=0xc00026dfb8 sp=0xc00026ddd8 pc=0x119ba0f
github.com/ollama/ollama/server.(*Scheduler).Run.func1()
	github.com/ollama/ollama/server/sched.go:92 +0x1f fp=0xc00026dfe0 sp=0xc00026dfb8 pc=0x119b91f
runtime.goexit({})
	runtime/asm_amd64.s:1695 +0x1 fp=0xc00026dfe8 sp=0xc00026dfe0 pc=0x6f2561
created by github.com/ollama/ollama/server.(*Scheduler).Run in goroutine 1
	github.com/ollama/ollama/server/sched.go:91 +0xb4

goroutine 12 gp=0xc0001dd880 m=nil [select]:
runtime.gopark(0xc00009bf50?, 0x3?, 0x0?, 0x0?, 0xc00009bd52?)
	runtime/proc.go:402 +0xce fp=0xc00009bbe0 sp=0xc00009bbc0 pc=0x6c17ee
runtime.selectgo(0xc00009bf50, 0xc00009bd4c, 0x0?, 0x0, 0x0?, 0x1)
	runtime/select.go:327 +0x725 fp=0xc00009bd00 sp=0xc00009bbe0 pc=0x6d1c45
github.com/ollama/ollama/server.(*Scheduler).processCompleted(0xc00070d720, {0x17df380, 0xc00070d6d0})
	github.com/ollama/ollama/server/sched.go:214 +0xec fp=0xc00009bfb8 sp=0xc00009bd00 pc=0x119c58c
github.com/ollama/ollama/server.(*Scheduler).Run.func2()
	github.com/ollama/ollama/server/sched.go:96 +0x1f fp=0xc00009bfe0 sp=0xc00009bfb8 pc=0x119b8df
runtime.goexit({})
	runtime/asm_amd64.s:1695 +0x1 fp=0xc00009bfe8 sp=0xc00009bfe0 pc=0x6f2561
created by github.com/ollama/ollama/server.(*Scheduler).Run in goroutine 1
	github.com/ollama/ollama/server/sched.go:95 +0x110
rax     0x7ffd47bfff00
rbx     0xc000760660
rcx     0x0
rdx     0x16c
rdi     0xc0007606b0
rsi     0x85f0dffc60
rbp     0x85f0dffc20
rsp     0x85f0dffa88
r8      0x16c
r9      0x16c
r10     0x16c
r11     0x85f0dff760
r12     0x7ffdc10bb1d0
r13     0x1e7d67e
r14     0x0
r15     0x85f0dffad0
rip     0x0
rflags  0x10246
cs      0x33
fs      0x53
gs      0x2b

### OS

Windows

### GPU

Other

### CPU

Intel

### Ollama version

0.1.40

**Comment by jmorganca** [comment]
Hi @18657769868 do you have an Intel ARC GPU by chance?

**Comment by tqangxl** [comment]
<img width="822" alt="屏幕截图 2024-06-02 095318" src="https://github.com/ollama/ollama/assets/9669944/043725c8-2b40-4179-b3ce-7342965bacdd">

[app.log](https://github.com/user-attachments/files/15523893/app.log)
[server.log](https://github.com/user-attachments/files/15523894/server.log)

**Comment by 18657769868** [comment]
![image](https://github.com/ollama/ollama/assets/22534813/b55be0ea-bbd0-41af-86fd-01f54904233b)


> do you have an Intel ARC GPU by chance?
Intel HD Graphics 630 , CPU is  i7-7700

**Comment by jmorganca** [comment]
@18657769868 thanks!

**Comment by 18657769868** [comment]
> <img alt="屏幕截图 2024-06-02 095318" width="822" src="https://private-user-images.githubusercontent.com/9669944/335836067-043725c8-2b40-4179-b3ce-7342965bacdd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcyOTYzNDMsIm5iZiI6MTcxNzI5NjA0MywicGF0aCI6Ii85NjY5OTQ0LzMzNTgzNjA2Ny0wNDM3MjVjOC0yYjQwLTQxNzktYjNjZS03MzQyOTY1YmFjZGQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYwMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MDJUMDI0MDQzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NWM5OTZiMTQ0MTRhNWQ0Mjc2OGRjYjU2YTBkNTA5ZmRmMjA3ZTAwMGNiZjAyMDk3NzU1MjE4NGYyNThlZDI5MCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.L5bvetSUnEOFQZim83t4wuoTEblrtXspLPTULMhkWkM">
> [app.log](https://github.com/user-attachments/files/15523893/app.log) [server.log](https://github.com/user-attachments/files/15523894/server.log)

Terminate ollama in Task Manager

**Comment by jmorganca** [comment]
This should be fixed in https://github.com/ollama/ollama/releases/tag/v0.1.41 – sorry this happened!
