### ISSUE TITLE
Support for jina-embeddings-v2-base-zh

### ISSUE THREAD

**Issue by wwjCMP** [ollama/ollama#4778]
https://huggingface.co/jinaai/jina-embeddings-v2-base-zh

**Comment by JoanFM** [comment]
Hey @wwjCMP 


the only problem for supporting this feature is to get the right preprocessing and tokenization right. 

I am not sure if there is currently supprt for another chinese model from which I can take inspiration.

**Comment by wwjCMP** [comment]
> Hey @wwjCMP
> 
> the only problem for supporting this feature is to get the right preprocessing and tokenization right.
> 
> I am not sure if there is currently supprt for another chinese model from which I can take inspiration.

I can't quite grasp what you mean. But, here is a Chinese embedding model that I am currently using.

https://huggingface.co/aspire/acge_text_embedding
mofanke/acge_text_embedding:latest

**Comment by JoanFM** [comment]
> > Hey @wwjCMP
> > the only problem for supporting this feature is to get the right preprocessing and tokenization right.
> > I am not sure if there is currently supprt for another chinese model from which I can take inspiration.
> 
> I can't quite grasp what you mean. But, here is a Chinese embedding model that I am currently using.
> 
> https://huggingface.co/aspire/acge_text_embedding mofanke/acge_text_embedding:latest

I mean, is this model available through llama.cpp?

**Comment by JoanFM** [comment]
hey @wwjCMP ,

I open a PR in `llama.cpp` to support this model https://github.com/ggerganov/llama.cpp/pull/7795

**Comment by EntropyYue** [comment]
Already supported, you can download it here [EntropyYue/jina-embeddings-v2-base-zh](https://ollama.com/EntropyYue/jina-embeddings-v2-base-zh).

**Comment by EntropyYue** [comment]
> 但是你做得怎么样呢？
> 
> 它如何支持 ？您确定分词化和结果等同于 ？`llama.cpp``HF`

It was successfully converted in the 'rf to gguf' script. If you are concerned about this issue, you can try comparing it

**Comment by EntropyYue** [comment]
> But how did you do @EntropyYue?
> 
> How is it supported in `llama.cpp`? Are you sure the tokenization and the result is equivalent to the usage of `HF`?

It was successfully converted in the 'rf to gguf' script. If you are concerned about this issue, you can try comparing it
