### ISSUE TITLE
Radeon VII gfx906:sramecc-:xnack- windows support

### ISSUE THREAD

**Issue by MrSteelRat** [ollama/ollama#4780]
Hello, please add support for this GPU Radeon VII to the regular version, I can help with testing if necessary

**Comment by dhiltgen** [comment]
I believe this GPU should be supported.  Have you tried?  If it didn't work, can you share the server log?

**Comment by MrSteelRat** [comment]
Hello, I looked at the news about AMD GPU support and there is only the Pro version of my video card, I have a regular one without the Pro prefix

**Comment by MrSteelRat** [comment]
![image](https://github.com/ollama/ollama/assets/31157848/c11347b2-06fa-4b70-873e-2f32dc48b6a6)
![image](https://github.com/ollama/ollama/assets/31157848/fb0758a4-36e8-4366-847d-f9de7fac2dae)

**Comment by dhiltgen** [comment]
If the GPU isn't working, please share your server log so we can see what went wrong.

https://github.com/ollama/ollama/blob/main/docs/troubleshooting.md

**Comment by fofocx** [comment]
Same problem.
GPU: AMD Radeon VII
OLLAMA version: 0.1.46

server.log:
2024/06/26 15:17:40 routes.go:1064: INFO server config env="map[CUDA_VISIBLE_DEVICES: GPU_DEVICE_ORDINAL: HIP_VISIBLE_DEVICES: HSA_OVERRIDE_GFX_VERSION: OLLAMA_DEBUG:false OLLAMA_FLASH_ATTENTION:false OLLAMA_HOST:http://0.0.0.0:11434 OLLAMA_INTEL_GPU:false OLLAMA_KEEP_ALIVE: OLLAMA_LLM_LIBRARY: OLLAMA_MAX_LOADED_MODELS:1 OLLAMA_MAX_QUEUE:512 OLLAMA_MAX_VRAM:0 OLLAMA_MODELS:C:\\Users\\Administrator\\.ollama\\models OLLAMA_NOHISTORY:false OLLAMA_NOPRUNE:false OLLAMA_NUM_PARALLEL:1 OLLAMA_ORIGINS:[http://localhost https://localhost http://localhost:* https://localhost:* http://127.0.0.1 https://127.0.0.1 http://127.0.0.1:* https://127.0.0.1:* http://0.0.0.0 https://0.0.0.0 http://0.0.0.0:* https://0.0.0.0:* app://* file://* tauri://*] OLLAMA_RUNNERS_DIR:C:\\Users\\Administrator\\AppData\\Local\\Programs\\Ollama\\ollama_runners OLLAMA_SCHED_SPREAD:false OLLAMA_TMPDIR: ROCR_VISIBLE_DEVICES:]"
time=2024-06-26T15:17:40.405+08:00 level=INFO source=images.go:730 msg="total blobs: 0"
time=2024-06-26T15:17:40.405+08:00 level=INFO source=images.go:737 msg="total unused blobs removed: 0"
time=2024-06-26T15:17:40.407+08:00 level=INFO source=routes.go:1111 msg="Listening on [::]:11434 (version 0.1.46)"
time=2024-06-26T15:17:40.409+08:00 level=INFO source=payload.go:44 msg="Dynamic LLM libraries [cpu cpu_avx cpu_avx2 cuda_v11.3 rocm_v5.7]"
time=2024-06-26T15:17:40.545+08:00 level=WARN source=amd_windows.go:97 msg="amdgpu is not supported" gpu=0 gpu_type=gfx906:sramecc-:xnack- library=C:\Users\Administrator\AppData\Local\Programs\Ollama\rocm supported_types="[gfx1030 gfx1100 gfx1101 gfx1102 gfx906]"
time=2024-06-26T15:17:40.545+08:00 level=WARN source=amd_windows.go:99 msg="See https://github.com/ollama/ollama/blob/main/docs/troubleshooting.md for HSA_OVERRIDE_GFX_VERSION usage"
time=2024-06-26T15:17:40.608+08:00 level=INFO source=types.go:98 msg="inference compute" id=0 library=cpu compute="" driver=0.0 name="" total="32.0 GiB" available="15.4 GiB"

**Comment by fofocx** [comment]
Ollama will throw "Error: llama runner process has terminated: exit status 0xc0000005" and crash when execute "ollama run .." if set Environment variable "HSA_OVERRIDE_GFX_VERSION=9.0.6" .

server.log:
2024/06/26 15:31:15 routes.go:1064: INFO server config env="map[CUDA_VISIBLE_DEVICES: GPU_DEVICE_ORDINAL: HIP_VISIBLE_DEVICES: HSA_OVERRIDE_GFX_VERSION:9.0.6 OLLAMA_DEBUG:false OLLAMA_FLASH_ATTENTION:false OLLAMA_HOST:http://0.0.0.0:11434 OLLAMA_INTEL_GPU:false OLLAMA_KEEP_ALIVE: OLLAMA_LLM_LIBRARY: OLLAMA_MAX_LOADED_MODELS:1 OLLAMA_MAX_QUEUE:512 OLLAMA_MAX_VRAM:0 OLLAMA_MODELS:C:\\Users\\Administrator\\.ollama\\models OLLAMA_NOHISTORY:false OLLAMA_NOPRUNE:false OLLAMA_NUM_PARALLEL:1 OLLAMA_ORIGINS:[http://localhost https://localhost http://localhost:* https://localhost:* http://127.0.0.1 https://127.0.0.1 http://127.0.0.1:* https://127.0.0.1:* http://0.0.0.0 https://0.0.0.0 http://0.0.0.0:* https://0.0.0.0:* app://* file://* tauri://*] OLLAMA_RUNNERS_DIR:C:\\Users\\Administrator\\AppData\\Local\\Programs\\Ollama\\ollama_runners OLLAMA_SCHED_SPREAD:false OLLAMA_TMPDIR: ROCR_VISIBLE_DEVICES:]"
time=2024-06-26T15:31:15.361+08:00 level=INFO source=images.go:730 msg="total blobs: 0"
time=2024-06-26T15:31:15.362+08:00 level=INFO source=images.go:737 msg="total unused blobs removed: 0"
time=2024-06-26T15:31:15.363+08:00 level=INFO source=routes.go:1111 msg="Listening on [::]:11434 (version 0.1.46)"
time=2024-06-26T15:31:15.365+08:00 level=INFO source=payload.go:44 msg="Dynamic LLM libraries [cpu cpu_avx cpu_avx2 cuda_v11.3 rocm_v5.7]"
time=2024-06-26T15:31:15.484+08:00 level=INFO source=amd_windows.go:65 msg="skipping rocm gfx compatibility check" HSA_OVERRIDE_GFX_VERSION=9.0.6
time=2024-06-26T15:31:16.212+08:00 level=INFO source=types.go:98 msg="inference compute" id=0 library=rocm compute=gfx906:sramecc-:xnack- driver=0.0 name="AMD Radeon VII" total="16.0 GiB" available="15.9 GiB"
[GIN] 2024/06/26 - 15:31:59 | 200 |            0s |       127.0.0.1 | HEAD     "/"
[GIN] 2024/06/26 - 15:32:34 | 201 |   20.6674284s |       127.0.0.1 | POST     "/api/blobs/sha256:08d6043f9b965d26fe8568c7b791d5b312eaaf09ce912d36defaca55f5cd711c"
[GIN] 2024/06/26 - 15:32:52 | 200 |   18.0231413s |       127.0.0.1 | POST     "/api/create"
[GIN] 2024/06/26 - 15:33:52 | 200 |            0s |       127.0.0.1 | HEAD     "/"
[GIN] 2024/06/26 - 15:33:52 | 200 |     22.6084ms |       127.0.0.1 | POST     "/api/show"
time=2024-06-26T15:33:53.561+08:00 level=INFO source=memory.go:309 msg="offload to rocm" layers.requested=-1 layers.model=33 layers.offload=33 layers.split="" memory.available="[15.9 GiB]" memory.required.full="6.0 GiB" memory.required.partial="6.0 GiB" memory.required.kv="256.0 MiB" memory.required.allocations="[6.0 GiB]" memory.weights.total="4.8 GiB" memory.weights.repeating="4.4 GiB" memory.weights.nonrepeating="411.0 MiB" memory.graph.full="164.0 MiB" memory.graph.partial="677.5 MiB"
time=2024-06-26T15:33:53.579+08:00 level=INFO source=server.go:368 msg="starting llama server" cmd="C:\\Users\\Administrator\\AppData\\Local\\Programs\\Ollama\\ollama_runners\\rocm_v5.7\\ollama_llama_server.exe --model C:\\Users\\Administrator\\.ollama\\models\\blobs\\sha256-08d6043f9b965d26fe8568c7b791d5b312eaaf09ce912d36defaca55f5cd711c --ctx-size 2048 --batch-size 512 --embedding --log-disable --n-gpu-layers 33 --parallel 1 --port 51536"
time=2024-06-26T15:33:53.646+08:00 level=INFO source=sched.go:382 msg="loaded runners" count=1
time=2024-06-26T15:33:53.647+08:00 level=INFO source=server.go:556 msg="waiting for llama runner to start responding"
time=2024-06-26T15:33:53.648+08:00 level=INFO source=server.go:594 msg="waiting for server to become available" status="llm server error"
INFO [wmain] build info | build=3171 commit="7c26775a" tid="28472" timestamp=1719387233
INFO [wmain] system info | n_threads=8 n_threads_batch=-1 system_info="AVX = 1 | AVX_VNNI = 0 | AVX2 = 0 | AVX512 = 0 | AVX512_VBMI = 0 | AVX512_VNNI = 0 | AVX512_BF16 = 0 | FMA = 1 | NEON = 0 | SVE = 0 | ARM_FMA = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 1 | SSE3 = 1 | SSSE3 = 1 | VSX = 0 | MATMUL_INT8 = 0 | LLAMAFILE = 1 | " tid="28472" timestamp=1719387233 total_threads=16
INFO [wmain] HTTP server listening | hostname="127.0.0.1" n_threads_http="15" port="51536" tid="28472" timestamp=1719387233
llama_model_loader: loaded meta data with 22 key-value pairs and 291 tensors from C:\Users\Administrator\.ollama\models\blobs\sha256-08d6043f9b965d26fe8568c7b791d5b312eaaf09ce912d36defaca55f5cd711c (version GGUF V3 (latest))
llama_model_loader: Dumping metadata keys/values. Note: KV overrides do not apply in this output.
llama_model_loader: - kv   0:                       general.architecture str              = llama
llama_model_loader: - kv   1:                               general.name str              = Llama-3
llama_model_loader: - kv   2:                          llama.block_count u32              = 32
llama_model_loader: - kv   3:                       llama.context_length u32              = 8192
llama_model_loader: - kv   4:                     llama.embedding_length u32              = 4096
llama_model_loader: - kv   5:                  llama.feed_forward_length u32              = 14336
llama_model_loader: - kv   6:                 llama.attention.head_count u32              = 32
llama_model_loader: - kv   7:              llama.attention.head_count_kv u32              = 8
llama_model_loader: - kv   8:                       llama.rope.freq_base f32              = 500000.000000
llama_model_loader: - kv   9:     llama.attention.layer_norm_rms_epsilon f32              = 0.000010
llama_model_loader: - kv  10:                          general.file_type u32              = 17
llama_model_loader: - kv  11:                           llama.vocab_size u32              = 128256
llama_model_loader: - kv  12:                 llama.rope.dimension_count u32              = 128
llama_model_loader: - kv  13:                       tokenizer.ggml.model str              = gpt2
llama_model_loader: - kv  14:                         tokenizer.ggml.pre str              = llama-bpe
llama_model_loader: - kv  15:                      tokenizer.ggml.tokens arr[str,128256]  = ["!", "\"", "#", "$", "%", "&", "'", ...
llama_model_loader: - kv  16:                  tokenizer.ggml.token_type arr[i32,128256]  = [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...
llama_model_loader: - kv  17:                      tokenizer.ggml.merges arr[str,280147]  = ["Ġ Ġ", "Ġ ĠĠĠ", "ĠĠ ĠĠ", "...
llama_model_loader: - kv  18:                tokenizer.ggml.bos_token_id u32              = 128000
llama_model_loader: - kv  19:                tokenizer.ggml.eos_token_id u32              = 128001
llama_model_loader: - kv  20:                    tokenizer.chat_template str              = {% set loop_messages = messages %}{% ...
llama_model_loader: - kv  21:               general.quantization_version u32              = 2
llama_model_loader: - type  f32:   65 tensors
llama_model_loader: - type q5_K:  193 tensors
llama_model_loader: - type q6_K:   33 tensors
time=2024-06-26T15:33:53.905+08:00 level=INFO source=server.go:594 msg="waiting for server to become available" status="llm server loading model"
llm_load_vocab: special tokens cache size = 256
llm_load_vocab: token to piece cache size = 0.8000 MB
llm_load_print_meta: format           = GGUF V3 (latest)
llm_load_print_meta: arch             = llama
llm_load_print_meta: vocab type       = BPE
llm_load_print_meta: n_vocab          = 128256
llm_load_print_meta: n_merges         = 280147
llm_load_print_meta: n_ctx_train      = 8192
llm_load_print_meta: n_embd           = 4096
llm_load_print_meta: n_head           = 32
llm_load_print_meta: n_head_kv        = 8
llm_load_print_meta: n_layer          = 32
llm_load_print_meta: n_rot            = 128
llm_load_print_meta: n_embd_head_k    = 128
llm_load_print_meta: n_embd_head_v    = 128
llm_load_print_meta: n_gqa            = 4
llm_load_print_meta: n_embd_k_gqa     = 1024
llm_load_print_meta: n_embd_v_gqa     = 1024
llm_load_print_meta: f_norm_eps       = 0.0e+00
llm_load_print_meta: f_norm_rms_eps   = 1.0e-05
llm_load_print_meta: f_clamp_kqv      = 0.0e+00
llm_load_print_meta: f_max_alibi_bias = 0.0e+00
llm_load_print_meta: f_logit_scale    = 0.0e+00
llm_load_print_meta: n_ff             = 14336
llm_load_print_meta: n_expert         = 0
llm_load_print_meta: n_expert_used    = 0
llm_load_print_meta: causal attn      = 1
llm_load_print_meta: pooling type     = 0
llm_load_print_meta: rope type        = 0
llm_load_print_meta: rope scaling     = linear
llm_load_print_meta: freq_base_train  = 500000.0
llm_load_print_meta: freq_scale_train = 1
llm_load_print_meta: n_ctx_orig_yarn  = 8192
llm_load_print_meta: rope_finetuned   = unknown
llm_load_print_meta: ssm_d_conv       = 0
llm_load_print_meta: ssm_d_inner      = 0
llm_load_print_meta: ssm_d_state      = 0
llm_load_print_meta: ssm_dt_rank      = 0
llm_load_print_meta: model type       = 8B
llm_load_print_meta: model ftype      = Q5_K - Medium
llm_load_print_meta: model params     = 8.03 B
llm_load_print_meta: model size       = 5.33 GiB (5.70 BPW) 
llm_load_print_meta: general.name     = Llama-3
llm_load_print_meta: BOS token        = 128000 '<|begin_of_text|>'
llm_load_print_meta: EOS token        = 128001 '<|end_of_text|>'
llm_load_print_meta: LF token         = 128 'Ä'
llm_load_print_meta: EOT token        = 128009 '<|eot_id|>'
ggml_cuda_init: GGML_CUDA_FORCE_MMQ:   no
ggml_cuda_init: CUDA_USE_TENSOR_CORES: yes
ggml_cuda_init: found 1 ROCm devices:
  Device 0: AMD Radeon VII, compute capability 9.0, VMM: no
llm_load_tensors: ggml ctx size =    0.30 MiB
llm_load_tensors: offloading 32 repeating layers to GPU
llm_load_tensors: offloading non-repeating layers to GPU
llm_load_tensors: offloaded 33/33 layers to GPU
llm_load_tensors:      ROCm0 buffer size =  5115.49 MiB
llm_load_tensors:        CPU buffer size =   344.44 MiB
llama_new_context_with_model: n_ctx      = 2048
llama_new_context_with_model: n_batch    = 512
llama_new_context_with_model: n_ubatch   = 512
llama_new_context_with_model: flash_attn = 0
llama_new_context_with_model: freq_base  = 500000.0
llama_new_context_with_model: freq_scale = 1
llama_kv_cache_init:      ROCm0 KV buffer size =   256.00 MiB
llama_new_context_with_model: KV self size  =  256.00 MiB, K (f16):  128.00 MiB, V (f16):  128.00 MiB
llama_new_context_with_model:  ROCm_Host  output buffer size =     0.50 MiB
llama_new_context_with_model:      ROCm0 compute buffer size =   258.50 MiB
llama_new_context_with_model:  ROCm_Host compute buffer size =    12.01 MiB
llama_new_context_with_model: graph nodes  = 1030
llama_new_context_with_model: graph splits = 2
time=2024-06-26T15:34:01.844+08:00 level=INFO source=server.go:594 msg="waiting for server to become available" status="llm server error"
time=2024-06-26T15:34:02.350+08:00 level=ERROR source=sched.go:388 msg="error loading llama server" error="llama runner process has terminated: exit status 0xc0000005 "
[GIN] 2024/06/26 - 15:34:02 | 500 |    9.5332306s |       127.0.0.1 | POST     "/api/chat"

**Comment by MrSteelRat** [comment]
Full log for experince https://pastebin.com/sB5LdD9h

**Comment by fofocx** [comment]
Another value "gfx906:sramecc-:xnack+" after installed AMD HIP SDK.
Is there a way to enable ecc?😂
server.log:
2024/06/28 19:33:47 routes.go:1064: INFO server config env="map[CUDA_VISIBLE_DEVICES: GPU_DEVICE_ORDINAL: HIP_VISIBLE_DEVICES: HSA_OVERRIDE_GFX_VERSION: OLLAMA_DEBUG:false OLLAMA_FLASH_ATTENTION:false OLLAMA_HOST:http://0.0.0.0:11434 OLLAMA_INTEL_GPU:false OLLAMA_KEEP_ALIVE: OLLAMA_LLM_LIBRARY: OLLAMA_MAX_LOADED_MODELS:1 OLLAMA_MAX_QUEUE:512 OLLAMA_MAX_VRAM:0 OLLAMA_MODELS:H:\\models OLLAMA_NOHISTORY:false OLLAMA_NOPRUNE:false OLLAMA_NUM_PARALLEL:1 OLLAMA_ORIGINS:[http://localhost https://localhost http://localhost:* https://localhost:* http://127.0.0.1 https://127.0.0.1 http://127.0.0.1:* https://127.0.0.1:* http://0.0.0.0 https://0.0.0.0 http://0.0.0.0:* https://0.0.0.0:* app://* file://* tauri://*] OLLAMA_RUNNERS_DIR:C:\\Users\\Administrator\\AppData\\Local\\Programs\\Ollama\\ollama_runners OLLAMA_SCHED_SPREAD:false OLLAMA_TMPDIR: ROCR_VISIBLE_DEVICES:]"
time=2024-06-28T19:33:47.704+08:00 level=INFO source=images.go:730 msg="total blobs: 7"
time=2024-06-28T19:33:47.705+08:00 level=INFO source=images.go:737 msg="total unused blobs removed: 0"
time=2024-06-28T19:33:47.705+08:00 level=INFO source=routes.go:1111 msg="Listening on [::]:11434 (version 0.1.47)"
time=2024-06-28T19:33:47.707+08:00 level=INFO source=payload.go:44 msg="Dynamic LLM libraries [cpu cpu_avx cpu_avx2 cuda_v11.3 rocm_v5.7]"
time=2024-06-28T19:33:47.838+08:00 level=WARN source=amd_windows.go:97 msg="amdgpu is not supported" gpu=0 gpu_type=gfx906:sramecc-:xnack+ library="C:\\Program Files\\AMD\\ROCm\\5.7\\bin" supported_types="[gfx1030 gfx1100 gfx1101 gfx1102 gfx906]"
time=2024-06-28T19:33:47.838+08:00 level=WARN source=amd_windows.go:99 msg="See https://github.com/ollama/ollama/blob/main/docs/troubleshooting.md for HSA_OVERRIDE_GFX_VERSION usage"
time=2024-06-28T19:33:47.897+08:00 level=INFO source=types.go:98 msg="inference compute" id=0 library=cpu compute="" driver=0.0 name="" total="31.9 GiB" available="20.6 GiB"

**Comment by dhiltgen** [comment]
Unfortunately with the latest ROCm v6 these cards are no longer supported on Windows.  I've updated our docs to reflect this in #5815

**Comment by MrSteelRat** [comment]
So, support for Radeon VII in ollama is not worth waiting for?

**Comment by miningnome** [comment]
Hi,

It's supposed the version 24.12.1 can be used for ROCm with Radeon VII. If you are on windows you shall do the wsl process.
