### ISSUE TITLE
ollama not show my model. 

### ISSUE THREAD

**Issue by tuantupharma** [ollama/ollama#4781]
### What is the issue?

ollama working well with chatbox but when i install open-webui at first it working well but after few day ollama forget all of my model. the model file still in my ssd but ollama not detect them!, i pull model again but one again ollama not detect them in 2 days

### OS

Windows

### GPU

Nvidia

### CPU

Intel

### Ollama version

0.1.41

**Comment by pdevine** [comment]
@tuantupharma sorry for the slow response in your issue. Are you still having the problem? Can you get a list of the files on the file system as well as the [logs](https://github.com/ollama/ollama/blob/main/docs/troubleshooting.md)?

**Comment by tuantupharma** [comment]
hmm, i think the bug is gone. i fixed is by just restart the windows system after update ollama and all model comeback.
