### ISSUE TITLE
How do I customize the number of layers to be loaded on GPU?

### ISSUE THREAD

**Issue by lingyezhixing** [ollama/ollama#4783]
I tried adding num_gpu parameters to the modelfile, but it didn't seem to work.
My graphics memory still has 1.4GB left, but I can't make use of it.
What makes me even more annoyed is that only one layer is placed on the CPU, but this greatly reduces the inference speed.

**Comment by dhiltgen** [comment]
Can you try setting num_gpu in the API request?
```
curl http://localhost:11434/api/generate -d '{
  "model": "myCustomModel",
  "prompt": "Why is the sky blue?",
  "stream": false, "options": {"num_gpu": 5}
}'
```

Then check `ollama ps` and the server log to see if it worked.  If the system isn't behaving properly, please share the logs and the repro scenario so we can try to understand what's going wrong.  If that does work, but the modelfile setting isn't working, please share a minimal modelfile that repro's the problem.
