### ISSUE TITLE
deepseek-v2 responding in Chinese by default

### ISSUE THREAD

**Issue by rb81** [ollama/ollama#4789]
### What is the issue?

deepseek-v2 seems to respond in Chinese only.

### OS

Linux

### GPU

Other

### CPU

Intel

### Ollama version

0.1.41

**Comment by jmorganca** [comment]
Hi @rb81 I believe this is how the lite version of the model was trained. I've gotten it to reply in English with system prompts. Will close this for now however do let me know if this isn't the case for the model elsewhere and I can revisit

**Comment by rb81** [comment]
@jmorganca - Thanks for the reply. Would you mind sharing how you got it to work in English? I've tried a variety of system prompts but seem to always get Chinese...

**Comment by randoentity** [comment]
I also only get Chinese with deepseek-v2:236b-chat-q4_0.  I've tried a custom system prompt and the standard "Canada" example messages. @jmorganca help is greatly appreciated :)

**Comment by djdookie** [comment]
For me the model answers english if ask in english if I just do ollama run "ollama run deepseek-coder-v2".
However if I use it on sourcecode in VSCode using the continue extension, then it always answers in chinese.
The deepseek-coder:6.7b-instruct model never did that. I have no idea how to solve that. The ollama template looks fine to me.

![grafik](https://github.com/ollama/ollama/assets/17240204/6df74eed-df56-4049-ba7a-60fac88a99dd)

**Comment by rb81** [comment]
@djdookie - I get the exact was getting Chinese all the time, then suddenly started getting only English now. I did pull the latest model, so perhaps something was fixed... Oddly enough, I noticed this when I started using Continue in VSCode as well...

**Comment by DavSimFel** [comment]
@djdookie - I have the same problem with continue.dev. Even with a system prompt it only works sometimes.

@jmorganca - I guess this is a a valid issue and should not be closed yet.

**Comment by jasalt** [comment]
Quantization related issue it seems, discussed at https://github.com/deepseek-ai/DeepSeek-Coder-V2/issues/12. All the variants here https://ollama.com/library/deepseek-coder-v2/tags I could run on ~12GB VRAM seem to be affected more or less.

**Comment by jmorganca** [comment]
Hi folks, we had a small correction to the template in https://ollama.com/library/deepseek-coder-v2 and https://ollama.com/library/deepseek-v2 - it should be fixed now and by default will answer in the prompt's language. Sorry about that!
