### ISSUE TITLE
Added the ability to configure maxvram per GPU when there are multiple GPUs

### ISSUE THREAD

**Issue by hamkido** [ollama/ollama#4792]
Current can config MaxVRAM, but can not config per gpu maxvram when have dual gpu.

**Comment by dhiltgen** [comment]
With 0.1.45 we'll now be aware of VRAM skew between multiple GPUs and should allocate the layers proportionally to what is available on each GPU.  While this doesn't address your feature request, hopefully you'll see better behavior on multiple GPUs with this new release.

**Comment by dhiltgen** [comment]
Please give the latest release a try and if you see it get the memory prediction incorrect between your skewed VRAM GPUs share your server log and I'll reopen the issue.
