### ISSUE TITLE
'Deepseek-V2' model output mix language

### ISSUE THREAD

**Issue by gigascake** [ollama/ollama#4807]
### What is the issue?

I used '16b-lite-chat-f16' (31GB) model.

This model inference speed more than  before vesion model.

But, Sometimes, output response context in chinese and mix request language.

and then continues output mix language.

this situation. using RAG, document upload, and then Querying, occur just Problem.

![image](https://github.com/ollama/ollama/assets/36724511/3f043b3c-7da0-4665-9cc5-a647fbc90f5d)

Check, 

Plz. the solution.

Os : Fedora 39
GPU : nvidia A4000 * 4
CPU : amd threadripper 7980x

Thanks. always.

### OS

Linux

### GPU

Nvidia

### CPU

AMD

### Ollama version

0.1.40

**Comment by gigascake** [comment]
May Be, multi-language not support problem.

**Comment by OldishCoder** [comment]
I am seeing similar weirdness with deepseek-v2:16b. Sometimes it will only generate in Chinese. Even if I ask it to generate in English.

**Comment by itsPreto** [comment]
I pulled [deepseek-v2:16b](https://ollama.com/library/deepseek-v2:16b) yesterday and literally have not been able to get it to stop generating in Chinese... But I've not had any issues using the model on their free inferencing server: https://chat.deepseek.com/

could this be a gguf-conversion issue? curious to see if anyone with sufficient hardware has been able to test the f16 version

**Comment by gigascake** [comment]
I have continuously tested it and there is no problem with the initial response. However, a problem arises in the second sentence. This is probably an issue where only Chinese is recognized as the memory context, and it becomes a problem if other languages ​​are in memory.

**Comment by jmorganca** [comment]
Hi folks, we had a small correction to the template in https://ollama.com/library/deepseek-coder-v2 and https://ollama.com/library/deepseek-v2 - it should be fixed now and by default will answer in the prompt's language. Sorry about that!
