### ISSUE TITLE
How to run with a specified gpu?

### ISSUE THREAD

**Issue by zyc1128** [ollama/ollama#4808]
### What is the issue?

I am ruuning a python script traing some model and there is another flask servive binded with ollama.In the script ,I set os.environ["CUDA_VISIBLE_DEVICES"] = "1".I want the flask servive binded with gpu "0",what shoud I do？

### OS

Windows

### GPU

Nvidia

### CPU

Intel

**Comment by MrSuddenJoy** [comment]
Pass GPU var as a parameter.

**Comment by dhiltgen** [comment]
GPU selection is described in our docs [here](https://github.com/ollama/ollama/blob/main/docs/gpu.md#gpu-selection)

This setting must be applied on the server - see docs [here](https://github.com/ollama/ollama/blob/main/docs/faq.md#how-do-i-configure-ollama-server)

**Comment by UQ-CVLab** [comment]
Hi @dhiltgen,

I am encountering a similar issue while running two separate programs on a workstation equipped with 4 Nvidia GPUs. Both programs utilize LLaMA3, and Ollama consistently directs both to the same GPU. This results in a noticeable decrease in response speed compared to running a single program.

I attempted to use CUDA_VISIBLE_DEVICES to allocate the second instance of LLaMA3 to an idle GPU, but it did not resolve the issue. Could you provide guidance on how to properly allocate the second LLaMA3 instance to a different GPU?

Thank you for your assistance.

**Comment by dhiltgen** [comment]
@UQ-CVLab can you explain your scenario a bit more?  How much VRAM do your GPUs have, and what size models are you trying to load.  The algorithm should distribute across the GPUs, unless there's asymmetry in the VRAM sizes.  I've filed #5773 to track improving the scheduling algorithm for that case which might be what you're experiencing.

**Comment by xiaobaishu0097** [comment]
Thank you, @dhiltgen, for your prompt assistance! I have used the wrong account to ask this question and might need to delete the previous message. 
Currently, my workstation has four 24GB RTX3090 GPUs, and I am trying to load the llama3:8b. When I start two separate processings, Ollama only loads the llama3 once and shares the same llama3 across two processings.

**Comment by dhiltgen** [comment]
The current Concurrency implementation will only load 1 copy of a given model per Ollama instance.  If you have multiple GPUs and want to run one copy of the model per GPU, for now, a workaround is to run separate Ollama instances on different ports, and use CUDA_VISIBLE_DEVICES to pin the instances to the specific GPUs.
