### ISSUE TITLE
"Server disconnected without sending a response" after ~60seconds.

### ISSUE THREAD

**Issue by michaelgloeckner** [ollama/ollama#4810]
### What is the issue?

I run mixtral model and using api/generate.
If I run a bigger prompt it returns "Server disconnected without sending a response."

I checked ollama logs and see:
[GIN] 2024/06/04 - 09:36:43 | 500 | 59.693208463s |    10.0.101.220 | POST     "/api/generate"

Is there a way to increase this kind of internal timeout?

I already tried setting timeout but it does not have an impact on this 
from ollama import Client
client = Client(host='OllamaServer', timeout=120)

### OS

Linux, Containerd, eks

### GPU

Nvidia

### CPU

AMD

### Ollama version

0.1.40

**Comment by michaelgloeckner** [comment]
> Dont containerize. Install on bare system.
How is docker causing this problem?
I am running ollama on eks with g5.4xlarge instance and gpu support.

**Comment by michaelgloeckner** [comment]
My decision is that I use eks cluster which has an amazon linux node, where inside ollama image is running.  At the end it is a ollama container running in linux (AmazonLinux) right?
BTW. Kubernetes is not pickable from the OS selection menu....

**Comment by MrSuddenJoy** [comment]
@michaelgloeckner Yes, its `ollama` container inside `Linux`.
Kubernetes may (and should) not be pickable, because its not OS, its software, so you can instal it after you have chosen OS.

**Comment by michaelgloeckner** [comment]
I enabled Debugging and get the attached logs.
One with a http 200 result and one with http 500 "Server disconnected without sending a response" result after 60 seconds.
[ollama_logs.txt](https://github.com/user-attachments/files/15574903/ollama_logs.txt)

Is there a way to adjust this 60seconds?

**Comment by michaelgloeckner** [comment]
As a temporary workaround I am using stream option now.

**Comment by amida47** [comment]
@michaelgloeckner got the same problem while running ollama in a codespaces, no api request goes above 60s, how did you fix this?
I used `curl -fsSL https://ollama.com/install.sh | sh` for installation.

**Comment by amida47** [comment]
> Dont containerize. Install on bare system.

@MrSuddenJoy why is that?

**Comment by michaelgloeckner** [comment]
@amida47 i am using the **stream=True** option like in the below code. This avoids the timeout in my case:

```
def generateAsStream(prompt, system=None, temperature=0.01):
    response = ""

    stop: Sequence[str] = ["[INST]", "[/INST]"]
    options = Options(temperature=temperature, stop=stop, num_ctx=4096)

    stream_response = client.generate('mixtral', prompt=prompt, options=options, system=system, stream=True)

    for chunk in stream_response:
        response+=chunk['response']
        
    return response
```

**Comment by ChenYiJing025** [comment]
I’ve tried the method above, but the issue persists. Any other suggestions or solutions would be greatly appreciated.
