### ISSUE TITLE
无法下载模型

### ISSUE THREAD

**Issue by yuchenwei28** [ollama/ollama#4812]
### What is the issue?

中国内地无法下载模型，严重影响正常使用

### OS

Windows

### GPU

Intel

### CPU

Intel

### Ollama version

0.1.41

**Comment by netspym** [comment]
Yes you can download it from China. the model is downloaded with mag link, it should not have regional issue.

**Comment by yuchenwei28** [comment]
C:\Users\17732>ollama run llava
pulling manifest
Error: Head "https://dd20bb891979d25aebc8bec07b2b3bbc.r2.cloudflarestorage.com/ollama/docker/registry/v2/blobs/sha256/17/170370233dd5c5415250a2ecd5c71586352850729062ccef1496385647293868/data?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=66040c77ac1b787c3af820529859349a%!F(MISSING)20240605%!F(MISSING)auto%!F(MISSING)s3%!F(MISSING)aws4_request&X-Amz-Date=20240605T115421Z&X-Amz-Expires=1200&X-Amz-SignedHeaders=host&X-Amz-Signature=61298b9464499330059cb28792eceeeea16c65d838b00eb7fa1f0ae4daafcfe1": dial tcp 104.18.8.90:443: i/o timeout

C:\Users\17732>ollama run llama2
pulling manifest
Error: Head "https://dd20bb891979d25aebc8bec07b2b3bbc.r2.cloudflarestorage.com/ollama/docker/registry/v2/blobs/sha256/89/8934d96d3f08982e95922b2b7a2c626a1fe873d7c3b06e8e56d7bc0a1fef9246/data?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=66040c77ac1b787c3af820529859349a%!F(MISSING)20240605%!F(MISSING)auto%!F(MISSING)s3%!F(MISSING)aws4_request&X-Amz-Date=20240605T114501Z&X-Amz-Expires=1200&X-Amz-SignedHeaders=host&X-Amz-Signature=4932281f371de251d6311542006332f7cf410765d242ef7013abcb4633c25500": dial tcp 104.18.9.90:443: i/o timeout

C:\Users\17732>ollama run gemma
pulling manifest
Error: Head "https://dd20bb891979d25aebc8bec07b2b3bbc.r2.cloudflarestorage.com/ollama/docker/registry/v2/blobs/sha256/ef/ef311de6af9db043d51ca4b1e766c28e0a1ac41d60420fed5e001dc470c64b77/data?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=66040c77ac1b787c3af820529859349a%!F(MISSING)20240605%!F(MISSING)auto%!F(MISSING)s3%!F(MISSING)aws4_request&X-Amz-Date=20240605T114229Z&X-Amz-Expires=1200&X-Amz-SignedHeaders=host&X-Amz-Signature=d1fff17a684274a976613c40011efc8b533706080f613110dcc519829f87a100": net/http: TLS handshake timeout
可是它不行啊

**Comment by TonyHuang6666** [comment]
我校园网裸连都没问题啊，甚至比挂梯子更快

**Comment by yuchenwei28** [comment]
C:\Users\17732>ollama run qwen2
pulling manifest
Error: pull model manifest: Get "https://registry.ollama.ai/v2/library/qwen2/manifests/latest": dial tcp 172.67.182.229:443: i/o timeout

**Comment by yuchenwei28** [comment]
ollama version is 0.1.42
Warning: client version is 0.1.38

**Comment by ytc0522** [comment]
确实无法下载，无论是否使用代理都无法下载

pulling manifest 
Error: pull model manifest: Get "https://registry.ollama.ai/v2/library/qwen/manifests/14b": net/http: TLS handshake timeout

**Comment by caseclose** [comment]
When I try to pull the deepseek-r1 model, I still can't download it successfully.

![Image](https://github.com/user-attachments/assets/06f1b68a-910a-4e07-9027-461d2371e809)

**Comment by AKMINSDC** [comment]
而且会有 wsarecv: An existing connection was forcibly closed by the remote host. 远程主机强行关闭连接的问题，我用的是校园网

**Comment by Kydon-ai** [comment]
有稳定的解决方法吗，现在？
