### ISSUE TITLE
Error: Head "http://127.0.0.1:11434/": dial tcp 127.0.0.1:11434: connectex: No connections could be made because the target machine actively refused them.

### ISSUE THREAD

**Issue by aledepaulaaa** [ollama/ollama#4815]
### What is the issue?

Good morning, does anyone know what this problem is?
I have already installed and downloaded the model correctly. I'm using phi3, but when running I get this error. I tried running other models and the error is the same. Did the service go down by any chance?
![erro_ollama](https://github.com/ollama/ollama/assets/88629170/812ef42a-7d32-4b77-905c-00e0368b94fa)

### OS

Windows

### GPU

AMD

### CPU

Intel

### Ollama version

 0.1.41

**Comment by dhiltgen** [comment]
Are you still experiencing this?  If so, can you upgrade?  If that doesn't clear it up, can you share the server log?

https://github.com/ollama/ollama/blob/main/docs/troubleshooting.md
