### ISSUE TITLE
Apple neural engine

### ISSUE THREAD

**Issue by EnderRobber101** [ollama/ollama#4817]
I was wondering if ollama will support Apple neural engine for faster computations in the future?

**Comment by thinkverse** [comment]
AFAIK and I've only been looking into ANE for about a week. It is currently not possible to use ANE outside or CoreML/Swift. The API is not public, even MLX doesn't support it, and that's Apple: https://github.com/ml-explore/mlx/issues/18

**Comment by qdrddr** [comment]
Duplicate
https://github.com/ollama/ollama/issues/3898

**Comment by pdevine** [comment]
Will close this since it's a dupe.
