### ISSUE TITLE
Error: llama runner process has terminated: signal: aborted (core dumped)

### ISSUE THREAD

**Issue by ignore1999** [ollama/ollama#4824]
### What is the issue?

When I run the MiniCPM-Llama3-V-2_5, I get an error:"Error: llama runner process has terminated: signal: aborted (core dumped)",This is the case for both version 0.1.39 and 0.1.41

### OS

Linux

### GPU

Nvidia

### CPU

Intel

### Ollama version

0.1.41

**Comment by imaxiaolong** [comment]
Me Too

**Comment by henryclw** [comment]
May I ask how did you pull and run the MiniCPM-Llama3-V-2_5? Would you mind telling the specify model name?

**Comment by ignore1999** [comment]
> May I ask how did you pull and run the MiniCPM-Llama3-V-2_5? Would you mind telling the specify model name?

Sure，you can pull by running “ollama pull hhao/openbmb-minicpm-llama3-v-2_5:q4_K_M“，but there is no official merge request to adapt this model, even in 0.1.41. You can compile the project, refer to: https://github.com/OpenBMB/ollama/tree/minicpm-v2.5/examples/minicpm-v2.5. If you compiled successfully on nvidia gpu, welcome to tell me your method.

**Comment by TonyHuang6666** [comment]
我这两天也一直在死磕这个模型，最终结果就是不管是WSL2还是Ubuntu 22.04都可以处理文本，但是就是不能分析图片，一旦载入图片，模型就会挂起，占着显存但不干活。不管是你发的那个hhao的库，还是我自己下载原始作者的gguf模型再加个Modelfile导入都是这个结果😭目前只看过mac能成功运行，Linux和docker都没成功的

**Comment by hmd78** [comment]
i have the same problem when pulling qwen2, Any idea?

**Comment by jmorganca** [comment]
Closing for https://github.com/ollama/ollama/issues/4900

**Comment by QCadjunct** [comment]
root@TwinTower1:/mnt/c/Users/thehitman# ollama run mistral-nemo

verifying sha256 digest
writing manifest
removing any unused layers
success
Error: llama runner process has terminated: signal: aborted

root@TwinTower1:/mnt/c/Users/thehitman# ollama list
NAME                    ID              SIZE    MODIFIED
mistral-nemo:latest     4b300b8c6a97    7.1 GB  2 minutes ago
llama3.1:latest         a23da2a80395    4.7 GB  42 hours ago
phi3:14b                1e67dff39209    7.9 GB  42 hours ago
gemma2:27b              53261bc9c192    15 GB   9 days ago
codestral:latest        fcc0019dcee9    12 GB   6 weeks ago

**Comment by calonye** [comment]
Same question.
`https://ollama.com/aiden_lu/minicpm-v2.6`
`ollama run aiden_lu/minicpm-v2.6:Q4_K_M`
