### ISSUE TITLE
Adapter doesnt work

### ISSUE THREAD

**Issue by namogg** [ollama/ollama#4825]
### What is the issue?

I have converted my adapter to GGML format and create ollama model sucessfully with this comman
ADAPTER downloads/ggml-adapter-model.bin
However when testing the model, the adapter have no affect on the model. 

### OS

Linux

### GPU

Nvidia

### CPU

Intel, AMD

### Ollama version

0.1.29

**Comment by pdevine** [comment]
@namogg I was just running into the same problem. Can you post the logs just so I can compare with what I've been seeing?
It seems like the adapter gets loaded into memory and then ignored.

**Comment by namogg** [comment]
nothing interesting with the logs, it just show that the adapter layer is created sucessfully. I haved to work around by merging the adapter with the hugging face model then convert it to GGUF. But i still want to use adapter with ollama.

**Comment by pdevine** [comment]
I've been struggling getting llama.cpp to work w/ any adapters at all. I'd like to be able to allow conversion from both NPZ and Safetensors, which I have the GGLA file being created, but unfortunately I haven't managed to get it to work quite yet. @namogg How are you creating the GGLA file?

**Comment by namogg** [comment]
Nevermind llama.cpp is also too buggy, i used unsloth to train and convert to GGUF sucessfully but it seems the GGUF model doesnt give correct answer. I also tried not using unsloth and using only hugging face but model cannot be merge and load (not enough Vram) therefore cannot be convert to GGUF. I am stuck now

**Comment by pdevine** [comment]
@namogg did you end up getting unstuck at all? I now have the NPZ file conversion working from MLX into GGLAs which can then be loaded. All of this is with LoRAs (no QLoRA yet).

**Comment by pdevine** [comment]
Let's track this in #4618
