### ISSUE TITLE
Ability to choose different installation location in Windows

### ISSUE THREAD

**Issue by nviraj** [ollama/ollama#4828]
Hi,
It would be good if we could change the installation path while installing using the Windows Installer. If it's already available in some way, please let me know.
Thanks!

**Comment by SYTBOTW** [comment]
After installing Ollama, locate the file directory and move the entire Ollama file to the target directory. Then, find the variable value of Ollama in the system environment variable and change it to the full path after the move. That's it

**Comment by nviraj** [comment]
Although, SYTBOTW alluded to the presence of an environment variable that points to the Ollama installation location, I couldn't really find any such variable. `OLLAMA_MODELS` exists, but it is to control where model blobs are placed.

I have found 2 working methods so far, documenting it in case it helps somebody. 

- Locate the file directory and move it to your desired location and add the new directory to your system path so that the Ollama executable can be found. 
- Use [winget](https://winget.run/) to install (One time) and update Ollama (Every time you need to update). Make sure you use the location flag for both commands. If not, the update will reset to the default location. 
  - `winget install -i -e --id Ollama.Ollama --location D:\Apps\Ollama`
  - `winget upgrade -i -e --id Ollama.Ollama --location D:\Apps\Ollama`

**Comment by dhiltgen** [comment]
Tracked via #2776
