### ISSUE TITLE
llama3:7b cache size set

### ISSUE THREAD

**Issue by ciscoivan** [ollama/ollama#4832]
![1](https://github.com/ollama/ollama/assets/55469637/440bb5f3-d605-4962-a895-3205d7c9d621)

I installed two NVIDIA RTX 2080 TI graphics cards in an experimental deployment and successfully ran the llama3:7b model. I want to know how to adjust the cache size.

thanks

**Comment by jmorganca** [comment]
Hi @ciscoivan thanks for the issue! What do you mean by cache size? The context window?

If you do mean the context window size, you can do this via the `num_ctx` option in the API or via `/set parameter num_ctx 8192` for example when using `ollama run`

Hope this helps - if not let me know and I can re-open the issue
