### ISSUE TITLE
Cannot pull models when http_proxy/HTTP_PROXY are set.

### ISSUE THREAD

**Issue by janukarhisa** [ollama/ollama#4834]
### What is the issue?

Our server is located behind a proxy. The environment variables for both the host and Docker daemon are set with `http_proxy`, `https_proxy`, `HTTP_PROXY`, and `HTTPS_PROXY` to apply proxy settings to all containers.

For testing purposes, I created a container using the following command:
```bash
docker run -d -v {host_path}:/root/.ollama ollama/ollama:latest
```

When I go inside the container and try to pull the Mistral model, I get the following error:
```
Error: something went wrong, please see the ollama server logs for details
```

However, if I unset the `http_proxy` and `HTTP_PROXY` environment variables, the pulling method works without any problem. What am I missing here?

### OS

Linux

### CPU

Intel

### Ollama version

0.1.41

**Comment by mxyng** [comment]
Ollama client uses HTTP to communicate with the server. If you've set HTTP_PROXY the container and are reusing it for the Ollama CLI, it'll forward the client requests through your proxy.
