### ISSUE TITLE
llama runner process has terminated: exit status 127

### ISSUE THREAD

**Issue by kruimol** [ollama/ollama#4836]
### What is the issue?

When i try running ollama run codestral or any other LLM, I keep getting the same status 127 error!
Is there a way to fix this?

I'm running EndeavourOs Arch linux.

### OS

Linux

### GPU

AMD

### CPU

AMD

### Ollama version

0.1.41

**Comment by pdevine** [comment]
@kruimol can you post the logs? What kind of system are you using?

**Comment by kruimol** [comment]
@pdevine,
Here are the logs of today!
The last error message it his:
`jun 06 13:15:54 gatekeeper ollama[1689]: time=2024-06-06T13:15:54.045+02:00 level=WARN source=amd_linux.go:48 msg="ollama recommends running the https://www.amd.com/en/support/linux-drivers" error="amdgpu version file missing: /sys/mod>
jun 06 13:15:54 gatekeeper ollama[1689]: time=2024-06-06T13:15:54.056+02:00 level=INFO source=amd_linux.go:301 msg="amdgpu is supported" gpu=0 gpu_type=gfx1102
jun 06 13:15:54 gatekeeper ollama[1689]: time=2024-06-06T13:15:54.057+02:00 level=INFO source=amd_linux.go:233 msg="unsupported Radeon iGPU detected skipping" id=1 total="512.0 MiB"
jun 06 13:15:54 gatekeeper ollama[1689]: time=2024-06-06T13:15:54.238+02:00 level=WARN source=sched.go:512 msg="gpu VRAM usage didn't recover within timeout" seconds=5.566086663`

And this are the session logs of today!
`jun 06 13:15:40 gatekeeper ollama[1689]: [GIN] 2024/06/06 - 13:15:40 | 200 |     551.871µs |       127.0.0.1 | HEAD     "/"
jun 06 13:15:40 gatekeeper ollama[1689]: [GIN] 2024/06/06 - 13:15:40 | 200 |     611.922µs |       127.0.0.1 | GET      "/api/tags"
jun 06 13:15:48 gatekeeper ollama[1689]: [GIN] 2024/06/06 - 13:15:48 | 200 |      22.292µs |       127.0.0.1 | HEAD     "/"
jun 06 13:15:48 gatekeeper ollama[1689]: [GIN] 2024/06/06 - 13:15:48 | 200 |    1.488752ms |       127.0.0.1 | POST     "/api/show"
jun 06 13:15:48 gatekeeper ollama[1689]: [GIN] 2024/06/06 - 13:15:48 | 200 |     452.135µs |       127.0.0.1 | POST     "/api/show"
jun 06 13:15:48 gatekeeper ollama[1689]: time=2024-06-06T13:15:48.194+02:00 level=WARN source=amd_linux.go:48 msg="ollama recommends running the http>
jun 06 13:15:48 gatekeeper ollama[1689]: time=2024-06-06T13:15:48.206+02:00 level=INFO source=amd_linux.go:301 msg="amdgpu is supported" gpu=0 gpu_ty>
jun 06 13:15:48 gatekeeper ollama[1689]: time=2024-06-06T13:15:48.206+02:00 level=INFO source=amd_linux.go:233 msg="unsupported Radeon iGPU detected >
jun 06 13:15:48 gatekeeper ollama[1689]: time=2024-06-06T13:15:48.418+02:00 level=INFO source=memory.go:133 msg="offload to gpu" layers.requested=-1 >
jun 06 13:15:48 gatekeeper ollama[1689]: time=2024-06-06T13:15:48.419+02:00 level=INFO source=memory.go:133 msg="offload to gpu" layers.requested=-1 >
jun 06 13:15:48 gatekeeper ollama[1689]: time=2024-06-06T13:15:48.419+02:00 level=INFO source=memory.go:133 msg="offload to gpu" layers.requested=-1 >
jun 06 13:15:48 gatekeeper ollama[1689]: time=2024-06-06T13:15:48.421+02:00 level=INFO source=server.go:341 msg="starting llama server" cmd="/tmp/oll>
jun 06 13:15:48 gatekeeper ollama[1689]: time=2024-06-06T13:15:48.421+02:00 level=INFO source=sched.go:338 msg="loaded runners" count=1
jun 06 13:15:48 gatekeeper ollama[1689]: time=2024-06-06T13:15:48.421+02:00 level=INFO source=server.go:529 msg="waiting for llama runner to start re>
jun 06 13:15:48 gatekeeper ollama[1689]: time=2024-06-06T13:15:48.421+02:00 level=INFO source=server.go:567 msg="waiting for server to become availab>
jun 06 13:15:48 gatekeeper ollama[1689]: /tmp/ollama278668274/runners/rocm_v60002/ollama_llama_server: error while loading shared libraries: libnuma.>
jun 06 13:15:48 gatekeeper ollama[1689]: time=2024-06-06T13:15:48.672+02:00 level=ERROR source=sched.go:344 msg="error loading llama server" error="l>
jun 06 13:15:48 gatekeeper ollama[1689]: [GIN] 2024/06/06 - 13:15:48 | 500 |  532.788804ms |       127.0.0.1 | POST     "/api/chat"
jun 06 13:15:48 gatekeeper ollama[1689]: time=2024-06-06T13:15:48.729+02:00 level=WARN source=amd_linux.go:48 msg="ollama recommends running the http>
jun 06 13:15:48 gatekeeper ollama[1689]: time=2024-06-06T13:15:48.737+02:00 level=INFO source=amd_linux.go:301 msg="amdgpu is supported" gpu=0 gpu_ty>
jun 06 13:15:48 gatekeeper ollama[1689]: time=2024-06-06T13:15:48.737+02:00 level=INFO source=amd_linux.go:233 msg="unsupported Radeon iGPU detected >
jun 06 13:15:49 gatekeeper ollama[1689]: time=2024-06-06T13:15:49.047+02:00 level=WARN source=amd_linux.go:48 msg="ollama recommends running the http>
jun 06 13:15:49 gatekeeper ollama[1689]: time=2024-06-06T13:15:49.059+02:00 level=INFO source=amd_linux.go:301 msg="amdgpu is supported" gpu=0 gpu_ty>
jun 06 13:15:49 gatekeeper ollama[1689]: time=2024-06-06T13:15:49.060+02:00 level=INFO source=amd_linux.go:233 msg="unsupported Radeon iGPU detected >
jun 06 13:15:49 gatekeeper ollama[1689]: time=2024-06-06T13:15:49.294+02:00 level=WARN source=amd_linux.go:48 msg="ollama recommends running the http>
jun 06 13:15:49 gatekeeper ollama[1689]: time=2024-06-06T13:15:49.306+02:00 level=INFO source=amd_linux.go:301 msg="amdgpu is supported" gpu=0 gpu_ty>
jun 06 13:15:49 gatekeeper ollama[1689]: time=2024-06-06T13:15:49.306+02:00 level=INFO source=amd_linux.go:233 msg="unsupported Radeon iGPU detected >
jun 06 13:15:51 gatekeeper ollama[1689]: time=2024-06-06T13:15:51.058+02:00 level=INFO source=amd_linux.go:233 msg="unsupported Radeon iGPU detected skipping" id=1 total="512.0 MiB"
jun 06 13:15:51 gatekeeper ollama[1689]: time=2024-06-06T13:15:51.296+02:00 level=WARN source=amd_linux.go:48 msg="ollama recommends running the https://www.amd.com/en/support/linux-drivers" error="amdgpu version file missing: /sys/mod>
jun 06 13:15:51 gatekeeper ollama[1689]: time=2024-06-06T13:15:51.309+02:00 level=INFO source=amd_linux.go:301 msg="amdgpu is supported" gpu=0 gpu_type=gfx1102
jun 06 13:15:51 gatekeeper ollama[1689]: time=2024-06-06T13:15:51.310+02:00 level=INFO source=amd_linux.go:233 msg="unsupported Radeon iGPU detected skipping" id=1 total="512.0 MiB"
jun 06 13:15:51 gatekeeper ollama[1689]: time=2024-06-06T13:15:51.544+02:00 level=WARN source=amd_linux.go:48 msg="ollama recommends running the https://www.amd.com/en/support/linux-drivers" error="amdgpu version file missing: /sys/mod>
jun 06 13:15:51 gatekeeper ollama[1689]: time=2024-06-06T13:15:51.556+02:00 level=INFO source=amd_linux.go:301 msg="amdgpu is supported" gpu=0 gpu_type=gfx1102
jun 06 13:15:51 gatekeeper ollama[1689]: time=2024-06-06T13:15:51.557+02:00 level=INFO source=amd_linux.go:233 msg="unsupported Radeon iGPU detected skipping" id=1 total="512.0 MiB"
jun 06 13:15:51 gatekeeper ollama[1689]: time=2024-06-06T13:15:51.794+02:00 level=WARN source=amd_linux.go:48 msg="ollama recommends running the https://www.amd.com/en/support/linux-drivers" error="amdgpu version file missing: /sys/mod>
jun 06 13:15:51 gatekeeper ollama[1689]: time=2024-06-06T13:15:51.806+02:00 level=INFO source=amd_linux.go:301 msg="amdgpu is supported" gpu=0 gpu_type=gfx1102
jun 06 13:15:51 gatekeeper ollama[1689]: time=2024-06-06T13:15:51.806+02:00 level=INFO source=amd_linux.go:233 msg="unsupported Radeon iGPU detected skipping" id=1 total="512.0 MiB"
jun 06 13:15:52 gatekeeper ollama[1689]: time=2024-06-06T13:15:52.044+02:00 level=WARN source=amd_linux.go:48 msg="ollama recommends running the https://www.amd.com/en/support/linux-drivers" error="amdgpu version file missing: /sys/mod>
jun 06 13:15:52 gatekeeper ollama[1689]: time=2024-06-06T13:15:52.056+02:00 level=INFO source=amd_linux.go:301 msg="amdgpu is supported" gpu=0 gpu_type=gfx1102
jun 06 13:15:52 gatekeeper ollama[1689]: time=2024-06-06T13:15:52.057+02:00 level=INFO source=amd_linux.go:233 msg="unsupported Radeon iGPU detected skipping" id=1 total="512.0 MiB"
jun 06 13:15:52 gatekeeper ollama[1689]: time=2024-06-06T13:15:52.296+02:00 level=WARN source=amd_linux.go:48 msg="ollama recommends running the https://www.amd.com/en/support/linux-drivers" error="amdgpu version file missing: /sys/mod>
jun 06 13:15:52 gatekeeper ollama[1689]: time=2024-06-06T13:15:52.307+02:00 level=INFO source=amd_linux.go:301 msg="amdgpu is supported" gpu=0 gpu_type=gfx1102
jun 06 13:15:52 gatekeeper ollama[1689]: time=2024-06-06T13:15:52.307+02:00 level=INFO source=amd_linux.go:233 msg="unsupported Radeon iGPU detected skipping" id=1 total="512.0 MiB"
jun 06 13:15:52 gatekeeper ollama[1689]: time=2024-06-06T13:15:52.544+02:00 level=WARN source=amd_linux.go:48 msg="ollama recommends running the https://www.amd.com/en/support/linux-drivers" error="amdgpu version file missing: /sys/mod>
jun 06 13:15:52 gatekeeper ollama[1689]: time=2024-06-06T13:15:52.556+02:00 level=INFO source=amd_linux.go:301 msg="amdgpu is supported" gpu=0 gpu_type=gfx1102
jun 06 13:15:52 gatekeeper ollama[1689]: time=2024-06-06T13:15:52.556+02:00 level=INFO source=amd_linux.go:233 msg="unsupported Radeon iGPU detected skipping" id=1 total="512.0 MiB"
jun 06 13:15:52 gatekeeper ollama[1689]: time=2024-06-06T13:15:52.799+02:00 level=WARN source=amd_linux.go:48 msg="ollama recommends running the https://www.amd.com/en/support/linux-drivers" error="amdgpu version file missing: /sys/mod>
jun 06 13:15:52 gatekeeper ollama[1689]: time=2024-06-06T13:15:52.811+02:00 level=INFO source=amd_linux.go:301 msg="amdgpu is supported" gpu=0 gpu_type=gfx1102
jun 06 13:15:52 gatekeeper ollama[1689]: time=2024-06-06T13:15:52.811+02:00 level=INFO source=amd_linux.go:233 msg="unsupported Radeon iGPU detected skipping" id=1 total="512.0 MiB"
jun 06 13:15:53 gatekeeper ollama[1689]: time=2024-06-06T13:15:53.044+02:00 level=WARN source=amd_linux.go:48 msg="ollama recommends running the https://www.amd.com/en/support/linux-drivers" error="amdgpu version file missing: /sys/mod>
jun 06 13:15:53 gatekeeper ollama[1689]: time=2024-06-06T13:15:53.056+02:00 level=INFO source=amd_linux.go:301 msg="amdgpu is supported" gpu=0 gpu_type=gfx1102
jun 06 13:15:53 gatekeeper ollama[1689]: time=2024-06-06T13:15:53.056+02:00 level=INFO source=amd_linux.go:233 msg="unsupported Radeon iGPU detected skipping" id=1 total="512.0 MiB"
jun 06 13:15:53 gatekeeper ollama[1689]: time=2024-06-06T13:15:53.297+02:00 level=WARN source=amd_linux.go:48 msg="ollama recommends running the https://www.amd.com/en/support/linux-drivers" error="amdgpu version file missing: /sys/mod>
jun 06 13:15:53 gatekeeper ollama[1689]: time=2024-06-06T13:15:53.309+02:00 level=INFO source=amd_linux.go:301 msg="amdgpu is supported" gpu=0 gpu_type=gfx1102
jun 06 13:15:53 gatekeeper ollama[1689]: time=2024-06-06T13:15:53.309+02:00 level=INFO source=amd_linux.go:233 msg="unsupported Radeon iGPU detected skipping" id=1 total="512.0 MiB"
jun 06 13:15:53 gatekeeper ollama[1689]: time=2024-06-06T13:15:53.527+02:00 level=WARN source=amd_linux.go:48 msg="ollama recommends running the https://www.amd.com/en/support/linux-drivers" error="amdgpu version file missing: /sys/mod>
jun 06 13:15:53 gatekeeper ollama[1689]: time=2024-06-06T13:15:53.539+02:00 level=INFO source=amd_linux.go:301 msg="amdgpu is supported" gpu=0 gpu_type=gfx1102
jun 06 13:15:53 gatekeeper ollama[1689]: time=2024-06-06T13:15:53.540+02:00 level=INFO source=amd_linux.go:233 msg="unsupported Radeon iGPU detected skipping" id=1 total="512.0 MiB"
jun 06 13:15:53 gatekeeper ollama[1689]: time=2024-06-06T13:15:53.738+02:00 level=WARN source=sched.go:512 msg="gpu VRAM usage didn't recover within timeout" seconds=5.066135349
jun 06 13:15:53 gatekeeper ollama[1689]: time=2024-06-06T13:15:53.790+02:00 level=WARN source=amd_linux.go:48 msg="ollama recommends running the https://www.amd.com/en/support/linux-drivers" error="amdgpu version file missing: /sys/mod>
jun 06 13:15:53 gatekeeper ollama[1689]: time=2024-06-06T13:15:53.800+02:00 level=INFO source=amd_linux.go:301 msg="amdgpu is supported" gpu=0 gpu_type=gfx1102
jun 06 13:15:53 gatekeeper ollama[1689]: time=2024-06-06T13:15:53.800+02:00 level=INFO source=amd_linux.go:233 msg="unsupported Radeon iGPU detected skipping" id=1 total="512.0 MiB"
jun 06 13:15:53 gatekeeper ollama[1689]: time=2024-06-06T13:15:53.989+02:00 level=WARN source=sched.go:512 msg="gpu VRAM usage didn't recover within timeout" seconds=5.316748367
jun 06 13:15:54 gatekeeper ollama[1689]: time=2024-06-06T13:15:54.045+02:00 level=WARN source=amd_linux.go:48 msg="ollama recommends running the https://www.amd.com/en/support/linux-drivers" error="amdgpu version file missing: /sys/mod>
jun 06 13:15:54 gatekeeper ollama[1689]: time=2024-06-06T13:15:54.056+02:00 level=INFO source=amd_linux.go:301 msg="amdgpu is supported" gpu=0 gpu_type=gfx1102
jun 06 13:15:54 gatekeeper ollama[1689]: time=2024-06-06T13:15:54.057+02:00 level=INFO source=amd_linux.go:233 msg="unsupported Radeon iGPU detected skipping" id=1 total="512.0 MiB"
jun 06 13:15:54 gatekeeper ollama[1689]: time=2024-06-06T13:15:54.238+02:00 level=WARN source=sched.go:512 msg="gpu VRAM usage didn't recover within timeout" seconds=5.566086663`

**Comment by lunatic-gh** [comment]
Exact same issue for me, with the exact same log messages.

The message `ollama recommends running the https://www.amd.com/en/support/linux-drivers"` isn't helpful in this case, as on arch you don't install amd drivers from the website. instead i ran `sudo pacman -S mesa lib32-mesa xf86-video-amdgpu vulkan-radeon lib32-vulkan-radeon mesa-vdpau lib32-mesa-vdpau libva-mesa-driver lib32-libva-mesa-driver` (as per archwiki)

**Comment by lunatic-gh** [comment]
Ha, found the issue.
Could fix it myself with `sudo pacman -S rocm-hip-sdk`, after which it ran perfectly. OP might wanna try this out as well.

**Comment by kruimol** [comment]
Ah, tank you. now it works!

**Comment by shubham-yadav2727** [comment]
i am getting the same error and i am running it in AWS linux ubuntu. still not found solution, please help.

**Comment by lunatic-gh** [comment]
> i am getting the same error and i am running it in AWS linux ubuntu. still not found solution, please help.

You need to find out how one installs amd's hip sdk on ubuntu. iirc that is included in the ubuntu package from amd's website, tho i might be wrong
