### ISSUE TITLE
Stop model without removing

### ISSUE THREAD

**Issue by alemian95** [ollama/ollama#4837]
Is it possible to have a command to clear the model from the memory without removing it?

**Comment by mili-tan** [comment]
Although there may not be a way to stop the model directly inside the Ollama CLI yet, but maybe you can try this:
`curl http://localhost:11434/api/generate -d '{"model": "llama3", "keep_alive": 0}'`

**Comment by pdevine** [comment]
@alemian95 I'm not 100% sure I understand the question, however, if you want to clear you conversation in the CLI, you can use the `/clear` command. If you want the model to unload from memory (but still be present on the disk), you can use the `curl` command that @mili-tan mention, or use `ollama run --keep-alive 0 <model> ""`.

LMK if that answers it.
