### ISSUE TITLE
Error: could not connect to ollama app, is it running?

### ISSUE THREAD

**Issue by yishubanku** [ollama/ollama#4849]
After downloading and installing, running the 'ollama list' command prompts this error.

OS
Windows 10 Professional

GPU
AMD

CPU
No response

Ollama version
ollama -v
Warning: could not connect to a running Ollama instance
Warning: client version is 0.1.41

ollama serve
2024/06/06 16:12:31 routes.go:1007: INFO server config env="map[OLLAMA_DEBUG:false OLLAMA_FLASH_ATTENTION:false OLLAMA_HOST: OLLAMA_KEEP_ALIVE: OLLAMA_LLM_LIBRARY: OLLAMA_MAX_LOADED_MODELS:1 OLLAMA_MAX_QUEUE:512 OLLAMA_MAX_VRAM:0 OLLAMA_MODELS: OLLAMA_NOHISTORY:false OLLAMA_NOPRUNE:false OLLAMA_NUM_PARALLEL:1 OLLAMA_ORIGINS:[http://localhost https://localhost http://localhost:* https://localhost:* http://127.0.0.1 https://127.0.0.1 http://127.0.0.1:* https://127.0.0.1:* http://0.0.0.0 https://0.0.0.0 http://0.0.0.0:* https://0.0.0.0:*] OLLAMA_RUNNERS_DIR:C:\\Users\\Administrator\\AppData\\Local\\Programs\\Ollama\\ollama_runners OLLAMA_TMPDIR:]"
time=2024-06-06T16:12:31.227+08:00 level=INFO source=images.go:729 msg="total blobs: 0"
time=2024-06-06T16:12:31.230+08:00 level=INFO source=images.go:736 msg="total unused blobs removed: 0"
time=2024-06-06T16:12:31.231+08:00 level=INFO source=routes.go:1053 msg="Listening on [::]:11434 (version 0.1.41)"
time=2024-06-06T16:12:31.232+08:00 level=INFO source=payload.go:44 msg="Dynamic LLM libraries [cpu_avx2 cuda_v11.3 rocm_v5.7 cpu cpu_avx]"
Exception 0xc0000005 0x8 0x270a0bd4470 0x270a0bd4470
PC=0x270a0bd4470
signal arrived during external code execution

runtime.cgocall(0x6a3d20, 0xc000069c08)
        runtime/cgocall.go:157 +0x3e fp=0xc000467120 sp=0xc0004670e8 pc=0x6393be
syscall.SyscallN(0x7ffe904f7790?, {0xc0003d0010?, 0x1?, 0x140fde0?})
        runtime/syscall_windows.go:544 +0x107 fp=0xc000467198 sp=0xc000467120 pc=0x69f247
github.com/ollama/ollama/gpu.(*HipLib).HipGetDeviceCount(0xc000472f90)
        github.com/ollama/ollama/gpu/amd_hip_windows.go:100 +0x7a fp=0xc000467248 sp=0xc000467198 pc=0xa381da
github.com/ollama/ollama/gpu.AMDGetGPUInfo()
        github.com/ollama/ollama/gpu/amd_windows.go:44 +0x91 fp=0xc0004677d8 sp=0xc000467248 pc=0xa387b1
github.com/ollama/ollama/gpu.GetGPUInfo()
        github.com/ollama/ollama/gpu/gpu.go:233 +0x725 fp=0xc000467ac0 sp=0xc0004677d8 pc=0xa3d025
github.com/ollama/ollama/server.Serve({0x178b6a0, 0xc000241620})
        github.com/ollama/ollama/server/routes.go:1078 +0x7bb fp=0xc000467c70 sp=0xc000467ac0 pc=0x114747b
github.com/ollama/ollama/cmd.RunServer(0xc0001a5400?, {0x1f57720?, 0x4?, 0x15eb6de?})
        github.com/ollama/ollama/cmd/cmd.go:979 +0x17c fp=0xc000467d58 sp=0xc000467c70 pc=0x11660dc
github.com/spf13/cobra.(*Command).execute(0xc000018608, {0x1f57720, 0x0, 0x0})
        github.com/spf13/cobra@v1.7.0/command.go:940 +0x882 fp=0xc000467e78 sp=0xc000467d58 pc=0x9db5e2
github.com/spf13/cobra.(*Command).ExecuteC(0xc000235808)
        github.com/spf13/cobra@v1.7.0/command.go:1068 +0x3a5 fp=0xc000467f30 sp=0xc000467e78 pc=0x9dbe25
github.com/spf13/cobra.(*Command).Execute(...)
        github.com/spf13/cobra@v1.7.0/command.go:992
github.com/spf13/cobra.(*Command).ExecuteContext(...)
        github.com/spf13/cobra@v1.7.0/command.go:985
main.main()
        github.com/ollama/ollama/main.go:11 +0x4d fp=0xc000467f50 sp=0xc000467f30 pc=0x116f78d
runtime.main()
        runtime/proc.go:271 +0x28b fp=0xc000467fe0 sp=0xc000467f50 pc=0x6713eb
runtime.goexit({})
        runtime/asm_amd64.s:1695 +0x1 fp=0xc000467fe8 sp=0xc000467fe0 pc=0x6a2561

goroutine 2 gp=0xc00005c700 m=nil [force gc (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
        runtime/proc.go:402 +0xce fp=0xc00005ffa8 sp=0xc00005ff88 pc=0x6717ee
runtime.goparkunlock(...)
        runtime/proc.go:408
runtime.forcegchelper()
        runtime/proc.go:326 +0xb8 fp=0xc00005ffe0 sp=0xc00005ffa8 pc=0x671678
runtime.goexit({})
        runtime/asm_amd64.s:1695 +0x1 fp=0xc00005ffe8 sp=0xc00005ffe0 pc=0x6a2561
created by runtime.init.6 in goroutine 1
        runtime/proc.go:314 +0x1a

goroutine 3 gp=0xc00005ca80 m=nil [GC sweep wait]:
runtime.gopark(0x1?, 0x0?, 0x0?, 0x0?, 0x0?)
        runtime/proc.go:402 +0xce fp=0xc000061f80 sp=0xc000061f60 pc=0x6717ee
runtime.goparkunlock(...)
        runtime/proc.go:408
runtime.bgsweep(0xc00003a070)
        runtime/mgcsweep.go:318 +0xdf fp=0xc000061fc8 sp=0xc000061f80 pc=0x65b89f
runtime.gcenable.gowrap1()
        runtime/mgc.go:203 +0x25 fp=0xc000061fe0 sp=0xc000061fc8 pc=0x650145
runtime.goexit({})
        runtime/asm_amd64.s:1695 +0x1 fp=0xc000061fe8 sp=0xc000061fe0 pc=0x6a2561
created by runtime.gcenable in goroutine 1
        runtime/mgc.go:203 +0x66

goroutine 4 gp=0xc00005cc40 m=nil [GC scavenge wait]:
runtime.gopark(0x10000?, 0x177d3a0?, 0x0?, 0x0?, 0x0?)
        runtime/proc.go:402 +0xce fp=0xc00006ff78 sp=0xc00006ff58 pc=0x6717ee
runtime.goparkunlock(...)
        runtime/proc.go:408
runtime.(*scavengerState).park(0x1ecb120)
        runtime/mgcscavenge.go:425 +0x49 fp=0xc00006ffa8 sp=0xc00006ff78 pc=0x659229
runtime.bgscavenge(0xc00003a070)
        runtime/mgcscavenge.go:658 +0x59 fp=0xc00006ffc8 sp=0xc00006ffa8 pc=0x6597d9
runtime.gcenable.gowrap2()
        runtime/mgc.go:204 +0x25 fp=0xc00006ffe0 sp=0xc00006ffc8 pc=0x6500e5
runtime.goexit({})
        runtime/asm_amd64.s:1695 +0x1 fp=0xc00006ffe8 sp=0xc00006ffe0 pc=0x6a2561
created by runtime.gcenable in goroutine 1
        runtime/mgc.go:204 +0xa5

goroutine 5 gp=0xc00005d180 m=nil [finalizer wait]:
runtime.gopark(0xc000063e48?, 0x643505?, 0xa8?, 0x1?, 0xc00005c000?)
        runtime/proc.go:402 +0xce fp=0xc000063e20 sp=0xc000063e00 pc=0x6717ee
runtime.runfinq()
        runtime/mfinal.go:194 +0x107 fp=0xc000063fe0 sp=0xc000063e20 pc=0x64f1c7
runtime.goexit({})
        runtime/asm_amd64.s:1695 +0x1 fp=0xc000063fe8 sp=0xc000063fe0 pc=0x6a2561
created by runtime.createfing in goroutine 1
        runtime/mfinal.go:164 +0x3d

goroutine 18 gp=0xc000084380 m=nil [GC worker (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
        runtime/proc.go:402 +0xce fp=0xc00006bf50 sp=0xc00006bf30 pc=0x6717ee
runtime.gcBgMarkWorker()
        runtime/mgc.go:1310 +0xe5 fp=0xc00006bfe0 sp=0xc00006bf50 pc=0x652285
runtime.goexit({})
        runtime/asm_amd64.s:1695 +0x1 fp=0xc00006bfe8 sp=0xc00006bfe0 pc=0x6a2561
created by runtime.gcBgMarkStartWorkers in goroutine 1
        runtime/mgc.go:1234 +0x1c

goroutine 6 gp=0xc0001d8a80 m=nil [GC worker (idle)]:
runtime.gopark(0xee991142dd0?, 0x0?, 0x0?, 0x0?, 0x0?)
        runtime/proc.go:402 +0xce fp=0xc000071f50 sp=0xc000071f30 pc=0x6717ee
runtime.gcBgMarkWorker()
        runtime/mgc.go:1310 +0xe5 fp=0xc000071fe0 sp=0xc000071f50 pc=0x652285
runtime.goexit({})
        runtime/asm_amd64.s:1695 +0x1 fp=0xc000071fe8 sp=0xc000071fe0 pc=0x6a2561
created by runtime.gcBgMarkStartWorkers in goroutine 1
        runtime/mgc.go:1234 +0x1c

goroutine 34 gp=0xc000482000 m=nil [GC worker (idle)]:
runtime.gopark(0xee991142dd0?, 0x0?, 0x0?, 0x0?, 0x0?)
        runtime/proc.go:402 +0xce fp=0xc000489f50 sp=0xc000489f30 pc=0x6717ee
runtime.gcBgMarkWorker()
        runtime/mgc.go:1310 +0xe5 fp=0xc000489fe0 sp=0xc000489f50 pc=0x652285
runtime.goexit({})
        runtime/asm_amd64.s:1695 +0x1 fp=0xc000489fe8 sp=0xc000489fe0 pc=0x6a2561
created by runtime.gcBgMarkStartWorkers in goroutine 1
        runtime/mgc.go:1234 +0x1c

goroutine 7 gp=0xc0001d8c40 m=nil [GC worker (idle)]:
runtime.gopark(0xee991142dd0?, 0x0?, 0x0?, 0x0?, 0x0?)
        runtime/proc.go:402 +0xce fp=0xc000485f50 sp=0xc000485f30 pc=0x6717ee
runtime.gcBgMarkWorker()
        runtime/mgc.go:1310 +0xe5 fp=0xc000485fe0 sp=0xc000485f50 pc=0x652285
runtime.goexit({})
        runtime/asm_amd64.s:1695 +0x1 fp=0xc000485fe8 sp=0xc000485fe0 pc=0x6a2561
created by runtime.gcBgMarkStartWorkers in goroutine 1
        runtime/mgc.go:1234 +0x1c

goroutine 19 gp=0xc000482380 m=3 mp=0xc000069008 [syscall]:
runtime.notetsleepg(0x1f58320, 0xffffffffffffffff)
        runtime/lock_sema.go:296 +0x31 fp=0xc00048bfa0 sp=0xc00048bf68 pc=0x641ad1
os/signal.signal_recv()
        runtime/sigqueue.go:152 +0x29 fp=0xc00048bfc0 sp=0xc00048bfa0 pc=0x69e249
os/signal.loop()
        os/signal/signal_unix.go:23 +0x13 fp=0xc00048bfe0 sp=0xc00048bfc0 pc=0x964093
runtime.goexit({})
        runtime/asm_amd64.s:1695 +0x1 fp=0xc00048bfe8 sp=0xc00048bfe0 pc=0x6a2561
created by os/signal.Notify.func1.1 in goroutine 1
        os/signal/signal.go:151 +0x1f

goroutine 20 gp=0xc000482540 m=nil [chan receive]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
        runtime/proc.go:402 +0xce fp=0xc000487f00 sp=0xc000487ee0 pc=0x6717ee
runtime.chanrecv(0xc0004f8540, 0x0, 0x1)
        runtime/chan.go:583 +0x3cd fp=0xc000487f78 sp=0xc000487f00 pc=0x63ba4d
runtime.chanrecv1(0x0?, 0x0?)
        runtime/chan.go:442 +0x12 fp=0xc000487fa0 sp=0xc000487f78 pc=0x63b652
github.com/ollama/ollama/server.Serve.func2()
        github.com/ollama/ollama/server/routes.go:1062 +0x3d fp=0xc000487fe0 sp=0xc000487fa0 pc=0x11475bd
runtime.goexit({})
        runtime/asm_amd64.s:1695 +0x1 fp=0xc000487fe8 sp=0xc000487fe0 pc=0x6a2561
created by github.com/ollama/ollama/server.Serve in goroutine 1
        github.com/ollama/ollama/server/routes.go:1061 +0x745

goroutine 21 gp=0xc000482700 m=nil [select]:
runtime.gopark(0xc000377f58?, 0x3?, 0x60?, 0x0?, 0xc000377e32?)
        runtime/proc.go:402 +0xce fp=0xc000377cb8 sp=0xc000377c98 pc=0x6717ee
runtime.selectgo(0xc000377f58, 0xc000377e2c, 0x0?, 0x0, 0x0?, 0x1)
        runtime/select.go:327 +0x725 fp=0xc000377dd8 sp=0xc000377cb8 pc=0x681c45
github.com/ollama/ollama/server.(*Scheduler).processPending(0xc00047e140, {0x178dfe0, 0xc00047e0f0})
        github.com/ollama/ollama/server/sched.go:102 +0xcf fp=0xc000377fb8 sp=0xc000377dd8 pc=0x114ae4f
github.com/ollama/ollama/server.(*Scheduler).Run.func1()
        github.com/ollama/ollama/server/sched.go:92 +0x1f fp=0xc000377fe0 sp=0xc000377fb8 pc=0x114ad5f
runtime.goexit({})
        runtime/asm_amd64.s:1695 +0x1 fp=0xc000377fe8 sp=0xc000377fe0 pc=0x6a2561
created by github.com/ollama/ollama/server.(*Scheduler).Run in goroutine 1
        github.com/ollama/ollama/server/sched.go:91 +0xb4

goroutine 22 gp=0xc0004828c0 m=nil [select]:
runtime.gopark(0xc00006df50?, 0x3?, 0x0?, 0x0?, 0xc00006dd52?)
        runtime/proc.go:402 +0xce fp=0xc00006dbe0 sp=0xc00006dbc0 pc=0x6717ee
runtime.selectgo(0xc00006df50, 0xc00006dd4c, 0x0?, 0x0, 0x0?, 0x1)
        runtime/select.go:327 +0x725 fp=0xc00006dd00 sp=0xc00006dbe0 pc=0x681c45
github.com/ollama/ollama/server.(*Scheduler).processCompleted(0xc00047e140, {0x178dfe0, 0xc00047e0f0})
        github.com/ollama/ollama/server/sched.go:214 +0xec fp=0xc00006dfb8 sp=0xc00006dd00 pc=0x114b9cc
github.com/ollama/ollama/server.(*Scheduler).Run.func2()
        github.com/ollama/ollama/server/sched.go:96 +0x1f fp=0xc00006dfe0 sp=0xc00006dfb8 pc=0x114ad1f
runtime.goexit({})
        runtime/asm_amd64.s:1695 +0x1 fp=0xc00006dfe8 sp=0xc00006dfe0 pc=0x6a2561
created by github.com/ollama/ollama/server.(*Scheduler).Run in goroutine 1
        github.com/ollama/ollama/server/sched.go:95 +0x110
rax     0x270e79aed90
rbx     0x270a0bd4470
rcx     0xcbb
rdx     0x6
rdi     0x270e7a7cb60
rsi     0x270e79aed90
rbp     0xcba
rsp     0xd7c1bfdf18
r8      0x2
r9      0x40
r10     0x2c0
r11     0x2b800000
r12     0x1
r13     0x270a0b14bf0
r14     0x270e7a73020
r15     0x270a0bd4470
rip     0x270a0bd4470
rflags  0x10202
cs      0x33
fs      0x53
gs      0x2b

**Comment by NasonZ** [comment]
Hey, did you manage to resole this error?
