### ISSUE TITLE
Probably I am missing something...

### ISSUE THREAD

**Issue by Zibri** [ollama/ollama#4862]
### What is the issue?

I created a file containing: ``FROM I:\models\Mistral-7b-Instruct-v0.3.f16.q6_k.gguf``

Then I did: `ollama create mistral file`
The model loaded.
then I did:
ollama run mistral

and If I say "Hello" it starts talking by itself introdfucing itself every time with a different identity.

Also, my GPU is an NVIDIA GTX 970M (which works with llama.cpp and opencl), but it's not apparently used.

### OS

Windows

### GPU

Nvidia

### CPU

Intel

### Ollama version

0.1.41

**Comment by Zibri** [comment]
Another example:
```
>>> ciao


"We're here because you wanted to learn how to paint, and I offered to help you," replied the woman with a
sigh. "You can't just give up after one try. Painting takes time and patience."

The young man looked at her with frustration in his eyes. "I've been trying for weeks now, and I still can't
make anything that looks decent. I don't have the talent for it."

"Talent is overrated," the woman said. "What you need is practice. Every great artist started out as a
beginner. You just have to keep trying and not give up."

The young man sighed again and looked back down at his canvas, still covered in splotches of unblended
paint. "I guess you're right," he said quietly. "But it's so hard."

"I know it is," the woman replied gently. "But remember why you wanted to learn how to paint in the first
place. What was it that drew you to it? That passion will carry you through the tough times."

The young man thought for a moment, then nodded slowly. "You're right," he said. "I just need to keep
going."

"That's the spirit!" the woman exclaimed, clapping her hands together. "Now let's get back to work and make
something amazing!"

The young man picked up his paintbrush and began to work on his canvas again, determined to improve. As they
worked side by side, the woman offered advice and encouragement, helping the young man to create a beautiful
painting that he could be proud of. It may have been difficult, but in the end, it was all worth it.

total duration:       1m42.4288454s
load duration:        1.6325ms
prompt eval count:    2 token(s)
prompt eval duration: 435.183ms
prompt eval rate:     4.60 tokens/s
eval count:           370 token(s)
eval duration:        1m41.988013s
eval rate:            3.63 tokens/s

```

**Comment by Zibri** [comment]
How can I do a normal inference as I do with llama.cpp ?

**Comment by Zibri** [comment]
Hmm I think I found the reason. Creating a model as I did the template is not taken from the model but must be specified.
So I added /set template [INST] {{ if .System }}{{ .System }} {{ end }}{{ .Prompt }} [/INST]
And the system prompt worked.

Now the problem I have is that it talks too much :D
I wonder what paremeter limits the length of the responses without truncating them...

**Comment by pdevine** [comment]
@Zibri you can use the `TEMPLATE` command in the Modelfile to specify the template, and you'll need to also add some stop parameters. It should look something like:

```
FROM I:\models\Mistral-7b-Instruct-v0.3.f16.q6_k.gguf
TEMPLATE [INST] {{ .System }} {{ .Prompt }} [/INST]
PARAMETER stop [inst]
PARAMETER stop [/INST]
```

HTH. I'll close out the issue, but feel free to keep commenting.

**Comment by AditiMondal1110** [comment]
mistral-large through ollama iS not working,has anyone faced the same issue ? (I am using RTX4000ada onn runpod.)
