### ISSUE TITLE
Exists a way of implements authentication with api-key on Ollama Client? 

### ISSUE THREAD

**Issue by claudiocassimiro** [ollama/ollama#4888]
With openAi client we can make this:

```
client = OpenAI(
    api_key=os.environ.get("OPENAI_API_KEY"),
)
```

why we can't make this with ollama client to?

Someone went make a Discord channel to implements something like this?

**Comment by jmorganca** [comment]
Hi @claudiocassimiro no API key is require to connect to Ollama - let me know if this helps. For custom auth see https://github.com/ollama/ollama/issues/1053
