### ISSUE TITLE
aya:35b-23-f16 erro

### ISSUE THREAD

**Issue by lymanzhao** [ollama/ollama#4892]
### What is the issue?

ollama run aya:35b-23-f16

Error: llama runner process has terminated: signal: aborted (core dumped) error:failed to create context with model '/home/ais/.ollama/models/blobs/sha256-6f800f35270cacdcbdd43e2b96991c7974907b859ab0efa0a91b1523724b7e43'

### OS

Linux

### GPU

Nvidia

### CPU

Intel

### Ollama version

0.1.38 and 0.1.41

**Comment by jmorganca** [comment]
Hi @lymanzhao that's a really big model to run at f16 precision (70GB+ of VRAM required) - do you know if you have that much memory between your GPU and system memory? Sorry about the error. I'll merge this with https://github.com/ollama/ollama/issues/4955
