### ISSUE TITLE
Error removing model

### ISSUE THREAD

**Issue by jmorganca** [ollama/ollama#4898]
### What is the issue?

```
ollama run wizardcoder:34b-python
ollama rm wizardcoder:34b-python
Error: remove /usr/share/ollama/.ollama/models/blobs/sha256-a168bedb9a09640289c5174690a6221adae48b75dc431a219923f052ef20d0af: no such file or directory
```

### OS

Linux

**Comment by rudrOwO** [comment]
I Can reproduce this issue on my machine.

**Comment by igorschlum** [comment]
@rudrOwO when jmorganca place an Issue, generally, he can reproduce it and fixe it as he is the founder on Ollama.

**Comment by mxyng** [comment]
@rudrOwO more data points are always welcome. Which model are you seeing this issue with?
