### ISSUE TITLE
Failed to get max tokens for LLM with name qwen2:7b-instruct-fp16 with ollama

### ISSUE THREAD

**Issue by wenlong1234** [ollama/ollama#4899]
### What is the issue?

utils.py 328 : Failed to get max tokens for LLM with name qwen2:7b-instruct-fp16. Defaulting to 4096.
                    api_server-1              | Traceback (most recent call last):
                    api_server-1              |   File "/app/danswer/llm/utils.py", line 318, in get_llm_max_tokens
                    api_server-1              |     model_obj = model_map[model_name]
                    api_server-1              |                 ~~~~~~~~~^^^^^^^^^^^^
                    api_server-1              | KeyError: 'qwen2:7b-instruct-fp16'

### GPU

AMD

### CPU

AMD

### Ollama version

0.1.41

**Comment by jmorganca** [comment]
Thanks for the issue. Make sure to download the model: `ollama pull qwen2:7b-instruct-fp16` - let me know if that doesn't fix it

**Comment by lucashaha** [comment]
sorry，it is not ollma problem，thanks。
