### ISSUE TITLE
Error: pull model manifest: ssh: no key found

### ISSUE THREAD

**Issue by 674316** [ollama/ollama#4901]
### What is the issue?

ollama pull vicuna
>>
pulling manifest
Error: pull model manifest: ssh: no key found

### OS

Windows

### GPU

Nvidia

### CPU

Intel

### Ollama version

ollama version is 0.1.41

**Comment by 674316** [comment]
2024/06/07 17:32:33 routes.go:1007: INFO server config env="map[OLLAMA_DEBUG:false OLLAMA_FLASH_ATTENTION:false OLLAMA_HOST: OLLAMA_KEEP_ALIVE: OLLAMA_LLM_LIBRARY: OLLAMA_MAX_LOADED_MODELS:1 OLLAMA_MAX_QUEUE:512 OLLAMA_MAX_VRAM:0 OLLAMA_MODELS: OLLAMA_NOHISTORY:false OLLAMA_NOPRUNE:false OLLAMA_NUM_PARALLEL:1 OLLAMA_ORIGINS:[http://localhost https://localhost http://localhost:* https://localhost:* http://127.0.0.1 https://127.0.0.1 http://127.0.0.1:* https://127.0.0.1:* http://0.0.0.0 https://0.0.0.0 http://0.0.0.0:* https://0.0.0.0:*] OLLAMA_RUNNERS_DIR:C:\\Users\\admin\\AppData\\Local\\Programs\\Ollama\\ollama_runners OLLAMA_TMPDIR:]"
time=2024-06-07T17:32:34.008+08:00 level=INFO source=images.go:729 msg="total blobs: 0"
time=2024-06-07T17:32:34.008+08:00 level=INFO source=images.go:736 msg="total unused blobs removed: 0"
time=2024-06-07T17:32:34.009+08:00 level=INFO source=routes.go:1053 msg="Listening on 127.0.0.1:11434 (version 0.1.41)"
time=2024-06-07T17:32:34.009+08:00 level=INFO source=payload.go:44 msg="Dynamic LLM libraries [cpu_avx cpu_avx2 cuda_v11.3 rocm_v5.7 cpu]"
time=2024-06-07T17:32:34.223+08:00 level=INFO source=types.go:71 msg="inference compute" id=GPU-b7b9745c-884e-03a1-4b88-b882bb50d3bd library=cuda compute=8.6 driver=12.2 name="NVIDIA GeForce RTX 3060 Ti" total="8.0 GiB" available="7.0 GiB"
[GIN] 2024/06/07 - 17:32:34 | 200 |            0s |       127.0.0.1 | HEAD     "/"
[GIN] 2024/06/07 - 17:32:34 | 404 |       512.4µs |       127.0.0.1 | POST     "/api/show"
[GIN] 2024/06/07 - 17:32:35 | 200 |     827.518ms |       127.0.0.1 | POST     "/api/pull"

**Comment by malteneuss** [comment]
Any idea what could be the issue? I'm running Ollama in NixOS after a fresh reinstall and it doesn't work anymore. Tried version 1.38 and 1.45.

**Comment by silviodonlic** [comment]
I opened id_ed25519 in VSC and saw a lot of symbols like a ? in a rhombus.
So I figured it was **_corrupted_** and created a new key using:
ssh-keygen -t rsa -b 4096 -C "my.email@gmail.com"

New key files were in my_user_folder/.ssh

Then I replaced old files:
- id_ed25519
- id_ed25519.pub

with newly generated (renaming them to match old names)
and it worked like a charm.

**Comment by pdevine** [comment]
@silviodonlic RSA keys aren't supported if you want to be able to push a model to ollama.com. The solution here is just to remove the two corrupted files and restart the ollama server which will automatically create new ed25519 keys (what @malteneuss did).

I would like to know how the keys got corrupted though. The keys are _supposed_ to be in PEM format which should be in plain text. They're also only created in one place, so I'm not quite sure how there could be a race condition there. I'm going to go ahead and close the issue since there's a simple work around, but if anyone can reproduce this I'm happy to reopen and try to trouble shoot.

**Comment by user2745** [comment]
I also got this same issue, running my OrangePi desktop PC

**Comment by tariqhawis** [comment]
I fixed this error as follows:
1. Copy ~/.ollama directory to /usr/share/ollama/
2. Restart the service: systemctl restart ollama
3. run again: ollama pull ...

**Comment by VladyslavSan** [comment]
Just run `ollama serve`, it will fail but in the meantime it will create a new keys and everything will work just fine.
