### ISSUE TITLE
Ollama model download fails on kubernetes

### ISSUE THREAD

**Issue by samyIO** [ollama/ollama#4913]
### What is the issue?

Im using the latest helmchart of ollama and deployed it to kubernetes. When i enter the pods shell and use "ollama pull <model>", it starts the download at fast pace (around 250Mbps) but suddenly drops to a very low rate when reaching the last GB of the download. Most of the time it ends with an error, that i dont understand. The Kubernetes side is fine my monitoring and network speed tests verified everything. Do you have an idea? Do you think this is caused by ollama itself? Never had this issue locally
![Bild](https://github.com/ollama/ollama/assets/65492678/eb4022a7-4957-4a40-b41a-b96d924da3ec)

### OS

Docker

### GPU

Nvidia

### CPU

Other

### Ollama version

0.33.0

**Comment by jmorganca** [comment]
Hi @samyIO would it be possible to upgrade to 0.1.42 - this should be fixed. Let me know if that's not the case. Thanks for the issue!
