### ISSUE TITLE
Request Ollama Web API to fetch all models data in the remote

### ISSUE THREAD

**Issue by edwinjhlee** [ollama/ollama#4914]
Is is possible that ollama officials provides API to fetch remote model data ?

---

I am developing a Ollama CLI. I currently use the data scraped from ollama website. If this API available, I can just request data using official API.

This is the demo:
https://www.x-cmd.com/mod/ollama

<img width="1494" alt="image" src="https://github.com/ollama/ollama/assets/4426319/04db018d-08f9-4e2d-bbb3-41077bbb0807">

**Comment by jmorganca** [comment]
Thanks for the issue. Merging with https://github.com/ollama/ollama/issues/1070

**Comment by edwinjhlee** [comment]
Impressive ...
