### ISSUE TITLE
need cogvlm2-llama3-chinese-chat

### ISSUE THREAD

**Issue by enryteam** [ollama/ollama#4915]
https://huggingface.co/THUDM/cogvlm2-llama3-chinese-chat-19B

thanks

**Comment by schizoposter** [comment]
You can **[convert the model yourself,](https://github.com/ollama/ollama/blob/main/docs/import.md)**

**Comment by enryteam** [comment]
尝试多次均失败，请官方上架该模型，谢谢

**Comment by enryteam** [comment]
@schizoposter
