### ISSUE TITLE
Fresh install.

### ISSUE THREAD

**Issue by paralyser** [ollama/ollama#4919]
Fresh install.
System synology .
Installed with both docker and portainer.
Wiped/restarted/updated/reinstalled several times. Tried around 10 (8888,8778,11434,11535,11636,11433 etc.. )different ports, but every port gives the same error( with different ports).
Specified ports, ( OLLAMA_HOST=0.0.0.0:11434 ) to every port, changed 0.0.0.0 to 127.0.0.1 also. Same errors
Error: listen tcp 0.0.0.0:11434: bind: address already in use. 
Have no idea how to fix it.

_Originally posted by @paralyser in https://github.com/ollama/ollama/issues/707#issuecomment-2155631712_

**Comment by paralyser** [comment]
Is a docker / install issue? found out, If i select host , and NOT BRIDGE at the installation, it will begin to work.

**Comment by jmorganca** [comment]
It seems that you might have a port conflict on port `11434` (this is the port Ollama uses). Did you install Ollama via the Linux install script? In which case you may want to turn that off so Docker can be exposed on port `11434`:

```
sudo systemctl stop ollama
```
