### ISSUE TITLE
ollama download时下载的server地址是开源的吗？在国内感觉不好拉，想弄个类似的

### ISSUE THREAD

**Issue by papandadj** [ollama/ollama#4923]

**Comment by taozhiyuai** [comment]
我速度拉满, 100MB/S

**Comment by jmorganca** [comment]
Hi there, I'm not quite sure what you are asking for specifically, but models are downloaded from ollama.com - see this existing issue for local model hosting https://github.com/ollama/ollama/issues/914 - hope this helps!
