### ISSUE TITLE
fail to upload models due to max try

### ISSUE THREAD

**Issue by taozhiyuai** [ollama/ollama#4926]
### What is the issue?

`pushing c165271d7cbb...  73% ▕████████████████       ▏  44 GB/ 61 GB  4.3 MB/s    1h3m
Error: max retries exceeded: Put "https://dd20bb891979d25aebc8bec07b2b3bbc.r2.cloudflarestorage.com/ollama/docker/registry/v2/repositories/taozhiyuai/qwen2-57b-a14b-instruct/_uploads/cb319ba7-5ab8-40c3-a59b-03a007ffbae6/data?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=66040c77ac1b787c3af820529859349a%!F(MISSING)20240607%!F(MISSING)auto%!F(MISSING)s3%!F(MISSING)aws4_request&X-Amz-Date=20240607T235721Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&partNumber=48&uploadId=AHVfUfgfMc11-7PxdRLFlN2yqnUV68oRPODmHTg-a_dG_1nK5pBAEcAFf7Jt-79U2UCiAWGFDI-cFvkNxjzWL23Ly7xfr6VkHhyZWUETuxPDm3ADSL8KM2P51ZZ-Vye1olRgYFzt2L6NhedUCxtrAogdpZKh6lGd25X25VLx7NOLr0V4Obd-W9w5HuPYyVIbegFqH8cHYrPbFbiso8zt8kzb3LwqINTnKF7IDzakHe5rzmztMAH-J5HI0Lu6ELbmS-k3qeZF4-Xwuf9rNp9jsBSkJOvkBbECUpt2FLKchLqT2uAVH4-zxRqVXu9UGkA-d-XzB4FglNJrk6fGd__EGRw&X-Amz-Signature=06249a03866edad37e421d5a34bf016714a2fcb46019545544c03dcdce29a470": write tcp 192.168.31.110:62212->104.18.9.90:443: write: broken pipe`

how to ignore max try.

### OS

macOS

### GPU

Apple

### CPU

Apple

### Ollama version

1.40

**Comment by taozhiyuai** [comment]
```
pushing c165271d7cbb... 100% ▕███████████████████████▏  61 GB                         
Error: 500: {"errors":[{"code":"UNKNOWN","message":"unknown error","detail":{"Path":"/docker/registry/v2/repositories/taozhiyuai/qwen2-57b-a14b-instruct/_uploads/1bf7af90-ba95-4e9d-8ec1-d4ced1f8096a/data","DriverName":"s3aws"}}]}
```


I AM F*ING CRAZY!

**Comment by igorschlum** [comment]
Hi @taozhiyuai can you update your ollama version to 0.1.42 and try again? I see that you are using Docker. Can you try without Docker?  What Memory do you have on your mac as I see that you are pushing a 61GB model.  it could be a memory issue. I have at my office a 192 GB Mac Station. I could try to reproduce this issue to see if it works with more memory.

**Comment by taozhiyuai** [comment]
not docker, I install from https://ollama.com/download/Ollama-darwin.zip

my Mac is m3 max 128g which is ok for my model. 

some versions of ollama raise upload issue. I have upgraded and trying.thx for help.

**Comment by taozhiyuai** [comment]
> Hi @taozhiyuai can you update your ollama version to 0.1.42 and try again? I see that you are using Docker. Can you try without Docker? What Memory do you have on your mac as I see that you are pushing a 61GB model. it could be a memory issue. I have at my office a 192 GB Mac Station. I could try to reproduce this issue to see if it works with more memory.


0.1.42 is ok. some previous version had the same issue, some not. I hope the upload is resumable.

**Comment by igorschlum** [comment]
If it's Ok with version 0.1.42 could you please close the Issue?
Thank you

**Comment by taozhiyuai** [comment]
> If it's Ok with version 0.1.42 could you please close the Issue? Thank you

but I hope upload is resumable in the future. 0.1.42 is ok. but I think new version in the future may not. previous version had the same issue. so please make uploading is resumable.

**Comment by igorschlum** [comment]
I agree that some problems went and came back, but Ollama is more stable at each version.
