### ISSUE TITLE
Cant see installed models

### ISSUE THREAD

**Issue by ahgsql** [ollama/ollama#4932]
### What is the issue?

I have 7 models installed and was using them till yesterday.

But now it re-tries to download them, even i have all manifests files and my blobs folder is over 18 GB.

After shutdown and restart of WSL, ollama is not running and i m trying with ollama serve cmd

### OS

Windows

### GPU

Nvidia

### CPU

Intel

### Ollama version

ollama version is 0.1.38

**Comment by igorschlum** [comment]
Hi @ahgsql could you try version 0.1.42 of Ollama? There was a lot of improvemzents in Windows version.

**Comment by scscgit** [comment]
I have version 0.2.8 running in Docker, and I had to quickly shutdown docker engine to reclaim internet bandwidth (to stop downloads). I saw one of the models had finished downloading. After I restarted the container, `ollama list` was empty, and after I started downloading the same models, all downloads started from scratch despite the Docker volume taking over 50GB. It would be great if the downloads automatically continued after restart...

**Comment by dhiltgen** [comment]
@scscgit if you cancel the client, not the server, then it will stop the download, and resume the next time you request.  If the server restarts, then we'll reset any incomplete downloads.

**Comment by igorschlum** [comment]
And if you pull them again, new files will replace partially downloaded ones.

@jmorganca 
Ollama could add  the .temp extension for temporary files.
This practice clearly indicates that the file is still in the process of being downloaded, preventing confusion with fully downloaded. In case of an interrupted download, it's easy to identify and remove incomplete files.
Using a standard extension like .temp helps maintain consistency across different downloads and applications.
