### ISSUE TITLE
Can't run ollama using cmd on Windows

### ISSUE THREAD

**Issue by ziarmandhost** [ollama/ollama#4940]
### What is the issue?

I can't run ollama using windows 11 terminal app:

![image](https://github.com/ollama/ollama/assets/30569343/9daecf0f-8662-48cb-8c5c-c00bcbb7fb5b)

But environment variable exists in "System variables":

![image](https://github.com/ollama/ollama/assets/30569343/de540c41-8133-408f-ad80-5c5e8d095114)

### OS

Windows

### GPU

Nvidia

### CPU

Intel

**Comment by ziarmandhost** [comment]
idk why, but it fixed when I discovered ollama.exe file was not present in C:\Users\MY_USER\AppData\Local\Programs\Ollama location. I asked in ollama discord to share this file with me. Copied it to this folder and it started work. Before that I tried: multiple restarts of laptop, reinstalls of ollama - nothing of this helped.

**Comment by s-andrianov** [comment]
So where can i get this file?

**Comment by Azkreg** [comment]
I fixed mine like this:
if anyone is still encountering the issue even though they added it to the system variables, open a terminal (admin) and add it to the system variables with this command:

setx /M PATH "%PATH%;C:\Users\USER\AppData\Local\Programs\Ollama"  

(don't forget to change the directory with your own.)
Open a new terminal and it should work

**Comment by ziarmandhost** [comment]
I just needed to add variable to windows PATH

> I ran the windows installer as an administrator and it worked?

**Comment by shoryajain300** [comment]
Doing this "setx /M PATH "%PATH%;C:\Users\USER\AppData\Local\Programs\Ollama" caused my entire system variables to be erased.
