### ISSUE TITLE
Cannot update ollama on windows through "restart to update"

### ISSUE THREAD

**Issue by TonyBlur** [ollama/ollama#4947]
### What is the issue?

cannot update ollama on windows through clicking "restart to update" at taskbar, it has no response

### OS

Windows

### GPU

AMD

### CPU

AMD

### Ollama version

0.1.41

**Comment by d-kleine** [comment]
Hm, restart with last update worked fine for me on Windows 10. Are you on 10 or 11?

**Comment by TonyBlur** [comment]
> Hm, restart with last update worked fine for me on Windows 10. Are you on 10 or 11?

Thanks for replying. I'm on Windows 11.

**Comment by d-kleine** [comment]
What's your ollama version right now? (`ollama -v` in the Terminal)

also see #4944 , maybe same issue?

**Comment by TonyBlur** [comment]
My current version is 0.1.41, and this issue also appeared last version. I do not think it's the same issue since my ollama never reestart it self.

**Comment by d-kleine** [comment]
I assume you mean the "system tray" in the lower right corner, not the taskbar. I think the best would be to take a screencast showing the problem in any case.

Take a look into the logs at *C:\Users\[username]\AppData\Local\Ollama*, especially `upgrade.log`, to see if there are any error messages printed.

**Comment by TonyBlur** [comment]
Yes I mean system tray actually, you're right, sorry for the confuse.
![image](https://github.com/ollama/ollama/assets/101348912/e674da04-396b-4e29-acfa-2c377bbcf39a)
![image](https://github.com/ollama/ollama/assets/101348912/765e5445-e38b-4273-98bc-03933d61276c)
I've checked `upgrade.log` as image above. I didn't see any error message, and the lastest log is from May 31st.

**Comment by TonyBlur** [comment]
> I assume you mean the "system tray" in the lower right corner, not the taskbar. I think the best would be to take a screencast showing the problem in any case.
> 
> Take a look into the logs at _C:\Users\[username]\AppData\Local\Ollama_, especially `upgrade.log`, to see if there are any error messages printed.

I think I found the reason at `app.log`.
"failed to register update available with tray: unable to set icon: This operation returned because the timeout period expired."
"upgrade attempt failed: no update downloads found"
![image](https://github.com/ollama/ollama/assets/101348912/189cb579-89c0-4688-90b9-2bfbc8a849d5)
I don't know if it is my network issue or due to other configuration problem.

**Comment by TonyBlur** [comment]
I think it would be better to show a popup window or something to warn me that message.

By the way, I found that using a system proxy maybe the true cause into this.

**Comment by d-kleine** [comment]
> By the way, I found that using a system proxy maybe the true cause into this.

Okay, cool 👍🏻 issue resolved (hopefully 🙂 ) ✔️

**Comment by TonyBlur** [comment]
Thanks to your help, I successfully updated to the latest version. Appreciate it ❤️

Maybe I could close this issue? Or looing into how to solve this proxy caused issue?

**Comment by d-kleine** [comment]
I think it's better to close this issue as it has been resolved. If other users have a similar issue, they will find this under "closed" in the Issues section of this repo or via google.

**Comment by pforhan** [comment]
hm, maybe I spoke too soon?  For some reason I had 2 or 3 ollama processes.  I killed all of them off, deleted all log files, and restarted and tried again, and this time it took.  I'm not sure if this is what has always been happening or what.

**Comment by d-kleine** [comment]
@pforhan Please try this if it fails again: https://github.com/ollama/ollama/issues/4944#issuecomment-2174521404
