### ISSUE TITLE
Ollama for Windows does not recognize amd 7600 gpu

### ISSUE THREAD

**Issue by jeffreysinclair** [ollama/ollama#4962]
### What is the issue?

I noticed that it is not using the amd GPU, as it presents the following error in the log:

time=2024-06-10T11:52:39.440-03:00 level=INFO source=amd_windows.go:90 msg="unsupported Radeon iGPU detected skipping" id=1 name="AMD Radeon(TM) Graphics" gfx=gfx1036
time=2024-06-10T11:52:39.496-03:00 level=INFO source=types.go:71 msg="inference compute" id=0 library=rocm compute=gfx1102 driver=0.0 name=**"AMD Radeon RX 7600" total="8.0** 

### OS

Windows

### GPU

AMD

### CPU

AMD

### Ollama version

Released v0.1.42

**Comment by dhiltgen** [comment]
Those log messages look normal, and we did correctly identify the discrete GPU.

What happens when you load a model, ideally one that fits in 8G?  What do you see in `ollama ps`?

**Comment by jeffreysinclair** [comment]
ollama ps
NAME            ID              SIZE    PROCESSOR       UNTIL
phi3:latest     64c1188f2485    3.8 GB  100% GPU        3 minutes from now

**Comment by jeffreysinclair** [comment]
Sorry, I thought the messages were errors

**Comment by dhiltgen** [comment]
It looks like it is running on your GPU, so I'll go ahead and close this.
