### ISSUE TITLE
OLLAMA_MODEL_DIR is not reflecting on MacOS

### ISSUE THREAD

**Issue by yusufaly** [ollama/ollama#4973]
### What is the issue?

I tried both the executable or home brew ollama and in both cases OLLAMA_MODEL_DIR is not reflecting. 
launchctl getenv OLLAMA_MODEL_DIR  does show the location and I presisted it on a plist file to work after restart. 
I have also tried the old school export OLLAMA_MODEL_DIR=  in the ~/.zshrc  file to no luck. 

Not sure what else to do. 

### OS

macOS

### GPU

Apple

### CPU

Apple

**Comment by pdevine** [comment]
Hey @yusufaly The env variable is `OLLAMA_MODELS`. You can get a full list of supported environment variables w/ `ollama serve -h`.
