### ISSUE TITLE
Please add GLM4 models

### ISSUE THREAD

**Issue by DK013** [ollama/ollama#5002]
Please add the GML-4-9B-Chat, GML-4-9B-Chat-1M and GML-4V-9B models. https://huggingface.co/THUDM/glm-4-9b-chat-1m/blob/main/README_en.md

Can't wait to test thes out
Thanks

**Comment by jmorganca** [comment]
Closing for https://github.com/ollama/ollama/issues/4826 - thanks for the issue!!

**Comment by DK013** [comment]
> Duplicate of #4826?

Thanks. I was hasty and didn't check for previous issues. My bad
