### ISSUE TITLE
How to prevent the model from automatically releasing after 5 minutes when requesting an OpenAI package?

### ISSUE THREAD

**Issue by GoEnthusiast** [ollama/ollama#5013]
from openai import OpenAI

client = OpenAI(
    base_url='http://localhost:11434/v1/',

    # required but ignored
    api_key='ollama',
)

chat_completion = client.chat.completions.create(
    messages=[
        {
            'role': 'user',
            'content': 'Say this is a test',
        }
    ],
    model='llama3',
)

In this code, how should I set the "keep alive": -1 request parameter to prevent the model from being released without a request for 5 minutes?

**Comment by JerrettDavis** [comment]
The default `keep_alive` or `Duration` for Ollama is 5 minutes. To extend this you have to pass in a new `keep_alive` to the request. In your example you're using the OpenAI library, and this library unfortunately does not have support setting a custom timeout. As such, when the Ollama OpenAI middleware is used to process the request, the default `5m` timeout is used for all requests. 

If you need to drive this functionality separately, it should be possible to introduce a new environment variable (like `OLLAMA_OPENAI_KEEPALIVE`. The existing OpenAI middleware would need to be adjusted to properly set the keep alive based on the new environment variable here: https://github.com/ollama/ollama/blob/c69bc19e46bf40b24518444cd6754453ac41cdd0/openai/openai.go#L285-L317

**Comment by GoEnthusiast** [comment]
> Ollama 的默认超时时间`keep_alive`为`Duration`5 分钟。要延长此时间，您必须`keep_alive`向请求传入一个新值。在您的示例中，您使用的是 OpenAI 库，但遗憾的是，此库不支持设置自定义超时。因此，当使用 Ollama OpenAI 中间件处理请求时，`5m`所有请求均使用默认超时。
> 
> 如果您需要单独驱动此功能，则应该可以引入一个新的环境变量（如`OLLAMA_OPENAI_KEEPALIVE`。现有的 OpenAI 中间件需要进行调整，以根据此处的新环境变量正确设置保持活动：
> 
> https://github.com/ollama/ollama/blob/c69bc19e46bf40b24518444cd6754453ac41cdd0/openai/openai.go#L285-L317

Okay, thank you very much for your guidance. I'll give it a try now. Thank you again

**Comment by GoEnthusiast** [comment]
> The default `keep_alive` or `Duration` for Ollama is 5 minutes. To extend this you have to pass in a new `keep_alive` to the request. In your example you're using the OpenAI library, and this library unfortunately does not have support setting a custom timeout. As such, when the Ollama OpenAI middleware is used to process the request, the default `5m` timeout is used for all requests.
> 
> If you need to drive this functionality separately, it should be possible to introduce a new environment variable (like `OLLAMA_OPENAI_KEEPALIVE`. The existing OpenAI middleware would need to be adjusted to properly set the keep alive based on the new environment variable here:
> 
> https://github.com/ollama/ollama/blob/c69bc19e46bf40b24518444cd6754453ac41cdd0/openai/openai.go#L285-L317

Okay, thank you very much for your guidance. I'll give it a try now. Thank you again

**Comment by pdevine** [comment]
You can also call `ollama serve` with the `OLLAMA_KEEP_ALIVE` env variable. This is covered in the [FAQ](https://github.com/ollama/ollama/blob/main/docs/faq.md#how-do-i-keep-a-model-loaded-in-memory-or-make-it-unload-immediately). I'll go ahead and close the issue.
