### ISSUE TITLE
Error: llama runner process no longer running: -1 error:check_tensor_dims: tensor 'output.weight' not found

### ISSUE THREAD

**Issue by isanwenyu** [ollama/ollama#5015]
### What is the issue?

ollama run qwen2 work well 
but 
ollama run qwen2:1.5b        
**Error: llama runner process no longer running: -1 error:check_tensor_dims: tensor 'output.weight' not found**

### OS

macOS

### GPU

Intel

### CPU

Intel

### Ollama version

0.1.32

**Comment by nilayg99** [comment]
Can you please share the ollama.yaml file details ?

**Comment by isanwenyu** [comment]
I don't have this file. Where is the file path in macOS?

**Comment by nilayg99** [comment]
You can search for the ollama.yaml file using the find command in the Terminal.
# Search in the home directory
find ~ -name "ollama.yaml"

**Comment by dhiltgen** [comment]
Support for this model was added after version 0.1.32.  Please upgrade and it should work.
