### ISSUE TITLE
NeuralDaredevil-8B-abliterated

### ISSUE THREAD

**Issue by deadmeu** [ollama/ollama#5020]
[mlabonne/NeuralDaredevil-8B-abliterated](https://huggingface.co/mlabonne/NeuralDaredevil-8B-abliterated) (or [QuantFactory/NeuralDaredevil-8B-abliterated-GGUF](https://huggingface.co/QuantFactory/NeuralDaredevil-8B-abliterated-GGUF)) is one of the highest ranked (and currently the highest ranked uncensored) model according to [this leaderboard](https://huggingface.co/spaces/mlabonne/Yet_Another_LLM_Leaderboard).

**Comment by lstep** [comment]
Just use the search input box at the top of the website, not the one on the library/models page. You'll find two (one from me :rofl:):

- https://ollama.com/lstep/neuraldaredevil-8b-abliterated
- https://ollama.com/closex/neuraldaredevil-8b-abliterated
