### ISSUE TITLE
DeepSeek-V2-Lite-Chat - ERROR [validate_model_chat_template] The chat template comes with this model is not yet supported

### ISSUE THREAD

**Issue by OldishCoder** [ollama/ollama#5023]
### What is the issue?

When I load DeepSeek-V2 I see this message:
`ERROR [validate_model_chat_template] The chat template comes with this model is not yet supported, falling back to chatml. This may cause the model to output suboptimal responses | tid="139815279423488" timestamp=1718280244` 

I do not know if it's related, but on inference the model sometimes, randomly (?), starts generating exclusively in Chinese, even if I ask it to generate the response in English.

### OS

WSL2

### GPU

Nvidia

### CPU

Intel

### Ollama version

git HEAD from June 11, 2024

**Comment by jmorganca** [comment]
Hi @OldishCoder this won't affect inference since templating happens ahead of the request being sent down this codepath. Will work on making sure this error doesn't show up
