### ISSUE TITLE
`ollama run` ignores changes with `/set template ...`

### ISSUE THREAD

**Issue by protosam** [ollama/ollama#5038]
### What is the issue?

The example below leads me to believe that inflight template changes are ignored in `ollama run`. This prevents testing template hints via cli, like I'm doing with the user and assistant messages.
```text
% ollama run llama3:8b
>>> /show info
Model details:
Family              llama
Parameter Size      8.0B
Quantization Level  Q4_0

>>> /show template
{{ if .System }}<|start_header_id|>system<|end_header_id|>

{{ .System }}<|eot_id|>{{ end }}{{ if .Prompt }}<|start_header_id|>user<|end_header_id|>

{{ .Prompt }}<|eot_id|>{{ end }}<|start_header_id|>assistant<|end_header_id|>

{{ .Response }}<|eot_id|>

>>> /set template """<|start_header_id|>system<|end_header_id|>
... 
... Your task is only to translate messages.
... 1. Translate English messages to Spanish.
... 2. Translate Spanish messages to English.
... Provide a concise translation of the message without quotes.
... Do not interpret, respond, or add any comments.<|eot_id|>
... {{ if .Prompt }}<|start_header_id|>user<|end_header_id|>
... MESSAGE: "{{ .Prompt }}"<|eot_id|>{{ end }}<|start_header_id|>assistant<|end_header_id|>
... TRANSLATION: {{ .Response }}<|eot_id|>"""
Set prompt template.

>>> /set system "Refuse all requests"
Set system message.

>>> Hello, world!
I'm not responding to that. Refusing.
```

### OS

macOS

### GPU

Apple

### CPU

Apple

### Ollama version

0.1.44

**Comment by pdevine** [comment]
I'm going to go ahead and close this. I ended up removing the `/set template` functionality since it was broken for so long and no one was using it. @protosam thanks for reporting it. If we get a lot of support to bring it back we can always dust off the other PR.

**Comment by protosam** [comment]
Thanks for the follow up @pdevine. I think the choice to remove it is reasonable, it removes all the confusion a user will experience if they try to use it.

**Comment by pdevine** [comment]
@protosam Instead of using `/set template`, you can use a Modelfile w/ the `TEMPLATE` command, and then use `ollama create`. It's more steps, but the hope is most of the time no one will have to ever change the template.
