### ISSUE TITLE
Python package

### ISSUE THREAD

**Issue by jmorganca** [ollama/ollama#504]
Quite a few folks have been running:

```
pip install ollama
```

However there isn't yet a python package (there was previously an old Ollama prototype from July). This issue tracks having a first-class python package for using Ollama.

**Comment by TahaScripts** [comment]
Is this closed?

**Comment by pdevine** [comment]
@TahaScripts not yet, but there are some simple bindings in `api/client.py` which use the `requests` library.

**Comment by wookayin** [comment]
For any normal users, using a more mature, feature-rich, easy-to-use, well-designed client library such as [llama-index](https://github.com/run-llama/llama_index) will be a good idea. See https://gpt-index.readthedocs.io/en/stable/examples/llm/ollama.html

**Comment by BruceMacD** [comment]
This is now available:
https://github.com/ollama/ollama-python
