### ISSUE TITLE
qwen2 model error

### ISSUE THREAD

**Issue by misi0202** [ollama/ollama#5056]
### What is the issue?

I'm try to use Qwen2-7b model by ollama(ollama run qwen2) , but meet timeout error by POST /api/compete, timed out occured.When I POST /api/chat,it can return reply error code like GGGGGGGGG, If the ollama don't support qwen2?

**Comment by alwqx** [comment]
Hi, Which ollama version you use? If the ollama version is < v0.1.42, you'd better upgrade to the latest ollama. This problem has been fixed in https://github.com/ollama/ollama/releases/tag/v0.1.42

refer https://github.com/ollama/ollama/issues/4907#issuecomment-2155671605

**Comment by misi0202** [comment]
Tks, I missed this question when I search, I will have a quick reply after updating Ollama.

**Comment by wgong** [comment]
`qwen2` works well now after updating Ollama, Thanks

**Comment by Speedway1** [comment]
What hardware are you running on ? I have seen that on my machine with 2 x AMD Radeon 7900 XTX cards, the 70B model puts out a load of GGGGGs or some other garbage, however on the smaller 7B model, it doesn't. However the 7B loads onto only 1 graphics card, not both.

This might be a fault in the AMD multi card usage. Llamacpp doesn't have this problem, runs perfectly. SO it's Ollama that seems to have this issue.

**Comment by wgong** [comment]
@Speedway1 I have 1 GPU (8GB vRAM) 
![image](https://github.com/ollama/ollama/assets/329928/fe6d4812-1a37-4244-8374-8504b370d5e4)
