### ISSUE TITLE
Ollama doesn't start in Docker!

### ISSUE THREAD

**Issue by samanthacarapathy** [ollama/ollama#5061]
### What is the issue?

Hi guys, I'm trying to deploy Ollama to Hugging Face space using the Docker SDK. I've added this Git repo to Hugging Face since spaces are hosted on the Hugging Face Hub as Git repo and using this Dockerfile without any changes but, it keeps building. I could never get ollama to successfully running. I'm using amd64 architecture and no GPU can someone resolve this issue?

### OS

Docker

### CPU

AMD

### Ollama version

Latest

**Comment by dhiltgen** [comment]
Can you share more logs or output so we can understand what's going wrong?

Does the `docker build` fail?  If so, can you share your Dockerfile and the docker build failure log?

Does it fail to `docker run`?  If so, can you share the logs of the container?

**Comment by dhiltgen** [comment]
If you're still having problems getting it to work, please share the information above and I'll reopen the issue
