### ISSUE TITLE
Timeout for long generation

### ISSUE THREAD

**Issue by slavonnet** [ollama/ollama#5081]
### What is the issue?

https://github.com/ollama/ollama-js/issues/103

After 5 minutes of execution, 500 error is received. There is no way to increase the time. I use `stream: false`. 
`keepalive: 15m` and env `OLLAMA_KEEP_ALIVE=15m` does not help

```
июн 16 17:43:34 ai ollama[3733311]: [GIN] 2024/06/16 - 17:43:34 | 500 |          5m1s |       127.0.0.1 | POST     "/api/chat"
```

### OS

Linux

### GPU

Nvidia

### CPU

Intel

### Ollama version

0.1.45-rc1

**Comment by slavonnet** [comment]
i found parametr in llama.cpp
```
-to N, --timeout N: Server read/write timeout in seconds. Default 600
```

**Comment by hopperelec** [comment]
600 seconds is 10 minutes, though, and I don't see anywhere where Ollama is overriding this

**Comment by slavonnet** [comment]
OK, what are the options to fix the 5 minute limit?

**Comment by slavonnet** [comment]
i have 3 x 4060ti 16gb and try run Mixtral 8x22b model (half run on gpu and half on cpu)

**Comment by slavonnet** [comment]
https://github.com/ollama/ollama/blob/89c79bec8cf7a7b04f761fcc5306d2edf47a4164/llm/ext_server/httplib.h#L26

**Comment by slavonnet** [comment]
https://github.com/ollama/ollama/pull/5084

**Comment by dhiltgen** [comment]
This was most likely a load timeout.  We added a new env var `OLLAMA_LOAD_TIMEOUT` to adjust this timeout for systems that take longer than 5m to load the model.

**Comment by SegFaulty** [comment]
After investigating on this isseue, here a maybe helpfully comment:
 
If you run bigger models on consumer hardware, you will instant discover the hardcoded 5 Minute time out for non streaming requests.

Our Solution to handle long running (like 10 minutes) requests: 
- stream=true,  
- collect all parts in the low level api request method (curl has a callback option (writefunction) to concate it relative easy)  
- return it like a one shot request response.
