### ISSUE TITLE
`ollama list` shows empty list of models

### ISSUE THREAD

**Issue by DoLife** [ollama/ollama#5082]
### What is the issue?

Hi

My models no longer load.
When i do ollama list it gives me a blank list, but all the models is in the directories.
See Images, it was working correctly a few days ago.

![Screenshot 2024-06-16 171354](https://github.com/ollama/ollama/assets/67223389/d9926fdf-7cf9-4128-b15a-f6d020e68b7d)
![Screenshot 2024-06-16 171451](https://github.com/ollama/ollama/assets/67223389/a19d329f-64e1-43b8-9bd3-cde7f489dd4e)
![Screenshot 2024-06-16 171510](https://github.com/ollama/ollama/assets/67223389/4a77c8fb-8d33-487a-a92c-93af30c66b62)

### OS

Windows

### GPU

Nvidia

### CPU

AMD

### Ollama version

0.1.44

**Comment by jmorganca** [comment]
Hi there, sorry this happened. Would it be possible to share your logs? The should be accessible by clicking the tray icon -> view logs and then in the `server.log` file.

**Comment by pdevine** [comment]
@DoLife is this still an issue?

**Comment by inzi** [comment]
FWIW, I just upgraded to latest Ollama today.  I had 29 models downloaded. After upgrade,  it deleted all of them. 
I pulled codegemma it's the only one I have now.

I have my OLLAMA_MODELS set. 
Win11pro, i7-13700, 64GBram, RTX4090.

I've zipped my logs.  I don't see anything in them indicating where it deleted them.  

On another machine, same thing - 
Win11pro, i7-13700, 64GB ram, RTX 4070. 

After ollama upgrade, all gone. 

I'm happy to share my logs with you, but not in here.

**Comment by jmorganca** [comment]
@inzi possible to share what you have OLLAMA_MODELS to? (Feel free to change the folder names but hoping this can help us reproduce)

**Comment by jmorganca** [comment]
Also feel free to drop me a note: jmorganca@gmail.com

**Comment by inzi** [comment]
Sorry, I made a dumb mistake.

I had a script that was calling /api/delete in a project I was working on, not setting timeout to 0 to get them to unload. 

Needless to say, when testing a model with that script, it proceeded to delete my models. 

After modifying the script to call timeout=0, I've not had to delete models. 

sigh... I should have double checked myself first.

**Comment by pdevine** [comment]
Holy moly! So glad you got it sorted out, @inzi . I'm going to go ahead and close the issue. @DoLife lmk if you're still having issues and we can reevaluate.
