### ISSUE TITLE
OllaMail - An email client powered by Ollama

### ISSUE THREAD

**Issue by perpendicularai** [ollama/ollama#5085]
Hi Ollama Team,

Thank you for your time and effort in making sure that the Ollama API is always exceptional when a new version is released.

With that said, I'd like to inform you of an email client that reads and sends email using Ollama. I'll be making a version native to Windows available and wanted to know if you would like to add it to the README.md Community Integrations. It's called OllaMail. See git repo: https://github.com/perpendicularai/OllaMail
I have attached an image for your perusal.
![test_0](https://github.com/ollama/ollama/assets/146530480/001fdeb2-4668-4142-9d6a-86ac987234fc)
![test_1](https://github.com/ollama/ollama/assets/146530480/6c1f703f-c4b8-410a-98da-b15b162c3467)

**Comment by jmorganca** [comment]
@perpendicularai this is awesome! Thank you for sharing! Would it be possible to add it to the README.md via a pull request? That way folks can find the project as a community integration! I'll close this for now.

**Comment by perpendicularai** [comment]
All done!
