### ISSUE TITLE
Qwen2 "GGGG" issue is back in version 0.1.44

### ISSUE THREAD

**Issue by Speedway1** [ollama/ollama#5087]
### What is the issue?

Qwen2 70B outputs a series of Gs or else random garbage. However Qwen2 7b, which fits on one card only, works fine. It seems that when Ollama needs to spread across 2 GPU cards, it doesn't work.

For example:

```
ollama@TH-AI2:~$ ollama run qwen2:72b
>>> Tell me a sotry about a bird and a tree who loved each other
25 and789320 and，

1202   164_39 a1.13   2019   the



    ,096
2,，',
314 is

```

$ ollama -v
ollama version is 0.1.44

llamacpp@TH-AI2:~$ /opt/rocm/bin/rocm-smi

========================================== ROCm System Management Interface ==========================================
==================================================== Concise Info ====================================================
Device  [Model : Revision]    Temp    Power   Partitions      SCLK    MCLK     Fan    Perf  PwrCap       VRAM%  GPU%  
        Name (20 chars)       (Edge)  (Avg)   (Mem, Compute)                                                          
======================================================================================================================
0       [0x5304 : 0xc8]       47.0°C  79.0W   N/A, N/A        189Mhz  1249Mhz  20.0%  auto  327.0W        86%   9%    
        0x744c                                                                                                        
1       [0x5304 : 0xc8]       48.0°C  81.0W   N/A, N/A        228Mhz  1249Mhz  20.0%  auto  327.0W        85%   9%    
        0x744c                                                                                                        
2       [0x8877 : 0xc3]       36.0°C  9.155W  N/A, N/A        None    1800Mhz  0%     auto  Unsupported   15%   0%    
        0x164e                                                                                                        

### OS

Linux

### GPU

AMD

### CPU

AMD

### Ollama version

0.1.44

**Comment by dhiltgen** [comment]
I was unable to reproduce on a dual Radeon test system I have.
```
time=2024-06-18T19:22:30.889Z level=INFO source=types.go:98 msg="inference compute" id=0 library=rocm compute=gfx1030 driver=6.3 name=1002:73bf total="16.0 GiB" available="16.0 GiB"
time=2024-06-18T19:22:30.889Z level=INFO source=types.go:98 msg="inference compute" id=1 library=rocm compute=gfx1030 driver=6.3 name=1002:73bf total="16.0 GiB" available="16.0 GiB"
```

```
% ollama run qwen2:72b
>>> Tell me a sotry about a bird and a tree who loved each other
Once upon a time, in the heart of a vast forest, there was an ancient oak tree named Oakley. He stood tall and proud amongst
his fellow trees, his branches reaching up to the sky, providing shade and shelter to all creatures that sought refuge under
him.
...
```

```
% ollama ps
NAME     	ID          	SIZE 	PROCESSOR      	UNTIL
qwen2:72b	14066dfa503f	45 GB	26%/74% CPU/GPU	4 minutes from now
```

```
llm_load_tensors: offloading 58 repeating layers to GPU
llm_load_tensors: offloaded 58/81 layers to GPU
llm_load_tensors:      ROCm0 buffer size = 13656.51 MiB
llm_load_tensors:      ROCm1 buffer size = 13656.51 MiB
llm_load_tensors:        CPU buffer size = 39315.94 MiB
```

Perhaps it's GPU model specific, or maybe there's a subtle out of memory corruption going on?  You could try setting num_gpu to a lower value than what we select and see if that changes behavior.

**Comment by Speedway1** [comment]
Thank you so much for looking into this and testing. I will try with num_gpu lower as it  might be getting confused. I note that you have 16GB Radeons, so we do have different models, I have the 24GB 7900 XTX models. Really hope it's not some esoteric hardware issue! But let's see what num_gpu fiddling does and thank you once again.

**Comment by Speedway1** [comment]
I can confirm that it's as soon as the model is loaded across the 2 GPU cards that it breaks. It's the same for llama3:70b as well. Setting num_gpu to 50 kicks in both cards, and gives garbage. Setting it to 30 uses only 1  card and it works fine. Whereas in llamacpp, it works fine across multiple cards.

Ollama:
```
>> /set parameter num_gpu 50
Set parameter 'num_gpu' to '50'
>>> Tell me a story about a princess and a leaf
D#E$@>.E8C9!C!=*:#+>A6C1%!%>-9*%$.:"@<1-3G9DED&<*2@HB"%)$.9GG;),HA.GA!0=!<&$$(%H>B"C.--0.<9C<C)GB"<C@21D=%@;H7-D(:6&&FD@F#0D8C074,74C+52:E84#&%EB#:"011;*8C,5GB9.8,C7<8"2@60>E^C

>>> /set parameter num_gpu 30
Set parameter 'num_gpu' to '30'
>>> Tell me a story about a princess and a leaf
I apologize for the mistakes earlier! Here's a new attempt at telling you a story about a princess and a leaf:

```

llamacpp:

```
llama_new_context_with_model:      ROCm0 compute buffer size =  1184.00 MiB
llama_new_context_with_model:      ROCm1 compute buffer size =  1104.00 MiB

sampling order: 
CFG -> Penalties -> top_k -> tfs_z -> typical_p -> top_p -> min_p -> temperature 
generate: n_ctx = 8192, n_batch = 2048, n_predict = 8192, n_keep = 1


== Running in interactive mode. ==
 - Press Ctrl+C to interject at any time.
 - Press Return to return control to LLaMa.
 - To return control without starting a new line, end your input with '/'.
 - If you want to submit another line, end your input with '\'.

 Tags: python, function, numpy, jupyter-notebook

Question: Function with two arguments to generate numpy arrays

I am trying to write a function that takes two parameters (`n` and `d`) and generates a random numpy array of shape (`n, n, d`), with the entries being random numbers from 0 to 1.

I can't work out what's going wrong, here's my code:


```

So it looks like this is an Ollama issue, not a Radeon driver issue.

**Comment by Speedway1** [comment]
I have extensively played around with the number of layers loaded into the GPUs and context length and without doubt, it's down to how Ollama is trying to share memory between the two GPUs.

When I limit to a single GPU, there is no problem. When I offload to CPU there is no problem. When I run the same model sizes in Llama.cpp, both GPUs load up properly and works and limiting layers so that excess memory is offloaded to the CPU/RAM also works.

It is purely when running >1 GPU under Ollama that the issues arise. Specifically there is memory faulting that I don't see with llamacpp indicating that Ollama is handling data/layer transfers differently than llamacpp and it's not working for AMD:

```
Jun 23 01:20:57 TH-AI2 ollama[421959]: time=2024-06-23T01:20:57.110+01:00 level=DEBUG source=server.go:686 msg="setting token limit to 10x num_ctx" num_ctx=4096 num_predict=40960
Jun 23 01:20:57 TH-AI2 ollama[473561]: DEBUG [process_single_task] slot data | n_idle_slots=4 n_processing_slots=0 task_id=37 tid="133852616667968" timestamp=1719102057
Jun 23 01:20:57 TH-AI2 ollama[473561]: DEBUG [launch_slot_with_data] slot is processing task | slot_id=1 task_id=38 tid="133852616667968" timestamp=1719102057
Jun 23 01:20:57 TH-AI2 ollama[473561]: DEBUG [update_slots] slot progression | ga_i=0 n_past=0 n_past_se=0 n_prompt_tokens_processed=669 slot_id=1 task_id=38 tid="133852616667968" timestamp=1719102057
Jun 23 01:20:57 TH-AI2 ollama[473561]: DEBUG [update_slots] kv cache rm [p0, end) | p0=0 slot_id=1 task_id=38 tid="133852616667968" timestamp=1719102057
Jun 23 01:20:57 TH-AI2 kernel: [352668.696989] amd_iommu_report_page_fault: 1274 callbacks suppressed
Jun 23 01:20:57 TH-AI2 kernel: [352668.696993] amdgpu 0000:0c:00.0: AMD-Vi: Event logged [IO_PAGE_FAULT domain=0x0014 address=0xf0a0000000 flags=0x0020]
Jun 23 01:20:57 TH-AI2 kernel: [352668.697010] amdgpu 0000:0c:00.0: AMD-Vi: Event logged [IO_PAGE_FAULT domain=0x0014 address=0xf0a0000500 flags=0x0020]
Jun 23 01:20:57 TH-AI2 kernel: [352668.697022] amdgpu 0000:0c:00.0: AMD-Vi: Event logged [IO_PAGE_FAULT domain=0x0014 address=0xf0a0000900 flags=0x0020]
Jun 23 01:20:57 TH-AI2 kernel: [352668.697034] amdgpu 0000:0c:00.0: AMD-Vi: Event logged [IO_PAGE_FAULT domain=0x0014 address=0xf0a0000e00 flags=0x0020]
Jun 23 01:20:57 TH-AI2 kernel: [352668.697045] amdgpu 0000:0c:00.0: AMD-Vi: Event logged [IO_PAGE_FAULT domain=0x0014 address=0xf0a0001100 flags=0x0020]
Jun 23 01:20:57 TH-AI2 kernel: [352668.697057] amdgpu 0000:0c:00.0: AMD-Vi: Event logged [IO_PAGE_FAULT domain=0x0014 address=0xf0a0001d00 flags=0x0020]
Jun 23 01:20:57 TH-AI2 kernel: [352668.697068] amdgpu 0000:0c:00.0: AMD-Vi: Event logged [IO_PAGE_FAULT domain=0x0014 address=0xf0a0001900 flags=0x0020]
Jun 23 01:20:57 TH-AI2 kernel: [352668.697080] amdgpu 0000:0c:00.0: AMD-Vi: Event logged [IO_PAGE_FAULT domain=0x0014 address=0xf0a0002400 flags=0x0020]
Jun 23 01:20:57 TH-AI2 kernel: [352668.697091] amdgpu 0000:0c:00.0: AMD-Vi: Event logged [IO_PAGE_FAULT domain=0x0014 address=0xf0a0001800 flags=0x0020]
Jun 23 01:20:57 TH-AI2 kernel: [352668.697102] amdgpu 0000:0c:00.0: AMD-Vi: Event logged [IO_PAGE_FAULT domain=0x0014 address=0xf0a0002100 flags=0x0020]
Jun 23 01:20:57 TH-AI2 kernel: [352668.700421] AMD-Vi: IOMMU event log overflow
Jun 23 01:20:57 TH-AI2 kernel: [352668.700429] AMD-Vi: IOMMU event log overflow
Jun 23 01:20:57 TH-AI2 kernel: [352669.112835] AMD-Vi: IOMMU event log overflow
Jun 23 01:21:01 TH-AI2 ollama[421959]: time=2024-06-23T01:21:01.163+01:00 level=DEBUG source=server.go:799 msg="prediction aborted, token repeat limit reached"
Jun 23 01:21:01 TH-AI2 ollama[421959]: [GIN] 2024/06/23 - 01:21:01 | 200 |   4.84362172s |   192.168.0.140 | POST     "/api/chat"
Jun 23 01:21:01 TH-AI2 ollama[421959]: time=2024-06-23T01:21:01.163+01:00 level=DEBUG source=sched.go:348 msg="context for request finished"
Jun 23 01:21:01 TH-AI2 ollama[421959]: time=2024-06-23T01:21:01.163+01:00 level=DEBUG source=sched.go:281 msg="runner with non-zero duration has gone idle, adding timer" modelPath=/home/ollama/.ollama/models/blobs/sha256-9d44b5302a369a2c7da61f6bc1850be70f7777d70a3446afde0fd91ffc8c7a02 duration=5m0s

```

**Comment by hackey** [comment]
I confirm the problem. It's exactly the same for me. On one 7900 xx GPU everything works both locally and in Docker. As soon as two 7900 HTH are used, Ollama displays nonsense.

**Comment by Speedway1** [comment]
> I confirm the problem. It's exactly the same for me. On one 7900 xtx GPU everything works both locally and in Docker. As soon as two 7900 xtx are used, Ollama displays nonsense: `->cuuzuyuz�yyuz->touyryuzwithCU是上是约上的uDBuivyisBV的uzywith律usingbv载BRuyyyuzvyyuzyCUuyuzuzuz->cuuiBVuuycliuzcuuz->QUuyuz^C`
> 
> Llama cpp works correctly with two 7900 xtx adapters. I compiled llamasp with these parameters: make clean && make -j32 LLAMA_CUDA_NO_PEER_COPY=ON LLAMA_HIPBLAS=1 AMDGPU_TARGETS=gfx1100 HIP_VISIBLE_DEVICES=0,1 and this is what helped me get Llama cpp to work on two cards. I have the latest clean version of ollama/ollama:0.1.46-rocm installed in docker, and ROCM 6.1.3 installed locally. Everywhere there is a problem with ollama.

Yes my llamacpp works.

I am not using docker, I am running Ollama natively and it's broken. Now on version 0.1.48 and still not working. This must be down to teh llamacpp that Ollama uses. I suspect that it's the LLAMA_CUDA_NO_PEER_COPY parameter that is key.

**Comment by dhiltgen** [comment]
@Speedway1 thanks!  I'll get a PR up to get that flag enabled on our ROCm builds.

**Comment by Speedway1** [comment]
@dhiltgen - You hero. Thank you.

**Comment by RePixelatedMC** [comment]
Howdy, I'm running into the same issue, but instead of the usual problem, I'm just getting spammed with weirdly formatted sentences full of "G"s. The crazy thing is that it happens on my 4070 Ti Super instance when using the 7B model, regardless of the quantization setting. What's even weirder is that the 70B model (which uses both VRAM and RAM) doesn't seem to have this problem at all.

**Comment by Speedway1** [comment]
> Howdy, I'm running into the same issue, but instead of the usual problem, I'm just getting spammed with weirdly formatted sentences full of "G"s. The crazy thing is that it happens on my 4070 Ti Super instance when using the 7B model, regardless of the quantization setting. What's even weirder is that the 70B model (which uses both VRAM and RAM) doesn't seem to have this problem at all. ( Edit: just wanted to note this out if it helps in the development process perhaps )

If you're running a 4070 then you are running Nvidia not AMD.  So this fix doesn't apply. It could be a template issue where the stop tag isn't being recognised. It MIGHT be related to memory. Try dropping the context window down to 512 or some other lower size and then retry. Sometimes when the LLM has a larger context window is can exceed the VRAM and in this case some weird things can happen which largely seem to be model dependent in my experience.

Also, use nvtop to monitor the RAM on the GPU and see if it's hitting the limit.
