### ISSUE TITLE
ollama 模型授权

### ISSUE THREAD

**Issue by yawzhe** [ollama/ollama#5107]
### What is the issue?

我想问一下ollama怎么自定义设置KEY_传参， 每个模型定义不同的key，2.ollama是否支持模型授权，加密模型之类的，

### OS

Linux

### GPU

Nvidia

### CPU

Intel

### Ollama version

最新的

**Comment by jmorganca** [comment]
Hi there, Ollama doesn't currently supported encrypted models or anything similar at the moment. That said don't hesitate to create a feature request! Thanks for the issue
