### ISSUE TITLE
Support InternLM

### ISSUE THREAD

**Issue by vansinhu** [ollama/ollama#511]
Dear ollama developer,

Greetings! I am vansinhu, a community developer and volunteer at InternLM. [InternLM](https://github.com/InternLM/InternLM) is a large language model similar to llama2, and we look forward to InternLM being supported in ollama. If there are any challenges or inquiries regarding support for InternLM, please feel free to join our Discord discussion at https://discord.gg/gF9ezcmtM3. 

Best regards,
vansinhu

**Comment by mchiang0610** [comment]
@vansinhu I would love to support this. Will take a look through your huggingface repos. Sorry for the delay!!

**Comment by mchiang0610** [comment]
Possible to ask you to quantize the models, and then upload it to ollama?

**Comment by jmorganca** [comment]
Hi @vansinhu. We'd love to support this. Ollama currently runs llama.cpp under the hood and we'd need some help getting that in https://github.com/ggerganov/llama.cpp/issues/3133. After that, this should be no problem to add

**Comment by CausalLM** [comment]
See https://github.com/ggerganov/llama.cpp/pull/4283

**Comment by BruceMacD** [comment]
Thanks for the request, the model is now supported, and it looks like some community members have added it to Ollama:
https://ollama.com/search?q=intern&p=1

Resolving this for now, depending on the popularity we might add it to the official library namespace.

**Comment by QiuZiXian** [comment]
@BruceMacD May you give me a template example？
I follow [fun-tunning](https://xtuner.readthedocs.io/zh-cn/latest/get_started/quickstart.html)，get the merge model，
then follow [ollama](https://github.com/ollama/ollama/blob/main/docs/modelfile.md#parameter) to convert to gguf
create from mainfest is ok，
but conversion is not.
replay can't stop
![image](https://github.com/ollama/ollama/assets/28780269/f4ec09f8-6678-4446-a952-0895f1382392)
