### ISSUE TITLE
RAM not being fully utilized (?)

### ISSUE THREAD

**Issue by rb81** [ollama/ollama#5111]
### What is the issue?

I've seen others complain about similar things but no solid answer. I'm running Ollama on Ubuntu Server with 64GB of RAM (CPU only). Inference time is better than my MacBook Air M1 with 8GB of RAM, but not as much as I would have expected. When looking at the stats, it seems RAM remains unused during inference. Brought this up in the Discord as well. Would sincerely appreciate understanding if this is a bug, something I'm doing/configuring wrong, or something else. Thanks!

<img width="749" alt="Screenshot_2024-06-18_at_12 22 20_PM" src="https://github.com/ollama/ollama/assets/48117105/8cb2e56a-ef03-4bc3-ba0a-81bc6360a608">

^ This is during inference, running qwen2:72b

### OS

Linux

### GPU

Other

### CPU

Intel

### Ollama version

0.1.44

**Comment by jmio23** [comment]
I was just looking at my ubuntu setup running llama3 70b, I was expecting about 16gb to turn up in RAM, and 24gb in VRAM, but only somewhere between 1.3gb and 0.7gb ended up in RAM, VRAM was filled

Maybe I got it wrong, I was expecting about 40GB ram use for the 70b llama3

**Comment by jmorganca** [comment]
Models are `mmap`'d into memory which can cause memory readings like this (reported as cache) – hope this helps!

**Comment by rb81** [comment]
Thanks, @jmorganca!
