### ISSUE TITLE
Model pull error - I/O timeout

### ISSUE THREAD

**Issue by VIGHNESH1521** [ollama/ollama#5112]
### What is the issue?

I tried to download llama 2 7b chat 8-bit quantized model, but I am getting the following error

![error](https://github.com/ollama/ollama/assets/90493668/0b8e8a7b-2449-46f0-b2dc-701aa26917d5)

Any suggestion how to resolve this?

### OS

Windows

### GPU

Nvidia

### CPU

Intel

### Ollama version

0.1.44

**Comment by jmorganca** [comment]
Closing for https://github.com/ollama/ollama/issues/3816
