### ISSUE TITLE
ERROR [validate_model_chat_template] deepseek-coder-v2:16b-lite-instruct-q8_0

### ISSUE THREAD

**Issue by ekolawole** [ollama/ollama#5116]
### What is the issue?

deepseek-coder-v2:16b-lite-instruct-q8_0:
INFO [main] model loaded | tid="0x1fe414c00" timestamp=1718717321
ERROR [validate_model_chat_template] The chat template comes with this model is not yet supported, falling back to chatml. This may cause the model to output suboptimal responses | tid="0x1fe414c00" timestamp=1718717321
time=2024-06-18T09:28:41.274-04:00 level=INFO source=server.go:572 msg="llama runner started in 2.66 seconds"
GGML_ASSERT: /Users/runner/work/ollama/ollama/llm/llama.cpp/ggml-metal.m:1853: dst_rows <= 2048

### OS

macOS

### GPU

Apple

### CPU

Apple

### Ollama version

0.1.44

**Comment by dhiltgen** [comment]
This is fixed in 0.1.45
