### ISSUE TITLE
CANNOT DOWNLOAD MODELS

### ISSUE THREAD

**Issue by Udacv** [ollama/ollama#5132]
### What is the issue?

Recently, when I use 'ollama run' to download models, I cannot download anything with the bug following.
![QQ截图20240619111403](https://github.com/ollama/ollama/assets/126667614/a4465567-74aa-4869-b12d-6b6d7d5701ea)

Im from China, I cannot download either with the local Internet or with a VPN.

### OS

Windows

### GPU

AMD

### CPU

AMD

### Ollama version

0.1.44

**Comment by Udacv** [comment]
WHO CAN HELP ME  /(ㄒoㄒ)/~~

**Comment by AncientMystic** [comment]
Not directly related to your bug but you could use open-webui and either download the models manually from ollama or download gguf files from huggingface and just upload the files manually via the open-webui instance (easy to deploy with docker) 

Id also suggest making sure of course that a firewall such as the built in windows firewall isn't stopping the download of models via ollama

**Comment by Udacv** [comment]
> Not directly related to your bug but you could use open-webui and either download the models manually from ollama or download gguf files from huggingface and just upload the files manually via the open-webui instance (easy to deploy with docker)
> 
> Id also suggest making sure of course that a firewall such as the built in windows firewall isn't stopping the download of models via ollama

Thanks, I will try. (●'◡'●)

**Comment by AncientMystic** [comment]
> > Not directly related to your bug but you could use open-webui and either download the models manually from ollama or download gguf files from huggingface and just upload the files manually via the open-webui instance (easy to deploy with docker)
> 
> > 
> 
> > Id also suggest making sure of course that a firewall such as the built in windows firewall isn't stopping the download of models via ollama
> 
> 
> 
> Thanks, I will try. (●'◡'●)

You're welcome, hopefully that works for you, i always just use links from huggingface or upload models downloaded from it, theres a much wider selection there anyways just search whatever name plus gguf and you will find a ton of ollama compatible models to use.
