### ISSUE TITLE
How do you ensure that the same questions you asked before are not used and that each time you ask a new conversation question through the api request /api/generate interface

### ISSUE THREAD

**Issue by mingLvft** [ollama/ollama#5133]
How do you ensure that the same questions you asked before are not used and that each time you ask a new conversation question through the api request /api/generate interface

**Comment by pdevine** [comment]
@mingLvft that's how the `/api/generate` endpoint works. Subsequent calls have no knowledge of previous calls to that endpoint.

If you don't want the same response you would have to tell the model something like "don't respond to this query with the following answers".
