### ISSUE TITLE
api interface /api/generate I need to make sure that every question is not answered from the previous record  How to do?

### ISSUE THREAD

**Issue by mingLvft** [ollama/ollama#5134]
api interface /api/generate I need to make sure that every question is not answered from the previous record  How to do?

**Comment by royjhan** [comment]
As long as you don't use the `context` parameter, generate does not keep chat memory.

**Comment by mdhuzaifapatel** [comment]
> As long as you don't use the `context` parameter, generate does not keep chat memory.

Hi @royjhan , can you please let me know how to use this context parameter, I'm unable to figure it out by reading the documentation. 

I want to use the context from previous responses in current one. 

Pls help me out, if possible give me a code example it would be a great help. Thanks!
