### ISSUE TITLE
HOW CAN I CHANGE THE PORT OLLAMA SERVE USES

### ISSUE THREAD

**Issue by Udacv** [ollama/ollama#5135]
### What is the issue?

My port 11434 is occupied. I wonder how can I change one?
I've tried "OLLAMA_HOST=127.0.0.1:11435 ollama serve", but my cmd cannot understand.

### OS

Windows

### GPU

AMD

### CPU

AMD

### Ollama version

0.1.44

**Comment by Udacv** [comment]
Who can help me?  /(ㄒoㄒ)/~~

**Comment by jmorganca** [comment]
If using cmd:

```
set OLLAMA_HOST= 127.0.0.1:11435
```

if using powershell:

```
$Env:OLLAMA_HOST = "127.0.0.1:11435"
```

Thanks for the issue!
