### ISSUE TITLE
A problem with "ollama create"

### ISSUE THREAD

**Issue by Udacv** [ollama/ollama#5137]
### What is the issue?

If I want to create a model with two part of gguf, how can I write my Modelfile.
![QQ截图20240619164359](https://github.com/ollama/ollama/assets/126667614/a700d34e-c627-4e74-bf9b-3bd0e35f6835)

### OS

Windows

### GPU

Nvidia

### CPU

Intel

### Ollama version

0.1.44

**Comment by jmorganca** [comment]
Closing for https://github.com/ollama/ollama/issues/5245

**Comment by werruww** [comment]
Does Obama support fragmented models? Important: They must be merged before running in Olama by modelfile
