### ISSUE TITLE
Chat template not yet supported for Deepseek-Coder-V2 lite

### ISSUE THREAD

**Issue by Joly0** [ollama/ollama#5140]
### What is the issue?

Whenever i try to chat with the llm through open-webui and ollama, i get this in the logs of ollama:
`ERROR [validate_model_chat_template] The chat template comes with this model is not yet supported, falling back to chatml. This may cause the model to output suboptimal responses | tid="22401915281408" timestamp=1718800491`

and the output in open-webui is just crap, nothing else. The answer has nothing to do with what i have requested.

### OS

Linux, Docker

### GPU

Nvidia

### CPU

AMD

### Ollama version

0.1.44

**Comment by dhiltgen** [comment]
This log message was stale and not relevant (the template logic isn't actually used by ollama) and we'll remove it in 0.1.45.

To your comment on the quality of responses in deepseek, in 0.1.44 the responses were poor, but in 0.1.45 it is much better.
