### ISSUE TITLE
Storing LLM's at desided location rather than on C:/

### ISSUE THREAD

**Issue by IWasThereWhenItWasWritten** [ollama/ollama#5153]
Hello!
I'm unsure if the topic had already been discussed, but I'll start anyway.
My issue is low C:/ capacity, so I can't afford downloading many LLM's to compare the output. 
My solution would be to add an option where Models should be stored. 

If it had been already implemented please show me the manual to it, so I could handle it myself.
Thank you for your time.

**Comment by hlstudio** [comment]
set OLLAMA_MODELS env
@see https://github.com/ollama/ollama/blob/main/docs/faq.md

**Comment by IWasThereWhenItWasWritten** [comment]
Thank you. Case closed ;)
