### ISSUE TITLE
Can we add support for `firefunction-v2` Competitive with GPT-4o at function-calling

### ISSUE THREAD

**Issue by talperetz** [ollama/ollama#5154]
https://huggingface.co/fireworks-ai/firefunction-v2

Competitive with GPT-4o at function-calling, scoring 0.81 vs 0.80 on a medley of public evaluations
Trained on Llama 3 and retains Llama 3’s conversation and instruction-following capabilities, scoring 0.84 vs Llama 3’s 0.89 on MT bench
Significant quality improvements over FireFunction v1 across the broad range of metrics

**Comment by jmorganca** [comment]
This model has been added: https://ollama.com/library/firefunction-v2

Thanks for the issue!
