### ISSUE TITLE
Update llama.cpp to support qwen2-57B-A14B pls

### ISSUE THREAD

**Issue by CoreJa** [ollama/ollama#5157]
### What is the issue?

llama.cpp is able to support qwen2-57B-A14B moe model now via https://github.com/ggerganov/llama.cpp/pull/7835. Please help update submodule llama.cpp to a newer version. Otherwise i quants of this model(I tried iq4_xs) would end up with a `CUDA error: CUBLAS_STATUS_NOT_INITIALIZED`. 

### OS

Linux

### GPU

Nvidia

### CPU

Intel

### Ollama version

v0.1.44

**Comment by dhiltgen** [comment]
This landed just after we updated for 0.1.45.  We'll pick this up on our next update ~next week.

**Comment by CoreJa** [comment]
Thx for your quick response, I'll close this issue when it releases. Appreciate your help!

**Comment by bunnyfu** [comment]
Also something to keep in mind with the Qwen2 57b MoE model is that it breaks if you raise the batch above 256. Ollama tries to default to batches of 512. I have been manually setting in llama.cpp -ubatch 256 to make sure to avoid this error on some configs (macs): GGML_ASSERT: ggml-metal.m:1857: dst_rows <= 2048 

More info here: https://github.com/ggerganov/llama.cpp/issues/7652
