### ISSUE TITLE
"error": "invalid character 'm' looking for beginning of value"

### ISSUE THREAD

**Issue by workmengxue** [ollama/ollama#5159]
### What is the issue?

![image](https://github.com/ollama/ollama/assets/154218248/759e26b3-a5bf-46a5-a059-ab6f19c39d4f)
![image](https://github.com/ollama/ollama/assets/154218248/0430650e-6d68-434f-b163-9d034ecf6157)

### OS

Windows

### GPU

Intel

### CPU

Intel

### Ollama version

ollama version is 0.1.44

**Comment by workmengxue** [comment]
![image](https://github.com/ollama/ollama/assets/154218248/e9a782cf-e85f-43d1-a23c-76c711ee55fd)

**Comment by workmengxue** [comment]
![image](https://github.com/ollama/ollama/assets/154218248/cb739d5f-b43a-4bd1-8f24-e9bd05878bb4)
curl http://localhost:11434/api/generate -d '{"model": "qwen2:0.5b","params":"who are you?"}'

**Comment by workmengxue** [comment]
![Uploading image.png…]()

**Comment by workmengxue** [comment]
![image](https://github.com/ollama/ollama/assets/154218248/6351aad0-977b-430f-874e-09a2a50799a5)

**Comment by jmorganca** [comment]
Hi there make sure to send the body as JSON in postman

![image](https://github.com/ollama/ollama/assets/251292/b8c906f8-7742-43fa-8c66-38fae3c155ad)

**Comment by wayyt-1** [comment]
Option 1:  Install PowerShell 7

Or,

Option 2: Change the script to:

curl http://localhost:11434/api/generate -d '{  \"model\": \"qwen2:0.5b\",  \"prompt\": \"Why is the sky blue?\"}'

**Comment by ExplorerSec** [comment]
This is a common issue, and there seem to be many related discussions on the Chinese Internet. I encountered it while using Python.  
```python
requests.post(
   url = "http://localhost:11434/api/generate", 
   data={
  "model": "llama3.2",
  "prompt": "Why is the sky blue?",
  "stream": False
})
```

And I found the solution by modifying it to:

```python
url = "http://localhost:11434/api/generate"
data={\
  "model": "llama3.2",\
  "prompt": "Why is the sky blue?",\
  "stream": False\
})
r2 =requests.post(url,json.dumps(data))
```
The key is to remember to use `json.dumps`.

**Comment by HaleyHalcyon** [comment]
Might not be the same problem, but I personally got around it in my environment by adding `\` before every `"`.
