### ISSUE TITLE
Deepseek-Coder-v2 Instruct Chat Template

### ISSUE THREAD

**Issue by RussellCanfield** [ollama/ollama#5189]
### What is the issue?

I was testing out Deepseek Coder V2 using the Ollama /api/chat endpoint and I get the following error. Does this model in general support chat?

**Model:**
deepseek-coder-v2:16b-lite-instruct-q4_0

**Error:**
ERROR [validate_model_chat_template] The chat template comes with this model is not yet supported, falling back to chatml. This may cause the model to output suboptimal responses | tid="0x1ee4b4c00" timestamp=1718899061

The request ends up failing, but that is captured from the Ollama log files.

### OS

macOS

### GPU

Apple

### CPU

Apple

### Ollama version

0.1.44

**Comment by s-kostyaev** [comment]
https://github.com/deepseek-ai/DeepSeek-Coder-V2/issues/12#issuecomment-2181255179

**Comment by jmorganca** [comment]
Hi folks this should be fixed now – sorry about that
