### ISSUE TITLE
How to import a model (.bin) from huggin face?

### ISSUE THREAD

**Issue by javierxio** [ollama/ollama#5195]
Hello. I would like to use a model from huggin face. I was able to download a file called `pytorch_model.bin` which I presume is the LLM. I created a directory and created a `Modelfile.txt` file. The contents of the `Modelfile.txt` are as:

```
FROM C:\ollama_models\florence-2-base\pytorch_model.bin
```

Running the ollama create command results in the following erros:

```sh
C:\ollama_models\florence-2-base>ollama create florence2:base -f ./Modelfile.txt
transferring model data
unpacking model metadata
Error: open C:\Users\javie\.ollama\models\blobs\1075676817\pytorch_model\data.pkl: The system cannot find the path specified.
```

Please help me understand? I am new at this. Thanks!

**Comment by bmabir17** [comment]
I think ollama does not support bin file models. AFIK it now supports gguf only

**Comment by mili-tan** [comment]
Try writing up the huggin face model directory instead of the bin file.
`FROM C:\ollama_models\florence-2-base\`

**Comment by javierxio** [comment]
@mili-tan thanks mili. that seems to help and now am getting to this stage:

```ps
C:\ollama_models\florence-2-base>ollama create florence2:base -f ./Modelfile.txt
transferring model data
unpacking model metadata
Error: open C:\Users\javie\.ollama\models\blobs\613013707\params.json: The system cannot find the file specified.
```

Seems I am now missing some other files (e.g. `params.json`). I will try and see if they are available in the hugging face repo.

**Comment by javierxio** [comment]
These are the files in hugging face. I don't know which is considered `params.json` but I will try to rename one of the files to that filename.

![image](https://github.com/ollama/ollama/assets/63758477/60117ad9-52d9-44df-a8ba-45a17000a46b)

**Comment by javierxio** [comment]
Ok. I downloaded `config.json` file and renamed as `params.json`

```sh
C:\ollama_models\florence-2-base>ollama create florence2:base -f ./Modelfile.txt
transferring model data
unpacking model metadata
processing tensors
```

It seems it went through but now cannot run `run` command and gives error:

```sh
C:\ollama_models\florence-2-base>ollama run florence2:base
pulling manifest
Error: pull model manifest: file does not exist
```

**Comment by javierxio** [comment]
i have moved to llama-cpp-python for the meantime. thanks.
