### ISSUE TITLE
use_mmap: Error: invalid int value [false]

### ISSUE THREAD

**Issue by JeffTix** [ollama/ollama#5198]
### What is the issue?

When adding the `use_mmap` parameter to a modelfile, it used to be like this: `PARAMETER use_mmap false`. Since 0.1.45, this does not work, it wants an integer value. So I put `PARAMETER use_mmap 0`. This allows me to create the modelfile.

However, when attempting to run the model, it comes back with this error: `Error: option "use_mmap" must be of type boolean`

Seems like a cast was forgotten somewhere maybe?

### OS

Linux

### GPU

AMD

### CPU

AMD

### Ollama version

0.1.45

**Comment by JeffTix** [comment]
By downgrading to 0.1.44, I was able to create the model, and run it using 0.1.45. So this behavior changed between 0.1.44 and 0.1.45.

**Comment by dhiltgen** [comment]
Sorry about that.  I recently change this to be a tri-state vairable and missed the parsing logic for the modelfile.  We'll get this fixed in the next release.

**Comment by ProjectMoon** [comment]
I am not sure this is actually fix. I also had to downgrade to 0.1.44 again to create a model with use_mmap false, even with 0.1.46. I could create the model on latest version, but it would not run, with a similar issue about missing the boolean.

**Comment by ProjectMoon** [comment]
For a bit more clarity on this: on the latest version, I can create the model with `use_mmap false`. But when I try to run it, it says that parameter use_mmap must be of type boolean.

**Comment by ProjectMoon** [comment]
Should this be reopened since there is another PR required for it? I don't think I can reopen it myself.
