### ISSUE TITLE
Can't even attempt to load Deepseek-Coder-v2:236B due to arbitrary timeout

### ISSUE THREAD

**Issue by Nantris** [ollama/ollama#5204]
### What is the issue?

This issue thread mentions the overarching issue, and the specific comment a potential workaround: https://github.com/ollama/ollama/issues/630#issuecomment-2182371780

My understanding is that the 236B model should be feasible to load into less RAM than the model actually takes up since not all parameters need to be loaded simultaneously - but I can't find out whether that's true because ollama decides it's giving up after an arbitrary amount of time.

### OS

Windows

### GPU

Nvidia

### CPU

AMD

### Ollama version

0.1.44

**Comment by dhiltgen** [comment]
On the topic of timeout when loading large models, new in 0.1.45 is adjusted logic to detect if the model is larger than available system memory and disable mmap based loading.  (you can still set `"use_map": false` to force this at the API level)  As long as the model load progresses and doesn't stall for more than 5 minutes we wont timeout.

**Comment by Nantris** [comment]
Thanks for the tip! Could I suggest a configurable timeout? I'd love to be able to try loading the model from an HDD rather than an SSD for trial purposes, even if it's not ideal.

As it stands now, I'd have to clear space on my SSD just to know if the model could even theoretically load.

I'd rather know I could load the model before I have to clear the space for it.

**Comment by Nantris** [comment]
Oh I may have misinterpreted. It's not a 5 minute timeout for the load to complete, but for some progress to occur?

**Comment by dhiltgen** [comment]
Correct, as long as the progress percentage is changing, we reset the timer.  We only timeout if it hasn't changed progress in 5 minutes.

**Comment by Nantris** [comment]
@dhiltgen with 0.1.45 it now just errors instantly when loading the 236B model: `Error: llama runner process has terminated: exit status 0xc0000409`

I have 64gb of system RAM, another 64 of swap, and 16gb VRAM. I understand this may still not be enough, but the behavior is still unexpected.

**Comment by dhiltgen** [comment]
It sounds like you're hitting #4955 

The current validation logic only kicks in on the 2nd+ model load, and we blindly attempt to load a first model regardless of size.  Once that issue is resolved, the system will detect models that can't possible load on a combination of VRAM+System memory and prevent attempting with a good error message.

**Comment by Nantris** [comment]
Thanks for the reply! That sounds like the issue. 

Related question: Am I misunderstanding how "active parameters" works in this context? I thought that only a portion of the model needs to be loaded for the gating network to decide which parameters do need to be loaded for use? Or is the entire model actually required to be loaded at initialization?

**Comment by hemangjoshi37a** [comment]
I tried to run on dual H100 80GB GPU with 256gb Ram. I got error out of memory for GPU. Has anyone got it running?
