### ISSUE TITLE
Claude 3.5 model

### ISSUE THREAD

**Issue by zhouhao27** [ollama/ollama#5235]
Is it possible to support loading the open source Claude 3.5 model? Thanks.

**Comment by Kreijstal** [comment]
![](https://i.imgflip.com/801s46.gif)

**Comment by heyimjonas** [comment]
> Is it possible to support loading the open source Claude 3.5 model? Thanks.

the model is not open source

**Comment by userforsource** [comment]
Send the model link for download.
You can't because it is not opensource.

**Comment by lengxii** [comment]
https://github.com/saoudrizwan/claude-dev
