### ISSUE TITLE
OLLAMA_NUM_PARALLEL and OLLAMA_MAX_LOADED_MODELS do not work in WSL2

### ISSUE THREAD

**Issue by dancinkid6** [ollama/ollama#5237]
### What is the issue?

I have been trying to get OLLAMA_NUM_PARALLEL and OLLAMA_MAX_LOADED_MODELS working in my wsl2 in the past 2 days,
but somehow it just doesnt work

i added these 2 into my envionrmental variables, but i still can only get one model and one inference at a time. 
there are certainly enough vram:
```
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 555.52.01              Driver Version: 555.99         CUDA Version: 12.5     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 4090 ...    On  |   00000000:01:00.0 Off |                  N/A |
| N/A   45C    P5             14W /  105W |    5776MiB /  16376MiB |      6%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+

+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI        PID   Type   Process name                              GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|    0   N/A  N/A     41069      C   /ollama_llama_server                        N/A   
```
and i can echo both, 
```
$ echo $OLLAMA_MAX_LOADED_MODELS
2
$ echo $OLLAMA_NUM_PARALLEL
2
```
anyone has this problem?? am i doing something wrong?? Thanks in advance

### OS

WSL2

### GPU

Nvidia

### CPU

Intel

### Ollama version

0.1.43

**Comment by dhiltgen** [comment]
The most likely explanation is you're not setting this for the server.   Ollama is a client-server architecture, and on a linux system typically the server is run as a systemd service. 
 See https://github.com/ollama/ollama/blob/main/docs/faq.md#how-do-i-configure-ollama-server for instructions on how to configure the server.

**Comment by dancinkid6** [comment]
Thanks for the suggestion, but i did set up that, 
`
[Service]
Environment="OLLAMA_HOST=0.0.0.0"
OLLAMA_MAX_LOADED_MODELS=2
OLLAMA_NUM_PARALLEL=2
`
And i test it in the terminal, they are not working in parallel,
Don’t why, am i missing something ;(
For now i just put one of the instances on docker

**Comment by dancinkid6** [comment]
Thanks, it works now. It turned out i wasn’t configuring that correctly.
