### ISSUE TITLE
windows环境，使用api接口调用，，并发请求是多少啊？可以配置吗？

### ISSUE THREAD

**Issue by liuHongyang0207** [ollama/ollama#5249]
windows环境，使用api接口调用，，并发请求是多少啊？可以配置吗？

为什么有一个请求在传输中，另外一个请求就要排队，，怎么增加并发量啊？

**Comment by dhiltgen** [comment]
The experimental concurrency feature was described briefly in the [release notes for 0.1.33](https://github.com/ollama/ollama/releases/tag/v0.1.33). In a future version we will enable this by default.
