### ISSUE TITLE
Wrong parameters for gemma:7b

### ISSUE THREAD

**Issue by qzc438** [ollama/ollama#5254]
### What is the issue?

Type `ollama show gemma:7b`: the parameters are 9b, not 7b.

**Comment by d-kleine** [comment]
> We are releasing weights in two sizes: Gemma 2B and Gemma 7B. 
https://cloud.google.com/blog/products/ai-machine-learning/gemma-model-available-in-vertex-ai-and-via-gke?hl=en

**Comment by qzc438** [comment]
I see, but the problem is the parameter should not be 9b.

**Comment by d-kleine** [comment]
https://ollama.com/library/gemma:7b
There is only 2b and 7b. Can you explain the issue here?

**Comment by qzc438** [comment]
The issue is type `ollama gemma:7b`: the parameter shown on the screen is 9b.

**Comment by qzc438** [comment]
The issue is type `ollama show gemma:7b`: the parameter shown on the screen is 9b.

**Comment by d-kleine** [comment]
Ah, now I see what you mean: `"num_params": 8537680896` for gemma 7b
https://ollama.com/library/gemma:7b/blobs/ef311de6af9d

There is a discussion going on out about that: https://huggingface.co/google/gemma-7b/discussions/34

Not a bug in ollama, the information is right there. But I understand your confusion here.

**Comment by qzc438** [comment]
Thank you. I also observed the same issue for gemma 2b. The parameter shown on the screen is 3b.

**Comment by pdevine** [comment]
It's just the way Google wanted to market the LLMs. The actual parameter counts are correct. The `2b` and `9b` are their marketing terms.
