### ISSUE TITLE
Interesting behavior when running in parallel

### ISSUE THREAD

**Issue by AI-Guru** [ollama/ollama#5269]
### What is the issue?

Hi!

I am trying to embed a lot of documents with `jina/jina-embeddings-v2-base-de`. I am trying to use request parallelism with `OLLAMA_NUM_PARALLEL=16`. I have a multiprocessing script that spawns 16 processes. When watching the Ollama output I observe the following.

- A lot of request got through fine.
- Then suddenly an assertion is violates. See below.
- Ollama then purges the model from GPU memory and reloads it.
- My processes continue. I have some retry-mechanism.

Here is the assertion's output:
`GGML_ASSERT: /go/src/github.com/ollama/ollama/llm/llama.cpp/llama.cpp:12063: seq_id < n_tokens && "seq_id cannot be larger than n_tokens with pooling_type == MEAN"
` 

Any ideas?

### OS

Linux

### GPU

Nvidia

### CPU

AMD

### Ollama version

0.1.45

**Comment by dhiltgen** [comment]
Do you see better behavior with a smaller parallel setting?  In the upcoming release (0.1.49) we'll be defaulting to 4 if the GPU has sufficient VRAM for the context.

How many CPU cores do you have?  Is it by any chance less than 16?  You might try setting it to a value equal or less than your core count and see if that improves reliability.

**Comment by dhiltgen** [comment]
Please make sure to upgrade to the latest version, and try first with the default settings, and if you're still having troubles, please share more information about your setup and I'll reopen the issue.
