### ISSUE TITLE
2024-June-25 conda-forge ollama v0.1.17 is too old

### ISSUE THREAD

**Issue by polySugar** [ollama/ollama#5273]
Please update the version in conda-forge after normal security checks.

https://anaconda.org/conda-forge/ollama 
current values 2024-June-25
linux-64 v0.1.17
osx-64 v0.1.17
osx-arm64 v0.1.17
win-64 v0.1.17 

is too old and is lacking in model-compatibility . Please note I appreciate your efforts and this feature request is just a reminder.

https://stackoverflow.com/a/67134507

**Comment by dhiltgen** [comment]
The core Ollama maintainers don't manage this, and I'm not sure who does actually.  Please reach out to the folks who run this site to ask them to either update it, or take it down if it's not being maintained.
