### ISSUE TITLE
"How to utilize the Ollama local model in Windows 10 to generate the same API link as OpenAI, enabling other programs to replace the GPT-4 link? Currently, entering 'ollama serve' in CMD generates the 'http://localhost:11434' link, but replacing this link with the GPT-4 link in applications does not work. Please provide a command to generate a link that supports replacing GPT-4."

### ISSUE THREAD

**Issue by windkwbs** [ollama/ollama#5277]
"How to utilize the Ollama local model in Windows 10 to generate the same API link as OpenAI, enabling other programs to replace the GPT-4 link? Currently, entering 'ollama serve' in CMD generates the 'http://localhost:11434/' link, but replacing this link with the GPT-4 link in applications does not work. Please provide a command to generate a link that supports replacing GPT-4.""How to utilize the Ollama local model in Windows 10 to generate the same API link as OpenAI, enabling other programs to replace the GPT-4 link? Currently, entering 'ollama serve' in CMD generates the 'http://localhost:11434/' link, but replacing this link with the GPT-4 link in applications does not work. Please provide a command to generate a link that supports replacing GPT-4."

**Comment by Luke100000** [comment]
You forgot `/v1/`, see https://github.com/ollama/ollama/blob/main/docs/openai.md

Also please don't abuse titles like this.

**Comment by dhiltgen** [comment]
Docs for the OpenAI Compatibility can be found here - https://github.com/ollama/ollama/blob/main/docs/openai.md
