### ISSUE TITLE
Is it possible to start llama server through dynamic dependency library?

### ISSUE THREAD

**Issue by leeyiding** [ollama/ollama#5278]
Hi, I'm trying to run Ollama in [Nanos Unikernel](https://github.com/nanovms/nanos), Unikernel a single-process operating system.

I found that in https://github.com/ollama/ollama/commit/58d95cc9bd446a8209e7388a96c70367cbafd653, the running mode of llama server changed from loading dynamic dependency libraries to running through subprocess. Therefore, before version 0.1.32, I could run Ollama normally in Nanos, but it could not run normally in later versions.

I would like to ask whether it is possible to continue to provide the method of loading llama server as a dynamic dependency library and avoid using subprocess. Perhaps the two methods can coexist and users can choose by themselves.

Looking forward to your reply, thank you very much.

**Comment by dhiltgen** [comment]
Process isolation has helped us improve reliability, and is a cornerstone of the new concurrency support.   We are looking at refining how we ingest llama.cpp via PR #5034 however that will still use the subprocess model.  It isn't implemented yet, but we've considered a lowest common denominator CPU version linked into the main application (without any AVX* extensions) so it is theoretically possible that could be wired up to skip the subprocess isolation, but inference performance will be slow by comparison the subprocess runners with GPU or vector extension support.

**Comment by leeyiding** [comment]
Got it
