### ISSUE TITLE
ollama cannot running

### ISSUE THREAD

**Issue by liliang-cn** [ollama/ollama#5288]
### What is the issue?

ollama list
Error: something went wrong, please see the ollama server logs for details

### OS

macOS

### GPU

Apple

### CPU

Apple

### Ollama version

0.1.46

**Comment by lstep** [comment]
What are the logs contents? (check `~/.ollama/logs/server.log`)

**Comment by liliang-cn** [comment]
I re-installed ollama.app, now it's working fine.
<img width="1694" alt="image" src="https://github.com/ollama/ollama/assets/20553741/191211a4-14fc-48a8-b79f-5fbe6d04afae">

**Comment by dhiltgen** [comment]
Happy to hear the reinstall cleared up whatever went wrong.
