### ISSUE TITLE
ollama-go bindings

### ISSUE THREAD

**Issue by k0marov** [ollama/ollama#5290]
Hi, I'm interested in having a native Go client library for Ollama REST API, like the Python and JS ones. 
I can start myself, but want to ask: is someone already working on it? 
If it's not taken, I'll be glad to make this contribution. 

Thanks for this awesome system!

**Comment by Gaurav-Gosain** [comment]
The official go bindings to the API already exist. I recently went looking for it myself and found these https://github.com/ollama/ollama/blob/main/api/client.go

Docs: https://pkg.go.dev/github.com/ollama/ollama/api


There are a few usage examples too:
- https://github.com/ollama/ollama/blob/main/examples/go-chat/main.go
- https://github.com/ollama/ollama/blob/main/examples/go-generate-streaming/main.go
- https://github.com/ollama/ollama/blob/main/examples/go-generate/main.go
- https://github.com/ollama/ollama/blob/main/examples/go-http-generate/main.go
- https://github.com/ollama/ollama/blob/main/examples/go-multimodal/main.go
- https://github.com/ollama/ollama/blob/main/examples/go-pull-progress/main.go

**Comment by k0marov** [comment]
My bad, thank you! Maybe it would be a good option to include a mention of these Go bindings in the "Libraries" section of the README.md?

**Comment by Gaurav-Gosain** [comment]
Agreed haha, for a library written in go, the go bindings don't seem to get the love they deserve 😅

**Comment by pdevine** [comment]
We're just a small team, so it's hard to keep all of the libraries up to date. 😅  The CLI client _does_ use the Go bindings exclusively though, so to some extent they may actually work even better than the Python/JS ones. I'm going to go ahead and close the issue.
