### ISSUE TITLE
upgrade attempt failed

### ISSUE THREAD

**Issue by NeilWang079** [ollama/ollama#5296]
### What is the issue?

time=2024-06-26T18:25:20.752+08:00 level=INFO source=updater.go:102 msg="New update available at https://github.com/ollama/ollama/releases/download/v0.1.46/OllamaSetup.exe"
time=2024-06-26T18:25:42.556+08:00 level=ERROR source=updater.go:212 msg="failed to download new release: error checking update: Get \"https://github.com/ollama/ollama/releases/download/v0.1.46/OllamaSetup.exe\": read tcp 192.168.31.139:3633->20.205.243.166:443: wsarecv: An established connection was aborted by the software in your host machine."
time=2024-06-26T18:25:50.338+08:00 level=WARN source=lifecycle.go:44 msg="upgrade attempt failed: no update downloads found"
time=2024-06-26T18:42:36.669+08:00 level=WARN source=lifecycle.go:44 msg="upgrade attempt failed: no update downloads found"

### OS

Windows

### GPU

Nvidia

### CPU

AMD

### Ollama version

v0.1.45

**Comment by d-kleine** [comment]
Tried that? https://github.com/ollama/ollama/issues/4944#issuecomment-2174521404

**Comment by dhiltgen** [comment]
I wasn't able to reproduce this.  On a win 11 system 0.1.45 successfully detected the update was available, and downloaded it.

The error message `wsarecv: An established connection was aborted by the software in your host machine` seems to imply something else on the system caused the abort.  Perhaps a firewall or AV product is blocking access to the URL?
