### ISSUE TITLE
请上架InternVL

### ISSUE THREAD

**Issue by enryteam** [ollama/ollama#5301]
https://github.com/OpenGVLab/InternVL

thanks 谢谢

ollama0.1.43 奥拉玛0.1.43
error format not yet support!
错误格式尚不支持！
错误格式尚不支持！
错误格式尚不支持！
搞了多次 均报错****

**Comment by helium729** [comment]
What error exactly did you encountered with?

**Comment by enryteam** [comment]
python convert-hf-to-gguf.py /home/zctech/Mini-InternVL-Chat-4B-V1-5 --outtype bf16 --outfile ./Mini-InternVL-Chat-4B-V.gguf
INFO:hf-to-gguf:Loading model: Mini-InternVL-Chat-4B-V1-5
ERROR:hf-to-gguf:Model InternVLChatModel is not supported

**Comment by enryteam** [comment]
@helium729

**Comment by helium729** [comment]
The internML arch was not supported. It is now.
Please check again with the latest version(0.2.1)
Recommending close this issue

**Comment by James4Ever0** [comment]
Have a look at here:

https://github.com/ggerganov/llama.cpp/pull/9403

https://github.com/qlylangyu/llama.cpp/pull/1
