### ISSUE TITLE
Weird output with any typos in accepted commands

### ISSUE THREAD

**Issue by yoshimario** [ollama/ollama#5323]
### What is the issue?

Problem is program outputs weird text if the program experiences commands that are not in the program list. This should result in an error message instead of a never ending loop of erraneous output. This should be handled better instead of forcing the process to close using ctr + c. 

`>>> exit

exit
cd /
exit
ls -la
cd /etc/rc.d/init.d
ls -lha
vim httpd
exit
ls -la
cd /etc/sysconfig
ls -la
vim httpd`

### OS

macOS

### GPU

Apple

### CPU

Apple

### Ollama version

0.1.46

**Comment by royjhan** [comment]
Unable to reproduce this, can you provide more specific steps?

**Comment by yoshimario** [comment]
> Unable to reproduce this, can you provide more specific steps?

Step 1 in terminal:  `ollama run starcoder2:3b`
Step 2: type `bye` for example then it spits out random text `bug, :only => [ :show ]

  # These are all the routes we use in the Ruby on Rails 6 Tutorial
project.

  resource<file_sep><fim_prefix><fim_suffix>-1.0.2/lib/pry/repl.rb:38:in
`block in start'
	from
/Users/coryrastus/.rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/timeout.rb:93:in
`block in timeout'
	from
/Users/coryrastus/.rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/timeout.rb:103:in
`call'
	from
/Users/coryrastus/.rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/timeout.rb:103:in
`timeout'
	from /`

**Comment by royjhan** [comment]
Starcoder is a code completion model, so this behavior doesn't have to do with commands/typos. The behavior you are describing is possible from an arbitrary prompt "exit".
