### ISSUE TITLE
Ollam does not work with some models.

### ISSUE THREAD

**Issue by grafsoft** [ollama/ollama#5332]
Hi,

When I want to run phi3 I get
Error: llama runner process no longer running: -1

Newest version installed with 
 curl -fsSL https://ollama.com/install.sh | sh

I try ollama --version :
ollama version is 0.0.0
Warning: client version is 0.1.47

BS: ubuntu 22.04.4 LTS

Would it help to uninstall and re-install? Is there anything to consider when doing that?

Best

Peter

**Comment by reply2future** [comment]
Duplicate issue, you should try to restart the server of ollama. https://github.com/ollama/ollama/issues/4944#issuecomment-2174521404

**Comment by grafsoft** [comment]
I did already, and restart the server - does not help.

**Comment by dhiltgen** [comment]
The sever version reporting `0.0.0` indicates you built from source.  Many fixes have happened recently to support phi3, so it's possible you've built an older git commit on the repo before those fixes went in.   Either refresh your local repo and rebuild or remove the prior custom build, and update to the latest official binaries and you should be set.
