### ISSUE TITLE
ollama -v shows correct ollama version but different client version

### ISSUE THREAD

**Issue by ganakee** [ollama/ollama#5334]
### What is the issue?

I custom compile Ollama for AMD. I change the version file to read the custom version such as `0.1.47-amd`. 

Yet, when I run `ollama -v ` within the compiled directory (I emphasize this as this is not running the ollama executable elsewhere) I see:
```
ollama version is 0.1.47-amd
Warning: client version is 0.1.20
```
The client never seems to update. (And I do not really know what client means.)

### OS

Linux

### GPU

AMD

### CPU

AMD

### Ollama version

0.1.47

**Comment by royjhan** [comment]
Have you installed Ollama with a separate package manager, can you uninstall there? A similar symptom happens in MacOS with brew install ollama.

**Comment by Huojunning** [comment]
ps -ef|grep ollama     
kill -9 ollama

reload

**Comment by ganakee** [comment]
Thank you @dhiltgen and @royjhan.

Yes, this was my issue. I had originally installed on Linux via the installer script.
```
which ollama
/usr/local/bin/ollama

ls olla*
ollama   ollama-amd.gpu
```

When I custom compile, I copy the executable `ollama` to `/usr/local/bin/ `but rename it to `ollama-amd.gpu` (because this is a custom, AMD GPU build on ROCM). As you both noted, this resulted in `ollama -v `showing two versions effectively when I ran `ollama -v`--one showing the custom compile version and one showing the old (and forgotten) script installed `ollama`. 

I used a symbolic link `sudo ln -s ollama ollama.gpu` to fix the issue. (One could also just copy the `ollama` executable as `ollama`.)

Now, when I run, I get a single entry and not the client version as reported before.:
```
ollama -v
ollama version is 0.1.47-AMD-ROCM61  {this is the custom name assigned during compile from my compiler directory located in` version/version.go` and will differ between users}
```

Thanks for the help.

Thank you to @Huojunning as well. This suggestion did not help in my case, but I understand why you suggested killing the running ollama instance and then re-running ollama--for me, from systemd as in `sudo systemd restart ollamagpu.service`.

**Comment by skhatri** [comment]
This can happen if you have an ollama already running. Kill all processes and install again to not have the mismatch.


```
ollama version is 0.2.7
Warning: client version is 0.5.1
```

**Comment by stephenreid321** [comment]
Getting this with the latest ollama on macOS

ollama version is 0.3.4
Warning: client version is 0.9.3

**Comment by dhiltgen** [comment]
@stephenreid321 does your Ollama menu have an entry for "Restart to update" ?  If so, select that to restart the server to get it running the new version.
