### ISSUE TITLE
Double text during installation

### ISSUE THREAD

**Issue by DuckyBlender** [ollama/ollama#5335]
### What is the issue?

![image](https://github.com/ollama/ollama/assets/42645784/1177c8b7-72c9-44dc-b1ef-3dcd77c8c940)
```
>>> The Ollama API is now available at 127.0.0.1:11434.
>>> Install complete. Run "ollama" from the command line.
```
This text was printed out twice :)

### OS

WSL2

### GPU

Nvidia

### CPU

Intel

### Ollama version

0.1.47

**Comment by pdevine** [comment]
Sorry for the slow response! I'm wondering if this happened because you couldn't connect to the port afterward? I haven't seen that during the install.

**Comment by DuckyBlender** [comment]
This has been fixed a long time ago with some release, i'll close this issue
