### ISSUE TITLE
"Mock" model

### ISSUE THREAD

**Issue by mweel1** [ollama/ollama#5344]
We are developing some application on ollama and the performance would be ok for a user, however when we are developing software the lag time to generate can be very slow.

Would it be possible to build a "development" model that didn't have a lot of parameters but at least let you build a product at a reasonable pace?

**Comment by mili-tan** [comment]
Maybe try this:
https://ollama.com/library/tinyllama:1.1b-chat-v0.6-q2_K
https://ollama.com/library/qwen2:0.5b-instruct-q2_K

**Comment by pdevine** [comment]
@mweel1 Definitely check out some of the smaller models that @mili-tan mentioned. There is also the [2B gemma model](https://ollama.com/library/gemma).
