### ISSUE TITLE
Error: llama runner process has terminated: signal: aborted (core dumped) 

### ISSUE THREAD

**Issue by mikestut** [ollama/ollama#5367]
### What is the issue?

ollama run gemma2:27b-instruct-q8_0
,....
Error: llama runner process has terminated: signal: aborted (core dumped) 

![image](https://github.com/ollama/ollama/assets/88723510/c5c3a9fb-c342-43e6-a002-454fd232e7c3)
nvcc -V
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Wed_Jun__8_16:49:14_PDT_2022
Cuda compilation tools, release 11.7, V11.7.99
Build cuda_11.7.r11.7/compiler.31442593_0

### OS

Linux

### GPU

Nvidia

### CPU

Intel

### Ollama version

0.1.45

**Comment by rick-github** [comment]
gemma2 needs ollama  0.1.47.  But there's also an issue with inaccurate calculation of required VRAM, see https://github.com/ollama/ollama/issues/5350#issuecomment-2196929454

**Comment by felixgao** [comment]
I got the same with the 9b model

➜  media ollama list       
NAME                               	ID          	SIZE  	MODIFIED       
gemma2:latest                      	c19987e1e6e2	5.4 GB	21 minutes ago	
yi:9b                              	3af70141e8eb	5.0 GB	6 days ago    	
phi3:14b                           	1e67dff39209	7.9 GB	6 days ago    	
deepseek-coder-v2:latest           	6d3369b54a0e	8.9 GB	10 days ago   	
➜  media ollama run gemma2   
Error: llama runner process has terminated: signal: aborted (core dumped)

**Comment by felixgao** [comment]
upgraded to the latest ollama fixed my problem

**Comment by jmorganca** [comment]
Thanks @felixgao @mikestut - this should be fixed now in 0.1.48
