### ISSUE TITLE
run gemma2 error

### ISSUE THREAD

**Issue by isold23** [ollama/ollama#5369]
### What is the issue?

Error: llama runner process has terminated: signal: abort trap error:error loading model architecture: unknown model architecture: 'gemma2'

### OS

macOS

### GPU

Apple

### CPU

Apple

### Ollama version

ollama version is 0.1.42

**Comment by jmorganca** [comment]
Hi there, sorry for the error. Gemma 2 requires Ollama 0.1.47 or higher: https://ollama.com/download

**Comment by jghorton14** [comment]
Can confirm. Upgrade is needed and worked as intended. Thanks for this amazing project!
