### ISSUE TITLE
Referring offline downloaded models in code

### ISSUE THREAD

**Issue by RaoPisay** [ollama/ollama#5383]
### What is the issue?

Need help: I trying to refer model downloaded from ollama. I know the path where it is downloaded `~/.ollama/models/*`
In the python code given
Python code --
`tokenizer = AutoTokenizer.from_pretrained(model)`
-- Python code

Here I want to mentioned the `model` variable with the path for example like I've downloaded 2 models and those are `llama3` and `gemma:2b`
When I navigate to the path `~/.ollama/models` I see 2 folder and those are `blobs` and `manifests`
In `blobs` folder I see the big files 4.7GB refers to `llama3` and 1.7GB refers to `gemma:2b`. 
I tried both the files path in place`model` variable but no luck
Below is the SS of the path just for reference
![image](https://github.com/ollama/ollama/assets/8242864/d4fb1c14-b592-409f-8ad6-e65d31c7a9e4)

has anyone tried to refer ollama downloaded offline models in their code like the python statement given above?

### OS

Windows

### GPU

Nvidia

### CPU

AMD

### Ollama version

0.1.48

**Comment by rick-github** [comment]
The files that ollama (actually llama.cpp) uses are in GGUF format, different from the format of the files used in transformers.  There is [some support](https://huggingface.co/docs/transformers/v4.42.0/gguf) for GGUF in transformers and you need to specify it's a GGUF file with `gguf_file`.  Note it only does a few architectures, so your downloaded models may not work and you might have to try a different one.

**Comment by RaoPisay** [comment]
Thank you for the clarification; I had been searching extensively online to find a method that aligned with my needs

I appreciate that Ollama downloads the entire LLM model, although I've encountered challenges in utilizing it as intended. Perhaps exploring enhancements could further optimize its usability.
