### ISSUE TITLE
deepseek-coder-v2-lite flash attention not enabled

### ISSUE THREAD

**Issue by reddev-aroy** [ollama/ollama#5390]
### What is the issue?

As soon as the context length limit is reached for deepseek-coder-v2-lite the models are just repeating previous answers and keeps looping itself even after asking for something else in its response. This issue is resolved in LM Studio as after enabling flash attention this seems to be resolved, however this issue still exists in the latest ollama 0.1.48
I am suspecting it to be issue with the model itself but flash attention seems to resolve it in LM Studio. Need help resolving this issue in Ollama as running this model in cpu only seems to be faster for me attest in ollama than LM Studio with num_gpu 0

Ollama version - 0.1.48
Model used - deepseek-coder-v2-lite-instruct-Q5_K_M

### OS

macOS

### GPU

Apple

### CPU

Apple

### Ollama version

0.1.48

**Comment by rick-github** [comment]
You can enable flash attention in ollama by setting OLLAMA_FLASH_ATTENTION=1 in the environment.

**Comment by reddev-aroy** [comment]
> You can enable flash attention in ollama by setting OLLAMA_FLASH_ATTENTION=1 in the environment.

Tried below and restarting ollama, doesn't seem to work. Maybe deepseek-coder-v2 in ollama is turning off flash_attn automatically for this model architecture? Not sure.

launchctl setenv OLLAMA_FLASH_ATTENTION 1

**Comment by rick-github** [comment]
It's an issue with llama.cpp, it [turns off flash attention](https://github.com/ggerganov/llama.cpp/blob/1c5eba6f8e628fb0a98afb27d8aaeb3b0e136451/src/llama.cpp#L17412) when the K and V heads are different.
