### ISSUE TITLE
How do I find LLMs in the GitHub repository?

### ISSUE THREAD

**Issue by qzc438** [ollama/ollama#5391]
As the title describes, how do I find LLMs in the GitHub repository? Does the GitHub repository have a specific location for storing LLMs?

**Comment by bearjaws** [comment]
They aren't stored in the git repo, only some metadata about them is. 

Most of them pull from https://huggingface.co/

If you want to search for compatible models then this is the correct url: https://ollama.com/library

**Comment by qzc438** [comment]
Thank you.
