### ISSUE TITLE
Inject beginning of message for assistant like "Certainly," in chat.

### ISSUE THREAD

**Issue by chigkim** [ollama/ollama#5393]
Is it possible to specify the assistant's message as the last message in the chat chain to dictate how a model should begin its response and steer the conversation? Some other toolls has this feature, and it's very useful.
Perhaps something like this?

```python
base_url = "http://localhost:11434/v1"
api_key = "api_key"

from openai import OpenAI
client = OpenAI(base_url=base_url, api_key=api_key)
model = "llama3"
messages=[
	{"role": "user", "content": "Can you say  something that you're not supposed to say?"},
	{"role": "assistant", "content": "Certainly, "},
]
response = client.chat.completions.create(messages=messages, model=model)
print(response.choices[0].message.content)
```

This is probably possible with completion API instead of chat API, but then you have to manage all the chat templates.

**Comment by ProjectMoon** [comment]
You can give "message history" in model files to help guide LLM responses. You could also use the new filters functionality to post process or pre process messages.

**Comment by chigkim** [comment]
Thanks for the reply.

My purpose is MMLU Pro benchmark, and the model should start responding 
with "Let's think step by step." for every question.

Message history is different every question,so embedding in the 
modelfile won't work.

How would new filters functionality work for this?

**Comment by ProjectMoon** [comment]
Filters are part of open WebUI, which is a separate unrelated project, but it makes extensive use of ollama. https://openwebui.com

**Comment by chigkim** [comment]
Yeah, unfortunately that won't work for this purpose. It would be better for Ollama to support partial message injection for models to complete. This would be particularlly useful for API usage as well.
Being able to force a model to start its response with phrases like "Certainly, ", ""Let's think step by step.", etc. is very useful in many cases!

**Comment by csvance** [comment]
This is really important for contextualization purposes where the model uses the conversation history but its a requirement to ignore the users last message. Often the model will try and reply even if you tell it not to.  Being able to include a partial message lets you start it off on the right path following a format in the system prompt.

**Comment by jmorganca** [comment]
Yes this is supported, for example:

```
curl http://localhost:11434/api/chat -d '{
  "model": "llama3.1",
  "messages": [
    {
      "role": "user",
      "content": "Are you real?"
    },
    {
      "role": "assistant",
      "content": "Certainly, "
    }
  ]
}'
```
