### ISSUE TITLE
deepseek-v2:236b Startup Issues

### ISSUE THREAD

**Issue by SongXiaoMao** [ollama/ollama#5396]
### What is the issue?

![微信截图_20240701092730](https://github.com/ollama/ollama/assets/55074934/b0fe48f4-e2eb-47e4-954b-29a72ce41bc1)

Computer configuration: 3090*4 128g memory

There are problems starting both models

### OS

Linux

### GPU

Nvidia

### CPU

Intel

### Ollama version

ollama version is 0.1.48

**Comment by dhiltgen** [comment]
It's possible this might be related to the recent nvidia 555 driver updates.  Can you try the workaround steps https://github.com/ollama/ollama/blob/main/docs/troubleshooting.md#container-fails-to-run-on-nvidia-gpu and see if that helps?

**Comment by dhiltgen** [comment]
If the workarounds don't resolve the problem, please make sure to upgrade, and share an updated server log and I'll reopen the issue.
