### ISSUE TITLE
V0.1.48 The model is loaded into the GPU Memory but runs on the CPU

### ISSUE THREAD

**Issue by wxtt522** [ollama/ollama#5397]
### What is the issue?

 ollama run gemma2:27b 
![image](https://github.com/ollama/ollama/assets/28422636/313df4c1-141f-4c61-aeeb-3525cc6fd975)
The same goes for loading other models. It was normal in the previous version. I did not change any environment variables.

### OS

Windows

### GPU

Nvidia

### CPU

Intel

### Ollama version

0.1.48

**Comment by issaccv** [comment]
I also encountered the same problem. According to my investigation, the problem is caused by OLLAMA_NUM_PARALLEL. When the value of this flag is set to a large value (such as 16 or 32), ollama will allocate more memory than VRAM, which causes some layers not to be offloaded to the GPU.

**Comment by dhiltgen** [comment]
@wxtt522 can you share your server log so I can see what's going on?

**Comment by wxtt522** [comment]
> @wxtt522 can you share your server log so I can see what's going on? Can you also share what `ollama ps` says?

[server-1.log](https://github.com/user-attachments/files/16076630/server-1.log)

Of course, this is my server log, I have adjusted the parameters mentioned above OLLAMA_NUM_PARALLEL, but it has no effect.
I noticed memory.available in the log，This is not normal. I found that the model started to be loaded into the memory when the gpu:p40 was loaded into the 4g gpu memory，But I didn't find any other way to adjust it

**Comment by wxtt522** [comment]
(base) PS C:\Users\admin> ollama ps
NAME                                            ID              SIZE    PROCESSOR       UNTIL
deepseek-coder-v2:16b-lite-instruct-q8_0        44250301ba51    18 GB   83%/17% CPU/GPU Forever

**Comment by wxtt522** [comment]
Although I don’t know the reason, I solved the problem by resetting the graphics card driver configuration
