### ISSUE TITLE
Please support models of rerank type

### ISSUE THREAD

**Issue by yushengliao** [ollama/ollama#5399]
There are so many users for the Ollama project, why hasn't it been so long to support Renanker
Similar software such as Localai、xinreference already supports rerank

https://localai.io/features/reranker/
https://inference.readthedocs.io/en/latest/models/builtin/rerank/index.html

![image](https://github.com/ollama/ollama/assets/29765903/016a2260-23b2-4296-9d51-9b725260b69d)

**Comment by yushengliao** [comment]
https://huggingface.co/BAAI/bge-reranker-v2-m3

**Comment by mptgg** [comment]
+1 Need this feature badly!

**Comment by mouse33333** [comment]
100% agree!

**Comment by enryteam** [comment]
+1

**Comment by Maxime479** [comment]
+1 That would be absolutely fantastic !

We need that so much.
It's a real pain to have to use Xinference or LocalAI just for this.

**Comment by springrain** [comment]
+1

**Comment by geneives233** [comment]
+1

**Comment by chubin518** [comment]
+1

**Comment by jmorganca** [comment]
Thanks for the issue! Merging with https://github.com/ollama/ollama/issues/3368

**Comment by fmecool** [comment]
We need rerank!!!
