### ISSUE TITLE
Gemma2 work incorrect in parallel request

### ISSUE THREAD

**Issue by dudukk1312** [ollama/ollama#5400]
### What is the issue?

I'm testing for the multiple requests that can be handled in my system. 
For Gemma2, when executing a single request, the respond is perfect.
But for multiple requests, the response looks so dummy.
![image](https://github.com/ollama/ollama/assets/33556384/3bdbbf5a-264e-4ba8-8f00-b6f3ea31f780)
I tried multi-request with llama3 but it worked perfectly on that.

### OS

Windows

### GPU

Nvidia

### CPU

AMD

### Ollama version

v0.1.48

**Comment by dhiltgen** [comment]
I'm not able to reproduce.  On a GPU where the model fully loads into VRAM, sending parallel requests doesn't result in gibberish responses.

Can you share more information about your setup?  Is the model split between GPU/CPU?  How much VRAM do you have?
