### ISSUE TITLE
ollama create model success but ps command returns empty

### ISSUE THREAD

**Issue by tammypi** [ollama/ollama#5404]
### What is the issue?

I used `ollama create emailphishing -f emailphishing.mf ` command, and it printed "success":
![企业微信截图_17198251075429](https://github.com/ollama/ollama/assets/4264858/b24f85a3-d399-4dab-a6ec-0893bc0711ef)
When I used command `ollama ps`, and it returned empty list:
![企业微信截图_17198251869432](https://github.com/ollama/ollama/assets/4264858/e5e4c139-629e-44c9-87fd-d0b00807d3e2)

### OS

Linux

### GPU

Other

### CPU

Intel

### Ollama version

0.1.48

**Comment by rick-github** [comment]
You have to run the model in order for it to be loaded and displayed in the `ps` list.

```
ollama run emailphishing
```

If you want to verify the model exists, you use the `list` command, not the `ps` command.

```
ollama list
```

**Comment by tammypi** [comment]
> You have to run the model in order for it to be loaded and displayed in the `ps` list.
> 
> ```
> ollama run emailphishing
> ```
> 
> If you want to verify the model exists, you use the `list` command, not the `ps` command.
> 
> ```
> ollama list
> ```

Thanks for your reply. Yes, when I connected open-webui with Ollama, the model appeared in the ps list when I sent a message on the open-webui webpage.

**Comment by jeffmacdonald** [comment]
I have just experienced this issue, where I was running a model. But it was in a previous closed terminal. So now ollama ps shows nothign, but ps aux|grep ollama shows the model running. I had to quit Ollama.
