### ISSUE TITLE
Ollama runs the model and loads it in GPU, but it doesn't clear GPU memory after exiting

### ISSUE THREAD

**Issue by PiyushDuggal-source** [ollama/ollama#5406]
### What is the issue?

![image](https://github.com/ollama/ollama/assets/63952890/d7357dc5-b427-4d9e-be94-592f851c619a)
As you can see, I exited from the prompt, but its still has model loaded in the GPU memory.

### OS

Linux

### GPU

Nvidia

### CPU

Intel

### Ollama version

0.1.47

**Comment by rick-github** [comment]
ollama is a client/server architecture.  the model is loaded by the server and remains loaded until either the server exits, or the model timeout expires (default 5 minutes).  the prompt is printed by the client, which you start and stop independently of the server.

**Comment by igorschlum** [comment]
hI @PiyushDuggal-source Does Rick explaination solve this issue? If so, please close the issue.

**Comment by PiyushDuggal-source** [comment]
Hey, yes. Thanks very much!
