### ISSUE TITLE
OLLAMA_NOHISTORY doesn't work

### ISSUE THREAD

**Issue by sogawa-sps** [ollama/ollama#5414]
### What is the issue?

OLLAMA_NOHISTORY is set to "true" but the history is still being written into the "history" file.

> ollama[77458]: 2024/07/01 14:04:09 routes.go:1064: INFO server config env="map[CUDA_VISIBLE_DEVICES: GPU_DEVICE_ORDINAL: HIP_VISIBLE_DEVICES: HSA_OVERRIDE_GFX_VERSION: OLLAMA_DEBUG:false OLLAMA_FLASH_ATTENTION:false OLLAMA_HOST:http://127.0.0.1:11434 OLLAMA_INTEL_GPU:false OLLAMA_KEEP_ALIVE: OLLAMA_LLM_LIBRARY: OLLAMA_MAX_LOADED_MODELS:2 OLLAMA_MAX_QUEUE:512 OLLAMA_MAX_VRAM:0 OLLAMA_MODELS:/usr/share/ollama/.ollama/models **_OLLAMA_NOHISTORY:true_** OLLAMA_NOPRUNE:false OLLAMA_NUM_PARALLEL:1 OLLAMA_ORIGINS:[http://localhost https://localhost http://localhost:* https://localhost:* http://127.0.0.1 https://127.0.0.1 http://127.0.0.1:* https://127.0.0.1:* http://0.0.0.0 https://0.0.0.0 http://0.0.0.0:* https://0.0.0.0:* app://* file://* tauri://*] OLLAMA_RUNNERS_DIR: OLLAMA_SCHED_SPREAD:false OLLAMA_TMPDIR: ROCR_VISIBLE_DEVICES:]"

### OS

WSL2

### GPU

Nvidia

### CPU

Intel

### Ollama version

0.1.48

**Comment by rick-github** [comment]
This line is logged by the server.  The history is managed by the client.  Try

```
OLLAMA_NOHISTORY=1 ollama run some-model
```

I tested this on 0.1.48 and no history was written.

**Comment by jmorganca** [comment]
Thanks @rick-github yes indeed this is something you can configure where you're running `ollama run` (Ollama and its API does not keep history)

**Comment by sogawa-sps** [comment]
Thank you @rick-github, @jmorganca, it works fine. It still creates a zero-size history file but doesn't write anything there.

I was confused because the server also had the same parameters, and I saw in the server logs that it was set to false by default.

`OLLAMA_NOHISTORY:false`
