### ISSUE TITLE
DeepSeek-Coder-V2 (Lite) spouts GGGs

### ISSUE THREAD

**Issue by lorenzodimauro97** [ollama/ollama#5418]
### What is the issue?

Eventually when using deepseek-coder-v2:16b-lite-instruct-q8_0 and Open Web UI (but also other means like for example continuedev) the model will stop working and spout GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG regardless of the input:

![image](https://github.com/ollama/ollama/assets/50343905/b90c39ae-9269-4f7f-b3a5-dda65186a208)

The only fix is to force stop and restart the model, which is bothersome enough to be worth issuing a bug

### OS

Windows

### GPU

AMD

### CPU

AMD

### Ollama version

0.1.48

**Comment by igorschlum** [comment]
Hi @lorenzodimauro97, with how many queries do the GGG appear?

**Comment by lorenzodimauro97** [comment]
It's not consistent, they can appear as soon as 2 queries or as long as about 30+, furthermore, there seems to be no errors on the console log

**Comment by igorschlum** [comment]
BTW this model is the only one exept ChatGPT that can answer correctly this prompt:
how many days between febuary 2nd 2021 and may 23rd, 2024?
I will try to ask him more questions. I'm on a macbook with 32GB or RAM.

**Comment by jmorganca** [comment]
Hi there, would it be possible to re-pull the model? This should fix things. Let me know if it continues though

**Comment by igorschlum** [comment]
@jmorganca I played with this model since then and had no problem on MacOS.

**Comment by lorenzodimauro97** [comment]
> Hi there, would it be possible to re-pull the model? This should fix things. Let me know if it continues though

I did re-pull the model but problem still occurs:
![image](https://github.com/ollama/ollama/assets/50343905/971dd3dd-15af-48e6-a7b7-d1826960fbf4)

**Comment by igorschlum** [comment]
I played quite a lot with this Model on MacOS without any problem. How much memory do you have? Can you write a simple Python script that can reproduce the issue so other users of Ollama could try to help on this issue?

**Comment by lorenzodimauro97** [comment]
> I played quite a lot with this Model on MacOS without any problem. How much memory do you have? Can you write a simple Python script that can reproduce the issue so other users of Ollama could try to help on this issue?

I have 48 GB DDR4 at 3800 MHz, a Ryzen 5800X and an AMD 6800XT. I am using Windows 11.

 I do not incur in memory saturation with the model, I stay at about 50-60% RAM usage, going 80-90 with heavy coding, but still, should be enough.

I do not have the means to reproduce it because it does not happen consistently. It can happen as often as after 3 queries or even after half a day's worth of coding, but still I find it hard to reproduce.

What I can say though is that it's the only model that has this issue, none of my other models seem to fail as hard and as frequently as this one does.
