### ISSUE TITLE
Unable to load model because of incorrect model path

### ISSUE THREAD

**Issue by whichxjy** [ollama/ollama#5430]
### What is the issue?

After downloading model with `ollama pull llama3`, calling API `POST /api/chat` with `ollama serve` running would get this error:

`model 'llama3' not found, try pulling it first`

> related issue: #3876 

Problem:

- When I run `ollama pull llama3`, the `OLLAMA_MODELS` env is not set. Then this model path is `/usr/share/ollama/.ollama/models`.

- But when I run `ollama serve`, the `OLLAMA_MODELS` env would be `~/.ollama/models`. Because of that, calling `POST /api/chat` could not find the model downloaded before.

I solved it when I set `OLLAMA_MODELS` to `/usr/share/ollama/.ollama/models` when running `ollama serve`.

### OS

Linux

### GPU

Nvidia

### CPU

Intel

### Ollama version

0.1.48

**Comment by dhiltgen** [comment]
I'm not sure what you're trying to do.  Mixing `ollama serve` running manually and the systemd service with inconsistent configuration isn't going to work since the systemd service uses a different user account.   If you're using the systemd service, you shouldn't run `ollama serve` manually with a different account.

**Comment by whichxjy** [comment]
I just follow the [docs](https://github.com/ollama/ollama/blob/main/README.md#cli-reference) step by step and it doesn't work when running `ollama serve`. Maybe adding more info about that (like #3936 ?) would be better.

**Comment by dhiltgen** [comment]
Those docs are a reference to the various CLI commands, not a step-by-step tutorial meant to be run in sequence.

My best guess is you're trying to learn how to set up an alternative location for storing the models.  If that's the case, then the following two sections of our FAQ will be helpful:
1. [How to configure the ollama server](https://github.com/ollama/ollama/blob/main/docs/faq.md#how-do-i-configure-ollama-server)
2. [Where are models stored ](https://github.com/ollama/ollama/blob/main/docs/faq.md#where-are-models-stored)

If that wasn't what you were trying to do, please explain what your goal was and I'll try to point you in the right direction.
