### ISSUE TITLE
level=ERROR source=sched.go:388 msg="error loading llama server" error="llama runner process no longer running: -1 "

### ISSUE THREAD

**Issue by popav4** [ollama/ollama#5432]
### What is the issue?

Macbook Air M1
Run with Docker:
`docker run -d -v ollama:/root/.ollama -p 11434:11434 --name ollama ollama/ollama`
`docker exec -it ollama ollama run codestral:22b`
Error:
> level=ERROR source=sched.go:388 msg="error loading llama server" error="llama runner process no longer running: -1 "
[docker.log](https://github.com/user-attachments/files/16067480/docker.log)

### OS

Docker

### GPU

Other

### CPU

Apple

### Ollama version

0.1.48

**Comment by rick-github** [comment]
Logs say `memory.available="[7.3 GiB]"` and `memory.required.full="13.1 GiB"` so I would guess that your hardware can't load the model.

**Comment by dhiltgen** [comment]
This is a dup of #4955 where we don't currently detect that the first model we try to load wont fit in available system memory when running in CPU mode.   Once that's fixed, we'll give a better error message than crashing when we fail to allocate enough memory.  @popav4 you can increase the memory size in Docker for the container VM and then you'll be able to load this model.
