### ISSUE TITLE
Ollama on Mac not free up space / what is equivalence of /usr/share/ollama/.ollama/models

### ISSUE THREAD

**Issue by tomaszstachera** [ollama/ollama#5444]
### What is the issue?

I've ran `ollama run llama3:70b` on Mac and CLI pulled 40GB of data that is not stored in ~/.ollama.
`ollama list` shows no models.
Where the heck is the data? How to clean it up?

### OS

macOS

### Ollama version

0.1.48

**Comment by pdevine** [comment]
Any *shared* models on the mac will not get cleaned up unless each of the models using the shared data are removed. The [FAQ](https://github.com/ollama/ollama/blob/main/docs/faq.md#where-are-models-stored) covers where each location for the data is stored, which is in `~/.ollama/models`.

**Comment by tomaszstachera** [comment]
The issue is that I've cleaned up model using `ollama rm` and cleaned up directory `~/.ollama/models` but space is still consumed somewhere.

**Comment by pdevine** [comment]
I'm not able to duplicate this. Here's a copy of command-r-plus which I had locally:

<img width="858" alt="Screenshot 2024-07-03 at 13 10 59" src="https://github.com/ollama/ollama/assets/75239/7cf025ee-3052-4257-a567-6baee57063d1">

You can see w/ `df -h` how much disk space I'm using:

<img width="1015" alt="Screenshot 2024-07-03 at 13 11 30" src="https://github.com/ollama/ollama/assets/75239/a0092924-948e-4297-88bf-9be9f36a1810">

I then used `ollama rm command-r-plus`. Here's the resulting amount of disk space (again w/ `df -h`):
<img width="1004" alt="Screenshot 2024-07-03 at 13 12 26" src="https://github.com/ollama/ollama/assets/75239/97cd101c-66c0-42b6-a321-642e1606d4c0">

**Comment by tomaszstachera** [comment]
It just got cleaned up bu itself. I think we can close without meaningful output.
