### ISSUE TITLE
Gemma2 template wrong

### ISSUE THREAD

**Issue by qinst64** [ollama/ollama#5457]
### What is the issue?

current gemma2 template cannot distinguish system and prompt
```
<start_of_turn>user
{{ if .System }}{{ .System }} {{ end }}{{ .Prompt }}<end_of_turn>
<start_of_turn>model
{{ .Response }}<end_of_turn>
```
url： [https://ollama.com/library/gemma2/blobs/109037bec39c](https://ollama.com/library/gemma2/blobs/109037bec39c)

**Comment by Bearsaerker** [comment]
It's not wrong, gemma wasn't trained with a system prompt. The template is right.

**Comment by qinst64** [comment]
> It's not wrong, gemma wasn't trained with a system prompt. The template is right.
ok...

**Comment by pdevine** [comment]
@qinst64 you can find out more info [here](https://www.promptingguide.ai/models/gemma).
