### ISSUE TITLE
Error: llama runner process has terminated: signal: aborted on Raspberry PI 3

### ISSUE THREAD

**Issue by iBukkoG104** [ollama/ollama#5459]
### What is the issue?

I installed ollama on my Raspberry PI 3 for some testing, but when I tried to run it with `ollama run mistral`, it downloaded it as normal but after that it gave me this error:

>Error: llama runner process has terminated: signal: aborted

### OS

Linux

### GPU

Other

### CPU

Other

### Ollama version

0.1.48

**Comment by igorschlum** [comment]
Hi @iBukkoG104, how much RAM does your Raspberry Pi 3 have?

Mistral takes up approximately 4.1GB of memory. To run Mistral on your 
Raspberry Pi, you should ideally have at least 8GB of RAM available.

For small devices like the Raspberry Pi, there are tiny models such as 
TinyDolphin that might be suitable alternatives.

BTW Ollama should tell you that you don't have enought memory.

**Comment by Moonlight1220** [comment]
@igorschlum The maximum ram amount for the RPI3 is 1gb therefore incompatible with Ollama

**Comment by igorschlum** [comment]
@Moonlight1220 ollama run tinyllama:1.1b-chat-v0.6-q3_K_S needing only 500Kb of RAM. So yes, it's possible to use Ollama on RPI3. There are multiples videos on youtube explaining that. It could be usefull for many usages.

**Comment by Moonlight1220** [comment]
@igorschlum I was un-aware that that tinyllama:1.1b-chat-v0.6-q3_K_S was available, thank you for pointing that out and I will make sure to remember that for future issue's.

**Comment by dhiltgen** [comment]
We've added logic in recent versions to try to catch the scenario where the model wont fit in total VRAM+system memory so it gives a better error message instead of just crashing, but ultimately you'll need to use one of the tiny models to have a working setup on a RPI.

**Comment by epeters3** [comment]
I've seen this same error when trying to run a new model `llama3.2` on an outdated version of `ollama` on my Raspberry PI 5. Upgrading `ollama` solved the problem.
