### ISSUE TITLE
Request: `docker compose` support for Ollama server

### ISSUE THREAD

**Issue by jamesbraza** [ollama/ollama#546]
It would be really nice if Ollama supported `docker compose` for the Ollama server.

This would enable one to run:
- `docker compose up`: start the Ollama server
- `docker compose down`: stop the Ollama server

`docker compose` imo has two benefits:
- A bit easier than having to deal with multiprocessing associated with `./ollama serve`
- Would enable Ollama server to be more OS independent, by outsourcing platform support to Docker

For reference, [LocalAI](https://github.com/go-skynet/LocalAI) supports this, and it works flawlessly, without having to deal with `brew install`s and compilation

Perhaps https://github.com/sickcodes/Docker-OSX can be used as the base image, since Ollama currently just supports macOS-based installations

**Comment by zdeneksvarc** [comment]
Since Docker Compose is a deployment tooling around Linux containers, a stable Linux version of Ollama must be available first.

**Comment by philipempl** [comment]
Ollama maintains a [Dockerfile](https://github.com/jmorganca/ollama/blob/main/Dockerfile) that I modified a bit by adding an entrypoint and a Docker compose file. In my version, I assume that the Dockerfile and the entrypoint.sh file are in the **docker/ollama** subdirectory. I hope this works for you:

**docker-compose.yml:**
```docker-compose.yml

version: '3'
services:
  ollama:
    hostname: ollama
    container_name: ollama
    build:
      context: ./docker/ollama
      dockerfile: Dockerfile
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/app
    networks:
      - net
```

**Dockerfile:**
```Dockerfile
# Stage 1: Build the binary
FROM golang:alpine AS builder

# Install required dependencies
RUN apk add --no-cache git build-base cmake

# Set the working directory within the container
WORKDIR /app

# Clone the source code from the GitHub repository
RUN git clone https://github.com/jmorganca/ollama.git .

# Build the binary with static linking
RUN go generate ./... \
    && go build -ldflags '-linkmode external -extldflags "-static"' -o .

# Stage 2: Create the final image
FROM alpine

ENV OLLAMA_HOST "0.0.0.0"

# Install required runtime dependencies
RUN apk add --no-cache libstdc++ curl

# Copy the custom entry point script into the container
COPY Modelfile /Modelfile

# Copy the custom entry point script into the container
COPY entrypoint.sh /entrypoint.sh

# Make the script executable
RUN chmod +x /entrypoint.sh

# Create a non-root user
ARG USER=ollama
ARG GROUP=ollama
RUN addgroup $GROUP && adduser -D -G $GROUP $USER

# Copy the binary from the builder stage
COPY --from=builder /app/ollama /bin/ollama

USER $USER:$GROUP

ENTRYPOINT ["/entrypoint.sh"]

```

**Entrypoint.sh:**
```shell
#!/bin/sh

./bin/ollama serve &

sleep 5

curl -X POST http://ollama:11434/api/pull -d '{"name": "llama2"}'

sleep 10

tail -f /dev/null
```

**Comment by jamesbraza** [comment]
Oh wow, thanks!  It would be cool if someone would list this image on Docker hub.  Interesting with the multistage build.

It'd be cool if you upstreamed your changes to this repo in a PR because you:
- Have nice code comments (over the currently-present `Dockerfile`, which has none)
- Created the missing `docker-compose.yaml`

**Comment by philipempl** [comment]
I agree, it would be cool to have a image for each model, e.g. ollama:llama27GB.... If I have the time, I will submit a pull request in the '''ollama repo''' and create base images on '''Dockerhub'''.

**Comment by jamesbraza** [comment]
Oh I just meant one general Docker image for the Ollama server, and users could run `docker container exec` to pull 1+ models into the container, or use volume mounting somehow

**Comment by oskarhane** [comment]
> I agree, it would be cool to have a image for each model, e.g. `ollama:llama27GB` .... If I have the time, I will submit a pull request in the `ollama repo` and create base images on `Dockerhub`.

@philipempl 

That would be incredibly useful. I don't see a use case where anyone would want to use an image without a model already present.

**Comment by philipempl** [comment]
> > I agree, it would be cool to have a image for each model, e.g. `ollama:llama27GB` .... If I have the time, I will submit a pull request in the `ollama repo` and create base images on `Dockerhub`.
> 
> 
> 
> @philipempl 
> 
> 
> 
> That would be incredibly useful. I don't see a use case where anyone would want to use an image without a model already present.

The only thing that might limit Docker image creation is the fact that ollama - as far as I know - detects the hardware on the host machine during creation. But let's give it a try....

**Comment by jamesbraza** [comment]
TIL of https://hub.docker.com/u/ollama's existance, so I guess one can just directly configure `docker-compose.yaml` for macOS, no need to worry about `docker build`/`buildx`.

**Comment by eddywashere** [comment]
Might have missed this but for the ollama dockerhub image, what path on the container side should folks mount a volume to persist models that get downloaded? Is anything like a container restart needed to pick up the changes?

**Comment by jamesbraza** [comment]
@eddywashere yeah, here is the [`Dockerfile`](https://github.com/jmorganca/ollama/blob/main/Dockerfile) underlying that Docker Hub image.  You can see the `WORKDIR` there.

> Is anything like a container restart needed to pick up the changes?

You don't need to restart the `ollama serve` process when you download a model, so similarly I don't think a container restart is necessary.

**Comment by jamesbraza** [comment]
Looks like https://github.com/jmorganca/ollama/pull/440 is working on this

**Comment by jamesbraza** [comment]
I don't feel this was resolved, having a Docker image in Docker hub is not a `docker compose` config.  Maybe to be more explicit, the resolution I was hoping for is an Ollama-official Docker compose config:

```bash
git clone git@github.com:jmorganca/ollama.git
cd ollama
# The below starts Ollama server
docker compose up
```

**Comment by technovangelist** [comment]
Ok, thanks for clarifying. I'll go ahead and reopen.

**Comment by JinnaBalu** [comment]
Here is what I am using while running on raspberry Pi or Mac 

```yml
version: '3.8'

services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports: ["11434:11434"]
    volumes:
      - ollama:/root/.ollama
    pull_policy: always
    tty: true
    restart: unless-stopped

  ollama-webui:
    image: ghcr.io/ollama-webui/ollama-webui:main
    container_name: ollama-webui
    ports: ["3000:8080"]
    volumes:
      - ollama-webui:/app/backend/data
    depends_on:
      - ollama
    environment:
      - 'OLLAMA_API_BASE_URL=http://ollama:11434/api'
    restart: unless-stopped

volumes:
  ollama: {}
  ollama-webui: {}
```

**Comment by Geezus42** [comment]
It may bee I just followed the docker instructions at in the Ollama-web readme. I may switch at some point at I do not like the complexity of using build scripts I don't have time to understand. However, it is running well.

[[ollama-webui - Installing Ollama and Ollama Web UI Together
Using Docker Compose - ](https://github.com/ollama-webui/ollama-webui?tab=readme-ov-file#installing-ollama-and-ollama-web-ui-together)

**Comment by jmorganca** [comment]
Hi folks, and thanks for the issue @jamesbraza. Given the different permutations of docker compose files possible with Ollama, we haven't published one yet. This may change in the future however for the time being we're sticking to the abstraction of the container image itself: https://github.com/ollama/ollama/blob/main/docs/docker.md
