### ISSUE TITLE
InternLM2.5 - 7 billion parameter with 1M context length

### ISSUE THREAD

**Issue by Qualzz** [ollama/ollama#5463]
[Link to the collection](https://huggingface.co/collections/internlm/internlm25-66853f32717072d17581bc13)

Introduction
InternLM2.5 has open-sourced a 7 billion parameter base model and a chat model tailored for practical scenarios. The model has the following characteristics:

Outstanding reasoning capability: State-of-the-art performance on Math reasoning, surpassing models like Llama3 and Gemma2-9B.

1M Context window: Nearly perfect at finding needles in the haystack with 1M-long context, with leading performance on long-context tasks like LongBench. Try it with [LMDeploy](https://huggingface.co/internlm/internlm2_5-7b-chat-1m/blob/main/chat/lmdeploy.md) for 1M-context inference.

Stronger tool use: InternLM2.5 supports gathering information from more than 100 web pages, corresponding implementation will be released in [Lagent](https://github.com/InternLM/lagent/tree/main) soon. InternLM2.5 has better tool utilization-related capabilities in instruction following, tool selection and reflection. See [examples](https://huggingface.co/internlm/internlm2_5-7b-chat-1m/blob/main/agent/).

**Comment by jthack** [comment]
1m token length 👀

**Comment by jvmx** [comment]
Seconded, this would be a fantastic addition.

**Comment by Qualzz** [comment]
[Online](https://ollama.com/library/internlm2)
