### ISSUE TITLE
How to setting N GPU usage?

### ISSUE THREAD

**Issue by CaoYunzhou** [ollama/ollama#5477]
### What is the issue?

why use one GPU 
I have four gpu device
![image](https://github.com/ollama/ollama/assets/28099773/775bb006-e7de-48cf-b001-98a49ff66595)

### OS

Linux

### GPU

Nvidia

### CPU

Intel

### Ollama version

0.1.48

**Comment by CaoYunzhou** [comment]
0   N/A  N/A     65952      C   ...unners/cuda_v11/ollama_llama_server      39122MiB
    maybe only use number 0 deviced

**Comment by CaoYunzhou** [comment]
I reslove find in issue
[Unit]
Description=Ollama Service
After=network-online.target

[Service]
ExecStart=/usr/local/bin/ollama serve
#Environment="CUDA_VISIBLE_DEVICES=32a47599-188e-dd99-4336-152ad66edb31,9e751506-fbbf-dc41-2475-60f78c4b87b8,db7c29cf-1f42-bbf7-04a4-c81b7eaa27b5,9bc1c429-31c1-8c38-7075-0de3e1992bd8"
#Environment="CUDA_VISIBLE_DEVICES=GPU-32a47599-188e-dd99-4336-152ad66edb31,GPU-9e751506-fbbf-dc41-2475-60f78c4b87b8,GPU-db7c29cf-1f42-bbf7-04a4-c81b7eaa27b5,GPU-9bc1c429-31c1-8c38-7075-0de3e1992bd8"
Environment="CUDA_VISIBLE_DEVICES=0,1,2,3"
Environment="OLLAMA_MAX_LOADED_MODELS=9"
Environment="OLLAMA_NUM_PARALLEL=100"
Environment="OLLAMA_HOST=0.0.0.0:11434"

User=ollama
Group=ollama
Restart=always
RestartSec=3
Environment="PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin"

[Install]
WantedBy=default.target



#-----------
need this env is working
Environment="CUDA_VISIBLE_DEVICES=0,1,2,3"
Environment="OLLAMA_MAX_LOADED_MODELS=9"
Environment="OLLAMA_NUM_PARALLEL=100"
Environment="OLLAMA_HOST=0.0.0.0:11434"

**Comment by haier-1314** [comment]
I have the same problem, please tell me how to solve it

**Comment by CaoYunzhou** [comment]
> need this env is working
> Environment="CUDA_VISIBLE_DEVICES=0,1,2,3"
> Environment="OLLAMA_MAX_LOADED_MODELS=9"
> Environment="OLLAMA_NUM_PARALLEL=100"
> Environment="OLLAMA_HOST=0.0.0.0:11434"

in your system setting change this ollama env service
need this env is working
Environment="CUDA_VISIBLE_DEVICES=0,1,2,3"
Environment="OLLAMA_MAX_LOADED_MODELS=9"
Environment="OLLAMA_NUM_PARALLEL=100"
Environment="OLLAMA_HOST=0.0.0.0:11434"
