### ISSUE TITLE
Ibm instruct models

### ISSUE THREAD

**Issue by botollama** [ollama/ollama#5478]
This is a open-source model with apache licence which have been developed using community of redhat and ibm.
https://ollama.com/library/granite-code (only base models)
https://huggingface.co/ibm-granite
**https://huggingface.co/ibm-granite/granite-34b-code-instruct-GGUF
https://huggingface.co/ibm-granite/granite-20b-code-instruct-GGUF
https://huggingface.co/ibm-granite/granite-8b-code-instruct-GGUF
https://huggingface.co/ibm-granite/granite-3b-code-instruct-GGUF**

Due to the nature of open-source it will evolve to become .

**Comment by rick-github** [comment]
https://ollama.com/library/granite-code

**Comment by botollama** [comment]
closing it

**Comment by rick-github** [comment]
https://ollama.com/library/granite-code:34b-instruct-q4_K_M
https://ollama.com/library/granite-code:20b-instruct-q4_K_M
https://ollama.com/library/granite-code:8b-instruct-q4_K_M
https://ollama.com/library/granite-code:3b-instruct-q4_K_M

**Comment by botollama** [comment]
> https://ollama.com/library/granite-code:34b-instruct-q4_K_M https://ollama.com/library/granite-code:20b-instruct-q4_K_M https://ollama.com/library/granite-code:8b-instruct-q4_K_M https://ollama.com/library/granite-code:3b-instruct-q4_K_M

thanks
closing this
