### ISSUE TITLE
Error: could not connect to ollama app, is it running? Windows

### ISSUE THREAD

**Issue by ArshSharan** [ollama/ollama#5482]
### What is the issue?

I am facing this error:- 
Error: could not connect to ollama app, is it running?

can someone please help me out?

### OS

Windows

### GPU

Nvidia, Intel

### CPU

Intel

### Ollama version

0.1.48

**Comment by jmorganca** [comment]
Hi @ArshSharan - is Ollama running in the tray bar? You may need to start it first. If you're still seeing this issue let me know and I can reopen 😊 

![image](https://github.com/ollama/ollama/assets/251292/749cbc48-4799-4b7a-8cea-99c1ba32c1ed)

**Comment by ArshSharan** [comment]
Yes, it runs in the tray bar, but it still gives me the same error. When I write the command a few times on the terminal, it opens multiple ollama (icons) in my tray bar.

**Comment by mct-lrh** [comment]
I also encountered this issue, and Ollama was NOT in the tray bar.  Running `ollama start` resolved the issue for me, but Ollama is still not in the tray bar (although it usually is).

My OS is Windows and my computer crashed a few times earlier this week, which I blame on Windows.  
ollama version is 0.3.0
