### ISSUE TITLE
granite code page does not show the 20 and 34 b models

### ISSUE THREAD

**Issue by olumolu** [ollama/ollama#5487]
### What is the issue?

![image](https://github.com/ollama/ollama/assets/162728301/d3143bc8-12a2-46e2-a382-b9f5fbaf441e)
granite code page does not show the 20 and 34 b models we can see there are 4 models but does not have the size mentioned on the website end

### OS

Linux

### GPU

AMD

### CPU

AMD

**Comment by rick-github** [comment]
Which website are you referring to?  The 20b and 34b models are listed on ollama.ai.  Click on `138 Tags` and the 20b and 34b models are third and second, respectively.

**Comment by rick-github** [comment]
Ah, you mean the blue tags under the model description.

**Comment by botollama** [comment]
> Ah, you mean the blue tags under the model description.

Sorry for my bad elaboration but thanks for that you have predicted correctly i am talking about that.

**Comment by igorschlum** [comment]
Ok here the info is missing.![image](https://github.com/ollama/ollama/assets/2884312/08ad12f3-69f9-4e39-b0c2-a470b37d508a)

**Comment by dhiltgen** [comment]
They're present now.
![Screenshot 2024-10-23 at 7 42 09 PM](https://github.com/user-attachments/assets/e4d3e07e-037e-479a-9648-05b78d2fcd45)
