### ISSUE TITLE
why GGML_CUDA_FORCE_MMQ is yes and CUDA_USE_TENSOR_CORES is no

### ISSUE THREAD

**Issue by rabbitpig** [ollama/ollama#5496]
Hi:

I am a newbie and curious about how these configs come out.

![image](https://github.com/ollama/ollama/assets/2839943/699df0ca-4d48-48e8-9fcb-ff081fb1ed12)

Someone can tell me how to chane these.

Thanks.

**Comment by egeres** [comment]
This actually comes from llama.cpp, which is the inference backend used by ollama

**Comment by dhiltgen** [comment]
The compiler flags for llama.cpp are defined in the Ollama build.  With the new Go server, see [llama.go](https://github.com/ollama/ollama/blob/main/llama/llama.go) and the [makefiles](https://github.com/ollama/ollama/tree/main/llama/make) 

Development instructions are here - https://github.com/ollama/ollama/blob/main/docs/development.md#transition-to-go-runner
