### ISSUE TITLE
Ollama OpenAI compatibility fails on GPU?

### ISSUE THREAD

**Issue by rhastie** [ollama/ollama#5498]
### What is the issue?

We have seen instances where when we use the OpenAI API compatibility layer Ollama fails to utilise our NVIDIA GPU. When we re-run the test using the Ollama generate API it does use the GPU.

Is this a configuration consideration or potentially a bug.

### OS

Linux

### GPU

Nvidia

### CPU

Intel

### Ollama version

0.1.48

**Comment by jmorganca** [comment]
This would be a bug - it should use the GPU the same way. May I ask what Nvidia hardware you may be running on? Sorry about this.

**Comment by rhastie** [comment]
Currently we are using a L40 NVIDIA GPU with 48Gb memory. It's part of the ADA generation so pretty new. Spec is here: https://www.nvidia.com/en-gb/data-center/l40/

**Comment by Moonlight1220** [comment]
Considering that your GPU was made with running LLM's in mind it's most likely a bug of some kind, may I ask if you are using OpenWebUI (Formerly known as OllamaWebUI)

**Comment by rhastie** [comment]
Not currently but we can easily do that if you feel it would help. 

Currently we are directly monitoring the GPU metrics and trying the respective APIs directly. At its simplest we are using "curl" to hit the two different API versions in a loop.

**Comment by Moonlight1220** [comment]
Unsure if it will help becouse i have never seen this issue before however its worth a try, are you running Ollama localy or on a server?

**Comment by royjhan** [comment]
@rhastie are you still experiencing this issue?

**Comment by dhiltgen** [comment]
If you're still seeing this, please upgrade to the latest version and if that doesn't clear it up, please share a server log and I'll reopen so we can further investigate.
