### ISSUE TITLE
Error Pull Model Manifest

### ISSUE THREAD

**Issue by Moonlight1220** [ollama/ollama#5499]
### Error Pulling Manifest Repeatedly

Hello Ollama Comunity,

When I first installed Ollama on my early 2015 13in Macbook Air (1.6GHz Dual Core Intel Core i5, 8 GB 1600 MHz DDR3, Intel HD Graphics 600 1536 MB) it worked perfectly fine once i used it again after instilation i got the error:

`Error: pull model manifest: file does not exist`

I looked through the github issues and was told to re-install Ollama and am still getting the same error, please advise on where to go next.

### OS

macOS

### GPU

Intel

### CPU

Intel

### Ollama version

0.1.48

**Comment by jmorganca** [comment]
Hi there which model did you pull? Running `ollama pull llama3` should do it! Let me know if you're still seeing the error.

**Comment by Moonlight1220** [comment]
Hello Again, 

Running this command did not seem to fix the error, please advise on where to go from here

**Comment by Moonlight1220** [comment]
New Issue Oppened 6/724

**Comment by dhiltgen** [comment]
@Moonlight1220 I'm able to pull models on an intel mac with 0.1.48.

Do you see any models with `ollama ls` ?  If you try something like `ollama pull llama3` does that give the same error, or does it work?

When I try to pull an incorrect model name, I see the same error you see
```
> ollama pull bogusmodelname
pulling manifest
Error: pull model manifest: file does not exist
```

Perhaps you have a typo in your model name?

**Comment by Moonlight1220** [comment]
Hello Again, 
I it still seems that I am having this issue I am in the process of trying a different more powerful Mac and seeing if it works.

**Comment by gaiaml** [comment]
I'm getting the same issue with a MacBook Pro 2019.
Ollama pull works, Ollama ls shows llama3.1:latest	91ab477bec9d	4.7 GB

ollama run llama 3.1 command throws: 
pulling manifest 
Error: pull model manifest: file does not exist

**Comment by dhiltgen** [comment]
@Moonlight1220 can you share more information?  What version of Ollama are you using?  What model are you trying to pull?  Most likely it's a typo, so please cut-and-paste the exact pull command you're trying.
