### ISSUE TITLE
`ollama run` returns `Error: open /home/user/.ollama/history: permission denied`

### ISSUE THREAD

**Issue by Nilabb** [ollama/ollama#5515]
### What is the issue?

Not sure what's going on. Toyed around a bit with environment variables to change `OLLAMA_HOST` and `OLLAMA_MODELS` but that's it. This didn't happen before when I first used Ollama, not changing any environment variables. I understand this means the `ollama` user can't access the file, and `sudo -u ollama cat /home/user/.ollama/history` returns the same thing. I've since deleted .ollama and replaced it with an empty directory and both commands return the same thing.
```
ls -lA | grep .ollama
drwxr-xr-x  2 ollama ollama  4096 Jul  6 23:08 .ollama
```
```
ls -l /home
drwx------ 41 myuser  users   4096 Jul  7 09:52 myuser
```
I know that my home directory doesn't give ollama read or write permissions but that shouldn't change anything. Before, when toying around with Ollama trying to move `OLLAMA_MODELS` to my home directory I encountered errors with permissions but (I think) I could still read `.ollama` from my home directory if I used `chown`

Haven't seen another issue with this, so I truly have no idea what's going on. I'm sure it's just because I made a mistake as my own bumbling sysadmin 

### OS

Linux

### GPU

Nvidia

### CPU

Intel

### Ollama version

0.1.48 - ollama-cuda from arch repos

**Comment by dhiltgen** [comment]
Ollama is a client-server architecture.  The OLLAMA_MODELS setting applies to the server, and if unset, defaults to `$HOME/.ollama/models` and if you use our install script, we create an `ollama` user with `HOME=/user/share/ollama` https://github.com/ollama/ollama/blob/main/docs/faq.md#where-are-models-stored

The history file is used by the client, and is always stored in $HOME/.ollama/history, unless you set `OLLAMA_NOHISTORY` to disable history support.  When you run the client, the user running the client needs write access to $HOME/.ollama/history.

**Comment by lizhen1412** [comment]
It's okay to change history directly with chown -R, I've tried it and it's fine.
