### ISSUE TITLE
Ollama-kis new model 

### ISSUE THREAD

**Issue by elearningshow** [ollama/ollama#5518]
How do you get your GUI listed in Community Integrations, Web & Desktop?  https://github.com/elearningshow/ollama-kis

**Comment by mchiang0610** [comment]
Thanks. Possible to do a pull request?

**Comment by elearningshow** [comment]
Thank you for your reply mchiang0610, I have not done this before and not sure of the steps.  Since it is not a change to the content and rather just a link to a new Community Integrations, Web & Desktop.  Not sure what to do?  Chatgpt, suggests the following (Fork the Repository: Start by forking the Ollama repository on GitHub to have your own copy to work with.
Create a Branch: Create a new branch in your forked repository for your changes.
Make Your Changes: Add your integration details to the relevant section of the documentation or README file. Ensure you follow the formatting and contribution guidelines provided by the Ollama repository.
Commit Your Changes: Commit your changes with a clear and descriptive commit message.
Open a Pull Request: Open a pull request (PR) to the main Ollama repository. In the PR description, explain your integration and why it should be included in the Community Integrations section. Reference any relevant documentation or examples that highlight the functionality of your integration.
Review Process: Wait for the maintainers of the Ollama repository to review your PR. They may request changes or provide feedback that you will need to address before the PR is merged.) but these instructions are not working for me.

**Comment by elearningshow** [comment]
I believe this maybe the correct structure for a pull request to be added into the Community Integration, Web & Desktop section - https://github.com/ollama/ollama/pull/5575
