### ISSUE TITLE
Error Pulling Manifest MacOSX 

### ISSUE THREAD

**Issue by Moonlight1220** [ollama/ollama#5528]
###  Issue #5499 Continued
This issue is associate with the issue #5499, please see that issue for more context, after some testing on my Windows 11 Hyper-V machine I can confidently say this bug is exclusive to MacOS, please let me know if you have any ideas on how I can get this up and running again.

### OS

macOS

### GPU

Intel

### CPU

Intel

### Ollama version

0.1.48

**Comment by mchiang0610** [comment]
Thanks @Moonlight1220. Closing this one to continue the conversation in #5499

**Comment by Moonlight1220** [comment]
Thank you!
