### ISSUE TITLE
autogen:   Model llama3 is not found

### ISSUE THREAD

**Issue by jjeejj** [ollama/ollama#5538]
### What is the issue?

Ref doc: https://ollama.com/blog/openai-compatibility

```python
llm_config = {
"model": "llama3",
"api_key": "ollama",
"base_url": "http://localhost:11434/v1",
}
```

[autogen.oai.client: 07-08 11:33:27] {329} WARNING - Model llama3 is not found. 

how to solve it ?

### OS

macOS

### GPU

Apple

### CPU

Apple

### Ollama version

0.1.32

**Comment by rick-github** [comment]
`ollama pull llama3`

**Comment by iamkhajan** [comment]
Same issue , i am behind a corporate proxy . ollama pull llama3 works and i can chat in terminal . However when i use it as an API from either browser, autogen studio or script it doesnt work . Always get this Web Site does not exist (dns_unresolved_hostname) . How can i fix this . I have http_proxy/https_proxy set already . Thanks

**Comment by rick-github** [comment]
Not really enough information to diagnose the issue.

Do you set OLLAMA_HOST when you chat in terminal?  Does autogen/browser/script run on the same machine as the ollama client?  Does the ollama client and ollama server run on the same machine?  Is the proxy configured to forward port 11434? 

If autogen is reporting missing model but you can use it from ollama client, it sounds like you have two servers running.

**Comment by shuaib7860** [comment]
Hi I have this same problem but I can give some more information around my setup. I have an Ollama model hosted on a remote server/machine which I utilise by setting up a port forwarding. But I still get the same error that was shared previously by the original author of the post, see below. 

[autogen.oai.client: 07-23 16:13:02] {315} WARNING - Model llama3:70b is not found. The cost will be 0. In your config_list, add field {"price" : [prompt_price_per_1k, completion_token_price_per_1k]} for customized pricing.

The weird thing is that keeping track of the GPU on the remote machine, which hosts the LLM, using nvtop shows that it is firing off and the LLM is being used even though it says it is not. Very strange.

Any idea on what could be causing this issue @rick-github?

**Comment by rick-github** [comment]
This is a warning message about the cost:

https://github.com/microsoft/autogen/blob/b7bdbe1ecc1c00abd5172f472c6051d0230249bd/autogen/oai/client.py#L330

It has no effect on operations, autogen will use the model, it's just that for accounting purposes, autogen us going to treat it as no cost.

**Comment by shuaib7860** [comment]
Ah thank you @rick-github. For anyone who comes across this warning after, see [this comment](https://github.com/microsoft/autogen/issues/2555#issuecomment-2208623783) for an example of how to suppress this warning.
