### ISSUE TITLE
can't embedding PDF file in Korean

### ISSUE THREAD

**Issue by codeMonkey-shin** [ollama/ollama#5539]
### What is the issue?

I'm trying to use rag by embedding a PDF file in Korean, but the encoding seems to be broken. When saved to vectordb, broken strings are stored.

### OS

Windows

### GPU

Nvidia

### CPU

Intel

### Ollama version

0.1.48

**Comment by mchiang0610** [comment]
@codeMonkey-shin sorry about this. May I ask which embedding model you are using? Is there a sample korean PDF in the public you could share for us to reproduce? 

Thank you!

**Comment by codeMonkey-shin** [comment]
> @codeMonkey-shin sorry about this. May I ask which embedding model you are using? Is there a sample korean PDF in the public you could share for us to reproduce?
> 
> Thank you!

I used the chatfire/bge-m3:q8_0 model.

This model also supports Korean.

[test.pdf](https://github.com/user-attachments/files/16138640/test.pdf)

You can use the short Korean pdf file here.

**Comment by codeMonkey-shin** [comment]
> @codeMonkey-shin sorry about this. May I ask which embedding model you are using? Is there a sample korean PDF in the public you could share for us to reproduce?
> 
> Thank you!
Don't worry about it, it was my mistake. There seems to be an issue with the front-end.
