### ISSUE TITLE
OpenAI v1/completion throws an error when passing list of strings to stop parameter.

### ISSUE THREAD

**Issue by chigkim** [ollama/ollama#5545]
### What is the issue?

The new OpenAI v1/completion, (not chat.completion) throws an error if you pass list of strings to stop parameter.

```python
from openai import OpenAI
client = OpenAI(base_url=base_url, api_key=api_key)
prompt = """User: Hello,
Assistant: Hi, how can I help you?
User: How's it going?
Assistant:"""
model="llama3:text"
stop = ["User:", "Assistant:"] # Triggers an error
stop = "User:" # No error
response = client.completions.create(prompt=prompt, model=model, max_tokens=128, stop=stop)
```

error Error code: 400 - {'error': {'message': "invalid type for 'stop' field: []interface {}", 'type': 'invalid_request_error', 'param': None, 'code': None}}

### OS

macOS

### GPU

Apple

### CPU

Apple

### Ollama version

0.1.49

**Comment by royjhan** [comment]
Thanks for the issue

**Comment by ceykmc** [comment]
I encountered the same problem. How to solve this problem ?
