### ISSUE TITLE
Account removal on ollama.com

### ISSUE THREAD

**Issue by mak448a** [ollama/ollama#5549]
Please add a "remove account" button on the website. Thank you!

**Comment by mchiang0610** [comment]
Hey @mak448a thank you for submitting this. This is definitely something that we will need to build! That being said we are racing to have more functionality built into Ollama.com 

Would it be possible to e-mail us, and we will remove your account? hello@ollama.com 

Sorry about the hassle, and hope we'll make ollama better for you in the future.

**Comment by DarthJahus** [comment]
Up.

**Comment by ghost** [comment]
> Hey [@mak448a](https://github.com/mak448a) thank you for submitting this. This is definitely something that we will need to build! That being said we are racing to have more functionality built into Ollama.com
> 
> Would it be possible to e-mail us, and we will remove your account? [hello@ollama.com](mailto:hello@ollama.com)
> 
> Sorry about the hassle, and hope we'll make ollama better for you in the future.

All lies, is 2025 and the button still don't appear

And no one answer in that email account

**Comment by mak448a** [comment]
At the time of the comment, I asked and my account got deleted. Not sure about what happens today when you request on that email.
