### ISSUE TITLE
If i have both a nvidia and intel arc card will Ollama use both?

### ISSUE THREAD

**Issue by AncientMystic** [ollama/ollama#5558]
I am considering a intel arc card for AV1 encoding and i would like to get more use out of it than just encoding, so if i have both a nvidia card and intel arc in the same system, will Ollama use both cards simultaneously just like any other multi gpu setup or do they have to be the same type because of cuda?

**Comment by mchiang0610** [comment]
@AncientMystic Intel has been a great partner of Ollama, and we are of course working hard to make it run smoothly. That being said, Ollama doesn't support the Arc cards well enough yet. 

As of now, it's really hard to recommend using cards from multiple vendors as driver support is just getting there. 

Thanks!
