### ISSUE TITLE
ollama 0.2.0 version is slower than 0.1.48

### ISSUE THREAD

**Issue by ceykmc** [ollama/ollama#5559]
### What is the issue?

I upgrade ollama from 0.1.48 to 0.2.0 in ubuntu20.04.
With all configures unchanged, using deepseek-coder-v2:16b, RTX4090D
in 0.1.48, inference speed is 0.4s
but in 0.2.0, inference speed is 4s.
I don't know why.

### OS

Linux

### GPU

Nvidia

### CPU

Intel

### Ollama version

0.2.0

**Comment by jmorganca** [comment]
Hi @ceykmc do you happen to have the logs available? `journalctl -fu ollama`

**Comment by ceykmc** [comment]
when use 0.2.0
if set OLLAMA_NUM_PARALLEL=1 which is default value, everything is fine.
when change OLLAMA_NUM_PARALLEL large than 1, e.g. OLLAMA_NUM_PARALLEL=4, the speed is slow, just as first load time.
maybe if OLLAMA_NUM_PARALLEL large than 1, the model will be reloaded every time?

**Comment by binarri** [comment]
I encountered the same problem, just like @ceykmc mentioned.

**Comment by binarri** [comment]
> I encountered the same problem, just like @ceykmc mentioned.

It seems that the model needs to be reloaded every time a request is made.

**Comment by jmorganca** [comment]
Hi folks, this should be fixed in https://github.com/ollama/ollama/releases/tag/v0.2.1 – sorry about the issue. Let me know if you're still seeing slowness in 0.2.1
