### ISSUE TITLE
The application “Ollama” can’t be opened.

### ISSUE THREAD

**Issue by stoneLee81** [ollama/ollama#5569]
### What is the issue?

I downloaded the latest Ollama-darwin.zip file from the official website, extracted it, and dragged it to the Applications directory. When I tried to open Ollama.app, I received an error message ‘The application “Ollama” can’t be opened.’. Additionally, when I run the command 'ollama --version' in the terminal, it says 'ollama: command not found'."

mac os version: ventura 13.4.1
Ollama version, latest from offical website

### OS

macOS

### GPU

Apple

### CPU

Apple

**Comment by icetech233** [comment]
ollama -v

**Comment by igorschlum** [comment]
Hi @stoneLee81 what Mac are you using with What amount of memory and what version of the Operating system?

**Comment by stoneLee81** [comment]
> Hi @stoneLee81 what Mac are you using with What amount of memory and what version of the Operating system?

m1max,ventura 13.4.1,64G ram

**Comment by igorschlum** [comment]
@stoneLee81 Il will try tonight on my m1max studio with 192 gb of Ram. Why didm't you update to MacOS Sonoma 14.5?

**Comment by jmorganca** [comment]
@stoneLee81 does redownloading it help? Sorry you hit this

If you run the app manually in the terminal do you see any errors?

/Applications/Ollama.app/Contents/MacOS/ollama

**Comment by igorschlum** [comment]
@stoneLee81 you can also create a new user on your mac with Admin rights and see if Ollama can run normally. I'm OK to help understand what cause the issue to improve Ollama. It should launch on 13.4.1.
