### ISSUE TITLE
Changing ollama service port will break ollama commandline

### ISSUE THREAD

**Issue by raymond-infinitecode** [ollama/ollama#5574]
### What is the issue?

Step to reproduce:
systemctl edit ollama.service

[Service]
Environment="OLLAMA_HOST=0.0.0.0:8080"

Ctrl + X save, exit nano editor

ollama list
Error: could not connect to ollama app. is it running ?

After changing the port back to 0.0.0.0:11434, it works.

### OS

Linux

### GPU

Other

### CPU

Intel

### Ollama version

0.1.41

**Comment by raymond-infinitecode** [comment]
Expectation, ollama command to connect to the correct port once change the service.

**Comment by pdevine** [comment]
You can just call it with: `OLLAMA_HOST=localhost:8080 ollama list`

**Comment by raymond-infinitecode** [comment]
Thanks !

**Comment by huoyalong** [comment]
> 谢谢！

老哥，请教一下怎么实现自定义端口启动ollama,Linxu中应该怎么配置呀
这一句在哪配置
OLLAMA_HOST=localhost:8080 ollama list

**Comment by raymond-infinitecode** [comment]
vi ~/.bashrc
export OLLAMA_HOST="localhost:8080"

**Comment by huoyalong** [comment]
> vi ~/.bashrc export OLLAMA_HOST="localhost:8080"
> 
> save the file wq
> 
> exit terminal, login again.
> 
> sudo systemctl edit ollama.service ... [Service] ... Environment="OLLAMA_HOST=0.0.0.0:8080" ... ctrl x
> 
> sudo systemctl restart ollama.service
我这两天已经研究明白了哈哈哈， 不过还是灰常感谢 ！！
