### ISSUE TITLE
version 0.2.1  error occurs when calling qwen-agent, but work normally in version 0.1.47 

### ISSUE THREAD

**Issue by bjfk2006** [ollama/ollama#5586]
### What is the issue?

gpu:cuda12.5+V100
model:qwen2:7b-instruct-q8_0
ollama: 0.2.1
code: https://github.com/QwenLM/Qwen-Agent
error info:
Jul 10 10:06:15 VM-77-13-ubuntu ollama[481292]: /go/src/github.com/ollama/ollama/llm/llama.cpp/ggml/src/ggml-cuda/template-instances/../mmq.cuh:2422: ERROR: CUDA kernel mul_mat_q has no device code compatible with CUDA arch 700. ggml-cuda.cu was compiled for: __CUDA_ARCH_LIST__
Jul 10 10:06:15 VM-77-13-ubuntu ollama[481292]: /go/src/github.com/ollama/ollama/llm/llama.cpp/ggml/src/ggml-cuda/template-instances/../mmq.cuh:2422: ERROR: CUDA kernel mul_mat_q has no device code compatible with CUDA arch 700. ggml-cuda.cu was compiled for: __CUDA_ARCH_LIST__
Jul 10 10:06:15 VM-77-13-ubuntu ollama[481292]: /go/src/github.com/ollama/ollama/llm/llama.cpp/ggml/src/ggml-cuda/template-instances/../mmq.cuh:2422: ERROR: CUDA kernel mul_mat_q has no device code compatible with CUDA arch 700. ggml-cuda.cu was compiled for: __CUDA_ARCH_LIST__
Jul 10 10:06:15 VM-77-13-ubuntu ollama[1057]: ggml_cuda_compute_forward: SILU failed
Jul 10 10:06:15 VM-77-13-ubuntu ollama[1057]: CUDA error: unspecified launch failure
Jul 10 10:06:15 VM-77-13-ubuntu ollama[1057]:   current device: 0, in function ggml_cuda_compute_forward at /go/src/github.com/ollama/ollama/llm/llama.cpp/ggml/src/ggml-cuda.cu:2283
Jul 10 10:06:15 VM-77-13-ubuntu ollama[1057]:   err
Jul 10 10:06:15 VM-77-13-ubuntu ollama[1057]: GGML_ASSERT: /go/src/github.com/ollama/ollama/llm/llama.cpp/ggml/src/ggml-cuda.cu:100: !"CUDA error"

### OS

Linux

### GPU

Nvidia

### CPU

Intel

### Ollama version

0.2.1

**Comment by jmorganca** [comment]
Thanks for the issue! Merging wit hhttps://github.com/ollama/ollama/issues/5571

**Comment by JerryKwan** [comment]
Encountered the same issue. 
Is there any compiled version to be used for validation?
