### ISSUE TITLE
Ollama running requests slow, while not utilizing entire VRAM

### ISSUE THREAD

**Issue by txhno** [ollama/ollama#5590]
I am continuously sending "generate" API requests to the Ollama server, querying the model wizardlm2:7b-q6_K. Each iteration takes approximately 3 seconds to respond. The model is using only 8GB of the 16GB VRAM available on my Tesla V100 GPU.

Is there a way to make it utilize the entire VRAM to speed up request processing? If so, how can I achieve this?

**Comment by HeroSong666** [comment]
I had a similar problem. I used four A30 gpus to reason about qwen2-72b's model. But even at peak times, each card was not used more than 35%. At the same time, the speed of reasoning is relatively slow.

**Comment by dhiltgen** [comment]
@txhno that VRAM usage sounds correct for that model.  There isn't a way to make a model use more memory to make it go faster.  I don't have a V100, but on an RTX 2080 Ti which is a similar generation, I see an initial load take ~3 seconds, and subsequent requests to the already loaded model are ~0.5s for a short prompt with a token rate of ~65 tokens per second.

Concurrency and parallelism will allow you to send multiple requests at the same time, which can help on aggregate throughput, but you'll need multiple concurrent client requests.

With concurrency, you can load a second model (we don't support loading the same model twice) but you may bump up against PCI bus throughput, CPU performance limits, etc.


If the performance you're seeing is significantly slower than what I described above, please share more details, and your server log and I'll reopen the issue so we can look into it more.

**Comment by txhno** [comment]
@dhiltgen Can I create a model file of the same model, perhaps increase the context size a bit, and then run concurrency with the modified model?

**Comment by dhiltgen** [comment]
@txhno unfortunately no, parameters do not affect the weight layer(s) in the model, so the uniqueness algorithm will treat them as the same model.
