### ISSUE TITLE
Upgrading removes all models

### ISSUE THREAD

**Issue by loranger** [ollama/ollama#5591]
### What is the issue?

Hi,

I just upgraded my ollama setup manually, by running the install script again, as [specified](https://github.com/ollama/ollama/blob/main/docs/faq.md#how-can-i-upgrade-ollama), but I also lost all my models, the ones pulled, the ones built, all are gone.

I supposed that's not the desired behaviour?

### OS

Linux

### GPU

Nvidia

### CPU

AMD

### Ollama version

0.2.1

**Comment by jmorganca** [comment]
Hi @loranger sorry about that, and sorry for the long reply. The recommended practice here is to create a systemd override file. Sorry this isn't better documented (will fix this momentarily)

```
systemctl edit mysqld.service
```

**Comment by loranger** [comment]
Thanks for the reply

I did create a `/etc/systemd/system/ollama.service.d/override.conf` file and added my customizations

```ini
[Service]
Environment="OLLAMA_HOST=0.0.0.0"
Environment="OLLAMA_MODELS=/home/ollama/models"
```

The latest upgrade worked flawlessly.
Thank you so much 👍🏻
