### ISSUE TITLE
Ollama installation from source code

### ISSUE THREAD

**Issue by dikshax86** [ollama/ollama#5592]
### What is the issue?

So I was required to install Ollama setup exe from the source code in windows 
so I found the steps as 
Note: The Windows build for Ollama is still under development.

First, install required tools:

MSVC toolchain - C/C++ and cmake as minimal requirements

Go version 1.22 or higher

MinGW (pick one variant) with GCC.
MinGW-w64
MSYS2

The ThreadJob Powershell module: Install-Module -Name ThreadJob -Scope CurrentUser
Then, build the ollama binary:

$env:CGO_ENABLED="1"
go generate ./...
go build .

I completed above steps but getting error in CMake 
details of software in my system 
go version 
MinGw software version 13.2.0
cmake version 3.29.0-rc2
visual studio 2022
system is 64bit

error is 

cmake version 3.29.0-rc2

CMake suite maintained and supported by Kitware (kitware.com/cmake).
CMake Error at CMakeLists.txt:2 (project):
  Generator

    NMake Makefiles

  does not support platform specification, but platform

    x64

  was specified.

CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!
llm\generate\generate_windows.go:3: running "powershell": exit status 1
### OS

Windows

### GPU

Other

### CPU

Intel

### Ollama version

0.1.48

**Comment by dhiltgen** [comment]
Our windows developer docs could use a bit of improvement.

Try building from a MSVC Developer Shell.  That should have all the right variables set up to get the build working.

**Comment by dhiltgen** [comment]
To build ollama we need CGO support, which requires gcc in your PATH.  If MSYS2 isn't an option, you'll need to use one of the other port toolkits that can deliver gcc.  (e.g., MinGW, Cygwin, etc.)

**Comment by dhiltgen** [comment]
Windows developer docs are much improved for the new Go server.  https://github.com/ollama/ollama/blob/main/docs/development.md#windows-1

We still recommend MSYS2 to install make/gcc, as we have found that's the most reliable path.  There are other ways to get gcc and make which you can explore at https://www.mingw-w64.org/
