### ISSUE TITLE
codegeex4

### ISSUE THREAD

**Issue by sinxyz** [ollama/ollama#5595]
### What is the issue?

can't use,output:GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG

### OS

Windows

### GPU

Nvidia

### CPU

AMD

**Comment by sinxyz** [comment]
suddenly started working

**Comment by jmorganca** [comment]
Hi there which GPU do you have? Sorry you hit this

**Comment by terlar** [comment]
I currently run into this with llama3.2 (a80c4f17acd5). Also on Windows (WSL) with Nvidia (NVIDIA RTX A2000 8GB Laptop GPU).

I did run into this with llama3.1 before, but eventually after a new release it started working. Other models I have tried work without issues.

**Comment by jmorganca** [comment]
Hi there this should be fixed now. Let me know if you continue to see it.
