### ISSUE TITLE
version is 0.2.1 can't run glm4

### ISSUE THREAD

**Issue by qiulaidongfeng** [ollama/ollama#5596]
### What is the issue?

run `ollama run glm4`

Error: this model is not supported by your version of Ollama. You may need to upgrade

### OS

Windows

### GPU

AMD

### CPU

AMD

### Ollama version

ollama version is 0.2.1

**Comment by qiulaidongfeng** [comment]
reinstall got `Error: llama runner process has terminated: exit status 0xc0000409 error:Could not initialize Tensile library`

use OLLAMA_LLM_LIBRARY=cpu_avx2 run success.

**Comment by jmorganca** [comment]
Hi there, sorry you hit this issue. Which AMD gpu do you have? Thanks!

**Comment by qiulaidongfeng** [comment]
780m



---Original---
From: "Jeffrey ***@***.***&gt;
Date: Wed, Jul 10, 2024 22:30 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [ollama/ollama] version is 0.2.1 can't run glm4 (Issue #5596)




 
Hi there, sorry you hit this issue. Which AMD gpu do you have? Thanks!

**Comment by jmorganca** [comment]
Closing for https://github.com/ollama/ollama/issues/5622
