### ISSUE TITLE
After executing 'qwen2', I interacted with it by posing several queries. Upon exiting the session and attempting to relaunch 'qwen2', I encountered an error

### ISSUE THREAD

**Issue by 20190441309** [ollama/ollama#5597]
After executing 'qwen2', I interacted with it by posing several queries. Upon exiting the session and attempting to relaunch 'qwen2', I encountered an error
![71c4326d8538c2e646820db12aa5a08](https://github.com/ollama/ollama/assets/56188085/ac18292e-1325-46b4-8ff5-63c45c16d9b2)
But the 'history' file does exist, and I am able to see its contents
![f9b98c4bee21bea2bf098c836159418](https://github.com/ollama/ollama/assets/56188085/c2c159d6-5501-48e7-8352-e9f77f85eead)
I'm not sure how to resolve this issue, seeking help from experienced individuals

**Comment by rick-github** [comment]
The error string indicates that your `HOME` environment variable is `/home/bingxing2/home/scx7kzf`.  If you correct that, ollama will be able to access the history file.
