### ISSUE TITLE
/clear - clears the terminal

### ISSUE THREAD

**Issue by dannyoo** [ollama/ollama#5610]
Greetings, I love using ollama. 

How can we make the /clear command clear the terminal as well?

Thanks

**Comment by ramtinkermani** [comment]
For the time being you can use "Command + k" on Mac to clear but would be nice to have that too

**Comment by igorschlum** [comment]
@ramtinkermani command K is working fine, bug when I type ollama run llama3 and after a prompt, I type /clear it's not working as you said.

>>> /clear
Unknown command '/clear'. Type /? for help
>>> /?
Available Commands:
  /set            Set session variables
  /show           Show model information
  /load <model>   Load a session or model
  /save <model>   Save your current session
  /bye            Exit
  /?, /help       Help for a command
  /? shortcuts    Help for keyboard shortcuts

Use """ to begin a multi-line message.

**Comment by ramtinkermani** [comment]
@igorschlum 
Clear was added in version v0.1.38. Make sure you have a newer version installed:
https://github.com/ollama/ollama/releases/tag/v0.1.38

**Comment by igorschlum** [comment]
When I launch Ollama and it detects that there's a new version available, 
the app prompts me to update. However, even when I click on the "Update" 
option in the menu bar, the CLI version doesn't get updated.

Additionally, when I manually reinstall Ollama by downloading the latest 
version from the server, the CLI version still remains outdated (0.1.22), 
despite the GUI version being updated to 0.2.1 and I clicked on Install CLI.

**Comment by ramtinkermani** [comment]
I think when you update thourgh the UI, it only updates the UI not the CLI. Please download the latest version of the CLI and install it. This should update the CLI.
https://ollama.com/

Make sure the new version is added to your environment:
```
> ollama --version
ollama version is 0.2.1
```

(Assuming you're using Mac or Linux) if still you see the old version, make sure the new version is in your path:
```
$ which ollama
/usr/local/bin/ollama
```

**Comment by igorschlum** [comment]
Thank you I updated with

```bash
 brew upgrade ollama
 ```
 But I created an Issue as installing Ollama CLI at first launch on a fresh download ollama.app should update it. If not Ollama should support "ollama update" command, to update both the app and the CLI.
 
 /clear works now.

**Comment by bmamatkadyr** [comment]
> For the time being you can use "Command + k" on Mac to clear but would be nice to have that too. Also /clear is already defined to clear the session context

[sticker.webm](https://github.com/user-attachments/assets/5f9d39a6-14b8-45d6-80ae-368d3715442a)

**Comment by bmamatkadyr** [comment]
> For the time being you can use "Command + k" on Mac to clear but would be nice to have that too. Also /clear is already defined to clear the session context

tu sir 🫡
