### ISSUE TITLE
CLI not updated when Ollama.app is updated

### ISSUE THREAD

**Issue by igorschlum** [ollama/ollama#5619]
### What is the issue?

(base) Igor@Mac ~ % ollama --version
Ollama version is 0.2.1
Warning: client version is 0.1.22

Is it normal, that even after downloading ollama.app, launching it and clicking on "Install CLI", the Ollama CLI version is not updated?

I foound that this command update Ollama CLI.

```bash
brew upgrade ollama
```

As Ollama should stay a simple app to use I think that Ollama should support "Ollama update".

BTW Ollama --help is not  showing /clear and other new commands. -- help 

```bash
Ollama --help
Large language model runner

Usage:
  ollama [flags]
  ollama [command]

Available Commands:
  serve       Start ollama
  create      Create a model from a Modelfile
  show        Show information for a model
  run         Run a model
  pull        Pull a model from a registry
  push        Push a model to a registry
  list        List models
  ps          List running models
  cp          Copy a model
  rm          Remove a model
  help        Help about any command

Flags:
  -h, --help      help for ollama
  -v, --version   Show version information
```

### OS

macOS

### GPU

Apple

### CPU

Apple

### Ollama version

0.2.1

**Comment by thinkverse** [comment]
Seems like you'd installed Ollama via Homebrew before, and then installed it again using the official Mac app. Homebrew is likely taking priority in `PATH` so `ollama` points to the Homebrew installation. Check with `which ollama` if it returns `/opt/homebrew/bin/ollama` then the CLI point to the Homebrew cask. If it's `usr/local/bin/ollama` then it should be the official Mac app.

I'd recommend removing the Homebrew version `brew uninstall ollama` and sticking with the official Mac app.

**Comment by igorschlum** [comment]
Thank you, that was it. I tested installing Ollama with Homebrew a long time ago for an issue on this forum, which is why I ended up with two installations of the CLI.

I'm surprised that Homebrew does not use the same directory as Ollama to install the CLI. This could be confusing for some people.

**Comment by thinkverse** [comment]
One of the reasons Homebrew switched to `opt/homebrew` for Apple Silicon was to reduce potential conflicts with other software, you can read more in the [Discussion: longterm Homebrew prefix on Apple Silicon Macs](https://github.com/Homebrew/brew/issues/9177).
