### ISSUE TITLE
Make full use of all GPU resources for inference

### ISSUE THREAD

**Issue by HeroSong666** [ollama/ollama#5624]
### What is the issue?

I used 4 A30 gpus to reason about qwen2-72b's model.  But even at peak times, each card was not used more than 35%.  At the same time, the speed of reasoning is relatively slow.

### OS

Linux, Docker

### GPU

Nvidia

### CPU

Intel

### Ollama version

0.2.0

**Comment by HeroSong666** [comment]
The model is loaded onto all 4 gpus, but each gpu is not fully used. Below is a screenshot of peak GPU usage:

**Comment by dhiltgen** [comment]
What does `ollama ps` show?  I'm expecting this is 100% loaded across your GPUs, but that will rule out partial CPU load.

My suspicion is there's just a lot of I/O taking place over the PCI bus and that's your bottleneck.  You could try and experiment and set CUDA_VISIBLE_DEVICES to just 2 of the GPUs and force the model into less GPUs.  If that significantly improves performance, we could look at a refinement to the scheduler to attempt to bin-pack on the smallest number of GPUS that will fit.  Today it's 1 or all, no in-between, but your use-case might benefit from that.

**Comment by HeroSong666** [comment]
> What does `ollama ps` show? I'm expecting this is 100% loaded across your GPUs, but that will rule out partial CPU load.
> 
> My suspicion is there's just a lot of I/O taking place over the PCI bus and that's your bottleneck. You could try and experiment and set CUDA_VISIBLE_DEVICES to just 2 of the GPUs and force the model into less GPUs. If that significantly improves performance, we could look at a refinement to the scheduler to attempt to bin-pack on the smallest number of GPUS that will fit. Today it's 1 or all, no in-between, but your use-case might benefit from that.

This is another area where I feel confused. My ollama‘s CLI commands have not been updated since I first used ollama (probably version 0.1.35). I can't use the 'ollama ps' command now:
`
root@fdt-ai-cloud-master03:~# ollama ps
Error: unknown command "ps" for "ollama"

Did you mean this?
        push
        cp
        rm
`

And I set CUDA_VISIBLE_DEVICES=1,2 to run qwen2-72b again, the inference speed becomes slower.
Below is a screenshot of peak GPU usage:
![11](https://github.com/user-attachments/assets/530d331a-3947-4325-8af5-2ebad1f714b1)

**Comment by dhiltgen** [comment]
@HeroSong666 are you running the `ollama` CLI within your Docker containers, or are you running it on your Linux host?  If you are running in a container, make sure to pull the latest image `docker pull ollama/ollama` so you have the latest version.  If you installed Ollama on your host, did you use the install script, or download the stand-alone binary?  If you used the install script (`curl -fsSL https://ollama.com/install.sh | sh`), just re-run the script to get the latest version.  If you manually downloaded the binary from our github releases page and placed it in your path, find where it's located with `which ollama` and replace that with the latest version from https://github.com/ollama/ollama/releases

**Comment by HeroSong666** [comment]
> @HeroSong666 are you running the `ollama` CLI within your Docker containers, or are you running it on your Linux host? If you are running in a container, make sure to pull the latest image `docker pull ollama/ollama` so you have the latest version. If you installed Ollama on your host, did you use the install script, or download the stand-alone binary? If you used the install script (`curl -fsSL https://ollama.com/install.sh | sh`), just re-run the script to get the latest version. If you manually downloaded the binary from our github releases page and placed it in your path, find where it's located with `which ollama` and replace that with the latest version from https://github.com/ollama/ollama/releases

I run the ollama CLI within my Docker containers, and it is the lastest image. But my running environment does not have a network, so I can only download the image in an environment with a network, then move it to my environment and install it. Probably for this reason, ollama did not update the CLI such as ollama ps.

**Comment by dhiltgen** [comment]
@HeroSong666 you can use the [manual installation instructions](https://github.com/ollama/ollama/blob/main/docs/linux.md#manual-install) to download the CLI on another system and copy it over to your target system to ugprade.

**Comment by dhiltgen** [comment]
@HeroSong666 you might also want to explore if the GPU is being throttled for cooling/power constraints. `nvidia-smi -a` may help shed some light.

**Comment by dhiltgen** [comment]
If you're still having trouble, please make sure you've got the latest version installed, and if that doesn't clear it up, please share your server logs and I'll re-open so we can continue investigating what the problem is.
