### ISSUE TITLE
unknown model architecture: 'gemma2'

### ISSUE THREAD

**Issue by mouse33333** [ollama/ollama#5627]
### What is the issue?

I'm trying to run models on my internal Intel GPU.

Here's the software env:
1. activate a virtual env in Anaconda
2. already installed ipex-llm[cpp], ipex-llm[xpu]
3. start the Ollama serve
4. start gemma2 model

Then the log said: unknown model architecture: 'gemma2' 

Here's the sreenshot of the log:

![screenshot-20240711-154648](https://github.com/ollama/ollama/assets/4304174/b7e59f45-c7bc-4e62-86dc-93f1083b8b55)

### OS

Windows, Docker

### GPU

Intel

### CPU

Intel

### Ollama version

0.2.1

**Comment by jmorganca** [comment]
Hi there, thanks for the issue. Are you sure you are on 0.2.1 in the Docker container? Gemma 2 has been supported for the last few releases. Would it be possible to try re-pulling the Docker image `docker pull ollama/ollama`? or checking `ollama -v` from within it? Let me know if that doesn't work

**Comment by mouse33333** [comment]
Appology for my mistake.  I just run Ollama on windows. The client version is 0.2.1

The Gemma2 works fine when running on CPU. However if I use Ollama serve mode and try to run the model on my iGPU (which is INTEL), it went wrong.
