### ISSUE TITLE
llama runner process has terminated

### ISSUE THREAD

**Issue by gsm1258** [ollama/ollama#5628]
### What is the issue?

 ollama run codegeex4:9b-all-q4_K_M
Error: llama runner process has terminated: exit status 0xc0000409 error:failed to create context with model 'C:\Users\ChatAI\.ollama\models\blobs\sha256-916173d92319f80a29db51321f7cb3441f326bac95c421de809e1d08eaaeb693'

### OS

Windows

### GPU

Other

### CPU

Intel

### Ollama version

0.2.1

**Comment by jmorganca** [comment]
Hi there - a fix for this will be in the next release: see #5622

**Comment by ftgreat** [comment]
@gsm1258 麻烦您关注下，谢谢
https://github.com/gsm1258/1383298/issues/1
