### ISSUE TITLE
ollama not use all GPUs

### ISSUE THREAD

**Issue by mavershang** [ollama/ollama#5635]
### What is the issue?

I ran ollama on a server with 4x A100. It only uses 1 of them. Is there some setting need to be changed? Thanks

![image](https://github.com/ollama/ollama/assets/8919917/8a49b4a4-fd85-4715-8ff0-1ea0c1276939)

### OS

Linux

### GPU

Nvidia

### CPU

Intel

### Ollama version

0.2.1

**Comment by Demirrr** [comment]
I have also similar issue. Setting [num_gpu:2](https://github.com/ollama/ollama/blob/main/docs/api.md#generate-request-with-options) doesn't do anything

**Comment by dhiltgen** [comment]
I'll update the FAQ to make this clearer.  In short, the default behavior is to use a single GPU if the model will fit as that typically yields the best performance.
