### ISSUE TITLE
Pass array of messages as an argument

### ISSUE THREAD

**Issue by M3cubo** [ollama/ollama#5640]
In the Docs, it shows that using the API you can pass an array of messages:

"messages": [
    { "role": "user", "content": "why is the sky blue?" }
  ]

My question is, how can I do it with the CLI? It is possible?

I'm looking into something like:

> ollama run "model" "prompt" "messages"

where the argument "messages" could be used to give context.

Do you have any ideas on how to do it?

**Comment by rick-github** [comment]
I don't think you can do this with stock ollama, but it's straightforward for a shell script:

```sh
#!/bin/bash

[ "${#@}" -lt 3 ] && { echo "Usage: $0 model prompt context" ; exit 1 ; }

model=$(echo "$1" | jq -R) ; shift
prompt=$(echo "$1" | jq -R) ; shift
context=$(echo "$1" | jq -R) ; shift
query=$(printf '{"model": %s, "messages":[{"role":"assistant","content":%s},{"role":"user","content":%s}],"stream":false}' "$model" "$context" "$prompt")

curl -s ${OLLAMA_HOST-localhost:11434}/api/chat -d "$query" | jq -r .message.content
```

```
$ ./ollama-context gemma2 'what does an apple cost' 'i see a sign that says "apples: $1.50"'
An apple costs $1.50, according to the sign I see. 🍎
```

**Comment by M3cubo** [comment]
Many thanks for the workaround!
