### ISSUE TITLE
退出后显存仍在占用 - Video memory is still occupied after exiting

### ISSUE THREAD

**Issue by gfkdliucheng** [ollama/ollama#5642]
### What is the issue?

退出后显存仍在占用

### OS

Linux

### GPU

Nvidia

### CPU

Intel

### Ollama version

0.2.2

**Comment by dhiltgen** [comment]
Please share more information about your scenario.  How did you shutdown Ollama?   If you signal the `ollama serve` with a SIGTERM then it will be able to shutdown the child processes and release the GPU memory.  If you use `kill -9` (SIGKILL) then the ollama_llama_server process will be orphaned and hold GPU resource indefinitely.
