### ISSUE TITLE
[Windows 10] Error: llama runner process has terminated: exit status 0xc0000139

### ISSUE THREAD

**Issue by hljhyb** [ollama/ollama#5643]
### What is the issue?

Previously, all models could run very well, but after a recent upgrade, errors are occurring. I have enabled Debug mode. What could be the issue?

[server.log](https://github.com/user-attachments/files/16186027/server.log)
[app.log](https://github.com/user-attachments/files/16186033/app.log)

### OS

Windows

### GPU

Nvidia

### CPU

Intel

### Ollama version

0.2.1

**Comment by jmorganca** [comment]
Hi there, this should be fixed in the upcoming version 0.2.2 - sorry about that! Stay tuned: https://github.com/ollama/ollama/releases

**Comment by hljhyb** [comment]
> Hi there, this should be fixed in the upcoming version 0.2.2 - sorry about that! Stay tuned: https://github.com/ollama/ollama/releases

Well, I tried 0.2.2, but the issue still persists.
