### ISSUE TITLE
 HELP I am trying to configure remote ollama api in Brave Browser Nightly, but Brave setting only allow https access but ollama api in remote server is in http://localhost:11434/v1/chat/completions. how can i configure with https for ollama api?

### ISSUE THREAD

**Issue by buts101** [ollama/ollama#5644]
should i use nginx reverse proxy for redirection? looking for easy method in built in ollama

**Comment by rick-github** [comment]
ollama doesn't support SSL, using a reverse proxy is the easiest long term solution.

For a short term solution, if you can `ssh` to the remote server, you can forward port 11434 from your local machine to the remote machine:

```
ssh -L 11434:127.0.0.1:11434 my.remote.server
```

**Comment by lotusorrose** [comment]
reverse proxy probably is the way to go
