### ISSUE TITLE
My Ollama stopped working to transcribe videos.

### ISSUE THREAD

**Issue by TioJota** [ollama/ollama#5649]
### What is the issue?

I updated to llama3, I use the SubtitleEdit program to transcribe other languages, the program translates correctly, but when I want to transcribe from English to Spanish it tells me the following message:

**"Ollama (local LLM)" requires a web server running locally!
{"error":"CreateFile C:\\Users\\jgcar\\.ollama\\models\\blobs\\sha256-00e1317cbf74d901080d7100f57580ba8dd8de57203072dc6f668324ba545f29: The system cannot find the file specified."}

Read more?**

I don't know absolutely anything about programming language, I'm just a video editor, if you could help me how I can solve it I would appreciate it.
![Captura de pantalla 2024-07-12 035221](https://github.com/user-attachments/assets/b1fa6d8e-79a6-43d2-87d5-dd2a321ded6d)

### OS

Windows

### GPU

Nvidia

### CPU

Intel

### Ollama version

llama3

**Comment by TioJota** [comment]
HI @jmorganca I just sent you an Email, check your inbox

**Comment by TioJota** [comment]
@jmorganca hey!!!

**Comment by jmorganca** [comment]
Hi @TioJota thanks for the issue! Sorry for the delay. Make sure Ollama's running – you should be able to see it in the system tray in the bottom right:

![image](https://github.com/user-attachments/assets/38e73316-1cac-458c-adea-a908dabae5c9)

Let me know if you're still having issues
