### ISSUE TITLE
API Responses missing fields

### ISSUE THREAD

**Issue by stavsap** [ollama/ollama#5671]
### What is the issue?

it seems that in this version the response from api calls changed.

no more `context` field nor `load_duration`

please advise.

### OS

Windows

### GPU

Nvidia

### CPU

AMD

### Ollama version

0.2.3

**Comment by slouffka** [comment]
Confirming that /api/generate response is broken. Multiple properties are missing in /api/generate response in latest Ollama release.

https://github.com/ollama/ollama/commit/269ed6e6a2cea822ab137d40d5c70c8bf09470f8#diff-829f94fd58de777429c6c25e68de745804cb600031e92995007fa08d7af32078L236

Here's the diff that introduced a bug. Starting on line 236.

**Comment by slouffka** [comment]
Meanwhile I've downgraded to 0.2.1 which does not have these changes. It works for me.

**Comment by doggi87** [comment]
I have same issues with 0.2.2 and 0.2.3 and works perfectly fine in 0.2.1

**Comment by jmorganca** [comment]
Hi folks, I'm sorry about this – 0.2.4 was released earlier today which fixes this https://github.com/ollama/ollama/releases/tag/v0.2.4
