### ISSUE TITLE
Ollama spins up USB HDD 

### ISSUE THREAD

**Issue by bkev** [ollama/ollama#5673]
### What is the issue?

When ever I run an Ollama model, Ollama now spins up my external USB hard drive despite not needing to as all the models are on the internal drive. 

I can't say I've always noticed it doing this, although it has always spun up the hard drive when upgrading as it seems to scan USB?

Is there anyway to stop Ollama doing this by disabling any kind of USB scan functionality etc?

This is on a raspberry pi with internal nvme (where the models are) and an external USB that Ollama didn't need. 

### OS

Linux

### Ollama version

0.2.3

**Comment by rick-github** [comment]
ollama doesn't explicitly do a USB scan on startup, but it does check various places on the filesystem looking for libraries, config files, etc.  If your external drive is mounted and one of the places that ollama check references a location on the USB filesystem, that will cause the drive to spin up.

You can check where ollama is looking by tracing its syscall activities:

```
strace -f -e openat,newfstatat,readlinkat -o /tmp/ollama.strace ollama serve
```

For example, on my pi ollama checks `/opt/cuda`, so if I had a USB drive mounted on `/opt`, that would cause the drive to activate.
