### ISSUE TITLE
Extremely slow on Mac M1 chip

### ISSUE THREAD

**Issue by lulunac27a** [ollama/ollama#5680]
### What is the issue?

I tried chatting using Llama from Meta AI, when the answer is generating, my computer is so slow and sometimes freezes (like my mouse not moving when I move the trackpad). It takes few minutes to completely generate an answer from a question. I use Apple M1 chip with 8GB of RAM memory.

### OS

macOS

### GPU

Apple

### CPU

Apple

### Ollama version

0.2.2

**Comment by rick-github** [comment]
What was the size of the model?  Most models are multi-gigabytes in size, if you tried to run one of these with 8G of RAM then I imagine that it will cause a lot of swap activity.   Try running a smaller model (eg, https://ollama.com/library/qwen2:0.5b) and see if performance improves.

**Comment by lulunac27a** [comment]
llama3 with 8B size

**Comment by sudochia** [comment]
Try https://ollama.com/library/tinyllama and see how it goes?

**Comment by igorschlum** [comment]
@lulunac27a you will need a 16GB mac, but to learn Tinyllama is good. You can also use llama3:8b-instruct-q2_K and restart your Mac before and use few apps to let max amount of memory to Ollama and the model.

**Comment by dhiltgen** [comment]
As others have pointed out, llama3 is going to be large for your system if you have anything else using memory.
```
> ollama ps
NAME         	ID          	SIZE  	PROCESSOR	UNTIL
llama3:latest	a6990ed6be41	5.5 GB	100% GPU 	4 minutes from now
```

On an 8G Mac, only ~5.7GB is available for VRAM usage, not leaving much buffer, so while it does work, it is pushing the limits of your system.

**Comment by piotrszczesniak** [comment]
> Try https://ollama.com/library/tinyllama and see how it goes?

@sudochia - this model is way quicker to respond, thanks!

**Comment by igorschlum** [comment]
Hi @piotrszczesniak, you can try pulling [llama3.2](https://ollama.com/library/llama3.2) which is a smaller LLM and may respond better than tinyllama.
