### ISSUE TITLE
System wide old version of cuda v11 used instead of bundled version - runner fails to start due to missing symbols

### ISSUE THREAD

**Issue by hljhyb** [ollama/ollama#5689]
### What is the issue?

Previously, all models could run very well, but after a recent upgrade, errors are occurring. I have enabled Debug mode. What could be the issue?
[GIN] 2024/07/14 - 16:05:11 | 200 |            0s |       127.0.0.1 | HEAD     "/"
[GIN] 2024/07/14 - 16:05:20 | 200 |        69.6µs |       127.0.0.1 | HEAD     "/"
[GIN] 2024/07/14 - 16:05:20 | 200 |     23.4842ms |       127.0.0.1 | POST     "/api/show"
time=2024-07-14T16:05:21.026+08:00 level=INFO source=sched.go:701 msg="new model will fit in available VRAM in single GPU, loading" model=C:\Users\X170\.ollama\models\blobs\sha256-6a0746a1ec1aef3e7ec53868f220ff6e389f6f8ef87a01d77c96807de94ca2aa gpu=GPU-06932cd6-8249-ad0c-67b5-f2bcc68be311 parallel=4 available=14287372288 required="6.2 GiB"
time=2024-07-14T16:05:21.026+08:00 level=INFO source=memory.go:309 msg="offload to cuda" layers.requested=-1 layers.model=33 layers.offload=33 layers.split="" memory.available="[13.3 GiB]" memory.required.full="6.2 GiB" memory.required.partial="6.2 GiB" memory.required.kv="1.0 GiB" memory.required.allocations="[6.2 GiB]" memory.weights.total="4.7 GiB" memory.weights.repeating="4.3 GiB" memory.weights.nonrepeating="411.0 MiB" memory.graph.full="560.0 MiB" memory.graph.partial="677.5 MiB"
time=2024-07-14T16:05:21.046+08:00 level=INFO source=server.go:383 msg="starting llama server" cmd="C:\\Users\\X170\\AppData\\Local\\Programs\\Ollama\\ollama_runners\\cuda_v11.3\\ollama_llama_server.exe --model C:\\Users\\X170\\.ollama\\models\\blobs\\sha256-6a0746a1ec1aef3e7ec53868f220ff6e389f6f8ef87a01d77c96807de94ca2aa --ctx-size 8192 --batch-size 512 --embedding --log-disable --n-gpu-layers 33 --no-mmap --parallel 4 --port 14534"
time=2024-07-14T16:05:21.050+08:00 level=INFO source=sched.go:437 msg="loaded runners" count=1
time=2024-07-14T16:05:21.050+08:00 level=INFO source=server.go:571 msg="waiting for llama runner to start responding"
time=2024-07-14T16:05:21.051+08:00 level=INFO source=server.go:612 msg="waiting for server to become available" status="llm server error"
time=2024-07-14T16:05:21.314+08:00 level=ERROR source=sched.go:443 msg="error loading llama server" error="llama runner process has terminated: exit status 0xc0000139 "
[GIN] 2024/07/14 - 16:05:21 | 500 |    354.9161ms |       127.0.0.1 | POST     "/api/chat"

[server.log](https://github.com/user-attachments/files/16216040/server.log)
[app.log](https://github.com/user-attachments/files/16216041/app.log)

### OS

Windows

### GPU

Intel

### CPU

Intel

### Ollama version

0.2.5

**Comment by AFellowSpeedrunner** [comment]
Have you tried reinstalling? This has fixed this issue for me. I'm assuming this is an issue with upgrading and installing manually seems to fix it.

You don't need to uninstall, you just download the latest Windows release and close Ollama and just let it overwrite. (This will not change Ollama environment tables or erase models, just the core of Ollama.)

**Comment by hljhyb** [comment]
> Have you tried reinstalling? This has fixed this issue for me. I'm assuming this is an issue with upgrading and installing manually seems to fix it.
> 
> You don't need to uninstall, you just download the latest Windows release and close Ollama and just let it overwrite. (This will not change Ollama environment tables or erase models, just the core of Ollama.)

I have reinstalled several times and upgraded from 0.2.1 to 0.2.4 to 0.2.5.  The same problem occurs every time

**Comment by AFellowSpeedrunner** [comment]
> I have reinstalled several times and upgraded from 0.2.1 to 0.2.4 to 0.2.5. The same problem occurs every time

Have you updated your graphics drivers recently? It may of been an issue with that. If not, try using a version pre-0.2.x. If any Windows Updates were installed recently prior to this issue occurring, try removing them in case they caused something to go wrong.

**Comment by jmorganca** [comment]
Hi @hljhyb sorry this happened – will get this fixed.

Would it be possible for you to open the following folder:

```
explorer.exe C:\Users\X170\AppData\Local\Programs\Ollama\ollama_runners\cuda_v11.3
```

Then double click on `ollama_llama_server.exe`? If there's an error, can you let me know it says? It might say there's a missing DLL.

**Comment by hljhyb** [comment]
> Hi @hljhyb sorry this happened – will get this fixed.嗨，对不起，这发生了 - 将解决这个问题。
> 
> Would it be possible for you to run in powershell:您是否可以在 powershell 中运行：
> 
> ```
> $env:PATH="C:\Users\jmorgan\AppData\Local\Programs\Ollama\cuda;" +$env:PATH
> explorer.exe C:\Users\X170\AppData\Local\Programs\Ollama\ollama_runners\cuda_v11.3\ollama_llama_server.exe
> ```
> 
> and let me know what error shows并让我知道显示什么错误

INFO [wmain] build info | build=3337 commit="a8db2a9c" tid="335452" timestamp=1721003942
INFO [wmain] system info | n_threads=10 n_threads_batch=-1 system_info="AVX = 1 | AVX_VNNI = 0 | AVX2 = 0 | AVX512 = 0 | AVX512_VBMI = 0 | AVX512_VNNI = 0 | AVX512_BF16 = 0 | FMA = 0 | NEON = 0 | SVE = 0 | ARM_FMA = 0 | F16C = 0 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 1 | SSE3 = 1 | SSSE3 = 1 | VSX = 0 | MATMUL_INT8 = 0 | LLAMAFILE = 0 | " tid="335452" timestamp=1721003942 total_threads=20
INFO [wmain] HTTP server listening | hostname="127.0.0.1" n_threads_http="19" port="8080" tid="335452" timestamp=1721003942
llama_model_load: error loading model: llama_model_loader: failed to load model from

llama_load_model_from_file: exception loading model

**Comment by dhiltgen** [comment]
@hljhyb the attached logs don't seem to have debug enabled.  Can you try updating to [v0.2.8](https://github.com/ollama/ollama/releases/tag/v0.2.8) and if that doesn't clear it up, try the following so we can try to see why it's not able to start up correctly.  Quit the tray app, then run the following which will restart it with debugging enabled.
```powershell
$env:OLLAMA_DEBUG="1"
& "ollama app"
```

Then try to load a model, and assuming it fails, share the server.log.

**Comment by hljhyb** [comment]
@dhiltgen 
I did it as you said, but it still doesn't work.
[server.log](https://github.com/user-attachments/files/16357034/server.log)

**Comment by hljhyb** [comment]
I ran "sfc /scannow" and "dism /online /cleanup-image /restorehealth," and changed the CUDA version to 11.5.
But it's still the same problem. Maybe there's an issue with my operating system.
Still, thank you for your help.

**Comment by AFellowSpeedrunner** [comment]
> I ran "sfc /scannow" and "dism /online /cleanup-image /restorehealth," and changed the CUDA version to 11.5. But it's still the same problem. Maybe there's an issue with my operating system. Still, thank you for your help.

Ah, no problem. It may be an OS issue but I'm not sure now. Can you try the latest 0.3 update to Ollama and see if that works? If not, a Windows Update assisted OS reinstallation may be needed but that's only when we exhaust all options.

If you are sure about reinstalling, you can do it by heading to "Recovery" in Settings and clicking "Reinstall now" at the "Fix problems using Windows Update" option. 

This will keep all data, settings and apps but I still recommend backing up important data for an edge case where something doesn't get kept. This also requires some patience as this could take an hour or two.

I know that the reinstall idea sounds like bad advice but it's the safest way to fix this when all options have been tried with failure as a result.

**Comment by hljhyb** [comment]
> > I ran "sfc /scannow" and "dism /online /cleanup-image /restorehealth," and changed the CUDA version to 11.5. But it's still the same problem. Maybe there's an issue with my operating system. Still, thank you for your help.
> 
> Ah, no problem. It may be an OS issue but I'm not sure now. Can you try the latest 0.3 update to Ollama and see if that works? If not, a Windows Update assisted OS reinstallation may be needed but that's only when we exhaust all options.
> 
> If you are sure about reinstalling, you can do it by heading to "Recovery" in Settings and clicking "Reinstall now" at the "Fix problems using Windows Update" option.
> 
> This will keep all data, settings and apps but I still recommend backing up important data for an edge case where something doesn't get kept. This also requires some patience as this could take an hour or two.
> 
> I know that the reinstall idea sounds like bad advice but it's the safest way to fix this when all options have been tried with failure as a result.

I did it , but it still doesn't work. I tried using  "Recovery" in Settings  as you said, but after reinstall, I still got the same error message.

**Comment by dhiltgen** [comment]
@hljhyb we might get a little more insight if you try to run the subprocess directly. Try the following:

```powershell
$env:PATH="C:\Users\X170\AppData\Local\Programs\Ollama\cuda;C:\Users\X170\AppData\Local\Programs\Ollama\ollama_runners\cuda_v11.3;C:\Users\X170\AppData\Local\Programs\Ollama\ollama_runners;$env:PATH"
C:\Users\X170\AppData\Local\Programs\Ollama\ollama_runners\cuda_v11.3\ollama_llama_server.exe --help
```

The most likely explanation for this status code is a missing or incorrect DLL, and starting it manually should hopefully cause an error dialog to pop up showing what DLL(s) are the problem.

**Comment by hljhyb** [comment]
> @hljhyb we might get a little more insight if you try to run the subprocess directly. Try the following:
> 
> ```powershell
> $env:PATH="C:\Users\X170\AppData\Local\Programs\Ollama\cuda;C:\Users\X170\AppData\Local\Programs\Ollama\ollama_runners\cuda_v11.3;C:\Users\X170\AppData\Local\Programs\Ollama\ollama_runners;$env:PATH"
> C:\Users\X170\AppData\Local\Programs\Ollama\ollama_runners\cuda_v11.3\ollama_llama_server.exe --help
> ```
> 
> The most likely explanation for this status code is a missing or incorrect DLL, and starting it manually should hopefully cause an error dialog to pop up showing what DLL(s) are the problem.

I may not have understood your method clearly. I did not receive any prompts after running these commands.
![11222](https://github.com/user-attachments/assets/e6a75066-9ca3-4861-a0c1-46e1ff101390)

**Comment by AFellowSpeedrunner** [comment]
> > > I ran "sfc /scannow" and "dism /online /cleanup-image /restorehealth," and changed the CUDA version to 11.5. But it's still the same problem. Maybe there's an issue with my operating system. Still, thank you for your help.
> > 
> > 
> > Ah, no problem. It may be an OS issue but I'm not sure now. Can you try the latest 0.3 update to Ollama and see if that works? If not, a Windows Update assisted OS reinstallation may be needed but that's only when we exhaust all options.
> > If you are sure about reinstalling, you can do it by heading to "Recovery" in Settings and clicking "Reinstall now" at the "Fix problems using Windows Update" option.
> > This will keep all data, settings and apps but I still recommend backing up important data for an edge case where something doesn't get kept. This also requires some patience as this could take an hour or two.
> > I know that the reinstall idea sounds like bad advice but it's the safest way to fix this when all options have been tried with failure as a result.
> 
> I did it , but it still doesn't work. I tried using "Recovery" in Settings as you said, but after reinstall, I still got the same error message.

I'm completely at a loss now, I don't exactly know what's happened at this point. Sorry for not being able to help. I hope your issue gets fixed sooner rather than later.

Dropping out here. Good luck to you.

**Comment by dhiltgen** [comment]
@hljhyb sorry about that.  It looks like powershell hides the error dialog I was hoping would pop up.  We need to use a `cmd` terminal for this experiment.

```cmd
set PATH=C:\Users\X170\AppData\Local\Programs\Ollama\cuda;C:\Users\X170\AppData\Local\Programs\Ollama\ollama_runners\cuda_v11.3;C:\Users\X170\AppData\Local\Programs\Ollama\ollama_runners;%PATH%
C:\Users\X170\AppData\Local\Programs\Ollama\ollama_runners\cuda_v11.3\ollama_llama_server.exe --help
```

You should get a dialog that pops up that looks something like this (most likely a different dll will be listed)

<img width="490" alt="Screenshot 2024-07-30 at 8 57 41 AM" src="https://github.com/user-attachments/assets/577bc7c6-a6bf-438d-8e9f-83fb779d9c99">

**Comment by hljhyb** [comment]
@dhiltgen 
> @hljhyb sorry about that. It looks like powershell hides the error dialog I was hoping would pop up. We need to use a `cmd` terminal for this experiment.
> 
> ```batchfile
> set PATH=C:\Users\X170\AppData\Local\Programs\Ollama\cuda;C:\Users\X170\AppData\Local\Programs\Ollama\ollama_runners\cuda_v11.3;C:\Users\X170\AppData\Local\Programs\Ollama\ollama_runners;%PATH%
> C:\Users\X170\AppData\Local\Programs\Ollama\ollama_runners\cuda_v11.3\ollama_llama_server.exe --help
> ```
> 
> You should get a dialog that pops up that looks something like this (most likely a different dll will be listed)
> 
> <img alt="Screenshot 2024-07-30 at 8 57 41 AM" width="490" src="https://private-user-images.githubusercontent.com/4033016/353530707-577bc7c6-a6bf-438d-8e9f-83fb779d9c99.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIzOTU3NjUsIm5iZiI6MTcyMjM5NTQ2NSwicGF0aCI6Ii80MDMzMDE2LzM1MzUzMDcwNy01NzdiYzdjNi1hNmJmLTQzOGQtOGU5Zi04M2ZiNzc5ZDljOTkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDczMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MzFUMDMxMTA1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NmQzN2EzMWNmZTg2ZGM2MDMwYWZjYzZhNGQ0ZjE5ZTcwMjY1ZTQ3MmQ5ODY5MDkwOTFkMGI3ZDM4MzdmMWVkYSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.65wHlhbJMcVSmU7fkCnyyB974Lkwnn5EsoDSGZG3rn8">
It shows a dialog like this.
The procedure entry point cublasLtGetStatusString could notbe located in the dynamic link library C:\WINDOWS\SYSTEM32\cublas64_11.dll 
![image](https://github.com/user-attachments/assets/4ef7d529-3e43-4897-9d2b-4a1342334f90)

**Comment by dhiltgen** [comment]
It should have picked up `C:\Users\X170\AppData\Local\Programs\Ollama\cuda\cublas64_11.dll` instead of the one in `C:\Windows\System32` given the PATH we set above, so that makes me think somehow `C:\Users\X170\AppData\Local\Programs\Ollama\cuda\` is missing the libraries.  Can you share what is reported with
```
dir C:\Users\X170\AppData\Local\Programs\Ollama\cuda\
```

**Comment by hljhyb** [comment]
![112177632](https://github.com/user-attachments/assets/2b443d65-1dee-4a63-a813-d81c3e9775ad)

**Comment by dhiltgen** [comment]
Thanks for that information.  So our bundled DLL exists, but even though we specify our directory first in the PATH, windows is defaulting to the system installed version of CUDA v11, and your install is most likely older than 11.3.1.  Until we can figure out how to fix the search order to force our copy, you can workaround this by upgrading cuda v11 to 11.3.1 or newer, or uninstall cuda v11 if you don't have other applications that need that version.

**Comment by hljhyb** [comment]
> Thanks for that information. So our bundled DLL exists, but even though we specify our directory first in the PATH, windows is defaulting to the system installed version of CUDA v11, and your install is most likely older than 11.3.1. Until we ~can figure out how to~ fix the search order to force our copy, you can workaround this by upgrading cuda v11 to 11.3.1 or newer, or uninstall cuda v11 if you don't have other applications that need that version.
> 
> **Update:** looks like we'll need to inject a side by side assembly into our subprocesse executables so they add a probing privatePath to search for our packaged dependencies before the system directories are searched to prevent an incompatible v11 library from accidentally getting loaded.

I've already uninstalled CUDA, but now a pop-up appears when I try to run the model, and it still doesn't work.
![Snipaste_2024-08-12_11-26-55](https://github.com/user-attachments/assets/125ccb5b-a9e2-4683-8cdf-a0bb07c6d5b9)

**Comment by dhiltgen** [comment]
I wouldn't expect that dll to exist if cuda v11 has been uninstalled.  Maybe some other piece of software installed it as a dependency in the system location?   

Until we get the issue fixed, you should be able to workaround this by installing cuda v11.3.1.

**Comment by hljhyb** [comment]
> I wouldn't expect that dll to exist if cuda v11 has been uninstalled. Maybe some other piece of software installed it as a dependency in the system location?
> 
> Until we get the issue fixed, you should be able to workaround this by installing cuda v11.3.1.

Thank you so much! You helped me solve this problem. It seems that a previous version of CUDA copied the cublas64_11.dll version 11.10.1 file into the system directory. The earlier version of Ollama could run, but after updating, it stopped working. The CUDA version installed later didn't update this file, so every time it was called, it used the old version. I just replaced the file, and now it's working!
