### ISSUE TITLE
API that breaks model output

### ISSUE THREAD

**Issue by wltime** [ollama/ollama#5694]
Sometimes when there is a lot of output, and I don't need the model to continue to output. Is there an API to interrupt the output of the model?

**Comment by jmorganca** [comment]
Hi @wltime you can interrupt the request it by cancelling the http connection or by setting `num_predict` in the options to set an upper limit

**Comment by wltime** [comment]
I am using ollama to deploy a dialogue application and the output of ollama is blocking, I am not able to interrupt the current output to continue a new dialogue

**Comment by wltime** [comment]
> Hi @wltime you can interrupt the request it by cancelling the http connection or by setting `num_predict` in the options to set an upper limit
I am using ollama to deploy a dialogue application and the output of ollama is blocking, I am not able to interrupt the current output to continue a new dialogue
