### ISSUE TITLE
The model cannot be loaded into the gpu

### ISSUE THREAD

**Issue by IanNOV13** [ollama/ollama#5696]
### What is the issue?

After updating to version 0.2.5, the gemma2:9b model cannot be loaded into the GPU.
After I downgraded the version back to 0.2.4, the model was successfully loaded into the GPU.

### OS

Windows

### GPU

Nvidia

### CPU

Intel

### Ollama version

0.2.5

**Comment by jmorganca** [comment]
Hi there, try re-pulling the model: `ollama pull gemma2:9b`

May I ask what `ollama ps` shows for you with `gemma2:9b` loaded? Sorry you hit this issue

**Comment by IanNOV13** [comment]
I reinstalled Ollama and it worked.
