### ISSUE TITLE
GPU isn't detected in Docker WSL2 in Win11 

### ISSUE THREAD

**Issue by pawpaw2022** [ollama/ollama#5718]
### What is the issue?

I followed the instruction on ollama dockerhub to set up my Nvidia-Toolkit 
but the container still didn't recognize the GPU on my computer. 
Here is the error log 
![1](https://github.com/user-attachments/assets/2fd2403a-5da9-4583-9b2e-c5fa7b27c8b2)

I am sure that I have CUDA and NVCC installed on my WSL2 
Here is my version
![2](https://github.com/user-attachments/assets/0441bf3c-9df0-49e4-95eb-54f15ac5e77f)

My environmental variable in ollama also seems to be normal 
![3](https://github.com/user-attachments/assets/e756b38b-081f-4787-b126-cbc68ff280a6)

Btw, the windows version of Ollama works fine, only the WSL docker doesn't work. 
I don't know why the Docker doesn't recognize my GPU. 
Please advise.  

### OS

Windows, Docker, WSL2

### GPU

Nvidia

### CPU

Intel

### Ollama version

latest

**Comment by dhiltgen** [comment]
The error 500 is one I haven't seen before
```
     /**
     * This indicates that a named symbol was not found. Examples of symbols
     * are global/constant variable names, driver function names, texture names,
     * and surface names.
     */
    CUDA_ERROR_NOT_FOUND                      = 500,
```

My suspicion is the nvidia tools in WSL2 are not set up correctly or completely.   Double check the instructions from nvidia here https://docs.nvidia.com/cuda/wsl-user-guide/index.html#nvidia-compute-software-support-on-wsl-2 to see if there's anything you missed.

**Comment by dhiltgen** [comment]
Also make sure to follow these instructions - https://docs.docker.com/desktop/gpu/

If their validation step works, but ollama still doesn't work, please run the ollama container with `-e OLLAMA_DEBUG=1` and share the logs and I'll reopen the issue.
