### ISSUE TITLE
Is ollama since 0.2.1 slower on CPU's

### ISSUE THREAD

**Issue by mklue** [ollama/ollama#5723]
### What is the issue?

Love the project, recently I updated from 0.2.1 to 0.2.2 and found the server's responses slower. I upgraded to 0.2.5 and I think it has not improved. Is it load times on the initial run ?
I have a 36 core xeon processor, 64 GB ram and an older radeon GPU, So all the work s going on the the CPU's. Before in 0.2.1 it responded quickly but now the response delay is noticiable. 

### OS

Linux

### GPU

AMD

### CPU

Intel

### Ollama version

0.2.5

**Comment by rick-github** [comment]
What model are you using?

**Comment by dbustosrc** [comment]
#5554

**Comment by dhiltgen** [comment]
Please share your server log so we can see what's going on.
