### ISSUE TITLE
Prompt Tokens for Image Chat

### ISSUE THREAD

**Issue by royjhan** [ollama/ollama#5728]
### What is the issue?

<img width="793" alt="Screenshot 2024-07-16 at 1 22 43 PM" src="https://github.com/user-attachments/assets/4d743995-26b6-463d-8848-38cc9623dfe3">

Image Chat returns 1 for prompt tokens

**Comment by chigkim** [comment]
Is this same issue?

https://github.com/ollama/ollama/issues/3671

Someone created a PR on fix Llama.cpp, but llama.cpp folks abandoned the vision language models (hopefully temporarily?).

**Comment by royjhan** [comment]
Closing for #3671
