### ISSUE TITLE
support minicpm language model

### ISSUE THREAD

**Issue by LDLINGLINGLING** [ollama/ollama#5740]
Hello, I am the open source staff member of openbmb. The openbmb/minicpm series has a very large audience in China. Many of our users hope that ollama can officially support the minicpm model. I have already processed the modelfile and gguf files, but I don’t know how to get ollama official support. Can you please give me some advice?

**Comment by LDLINGLINGLING** [comment]
Does anyone have a reply?please.

**Comment by pdevine** [comment]
Dupe of #6417
