### ISSUE TITLE
process cant't kill on windows 10

### ISSUE THREAD

**Issue by wszgrcy** [ollama/ollama#5743]
### What is the issue?

I use child process in node to start ollama,and when I kill process,The process will be partially retained(`ollama.exe` is killed ollama_llama_server retained) 
![image](https://github.com/user-attachments/assets/48d9f7d5-92dc-4357-ac1b-f293b994e788)
Ubuntu will correctly kill all processes
### OS

Windows

### GPU

AMD

### CPU

AMD

### Ollama version

0.2.5

**Comment by nikhil-swamix** [comment]
True i can confirm the same

**Comment by dhiltgen** [comment]
How are you terminating the tray application?  If you gracefully signal the app to exit then it should shutdown the subprocesses.  If you forcefully terminate then it has no chance to shutdown the subprocesses.

**Comment by wszgrcy** [comment]
> How are you terminating the tray application? If you gracefully signal the app to exit then it should shutdown the subprocesses. If you forcefully terminate then it has no chance to shutdown the subprocesses.

```ts
   const process = cp.spawn(`${fileName}`, ['serve'], { cwd: dir });
// After waiting for the first round of chat
process.kill();
```
I try to use `SIGTERM`,`SIGHUP`,`SIGINT`,`SIGKILL`,But none of them killed all processes

**Comment by dhiltgen** [comment]
From your code snippet, I'm guessing that you're using NodeJS and trying to manage the ollama server yourself.   Looking around online, it seems the NodeJS implementation of `kill` may not be fully wired up on Windows, and I see some folks recommending using something like this:
```
spawn("taskkill", ["/pid", process.pid, '/t']);
```

**Comment by wszgrcy** [comment]
> From your code snippet, I'm guessing that you're using NodeJS and trying to manage the ollama server yourself. Looking around online, it seems the NodeJS implementation of `kill` may not be fully wired up on Windows, and I see some folks recommending using something like this:
> 
> ```
> spawn("taskkill", ["/pid", process.pid, '/t']);
> ```

thanks! I use `spawn("taskkill", ["/pid", process.pid, '/t','/F']);` kill all process
