### ISSUE TITLE
How to pass a custom file (txt\doc\pdf) to prompt through the API

### ISSUE THREAD

**Issue by liukesoft** [ollama/ollama#5762]
Hello, I have deployed Olama on my local Linux and would like to call it through an API. The model is llama3, and prompt is my custom Python template, which allows the model to generate new Python code according to my Python template. How can I send my template (txt \ doc \ pdf) to the interface through API calls? How to set parameters? thanks！！

curl http://localhost:11434/api/generate -d '{
  "model": "llama3",
  "prompt":"Why is the sky blue?"  //How to use custom prompt templates？？
}'

**Comment by rick-github** [comment]
ollama is just an inference engine, it doesn't do document extraction.  For that you would use something like a document loader from `langchain_community.document_loaders`  or `llama_parse.LLamaParse`.  Then you include the extracted information along with your prompt in the `prompt` field of the message you send to ollama.  The parameters you can set are laid out in the [API guide](https://github.com/ollama/ollama/blob/main/docs/api.md).

**Comment by robotom** [comment]
I can do the text extraction from the document. At that point, is it recommended to just pass entire walls of text into each prompt? 

Are there any tunable settings to maximize the model's understanding of this wall of text? 

Or is it just as simple of dumping all the text into the message that I send to the model.

Any advice on this would be super helpful! Thank you.

**Comment by rick-github** [comment]
Increase the context size (https://github.com/ollama/ollama/issues/7341) and send the text.

**Comment by robotom** [comment]
Thanks. Any idea on how well the model will understand this text? Are there other methods like tuning, params, etc. to achieve this?

Thanks.

**Comment by rick-github** [comment]
https://github.com/ollama/ollama/issues/7341#issuecomment-2436504435

**Comment by armartinez** [comment]
@rick-github The ollama app supports passing files as input, is this functionality available on the API ?

**Comment by rick-github** [comment]
The app does as outlined in https://github.com/ollama/ollama/issues/5762#issuecomment-2237027537: it converts the input file into text that is added to the prompt.  The API doesn't provide this, it's done by the client.  In the app's case, the app is the client doing the conversion.
