### ISSUE TITLE
ollama serve supports only llama3 for other models like gemma its 404 error

### ISSUE THREAD

**Issue by RakshitAralimatti** [ollama/ollama#5768]
Before I downloaded the Llama 3 and used it using the Ollama serve and made API calls using python.

Now I downloaded Gemma 2 and when I run Ollama serve and in API I use the model as gemma2 it shows 404 but when I run using llama3 it's working fine.
Thanks in advance

**Comment by rick-github** [comment]
Does `ollama list` show the gemma2 model?  If you include this line in your python app, does it show the same list?

`print("\n".join([m["name"] for m in ollama.Client().list()["models"]]))`

**Comment by RakshitAralimatti** [comment]
Thanks for your response @rick-github 
When I do ollama list it shows the model name gemma2

**Comment by rick-github** [comment]
Does your app see the same models when it runs the `print` command?  Is it possible that the model name in the app is mis-spelled?  If you copy&paste the model name from your code to `ollama run <modelname>`, does it start the model?

**Comment by RakshitAralimatti** [comment]
@rick-github Thanks for your response 
Yes its shows the model name with print and also when I run `ollama run gemma2` in terminal its working.
But when using ollama serve and using my python script its showing 404 error.

**Comment by rick-github** [comment]
What is the exact error message returned with the 404 response?

**Comment by RakshitAralimatti** [comment]
![ollama404](https://github.com/user-attachments/assets/977707ed-4357-46d8-b6a8-a5ec97c97712)
code i am trying to run - 
`    output = infer.generate({
        "model": "gemma2",
        "prompt": "Write a story of 500 words",
        "stream": False,
        # "options":{
        #     "num_gpu":1,
        #     "num_predict":64
        # }
    })`
    
    The generate function sends the request to API -  http://localhost:11434/api/generate

**Comment by rick-github** [comment]
The response to `infer.generate` will have a body that tells you why it's returning 404.  What is the content of that body?

**Comment by RakshitAralimatti** [comment]
This is the body showing - Content - b'{"error":"model \\"gemma2\\" not found, try pulling it first"}'
But I have gemma2 it shows in the ollama list
NAME          	ID          	SIZE  	MODIFIED     
gemma2:latest 	ff02c3702f32	5.4 GB	24 hours ago	
llama3:latest 	365c0bd3c000	4.7 GB	3 weeks ago 	
example:latest	65cd853c43c7	16 GB 	5 weeks ago 	
phi3:mini     	64c1188f2485	2.4 GB	5 weeks ago 	
phi3:latest   	64c1188f2485	2.4 GB	7 weeks ago

**Comment by rick-github** [comment]
Are you sure that your app is talking to the same ollama server that you are using when you run `ollama list`?  When you ran the `print` command, did you run it within the app?  What was the output of the `print` command?

**Comment by RakshitAralimatti** [comment]
@rick-github  
You r right when I ran the print command within my Python script its showed only `llama3:latest`
But why is it so? I have run ollama in only one terminal

**Comment by rick-github** [comment]
It seems like you are running 2 (or more) ollama servers.  Is your app running in a container?  Is OLLAMA_HOST set in your environment or the environment of the app?  What's the output of `ps wwp$(pidof ollama)`?

**Comment by cleverpig** [comment]
Watch this problem, seem like mine.

**Comment by RakshitAralimatti** [comment]
@rick-github 
When I run `pidof ollama`  the output I get is `50778`.
If I am running more than 2 Ollama servers, how can I stop all the servers?
And the OLLAMA_HOST  env is not set in the environment.

**Comment by rick-github** [comment]
If `pidof ollama` is showing only one process id, that means there's only one ollama server on that machine.   But since `ollama list` and your app are seeing two different model lists, that means there are two servers.  So you will have to figure out why that is.
