### ISSUE TITLE
Update llama.cpp to support Ascend

### ISSUE THREAD

**Issue by zhongTao99** [ollama/ollama#5769]
### What is the issue?

llama.cpp is able to support ascend via https://github.com/ggerganov/llama.cpp/pull/6035/files. I hope to update the llama.cpp submodule to the latest version. According to it, I can adapt ollama in the ascend

### OS

Linux

### GPU

Other

### Ollama version

v0.2.0

**Comment by dhiltgen** [comment]
We're relatively current on llama.cpp at this point.
