### ISSUE TITLE
Can  we add the new smollm models 

### ISSUE THREAD

**Issue by psikosen** [ollama/ollama#5770]
These small models would be a valuable  addition to ollama.

https://huggingface.co/collections/HuggingFaceTB/smollm-6695016cad7167254ce15966

**Comment by weidu-tpvision** [comment]
+1

**Comment by slewisma** [comment]
I'd also like to see the SmolLM models in ollama. They are well suited to local execution on consumer computers and for learning.

**Comment by rick-github** [comment]
The llama.cpp convert scripts needs to be updated, https://github.com/ggerganov/llama.cpp/issues/8568.

**Comment by dhiltgen** [comment]
Looks like a dup of #5731
