### ISSUE TITLE
Error 500 on `/api/embed`

### ISSUE THREAD

**Issue by jmorganca** [ollama/ollama#5781]
### What is the issue?

```
DEBUG [launch_slot_with_data] slot is processing task | slot_id=0 task_id=6368 tid="0x2000bcc00" timestamp=1721333414
time=2024-07-18T13:10:14.830-07:00 level=ERROR source=routes.go:367 msg="embedding generation failed" error="do embedding request: Post \"http://127.0.0.1:64691/embedding\": EOF"
[GIN] 2024/07/18 - 13:10:14 | 500 |  166.036292ms |       127.0.0.1 | POST     "/api/embed"
```

**Comment by royjhan** [comment]
Probably not related but worth noting that passing in input: [""] returns an embedding and is equal to passing in [" "] (with a space) due to the line below in server.cpp:

` task.data["prompt"] = " "; // add a space so that we have one token`

**Comment by royjhan** [comment]
occurs ~1/3 of the time with `python demo.py data/paul_graham_essays.txt '' '' '' ''`, unable to reproduce if empty strings replaced with characters

**Comment by royjhan** [comment]
Unable to reproduce after moving batching from runner to server
