### ISSUE TITLE
add GraphRAG

### ISSUE THREAD

**Issue by tqangxl** [ollama/ollama#5785]
add  GraphRAG

**Comment by rick-github** [comment]
ollama is just an inference engine, it doesn't do RAG.  See the [list of projects](https://github.com/ollama/ollama#web--desktop) that use ollama for something that might implement GraphRAG.

**Comment by FellowTraveler** [comment]
@tqangxl Can you please close this issue? Ollama is not a RAG engine though it does interoperate with many of those, see link above.
