### ISSUE TITLE
Support LoRA GGUF Adapters

### ISSUE THREAD

**Issue by suncloudsmoon** [ollama/ollama#5788]
Recently, [llama.cpp added support for LoRA GGUF adapters](https://github.com/ggerganov/llama.cpp/pull/8332), replacing the old GGML format. I would love to see this feature extended to Ollama if it's possible. Currently, Ollama only supports GGML adapters as shown in [```modelfile.md```](https://github.com/ollama/ollama/blob/main/docs/modelfile.md#adapter).

> The ADAPTER instruction is an optional instruction that specifies any LoRA adapter that should apply to the base model. The value of this instruction should be an absolute path or a path relative to the Modelfile and the file must be in a GGML file format. The adapter should be tuned from the base model otherwise the behaviour is undefined.

**Comment by pdevine** [comment]
It actually is supported! We've removed support for GGLA, but the `ADAPTER` command will work with both GGUF and Safetensors files. Check out the [import docs](https://github.com/ollama/ollama/blob/main/docs/import.md#Importing-a-fine-tuned-adapter-from-Safetensors-weights)

**Comment by rbrisita** [comment]
Would be great if it was also a REPL command to dynamically load adapters so that the Modelfile and `create` command weren't needed.
