### ISSUE TITLE
Windows: could not connect to ollama app, is it running?

### ISSUE THREAD

**Issue by NasonZ** [ollama/ollama#5795]
### What is the issue?

Logged on to my machine today to find ollama has stopped working.

There's been no changes I can think of between when it was working 12 hours ago and now.

I've tried uninstalling and reinstalling llama but this didn't help.

```
>ollama --version
Warning: could not connect to a running Ollama instance
Warning: client version is 0.2.7

>ollama list
Error: could not connect to ollama app, is it running?
```

App logs:
[app.log](https://github.com/user-attachments/files/16312415/app.log)

### OS

Windows

### GPU

Nvidia

### CPU

AMD

### Ollama version

0.2.7

**Comment by rick-github** [comment]
Do you have the server log (C:\Users\Nason\AppData\Local\Ollama\server.log)?

**Comment by TorresIgnacio** [comment]
I have the same problem, maybe this is a dumb question but has this something to do with the crowdstrike worldwide bug situation? Does ollama need to conect to a server in order to start the service locally?

**Comment by rick-github** [comment]
@TorresIgnacio No.

**Comment by NasonZ** [comment]
> Do you have the server log (C:\Users\Nason\AppData\Local\Ollama\server.log)?

Error: listen tcp 127.0.0.1:11434: bind: An attempt was made to access a socket in a way forbidden by its access permissions.

**Comment by rick-github** [comment]
Sounds like a firewall and anti-virus problem.  You may need to change settings on whatever is blocking the port.

**Comment by NasonZ** [comment]
> Sounds like a firewall or anti-virus problem. You may need to change settings on whatever is blocking the port.

```
C:\Users\Nason>netstat -aon | findstr :11434
  TCP    192.168.0.14:11434     188.172.198.138:5938   ESTABLISHED     4808

C:\Users\Nason>tasklist /FI "PID eq 4808"

Image Name                     PID Session Name        Session#    Mem Usage
========================= ======== ================ =========== ============
TeamViewer_Service.exe        4808 Services                   0     20,284 K

C:\Users\Nason>net stop TeamViewer
The TeamViewer service is stopping..
The TeamViewer service was stopped successfully.


C:\Users\Nason>ollama list
NAME    ID      SIZE    MODIFIED
```
Thanks for the heads up, teamviewer highjacked the port. No idea why as I've had both team viewer and ollama on this PC for months without issue.

**Comment by gokulcoder7** [comment]
Error: unable to initialize llm runners unable to locate runners in any search path [C:\Users\Sushant\AppData\Local\Programs\Ollama C:\Users\Sushant\AppData\Local\Programs\Ollama\windows-amd64 C:\Users\Sushant\AppData\Local\Programs\Ollama\dist\windows-amd64 C:\Users\Sushant\AppData\Local\Programs\Ollama C:\Users\Sushant\AppData\Local\Programs\Ollama\windows-amd64 C:\Users\Sushant\AppData\Local\Programs\Ollama\dist\windows-amd64 C:\Windows\System32 C:\Windows\System32\windows-amd64 C:\Windows\System32\dist\windows-amd64]
please help

**Comment by rick-github** [comment]
@gokulcoder7 Open a new issue and include [server logs](https://github.com/ollama/ollama/blob/main/docs/troubleshooting.md#how-to-troubleshoot-issues).

**Comment by gokulcoder7** [comment]
Yes I have opened new issue : https://github.com/ollama/ollama/issues/7697

**Comment by gokulcoder7** [comment]
https://github.com/ollama/ollama/issues/7697#issuecomment-2480396030

**Comment by gokulcoder7** [comment]
[server-2.log](https://github.com/user-attachments/files/17783492/server-2.log)
[server-3.log](https://github.com/user-attachments/files/17783493/server-3.log)
[server-4.log](https://github.com/user-attachments/files/17783494/server-4.log)
[server-5.log](https://github.com/user-attachments/files/17783495/server-5.log)
[server.log](https://github.com/user-attachments/files/17783496/server.log)
[server-1.log](https://github.com/user-attachments/files/17783497/server-1.log)

**Comment by gokulcoder7** [comment]
@rick-github please help me
