### ISSUE TITLE
support for arm linux

### ISSUE THREAD

**Issue by olumolu** [ollama/ollama#5797]
Support for arm linux build so it can be installed in arm laptops which will be coming with new snapdragon x elite cpus with a good npu

**Comment by rick-github** [comment]
#2589, #5360

**Comment by dhiltgen** [comment]
@olumolu we already build ARM64 linux binaries.  e.g. https://github.com/ollama/ollama/releases/download/v0.2.7/ollama-linux-arm64

If those don't work, please share more details and I'll reopen the issue.

**Comment by zuyingwo-lenovo** [comment]
is there anybody working on enabling this on AWS EC2 ARM instance?

this is o screenshot when i tried to install this on g5g instance.

![image](https://github.com/user-attachments/assets/20a2cca4-1f77-4014-8d16-15a8775e0ead)

**Comment by dhiltgen** [comment]
@zuyingwo-lenovo it looks like there might be a slight misalignment on architecture name...

It looks like nvidia is calling it `arm64` https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/ but our install script uses `uname -m` which expands to `aarch64`

Until we get that fixed, you can follow the guidance on the message and install the cuda drivers manually, then Ollama should work on the GPU.

**Comment by daffodils-ai** [comment]
can any body let me know how can i accelerate it on snapdragon x , i have hp omnibook 5 running with 16gb of ram and qualcomm adreno gpu 8gb, i have installed ollama on ubuntu via wsl, however my cpu is beings saturated at 90-100% and gpu is still 2% utilized
