### ISSUE TITLE
unknown architecture DeepseekV2ForCausalLM

### ISSUE THREAD

**Issue by DevLLM** [ollama/ollama#5801]
i have this problem:

docker run --rm -v .:/model ollama/quantize -q q4_K_M /model 
unknown architecture DeepseekV2ForCausalLM

ollama --version
ollama version is 0.2.7`

**Comment by rick-github** [comment]
DeepseekV2ForCausalLM is not a supported architecture, see the [project page](https://registry.hub.docker.com/r/ollama/quantize).  You might be able to do it with the llama.cpp container, which is more up to date:

```
docker run -rm --gpus all -v .:/models ghcr.io/ggerganov/llama.cpp:full-cuda -q /models/ggml-model-f16.gguf Q4_K_M
```
Although it's not clear what model you are trying  to quantize, both deepseek-v2 and deepseek-coder-v2 models are already available on ollama.com at https://ollama.com/search?q=deepseek, so perhaps you don't need to.
