### ISSUE TITLE
allowing ollama 3 to access local txt files for a larger memory?

### ISSUE THREAD

**Issue by boba1234567890** [ollama/ollama#5806]
is there a way to allow ollama 3 to use local txt files for a larger memory and maybe other stuff?

**Comment by rick-github** [comment]
ollama is just an inference engine, see [community integrations](https://github.com/ollama/ollama?tab=readme-ov-file#community-integrations) for projects that build on ollama to offer more functionality.

**Comment by olumolu** [comment]
Alpaca can do this with now 1.0 update https://jeffser.com/alpaca/

**Comment by jmorganca** [comment]
Hi @boba1234567890 thanks for the issue. As @rick-github mentioned, Ollama focuses on providing an API for inference – however the community integrations offer quite a few ways to access local files.
