### ISSUE TITLE
please add `https://huggingface.co/nvidia/Nemotron-4-340B-Instruct` to `https://ollama.com/library`

### ISSUE THREAD

**Issue by hemangjoshi37a** [ollama/ollama#5808]
please add [nvidia/Nemotron-4-340B-Instruct](https://huggingface.co/nvidia/Nemotron-4-340B-Instruct) to `https://ollama.com/library`

**Comment by rick-github** [comment]
dupe https://github.com/ollama/ollama/issues/5777

**Comment by Ramzee-S** [comment]
Nemotron is not the same as Mistral Nemo! so no dupe!

**Comment by jmorganca** [comment]
Closing for https://github.com/ollama/ollama/issues/5068
