### ISSUE TITLE
Tinyllama has issues understanding the Modelfile

### ISSUE THREAD

**Issue by DuilioPerez** [ollama/ollama#5810]
### What is the issue?

When I start a conversation with Tinyllama with a greeting, it answer with a revision of the Modelfile. That's strange. Here is an example
![chrome_screenshot_20 jul  2024 6_39_17 a  m  CST](https://github.com/user-attachments/assets/4bbb17a2-8411-4b1d-a8c5-2f86f63c7e40)

### OS

Linux

### GPU

Other

### CPU

Other

### Ollama version

0.2.7

**Comment by rick-github** [comment]
tinyllama is a, well, tiny model, and as such, has little internal guidance on how to do completions that are open ended.  It works better if you have specific questions or instructions:

```
$ ollama run tinyllama:latest "why is the sky blue?"
The sky is blue due to sunlight reflecting off of its surface at different angles, causing it to appear blue. The exact process by which this happens is complex and involves several factors such as clouds, temperature, and 
atmospheric pressure. However, for our purposes here, we can assume that the primary reason why the sky is blue is because of sunlight reflecting off of its surface in a specific way.
```

It's also pretty old as models go, there are more recent small models that perform better.  For example, qwen2 has a version that is of similar size and is less prone to running off it's "mouth":

```
$ ollama run qwen2:0.5b-instruct-q4_K_M "Hello"
Hello! How can I assist you today?
$ ollama run qwen2:0.5b-instruct-q4_K_M "why is the sky blue?"
Blue is considered a characteristic of water. This is because sunlight falls on water, which reflects and absorbs certain wavelengths (red, blue, and green) of light. When light reaches the Earth's surface, it interacts with other 
particles in the atmosphere, such as nitrogen and oxygen molecules, and causes them to absorb these colors. The color we see when we look at the sky is primarily caused by a combination of the absorption of these different 
wavelengths.
```
