### ISSUE TITLE
Mistral-Nemo support/bug

### ISSUE THREAD

**Issue by phalexo** [ollama/ollama#5812]
### What is the issue?

(Pythogora) developer@ai:~/PROJECTS$ ~/ollama/ollama run mistral-Nemo-Instruct-2407-f16:latest
Error: llama runner process has terminated: signal: aborted (core dumped) error loading model: check_tensor_dims: tensor 'blk.0.attn_q.weight' has wrong shape; expected  5120,  5120, got  5120,  4096,     1,     1
llama_load_model_from_file: exception loading model

### OS

Linux

### GPU

Nvidia

### CPU

Intel

### Ollama version

latest from source.

**Comment by rick-github** [comment]
dupe https://github.com/ollama/ollama/issues/5777

**Comment by dhiltgen** [comment]
Support for mistral-nemo was added in [0.2.8](https://github.com/ollama/ollama/releases/tag/v0.2.8).
