### ISSUE TITLE
Bug: ToolCall issue

### ISSUE THREAD

**Issue by KSemenenko** [ollama/ollama#5813]
### What is the issue?

**Describe the bug**
Tool Calling parameters 

**To Reproduce**
I use Ollama witn OpenAI API.

I used this model
https://ollama.com/library/llama3-groq-tool-use

and Im doung function calling (for gpt4o this code works perfectly)

But I see this as text asnwer from model.
```
<tool_call> {“id”: 0, “name”: “createReservation-Answer”, “arguments”: {“amount”: 1, “roomName”: “Single Room”, “startDate”: “2024-07-21”, “endDate”: “2024-07-23”}} </tool_call>
```
and the function doesn't called.

**Expected behavior**
I expected my function will called.

maybe related https://github.com/microsoft/semantic-kernel/issues/7376

### OS

macOS

### GPU

Apple

### CPU

Apple

### Ollama version

0.2.7

**Comment by KSemenenko** [comment]
Maybe this is sometgin is not supported in ollama api?
https://platform.openai.com/docs/api-reference/chat/create#chat-create-tool_choice

**Comment by rick-github** [comment]
dupe https://github.com/ollama/ollama/issues/5796
