### ISSUE TITLE
Always output GGGGGGG when encountering problems that will not occur... .

### ISSUE THREAD

**Issue by enryteam** [ollama/ollama#5814]
### What is the issue?

https://ollama.com/library/glm4

### OS

Linux

### GPU

Nvidia

### CPU

Intel

### Ollama version

0.2.7

**Comment by rick-github** [comment]
dupe https://github.com/ollama/ollama/issues/5668

**Comment by kindzhon** [comment]
me too

**Comment by AdamWangT** [comment]
me too too

**Comment by enryteam** [comment]
只要出现“ GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG” 接着问任何问题 都是“ GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG”

**Comment by enryteam** [comment]
+1

**Comment by jiaolongxue** [comment]
+1

**Comment by pdevine** [comment]
Make sure you're on the latest version of Ollama and you `ollama pull glm4` to get the latest version. I just tested it w/ both linux and mac and it's working correctly. I'll go ahead and close this, but we can reopen if people are still seeing problems.

**Comment by GwynnePrints** [comment]
Having this issue years later. Clearly not fixed unfortunately. Very disappointing to not be able to use the boards as intended.
