### ISSUE TITLE
OpenAI endpoint gives 404

### ISSUE THREAD

**Issue by defaultsecurity** [ollama/ollama#5830]
### What is the issue?

- http://localhost:11434/v1/chat/completions (gives 404)
- http://localhost:11434 (shows ollama is running)

Otherwise Ollama is working. I'm not sure what to do.

### OS

Linux

### GPU

Nvidia

### CPU

AMD

### Ollama version

0.2.7

**Comment by rick-github** [comment]
If you're using `curl` or `wget` to test the endpoint, be aware that by default these tools send a `GET` and /v1/chat/completions requires a `POST`.

```
$ curl -D - http://localhost:11434/v1/chat/completions
HTTP/1.1 404 Not Found
Content-Type: text/plain
Date: Sun, 21 Jul 2024 14:31:09 GMT
Content-Length: 18

404 page not found(base)
```
```
$ curl -D - -X POST http://localhost:11434/v1/chat/completions
HTTP/1.1 400 Bad Request
Content-Type: application/json; charset=utf-8
Date: Sun, 21 Jul 2024 14:31:44 GMT
Content-Length: 83

{"error":{"message":"EOF","type":"invalid_request_error","param":null,"code":null}}
```

`curl` will automatically use `POST` when you supply data (-d, --data):

```
$ curl -D - http://localhost:11434/v1/chat/completions -d '{"model": "gemma2", "messages": [{"role": "user", "content": "hello"}], "stream": false}'
HTTP/1.1 200 OK
Content-Type: application/json
Date: Sun, 21 Jul 2024 14:36:54 GMT
Content-Length: 326

{"id":"chatcmpl-385","object":"chat.completion","created":1721572614,"model":"gemma2","system_fingerprint":"fp_ollama","choices":[{"index":0,"message":{"role":"assistant","content":"Hello! 👋\n\nHow can I help you today? 😊"},"finish_reason":"stop"}],"usage":{"prompt_tokens":10,"completion_tokens":13,"total_tokens":23}}
```

**Comment by defaultsecurity** [comment]
You're aboslutely right. Thank you for the information.

**Comment by gamersalpha** [comment]
I'm experiencing the exact same issue on a fresh Ollama installation.

**Environment:**
- OS: Debian Trixie (testing)
- Ollama version: Latest (installed today via `curl -fsSL https://ollama.com/install.sh | sh`)
- CPU-only setup (no GPU)
- Ollama running as systemd service

**What works:**
```bash
curl http://127.0.0.1:11434/api/generate -d '{
  "model": "mistral:7b",
  "prompt": "Hello",
  "stream": false
}'
# ✅ Returns valid response in ~4.8 seconds
```

**What doesn't work:**
```bash
curl http://127.0.0.1:11434/v1/chat/completions \
  -H "Content-Type: application/json" \
  -d '{
    "model": "mistral:7b",
    "messages": [{"role": "user", "content": "Hello"}],
    "stream": false
  }'
# ❌ Hangs indefinitely, no response, no error
```

The native Ollama API (`/api/generate`) works perfectly, but the OpenAI-compatible endpoint (`/v1/chat/completions`) doesn't respond at all - it just hangs without returning any HTTP status code.

I tried using litellm as a proxy with `--drop_params` flag but that only revealed that the `/v1` endpoint itself isn't responding to requests.

This makes Ollama incompatible with tools that require OpenAI-compatible APIs (like OpenClaw/Clawdbot).

Is the `/v1` endpoint supposed to work out of the box, or does it require specific configuration?

**Comment by rick-github** [comment]
It is not the exact same issue.  Open a new issue.

**Comment by carloslockward** [comment]
@gamersalpha Did you find a solution?
