### ISSUE TITLE
Please add a tipp

### ISSUE THREAD

**Issue by commitcompanion** [ollama/ollama#5831]
Ollama is the best tool for downloading ai models. Please could you add the following line at the end of the instaler?:
`echo "To get ollama working correctly, specialy if it was instaled in another pakaging before, its recomended to reboot the computer"`

**Comment by rick-github** [comment]
Needing to reboot indicates a problem with the installer/de-installer.  Which packages did you install/remove and what was the symptom of the failure?

**Comment by commitcompanion** [comment]
I am using opensuse. their ollama pakage is broken since 2 weeks, they don't now really what to do. so i installed  ollama from the ollama website. before the reboot my system thinks that ollama is located at /usr/bin, after reboot it was corectly set to /usr/local/bin. 

Ps: Ollama is verry good! It runs without problems on a 10 years old quad core cpu!

**Comment by rick-github** [comment]
This may have been the shell caching the location of the binary.  Did you get `ollama: command not found` errors from the command line, or were there other errors?

There are a couple of simple ways to flush the cache, either run `hash -r` or log out and back in again.

**Comment by commitcompanion** [comment]
Yes i get this error! Is it possible that the hash -r can be includet in the instaler?
This would make it easier for other people with the same problem. 
Thank you all a lot!

**Comment by rick-github** [comment]
Unfortunately `hash -r` needs to run in the parent process, running it in the installer (a child process) will have no effect.

Another workaround is to start a new shell, either run `bash` in the current terminal, or open a new terminal session.
