### ISSUE TITLE
The logs do not contain the request content sent by the client.

### ISSUE THREAD

**Issue by H9990HH969** [ollama/ollama#5848]
To facilitate debugging of the program, I need to see the requests sent to the large model from the frontend. However, I've noticed that the request URLs and contents are not visible in the logs. Where can I find them?

I have deployed DBGPT using Docker.

**Comment by rick-github** [comment]
The request body is not logged.  You can see the prompt sent to the inference engine by setting `OLLAMA_DEBUG=1` in the server environment and searching for `msg="generate request"` in the logs.  If you want the contents of the HTTP traffic you'll have to use external tools.  I usually install `tcpflow` in my ollama container image and use that:

```
tcpflow -c 'src port 11434 or dst port 11434'`
```

Other tools like `ngrep` are also useful.

**Comment by konstantin1722** [comment]
I used WireShark. I have ollama deployed on a regular pc, so I used such a filter to inspect how langchain composes some promts: `ip.dst == 192.168.1.55 && tcp.dstport == 11434 && http`. Accordingly, by slightly changing the filter you can intercept requests for the docker container.

**Comment by dhiltgen** [comment]
As mentioned above, by default, for privacy concerns, we intentionally do not log the contents of the requests on the server.  If you enable debug logging, then much more logging is produced, including the prompts.
