### ISSUE TITLE
function calling documentation

### ISSUE THREAD

**Issue by UmutAlihan** [ollama/ollama#5863]
While searching the web I couldn't yet find a resource except function callilng through mistral_inference package.

I am curious whether anyone wrote a raw prompt in which function calling is working?

**Comment by 812781385** [comment]
Maybe you should try it：
https://github.com/812781385/ollama-webUI

**Comment by rick-github** [comment]
An example of function calling documentation is https://docs.mistral.ai/capabilities/function_calling/

If you want to do function calling without using an LLM specific package, it can be done with direct HTTP calls, for example with the python `requests` package or using shell tools.  For instance, if we take the mistral document from above, we can transpose it into a shell script.

First we set the model.  This can be any tool-supporting model, but you asked about mistral-nemo so we'll use that:

```sh
model="mistral-nemo"
```

Then we create the tool list.  This is copied from the mistral doc with some syntax changes to account for the difference between python and JSON structures:

```sh
tools='[
  {
        "type": "function",
        "function": {
            "name": "retrieve_payment_status",
            "description": "Get payment status of a transaction",
            "parameters": {
                "type": "object",
                "properties": {
                    "transaction_id": {
                        "type": "string",
                        "description": "The transaction id."
                    }
                },
                "required": ["transaction_id"]
            }
        }
    },
    {
        "type": "function",
        "function": {
            "name": "retrieve_payment_date",
            "description": "Get payment date of a transaction",
            "parameters": {
                "type": "object",
                "properties": {
                    "transaction_id": {
                        "type": "string",
                        "description": "The transaction id."
                    }
                },
                "required": ["transaction_id"]
            }
        }
    }
]
'
```

Next we construct the message that will be answered by the LLM using the tools:

```sh
messages='[
        {
            "content": "What'\''s the status of my transaction T1001?",
            "role": "user"
        }
    ]
'
```

Now we create the data that is sent to the LLM:

```sh
data='
  {
    "messages": '"$messages"',
    "tools": '"$tools"',
    "model": "'$model'",
    "temperature": 0.3
  }
'
```

Finally, send the query to ollama:

```sh
curl -s --location --request POST 'http://localhost:11434/v1/chat/completions' \
--header 'Content-Type: application/json' \
--data "$data"
```

The result is:

```json
{
  "id": "chatcmpl-956",
  "object": "chat.completion",
  "created": 1721723598,
  "model": "mistral-nemo",
  "system_fingerprint": "fp_ollama",
  "choices": [
    {
      "index": 0,
      "message": {
        "role": "assistant",
        "content": "",
        "tool_calls": [
          {
            "id": "call_bst9zzpx",
            "type": "function",
            "function": {
              "name": "retrieve_payment_status",
              "arguments": "{\"transaction_id\":\"T1001\"}"
            }
          }
        ]
      },
      "finish_reason": "stop"
    }
  ],
  "usage": {
    "prompt_tokens": 125,
    "completion_tokens": 27,
    "total_tokens": 152
  }
}

```

The script then needs to iterate over the tools calls and make the actual function call to retrieve the data:

```sh
$ resp=$(./function-call)
$ echo "$resp" | jq -c .choices[].message.tool_calls[]
{"id":"call_t6chpn4u","type":"function","function":{"name":"retrieve_payment_status","arguments":"{\"transaction_id\":\"T1001\"}"}}
$ for tool_call in $(echo "$resp" | jq -c .choices[].message.tool_calls[]) ; do
  function=$(echo "$tool_call" | jq -r .function.name)
  _=$(which $function) || { echo "function $function not found" ; break ; }
  args=$(echo "$tool_call" | jq -r .function.arguments)
  $function $args    # do the function
done
```

The python equivalent using `requests` is:

```python
#!/usr/bin/env python3

import requests

model="mistral-nemo"

tools = [
  {
        "type": "function",
        "function": {
            "name": "retrieve_payment_status",
            "description": "Get payment status of a transaction",
            "parameters": {
                "type": "object",
                "properties": {
                    "transaction_id": {
                        "type": "string",
                        "description": "The transaction id."
                    }
                },
                "required": ["transaction_id"]
            }
        }
    },
    {
        "type": "function",
        "function": {
            "name": "retrieve_payment_date",
            "description": "Get payment date of a transaction",
            "parameters": {
                "type": "object",
                "properties": {
                    "transaction_id": {
                        "type": "string",
                        "description": "The transaction id."
                    }
                },
                "required": ["transaction_id"]
            }
        }
    }
]

messages = [
    {
        "content": "What'\''s the status of my transaction T1001?",
        "role": "user"
    }
]

data={
    "messages": messages,
    "tools": tools,
    "model": model,
    "temperature": 0.3
}

response = requests.post('http://localhost:11434/v1/chat/completions',
    headers={"Content-Type": "application/json"},
    json=data)

print(response.text)
```

**Comment by UmutAlihan** [comment]
> An example of function calling documentation is https://docs.mistral.ai/capabilities/function_calling/
> 
> If you want to do function calling without using an LLM specific package, it can be done with direct HTTP calls, for example with the python `requests` package or using shell tools.  For instance, if we take the mistral document from above, we can transpose it into a shell script.
> 
> First we set the model.  This can be any tool-supporting model, but you asked about mistral-nemo so we'll use that:
> 
> ```sh
> model="mistral-nemo"
> ```
> 
> Then we create the tool list.  This is copied from the mistral doc with some syntax changes to account for the difference between python and JSON structures:
> 
> ```sh
> tools='[
>   {
>         "type": "function",
>         "function": {
>             "name": "retrieve_payment_status",
>             "description": "Get payment status of a transaction",
>             "parameters": {
>                 "type": "object",
>                 "properties": {
>                     "transaction_id": {
>                         "type": "string",
>                         "description": "The transaction id."
>                     }
>                 },
>                 "required": ["transaction_id"]
>             }
>         }
>     },
>     {
>         "type": "function",
>         "function": {
>             "name": "retrieve_payment_date",
>             "description": "Get payment date of a transaction",
>             "parameters": {
>                 "type": "object",
>                 "properties": {
>                     "transaction_id": {
>                         "type": "string",
>                         "description": "The transaction id."
>                     }
>                 },
>                 "required": ["transaction_id"]
>             }
>         }
>     }
> ]
> '
> ```
> 
> Next we construct the message that will be answered by the LLM using the tools:
> 
> ```sh
> messages='[
>         {
>             "content": "What'\''s the status of my transaction T1001?",
>             "role": "user"
>         }
>     ]
> '
> ```
> 
> Now we create the data that is sent to the LLM:
> 
> ```sh
> data='
>   {
>     "messages": '"$messages"',
>     "tools": '"$tools"',
>     "model": "'$model'",
>     "temperature": 0.3
>   }
> '
> ```
> 
> Finally, send the query to ollama:
> 
> ```sh
> curl -s --location --request POST 'http://localhost:11434/v1/chat/completions' \
> --header 'Content-Type: application/json' \
> --data "$data"
> ```
> 
> The result is:
> 
> ```json
> {
>   "id": "chatcmpl-956",
>   "object": "chat.completion",
>   "created": 1721723598,
>   "model": "mistral-nemo",
>   "system_fingerprint": "fp_ollama",
>   "choices": [
>     {
>       "index": 0,
>       "message": {
>         "role": "assistant",
>         "content": "",
>         "tool_calls": [
>           {
>             "id": "call_bst9zzpx",
>             "type": "function",
>             "function": {
>               "name": "retrieve_payment_status",
>               "arguments": "{\"transaction_id\":\"T1001\"}"
>             }
>           }
>         ]
>       },
>       "finish_reason": "stop"
>     }
>   ],
>   "usage": {
>     "prompt_tokens": 125,
>     "completion_tokens": 27,
>     "total_tokens": 152
>   }
> }
> 
> ```
> 
> The script then needs to iterate over the tools calls and make the actual function call to retrieve the data:
> 
> ```sh
> $ resp=$(./function-call)
> $ echo "$resp" | jq -c .choices[].message.tool_calls[]
> {"id":"call_t6chpn4u","type":"function","function":{"name":"retrieve_payment_status","arguments":"{\"transaction_id\":\"T1001\"}"}}
> $ for tool_call in $(echo "$resp" | jq -c .choices[].message.tool_calls[]) ; do
>   function=$(echo "$tool_call" | jq -r .function.name)
>   _=$(which $function) || { echo "function $function not found" ; break ; }
>   args=$(echo "$tool_call" | jq -r .function.arguments)
>   $function $args    # do the function
> done
> ```
> 
> The python equivalent using `requests` is:
> 
> ```python
> #!/usr/bin/env python3
> 
> import requests
> 
> model="mistral-nemo"
> 
> tools = [
>   {
>         "type": "function",
>         "function": {
>             "name": "retrieve_payment_status",
>             "description": "Get payment status of a transaction",
>             "parameters": {
>                 "type": "object",
>                 "properties": {
>                     "transaction_id": {
>                         "type": "string",
>                         "description": "The transaction id."
>                     }
>                 },
>                 "required": ["transaction_id"]
>             }
>         }
>     },
>     {
>         "type": "function",
>         "function": {
>             "name": "retrieve_payment_date",
>             "description": "Get payment date of a transaction",
>             "parameters": {
>                 "type": "object",
>                 "properties": {
>                     "transaction_id": {
>                         "type": "string",
>                         "description": "The transaction id."
>                     }
>                 },
>                 "required": ["transaction_id"]
>             }
>         }
>     }
> ]
> 
> messages = [
>     {
>         "content": "What'\''s the status of my transaction T1001?",
>         "role": "user"
>     }
> ]
> 
> data={
>     "messages": messages,
>     "tools": tools,
>     "model": model,
>     "temperature": 0.3
> }
> 
> response = requests.post('http://localhost:11434/v1/chat/completions',
>     headers={"Content-Type": "application/json"},
>     json=data)
> 
> print(response.text)
> ```

wow thank you for comprehensive answer, I will try it asap when I get back to mt pc 

cheers

**Comment by ronneldavis** [comment]
> An example of function calling documentation is https://docs.mistral.ai/capabilities/function_calling/
> 
> If you want to do function calling without using an LLM specific package, it can be done with direct HTTP calls, for example with the python `requests` package or using shell tools. For instance, if we take the mistral document from above, we can transpose it into a shell script.
> 
> First we set the model. This can be any tool-supporting model, but you asked about mistral-nemo so we'll use that:
> 
> ```shell
> model="mistral-nemo"
> ```
> 
> Then we create the tool list. This is copied from the mistral doc with some syntax changes to account for the difference between python and JSON structures:
> 
> ```shell
> tools='[
>   {
>         "type": "function",
>         "function": {
>             "name": "retrieve_payment_status",
>             "description": "Get payment status of a transaction",
>             "parameters": {
>                 "type": "object",
>                 "properties": {
>                     "transaction_id": {
>                         "type": "string",
>                         "description": "The transaction id."
>                     }
>                 },
>                 "required": ["transaction_id"]
>             }
>         }
>     },
>     {
>         "type": "function",
>         "function": {
>             "name": "retrieve_payment_date",
>             "description": "Get payment date of a transaction",
>             "parameters": {
>                 "type": "object",
>                 "properties": {
>                     "transaction_id": {
>                         "type": "string",
>                         "description": "The transaction id."
>                     }
>                 },
>                 "required": ["transaction_id"]
>             }
>         }
>     }
> ]
> '
> ```
> 
> Next we construct the message that will be answered by the LLM using the tools:
> 
> ```shell
> messages='[
>         {
>             "content": "What'\''s the status of my transaction T1001?",
>             "role": "user"
>         }
>     ]
> '
> ```
> 
> Now we create the data that is sent to the LLM:
> 
> ```shell
> data='
>   {
>     "messages": '"$messages"',
>     "tools": '"$tools"',
>     "model": "'$model'",
>     "temperature": 0.3
>   }
> '
> ```
> 
> Finally, send the query to ollama:
> 
> ```shell
> curl -s --location --request POST 'http://localhost:11434/v1/chat/completions' \
> --header 'Content-Type: application/json' \
> --data "$data"
> ```
> 
> The result is:
> 
> ```json
> {
>   "id": "chatcmpl-956",
>   "object": "chat.completion",
>   "created": 1721723598,
>   "model": "mistral-nemo",
>   "system_fingerprint": "fp_ollama",
>   "choices": [
>     {
>       "index": 0,
>       "message": {
>         "role": "assistant",
>         "content": "",
>         "tool_calls": [
>           {
>             "id": "call_bst9zzpx",
>             "type": "function",
>             "function": {
>               "name": "retrieve_payment_status",
>               "arguments": "{\"transaction_id\":\"T1001\"}"
>             }
>           }
>         ]
>       },
>       "finish_reason": "stop"
>     }
>   ],
>   "usage": {
>     "prompt_tokens": 125,
>     "completion_tokens": 27,
>     "total_tokens": 152
>   }
> }
> ```
> 
> The script then needs to iterate over the tools calls and make the actual function call to retrieve the data:
> 
> ```shell
> $ resp=$(./function-call)
> $ echo "$resp" | jq -c .choices[].message.tool_calls[]
> {"id":"call_t6chpn4u","type":"function","function":{"name":"retrieve_payment_status","arguments":"{\"transaction_id\":\"T1001\"}"}}
> $ for tool_call in $(echo "$resp" | jq -c .choices[].message.tool_calls[]) ; do
>   function=$(echo "$tool_call" | jq -r .function.name)
>   _=$(which $function) || { echo "function $function not found" ; break ; }
>   args=$(echo "$tool_call" | jq -r .function.arguments)
>   $function $args    # do the function
> done
> ```
> 
> The python equivalent using `requests` is:
> 
> ```python
> #!/usr/bin/env python3
> 
> import requests
> 
> model="mistral-nemo"
> 
> tools = [
>   {
>         "type": "function",
>         "function": {
>             "name": "retrieve_payment_status",
>             "description": "Get payment status of a transaction",
>             "parameters": {
>                 "type": "object",
>                 "properties": {
>                     "transaction_id": {
>                         "type": "string",
>                         "description": "The transaction id."
>                     }
>                 },
>                 "required": ["transaction_id"]
>             }
>         }
>     },
>     {
>         "type": "function",
>         "function": {
>             "name": "retrieve_payment_date",
>             "description": "Get payment date of a transaction",
>             "parameters": {
>                 "type": "object",
>                 "properties": {
>                     "transaction_id": {
>                         "type": "string",
>                         "description": "The transaction id."
>                     }
>                 },
>                 "required": ["transaction_id"]
>             }
>         }
>     }
> ]
> 
> messages = [
>     {
>         "content": "What'\''s the status of my transaction T1001?",
>         "role": "user"
>     }
> ]
> 
> data={
>     "messages": messages,
>     "tools": tools,
>     "model": model,
>     "temperature": 0.3
> }
> 
> response = requests.post('http://localhost:11434/v1/chat/completions',
>     headers={"Content-Type": "application/json"},
>     json=data)
> 
> print(response.text)
> ```

@rick-github This example uses the mistral client and not ollama. Ollama does not have native support for tool use as of yet.

**Comment by rick-github** [comment]
@ronneldavis Tool support is evolving but ollama supports tool use with tool supporting models since https://github.com/ollama/ollama/pull/5284.  This example code does not use the mistral client.

**Comment by ronneldavis** [comment]
@rick-github Oh that's awesome! I believe the documentation hasn't been updated with the new addition so my apologies

**Comment by jmorganca** [comment]
Hi there! Function calling is now supported in Ollama. See https://ollama.com/blog/tool-support or the api documentation: https://github.com/ollama/ollama/blob/main/docs/api.md#chat-request-with-tools

**Comment by UmutAlihan** [comment]
thank you thank you thank you
