### ISSUE TITLE
无限更新

### ISSUE THREAD

**Issue by yuchenwei28** [ollama/ollama#5865]
### What is the issue?

无限更新到2.0.8

### OS

Windows

### GPU

Intel

### CPU

Intel

**Comment by mchiang0610** [comment]
对不起，可以问，这是那一个Windows 吗? 我们想要看为什么会这样

**Comment by Karl8023** [comment]
我也遇到了同样的问题，我的系统是：Windows 10 Enterprise 22H2

**Comment by taozhiyuai** [comment]
什么是无限更新?
