### ISSUE TITLE
about mistral-nemo:12b  using issue , please help

### ISSUE THREAD

**Issue by ryanlxb** [ollama/ollama#5866]
### What is the issue?

ollama pull  mistral-nemo:12b
pulling manifest 
pulling b559938ab7a0... 100% ▕██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏ 7.1 GB                         
pulling f023d1ce0e55... 100% ▕██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏  688 B                         
pulling 8fe8671a714f... 100% ▕██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏  11 KB                         
pulling ed11eda7790d... 100% ▕██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏   30 B                         
pulling 65d37de20e59... 100% ▕██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏  486 B                         
verifying sha256 digest 
writing manifest 
removing any unused layers 
success 

ollama run mistral-nemo:12b  
Error: llama runner process has terminated: signal: abort trap error:check_tensor_dims: tensor 'blk.0.attn_q.weight' has wrong shape; expected  5120,  5120, got  5120,  4096,     1,     1

 ollama --version
ollama version is 0.2.7

### OS

macOS

### GPU

Apple

### CPU

Apple

### Ollama version

0.2.7

**Comment by jmorganca** [comment]
Hi @ryanlxb sorry about the bad error message – you'll need to upgrade to 0.2.8 to run `mistral-nemo` - you can download it here: https://ollama.com/download

**Comment by ryanlxb** [comment]
> Hi @ryanlxb sorry about the bad error message – you'll need to upgrade to 0.2.8 to run `mistral-nemo` - you can download it here: https://ollama.com/download

Thanks ，I'll try :)
