### ISSUE TITLE
Wrong template for NuExtract model

### ISSUE THREAD

**Issue by adam-the** [ollama/ollama#5875]
The template for this model should be more like:
```
{{- range .Messages }}
{{- if eq .Role "user" }}<|input|>
{{ .Content }}<|output|>
{{- else if eq .Role "assistant" }}
{{ .Content }} <|end-output|>
{{- end }}
{{- end }}
```
I put a space before the `<|end-output|>` token as recommended [here](https://huggingface.co/numind/NuExtract/discussions/8).
<sub>Reference: https://huggingface.co/numind/NuExtract#usage</sub>

And the stop params file should contain these entries:
```
<|endoftext|>
<|assistant|>
<|end|>
<|end-output|>
```
<sub>Reference: https://huggingface.co/numind/NuExtract/blob/main/generation_config.json</sub>

After making these changes in my local Modelfile, the model functions as expected.

### Ollama version

0.2.8

**Comment by adam-the** [comment]
Additionally, it would be nice if the README could be updated to include an example of the model's usage:
```
### Template:
{
  "Person's Name": "",
  "Person's Age": ""
}

### Example:
[
  {
    "Person's Name": "John Smith",
    "Person's Age": "20"
  },
  ...
]

### Text:
My name is Jane Doe and I am 30.
```
Including the examples section is optional.

**Comment by jmorganca** [comment]
Hi there, I believe this has been fixed. If that isn't the case please let me know.

**Comment by ProjectMoon** [comment]
https://ollama.com/library/nuextract/blobs/e3e379c2858c is this the current template?
