### ISSUE TITLE
Ollama API not seeing messages provided in conversation_history

### ISSUE THREAD

**Issue by barclaybrown** [ollama/ollama#5877]
### What is the issue?

When I pass a list of dictionaries (messages) to ollama.chat it seems that the model does not see anything other than the latest message. For example, I want the model to get a bunch of text, and then answer a question about it. I send something like:

role : system  content: You are a helpful assistant
role: user       content:  a bunch of reference text
role: user       content: a question related to the reference text

then I get back

role: assistant  content:  an answer unrelated to the reference text, as if it doesn't see it

Is this a bug, or maybe I'm doing something wrong?

### OS

Windows

### GPU

Nvidia

### Ollama version

0.2.7

**Comment by rick-github** [comment]
Can you provide an example?  It looks to work here:

```sh
$ curl -s localhost:11434/api/chat -d '{
  "model": "qwen2:0.5b",
  "messages": [
    {
      "role": "user",
      "content": "an apple is $1.50"
    },
    {
      "role": "user",
      "content": "how much is an apple?"
    }
  ],
  "stream": false
}' | jq .message
```
```json
{
  "role": "assistant",
  "content": "An apple costs $1.50."
}

```

**Comment by barclaybrown** [comment]
Thanks very much This might have given me the hint I needed. The text I'm supplying in the first user message is 45000 tokens, which I thought Phi3 128k should be fine with. Is there a chance that Ollama is throwing it out because it's too long? My same example worked, like yours, when I chopped the text down to about 4k tokens. If there's a limit to user message length, I could split up my text?

**Comment by rick-github** [comment]
The default context length for ollama is 2048, so it's likely the text is being discarded (check the server logs for "input truncated").  You can pass an option in the API call to increase the window:

```
$ curl -s localhost:11434/api/chat -d '{
  "model": "qwen2:0.5b",
  "messages": [
    {
      "role": "user",
      "content": "an apple is $1.50"
    },
    {
      "role": "user",
      "content": "how much is an apple?"
    }
  ],
  "options": { "num_ctx": 45000 },
  "stream": false
}' | jq .message
```

Be aware that this can significantly increase the VRAM/RAM requirements for the model, memory usage is quadratic on the length of the context window.

**Comment by pdevine** [comment]
@rick-github 's answer is correct. I'll go ahead and close this out.
