### ISSUE TITLE
Definiting a host in /etc/hosts doesn't work

### ISSUE THREAD

**Issue by JayCroghan** [ollama/ollama#5879]
### What is the issue?

I am trying to set a hostname in /etc/hosts and it works fine for ping but ollama gives the following output:

somedomain.com below most definitely does not exist.

```
  ___                    __        __   _     _   _ ___
 / _ \ _ __   ___ _ __   \ \      / /__| |__ | | | |_ _|
| | | | '_ \ / _ \ '_ \   \ \ /\ / / _ \ '_ \| | | || |
| |_| | |_) |  __/ | | |   \ V  V /  __/ |_) | |_| || |
 \___/| .__/ \___|_| |_|    \_/\_/ \___|_.__/ \___/|___|
      |_|


v0.3.6 - building the best open-source AI user interface.

https://github.com/open-webui/open-webui

INFO:apps.openai.main:get_all_models()
INFO:apps.ollama.main:get_all_models()
ERROR:apps.ollama.main:Connection error: Cannot connect to host somedomain.com:11434 ssl:default [Name or service not known]
INFO:     192.168.2.108:0 - "GET /ws/socket.io/?EIO=4&transport=polling&t=P3W7LDd HTTP/1.0" 200 OK
INFO:apps.openai.main:get_all_models()
INFO:apps.ollama.main:get_all_models()
ERROR:apps.ollama.main:Connection error: Cannot connect to host somedomain.com:11434 ssl:default [Name or service not known]
INFO:     192.168.2.108:0 - "POST /ws/socket.io/?EIO=4&transport=polling&t=P3W7LZz&sid=qzoO8V8hGw4XAjT7AAAA HTTP/1.0" 200 OK
INFO:apps.openai.main:get_all_models()
INFO:apps.ollama.main:get_all_models()
INFO:apps.openai.main:get_all_models()
INFO:apps.ollama.main:get_all_models()
ERROR:apps.ollama.main:Connection error: Cannot connect to host somedomain.com:11434 ssl:default [Name or service not known]
INFO:     192.168.2.108:0 - "GET /ws/socket.io/?EIO=4&transport=websocket&sid=qzoO8V8hGw4XAjT7AAAA HTTP/1.0" 200 OK
ERROR:apps.ollama.main:Connection error: Cannot connect to host jayinchinalocal.com:11434 ssl:default [Name or service not known]

```
The IP is actually the one from the hosts file but for some reason it can't find it the hostname?

```
ping somedomain.com
PING somedomain.com (192.168.2.108) 56(84) bytes of data.

64 bytes from somedo127.0.1.1 (192.168.2.108): icmp_seq=1 ttl=128 time=1.02 ms
```

I'm guessing the somedo in the return is some kind of internal hostname but hardly has anything to do with the issue.

Ollama is on another Windows machine than my server calling the queries from Linux.

### OS

Linux, Docker

### GPU

Nvidia

### CPU

Intel

### Ollama version

0.2.8

**Comment by rick-github** [comment]
This doesn't look like an ollama issue.

Are you editing /etc/hosts in the docker container or on the host system?

**Comment by rick-github** [comment]
Is the IP address dynamic or static?

One approach would to take a copy of the /etc/hosts from the open-webui container, edit it as required, and mount it during start as an additional `volume` in your docker-compose.yaml:

```yaml
services:
  ollama:
#...
  open-webui:
#...
    volumes:
      - ./hosts:/etc/hosts
```

**Comment by JayCroghan** [comment]
It's dynamic, I wrote an API to take the dynamic IP from the host that writes to my local file. I could just docker cp that across to my container but they are different.

In your example, adding it a volume, that still doesn't allow me to edit it without copying it to the host, editing it and copying it back.

**Comment by rick-github** [comment]
In your docker-compose.yaml:

```yaml
services:
  open-webui:
#...
    extra_hosts:
      - ${OLLAMA_HOST-somedomain.com:127.0.0.1}
```
When you start the open-webui service:
```sh
$ export OLLAMA_HOST=somedomain.com:$(script-that-gets-the-ip-address-of-the-ollama-server)
$ docker compose up -d open-webui
```

**Comment by JayCroghan** [comment]
Ok, I can do that much easier than the server I was using to write to the hosts file and skip hosts file completely.

Can I skip compose and just use that EXPORT for docker run or that's a no no with docker?? Sorry I'm new with docker.

Thanks!

**Comment by JayCroghan** [comment]
Or I can make my script copy the file into the container anytime a change is made I guess.

**Comment by JayCroghan** [comment]
And that will run the script on the host and not in the container?

**Comment by rick-github** [comment]
Yes, `$(cmd)` will be executed on the host, the contents will be put in the environment variable `OLLAMA_BASE_URL`, and open-webui inside the container will use that when trying to connect to the ollama server.

**Comment by JayCroghan** [comment]
Thank you so much that is superb.

**Comment by JayCroghan** [comment]
For my specific problem it was a lot easier actually, the top answer here worked. I just add .local to the end of the windows hostname and it works fine!

https://askubuntu.com/questions/266265/access-windows-machines-from-ubuntu-on-local-network-by-hostname

**Comment by technovangelist** [comment]
Can you go ahead and close the issue. And try to only add the bug label when it is a bug.

**Comment by JayCroghan** [comment]
> Yes, `$(cmd)` will be executed on the host, the contents will be put in the environment variable `OLLAMA_BASE_URL`, and open-webui inside the container will use that when trying to connect to the ollama server.

Question though: I have '-e OLLAMA_BASE_URL=http://$(cat /home/jay/dynip/ip.txt)' in my docker run, when the IP changes, how does that change the environment variable? That was my problem from the outset was how do I tell OLLAMA that the IP has changed without taking it down...

**Comment by rick-github** [comment]
Yeah, during the initial discussion I meant to ask you if the IP address would change during the life of the ollama container, I forgot to follow up on that.  If you are using `.local`, then use `'-e OLLAMA_BASE_URL=http://myollamaserver.local` instead.  When the ollama server restarts, it will broadcast it's new WINS allocation and open-webui will resolve it and talk to the new IP address.

**Comment by JayCroghan** [comment]
Adding the following resulted in the same issue, except the ports don't change as normal because of 'network host'

'-e OLLAMA_BASE_URL=http://desktop-jay.local:11434 -v /etc/nsswitch.conf:/etc/nsswitch.conf -v open-webui:/app/backend/data -d --network host'

**Comment by rick-github** [comment]
Did you install `winbind` in the open-webui container?  If not, then adding `wins` to the `hosts` won't work.

**Comment by JayCroghan** [comment]
> Did you install `winbind` in the open-webui container? If not, then adding `wins` to the `hosts` won't work.

No I'm using ghcr.io/open-webui/open-webui:main so I can't change the docker file and yes that's why wins won't work and why I'm resorting to changing the IP at runtime. ENV variable won't work as that's only checked at runtime.

**Comment by rick-github** [comment]
If you don't want to modify the container, you'll have to do the resolution on the host.  There are a number of ways to do this, none of them pretty.

Are the windows and linux hosts on the same network?  Are the ip addresses in a public or private (192.168, 172., etc) space?  If private, do you have access to the device that does the dynamic IP address allocation?  Does yout linux server currently run a DNS server?  Can you add services to the windows machine?

BTW, this would be simpler if both services ran on the same machine, is the separation a requirement?

**Comment by rick-github** [comment]
Get a copy of the hosts file from the open-webui image:
```
docker run -it --rm --entrypoint bash ghcr.io/open-webui/open-webui -c 'cat /etc/hosts' > hosts
```
Add a place holder to it:
```
echo "127.0.0.1 ollama" >> hosts
```
Run your open-webui, mounting the hosts file and setting OLLAMA_BASE_URL:
```
docker run -d -p 3000:8080 \
    -e OLLAMA_BASE_URL=http://ollama:11434 \
    -v ./hosts:/etc/hosts \
    -v open-webui:/app/backend/data \
    --name open-webui \
    --restart always \
    ghcr.io/open-webui/open-webui:main
```
When the windows box calls the service on the OpenWebUI machine to notify an IP change, have it update the `ollama` line in the hosts file, eg:
```
file=/path/to/hosts ; hosts=$(cat $file) ; echo "$hosts" | sed -e "s/^[0-9.]* ollama$/$NEW_IP_ADDRESS ollama/" > $file
```
Note that you must use an update method that doesn't change the inode of the file, `perl -pi -e` won't work.

Also note that you may have state saved in the open-webui volume that already set the ollama endpoint and setting OLLAMA_BASE_URL may not override it.  You can either go to the admin panel in open-webui and set it to http://ollama:11434, or remove the open-webui volume and start from scratch: `docker volume rm open-webui`.

**Comment by JayCroghan** [comment]
Thanks very much for this, it gives me plenty to think about and play with. It's really hard to imagine why there is no way to programmatically tell Ollama the host is updated.

>You can either go to the admin panel in open-webui and set it to http://ollama:11434, or remove the open-webui volume and start from scratch: `docker volume rm open-webui`.

The input box for the URI is _always_ greyed out for me, otherwise I wouldn't need this solution!!

**Comment by JayCroghan** [comment]
> Get a copy of the hosts file from the open-webui image:
> 
> ```
> docker run -it --rm --entrypoint bash ghcr.io/open-webui/open-webui -c 'cat /etc/hosts' > hosts
> ```
> 
> Add a place holder to it:
> 
> ```
> echo "127.0.0.1 ollama" >> hosts
> ```
> 
> Run your open-webui, mounting the hosts file and setting OLLAMA_BASE_URL:
> 
> ```
> docker run -d -p 3000:8080 \
>     -e OLLAMA_BASE_URL=http://ollama:11434 \
>     -v ./hosts:/etc/hosts \
>     -v open-webui:/app/backend/data \
>     --name open-webui \
>     --restart always \
>     ghcr.io/open-webui/open-webui:main
> ```
> 
> When the windows box calls the service on the OpenWebUI machine to notify an IP change, have it update the `ollama` line in the hosts file, eg:
> 
> ```
> file=/path/to/hosts ; hosts=$(cat $file) ; echo "$hosts" | sed -e "s/^[0-9.]* ollama$/$NEW_IP_ADDRESS ollama/" > $file
> ```
> 
> Note that you must use an update method that doesn't change the inode of the file, `perl -pi -e` won't work.
> 
> Also note that you may have state saved in the open-webui volume that already set the ollama endpoint and setting OLLAMA_BASE_URL may not override it. You can either go to the admin panel in open-webui and set it to http://ollama:11434, or remove the open-webui volume and start from scratch: `docker volume rm open-webui`.

IT WORKS!!!! I'm using an edited npm package called Hostile to edit the hosts file with `-v /home/jay/dynip/hosts:/etc/hosts` in my `docker run` and it updates automatically when I call my webserver to update it. Thanks so much!
