### ISSUE TITLE
Is llama 3.1 already supported (on 2.8) or should we wait another update ?

### ISSUE THREAD

**Issue by Qualzz** [ollama/ollama#5881]
### What is the issue?

The model page seems to already exists in ollama website, but the model is clearly behaving erratically, which makes me wonder if we should wait for an update before using llama 3.1.  

### OS

Windows

### GPU

Nvidia

### CPU

AMD

### Ollama version

2.8

**Comment by Qualzz** [comment]
![image](https://github.com/user-attachments/assets/aa403a90-5622-4d40-a416-8fb53499bc14)

**Comment by rick-github** [comment]
What model and UI?  I tried the "sticky header" question with open-webui v0.3.8, ollama 0.2.8 and model llama3.1:8b-instruct-q4_K_M and got a perfectly reasonable answer.

**Comment by Qualzz** [comment]
same issue without any ui:
![image](https://github.com/user-attachments/assets/3738af1d-4eb7-4aca-9b13-480aaae70834)

0.2.8 and basic Q8 quant

**Comment by sam2332** [comment]
model just spams text until stopped

**Comment by taozhiyuai** [comment]
works fine on m3 max 128GB.  version=0.2.8

**Comment by debackerl** [comment]
I don't think that the Ollama config is finalized yet. For example, they explain that when the Llama 3.1 is using a tool, it would emit <|eom_id|> instead of <|eot_id|>, however, that new token is still missing in Ollama's config: https://ollama.com/library/llama3.1/blobs/56bb8bd477a5

I guess it's not related to your problem, but it shows that more improvements will be needed.

**Comment by rick-github** [comment]
Q8 also worked fine for me, intel + nvidia rtx4070 with 12G VRAM.

**Comment by sam2332** [comment]
the Q8 loads and does not constantly spam out text for me as well

**Comment by rick-github** [comment]
Tried Q4_0, Q4_1, Q4_K_S, Q4_K_M, Q8, FP16, all returned expected results.

**Comment by Qualzz** [comment]
> Tried Q4_0, Q4_1, Q4_K_S, Q4_K_M, Q8, FP16, all returned expected results.

Did you tried anything with longer context windows ? for exemple 32k ? The more the context is, the less the model is coherent.

**Comment by rick-github** [comment]
I did a needle-in-a-haystack for various window lengths up to 32k, the performance went down as the context window went up, but it never went off the rails - the answers were coherent, if not correct.

**Comment by Qualzz** [comment]
Seems like an issue was raised in llama.cpp with other people having the same kind of experience. It's weird everything work fine for you :o 

[#8650](https://github.com/ggerganov/llama.cpp/issues/8650)

**Comment by mirek190** [comment]
ollama or llamacpp works bad with llama 3.1 .... so do mot bother because is dumber than llama 3 currently

**Comment by Baughn** [comment]
It's also configured with an 8k context size. Though I thought the model was trained as 128k?

**Comment by ouening** [comment]
I got bad response using llama3.1(Q4_0)：
![image](https://github.com/user-attachments/assets/7d637895-00de-4646-9014-11b4f7c30392)

**Comment by kiradzS** [comment]
> I got bad response using llama3.1(Q4_0)： ![image](https://private-user-images.githubusercontent.com/15122811/351562992-7d637895-00de-4646-9014-11b4f7c30392.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE4MTQ3NTgsIm5iZiI6MTcyMTgxNDQ1OCwicGF0aCI6Ii8xNTEyMjgxMS8zNTE1NjI5OTItN2Q2Mzc4OTUtMDBkZS00NjQ2LTkwMTQtMTFiNGY3YzMwMzkyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI0VDA5NDczOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNhZDBlYTgxMzIwZWU4YWRmYmYwOThmYjQ1Zjc5ODI3MjVkN2JjODczMTg2Y2FjMWEzM2Y2MTI2YjZjNjJlNjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4QQgY-1E40-GEW88aRkj_6KJF6abicnMzs6cV5xcLgM)

It doesn't support Chinese, only a few languages on the page, you have to translate it into English and send it to it first to get better results.
But I feel it's not much better than 3. I tried Q8 and tested it on various projects and it didn't work as well as glm4

**Comment by MeinDeutschkurs** [comment]
Up to 4096 Tokens, everything seems to be fine. I tried to get a summary on 70.000 input (expected output about 4000 tokens) and I got jibberish:

Something like:
`I ...., was .... !+ //a ... like I go 1 547wtr ... never...`

In comparison to the "gradient" version, no meaning at all. (The gradient version did the summary, but was not able to end the summary - it hallucinated it further, till the context window was completely used)

**Comment by zakcali** [comment]
llama3.1:8b-instruct-fp16 can-not answer that question correctly: 
A dead cat is placed into a box along with a nuclear isotope, a vial of poison and a radiation detector. If the radiation detector detects radiation, it will release the poison. The box is opened one day later. What is the probability of the cat being alive?

**Comment by nonetrix** [comment]
Llama 3.1 8B at even Q8 or Q4 seems much worse than on Groq, on Groq it is like same ball park as model like Gemma 27B if not better but on Ollama it is like one of worst 8B models I have tried. 70B seems better, but I think it's still slightly better on Groq

**Comment by pdevine** [comment]
I'm going to go ahead and close this since llama3.1 is working correctly.
