### ISSUE TITLE
Sometimes the model (or ollama) returns nothing - model: llama 3.1 8B

### ISSUE THREAD

**Issue by llagerlof** [ollama/ollama#5883]
### What is the issue?

In a simple conversation, 50/40% of the time it returns nothing. I just run the model normally:

`ollama run llama3.1`

And after a successful start, I make some random questions. Sometimes it responds. Some times it returns empty.

This is not happening with llama3 8B model.

My NVIDIA has 12GB and the PC has 32GB.

### OS

Linux

### GPU

Nvidia

### CPU

Intel

### Ollama version

0.2.5

**Comment by taozhiyuai** [comment]
it is ok for me on MAC. m3 max 128GB

**Comment by llagerlof** [comment]
I updated to ollama 0.2.7. Now it's working fine.
