### ISSUE TITLE
Assistant doesn't continue from its last message on 0.2.8

### ISSUE THREAD

**Issue by josegtmonteiro** [ollama/ollama#5890]
### What is the issue?

@jmorganca , thanks for the quick fix on the https://github.com/ollama/ollama/issues/5775

However, testing here with 0.2.8. Still not able to continue the message.

With the same example I mentioned before, using the OLLAMA_DEBUG I'm able to see the final prompt on the console, it is:

prompt="<|start_header_id|>system<|end_header_id|>\n\nYou are a helpful assistant.<|eot_id|><|start_header_id|>user<|end_header_id|>\n\nHello, how are you today?<|eot_id|><|start_header_id|>assistant<|end_header_id|>\n\nThanks for asking! I'm <|eot_id|><|start_header_id|>assistant<|end_header_id|>\n\n"

The messages I'm passing to the chat endpoint are:
history = [ {"role": "system", "content": 'You are a helpful assistant.'}, {"role": "user", "content": "Hello, how are you today?"}, {"role": "assistant", "content": "Thanks for asking! I'm "}, ]

Not sure it has any difference, but I'm testing with "llama3-groq-tool-use:8b-q8_0" model. Was the fix just made for some specific model? or it should be applied to all of them?

Please let me know if more info/tests needed from my side. 

### OS

Windows

### GPU

Nvidia

### CPU

Intel

### Ollama version

0.2.8

**Comment by jmorganca** [comment]
Hi @josegtmonteiro thanks for the issue!

It might be the model, here's an example with llama 3

```
curl http://localhost:11434/api/chat -d '{
    "model": "llama3",
    "messages": [
      {
        "role": "system",
        "content": "You are a helpful assistant."
      },
      {
        "role": "user",
        "content": "Hello, how are you today?"
      },
      {
        "role": "assistant",
        "content": "Thanks for asking! I am "
      }
    ], "stream": false
  }' | jq .message.content
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   918  100   577  100   341    464    274  0:00:01  0:00:01 --:--:--   739
"100% functioning properly and ready to help with any questions or tasks you may have. It's great to chat with you! Is there something specific on your mind that you'd like to discuss, or do you need assistance with a particular topic or problem? I'm all ears (or in this case, all text)!"
```

I will double check on the model and update its template if required

**Comment by jmorganca** [comment]
May I ask how you're using the API, AFAIK there is no `history` field in the API, so it could be the tool you're using to call the Ollama API. Happy to help dig in more

**Comment by josegtmonteiro** [comment]
Sorry for that @jmorganca, I'm calling ollama API from a python function, `history` was just the name of the varible I'm passing to the function. 

Here is a test with curl to make it easier:

0.2.1:
`curl http://localhost:11434/api/chat -d "{\"model\":\"llama3-groq-tool-use:8b-q8_0\",\"messages\":[{\"role\":\"system\",\"content\":\"You are a helpful assistant.\"},{\"role\":\"user\",\"content\":\"Hello, how are you today?\"},{\"role\":\"assistant\",\"content\":\"Thanks for asking! I am \"}],\"stream\":false}"`

`{"model":"llama3-groq-tool-use:8b-q8_0","created_at":"2024-07-23T21:20:51.2802235Z","message":{"role":"assistant","content":"100% here to help with any questions or tasks you have. What do you need assistance with today?"},"done_reason":"stop","done":true,"total_duration":2204791900,"load_duration":15954000,"prompt_eval_count":36,"prompt_eval_duration":549710000,"eval_count":22,"eval_duration":1636985000}`

0.2.8:
`curl http://localhost:11434/api/chat -d "{\"model\":\"llama3-groq-tool-use:8b-q8_0\",\"messages\":[{\"role\":\"system\",\"content\":\"You are a helpful assistant.\"},{\"role\":\"user\",\"content\":\"Hello, how are you today?\"},{\"role\":\"assistant\",\"content\":\"Thanks for asking! I am \"}],\"stream\":false}"
`
`{"model":"llama3-groq-tool-use:8b-q8_0","created_at":"2024-07-23T21:24:08.1458456Z","message":{"role":"assistant","content":"What can I assist you with today?"},"done_reason":"stop","done":true,"total_duration":17892179100,"load_duration":16749627300,"prompt_eval_count":40,"prompt_eval_duration":459699000,"eval_count":9,"eval_duration":670384000}`

**Comment by josegtmonteiro** [comment]
Another example here with `llama3.1:8b-instruct-q8_0`, have the same issue. 

`curl http://localhost:11434/api/chat -d "{\"model\":\"llama3.1:8b-instruct-q8_0\",\"messages\":[{\"role\":\"system\",\"content\":\"You are a helpful assistant.\"},{\"role\":\"user\",\"content\":\"Hello, how are you today?\"},{\"role\":\"assistant\",\"content\":\"Thanks for asking! I am \"}],\"stream\":false}"
`

`{"model":"llama3.1:8b-instruct-q8_0","created_at":"2024-07-23T21:32:34.0023863Z","message":{"role":"assistant","content":"I'm just a language model, so I don't have feelings or emotions like humans do, but I'm functioning properly and ready to help with any questions or tasks you may have. How can I assist you today?"},"done_reason":"stop","done":true,"total_duration":11222101900,"load_duration":6797393300,"prompt_eval_count":50,"prompt_eval_duration":382119000,"eval_count":45,"eval_duration":4038738000}`

**Comment by jmorganca** [comment]
Thanks! @josegtmonteiro. Are you sure you're running Ollama 0.2.8? Would it be possible to run `ollama -v`

**Comment by jmorganca** [comment]
Here's what I get from that prompt, for example:

```
% curl http://localhost:11434/api/chat -d "{\"model\":\"llama3.1:8b-instruct-q8_0\",\"messages\":[{\"role\":\"system\",\"content\":\"You are a helpful assistant.\"},{\"role\":\"user\",\"content\":\"Hello, how are you today?\"},{\"role\":\"assistant\",\"content\":\"Thanks for asking! I am \"}],\"stream\":false}"
{"model":"llama3.1:8b-instruct-q8_0","created_at":"2024-07-23T22:47:08.077302Z","message":{"role":"assistant","content":"100% digital, so I don't have feelings like humans do, but I'm functioning properly and ready to help with any questions or tasks you may have! How about you? How's your day going so far?"},"done_reason":"stop","done":true,"total_duration":2066221042,"load_duration":788808833,"prompt_eval_count":34,"prompt_eval_duration":113163000,"eval_count":45,"eval_duration":1157882000
```

**Comment by josegtmonteiro** [comment]
@jmorganca , in fact I was on 0.2.8-rc1. 

However, look at this:

**0.2.8-rc1 test:**


`curl http://localhost:11434/api/chat -d "{\"model\":\"llama3.1:8b-instruct-q8_0\",\"messages\":[{\"role\":\"system\",\"content\":\"You are a helpful assistant.\"},{\"role\":\"user\",\"content\":\"Hello, how are you today?\"},{\"role\":\"assistant\",\"content\":\"Thanks for asking! I am \"}],\"stream\":false}"`

`{"model":"llama3.1:8b-instruct-q8_0","created_at":"2024-07-23T23:39:38.9715264Z","message":{"role":"assistant","content":"doing well, thanks for checking in! How about you, is there anything I can help with or would you like to chat?"},"done_reason":"stop","done":true,"total_duration":12370306400,"load_duration":9781381000,"prompt_eval_count":50,"prompt_eval_duration":305007000,"eval_count":27,"eval_duration":2269103000}`

`ollama -v`
ollama version is 0.2.8-rc1

`curl http://localhost:11434/api/chat -d "{\"model\":\"llama3-groq-tool-use:8b-q8_0\",\"messages\":[{\"role\":\"system\",\"content\":\"You are a helpful assistant.\"},{\"role\":\"user\",\"content\":\"Hello, how are you today?\"},{\"role\":\"assistant\",\"content\":\"Thanks for asking! I am \"}],\"stream\":false}"`

`{"model":"llama3-groq-tool-use:8b-q8_0","created_at":"2024-07-23T23:40:27.0570595Z","message":{"role":"assistant","content":"doing well and here to help you with anything you need. How can I assist you today?"},"done_reason":"stop","done":true,"total_duration":9054546600,"load_duration":7113248600,"prompt_eval_count":40,"prompt_eval_duration":270677000,"eval_count":20,"eval_duration":1657589000}`

`ollama -v`
ollama version is 0.2.8-rc1

**Updated to 0.2.8**

`ollama -v`
ollama version is 0.2.8

`curl http://localhost:11434/api/chat -d "{\"model\":\"llama3.1:8b-instruct-q8_0\",\"messages\":[{\"role\":\"system\",\"content\":\"You are a helpful assistant.\"},{\"role\":\"user\",\"content\":\"Hello, how are you today?\"},{\"role\":\"assistant\",\"content\":\"Thanks for asking! I am \"}],\"stream\":false}"
`

`{"model":"llama3.1:8b-instruct-q8_0","created_at":"2024-07-23T23:42:14.5390654Z","message":{"role":"assistant","content":"I'm functioning properly and ready to assist you with any questions or tasks you may have. How about you? How's your day going so far?"},"done_reason":"stop","done":true,"total_duration":12412734900,"load_duration":9339561300,"prompt_eval_count":50,"prompt_eval_duration":371648000,"eval_count":31,"eval_duration":2694835000}`
_______________________

`curl http://localhost:11434/api/chat -d "{\"model\":\"llama3-groq-tool-use:8b-q8_0\",\"messages\":[{\"role\":\"system\",\"content\":\"You are a helpful assistant.\"},{\"role\":\"user\",\"content\":\"Hello, how are you today?\"},{\"role\":\"assistant\",\"content\":\"Thanks for asking! I am \"}],\"stream\":false}"`

`{"model":"llama3-groq-tool-use:8b-q8_0","created_at":"2024-07-23T23:42:36.5827607Z","message":{"role":"assistant","content":"Great! What can I assist you with today?"},"done_reason":"stop","done":true,"total_duration":8349428700,"load_duration":7211502800,"prompt_eval_count":40,"prompt_eval_duration":267179000,"eval_count":11,"eval_duration":865629000}`

So, started to repeat the same request to see if something changes:

`curl http://localhost:11434/api/chat -d "{\"model\":\"llama3-groq-tool-use:8b-q8_0\",\"messages\":[{\"role\":\"system\",\"content\":\"You are a helpful assistant.\"},{\"role\":\"user\",\"content\":\"Hello, how are you today?\"},{\"role\":\"assistant\",\"content\":\"Thanks for asking! I am \"}],\"stream\":false}"`

`
{"model":"llama3-groq-tool-use:8b-q8_0","created_at":"2024-07-23T23:47:19.8793515Z","message":{"role":"assistant","content":"I'm here to help with any questions or tasks you have. What's on your mind today?"},"done_reason":"stop","done":true,"total_duration":2478095500,"load_duration":16654200,"prompt_eval_count":40,"prompt_eval_duration":454376000,"eval_count":21,"eval_duration":2005076000}`
_______________________

`curl http://localhost:11434/api/chat -d "{\"model\":\"llama3-groq-tool-use:8b-q8_0\",\"messages\":[{\"role\":\"system\",\"content\":\"You are a helpful assistant.\"},{\"role\":\"user\",\"content\":\"Hello, how are you today?\"},{\"role\":\"assistant\",\"content\":\"Thanks for asking! I am \"}],\"stream\":false}"`

`{"model":"llama3-groq-tool-use:8b-q8_0","created_at":"2024-07-23T23:47:30.7754623Z","message":{"role":"assistant","content":"Doing well, thanks. How can I assist you today?"},"done_reason":"stop","done":true,"total_duration":1656656700,"load_duration":22224900,"prompt_eval_count":40,"prompt_eval_duration":341294000,"eval_count":13,"eval_duration":1290546000}`
_______________________

`curl http://localhost:11434/api/chat -d "{\"model\":\"llama3-groq-tool-use:8b-q8_0\",\"messages\":[{\"role\":\"system\",\"content\":\"You are a helpful assistant.\"},{\"role\":\"user\",\"content\":\"Hello, how are you today?\"},{\"role\":\"assistant\",\"content\":\"Thanks for asking! I am \"}],\"stream\":false}"`

`{"model":"llama3-groq-tool-use:8b-q8_0","created_at":"2024-07-23T23:47:35.2650314Z","message":{"role":"assistant","content":"Do you need any help with something specific today?"},"done_reason":"stop","done":true,"total_duration":1140066400,"load_duration":12952200,"prompt_eval_count":40,"prompt_eval_duration":119064000,"eval_count":11,"eval_duration":1004321000}`

_______________________

`curl http://localhost:11434/api/chat -d "{\"model\":\"llama3-groq-tool-use:8b-q8_0\",\"messages\":[{\"role\":\"system\",\"content\":\"You are a helpful assistant.\"},{\"role\":\"user\",\"content\":\"Hello, how are you today?\"},{\"role\":\"assistant\",\"content\":\"Thanks for asking! I am \"}],\"stream\":false}"`

`{"model":"llama3-groq-tool-use:8b-q8_0","created_at":"2024-07-23T23:47:40.6509125Z","message":{"role":"assistant","content":"doing well and here to help. How can I assist you today?"},"done_reason":"stop","done":true,"total_duration":1574673700,"load_duration":12541900,"prompt_eval_count":40,"prompt_eval_duration":202849000,"eval_count":15,"eval_duration":1356576000}`

**Comment by jmorganca** [comment]
Hi there, the templates for `llama3.1` and `llama3-groq-tool-use` have been fixed. Sorry this happened!

To repull them:

```
ollama pull llama3.1
ollama pull llama3-groq-tool-use
```

And this should work. Thanks for the issue!
