### ISSUE TITLE
please add https://huggingface.co/meta-llama/Meta-Llama-3.1-8B-Instruct to https://ollama.com/library

### ISSUE THREAD

**Issue by Orgoth** [ollama/ollama#5903]
please add https://huggingface.co/meta-llama/Meta-Llama-3.1-8B-Instruct to https://ollama.com/library

**Comment by ronneldavis** [comment]
I believe its already added and available at https://ollama.com/library/llama3.1

**Comment by Orgoth** [comment]
These are two different trained models.

This model was trained for Chat conversations: https://huggingface.co/meta-llama/Meta-Llama-3.1-8B
This model was trained for Instruction based interactions: https://huggingface.co/meta-llama/Meta-Llama-3.1-8B-Instruct

**Comment by Orgoth** [comment]
Sorry you are right, found it within the models details. :)
https://ollama.com/library/llama3.1/blobs/87048bcd5521

> general.name Meta Llama 3.1 8B Instruct
