### ISSUE TITLE
Forcing Ollama to bind to 0.0.0.0 instead of localhost

### ISSUE THREAD

**Issue by MrLinks75** [ollama/ollama#5905]
Hi everyone,
Hope you're doing great.

The request would be to force ollama to  bind automatically to 0.0.0.0 to allow it to interface with tools / instances inside a docker container.

At the moment the only feasible option I've figured was to add 
`Environment="OLLAMA_HOST=0.0.0.0"`
into the `ollama.service` file, and this is required to be done after every update.

Would it be possible to implement that feature ? Or even have it bind on both 0.0.0.0 and localhost on deployment?

**Comment by AncientMystic** [comment]
Personally i just use the manual install instructions to update the binary by itself when I don't want to update all of ollama, that doesn't overwrite the service 

I think you can also set the service file to read only, but haven't done that.

**Comment by rick-github** [comment]
```sh
sudo mkdir -p /etc/systemd/system/ollama.service.d/
printf '[Service]\nEnvironment="OLLAMA_HOST=0.0.0.0"\n' | sudo tee /etc/systemd/system/ollama.service.d/override.conf
```

**Comment by jpummill** [comment]
You could also add the now common "--listen" option to connect Ollama to 0.0.0.0 instead of localhost.

**Comment by jmorganca** [comment]
@rick-github's comment is spot-on. You can create an override file that will continue to work even when re-running the installer script. Ollama isn't exposed on 0.0.0.0 by default, but the Docker image does (simply exposing/mapping port 11434 for the `ollama/ollama` Docker image should work)

**Comment by viniciusgati** [comment]
> You could also add the now common "--listen" option to connect Ollama to 0.0.0.0 instead of localhost.

no success trying this option

**Comment by rick-github** [comment]
`--listen` is not a valid option for ollama.  Add `OLLAMA_HOST=0.0.0.0` to the [service configuration](https://github.com/ollama/ollama/blob/main/docs/faq.md#how-do-i-configure-ollama-server).
