### ISSUE TITLE
Ollama serve hangs on openai completions request

### ISSUE THREAD

**Issue by ikamensh** [ollama/ollama#5910]
### What is the issue?

I was processing files locally in a loop, and at some point process just stopped moving forward. I had to do keyboard interrupt. In the terminal, this gave this entry, at the end of the log below. In the terminal running python query source, on termination I've seen it hanged in sock.receive() call.

[GIN] 2024/07/24 - 14:25:35 | 200 |  2.729474292s |       127.0.0.1 | POST     "/v1/chat/completions"
[GIN] 2024/07/24 - 14:25:36 | 200 |   1.86225825s |       127.0.0.1 | POST     "/v1/chat/completions"
[GIN] 2024/07/24 - 14:25:40 | 200 |      3.38871s |       127.0.0.1 | POST     "/v1/chat/completions"
[GIN] 2024/07/24 - 14:25:45 | 200 |    4.8193825s |       127.0.0.1 | POST     "/v1/chat/completions"
[GIN] 2024/07/24 - 14:25:47 | 200 |    2.7770215s |       127.0.0.1 | POST     "/v1/chat/completions"

[GIN] 2024/07/24 - 14:31:02 | 500 |         5m14s |       127.0.0.1 | POST     "/v1/chat/completions"
time=2024-07-24T14:33:00.048+02:00 level=INFO source=memory.go:309 msg="o

### OS

macOS

### GPU

AMD

### CPU

Apple

### Ollama version

0.1.48

**Comment by jmorganca** [comment]
@ikamensh do you have the remaining logs after `time=2024-07-24T14:33:00.048+02:00 level=INFO source=memory.go:309 msg="o`? This would help us debug 😊

**Comment by ikamensh** [comment]
Is there some log file locally? I didn't notice I've missed something in copy paste. If it reoccurs I could paste more

**Comment by royjhan** [comment]
@ikamensh https://github.com/ollama/ollama/blob/main/docs/troubleshooting.md

**Comment by ikamensh** [comment]
server.log surprisingly has the oldest and latest entries but not from the date this happened. It has some stuff from when I just installed ollama (June) and late July 28-30. if it reoccurs I will post whats in the logs.

**Comment by jmorganca** [comment]
@ikamensh is this still happening? If so let me know and I can re-open. Version 0.1.48 is quite old – I'd recommend upgrading and then let us know if the issue still persists and I can re-open this.
