### ISSUE TITLE
Simplify model loading via model numbering

### ISSUE THREAD

**Issue by jpummill** [ollama/ollama#5916]
Model names can be very long and somewhat cryptic.

For example, I may have the following models on my system for testing:
mistral-nemo:12b-instruct-2407-q3_K_S
mistral-nemo:12b-instruct-2407-q4_K_S
mistral-nemo:12b-instruct-2407-q5_K_M

I think it would be helpful to see a numbered list of model names when using the load command from within the Ollama interface.  For example, if I type "/load mi", instead of seeing "Error: model 'mi' not found", I would instead see the following:
1:  mistral-nemo:12b-instruct-2407-q3_K_S
2:  mistral-nemo:12b-instruct-2407-q4_K_S
3:  mistral-nemo:12b-instruct-2407-q5_K_M

At this point the "/load" prompt would be waiting for me to either type out the model name or just select the number of the model from the list, allowing us to avoid typing out long complex names with lots of hyphens (-) and underscores (_).

You could still have the existing functionality with the error message if no downloaded models match the search filter.

**Comment by jmorganca** [comment]
Hi there, see @rick-github's suggestion here: https://github.com/ollama/ollama/issues/5380#issuecomment-2198365573

**Comment by jmorganca** [comment]
(Thanks @rick-github!)
