### ISSUE TITLE
Integrate LM Format Enforcer

### ISSUE THREAD

**Issue by mjspeck** [ollama/ollama#5917]
It would be really powerful to be able to integrate [LM Formate Enforcer](https://github.com/noamgat/lm-format-enforcer) with Ollama. It already supports llama.cpp as well.

**Comment by xucian** [comment]
what's the stance on this? lm format enforcer claims it beats the Outlines lib, so that's a big deal

**Comment by ParthSareen** [comment]
Closing this out for now with our structured outputs PR - already digging into some constrained decoding work - will check this out and keep in mind! Thank you!

**Comment by mjspeck** [comment]
> Closing this out for now with our structured outputs PR - already digging into some constrained decoding work - will check this out and keep in mind! Thank you!

Is that [this PR](https://github.com/ollama/ollama/pull/7939)?

**Comment by ParthSareen** [comment]
> > Closing this out for now with our structured outputs PR - already digging into some constrained decoding work - will check this out and keep in mind! Thank you!
> 
> 
> 
> Is that [this PR](https://github.com/ollama/ollama/pull/7939)?

Oops forgot to tag it #7900
