### ISSUE TITLE
Llama3.1 70b-instruct-q4_1 buggy

### ISSUE THREAD

**Issue by velaia** [ollama/ollama#5918]
### What is the issue?

When I run the **70b-instruct-q4_1** version of Llama3.1 ollama gives a buggy reply:

My sample request:

> ➜  ollama-tests curl http://localhost:11434/api/chat -d '{
    "model": "llama3.1:70b-instruct-q4_1",
    "messages": [
      {
        "role": "system",
        "content": "You are a helpful assistant."
      },
      {
        "role": "user",
        "content": "Tell me about the top 3 commercial industrial computer vision products on the market."
      }
    ], "stream": false
  }'

The model's response

> {
    "model": "llama3.1:70b-instruct-q4_1",
    "created_at": "2024-07-24T15:45:23.026538Z",
    "message": {
        "role": "assistant",
        "content": "assistant\nassistantassistantassistant"
    },
    "done_reason": "stop",
    "done": true,
    "total_duration": 56814340833,
    "load_duration": 53209095791,
    "prompt_eval_count": 37,
    "prompt_eval_duration": 2107466000,
    "eval_count": 6,
    "eval_duration": 1493717000
}`

The same request generates a proper response using **llama3.1:8b-instruct-q8_0**.

### OS

macOS

### GPU

Apple

### CPU

Apple

### Ollama version

0.2.8

**Comment by rick-github** [comment]
Logs may help in the diagnosis of the issue.

**Comment by rick-github** [comment]
Re-pulled the model, no improvement.

```
$ curl -s localhost:11434/api/chat -d '{ "model": "llama3.1:70b-instruct-q4_1", "messages": [ { "role": "system", "content": "You are a helpful assistant." }, { "role": "user
", "content": "Tell me about the top 3 commercial industrial computer vision products on the market." } ], "stream": false }' | jq .message
{
  "role": "assistant",
  "content": "assistantassistant"
}
```

**Comment by velaia** [comment]
Same here. I had to 'rm' it and re-download. Even using a custom Modelfile with adjusted TEMPLATE didn't work for me.

**Comment by rick-github** [comment]
Deleted, pulled, no change.

**Comment by rick-github** [comment]
Installed ollama:0.2.8 on a different machine, never had ollama on it before.

```
$ ollama run llama3.1:70b-instruct-q4_1
pulling manifest 
pulling 3177e205cbbb... 100% ▕██████████████████████████████████▏  44 GB                         
pulling 8cf247399e57... 100% ▕██████████████████████████████████▏ 1.7 KB                         
pulling f1cd752815fc... 100% ▕██████████████████████████████████▏  12 KB                         
pulling 56bb8bd477a5... 100% ▕██████████████████████████████████▏   96 B                         
pulling eaa5bd3ca6da... 100% ▕██████████████████████████████████▏  560 B                         
verifying sha256 digest 
writing manifest 
removing any unused layers 
success 
>>> hello
##assistant

>>> Send a message (/? for help)
```

Just doesn't like me, I guess.

**Comment by Jsin01** [comment]
Same

**Comment by pdevine** [comment]
I ended up rebuilding the q4_1 weights and still ran into issues. In talking with the Llama team, the model is really sensitive to certain quantizations, although they didn't give guidelines for which quantizations work best w/ 8b or 70b, but only for 405b.

I think the best case here is we just remove q4_1 since it's unlikely it's going to be able to work.

**Comment by pdevine** [comment]
We ended up removing the quantization. I think there was probably an issue also w/ the kv cache. There are some changes coming to improve kv cache performance and I'm wondering if that might at least fix the `assistant` issue. Regardless, this quantization level isn't super great.

I'll go ahead and close out the issue as something we won't fix.

cc @jessegross

**Comment by jessegross** [comment]
The KV changes are really just around speed so I think they are unlikely to have an impact on this unless there was another bug that I'm not aware of that happened to get fixed at the same time. I think quantization is more likely the issue.
