### ISSUE TITLE
Second Disk

### ISSUE THREAD

**Issue by wioniqle-q** [ollama/ollama#5930]
### What is the issue?

I have a second disc that have large capacity but when try the I install ollama.exe (for windows) that install models directly USERS/USERNAME/.ollama installing

but I don't have any space on my C drive. So That I need to run for a on my second disc that I can download models into second disc and download the models to the second disc

### OS

Windows

### GPU

Nvidia

### CPU

Intel

### Ollama version

latest

**Comment by rick-github** [comment]
Set `OLLAMA_MODELS` to the directory you want to save the models, eg `D:\ollama`.  See [here](https://github.com/ollama/ollama/blob/main/docs/faq.md#setting-environment-variables-on-windows) for information on how to change Windows environment variables.

**Comment by wioniqle-q** [comment]
thanks
