### ISSUE TITLE
ollama网页端聊天数据

### ISSUE THREAD

**Issue by mywwq** [ollama/ollama#5936]
ollama网页端聊天数据请问默认存在哪里，浏览器缓存还是什么默认路径

**Comment by handsomejustin** [comment]
你需要把你历史的聊天内容写道history中，让大模型知道你历史交流什么，而不是存放在哪里。
比如:
messages = [{'role': 'user', 'content': message}]
其中{'role': 'user', 'content': message}这个部分历史记录，你可以 messages.append 到列表中，成为历史数据。

**Comment by handsomejustin** [comment]
> 好的 其实我想知道的是，windows端用的open wenbui，当我退出了网页之后，网页上的聊天记录是在哪存的，浏览器缓存、某个文件还是log日志当中，因为第二次打开网页是有历史记录的
> […](#)
> ---- 回复的原邮件 ---- 发件人 Justin ***@***.***> 日期 2024年07月25日 13:02 收件人 ***@***.***> 抄送至 wenqi ***@***.***>***@***.***> 主题 Re: [ollama/ollama] ollama网页端聊天数据 (Issue #5936) 你需要把你历史的聊天内容写道history中，让大模型知道你历史交流什么，而不是存放在哪里。 比如: messages = [{'role': 'user', 'content': message}] 其中{'role': 'user', 'content': message}这个部分历史记录，你可以 messages.append 到列表中，成为历史数据。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***>
这种暂存的方式有很多，数据量小的话，用html5的localstorage 保存，数据量大的话，可以用redis或者memcache之类。

**Comment by dhiltgen** [comment]
Ollama is a client-server architecture.  The server does not cache or store historical chat messages.  The CLI client does keep history in `$HOME/.ollama/history` unless you set OLLAMA_NOHISTORY in the environment for the client.  When you use another client, like a web client, it is interacting with the server only, so how history is stored is defined by that client, not Ollama.
