### ISSUE TITLE
Error: could not connect to ollama app, is it running?

### ISSUE THREAD

**Issue by wwjCMP** [ollama/ollama#5938]
### What is the issue?

Environment="OLLAMA_MODELS=/home/try/ollama/models"

After changing the Environment OLLAMA_MODELS, ollamal can not connect. If i cancel it, ollama can run again. What is the reason?

### OS

Linux

### GPU

Nvidia

### CPU

Intel

### Ollama version

0.2.8

**Comment by DanielPradoPino** [comment]
Hi!
Not sure if this will solve your issue but Ollama works with environment variables, if you changed your host or you models location for the service you would need to change also the environment variables that point to them.
For Host try:
`export OLLAMA_HOST=0.0.0.0:12345` This will set your Ollama Host Env Var to this url (0.0.0.0) and this port (12345), change for yours accordingly
For models folder try:
`export OLLAMA_MODELS=/home/try/ollama/models` This will set your Ollama Models Env Var to this folder

I hope this helps you.

**Comment by rick-github** [comment]
Does the directory exist?

**Comment by wwjCMP** [comment]
> Does the directory exist?

Yes, it exists.

**Comment by rick-github** [comment]
What does `journalctl _SYSTEMD_UNIT=ollama.service` show?

**Comment by wwjCMP** [comment]
> What does `journalctl _SYSTEMD_UNIT=ollama.service` show?

(base) try@master:~/ollama/models$ journalctl _SYSTEMD_UNIT=ollama.service
5月 07 06:59:38 master ollama[176672]: [GIN] 2024/05/07 - 06:59:38 | 200 |      57.489µs |       127.0.0.1 | HEAD     "/"
5月 07 06:59:38 master ollama[176672]: [GIN] 2024/05/07 - 06:59:38 | 200 |     3.24324ms |       127.0.0.1 | POST     "/api/create"
5月 07 07:00:15 master ollama[176672]: [GIN] 2024/05/07 - 07:00:15 | 204 |      69.657µs |   192.168.101.5 | OPTIONS  "/api/chat"
5月 07 07:00:15 master ollama[176672]: time=2024-05-07T07:00:15.526+08:00 level=INFO source=gpu.go:96 msg="Detecting GPUs"
5月 07 07:00:15 master ollama[176672]: time=2024-05-07T07:00:15.533+08:00 level=INFO source=cpu_common.go:11 msg="CPU has AVX2"
5月 07 07:00:16 master ollama[176672]: time=2024-05-07T07:00:16.100+08:00 level=WARN source=server.go:76 msg="requested context length is greater than the model's training>
5月 07 07:00:16 master ollama[176672]: time=2024-05-07T07:00:16.100+08:00 level=INFO source=cpu_common.go:11 msg="CPU has AVX2"
5月 07 07:00:16 master ollama[176672]: time=2024-05-07T07:00:16.100+08:00 level=INFO source=server.go:289 msg="starting llama server" cmd="/tmp/ollama3115653840/runners/cp>
5月 07 07:00:16 master ollama[176672]: time=2024-05-07T07:00:16.101+08:00 level=INFO source=sched.go:340 msg="loaded runners" count=1
5月 07 07:00:16 master ollama[176672]: time=2024-05-07T07:00:16.101+08:00 level=INFO source=server.go:432 msg="waiting for llama runner to start responding"
5月 07 07:00:16 master ollama[557245]: {"function":"server_params_parse","level":"INFO","line":2606,"msg":"logging to file is disabled.","tid":"128922130913152","timestamp>
5月 07 07:00:16 master ollama[557245]: {"build":1,"commit":"952d03d","function":"main","level":"INFO","line":2822,"msg":"build info","tid":"128922130913152","timestamp":17>
5月 07 07:00:16 master ollama[557245]: {"function":"main","level":"INFO","line":2825,"msg":"system info","n_threads":48,"n_threads_batch":-1,"system_info":"AVX = 1 | AVX_V>
5月 07 07:00:16 master ollama[176672]: llama_model_loader: loaded meta data with 22 key-value pairs and 543 tensors from /usr/share/ollama/.ollama/models/blobs/sha256-243d>
5月 07 07:00:16 master ollama[176672]: llama_model_loader: Dumping metadata keys/values. Note: KV overrides do not apply in this output.
5月 07 07:00:16 master ollama[176672]: llama_model_loader: - kv   0:                       general.architecture str              = llama
5月 07 07:00:16 master ollama[176672]: llama_model_loader: - kv   1:                               general.name str              = LLaMA v2
5月 07 07:00:16 master ollama[176672]: llama_model_loader: - kv   2:                       llama.context_length u32              = 4096
5月 07 07:00:16 master ollama[176672]: llama_model_loader: - kv   3:                     llama.embedding_length u32              = 7168
5月 07 07:00:16 master ollama[176672]: llama_model_loader: - kv   4:                          llama.block_count u32              = 60
5月 07 07:00:16 master ollama[176672]: llama_model_loader: - kv   5:                  llama.feed_forward_length u32              = 20480
5月 07 07:00:16 master ollama[176672]: llama_model_loader: - kv   6:                 llama.rope.dimension_count u32              = 128
5月 07 07:00:16 master ollama[176672]: llama_model_loader: - kv   7:                 llama.attention.head_count u32              = 56
5月 07 07:00:16 master ollama[176672]: llama_model_loader: - kv   8:              llama.attention.head_count_kv u32              = 8
5月 07 07:00:16 master ollama[176672]: llama_model_loader: - kv   9:     llama.attention.layer_norm_rms_epsilon f32              = 0.000010
5月 07 07:00:16 master ollama[176672]: llama_model_loader: - kv  10:                       llama.rope.freq_base f32              = 5000000.000000
5月 07 07:00:16 master ollama[176672]: llama_model_loader: - kv  11:                          general.file_type u32              = 18
5月 07 07:00:16 master ollama[176672]: llama_model_loader: - kv  12:                       tokenizer.ggml.model str              = llama
5月 07 07:00:16 master ollama[176672]: llama_model_loader: - kv  13:                      tokenizer.ggml.tokens arr[str,64000]   = ["<unk>", "<|startoftext|>", "<|endof...
5月 07 07:00:16 master ollama[176672]: llama_model_loader: - kv  14:                      tokenizer.ggml.scores arr[f32,64000]   = [0.000000, 0.000000, 0.000000, 0.0000...
5月 07 07:00:16 master ollama[176672]: llama_model_loader: - kv  15:                  tokenizer.ggml.token_type arr[i32,64000]   = [2, 3, 3, 3, 3, 3, 1, 1, 1, 3, 3, 3, ...
5月 07 07:00:16 master ollama[176672]: llama_model_loader: - kv  16:                tokenizer.ggml.bos_token_id u32              = 1
5月 07 07:00:16 master ollama[176672]: llama_model_loader: - kv  17:                tokenizer.ggml.eos_token_id u32              = 2
5月 07 07:00:16 master ollama[176672]: llama_model_loader: - kv  18:               tokenizer.ggml.add_bos_token bool             = false
5月 07 07:00:16 master ollama[176672]: llama_model_loader: - kv  19:               tokenizer.ggml.add_eos_token bool             = false
lines 1-35

**Comment by wwjCMP** [comment]
> What does `journalctl _SYSTEMD_UNIT=ollama.service` show when you have `OLLAMA_MODELS=/home/try/ollama/models`?

root@master:/home/try# ollama list
Error: could not connect to ollama app, is it running?
root@master:/home/try# ollama list
Error: could not connect to ollama app, is it running?
root@master:/home/try# journalctl _SYSTEMD_UNIT=ollama.service
5月 07 06:59:38 master ollama[176672]: [GIN] 2024/05/07 - 06:59:38 | 200 |      57.489µs |       127.0.0.1 | HEAD     "/"
5月 07 06:59:38 master ollama[176672]: [GIN] 2024/05/07 - 06:59:38 | 200 |     3.24324ms |       127.0.0.1 | POST     "/api/create"
5月 07 07:00:15 master ollama[176672]: [GIN] 2024/05/07 - 07:00:15 | 204 |      69.657µs |   192.168.101.5 | OPTIONS  "/api/chat"
5月 07 07:00:15 master ollama[176672]: time=2024-05-07T07:00:15.526+08:00 level=INFO source=gpu.go:96 msg="Detecting GPUs"
5月 07 07:00:15 master ollama[176672]: time=2024-05-07T07:00:15.533+08:00 level=INFO source=cpu_common.go:11 msg="CPU has AVX2"
5月 07 07:00:16 master ollama[176672]: time=2024-05-07T07:00:16.100+08:00 level=WARN source=server.go:76 msg="requested context length is greater than the model's training context window s>
5月 07 07:00:16 master ollama[176672]: time=2024-05-07T07:00:16.100+08:00 level=INFO source=cpu_common.go:11 msg="CPU has AVX2"
5月 07 07:00:16 master ollama[176672]: time=2024-05-07T07:00:16.100+08:00 level=INFO source=server.go:289 msg="starting llama server" cmd="/tmp/ollama3115653840/runners/cpu_avx2/ollama_lla>
5月 07 07:00:16 master ollama[176672]: time=2024-05-07T07:00:16.101+08:00 level=INFO source=sched.go:340 msg="loaded runners" count=1
5月 07 07:00:16 master ollama[176672]: time=2024-05-07T07:00:16.101+08:00 level=INFO source=server.go:432 msg="waiting for llama runner to start responding"
5月 07 07:00:16 master ollama[557245]: {"function":"server_params_parse","level":"INFO","line":2606,"msg":"logging to file is disabled.","tid":"128922130913152","timestamp":1715036416}
5月 07 07:00:16 master ollama[557245]: {"build":1,"commit":"952d03d","function":"main","level":"INFO","line":2822,"msg":"build info","tid":"128922130913152","timestamp":1715036416}
5月 07 07:00:16 master ollama[557245]: {"function":"main","level":"INFO","line":2825,"msg":"system info","n_threads":48,"n_threads_batch":-1,"system_info":"AVX = 1 | AVX_VNNI = 0 | AVX2 = >
5月 07 07:00:16 master ollama[176672]: llama_model_loader: loaded meta data with 22 key-value pairs and 543 tensors from /usr/share/ollama/.ollama/models/blobs/sha256-243d4aa931101d4765566>
5月 07 07:00:16 master ollama[176672]: llama_model_loader: Dumping metadata keys/values. Note: KV overrides do not apply in this output.
5月 07 07:00:16 master ollama[176672]: llama_model_loader: - kv   0:                       general.architecture str              = llama
5月 07 07:00:16 master ollama[176672]: llama_model_loader: - kv   1:                               general.name str              = LLaMA v2
5月 07 07:00:16 master ollama[176672]: llama_model_loader: - kv   2:                       llama.context_length u32              = 4096
5月 07 07:00:16 master ollama[176672]: llama_model_loader: - kv   3:                     llama.embedding_length u32              = 7168
5月 07 07:00:16 master ollama[176672]: llama_model_loader: - kv   4:                          llama.block_count u32              = 60
5月 07 07:00:16 master ollama[176672]: llama_model_loader: - kv   5:                  llama.feed_forward_length u32              = 20480
5月 07 07:00:16 master ollama[176672]: llama_model_loader: - kv   6:                 llama.rope.dimension_count u32              = 128
5月 07 07:00:16 master ollama[176672]: llama_model_loader: - kv   7:                 llama.attention.head_count u32              = 56
5月 07 07:00:16 master ollama[176672]: llama_model_loader: - kv   8:              llama.attention.head_count_kv u32              = 8
5月 07 07:00:16 master ollama[176672]: llama_model_loader: - kv   9:     llama.attention.layer_norm_rms_epsilon f32              = 0.000010
5月 07 07:00:16 master ollama[176672]: llama_model_loader: - kv  10:                       llama.rope.freq_base f32              = 5000000.000000
5月 07 07:00:16 master ollama[176672]: llama_model_loader: - kv  11:                          general.file_type u32              = 18
5月 07 07:00:16 master ollama[176672]: llama_model_loader: - kv  12:                       tokenizer.ggml.model str              = llama
5月 07 07:00:16 master ollama[176672]: llama_model_loader: - kv  13:                      tokenizer.ggml.tokens arr[str,64000]   = ["<unk>", "<|startoftext|>", "<|endof...
5月 07 07:00:16 master ollama[176672]: llama_model_loader: - kv  14:                      tokenizer.ggml.scores arr[f32,64000]   = [0.000000, 0.000000, 0.000000, 0.0000...
5月 07 07:00:16 master ollama[176672]: llama_model_loader: - kv  15:                  tokenizer.ggml.token_type arr[i32,64000]   = [2, 3, 3, 3, 3, 3, 1, 1, 1, 3, 3, 3, ...
5月 07 07:00:16 master ollama[176672]: llama_model_loader: - kv  16:                tokenizer.ggml.bos_token_id u32              = 1
5月 07 07:00:16 master ollama[176672]: llama_model_loader: - kv  17:                tokenizer.ggml.eos_token_id u32              = 2
5月 07 07:00:16 master ollama[176672]: llama_model_loader: - kv  18:               tokenizer.ggml.add_bos_token bool             = false
5月 07 07:00:16 master ollama[176672]: llama_model_loader: - kv  19:               tokenizer.ggml.add_eos_token bool             = false
5月 07 07:00:16 master ollama[176672]: llama_model_loader: - kv  20:                    tokenizer.chat_template str              = {% if not add_generation_prompt is de...
5月 07 07:00:16 master ollama[176672]: llama_model_loader: - kv  21:               general.quantization_version u32              = 2
5月 07 07:00:16 master ollama[176672]: llama_model_loader: - type  f32:  121 tensors
5月 07 07:00:16 master ollama[176672]: llama_model_loader: - type q6_K:  422 tensors

**Comment by zhubx007** [comment]
I think you can run command with "export OLLAMA_HOST=0.0.0.0:11434" then run command "ollama list".

**Comment by wwjCMP** [comment]
> I think you can run command with "export OLLAMA_HOST=0.0.0.0:11434" then run command "ollama list".

It dosen't work.

**Comment by rick-github** [comment]
The logs you posted are just the few at the start, we need to see logs from when the failure happens.

**Comment by wwjCMP** [comment]
> journalctl _SYSTEMD_UNIT=ollama.service

7月 26 18:32:56 master ollama[293353]: Error: mkdir /home/try/ollama: permission denied
7月 26 18:32:56 master ollama[293353]: 2024/07/26 18:32:56 routes.go:1100: INFO server config env="map[CUDA_VISIBLE_DEVICES: GPU_DEVICE_ORDINAL: HIP_VISIBLE_DEVICES: HSA_OVERRIDE_GFX_VERSI>
7月 26 18:32:53 master ollama[293344]: Error: mkdir /home/try/ollama: permission denied
7月 26 18:32:53 master ollama[293344]: 2024/07/26 18:32:53 routes.go:1100: INFO server config env="map[CUDA_VISIBLE_DEVICES: GPU_DEVICE_ORDINAL: HIP_VISIBLE_DEVICES: HSA_OVERRIDE_GFX_VERSI>
7月 26 18:32:50 master ollama[293334]: Error: mkdir /home/try/ollama: permission denied
7月 26 18:32:50 master ollama[293334]: 2024/07/26 18:32:50 routes.go:1100: INFO server config env="map[CUDA_VISIBLE_DEVICES: GPU_DEVICE_ORDINAL: HIP_VISIBLE_DEVICES: HSA_OVERRIDE_GFX_VERSI>
7月 26 18:32:47 master ollama[293325]: Error: mkdir /home/try/ollama: permission denied
7月 26 18:32:47 master ollama[293325]: 2024/07/26 18:32:47 routes.go:1100: INFO server config env="map[CUDA_VISIBLE_DEVICES: GPU_DEVICE_ORDINAL: HIP_VISIBLE_DEVICES: HSA_OVERRIDE_GFX_VERSI>
7月 26 18:32:43 master ollama[293315]: Error: mkdir /home/try/ollama: permission denied
7月 26 18:32:43 master ollama[293315]: 2024/07/26 18:32:43 routes.go:1100: INFO server config env="map[CUDA_VISIBLE_DEVICES: GPU_DEVICE_ORDINAL: HIP_VISIBLE_DEVICES: HSA_OVERRIDE_GFX_VERSI>
7月 26 18:32:40 master ollama[293306]: Error: mkdir /home/try/ollama: permission denied
7月 26 18:32:40 master ollama[293306]: 2024/07/26 18:32:40 routes.go:1100: INFO server config env="map[CUDA_VISIBLE_DEVICES: GPU_DEVICE_ORDINAL: HIP_VISIBLE_DEVICES: HSA_OVERRIDE_GFX_VERSI>
7月 26 18:32:37 master ollama[293297]: Error: mkdir /home/try/ollama: permission denied
7月 26 18:32:37 master ollama[293297]: 2024/07/26 18:32:37 routes.go:1100: INFO server config env="map[CUDA_VISIBLE_DEVICES: GPU_DEVICE_ORDINAL: HIP_VISIBLE_DEVICES: HSA_OVERRIDE_GFX_VERSI>
7月 26 18:32:34 master ollama[293287]: Error: mkdir /home/try/ollama: permission denied
7月 26 18:32:34 master ollama[293287]: 2024/07/26 18:32:34 routes.go:1100: INFO server config env="map[CUDA_VISIBLE_DEVICES: GPU_DEVICE_ORDINAL: HIP_VISIBLE_DEVICES: HSA_OVERRIDE_GFX_VERSI>
7月 26 18:32:30 master ollama[293277]: Error: mkdir /home/try/ollama: permission denied
7月 26 18:32:30 master ollama[293277]: 2024/07/26 18:32:30 routes.go:1100: INFO server config env="map[CUDA_VISIBLE_DEVICES: GPU_DEVICE_ORDINAL: HIP_VISIBLE_DEVICES: HSA_OVERRIDE_GFX_VERSI>
7月 26 18:32:27 master ollama[293268]: Error: mkdir /home/try/ollama: permission denied
7月 26 18:32:27 master ollama[293268]: 2024/07/26 18:32:27 routes.go:1100: INFO server config env="map[CUDA_VISIBLE_DEVICES: GPU_DEVICE_ORDINAL: HIP_VISIBLE_DEVICES: HSA_OVERRIDE_GFX_VERSI>
7月 26 18:32:24 master ollama[293259]: Error: mkdir /home/try/ollama: permission denied
7月 26 18:32:24 master ollama[293259]: 2024/07/26 18:32:24 routes.go:1100: INFO server config env="map[CUDA_VISIBLE_DEVICES: GPU_DEVICE_ORDINAL: HIP_VISIBLE_DEVICES: HSA_OVERRIDE_GFX_VERSI>
7月 26 18:32:21 master ollama[293249]: Error: mkdir /home/try/ollama: permission denied
7月 26 18:32:21 master ollama[293249]: 2024/07/26 18:32:21 routes.go:1100: INFO server config env="map[CUDA_VISIBLE_DEVICES: GPU_DEVICE_ORDINAL: HIP_VISIBLE_DEVICES: HSA_OVERRIDE_GFX_VERSI>
7月 26 18:32:17 master ollama[293239]: Error: mkdir /home/try/ollama: permission denied
7月 26 18:32:17 master ollama[293239]: 2024/07/26 18:32:17 routes.go:1100: INFO server config env="map[CUDA_VISIBLE_DEVICES: GPU_DEVICE_ORDINAL: HIP_VISIBLE_DEVICES: HSA_OVERRIDE_GFX_VERSI>
7月 26 18:32:14 master ollama[293230]: Error: mkdir /home/try/ollama: permission denied
7月 26 18:32:14 master ollama[293230]: 2024/07/26 18:32:14 routes.go:1100: INFO server config env="map[CUDA_VISIBLE_DEVICES: GPU_DEVICE_ORDINAL: HIP_VISIBLE_DEVICES: HSA_OVERRIDE_GFX_VERSI>
7月 26 18:32:11 master ollama[293219]: Error: mkdir /home/try/ollama: permission denied
7月 26 18:32:11 master ollama[293219]: 2024/07/26 18:32:11 routes.go:1100: INFO server config env="map[CUDA_VISIBLE_DEVICES: GPU_DEVICE_ORDINAL: HIP_VISIBLE_DEVICES: HSA_OVERRIDE_GFX_VERSI>
7月 26 18:32:08 master ollama[293209]: Error: mkdir /home/try/ollama: permission denied
7月 26 18:32:08 master ollama[293209]: 2024/07/26 18:32:08 routes.go:1100: INFO server config env="map[CUDA_VISIBLE_DEVICES: GPU_DEVICE_ORDINAL: HIP_VISIBLE_DEVICES: HSA_OVERRIDE_GFX_VERSI>
7月 26 18:32:04 master ollama[293200]: Error: mkdir /home/try/ollama: permission denied
7月 26 18:32:04 master ollama[293200]: 2024/07/26 18:32:04 routes.go:1100: INFO server config env="map[CUDA_VISIBLE_DEVICES: GPU_DEVICE_ORDINAL: HIP_VISIBLE_DEVICES: HSA_OVERRIDE_GFX_VERSI>
7月 26 18:32:01 master ollama[293191]: Error: mkdir /home/try/ollama: permission denied
7月 26 18:32:01 master ollama[293191]: 2024/07/26 18:32:01 routes.go:1100: INFO server config env="map[CUDA_VISIBLE_DEVICES: GPU_DEVICE_ORDINAL: HIP_VISIBLE_DEVICES: HSA_OVERRIDE_GFX_VERSI>
7月 26 18:31:58 master ollama[293181]: Error: mkdir /home/try/ollama: permission denied
7月 26 18:31:58 master ollama[293181]: 2024/07/26 18:31:58 routes.go:1100: INFO server config env="map[CUDA_VISIBLE_DEVICES: GPU_DEVICE_ORDINAL: HIP_VISIBLE_DEVICES: HSA_OVERRIDE_GFX_VERSI

**Comment by rick-github** [comment]
```
7月 26 18:31:58 master ollama[293181]: Error: mkdir /home/try/ollama: permission denied
```
`/home/try/` has a permission setting that doesn't allow ollama to make it's directory.  Change the permissions:

```
chmod 777 /home/try
```

**Comment by wwjCMP** [comment]
> It dosen't work.

It dose work. Thanks.
