### ISSUE TITLE
My model reports an error when running：Error: llama runner process has terminated: error loading model: unable to allocate backend buffer

### ISSUE THREAD

**Issue by luyoulingoi** [ollama/ollama#5941]
Error: llama runner process has terminated: error loading model: unable to allocate backend buffer
This is my computer configuration
CPU:i5-12500H
mem:32Gb
disk:512Gb+512Gb
graphics card:RTX 3050Ti 4Gb
can u tell me reason?

**Comment by dhiltgen** [comment]
If you're still having trouble, please upgrade to the latest version, and if that doesn't clear it up, please share the server logs and what model you were trying to load and I'll reopen the issue.
