### ISSUE TITLE
Error: pull model manifest: Get "https://registry.ollama.ai/v2/library/llama3.1/manifests/latest": net/http: TLS handshake timeout

### ISSUE THREAD

**Issue by kid1milli** [ollama/ollama#5943]
### What is the issue?

when I deploy llama3.1 on ollma on Windows, the system displays Error: pull model manifest: Get "https://registry.ollama.ai/v2/library/llama3.1/manifests/latest": net/http: TLS handshake timeout

### OS

Windows

### GPU

AMD

### CPU

AMD

**Comment by zbschat** [comment]
> 确保您的网络连接工作正常，并且没有被防火墙或其他安全软件阻止。您可以尝试在浏览器中打开 https://registry.ollama.ai 以确认它是否可访问。

好像并非网络的问题，浏览器是可以正常访问访网页的，有人说是跟运营商的网络限制有关，不过目前测试的是3大运营商都出现了一样的问题，也可能是地区的问题，一些电脑第一次运行的时候可以正常下载一点，但是等待一会儿就会出现同样的问题

**Comment by zbschat** [comment]
提供一种解决方式：浏览器访问"https://registry.ollama.ai/v2/library/llama3.1/manifests/latest"这个网址，将网址的内容下载另存为“latest”文件，文件保存位置“C:\Users\Admin\.ollama\models\manifests\registry.ollama.ai\library\llama3.1\latest”； 然后根据这个文件中的sha文件名称分别修改网址，使用浏览器下载大模型的文件，下载网址如“https://registry.ollama.ai/v2/library/llama3.1/blobs/sha256:87048bcd55216712ef14c11c2c303728463207b165bf18440b9b84b07ec00f87"  下载好的文件修改成对应的文件名称就行”sha256-87048bcd55216712ef14c11c2c303728463207b165bf18440b9b84b07ec00f87“  这些文件保存在”C:\Users\Admin\.ollama\models\blobs“这个路径下。

**Comment by eust-w** [comment]
> 提供一种解决方式：浏览器访问"[https://registry.ollama.ai/v2/library/llama3.1/manifests/latest"这个网址，将网址的内容下载另存为“latest”文件，文件保存位置“C:\Users\Admin\.ollama\models\manifests\registry.ollama.ai\library\llama3.1\latest”；](https://registry.ollama.ai/v2/library/llama3.1/manifests/latest%22%E8%BF%99%E4%B8%AA%E7%BD%91%E5%9D%80%EF%BC%8C%E5%B0%86%E7%BD%91%E5%9D%80%E7%9A%84%E5%86%85%E5%AE%B9%E4%B8%8B%E8%BD%BD%E5%8F%A6%E5%AD%98%E4%B8%BA%E2%80%9Clatest%E2%80%9D%E6%96%87%E4%BB%B6%EF%BC%8C%E6%96%87%E4%BB%B6%E4%BF%9D%E5%AD%98%E4%BD%8D%E7%BD%AE%E2%80%9CC:%5CUsers%5CAdmin%5C.ollama%5Cmodels%5Cmanifests%5Cregistry.ollama.ai%5Clibrary%5Cllama3.1%5Clatest%E2%80%9D%EF%BC%9B) 然后根据这个文件中的sha文件名称分别修改网址，使用浏览器下载大模型的文件，下载网址如“https://registry.ollama.ai/v2/library/llama3.1/blobs/sha256:87048bcd55216712ef14c11c2c303728463207b165bf18440b9b84b07ec00f87" 下载好的文件修改成对应的文件名称就行”sha256-87048bcd55216712ef14c11c2c303728463207b165bf18440b9b84b07ec00f87“ 这些文件保存在”C:\Users\Admin.ollama\models\blobs“这个路径下。

浏览器可以访问的话，说明你的terminal可能无法访问，检查是否走了代理以及TLS设置是否正确

**Comment by pdevine** [comment]
I'm going to close this as a dupe of 3786

**Comment by Muusa1617** [comment]
> 提供一种解决方式：浏览器访问"[https://registry.ollama.ai/v2/library/llama3.1/manifests/latest"这个网址，将网址的内容下载另存为“latest”文件，文件保存位置“C:\Users\Admin\.ollama\models\manifests\registry.ollama.ai\library\llama3.1\latest”；](https://registry.ollama.ai/v2/library/llama3.1/manifests/latest%22%E8%BF%99%E4%B8%AA%E7%BD%91%E5%9D%80%EF%BC%8C%E5%B0%86%E7%BD%91%E5%9D%80%E7%9A%84%E5%86%85%E5%AE%B9%E4%B8%8B%E8%BD%BD%E5%8F%A6%E5%AD%98%E4%B8%BA%E2%80%9Clatest%E2%80%9D%E6%96%87%E4%BB%B6%EF%BC%8C%E6%96%87%E4%BB%B6%E4%BF%9D%E5%AD%98%E4%BD%8D%E7%BD%AE%E2%80%9CC:%5CUsers%5CAdmin%5C.ollama%5Cmodels%5Cmanifests%5Cregistry.ollama.ai%5Clibrary%5Cllama3.1%5Clatest%E2%80%9D%EF%BC%9B) 然后根据这个文件中的sha文件名称分别修改网址，使用浏览器下载大模型的文件，下载网址如“https://registry.ollama.ai/v2/library/llama3.1/blobs/sha256:87048bcd55216712ef14c11c2c303728463207b165bf18440b9b84b07ec00f87" 下载好的文件修改成对应的文件名称就行”sha256-87048bcd55216712ef14c11c2c303728463207b165bf18440b9b84b07ec00f87“ 这些文件保存在”C:\Users\Admin.ollama\models\blobs“这个路径下。

小哥，我在使用这个方法之后，执行Olama List并不能读取到相关模型，而且它会自行清空文件夹，这个后续应该如何操作才能使用呢
