### ISSUE TITLE
Model request for Llama Guard 3

### ISSUE THREAD

**Issue by prane-eth** [ollama/ollama#5955]
Llama Guard 3 is a model for AI Safety. It is released along with Llama 3.1.
https://llama.meta.com/docs/model-cards-and-prompt-formats/llama-guard-3/
https://huggingface.co/meta-llama/Llama-Guard-3-8B
https://github.com/meta-llama/PurpleLlama/blob/main/Llama-Guard3/MODEL_CARD.md

**Comment by notasquid1938** [comment]
This would be very helpful to add, the only currently available guard models are uploaded by community members and several of them are not labeled with a version which makes it difficult to know which of the 3 releases you are getting.

**Comment by jmorganca** [comment]
Thanks for the issue! Will work on this – closing for https://github.com/ollama/ollama/issues/1894
