### ISSUE TITLE
Llama 3.1 base models for text completion

### ISSUE THREAD

**Issue by kaetemi** [ollama/ollama#5957]
Currently only the instruct models appear to be in the library, the text completion models would be appreciated too. Thanks! :)

**Comment by d-kleine** [comment]
@kaetemi @sala91 @alexOarga @gwillen @chigkim
Llama 3.1 text completion models are now available:
https://ollama.com/library/llama3.1

**Comment by chigkim** [comment]
Thanks, but can we also have for 405b as well? There are only 405b quants for instruct.

**Comment by d-kleine** [comment]
https://github.com/ollama/ollama/issues/6060#issuecomment-2271938799

**Comment by d-kleine** [comment]
Just saw 405b text generation models are being added too, might take some more hours because the files are quite large to be uploaded

**Comment by d-kleine** [comment]
Oh wow 😓 

@igorschlum Would it be possible to update the Llama 3.1 405b models (both `text` and `instruct`are affected) in Ollama again?

**Comment by chigkim** [comment]
Arthur Zucker: "The recent update to Llama checkpoints is from a good catch by @vllm_project, allows ~20% memory reduction because the 16 heads were already 8 heads copied 2 times. When you compute attention you expand (shared mem) to 32. Now it’s 8x4 instead of 16x2."

https://x.com/art_zucker/status/1822243183889105368

**Comment by d-kleine** [comment]
#6303

**Comment by igorschlum** [comment]
@d-kleine Llama3.1:405b is in the process of being updated on the [library](https://ollama.com/library/llama3.1/tags) page. I don’t know who is responsible for updating the models on the Ollama team, as I’m just a user of Ollama, like you.

@kaetemi As this issue has been addressed, could you please close it so we can focus on other issues to solve?

**Comment by kaetemi** [comment]
Seems to be resolved now.
