### ISSUE TITLE
Ollama is running but can't acces it from OpenWebUI

### ISSUE THREAD

**Issue by ns-bcr** [ollama/ollama#5959]
### What is the issue?

Hey,
So, I am having a problem, I have Ollama runnig on ubuntu-server 24.04 LTS.
It works properly locally but from my computer I can't acces it, like from it, I can run : `ollama run llama2` and it works.
I can also try to make this command from the server : `curl localhost:11434` and it will say "Ollama is running"
But from my computer when I go to 192.168.1.145:11434 I get nothing. And if i try to run `curl 192.168.1.145:11434` I get "curl: (7) Failed to connect to 192.168.1.145 port 80 after 0 ms: Couldn't connect to server"

I tried multiple thing : 
- I tried opening the port on TCP
- I tried looking in the LOGS but nothing wrong
- I also tried reinstalling it from zero.

I can provide more information if necessary.
Thx.

### OS

Linux

### GPU

Intel

### CPU

Intel

### Ollama version

0.2.8

**Comment by rick-github** [comment]
Add `OLLAMA_HOST=0.0.0.0:11434` to the server environment and restart.

**Comment by ns-bcr** [comment]
I tried but now its still weird... If I try to do curl 192.168.1.145:11434 on the server it works, but if I try from my computer on the browser, I still get nothing. Same thing on OpenWebUI. I tried disabling the firewall but nothing changed.

**Comment by rick-github** [comment]
On the server, what does `sudo netstat -pant | grep :11434` show?

**Comment by ns-bcr** [comment]
it shows this: 
![image](https://github.com/user-attachments/assets/c514f152-240a-4a54-a717-cb9fbb7ab437)

**Comment by rick-github** [comment]
ollama has the right port binding.  I started a vserver and installed ubuntu-24.04-live-server-amd64 on it, installed ollama, made the adjustment to OLLAMA_HOST, and was able to get "Ollama is running" from a different machine.  So there's either a firewall on your server, a firewall on your local computer, or some other network kit between the two that is blocking the connection.

What do you see if you run the following on your server: `sudo tcpdump -i any dst port 11434 or src host <ip-of-your-local-machine>` and then do `curl <ip-or-name-of-server>:11434` on your local machine?

**Comment by ns-bcr** [comment]
Its going even worst. When I type sudo tcpdump -i any dst port 11434 or src host <ip-of-your-local-machine> its start listing port in loop. and now curl doesn't even work anymore? Like I doesn't get any awnsers at all? for curl localhost:11434 or 192.168.1.145:11434 or even 127.0.0.1:11434, nothing.
I am gonna try to reinstall from zero another machine and see if anything changed.

**Comment by rick-github** [comment]
Try it without 'or src host xx'

**Comment by rick-github** [comment]
or better: `sudo tcpdump -i any \( dst port 11434 or src host <ip-of-your-local-machine>\) and not port 22`

**Comment by ns-bcr** [comment]
Still same, it start listing in loop ports

**Comment by rick-github** [comment]
OK, `sudo tcpdump -i any dst port 11434 or src port 11434`.

**Comment by ns-bcr** [comment]
Nothing changed

**Comment by rick-github** [comment]
`sudo tcpdump -i any dst port 11434 or src port 11434` prints lots of output?  are you pulling a model?

**Comment by ns-bcr** [comment]
I am a bit lost actully rn, I'll try tomorrow.

**Comment by ns-bcr** [comment]
Ok so I wen't running another machine with ollama and still doesn't work. Weird.

**Comment by ns-bcr** [comment]
And now for `sudo netstat -pant | grep :11434` I get : tcp        0      0 127.0.0.1:11434         0.0.0.0:*               LISTEN      2564/ollama

**Comment by ns-bcr** [comment]
Ok so I found out, I can't acces it somewhere else than my server so I made OpenWebUI be on the server have the localhost ip and port and not it works.
Thanks for your help!

**Comment by rice818** [comment]
> Ok so I found out, I can't acces it somewhere else than my server so I made OpenWebUI be on the server have the localhost ip and port and not it works. Thanks for your help!

may I know how to "made OpenWebUI be on the server have the localhost ip and port"?

**Comment by rick-github** [comment]
He installed open-webui on the same machine on which ollama was running, and configured open-webu to connect to `http://127.0.0.1:11434`.

**Comment by ClaireRovic** [comment]
This worked for me, from https://github.com/ollama/ollama/blob/main/docs/faq.md. Using sudo ss -tulnp | grep 11434 it showed ollama was only listening on port 127.0.0.1.

Setting environment variables on Linux
If Ollama is run as a systemd service, environment variables should be set using systemctl:

Edit the systemd service by calling **systemctl edit ollama.service**. This will open an editor.

For each environment variable, add a line Environment under section [Service]: THIS NEEDS TO BE CREATED NEAR THE TOP

[Service]
Environment="OLLAMA_HOST=0.0.0.0:11434"

Save and exit.

Reload systemd and restart Ollama:

systemctl daemon-reload
systemctl restart ollama

**Comment by glovacai** [comment]
> This worked for me, from https://github.com/ollama/ollama/blob/main/docs/faq.md. Using sudo ss -tulnp | grep 11434 it showed ollama was only listening on port 127.0.0.1.
> 
> Setting environment variables on Linux If Ollama is run as a systemd service, environment variables should be set using systemctl:
> 
> Edit the systemd service by calling **systemctl edit ollama.service**. This will open an editor.
> 
> For each environment variable, add a line Environment under section [Service]: THIS NEEDS TO BE CREATED NEAR THE TOP
> 
> [Service] Environment="OLLAMA_HOST=0.0.0.0:11434"
> 
> Save and exit.
> 
> Reload systemd and restart Ollama:
> 
> systemctl daemon-reload systemctl restart ollama

This is what fixed it for me.
