### ISSUE TITLE
Would it be possible to save chat history into season data? 

### ISSUE THREAD

**Issue by mcDandy** [ollama/ollama#5961]
I was creating a story with AI but ollama crashed shortly after I saved seassion. Due to the fact I have only 12GB VRAM each token is taking forever (20s) using gemma2_27B (GPU barely utilised becouse of massive amounts of data being moved between RAM and VRAM). It would help me if I could just saved seasion with tokens sent between me and AI and could turn off Laptop for the night. File containing the season only contains settings. Only thing I found was `{"mediaType":"application/vnd.ollama.image.messages","digest":"sha256:f15e8d427ebb0dbab95d18481f910d293b1b1544aece22aceeff822063ce29e5","size":26616}` which do not contain messages or point to file which contain it. AI behaves as if the previous parts were not there and the prompt was new beginning. The story simply does not continue.

Laptop: MSI Vector GP68HX 13VH

**Comment by mcDandy** [comment]
Controlled result:

Without pasting prompt
```
>>> Who is Stella?
Please give me more context! "Stella" is a common name.

To help me figure out who you mean, tell me:

* **Where did you hear or read about Stella?** Was it in a
book, movie, TV show, song, or somewhere else?
* **What are...

```

With pasting last part of story (I swear I copied entirlety of it...)

```
Based on this excerpt, Stella is a young woman who has
recently discovered she possesses incredible powers over
electromagnetism.

Here are some key things we learn about her:

* **She's adventurous:**  Stella cra...
```

**Comment by rick-github** [comment]
It sounds like a simple terminal frontend would do what you need, see [Terminal](https://github.com/ollama/ollama?tab=readme-ov-file#terminal) in the integrations page.

**Comment by mcDandy** [comment]
I will check it out. I am currently using Powershell 7.4.3
