### ISSUE TITLE
Add   "Mistral large v2" , thanks

### ISSUE THREAD

**Issue by enryteam** [ollama/ollama#5966]
Mistral又重磅开源了，7月是一个适合开源的月份~。 Mistral large v2支持中文，特点是对编码和agent能力、推理能力做了很好的优化，110B模型可以与llama 3.1 405B分庭抗礼！

hf模型地址：https://huggingface.co/mistralai/Mistral-Large-Instruct-2407

试玩地址：https://chat.mistral.ai/chat/e56844bf-f6c1-46be-8f17-9072766fec10

**Comment by ycyy** [comment]
update to new version，you can get it,
