### ISSUE TITLE
llama3.1 8B losses context

### ISSUE THREAD

**Issue by Damien2s** [ollama/ollama#5969]
### What is the issue?

llama3.1 doesn't seems to remember the context. 
Here is an example:

> Me:
> Hello can you tell me how much is 56*9?
> 
> llama3.1:
> That's a simple one!
> 56 * 9 = 504
> Is that correct?
> 
> Me:
> can you divide this by 4?
> 
> llama3.1
> However, I don't see any specific numbers or values mentioned in the text that can be divided by 4.
> 
> If you're looking for a way to break up the content into smaller chunks, I could try suggesting some possible ways to reorganize it. For example:
> 
> 1. **Divide into sections**: Break down the content into distinct sections or topics, such as "Core Principles and Capabilities", "Advanced Features", "Technical Details", etc.
> 2. **Create a summary**: Extract the main points or key information from the text and create a concise summary.
> 3. **Organize by feature**: Group related features or capabilities together, such as "Content Generation", "Knowledge Base", "Reasoning Capabilities", etc.
> 
> Please let me know if any of these options sound helpful!

On the other hand, when I use the same prompt with llama3 it work perfectly.

### OS

Linux

### GPU

AMD

### CPU

AMD

### Ollama version

0.3.0

**Comment by d-kleine** [comment]
Which model settings did you use?

**Comment by FellowTraveler** [comment]
@Damien2s Can you please verify that if this problem is fixed in latest Ollama and latest Llama3.1 recently uploaded? If no, please provide model settings as well.

**Comment by Damien2s** [comment]
I just give it a try and the problem seems to be solved with the latest version of Ollama. Thanks.
