### ISSUE TITLE
run  glm4  Error: llama runner process has terminated: signal: aborted (core dumped)

### ISSUE THREAD

**Issue by x-future** [ollama/ollama#5970]
Error: llama runner process has terminated: signal: aborted (core dumped)

# ollama run glm4
pulling manifest
pulling b506a070d115... 100% ▕█████████████████████████████████████████████████████████████████████████████████████▏ 5.5 GB
pulling e7e7aebd710c... 100% ▕█████████████████████████████████████████████████████████████████████████████████████▏  137 B
pulling e4f0dc83900a... 100% ▕█████████████████████████████████████████████████████████████████████████████████████▏ 6.5 KB
pulling 4134f3eb0516... 100% ▕█████████████████████████████████████████████████████████████████████████████████████▏   81 B
pulling ca0dd08dd282... 100% ▕█████████████████████████████████████████████████████████████████████████████████████▏  489 B
verifying sha256 digest
writing manifest
removing any unused layers
success
Error: llama runner process has terminated: signal: aborted (core dumped)

system info: LSB Version:	core-11.1.0ubuntu4-noarch:security-11.1.0ubuntu4-noarch
gpu info:
<img width="760" alt="image" src="https://github.com/user-attachments/assets/accf2f79-e24b-4eb0-a094-525db8c31f96">

**Comment by rick-github** [comment]
Server logs would help with diagnosis.

**Comment by chrisbward** [comment]
also hitting this after leaving machine idle for some time - restarting the service didn't help, machine was not awoken from a sleep state

**Comment by rick-github** [comment]
Server logs would help with diagnosis.

**Comment by chrisbward** [comment]
how would I go about obtaining those? Is there a dedicated log just for ollama?

also to note, my issue arises when I run `ollama run codegeex4:9b-all-fp16` but not `ollama run llama3.1:8b-instruct-fp16`

**Comment by dhiltgen** [comment]
This might be resolved by following the steps in the troublshooting guide for nvidia drivers unloading.  https://github.com/ollama/ollama/blob/main/docs/troubleshooting.md#linux-nvidia-troubleshooting

If not, please share your server logs so we can see why it ran into problems

**Comment by chrisbward** [comment]
`journalctl -u ollama` comes up empty, last log messages were from July 5th, and can confirm my drivers are loaded in fine as I can run inference on the other model / other apps

**Comment by chrisbward** [comment]
```
➜  ~ ollama -v    
ollama version is 0.1.47
```

**Comment by chrisbward** [comment]
okay, upgrading ollama has resolved this issue for myself;
```
➜  ~ ollama -v
ollama version is 0.3.0
```

**Comment by x-future** [comment]
thanks, I upgrading ollama has resolved this issue too.
~# ollama -v
ollama version is 0.3.0
