### ISSUE TITLE
Error: template: :28:7: executing "" at <.ToolCalls>: can't evaluate field ToolCalls in type *api.Message

### ISSUE THREAD

**Issue by dashan996** [ollama/ollama#5973]
### What is the issue?

After downloaded llama3.1:70b and run it, I meet this question. I have tried other models and everyone works well. I deleted it and download again, but error still appears again.

### OS

macOS

### GPU

Apple

### CPU

Apple

### Ollama version

ollama version is 0.2.2

**Comment by keesj-riscure** [comment]
Same here, on the second call it fails

![image](https://github.com/user-attachments/assets/74f66185-9ec1-4787-a273-eda9be288409)

**Comment by keesj-riscure** [comment]
After also updating the server side it is working. 

![image](https://github.com/user-attachments/assets/0a7f8f33-d855-47b7-b25f-70e2bacb11a6)

**Comment by ad1tyac0des** [comment]
hey, could you elaborate how you fixed this?

**Comment by LiuZhiXiong** [comment]
I also encountered this problem

**Comment by tsaritsar** [comment]
Try restarting the ollama server. If you're using homebrew that would be `brew services restart ollama`

**Comment by madlbx** [comment]
> hey, could you elaborate how you fixed this?

1. stop ollama service  `systemclt stop ollama`
2. 4einstall the latest version(0.3.0) of ollama based on your operating system
```
(Linux)
curl -fsSL https://ollama.com/install.sh | sh
ollama -v
ollama version is 0.3.0
```
I've solved it. Good luck

**Comment by dashan996** [comment]
It isit is strange. I retry gemma2:27, llama3:70, glm, phi3:14b and so on. Everyone is ok. I also download a llama3.1:8b and it doesn't work eithor. Seems just llama3.1 can't work . Rebooting machine doesn't work!

**Comment by shutter-cp** [comment]
llama3.1:8b
Error: template: :28:7: executing "" at <.ToolCalls>: can't evaluate field ToolCalls in type *api.Message

**Comment by LiuZhiXiong** [comment]
hi, guys～
After I restarted ollama, the problem was solved and llama3.1 can run normally.

**Comment by dashan996** [comment]
I have updated to ollama o.3 versinon , llama3.1 works wll no matter with 70B or 8B.

**Comment by hhstore** [comment]
update + restart `ollama`, fix this problem.

**Comment by jmorganca** [comment]
Hi folks sorry about this error, it happens on versions 0.2.2-0.2.5 and is fixed when updating Ollama. We'll be careful to avoid this in the future
