### ISSUE TITLE
system variable (user only) OLLAMA_MODELS is ignored Worked in 0.2.8

### ISSUE THREAD

**Issue by mcDandy** [ollama/ollama#5978]
### What is the issue?

I had custom location of ollama model in 2.8 but after 3.0 update it is ignored.

```
 ollama run gemma2:27b
pulling manifest
pulling d7e4b00a7d7a...   1% ▕                ▏ 157 MB/ 15 GB  768 KB/s   5h35m
Error: max retries exceeded: write C:\Users\danda\.ollama\models\blobs\sha256-d7e4b00a7d7a8d03d4eed9b0f3f61a427e9f0fc5dea6aeb414e41dee23dc8ecc-partial: Na disku není dost místa.
```
![image](https://github.com/user-attachments/assets/c0c74917-4758-4743-91ae-a060b9fd989a)

### OS

Windows

### GPU

Nvidia

### CPU

Intel

### Ollama version

0.3.0

**Comment by rick-github** [comment]
What did you do to update?  Did you restart ollama?

**Comment by mcDandy** [comment]
I updated 2 hours ago or so. I did not restart ollama after updating to 0.3.0 since it was restarted by installer. I restarted it 2 days ago when I set up ollama so the variable took effect (it did). No restarts or variable changes since then.

**Comment by mcDandy** [comment]
Sorry I did not understand the question. I just ran the installer since variable was setup. No additional restarts done by me.

**Comment by rick-github** [comment]
Server logs will show what `OLLAMA_MODELS` is set to, if you add some logs we can check.  If it's set to `F:\Users\danda` but the server is writing to `C:\Users\danda` then that is indeed a problem.  I have tested it locally, ollama 0.3.0 on a linux system does respect the setting of `OLLAMA_MODELS`.

**Comment by mcDandy** [comment]
I am on windows...
[server.zip](https://github.com/user-attachments/files/16392611/server.zip)

**Comment by rick-github** [comment]
```
2024/07/23 21:50:01.262+02:00 level=INFO source=routes.go:1147 msg="Listening on 127.0.0.1:11434 (version 0.2.8)"
2024/07/23 21:50:01 routes.go:1100: INFO server config env="map[ OLLAMA_MODELS:C:\\Users\\danda\\.ollama\\models OLLAMA_NOHISTORY:false 
2024/07/23 23:09:37.655+02:00 level=INFO source=routes.go:1147 msg="Listening on 127.0.0.1:11434 (version 0.2.8)"
2024/07/23 23:09:37 routes.go:1100: INFO server config env="map[ OLLAMA_MODELS:F:\\Users\\danda\\OneDrive - Univerzita Pardubice\\Dokumenty\\LLMs OLLAMA_NOHISTORY:false 
2024/07/26 11:03:09.968+02:00 level=INFO source=routes.go:1146 msg="Listening on 127.0.0.1:11434 (version 0.3.0)"
2024/07/26 11:03:09 routes.go:1099: INFO server config env="map[ OLLAMA_MODELS:C:\\Users\\danda\\.ollama\\models OLLAMA_NOHISTORY:false 
2024/07/26 11:40:19.347+02:00 level=INFO source=routes.go:1146 msg="Listening on 127.0.0.1:11434 (version 0.3.0)"
2024/07/26 11:40:19 routes.go:1099: INFO server config env="map[ OLLAMA_MODELS:F:\\Users\\danda\\OneDrive - Univerzita Pardubice\\Dokumenty\\LLMs OLLAMA_NOHISTORY:false 
```

The first time you restarted 0.3.0 at 2024/07/26 11:03:09, OLLAMA_MODELS was set to C:.  The second time at 2024/07/26 11:40:19 it is set to F:.  If you haven't restarted since, `ollama pull` should download the model to F:.  Since it alternates, I am guessing you have two different ways of updating/restarting ollama.  Which ever way it is, the one you did at 2024/07/26 11:40:19 is the better way.

**Comment by mcDandy** [comment]
I am allways updating through the installer and allways starting with `ollama run gemma2:27b`. Wierd thing is that I did nothing different from the beginning and everything was exactly the same. I just restarted PC before the last run.

**Comment by mcDandy** [comment]
Well apart of the very first run where I did not have the variable set.

**Comment by dhiltgen** [comment]
@mcDandy the simplest way to make sure things are totally set up would be a reboot, but that's not strictly necessary as long as you restart your shells and the ollama tray application.  What is probably going on is you set the environment variable, but still had a cmd or powershell terminal running with the old environment, and at some point you quit the Ollama tray application, and ran the CLI in one of those "stale" terminals, which caused Ollama to restart with the old environment.
