### ISSUE TITLE
Ollama is amazing!!

### ISSUE THREAD

**Issue by robertguss** [ollama/ollama#5982]
This really isn't an issue but I just wanted to say that everyone who works on and maintains this project is doing incredible work! Thank you so much for all of the countless hours and hard work you put into making Ollama. 

I was a little shocked to see the project has over 900 issues at the time of this writing and I just want to hopefully encourage you all. You truly are doing important work and this project means a lot to a lot of people! 

God speed.

Cheers,
Robert

**Comment by kiradzS** [comment]
That's it!

**Comment by igorschlum** [comment]
We can all try to help other users and from time to time, go back to the list of issues to see if new version of ollama fixes old issues. I learn a lot just reading the issue and trying to understand them. And yes, Ollama is a very exiting project. Each time a new major release get out, I'm impressed with the new features.

**Comment by ZX-math** [comment]
> 我们都可以尝试帮助其他用户，并不时返回问题列表，以查看新版本的ollama是否修复了旧问题。我学到了很多只是阅读问题，并试图理解它们。是的，Ollama是一个非常退出的项目。每次新的主要版本发布时，我都会对新功能印象深刻。

hi I would like to ask where I can see the updated content of ollama，thanks.

**Comment by igorschlum** [comment]
Hi @robertguss, since this place is for issues, it would be better to close this one to reduce the number of open issues on Ollama. It’s better to use X.com (Twitter) to show our enthusiasm for Ollama.

**Comment by ZX-math** [comment]
> 嗨@robertguss,由于这个地方是用于发行的，因此最好关闭这个以减少Ollama上的未发行数量。最好让我们e X.com (Twitter) 表现出我们对Ollama的热情。

To be honest, this scared me, I thought it was my post that affected the feedback speed of the question, today, my mailbox suddenly showed that someone commented under my mailbox, asking me to go to X.com, I looked carefully, he was not talking to me, but I still wonder why it was sent to my mailbox

**Comment by igorschlum** [comment]
@ZX-math, it was sent to your mailbox because you reacted to this issue, and each time, someone new react to this issue, a mail is sent to everyone as GitHub issues are for fixing issues and each one you participate receive notification of new activity.

You have on the rigth side of the window a button to Unsubscribe to this issue and you will no longer receive updates.
