### ISSUE TITLE
Tools should support streaming=true

### ISSUE THREAD

**Issue by drazdra** [ollama/ollama#5989]
When the stream=true, ollama doesn't return tool request in the final "done" message, instead it returns it just part by part as if it was a regular reply. 

At that, we have no way to determine it was a tool request, because ollama doesn't change the role to "tool" and it's just "assistant". Due to that we can not hide the tool call code from users, as we can't recognize it's a tool request and not a usual reply, until we get the final "done" message that says "done_reason='stop'". Which is also not a good way to detect that.

And in addition to that, final "done" message doesn't carry the tool request field if the stream=true, as it does when stream=false. The field is just absent.

Both of these obviously make no sense. It would make sense to:
1. In case of streaming reply there should be a special role in the message that prints a tool request, like, role='tool' or anything.
2. In any case, tools request should be presented in the final "done" message, so it could be taken from there as it can be when stream=false right now.

I would suggest the best way is to drop streaming flag internally when you return tool request, as streaming is totally unneeded here, we need to see content for users live but we do not to see function calling live as we never show it to users and we can't execute it partially.

So you just need to return the tool call in a single "done" object when the model produces a tool request. 

More lyrics: 
The reason why we can not just disable streaming for using tools is because tools are supposed to be called spontaneously during the chat, whenever _model_ decides it needs a tool and requests it. 

It means, that this process happens during a regular chat and we can not predict when the model will require a tool request.

**Comment by vertrue** [comment]
Dupe #5796 
Also PR #5915 is waiting for review

**Comment by drazdra** [comment]
> Dupe #5796 Also PR #5915 is waiting for review

does your patch make it possible to see that stream is started for tool reply, not a regular reply, so UI can know that the reply should not be shown to user?

**Comment by vertrue** [comment]
> > Dupe #5796 Also PR #5915 is waiting for review
> 
> does your patch make it possible to see that stream is started for tool reply, not a regular reply, so UI can know that the reply should not be shown to user?

Actually no, because current setup for tools in ollama generates tools instructions right to the stream
You can build my branch and check if it’s match your requirements
If not, please, update your issue so developers can see what is expected

**Comment by jmorganca** [comment]
Thanks for the issue @drazdra, will merge this with https://github.com/ollama/ollama/issues/5796 so we have the conversation in one place.
