### ISSUE TITLE
Tool calls streaming

### ISSUE THREAD

**Issue by jacob-ebey** [ollama/ollama#5993]
### What is the issue?

Looking through PR's and issues around tool calls + streaming, it seems we are overlooking that when a tool call is encountered, the body of the tool-call should be discriminated from the "chat response".

We need to be able to implement the following high level logic:
```js
for await (const chunk of response) {
  if (chunk is tool response) {
    storeAndCallToolLater(chunk);
  } else {
    showChatResponseToUser(chunk);
  }
```

I may be overlooking something, so please let me know if I am.

**Comment by jacob-ebey** [comment]
I've implemented this functionality in user-land if anyone needs it now: https://github.com/jacob-ebey/ollama-tools

**Comment by RobinBially** [comment]
There's already a fix:
https://github.com/ollama/ollama/pull/5995

**Comment by jmorganca** [comment]
Merging with https://github.com/ollama/ollama/issues/5796
