### ISSUE TITLE
Cli broken with the new tools update

### ISSUE THREAD

**Issue by anandanand84dv** [ollama/ollama#6000]
### What is the issue?

After the new tools implementation. It errors out on the second question.

```Error: template: :28:7: executing "" at <.ToolCalls>: can't evaluate field ToolCalls in type *api.Message```

![image](https://github.com/user-attachments/assets/b4b283ef-7f4e-498f-97a7-7afa71b0e32a)

### OS

Linux

### GPU

Nvidia

### CPU

Intel

### Ollama version

0.2.5

**Comment by jmorganca** [comment]
Hi @anandanand84dv sorry about this. Would it be possible to upgrade to 0.3.0? This should fix it.
