### ISSUE TITLE
Each word gets returned instead of the entire message being send

### ISSUE THREAD

**Issue by SusgUY446** [ollama/ollama#6004]
### What is the issue?

When using curl to access the api it returns each word as its own json. 

### OS

Linux

### GPU

Intel

### CPU

Intel

### Ollama version

0.3.0

**Comment by Apokalypser** [comment]
Did you try to disable streaming?

**Comment by lotusorrose** [comment]
set 
```"stream": false``` in the payload

**Comment by SusgUY446** [comment]
> set `"stream": false` in the payload

worket. thank you
