### ISSUE TITLE
Docker version of Ollama model loads slowly

### ISSUE THREAD

**Issue by billowssun** [ollama/ollama#6006]
### What is the issue?

![image](https://github.com/user-attachments/assets/7897f2a4-3a33-4fc7-9ca5-eac8b1839431)

**Comment by billowssun** [comment]
![image](https://github.com/user-attachments/assets/9c3476e1-da62-4c4e-a079-c6b04c8eb7ff)

**Comment by mxmp210** [comment]
Is docker running on WSL2 backend? If then move the model in WSL2's HDD space some where in your user folder, it's technically a VM extension and filesystem is slower due to system calls being translated between two kernels. If not please provide further information on environment, OS, system specs, GPU etc. Attach ollama log file.

**Comment by billowssun** [comment]
> Is docker running on WSL2 backend? If then move the model in WSL2's HDD space some where in your user folder, it's technically a VM extension and filesystem is slower due to system calls being translated between two kernels. If not please provide further information on environment, OS, system specs, GPU etc. Attach ollama log file.

I found the root of the problem. It's because mapping the local directory causes the large model to load slowly. If file path mapping is not used, loading materials would be very fast

**Comment by mxmp210** [comment]
Yes, it works because docker volumes load from Linux mapped filesystem, and it has no extra system call overhead. So, it's not a bug, this behaviour is expected. 

It is the technical limitation of WSL2 filesystem architecture.

**Comment by jmorganca** [comment]
Hi @billowssun, yes, while WSL2's filesystem mapping is very fast, it still may have some performance constraints that running on Windows directly may not have, including not being able to memory map chunks of the model into memory.

**Comment by dhiltgen** [comment]
I think we can close this one.  When using WSL2, I/O back to the NTFS filesystem can be slow, so using the native linux filesystem on the vhd will be much faster.

**Comment by agibson-fl** [comment]
> Is docker running on WSL2 backend? If then move the model in WSL2's HDD space some where in your user folder, it's technically a VM extension and filesystem is slower due to system calls being translated between two kernels. If not please provide further information on environment, OS, system specs, GPU etc. Attach ollama log file.

I'm having the same issue as reported in this issue. However, I'm not exactly following this guidance to get around the issue. 

I have the following volumes setup on my docker run command.
```
-v C:\Users\owner\Documents\docker\ollama\ollama:/root/.ollama `
-v C:\Users\owner\Documents\docker\ollama\data:/app/backend/data `
```
Where do I need to move the ollama and data folders? When I look under Resources in Docker Desktop, it shows WSL 2 backed and that the disk image location is in `C:\Users\owner\AppData\Local\Docker\wsl`

**Comment by mxmp210** [comment]
> Where do I need to move the ollama and data folders? Can you be more explicit?

Anything in your home folder `/home` and root directory `/` except `/mnt/<drive_letter>`  resides inside virtual disk, other devices in `/mnt` are mounted via qemu compatibility layer. That is the core reason why other paths are slower as the layer is responsible to translate Linux system calls to Windows compatible system calls. 

Use user's home directory and it will have native like performance. 

Hope that helps!

**Comment by agibson-fl** [comment]
@mxmp210 The default location for models inside the container seems to be /root/.ollama. So I setup my volume as such:
```
-v C:\Users\owner\Documents\docker\ollama\ollama:/root/.ollama `
```
However, when i remove this, I have 0 problems running the models. As a cost of making this change though, my downloaded models won't persist which is annoying since they're quite large.  I'm STILL not following what you're saying to change to fix this. Can I add back the volume but a different windows path that would be faster and allow the models to load? All your suggestions refer to Linux paths I'm presuming inside the container. Do you have an example volume mount where I can persist my models beyond destroying/recreating the container AND have the models work when loaded, for example?

**Comment by mxmp210** [comment]
> ```
> -v C:\Users\owner\Documents\docker\ollama\ollama:/root/.ollama `
> ```

This translates to `/mnt/c/Users/owner/Documents/docker/ollama/ollama:/root/.ollama`

What you need is to create an explicit volume via `docker volume create ollama_data` and then reference it like `-v ollama_data:/root/.ollama` that ensures `/root/.ollama` path resides at `/var/lib/docker/volumes/` which is the default location for the volumes managed by docker in most linux distros. This location happens to be outside `/mnt/<location>` thus gives the performance.

If you are using docker-compose :
```
services:
  ollama:
    ...
    volumes:
      - ollama_data:/root/.ollama
 
# Declare volume here - docker will create it / reference it & reuse it as long as it exists.      
volumes:
  ollama_data:
    #external: true # Only needed if volume already exists from external sources
```

Declaring volume keeps the data on disk as long as volume exists with docker. It will stay persistent unlike temporary volumes that are created on-the-go basis. 

Please read [docker volumes documentation](https://docs.docker.com/engine/storage/volumes/) for more details, if you are still having trouble understanding how docker volumes work.

**Comment by agibson-fl** [comment]
@mxmp210 I follow this. Thank you for the more clear, direct example!

**Comment by Milor123** [comment]
> > ```
> > -v C:\Users\owner\Documents\docker\ollama\ollama:/root/.ollama `
> > ```
> 
> This translates to `/mnt/c/Users/owner/Documents/docker/ollama/ollama:/root/.ollama`
> 
> What you need is to create an explicit volume via `docker volume create ollama_data` and then reference it like `-v ollama_data:/root/.ollama` that ensures `/root/.ollama` path resides at `/var/lib/docker/volumes/` which is the default location for the volumes managed by docker in most linux distros. This location happens to be outside `/mnt/<location>` thus gives the performance.
> 
> If you are using docker-compose :
> 
> ```yaml
> services:
>   ollama:
>     ...
>     volumes:
>       - ollama_data:/root/.ollama
>  
> # Declare volume here - docker will create it / reference it & reuse it as long as it exists.      
> volumes:
>   ollama_data:
>     #external: true # Only needed if volume already exists from external sources
> ```
> 
> Declaring volume keeps the data on disk as long as volume exists with docker. It will stay persistent unlike temporary volumes that are created on-the-go basis.
> 
> Please read [docker volumes documentation](https://docs.docker.com/engine/storage/volumes/) for more details, if you are still having trouble understanding how docker volumes work.

Ohh excellent, I came from linux and now I'm on windows, a lot of things have happened to me, and thanks to your comment I could understand and solve the problem.

My ollama was very slow, but since I moved all my files to the volume inside WSL then they load very fast as in linux.
Thanks guys!❤️

**Comment by gitnlsn** [comment]
Hi.

I'm running llama3:1b in ollama docker. It seems that after some idle time the next call takes longer. Why I ask? Is it docker configuration or should I run ollama without docker?

I'm not expert at docker performance.

**Comment by TafadzwaD** [comment]
> Hi.
> 
> I'm running llama3:1b in ollama docker. It seems that after some idle time the next call takes longer. Why I ask? Is it docker configuration or should I run ollama without docker?
> 
> I'm not expert at docker performance.

@gitnlsn You can specify [`OLLAMA_KEEP_ALIVE`](https://github.com/ollama/ollama/pull/3094), environment variable, when you run your ollama to stop the model from being offloaded from memory when idle. This will solve your cold start issue, the downside is that ollama ends up holding memory it is not using when idle.
