### ISSUE TITLE
Qwen2 tool calling support

### ISSUE THREAD

**Issue by jiandandema** [ollama/ollama#6007]
Please support the API tool calling capability of Qwen2. By the way, if I want to implement the API tool calling capability of Qwen2 in Ollma myself, can I make it? What shall I do?
 thank you!!!

**Comment by mmmmm21** [comment]
I also want to know that .
I downloaded Qwen/Qwen2-7B Instruction, which supports tools but cannot be used in Ollama

**Comment by jiandandema** [comment]
谢谢您给马坤发送邮件，我会及时查看的，谢谢，辛苦了

**Comment by jiandandema** [comment]
> I also want to know that . I downloaded Qwen/Qwen2-7B-Instruct , which supports tools but cannot be used in Ollama

glm4 also do not work. Maybe ollama only support llama3.1, mistral for now.

**Comment by JianxinMa** [comment]
FYI, this is the reference implementation from Qwen:
- https://github.com/QwenLM/Qwen-Agent/blob/main/qwen_agent/llm/function_calling.py#L381 

Example usages:
- https://github.com/QwenLM/Qwen-Agent/blob/main/examples/function_calling.py
- https://github.com/QwenLM/Qwen-Agent/blob/main/examples/function_calling_in_parallel.py

I'm looking into how to port Qwen's implementation to Ollama as well. Unfortunately, Ollama is written in Go, not Python. I'm not familiar with Go. So the progress is slow. If the upcoming Qwen 2.5 supports the tool-calling prompt used by LLaMA 3.1, things might be easier.

cc @JustinLin610

**Comment by jiandandema** [comment]
> FYI, this is the reference implementation from Qwen:
> 
> * https://github.com/QwenLM/Qwen-Agent/blob/main/qwen_agent/llm/function_calling.py#L381
> 
> Example usages:
> 
> * https://github.com/QwenLM/Qwen-Agent/blob/main/examples/function_calling.py
> * https://github.com/QwenLM/Qwen-Agent/blob/main/examples/function_calling_in_parallel.py
> 
> I'm looking into how to port Qwen's implementation to Ollama as well. Unfortunately, Ollama is written in Go, not Python. I'm not familiar with Go. So the progress is slow. If the upcoming Qwen 2.5 supports the tool-calling prompt used by LLaMA 3.1, things might be easier.
> 
> cc @JustinLin610

Thank you for your information! I have been searching for ways to use API tools calling for a long time, such as: fastchat, vllm. But they do not support glm4, Qwen2, etc. In my observation, many methods in Langchain require API tools calling, such as llm.bind_tools(), llm.with_structured_output(), etc. So if there is a middleware that can implement API tool calling for Chinese open source llm in the future, that would be excellent.

**Comment by jiandandema** [comment]
I have read the source code of Ollma, but since I am not very familiar with Go, I am not sure if my understanding is correct.

1. Receiving a POST request from this line of code:
```go
r.POST("/v1/chat/completions", openai.ChatMiddleware(), s.ChatHandler)
```
2. `s.GeneratedHandler` will determine whether the model has tool capability in following code:
```go
r, m, opts, err := s.scheduleRunner(c.Request.Context(), req.Model, caps, req.Options, req.KeepAlive)
```
3. `s.scheduleRunner` function first reads the corresponding prompt template file under `/usr/share/ollama/.ollama/models/Blobs/`, which code is:
```go
        mp := ParseModelPath(name)
	manifest, digest, err := GetManifest(mp)
	if err != nil {
		return nil, err
	}

	model := &Model{
		Name:      mp.GetFullTagname(),
		ShortName: mp.GetShortTagname(),
		Digest:    digest,
		Template:  template.DefaultTemplate,
	}

	filename, err := GetBlobsPath(manifest.Config.Digest)
```
4. If there is {{. tool}} in this template file, `model.CheckCapabilities(caps...)` can pass(in `s.scheduleRunner`), otherwise it will report an error
5. Assembling template files as prompt:
```go
prompt, images, err := chatPrompt(c.Request.Context(), m, r.Tokenize, opts, req.Messages, req.Tools)
```
6. llm responds based on prompt(Tools information only appear in prompt)
```go
r.Completion(c.Request.Context(), llm.CompletionRequest{
			Prompt:  prompt,
			Images:  images,
			Format:  req.Format,
			Options: opts,
		}
```

**Comment by jiandandema** [comment]
> I have read the source code of Ollma, but since I am not very familiar with Go, I am not sure if my understanding is correct.
> 
> 1. Receiving a POST request from this line of code:
> 
> ```go
> r.POST("/v1/chat/completions", openai.ChatMiddleware(), s.ChatHandler)
> ```
> 
> 2. `s.GeneratedHandler` will determine whether the model has tool capability in following code:
> 
> ```go
> r, m, opts, err := s.scheduleRunner(c.Request.Context(), req.Model, caps, req.Options, req.KeepAlive)
> ```
> 
> 3. `s.scheduleRunner` function first reads the corresponding prompt template file under `/usr/share/ollama/.ollama/models/Blobs/`, which code is:
> 
> ```go
>         mp := ParseModelPath(name)
> 	manifest, digest, err := GetManifest(mp)
> 	if err != nil {
> 		return nil, err
> 	}
> 
> 	model := &Model{
> 		Name:      mp.GetFullTagname(),
> 		ShortName: mp.GetShortTagname(),
> 		Digest:    digest,
> 		Template:  template.DefaultTemplate,
> 	}
> 
> 	filename, err := GetBlobsPath(manifest.Config.Digest)
> ```
> 
> 4. If there is {{. tool}} in this template file, `model.CheckCapabilities(caps...)` can pass(in `s.scheduleRunner`), otherwise it will report an error
> 5. Assembling template files as prompt:
> 
> ```go
> prompt, images, err := chatPrompt(c.Request.Context(), m, r.Tokenize, opts, req.Messages, req.Tools)
> ```
> 
> 6. llm responds based on prompt(Tools information only appear in prompt)
> 
> ```go
> r.Completion(c.Request.Context(), llm.CompletionRequest{
> 			Prompt:  prompt,
> 			Images:  images,
> 			Format:  req.Format,
> 			Options: opts,
> 		}
> ```

So, Is it possible for Qwen2 to implement API tool calling as long as I adapt the prompt template in /usr/share/ollama/.ollama/models/Blobs/?

**Comment by JianxinMa** [comment]
I just made a tool call template for `qwen2:7b`: https://ollama.com/majx13/test

However, the latest install.sh installs Ollama version 0.3.0 for me (which is weird), not 0.3.1 that includes the tool call functionality. Therefore, I haven't tested if the template is correct. I'm just sharing this and hope it helps.

I'll test it later once I have 0.3.1 installed.

**Comment by jiandandema** [comment]
> I just made a tool call template for `qwen2:7b`: https://ollama.com/majx13/test
> 
> However, the latest install.sh installs Ollama version 0.3.0 for me (which is weird), not 0.3.1 that includes the tool call functionality. Therefore, I haven't tested if the template is correct. I'm just sharing this and hope it helps.
> 
> I'll test it later once I have 0.3.1 installed.

@JianxinMa Firstly, thank you for your attention and work. I downloaded the test model you provided, made a request using curl and received the following response. I feel like it works.
![微信截图_20240731140832](https://github.com/user-attachments/assets/dd5d2bcf-a1e2-4168-a4df-e37f2ce52735)
However, further experiments and adaptation may be necessary.
This is the corresponding content field:
'''json
<tool_call>
{"name": "get_current_weather", "arguments": {"location": "Paris", "format": "celsius"}}
<tool_call>
```

**Comment by JianxinMa** [comment]
@jiandandema Hi, I have just updated the template at https://ollama.com/majx13/test Please make sure to `ollama pull majx13/test`. It should work now. Tested with ollama 0.3.2.

The script for testing:
```py
from openai import OpenAI
import json

model = "majx13/test"
client = OpenAI(
    base_url="http://localhost:11434/v1/",
    # required but ignored
    api_key="ollama",
)


# Example dummy function hard coded to return the same weather
# In production, this could be your backend API or an external API
def get_current_weather(location, unit="fahrenheit"):
    """Get the current weather in a given location"""
    if "tokyo" in location.lower():
        return json.dumps({"location": "Tokyo", "temperature": "10", "unit": unit})
    elif "san francisco" in location.lower():
        return json.dumps(
            {"location": "San Francisco", "temperature": "72", "unit": unit}
        )
    elif "paris" in location.lower():
        return json.dumps({"location": "Paris", "temperature": "22", "unit": unit})
    else:
        return json.dumps({"location": location, "temperature": "unknown"})


def run_conversation():
    # Step 1: send the conversation and available functions to the model
    messages = [
        {
            "role": "user",
            "content": "What's the weather like in San Francisco, Tokyo, and Paris?",
        }
    ]
    tools = [
        {
            "type": "function",
            "function": {
                "name": "get_current_weather",
                "description": "Get the current weather in a given location",
                "parameters": {
                    "type": "object",
                    "properties": {
                        "location": {
                            "type": "string",
                            "description": "The city and state, e.g. San Francisco, CA",
                        },
                        "unit": {"type": "string", "enum": ["celsius", "fahrenheit"]},
                    },
                    "required": ["location"],
                },
            },
        }
    ]
    response = client.chat.completions.create(
        model=model,
        messages=messages,
        tools=tools,
    )
    print(response)
    response_message = response.choices[0].message
    tool_calls = response_message.tool_calls
    # Step 2: check if the model wanted to call a function
    if tool_calls:
        # Step 3: call the function
        # Note: the JSON response may not always be valid; be sure to handle errors
        available_functions = {
            "get_current_weather": get_current_weather,
        }  # only one function in this example, but you can have multiple
        messages.append(response_message)  # extend conversation with assistant's reply
        # Step 4: send the info for each function call and function response to the model
        for tool_call in tool_calls:
            function_name = tool_call.function.name
            function_to_call = available_functions[function_name]
            function_args = json.loads(tool_call.function.arguments)
            print(f'Calling Function {function_name} with Argument {function_args}...')
            function_response = function_to_call(
                location=function_args.get("location"),
                unit=function_args.get("unit"),
            )
            messages.append(
                {
                    "tool_call_id": tool_call.id,
                    "role": "tool",
                    "name": function_name,
                    "content": function_response,
                }
            )  # extend conversation with function response
        second_response = client.chat.completions.create(
            model=model,
            messages=messages,
            tools=tools,
        )  # get a new response from the model where it can see the function response
        print(second_response)


run_conversation()
```
which should output:
```
ChatCompletion(id='chatcmpl-697', choices=[Choice(finish_reason='tool_calls', index=0, logprobs=None, message=ChatCompletionMessage(content='', role='assistant', function_call=None, tool_calls=[ChatCompletionMessageToolCall(id='call_kknhr1o0', function=Function(arguments='{"location":"San Francisco, CA"}', name='get_current_weather'), type='function'), ChatCompletionMessageToolCall(id='call_8cqnavtc', function=Function(arguments='{"location":"Tokyo","unit":"celsius"}', name='get_current_weather'), type='function'), ChatCompletionMessageToolCall(id='call_9jzm14a3', function=Function(arguments='{"location":"Paris, FR"}', name='get_current_weather'), type='function')]))], created=1722493532, model='majx13/test', object='chat.completion', service_tier=None, system_fingerprint='fp_ollama', usage=CompletionUsage(completion_tokens=89, prompt_tokens=200, total_tokens=289))
Calling Function get_current_weather with Argument {'location': 'San Francisco, CA'}...
Calling Function get_current_weather with Argument {'location': 'Tokyo', 'unit': 'celsius'}...
Calling Function get_current_weather with Argument {'location': 'Paris, FR'}...
ChatCompletion(id='chatcmpl-175', choices=[Choice(finish_reason='stop', index=0, logprobs=None, message=ChatCompletionMessage(content="The current weather in San Francisco is 72 degrees. In Tokyo, the temperature is 10 degrees Celsius. And in Paris, it's around 22 degrees.", role='assistant', function_call=None, tool_calls=None))], created=1722493548, model='majx13/test', object='chat.completion', service_tier=None, system_fingerprint='fp_ollama', usage=CompletionUsage(completion_tokens=37, prompt_tokens=275, total_tokens=312))
```

I will try to contact the maintainer of Qwen2 to use this template if it works for you as well.

**Comment by jiandandema** [comment]
> @jiandandema Hi, I have just updated the template at https://ollama.com/majx13/test Please make sure to `ollama pull majx13/test`. It should work now. Tested with ollama 0.3.2.
> 
> The script for testing:
> 
> ```python
> from openai import OpenAI
> import json
> 
> model = "majx13/test"
> client = OpenAI(
>     base_url="http://localhost:11434/v1/",
>     # required but ignored
>     api_key="ollama",
> )
> 
> 
> # Example dummy function hard coded to return the same weather
> # In production, this could be your backend API or an external API
> def get_current_weather(location, unit="fahrenheit"):
>     """Get the current weather in a given location"""
>     if "tokyo" in location.lower():
>         return json.dumps({"location": "Tokyo", "temperature": "10", "unit": unit})
>     elif "san francisco" in location.lower():
>         return json.dumps(
>             {"location": "San Francisco", "temperature": "72", "unit": unit}
>         )
>     elif "paris" in location.lower():
>         return json.dumps({"location": "Paris", "temperature": "22", "unit": unit})
>     else:
>         return json.dumps({"location": location, "temperature": "unknown"})
> 
> 
> def run_conversation():
>     # Step 1: send the conversation and available functions to the model
>     messages = [
>         {
>             "role": "user",
>             "content": "What's the weather like in San Francisco, Tokyo, and Paris?",
>         }
>     ]
>     tools = [
>         {
>             "type": "function",
>             "function": {
>                 "name": "get_current_weather",
>                 "description": "Get the current weather in a given location",
>                 "parameters": {
>                     "type": "object",
>                     "properties": {
>                         "location": {
>                             "type": "string",
>                             "description": "The city and state, e.g. San Francisco, CA",
>                         },
>                         "unit": {"type": "string", "enum": ["celsius", "fahrenheit"]},
>                     },
>                     "required": ["location"],
>                 },
>             },
>         }
>     ]
>     response = client.chat.completions.create(
>         model=model,
>         messages=messages,
>         tools=tools,
>     )
>     print(response)
>     response_message = response.choices[0].message
>     tool_calls = response_message.tool_calls
>     # Step 2: check if the model wanted to call a function
>     if tool_calls:
>         # Step 3: call the function
>         # Note: the JSON response may not always be valid; be sure to handle errors
>         available_functions = {
>             "get_current_weather": get_current_weather,
>         }  # only one function in this example, but you can have multiple
>         messages.append(response_message)  # extend conversation with assistant's reply
>         # Step 4: send the info for each function call and function response to the model
>         for tool_call in tool_calls:
>             function_name = tool_call.function.name
>             function_to_call = available_functions[function_name]
>             function_args = json.loads(tool_call.function.arguments)
>             print(f'Calling Function {function_name} with Argument {function_args}...')
>             function_response = function_to_call(
>                 location=function_args.get("location"),
>                 unit=function_args.get("unit"),
>             )
>             messages.append(
>                 {
>                     "tool_call_id": tool_call.id,
>                     "role": "tool",
>                     "name": function_name,
>                     "content": function_response,
>                 }
>             )  # extend conversation with function response
>         second_response = client.chat.completions.create(
>             model=model,
>             messages=messages,
>             tools=tools,
>         )  # get a new response from the model where it can see the function response
>         print(second_response)
> 
> 
> run_conversation()
> ```
> 
> which should output:
> 
> ```
> ChatCompletion(id='chatcmpl-697', choices=[Choice(finish_reason='tool_calls', index=0, logprobs=None, message=ChatCompletionMessage(content='', role='assistant', function_call=None, tool_calls=[ChatCompletionMessageToolCall(id='call_kknhr1o0', function=Function(arguments='{"location":"San Francisco, CA"}', name='get_current_weather'), type='function'), ChatCompletionMessageToolCall(id='call_8cqnavtc', function=Function(arguments='{"location":"Tokyo","unit":"celsius"}', name='get_current_weather'), type='function'), ChatCompletionMessageToolCall(id='call_9jzm14a3', function=Function(arguments='{"location":"Paris, FR"}', name='get_current_weather'), type='function')]))], created=1722493532, model='majx13/test', object='chat.completion', service_tier=None, system_fingerprint='fp_ollama', usage=CompletionUsage(completion_tokens=89, prompt_tokens=200, total_tokens=289))
> Calling Function get_current_weather with Argument {'location': 'San Francisco, CA'}...
> Calling Function get_current_weather with Argument {'location': 'Tokyo', 'unit': 'celsius'}...
> Calling Function get_current_weather with Argument {'location': 'Paris, FR'}...
> ChatCompletion(id='chatcmpl-175', choices=[Choice(finish_reason='stop', index=0, logprobs=None, message=ChatCompletionMessage(content="The current weather in San Francisco is 72 degrees. In Tokyo, the temperature is 10 degrees Celsius. And in Paris, it's around 22 degrees.", role='assistant', function_call=None, tool_calls=None))], created=1722493548, model='majx13/test', object='chat.completion', service_tier=None, system_fingerprint='fp_ollama', usage=CompletionUsage(completion_tokens=37, prompt_tokens=275, total_tokens=312))
> ```
> 
> I will try to contact the maintainer of Qwen2 to use this template if it works for you as well.

@JianxinMa Yes, I received the expected input! Here is the content I output:
```
ChatCompletion(id='chatcmpl-110', choices=[Choice(finish_reason='stop', index=0, logprobs=None, message=ChatCompletionMessage(content='', role='assistant', function_call=None, tool_calls=[ChatCompletionMessageToolCall(id='call_0b4t0xdv', function=Function(arguments='{"location":"San Francisco","unit":"fahrenheit"}', name='get_current_weather'), type='function'), ChatCompletionMessageToolCall(id='call_up10pk71', function=Function(arguments='{"location":"Tokyo","unit":"celsius"}', name='get_current_weather'), type='function'), ChatCompletionMessageToolCall(id='call_7obsb4sn', function=Function(arguments='{"location":"Paris","unit":"fahrenheit"}', name='get_current_weather'), type='function')]))], created=1722659045, model='majx13/test', object='chat.completion', service_tier=None, system_fingerprint='fp_ollama', usage=CompletionUsage(completion_tokens=99, prompt_tokens=200, total_tokens=299))
Calling Function get_current_weather with Argument {'location': 'San Francisco', 'unit': 'fahrenheit'}...
Calling Function get_current_weather with Argument {'location': 'Tokyo', 'unit': 'celsius'}...
Calling Function get_current_weather with Argument {'location': 'Paris', 'unit': 'fahrenheit'}...
ChatCompletion(id='chatcmpl-947', choices=[Choice(finish_reason='stop', index=0, logprobs=None, message=ChatCompletionMessage(content="The current weather in San Francisco is 72 degrees Fahrenheit. In Tokyo, it's 10 degrees Celsius and in Paris, the temperature is 22 degrees Fahrenheit.", role='assistant', function_call=None, tool_calls=None))], created=1722659046, model='majx13/test', object='chat.completion', service_tier=None, system_fingerprint='fp_ollama', usage=CompletionUsage(completion_tokens=37, prompt_tokens=279, total_tokens=316))
```
Finally, thank you again for your attention and work!

**Comment by jiandandema** [comment]
I also tested the `llm.with_structured_output()` method in Langchain and was able to obtain the expected results. This is fantastic!
![760fb4f4197d02d951877faf2737757](https://github.com/user-attachments/assets/a56721a6-17db-4f4f-957c-e182abc3bcf2)
I've been aiming for this result for the past month or two, and I was able to achieve it using OpenAI's API earlier on. I will continue to test other methods in Langchain going forward.
here are the test codes
```python
import getpass
import os
from langchain_openai import ChatOpenAI
from typing import Annotated, List, Tuple, TypedDict
from typing import Optional
from langchain_core.pydantic_v1 import BaseModel, Field

os.environ["LANGCHAIN_TRACING_V2"] = "true"
os.environ["LANGCHAIN_ENDPOINT"] = "https://api.smith.langchain.com"
os.environ["LANGCHAIN_API_KEY"] = "your_langsmith_api_key"

class Joke(BaseModel):
    """Joke to tell user."""

    setup: str = Field(description="The setup of the joke")
    punchline: str = Field(description="The punchline to the joke")
    rating: Optional[int] = Field(description="How funny the joke is, from 1 to 10")


class planer(BaseModel):
    """Based on user question, plan a list of steps"""

    steps: List[str] = Field(description="List of steps")

llm = ChatOpenAI(model="majx13/test",base_url="http://localhost:11434/v1",api_key="1", temperature=0)

structured_llm = llm.with_structured_output(planer)

print(structured_llm.invoke("I want to put the elephant in the fridge."))
```

**Comment by zhanghuanhuanlive** [comment]
Thanks,it works on Ollama0.3.4 with Qwen2:7b.
How can I make it support Qwen2:72b?

**Comment by jiandandema** [comment]
> Thanks,it works on Ollama0.3.4 with Qwen2:7b. How can I make it support Qwen2:72b?

I think it can be done. I think updating the prompt template is enough. The path in Linux is:`/usr/share/ollama/. ollama/models/Blobs/`. You can take a detailed look at the files in this directory

**Comment by codefromthecrypt** [comment]
@jiandandema I wonder if you add the label "model request", this might become closer to solved? I tried majx13/test as well, and I think main thing is to get the right folks aware of this issue.

**Comment by jiandandema** [comment]
谢谢您给马坤发送邮件，我会及时查看的，谢谢，辛苦了

**Comment by jiandandema** [comment]
> @jiandandema I wonder if you add the label "model request", this might become closer to solved? I tried majx13/test as well, and I think main thing is to get the right folks aware of this issue.

sorry, I don’t know which “model request” label you mean. In LangChain or Ollama?

**Comment by codefromthecrypt** [comment]
On this issue here in ollama.. I don't know if you have the right to add the label, but maybe try

<img width="226" alt="Screenshot 2024-09-02 at 9 06 48 AM" src="https://github.com/user-attachments/assets/470990ef-236e-46b3-905a-d9f4d8476943">

**Comment by codefromthecrypt** [comment]
For example, you can look at https://github.com/ollama/ollama/issues/6564 which has the label "model request"
<img width="186" alt="Screenshot 2024-09-02 at 9 32 50 AM" src="https://github.com/user-attachments/assets/00e0ffb3-b946-4608-95ca-44f523a56866"> instead of what this issue has, which is "feature request" 
![image](https://github.com/user-attachments/assets/ec4b3946-850b-4ac3-a866-d9e87d83a7a7)

By adding the label "model request" to this issue #6007, there is a chance someone may look at it who currently isn't yet.

**Comment by jiandandema** [comment]
> For example, you can look at #6564 which has the label "model request" <img alt="Screenshot 2024-09-02 at 9 32 50 AM" width="186" src="https://private-user-images.githubusercontent.com/64215/363534365-00e0ffb3-b946-4608-95ca-44f523a56866.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUyNDE3NDIsIm5iZiI6MTcyNTI0MTQ0MiwicGF0aCI6Ii82NDIxNS8zNjM1MzQzNjUtMDBlMGZmYjMtYjk0Ni00NjA4LTk1Y2EtNDRmNTIzYTU2ODY2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAyVDAxNDQwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE3ZDM1NjAxODZmNDMyMmU0OTNhYmU2MWQ4ZDNjNWRlNTIxM2I1ZGJjZTZhZGFmNDdiZjQwZjk4ODg5MmY0ZGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.izGtznFBpIUvOzyl9adupCcfDdI8hsmpYj-L3pmygIE"> instead of what this issue has, which is "feature request" ![image](https://private-user-images.githubusercontent.com/64215/363534389-ec4b3946-850b-4ac3-a866-d9e87d83a7a7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUyNDE3NDIsIm5iZiI6MTcyNTI0MTQ0MiwicGF0aCI6Ii82NDIxNS8zNjM1MzQzODktZWM0YjM5NDYtODUwYi00YWMzLWE4NjYtZDllODdkODNhN2E3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAyVDAxNDQwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE0ZGE5MDE1YzliNjM3OTFkNmQyZDQ4MDgyYjg5MDNlNjRhOTI4MzE5NzdmODgwODFkYjQ1Zjg2ZmE1NjJkNTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2S7IsARG0kEigpdNB60-ql_f2WSltONxMu61hS2Zb-4)
> 
> By adding the label "model request" to this issue #6007, there is a chance someone may look at it who currently isn't yet.

I'm sorry, I misunderstood what you meant. I'll add that label in a moment. Thank you for your reminding!

**Comment by donkey566788** [comment]
> I also tested the `llm.with_structured_output()` method in Langchain and was able to obtain the expected results. This is fantastic! ![760fb4f4197d02d951877faf2737757](https://private-user-images.githubusercontent.com/51021076/354794311-a56721a6-17db-4f4f-957c-e182abc3bcf2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUzNTA0NzksIm5iZiI6MTcyNTM1MDE3OSwicGF0aCI6Ii81MTAyMTA3Ni8zNTQ3OTQzMTEtYTU2NzIxYTYtMTdkYi00ZjRmLTk1N2MtZTE4MmFiYzNiY2YyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAzVDA3NTYxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFjMDkxNzM2Y2Q1OWRkODRhMzE1ZDQ5MDc4YWRjYjhkNjBmYjMwM2FhYjcyYzcyZTEyMmVhMDZlMWY2MGU5Y2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MosK_LbDCmrjsPMO_WuiRtzOFlxWsx-YOPoEhZCf_FA) I've been aiming for this result for the past month or two, and I was able to achieve it using OpenAI's API earlier on. I will continue to test other methods in Langchain going forward. here are the test codes
> 
> ```python
> import getpass
> import os
> from langchain_openai import ChatOpenAI
> from typing import Annotated, List, Tuple, TypedDict
> from typing import Optional
> from langchain_core.pydantic_v1 import BaseModel, Field
> 
> os.environ["LANGCHAIN_TRACING_V2"] = "true"
> os.environ["LANGCHAIN_ENDPOINT"] = "https://api.smith.langchain.com"
> os.environ["LANGCHAIN_API_KEY"] = "your_langsmith_api_key"
> 
> class Joke(BaseModel):
>     """Joke to tell user."""
> 
>     setup: str = Field(description="The setup of the joke")
>     punchline: str = Field(description="The punchline to the joke")
>     rating: Optional[int] = Field(description="How funny the joke is, from 1 to 10")
> 
> 
> class planer(BaseModel):
>     """Based on user question, plan a list of steps"""
> 
>     steps: List[str] = Field(description="List of steps")
> 
> llm = ChatOpenAI(model="majx13/test",base_url="http://localhost:11434/v1",api_key="1", temperature=0)
> 
> structured_llm = llm.with_structured_output(planer)
> 
> print(structured_llm.invoke("I want to put the elephant in the fridge."))
> ```

在LangGraph上可用， 感谢

**Comment by donkey566788** [comment]
> I just made a tool call template for `qwen2:7b`: https://ollama.com/majx13/test
> 
> However, the latest install.sh installs Ollama version 0.3.0 for me (which is weird), not 0.3.1 that includes the tool call functionality. Therefore, I haven't tested if the template is correct. I'm just sharing this and hope it helps.
> 
> I'll test it later once I have 0.3.1 installed.

@JianxinMa  在LangGraph上测试可用，感谢，
 请问qwen 对齐tool call的正式版什么时候会发布

**Comment by JianxinMa** [comment]
> > I just made a tool call template for `qwen2:7b`: https://ollama.com/majx13/test
> > However, the latest install.sh installs Ollama version 0.3.0 for me (which is weird), not 0.3.1 that includes the tool call functionality. Therefore, I haven't tested if the template is correct. I'm just sharing this and hope it helps.
> > I'll test it later once I have 0.3.1 installed.
> 
> @JianxinMa 在LangGraph上测试可用，感谢， 请问qwen 对齐tool call的正式版什么时候会发布

The Qwen2 repository on Ollama is maintained by the Ollama team and not by the Qwen team. We reached out to them several weeks ago, but we haven't received any updates from Ollama recently.

Our plan is to at least introduce support for tool calls in Qwen2.5, which should be happening soon.

**Comment by jmorganca** [comment]
@JianxinMa thank you! Sorry for delay, we will look at this asap (and in the near future make it easier to collaborate/contribute to this repository)

**Comment by lxysl** [comment]
Is there any plan to introduce the [tool-use instruction tuning model of qwen2](https://huggingface.co/modelscope/qwen2-7b-agent-instruct) into ollama?

**Comment by jmorganca** [comment]
Hi folks sorry for the delay. Qwen2 has been updated with the recommended system prompt, as well as the nous-style tool calling from the Qwen-Agent repo https://ollama.com/library/qwen2

**Comment by codefromthecrypt** [comment]
@jmorganca great! I can verify qwen2. I often use qwen2:0.5b and qwen2 qwen2:1.5b in tests as they are a lot smaller. Is there any chance you can update the prompts on the other tags?

**Comment by jmorganca** [comment]
@codefromthecrypt I'm not sure qwen2:0.5b and qwen2:1.5b support tool calling. I tried with these models but it didn't seem to produce the intended output.

**Comment by codefromthecrypt** [comment]
@jklj077 do you mind verifying the expectations on  qwen2:0.5b and qwen2:1.5b vs qwen2 (7b) on this template? https://ollama.com/library/qwen2/blobs/77c91b422cc9

Ack I recall 2.5 will more formally support tools.

**Comment by jklj077** [comment]
@codefromthecrypt Both Qwen2-0.5B-Instruct and Qwen2-1.5B-Instruct were indeed trained using function/tool calling data. While the original template might not be entirely feasible with Go, it seems that the new template (nous-style) works largely thanks to the models' ability to follow instructions. However, the smaller models, especially after quantization, don't always follow instructions as accurately. I found that the tags were often missing in the generated text, which I would say is expected.

**Comment by michaelneale** [comment]
@jklj077 this makes sense - I did see with Qwen2 it fail at tool calling syntax at one point - ebem 7B - 72B seemed potentialy better (but a little slow in my current hardware to fully experience) so makes sense.

**Comment by ivanstepanovftw** [comment]
Does Qwen have ability to respond with special token `<tool_call>`?

**Comment by jiandandema** [comment]
谢谢您给马坤发送邮件，我会及时查看的，谢谢，辛苦了

**Comment by jklj077** [comment]
@ivanstepanovftw technically yes for all models from all gens. There are examples in that pattern/template in training Qwen2.5 instruct models; for other gens, prompt engineering should also work. but since 2.5, <tool_call> is a special token and due to implementation differences, it may or may not be filtered by the framework in the output.

**Comment by ivanstepanovftw** [comment]
@jklj077 I have troubles in llama.cpp to get <tool_call> token :disappointed:, though I do not remember if it is filtered somewhere...
