### ISSUE TITLE
/api/chat API returns empty information

### ISSUE THREAD

**Issue by du-kk** [ollama/ollama#6012]
environment：
OS： UOS Linux
GPU：NVIDIA L20
Ollama version：0.2.8

issue
input: curl 127.0.0.1:11434/api/generate - d '{"model": "qwen2:0.5b", "pormpt": "who are you?", "format": "json", "stream": false}' 
always returns 
{"model": "qwen2:0.5b", "creatd_at": "2024-07-27T08:46:47.54755Z", "response": "" "," done ": true," done_ reason ":" load "}

There are no error messages in Journalctl - u ollama, only one request message
gpu1 ollama[30085]: [GIN] 2024/07/27 - 16:44:36 | 200 |   39.405859ms |    23.36.75.155 | POST     "/api/chat"

Please help me, thank you

**Comment by Apokalypser** [comment]
You wrote "pormpt".

**Comment by du-kk** [comment]
> You wrote "pormpt".

Thank you for pointing out my spelling mistake

**Comment by thinkverse** [comment]
> Thank you for pointing out my spelling mistake

If your issue is resolved please consider closing the issue.

**Comment by du-kk** [comment]
Sorry
