### ISSUE TITLE
Gemma2 and Mistral-nemo not running on ollama

### ISSUE THREAD

**Issue by gus147** [ollama/ollama#6016]
### What is the issue?

[147@Clevo ~]$ ollama run mistral-nemo:12b-instruct-2407-fp16
Error: exception error loading model hyperparameters: invalid n_rot: 128, expected 160
[147@Clevo ~]$ ollama run gemma2:27b-instruct-q8_0 
Error: exception error loading model architecture: unknown model architecture: 'gemma2'

Can someone explain why this is happening?
It is the first time models do not run on my ollama v0.1.30

### OS

Linux

### GPU

Nvidia

### CPU

Intel

### Ollama version

0.1.30

**Comment by rick-github** [comment]
Gemma2 needs ollama 0.1.47 or newer.  minstal-nemo needs ollama 0.2.8 or newer.

**Comment by gus147** [comment]
Thanks Rick

**Comment by thinkverse** [comment]
> Thanks Rick

If your issue is resolved please consider closing it.

**Comment by gus147** [comment]
Thank you
