### ISSUE TITLE
max retries exceeded: unexpected EOF

### ISSUE THREAD

**Issue by davidsolal** [ollama/ollama#6018]
> The bug shown in this issue specifically is now fixed as we run models directly rather than in a subprocess. Although there are still on EOF errors. If anyone else sees an EOF please open a new issue so we can triage it appropriately.
_Originally posted by @BruceMacD in https://github.com/ollama/ollama/issues/1158#issuecomment-1989152214_

            
Hi, I am new to reporting issues, found this issue is closed but also read I should open a new one if it happens again. 

Anything I can do to help finding the origin of the issue ? 

![image](https://github.com/user-attachments/assets/7a723d68-c52c-4c55-9e52-9071babd0af9)

**Comment by rick-github** [comment]
Server logs would help diagnose the issue.  Since larger modules require more connections and more data transfer, they're more susceptible to interruptions.

**Comment by davidsolal** [comment]
Of course, makes complete sense. 
Should I close the request?
Thank you for your time.

**Comment by rick-github** [comment]
If you are happy to treat it as a transient event, close the ticket.  If it happens again, re-open it and add some server logs.

**Comment by rampageservices** [comment]
See #4625 related to this issue.

**Comment by jmorganca** [comment]
Sorry about this, merging with https://github.com/ollama/ollama/issues/1036
