### ISSUE TITLE
Docker image looks for `libcudart.so.12` but doesn't ifnd it

### ISSUE THREAD

**Issue by jmorganca** [ollama/ollama#602]
The subprocess `server` looks for `libcudart.so.12` but can't find it. It seems `libcudart.so.12.0` is packaged

```
error while loading shared libraries: libcudart.so.12: cannot open shared object file: No such file or directory
```

When looking at the temporary subprocess directory:

```
ls -al /tmp/ollama3423059418/llama.cpp/ggml/build/cuda/bin/
drwxr-xr-x 2 ollama ollama      4096 Sep 26 06:27 .
drwxr-xr-x 3 ollama ollama      4096 Sep 26 06:27 ..
-rwxr-xr-x 1 ollama ollama 107473968 Sep 26 06:27 libcublas.so.12
-rwxr-xr-x 1 ollama ollama 515090264 Sep 26 06:27 libcublasLt.so.12
-rwxr-xr-x 1 ollama ollama    687456 Sep 26 06:27 libcudart.so.12.0
-rwxr-xr-x 1 ollama ollama   5471600 Sep 26 06:27 server
```

**Comment by jmorganca** [comment]
Fixed on `main`

**Comment by willswire** [comment]
I am having this issue currently:

`/tmp/ollama568860520/11ama.cpp/gguf/build/cuda/bin/ollama-runner: error while loading shared libraries: libcudart.so.12: cannot open shared object file: No such file or directory`

but when I look in the directory, I see libcudart.so.12.0
