### ISSUE TITLE
ollama version is 0.0.0 (windows preview) 

### ISSUE THREAD

**Issue by dispather** [ollama/ollama#6022]
### What is the issue?

 I installed windows preview ollama and I found gpu is not working when using ollama. So I check ollama version. 
 
 C:\Users\mightyhun\AppData\Local\Programs\Ollama>ollama -v
ollama version is 0.0.0
Warning: client version is 0.3.0

It shows mismatch of ollama version. and I checked ollama location. 

C:\Users\mightyhun\AppData\Local\Programs\Ollama>where ollama
C:\Users\mightyhun\AppData\Local\Programs\Ollama\ollama.exe

As you see, ollama is running correct location but, it shows wrong version, not showing tray icon.
I delete wsl2 ubuntu not to interfere windows runnnig env.

what can I do to solve this?

### OS

Windows

### GPU

Nvidia

### CPU

AMD

### Ollama version

0.3.0

**Comment by BruceMacD** [comment]
Hi @dispather, did you build Ollama from source by chance? If you built the server the version will be set to `0.0.0`.

**Comment by dispather** [comment]
@BruceMacD Yes, I wanted to make my gpu work, I did many atempt. among it, I set up an ollama on wsl2 ubuntu. Is it some influence on this problem? I delete the ubuntu system, docker, ollama all. and now, I clean my hdd and registry wishing it makes some change.  what I should do to solve this? can you give me a advice?

**Comment by dispather** [comment]
@BruceMacD I did it! After clearing all the temp files and registry, it works! Thank you for your concern! Now, I'll try the web UI on the GPU again.
