### ISSUE TITLE
Expose unavaiable Llama-CPP flags

### ISSUE THREAD

**Issue by doomgrave** [ollama/ollama#6023]
Please expose all the llama-cpp flags when we configure the modelcard.
For example: offload_kqv, flash_attn, logits_all can be needed in specific usecases!

**Comment by jmorganca** [comment]
Hi @doomgrave . Thanks for the issue.

`flash_attn` and similar flags are available as an environment variable `OLLAMA_FLASH_ATTENTION`. Others can be found in respective feature requests #2415
