### ISSUE TITLE
ollamar how to boot using a fixed port

### ISSUE THREAD

**Issue by huoyalong** [ollama/ollama#6025]
### What is the issue?

ollamar how to boot using a fixed port

### OS

Linux

**Comment by rick-github** [comment]
By default ollama always uses port 11434.  If you want to change to a different fixed port, set `OLLAMA_HOST=127.0.0.1:<port>` in the server environment.

**Comment by huoyalong** [comment]
> By default ollama always uses port 11434. If you want to change to a different fixed port, set `OLLAMA_HOST=127.0.0.1:<port>` in the server environment.

ok,thank you!!
But I think remote access is going to need to be changed to OLLAMA_HOST=0.0.0.0:<port>
