### ISSUE TITLE
The 1k context limit in Open-WebUI request is causing low-quality responses.

### ISSUE THREAD

**Issue by anrgct** [ollama/ollama#6026]
### What is the issue?

When using open-webui, I've noticed that long contextual messages sent to ollama consistently result in poor responses. After investigating the issue, it appears that the `/api/chat` and `/v1/chat/completions` endpoints are defaulting to a 1k context limit. This means that when the content exceeds this length, the system automatically discards the earlier portions, leading to subpar answers. What follows is the captured network request data for open-webui version 0.3.8.
```
curl 'http://localhost:11434/api/chat' \
-X POST \
-H 'Host: localhost:11434' \
-H 'Accept: */*' \
-H 'User-Agent: Python/3.11 aiohttp/3.9.5' \
-H 'Content-Type: text/plain; charset=utf-8' \
--data-raw '{"model": "qwen1_5-4b-chat-q4_k_m", "messages": [{"role": "user", "content": "<long context>"}], "options": {}, "stream": true}' 
```
Based on the final response, we can observe that the prompt_eval_count is 1026, which indicates that only approximately 1,000 tokens of context were processed. 
```
{"role":"assistant","content":""},"done_reason":"stop","done":true,"total_duration":9987503333,"load_duration":28999667,"prompt_eval_count":1026,"prompt_eval_duration":1896469000,"eval_count":238,"eval_duration":8059779000}
```
I'm uncertain whether I should submit an issue about this bug to the open-webui repository.

### OS

macOS

### GPU

Apple

### CPU

Apple

### Ollama version

0.3.0

**Comment by rick-github** [comment]
https://github.com/ollama/ollama/issues/5965#issuecomment-2252354726

**Comment by rick-github** [comment]
You also set a context length for a model in open-webui.  Go to Workspace > Models > Create a model, choose the base model, scroll down to Model Params and under Advanced Params, set the context length.

**Comment by anrgct** [comment]
Thank you for your response! I've also discovered another bug. When I add "options": {"num_ctx": 32000} to the `/v1/chat/completions` endpoint, it doesn't take effect and the context length remains at 1k. This option works correctly on the `/api/chat` and `/api/generate endpoints`.

**Comment by rick-github** [comment]
Probably because the OpenAI API doesn't support specifying the context window, just `max_tokens`.  So yes, that would be an appropriate feature request for ollama.

**Comment by rick-github** [comment]
A bit more information is needed.  If you supply a server log (`docker logs <name-of-ollama-container>`) it can be checked for truncation messages.  It would also be useful to see the actual HTTP request that open-webui is sending.  Unfortunately that's not logged, so a tool needs to be installed to capture that:
```
$ docker exec -it <name-of-ollama-container> apt install -y tcpflow
$ docker exec -it <name-of-ollama-comtainer> tcpflow -c 'src port 11434 or dst port 11434' > ollama-open-webui.log
```
Run this, use open-webui for a long context conversation, ^C tcpflow, remove any PII from the log, and add it here.

**Comment by anrgct** [comment]
@chris-31337 , "prompt_eval_count" refers to the actual length of the processed prompt, which is 934 in your ollama-open-webui.log, meaning only the last 934 tokens were used as the prompt. Didn't you modify the modelfile as suggested? It worked for me after I made the changes. Also, is this screenshot from [openwebui](https://github.com/open-webui/open-webui)? I haven't seen this option before.

> [#5965 (comment)](https://github.com/ollama/ollama/issues/5965#issuecomment-2252354726)

**Comment by rick-github** [comment]
From ollama-docker.log:
```
INFO [update_slots] input truncated | n_ctx=2048 n_erase=19335 n_keep=4 n_left=2044 n_shift=1022 tid="133210613727232" timestamp=1722942601
```
From ollama-open-webui.log:
```
have ever known."}],"options":{},"keep_alive":"15m","sess
```
There's no `num_ctx` in the `options` field, so the input text of ~21k tokens is being whittled down to 2048 by throwing away 19335 of them.  What version of open-webui are you using?  I'll fire up a docker container with it and see if I can replicate.

**Comment by anrgct** [comment]
I just discovered this setting in open-webui. My version is v0.3.11, and it's actually working. I had no idea about it before... @chris-31337
![1723208848023](https://github.com/user-attachments/assets/b18774b5-a10a-4404-a2e0-b4d6feac6447)

**Comment by igorschlum** [comment]
@anrgct interesting issue. As it is solved. Could you please close it to reduce the number of open issues?

**Comment by anrgct** [comment]
Thank you for your patient replies! @igorschlum @rick-github
