### ISSUE TITLE
How to Move Model Files on an External Hard Drive? 

### ISSUE THREAD

**Issue by lennondong** [ollama/ollama#6030]
How to Move Model Files on an External Hard Drive? 
Due to insufficient internal storage on my Mac, I would like to store model files on an external hard drive to run them.

**Comment by rick-github** [comment]
Set `OLLAMA_MODELS` to the path of where you want to store the models.  You can only have one path, so you need to have all models in the same place.  If you've already downloaded some models, copy them from the old path to the new path.

**Comment by jiushun** [comment]
When I set the OLLAMA_MODELS into the ollama.service file, the systemctl restart is not work, ollama cannot restart, please give me some advice?

**Comment by rick-github** [comment]
[Server logs](https://github.com/ollama/ollama/blob/main/docs/troubleshooting.md#how-to-troubleshoot-issues) will help in debugging.

**Comment by rick-github** [comment]
@jiushun If you are still having problems, open a new issue and add server logs.
