### ISSUE TITLE
can't import DarkIdol-Llama-3.1-Instruct-1.2-Uncensored:8b_Q8_0

### ISSUE THREAD

**Issue by taozhiyuai** [ollama/ollama#6034]
### What is the issue?

1. modelfile

FROM ./DarkIdol-Llama-3.1-8B-Instruct-1.2-Uncensored.Q8_0.gguf
TEMPLATE "{{- if .Messages }}
{{- if .System }}<|start_header_id|>system<|end_header_id|>

{{ .System }}<|eot_id|>
{{- end }}
{{- range .Messages }}<|start_header_id|>{{ .Role }}<|end_header_id|>

{{ .Content }}<|eot_id|>
{{- end }}<|start_header_id|>assistant<|end_header_id|>

{{ else }}
{{- if .System }}<|start_header_id|>system<|end_header_id|>

{{ .System }}<|eot_id|>{{ end }}{{ if .Prompt }}<|start_header_id|>user<|end_header_id|>

{{ .Prompt }}<|eot_id|>{{ end }}<|start_header_id|>assistant<|end_header_id|>

{{ end }}{{ .Response }}{{ if .Response }}<|eot_id|>{{ end }}"
PARAMETER stop <|start_header_id|>
PARAMETER stop <|end_header_id|>
PARAMETER stop <|eot_id|>

taozhiyu@603e5f4a42f1 DarkIdol-Llama-3.1-8B-Instruct-1.2-Uncensored-GGUF % ollama create taozhiyuai/DarkIdol-Llama-3.1-Instruct-1.2-Uncensored:8b_Q8_0 -f modelfile
transferring model data 
using existing layer sha256:9ad16d0a1bb54a5efcaa4dfbfde70254768724ec5f453934de4e688dca2a3070 
using existing layer sha256:cdbcae7e69d520e3d5a17b4979c31331dfba959f36641a81576349875d682127 
using existing layer sha256:56bb8bd477a519ffa694fc449c2413c6f0e1d3b1c88fa7e3c9d88d3ae49d4dcb 
creating new layer sha256:a67d6d41b0d6ca312152b392a024900ae436f3eee547dd5c914dadba0229bf8b 
writing manifest 
success 

taozhiyu@603e5f4a42f1 DarkIdol-Llama-3.1-8B-Instruct-1.2-Uncensored-GGUF % ollama run taozhiyuai/DarkIdol-Llama-3.1-Instruct-1.2-Uncensored:8b_Q8_0
Error: llama runner process has terminated: error:done_getting_tensors: wrong number of tensors; expected 292, got 291

### OS

macOS

### GPU

Apple

### CPU

Apple

### Ollama version

0.3.0

**Comment by 44670** [comment]
I have found an issue might be related: https://github.com/LostRuins/koboldcpp/issues/1026

**Comment by 44670** [comment]
According to https://github.com/ollama/ollama/issues/6048#issuecomment-2258749861, this issue should have been resolved in 0.3.1.

**Comment by taozhiyuai** [comment]
> According to [#6048 (comment)](https://github.com/ollama/ollama/issues/6048#issuecomment-2258749861), this issue should have been resolved in 0.3.1.

DONE! thanks.
