### ISSUE TITLE
Model and Framework Adaptation

### ISSUE THREAD

**Issue by 673092756** [ollama/ollama#6038]
### What is the issue?

One but ollama set "OLLAMA_KEEP_ALIVE=24h"
"ollama3.1:8b-instruct-fp16" the model won't start or fails to start!

### GPU

Nvidia

### CPU

Intel

### Ollama version

0.3.0

**Comment by rick-github** [comment]
Mis-spelled: "llama3.1:8b-instruct-fp16", not "ollama3.1:8b-instruct-fp16".

**Comment by 673092756** [comment]
> Mis-spelled: "llama3.1:8b-instruct-fp16", not "ollama3.1:8b-instruct-fp16".

哦哦，这样啊

**Comment by jmorganca** [comment]
Thanks @rick-github, will close this 😊
