### ISSUE TITLE
[Model request] Llama3.1 `text` model (not `instruct`)

### ISSUE THREAD

**Issue by d-kleine** [ollama/ollama#6040]
As per comment: https://github.com/ollama/ollama/issues/5919#issuecomment-2248604007

Could you please add the Meta-Llama-3.1 models to Ollama models please?
https://ollama.com/library/llama3.1

Currently, there are only the instruction-finetuned models (`...-instruct-...`), but not the vanilla models (`...-text-...`):
https://huggingface.co/meta-llama/Meta-Llama-3.1-8B
https://huggingface.co/meta-llama/Meta-Llama-3.1-70B
https://huggingface.co/meta-llama/Meta-Llama-3.1-405B

**Comment by kaetemi** [comment]
Duplicate https://github.com/ollama/ollama/issues/5957

**Comment by chigkim** [comment]
+1 I'd also love to see it on the library!

**Comment by d-kleine** [comment]
@chigkim please use #5957, and just give a thumbs up 👍🏻 to keep issue tracking concise
