### ISSUE TITLE
I can't run llama3.1

### ISSUE THREAD

**Issue by Saber120** [ollama/ollama#6048]
### What is the issue?

I trained my own model from llama version 3.1 8b and created the modlefile for it successfully, but when I start running it it does not work and I get this error 
`
ollama run  mymodle:latest
Error: llama runner process has terminated: error loading model: done_getting_tensors: wrong number of tensors; expected 292, got 291
`

Knowing that the llama 3 8b model was working and is still working well

### OS

Linux

### GPU

Nvidia

### CPU

Other

### Ollama version

0.3.0

**Comment by maciekpoplawski** [comment]
Git the exact same problem :( 
`Error: llama runner process has terminated: error loading model: done_getting_tensors: wrong number of tensors; expected 292, got 291`

**Comment by Lexazan** [comment]
Got same error after trying to run just converted hf to guff model (https://huggingface.co/Undi95/Meta-Llama-3.1-8B-Claude).
Seems to be related to https://github.com/ggerganov/llama.cpp/issues/8650

**Comment by rick-github** [comment]
ollama lags the leading edge of llama.cpp, and it looks like the recent versions of llama.cpp create GGUF files that the older versions can't process.  If you use an older version of llama.cpp to convert hf to GGUF it might work.

**Comment by Saber120** [comment]
> ollama lags the leading edge of llama.cpp, and it looks like the recent versions of llama.cpp create GGUF files that the older versions can't process. If you use an older version of llama.cpp to convert hf to GGUF it might work.

Does this mean that the main problem comes from llamacpp? Indeed, I tried a model that I had trained on a long time ago and it really worked. Currently, the model that I am trying to operate is one that I use with unsloth and convert it to gguf  using unsloth and unsloth downloads the latest version of llamacpp.

**Comment by rick-github** [comment]
> Does this mean that the main problem comes from llamacpp?

This is my understanding.  Apparently, a change has been made that is not forwards and backwards compatible.  This sort of breaking change is not ideal, if it remains in place then when ollama syncs past that point in the llama.cpp, all models based on lllama3 will stop working.  I can't imagine that is acceptable to anybody, so I expect a fix will be developed.  Until then, if you want to use a llama3 model with ollama <= 0.3.0, model conversion will need to be done with an older version of llama.cpp.

**Comment by jmorganca** [comment]
Hi all, this will be fixed in [version 0.3.1](https://github.com/ollama/ollama/releases/tag/v0.3.1) which is in prerelease but will be released soon

**Comment by Lexazan** [comment]
Can confirm that issue is gone on [0.3.1](https://github.com/ollama/ollama/releases/tag/v0.3.1)
