### ISSUE TITLE
Update template: Llama 3.1

### ISSUE THREAD

**Issue by MaxJa4** [ollama/ollama#6060]
Meta / HF updated the tokenizer config (specifically the chat template) of all the Llama 3.1 (instruct) models a few hours ago:

- [Meta-Llama-3.1-8B-Instruct](https://huggingface.co/meta-llama/Meta-Llama-3.1-8B-Instruct/commit/b2a4d0f33b41fcd59a6d31662cc63b8d53367e1e)
- [Meta-Llama-3.1-70B-Instruct](https://huggingface.co/meta-llama/Meta-Llama-3.1-70B-Instruct/commit/168b5b277b07436c229bd69844a73872eb8b73a8)
- [Meta-Llama-3.1-405B-Instruct](https://huggingface.co/meta-llama/Meta-Llama-3.1-405B-Instruct/commit/f9801cba95a53242b3cc928a4a418d12571d1c5f)

Since there have been some reports of quality issues with the models themselves (not with Ollama specifically), it may help fix things.
The new chat templates are quite different from the original ones.
Just as a heads up, so it doesn't get overlooked.

Thanks! :)

Update: it changed again

**Comment by d-kleine** [comment]
When added, please also consider adding #5957

**Comment by igorschlum** [comment]
Llama3.1 are being updated since yesterday: https://ollama.com/library/llama3.1/tags

**Comment by d-kleine** [comment]
Nice, thanks a lot!

**Comment by d-kleine** [comment]
@igorschlum Would it be possible to add the 405b `text` completion LLama 3.1 model there as well? Curently there is only the `instruct` fine-tuned version of the 405b model.
