### ISSUE TITLE
ollama serve --choice a model name

### ISSUE THREAD

**Issue by ruanjianlun** [ollama/ollama#6068]
hi guys I have a problem with aggregation, I am using it on windows, when I pass ollama serve, how do I select the aggregation model? For example, the following operation

(base) PS C:\Users\Administrator> ollama serve --model codellama:7b
Error: unknown flag: --model
(base) PS C:\Users\Administrator>

**Comment by ethanknights** [comment]
The local server is generic. So you'd use start it once:
`./ollama serve`

Then run a specific model using that local server with:
`./ollama run llama3.1`

**Comment by ruanjianlun** [comment]
@ethanknights thanks, bro! Got it, ollama is so exciting!

**Comment by qalqi** [comment]
You can check the current running model at http://127.0.0.1:11434/api/ps
