### ISSUE TITLE
Any solution to run on termux?

### ISSUE THREAD

**Issue by rahulmehtas** [ollama/ollama#6069]
Any solution to run on termux?

**Comment by rick-github** [comment]
The Android terminal emulator?  Unlikely.  You are better off setting up a small server somewhere and using a client on the phone to connect to it, for example: https://medium.com/@jldevtech/mobile-ollama-e52633b4c9c9

**Comment by dhiltgen** [comment]
It's not officially supported, but folks in the community have been experimenting.  Related issues #1006 #1926 #4950
