### ISSUE TITLE
Run Ollama on multiple GPU using ollama run 

### ISSUE THREAD

**Issue by atharvnagrikar** [ollama/ollama#6070]
Hi, 
I have 2 gpus each having 40 gb of memory and i want to run llama3.1 70b  using these GPUs, are there any features to run ollama on distributed way

**Comment by rick-github** [comment]
ollama will use multiple GPUs if available.  If you tried it and it didn't work, adding server logs will aid in debugging.

**Comment by dhiltgen** [comment]
@atharvnagrikar let us know if you have any problems loading the model and if so I'll reopen.
