### ISSUE TITLE
llama3.1:70b <|eom_id|> missing as stop in template

### ISSUE THREAD

**Issue by SinanAkkoyun** [ollama/ollama#6071]
### What is the issue?

llama3.1:70b outputs <|eom_id|> as a string rather than an input. To test this, make a function call to the model without a 'tool' response message multiple times. 8B hallucinates, 70B wants to refuse, returns an <|eom_id|> but ollama doesn't recognize it.

### OS

Linux

### GPU

Nvidia

### CPU

Intel

### Ollama version

latest

**Comment by jmorganca** [comment]
This should be fixed now as per @MaxJa4's comment
