### ISSUE TITLE
Model request: Llama3-Athene-70B

### ISSUE THREAD

**Issue by joliss** [ollama/ollama#6073]
It would be lovely to have the Llama3-based post-trained Athene-70b model available on Ollama! It is currently the highest-ranked open 70b model on the [LMSYS leaderboard](https://chat.lmsys.org/?leaderboard).

https://nexusflow.ai/blogs/athene
https://huggingface.co/Nexusflow/Athene-70B

Somebody also published a GGUF version: https://huggingface.co/bullerwins/Athene-70B-GGUF

**Comment by MaxJa4** [comment]
@joliss can this be closed now?
I don't think that many finetunes of base models like this one will be added to the main Ollama model repository, since anyone can upload them by themselves anyway.

**Comment by joliss** [comment]
Yeah, fair to close this I think! Thanks @MaxJa4 for uploading those quants!
