### ISSUE TITLE
`llama3.1:8b` gives empty response first, then hallucinates when prompted with `system` role

### ISSUE THREAD

**Issue by rb81** [ollama/ollama#6075]
### What is the issue?

I've suddenly started getting weird behavior from `llama3.1:8b` when prompting it with the `system` role. `user` works as expected. `system` was working a few days ago, so I don't know if this is related to an issue with a recent model or Ollama update. Anybody else facing similar issues?

### Ollama version

0.3.0

**Comment by rick-github** [comment]
An example of a failed prompt and server logs would help with diagnosis.

**Comment by rb81** [comment]
It seems this issue was related to a bug in my application where an invalid role was provided following the system role. Funny how this worked before (hence why I didn't pick up on it).
