### ISSUE TITLE
Ollama Services run on tcp6

### ISSUE THREAD

**Issue by niravgshah28** [ollama/ollama#6077]
### What is the issue?

Hi 

I am trying to run ollama services with Meta 3-70b model, but when I start my services on my VM even with config file ollama_host with port number still runs on tcp6

if anyone facing similar issue on RHEL 8 Vm

### OS

Linux

### GPU

Nvidia

### CPU

AMD

### Ollama version

Ollam Version 0.2.5

**Comment by dhiltgen** [comment]
This looks like it's likely a dup of #3300.

There's a workaround described in that issue that may still work, but the OLLAMA_HOST parsing logic has changed since March, so I'm not sure.  Let us know on that issue either way.
