### ISSUE TITLE
why wsarecv: An existing connection was forcibly closed by the remote host     ollama windows preview 

### ISSUE THREAD

**Issue by springsuu** [ollama/ollama#6082]
### What is the issue?

Error: pull model manifest: Get "https://registry.ollama.ai/v2/library/llama3/manifests/latest": read tcp 192.168.2.23:51514->172.67.182.229:443: wsarecv: An existing connection was forcibly closed by the remote host

**Comment by dhiltgen** [comment]
Looks like it's most likely a dup of #4042
