### ISSUE TITLE
hope to add "Telechat" 

### ISSUE THREAD

**Issue by enryteam** [ollama/ollama#6087]
https://github.com/Tele-AI/Telechat

**Comment by rampageservices** [comment]
Hey!
This seems to be entirely in Chinese. Can you explain in English what this model is for those who don't know/don't have the time to translate?

**Comment by mighty-laolin** [comment]
I'm looking into this model recently as well and it would actually be very helpful if it could be incorporated into Ollama.

Per the intro on their Github README (translated by chatGPT and proof read by me):

The TeleChat language model is developed and trained by the AI subsidiary of China Telecom. The 7B model is trained on 1.5 trillion tokens of high-quality Chinese and English corpus, while the 12B model is trained on 3 trillion tokens of high-quality Chinese and English corpus.

We have open-sourced the chat models TeleChat-1B, TeleChat-7B, and TeleChat-12B, along with their HuggingFace format weights. Additionally, we have released the int8 and int4 quantized versions of the 7B and 12B models.

TeleChat-12B has undergone improvements in model architecture, training data, and training methods, achieving significant performance gains over TeleChat-7B in general Q&A, knowledge, code, and mathematics tasks. 
- In terms of model architecture, we experimented with a variety of architectural combinations using small-scale models and selected the optimal structure. Compared to the TeleChat-7B model, TeleChat-12B adopts a decoupled structure between the word embedding layer and the output layer, separating the parameters of the word embedding layer from the output lm head layer, enhancing training stability and convergence.
- In terms of training data, we collected a vast amount of bilingual data covering areas such as books, encyclopedias, news, government affairs, law, medicine, patents, academic papers, mathematics, and code. By optimizing data cleaning strategies, we significantly improved the cleanliness, neutrality, effectiveness, and formatting of the data.
- In terms of training methods, we employed scientific data ratio learning and curriculum learning methods. Small-parameter models were used to fit data with various distributions, providing prior estimates of the difficulty of each dataset. During training, periodical autonomous evaluation of the model’s loss across all datasets and its generation performance on evaluation sets was performed, which dynamically increasing the weight of more difficult datasets to ensure optimal fitting across all datasets.

The TeleChat-12B-V2 version utilizes dynamic data ratios and curriculum learning methods for continuous training and enhancement of the base model. Its dialogue model has seen a 5.5% improvement in general capability evaluation, with a 24.6% improvement in mathematical capabilities, a 9% improvement in translation capabilities, a 10.3% improvement in hallucination testing, and varying degrees of enhancement in safety refusal, knowledge Q&A, and casual conversation Q&A.

[https://github.com/Tele-AI/Telechat/blob/master/README.md](url)

**Comment by rampageservices** [comment]
Looks fascinating. Thanks @mighty-laolin for the translation. On first glance a model by China Telecom should be of high quality based on the potential training data they have access to. +1 for working towards incorporating it into Ollama.
