### ISSUE TITLE
Why is the llama3 model missing after I restart Ollama? When I run “ollama run llama3”, it re-pulls the manifest.

### ISSUE THREAD

**Issue by fanjikang** [ollama/ollama#6098]
### What is the issue?

Why is the llama3 model missing after I restart Ollama? When I run “ollama run llama3”, it re-pulls the manifest.

### OS

Linux

### GPU

Nvidia

### CPU

Intel

### Ollama version

v0.2.8

**Comment by rick-github** [comment]
Did you change the server environment variable `OLLAMA_MODELS`?  If you add server logs it may be easier to diagnose the issue.

**Comment by Siddharth-Latthe-07** [comment]
The above issue suggests that the model is not being persistently stored or there is a configuration problem causing it to be removed upon restart.
steps to diagnose:-
1. Check Ollama Configuration
2. Disk Space and Permissions
3. Model cache and log directory
4. service restarts and version updation
5. Persistent Storage Configuration:
`ollama config set model_storage_path /path/to/persistent/storage`
6. Checking and Setting Up Model Cache Directory

Hope this helps,
Thanks

**Comment by FellowTraveler** [comment]
@fanjikang Can you please confirm via above tips if this is a real issue? Otherwise please close this issue.

**Comment by skjortan23** [comment]
I am actually having the same problem. after a power outage `ollama list` is empty however i still see all my models by listing the model directory.

e.g
```/usr/share/ollama/.ollama/models$ du -h ./
126G	./blobs
8,0K	./manifests/registry.ollama.ai/hengwen/watt-tool-8B
12K	./manifests/registry.ollama.ai/hengwen
8,0K	./manifests/registry.ollama.ai/library/llama3-groq-tool-use
8,0K	./manifests/registry.ollama.ai/library/codeqwen
8,0K	./manifests/registry.ollama.ai/library/phi4
8,0K	./manifests/registry.ollama.ai/library/Qwen2.5
12K	./manifests/registry.ollama.ai/library/qwen2.5-coder
8,0K	./manifests/registry.ollama.ai/library/deepseek-coder-v2
8,0K	./manifests/registry.ollama.ai/library/deepseek-coder
8,0K	./manifests/registry.ollama.ai/library/llama3.1
16K	./manifests/registry.ollama.ai/library/deepseek-r1
8,0K	./manifests/registry.ollama.ai/library/llama3.2
8,0K	./manifests/registry.ollama.ai/library/gemma2
8,0K	./manifests/registry.ollama.ai/library/yi-coder
8,0K	./manifests/registry.ollama.ai/library/phi3
8,0K	./manifests/registry.ollama.ai/library/mixtral
8,0K	./manifests/registry.ollama.ai/library/mistral
136K	./manifests/registry.ollama.ai/library
152K	./manifests/registry.ollama.ai
156K	./manifests
126G	./```

**Comment by rick-github** [comment]
Did you change the server environment variable `OLLAMA_MODELS`?  If you add [server logs](https://github.com/ollama/ollama/blob/main/docs/troubleshooting.md#how-to-troubleshoot-issues) it may be easier to diagnose the issue.

**Comment by FellowTraveler** [comment]
You're probably aware of this but it's worth mentioning...

When I do "ollama list" I see this in the list:
llama3.3:70b-instruct-q5_K_M

...but q5_K_M is NOT the default quant. So if I do "ollama run llama3.3:70b-instruct-q5_K_M" it will run immediately.

**But if I do "ollama run llama3.3" it will start downloading q4_0 or whatever the default quant is.**
