### ISSUE TITLE
Ollama is unable to resume interrupted pulls

### ISSUE THREAD

**Issue by nviraj** [ollama/ollama#6101]
### What is the issue?

Previously if I interrupted a pull and started it again (Usually after the speed dropped or wouldn't go to completion after 95%), it was able to resume. 

However today when I pulled the gemma2:2b model, it was unable to do so and started from scratch. This happened multiple times.

Not sure why this could be the case. I am on Windows 11, with the latest version.

### OS

Windows

### GPU

Nvidia

### Ollama version

0.3.1

**Comment by mxyng** [comment]
this is fixed by #6108 which will be in the next release
