### ISSUE TITLE
Ollama not using GPU (AMD)

### ISSUE THREAD

**Issue by theogbob** [ollama/ollama#6105]
### What is the issue?

Im using ollama and I have an Ryzen 9 7900X3D and a Radeon RX 7900XTX, I have rocm installed:
rocm-smi output:

```============================================ ROCm System Management Interface ============================================
====================================================== Concise Info ======================================================
Device  Node  IDs              Temp    Power    Partitions          SCLK    MCLK     Fan  Perf  PwrCap       VRAM%  GPU%  
              (DID,     GUID)  (Edge)  (Avg)    (Mem, Compute, ID)                                                        
==========================================================================================================================
0       1     0x744c,   58112  31.0°C  21.0W    N/A, N/A, 0         137Mhz  96Mhz    0%   auto  303.0W       5%     7%    
1       2     0x164e,   26843  42.0°C  43.199W  N/A, N/A, 0         None    3000Mhz  0%   auto  Unsupported  4%     0%    
==========================================================================================================================
================================================== End of ROCm SMI Log ===================================================
```
The issue is ollama is using my CPU and RAM and never uses my GPU.

### OS

Linux

### GPU

AMD

### CPU

AMD

### Ollama version

reporting as 0.0.0?

**Comment by rick-github** [comment]
Did you download ollama or build it from source?  A version of 0.0.0 usually means built from source, in which it may not have the correct build parameters.  I just downloaded it and it responds as v0.3.1.

**Comment by theogbob** [comment]
I found my issue, (it was so stupid) this may effect any distro but i was using openSUSE tumbleweed, if you install ollama from the package manager it appears to be out of date or somethings wrong, installing using the script appeared to fix my issue.
