### ISSUE TITLE
Generations API for nuextract/phi

### ISSUE THREAD

**Issue by alphastrata** [ollama/ollama#6113]
hitting /api/generate yields nothing :(

if interacting in the manner with neextract/phi is possible please do let us know && we can update the readme etc accordingly.

**Comment by rick-github** [comment]
An example of a failed request and server logs would aid in diagnosis.

```
$ curl -s localhost:11434/api/generate -d '{"model":"nuextract","prompt":"count to 10","stream":false}' | jq 'del(.context)'
{
  "model": "nuextract",
  "created_at": "2024-08-01T13:28:41.744467739Z",
  "response": " Here is the count from 1 to 10:\n\n1. One\n\n2. Two\n\n3. Three\n\n4. Four\n\n5. Five\n\n6. Six\n\n7. Seven\n\n8. Eight\n\n9. Nine\n\n10. Ten",
  "done": true,
  "done_reason": "stop",
  "total_duration": 1524357722,
  "load_duration": 1068789432,
  "prompt_eval_count": 13,
  "prompt_eval_duration": 9086000,
  "eval_count": 66,
  "eval_duration": 445165000
}
$ curl -s localhost:11434/api/version
{"version":"0.3.2"}
```

**Comment by alphastrata** [comment]
> An example of a failed request and server logs would aid in diagnosis.
> 
> ```
> $ curl -s localhost:11434/api/generate -d '{"model":"nuextract","prompt":"count to 10","stream":false}' | jq 'del(.context)'
> {
>   "model": "nuextract",
>   "created_at": "2024-08-01T13:28:41.744467739Z",
>   "response": " Here is the count from 1 to 10:\n\n1. One\n\n2. Two\n\n3. Three\n\n4. Four\n\n5. Five\n\n6. Six\n\n7. Seven\n\n8. Eight\n\n9. Nine\n\n10. Ten",
>   "done": true,
>   "done_reason": "stop",
>   "total_duration": 1524357722,
>   "load_duration": 1068789432,
>   "prompt_eval_count": 13,
>   "prompt_eval_duration": 9086000,
>   "eval_count": 66,
>   "eval_duration": 445165000
> }
> $ curl -s localhost:11434/api/version
> {"version":"0.3.2"}
> ```

looks like it's just a matter of `localhost` in my powershell not resolving to `127.0.0.1` .. weird.
