### ISSUE TITLE
mistral nemo

### ISSUE THREAD

**Issue by Domi31tls** [ollama/ollama#6116]
### What is the issue?

I use open-webui. When i want to use mistral nemo, I have an error 500 : 

![image](https://github.com/user-attachments/assets/19593786-c426-424c-bbcf-8a83eb849135)

### OS

Linux

### GPU

Nvidia

### CPU

Intel

### Ollama version

0.1.37

**Comment by rick-github** [comment]
You need Ollama 0.2.8 or newer to run mistral-nemo.

**Comment by Domi31tls** [comment]
Thanks
