### ISSUE TITLE
Do not generate a history

### ISSUE THREAD

**Issue by zipfile6209** [ollama/ollama#6124]
I would like to request that history can be disabled, as it can be undesirable to write sensitive data to disk for no reason.

I would like to point out that ollama is a bit aggressive about it, the usual tricks like turning it into a symbolic link, giving ownership to root or removing all permissions didn't work :-/

**Comment by mxyng** [comment]
`OLLAMA_NOHISTORY` disables readline history. You can set it in your `~/.bashrc` or equivalent for persistence or invoke one time with `OLLAMA_NOHISTORY=1 ollama run <model>`
