### ISSUE TITLE
can't change ollama server address :127.0.0.1:11434 after binary ollama install 

### ISSUE THREAD

**Issue by cnopens** [ollama/ollama#6134]
### What is the issue?

i install ollama  using binary package ,find that ollama server address 127.0.0.1:11434 ,ip why can't change it ? who  run into the problem ?  later i only used nginx proxy ,but  ,open-webui reponse-webui was very slow vs command consle

### OS

Linux

### GPU

Intel

### CPU

Intel

### Ollama version

0.3.2

**Comment by cnopens** [comment]
add: open-webui docker don't reconigze  127.0.0.1:11434 ,not communicate ,only counld use nginx proxy! who know it

**Comment by rick-github** [comment]
You can change the IP address that ollama binds to by setting `OLLAMA_HOST`, see [here](https://github.com/ollama/ollama/blob/main/docs/faq.md#how-can-i-expose-ollama-on-my-network).  If you are running open-webui in a docker container, you need to either configure open-webui to use host networking, or set the IP address of the ollama connection to the external IP of the host.  An alternative is to run both ollama and open-webui in docker containers, see https://github.com/ollama/ollama/issues/6072#issuecomment-2258419074

**Comment by dhiltgen** [comment]
@cnopens if the above suggestions don't help you resolve, please share a little more information about what you're trying to do and what the topology looks like (are you running them both in separate containers, etc.)
