### ISSUE TITLE
unable to pull  model

### ISSUE THREAD

**Issue by jdzhang1221** [ollama/ollama#6140]
### What is the issue?

ollama pull mxbai-embed-large
pulling manifest 
Error: pull model manifest: Get "https://registry.ollama.ai/v2/library/mxbai-embed-large/manifests/latest": read tcp 192.168.1.94:50046->104.21.75.227:443: read: connection reset by peer

### OS

macOS

### GPU

Intel

### CPU

Intel

### Ollama version

0.3.2

**Comment by Marcus1Pierce** [comment]
Same Ollama version and same command. Is your docker container have internet access?

![image](https://github.com/user-attachments/assets/478cd841-3af3-4135-93cf-85970a03dda3)

**Comment by rampageservices** [comment]
I was just able to pull this model. This may be a temporary error or issue with your internet connection. Please try again a little sometime later.

**Comment by jdzhang1221** [comment]
ollama pull mxbai-embed-large
pulling manifest 
pulling 819c2adf5ce6... 100% ▕████████████████▏ 669 MB                         
Error: Head "https://registry.ollama.ai/v2/library/mxbai-embed-large/blobs/sha256:c71d239df91726fc519c6eb72d318ec65820627232b2f796219e87dcf35d0ab4": read tcp 192.168.0.102:63460->172.67.182.229:443: read: connection reset by peer

oh,no,is it a network problem?

**Comment by jdzhang1221** [comment]
> I was just able to pull this model. This may be a temporary error or issue with your internet connection. Please try again a little sometime later.

Thank you, I tried many times and now it finally works. Maybe it's a network problem. Thank you anyway.

**Comment by Visual-Dawg** [comment]
Same for me, initially it just didn't print anything.
Now a couple hours later and some retries it downloads

**Comment by Visual-Dawg** [comment]
Same for me, initially it just didn't print anything.
Now a couple hours later and some retries it downloadsj

**Comment by rampageservices** [comment]
This is a symptom of a deeper problem with the downloading part of ollama's codebase.
Once this PR is pulled, it should help somewhat but requires deeper investigation.
https://github.com/ollama/ollama/pull/4625

Sadly the download function is not so robust on unreliable internet connections.
