### ISSUE TITLE
BitDefender false positive when downloading Ollama Windows installer

### ISSUE THREAD

**Issue by E-Nyamsuren** [ollama/ollama#6142]
### What is the issue?

BitDefender detects a false positive(?) in the downloaded Windows installer of Ollama.

I also have Ollama installer for Windows downloaded on 27 June 2024. That installer does not have this issue.

**Where**: The current downloadable installer of Ollama on the Ollama website.
**Threat name**: Gen:Suspicious.Cloud.4.@V3@aK5DIadi
**Antivirus**: BitDefender Total Security, Build 27.0.40.174 (latest update)
**OS**: Windows 11
![image](https://github.com/user-attachments/assets/fa1a0b68-0506-4946-b994-e360496037bb)

### OS

Windows

### GPU

Intel

### CPU

Intel

**Comment by dhiltgen** [comment]
We're submitting the latest binaries to msft to resolve the false positive.  It should clear up in a few days.

**Comment by dhiltgen** [comment]
I'll close this as a dup of the recently reopened #2519
