### ISSUE TITLE
ollama0.32下载gemma2 2b时报错，已经最新版本还要求更新ollama；或者是否可以提供下gemma2 2b的清单文件呢？

### ISSUE THREAD

**Issue by zbschat** [ollama/ollama#6150]
### What is the issue?

ollama0.32版本下载gemma2 2b版本的时候，提示清单文件下载失败，打开“[https://registry.ollama.ai/v2/library/gemma2/manifests/2b](https://registry.ollama.ai/v2/library/gemma2/manifests/2b)”页面提示要求更新ollama，但当时已经是最新版本，测试latest版本跟27b的版本都可以正常显示清单，只有2b版本存在报错，或者是否有人可以上传下2b版本的清单文件呢))

### OS

Windows

### GPU

Intel

### CPU

Intel

### Ollama version

0.3.2

**Comment by AlexMa2011** [comment]
Don't use any language except English.

**Comment by rick-github** [comment]
If you recently updated ollama without restarting the server, it's possible that your ollama server is not the same version as your ollama client.  That would explain the failed pull.  What does `ollama --version` show?

**Comment by rjmalagon** [comment]
你好，中文不是我的母语，我正在使用翻译器。

如果可以的话，我想帮助你。
你如何更新 ollama？我的意思是，你是否从 github.com 下载了 Ollama 并直接替换了旧的二进制文件。

@rick-github 提到了一个合理的问题。也许你在替换旧的二进制文件时没有停止最后一个“ollama serve”守护进程。

**Comment by dhiltgen** [comment]
Version 0.3.1 or newer is required for that model to run.  @zbschat if you installed with `OllamaSetup.exe` then you should be able to simply click `Restart to update` from the tray icon menu.

<img width="302" alt="image" src="https://github.com/user-attachments/assets/61ad862c-14d1-4065-a829-1fafa5713d66">


If you installed via the zip file, you'll need to follow the instructions again to get the server updated - https://github.com/ollama/ollama/blob/main/docs/windows.md#standalone-cli

If your server is running 0.3.1 or newer and still sees this error message, please share the server log and I'll reopen the issue.
