### ISSUE TITLE
Anythingllm says This feature is disabled on Linux operating systems

### ISSUE THREAD

**Issue by HSTe** [ollama/ollama#6158]
### What is the issue?

After a reinstallation on my fedora workstation I can't use anythingllm llm provider it says:
"This feature is disabled on Linux operating systems" 
This worked on the system setup I had in june.
Has something happend with linux support on Anythingllm?

### OS

Linux

### GPU

Nvidia

### CPU

Intel

### Ollama version

0.3.3

**Comment by rick-github** [comment]
Sounds like an issue for https://github.com/Mintplex-Labs/anything-llm/issues

**Comment by dhiltgen** [comment]
If there's some defect related to Ollama, let us know.
