### ISSUE TITLE
sorting issues on website 

### ISSUE THREAD

**Issue by TheVegeta** [ollama/ollama#6161]
Hello there, can someone please guide me to the website's code so I can fix the sorting issue? As you can see in the image below, it's not sorting correctly. After fixing it, I'll create a new pull request.

![ollama_](https://github.com/user-attachments/assets/a0c8ecfd-a172-479f-a38a-e1cf4b0477c2)

**Comment by rick-github** [comment]
https://github.com/ollama/ollama/issues/5942

**Comment by TheVegeta** [comment]
@rick-github, I can fix the sorting issue myself, so can you please guide me to the website's code?

**Comment by rick-github** [comment]
Sorry, I don't know where the website repo is.

**Comment by igorschlum** [comment]
The sorting is based on the last upload of a model, not on the update of the description, which also has its own logic.

**Comment by jmorganca** [comment]
Thanks for the issue. Merging with https://github.com/ollama/ollama/issues/5942
