### ISSUE TITLE
Number of LLMs in Ollama Libary

### ISSUE THREAD

**Issue by Gautamshahi** [ollama/ollama#6162]
### What is the issue?

How can we calculate the number of LLMs in the Ollama library?

**Comment by rick-github** [comment]
Download them all, then run
```
 ollama list | grep -v "^NAME" | wc -l
```
jk.
```
for p in {1..133} ; do wget -qO - https://ollama.com/search?p=$p | sed -ne 's/^\s*\([0-9][0-9]*\)<.*Tags.*/\1/p' ; done | awk '{sum+=$1}END{print sum}'
8530
```
That's all variations of quantization.  If you just wanted the count of model families, there's 133 pages and 25 models per page, so 3325.  That includes model uploaded by ollama users.

**Comment by Gautamshahi** [comment]
thanks, it really helped, but what is 8530 from grep command?

**Comment by rick-github** [comment]
8530 is the number of tagged models in the ollama library, eg gemma2:2b, gemma2:2b-instruct-fp16, gemma2:2b-instruct-q2_K, etc.  The grep command is just a joke, to make that work you would need to download terabytes of models, which is infeasible for most users.

**Comment by Gautamshahi** [comment]
okay thank you

**Comment by igorschlum** [comment]
@Gautamshahi, now that you have your answer, could you please close the issue? If you have questions like this, it's better to use Discord rather than the bug reports on GitHub, which are dedicated to solvable problems. When people see a high number of reported bugs, they might become concerned.

**Comment by FellowTraveler** [comment]
@Gautamshahi please close this issue.
