### ISSUE TITLE
GPU Usage Never Exceeds 70% When Using LLaMA 3:8B with Ollama

### ISSUE THREAD

**Issue by drspam1991** [ollama/ollama#6163]
### What is the issue?

When using the Ollama tool with the LLaMA 3:8B model and all 33 offload layers loaded on the GPU, the GPU usage never goes over 70%. This seems suboptimal and may indicate an issue with how resources are being utilized.

![Screenshot from 2024-08-04 17-24-02](https://github.com/user-attachments/assets/81d3a8e1-89f0-4d21-9e2c-141db55f585e)

### OS

Linux

### GPU

Nvidia

### Ollama version

0.2.8

**Comment by rick-github** [comment]
What's the prompt?  What's the CPU usage?  What's the output of `nvidia-smi -q -d POWER,TEMPERATURE`?  What's the output of `nvidia-smi -q | grep -A9 'Clocks Throttle Reasons'`?

**Comment by drspam1991** [comment]
**I use 'hey' load test tool to send parallel request to ollama with this prompt:**
'_Consider the following Text and list of Topics: \n Text: 'ﺐﯿﺴﺘﻤﯿﻧ ﺩﻭﺮﻫ ﺡﺭﺎﺟ ﺖﻫﺭﺎﻧ ﺏﺍ ﻡﻮﺿﻮﻋ «ﻪﻧﺭ ﻡﺩﺮﻧ ﻭ ﻢﻋﺎﺻﺭ» ﺞﻤﻌﻫ ـ ۱۵ ﺖﯾﺮﻣﺎﻫ ـ ﺩﺭ ﺡﺎﻠﯾ ﺏﺮﮔﺯﺍﺭ ﺵﺩ ﮏﻫ ﻦﺴﺒﺗ ﺐﻫ ﺩﻭﺮﻫ ﻪﻓﺪﻬﻣ ـ ﺏﺍ ﮎﺎﻬﺷ ﺩﺭ ﺍﺮﻗﺎﻣ ﻦﻫﺎﯿﯾ ﻡﺯﺎﯾﺪﻫ ﻭ ﻑﺭﻮﺷ ﻪﻣﺭﺎﻫ ﺏﻭﺪﻫ ﺎﺴﺗ؛ ﺎﯿﻧ ﺵﺭﺎﯿﻃ ﺎﻠﺒﺘﻫ ﺩﺭ ﺡﺎﻠﯾ ﺮﻘﻣ ﺥﻭﺭﺪﻫ ﺎﺴﺗ ﮏﻫ ﺩﺭ ﺩﻭﺮﻫ ﻪﻓﺪﻬﻣ ﺂﺛﺍﺭ ﺵﺎﺨﺼﯾ ﻪﻤﭼﻮﻧ ﺩﻭ ﺎﺛﺭ ﺍﺯ ﺲﻫﺭﺎﺑ ﺲﭙﻫﺮﯾ ﮏﻫ ﻢﻌﻣﻭﻻ ﺮﻘﻣ\u200cﻩﺎﯾ ﺡﺭﺎﺠﯾ\u200cﻩﺍ ﺭﺍ ﺝﺎﺒﻫ\u200cﺝﺍ ﻢﯾ\u200cﮏﻨﻧﺩ، ﺐﻫ ﺡﺭﺎﺟ ﮒﺫﺎﺸﺘﻫ ﺵﺪﻫ ﺏﻭﺩ.\n' \n Topics: ( ﻦﻗﺎﺸﯾ|ﻢﺠﺴﻤﻫ\u200cﺱﺍﺰﯾ|ﻊﮐﺎﺴﯾ|ﻁﺭﺎﺤﯾ|ﻪﻧﺭ ﺪﯿﺠﯿﺗﺎﻟ|ﻪﻧﺮﻫﺎﯾ ﺖﺠﺴﻤﯾ|ﺖﺋﺎﺗﺭ|ﺮﻘﺻ|ﻡﻮﺴﯿﻘﯾ|ﺎﭘﺭﺍ|ﻪﻧﺮﻫﺎﯾ ﻦﻣﺎﯿﺸﯾ|ﺶﻋﺭ|ﺩﺎﺴﺗﺎﻧ|ﻎﯾﺭﺩﺎﺴﺗﺎﻨﯾ|ﻦﻣﺎﯿﺸﻧﺎﻤﻫ|ﺍﺪﺒﯾﺎﺗ|ﺞﻨﺒﺷ ﻪﻧﺮﯾ|ﺲﺒﮐ ﻪﻧﺮﯾ|ﺱﺎﻨﺳﻭﺭ|ﺥﺮﯾﺩ ﻭ ﻑﺭﻮﺷ ﺂﺛﺍﺭ ﻪﻧﺮﯾ|ﮏﺗﺎﺑ|ﺭﻮﯾﺩﺍﺩ ﻭ ﺞﺸﻧﻭﺍﺮﻫ|ﻁﺭﺎﺤﯾ ﮒﺭﺎﻔﯿﮐ|ﻁﺭﺎﺤﯾ ﺩﺎﺨﻠﯾ|ﻁﺭﺎﺤﯾ ﺺﻨﻌﺘﯾ|ﻁﺭﺎﺤﯾ ﻡﺩ|ﺺﻧﺎﯿﻋ ﺪﺴﺘﯾ|ﻢﻌﻣﺍﺮﯾ|ﻪﻧﺮﻫﺎﯾ ﮎﺍﺮﺑﺭﺪﯾ|ﺖﺟﺍﺮﺗ ﺐﯿﻧ\u200cﺎﻠﻤﻠﻟ|ﺐﯿﮐﺍﺮﯾ|ﺂﻣﻭﺰﺷ|ﺝﺭﺎﺌﻣ ﻡﺎﻠﯾ|ﮏﺗﺎﺑ|ﻡﺎﻠﯾﺎﺗ|ﺕﻭﺮﻣ|ﻭﺍﺭﺩﺎﺗ/ﺹﺍﺩﺭﺎﺗ|ﺍﺭﺯ|ﺏﺎﻨﮐﺩﺍﺮﯾ|ﺢﺳﺎﺑﺩﺍﺮﯾ|ﺏﻼﮑﭽﯿﻧ|ﺎﻣﻼﮐ ﻭ ﻢﺴﺘﻏﻼﺗ|ﻒﻟﺯﺎﺗ ﮒﺭﺎﻨﺒﻫﺍ|ﻭﺯﺍﺮﺗ ﺎﻘﺘﺻﺍﺩ|ﻭﺯﺍﺮﺗ ﺺﻨﻌﺗ|ﺹﺭﺎﻔﯾ|ﮎﺍﺮﮔﺯﺍﺭ|ﺏﺍﺯﺍﺮﯾﺎﺒﯾ|ﺏﺍﺯﺍﺭ ﮎﺍﺭ|ﻢﻫﺎﺟﺮﺗ ﮎﺍﺮﯾ|ﺢﻗﻮﻗ ﻭ ﻡﺯﺎﯾﺍ|ﺐﯿﻤﻫ|ﺱﺮﻣﺎﯿﻫ\u200cﮒﺫﺍﺮﯾ|ﭗﺳ\u200cﺎﻧﺩﺍﺯ|ﺏﺍﺰﻨﺸﺴﺘﮕﯾ|ﺎﻣﻭﺭ ﻡﺎﻠﯾ ﺶﺨﺼﯾ|ﺏﻭﺮﺳ|ﻑﺍﺮﮑﺳ|ﺮﻣﺯ ﺍﺭﺯ|ﻁﻻ|ﺏﺍﺯﺍﺮﻫﺎﯾ ﻡﺎﻠﯾ ). \n Choose most related topic(s) to the Text from the list. Your output must be topics name from the list with format [t1, ...] and say nothing else._'

**This is my CPU usage during test:**
![Screenshot from 2024-08-04 21-19-24](https://github.com/user-attachments/assets/f26b699e-9f20-43ee-8dde-c23e367e9fdd)


**nvidia-smi -q -d POWER,TEMPERATURE**
==============NVSMI LOG==============

Timestamp                                 : Sun Aug  4 21:13:32 2024
Driver Version                            : 545.29.06
CUDA Version                              : 12.3

Attached GPUs                             : 1
GPU 00000000:0B:00.0
    Temperature
        GPU Current Temp                  : 54 C
        GPU T.Limit Temp                  : N/A
        GPU Shutdown Temp                 : 100 C
        GPU Slowdown Temp                 : 97 C
        GPU Max Operating Temp            : 88 C
        GPU Target Temperature            : 83 C
        Memory Current Temp               : N/A
        Memory Max Operating Temp         : N/A
    GPU Power Readings
        Power Draw                        : 2.93 W
        Current Power Limit               : 225.00 W
        Requested Power Limit             : 225.00 W
        Default Power Limit               : 225.00 W
        Min Power Limit                   : 125.00 W
        Max Power Limit                   : 280.00 W
    Power Samples
        Duration                          : 52.45 sec
        Number of Samples                 : 119
        Max                               : 42.78 W
        Min                               : 2.88 W
        Avg                               : 4.44 W
    GPU Memory Power Readings 
        Power Draw                        : N/A
    Module Power Readings
        Power Draw                        : N/A
        Current Power Limit               : N/A
        Requested Power Limit             : N/A
        Default Power Limit               : N/A
        Min Power Limit                   : N/A
        Max Power Limit                   : N/A


and `nvidia-smi -q | grep -A9 'Clocks Throttle Reasons'` has not any result

**Comment by rick-github** [comment]
Output of `nvidia-smi -q -d POWER,TEMPERATURE,PERFORMANCE` while the test is running?  What is `OLLAMA_NUM_PARALLEL` set to?  Can you include some [server logs](https://github.com/ollama/ollama/blob/main/docs/troubleshooting.md#how-to-troubleshoot-issues)?

**Comment by igorschlum** [comment]
@drspam1991 did you tried with another model than LLama3:8B? What are the results?

**Comment by drspam1991** [comment]
> Output of `nvidia-smi -q -d POWER,TEMPERATURE,PERFORMANCE` while the test is running? What is `OLLAMA_NUM_PARALLEL` set to? Can you include some [server logs](https://github.com/ollama/ollama/blob/main/docs/troubleshooting.md#how-to-troubleshoot-issues)?

**This is the result of** `nvidia-smi -q -d POWER,TEMPERATURE,PERFORMANCE` **while test is running:**

==============NVSMI LOG==============

Timestamp                                 : Mon Aug  5 12:57:09 2024
Driver Version                            : 545.29.06
CUDA Version                              : 12.3

Attached GPUs                             : 1
GPU 00000000:0B:00.0
    Performance State                     : P2
    Clocks Event Reasons
        Idle                              : Not Active
        Applications Clocks Setting       : Not Active
        SW Power Cap                      : Active
        HW Slowdown                       : Not Active
            HW Thermal Slowdown           : Not Active
            HW Power Brake Slowdown       : Not Active
        Sync Boost                        : Not Active
        SW Thermal Slowdown               : Not Active
        Display Clock Setting             : Not Active
    Temperature
        GPU Current Temp                  : 77 C
        GPU T.Limit Temp                  : N/A
        GPU Shutdown Temp                 : 100 C
        GPU Slowdown Temp                 : 97 C
        GPU Max Operating Temp            : 88 C
        GPU Target Temperature            : 83 C
        Memory Current Temp               : N/A
        Memory Max Operating Temp         : N/A
    GPU Power Readings
        Power Draw                        : 157.68 W
        Current Power Limit               : 225.00 W
        Requested Power Limit             : 225.00 W
        Default Power Limit               : 225.00 W
        Min Power Limit                   : 125.00 W
        Max Power Limit                   : 280.00 W
    Power Samples
        Duration                          : 2.37 sec
        Number of Samples                 : 119
        Max                               : 246.08 W
        Min                               : 60.98 W
        Avg                               : 159.74 W
    GPU Memory Power Readings 
        Power Draw                        : N/A
    Module Power Readings
        Power Draw                        : N/A
        Current Power Limit               : N/A
        Requested Power Limit             : N/A
        Default Power Limit               : N/A
        Min Power Limit                   : N/A
        Max Power Limit                   : N/A



**And this is the ollama log:**
[ollama.log](https://github.com/user-attachments/files/16493857/ollama.log)

**Comment by rick-github** [comment]
It looks there is some clock throttling happening: `SW Power Cap : Active`.  I'm not sure this fully explains the low GPU usage, but it's worth looking in to.

From the nvidia-smi manual page:
```
SW Power Cap SW Power Scaling algorithm is reducing the clocks below
 requested clocks because the GPU is consuming too much
 power. E.g. SW power cap limit can be changed with
 nvidia-smi --power-limit=
```
But you may not be able to do anything about this by adjusting the power-limit:
```
   -pl, --power-limit=POWER_LIMIT
       Specifies maximum power limit in watts.  Accepts integer and floating point numbers.
       Only on supported devices from Kepler family.  Requires administrator privileges.
       Value  needs  to be between Min and Max Power Limit as reported by nvidia-smi.
```
From Wikipedia:

Kepler is the codename for a [GPU](https://en.wikipedia.org/wiki/GPU) [microarchitecture](https://en.wikipedia.org/wiki/Microarchitecture) developed by [Nvidia](https://en.wikipedia.org/wiki/Nvidia), first introduced at retail in April 2012,[[1]](https://en.wikipedia.org/wiki/Kepler_(microarchitecture)#cite_note-1) as the successor to the [Fermi](https://en.wikipedia.org/wiki/Fermi_(microarchitecture)) microarchitecture. Kepler was Nvidia's first microarchitecture to focus on [energy efficiency](https://en.wikipedia.org/wiki/Efficient_energy_use). Most [GeForce 600 series](https://en.wikipedia.org/wiki/GeForce_600_series), most [GeForce 700 series](https://en.wikipedia.org/wiki/GeForce_700_series), and some [GeForce 800M series](https://en.wikipedia.org/wiki/GeForce_800M_series) GPUs were based on Kepler, all manufactured in 28 nm. Kepler found use in the GK20A, the GPU component of the [Tegra K1](https://en.wikipedia.org/wiki/Tegra_K1) [SoC](https://en.wikipedia.org/wiki/System_on_a_chip), and in the [Quadro](https://en.wikipedia.org/wiki/Nvidia_Quadro) Kxxx series, the Quadro NVS 510, and [Tesla](https://en.wikipedia.org/wiki/Nvidia_Tesla) computing modules.

From [GEFORCE_RTX_2080_User_Guide.pdf](https://www.nvidia.com/content/geforce-gtx/GEFORCE_RTX_2080_User_Guide.pdf):

The GeForce® RTX 2080 is powered by the all-new NVIDIA Turing™ architecture to give you incredible new levels of gaming realism, speed, power efficiency, and immersion. This is graphics reinvented.

I also noticed in your first screencap of nvtop that your temperature was at 81°C, and your `GPU Target Temperature` is 83°C, so you may also be experiencing `SW Thermal Slowdown`.

You can monitor the GPU temperature, power draw and clock rate in nvtop by adjusting the settings in Setup > Chart > Displayed all GPUs.

**Comment by pdevine** [comment]
@drspam1991 did you end up sorting this out?
