### ISSUE TITLE
Unable to run / pull llama3 model

### ISSUE THREAD

**Issue by Maha-vignesh09** [ollama/ollama#6174]
### What is the issue?

Error: pull model manifest: Get "https://registry.ollama.ai/v2/library/llama3/manifests/latest": proxyconnect tcp: dial tcp: lookup https on 100.76.191.242:53: no such host
when trying to pull llama3 

[root@fsgbu-mum-918 ~]# export https_proxy=https://www-***.com:80
[root@fsgbu-mum-918 ~]# export https_proxy=https://www-***.com:80*
[root@fsgbu-mum-918 ~]# curl https://registry.ollama.ai/v2/library/llama3/manifests/latest
{"schemaVersion":2,"mediaType":"application/vnd.docker.distribution.manifest.v2+json","config":{"digest":"sha256:3f8eb4da87fa7a3c9da615036b0dc418d31fef2a30b115ff33562588b32c691d","mediaType":"application/vnd.docker.container.image.v1+json","size":485},"layers":[{"digest":"sha256:6a0746a1ec1aef3e7ec53868f220ff6e389f6f8ef87a01d77c96807de94ca2aa","mediaType":"application/vnd.ollama.image.model","size":4661211424},{"digest":"sha256:4fa551d4f938f68b8c1e6afa9d28befb70e3f33f75d0753248d530364aeea40f","mediaType":"application/vnd.ollama.image.license","size":12403},{"digest":"sha256:8ab4849b038cf0abc5b1c9b8ee1443dca6b93a045c2272180d985126eb40bf6f","mediaType":"application/vnd.ollama.image.template","size":254},{"digest":"sha256:577073ffcc6ce95b9981eacc77d1039568639e5638e83044994560d9ef82ce1b","mediaType":"application/vnd.ollama.image.params","size":110}]}
[root@fsgbu-mum-918 ~]# ollama run llama3
pulling manifest
Error: pull model manifest: Get "https://registry.ollama.ai/v2/library/llama3/manifests/latest": proxyconnect tcp: dial tcp: lookup https on 100.76.191.242:53: no such host

### OS

Linux

### GPU

Other

### CPU

AMD

### Ollama version

0.3.2

**Comment by igorschlum** [comment]
@Maha-vignesh09 Could you please upgrade Ollama to version 0.3.3? If it still does not work, are you sure you want to work with Llama3? Llama3.1 works better. Could you try with Llama3.1 to see if pulling works?

**Comment by Maha-vignesh09** [comment]
@igorschlum I have tried to run Llama3.1, still facing similar error. However, i am able to run Llama3.1 on my windows. Is there any way to copy the downloaded model to Linux.

I have tried copying the model folder from my windows to "systempath/.ollama/model" folder in the linux machine, it still tries to pull the manifest when i run on linux, any way to stop this activity of model download and use the one downloaded and copied from Windows

**Comment by Maha-vignesh09** [comment]
Thanks @igorschlum , I am able to proceed with Llama3.1

**Comment by igorschlum** [comment]
@Maha-vignesh09 Nice! Could you please close the issue so we don't reach the 1000 issue barrier too soon?

**Comment by wipas-p** [comment]
@igorschlum 

root@u22gpu:~# ollama -v
ollama version is 0.3.3

root@u22gpu:~# ollama pull llama3.1:70b
pulling manifest
pulling aa81b541aae6... 100% ▕████████████████████████████████████████████████████████████████████████████████████████████████▏  39 GB
pulling 8cf247399e57... 100% ▕████████████████████████████████████████████████████████████████████████████████████████████████▏ 1.7 KB
pulling f1cd752815fc... 100% ▕████████████████████████████████████████████████████████████████████████████████████████████████▏  12 KB
pulling 56bb8bd477a5... 100% ▕████████████████████████████████████████████████████████████████████████████████████████████████▏   96 B
pulling 3c1c2d3df5b3... 100% ▕████████████████████████████████████████████████████████████████████████████████████████████████▏  486 B
verifying sha256 digest
Error: digest mismatch, file must be downloaded again: want sha256:aa81b541aae64003237a98f9f11c01e091368fda4d61ea5085bd66f83816be9f, got sha256:58d5cbd7b6f69136bd461a1a545d58fc07814fc8274fbcb23af3b2f4a717cfcc

Could you help to fix these issue?

**Comment by igorschlum** [comment]
Hi @wipas-p, it's possible that you were trying to download the model while it was being updated. Could you try restarting your computer and then attempt to download the model again? Restarting should automatically cancel any partial downloads.

**Comment by wipas-p** [comment]
> Hi @wipas-p, it's possible that you were trying to download the model while it was being updated. Could you try restarting your computer and then attempt to download the model again? Restarting should automatically cancel any partial downloads.

issue still exist.


 08:35:00 up 2 min,  2 users,  load average: 0.43, 0.36, 0.15
root@u22gpu:/etc/systemd/system# ollama pull llama3.1:70b
pulling manifest
pulling a677b4a4b70c... 100% ▕████████████████████████████████████████████████████████████████████████████████████████████████▏  39 GB
pulling 11ce4ee3e170... 100% ▕████████████████████████████████████████████████████████████████████████████████████████████████▏ 1.7 KB
pulling 0ba8f0e314b4... 100% ▕████████████████████████████████████████████████████████████████████████████████████████████████▏  12 KB
pulling 56bb8bd477a5... 100% ▕████████████████████████████████████████████████████████████████████████████████████████████████▏   96 B
pulling 654440dac7f3... 100% ▕████████████████████████████████████████████████████████████████████████████████████████████████▏  486 B
verifying sha256 digest
Error: digest mismatch, file must be downloaded again: want sha256:a677b4a4b70c45e702b1d600f7905e367733c53898b8be60e3f29272cf334574, got sha256:40f44111db01aa313a8cef9786b336249246a03fe60083fd647f2112d7fb5db9
root@u22gpu:/etc/systemd/system# ollama -v
ollama version is 0.3.4

:(

**Comment by igorschlum** [comment]
Hi @wipas-p 70b models have ben updated Again Yesterday. So please try Again

´´´bash
Ollama rm llama3.1:70b
Ollama pull llama3.1:70b
´´´

I think that we are facing an issue with cached blob files (parts of llm) in cloudflare as llama3.1 where updated without versioning.

Try again and it could work.
