### ISSUE TITLE
Fail when calling ollama.embeddings function

### ISSUE THREAD

**Issue by weixu-tf4** [ollama/ollama#6175]
### What is the issue?

I was follow the example by https://ollama.com/blog/embedding-models
But, it allways fail when running:  response = ollama.embeddings(model='mxbai-embed-large', prompt=d)
I don't no WHY

### OS

Windows

### GPU

Nvidia

### CPU

Intel

### Ollama version

0.3.3

**Comment by rick-github** [comment]
If you can provide the code you are running, the error message you receive, and the [server logs](https://github.com/ollama/ollama/blob/main/docs/troubleshooting.md#how-to-troubleshoot-issues) when the error occurred, it will make debugging easier.

**Comment by royjhan** [comment]
I was unable to reproduce the issue, running the example below

>>> import ollama
>>> response = ollama.embeddings(model='mxbai-embed-large', prompt="hello")
>>> print(response)

Can you provide more information on the error? Namely the exact code you are running and the error message.

**Comment by jmorganca** [comment]
Hi @weixu-tf4 thanks for the issue. It will be hard to debug this issue to the finish line without more info. Feel free to add to this issue and I will re-open it so we can make sure you can generate embeddings :)
