### ISSUE TITLE
run OI with OLLAMA SERVER IN NETWORK

### ISSUE THREAD

**Issue by RM-S2** [ollama/ollama#6177]
### What is the issue?

i try to run OI with ollama server in another server computer in my network.and the command start OI is:
interpreter --model  ollama/llama3.1 --api_base "http://192.168.3.13:11434" --api_key "fake_key"
but i get error say cant fine ollama in my computer ,what i thought is wrong because  OI shoud find ollama in my server computer.
what should i do ?

### OS

Windows

### GPU

Nvidia

### CPU

Intel

### Ollama version

0.1.32

**Comment by rick-github** [comment]
By default ollama binds to `localhost`, ie `127.0.0.1`.  If you want it to be available to other computers, you need to set `OLLAMA_HOST=0.0.0.0:11434` in the server environment.  Also, ollama version 0.1.32 will not support llama3.1, you need to upgrade to 0.3.0 or newer.

**Comment by RM-S2** [comment]
It work well now.thank a lot.
