### ISSUE TITLE
LINE FEED problems in recent commit

### ISSUE THREAD

**Issue by FellowTraveler** [ollama/ollama#6183]
### What is the issue?

Since I grabbed the latest code, it IMMEDIATELY tells me that I have unstaged changes and won't let me checkout other branches. Also makes it impossible to rebase, etc. Git stash doesn't fix it. There is some kind of line feed issue probably in a very recent merge.
**I can't be the only one who has noticed this problem.**

### OS

macOS

### GPU

Apple

### CPU

Apple

### Ollama version

LATEST main branch

**Comment by rick-github** [comment]
https://github.com/ollama/ollama/pull/6167

**Comment by FellowTraveler** [comment]
**LOOK at this! What the hell is going on?**

<img width="774" alt="image" src="https://github.com/user-attachments/assets/204f5eb7-d530-4c73-a022-e374f5f5cce5">

**Comment by Nicholas42** [comment]
I have the same problem, it seems to be caused by the line `* text eol=lf` line in `.gitattributes`. I fix it in #6235.

**Comment by igorschlum** [comment]
Hi @FellowTraveler
the merge was approve on Github. Could you try and if git works well on your Mac with Ollama, please close this issue.

**Comment by FellowTraveler** [comment]
Looks fixed.
