### ISSUE TITLE
Add InternLM 2.5 family of models

### ISSUE THREAD

**Issue by nviraj** [ollama/ollama#6184]
Please add [InternLM 2.5 family of models](https://huggingface.co/collections/internlm/internlm25-66853f32717072d17581bc13) to registry. Comes in 1.8, 7 and 20b sizes with both base and chat models. 

While [this](https://ollama.com/internlm/internlm2.5) exists, at the moment it is F16 only.

Thank you!

**Comment by wszgrcy** [comment]
![image](https://github.com/user-attachments/assets/a7897a9f-2338-4ea5-b824-ec1d1d427572)
https://ollama.com/library/internlm2/tags

**Comment by nviraj** [comment]
> https://ollama.com/library/internlm2/tags

Apologies, I had assumed that tag was for v2 rather than v2.5 (Similar to llama3 and llama3.1)
However 1.8 and 20b variants are still missing. Thanks.

**Comment by nviraj** [comment]
Thank you!
