### ISSUE TITLE
Custom models without reasoning using gpu

### ISSUE THREAD

**Issue by CyanMystery** [ollama/ollama#6191]
### What is the issue?

I downloaded this model **https://www.modelscope.cn/models/LLM-Research/Mistral-7B-Instruct-v0.3-GGUF/files** Create from modelfiles but do not use GPU reasoning, direct ollama run mistral can be used normally

### OS

Windows

### GPU

Nvidia

### CPU

Intel

### Ollama version

0.3.0

**Comment by CyanMystery** [comment]
modelfile:

FROM Mistral-7B-Instruct-v0.3.fp16.gguf
PARAMETER stop "[INST]"
PARAMETER stop "[/INST]"


TEMPLATE """{{- if .Messages }}
{{- range $index, $_ := .Messages }}
{{- if eq .Role "user" }}
{{- if and (eq (len (slice $.Messages $index)) 1) $.Tools }}[AVAILABLE_TOOLS] {{ $.Tools }}[/AVAILABLE_TOOLS]
{{- end }}[INST] {{ if and $.System (eq (len (slice $.Messages $index)) 1) }}{{ $.System }}

{{ end }}{{ .Content }}[/INST]
{{- else if eq .Role "assistant" }}
{{- if .Content }} {{ .Content }}
{{- else if .ToolCalls }}[TOOL_CALLS] [
{{- range .ToolCalls }}{"name": "{{ .Function.Name }}", "arguments": {{ .Function.Arguments }}}
{{- end }}]
{{- end }}</s>
{{- else if eq .Role "tool" }}[TOOL_RESULTS] {"content": {{ .Content }}} [/TOOL_RESULTS]
{{- end }}
{{- end }}
{{- else }}[INST] {{ if .System }}{{ .System }}

{{ end }}{{ .Prompt }}[/INST]
{{- end }} {{ .Response }}
{{- if .Response }}</s>
{{- end }}"""



run command:
ollama create mymodel -f ./Modelfile
ollama run mymodel

**Comment by rick-github** [comment]
[Server  logs](https://github.com/ollama/ollama/blob/main/docs/troubleshooting.md#how-to-troubleshoot-issues) will help with debugging.

**Comment by jmorganca** [comment]
Hi @CyanMystery have you tried the Mistral 7b in the library? https://ollama.com/library/mistral it should function correctly including with tool calling. Let me know if that doesn't help
