### ISSUE TITLE
llm decode error: 500 Internal Server Error - detokenize doesn't handle unicode characters from server.cpp properly on windows

### ISSUE THREAD

**Issue by iBog** [ollama/ollama#6196]
### What is the issue?

Happened few times when same chat log (history) was used after local model was switched.
For example chat was started with "llava:7b-v1.6" when switched to "llama3.1:latest" without clear context array (not sure with exact same llm's pair)

LOG:
```
time=2024-08-05T14:54:58.212+03:00 level=INFO source=server.go:623 msg="llama runner started in 2.92 seconds"
time=2024-08-05T14:54:58.214+03:00 level=INFO source=server.go:1028 msg="llm decode error: 500 Internal Server Error\n[json.exception.type_error.316] invalid UTF-8 byte at index 181: 0x6C"
[GIN] 2024/08/05 - 14:54:58 | 500 |    3.3204013s |       127.0.0.1 | POST     "/api/generate"
```

### OS

Windows

### GPU

Nvidia

### CPU

Intel

### Ollama version

0.3.3

**Comment by dhiltgen** [comment]
My suspicion is the subprocess is emitting unicode characters in a way that the json deserializer isn't expecting.  This looks to be happening in Detokenize.   We're switching this implementation to cgo in an upcoming release which should resolve this. #5034
