### ISSUE TITLE
 Request to Add JAIS 70B Model

### ISSUE THREAD

**Issue by umar052001** [ollama/ollama#6198]
**Description:**
I would like to suggest adding the JAIS 70B model to Ollama. The model is available on Hugging Face [here](https://huggingface.co/inceptionai/jais-adapted-70b) and offers significant advancements in Arabic-English natural language processing. It would be a valuable addition for users interested in Arabic-centric NLP applications.

**Reason for Request:**
The JAIS 70B model is specifically designed to handle complex Arabic-English tasks, and its availability on Ollama would allow for broader testing and application in various use cases. This addition would enhance the platform’s offerings for users working with Arabic and bilingual datasets.

**Reference:**
- [JAIS 70B on Hugging Face](https://huggingface.co/inceptionai/jais-adapted-70b)

**Additional Information:**
This model was recently launched by Inception under the G42 group and has been well-received for its large-scale capabilities and efficient training on a vast dataset, including 330 billion Arabic tokens.

Thank you for considering this suggestion!

**Comment by rajaz26** [comment]
This model could provide substantial benefits for Arabic-centric application. It would be a fantastic addition 💯

**Comment by MZainMehar** [comment]
Fantastic suggestion! The JAIS 70B model is a game-changer for Arabic-English NLP, and it’s great to see such a valuable tool being proposed for Ollama.

**Comment by hammadrao891** [comment]
Would be a great addition

**Comment by ezzcodeezzlife** [comment]
Any progress on this? 🚀

**Comment by umar052001** [comment]
> Any progress on this? 🚀

Yeah, there is a 8b param version available [here ](https://ollama.com/jwnder/jais-adaptive)
Also, now you can run any hugging face model with ollama locally so closing this issue. You can read about it [here](https://huggingface.co/docs/hub/en/ollama).
