### ISSUE TITLE
The Quickstart section in README is missing the 'ollama start' command

### ISSUE THREAD

**Issue by yurivict** [ollama/ollama#6204]
### What is the issue?

People who run ollama for the first time wouldn't know that 'ollama start' needs to be run.

### OS

Linux

### CPU

Intel

### Ollama version

0.3.4

**Comment by rick-github** [comment]
If the user has installed via the methods listed on the README, the ollama service should be started automatically.  The manual install instructions recommend installing a service to run the downloaded file, but you are right that if they skip the recommendations, the ollama server won't be running.

**Comment by yurivict** [comment]
I installed from the FreeBSD port which builds from source. The user only has the ```ollama``` command.

**Comment by cfjedimaster** [comment]
I just ran into this as well. Did the Linux install. Everything looked fine. `ollama` at the CLI returned a list of commands. I went to the quick start and had this exact issue.

**Comment by cfjedimaster** [comment]
As an aside, `start` isn't even listed in the available commands when you type `ollama`. Making a PR now for a suggested fix.

**Comment by rick-github** [comment]
If you run `ollama start` it will start the ollama server in your environment - models will be stored in ~/.ollama/models instead of /usr/share/ollama/.ollama/models, environment variable changes made in the ollama service file won't affect the server, etc.  If you did the `curl -fsSL https://ollama.com/install.sh | sh` method of install and the server didn't start, it would be better to figure out why that failed.  What does `journalctl -u ollama --no-pager` show?

**Comment by cfjedimaster** [comment]
It returns `No journal files were found`. I'll add that when I ran the install script, it certainly seemed like everything went ok. I don't remember any issues.

**Comment by rick-github** [comment]
What Linux distro are you using?

**Comment by cfjedimaster** [comment]
Ubuntu 22.04.4 LTS, via WSL.

**Comment by rick-github** [comment]
What's the output of `systemctl status ollama.service`?

**Comment by cfjedimaster** [comment]
```
System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to connect to bus: Host is down
```

**Comment by rick-github** [comment]
OK, seems systemd is not working, which would explain why the ollama server wasn't started.  Not sure why, was it desktop or server image (or something special for WSL)?

**Comment by cfjedimaster** [comment]
Eh... this I can't say. I've been a WSL user for 5+ years or so, but am mostly a casual user of Linux. I prefer it over cmd.exe, PowerShell, etc, and know it better, but just enough to be dangerous. ;)

**Comment by cfjedimaster** [comment]
Looks like systemd support in WSL is -very- new, https://learn.microsoft.com/en-us/windows/wsl/systemd, and therefore may be why it's not running on my side.

**Comment by cfjedimaster** [comment]
In theory, and this could be a new issue, shouldn't the install script have thrown an error of some sort? I'm looking at the output now and nothing at all seems amiss:

```
ray@Hoth:~/projects/raymondcamden2023$ curl -fsSL https://ollama.com/install.sh | sh
>>> Installing ollama to /usr/local
[sudo] password for ray:
>>> Downloading Linux amd64 bundle
######################################################################## 100.0%##O#-#
######################################################################## 100.0%
>>> Creating ollama user...
>>> Adding ollama user to render group...
>>> Adding ollama user to video group...
>>> Adding current user to ollama group...
>>> Creating ollama systemd service...
>>> Nvidia GPU detected.
>>> The Ollama API is now available at 127.0.0.1:11434.
>>> Install complete. Run "ollama" from the command line.
>>> The Ollama API is now available at 127.0.0.1:11434.
>>> Install complete. Run "ollama" from the command line.
```

**Comment by cfjedimaster** [comment]
FYI, I followed the directions at the link above and systemd is now running, and the command you shared earlier now shows the Ollama Service.

**Comment by rick-github** [comment]
Yes, it looks like an issue for the installer, it checks for a running systemd but if it's not, the installer doesn't notify the user that the service won't be automatically started.

**Comment by cfjedimaster** [comment]
I'll file a new bug. I do think the QS could use a quick note (like what I added in my PR) though. :)

**Comment by rick-github** [comment]
The problem with having other ways to start the server is that it multiplies the support burden.   For example, if you file a bug with ollama, one of the frequent responses is to ask for logs, and as demonstrated, the logs are not available if you `ollama start`.

Is there any reason you are not using the windows version of ollama?

**Comment by cfjedimaster** [comment]
But - don't you agree that if the script tries to use systemd and fails, it should report it? Obviously the issue was on my side, but w/ no output from the script about the failure, it took longer to debug.

As for your second question - I generally use the linux version of CLIs as I spend my time in WSL usually.

**Comment by rick-github** [comment]
Yes, I agree that the script should notify the user that the system won't perform as expected due to the lack of a working systemd.

**Comment by dhiltgen** [comment]
BSD support isn't part of the official release - this is tracked via #1102 

The quickstart guide is intended to cover officially supported binary distributions.  It sounds like there is a port out there for BSD which does not include any system service configuration, nor documentation on how to use it.  The requested docs seem like they should belong there.

When building from source, we do discuss the server command (start is an alias) in the main readme - https://github.com/ollama/ollama/tree/main?tab=readme-ov-file#building

**Comment by yurivict** [comment]
> It sounds like there is a port out there for BSD which does not include any system service configuration, nor documentation on how to use it.

Wrong. The FreeBSD port comes with this initial documentation packaged as a package message:
https://cgit.freebsd.org/ports/tree/misc/ollama/pkg-message

My suggestion was for people who attempt to install ollama using this repository.
