### ISSUE TITLE
support for llama3 and llama3.1 uncensored 

### ISSUE THREAD

**Issue by olumolu** [ollama/ollama#6209]
https://huggingface.co/Orenguteng/Llama-3-8B-Lexi-Uncensored-GGUF
https://huggingface.co/Orenguteng/Llama-3.1-8B-Lexi-Uncensored
70balso i have added only the 8b

**Comment by AFellowSpeedrunner** [comment]
https://huggingface.co/Orenguteng/Llama-3.1-8B-Lexi-Uncensored-GGUF/ also exists too. GGUF's are much easier to import into Ollama than safetensors. 

You can just import them using a Modelfile.

There are tutorials for making custom llama3 Modelfiles on YouTube and they should be easy enough to follow.

Have fun!

**Comment by jmorganca** [comment]
Hi @olumolu as mentioned by @AFellowSpeedrunner in this case it would be best to import the GGUF file

**Comment by jmorganca** [comment]
Also, here are instructions on how to do that: https://github.com/ollama/ollama/blob/main/docs/import.md#Importing-a-GGUF-based-model-or-adapter
