### ISSUE TITLE
Error: max retries exceeded

### ISSUE THREAD

**Issue by igorschlum** [ollama/ollama#6211]
### What is the issue?

I am in a place with a slow ADSL connection that works for loading pages and checking emails. However, I can't pull LLM models because it's regularly interrupted by an 'Error: max retries exceeded after about 2 or 3 minutes. If I use my phone with Share Connection, it works well in 5G. I don't think it's a new problem, as I don't often pull models from this location, but I remember that this issue was supposed to be fixed about a year ago.

(base) igor@Mac-Studio-192 ~ % ollama pull llama3.1:405b-instruct-q2_K
pulling manifest 
pulling 91a950ecda13...   0% ▕                                           ▏ 240 MB/151 GB                  
Error: max retries exceeded: Get "https://dd20bb891979d25aebc8bec07b2b3bbc.r2.cloudflarestorage.com/ollama/docker/registry/v2/blobs/sha256/91/91a950ecda13411e7b54f0df08b965a4ff2d38738556e89fbbe06ab5ee1a8d18/data?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=66040c77ac1b787c3af820529859349a%2F20240806%2Fauto%2Fs3%2Faws4_request&X-Amz-Date=20240806T212828Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-Amz-Signature=b0480c0fd7b0c78a2204922fa1608e972c6438155b83ff03c7555a43fdc0e6b5": net/http: TLS handshake timeout
(base) igor@Mac-Studio-192 ~ % ollama pull llama3.1:405b-instruct-q2_K
pulling manifest 
pulling 91a950ecda13...   0% ▕                                           ▏ 468 MB/151 GB                  
Error: max retries exceeded: Get "https://dd20bb891979d25aebc8bec07b2b3bbc.r2.cloudflarestorage.com/ollama/docker/registry/v2/blobs/sha256/91/91a950ecda13411e7b54f0df08b965a4ff2d38738556e89fbbe06ab5ee1a8d18/data?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=66040c77ac1b787c3af820529859349a%2F20240806%2Fauto%2Fs3%2Faws4_request&X-Amz-Date=20240806T213331Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-Amz-Signature=12d37fed240dd1f741823322bb3718b46ca05e4f78eabaf4fc69054275592cd0": net/http: TLS handshake timeout
(base) igor@Mac-Studio-192 ~ % ollama pull llama3.1:405b-instruct-q2_K
pulling manifest 
pulling 91a950ecda13...   0% ▕                                           ▏ 709 MB/151 GB                  
Error: max retries exceeded: Get "https://dd20bb891979d25aebc8bec07b2b3bbc.r2.cloudflarestorage.com/ollama/docker/registry/v2/blobs/sha256/91/91a950ecda13411e7b54f0df08b965a4ff2d38738556e89fbbe06ab5ee1a8d18/data?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=66040c77ac1b787c3af820529859349a%2F20240806%2Fauto%2Fs3%2Faws4_request&X-Amz-Date=20240806T213930Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-Amz-Signature=2ba7b7e37ec8436dde00315d61e53fabc7bb784a4b2360a6c5f6b19e54e362e1": net/http: TLS handshake timeout
(base) igor@Mac-Studio-192 ~ % ollama pull llama3.1:405b-instruct-q2_K
pulling manifest 
pulling 91a950ecda13...   1% ▕                                           ▏ 950 MB/151 GB                  
Error: max retries exceeded: Get "https://dd20bb891979d25aebc8bec07b2b3bbc.r2.cloudflarestorage.com/ollama/docker/registry/v2/blobs/sha256/91/91a950ecda13411e7b54f0df08b965a4ff2d38738556e89fbbe06ab5ee1a8d18/data?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=66040c77ac1b787c3af820529859349a%2F20240806%2Fauto%2Fs3%2Faws4_request&X-Amz-Date=20240806T214526Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-Amz-Signature=e58417cf631b6443136f09b1dc99c131059a7021b712ec938a6c523426e56801": net/http: TLS handshake timeout
(base) igor@Mac-Studio-192 ~ % ollama pull llama3.1:405b-instruct-q2_K
pulling manifest 
pulling 91a950ecda13...   1% ▕                                           ▏ 1.1 GB/151 GB  316 KB/s    99h+
Error: max retries exceeded: Get "https://dd20bb891979d25aebc8bec07b2b3bbc.r2.cloudflarestorage.com/ollama/docker/registry/v2/blobs/sha256/91/91a950ecda13411e7b54f0df08b965a4ff2d38738556e89fbbe06ab5ee1a8d18/data?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=66040c77ac1b787c3af820529859349a%2F20240806%2Fauto%2Fs3%2Faws4_request&X-Amz-Date=20240806T214937Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-Amz-Signature=d0551598d8332b8fa7680e42c0bbf2298d9ea0d78afeeb1042c681b7c4563b64": net/http: TLS handshake timeout
(base) igor@Mac-Studio-192 ~ % ollama pull llama3.1:405b-instruct-q2_K
pulling manifest 
pulling 91a950ecda13...   1% ▕                                                                         ▏ 1.4 GB/151 GB  1.3 MB/s  31h26m
Error: max retries exceeded: Get "https://dd20bb891979d25aebc8bec07b2b3bbc.r2.cloudflarestorage.com/ollama/docker/registry/v2/blobs/sha256/91/91a950ecda13411e7b54f0df08b965a4ff2d38738556e89fbbe06ab5ee1a8d18/data?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=66040c77ac1b787c3af820529859349a%2F20240806%2Fauto%2Fs3%2Faws4_request&X-Amz-Date=20240806T215955Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-Amz-Signature=410db491fc93079799905b740c91755269e7daf54433e3be6ae6a3e57f338209": net/http: TLS handshake timeout
(base) igor@Mac-Studio-192 ~ % ollama pull llama3.1:405b-instruct-q2_K
pulling manifest 
pulling 91a950ecda13...   1% ▕                                                                         ▏ 1.7 GB/151 GB                  
Error: max retries exceeded: Get "https://dd20bb891979d25aebc8bec07b2b3bbc.r2.cloudflarestorage.com/ollama/docker/registry/v2/blobs/sha256/91/91a950ecda13411e7b54f0df08b965a4ff2d38738556e89fbbe06ab5ee1a8d18/data?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=66040c77ac1b787c3af820529859349a%2F20240806%2Fauto%2Fs3%2Faws4_request&X-Amz-Date=20240806T222208Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-Amz-Signature=bc366a803f1e3a7a717b3fd2ab54d31e6804057a0e4d0c4c77f5324d83cec398": read tcp 192.168.1.30:55654->104.18.9.90:443: read: connection reset by peer

### OS

macOS

### GPU

Apple

### CPU

Apple

### Ollama version

0.3.4

**Comment by dkgaraujo** [comment]
I am facing the same problem with an ubuntu computer, for llama3.1. I haven't tried with other LLMs but the previous version worked fine in the same machine, same config with llama3:

```
(base) douglas@ubuntu:~$ ollama run llama3.1
pulling manifest 
pulling 4f6dc812262a...   0% ▕                                                                                                                                                                ▏  12 MB/4.7 GB                  
Error: max retries exceeded: Get "https://dd20bb891979d25aebc8bec07b2b3bbc.r2.cloudflarestorage.com/ollama/docker/registry/v2/blobs/sha256/4f/4f6dc812262ac5e1a74791c2a86310ebba1aa1804fa3cd1c216f5547a620d2f2/data?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=66040c77ac1b787c3af820529859349a%!F(MISSING)20240807%!F(MISSING)auto%!F(MISSING)s3%!F(MISSING)aws4_request&X-Amz-Date=20240807T171933Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-Amz-Signature=f5827dcdc260bbfff08f9d872ac5f2ed2b1049f7789c151b9802267049bcc08a": dial tcp [2606:4700::6812:95a]:443: i/o timeout
```

**Comment by igorschlum** [comment]
In fact, when I pull a small model, it works well. No problem pulling phi3:mini, but ollama pull llama3.1:405b-instruct-q2_K cannot pull more than 200K without error.

igor@Mac-Studio-192 ~ % ollama run phi3:mini
pulling manifest 
pulling 633fc5be925f... 100% ▕████████████████▏ 2.2 GB                         
pulling fa8235e5b48f... 100% ▕████████████████▏ 1.1 KB                         
pulling 542b217f179c... 100% ▕████████████████▏  148 B                         
pulling 8dde1baf1db0... 100% ▕████████████████▏   78 B                         
pulling 23291dc44752... 100% ▕████████████████▏  483 B                         
verifying sha256 digest 
writing manifest 
removing any unused layers 
success 
>>> Send a message (/? for help)

**Comment by rampageservices** [comment]
People will keep running into this issue and more and more tickets will be created unless the project maintainers help to make the model downloader more robust by pulling this pending PR as a step in the right direction.

https://github.com/ollama/ollama/pull/4625

**Comment by igorschlum** [comment]
Closing for https://github.com/ollama/ollama/issues/2006

**Comment by liuwq999** [comment]
how to solve this problems?I met this error now.

**Comment by igorschlum** [comment]
@liuwq999 It's a matter of the number of simultaneous threads used to pull a model. It was set too high, and although it was lowered, it still wasn't enough. This issue is now closed, and the discussion has moved to this other issue. Please post your message there.

https://github.com/ollama/ollama/issues/2006

**Comment by ifeelsam** [comment]
i don't exactly know how i solved this but it was dns issue, and it wasn't able to resolve the hostname

so i checked my `/etc/systemd/resolved.conf` 
and i wasn't there

so i just created that file 

```
[Resolve]
DNS=8.8.8.8 8.8.4.4
DNSSEC=no
```
and restared systemd-resolved
```
sudo systemctl status systemd-resolved
```
hope this helps

**Comment by Samarth-tate** [comment]
I had the same issue and fixed it by changing my DNS to (8.8.8.8 & 8.8.4.4). Looks like it was a DNS problem causing the errors. If you're facing this, try switching your DNS in network settings—it worked for me

**Comment by mdsadiqueinam** [comment]
Changing the dns does not solve problem for me

**Comment by danyQe** [comment]
## Issue: Unable to Pull Deepseek-R1 Model in Ollama (Windows)  

I encountered an issue while trying to pull the `deepseek-r1:1.5b` model using Ollama on Windows. The download process stalled at 0% and eventually failed with the following error:  

ollama pull deepseek-r1:1.5b
pulling manifest
pulling aabd4debf0c8...   0% ▕                                                                                                      ▏    0 B/1.1 GB
Error: max retries exceeded: Get "https://dd20bb891979d25aebc8bec07b2b3bbc.r2.cloudflarestorage.com/ollama/docker/registry/v2/blobs/sha256/aa/aabd4debf0c8f08881923f2c25fc0fdeed24435271c2b3e92c4af36704040dbc/data?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=66040c77ac1b787c3af820529859349a%2F20250131%2Fauto%2Fs3%2Faws4_request&X-Amz-Date=20250131T074418Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-Amz-Signature=710bfefba31d920c37d8d47cd265ef40395d2590d617eafe5f1190f86c261267": dial tcp: lookup dd20bb891979d25aebc8bec07b2b3bbc.r2.cloudflarestorage.com: no such host


### Solution  

I resolved this issue by changing my DNS server to Cloudflare (1.1.1.1). After making this change, the model pulled successfully.  

To change the DNS settings on Windows, refer to this guide:  
[How to Change Your PC’s DNS Settings on Windows 10](https://www.windowscentral.com/how-change-your-pcs-dns-settings-windows-10).  

This solution might help others facing the same issue. Let me know if it works for you!

**Comment by Amit2001** [comment]
Changing DNS helped me to resolve the issue, I was facing a similar issue but after changing DNS, I have successfully installed the model, and it is running perfectly fine.

**Comment by sharma-shanu** [comment]
Changing the dns also solved the issue for me.

**Comment by max-keviv** [comment]
i was also facing this issue in my mac, changing the dns fixed the issue
run this command to fix the issue 
sudo networksetup -setdnsservers Wi-Fi 8.8.8.8 8.8.4.4

**Comment by ssingh-teachx** [comment]
> i was also facing this issue in my mac, changing the dns fixed the issue run this command to fix the issue sudo networksetup -setdnsservers Wi-Fi 8.8.8.8 8.8.4.4

Works like charm. Thanks @max-keviv

**Comment by Marrpee2013** [comment]
![Image](https://github.com/user-attachments/assets/32cdeb0c-547f-4d68-a618-ad01dfce2183)
change DNS didn't work on this issue

**Comment by ssingh-teachx** [comment]
> ![Image](https://github.com/user-attachments/assets/32cdeb0c-547f-4d68-a618-ad01dfce2183) change DNS didn't work on this issue

From commands, I am guessing you are using windows machine. I checked this model on my Mac and its working as I had changed dns servers to 8.8.8.8, 8.8.4.4.

It's hard to determine why its not working on yours if you have followed previous suggestions in chat. If you are able to solve it, let us know how u did it. Thanks.

**Comment by Bhargav-CS** [comment]
Yeah setting 1.1.1.1 works

**Comment by Aryan-GNDU** [comment]
yes if you are facing an error in which the download process stalled at 0% and eventually failed with the following error:

ollama pull (any model)
pulling manifest
pulling aabd4debf0c8... 0% ▕ ▏ 0 B/1.1 GB
Error: max retries exceeded: Get "https://dd20bb891979d25aebc8bec07b2b3bbc.r2.cloudflarestorage.com/ollama/docker/registry/v2/blobs/sha256/aa/aabd4debf0c8f08881923f2c25fc0fdeed24435271c2b3e92c4af36704040dbc/data?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=66040c77ac1b787c3af820529859349a%2F20250131%2Fauto%2Fs3%2Faws4_request&X-Amz-Date=20250131T074418Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-Amz-Signature=710bfefba31d920c37d8d47cd265ef40395d2590d617eafe5f1190f86c261267": dial tcp: lookup dd20bb891979d25aebc8bec07b2b3bbc.r2.cloudflarestorage.com: no such host
then if you just change your  DNS to Cloudfare then you will be able to pull the model

**Comment by iamprathamjain** [comment]
Changing the DNS worked for me on Windows 11
Let me guide you through the steps:

1 Open Control Panel → Network and Internet → Network and Sharing Center.
2  Click Change adapter settings on the left.
3  Right-click your active network connection (Wi-Fi or Ethernet) and select Properties.
4  Choose Internet Protocol Version 4 (TCP/IPv4) and click Properties.
5  Enter the following DNS servers:
Preferred DNS: 8.8.4.4 (Google)
Alternate DNS: 1.1.1.1 (Cloudflare)

6 Save and Retry

**Comment by rohangore1999** [comment]
Changing the DNS for MAC - mac silicon chip

1) Open System Settings:

- Click the Apple logo → System Settings (or System Preferences on older macOS versions).

2) Go to Network Settings:
- Click Network from the sidebar.

3) Select Active Network:
- Choose your active connection (Wi-Fi or Ethernet) → Click Details (or Advanced on older versions).

4) Go to DNS Tab:
- In the Details/Advanced window, navigate to the DNS tab.

5) Add DNS Servers:
- Click the + button and add:
    - Preferred DNS: 8.8.4.4 (Google)
    - Alternate DNS: 1.1.1.1 (Cloudflare)

6) Save Changes:
- Click OK → Apply to save the new DNS settings.

**Comment by cptiwari20** [comment]
https://github.com/ollama/ollama/issues/6211#issuecomment-2727355391
This worked for me,
thanks @rohangore1999

**Comment by eust-w** [comment]
> I have the same exception，and solved as follow:
> 
> ollama run **hf.co**/{username}/{reponame}:latest replaced by ollama run **hf-mirror.com**/{username}/{reponame}:latest

This solution is effective

**Comment by SrLeet03** [comment]
I had the same issue , turned out to be a DNS problem.

Switching to Google’s public DNS (8.8.8.8 & 8.8.4.4) fixed it for me.

**On macOS:**  
System Settings > Network > Wi-Fi > Details > DNS > Add 8.8.8.8 & 8.8.4.4. 

Then simply turn off your WIFI/LAN and reconnect with it and to confirm use **scutil --dns**  if DNS got added.

**Comment by Penguin5681** [comment]
> I had the same issue and fixed it by changing my DNS to (8.8.8.8 & 8.8.4.4). Looks like it was a DNS problem causing the errors. If you're facing this, try switching your DNS in network settings—it worked for me

It did turn to be a dns issue, lol.
Thanks for figuring it out

**Comment by zadescoxp** [comment]
Just change the DNS, use this command 
`sudo networksetup -setdnsservers Wi-Fi 8.8.8.8 8.8.4.4`

**Comment by PriDebnath** [comment]
> Changing the DNS for MAC - mac silicon chip
> 
> 1. Open System Settings:
> 
> * Click the Apple logo → System Settings (or System Preferences on older macOS versions).
> 
> 2. Go to Network Settings:
> 
> * Click Network from the sidebar.
> 
> 3. Select Active Network:
> 
> * Choose your active connection (Wi-Fi or Ethernet) → Click Details (or Advanced on older versions).
> 
> 4. Go to DNS Tab:
> 
> * In the Details/Advanced window, navigate to the DNS tab.
> 
> 5. Add DNS Servers:
> 
> * Click the + button and add:
>   
>   * Alternate DNS: 1.1.1.1 (Cloudflare)
> 
> 6. Save Changes:
> 
> * Click OK → Apply to save the new DNS settings.

Thank you @rohangore1999

**Comment by anton-karlovskiy** [comment]
@mdsadiqueinam @ziyouzhea @rampageservices @dkgaraujo @igorschlum

👋 I’ve been trying to download llama3.2 on Windows 11 (ollama run llama3.2) and keep running into issues:

- An existing connection was forcibly closed by the remote host
- Error: max retries exceeded

What I’ve tried so far:

- https://github.com/ollama/ollama/issues/3769#issuecomment-2076767384: closed VPN → no change
- https://github.com/ollama/ollama/issues/6211#issuecomment-2626567037: changed DNS → made some progress (got to ~37%) but stuck again

<img width="1086" height="124" alt="Image" src="https://github.com/user-attachments/assets/774acce1-b0af-4b66-b2ae-415baf6f0fe0" />

From what I can tell, the main culprit seems to be an unstable connection. The workaround right now is to just re-run the command until it eventually completes, but this gets tedious.

To automate retries, I wrapped it in a small script. Sharing here in case it helps others or the devs want to consider integrating retry logic directly:

**Windows**
Open new notepad and put this code.

```bash
@echo off
:loop
echo Running ollama run llama3.2...
ollama run llama3.2

if %errorlevel% neq 0 (
    echo The command failed. Retrying... Press Ctrl+C to exit.
    goto loop
)
echo The command completed successfully!
```

Next go to save as… and pick All files as file type and name the file with `.bat` extension.
And finally you can run it.
To edit the code above, just change model name from `llama3.2` to any other model you like.

**Linux**
I didn’t test the code for Linux but this should hopefully work.

#!/bin/bash
```bash
# Function to handle Ctrl+C
trap 'echo "Script terminated by user. Exiting..."; exit' SIGINT
while true; do
    echo "Running ollama run llama3.2..."
    ollama run llama3.2
    if [ $? -eq 0 ]; then
        echo "The command completed successfully!"
        break
    else
        echo "The command failed. Retrying... Press Ctrl+C to exit."
    fi
done
```

Save this as `run_loop.sh` then run these commands.

```bash
chmod +x run_loop.sh
```
```bash
./run_loop.sh
```

Re: https://medium.com/@timnirmal/ollama-max-retries-exceeded-error-de6e0f86383e

Good luck 🤞

**Comment by Shivamp9** [comment]
restarted wifi router and worked for me.

**Comment by tangelll** [comment]
for macOS m4 run it with sudo su worked for me!

**Comment by tangelll** [comment]
> for macOS m4 run it with sudo su worked for me!

open another terminal and enter caffeinate. I think that when computer goes to sleep it is terminating.
