### ISSUE TITLE
Ollama update (0.3.3) prevents running llama3.1:70b or llama3.1:8b with tools

### ISSUE THREAD

**Issue by imsaumil** [ollama/ollama#6215]
### What is the issue?

I had an old version of Ollama (do not remember the previous version) and had llama3.1:70b installed which was running fine. But I wanted to install llama3.1:8b and it did not let me pull without updating my Ollama. After the update with fresh pull of llama3.1:70b does not work as expected and gives following error. It does use @tool decorator with a single output function and ChatOllama API from langchain.

I tried downgrading the Ollama to a previous version to re-test but then it does not allow me to pull models without upgrading Ollama. 

Error message:
<img width="1289" alt="image" src="https://github.com/user-attachments/assets/ccb9b9e6-1d7f-4288-a97c-5c9039ccfa13">

### OS

Linux

### GPU

Nvidia

### CPU

AMD

### Ollama version

0.3.3

**Comment by rick-github** [comment]
https://github.com/langchain-ai/langchain/issues/20924

**Comment by dhiltgen** [comment]
It looks like the defect was resolved in langchain.  If you're still having problems with the latest versions of both Ollama and Langchain let us know.

**Comment by SIDDHARTH000001** [comment]
Name: langgraph
Version: 0.2.45

Name: ollama
Version: 0.3.3

Name: langchain
Version: 0.3.7

Name: langchain-community
Version: 0.3.2


still facing ValueError: Received unsupported message type for Ollama.

**Comment by nwheeler81** [comment]
@dhiltgen I'm facing the same issue `ValueError: Received unsupported message type for Ollama` with LangGraph and Ollama:
langchain-ollama            0.2.3
ollama                             0.4.7
langchain                        0.3.18
langchain-core               0.3.35
langchain-ollama            0.2.3
langgraph                       0.2.72

**Comment by dhiltgen** [comment]
@nwheeler81 0.4.7 is a bit old (we're up to 0.5.11) - please make sure you upgrade to the latest versions and if you still see incompatibilities, please open a new issue.
