### ISSUE TITLE
Is the ollama request multi-process?

### ISSUE THREAD

**Issue by chensuo2048** [ollama/ollama#6216]
I tested the ollama service and found that every time a request is sent, a new process is started. My question is why a new process is started instead of a new thread? Will starting a new process affect efficiency?

**Comment by sammcj** [comment]
Hey there 👋 , I'd suggest asking on the [Ollama Discord](https://discord.gg/ollama) which is used for general support/troubleshooting as opposed to Github which is more focused on logging bugs/feature requests.

**Comment by chensuo2048** [comment]
> Hey there 👋 , I'd suggest asking on the [Ollama Discord](https://discord.gg/ollama) which is used for general support/troubleshooting as opposed to Github which is more focused on logging bugs/feature requests.

Sure, I'll do that. Thanks!
