### ISSUE TITLE
POST "/api/generate" retrun 500

### ISSUE THREAD

**Issue by w16645395520** [ollama/ollama#6225]
### What is the issue?

I use the Qwen1.5-14B model
GGUF model file synthesized by llama.cpp
Ollama is installed directly locally in centos
`ollama create qwen1.5_14b -f Modelfile`
POST "/api/generate" when requesting
Errors are reported from time to time, and there is no error message
`journalctl -u ollama --no-pager | grep "Aug 07 13:3"`
```
...
Aug 07 13:30:28 chh-litb-sd-webui4 ollama[17408]: [GIN] 2024/08/07 - 13:30:28 | 200 | 1.788628934s | ip xxx | POST "/api/generate"
Aug 07 13:30:29 chh-litb-sd-webui4 ollama[17408]: [GIN] 2024/08/07 - 13:30:29 | 500 | 20.000781644s | ip xxx | POST "/api/generate"
Aug 07 13:30:41 chh-litb-sd-webui4 ollama[17408]: [GIN] 2024/08/07 - 13:30:41 | 200 | 1.56062356s | ip xxx | POST "/api/generate"
...
```
I don't know where else I can see more detailed error messages and show them to you

### OS

Linux

### GPU

Nvidia

### CPU

Intel

### Ollama version

0.1.48

**Comment by rick-github** [comment]
Add `Environment="OLLAMA_DEBUG=1"` to /etc/systemd/system/ollama.service, restart ollama and add the logs when the error occurs.

**Comment by w16645395520** [comment]
> Add `Environment="OLLAMA_DEBUG=1"` to /etc/systemd/system/ollama.service, restart ollama and add the logs when the error occurs.

I added `OLLAMA_DEBUG=1`, and it did print out detailed log information, but there was no error information in it. I don’t know if there is a limit on the generation time. I observed several 500 requests and found that if the generation time is less than 20 seconds and there is no result returned, it will return 500.

**Comment by w16645395520** [comment]
Wrong, it is more than 20s
