### ISSUE TITLE
llama_init_from_gpt_params: error: failed to load model 'models\gemma-1.1-7b-it.Q4_K_M.gguf'

### ISSUE THREAD

**Issue by stephen521** [ollama/ollama#6228]
### What is the issue?

when I run the code below in Windows machine(Intel Xeon Silver 421R 2.4GHz, 512m, NVIDIA GeForce RTX 3090) and I got the error below:
llama-cli.exe -m models\gemma-1.1-7b-it.Q4_K_M.gguf --prompt "Once upon a time"
Log start
main: build = 0 (unknown)
main: built with cc (GCC) 14.1.0 for i686-w64-mingw32
main: seed  = 1723019120
llama_model_load: error loading model: tensor 'blk.2.ffn_down.weight' data is not within the file bounds, model is corrupted or incomplete
llama_load_model_from_file: failed to load model
llama_init_from_gpt_params: error: failed to load model 'models\gemma-1.1-7b-it.Q4_K_M.gguf'
main: error: unable to load model
What the problem is? Need help!
Thanks a lots.

### OS

Windows

### GPU

Nvidia

### CPU

Intel

### Ollama version

3.1

**Comment by rick-github** [comment]
```
llama_model_load: error loading model: tensor 'blk.2.ffn_down.weight' data is not within the file bounds, model is corrupted or incomplete
```
As per the error, the model is broken, where did you get the file from?  Also, this is the issue tracker for ollama, not llama.cpp, which is over [here](https://github.com/ggerganov/llama.cpp/issues).

**Comment by jmorganca** [comment]
Thanks @rick-github – indeed it might be hard to help debug this here, but it looks as if the GGUF file you have wasn't saved correctly
