### ISSUE TITLE
Why until now the Qwen2ForCausalLM is not supported until now

### ISSUE THREAD

**Issue by wisamidris7** [ollama/ollama#6231]
### What is the issue?

I made ollama create it says

```
> ollama create myai -f ./Modelfile
transferring model data
converting model
Error: unsupported architecture
```

and this

```
> docker run --rm -v .:/model ollama/quantize -q q4_0 /model
unknown architecture Qwen2ForCausalLM
```

### OS

Windows

### Ollama version

ollama version is 0.3.3

**Comment by wisamidris7** [comment]
Does llama3 architecture supported 

The problem I need a model that support multi language like meta llama3 or qwen2
The language required is arabic

**Comment by rick-github** [comment]
ollama/quantize uses an older version of llama.cpp that doesn't support qwen2, see the supported architectures on https://registry.hub.docker.com/r/ollama/quantize.  However, both [qwen2](https://ollama.com/search?q=qwen2) and [llama3](https://ollama.com/search?q=llama3) models are already in the ollama library, you can just pull them and use them: `ollama pull qwen2`, `ollama pull llama3`.  Note that llama3 is old as models go, and llama3.1 might work better, depending on its support for Arabic.

**Comment by wisamidris7** [comment]
No the problem I had fine tuned qwen2 I need to fine tune it for personal purposes
And when I fine tuned it into lora it was very very stupid and the loss rate was 3.7 in the end
And when I fine tuned it into full I didn't test it in ollama until now and the loss rate was 0.2 in the end

**Comment by wisamidris7** [comment]
And also vllm has supported it aleardy

![image](https://github.com/user-attachments/assets/6b838adf-32fb-43df-bc7c-01090cb4af7e)

**Comment by rick-github** [comment]
As I said, ollama/quantize uses an old version of llama.cpp.  If you want qwen2 support, use a newer version from ghcr.io/ggerganov/llama.cpp.

**Comment by wisamidris7** [comment]
I mean I need to use windows version not docker?

**Comment by rick-github** [comment]
This is what I use:
```
docker run -it --gpus all -v .:/app/models ghcr.io/ggerganov/llama.cpp:full-cuda -q /app/models/model.gguf Q4_K_M
```

**Comment by wisamidris7** [comment]
Thanks very much!
👍

**Comment by wisamidris7** [comment]
Sorry but little problem is 

Unable to find image 'ghcr.io/ggerganov/llama.cpp:full-cuda' locally
docker: Error response from daemon: Head "https://ghcr.io/v2/ggerganov/llama.cpp/manifests/full-cuda": denied: denied.
See 'docker run --help'.

**Comment by rick-github** [comment]
`docker pull ghcr.io/ggerganov/llama.cpp:full-cuda`

**Comment by wisamidris7** [comment]
No it seems i need to login with my github account

**Comment by wisamidris7** [comment]
Sorry but I mean to convert it from full or model.safetensors to gguf or ggml using ghcr.io/ggerganov/llama.cpp:full-cuda
It says this

```
main: build = 0 (unknown)
main: built with cc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0 for x86_64-linux-gnu
main: quantizing '/app/models/' to '/app/models/ggml-model-Q4_K_M.gguf' as Q4_K_M
gguf_init_from_file: invalid magic characters 'D'
llama_model_quantize: failed to quantize: llama_model_loader: failed to load model from /app/models/

main: failed to quantize model from '/app/models/'
```

**Comment by wisamidris7** [comment]
All I care about is running it on ollama

**Comment by wisamidris7** [comment]
I used this to convert it

https://github.com/kevkid/gguf_gui

**Comment by henryxiao1997** [comment]
I'm not familar with docker commend. Is it possible to use new llama.cpp in the commendline way, i.e. in 'ollama create mymodel'? Thanks!

**Comment by rick-github** [comment]
Try it.  `ollama create --quantize` will handle some models.  If it doesn't work for the model you try it on, post details.

**Comment by sunday-hao** [comment]
I am in the same troube with @wisamidris7. OS -> Windows 10, newest version of ollama.
I firstly fine-tuned the Qwen2.5-Instruct base model on my private dataset. Then, I covert the fine-tuned model into .gguf format by llama.cpp. While I tried to 'ollama create' and 'ollama create --quantize' my fine-tuned model, it both turned out to 'Error: unsupported architecture'. Nevertheless, I saw qwen2.5 series supported in the ollama library[https://ollama.com/library](url) So, I can't run my fine-tuned model on ollama.
Is this a bug? Or any solution?

**Comment by rick-github** [comment]
If you add some details it will make it easier to debug.  Pointer to base model, llama.cpp command, contests of Modelfile, error message.

**Comment by sunday-hao** [comment]
I opened a new issue, there is more details.
And my base model is Qwen2.5-Instruct.
the command of llama.cpp used to convert the format of my fine-tuned model as below:
`python convert-hf-to-gguf.py --outfile path/to/outfile  path/to/safetensors`
contents of Modelfile as below:
`FROM /path/to/gguf_file`
error message as below:

> ollama create my_model -f ./Modelfile
> transferring model data 100%
> converting model
> Error: unsupported architecture
