### ISSUE TITLE
Strange! Each request consumes an additional 2 seconds when I used /api/embed

### ISSUE THREAD

**Issue by AlbertXu233** [ollama/ollama#6233]
### What is the issue?

<img width="809" alt="image" src="https://github.com/user-attachments/assets/d649cc9e-7b95-4146-aeef-4eb564be7047">
OS: win11
device: intel i5 1335U with only iGPU
embedding model: shaw/dmeta-embedding-zh-q4
I test with very simple input: ["你好"]

### OS

Windows

### GPU

Intel

### CPU

Intel

### Ollama version

0.3.4

**Comment by rick-github** [comment]
What's making the API call?  Making a direct API call in linux doesn't show any delays:
```
$ curl -s localhost:11434/api/version
{"version":"0.3.4"}

$ for i in {1..5} ; do curl -s localhost:11434/api/embed -d '{"model":"shaw/dmeta-embedding-zh-q4","input":"你好"}' | jq -c 'del(.embeddings[0][])' ; done
{"model":"shaw/dmeta-embedding-zh-q4","embeddings":[[]],"total_duration":138950724,"load_duration":1587447,"prompt_eval_count":4}
{"model":"shaw/dmeta-embedding-zh-q4","embeddings":[[]],"total_duration":142275262,"load_duration":1525043,"prompt_eval_count":4}
{"model":"shaw/dmeta-embedding-zh-q4","embeddings":[[]],"total_duration":145625093,"load_duration":1402358,"prompt_eval_count":4}
{"model":"shaw/dmeta-embedding-zh-q4","embeddings":[[]],"total_duration":148817738,"load_duration":1032026,"prompt_eval_count":4}
{"model":"shaw/dmeta-embedding-zh-q4","embeddings":[[]],"total_duration":145985135,"load_duration":1396395,"prompt_eval_count":4}

$ docker compose logs ollama | grep /api/embed
ollama  | [GIN] 2024/08/07 - 17:34:32 | 200 |  139.237667ms |   192.168.192.1 | POST     "/api/embed"
ollama  | [GIN] 2024/08/07 - 17:34:32 | 200 |  142.622972ms |   192.168.192.1 | POST     "/api/embed"
ollama  | [GIN] 2024/08/07 - 17:34:32 | 200 |  145.953288ms |   192.168.192.1 | POST     "/api/embed"
ollama  | [GIN] 2024/08/07 - 17:34:32 | 200 |  149.176403ms |   192.168.192.1 | POST     "/api/embed"
ollama  | [GIN] 2024/08/07 - 17:34:32 | 200 |  146.312404ms |   192.168.192.1 | POST     "/api/embed"

```

**Comment by AlbertXu233** [comment]
> What's making the API call? Making a direct API call in linux doesn't show any delays:
> 
> ```
> $ curl -s localhost:11434/api/version
> {"version":"0.3.4"}
> 
> $ for i in {1..5} ; do curl -s localhost:11434/api/embed -d '{"model":"shaw/dmeta-embedding-zh-q4","input":"你好"}' | jq -c 'del(.embeddings[0][])' ; done
> {"model":"shaw/dmeta-embedding-zh-q4","embeddings":[[]],"total_duration":138950724,"load_duration":1587447,"prompt_eval_count":4}
> {"model":"shaw/dmeta-embedding-zh-q4","embeddings":[[]],"total_duration":142275262,"load_duration":1525043,"prompt_eval_count":4}
> {"model":"shaw/dmeta-embedding-zh-q4","embeddings":[[]],"total_duration":145625093,"load_duration":1402358,"prompt_eval_count":4}
> {"model":"shaw/dmeta-embedding-zh-q4","embeddings":[[]],"total_duration":148817738,"load_duration":1032026,"prompt_eval_count":4}
> {"model":"shaw/dmeta-embedding-zh-q4","embeddings":[[]],"total_duration":145985135,"load_duration":1396395,"prompt_eval_count":4}
> 
> $ docker compose logs ollama | grep /api/embed
> ollama  | [GIN] 2024/08/07 - 17:34:32 | 200 |  139.237667ms |   192.168.192.1 | POST     "/api/embed"
> ollama  | [GIN] 2024/08/07 - 17:34:32 | 200 |  142.622972ms |   192.168.192.1 | POST     "/api/embed"
> ollama  | [GIN] 2024/08/07 - 17:34:32 | 200 |  145.953288ms |   192.168.192.1 | POST     "/api/embed"
> ollama  | [GIN] 2024/08/07 - 17:34:32 | 200 |  149.176403ms |   192.168.192.1 | POST     "/api/embed"
> ollama  | [GIN] 2024/08/07 - 17:34:32 | 200 |  146.312404ms |   192.168.192.1 | POST     "/api/embed"
> ```

I used python requests in windows
Here is the code:
```python
    def request_ollama(query, host="localhost:11434", ollama_model_name="shaw/dmeta-embedding-zh"):
        """
        使用ollama的embedding策略
        """
        url = f"http://{host}/api/embeddings"

        payload = json.dumps(
                {
                    "model": ollama_model_name,
                    "prompt": query,
                }
            )
        headers = {"Content-Type": "application/json"}

        response = requests.request(
                "POST", url, headers=headers, data=payload, stream=False
            )
        embeddings = json.loads(response.text)
        return [embeddings["embedding"]]
    for i in range(10):
        print(i)
        print(request_ollama("你好"))
```

**Comment by rick-github** [comment]
If you change `localhost` to `127.0.0.1` does it run faster?

**Comment by AlbertXu233** [comment]
> If you change `localhost` to `127.0.0.1` does it run faster?

Amazing! It works! Thanks!

**Comment by royjhan** [comment]
@AlbertXu233 does the issue persist when using localhost?

**Comment by dhiltgen** [comment]
By switching to the IP you're likely bypassing hostname resolution and/or proxy configurations which are likely what is adding the latency.
