### ISSUE TITLE
Ollama server running out of memory when it didn't in previous version

### ISSUE THREAD

**Issue by MxtAppz** [ollama/ollama#6238]
### What is the issue?

Hello,

I'm trying to run Llama 3.1 8b in Ollama 0.3.4 on a laptop (it has 8gb ram and 4 cpu cores, running it on CPU as my GPU is integrated and not compatible). Maybe this sounds crazy, but it worked fine on Ollama 0.3.3, and just after updating to 0.3.4 and running it (I also tried updating the model but the same) I get:

Error: Post "http://127.0.0.1:11434/api/chat": EOF

and when I try again:

Error: llama runner process has terminated: signal: killed

So I think it's running out of memory. I like to try things on my laptop before deploying them to my server, so I would like if you could "fix" that back, or show me a workaround for this. (Mistral 7b works fine with 0.3.4).

Thanks in advanced.

### OS

Linux

### GPU

Other

### CPU

Intel

### Ollama version

0.3.4

**Comment by rick-github** [comment]
[Server logs](https://github.com/ollama/ollama/blob/main/docs/troubleshooting.md#how-to-troubleshoot-issues) will help in debugging.

**Comment by igorschlum** [comment]
@MxtAppz Alongside the new version of Ollama, there is an update for the Llama3.1 LLMs. Did you pull this latest version? If you are experiencing memory issues, could you try a lighter version of Llama3.1?

```bash
ollama run llama3.1:8b-instruct-q3_K_L
```
This version is slightly lighter than the default q4_0 and should resolve the issue you're facing.

Yes, the system size grows as Ollama and Llama3.1 grow as well. Another option is to restart your Mac before testing Ollama and ensure no other applications are running besides Ollama and the terminal.

**Comment by MxtAppz** [comment]
> @MxtAppz Alongside the new version of Ollama, there is an update for the Llama3.1 LLMs. Did you pull this latest version? If you are experiencing memory issues, could you try a lighter version of Llama3.1?
> 
> ```shell
> ollama run llama3.1:8b-instruct-q3_K_L
> ```
> 
> This version is slightly lighter than the default q4_0 and should resolve the issue you're facing.
> 
> Yes, the system size grows as Ollama and Llama3.1 grow as well. Another option is to restart your Mac before testing Ollama and ensure no other applications are running besides Ollama and the terminal.

Yes, I pulled the latest llama3.1 model, and doesn't work (the older one didn't work either though). I'll try the instruct version as soon as possible and tell you.

**Comment by rick-github** [comment]
```
Error: llama runner process has terminated: signal: killed
```
This indicates a problem with the runner, not the model (unless the model is borked somehow).  Server logs will help in debugging.

**Comment by jmorganca** [comment]
@MxtAppz would it be possible to check the logs with `journalctl -u ollama` to see what the error may be? Sorry about this

**Comment by MxtAppz** [comment]
Hello newly,

Finally, the issue was resolved by rebooting the system (thanks to @igorschlum for telling me). Anyway, I will leave the issue open and attach the log after updating Ollama in case someone wants to check it out. Thanks for your time.
[ollama.txt](https://github.com/user-attachments/files/16534385/ollama.txt)

**Comment by jmorganca** [comment]
This should be fixed now – you'll need to re-pull `llama3.1` let me know if that doesn't help!
