### ISSUE TITLE
support keep_alive in config.json

### ISSUE THREAD

**Issue by avelican** [ollama/ollama#6239]
Hi. I'm talking about the global config.json in ollama's config folder.
On my system that's `C:\Users\me\AppData\Local\Ollama`.
I suggest adding the keep_alive parameter globally to this file.
Currently it must be added to each client application's API requests individually.

**Comment by rick-github** [comment]
You can set this globally by adding `OLLAMA_KEEP_ALIVE=10m` to the [environment variables](https://github.com/ollama/ollama/blob/main/docs/faq.md#setting-environment-variables-on-windows).

**Comment by dhiltgen** [comment]
Adding support for a config file is tracked via #204.
