### ISSUE TITLE
Modelfile - Customize a prompt

### ISSUE THREAD

**Issue by LucasFreitas88** [ollama/ollama#6246]
### What is the issue?

I cannot change the modelfile file with new prompt instructions, as in the documentation example (Customize a prompt item). 

Model: Llama 3.1 8B

Notebook: Macbook Air M1 - Mac Os Sonoma 14.6.1

The answer to the question posed in the example (hi) is an endless sequence of strange characters like:

H*114@(02228'6.:@6@?/B+:&H((,/1A:8/=>=<.C-.C2>9C*;H!$C=+5&,'*&C7@44D>&BC=D"C%6<BB%;;$*//2<D814),';?:@!!9:2H*114@(02228'6.:@6@?/B+:&H((,/1A:8/=>=<.-C-.C2>9C*;H!$C=+5&,'*&C7@44D>&BC=D"C%6< ...

What is happening? The procedure I used is exactly the same as described in the documentation.

### OS

macOS

### Ollama version

0.3.4

**Comment by rick-github** [comment]
What's the contents of your modelfile?

**Comment by LucasFreitas88** [comment]
both work with other models, such as mistral

**Comment by rick-github** [comment]
There's another report (#6249) of llama3.1 on a Mac outputting random characters.  If you run the model without a customized prompt, does it work any better?  Have you tried other quants?

**Comment by LucasFreitas88** [comment]
Without customizing prompt, it works perfectly. I haven't tried other quants.

**Comment by LucasFreitas88** [comment]
I uploaded the version of ollama on my Mac yesterday, exclusively to test prompt changes in Llama3.1 modelfile. 
Everything was fine until the day before yesterday, that's why I hadn't tested the model myself. I tested it now, on a new installation, and the model itself actually generates the same random characters.

**Comment by rick-github** [comment]
It's been reported that `llama3.1:8b-instruct-q4_K_M` works fine, do you find the same?

**Comment by LucasFreitas88** [comment]
on my old installation (version before 0.3.4), the Llama3.1 was working perfectly without prompt changes.

**Comment by LucasFreitas88** [comment]
llama3.1:8b-instruct-q4_K_M works fine

**Comment by LucasFreitas88** [comment]
It was exactly this error! Thank you so much! I switched to a machine with 32GB of RAM, and it worked perfectly. I realized that it’s necessary to have 4-6GB free, at least on my Mac, to use Llama 3.1 8B, and there are only 8GB of RAM in total.

**Comment by LucasFreitas88** [comment]
Thanks!
