### ISSUE TITLE
ollama run llama3.1 command outputs nonsense 

### ISSUE THREAD

**Issue by erfan-khalaji** [ollama/ollama#6249]
### What is the issue?

After installing Ollama on macOS, I attempted to run the model using the `ollama run llama3.1` command. However, when I tried running the model by inputting "hello," it returned what appeared to be random ASCII characters, which didn't make sense. I then used `ollama pull llama2` and `ollama pull llama3` to see if that would resolve the issue. While `ollama run llama3.1` still resulted in nonsensical output, `ollama run llama3` and `ollama run llama2` worked perfectly. I thought I would share my experience in case it helps someone facing a similar issue.

### OS

macOS

### GPU

Apple

### CPU

Apple

### Ollama version

3.1

**Comment by rick-github** [comment]
It seems that the Q4_0 quant of llama3.1 doesn't work for a subset of Mac users.  What type of Mac are you running?  Can you provide [server logs](https://github.com/ollama/ollama/blob/main/docs/troubleshooting.md#how-to-troubleshoot-issues)?

**Comment by rick-github** [comment]
If you are running a Mac M1 with 8GB of RAM, the PR https://github.com/ollama/ollama/pull/6260 may fix the issue in the next release.

**Comment by jmorganca** [comment]
Hi @erfan-khalaji , this should be fixed now. You'll need to re-pull `llama3.1`: `ollama pull llama3.1` (sorry!). Let me know if you're still seeing it afterwards.

**Comment by erfan-khalaji** [comment]
@rick-github @jmorganca 
After re-pulling Llama 3.1, the problem was resolved. Thank you, folks!
