### ISSUE TITLE
运行glm4-9b模型,对话时间久了会偶发性的回复GGGGGGG

### ISSUE THREAD

**Issue by MdcGIt** [ollama/ollama#6250]
### What is the issue?

运行glm4-9b模型,对话时间久了会偶发性的回复GGGGGGG
显卡信息如下:
![image](https://github.com/user-attachments/assets/5ae71376-3667-4d65-8603-549768fccb40)

### OS

Linux

### GPU

Intel

### CPU

Intel

### Ollama version

0.3.0

**Comment by wszgrcy** [comment]
不一定运行久,有时候第一次正常,再来一次就失败了

**Comment by AeneasZhu** [comment]
This might be `llama.cpp`'s problem that causes the bug. I suggest you post your issue in `llama.cpp`.

**Comment by jmorganca** [comment]
Having trouble reproducing this one. May I ask what prompt you used and which glm4 model? Was it `ollama run glm4`?

**Comment by wszgrcy** [comment]
> Having trouble reproducing this one. May I ask what prompt you used and which glm4 model? Was it `ollama run glm4`?

Llama.cpp seems to have fixed this issue 
https://github.com/ggerganov/llama.cpp/pull/9130
But the code is not synchronized?

**Comment by shuye-cheung** [comment]
I use 
```
ollama run glm4
```
namely **9b-chat-q4_0**

Then, the model will return "GGGGGGGGGGGGGGGGGGG" error。

**Comment by dhiltgen** [comment]
Please upgrade to the latest version of Ollama which includes upstream fixes for glm4 in llama.cpp.  If you're still having troubles, share an updated server log and we'll reopen the issue.

**Comment by 1003663050** [comment]
要看显卡支持的指令集，比如：NVIDIA GeForce RTX 3080不支持INT4指令集‌。RTX 3080使用的是Ampere架构，该架构支持INT8和FP16运算，但不直接支持INT4运算‌，但是Q4模型是需要int4指令集的
