### ISSUE TITLE
Offload a model command

### ISSUE THREAD

**Issue by stavsap** [ollama/ollama#6261]
Can we have an offload a model cli/api command to remove a model from memory/vram?

**Comment by rick-github** [comment]
You can do this via the API by setting `keep_alive` to 0:

```
curl ${OLLAMA_HOST-localhost:11434}/api/generate -d '{"model":"'$MODEL'","keep_alive":0}'
```

**Comment by stavsap** [comment]
yes but this command dosnt work on windows

it will be much cleaner to have

`ollama stop <model_name>`

and 

`api/stop` end point

**Comment by rick-github** [comment]
`curl` is a default component of windows since December 19 2017, although it's possible the arguments are different.  You can wrap in a batch file called `ollamastop.bat` or write a PS cmdlet and use that until the ollama cli is extended.

**Comment by stavsap** [comment]
yes curl is in windows but there is argument issue, anyway thanks for the advice ill try to make temp script until cli/api will be available.

**Comment by pdevine** [comment]
Let's track this in #4077
