### ISSUE TITLE
Not a feature request, not a bug, problem with LLama3.1

### ISSUE THREAD

**Issue by airdogvan** [ollama/ollama#6265]
I have several models all running fine on ollama, including  Llama3.  Lama3.1 gives very long answers, then repeats them and finally prints random characters and if I didn't use the interface to stop seemingly would go on forever.

Running llama3.1 with the same parameters that seem to be ok with all other models.

Any suggestions welcome as it seems to be quite a bit more powerful than all other models.

**Comment by igorschlum** [comment]
@airdogvan did you updated Ollama to version 0.3.4 and pull again your llama3.1 models? You should try and please share your [ollama logs](https://github.com/ollama/ollama/blob/main/docs/troubleshooting.md) to help finding the problem if still present.

**Comment by airdogvan** [comment]
thanks for the quick answer.  Running docker ollama.  Had 3.2 pulled 3.4.  Deleted llama3.1, restarted ollama.  When I try to download llama3.1 error message:

```The model you are attempting to pull requires a newer version of Ollama. Please download the latest version at: https://ollama.com/download ```

Double checked, have 3.4 running.

**Comment by igorschlum** [comment]
@airdogvan when you type

```bash
ollama --version
```
what is displayed? It is strange that ollama3.1 don't pull.

**Comment by airdogvan** [comment]
ollama --version
ollama version is 0.3.4

**Comment by airdogvan** [comment]
could download gemma2 but when sending query I get:"Open WebUI: Server Connection Error".  Again that problem does not come up with older models.  Still cannot download llama3.1

**Comment by igorschlum** [comment]
@airdogvan if it is an open_webui problem, please close this issue.
BTW new version of llama3.1 is being uploaded today in the library. Try also to pull again the llama3.1 model you are using.

**Comment by KrallBigFan** [comment]
got the same issue on MacOS M3, (ollama version is 0.3.4, llama3:70b run ok):

`~ ollama run llama3.1:70b
pulling manifest
Error: pull model manifest: 412: 
The model you are attempting to pull requires a newer version of Ollama.
Please download the latest version at:
https://ollama.com/download`

in fact, this is what https://registry.ollama.ai/v2/library/llama3.1/manifests/70b returns.

**Comment by igorschlum** [comment]
@KrallBigFan can you check with 

```bash
ollama --version
```
what is your version.
You should have

ollama version is 0.3.4

if ollama cannot pull your model, can you try

```bash
ollama rm llama3.1:70b
```

and then again

```bash
ollama pull llama3.1:70b
```

let us know if it works.

**Comment by KrallBigFan** [comment]
no more issue after the reinstalling the brew package:
`brew reinstall ollama` 
and 
`brew services restart ollama`
