### ISSUE TITLE
Cannot get to UI Web page

### ISSUE THREAD

**Issue by lamachine** [ollama/ollama#6268]
### What is the issue?

Installed ollama .34 on windows, pointed it to a different location for models.  I can use the command line interface, but cannot get to the UI.  I checked the server log and found
` time=2024-08-08T17:41:36.431-07:00 level=INFO source=server.go:626 msg="waiting for server to become available" status="llm server error"`

I uninstalled and reinstalled.  I had it working on docker, but wanted to run native if possible.  

### OS

Windows

### GPU

Nvidia

### CPU

AMD

### Ollama version

0.3.4

**Comment by lamachine** [comment]
>  ollama serve
2024/08/08 18:09:31 routes.go:1108: INFO server config env="map[CUDA_VISIBLE_DEVICES: GPU_DEVICE_ORDINAL: HIP_VISIBLE_DEVICES: HSA_OVERRIDE_GFX_VERSION: OLLAMA_DEBUG:false OLLAMA_FLASH_ATTENTION:false OLLAMA_HOST:http://127.0.0.1:11434 OLLAMA_INTEL_GPU:false OLLAMA_KEEP_ALIVE:5m0s OLLAMA_LLM_LIBRARY: OLLAMA_MAX_LOADED_MODELS:0 OLLAMA_MAX_QUEUE:512 OLLAMA_MODELS:F:\\Ollama\\ollama_models OLLAMA_NOHISTORY:false OLLAMA_NOPRUNE:false OLLAMA_NUM_PARALLEL:0 OLLAMA_ORIGINS:[http://localhost https://localhost http://localhost:* https://localhost:* http://127.0.0.1 https://127.0.0.1 http://127.0.0.1:* https://127.0.0.1:* http://0.0.0.0 https://0.0.0.0 http://0.0.0.0:* https://0.0.0.0:* app://* file://* tauri://*] OLLAMA_RUNNERS_DIR:C:\\Users\\Owner\\AppData\\Local\\Programs\\Ollama\\ollama_runners OLLAMA_SCHED_SPREAD:false OLLAMA_TMPDIR: ROCR_VISIBLE_DEVICES:]"
time=2024-08-08T18:09:31.535-07:00 level=INFO source=images.go:781 msg="total blobs: 5"
time=2024-08-08T18:09:31.537-07:00 level=INFO source=images.go:788 msg="total unused blobs removed: 0"
time=2024-08-08T18:09:31.539-07:00 level=INFO source=routes.go:1155 msg="Listening on 127.0.0.1:11434 (version 0.3.4)"
time=2024-08-08T18:09:31.540-07:00 level=INFO source=payload.go:44 msg="Dynamic LLM libraries [cpu cpu_avx cpu_avx2 cuda_v11.3 rocm_v6.1]"
time=2024-08-08T18:09:31.540-07:00 level=INFO source=gpu.go:204 msg="looking for compatible GPUs"
time=2024-08-08T18:09:31.707-07:00 level=INFO source=gpu.go:288 msg="detected OS VRAM overhead" id=GPU-00f80bb6-f1db-f53e-4a4a-27dbdc2f30ce library=cuda compute=8.9 driver=12.4 name="NVIDIA GeForce RTX 4070" overhead="918.0 MiB"
time=2024-08-08T18:09:31.834-07:00 level=INFO source=types.go:105 msg="inference compute" id=GPU-00f80bb6-f1db-f53e-4a4a-27dbdc2f30ce library=cuda compute=8.9 driver=12.4 name="NVIDIA GeForce RTX 4070" total="12.0 GiB" available="10.8 GiB"
time=2024-08-08T18:09:31.834-07:00 level=INFO source=types.go:105 msg="inference compute" id=GPU-bed8562d-fb5d-389f-72d0-fcc5fb8676d9 library=cuda compute=7.5 driver=12.4 name="NVIDIA GeForce GTX 1650" total="4.0 GiB" available="3.2 GiB"
[GIN] 2024/08/08 - 18:11:50 | 200 |            0s |       127.0.0.1 | HEAD     "/"
[GIN] 2024/08/08 - 18:11:50 | 200 |            0s |       127.0.0.1 | GET      "/api/ps"

**Comment by rick-github** [comment]
There is no UI included in ollama.  What program are you using for that purpose?

**Comment by lamachine** [comment]
Rick, @rick-github 

  When I installed the docker version, it gave me a webpage at localhost:8080 that let me select models, load new models, etc.  It required creating an account as admin and let me create other accounts for my family.  When I looked into this on the Anthropic site, they said a web interface should be available at localhost:3000.

**Comment by rick-github** [comment]
Sounds like [open-webui](https://github.com/open-webui/open-webui).  From your issue description, it seems that you can't connect to open-webui with your browser.  What does `docker ps` show?

**Comment by lamachine** [comment]
I got rid of docker ollama in favor of running locally, so docker ps says unrecognized command.  And it does sound like that.  Looks like I am putting docker back in.

**Comment by rick-github** [comment]
It is possible to run open-webui and ollama as standalone services, but personally I think it's much more convenient to run everything inside docker - management and updates are made much simpler.  What was your objection to using docker?
