### ISSUE TITLE
Please add LGAI-EXAONE/EXAONE-3.0-7.8B-Instruct model

### ISSUE THREAD

**Issue by xest** [ollama/ollama#6269]
* huggingface: [LGAI-EXAONE/EXAONE-3.0-7.8B-Instruct](https://huggingface.co/LGAI-EXAONE/EXAONE-3.0-7.8B-Instruct)

**Comment by acejsk** [comment]
yes, i want to add, too

**Comment by xest** [comment]
FYI: https://github.com/xest/hf2ollama

**Comment by xest** [comment]
See also: https://github.com/ggerganov/llama.cpp/commit/c679e0cb5c378bfb63643c44a453345ba8b90126

**Comment by acejsk** [comment]
> FYI: https://github.com/xest/hf2ollama

답변 감사합니다. 혹시 gguf 파일을 만들었나요?
hugging face나 git에 공유해주시면 ollama 에서 사용해 볼 수 있을 것 같습니다.

**Comment by xest** [comment]
> > FYI: https://github.com/xest/hf2ollama
> 
> 답변 감사합니다. 혹시 gguf 파일을 만드셨나요? hugging face나 git에 공유해주시면 ollama 에서 사용해 볼 수 있을 것 같습니다.

https://huggingface.co/bartowski/EXAONE-3.0-7.8B-Instruct-GGUF 참고하세요

**Comment by acejsk** [comment]
> > > FYI: https://github.com/xest/hf2ollama
> > 
> > 
> > 답변 감사합니다. 혹시 gguf 파일을 만드셨나요? hugging face나 git에 공유해주시면 ollama 에서 사용해 볼 수 있을 것 같습니다.
> 
> https://huggingface.co/bartowski/EXAONE-3.0-7.8B-Instruct-GGUF 참고하세요

이것으로 며칠전에 진행해봤습니다. 
ollama create 성공
ollama run 실패 (ollama ver 0.3.8)

**Comment by freddydopfel** [comment]
Are either of these Exaone? Or just someone claiming to have it be Exaone?

https://ollama.com/onebottlekick/exaone
https://ollama.com/jmpark333/exaone

**Comment by freddydopfel** [comment]
> Are either of these Exaone? Or just someone claiming to have it be Exaone?
> 
> https://ollama.com/onebottlekick/exaone https://ollama.com/jmpark333/exaone

I am a bit suspicious that this may not be ExaOne though.

**Comment by jmorganca** [comment]
https://ollama.com/library/exaone3.5
