### ISSUE TITLE
ollama does not work continuously

### ISSUE THREAD

**Issue by peanutpaste** [ollama/ollama#6270]
### What is the issue?

After I start the ollama service, it will freeze when I run it for a while. When I access it, it will keep loading, but there is no result. I kill the thread, and after restarting it, it can be used for a while (or a certain number of accesses), and then it will freeze again. Why is this?
My Divice is A6000(48G)

[Service]
ExecStart=/usr/local/bin/ollama serve
User=ollama
Group=ollama
Restart=always
RestartSec=3
Environment="OLLAMA_MODELS=/home/q/ollama_models"
Environment="OLLAMA_HOST=0.0.0.0"
Environment="OLLAMA_NUM_PARALLEL=32"
Environment="OLLAMA_MAX_QUEUE=2048"

**Comment by rick-github** [comment]
[Server logs](https://github.com/ollama/ollama/blob/main/docs/troubleshooting.md#how-to-troubleshoot-issues) will help in debugging.

**Comment by dhiltgen** [comment]
If you're still having problems, please make sure to upgrade to the latest version and if that doesn't clear it up, please share your server log and I'll reopen so we can investigate.
