### ISSUE TITLE
Ollama Creat  手动部署 报错 Error: invalid file magic

### ISSUE THREAD

**Issue by JaminYan** [ollama/ollama#6272]
### What is the issue?

按飞书文档找的modelfile 文件，ollama creat 后输出报错
Error: invalid file magic  ，因此无法部署在ollama

### OS

Windows

### GPU

Nvidia

### CPU

AMD

### Ollama version

0.34

**Comment by rick-github** [comment]
Contents of modelfile?  Which model are you trying to import?

**Comment by JaminYan** [comment]
FROM ./MiniCPM-V-2_6/model/ggml-model-Q4_K_M.gguf
FROM ./MiniCPM-V-2_6/mmproj-model-f16.gguf

TEMPLATE """{{ if .System }}<|im_start|>system

{{ .System }}<|im_end|>{{ end }}

{{ if .Prompt }}<|im_start|>user

{{ .Prompt }}<|im_end|>{{ end }}

<|im_start|>assistant<|im_end|>

{{ .Response }}<|im_end|>"""

PARAMETER stop "<|endoftext|>"
PARAMETER stop "<|im_end|>"
PARAMETER num_ctx 2048

**Comment by JaminYan** [comment]
ggml-model-Q4_K_M.gguf  and ggml-model-f16.gguf are all from huggingface

**Comment by rick-github** [comment]
MiniCPM-V-2_6 is not supported yet.  When https://github.com/ggerganov/llama.cpp/pull/7599 is merged then it will work.

**Comment by JaminYan** [comment]
Thanks

**Comment by jmorganca** [comment]
Closing as we are tracking if MiniCPM is supported! Thanks for the issue, and thanks @rick-github

**Comment by arkohut** [comment]
The official model minicpm-v is already there. So I think right now it is supported? But I still get error message "Error: invalid file magic" when I try to create a Q4_K_M model using ollama. 

BTW ollama can create a fp16 model successfully.

**Comment by yjflike1** [comment]
I meet the same issue...

**Comment by yzyhyt** [comment]
I have met the same problem when creating minicpm-v 2.6 Q4_K_M model using ollama, while llama.cpp can smoothly run the model.

**Comment by rick-github** [comment]
What commands are you running to create the model?

**Comment by yzyhyt** [comment]
> What commands are you running to create the model?

I've used `ollama create minicpm2.6 -f minicpmv2_6.Modelfile` to create the model.

minicpmv2_6.Modelfile is like this:
```
FROM ./MiniCPM-V-2_6/model/ggml-model-Q4_K_M.gguf
FROM ./MiniCPM-V-2_6/mmproj-model-f16.gguf

TEMPLATE """{{ if .System }}<|im_start|>system

{{ .System }}<|im_end|>{{ end }}

{{ if .Prompt }}<|im_start|>user

{{ .Prompt }}<|im_end|>{{ end }}

<|im_start|>assistant<|im_end|>

{{ .Response }}<|im_end|>"""

PARAMETER stop "<|endoftext|>"
PARAMETER stop "<|im_end|>"
PARAMETER num_ctx 2048
```

**Comment by rick-github** [comment]
Where are you getting the GGUF files from, or how are you creating them?

**Comment by yzyhyt** [comment]
> Where are you getting the GGUF files from, or how are you creating them?

I directly download the GGUF files from [https://huggingface.co/openbmb/MiniCPM-V-2_6-gguf/tree/main](url) instead of manually converting from pytorch weights.

**Comment by rick-github** [comment]
The ggml-model-Q4_K_M.gguf that I downloaded has 8 extra null bytes on the end, these confuse ollama.  If your copy of the file is 4681089344 bytes long, this is the problem.  On linux, you can remove these bytes with:
```
truncate --size=4681089336 ggml-model-Q4_K_M.gguf
```
On windows:
```
FSUTIL file seteof ggml-model-Q4_K_M.gguf 4681089336
```

**Comment by arkohut** [comment]
> The issue has been fixed. Thank you so much. By the way, could you tell me how to swiftly judge if a file has extra null bytes on its end? I used xxd command but it's too slow.

Could you please tell me how to solve it? I have the same issue.

**Comment by rick-github** [comment]
```console
$ xxd -R never -s -32 ggml-model-Q4_K_M.gguf
11703c120: aac7 5652 a521 b9a5 65b4 65b8 aca0 5554  ..VR.!..e.e...UT
11703c130: 80ad a564 9499 8900 0000 0000 0000 0000  ...d............
```

**Comment by rick-github** [comment]
I have a modified ollama that I used to detect this problem.
```diff
diff --git a/llm/ggml.go b/llm/ggml.go
index e857d4b8..0f92965a 100644
--- a/llm/ggml.go
+++ b/llm/ggml.go
@@ -324,6 +324,7 @@ func DecodeGGML(rs io.ReadSeeker, maxArraySize int) (*GGML, int64, error) {
 
        rs = bufioutil.NewBufferedSeeker(rs, 32<<10)
 
+        xx, _ := rs.Seek(0, io.SeekCurrent)
        var magic uint32
        if err := binary.Read(rs, binary.LittleEndian, &magic); err != nil {
                return nil, 0, err
@@ -340,7 +341,7 @@ func DecodeGGML(rs io.ReadSeeker, maxArraySize int) (*GGML, int64, error) {
        case FILE_MAGIC_GGUF_BE:
                c = &containerGGUF{ByteOrder: binary.BigEndian, maxArraySize: maxArraySize}
        default:
-               return nil, 0, errors.New("invalid file magic")
+               return nil, 0, errors.New(fmt.Sprintf("invalid file magic at %d", xx))
        }
 
        model, err := c.Decode(rs)

```

**Comment by yzyhyt** [comment]
I appreciate your help and instruction. if your modification is merged, it will be easier to figure out the problem.

**Comment by fengqiliang93** [comment]
> The ggml-model-Q4_K_M.gguf that I downloaded has 8 extra null bytes on the end, these confuse ollama. If your copy of the file is 4681089344 bytes long, this is the problem. On linux, you can remove these bytes with:
> 
> ```
> truncate --size=4681089336 ggml-model-Q4_K_M.gguf
> ```
> 
> On windows:
> 
> ```
> FSUTIL file seteof ggml-model-Q4_K_M.gguf 4681089336
> ```

My ggml-model-Q4_K_M.gguf file is quantified by myself, and the size is 4681089440. After I follow this  command, `ollama create...`  worked, but `ollama run...`  reports error was :

> Error: llama runner process has terminated: error loading model: tensor 'output.weight' data is not within the file bounds, model is corrupted or incomplete

**Comment by rick-github** [comment]
My advice was based on that specific file.  A different file will require different corrective measures.

**Comment by arkohut** [comment]
BTW using command `ollama create xxxx -f Modelfile -q Q4_K_M` to perform quantization with Ollama will not encounter this issue.
