### ISSUE TITLE
unsupported content type: unknown

### ISSUE THREAD

**Issue by little1d** [ollama/ollama#6273]
### What is the issue?

Is ollama available to create model through safetensors file?
I run this commad, and error says unsupported content type: unknown. I have tried llama3.1 model and qwen2-0.5b, same outcome

**`command`**
ollama create mymodel2 -f ./Modelfile
![image](https://github.com/user-attachments/assets/c395b48d-a37b-4f5f-8c75-c60163dc8f58)
**`model file`**
![image](https://github.com/user-attachments/assets/e860bd3b-e622-4a7c-acc7-07e23a4959aa)
**`Modelfile`**
`FROM ./model/llama.safetensors`

### OS

Windows

### GPU

Nvidia

### CPU

Intel

### Ollama version

0.3.4

**Comment by rick-github** [comment]
When importing safetensors, you specify the directory, not the full path:
```
FROM ./model
```

**Comment by little1d** [comment]
> When importing safetensors, you specify the directory, not the full path:
> 
> ```
> FROM ./model
> ```
Thank you!
I find something intresting!
if i rename the safetensors' name,such as llama.safetensors, it goes wrong
![image](https://github.com/user-attachments/assets/1ca17806-da0d-4790-ae89-8d8006a76c89)
but if I rename this file as model.safetensors, it works well!

**Comment by little1d** [comment]
still some problems, when I created the model with modelfile
Error Message:
![image](https://github.com/user-attachments/assets/ca37aaa5-1517-47a3-9189-8b1492706410)
where is the config.json?

**Comment by rick-github** [comment]
Where did you download the safetensor from?  That's where config.json should be.

**Comment by mxyng** [comment]
to summarize, creating an ollama model from safetensors (or pytorch) requires more than just the `*.safetensors` files. model metadata and vocabulary is distributed across multiple files which are all required for import. therefore, you need to specify the entire directory rather than individual files
