### ISSUE TITLE
Intel GPU in Docker container crashes

### ISSUE THREAD

**Issue by Minionflo** [ollama/ollama#6284]
### What is the issue?

with the error `panic: runtime error: invalid memory address or nil pointer dereference`

Docker Compose File: https://bin.minionflo.net/p/E9gFhE.yaml

Log: https://bin.minionflo.net/p/QyrT8Z.txt

### OS

Docker on Linux

### GPU

Intel

### CPU

AMD

### Ollama version

0.3.4

**Comment by dhiltgen** [comment]
Intel isn't officially supported yet, but it does look like we have a null pointer dereference that needs to be fixed.
