### ISSUE TITLE
UHD intel GPU Accelerate

### ISSUE THREAD

**Issue by jomardyan** [ollama/ollama#6287]
### What is the issue?

Why Ollama  use CPU, but not utilizing intel UHD integrated GPU ? 

(Computer with not Nvidia GPU) 

### OS

Linux

### GPU

Intel

### CPU

Intel

**Comment by dhiltgen** [comment]
Integrated Intel GPU support is tracked via #3113

**Comment by ayttop** [comment]
https://github.com/intel-analytics/ipex-llm/blob/main/docs/mddocs/Quickstart/llama_cpp_quickstart.md
