### ISSUE TITLE
"The model you are attempting to pull requires a newer version of Ollama" when Ollama is built from the latest source

### ISSUE THREAD

**Issue by sammcj** [ollama/ollama#6293]
### What is the issue?

When trying to pull models from the official Ollama registry - if you're building Ollama from source it now seems to fail with an error that your Ollama version is too old.

```
ollama pull llama3.1:8b-instruct-q8_0
pulling manifest
Error: pull model manifest: 412:

The model you are attempting to pull requires a newer version of Ollama.

Please download the latest version at:

	https://ollama.com/download
```

However I highly doubt my Ollama version is too old as I bought it from source every day.

```
ollama --version
ollama version is e9aa5117c409c94861af1c50b246f29a72d05147
```

### OS

Linux, Docker

### GPU

Nvidia

### CPU

AMD

### Ollama version

e9aa5117c409c94861af1c50b246f29a72d05147

**Comment by dhiltgen** [comment]
Typically the default version for local builds shows up as 0.0.0
```
./ollama --version
ollama version is 0.3.0
Warning: client version is 0.0.0
```

Are you doing anything special to get the hash version string?  How did you build?

**Comment by sammcj** [comment]
Ah, yes indeed - I am setting it to the commit SHA as I thought 0.0.0 was a bug actually!

FYI 0.0.0 was causing some Ollama clients (I can't remember which right now) to error stating the version was too old as I'm assuming they're doing something simple like checking =< <version>.

Thanks for the tip Daniel :)

**Comment by dhiltgen** [comment]
Check out the various `./scripts/build*` scripts for how we set the version using `git describe` which will incorporate the nearest git tag, plus your hash, so that can be useful if you want a more "real" version string.

**Comment by sammcj** [comment]
That's actually really useful, thank you.

Can confirm swapping back to 0.0.0 works for pulling now as well.

```
ollama pull llama3.1:8b-instruct-q8_0
pulling manifest
...
```

**Comment by jvel07** [comment]
Hi @dhiltgen!
On a fresh install `docker run -d --gpus=all -v ollama:/root/.ollama -p 11434:11434 --name ollama ollama/ollama` and then `docker exec -it ollama ollama pull llama3.1` I get:

```
pulling manifest 
Error: pull model manifest: 412: 

The model you are attempting to pull requires a newer version of Ollama.

Please download the latest version at:

        https://ollama.com/download
```
Am I missing something?

**Comment by darkstar1227** [comment]
> 你好@dhiltgen！ 全新安裝`docker run -d --gpus=all -v ollama:/root/.ollama -p 11434:11434 --name ollama ollama/ollama`後`docker exec -it ollama ollama pull llama3.1`我得到：
> 
> ```
> pulling manifest 
> Error: pull model manifest: 412: 
> 
> The model you are attempting to pull requires a newer version of Ollama.
> 
> Please download the latest version at:
> 
>         https://ollama.com/download
> ```
> 
> 我錯過了什麼嗎？

I am also facing this problem for pulling llama3.1 and I just pull the newest ollama docker.
May I ask whether you figure it out?

**Comment by dhiltgen** [comment]
Can you check which version of Ollama is in your container image?  Have you run a `docker pull ollama/ollama` to update the image to the latest version?    I just pulled `ollama/ollama:latest` which contains version 0.3.5 and was able to pull llama3.1.

**Comment by darkstar1227** [comment]
Hi, I just recompose again today, and it is working now. Thank you very much.
