### ISSUE TITLE
Ability to preload embedding model

### ISSUE THREAD

**Issue by comunidadio** [ollama/ollama#6295]
The "empty request" trick to preload a model does not currently work for embedding models.

Source: https://github.com/ollama/ollama/blob/main/docs/faq.md#how-can-i-preload-a-model-into-ollama-to-get-faster-response-times and #2431 

```
$ curl http://localhost:11434/api/embed -d '{"model": "all-minilm:latest"}'
{"error":"invalid input type"}%       
```

```
ollama --version
ollama version is 0.3.4
```

**Comment by PaulCapestany** [comment]
I just send a throwaway request with infinite `keep_alive`, like so:

```sh
curl http://localhost:11434/api/embed -d "{\"input\": \"whatever\", \"model\": \"bge-m3\", \"keep_alive\": -1}"
```
