### ISSUE TITLE
Better to add athene70b f16 and q8

### ISSUE THREAD

**Issue by Llamadouble999q** [ollama/ollama#6296]
Why ollama stopped uploading athene?

**Comment by MaxJa4** [comment]
The used GGUF source (https://huggingface.co/bullerwins/Athene-70B-GGUF) had split files for Q6_K and Q8_0, which is not compatible with Ollama's import yet (#5245).

I converted the GGUFs myself now from the original model authors' HF and quantized the remaining types, so there's Q6_K, Q8_0 and FP16 now too:
https://ollama.com/finalend/athene-70b

**Comment by MaxJa4** [comment]
@Llamadouble999q can this be closed now?

**Comment by jmorganca** [comment]
Thanks for uploading @MaxJa4. I'll close for now @Llamadouble999q but let me know any issues remain
