### ISSUE TITLE
ollama creates a new ollama runner folder each container restart

### ISSUE THREAD

**Issue by Minionflo** [ollama/ollama#6300]
### What is the issue?

If you for example run ollama/ollama with `--restart=unless-stopped` and it crashes after “extracting embedded files” it creates a new Ollama runner folder in /tmp/ and with each additional restart it creates a new folder. This behavior fills the Host Disk VERY fast.

### OS

Docker

### GPU

Intel

### CPU

AMD

### Ollama version

0.3.4

**Comment by rick-github** [comment]
You can tell ollama to use a consistent directory by setting `OLLAMA_TMPDIR` in the environment, eg `--env OLLAMA_TMPDIR=/tmp/ollama`.

**Comment by Minionflo** [comment]
That works Thanks, but I think it should not do that in the first place

**Comment by dhiltgen** [comment]
We fixed some cleanup logic in v0.3.5 which should hopefully resolve this.  If you're still seeing this behavior of leaving old tmp dir extracts lying around after a restart on newer versions, please share a server log with OLLAMA_DEBUG=1 set and I'll reopen the issue.
