### ISSUE TITLE
Running ollama on island device with no Internet connection

### ISSUE THREAD

**Issue by whatdhack** [ollama/ollama#6306]
Trying to run ollama on island devices  with no Internet connection.  Getting the following error message. 

`Error: pull model manifest: Get "https://registry.ollama.ai/v2/library/llama2/manifests/latest":`

**Comment by rick-github** [comment]
Downloading a model requires internet connectivity.  You can download the model on a different computer and copy it across if the island device cannot be connected.  Where the [model is stored](https://github.com/ollama/ollama/blob/main/docs/faq.md#where-are-models-stored) depends on your setup.

**Comment by jmorganca** [comment]
Hi @whatdhack as @rick-github mentioned you'd need to be connected to `ollama pull` a model, or to `ollama run` (if you don't have it yet)

**Comment by whatdhack** [comment]
Can ollama use the  Meta  format  models ?  For example the 16GB llama 3.1 models ?

**Comment by rick-github** [comment]
https://ollama.com/library/llama3.1

**Comment by whatdhack** [comment]
On a host with access to the Internet, I set the OLLAMA_MODELS variable. It was ignored and ollama  pulled the model to ~/.ollama .

**Comment by whatdhack** [comment]
https://ollama.com/library/llama3.1 shows it is using the 4 bit checkpoint

**Comment by whatdhack** [comment]
Still tries to  pull , even when the model was already available in ~/.ollama/models

**Comment by rick-github** [comment]
https://ollama.com/library/llama3.1:8b-instruct-fp16

**Comment by rick-github** [comment]
The ollama server does the work of pulling the model, so `OLLAMA_MODELS` has to set in the environment of the server.

**Comment by whatdhack** [comment]
Hmm, "OLLAMA_MODELS has to set in the environment of the server " - was in fact set

**Comment by rick-github** [comment]
[Server logs](https://github.com/ollama/ollama/blob/main/docs/troubleshooting.md#how-to-troubleshoot-issues) will help in debugging.
