### ISSUE TITLE
Sharing computing power in a decentralized P2P network

### ISSUE THREAD

**Issue by trymeouteh** [ollama/ollama#6315]
To have a feature built into Ollama to join the Ollama P2P network. When you join this network, you can use computing power from others in the network and also share your computing power.

Privacy should be in mind by using E2EE, choosing which models on your system is apart of the P2P network, settings to disable and enable the use of the P2P network and if the [users](https://github.com/ollama/ollama/issues/2863) feature becomes a thing, to allow users the setting on weather to be apart or use this P2P network when working with models.

Twinny Symmetry Project
https://twinny.dev/symmetry

**Comment by rick-github** [comment]
ollama is already listed as an Inference provider in twinny.

**Comment by Readon** [comment]
It would be also an good idea to share computing power in a private LAN.
