### ISSUE TITLE
ollama create will use a large amount of disk space in the /tmp

### ISSUE THREAD

**Issue by garyyang85** [ollama/ollama#6316]
### What is the issue?

ollama create cmd will use a large amount of disk space in the /tmp directory by default. Is there a way to change the /tmp to other directory?

### OS

Linux

### GPU

Nvidia

### CPU

Intel

### Ollama version

latest

**Comment by jmorganca** [comment]
Hi there, this should be fixed in https://github.com/ollama/ollama/releases/tag/v0.3.5. If you'd like to install it ahead of it being fully released you can run:

```
curl -fsSL https://ollama.com/install.sh | OLLAMA_VERSION=0.3.5 sh
```

**Comment by garyyang85** [comment]
Hi @jmorganca  I want to find a way to use another disk directory instead of /tmp when run ollama create. I have a lot of space in other directories but not /tmp.  Can I do this?

**Comment by rick-github** [comment]
https://github.com/ollama/ollama/blob/01b80e9ffcd05825b413b61a91f9656723ce8afa/envconfig/config.go#L260
