### ISSUE TITLE
Feature request : Tools support of Qwen2

### ISSUE THREAD

**Issue by trinhkiet0105** [ollama/ollama#6317]
**Why ?** 
So i just found out that Qwen2 have tools support. However, ollama current do not have tools support for qwen2 models. And there is a section of [Qwen2 github talking about ollama on tools use](https://github.com/QwenLM/Qwen2?tab=readme-ov-file#-run-locally
). And this seems prombles of ollama in older versions. I think this should be resolvable with version 0.3.x 

**Request**

- I would like to request tools support for Qwen2 models
- If possible I would like to know how the process of adding tools support for a model (like ollama team can add tools to Qwen2 directly or participation of Qwen2 team is required)

Thanks for reading

**Comment by hlstudio** [comment]
may be you can pull [sam4096/qwen2tools](https://ollama.com/sam4096/qwen2tools) and test.
then check the modelfile，only the modelfile has been modified，and the model weight file has not changed, which is exactly the same as the original qwen2

**Comment by trinhkiet0105** [comment]
> So i just found out that Qwen2 have tools support. However, ollama current do not have tools support for qwen2 models. And there is a section of [Qwen2 github talking about ollama on tools use](https://github.com/QwenLM/Qwen2?tab=readme-ov-file#-run-locally). And this seems prombles of ollama in older versions. I think this should be resolvable with version 0.3.x

It work! thank you

**Comment by trinhkiet0105** [comment]
> [hlstudio](/hlstudio)

It works! thank you

**Comment by codefromthecrypt** [comment]
#6007 has most progress from the Qwen maintainer, so perhaps we can close this one and focus energy on getting the other sorted out?

**Comment by jmorganca** [comment]
@codefromthecrypt thanks! Will close for https://github.com/ollama/ollama/issues/6007
