### ISSUE TITLE
ollama.app cannot open on my macbookpro with m3 pro

### ISSUE THREAD

**Issue by Spockkk0225** [ollama/ollama#6318]
### What is the issue?

environment: macbook pro, m3 pro, 18gb memory, Sonoma 14.4.1

the ollama.app cannot be opened with double click
it reports segmentation fault when I execute it in terminal

\>\>\> /Applications/Ollama.app/Contents/MacOS/ollama 
<<< segmentation fault  /Applications/Ollama.app/Contents/MacOS/ollama

<img width="523" alt="截屏2024-08-12 13 07 49" src="https://github.com/user-attachments/assets/b7b0d4c3-66c0-4920-b7d0-ce8d8a7e4dde">

### OS

macOS

### GPU

Apple

### CPU

Apple

### Ollama version

0.3.4

**Comment by MaxJa4** [comment]
Weird, I have exactly the same machine and everything works fine. Did you try a clean reinstall of ollama? Like deleting it entirely and then reinstalling with the newest version?

**Comment by Spockkk0225** [comment]
> Weird, I have exactly the same machine and everything works fine. Did you try a clean reinstall of ollama? Like deleting it entirely and then reinstalling with the newest version?
> 
> Edit: Also setting the env var OLLAMA_DEBUG=1 could help with additional info.

Thanks for your suggestion! Instead, I use homebrew to install. I don't know why but now it works... Maybe there are some environment issues.
> brew install ollama

**Comment by igorschlum** [comment]
@Spockkk0225 It's recommended to install Ollama with the installer downloaded from Ollama.com, as updates are then automatic. I had an issue 
with updates because I installed Ollama using Homebrew.
Read [issue #5619](https://github.com/ollama/ollama/issues/5619) for more details.

if you want to stay with HomeBrew, please follow [those guidelignes](https://github.com/ollama/ollama/blob/main/docs/troubleshooting.md)  to provide logs or close the issue.

**Comment by FellowTraveler** [comment]
Then Ollama should be removed from brew entirely.

**Comment by Spockkk0225** [comment]
However, I **can** only install Ollama with homebrew.
Application often has some unknown limitations.

**Comment by igorschlum** [comment]
I had a problem becquée I installed Ollama with homebrew, but then switch to manual install. Ollama was well updated, but not CLI.

If Ollama is installed with homebrew, CLI is installed in standard homebrew destination folder that is not the same as where ollama install CLI.

So yes Ollama should works well with Homebrew is you stay with this installation and then use homebrew script to update it.

**Comment by pdevine** [comment]
@Spockkk0225 we don't maintain the ollama application on Homebrew; I think that's done by the Homebrew folks? I'll go ahead and close the issue.

**Comment by zhaihuayang** [comment]
@Spockkk0225  use `sudo spctl --master-disable` in terminal, and then reboot your macbook, should solve your problem
