### ISSUE TITLE
Ubuntu based rocm images

### ISSUE THREAD

**Issue by kunaltyagi** [ollama/ollama#6320]
Currently, rocm image is based on centos. Could we add ubuntu based rocm images as well?

**Comment by jmorganca** [comment]
Hi @kunaltyagi, thanks for the issue!

We built with centos since it has an older and more compatible version of glibc. May I ask why you'd want Ubuntu-based images? They are quite large and so we're hoping to stick to one Docker image – let me know and I can re-open the issue as needed!

**Comment by kunaltyagi** [comment]
I'm not able to use centos image in my docker compose, but using rocm ubuntu base, I was able to set the groups and use the GPU

How should I use the centos rocm images so I can use GPU?

**Comment by cazlo** [comment]
There are several compelling reasons to make the switch to Ubuntu Rocm layers away from Centos.

In this case, the Ubuntu layers are actually a little smaller:
- [rocm/dev-ubuntu-24.04:6.2](https://hub.docker.com/r/rocm/dev-ubuntu-24.04/tags) = 1.0 GB (last push 2 months ago)
- [rocm/dev-centos-7:6.2](https://hub.docker.com/r/rocm/dev-centos-7/tags) = 1.68 GB (last push 2 months ago)

Also Centos 7 is EOL, while Ubuntu 24.04 is not. See also https://endoflife.date/centos

Also Ubuntu 24.04 is officially supported by Rocm, while Centos 7 is not. See also https://rocm.docs.amd.com/en/docs-6.2.0/about/release-notes.html#operating-system-and-hardware-support-changes

> ROCm 6.2.0 marks the end of support (EoS) for:
> ...
> CentOS 7.9

I'm messing around with a few performance analysis tests now, if I get some time, I'll see if there is an easy migration path to the Ubuntu image.
