### ISSUE TITLE
Feature request : get probability distribution

### ISSUE THREAD

**Issue by Alireza3242** [ollama/ollama#6321]
I have a prompt and then i get an answer. In some part of answer is a JSON, something like this:
```
{
    res:"yes"
}
```
or this:
```
{
    res:"no"
}
```
I want to know the probability of token "yes" and "no". and use these probabilities in some algorithm.

**Comment by jmorganca** [comment]
Hi there, will merge this with https://github.com/ollama/ollama/issues/2415
