### ISSUE TITLE
Error: pull model manifest:

### ISSUE THREAD

**Issue by w123456789zy** [ollama/ollama#6332]
### What is the issue?

pulling manifest
Error: pull model manifest: Get "https://registry.ollama.ai/v2/library/llama3.1/manifests/latest": read tcp 192.168.0.106:50767->172.67.182.229:443: wsarecv: An existing connection was forcibly closed by the remote host.

### OS

Windows

### GPU

Nvidia

### CPU

Intel

### Ollama version

0.3.5

**Comment by pdevine** [comment]
Looks like a dupe of #4042
