### ISSUE TITLE
./ollama-linux-amd64 pull llama3.1:405b the rate very slow, only several Kb/s

### ISSUE THREAD

**Issue by EGOIST5** [ollama/ollama#6334]
### What is the issue?

Before the version of ollama-linux-amd64 update, I could pull the models normally. But once I updated the new version of ollama-linux-amd64, pulling the models fails frequently.
Command: ./ollama-linux-amd64 pull llama3.1:405b
sometimes it will print the following error:
Error: pull model manifest: Get "https://registry.ollama.ai/v2/library/llama3.1/manifests/405b": net/http: TLS handshake timeout
And sometimes I could pull the request, but the download rate is nearly zero
And the server will report:
time=2024-08-13T05:24:21.850-04:00 level=INFO source=download.go:370 msg="939fd971f038 part 43 stalled; retrying. If this persists, press ctrl-c to exit
, then 'ollama pull' to find a faster connection."
time=2024-08-13T05:24:21.881-04:00 level=INFO source=download.go:291 msg="939fd971f038 part 10 attempt 1 failed: Get \"https://dd20bb891979d25aebc8bec07
b2b3bbc.r2.cloudflarestorage.com/ollama/docker/registry/v2/blobs/sha256/93/939fd971f03801a9447af720a78d1fc00833cadf05252b4fc871bfb70eafdda6/data?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=66040c77ac1b787c3af820529859349a%2F20240813%2Fauto%2Fs3%2Faws4_request&X-Amz-Date=20240813T092341Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-Amz-Signature=e9309a6a23b298d8993983a4c47f04311f5dfe41037808a421ba240c37b9f0af\": net/http: TLS handshake timeout, retrying in 2s"

**Comment by rampageservices** [comment]
Have you tried running speed tests separately to ensure it is not your connection?
https://www.speedtest.net/

I'm not saying it is 100% not a problem with Ollama but if you show that your connection fares well in speed tests while your having issues pulling it could lead to better knowledge that it is indeed an Ollama issue.

**Comment by EGOIST5** [comment]
> Have you tried running speed tests separately to ensure it is not your connection? https://www.speedtest.net/
> 
> I'm not saying it is 100% not a problem with Ollama but if you show that your connection fares well in speed tests while your having issues pulling it could lead to better knowledge that it is indeed an Ollama issue.

Thank you a lot. Before I saw your reply, I can download normally again, maybe my bad network. Thank you
