### ISSUE TITLE
Windows Defender

### ISSUE THREAD

**Issue by Eniti-Codes** [ollama/ollama#6342]
### What is the issue?

So for some reason, with the newest update, Windows Defender thinks this is a Trojan.
<img width="210" alt="ApplicationFrameHost_ye04kXZxFA" src="https://github.com/user-attachments/assets/85525c54-a0ca-40e5-a764-f4227bf73ba3">

### OS

Windows

### GPU

Nvidia

### CPU

AMD

### Ollama version

I don't know. Windows removed it

**Comment by jmorganca** [comment]
Hi there. Sorry you hit this. This is a false positive - we are working with Microsoft to fix the virus definitions as in the past.
