### ISSUE TITLE
Is this wrong in https://ollama.com/blog/gemma2

### ISSUE THREAD

**Issue by wonpn** [ollama/ollama#6350]
### What is the issue?

![PixPin_2024-08-14_11-53-39](https://github.com/user-attachments/assets/3c245d45-3f4c-4ed8-87d1-727b31797ec9)

8B to 9B？

### OS

Windows

### GPU

Nvidia

### CPU

Intel

**Comment by zwilch** [comment]
### https://ollama.com/library/gemma2
<img width="409" alt="gemma2-2b-9b-27b" src="https://github.com/user-attachments/assets/9a00409c-5f6c-44f3-b1b6-2719d3c3170c">

- ** https://ollama.com/library/gemma2:2b
- ** https://ollama.com/library/gemma2:9b
- ** https://ollama.com/library/gemma2:27b

**Comment by mchiang0610** [comment]
Thank you. It is 2B, 9B, and 27B. 

I will correct this, and deploy the blog post with the fixes.
