### ISSUE TITLE
Embedding interface routing

### ISSUE THREAD

**Issue by xuzeyu91** [ollama/ollama#6354]
The chat interface is currently compatible with OpenAI in terms of interface routing.
Would you consider making Embedding's interface routing also compatible with OpenAI's format, so that it will be more user-friendly when called by third-party applications? Otherwise, we need to focus on
```
http://host/v1/embeddings
```
 Perform separate processing 
```
http://host/embeddings  
```
If it's compatible, that would be great

**Comment by xuzeyu91** [comment]
Sorry, I see that the current version already supports it

**Comment by FellowTraveler** [comment]
@xuzeyu91 Can you please close this issue?

**Comment by xuzeyu91** [comment]
yes
