### ISSUE TITLE
Segmentation fault 

### ISSUE THREAD

**Issue by yicheng-2019** [ollama/ollama#6358]
I want to express my appreciation for the fantastic work done on this project. The capabilities and ease of use are truly impressive. 

However, after successfully deploying and running a model using the Ollama remote API, I encountered an issue that I haven't been able to resolve. I would like to ask if you have any experience or suggestions regarding the following problem.

After running and deploying a model using the remote API of ollama for an extended period, I encountered a segmentation fault that now persists across all commands. Initially, the software functioned correctly, but after a period of operation, all ollama commands, including ollama list, now result in a segmentation fault. Even after reinstalling the latest version of ollama, the issue persists, rendering the tool completely unusable.

Actual Behavior:
Any attempt to run an ollama command results in a segmentation fault. Here is an example output.

(base) qiuyc@server21:~$ ollama -v
Segmentation fault

### OS

Linux

### GPU

Nvidia

### CPU

AMD

### Ollama version

latest

**Comment by yicheng-2019** [comment]
Thank you for your suggestion. Based on the command you provided, I obtained the following results:


(base) qiuyc@server21:/aidata/qiuyc/tools/ollama$ which ollama
/usr/local/bin/ollama

(base) qiuyc@server21:/aidata/qiuyc/tools/ollama$ ldd ollama
ldd: ./ollama: No such file or directory

(base) qiuyc@server21:/aidata/qiuyc/tools/ollama$ strace ollama -v
execve("/usr/local/bin/ollama", ["ollama", "-v"], 0x7ffc16d531a8 /* 34 vars */) = 0
brk(NULL)                               = 0x2400c000
arch_prctl(0x3001 /* ARCH_??? */, 0x7ffff81f72f0) = -1 EINVAL (Invalid argument)
mmap(NULL, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f7aae443000
access("/etc/ld.so.preload", R_OK)      = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/local/cuda-11.8/lib64/tls/haswell/avx512_1/x86_64/libresolv.so.2", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
stat("/usr/local/cuda-11.8/lib64/tls/haswell/avx512_1/x86_64", 0x7ffff81f6540) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/local/cuda-11.8/lib64/tls/haswell/avx512_1/libresolv.so.2", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
stat("/usr/local/cuda-11.8/lib64/tls/haswell/avx512_1", 0x7ffff81f6540) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/local/cuda-11.8/lib64/tls/haswell/x86_64/libresolv.so.2", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
stat("/usr/local/cuda-11.8/lib64/tls/haswell/x86_64", 0x7ffff81f6540) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/local/cuda-11.8/lib64/tls/haswell/libresolv.so.2", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
stat("/usr/local/cuda-11.8/lib64/tls/haswell", 0x7ffff81f6540) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/local/cuda-11.8/lib64/tls/avx512_1/x86_64/libresolv.so.2", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
stat("/usr/local/cuda-11.8/lib64/tls/avx512_1/x86_64", 0x7ffff81f6540) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/local/cuda-11.8/lib64/tls/avx512_1/libresolv.so.2", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
stat("/usr/local/cuda-11.8/lib64/tls/avx512_1", 0x7ffff81f6540) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/local/cuda-11.8/lib64/tls/x86_64/libresolv.so.2", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
stat("/usr/local/cuda-11.8/lib64/tls/x86_64", 0x7ffff81f6540) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/local/cuda-11.8/lib64/tls/libresolv.so.2", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
stat("/usr/local/cuda-11.8/lib64/tls", 0x7ffff81f6540) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/local/cuda-11.8/lib64/haswell/avx512_1/x86_64/libresolv.so.2", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
stat("/usr/local/cuda-11.8/lib64/haswell/avx512_1/x86_64", 0x7ffff81f6540) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/local/cuda-11.8/lib64/haswell/avx512_1/libresolv.so.2", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
stat("/usr/local/cuda-11.8/lib64/haswell/avx512_1", 0x7ffff81f6540) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/local/cuda-11.8/lib64/haswell/x86_64/libresolv.so.2", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
stat("/usr/local/cuda-11.8/lib64/haswell/x86_64", 0x7ffff81f6540) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/local/cuda-11.8/lib64/haswell/libresolv.so.2", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
stat("/usr/local/cuda-11.8/lib64/haswell", 0x7ffff81f6540) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/local/cuda-11.8/lib64/avx512_1/x86_64/libresolv.so.2", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
stat("/usr/local/cuda-11.8/lib64/avx512_1/x86_64", 0x7ffff81f6540) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/local/cuda-11.8/lib64/avx512_1/libresolv.so.2", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
stat("/usr/local/cuda-11.8/lib64/avx512_1", 0x7ffff81f6540) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/local/cuda-11.8/lib64/x86_64/libresolv.so.2", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
stat("/usr/local/cuda-11.8/lib64/x86_64", 0x7ffff81f6540) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/local/cuda-11.8/lib64/libresolv.so.2", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
stat("/usr/local/cuda-11.8/lib64", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
openat(AT_FDCWD, "tls/haswell/avx512_1/x86_64/libresolv.so.2", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "tls/haswell/avx512_1/libresolv.so.2", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "tls/haswell/x86_64/libresolv.so.2", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "tls/haswell/libresolv.so.2", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "tls/avx512_1/x86_64/libresolv.so.2", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "tls/avx512_1/libresolv.so.2", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "tls/x86_64/libresolv.so.2", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "tls/libresolv.so.2", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "haswell/avx512_1/x86_64/libresolv.so.2", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "haswell/avx512_1/libresolv.so.2", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "haswell/x86_64/libresolv.so.2", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "haswell/libresolv.so.2", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "avx512_1/x86_64/libresolv.so.2", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "avx512_1/libresolv.so.2", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "x86_64/libresolv.so.2", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "libresolv.so.2", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/etc/ld.so.cache", O_RDONLY|O_CLOEXEC) = 3
fstat(3, {st_mode=S_IFREG|0644, st_size=104758, ...}) = 0
mmap(NULL, 104758, PROT_READ, MAP_PRIVATE, 3, 0) = 0x7f7aae429000
close(3)                                = 0
openat(AT_FDCWD, "/lib/x86_64-linux-gnu/libresolv.so.2", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0 G\0\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0644, st_size=101352, ...}) = 0
mmap(NULL, 113280, PROT_READ, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f7aae40d000
mmap(0x7f7aae411000, 65536, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x4000) = 0x7f7aae411000
mmap(0x7f7aae421000, 16384, PROT_READ, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x14000) = 0x7f7aae421000
mmap(0x7f7aae425000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x17000) = 0x7f7aae425000
mmap(0x7f7aae427000, 6784, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7f7aae427000
close(3)                                = 0
openat(AT_FDCWD, "/usr/local/cuda-11.8/lib64/libpthread.so.0", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "tls/haswell/avx512_1/x86_64/libpthread.so.0", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "tls/haswell/avx512_1/libpthread.so.0", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "tls/haswell/x86_64/libpthread.so.0", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "tls/haswell/libpthread.so.0", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "tls/avx512_1/x86_64/libpthread.so.0", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "tls/avx512_1/libpthread.so.0", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "tls/x86_64/libpthread.so.0", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "tls/libpthread.so.0", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "haswell/avx512_1/x86_64/libpthread.so.0", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "haswell/avx512_1/libpthread.so.0", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "haswell/x86_64/libpthread.so.0", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "haswell/libpthread.so.0", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "avx512_1/x86_64/libpthread.so.0", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "avx512_1/libpthread.so.0", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "x86_64/libpthread.so.0", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "libpthread.so.0", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/lib/x86_64-linux-gnu/libpthread.so.0", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\220q\0\0\0\0\0\0"..., 832) = 832
pread64(3, "\4\0\0\0\24\0\0\0\3\0\0\0GNU\0\232e\273F\236E\241\306\373\317\372\345\270*/\327"..., 68, 824) = 68
fstat(3, {st_mode=S_IFREG|0755, st_size=157224, ...}) = 0
pread64(3, "\4\0\0\0\24\0\0\0\3\0\0\0GNU\0\232e\273F\236E\241\306\373\317\372\345\270*/\327"..., 68, 824) = 68
mmap(NULL, 140408, PROT_READ, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f7aae3ea000
mmap(0x7f7aae3f0000, 69632, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x6000) = 0x7f7aae3f0000
mmap(0x7f7aae401000, 24576, PROT_READ, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x17000) = 0x7f7aae401000
mmap(0x7f7aae407000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x1c000) = 0x7f7aae407000
mmap(0x7f7aae409000, 13432, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7f7aae409000
close(3)                                = 0
openat(AT_FDCWD, "/usr/local/cuda-11.8/lib64/libstdc++.so.6", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "tls/haswell/avx512_1/x86_64/libstdc++.so.6", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "tls/haswell/avx512_1/libstdc++.so.6", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "tls/haswell/x86_64/libstdc++.so.6", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "tls/haswell/libstdc++.so.6", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "tls/avx512_1/x86_64/libstdc++.so.6", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "tls/avx512_1/libstdc++.so.6", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "tls/x86_64/libstdc++.so.6", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "tls/libstdc++.so.6", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "haswell/avx512_1/x86_64/libstdc++.so.6", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "haswell/avx512_1/libstdc++.so.6", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "haswell/x86_64/libstdc++.so.6", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "haswell/libstdc++.so.6", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "avx512_1/x86_64/libstdc++.so.6", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "avx512_1/libstdc++.so.6", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "x86_64/libstdc++.so.6", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "libstdc++.so.6", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/lib/x86_64-linux-gnu/libstdc++.so.6", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\3\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\0\0\0\0\0\0\0\0"..., 832) = 832
pread64(3, "\5\0\0\0GNU\0\1\0\1\300\4\0\0\0\v\0\0\0\0\0\0\0\2\0\1\300\4\0\0\0"..., 48, 2105168) = 48
fstat(3, {st_mode=S_IFREG|0644, st_size=17981231, ...}) = 0
pread64(3, "\5\0\0\0GNU\0\1\0\1\300\4\0\0\0\v\0\0\0\0\0\0\0\2\0\1\300\4\0\0\0"..., 48, 2105168) = 48
mmap(NULL, 2177152, PROT_READ, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f7aae1d6000
mprotect(0x7f7aae277000, 1449984, PROT_NONE) = 0
mmap(0x7f7aae277000, 1003520, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0xa1000) = 0x7f7aae277000
mmap(0x7f7aae36c000, 442368, PROT_READ, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x196000) = 0x7f7aae36c000
mmap(0x7f7aae3d9000, 57344, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x202000) = 0x7f7aae3d9000
mmap(0x7f7aae3e7000, 10368, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7f7aae3e7000
--- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=0x8} ---
+++ killed by SIGSEGV (core dumped) +++
Segmentation fault

**Comment by rick-github** [comment]
What's the result of these commands:
`command -v ollama`
`ldd /usr/local/bin/ollama`

**Comment by dhiltgen** [comment]
In addition to those commands a few more might shed some light.
```
ls -lh /usr/local/bin/ollama
sha256sum /usr/local/bin/ollama
```

My suspicion is your binary may have somehow become corrupted, so rerunning the install may clear things up.
https://ollama.com/download/linux
