### ISSUE TITLE
About update

### ISSUE THREAD

**Issue by ZX-math** [ollama/ollama#6359]
After using "ollama", I found that this is really an open source project that allows people all over the world to build digital lives by hand, we learn knowledge from it and enjoy it, but I have some small doubts, "ollama" from version 0.1.6 to version 0.3.6, what is the updated content in the middle? Where can I get this information? I hope someone can give me an explanation. and~~——Thank you！

**Comment by rick-github** [comment]
https://github.com/ollama/ollama/releases

**Comment by ZX-math** [comment]
> https://github.com/ollama/ollama/releases

thanks! you are very kind!

**Comment by FellowTraveler** [comment]
@ZX-math please close those PR.
