### ISSUE TITLE
Detected as a virus by windows defender during/after update

### ISSUE THREAD

**Issue by mcDandy** [ollama/ollama#6360]
### What is the issue?

Windows Defender thinks it is some sort of command and control malware. 

![image](https://github.com/user-attachments/assets/9da628f7-60b7-4985-b837-2154b91a7dfc)
![image](https://github.com/user-attachments/assets/47395c68-4d31-48ef-9dbe-7844ecb8b5a8)

### OS

Windows

### GPU

Nvidia

### CPU

Intel

### Ollama version

0.3.5

**Comment by rick-github** [comment]
https://github.com/ollama/ollama/issues/6342

**Comment by mcDandy** [comment]
OH, forgot to check 😅
