### ISSUE TITLE
Error: llama runner process no longer running: -1

### ISSUE THREAD

**Issue by josephyuzb** [ollama/ollama#6370]
### What is the issue?

root@ai-Default-string:/home/ai# ollama run llama3.1:405b
pulling manifest
pulling 939fd971f038... 100% ▕██████████████████████████████████████████████████████████████████████▏ 228 GB
pulling f000eeb056ec... 100% ▕██████████████████████████████████████████████████████████████████████▏ 1.4 KB
pulling 0ba8f0e314b4... 100% ▕██████████████████████████████████████████████████████████████████████▏  12 KB
pulling 56bb8bd477a5... 100% ▕██████████████████████████████████████████████████████████████████████▏   96 B
pulling 02766cd47dfb... 100% ▕██████████████████████████████████████████████████████████████████████▏  487 B
verifying sha256 digest
writing manifest
removing any unused layers
success
Error: llama runner process no longer running: -1

### OS

Linux

### GPU

AMD

### CPU

Intel

### Ollama version

ollama version is 0.0.0

**Comment by josephyuzb** [comment]
root@ai-Default-string:/home/ai# ollama run llama3.1:70b --verbose
Error: llama runner process no longer running: -1

**Comment by rick-github** [comment]
```
ollama version is 0.0.0
```
Using an official release makes it easier to debug.
```
pulling 939fd971f038... 100% ▕███████████▏ 228 GB
```
This is a large model, do you have the resources on your machine to run it?

[Server logs](https://github.com/ollama/ollama/blob/main/docs/troubleshooting.md#how-to-troubleshoot-issues) would help in debugging this issue.

**Comment by dhiltgen** [comment]
@josephyuzb we'll need more info to help troubleshoot.  

As mentioned above, you're trying to load very large models but haven't told us what sort of system you're trying to load them on.  The 405b is ~230GB, and the 70b is ~40GB.   If you can share your server log I'll re-open the issue.
