### ISSUE TITLE
System tray icon is empty

### ISSUE THREAD

**Issue by Biyakuga** [ollama/ollama#6372]
### What is the issue?

In the image below, you'll notice that the hover bubble for the Ollama system tray icon is empty. In contrast, other apps display the application's name when you hover over their icons.

![image](https://github.com/user-attachments/assets/d79a6b65-6a22-4cce-ab62-500a0b409b98)

### OS

Windows

### GPU

Nvidia, Intel

### CPU

Intel

### Ollama version

0.3.6

**Comment by eust-w** [comment]
![image](https://github.com/user-attachments/assets/ac247f68-99f0-417c-908b-b713fa905b9b)
fixed
