### ISSUE TITLE
Open WebUI: Server Connection Error

### ISSUE THREAD

**Issue by ChaoYue97** [ollama/ollama#6384]
### What is the issue?

When I try to download a model through the WebUI, I encounter an error: Open WebUI: Server Connection Error, and I get a notification that the download has been canceled.
![jietu](https://github.com/user-attachments/assets/6632603f-bc18-40b2-922f-f13fda2fcff8)

### OS

Linux

### GPU

Nvidia

### CPU

AMD

### Ollama version

0.3.6

**Comment by Yitianw** [comment]
同样的问题
