### ISSUE TITLE
pulling manifest Error: pull model manifest: 412: The model you are attempting to pull requires a newer version of Ollama.  Please download the latest version at:  https://ollama.com/download

### ISSUE THREAD

**Issue by jzhang82119** [ollama/ollama#6396]
### What is the issue?

curl -fsSL https://ollama.com/install.sh | sh
```
>>> Downloading ollama...
######################################################################## 100.0%##O#-#
>>> Installing ollama to /usr/local/bin...
>>> Creating ollama user...
>>> Adding ollama user to render group...
>>> Adding ollama user to video group...
>>> Adding current user to ollama group...
>>> Creating ollama systemd service...
>>> Enabling and starting ollama service...
Created symlink /etc/systemd/system/default.target.wants/ollama.service → /etc/systemd/system/ollama.service.
>>> Compatible AMD GPU ROCm library detected at /opt/rocm
>>> The Ollama API is now available at 127.0.0.1:11434.
>>> Install complete. Run "ollama" from the command line.

```

ollama run llama3.1:405b
```
pulling manifest
Error: pull model manifest: 412:

The model you are attempting to pull requires a newer version of Ollama.

Please download the latest version at:

        https://ollama.com/download
```

ollama --version
```
ollama version is 0.3.0
Warning: client version is 0.3.6
```

I have already followed manual or automatic way to install ollama. But none of them works. Can you help?

### OS

Linux

### GPU

AMD

### CPU

Intel

### Ollama version

ollama version is 0.3.0 Warning: client version is 0.3.6

**Comment by rick-github** [comment]
You need to restart the server.
```
sudo systemctl stop ollama
sudo systemctl daemon-reload
sudo systemctl start ollama
```

**Comment by jzhang82119** [comment]
that does not resolve the issue

sudo systemctl stop ollama
sudo systemctl daemon-reload
sudo systemctl start ollama
ollama --version

```
ollama version is 0.3.0
Warning: client version is 0.3.6
``
```
ollama run llama3.1:405b
```
pulling manifest
Error: pull model manifest: 412:

The model you are attempting to pull requires a newer version of Ollama.

Please download the latest version at:

        https://ollama.com/download
```

**Comment by rick-github** [comment]
Your ollama server is out of date.  You need to figure out where it's running and update it.  Have you set `OLLAMA_HOST` in your bash environment?  What's the output of `sudo systemctl status ollama`?  What's the output of `journalctl -u ollama --no-pager`?

**Comment by jzhang82119** [comment]
I have to reboot my machine to make it work. Not sure if this is a os bug or something.

**Comment by rick-github** [comment]
What's the output of
```
ollama -v
```

**Comment by vikasbnsl** [comment]
getting same error

```
ollama run gemma3n:latest
pulling manifest 
Error: pull model manifest: 412: 
```

```
 ollama --version
ollama version is 0.9.1
Warning: client version is 0.9.3
```

**Comment by rick-github** [comment]
> `ollama version is 0.9.1`

Restart your server.

**Comment by ifeanyiBatman** [comment]
I solved it by just restarting my computer.

**Comment by abereghici** [comment]
`pgrep ollama` and then kill the process and open ollama again worked for me.

**Comment by kovs705** [comment]
> `pgrep ollama` and then kill the process and open ollama again worked for me.

worked for me without rebooting MacBook, thanks

**Comment by farukomerballi** [comment]
My own solution management (no restart required)
Version v0.14.2 was installed, but I was getting an error when I tried to download the model. When I checked the https://github.com/ollama/ollama/releases page, I saw that v0.14.3 pre-release had been published 3 days ago, so I installed it and it worked. I was able to download the models this way. 

So if you're getting the same error, check the releases page. Most likely, a different version has been released. (Since it's a pre-release, they probably haven't added it to the website, brew, or Docker image.)

**Comment by tikumo** [comment]
> My own solution management (no restart required) Version v0.14.2 was installed, but I was getting an error when I tried to download the model. When I checked the https://github.com/ollama/ollama/releases page, I saw that v0.14.3 pre-release had been published 3 days ago, so I installed it and it worked. I was able to download the models this way.
> 
> So if you're getting the same error, check the releases page. Most likely, a different version has been released. (Since it's a pre-release, they probably haven't added it to the website, brew, or Docker image.)

Worked for me on M5 macbook! Thanks

**Comment by FrankenLab** [comment]
I'm on Ubuntu,  ollama version is 0.15.4. I have a script to update and it's worked flawlessly til now. Now I'm getting the same error 412. My script is below, so wtf has changed? Why are new models being posted when the proper version of Ollama isn't available?
```
  install_ollama(){
  cp /etc/systemd/system/ollama.service /etc/systemd/system/ollama.service.BAK
  curl -fsSL https://ollama.com/install.sh | sh
  cp /etc/systemd/system/ollama.service.BAK /etc/systemd/system/ollama.service
  systemctl daemon-reload
  systemctl restart ollama
}

**Comment by rick-github** [comment]
What model are you trying to pull?

Also, you can store your [configuration changes](https://github.com/ollama/ollama/blob/main/docs/faq.mdx#setting-environment-variables-on-linux) in `/etc/systemd/system/ollama.service.d/override.conf` and you won't have to play shell games with BAK files.

**Comment by rick-github** [comment]
> What model are you trying to pull?

I'm guessing it's [glm-ocr](https://ollama.com/library/glm-ocr#:~:text=Readme-,Note,-%3A%20this%20model%20requiresl).

<img width="762" height="166" alt="Image" src="https://github.com/user-attachments/assets/d8109d95-a029-4d04-a894-276d32344eb2" />

**Comment by FrankenLab** [comment]
Yes, but that image you posted wasn't visible and it isn't clear that what pre-release means in this context. If it's being published, then it should be the version that's available if I upgrade, not some behind the scenes version that requires a special incantation. If it's alpha/beta, that should be clearer with a link.

The image wasn't visible because I have my theme set to dark mode and the text was faded. It's strange that it's visible here but not on the download page.

**Comment by Himwong113** [comment]
1)try ```ollama serve```
2) check ver>0.20.0
3) open a new terminal and run ``` ollama pull gemma4```

**Comment by The1Ice9** [comment]
I had installed via snap and had to do this to remove completely.



Steps to Resolve
Identify the stuck process:
Run the following command to see pending or stuck snap tasks:

snap changes

Look for a row where "ollama" is mentioned and the status is "Doing" or "Error". Note the corresponding number in the ID column.
Abort the stuck task

Use the ID from the previous step to abort the process (replace <ID> with the actual number, e.g., 12):

sudo snap abort <ID>

If the task is still stuck, you might need to use sudo snap abort --last=ollama or find the process ID (PID) and kill it, though snap abort is usually sufficient.

Retry removing Ollama:
Once the change is aborted, try removing the snap again:

sudo snap remove ollama
 
Alternative: Force Remove
If the above does not work, you may need to try removing the snap while ignoring the current state, though this is less conventional:

sudo snap remove --purge ollama
