### ISSUE TITLE
Warning "Prompt does not specify that the LLM should response in JSON, but JSON format is expected."

### ISSUE THREAD

**Issue by itinance** [ollama/ollama#6397]
### What is the issue?

As written in title, from where comes this message using llama 3.1?

In my prompt, it clearly states 

> Answer in JSON. The JSON should be a list (length 5) of dictionaries whose keys are "missing_entities" and "denser_summary".
> Properly escape all special characters, especially double quotes within strings.

running `sudo journalctl -u ollama --no-pager -f`, I see this log message then:

_Prompt does not specify that the LLM should response in JSON, but JSON format is expected._

The response is valid JSON, so that is not an issue. However, the message indicates that some pre-processing step seems to not be able to "read" the prompt catefully.

### OS

Linux

### GPU

Nvidia

### CPU

Intel

### Ollama version

0.3.6

**Comment by rick-github** [comment]
Warning comes from [here](https://github.com/ollama/ollama/blob/d29cd4c2ed104a1f6fba16a264c3cc7785a7d82f/llm/server.go#L767), which just checks the the presence of the string "json" in the prompt.  Can you show the code that takes your prompt and sends it to ollama?

**Comment by itinance** [comment]
> Warning comes from [here](https://github.com/ollama/ollama/blob/d29cd4c2ed104a1f6fba16a264c3cc7785a7d82f/llm/server.go#L767), which just checks the the presence of the string "json" in the prompt. Can you show the code that takes your prompt and sends it to ollama?

@rick-github it's the same like here https://github.com/ollama/ollama/issues/6380#issuecomment-2294829833

**Comment by rick-github** [comment]
Can you show the code that takes your prompt and sends it to FastAPI app?
