### ISSUE TITLE
Error during API call: litellm.APIConnectionError: Ollama Error - {'error': 'error reading llm response: read tcp 127.0.0.1:5644->127.0.0.1:5600: wsarecv: An existing connection was forcibly closed by the remote host.'}

### ISSUE THREAD

**Issue by 720pixel** [ollama/ollama#6404]
### What is the issue?

I'm using latest Aider + [deepseek-coder-v2](https://ollama.com/library/deepseek-coder-v2)

I am facing this issue frequently. It works automatically after a while. 

[server.log](https://github.com/user-attachments/files/16648359/server.log)

### OS

Windows

### GPU

Nvidia

### CPU

Intel

### Ollama version

0.3.6

**Comment by rick-github** [comment]
```
C:\a\ollama\ollama\llm\llama.cpp\src\llama.cpp:15104: Deepseek2 does not support K-shift
```
As per the error, there are problems with supporting this model.  There are possible fixes from a couple of PRs in https://github.com/ollama/ollama/issues/5975.

**Comment by rick-github** [comment]
Workaround discussed in https://github.com/ggerganov/llama.cpp/issues/8862.

**Comment by RealIndica** [comment]
Also having the same issue, but using Msty.

**Comment by rick-github** [comment]
Have you tried the workaround in https://github.com/ollama/ollama/issues/6199#issuecomment-2295952982? [Server logs](https://github.com/ollama/ollama/blob/main/docs/troubleshooting.md#how-to-troubleshoot-issues) would aid in debugging.

**Comment by RealIndica** [comment]
> Have you tried the workaround in [#6199 (comment)](https://github.com/ollama/ollama/issues/6199#issuecomment-2295952982)? [Server logs](https://github.com/ollama/ollama/blob/main/docs/troubleshooting.md#how-to-troubleshoot-issues) would aid in debugging.

I have tried setting the parameters to those values, but still doesn't work unfortunately.

**Comment by dhiltgen** [comment]
Dup of #5975
