### ISSUE TITLE
Ollama (WindowsSetup) fail to access from external ip

### ISSUE THREAD

**Issue by MorrisLu-Taipei** [ollama/ollama#6406]
### What is the issue?

Ollama ( docker version ) support external accesss n Windows 11, BUT not working in Ollama (WindowsSetup)

For example, the machine ip is 192.168.1.107 
w/Ollama (WindowsSetup)
1) 127.0.0.1:11434 works (o)
2) 192.168.1.107:11434 not works (x)

But w/Ollama (Docker ver)
1) 127.0.0.1:11434 works (o)
2) 192.168.1.107:11434 works (o)

### OS

Win11

### GPU

AMD 7900XTX

### CPU

Xeon

### Ollama version

0.3.6

**Comment by elsatch** [comment]
Have you tried following the instructions at the FAQ to setup the OLLAMA_HOST environmental variable to 0.0.0.0 ? 

https://github.com/ollama/ollama/blob/main/docs/faq.md#setting-environment-variables-on-windows

**Comment by elsatch** [comment]
For additional info check: https://github.com/ollama/ollama/blob/main/docs/faq.md#how-can-i-expose-ollama-on-my-network

**Comment by MorrisLu-Taipei** [comment]
Thanks you, it really works to me
![image](https://github.com/user-attachments/assets/f68152ec-fd0f-4abc-8d25-1b31216f2f32)
