### ISSUE TITLE
Is the speed of the Olama running model related to the CUDA version?

### ISSUE THREAD

**Issue by TianWuYuJiangHenShou** [ollama/ollama#6420]
### What is the issue?

I deployed qwen2:72B with the latest version of Ollama, but I found that the loading speed of Ollama models varies greatly under different nvidia driver version.
# driver:535.183.06 | cuda version:12.2
ollama version:0.3.4
Time of Loading Model:29s

# driver:515.105.01 | cuda version:11.7
ollama version:0.3.6
Time of Loading Model:659s

### OS

Linux

### GPU

Nvidia

**Comment by rick-github** [comment]
If the model is already in the buffer cache, reloading will be a lot faster.  Try tthis:
```
time curl localhost:11434/api/generate -d '{"model":"qwen2:72b","prompt":"hi","options":{"seed":0},"stream":false,"keep_alive":0}'
sleep 5
time curl localhost:11434/api/generate -d '{"model":"qwen2:72b","prompt":"hi","options":{"seed":0},"stream":false,"keep_alive":0}'
```
The second command will load the model from buffer cache and will give you a better measure of how long it takes the cuda driver to load the model into the GPU.

**Comment by dhiltgen** [comment]
I wouldn't expect the driver version alone to make that large of a difference.  

Can you share your server log for both scenarios so we can see more details?

**Comment by dhiltgen** [comment]
If you're still seeing performance problems, please share your server log and I'll reopen the issue.
