### ISSUE TITLE
How to load multiple but same species models on different GPUs?

### ISSUE THREAD

**Issue by EGOIST5** [ollama/ollama#6439]
### What is the issue?

Linux, I use the following command to start Ollama server:
CUDA_VISIBLE_DEVICES=1,2,3,4,5 OLLAMA_MAX_LOADED_MODELS=5 ./ollama-linux-amd64 serve&
Then I want to run several py files used llama3.1:70b, but when I run the several py files, then they all use the same model.
That's to say, only one Gpu is activated. I want to my five gpus to load diffrent llama3.1:70b to run the different py files.
Is there a way to achieve it? Thank you!

**Comment by wrapss** [comment]
but why load the same model several times? couldn't you just enable parralele requests? (OLLAMA_NUM_PARALLEL + OLLAMA_SCHED_SPREAD)

**Comment by EGOIST5** [comment]
> but why load the same model several times? couldn't you just enable parralele requests? (OLLAMA_NUM_PARALLEL + OLLAMA_SCHED_SPREAD)

Thank you, I think my way would be faster.

**Comment by wrapss** [comment]
but what's the point of loading a model several times? just explain it's ez

**Comment by EGOIST5** [comment]
> but what's the point of loading a model several times? just explain it's ez

I mean my five GPUs are each loaded with a llama3.1:70b, so no GPU is idle and this way is the fastest

**Comment by wrapss** [comment]
that's what OLLAMA_SCHED_SPREAD is all about

**Comment by wrapss** [comment]
OLLAMA_SCHED_SPREAD splits the model across all your gpu's and OLLAMA_NUM_PARALLEL lets you choose how many requests you can make at the same time, which is literally what you want to do 100X simpler.

**Comment by EGOIST5** [comment]
Thank you. I set OLLAMA_SCHED_SPREAD=3, OLLAMA_NUM_PARALLEL=1, then I run several py files, It still load one llama3.1:70b, and split it into three gpus, but my one gpu can contain the whole model. By the way, if I set OLLAMA_NUM_PARALLEL=the num of my py files, does it affect the accuracy?

**Comment by wrapss** [comment]
It's the other way around, OLLAMA_SCHED_SPREAD must be a 1 (sort of boolean), and OLLAMA_NUM_PARALLEL must be the number of py files you launch at the same time. this won't affect quality but it will affect tokens/sec

**Comment by EGOIST5** [comment]
I tried OLLAMA_SCHED_SPREAD=1, OLLAMA_NUM_PARALLEL=3, but it still split one model into 3 gpus,
and I tired OLLAMA_SCHED_SPREAD=False, OLLAMA_NUM_PARALLEL=3, it worked the way initiallly.

**Comment by mxyng** [comment]
It's not currently possible to run the same model multiple times. This may change in the future

**Comment by rick-github** [comment]
Before ollama supported parallelism, I played around with running multiple ollama instances and load balancing across them using litellm.  It wasn't deployed to production so I don't how reliable it would have been.

**Comment by ovaisq** [comment]
Are options such as OLLAMA_SCHED_SPREAD and others documented somewhere? Also, if there's any other venue that I should be posting this, please let me know. Thx!

**Comment by dhiltgen** [comment]
Support for loading the same model multiple times (across multiple GPUs) is tracked via #3902
