### ISSUE TITLE
Update model parameters for SmolLM (and other models)

### ISSUE THREAD

**Issue by DuckyBlender** [ollama/ollama#6444]
### What is the issue?

It is crucial to follow the recommended model parameters, especially for such small models such as SmolLM. They are much worse at higher temperatures. Ollama team, respectfully, PLEASE make sure the model parameters are set correctly 🙏 

From the SmolLM HF:
![firefox_n1LVtmDwfP](https://github.com/user-attachments/assets/967375c9-eefa-4a12-a0d9-d3cdc3386a94)

**Comment by DuckyBlender** [comment]
kind of related: #4709

**Comment by mxyng** [comment]
Thanks for creating the issue. The models has been updated with the suggested parameters
