### ISSUE TITLE
obtain attention matrices during inference, similar to the output_attentions=True parameter in the transformers package

### ISSUE THREAD

**Issue by yuhkalhic** [ollama/ollama#6454]
I'd like to propose a new feature for Ollama: the ability to access attention matrices and/or the KV-Cache during model inference. This functionality is similar to what's available in the Hugging Face Transformers library, where users can set `output_attentions=True` or access `past_key_values`.

**Comment by rick-github** [comment]
This is more likely a feature request for [llama.cpp](https://github.com/ggerganov/llama.cpp/issues).

**Comment by yuhkalhic** [comment]
> This is more likely a feature request for [llama.cpp](https://github.com/ggerganov/llama.cpp/issues).

OK, thanks
