### ISSUE TITLE
In order to facilitate technical exchanges, a multi-modal large model technical exchange group has been created. Anyone who needs it can join

### ISSUE THREAD

**Issue by feihuamantian** [ollama/ollama#6458]
You can scan the QR code to join us, or add me on WeChat to join the group: yx116169
![20240822-142406](https://github.com/user-attachments/assets/7458ec62-c6c8-40af-a25a-c2179be95b29)

**Comment by mchiang0610** [comment]
Hey @feihuamantian thank you for sharing this. Is it possible to share this in our Discord. It's probably a better medium for exchanging other discussion forums than the GitHub repo. 

Just trying to relate to issues here. 

Really appreciate this though

Thank you
