### ISSUE TITLE
Unable to Access Linux Package for Installation

### ISSUE THREAD

**Issue by f1mahesh** [ollama/ollama#6463]
### What is the issue?

Hi Team,

We are encountering a 404 error when attempting to download the Linux package from the following URL: https://ollama.com/download/ollama-linux-amd64.tgz.

**Details:**
URL: https://ollama.com/download/ollama-linux-amd64.tgz
Error: 404 Not Found
Impact: Users are unable to download and install the required Linux package, which may hinder their ability to use the software or service provided by Ollama.

**Steps to Reproduce:**
Open a web browser.
Navigate to the URL: https://ollama.com/download/ollama-linux-amd64.tgz.
Observe the 404 error message displayed.

### OS

Linux

**Comment by preshanth** [comment]
Yeah I am unable to access the linux package download as well.

```
curl -fsSL https://ollama.com/download/ollama-linux-amd64.tgz
curl: (22) The requested URL returned error: 404

```

**Comment by rick-github** [comment]
Why are you trying to download the tgz directly?  The packaging for ollama was changed in https://github.com/ollama/ollama/commit/74d45f010276c2f2653f3ca8c4f76cb0552fb46e, but it has a fallback to the previous method in the case where the tgz is not found.  I expect that the next release (0.3.7) will be in the new format and the direct link will work, but users should be using the `install.sh` script, not downloading random files.

**Comment by preshanth** [comment]
It is for the case of not having root on a machine which the install script needs or does not end up installing into a local users area. I suppose the solution is to move to the containerized version ?

**Comment by rick-github** [comment]
When the next release is cut you will be able to download the tgz, but this is an archive, not a binary as it was previously.  Whatever install method you used to get around the root requirement will need to be adjusted.  If you have the ability to install docker, the containerized version will be much simpler to manage.

**Comment by preshanth** [comment]
I do use the containerized version where docker is available. Thanks for the info on the release.

**Comment by mxyng** [comment]
@rick-github is correct. The linked change adds `.tgz` packaging. There isn't a release with that change currently so the artifact does not exist and the install script will fallback to the previous single binary download. 

This will be resolved in the next release. In the meantime, please use either the single binary form factor `ollama-linux-<arch>` or the container image.

**Comment by f1mahesh** [comment]
> files.

The install.sh file internally referring to the same file and trying to download form the same location.
