### ISSUE TITLE
Error: unsupported content type: unknown

### ISSUE THREAD

**Issue by CorrectPath** [ollama/ollama#6464]
### What is the issue?

This is the first time I tried to create a model with a gguf file, but it failed
![屏幕截图 2024-08-22 224737](https://github.com/user-attachments/assets/a2b95b02-11b1-48d4-a318-3dd52c276da7)
model.modelfile
![屏幕截图 2024-08-22 224322](https://github.com/user-attachments/assets/c4d85c12-3542-4f4f-b026-634f8dfcf9b1)

### OS

Windows

### GPU

Nvidia

### CPU

Intel

### Ollama version

0.3.6

**Comment by CorrectPath** [comment]
Somebody help me😭

**Comment by rick-github** [comment]
Where did you get `model.gguf` from?

**Comment by CorrectPath** [comment]
> Where did you get `model.gguf` from?

This is a personal model given to me by a friend, so is there a problem with gguf files?

**Comment by rick-github** [comment]
Some GGUF files require capabilities or ancillary files that are not yet supported in ollama.

**Comment by mxyng** [comment]
What does you gguf contain? Can you take the first few bytes so we can get a sense of what kind of gguf it is?

On Windows, it should be something like this in powershell

```
Format-Hex -Count 64 -Path .\model.gguf
```

**Comment by CorrectPath** [comment]
> What does your gguf contain? Can you take the first few bytes so we can get a sense of what kind of gguf it is?你的gguf包含什么？你能把前几个字节，所以我们可以得到一个什么样的gguf的感觉？
> 
> On Windows, it should be something like this in powershell在Windows上，在powershell中应该是这样的
> 
> ```
> Format-Hex -Count 64 -Path .\model.gguf
> ```

The command you provided had an error when running on my powerShell, so I used another command that ChatGPT told me. 
```
Get-Content -Path .\model.gguf -Encoding Byte -TotalCount 64 | Format-Hex
```
Can this provide you with useful information, I'm sorry if not😥
![image](https://github.com/user-attachments/assets/a9b3ad1e-6912-498b-ac71-2927ce6e1f80)

**Comment by rick-github** [comment]
This looks like a pytorch file, perhaps a finetune adapter.

**Comment by pdevine** [comment]
@CorrectPath I'm not sure what kind of file that is, but it's not a GGUF. A GGUF file should start with:

```
00000000  47 47 55 46 03 00 00 00  24 01 00 00 00 00 00 00  |GGUF....$.......|
00000010  18 00 00 00 00 00 00 00  14 00 00 00 00 00 00 00  |................|
```

It doesn't look like a Safetensors file, and it doesn't look like a compressed pytorch model to me (that would have started with 0x50 0x4b which is `PK`). I'm going to go ahead and close out the issue since Ollama is behaving correctly. Feel free to keep commenting though.
