### ISSUE TITLE
OpenAI Structured Output Compatability

### ISSUE THREAD

**Issue by jd-solanki** [ollama/ollama#6473]
Hi 👋🏻 

Loving ollama always ❤️ 

I'm eager to use newly released structured output using ollama but it looks like ollama doesn't have compatibility yet so I can just put base_url and I'll get response from my local LLM.

Also, I would like will it support [streaming](https://python.useinstructor.com/concepts/partial/) like instructor?

Thanks.

**Comment by vish0l** [comment]
We can include it, but it will only function with models that support structured output.

**Comment by codefromthecrypt** [comment]
not sure if this is helpful, but I see a PR for langchaingo's openai client https://github.com/tmc/langchaingo/pull/986

**Comment by wassimMsw** [comment]
> We can include it, but it will only function with models that support structured output.

llama3.1 supports it as mentioned [here](https://llama.meta.com/docs/model-cards-and-prompt-formats/llama3_1#json-based-tool-calling). For it to work it requires adding the following to the prompt:
```
Respond in the format {"name": function name, "parameters": dictionary of argument name and its value}. Do not use variables.
```

A solution is to generate the addition mentioned above out of `response_format` parameter in OpenAI chat completion API. Will you consider doing this?

Example of OpenAI response format API:

```
client.chat.completions.create(
    model="gpt-4o-2024-08-06",
    messages=[
        {"role": "system", "content": "You are a helpful math tutor. Guide the user through the solution step by step."},
        {"role": "user", "content": "how can I solve 8x + 7 = -23"}
    ],
    response_format={
        "type": "json_schema",
        "json_schema": {
            "name": "math_response",
            "schema": {
                "type": "object",
                "properties": {
                    "steps": {
                        "type": "array",
                        "items": {
                            "type": "object",
                            "properties": {
                                "explanation": {"type": "string"},
                                "output": {"type": "string"}
                            },
                            "required": ["explanation", "output"],
                            "additionalProperties": False
                        }
                    },
                    "final_answer": {"type": "string"}
                },
                "required": ["steps", "final_answer"],
                "additionalProperties": False
            },
            "strict": True
        }
    }
    )

```

**Comment by cpfiffer** [comment]
> We can include it, but it will only function with models that support structured output.

This is not a requirement for structured output.

[Outlines](https://github.com/dottxt-ai/outlines) supports any open-weight model, and you could easily turn Ollama into an OpenAI-compatible structured output server with more functionality than OpenAI's endpoint.

We're happy to help implement it. We've recently re-written our backend into Rust, so it should not be outrageously difficult to bolt in. I get the sense that there's quite a lot of demand for it -- I've heard as much in private, in public, on issues here, etc.

I think at this point we need serious discussion with the Ollama team about how it would look in the internals.

**Comment by ashwinb** [comment]
+1 for having this. And yes, there is no reason why this needs to be limited to only models supporting structured output as @cpfiffer mentions above. 

Why we on llama-stack are interested? See https://github.com/meta-llama/llama-stack/pull/281

**Comment by mitar** [comment]
There is no special need in models to support structured output. Any model can be used with structured output and for example PR #5348 adds such support to Ollama. The question is only where do you do JSON Schema -> grammar conversion, inside Ollama or outside it. And then you have to pass grammar to select tokens to llama.cpp (or another model runtime supporting grammars).

The issue with opening grammars as a whole is that bad grammars can have quite a negative impact on both generation speed and quality. This is why most decide to open only JSON Schema as an API surface.

**Comment by yumemio** [comment]
FYI, something along the lines of *"Define the format as Pydantic classes and get the JSON"* is possible with [the function calling feature](https://ollama.com/blog/functions-as-tools). It will be great if Ollama supports structured outputs natively on the OAI endpoint, though!

### Sample code

Equivalent of the [Chain of Thought structured output example](https://platform.openai.com/docs/guides/structured-outputs/structured-outputs#chain-of-thought) from the OpenAI documentation
(not my code - generated by o1-preview)

```python
from ollama import Client
from typing import List
from pydantic import BaseModel

class Step(BaseModel):
    explanation: str
    output: str


class MathReasoning(BaseModel):
    steps: list[Step]
    final_answer: str


def provide_math_reasoning(steps: List[Step], final_answer: str) -> None:
    """
    Provide math reasoning steps and final answer.

    Args:
        steps: A list of Step objects containing 'explanation' and 'output'.
        final_answer: The final answer as a string.

    Returns:
        None
    """
    pass


client = Client(host='http://remote-server-address:11434')

# Define the function as a tool
tools = [provide_math_reasoning]

# Prepare the messages
messages = [
    {'role': 'system', 'content': 'You are a helpful math tutor. Use the provided function to explain your reasoning step by step.'},
    {'role': 'user', 'content': 'How can I solve 8x + 7 = -23?'}
]

# Call the model
response = client.chat(
    'qwen2.5-coder:7b',
    messages=messages,
    tools=tools,
)

# Process the response
for tool_call in response.message.tool_calls or []:
    if tool_call.function.name == 'provide_math_reasoning':
        steps = tool_call.function.arguments.get('steps')
        final_answer = tool_call.function.arguments.get('final_answer')
        math_reasoning = MathReasoning(steps=steps, final_answer=final_answer)
        print(math_reasoning.model_dump_json(indent=2))
    else:
        print('Function not found:', tool_call.function.name)
```

### Output

```json
{
  "steps": [
    {
      "explanation": "Subtract 7 from both sides to isolate the term with x.",
      "output": "8x = -30"
    },
    {
      "explanation": "Divide both sides by 8 to solve for x.",
      "output": "x = -15/4"
    }
  ],
  "final_answer": "-15/4"
}
```

**Comment by nadeesha** [comment]
> There is no special need in models to support structured output

Ok, this is fair. I implemented my own around ollama with `zod` and `async-retry` at the application level. It's somewhat trivial. [Guide](https://www.inferable.ai/blog/posts/llm-json-parser-structured-output) for anyone else wanting to do the same.

**Comment by dgutson** [comment]
> > There is no special need in models to support structured output
> 
> Ok, this is fair. I implemented my own around ollama with `zod` and `async-retry` at the application level. It's somewhat trivial. [Guide](https://www.inferable.ai/blog/posts/llm-json-parser-structured-output) for anyone else wanting to do the same.

This is basically brute force retrying, we need native support.

**Comment by ParthSareen** [comment]
This will get rolled out with #7900! @dgutson @nadeesha @jd-solanki
