### ISSUE TITLE
Add linux start command to docs 

### ISSUE THREAD

**Issue by bdytx5** [ollama/ollama#6478]
nohup ollama serve &

**Comment by rick-github** [comment]
If the recommended way to install ollama is followed, ollama will be started automatically.

If the service is installed manually, ollama can be started on linux with [`sudo systemctl start ollama`](https://github.com/ollama/ollama/blob/main/docs/linux.md#start-ollama).

**Comment by jmorganca** [comment]
Thanks @rick-github ! As Rick mentioned, the default uses systemd. Other ways are possible as well, but we try to keep focused on `ollama serve`

**Comment by bdytx5** [comment]
In my case, I was using a container that did not support systemctl. Also, its a bit confusing what the difference between start and serve is?

**Comment by rick-github** [comment]
`start` and `serve` are synonyms for ollama, they do the same thing.  If you are running ollama in a container, the act of starting the container (`docker run` or `docker compose up`) will start the server.

**Comment by bdytx5** [comment]
In my case, I don't have control over starting the container, as this was a vast ai instance. Also, I think it would make more sense to just have one start command?
