### ISSUE TITLE
Ollama serve crashes with llama3.1:70b

### ISSUE THREAD

**Issue by remco-pc** [ollama/ollama#6488]
### What is the issue?

i am running this command: 

ollama run llama3.1:70b "can you give me the route to account: $(cat '/tmp/r3m/io/3d651238-75bf-4d4d-a1e1-7c902a83450c/0/Node/List/System.Route.7995d5f2c60a87c4b09a3515ef58f1b75af24058.json')"

and at the end of the response (mid way) it just crashes.

The model runs on the cpu

### OS

Linux
Debian 12.6
### GPU

Other

### CPU

Intel

### Ollama version

ollama version is 0.3.6

**Comment by remco-pc** [comment]
i might know what the error is: 
OLLAMA_KEEP_ALIVE (default "5m") is too short for my model, it is still generating at that point (it might take more then 5 minutes on my computer to generate a response ?)

**Comment by rick-github** [comment]
The keep-alive timer doesn't start until the generation is finished.  If you could provide [server logs](https://github.com/ollama/ollama/blob/main/docs/troubleshooting.md#how-to-troubleshoot-issues) it would help with debugging.

**Comment by remco-pc** [comment]
@rick-github i don't have a server log yet (no entries)

**Comment by viba1** [comment]
1. The model runs on the cpu => no gpu?
2. Ollama serve crashes => just Ollama crashes or the whole server (host machine)?
3. Is Ollama directly installed on the host or on a VM or in a docker container?

**Comment by pdevine** [comment]
@remco-pc any update w/ the server logs?

**Comment by dhiltgen** [comment]
@remco-pc can you clarify "and at the end of the response (mid way) it just crashes."

Do you get any output?  If you get any output, there has to be some server log to go along with loading the model.  I'm assuming the server crashed, so the crash information should be in the server log.

**Comment by remco-pc** [comment]
i am currently not having issues, if i have issues i will create a new ticket
