### ISSUE TITLE
Error 403 occurs when I call ollama's api

### ISSUE THREAD

**Issue by brownplayer** [ollama/ollama#6489]
### What is the issue?

Prerequisite: Use the C++ interface of ipex-llm as ollama's acceleration backend. Then start the ollama server (port 127.0.0.1.11434). When you use the edge browser plug-in to access the api of ollama, error 403 occurs
![image](https://github.com/user-attachments/assets/b9d4eee0-0293-41e7-9437-23ae4dc660af)

### OS

Windows

### GPU

Intel

### CPU

Intel

**Comment by rick-github** [comment]
The body of the 403 response might provide a reason for the failure, is it possible for you to capture it?  Perhaps in the logs for ipex-llm?

**Comment by rick-github** [comment]
So it seems ipex-llm is a shim for ollama to enable intel GPU use, so it's not responsible for the 403s.  What does the edge browser plug-in show when the 403 error is returned?

**Comment by brownplayer** [comment]
The command output is as follows: [403:fetchError] The service returns an error, and no permission is granted to access the service

**Comment by rick-github** [comment]
That looks like a generic error message from the plug-in.  What is the plug-in?  What happens when you run the curl command in a cmd window?

**Comment by brownplayer** [comment]
Hold on. I'm trying

**Comment by brownplayer** [comment]
When I open the ollama server (ollama serve), I also open a terminal serial port to call the ollama server. Everything is normal, and the server returns a message indicating that the server is running properly. The name of the web plugin is Immersive Translate.
![image](https://github.com/user-attachments/assets/64dfd3bf-3fde-40ff-bbb6-5bf23b6453c5)
![image](https://github.com/user-attachments/assets/feb8ffc3-f3d7-4d3d-928c-6b473eaf3554)
The first picture shows my local call to the ollama server (everything is fine). Figure 2 shows the name of the plug-in.
I don't know if the reason I'm using ollama is not the community edition

**Comment by brownplayer** [comment]
hi，I tried to connect the api that calls the ollama server to anythingllm, and the result was very successful. Does this mean that there is no problem with the ollama server?

**Comment by rick-github** [comment]
The problem is that the extension is sending an 'Origin: chrome-extension://amkbndfnliijdhojkpoglbnaaahippg' header which is not in the list of allowed origins.  You can fix this by [adding the environment variable](https://github.com/ollama/ollama/blob/main/docs/faq.md#setting-environment-variables-on-windows) `OLLAMA_ORIGINS=chrome-extension://*` to the server config.

**Comment by brownplayer** [comment]
Great. Problem solved. Thank you for your contribution

**Comment by brownplayer** [comment]
I will close this issue and thank you again for your help

**Comment by WayneKim92** [comment]
for mac user. good luck!

```
launchctl setenv OLLAMA_ORIGINS "chrome-extension://*"
```

you should turn off ollama( if you are using termial also). and than restart ollama.

**Comment by rick-github** [comment]
@deepanjan0604 https://github.com/ollama/ollama/issues/6489#issuecomment-2308355334

**Comment by deepanjan0604** [comment]
Is there any way we can run ollama serve on verbose mode? @rick-github

**Comment by deepanjan0604** [comment]
@rick-github still getting: [GIN] 2025/05/22 - 14:51:26 | 403 |       26.68µs |   10.173.177.85 | POST     "/api/generate"

Debug mode is not coming up

**Comment by rick-github** [comment]
Are you trying to get the 403 response?  Look in the client logs, not ollama logs.

**Comment by deepanjan0604** [comment]
No, When I am trying to hit /api/generate api from postman which goes through azure aks ingress it is giving me 403 forbidden error and in the ollama pod logs it is giving 403

**Comment by thinkrivan** [comment]
im having the same problem, it used to work just fine though

**Comment by Yann0s** [comment]
> Is there any way we can run ollama serve on verbose mode? [@rick-github](https://github.com/rick-github)

yes : ollama run model-name --verbose

**Comment by rick-github** [comment]
That's client verbose mode, not server verbose mode.

**Comment by ssy341** [comment]
On windows，I created a new variable for OLLAMA_ORIGINS with value "*", it's works for me

**Comment by luckylinux** [comment]
A minor Note for those that maybe set the Port explicitly in the URL for `CORS_ALLOW_ORIGIN`.

A URL `https://host:443` will be treated differently than `https://host` even though, by default, for the Web Browser (and for the vast majority of HTTPS Servers), they **should** be the same Thing.

Therefore, make sure to list BOTH of them in the Parameter:
```
CORS_ALLOW_ORIGIN=https://ollama.MYDOMAIN.TLD:443;https://ollama.MYDOMAIN.TLD
```
