### ISSUE TITLE
WISPER

### ISSUE THREAD

**Issue by DewiarQR** [ollama/ollama#6490]
Hello. You have both regular LLM models and those that support digital vision. Now it remains to add models for transcription and voice synthesis... and it would be possible to solve any problems on your system.
Can we expect such models as

https://huggingface.co/Systran/faster-distil-whisper-large-v3

Or maybe it is possible to install it yourself now?

**Comment by bdqfork** [comment]
+1

**Comment by dhiltgen** [comment]
Tracked via #1168
