### ISSUE TITLE
igpu

### ISSUE THREAD

**Issue by ayttop** [ollama/ollama#6494]
ollama with igpu intel
how to run ollama on igpu intel

**Comment by hxhue** [comment]
There is a related PR: https://github.com/ollama/ollama/pull/5593

The contributor released [an experimental package](https://github.com/zhewang1-intc/ollama/releases) last month. After installing Intel's oneAPI package and setting the environment variables according to the PR, I managed to utilize my Intel Core Ultra 9 185H to run models. My machine is a Windows laptop.

The speed is only slightly faster than the CPU inference mode, but I don't get 100% CPU usage and the fan has stopped whining crazily.

**Comment by byjrack** [comment]
And same boat, but using an older Raptor Lake/13th gen Xe-LP chip.  Hoping to see the work in the fork merged to an official build sooner rather than later.  Performance is not awesome, but not sure what they can squeeze out of oneAPI supported chips and avoids CPU contention during use that makes the machine unresponsive.

**Comment by hxhue** [comment]
@byjrack The iGPU doesn't rely on the CPU to compute. They are two different parts, so the machine is still responsive. 😂

**Comment by byjrack** [comment]
Yup well aware of that and one of the benefits for using it vs AVX2.  I will say fans still go to 11 as both burn a ton of electrons to make things go compared to Metal on aarch as an example, but will take what i can get.

**Comment by dhiltgen** [comment]
Let's track this via #3113

**Comment by ayttop** [comment]
it run with

https://github.com/intel-analytics/ipex-llm/blob/main/docs/mddocs/Quickstart/llama_cpp_quickstart.md
