### ISSUE TITLE
Docker: "layers from manifest don't match image configuration" when pulling ROCm image

### ISSUE THREAD

**Issue by bitfl0wer** [ollama/ollama#6499]
### What is the issue?

When trying to pull the `rocm` tagged versions of the `ollama/ollama` image from Docker Hub, the pull ultimately fails for me with the message `layers from manifest don't match image configuration`. Pulling the non-rocm versions of the image works fine, however.

So far, I have tried pulling the following tags using `docker pull`:
- `rocm` (digest matches `0.3.5-rocm`, assuming they are the same)
- `0.3.6-rocm`
- `0.3.4-rocm`

all of which yielded the same failing result.

Additional System Information:
- OS: Fedora Linux 40 (Workstation) x64
- Docker: Version 27.1.2, build d01f264

I do not have an ollama image already pulled: `docker image ls | grep ollama` yields no output.

I have also removed all containers using an ollama image.

### OS

Linux

### GPU

AMD

### CPU

AMD

**Comment by rick-github** [comment]
Apparently a problem with pigz on Fedora: https://github.com/ollama/ollama/issues/6413

FWIW pulling 0.3.4-rocm on Mint (Ubuntu/Debian based) works fine.

**Comment by bitfl0wer** [comment]
Can confirm that running `dnf remove pigz` solves this. Thank you!
