### ISSUE TITLE
Ollama with RX6600, Openwebui and win 11 support

### ISSUE THREAD

**Issue by kevinleijh** [ollama/ollama#6506]
I'm a big fan of running Ollama on Windows 11 with OpenWebUI, as it offers a seamless and feature-rich experience. However, I'm facing a challenge with my rx6600 graphics card, which isn't currently supported. I'd greatly appreciate it if you could add it to the list of supported cards, along with all other AMD cards. I'm excited to see the project grow and improve, and I'm confident that with your support, we can make it even better!

**Comment by dhiltgen** [comment]
Let's track this via #4464 

Unfortunately the override variable only works on Linux, so we don't currently have a solution for Windows given ROCm doesn't support this GPU.

**Comment by kevinleijh** [comment]
Thank you, but if you look at kobold AI, I can run any Q6 GGUF with no problem and it's very fast for RX6600.
