### ISSUE TITLE
Create Blob API returned nothing

### ISSUE THREAD

**Issue by cool-firer** [ollama/ollama#6507]
### What is the issue?

From the API doc：

> Create a Blob
> `POST /api/blobs/:digest`
> Create a blob from a file on the server. Returns the server file path.

tried, got 201 status code，but got nothing else returned. bugs?

### Ollama version

ollama version is 0.3.6

**Comment by jmorganca** [comment]
Hi @cool-firer this is expected, as the blob was created. Let me know if you encounter any more issues
