### ISSUE TITLE
Error downloading the ollama tgz file 

### ISSUE THREAD

**Issue by CjhHa1** [ollama/ollama#6512]
### What is the issue?

 downloading ollama pakage using `curl -fsSL https://ollama.com/download/ollama-linux-amd64.tgz | sudo tar zx -C /usr`  
 shown in [linux doc](https://github.com/ollama/ollama/blob/main/docs/linux.md). But found no file error and I checked the website, no this file too.

### OS

Linux

### GPU

Nvidia

### CPU

Intel

**Comment by rick-github** [comment]
https://github.com/ollama/ollama/issues/6463

**Comment by dhiltgen** [comment]
We've switched 0.3.7 to the latest release which has resolved this.  We should have held the doc updates back until after we made the switch.  Sorry about that.

**Comment by CjhHa1** [comment]
> We've switched 0.3.7 to the latest release which has resolved this. We should have held the doc updates back until after we made the switch. Sorry about that.

happy  to hear that 👍🏻
