### ISSUE TITLE
OLLAMA_NUM_PARALLEL with Gemma-2-9B model

### ISSUE THREAD

**Issue by lihkinVerma** [ollama/ollama#6516]
### What is the issue?

When either steting the OLLAMA_NUM_PARALLEL varaible to value greater than 1 in ollama.service or in docker run command (`sudo docker run -d --gpus=all -v ollama:/root/.ollama -p 9000:11434 -e OLLAMA_NUM_PARALLEL=10 -e OLLAMA_MAX_LOADED_MODELS=4 --name ollama ollama/ollama`) it do not works properly, if running model gemma2:9b-instruct-fp16

Either the docker container do not starts or if running with ollama.service then the command starts with variable --parallel 1

This is not the case with other models like phi-3.5, llama-3.1 or even gemma2:2b-instruct-fp16

Can you please check the issue?

I am using RTX4090, with single node having 4 GPUs each of VRAM 8GB in size

### OS

Linux

### GPU

Nvidia

### CPU

Intel

### Ollama version

0.3.5

**Comment by igorschlum** [comment]
Hi @lihkinVerma can you try with version 0.3.7-rc6 ?

https://github.com/ollama/ollama/releases/tag/v0.3.7-rc6

**Comment by rick-github** [comment]
Fixed with https://github.com/ollama/ollama/pull/6402, as per igorschlum 0.3.7-rc6 should work.

**Comment by lihkinVerma** [comment]
Thankyou using the latest version, fixed the issue (0.3.7-rc6)
