### ISSUE TITLE
Unable to run on tcp4/ipv4 on Lambda Labs instance

### ISSUE THREAD

**Issue by bayadyne** [ollama/ollama#6518]
### What is the issue?

I used OLLAMA_HOST=0.0.0.0:8080 (and attempted with other ports) and when I checked, the service was only on tcp6 which I'm currently unable to use.

### OS

Linux

### GPU

Nvidia

### CPU

Intel, AMD

### Ollama version

0.3.6

**Comment by bayadyne** [comment]
Issues I read and was unable to work around the problem with:
#3961
#3300
#6077

**Comment by rick-github** [comment]
You can try disabling ipv6 on the instance.  You don't specify the OS, but something like the following:
```
sudo sysctl -w net.ipv6.conf.all.disable_ipv6=1
sudo sysctl -w net.ipv6.conf.default.disable_ipv6=1
sudo sysctl -w net.ipv6.conf.lo.disable_ipv6=1
```
If you want the changes to survive a reboot, add them to /etc/sysctl.conf or the eqivalent.

**Comment by rick-github** [comment]
@xuijuthub What's your actual problem?  Most linux machines are dual-stack, if it's listening on :::11434 it will also answer on 127.0.0.1:11434:
```console
$ sudo netstat -pant | grep 11434
tcp6       0      0 :::11434                :::*                    LISTEN      1602578/ollama      
$ curl --ipv4 http://127.0.0.1:11434
Ollama is running
$ curl --ipv6 http://[::1]:11434
Ollama is running
```
If you want to prevent listening on ip6, do the `sysctl` commands above not work?
