### ISSUE TITLE
Installer: Linux : Ask if unit/systemd file needs to be recreated or left alone

### ISSUE THREAD

**Issue by jonz-secops** [ollama/ollama#6519]
It's one of the minor and few annoyances, but also potentially easy to resolve. That every time a new installation of ollama is performed on linux we need to return the the unit/systemd file and recreate our modifications.

Possible solutions: 

1. backup the existing to a ._bu file, then ask if it should be restored

2. prompt for recreating the unit file if or not with (y/n)

**Comment by rick-github** [comment]
Add your overrides  to `/etc/systemd/system/ollama.service.d/override.conf`.
