### ISSUE TITLE
database modify capability

### ISSUE THREAD

**Issue by nRanzo** [ollama/ollama#6526]
it would be interesting to have the possibility to provide ollama with a folder containing data and ask him to extrapolate a database with the required fields in an .md file

**Comment by rick-github** [comment]
ollama is just an inference engine.  See [integrations](https://github.com/ollama/ollama?tab=readme-ov-file#community-integrations) for projects that build on ollama and perhaps offer the feature you are looking for.

**Comment by igorschlum** [comment]
Hi @nRanzo, that's a good idea! I think you will find more people interested in this topic on Discord. Do you have a Discord account? You can create one for free. Please close this issue, as GitHub Issues are meant for improving Ollama and hunting bugs

**Comment by jmorganca** [comment]
@nRanzo Neat idea! As @rick-github and @igorschlum mentioned, it would be best to share this in the Discord!
