### ISSUE TITLE
Ollama will stop using GPU when the total graphics memory usage exceeds the dedicated graphics memory size

### ISSUE THREAD

**Issue by UserGzy** [ollama/ollama#6529]
### What is the issue?

When I tried to run models, I noticed that once the total graphics memory usage exceeded the dedicated graphics memory size of the graphics card, Ollama would stop using GPU for inference. 
I saw in the task manager that the utilization rate of the graphics card was 0%. But when I tried to use a low graphics memory usage model, the GPU utilization increased to 100%.

### OS

Windows

### GPU

Nvidia

### CPU

Intel

### Ollama version

0.3.6

**Comment by rick-github** [comment]
[Server logs](https://github.com/ollama/ollama/blob/main/docs/troubleshooting.md#how-to-troubleshoot-issues) will give more insight into what is happening. but generally, ollama will split the model between the GPU and CPU, loading as much as it can on the GPU.  However, the CPU is less efficient than the GPU, so inference of the layers on the CPU will take longer than the layers on the GPU.  This means there will be periods where the GPU is idle, waiting for the CPU inference to complete.

**Comment by pdevine** [comment]
@UserGzy @rick-github 's answer is correct, and Ollama is behaving as intended. Any time you split a model across GPU/CPU it will slow down because inference needs to wait for the CPU which will cause the GPU to idle.

I'll go ahead and close out the issue.
