### ISSUE TITLE
/api/embeddings returning 404

### ISSUE THREAD

**Issue by jwstanwick** [ollama/ollama#6533]
### What is the issue?

I am on an M3 Mac. I am running Ollama using the installer, not on docker. When running `curl localhost:11434/api/embeddings`, Ollama returns `404 page not found`. Other api calls such as `pull` and `show` work as intended. The output from my Ollama logs is as follows:

```
[GIN] 2024/08/27 - 17:57:12 | 404 |      24.875µs |       127.0.0.1 | GET      "/api/embeddings"
[GIN] 2024/08/27 - 17:57:21 | 404 |      19.875µs |       127.0.0.1 | GET      "/api/embeddings"
[GIN] 2024/08/27 - 17:57:32 | 404 |      18.958µs |       127.0.0.1 | GET      "/api/embeddings"
```

I have tried restarting Ollama, restarting my pc, and the other normal "turn it off and on again" checks. I am completely stumped! Any help is appreciated.

### OS

macOS

### GPU

Apple

### CPU

Apple

### Ollama version

0.3.7

**Comment by rick-github** [comment]
/api/embeddings is a `POST` endpoint.
```
$ curl -s -X POST localhost:11434/api/embeddings | jq
{
  "error": "missing request body"
}
```

**Comment by pdevine** [comment]
@jwstanwick Also note that the `POST /api/embeddings` endpoint is deprecated and you should use `POST /api/embed` instead. Here are the [docs for the endpoint](https://github.com/ollama/ollama/blob/main/docs/api.md#generate-embeddings).
