### ISSUE TITLE
Specifying options via openai client extra_body are not handled by ollama

### ISSUE THREAD

**Issue by gaardhus** [ollama/ollama#6544]
### What is the issue?

So I've been trying to set the num_ctx for the mistral-nemo through the openai api client, however it does not seem to have an effect.

```python
        # Ollama client
        client = OllamaAsyncClient(host=base_url, **kwargs)
        chat_completion = await client.chat(
            messages=messages,
            model=model,
            stream=stream,
            options={
                "num_ctx": 64_000,
                "temperature": temperature,
                "stop": stop_tokens,
            },
            **kwargs,
        )
        message = chat_completion["message"]["content"].strip()
        
        # OpenAI client
        client = AsyncOpenAI(api_key=api_key, base_url=base_url, **kwargs)
        chat_completion = await client.chat.completions.create(
            messages=messages,
            model=model,
            temperature=temperature,
            stream=stream,
            stop=stop_tokens,
            extra_body={"options": {"num_ctx": 64_000}},
            **kwargs,
        )
        message = chat_completion.choices[0].message.content.strip()
```

Doing it with ollama works, but the extra_body argument from openai seems to be handled as an extra field rather than merged with the rest of the request.

```
'model': 'mistral-nemo:12b-instruct-2407-q8_0', 'stop': None, 'stream': False, 'temperature': 0.7}, 'extra_json': {'options': {'num_ctx': 64000}}}
```

I guess the solution would be to unpack the extra_json field on the server end?

### OS

Linux

### GPU

Nvidia

### CPU

Intel

### Ollama version

0.3.8

**Comment by rick-github** [comment]
ollama sticks to the OpenAI API spec which doesn't allow changing the context window size via `num_ctx`.  There is a pending PR (https://github.com/ollama/ollama/pull/6504) which allows changing the size via `max_tokens`.

**Comment by gaardhus** [comment]
Ah sweet, that would solve my issue. However I would expect there are other parameters/options which can't be specified via the openai client, so wouldn't it be easier to use the extra_body(/json) field for these things? Or would you rather create per use integrations?

**Comment by devilteo911** [comment]
I'm not sure if this issue should be closed, as this feels more like a workaround than a solution. @jmorganca, I found this issue through your PR, which seems like a more comprehensive approach. Hopefully, it will get merged soon!
