### ISSUE TITLE
Cannot set custom folder for storing models

### ISSUE THREAD

**Issue by anonymux1** [ollama/ollama#6553]
### What is the issue?

I have run sudo systemctl edit ollama.service, and added the following lines using the text editor. 

[Service]
Environment = OLLAMA_MODELS = "/home/<username>/AI/ollama_models"

i ran systemctl daemon-reload
systemctl restart ollama

Also rebooted, but models are still being stored in /usr/share/ollama/.ollama/models

### OS

Linux

### GPU

AMD

### CPU

Intel

### Ollama version

0.3.8

**Comment by rick-github** [comment]
Remove the spaces.

**Comment by vap0rtranz** [comment]
> Remove the spaces.

Thanks for catching this.

For anyone else who bumps into this, the FAQ has an example with syntax for setting env variables:

[How Do I Configure Ollama Server](https://github.com/ollama/ollama/blob/main/docs/faq.md#how-do-i-configure-ollama-server)
