### ISSUE TITLE
/api/embed returns empty embeddings in docker environment 

### ISSUE THREAD

**Issue by smoothdvd** [ollama/ollama#6555]
### What is the issue?

```
curl http://localhost:11434/api/embed -d '{
  "model": "bge-m3",
  "prompt": "Llamas are members of the camelid family"
}'
{"model":"bge-m3","embeddings":[]}%
```

but old /api/embedding endpoint still worked

### OS

Docker

### GPU

Nvidia

### CPU

Intel

### Ollama version

0.3.8

**Comment by rick-github** [comment]
[/api/embed](https://github.com/ollama/ollama/blob/main/docs/api.md#generate-embeddings) uses `input` not `prompt`.
