### ISSUE TITLE
Where are /save and /load models saved and loaded? Which directory?

### ISSUE THREAD

**Issue by bitcoinmeetups** [ollama/ollama#6557]
Where are /save and /load models saved and loaded? Which directory? Linux. I can't find it.

**Comment by rick-github** [comment]
If it's installed as a service, by default in `/usr/share/ollama/.ollama/models`.  This can be overridden with the variable `OLLAMA_MODELS`.

**Comment by pdevine** [comment]
@bitcoinmeetups you can find that in the [FAQ](https://github.com/ollama/ollama/blob/main/docs/faq.md#where-are-models-stored)
