### ISSUE TITLE
 Logging final input after prompting specified in model file as a debug flag

### ISSUE THREAD

**Issue by adela185** [ollama/ollama#6560]
Just as the title says, it would be useful to log the final input text given to the model after it undergoes the prompting specified in the model file. This is for the windows preview. The logging already included only prints the parameters and API request, but not the final input.

**Comment by rick-github** [comment]
If you add `OLLAMA_DEBUG=1` to the server environment, the processed prompt will be logged:
```
ollama-1  | time=2024-08-29T17:15:51.787Z level=DEBUG source=routes.go:208 msg="generate request" prompt="<|im_start|>user\nhello<|im_end|>\n<|im_start|>assistant\n" images=[]
```

**Comment by adela185** [comment]
Y'know, I probably should've tried that first instead of assuming it was turned on by default on windows... Thanks 😅.
