### ISSUE TITLE
Impossible to connect to ollama locally from another pc

### ISSUE THREAD

**Issue by Wilnox23** [ollama/ollama#6571]
### What is the issue?

Hello, I'm using ollama on windows but I can't connect to the server from another PC on the local network.
I have already changed the following system environment variables.
`OLLAMA_HOST=0.0.0.0`
`OLLAMA_ORIGINS=*`
Thank you for your assistance.

### OS

Windows

### GPU

Nvidia

### CPU

Intel

### Ollama version

0.3.8

**Comment by rick-github** [comment]
Any firewall or anti-virus software installed?  What error does the client give?   What does `netstat -nq | findstr 11434` show?

**Comment by Wilnox23** [comment]
curl 192.168.1.194:11434
curl: (28) Failed to connect to 192.168.1.194 port 11434 after 21069 ms: Couldn't connect to server

netstat -nq | findstr 11434
  TCP    0.0.0.0:11434          0.0.0.0:0              LISTENING
  TCP    192.168.1.194:11434    0.0.0.0:0              LISTENING
  TCP    [::]:11434             [::]:0                 LISTENING

**Comment by rick-github** [comment]
This looks like a firewall issue.  ollama is listening on the right port, but the connection timed out after 21 seconds.  This has the hallmarks of a firewall rule dropping TCP SYN packets.

**Comment by Wilnox23** [comment]
Thanks you rick-github
curl 192.168.1.194:11434
Ollama is running
