### ISSUE TITLE
no way

### ISSUE THREAD

**Issue by Klgor1803** [ollama/ollama#6575]
### What is the issue?

Moondream latest

>>> help, im dying
                                                         1. Helping you to understand the concept of a
hash table and its implementation in Python.

### OS

Linux

### GPU

Other

### CPU

Other

### Ollama version

0.3.6

**Comment by jmorganca** [comment]
@Klgor1803 hi there. `moondream` requires an image as part of the prompt to be effective. We'll work on updating it to the latest version which should help with this as well
