### ISSUE TITLE
phi3.5:3.8b-mini-instruct is missing parameters on Ollama's website.

### ISSUE THREAD

**Issue by vYLQs6** [ollama/ollama#6580]
### What is the issue?

As shown in the screenshot, there is no parameters, so `ollama run phi3.5:latest` will not function correctly.

![](https://github.com/user-attachments/assets/07facb4d-e7e3-4902-bee5-744131832319)

Here is the corrected modelfile if anyone needs it:

```

FROM phi3.5:3.8b-mini-128k-instruct-q8_0
TEMPLATE """{{ if .System }}<|system|>
{{ .System }}<|end|>
{{ end }}{{ if .Prompt }}<|user|>
{{ .Prompt }}<|end|>
{{ end }}<|assistant|>
{{ .Response }}<|end|>
"""
PARAMETER stop "<|system|>"
PARAMETER stop "<|user|>"
PARAMETER stop "<|end|>"
PARAMETER stop "<|assistant|>"

``` 

### OS

Windows

### GPU

Nvidia

### CPU

AMD

### Ollama version

0.3.8

**Comment by kth8** [comment]
Thanks for the corrected modelfile. This was reported has week in #6449 and #6474 so I'm surprised it still hasn't been fixed yet.

**Comment by mxyng** [comment]
phi3.5 has been updated with parameters
