### ISSUE TITLE
couldn't remove unused layers: invalid character '\x00' looking for beginning of value

### ISSUE THREAD

**Issue by hhhaiai** [ollama/ollama#6590]
### What is the issue?

$ollama run llama3-groq-tool-use:8b
pulling manifest
pulling manifest
pulling 23e78d0ea1ab... 100% ▕████████████████████████████████████████████▏ 4.7 GB
pulling d5f55f09bfc5... 100% ▕████████████████████████████████████████████▏ 9.8 KB
pulling 4d1abb94190b... 100% ▕████████████████████████████████████████████▏ 1.7 KB
pulling 56bb8bd477a5... 100% ▕████████████████████████████████████████████▏   96 B
pulling c9300739186a... 100% ▕████████████████████████████████████████████▏  485 B
verifying sha256 digest
writing manifest
removing any unused layers
couldn't remove unused layers: invalid character '\x00' looking for beginning of value
success

### OS

macOS

### GPU

Intel, Other

### CPU

Intel

### Ollama version

ollama version is 0.3.6

**Comment by igorschlum** [comment]
@hhhaiai No problem with MacOS X, version 0.3.9 and a lot of memory. Could you update Ollama to try with the latest version?

**Comment by rick-github** [comment]
Fixed in 0.3.7 by https://github.com/ollama/ollama/pull/6363

**Comment by jmorganca** [comment]
Hi thanks @rick-github, yes this was recently fixed as mentioned. So sorry for the error.
