### ISSUE TITLE
Please fix Linux installer, so any Environment in /etc/systemd/system/ollama.service isn't overwritten

### ISSUE THREAD

**Issue by nightness** [ollama/ollama#6594]
### What is the issue?

Per instructions at [setting-environment-variables-on-linux](https://github.com/ollama/ollama/blob/main/docs/faq.md#setting-environment-variables-on-linux) I'm using 
Environment="OLLAMA_HOST=0.0.0.0:11434" in `/etc/systemd/system/ollama.service`. Please stop overwriting this with every reinstall to upgrade. Maybe ask on install if an existing config file is detected, or just don't overwrite if it exists (with maybe a flag to force overwrite instead).

### OS

Linux

### GPU

AMD

### CPU

AMD

### Ollama version

0.3.9

**Comment by rick-github** [comment]
Add your overrides to `/etc/systemd/system/ollama.service.d/override.conf`.
