### ISSUE TITLE
Unloading a model

### ISSUE THREAD

**Issue by tallesl** [ollama/ollama#6596]
Is `systemctl restart ollama` the way to go?

**Comment by rick-github** [comment]
`curl localhost:11434/api/generate -d '{"model":"model-name","keep_alive":0}'`

**Comment by dhiltgen** [comment]
I believe @pdevine is working on some refined CLI UX to make this a bit easier.

**Comment by jmorganca** [comment]
Merging this with https://github.com/ollama/ollama/issues/4764

Until then, you can use with @rick-github suggested! Thanks for the issue.

**Comment by pdevine** [comment]
PR is #6739
