### ISSUE TITLE
In ollama, do these llama3.1 models refer to  the pretrained basic models or instruction tuned models?

### ISSUE THREAD

**Issue by icecream-and-tea** [ollama/ollama#6600]
### What is the issue?

the model id is llama3.1:8b that it seems to refer to the pretrained basic model, but in the ollama model library, the performance of llama3.1:8b is consistent with the finetuned model

llama3.1 huggingface performance
![image](https://github.com/user-attachments/assets/35485fce-b185-4286-b827-6dd6ac1a6c7d)

the ollama library introduction of llama3.1
![image](https://github.com/user-attachments/assets/e614e393-7d9f-49e7-9174-b7d9b09d45cc)

**Comment by rick-github** [comment]
The short form model name in ollama usually refers to the instruction tuned model.  The base model normally has the word `text` or `base` in the tag, eg [llama3.1:8b-instruct-q4_0](https://ollama.com/library/llama3.1:8b-instruct-q4_0) vs [llama3.1:8b-text-q4_0](https://ollama.com/library/llama3.1:8b-text-q4_0)

**Comment by mxyng** [comment]
as @rick-github mentioned, pretrained models generally contain `text` or `base` in the tag name
