### ISSUE TITLE
n_ctx parameter display error

### ISSUE THREAD

**Issue by JinheTang** [ollama/ollama#6602]
When I create model from a Modelfile:
```log
FROM mistral:latest
PARAMETER num_ctx 4096
```
and load with:
```log
ollama create mistral:latest-nctx4096 -f Modelfile
ollama run mistral:latest-nctx4096
```
setting `n_ctx` to 4096, it is discovered that on the server end `n_ctx` is wrongly displayed as `16384`:
![image](https://github.com/user-attachments/assets/c71f4668-40cd-4bcf-b42d-186028eba52a)

### OS

Linux

### CPU

Intel

### Ollama version

0.3.9

**Comment by rick-github** [comment]
You have `OLLAMA_NUM_PARALLEL=4`, or it's unset, and ollama is using a default value of 4.  Each model instance has its own context space.  `n_ctx` is the total space allocated for context, 4 * 4096 = 16384.  If you set `OLLAMA_NUM_PARALLEL=1` in the server environment, `n_ctx` will show as 4096.

**Comment by jmorganca** [comment]
@rick-github is correct. Sorry this isn't more obvious – we'll improve the logging over time :)
