### ISSUE TITLE
Add Phi-3.5-mini-instruct

### ISSUE THREAD

**Issue by oscarwang22** [ollama/ollama#6603]
Add Phi-3.5-mini-instruct.

**Comment by awaescher** [comment]
Ollama's [phi3.5](https://ollama.com/library/phi3.5:3.8b) model is phi3.5-mini-instruct.

![image](https://github.com/user-attachments/assets/1d349225-64c2-4173-a776-81ccfb92efd2)

However its modelfile seems to be slightly incorrect #6580.

**Comment by oscarwang22** [comment]
Thanks, will the MoE version be supported in the future?

**Comment by jmorganca** [comment]
Thanks for the issue. You can find it here: https://ollama.com/library/phi3.5
