### ISSUE TITLE
Model is not running 

### ISSUE THREAD

**Issue by tilakpatel22** [ollama/ollama#6606]
### What is the issue?

PS C:\Users\Admin> ollama run mistral-nemo
Error: llama runner process has terminated: error loading model: unable to allocate backend buffer 

whenever I try to run this model it shows me this error I don't know how to solve it.. i have 16gb ram with rtx3050

### OS

Windows

### GPU

Nvidia

### CPU

AMD

### Ollama version

0.3.9

**Comment by rick-github** [comment]
[Server logs](https://github.com/ollama/ollama/blob/main/docs/troubleshooting.md#how-to-troubleshoot-issues) will aid in debugging.

**Comment by tilakpatel22** [comment]
@rick-github Thanks for the help after checking server logs I found that my memory on the computer was insufficient.
