### ISSUE TITLE
docker image for rocm-3.5.1 to run on older AMD gpus

### ISSUE THREAD

**Issue by drhboss** [ollama/ollama#6607]
any chance an image with rocm-3.5.1 can be prepared for older gpus, i.e rx580?

**Comment by dhiltgen** [comment]
I tried a couple different old rocm base images from Docker Hub and it doesn't look like this is straight forward.  The header layout has changed quite a bit, and llama.cpp assumes the newer layout.  Even with some symlinks to try to get the headers found, things wont compile based on missing definitions.

We're tracking support for these older GPUs via #2453
