### ISSUE TITLE
GPU Not Use

### ISSUE THREAD

**Issue by MEnsar55** [ollama/ollama#6612]
Hello, I am using Windows 11 and I have installed LLama3.1 7B and Gemma 2 27B in Ollama. When using these modems the GPU is between 0%-1%. What should I do? 
My laptop specs are:
HP Victus
14700hx
4070
32 GB Ram

**Comment by rick-github** [comment]
[Server logs](https://github.com/ollama/ollama/blob/main/docs/troubleshooting.md#how-to-troubleshoot-issues) will help in debugging.

**Comment by dhiltgen** [comment]
There is no llama3.1 7B, but there is a 70B, and given you also mentioned gemma2 27B, I believe you're trying to load large models on a small VRAM system.  Those two models are ~40G and ~16G respectively.  I believe your GPU is an 8G card.  Neither of these models will fit in VRAM, so they'll have to load mostly into system RAM and run on your CPU.  Low GPU utilization in this case is expected, as the CPU is the bottleneck.  Try loading smaller models that fit in your VRAM and you'll see much better performance.  If you want the quality of these larger models, they will run slowly on your system.
