### ISSUE TITLE
[Bug] open-webui integration error when ui docker listen on 11434

### ISSUE THREAD

**Issue by zydmtaichi** [ollama/ollama#6622]
### What is the issue?

i start open-webui via below cmd first and then ollama service failed to up by using `ollama serve`. Output tells the port already in use. I got the same err reason if i change the order of launch(first ollama, then open-webui docker), please check and improve the integration of ollama and open-webui.
my cmd for start open-webui:
`docker run -d -p 3000:8080 -p 127.0.0.1:11434:11434 -v open-webui:/app/backend/data -e OLLAMA_BASE_URL=http://127.0.0.1:11434 --name open-webui --restart always registry.cn-hangzhou.aliyuncs.com/kin-images/open-webui:git-18ae586`
my cmd for start ollama:
`ollama serve`

### OS

Linux

### GPU

Nvidia

### CPU

Intel

### Ollama version

0.3.6

**Comment by igorschlum** [comment]
Hi @zydmtaichi could you update Ollama to version 0.3.9?

**Comment by rick-github** [comment]
```
docker network create ollama-openwebui
docker run -d -p 11434:11434 --network ollama-openwebui -v ollama:/root/.ollama --name ollama --restart always ollama/ollama
docker run -d -p 3000:8080 --network ollama-openwebui -v open-webui:/app/backend/data -e OLLAMA_BASE_URL=http://ollama:11434 --name open-webui --restart always registry.cn-hangzhou.aliyuncs.com/kin-images/open-webui:git-18ae586
```

**Comment by zydmtaichi** [comment]
> ```
> docker network create ollama-openwebui
> docker run -d -p 11434:11434 --network ollama-openwebui -v ollama:/root/.ollama --name ollama --restart always ollama/ollama
> docker run -d -p 3000:8080 --network ollama-openwebui -v open-webui:/app/backend/data -e OLLAMA_BASE_URL=http://ollama:11434 --name open-webui --restart always registry.cn-hangzhou.aliyuncs.com/kin-images/open-webui:git-18ae586
> ```

Thanks, I solve the problem by using `docker run -d -p 3000:8000 -v open-webui:/app/backend/data -e http://172.17.0.1:11434 --name open-webui --restart always registry.cn-hangzhou.aliyuncs.com/kin-images/open-webui:git-18ae586` and running the ollama cmd `OLLAMA_HOST=172.17.0.1:11434 ollama serve`.

the key of solving is virtual network addr for docker. It seems this is only way for program inside visit the host port outside under bridge mode.
