### ISSUE TITLE
POST /v1/chat/completions returns 404 not 400 for model not found

### ISSUE THREAD

**Issue by codefromthecrypt** [ollama/ollama#6646]
### What is the issue?

POST /v1/chat/completions returns 404 not 400 for model not found. Semantically, the better code here is 400, as it is an invalid argument on a correct route. Using 404 messages on a route that exists is confusing and had me doubting if the routes were mounted or not.

This seems to be the same for other routes. Basically, I suggest any code that looks like this:
```go
			c.JSON(http.StatusNotFound, gin.H{"error": fmt.Sprintf("model '%s' not found", req.Model)})
```

switch it to bad request

```go
			c.JSON(http.StatusBadRequest, gin.H{"error": fmt.Sprintf("model '%s' not found", req.Model)})
```

That way, we know the parameter was wrong vs not being able to find the route. I can raise a PR if you like

### OS

Linux

### GPU

Apple

### Ollama version

0.3.9

**Comment by jmorganca** [comment]
Thanks @codefromthecrypt. A PR would be awesome!

**Comment by codefromthecrypt** [comment]
actually, I double checked.. openai uses 404 for model not found, surprising to me. So, we have a choice of using 400 only in our endpoints, or using 404 because openai does, for ollama endpoints. preferences?

```bash
$ curl -v https://api.openai.com/v1/chat/completions \
>                                 -H "Content-Type: application/json" \
>                                 -H "Authorization: Bearer $OPENAI_API_KEY" \
>                                 -d '{
>                                   "model": "gpt-4l",
>                                   "messages": [
>                                     {
>                                       "role": "user",
>                                       "content": [
>                                         {
>                                           "type": "text",
>                                           "text": "hello?"
>                                         }
>                                       ]
>                                     }
>                                   ],
>                                   "max_tokens": 10
>                                 }'
--snip--
< HTTP/2 404 
< date: Thu, 05 Sep 2024 01:53:03 GMT
< content-type: application/json; charset=utf-8
< content-length: 212
--snip--
{
    "error": {
        "message": "The model `gpt-4l` does not exist or you do not have access to it.",
        "type": "invalid_request_error",
        "param": null,
        "code": "model_not_found"
    }
}
```

**Comment by pdevine** [comment]
I would be worried about changing this given other people might be expecting 404 and not 400 in their own applications/scripts. Given there is precedent, let's leave this as it is.
