### ISSUE TITLE
Reflection 70B model request

### ISSUE THREAD

**Issue by gileneusz** [ollama/ollama#6664]
would be nice to add it

<img width="593" alt="Screenshot 2024-09-06 at 01 04 54" src="https://github.com/user-attachments/assets/4d83c4aa-9d6d-43c0-8e25-693aa3c8cee6">

https://huggingface.co/mattshumer/Reflection-70B

**Comment by Techronico** [comment]
senseable/Reflection-Llama-3.1-70B-gguf

**Comment by jmorganca** [comment]
https://ollama.com/library/reflection

Thanks @gileneusz!

**Comment by bardThis** [comment]
So how to request to REMOVE this model from ollama? It might be fine to keep it around for a week or something for people to gather their own data on it, but maybe can a warning be put on the model page (warning: the authors of this model or other publications are making invalid performance claims about [name of model])?
