### ISSUE TITLE
Reflection 70B NEED Tools 

### ISSUE THREAD

**Issue by xiaoyu9982** [ollama/ollama#6671]
Reflection 70B NEED Tools

**Comment by Utopiah** [comment]
Is this covered by https://github.com/ollama/ollama/issues/6664 ?

**Comment by rick-github** [comment]
Since Reflection is based on llama3.1, you might be able to take the [template](https://ollama.com/library/llama3.1/blobs/73b313b5552d) from llama3.1 and use that in place of the current one.

**Comment by rick-github** [comment]
I tried using the llama3.1 template and needs some work.  Because of the <thinking>, <reflection> and <output> stages, the model ends up making three tool calls for every query.

**Comment by jmorganca** [comment]
@rick-github that was my worry. I don't think this model is designed for tool calling. If it is, we can re-open this issue. Thanks for giving it a try, I was curious :)
