### ISSUE TITLE
VG

### ISSUE THREAD

**Issue by vioricavg** [ollama/ollama#6677]
# Use a pipeline as a high-level helper
from transformers import pipeline

messages = [
    {"role": "user", "content": "Who are you?"},
]
pipe = pipeline("text-generation", model="LGAI-EXAONE/EXAONE-3.0-7.8B-Instruct", trust_remote_code=True)
pipe(messages)

**Comment by jmorganca** [comment]
Hi @vioricavg! Thanks for the issue. I'm not quite sure this is for Ollama – but let me know if you need any help

**Comment by vioricavg** [comment]
> # Use a pipeline as a high-level helper
> from transformers import pipeline
> 
> messages = [
>     {"role": "user", "content": "Who are you?"},
> ]
> pipe = pipeline("text-generation", model="LGAI-EXAONE/EXAONE-3.0-7.8B-Instruct", trust_remote_code=True)
> pipe(messages)
