### ISSUE TITLE
Deepseek v2.5 sha256 digest mismatch

### ISSUE THREAD

**Issue by mintisan** [ollama/ollama#6684]
### What is the issue?

➜  ~ ollama pull deepseek-v2.5:236b
pulling manifest 
pulling manifest 
pulling manifest 
pulling manifest 
pulling manifest 
pulling manifest 
pulling manifest 
pulling manifest 
pulling manifest 
pulling manifest 
pulling 799587243b19... 100% ▕█████████████████████████████████████████████████████████▏ 132 GB                         
pulling 8aa4c0321ccd... 100% ▕█████████████████████████████████████████████████████████▏  493 B                         
pulling ccfee4895df0... 100% ▕█████████████████████████████████████████████████████████▏  13 KB                         
pulling 059ecca256c0... 100% ▕█████████████████████████████████████████████████████████▏  241 B                         
pulling f50c0c6cdd1e... 100% ▕█████████████████████████████████████████████████████████▏  495 B                         
verifying sha256 digest 
Error: digest mismatch, file must be downloaded again: want sha256:799587243b19fdcc715a4aab927f5700d1b9508bd0b8b0db9dc2bd6fc622979c, got sha256:e6500636daabf1a172ad5775c9d17f170478d5243055c26d8877f1aa3503425f

### OS

macOS

### GPU

Apple

### CPU

Apple

### Ollama version

0.3.9

**Comment by mintisan** [comment]
maybe network issues...

**Comment by doug62** [comment]
I have the same issue, running in a container....
