### ISSUE TITLE
Model shows wrong date.

### ISSUE THREAD

**Issue by ghaisasadvait** [ollama/ollama#6686]
### What is the issue?

![image](https://github.com/user-attachments/assets/b1debc6f-31e7-4ceb-83bb-b0d32a97d274)

I also tried using Open WEb UI and turned on the Duck DUck GO search functionality but somehow the model still returns the wrong date:

![image](https://github.com/user-attachments/assets/cb4b4d6b-37bc-4616-ab7b-5b2de88d87a0)

### OS

Windows

### GPU

Nvidia

**Comment by rick-github** [comment]
If you type `what is todays date according to google` in to [duckduckgo](https://duckduckgo.com/?t=h_&q=what+is+todays+date+according+to+google&ia=web), do you get the right answer?

Models work off the given context without access to real world information, as the model said.  Without context, they
can't give an answer.  Even with context, they may hallucinate and give an incorrect answer.  You should not rely on an LLM to give a correct factual answer.

**Comment by jmorganca** [comment]
Thanks for the issue! @rick-github summarized this well
