### ISSUE TITLE
Reflection 70B fix?

### ISSUE THREAD

**Issue by gileneusz** [ollama/ollama#6689]
There are rumors that Reflection model does not run properly on ollama, can anyone confirm it?

comments here:

https://www.reddit.com/r/LocalLLaMA/comments/1fa72an/reflectionllama3170b_available_on_ollama/

**Comment by rick-github** [comment]
I haven't used it much because I don't have the hardware to run at a reasonable speed, but it seems to have basic functionality.
```
$ ollama run reflection:70b-q4_0
>>> hello
<thinking>
To respond to "hello", I'll need to consider several factors:

1. The user's intent: They're likely saying hello as a greeting.
2. Appropriate responses: Common ways to respond to "hello" are:
   - Hello back
   - Hi
   - Hey
3. Formality level: Since this is an AI response, I'll aim for a friendly but professional tone.

<reflection>
The approach of responding with a standard greeting seems appropriate in this context. It acknowledges the user's hello and provides a polite response.
</reflection>

Given these considerations, the most suitable response would be to echo "hello" back to the user.
</thinking>

<output>
Hello!
</output>

>>> Send a message (/? for help)
```

**Comment by gileneusz** [comment]
I had the same - good outputs, but benchmarks results were inferior to llama 3.1 70b...

**Comment by gileneusz** [comment]
new weights just dropped:

https://huggingface.co/mattshumer/ref_70_e3/tree/main

**Comment by DougHaber** [comment]
As a note to save anyone else a few minutes, this model doesn't work correctly without the [system prompt](https://ollama.com/library/reflection/blobs/c782799f4377).  If you are overriding that or using it through the API, it might be necessary to manually provide it.  On X, [Matt Shumer said](https://x.com/mattshumer_/status/1832169489309561309) removing that requirement is on his list for a future version.

**Comment by gileneusz** [comment]
they benchmarked this on claude, and published fine tuned llama 3.... Matt missed it somehow...

https://www.reddit.com/r/LocalLLaMA/comments/1fc98fu/confirmed_reflection_70bs_official_api_is_sonnet/
