### ISSUE TITLE
Q6_K is slower than Q8_0

### ISSUE THREAD

**Issue by napa3um** [ollama/ollama#6695]
### What is the issue?

gemma2:9b-instruct-**q6_K** : gemma2:9b-instruct-**q8_0** = **21**t/s : **25**t/s
mistral-nemo:12b-instruct-2407-**q6_K** : mistral-nemo:12b-instruct-2407-**q8_0** = **17**t/s : **21**t/s

It used to be different.

### OS

macOS

### GPU

Apple

### CPU

Apple

### Ollama version

0.3.9

**Comment by rick-github** [comment]
[Server logs](https://github.com/ollama/ollama/blob/main/docs/troubleshooting.md#how-to-troubleshoot-issues) of sessions involving both Q6_K and Q8_0 models may give some insight to what's going on, especially if you can get logs from before the tps rate changed.  FWIW a linux+nvidia system shows consistent tps over a range of ollama versions.

| Ollama version | gemma2:9b-instruct-q6_K | gemma2:9b-instruct-q8_0 | mistral-nemo:12b-instruct-2407-q6_K | mistral-nemo:12b-instruct-2407-q8_0 |
| --- | --- | --- | --- | --- |
| 0.2.8 |   29.10|   24.06|   25.12|   20.30 |
| 0.3.0 |   29.05|   24.04|   25.09|   20.34 |
| 0.3.1 |   29.07|   24.08|   25.12|   20.36 |
| 0.3.2 |   29.08|   24.06|   25.07|   20.36 |
| 0.3.3 |   28.99|   24.03|   25.05|   20.35 |
| 0.3.4 |   29.00|   24.00|   25.02|   20.32 |
| 0.3.5 |   28.96|   24.00|   25.00|   20.31 |
| 0.3.6 |   29.00|   23.99|   24.98|   20.27 |
| 0.3.7 |   28.99|   24.01|   24.97|   20.31 |
| 0.3.8 |   28.99|   23.84|   24.96|   20.30 |
| 0.3.9 |   29.00|   24.00|   24.95|   20.29 |
