### ISSUE TITLE
IGPUMemLimit/rocmMinimumMemory are undefined

### ISSUE THREAD

**Issue by wangzd0209** [ollama/ollama#6697]
### What is the issue?

when i first run the code with goland，i can not compile it. it said the IGPUMemLimit/rocmMinimumMemory is undefined.
GPUMemLimit or rocmMinimumMemory is just a const. Can anyone help me?
![屏幕截图 2024-09-08 145031](https://github.com/user-attachments/assets/016bc32f-9f31-4837-813a-9004c6ea99e5)

### OS

Windows

**Comment by dhiltgen** [comment]
Ollama utilizes [cgo](https://go.dev/blog/cgo) to compile and leverage native code.  You'll need to enable this by setting CGO_ENABLED=1 in your environment.  You'll also need to make sure gcc is in your path.
