### ISSUE TITLE
Custom OLLAMA_MODELS Environment Variable Not Respected

### ISSUE THREAD

**Issue by sascharo** [ollama/ollama#6698]
### What is the issue?

Despite setting the environment variable `OLLAMA_MODELS` to a custom path, Ollama continues to download models to the default location (`C:\Users\%username%\.ollama\models`). The environment variable is set correctly and confirmed via echo `env:OLLAMA_MODELS`, but the expected behavior of downloading models to the custom path is not happening.

### OS

Windows

### GPU

Nvidia

### CPU

AMD

### Ollama version

0.3.9

**Comment by rick-github** [comment]
[Server logs](https://github.com/ollama/ollama/blob/main/docs/troubleshooting.md#how-to-troubleshoot-issues) may help in debugging.

**Comment by SamuelHafner** [comment]
Did you set the `OLLAMA_MODELS` ENV before your ollama serve like:

```bash
OLLAMA_MODELS=~/Documents/ollama_models/ ollama serve
```

this works for me but I work on linux

**Comment by sascharo** [comment]
For some reason, it's working in a new terminal now.
