### ISSUE TITLE
MiniCPM3 not supported

### ISSUE THREAD

**Issue by sataliulan** [ollama/ollama#6700]
### What is the issue?

hi there,
I tried to run MiniCPM3 with ollama. I converted the model's bin file to gguf ,and quantized it to Q4_K_M successfully. 
Then , I created a modelfile and ran the model with cmd: 
 ollama run MiniCPM3Q4 "hi ,你好吗"
And I got an error, as shown in the picture, 
![image](https://github.com/user-attachments/assets/f3277275-a980-4580-8ea3-3da19de623f6)
hmm, it seems my ollama (version:0.3.9) is not supported for the model

### OS

Linux

### GPU

Nvidia

### CPU

Intel

### Ollama version

0.3.9

**Comment by jmorganca** [comment]
@sataliulan still in testing, but https://github.com/ollama/ollama/releases/tag/v0.3.10 should work

**Comment by enryteam** [comment]
0.3.10 NOT GOOD TOO

**Comment by sataliulan** [comment]
my ollama has upgraded to 0.3.10 , hmm it's still not working

**Comment by ALTdeveloper** [comment]
my ollama version is 0.3.12 and it still not work :(

**Comment by kaka2008** [comment]
0.3.13 still not work
