### ISSUE TITLE
Windows app gets confused if wsl2 based server is still running

### ISSUE THREAD

**Issue by ares0027** [ollama/ollama#6701]
### What is the issue?

i am using ollama with open web ui but sometimes ollama refuses to launch. no error, no nothing, i double click, it does not even show up on task manager. only solution i have is restarting the pc.

checking the log file it says another instance of ollama is running, but it is not;

```
time=2024-09-08T13:56:31.047+03:00 level=INFO source=logging.go:50 msg="ollama app started"
time=2024-09-08T13:56:31.106+03:00 level=INFO source=lifecycle.go:70 msg="Detected another instance of ollama running, exiting"
```

![2024-09-08 13_57_35-New Issue · ollama_ollama](https://github.com/user-attachments/assets/956504ca-ce06-4127-b68c-065cd09a766b)

### OS

Windows

### GPU

Nvidia

### CPU

Intel

### Ollama version

0.1.19, client 0.3.8

**Comment by rick-github** [comment]
Your system is running a very old version of ollama as the server.  Since it doesn't seem to be showing up in the task list, you can find the name and process ID of the server by opening a Powershell in administrator mode and running:
```
netstat -bano | Select-String -Pattern 11434 -Context 0,1
```

**Comment by ares0027** [comment]
> Your system is running a very old version of ollama as the server. Since it doesn't seem to be showing up in the task list, you can find the name and process ID of the server by opening a Powershell in administrator mode and running:
> 
> ```
> netstat -bano | Select-String -Pattern 11434 -Context 0,1
> ```
> 
> You can then check Startup Apps or Services to see where the program is launched from.

thank you, it was wslrelay.exe. probably when i tried to use wsl to install ollama. ill try to take care of that. thank you :)

**Comment by dhiltgen** [comment]
@ares0027 to clarify your scenario, I believe you installed ollama in WSL2, had it running as a service, and then installed the Windows app without uninstalling the WSL2 instance.  This led the Windows app to see the existing server already running, so it wouldn't start the tray app.  Does that sound accurate?

We should try to add some logic to detect this scenario better and report a more useful message to help guide users if possible.

**Comment by ares0027** [comment]
> @ares0027 to clarify your scenario, I believe you installed ollama in WSL2, had it running as a service, and then installed the Windows app without uninstalling the WSL2 instance. This led the Windows app to see the existing server already running, so it wouldn't start the tray app. Does that sound accurate?
> 
> We should try to add some logic to detect this scenario better and report a more useful message to help guide users if possible.

Yep. Exactly what i think happened. I think first i tried wsl then docker then windows app. Docker was easy to remove and i think i completely ignored/forgot wsl. 

Actually a notification or something could be useful. At least in the logs just like what rick suggested it can at least tell the process name to push the user the right way. Or maybe “it is already running do you want to end this and launch this instance instead?”
