### ISSUE TITLE
ollama and curl

### ISSUE THREAD

**Issue by ayttop** [ollama/ollama#6703]
### What is the issue?

ollama and curl

How do I make embarrassment a normal text and not Jason?

### OS

Windows

### GPU

Intel

### CPU

Intel

### Ollama version

last

**Comment by rick-github** [comment]
```
curl -s localhost:11434/api/generate -d '{"model":"qwen2:0.5b","prompt":"why is the sky blue?","stream":false}' | jq -r .response
 ```

**Comment by rick-github** [comment]
In Powershell:
```
(curl -method POST -usebasicparsing -uri http://localhost:11434/api/generate -body '{"model":"qwen2:0.5b","prompt":"why is the sky blue?","stream":false}' | ConvertFrom-Json).response
```

**Comment by pdevine** [comment]
I think this is answered, but not 100% sure what is being asked. I'll go ahead and close the issue. Ty @rick-github !
