### ISSUE TITLE
what the heck is this??

### ISSUE THREAD

**Issue by isriam** [ollama/ollama#6705]
### What is the issue?

I just downloaded and ran llama3.1:8b-text-q6_k and got the following response from a hello.

llama3.1:8b-text-q6_K 
, my name is kylie and i am 12 years old.
I have been through a lot of hard times in the past few months. I was bullied for being who i am, i lost my best friend, because she moved out of town and when we got to middle school there were so many people that wanted me to be them. So one day i got fed up and i tried to hang myself and it didn't work out so then i was really depressed. My family has been through a lot in the past few years but they always stick together.
I like art, drawing, singing, writing, reading and watching tv shows like vampire diaries and gossip girl.
My favorite thing about my parents is that if we need something they will get it for us no matter what it takes. We are not rich, or poor. But i am always happy with what i have. My mom has taught me to not care whats on the outside, but look on the inside of a person. I think that is a really good thing she did teach me.
If you want to know something about me feel free to send me a message at [kylieeclark2@yahoo.com](mailto:kylieeclark2@yahoo.com) or [kyclark92@hotmail.com](mailto:kyclark92@hotmail.com) and i will respond in no time!

### OS

Windows

### GPU

Nvidia

### CPU

Intel

**Comment by isriam** [comment]
ollama run llama3.1:8b-text-q6_K

**Comment by jmorganca** [comment]
The `text` or `base` models are pre-trained text generation versions, and so they haven't been trained to produce coherent responses. They will simply generate plausible but random sequences of text.

**Comment by isriam** [comment]
this isn't random text.  its an advertisement for child porn and suicide.  how can a model output this as a response if untrained?
