### ISSUE TITLE
Reflection 70B has significant issue with the weights

### ISSUE THREAD

**Issue by gileneusz** [ollama/ollama#6706]
The whole drama is described here:

https://x.com/shinboson/status/1832933753837982024

sorry for recommending the model, I was unaware of that and easily got into the hype

it's still possible that's just technical issue, but I'm suspicious:

https://x.com/rohanpaul_ai/status/1833094994929897862/photo/1

**Comment by juanjgit** [comment]
Yes, please, remove Reflection from the library

**Comment by nisten** [comment]
You have to fix the damn tokenizer_config.json before it works correctly on llama.cpp , please stop making assumptions on twitter threads about a broken 3rd party api , i was not able to reproduce anything the twitter thread said when running it locally.  
![Screenshot 2024-09-09 at 12 51 43 AM](https://github.com/user-attachments/assets/6a8c5e20-20b6-49d9-ae6c-8e8610a45f87)

**Comment by juanjgit** [comment]
I'm 99% sure this is a scam. 

It's not just "Twitter threads." Multiple independent researchers from the LLM community have analyzed both the API and the local model.  

Yes, there's a 1% chance that a single individual who releases an LLM he admits to developing in only 15 days using a known technique has found the holy grail by creating a 70B model that surpasses models from OpenAI and Claude. Yes, there's a 1% chance he used a fake API, but only by mistake.  Yes, there's a 1% chance of an unknown and unexplained "upload error" causing a bug that makes the model seem less capable. 

But the fact is, no one has been able to reproduce his metrics. There's no single piece of concrete proof that the model is as intelligent as he claims. It's highly likely a scam. It should be removed from Ollama.

**Comment by kowshik24** [comment]
I have tried just a simple question! 😉

![image](https://github.com/user-attachments/assets/b9428742-c40b-4de3-8c87-4b9520018343)

**Comment by jmorganca** [comment]
https://ollama.com/library/reflection is updated to the latest available weights: https://huggingface.co/mattshumer/ref_70_e3

Keep in mind the controversy around this model...
