### ISSUE TITLE
 ERROR unable to locate llm runner directory. Set OLLAMA_RUNNERS_DIR to the location of 'ollama/runners'

### ISSUE THREAD

**Issue by Harsha0056** [ollama/ollama#6709]
### What is the issue?

Model is Downloaded  but unable to run it. Tried to locate ollama/runners couldn't find it.

2024/09/09 04:48:23 config.go:173: ERROR unable to locate llm runner directory. Set OLLAMA_RUNNERS_DIR to the location of 'ollama/runners'
.......
pulling manifest
verifying sha256 digest
writing manifest
success
Error: no suitable llama servers found

Running in a windows system
 Specs :

Processor :  Snapdragon(TM) X Elite - X1E78100 - Qualcomm(TM) Oryon(TM) CPU   3.42 GHz
GPU  : Qualcomm(R) Adreno(TM) X1-85  
NPU : Snapdragon(R) X Elite - X1E78100 - Qualcomm(R) Hexagon (TM) 

### OS

Windows

### GPU

Other

### CPU

Other

### Ollama version

0.3.9

**Comment by rick-github** [comment]
[Server logs](https://github.com/ollama/ollama/blob/main/docs/troubleshooting.md#how-to-troubleshoot-issues) may aid in debugging.

**Comment by Harsha0056** [comment]
Uninstalled and reinstalled , working now.

**Comment by dhiltgen** [comment]
We've seen scenarios where AV software has removed binaries due to false positives leading to these sorts of failure modes in prior versions.  If it happens again, please check your AV settings/logs to see if that's what might explain the removing of these files and let us know.
