### ISSUE TITLE
Can I stop then start a "pull" when the LLM is not completely downloaded?

### ISSUE THREAD

**Issue by bulrush15** [ollama/ollama#6711]
### What is the issue?

I'm on Windows 11 with an Nvidia GeForce RTX 3060 video card. I've already used ollama with a smaller LLM that I pulled. I started a pull of a large LLM, mistral-large. It seems it would take 3 hours on my PC and it's really slowing down my network. So I stopped the download/pull. 

1. If I restart the pull will Ollama save the contents that were already downloaded? 
2. Or do I have to start the pull from the beginning again? 
3. Do I have to delete the downloaded portion of the LLM first before restarting the pull? 

Thanks.

### OS

Windows

### GPU

Nvidia

### CPU

AMD

### Ollama version

0.3.9

**Comment by rick-github** [comment]
It depends on how you stopped ollama.  If you interrupted the client (^C on Linux, maybe the same for windows), ollama should detect the previously downloaded shards and resume pulling just the missing shards.  If you stopped the server, then when it restarted it will have done a cleanup of the model area and deleted the shards, so re-pulling will download everything.

**Comment by bulrush15** [comment]
Yes, I stopped the program in cmd.exe with CTRL-C. I did not reboot my pc or stop the ollama server in my systray either. 

Thank you. I will consider this closed.
