### ISSUE TITLE
Error loading model architecture for miniCPM3-4B: Unknown architecture 'minicpm3'

### ISSUE THREAD

**Issue by ChuiyuWang1** [ollama/ollama#6721]
Hello Ollama team,

First of all, I want to express my appreciation for the amazing work you’ve done with Ollama. The tool has been incredibly helpful, and I hope your team continues to thrive and build even more powerful features!

I’ve encountered an issue while trying to use the miniCPM3-4B model with Ollama for inference.

Since there is no miniCPM3-4B model in ollama library, I used `yefx/minicpm3_4b` and `shibing624/minicpm3_4b`. When I perform inference using these models, the error shows

`llama_model_load: error loading model: error loading model architecture: unknown model architecture: 'minicpm3'`

I'm using ollama version 0.3.10 and Windows 11 OS.

I have two questions here:
1. Does Ollama currently support the miniCPM3-4B model architecture?
2. If not, are there any plans to support it, or is there a workaround that would allow me to use this model with Ollama?

Thank you for your time and for any guidance you can provide!

**Comment by jmorganca** [comment]
Merging with https://github.com/ollama/ollama/issues/6722. Thanks @rick-github

**Comment by enryteam** [comment]
0.3.13, the same error
