### ISSUE TITLE
How to change the system memory folder ? 

### ISSUE THREAD

**Issue by mdabir1203** [ollama/ollama#6723]
### What is the issue?

I tried to run the llama 3.1 with Ollama and I am getting this : 
![image](https://github.com/user-attachments/assets/1c5903d2-fd77-434e-b00b-f39ab349aede)

I have enough diskspace but what are the reasons behind this ? 

### OS

Windows

### CPU

Intel

### Ollama version

0.3.9

**Comment by rick-github** [comment]
You don't have enough RAM to load the model.  If you increase swap or terminate other programs you may have enough, you need 500M.

**Comment by jmorganca** [comment]
As @rick-github mentioned this there isn't enough memory or page size for the model to run – it would most likely crash.
