### ISSUE TITLE
Tools Tag with  "ollama show" command

### ISSUE THREAD

**Issue by LilPiep** [ollama/ollama#6724]
Hey there, 

It would be wonderfull to have the opportunity to check if a model is Tool compatible or not after pulling its manifest. It's pretty clear on the online model library but once the model is pulled, the information is lost. 

Thanks for your attention :)

![image](https://github.com/user-attachments/assets/9ca53eaf-1e97-4783-b95b-92eff5e019bf)

**Comment by rick-github** [comment]
Related: https://github.com/ollama/ollama/issues/5794

**Comment by LilPiep** [comment]
Same as #5794
