### ISSUE TITLE
Does ollama check for free disk space BEFORE pulling a new model?

### ISSUE THREAD

**Issue by bulrush15** [ollama/ollama#6727]
I actually have 3 drives in my Windows 11 system. 

Does ollama check for free disk on the drive it's installed space BEFORE Pulling a new model? Before it pulls a model it should check that the user has at least 2-3GB of free disk space after pulling the model. If the user doesn't have that, then ollama should show an error message and links on how to clean up browser caches, temp files, etc.

**Comment by jmorganca** [comment]
Hi @bulrush15 thanks for the issue. It currently doesn't since disk space can fluctuate while the user is downloading a model (e.g. downloading two models at once) and so it would be hard to know for sure.
