### ISSUE TITLE
error wile install on opensuse leap 15.6

### ISSUE THREAD

**Issue by kc8pdr205** [ollama/ollama#6731]
### What is the issue?

I'm trying to install ollame in leap 15.6 When I try the command to install ollama . I getting his error. I have both files installed 

WARNING: Unable to detect NVIDIA/AMD GPU. Install lspci or lshw to automatically detect and install GPU dependencies.I do have cuda and the NVIDIA drivers installed

### OS

Linux

### GPU

Nvidia

### CPU

AMD

**Comment by rick-github** [comment]
The install script doesn't think `lspci` or `lshw` are installed.  What happens if you run `lspci` and `lshw`?  If they work, what's the result of `which lspci` and `which lshw`?

**Comment by kc8pdr205** [comment]
When I run for lshw I get /usr/sbin/lshw
and for lspci I get /sbin/lspci

**Comment by rick-github** [comment]
Looks like you installing in an environment that does have /sbin/ in the `PATH` variable. Try running
```
curl -fsSL https://ollama.com/install.sh | PATH="/sbin:/usr/sbin:$PATH" sh
```

**Comment by jmorganca** [comment]
Thanks @rick-github! Will close this
