### ISSUE TITLE
curl

### ISSUE THREAD

**Issue by ayttop** [ollama/ollama#6733]
### What is the issue?

how to run
curl http://localhost:11434/api/generate -d '{
  "model": "llama3.1",
  "prompt":"Why is the sky blue?"
}' 

on cmd
In the same way

### OS

Windows

### GPU

Intel

### CPU

Intel

### Ollama version

last

**Comment by jmorganca** [comment]
See https://github.com/ollama/ollama/blob/83a9b5271a68c7d1f8443f91c8d8b7d24ab581a9/docs/windows.md#api-access

Thanks for the issue!
