### ISSUE TITLE
Model looses modelfile context

### ISSUE THREAD

**Issue by kayloren** [ollama/ollama#6737]
### What is the issue?

Hi, I have created a custom model using llava and also I created a custom modelfile, however, after several requests or computer restarts the model looses the modelfile configuration, I supposed that modelfile configuration wont change at least if I perform manual changes otherwise it should be working as expected, In the beggining I thought that I should save the session/state but that just works with the interactive console, I'm experiencing the error through the API calls (generate endpoint)

any help or advice is welcome
thanks in advance!

### OS

Linux, Docker

### GPU

Nvidia

### CPU

Intel

### Ollama version

0.3.9

**Comment by rick-github** [comment]
What are the contents of your Modelfile?  Can you give examples of API calls that fail, and the expected results?  Can you supply [system logs](https://github.com/ollama/ollama/blob/main/docs/troubleshooting.md#how-to-troubleshoot-issues) for the times when the API calls fail?
