### ISSUE TITLE
Add OLMoE 1b-7b

### ISSUE THREAD

**Issue by Meshwa428** [ollama/ollama#6742]
It's the best for mobile applications and can run on edge devices with only 1b active params

Hf reference: https://huggingface.co/allenai/OLMoE-1B-7B-0924-Instruct

Motivation:
It is fast, reduces carbon emissions and runs on edge devices. What else do we need 😋?

With only 1b active params it is on par with other llms

**Comment by Meshwa428** [comment]
Update:

Gguf quants for this model can be found here: 
**Meshwa/OLMoE-1b-7b-0924-Instruct-gguf**

These quants are created using this llama.cpp fork whose merge is pending
[#9462](https://github.com/ggerganov/llama.cpp/pull/9462)

Repo: https://github.com/2015aroras/llama.cpp/tree/olmoe

**Comment by Meshwa428** [comment]
Any updates?

**Comment by Meshwa428** [comment]
OLMoE 1b-7b has been finally implemented in [llama.cpp - master branch](https://github.com/ggerganov/llama.cpp)

Thanks🙏

**Comment by dhiltgen** [comment]
Let's track this via #2337
