### ISSUE TITLE
Add version when the docker container is starting

### ISSUE THREAD

**Issue by svaningelgem** [ollama/ollama#6749]
It'd be nice to know what version is running when sharing logs. So my feature request is to add the current version when you start the docker container.

**Comment by jmorganca** [comment]
Hi @svaningelgem it should be in the logs:

```
time=2024-09-11T16:56:38.833-07:00 level=INFO source=routes.go:1172 msg="Listening on 127.0.0.1:11434 (version 0.3.10)"
```

**Comment by svaningelgem** [comment]
Thanks, I overlooked that!
