### ISSUE TITLE
encountered an error while using the new model minicpm-v

### ISSUE THREAD

**Issue by supersaiyan2019** [ollama/ollama#6751]
### What is the issue?

ollama run minicpm-v
Error: llama runner process has terminated: GGML_ASSERT(new_clip->has_llava_projector) failed

win11
ollama version is 0.3.6
Warning: client version is 0.3.10

### OS

Windows

### GPU

Nvidia

### CPU

Intel

### Ollama version

0.3.10

**Comment by delfireinoso** [comment]
On Mac M2 Pro 32 Gbytes, with OpenWebUi, the model is not Multimodal, has no vision capabilities

**Comment by igorschlum** [comment]
version q8_0 is not working well:

Last login: Wed Sep 11 14:12:43 on ttys001
(base) igor@Mac-Studio-192 FineTuning % ollama run minicpm-v:8b-2.6-q8_0
pulling manifest 
pulling 1dcd11b83b5e... 100% ▕███████████████████████████████████████████████████████▏ 8.1 GB                         
pulling f8a805e9e620... 100% ▕███████████████████████████████████████████████████████▏ 1.0 GB                         
pulling 60ed67c565f8... 100% ▕███████████████████████████████████████████████████████▏  506 B                         
pulling 43070e2d4e53... 100% ▕███████████████████████████████████████████████████████▏  11 KB                         
pulling f02dd72bb242... 100% ▕███████████████████████████████████████████████████████▏   59 B                         
pulling cb9e566c141e... 100% ▕███████████████████████████████████████████████████████▏  566 B                         
verifying sha256 digest 
writing manifest 
success 
>>> can you read text on this picture ? /Users/igor/Desktop/Capture\ d’écran\ 2024-08-31\ à\ 16.43.15.png 
Added image '/Users/igor/Desktop/Capture d’écran 2024-08-31 à 16.43.15.png'
<doc>     
spiritualite_bien_etre_spiritualite_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_biespiritualite_bien_etre_spiritualite_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bie_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bie_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bie_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bie_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bie_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bie_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bie_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bie_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bie_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bie_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bie_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bie_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bie_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bie_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bie_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bie_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bie_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bie_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bie_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bie_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bie_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bie_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bie_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bie_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bie_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bie_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bie_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bie_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bie_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bie_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bie_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bie_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bie_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bie_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_bien_b^C

>>> /exit
(base) igor@Mac-Studio-192 FineTuning % ollama -v
ollama version is 0.3.10
(base) igor@Mac-Studio-192 FineTuning %

**Comment by igorschlum** [comment]
with latest :

(base) igor@Mac-Studio-192 FineTuning % ollama run minicpm-v:latest
pulling manifest 
pulling 262843d4806a... 100% ▕███████████████████████████████████████████████████████▏ 4.4 GB                         
pulling f8a805e9e620... 100% ▕███████████████████████████████████████████████████████▏ 1.0 GB                         
pulling 60ed67c565f8... 100% ▕███████████████████████████████████████████████████████▏  506 B                         
pulling 43070e2d4e53... 100% ▕███████████████████████████████████████████████████████▏  11 KB                         
pulling f02dd72bb242... 100% ▕███████████████████████████████████████████████████████▏   59 B                         
pulling 175e3bb367ab... 100% ▕███████████████████████████████████████████████████████▏  566 B                         
verifying sha256 digest 
writing manifest 
success 
>>> can you read text on this picture ? /Users/igor/Desktop/Capture\ d’écran\ 2024-08-31\ à\ 16.43.15.png 
Added image '/Users/igor/Desktop/Capture d’écran 2024-08-31 à 16.43.15.png'
<doc>     spiritualite_bien_etrer 
     maroc    Suivre 
     Audio d'origine Original 
  TSuIE </doc>

>>> >>> can you read text on this picture ? /Users/igor/Desktop/Capture\ d’écran\ 2024-08-31\ à\ 16.43.15.png 
... Added image '/Users/igor/Desktop/Capture d’écran 2024-08-31 à 16.43.15.png'
... <doc>     spiritualite_bien_etrer 
...      maroc    Suivre 
...      Audio d'origine Original 
...   TSuIE </doc>
![Uploading Capture d’écran 2024-08-31 à 16.43.15.png…]()

**Comment by delfireinoso** [comment]
On my system all text is working 

The only problem is that the model doesn't proclaim it's a vision model

**Comment by igorschlum** [comment]
For me model minicpm-v:8b-2.6-q6_K is not working.

>>> /exit
(base) igor@macIgor-2 ~ % ollama run minicpm-v:8b-2.6-q6_K
>>> can you generate a text on a young boy on his first day of class that cry and his teacher who wants to calm him.
On the first day of school, a young boy nervously approached the classroom door, tears streaming down his face as he hesitated at the threshold.
His name was Alex, and today marked the beginning of what would be an exciting but terrifying new chapter in his life - elementary school. He 
had always been shy around strangers, never mind a whole room full of them! The thought alone made him feel dizzy with anxiety.
As he finally pushed open the door to step into Mr. Johnson's classroom for the first time ever as a student, there stood his new teacher 
waiting patiently by the entrance - her hands gently clasped in front of her chest and an encouraging smile on her face that was just enough to 
make Alex's heart race even faster.
"Hello," she said warmly with a nod, "Welcome to class. My name is Mrs. Johnson!"
Alex felt like he could hardly breathe as his eyes darted around the room at all the other students staring back at him in awe or excitement - 
but then Mr. Johnson himself appeared beside her and gave Alex an encouraging pat on the shoulder.
"Don't worry," said Mr. John

>>> can you OCR this image? /Users/igor/Documents/Capture\ d’écran\ 2024-09-09\ à\ 23.43.00.png 
Added image '/Users/igor/Documents/Capture d’écran 2024-09-09 à 23.43.00.png'
On the first day of school, a young boy nervously approached the classroom door, tears streaming down his face as he hesitated at the threshold.
His name was Alex and today marked the beginning of what would be an exciting but terrifying new chapter in his life - elementary school. He had 
always been shy around strangers, never mind a whole room full of them! The thought alone made him feel dizzy with anxiety.
As he finally pushed open the door to step into Mr. Johnson's classroom for the first time ever as a student, there stood his new teacher 
waiting patiently by the entrance - her hands gently clasped in front of her chest and an encouraging smile on her face that was just enough to 
make Alex's heart race even faster.
"Hello," she said warmly with a nod, "Welcome to class. My name is Mrs. Johnson!

>>> Send a message (/? for help)

**Comment by pdevine** [comment]
@supersaiyan2019 It looks like you need to restart your ollama server and it should work. The client you're connecting with is correct, but the server is out of date.

I'll go ahead and close the issue.
