### ISSUE TITLE
Add support for TPUs accelerators such as Coral.AI TPUs.

### ISSUE THREAD

**Issue by gtherond** [ollama/ollama#6755]
Hi team, would it be doable to get support of TPUs accelerators such as Coral.ai TPUs?

https://www.coral.ai/docs/accelerator/get-started/

That would help us to make the models available to our low power lab that leverage such TPUs accelerator type to run AI models on low power platforms.

Thanks a lot!

**Comment by jmorganca** [comment]
Merging with https://github.com/ollama/ollama/issues/990

Thanks for the issue!

**Comment by gtherond** [comment]
thanks!
