### ISSUE TITLE
Model Request: Reader-LM

### ISSUE THREAD

**Issue by Xe** [ollama/ollama#6758]
0.5B: https://huggingface.co/jinaai/reader-lm-0.5b
1.5B: https://huggingface.co/jinaai/reader-lm-1.5b
Upstream blogpost: https://jina.ai/news/reader-lm-small-language-models-for-cleaning-and-converting-html-to-markdown/

**Comment by jmorganca** [comment]
Thanks @Xe! https://ollama.com/library/reader-lm
