### ISSUE TITLE
reflection

### ISSUE THREAD

**Issue by ayttop** [ollama/ollama#6759]
### What is the issue?

how add reflection to ollama with modelfile?

### OS

Windows

### GPU

Intel

### CPU

Intel

### Ollama version

last

**Comment by jmorganca** [comment]
Try the system prompt!

```
SYSTEM """You are a world-class AI system, capable of complex reasoning and reflection. Reason through the query inside <thinking> tags, and then provide your final response inside <output> tags. If you detect that you made a mistake in your reasoning at any point, correct yourself inside <reflection> tags."""
```

Let me know if this helps :)

**Comment by ayttop** [comment]
PS C:\Users\Aytto\OneDrive\Desktop\1> ollama create Reflection-Llama-3.1-70B.Q2_K_L.gguf -f a.txt
transferring model data 100%
Error: invalid file magic

**Comment by ayttop** [comment]
FROM ./Reflection-Llama-3.1-70B.Q2_K_L.gguf


SYSTEM """You are a world-class AI system, capable of complex reasoning and reflection. Reason through the query inside <thinking> tags, and then provide your final response inside <output> tags. If you detect that you made a mistake in your reasoning at any point, correct yourself inside <reflection> tags."""

**Comment by ayttop** [comment]
"C:\Users\Aytto\.ollama\models\blobs\sha256-76b2096077dd883d544fea8cb1dfd89e33ca0c917a349a4f587fa26837b38201"
"C:\Users\Aytto\.ollama\models\blobs\sha256-819c2adf5ce6df2b6bd2ae4ca90d2a69f060afeb438d0c171db57daa02e39c3d"
"C:\Users\Aytto\.ollama\models\blobs\sha256-75357d685f238b6afd7738be9786fdafde641eb6ca9a3be7471939715a68a4de"
"C:\Users\Aytto\.ollama\models\blobs\sha256-395085bdc570090eef8e9f5a5e9236a08e6226d36acb48cb1ba83003dfd9bb97"
"C:\Users\Aytto\.ollama\models\blobs\sha256-2190828de961641d5a7b034d11c3e34f3a7e91e9ec195309770fb337231cc085"
"C:\Users\Aytto\.ollama\models\blobs\sha256-b837481ff8556a29d9bb27ac280c23495a491e7268d8f043f2e617f7f795d089"
"C:\Users\Aytto\.ollama\models\blobs\sha256-c71d239df91726fc519c6eb72d318ec65820627232b2f796219e87dcf35d0ab4"
"C:\Users\Aytto\.ollama\models\blobs\sha256-3f1efe5e9d9d9349e5f1f93a87626329fd56c974552b3580f20cc1204641a4bf"
"C:\Users\Aytto\.ollama\models\blobs\sha256-7a3af5a049b5df59a1e07a76d316911700b78fbc21e0675a8472c80bf9e5b6c0"
"C:\Users\Aytto\.ollama\models\blobs\sha256-7b4601d271b2988c5150ba081dfd9263197b5b7f2d39b25e8bad601380019031"
"C:\Users\Aytto\.ollama\models\blobs\sha256-38badd946f91096f47f2f84de521ca1ef8ba233625c312163d0ad9e9d253cdda"

**Comment by ayttop** [comment]
"C:\Users\Aytto\.ollama\models\blobs\sha256-7a3af5a049b5df59a1e07a76d316911700b78fbc21e0675a8472c80bf9e5b6c0"
"C:\Users\Aytto\.ollama\models\blobs\sha256-3f1efe5e9d9d9349e5f1f93a87626329fd56c974552b3580f20cc1204641a4bf"

**Comment by ayttop** [comment]
https://github.com/ollama/ollama/issues/6746
what this?
