### ISSUE TITLE
Would be nice to have a "continue last message" option with the `/api/chat` endpoint

### ISSUE THREAD

**Issue by hammer-ai** [ollama/ollama#6778]
Hi there, it would be nice to have a "continue last message" option with the `/api/chat` endpoint. Thanks!

**Comment by pdevine** [comment]
@hammer-ai not quite sure what you're asking for here. If you want to continue a conversation you just pass back the entire `messages` array with the next message that you want to send. Did you mean something different?

**Comment by jmorganca** [comment]
@hammer-ai this can be done today with a request similar to:

```
curl http://localhost:11434/api/chat -d '{
  "model": "llama3.1",
  "messages": [
    {
      "role": "user",
      "content": "why is the sky blue?"
    },
    {
      "role": "assistant",
      "content": "Great question, the sky is blue because it was painted by "
      }
  ]
}'
```

Hope this helps!

**Comment by Omega-Centauri-21** [comment]
I guess what @hammer-ai was asking is a functionality in ollama like [HuggingFace Continue final message](https://huggingface.co/docs/transformers/main/en/chat_templating#what-does-continuefinalmessage-do).

I too do hope for this!

Thanks!

**Comment by pdevine** [comment]
@Omega-Centauri-21 This is already essentially how the API already works today. Try out @jmorganca 's snippet above.

**Comment by Omega-Centauri-21** [comment]
@pdevine I have already used this method, was hoping if there is any other way so that I don't have to pass the old message intrinsically. I do have another question. If I keep using this method, won't my message size or question token size be bigger and unstable as compared to a clean slate?
