### ISSUE TITLE
The system parameter OLLAMA_NUM_PALLEL is invalid for embeding model

### ISSUE THREAD

**Issue by black-fox-user** [ollama/ollama#6792]
### What is the issue?

I have set the system parameters, but when loading the embedding model, only one is still in effect. I copied this model, and surprisingly, their model IDs are the same. After importing the model, the model ID changed, but the same model was still used in the end。
![image](https://github.com/user-attachments/assets/e331defe-5548-479b-a5de-32a3d8d1de4d)

### OS

Windows

### GPU

Nvidia

### CPU

Intel

### Ollama version

0.3.10

**Comment by rick-github** [comment]
This is due to a [change](https://github.com/ollama/ollama/pull/6467) that was introduced to fix memory corruption in embedding models.

**Comment by black-fox-user** [comment]
> This is due to a [change](https://github.com/ollama/ollama/pull/6467) that was introduced to fix memory corruption in embedding models.
Perhaps my description is not comprehensive. I originally intended to set up the vector model to support concurrency, but only one concurrent number is effective. Then I remembered the OLLAMA_MAX_LOADEDMODELS parameter and copied a model, but with the same ID, the same model was still loaded. I tried importing another model again, although the IDs are different, their digest parameter points to the same model. The OLLAMA_NUMPARALLEL and OLLAMA_MAX_LOADEDMODELS parameters are valid for other models, such as qwen2:1.5b.
![1726219316562](https://github.com/user-attachments/assets/028cda9a-36ec-4187-99cb-8c6e3075fdb2)

**Comment by rick-github** [comment]
ollama doesn't support loading the same model more than once.  A model is identified by the sha256 of the GGUF file, so creating a new model using the same GGUF file is just like giving the same model a new name, you still can't load it more than once.  If you want to run the same model more than once, you need to run multiple ollama servers.
