### ISSUE TITLE
Running the model under jetpack6 failed

### ISSUE THREAD

**Issue by litao-zhx** [ollama/ollama#6798]
![image](https://github.com/user-attachments/assets/7a30c042-e67a-4d11-a9a3-705f9149fc38)
The error message is shown in the above figure. After the download is completed, the runtime keeps timeout

**Comment by cplasfwst** [comment]
同样的问题，请求解答

**Comment by dhiltgen** [comment]
Dup of #2408 fixed by PR #6400

Until that is merged, you can build from source and it should work.
