### ISSUE TITLE
Run bug of 0.3.10

### ISSUE THREAD

**Issue by ZX-math** [ollama/ollama#6804]
### What is the issue?

I'm sorry for raising this problem. This problem mainly comes from when I installed ollama0.3.10, I was prompted that I could not find VCRUNTIME140.dll, MSVCP140.dll, VCRUNTIME140_1.dll, and Error was displayed: llama runner process has terminated: exit status 0xc0000135, so I came to seek answers from netizens

### OS

Windows

### CPU

Intel

### Ollama version

0.3.10

**Comment by ZX-math** [comment]
I tried 0.3.9 with the same result

**Comment by levicki** [comment]
https://aka.ms/vs/17/release/vc_redist.x64.exe
https://aka.ms/vs/17/release/vc_redist.x86.exe

**Comment by nikelius** [comment]
I tried 0.3.11 on windows，with the same result：
“ollama_llama_server.exe - 系统错误：由于找不到VCRUNTIME140_1.dll，无法继续执行代码。重新安装程序可能会解决。”

But I succeeded with version 0.3.2.

**Comment by dhiltgen** [comment]
@nikelius the fix is in 0.3.12

**Comment by LeonelRFF** [comment]
Hello, I am having the same problem. I have ollama version 0.3.14 installed on windows 11 version 23H2, MSVCP140.dll is not found.

**Comment by dhiltgen** [comment]
@LeonelRFF can you try the latest 0.4.0 RC and see if that clears it up?  If not, please share the app.log and server.log if present.

**Comment by LeonelRFF** [comment]
Perfect in version 0.4.0 RC it works.
