### ISSUE TITLE
how do l install the model to D hard drive?

### ISSUE THREAD

**Issue by 0bubble0** [ollama/ollama#6813]
**how do l install the model to D hard drive?**

**Comment by 0bubble0** [comment]
> **如何将模型安装到 D drive？**

**Comment by cgimenez** [comment]
Check the doc for the OLLAMA_MODELS environment variable

**Comment by 0bubble0** [comment]
> 查看 doc 中的 OLLAMA_MODELS 环境变量

It doesn't work🥲🥲🥲

**Comment by 0bubble0** [comment]
> Check the doc for the OLLAMA_MODELS environment variable

It works when me reboot my computer😀😀😀

**Comment by weichanglang** [comment]
我关机也不起作用，还重新卸载后安装，反复下载模型
