### ISSUE TITLE
Typo in Gemma 2 model card

### ISSUE THREAD

**Issue by nonetrix** [ollama/ollama#6820]
For some reason at https://ollama.com/library/gemma2 it says
```
Google Gemma 2 is a high-performing and efficient model by now available in three sizes: 2B, 9B, and 27B. 
```
Which makes zero sense if you read the `efficient model by now available in three sizes: 2B, 9B, and 27B. ` part which I assume should be `efficient model by Google now available in three sizes: 2B, 9B, and 27B.`

**Comment by nonetrix** [comment]
Had my own typo 😅

**Comment by jmorganca** [comment]
This should be fixed now. Thanks so much @nonetrix !!!
