### ISSUE TITLE
使用Modelfile加载本地gguf文件，会胡乱输出内容

### ISSUE THREAD

**Issue by czhcc** [ollama/ollama#6821]
### What is the issue?

我是使用llama-factory在qwen2-1.5b的基础上微调出一个hf模型。
再用llama.cpp将其转为gguf，加载到ollama后会胡乱输出。

但将原始的qwen2-1.5b转换为gguf后加载没问题。
微调出的hf模型用vllm加载测试没问题。
微调出的hf模型转换出的gguf文件，用llama-server加载测试也没问题。

就是ollama加载这个gguf会胡乱输出。

### OS

Windows, Docker

### GPU

Nvidia

### CPU

Intel

### Ollama version

0.3.10

**Comment by czhcc** [comment]
没事了，要增加TEMPLATE

**Comment by light-266** [comment]
我也遇到了同样的问题，能问下你的TEMPLATE是怎么写的吗？

> 没事了，要增加TEMPLATE

**Comment by qq1273834091** [comment]
> 没事了，要增加模板

我也遇到了同样的问题，能问下你的模板是怎么写的吗？

**Comment by qq1273834091** [comment]
> 我也遇到了同样的问题，能问下你的模板是怎么写的吗？
> 
> > 没事了，要增加模板

你有解决吗？我如何规定我的模版
