### ISSUE TITLE
Old Context Information fetched

### ISSUE THREAD

**Issue by atul-siriusai** [ollama/ollama#6838]
Hello,

I am currently working on a Retrieval-Augmented Generation (RAG) application using LLaMA 3.1 70B. The workflow involves a set of documents in markdown format and an Excel sheet containing specific information that needs to be extracted from these documents. The process iterates over each row, dynamically generating a prompt and retrieving the relevant record along with its citation.

However, I am encountering an issue when processing subsequent documents. It appears that the model is retaining context from the previous document and using it to answer queries for the new document. This is causing inconsistencies in the responses and affecting the accuracy of the extraction.

Any insights on how to ensure the model resets context between documents would be appreciated

### OS

Linux

### GPU

Nvidia

### CPU

Intel

### Ollama version

0.3.6

**Comment by YonTracks** [comment]
Send a empty context[] to reset, I sent a email, I thought maybe security issue, but if local all good, trying to make sure this is not also a feature. Good luck.

**Comment by rick-github** [comment]
What client are you using?  The model itself is stateless, if the responses from the model include context from previous prompts, it means the client must be sending that information with the prompt.

**Comment by YonTracks** [comment]
yes, being sure the default context[] embedding is reset with the new chat(check for cache etc) each time for me yes solved/fixed, a react/next.js issue (skills issue lol srry). native windows ollama local install,  api/generate.
api/chat not affected. 
cheers.

**Comment by YonTracks** [comment]
thankyou.

**Comment by atul-siriusai** [comment]
I am using ChalOllama from Langchain.

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by rick-github** [comment]
Your langchain app may be doing something like
```python
from langchain_ollama import ChatOllama

messages = [
  SystemMessage{"You are an AI expert in RAG"),
]

while not finished_all_instructions():
  messages.append(HumanMessage(get_instruction_from_excel()))
  response = ChatOllama(model="llama3.1").invoke(messages)
  messages.append(response)
  do_something_with_response(response)
```
so it's accumulating context with each `invoke()`.

If you can provide a code snippet, or better, a standalone script that demonstrates the problem, debugging would be easier.

**Comment by YonTracks** [comment]
good info here `https://python.langchain.com/docs/tutorials/local_rag/` , seems embeddings / context needs to be reset same same  ensure reset input["context"].   good luck

**Comment by atul-siriusai** [comment]
Thanks for your comments. 

If it is accumulating with each invoke(). Is there a way to clear it? 
When you say send empty context, would that even clear it, as only empty entry would be appended.

**Comment by YonTracks** [comment]
It actually shows ollama is getting even better, love it cheers,  ollama.

Best to understand exactly what is happening here? 
but, try no context(your use case might not need it, if can be done even not sure need code example?),
also srry if not the issue but, I'm thinking there is the "prompt"/ messages , then the context, but langchain might not allow that(auto context or something). check your updated / latest etc.   doc's should say? cache is a gotcha big time? guessing that will be it. good luck, I tried. cheers

**Comment by rick-github** [comment]
If we can see the actual code, we can offer better suggestions.  But the simplest way to clear the context is to just create a new message structure each time.

```python
from langchain_ollama import ChatOllama

while not finished_all_instructions():
  messages = [
    SystemMessage{"You are an AI expert in RAG"),
    HumanMessage(get_instruction_from_excel())
  ]
  response = ChatOllama(model="llama3.1").invoke(messages)
  do_something_with_response(response)
```

**Comment by mdhuzaifapatel** [comment]
Can you guys please tell me (if possible with a code example) how to use context (list of numbers) which we get from current response in next response? 

Everytime I'm hitting Ollama API it's generating general answers, not related to the conversation history, I mean, I think it's not using previous responses context . 
Please help me out 
Thanks

**Comment by rick-github** [comment]
```python
#!/usr/bin/env python3

import ollama

prompts = [
  'An apple is $1.50',
  'How much is an apple?'
]

context = []
llm = ollama.Client()

for p in prompts:
  response = llm.generate(
      model="llama3.2:3b-instruct-q4_K_M",
      prompt=p,
      context=context
      )
  context = context + response["context"]
  print(response["response"]+"\n==")
```
```console
$ ./6838.py 
That sounds like a pretty standard price for an apple! Would you like to know the nutritional information or some fun facts about apples?
==
You mentioned earlier that an apple costs $1.50.
==
```

**Comment by rick-github** [comment]
@mdhuzaifapatel Note that the `context`  field is being deprecated: https://github.com/ollama/ollama/pull/7878
