### ISSUE TITLE
link downloaded model to ollama

### ISSUE THREAD

**Issue by Jason-Zhi** [ollama/ollama#6856]
Is there any API for linking an downloaded model to ollama from elsewhere. Suppose the model is downloaded before installing ollama, is there any way to link the model to ollama?

**Comment by rick-github** [comment]
You can import the model.
```
$ echo FROM downloaded-model.gguf > Modelfile
$ ollama create my-downloaded-model
```
This will also work for some huggingface models that use safetensors, you just point the Modelfile at the directory of the HF model:
```
$ echo FROM huggingface/model/directory > Modelfile
$ ollama create my-downloaded-model
```

**Comment by ayttop** [comment]
PS C:\Users\Aytto\OneDrive\Desktop\2> echo FROM Phi-3-mini-4k-instruct > Modelfile
PS C:\Users\Aytto\OneDrive\Desktop\2> ollama create Phi-3-mini-4k-instruct


PS C:\Users\Aytto\OneDrive\Desktop\2> ollama create Phi-3-mini-4k-instruct -f Modelfile
transferring model data 100%
converting model
creating new layer sha256:3108066c18e150659c9bb4f77d704968dd62cb0021b222a1e1ad2fe68449b36a
using autodetected template zephyr
using existing layer sha256:b9fe8949313d978079167065437123c7603d980b0c3bba2214bf97296004f54c
creating new layer sha256:7414535def53302c5e1fb9a1c50ef101b459da6258da84bc63942b2375b9208a
writing manifest
success
PS C:\Users\Aytto\OneDrive\Desktop\2> ollama list
NAME                             ID              SIZE      MODIFIED
Phi-3-mini-4k-instruct:latest    aa8c1a07f8be    7.6 GB    14 seconds ago
PS C:\Users\Aytto\OneDrive\Desktop\2> ollama run Phi-3-mini-4k-instruct:latest
Error: llama runner process has terminated: GGML_ASSERT(info->ne[i] > 0) failed
PS C:\Users\Aytto\OneDrive\Desktop\2>

**Comment by rick-github** [comment]
This model is already in the [ollama library](https://ollama.com/library/phi3:3.8b-mini-4k-instruct-fp16).  If you stil want to import, [server logs](https://github.com/ollama/ollama/blob/main/docs/troubleshooting.md#how-to-troubleshoot-issues) may aid in debugging.
