### ISSUE TITLE
Unable to pull models in Windows

### ISSUE THREAD

**Issue by charliebaer** [ollama/ollama#6861]
### What is the issue?
Unable to pull models

![image](https://github.com/user-attachments/assets/d7240b43-af2d-4b3b-aa04-4094d802e07f)

When I say 
`ollama -v`
It says the following
`ollama version is 0.1.17
Warning: client version is 0.3.10`
Ollama also disappeared from the system tray.
I tried uninstalling and installing it again but I still see the same result as above.

### OS

Windows

### GPU

Nvidia

### CPU

Intel

### Ollama version

0.1.17

**Comment by rick-github** [comment]
Have you previously installed ollama in WSL? https://github.com/ollama/ollama/issues/6701

**Comment by charliebaer** [comment]
I've uninstalled the ollama in WSL, and tried installing ollama again on windows.
It works now.

Thanks for the help
