### ISSUE TITLE
Qwen2.5

### ISSUE THREAD

**Issue by lyfuci** [ollama/ollama#6862]
request for Qwen2.5 family, the belowing is the 7B size url
https://huggingface.co/Qwen/Qwen2.5-7B-Instruct

**Comment by jmorganca** [comment]
Thanks for the issue @lyfuci  https://ollama.com/library/qwen2.5

**Comment by netnem** [comment]
How about the 72b?

**Comment by lyfuci** [comment]
> do I need to update ollama program to use this latest model
> 
> now I use ollama 0.3.10

I run this model in ollama 0.3.10 at first ,but update to 0.3.11 after download, it's do not seem to be mandatory.
