### ISSUE TITLE
Qwen/Qwen2.5-Coder-7B

### ISSUE THREAD

**Issue by wuweinero** [ollama/ollama#6863]
https://huggingface.co/Qwen/Qwen2.5-Coder-7B

**Comment by xsoloking** [comment]
https://ollama.com/library/qwen2.5-coder/tags

**Comment by 00010110** [comment]
> https://ollama.com/library/qwen2.5-coder/tags

需要Qwen2.5-Coder: Base Models版本,不仅仅是instruct版本
![image](https://github.com/user-attachments/assets/8c37c7af-bb99-46c7-bcc2-3ee518f7ec40)

**Comment by mxyng** [comment]
non-instruct models are tagged with `base` to distinguish them from other tags: https://ollama.com/library/qwen2.5-coder:7b-base

**Comment by wuweinero** [comment]
> https://ollama.com/library/qwen2.5-coder/tags

thanks.
