### ISSUE TITLE
ollama import does not work

### ISSUE THREAD

**Issue by CPLACKY** [ollama/ollama#6867]
### What is the issue?

<img width="806" alt="1" src="https://github.com/user-attachments/assets/646b7aca-dbcd-4227-bfef-4a1d54c7a912">
<img width="861" alt="ollama" src="https://github.com/user-attachments/assets/9be387e9-2d7e-4ec0-8118-3d174b998a7d">

dosent work T_T how can i fix this?

**Comment by rick-github** [comment]
This is ComfyUI, not ollama.
