### ISSUE TITLE
Nemotron-mini Tool Calling not using the tools API 50% of the time

### ISSUE THREAD

**Issue by whogben** [ollama/ollama#6870]
### What is the issue?

When [Nemotron-mini](https://ollama.com/library/nemotron-mini) tries to call tools, it often returns this XML wrapping a JSON tool call string, rather than triggering the Ollama tools API - see this message payload:
```
"message": {
    "content": " <toolcall> {\"name\": \"weather_lookup\", \"arguments\": {\n  \"temp_units\": \"celsius\",\n  \"zip_codes\": [\n    12345\n  ]\n}} </toolcall>",
    "role": "assistant"
},
```
However, sometimes it does use the tool calling API, (example correct payload):
```
"message": {
		"content": "",
		"role": "assistant",
		"tool_calls": [
			{
				"function": {
					"arguments": {
						"temp_units": "celsius",
						"zip_codes": [
							"12345"
						]
					},
					"name": "weather_lookup"
				}
			}
		]
	}
```
What I have noticed is that it either succeeds right away, or it gets locked into repeatedly making the unrecognized tool call indefinitely - eg, once it has it's own wrong-example in the chat history, it persists in using that format indefinitely.
I'm not sure what the recommendation would be here - normally I'd expect one should edit the template, but since it works about 50% of the time and fails about 50% of the time, I'm not sure which style to represent in the template.

### OS

Windows

### GPU

Nvidia

### CPU

Intel

### Ollama version

0.3.11

**Comment by rick-github** [comment]
What's the code you are using to make the request that responds with `<toolcall>`?

**Comment by whogben** [comment]
Identical payload each time, the results vary between those two examples above with no code changes. Here's the payload:
```
{
	"messages": [
		{
			"content": "What is the weather in Example State, zip 12345, in degrees Celsius?",
			"role": "user"
		}
	],
	"model": "hermes3:latest",
	"stream": false,
	"tools": [
		{
			"function": {
				"description": "Use this tool to get the weather.",
				"name": "weather_lookup",
				"parameters": {
					"properties": {
						"temp_units": {
							"description": "What units to use for the temperature.",
							"enum": [
								"fahrenheit",
								"celsius",
								"kelvin"
							],
							"type": "string"
						},
						"zip_codes": {
							"description": "An array of zip codes to get the weather for.",
							"items": {
								"description": " A 5 digit USA zipcode string",
								"type": "string"
							},
							"type": "array"
						}
					},
					"required": [
						"zip_codes"
					],
					"type": "object"
				}
			},
			"type": "function"
		}
	]
}
```  
(I've redacted my actual state and zip code)

**Comment by rick-github** [comment]
I ran the query 200 times and apart from differences in argument quoting, it worked as expected:
```console
$ for i in {1..200} ; do curl -s localhost:11434/api/chat -d "$(cat 6870.prompt)" | jq -c .message.tool_calls ; done | sort | uniq -c
     51 [{"function":{"name":"weather_lookup","arguments":{"temp_units":"celsius","zip_codes":["12345"]}}}]
    149 [{"function":{"name":"weather_lookup","arguments":{"temp_units":"celsius","zip_codes":[12345]}}}]
```
I pulled the model this morning specifically for testing, I see that the model is marked as updated yesterday,  and you filed the ticket two days ago, so perhaps a model update has taken care of the issue.

**Comment by whogben** [comment]
Yup working for me too after I pulled the latest, thanks for testing!

**Comment by tripolskypetr** [comment]
After the update it still spamming `<toolcall> {\"type\": \"function\", \"arguments\": {\n  \"name\": \"navigate_to_sales_agent_tool\"\n}} </toolcall>` to the text chat instead of function execution. Please downgrade the model

**Comment by rick-github** [comment]
Example code?

**Comment by tripolskypetr** [comment]
Got the steps to reproduce in https://github.com/ollama/ollama/issues/8287#issuecomment-2571758553
