### ISSUE TITLE
Ollama crashes the Radeon display driver

### ISSUE THREAD

**Issue by muntakim1** [ollama/ollama#6871]
### What is the issue?

Hello Guys, 
I have a system with ryzen 3700x and rx6800. With ollama v3.9 in windows is working and never faced any issue. But with ollama v3.10 in windows was breaking my display driver, whenever I try to use any bigger model like mistral-nemo:12b or even smaller models also crashes. 

### OS

Windows

### GPU

AMD

### CPU

AMD

### Ollama version

3.10

**Comment by jmorganca** [comment]
Hi @muntakim1 do you have the logs by chance? https://github.com/ollama/ollama/blob/main/docs/troubleshooting.md

**Comment by muntakim1** [comment]
I had to reinstall windows to get rid of the broken driver. Now using with the same driver with ollama v3.9 no issues. 

Driver version: adrenaline edition v24.8.1
