### ISSUE TITLE
GGGGG in pesponce

### ISSUE THREAD

**Issue by air55555** [ollama/ollama#6872]
### What is the issue?

---- command log
C:\Program Files\Far Manager>ollama run llama3.1:70b                            >>> name
GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG

>>> /?
Available Commands:
  /set            Set session variables
  /show           Show model information
  /load <model>   Load a session or model
  /save <model>   Save your current session
  /clear          Clear session context
  /bye            Exit
  /?, /help       Help for a command
  /? shortcuts    Help for keyboard shortcuts

Use """ to begin a multi-line message.

>>> /show
Available Commands:
  /show info         Show details for this model
  /show license      Show model license
  /show modelfile    Show Modelfile for this model
  /show parameters   Show parameters for this model
  /show system       Show system message
  /show template     Show prompt template

>>> /show info
  Model
        parameters              70.6B
        quantization            Q4_0
        arch                    llama
        context length          131072
        embedding length        8192

  Parameters
        stop    "<|start_header_id|>"
        stop    "<|end_header_id|>"
        stop    "<|eot_id|>"

  License

        LLAMA 3.1 COMMUNITY LICENSE AGREEMENT
        Llama 3.1 Version Release Date: July 23, 2024

---- server log [server.log](https://github.com/user-attachments/files/17054228/server.log)

### OS

Windows

### GPU

Nvidia

### CPU

AMD

### Ollama version

0.3.10

**Comment by dhiltgen** [comment]
This may be a scenario where we're slightly overshooting memory and windows is paging some of it and leading to gibberish.  As a workaround, you can try to set `OLLAMA_GPU_OVERHEAD` on the server to reduce the amount of layers we load.  If this works, let us know how much overhead you had to set aside and how many layers it was able to load to start producing correct resuilts.

**Comment by air55555** [comment]
Just made fresh ollama install + model pull and now its ok . Thanks !
