### ISSUE TITLE
Unable to pull models behind the proxy on windows

### ISSUE THREAD

**Issue by WeiguangHan** [ollama/ollama#6874]
```
PS C:\Users\Administrator>  set HTTPS_PROXY=http://child-prc.intel.com:913
PS C:\Users\Administrator> set https_proxy=http://child-prc.intel.com:913
PS C:\Users\Administrator>  ollama run qwen2.5:7b
pulling manifest
Error: pull model manifest: Get "https://registry.ollama.ai/v2/library/qwen2.5/manifests/7b": dial tcp 172.67.182.229:443: i/o timeout
```
I set the https_proxy but it doesn't work on my windows computer. I try it many times but it doesn't work.

**Comment by rick-github** [comment]
Set proxy in server, not client.

**Comment by rick-github** [comment]
https://github.com/ollama/ollama/blob/main/docs/faq.md#setting-environment-variables-on-windows

**Comment by dhiltgen** [comment]
Automatically detecting the Windows native proxy configuration and setting Ollama to use that is tracked in #5354 - until that's resolved, users will need to set the environment variables in the server as described above.

If you run into problems setting this @WeiguangHan let us know.
