### ISSUE TITLE
Phi3:mini is using only cpu, llama3:8b is using cpu and gpu, want to enforce only gpu usage.

### ISSUE THREAD

**Issue by KaloyanGeorgiev99** [ollama/ollama#6879]
### What is the issue?

These are my specs and also a comparison between two ollama models and a script how I run ollama locally, **_My questions are:_** Why is the phi3:mini only using the cpu and the ollama3:8b model is using both of them and additionally I would like to ask how to enforce only gpu usage on both models, I have tried the suggestions to set PATH variable to where the cuda dlls are in order to enforce GPU usage.

OLLAMA_SCRIPT:
![ollamascript](https://github.com/user-attachments/assets/1b49ccd5-a1d3-42be-abb4-c8aeb860cb6b)

CUDA:
![NVIDIA_cuda](https://github.com/user-attachments/assets/96d361a6-00c7-4990-aee7-f6ccc6721dd9)

GPU:
![nvidia](https://github.com/user-attachments/assets/7a5c2fbb-f701-4160-93c7-e797079383ef)

PROCESSOR:
12th Gen Intel(R) Core(TM) i7-12850HX, 2100 MHz, 16 Cores, 24 logical Processors

LLAMA3:8B:
![llama3](https://github.com/user-attachments/assets/fff3fd9d-3ae9-4812-b73e-e489d28ea97d)

PHI3:MINI:
![phi3-mini](https://github.com/user-attachments/assets/0642e51d-3c08-4a8b-bb71-a48bf8b850c0)

PHI3:MINI-OLLAMA OUTPUT:
[
![ollamaoutput](https://github.com/user-attachments/assets/e65b2c6c-ec7d-4193-9514-2448de255a17)
![ollamaoutput1](https://github.com/user-attachments/assets/d743ef98-f29d-4476-ac41-43c88804518c)
](url)

LLAMA3:8B-OLLAMA OUTPUT:
![ollamaoutput2](https://github.com/user-attachments/assets/f8080260-cbca-4606-985d-4af7772aff0b)
![ollamaoutput3](https://github.com/user-attachments/assets/74e4f43b-03ef-44fb-91ed-4b303ec868e3)

### OS

Windows

### GPU

Nvidia

### CPU

Intel

### Ollama version

0.3.11

**Comment by rick-github** [comment]
There is no way you are going to get these models to be GPU only.  You have 12G of VRAM on your GPU, llama3 wants 31G and phi3 wants 52G.  This is driven by the context size you have chosen, 128K is consuming all the VRAM leaving little to none for model weights.  You will be able to fit these models on GPU if you reduce context size and also terminate the other programs (ms-teams, SnagitEditor, TextInputHost) that are using the GPU.

**Comment by xiaohan815** [comment]
> There is no way you are going to get these models to be GPU only. You have 12G of VRAM on your GPU, llama3 wants 31G and phi3 wants 52G. This is driven by the context size you have chosen, 128K is consuming all the VRAM leaving little to none for model weights. You will be able to fit these models on GPU if you reduce context size and also terminate the other programs (ms-teams, SnagitEditor, TextInputHost) that are using the GPU.

can you tell me how to reduce the context size?

**Comment by rick-github** [comment]
The default context size is 2048, if the logs indicates it's more than that, then it's either because the model has been configured with a different context size, or because a client has set `num_ctx` in the API call.

If it's a model with a different context size, you can create a new model with a different size:
```
$ cat > Modelfile <<EOF
FROM model-with-large-context
PARAMETER num_ctx 2048
EOF
$ ollama create model-with-2k-context
```

If it's a client setting the size, you need to configure the client to use a smaller context size.  If you supply more information about your client, we can offer more concrete advice on how to adjust the context size.

**Comment by KaloyanGeorgiev99** [comment]
Question was answered, closed the issue.
