### ISSUE TITLE
pulling a big model can freeze the cpu

### ISSUE THREAD

**Issue by remco-pc** [ollama/ollama#6881]
### What is the issue?

i had a cpu lock and when i was trying to type something through ssh the system crashed with cpu locks during a model download, 

### OS

Linux

### CPU

Intel

### Ollama version

ollama version is 0.3.6

**Comment by dhiltgen** [comment]
Can you clarify?  When you say "system crashed" was there a kernel panic resulting in a reboot of the system, or did ollama crash?   Ollama starts multiple threads downloading in parallel which can stress slow network connections (#2006 tracks rate limiting support). This could cause a remote ssh session to slow or hang during downloads, but it should recover after the download completes.

**Comment by remco-pc** [comment]
well i am not so certain now when it comes to my cpu crashes, found some log files which i now monitor, my system says cpu hard lock detected and then hangs.

**Comment by dhiltgen** [comment]
We fixed a bug in the last release where on retries during pull file descriptors were being left open, so on a very slow/flaky network, this may result in open socket exhaustion.   Please give 0.3.13 a try and let us know if that resolves your problem.

**Comment by dhiltgen** [comment]
If you still see the problem on the latest release, let us know and I'll reopen.

**Comment by remco-pc** [comment]
It looks that an invalid cronjob caused this, i am using ollama a little bit and dont experience any crashes at all. Its working fine
