### ISSUE TITLE
Please support FreeBSD

### ISSUE THREAD

**Issue by yurivict** [ollama/ollama#6885]
Hi,

We have the FreeBSD port for ollama version 0.3.6: https://cgit.freebsd.org/ports/tree/misc/ollama
However, later versions fail to compile because of this extensive patch that one user submitted: https://cgit.freebsd.org/ports/tree/misc/ollama/files/patch-FreeBSD-compatibility

FreeBSD is very similar to Linux and in general should just compile except for some bits from the above patch.

Could you please integrate these bits into ollama so that it would build out-of-the-box on FreeBSD?

Thank you,
Yuri

**Comment by lee-b** [comment]
Worth noting that it looks like merging this patch to ollama would add support for not just FreeBSD, but OpenBSD, Dragonfly BSD, and NetBSD too.

**Comment by pdevine** [comment]
Hey guys, thanks for the issue. It is something we've talked about but it's hard to support a lot of different platforms w/ lots of different GPUs.

There is an existing issue which is tracking this: #1102 so let's keep tracking that there. If there's enough demand we'll definitely up the priority.
