### ISSUE TITLE
somethings wrong with parameters

### ISSUE THREAD

**Issue by realkosmoss** [ollama/ollama#6891]
### What is the issue?

/set parameter num_gpu 40
previous update it worked and made my model type faster but now it seems to not

### OS

Windows

### GPU

Nvidia

### CPU

Intel

### Ollama version

0.3.11

**Comment by rick-github** [comment]
[Server logs](https://github.com/ollama/ollama/blob/main/docs/troubleshooting.md#how-to-troubleshoot-issues) will aid in debugging.

**Comment by realkosmoss** [comment]
sorry im retarded might have used another version as it seems fixed after updating again
