### ISSUE TITLE
nexusraven:13b-v2-q2_K EOF

### ISSUE THREAD

**Issue by shuther** [ollama/ollama#6903]
### What is the issue?

either using the API or the CLI, I can't get nexusraven:13b-v2-q2_K to work (other models work fine)
```
ollama pull nexusraven:13b-v2-q2_K
OLLAMA_DEBUG="1" ollama run nexusraven:13b-v2-q2_K
Error: Post "http://127.0.0.1:11434/api/generate": EOF
```

### OS

Linux

### GPU

Nvidia

### CPU

AMD

### Ollama version

0.3.11

**Comment by rick-github** [comment]
[Server logs](https://github.com/ollama/ollama/blob/main/docs/troubleshooting.md#how-to-troubleshoot-issues) will aid in debugging.  Also, for `OLLAMA_DEBUG="1" ` to have an effect, it needs to be [set in the environment of the server](https://github.com/ollama/ollama/blob/main/docs/faq.md#setting-environment-variables-on-linux).

**Comment by rick-github** [comment]
7.4G VRAM in total, search for `layers.offload` in the [server logs](https://github.com/ollama/ollama/blob/main/docs/troubleshooting.md#how-to-troubleshoot-issues).

**Comment by dhiltgen** [comment]
The behavior is a little different, but this may be a variation on #7393
