### ISSUE TITLE
Pixtral 12b

### ISSUE THREAD

**Issue by mrmiket64** [ollama/ollama#6906]
Hello dear Ollama team.

Could you please consider adding Pixtral 12b to the available models?

This seems to be a very capable multimodal model.
![image](https://github.com/user-attachments/assets/f97c32e8-81d1-496c-9017-bbca7567f948)

Thank you

All the best
Miguel

**Comment by rick-github** [comment]
https://github.com/ollama/ollama/issues/6748

**Comment by pdevine** [comment]
Thanks for the issue. We definitely want to add the model. I'll close this as a dupe though.
