### ISSUE TITLE
Error: registry.ollama.ai/library/command-r:latest: EOF

### ISSUE THREAD

**Issue by remco-pc** [ollama/ollama#6920]
### What is the issue?

trying to run/pull this model: command-r

### OS

Linux

### CPU

Intel

### Ollama version

ollama version is 0.3.6

**Comment by Corxo** [comment]
any news on this? I have the same error on Fedora

**Comment by rick-github** [comment]
What is the error message?  What's the output of the following command:
```
curl -D - https://registry.ollama.ai/v2/library/command-r/manifests/latest
```

**Comment by dhiltgen** [comment]
server logs would confirm, but this most likely is the same scenario as #7393 and is caused by a corrupt file in the local store which we aren't handling well.
