### ISSUE TITLE
Ollam build error wih  CUDA on Jetson Orin  (CUDA v12.6)

### ISSUE THREAD

**Issue by jarek7777** [ollama/ollama#6921]
### What is the issue?

Error: llama runner process has terminated: CUDA error: the provided PTX was compiled with an unsupported toolchain.
  current device: 0, in function ggml_cuda_compute_forward at /ollama/llm/llama.cpp/ggml/src/ggml-cuda.cu:2326
  err
/ollama/llm/llama.cpp/ggml/src/ggml-cuda.cu:102: CUDA error

CUDA version 12.6.68

### OS

Linux

### GPU

Nvidia

### CPU

Other

### Ollama version

0.3.11

**Comment by dhiltgen** [comment]
Dup of #2408 - we're working towards supporting this in the official builds, but until then, you can build from source locally and it should work.  The CUDA libraries we link against in our arm builds are for servers with discrete GPUs which unfortunately are incompatible with Jetsons.
