### ISSUE TITLE
Typo in Linux uninstallation docs

### ISSUE THREAD

**Issue by jasondunsmore** [ollama/ollama#6935]
### What is the issue?

At the bottom of docs/linux.md, it should say `sudo rm -r /usr/lib/ollama/` instead of `sudo rm -r /usr/share/ollama`.

### OS

Linux

**Comment by kmerenkov** [comment]
Hey @jasondunsmore ,

This section of FAQ is about uninstalling pulled models, which are actually stored in `/usr/share/ollama` and not `/usr/lib/ollama`

Quote (emphasis is my own):
> Remove **the downloaded models** and Ollama service user and group:
> 
> ```shell
> sudo rm -r /usr/share/ollama
> sudo userdel ollama
> sudo groupdel ollama
> ```

Existing text seems correct to me.

**Comment by dhiltgen** [comment]
The uninstall docs line up with the install script and docs above.  `/usr/share/ollama` is the correct directory to remove
