### ISSUE TITLE
glm4 model return "GGGGGGGGGG"

### ISSUE THREAD

**Issue by shuye-cheung** [ollama/ollama#6936]
### What is the issue?

After deploying the GLM4 model with ollama, the model returns a series of "GGGG".

### OS

Linux

### GPU

Nvidia

### CPU

Intel

### Ollama version

0.3.3

**Comment by dhiltgen** [comment]
I was able to load glm4 on an nvidia GPU on linux and get good results.  Sometimes this sort of giberish response can be the result of loading too many layers leading to subtle memory corruption on the GPU.  Can you share your server log so we can see what might be going wrong?

https://github.com/ollama/ollama/blob/main/docs/troubleshooting.md

**Comment by wszgrcy** [comment]
> ### What is the issue?
> After deploying the GLM4 model with ollama, the model returns a series of "GGGG".
> 
> ### OS
> Linux
> 
> ### GPU
> Nvidia
> 
> ### CPU
> Intel
> 
> ### Ollama version
> 0.3.3

建议更新到最新试一下.我记得llama.cpp最近修过一次glm4的问题.不知道ollama是否合并进来
