### ISSUE TITLE
怎么样才能将ollama打包成应用程序模块，集成到自己的单机软件中

### ISSUE THREAD

**Issue by lymgithub** [ollama/ollama#6944]
在windows中现在安装了ollama，也成功部署了千问大模型，如何将现有的环境打包集成到自己的单机软件中呢

**Comment by gavinwang668** [comment]
为啥要打包呢，直接接口调用不好吗

**Comment by dhiltgen** [comment]
We publish a zip file [ollama-windows-amd64.zip](https://github.com/ollama/ollama/releases/download/v0.3.12/ollama-windows-amd64.zip) with each release.  This include the `ollama` binary along with the dependencies.  It does not include the tray application, so you will need to manage the lifecycle of the server.  See https://github.com/ollama/ollama/blob/main/docs/windows.md#standalone-cli

**Comment by ajmz** [comment]
> We publish a zip file [ollama-windows-amd64.zip](https://github.com/ollama/ollama/releases/download/v0.3.12/ollama-windows-amd64.zip) with each release. This includes the `ollama` binary along with the dependencies. It does not include the tray application, so you will need to manage the lifecycle of the server. See https://github.com/ollama/ollama/blob/main/docs/windows.md#standalone-cli

"ollama-windows-amd64.zip zip file is available containing only the Ollama CLI and GPU library dependencies for Nvidia and AMD"
It means "CPU only" is not supported by ollama-windows-amd64.zip?

**Comment by dhiltgen** [comment]
The windows zip file contains the following runners `cpu_avx2 cuda_v11 cuda_v12 rocm cpu cpu_avx` (3 CPU runners, a v11 and v12 cuda runner, and rocm)

**Comment by ajmz** [comment]
> The windows zip file contains the following runners `cpu_avx2 cuda_v11 cuda_v12 rocm cpu cpu_avx` (3 CPU runners, a v11 and v12 cuda runner, and rocm)

My ollama-windows-amd64.zip, starting to the steps in the screenshot, kept flashing the cursor and couldn't continue. 
What other system configurations should be done in advance?
Thanks.
![2024-09-27_14-58-37](https://github.com/user-attachments/assets/6439606e-5fd9-4a45-9de0-8f1398222488)
