### ISSUE TITLE
nvidia gpu discovery problem in docker container on wsl

### ISSUE THREAD

**Issue by Paramjethwa** [ollama/ollama#6955]
### What is the issue?

Developed a chat app with a function of pulling the model by user directly into streamlit and select the model through dropdown.

i have pulled several model succesfully but when i try to do with large model Eg: Llava ii gives me a Asyncio.timeout.error.

i am using WSL2 (UBUNTU) and running the chat app through docker file 

ERROR: 
[ERROR FILE TIMEOUT ERROR.txt](https://github.com/user-attachments/files/17132576/ERROR.FILE.TIMEOUT.ERROR.txt)

Docker compose File : 
[Docker_compose.txt](https://github.com/user-attachments/files/17132787/Docker_compose.txt)

also, somehow i am not able to use GPU in docker, any solution for that too?

thankyou!

### OS

Windows, Docker, WSL2

### GPU

Nvidia

### CPU

Intel

### Ollama version

0.3.11

**Comment by rick-github** [comment]
Does your `pull_ollama_model_async` function set a timeout?  Because the the error is `TimeoutError` and the request failed after 300 seconds (5m).

For your GPU problem, what's the result of running `nvidia-smi` inside the ollama container (`docker exec -it ollama nvidia-smi`)?

**Comment by Paramjethwa** [comment]
paramubuntu@LAPTOP-AF3LO3NQ:/mnt/c/Users/Param Jethwa/Desktop/local_multimodal_ai$ docker exec -it local_multimodal_ai-ollama-1 nvidia-smi
Wed Sep 25 18:08:33 2024
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 560.35.02              Driver Version: 560.94         CUDA Version: 12.6     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 4050 ...    On  |   00000000:01:00.0 Off |                  N/A |
| N/A   51C    P8              1W /   80W |       0MiB /   6141MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+

+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI        PID   Type   Process name                              GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|  No running processes found                                                             |
+-----------------------------------------------------------------------------------------+

this is what nvidia-sim return inside my container

**Comment by Paramjethwa** [comment]
`paramubuntu@LAPTOP-AF3LO3NQ:/mnt/c/Users/Param Jethwa/Desktop/local_multimodal_ai$ docker exec -it local_multimodal_ai-ollama-1 nvidia-smi
Wed Sep 25 18:08:33 2024
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 560.35.02              Driver Version: 560.94         CUDA Version: 12.6     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 4050 ...    On  |   00000000:01:00.0 Off |                  N/A |
| N/A   51C    P8              1W /   80W |       0MiB /   6141MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+

+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI        PID   Type   Process name                              GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|  No running processes found                                                             |
+-----------------------------------------------------------------------------------------+`

this is what it returns

**Comment by Paramjethwa** [comment]
docker exec -it local_multimodal_ai-ollama-1 nvidia-smi
Wed Sep 25 18:08:33 2024
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 560.35.02              Driver Version: 560.94         CUDA Version: 12.6     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 4050 ...    On  |   00000000:01:00.0 Off |                  N/A |
| N/A   51C    P8              1W /   80W |       0MiB /   6141MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+

+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI        PID   Type   Process name                              GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|  No running processes found                                                             |
+-----------------------------------------------------------------------------------------+

this is what it returns

**Comment by Paramjethwa** [comment]
Does your pull_ollama_model_async function set a timeout? Because the the error is TimeoutError and the request failed after 300 seconds (5m).   

I did fixed it by changing in my docker-compose-yaml

```
environment:
      - OLLAMA_LOAD_TIMEOUT=15m # increase if you get a Timeout Error
```
and 
increase tieout in my utils.py 
async` with aiohttp.ClientSession(timeout=aiohttp.ClientTimeout(total=1800)) as session:

**Comment by dhiltgen** [comment]
It sounds like you fixed the timeout problem.

Are you still having trouble getting it to work on your GPU?  If so, please share a server log so we can see why it fails to discover the GPU.  Setting `-e OLLAMA_DEBUG=1` may also help to increase the amount of logs.
