### ISSUE TITLE
Why doesn't the model know which model it is? 

### ISSUE THREAD

**Issue by robotom** [ollama/ollama#6956]
### What is the issue?

If I load llama 3.1 8B and ask it which model it is, it does not know what LLaMa 3.1 is at all. Sometimes it thinks it's LLama 3 or a 7B param model. Is there any reason for this? How can I be sure what I am running except for whatever `ollama ps` reports? 

(running on 4070 8GB VRAM and i7-13700HX)

### OS

Linux

### GPU

Nvidia

### CPU

Intel

### Ollama version

ollama 3.1:8B

**Comment by rick-github** [comment]
Models don't "know" anything, they're fancy autocomplete based on a large corpus of random information.  You can provide a model with guidance with context or system prompts and it will generate seemingly authoritative statements, but if you want actual facts, you can't rely on a model.

**Comment by robotom** [comment]
> Models don't "know" anything, they're fancy autocomplete based on a large corpus of random information. You can provide a model with guidance with context or system prompts and it will generate seemingly authoritative statements, but if you want actual facts, you can't rely on a model.

Valid, though it is overtly unaware of the existence of LLaMa 3.1 at all. It knows about couscous recipes and Shouldn't it at least have that training data? Seems odd.

**Comment by dhiltgen** [comment]
How the models respond to these sorts of questions is based on how they're trained (or fine tuned) and you'll see varying results from different models.  Try different models out to find the one that best suits your needs.
