### ISSUE TITLE
Please add support for Molmo-7B, new SOTA multimodal model from Allen AI

### ISSUE THREAD

**Issue by robert-mcdermott** [ollama/ollama#6960]
https://huggingface.co/allenai/Molmo-7B-O-0924

**Comment by CAFxX** [comment]
Duplicate of https://github.com/ollama/ollama/issues/6958

**Comment by Owen718** [comment]
Fully agree +1. REALLY NEED.

**Comment by ryanholtschneider2** [comment]
and 7D please

**Comment by sfdkiaei** [comment]
and https://huggingface.co/allenai/Molmo-7B-D-0924 please.

**Comment by MrCabss69** [comment]
+1

There's a guide on how to contribute btw?

**Comment by rick-github** [comment]
dupe https://github.com/ollama/ollama/issues/6958

**Comment by wzhisaso** [comment]
+1
