### ISSUE TITLE
Model cannot be automatically unloading

### ISSUE THREAD

**Issue by Han-Huaqiao** [ollama/ollama#6973]
### What is the issue?

I ran the following model, but keep_alive is at the default value. I haven't requested the above model for more than 10 hours, why is the following model not automatically uninstalled? Why does the `UNTIL` column of `ollama ps` change to the model's start time (how long ago was the model started)? How can I manually uninstall the above model?

``` python
NAME                                    ID              SIZE    PROCESSOR       UNTIL
LongWriter-llama3.1-8b-quantized:latest 1f0dfed4427c    6.7 GB  100% GPU        4 minutes from now
LongWriter-glm4-9b-quantized:latest     e37d70795165    29 GB   100% GPU        19 hours ago
qwen2-tools:7b                          474fd321869c    5.7 GB  100% GPU        19 hours ago
llama3.1:latest                         91ab477bec9d    6.7 GB  100% GPU        19 hours ago
LongWriter-glm4-9b:latest               1d3f6bf6ada8    6.6 GB  100% GPU        19 hours ago
```

### OS

Linux

### GPU

Nvidia

### CPU

Intel

### Ollama version

0.1.10

**Comment by rick-github** [comment]
https://github.com/ollama/ollama/blob/main/docs/faq.md#how-do-i-keep-a-model-loaded-in-memory-or-make-it-unload-immediately

**Comment by dhiltgen** [comment]
Version 0.1.10 is pretty old, and we've fixed a lot of bugs since then.  Please upgrade to the latest version and let us know if you're still having troubles with unload timeouts not being respected.
