### ISSUE TITLE
To configure Ollama to run multiple models simultaneously

### ISSUE THREAD

**Issue by DavidAlpha007** [ollama/ollama#6977]
if the design of Ollama can support calling multiple models simultaneously. For example, can it be used in evaluation scenarios? Thanks for your support.

**Comment by rick-github** [comment]
https://github.com/ollama/ollama/blob/main/docs/faq.md#how-does-ollama-handle-concurrent-requests

**Comment by dhiltgen** [comment]
@DavidAlpha007 if the docs above don't clear it up, please clarify your question on what you're trying to accomplish.
