### ISSUE TITLE
rerank model 

### ISSUE THREAD

**Issue by HARISHSENTHIL** [ollama/ollama#6978]
how can i add HF -  BAAI/bge-reranker-v2-m3  rerank model to ollama  
while trying this approach i am getting architecture error 
can anyone help to resolve this issue

**Comment by rick-github** [comment]
https://github.com/ollama/ollama/issues/3368

**Comment by lixc123** [comment]
Ollama will be more powerful if it supports rerank model

**Comment by ardyli** [comment]
同样希望ollama能提供rerank模型的支持、能提供语音识别模型、语音转文字模型的支持。

We also hope that ollama can provide support for rerank models, speech recognition models, and speech-to-text models.

**Comment by rick-github** [comment]
#7219

**Comment by dengcao** [comment]
ollama似乎不重视用户的反馈问题。过去这么久了还不回复。
