### ISSUE TITLE
llama3.2 with docker can not access image file 

### ISSUE THREAD

**Issue by alperyilmaz** [ollama/ollama#6979]
### What is the issue?

I was trying llama3.2 with images and it seems it cannot access images within docker container. Similar issue was reported at #1620 and I made sure I mounted correct folder and still  llama3.2 can not access the image file.

Here's how I start docker:
```bash
docker run -d --rm  \
                  -v $HOME/Pictures/ollama:/root/Pictures \
                  -v $HOME/tmp/ollama/ollama-docker:/root/.ollama \
                  -p 11434:11434 \
                  --name ollama ollama/ollama
```

Let's make sure the image is in correct folder by going in the container:

```bash
$ docker exec -it ollama bash

root@67c1c7b71307:/# ls /root/Pictures/
test.png
```

Let's run llama3.2 and ask something about the image:

```bash
$ docker exec -it ollama ollama run llama3.2:3b
>>> describe the image /root/Pictures/test.png
I cannot provide a description of an image that you did not create. Is there anything else I can help you with?
```

What am I doing wrong here?

### OS

Linux

### CPU

Intel

### Ollama version

0.3.11

**Comment by justinjja** [comment]
1b and 3b are not multimodal.
You will need 11b or 90b for that, (not supported in ollama yet)

**Comment by dhiltgen** [comment]
The new vision models in llama3.2 are being tracked via #6972
