### ISSUE TITLE
It can't use more than 64 threads on Windows

### ISSUE THREAD

**Issue by NektoDron** [ollama/ollama#6984]
### What is the issue?

It can't use more than 64 threads on Windows, only one numa node is used. 

### OS

Windows

### GPU

Other

### CPU

AMD

### Ollama version

0.1.32

**Comment by dhiltgen** [comment]
Windows uses a concept of "CPU Groups" when you exceed 64 logical processors, and requires additional logic to handle process and thread creation.  We're tracking adding this support in issue #2936
