### ISSUE TITLE
Unrecognized import path "gorgonia.org/vecf64"

### ISSUE THREAD

**Issue by opacicmarko** [ollama/ollama#6990]
### What is the issue?

I tried to build the project from source, but running `go build .` fails with the following errors:
```
go: downloading gorgonia.org/vecf32 v0.9.0
go: downloading gorgonia.org/vecf64 v0.9.0
../../go/pkg/mod/github.com/pdevine/tensor@v0.0.0-20240510204454-f88f4562727c/internal/execution/generic_arith_vv.go:10:2: unrecognized import path "gorgonia.org/vecf32": reading https://gorgonia.org/vecf32?go-get=1: 436 
../../go/pkg/mod/github.com/pdevine/tensor@v0.0.0-20240510204454-f88f4562727c/internal/execution/generic_arith_vv.go:11:2: unrecognized import path "gorgonia.org/vecf64": reading https://gorgonia.org/vecf64?go-get=1: 436
```

It appears the [gorgonia.org](https://gorgonia.org/) domain has expired:

![Screenshot 2024-09-27 at 00-00-09 gorgonia org - gorgonia Resources and Information](https://github.com/user-attachments/assets/4ddea9a8-90c0-4840-9206-0bae19072da8)

### OS

Linux

### GPU

AMD

### CPU

AMD

### Ollama version

0.3.12

**Comment by dhiltgen** [comment]
Sorry you hit that.  It looks like the domain expired, but they have since renewed it.  You should be able to build from source again now.

**Comment by lazka** [comment]
I'm see the same thing again now.

**Comment by lazka** [comment]
Looks like they just fixed it again.

See you on 2027-09-16 when it will expire next :D
