### ISSUE TITLE
pulling manifest Error: 403:

### ISSUE THREAD

**Issue by JitaekJo** [ollama/ollama#6996]
### What is the issue?

Dears

I faced an error when I pull models.
I don't have any idea. Could you please help?

![image](https://github.com/user-attachments/assets/bf8c64ca-2245-4d33-abf6-aa4af2f5df7f)

### OS

Windows

### GPU

Intel

### CPU

Intel

### Ollama version

0.3.12

**Comment by dhiltgen** [comment]
Do you see this every time you try to run or pull a model?   Could you check your system clock to see if it's more than 24h off?

If your system clock is set correctly, and this fails every time, could you share your server log so we can see a little more detail on what might be going wrong?

https://github.com/ollama/ollama/blob/main/docs/troubleshooting.md
