### ISSUE TITLE
CUDA error: device kernel image is invalid - CC 7.5

### ISSUE THREAD

**Issue by nikita228gym** [ollama/ollama#6997]
### What is the issue?

Hello, I would like to apologize for my poor English (I am using a translator from another language). Could you please help me?

I had a problem with Ollama. As always, I tried to run it with the command "Ollama ru llama3.1:8b," but then an error occurred: "Error: llama runner process has terminated: CUDA error: device kernel image is invalid current device: 0, in function ggml_cuda_compute_forward at C:\a\ollama\ollama/llm/llama.cpp/ggml/src/ggml-cuda.cu:2326".

At first, I thought it might be because my version 3.1 was outdated, so I needed to update it. I installed version 3.2, but now, when I try to run 3.2, it gives me this error: Error: lama runner has terminated.

![image](https://github.com/user-attachments/assets/e2a9e730-a9fb-42af-972f-6cc4de4453c2)

my NVIDIA GeForce GTX 1660 Super graphics card
I just talked to Ollama3.1:8b for 2 weeks, and today it stopped working for me 

### OS

Windows

### GPU

Nvidia

### CPU

AMD

### Ollama version

3.1-3.2

**Comment by rick-github** [comment]
This may be a driver mismatch, other people have fixed similar issues by re-installing (https://github.com/deepchem/deepchem/issues/2156#issuecomment-690843354).

Have you updated the Nvidia driver recently?  What's the output of `nvidia-smi`?

**Comment by nikita228gym** [comment]
> This may be a driver mismatch, other people have fixed similar issues by re-installing ([deepchem/deepchem#2156 (comment)](https://github.com/deepchem/deepchem/issues/2156#issuecomment-690843354)).
> 
> Have you updated the Nvidia driver recently? What's the output of `nvidia-smi`?


no, I haven't updated the drivers. That's what this command gives you:
![image](https://github.com/user-attachments/assets/20657561-e30d-4404-b980-fa1dddb81824)

**Comment by dhiltgen** [comment]
I believe your GPU is a Compute Capability 7.5 GPU, which is one of the architectures we compile both cuda v11 and v12 for.

Did this work on an older version of Ollama?  If so, can you try installing that older version and see if it still works?

I believe we should default to the cuda v12 runner for your system.  A possible workaround to try would be forcing it to use the cuda v11 runner instead and maybe that works on your GPU.  Set OLLAMA_LLM_LIBRARY=cuda_v11

https://github.com/ollama/ollama/blob/main/docs/faq.md#how-do-i-configure-ollama-server
