### ISSUE TITLE
Is your llama3.2 models working?

### ISSUE THREAD

**Issue by dhandhalyabhavik** [ollama/ollama#6998]
### What is the issue?

llm_load_tensors: ggml ctx size =    0.13 MiB
llama_model_load: error loading model: done_getting_tensors: wrong number of tensors; expected 255, got 254
llama_load_model_from_file: exception loading model
terminate called after throwing an instance of 'std::runtime_error'
  what():  done_getting_tensors: wrong number of tensors; expected 255, got 254
[GIN] 2024/09/27 - 08:05:40 | 404 |     331.549µs |  10.190.167.113 | POST     "/api/generate"

### OS

Linux

### CPU

Intel

### Ollama version

0.1.34

**Comment by briansan** [comment]
https://github.com/ollama/ollama/pull/6965
