### ISSUE TITLE
Option to Override a Model's Memory Requirements

### ISSUE THREAD

**Issue by dabockster** [ollama/ollama#7013]
I was trying to load the 70b Llama3 model and Ollama says I need 33.6 GB of 30.5 GB ram. I believe this is a safety thing Meta put into the model, so I want to have the ability to override this and attempt to run it on lower amounts of memory. I know this will likely dip into swap/page file space, possibly even causing kernel panics and BSODs. But I still want to make the attempt.

_Computer, disable holodeck safety protocols. Authorization Picard-4-7-Alpha-Tango._

**Comment by dhiltgen** [comment]
We take swap space into consideration.  If you increase the size of your swap file it should try to load it, but expect extremely slow performance if you're paging in/out of swap to fit the model.

If that doesn't work, please share your server log so we can see more details on why it wouldn't load the model and I'll reopen the issue.
