### ISSUE TITLE
Ollama not utilizing Radeon RX 570 GPU - Possible incompatibility?

### ISSUE THREAD

**Issue by X4n71uM** [ollama/ollama#7016]
### What is the issue?

Hi Ollama team and community,

I'm running Ollama (v0.3.12) on Windows 10 and I'm unable to get it to utilize my Radeon RX 570 OC 8GB GPU (With latest Adrenaline Driver).  Ollama seems to be defaulting to CPU, which is significantly slower for my use case.

Here's the relevant part of the log:
"""
time=2024-09-28T02:43:51.626+02:00 level=INFO source=gpu.go:199 msg="looking for compatible GPUs"
time=2024-09-28T02:43:51.744+02:00 level=INFO source=gpu.go:347 msg="no compatible GPUs were discovered"
"""

Is there any way to force GPU usage, perhaps through a command-line flag or configuration setting?  Is my RX 570 simply too old or unsupported by Ollama's current ROCm implementation?

I'd appreciate any guidance on how to enable GPU usage or confirmation if my GPU is indeed incompatible.  Even if my GPU isn't ideal for large models, any performance boost would be welcome.

Thanks in advance!

### OS

Windows

### GPU

AMD

### CPU

AMD

### Ollama version

v0.3.12

**Comment by guxanan** [comment]
ROCM isn't really supported on Polaris, you might want to look out for #5059 since that adds Vulkan, which should work.

**Comment by dhiltgen** [comment]
Older Radeon support is being tracked via #2453

**Comment by juwonpee** [comment]
Wouldnt vulkan still be supported though?
