### ISSUE TITLE
AMD Radeon Pro 5700 XT 16GB GPU Support

### ISSUE THREAD

**Issue by tomasznazarenko** [ollama/ollama#7018]
Hi,

Would it be possible to add support for AMD Radeon Pro 5700 XT 16GB VRAM GPU?

System: macOS Sequoia
CPU: 3,8 GHz 8-Core Intel Core i7
RAM: 128GB

Currently when using such hardware Ollama utilizes only CPU.
The system is from 2020, but it is still a capable machine. 

Best,

**Comment by dhiltgen** [comment]
We're tracking MacOS x86 Radeon GPU support with #1016.
