### ISSUE TITLE
Why are all pixtral models removed from the ollama model library?

### ISSUE THREAD

**Issue by CRCODE22** [ollama/ollama#7019]
https://ollama.com/library?q=pixtral&sort=newest

**Comment by rick-github** [comment]
Pixtral hasn't been added yet.  https://github.com/ollama/ollama/issues/6906

**Comment by CRCODE22** [comment]
> Pixtral hasn't been added yet. #6906

1B and 3B had been added some time ago and they had a status that they would add the vision models soon now they are all gone.

**Comment by rick-github** [comment]
Pixtral doesn't have 1B and 3B variants, you are thinking of [llama3.2](https://ollama.com/library/llama3.2).

**Comment by CRCODE22** [comment]
> Pixtral doesn't have 1B and 3B variants, you are thinking of [llama3.2](https://ollama.com/library/llama3.2).

You are correct I confused Pixtral with Llama3.2 both have vision capabilities.

https://ollama.com/blog/llama3.2

Thank you for letting me know.
