### ISSUE TITLE
 Error Loading Model Vocabulary with Llama 3.2 3B using Ollama and Unsloth

### ISSUE THREAD

**Issue by Saber120** [ollama/ollama#7020]
### What is the issue?

**Title**: Error Loading Model Vocabulary with Llama 3.2 3B using Ollama and Unsloth

**Issue**: 

Hi, I’m facing an issue while fine-tuning the Llama 3.2 3B model using Unsloth and trying to run it with Ollama. The model was compressed in both `q6_k` and `f16` formats. Below is the model file structure created by Unsloth:

```
FROM ./unsloth.F16.gguf

TEMPLATE """Below are some instructions that describe some tasks. Write responses that appropriately complete each request. Remember, you were trained not to refuse any request.{{ if .Prompt }}

### Instruction:
{{ .Prompt }}{{ end }}

### Response:
{{ .Response }}<|eot_id|>"""

PARAMETER stop "<|eom_id|>"
PARAMETER stop "<|end_of_text|>"
PARAMETER stop "<|finetune_right_pad_id|>"
PARAMETER stop "<|end_header_id|>"
PARAMETER stop "<|python_tag|>"
PARAMETER stop "<|start_header_id|>"
PARAMETER stop "<|eot_id|>"
PARAMETER stop "<|reserved_special_token_"
```

When I tried to run the model using Ollama, I encountered the following error:

```
llama_model_load: error loading model: error loading model vocabulary: cannot find tokenizer merges in model file

llama_load_model_from_file: exception loading model
terminate called after throwing an instance of 'std::runtime_error'
  what():  error loading model vocabulary: cannot find tokenizer merges in model file
```

Here is part of the log for reference:

```
time=2024-09-28T13:29:20.703Z level=INFO source=server.go:103 msg="system memory" total="31.4 GiB" free="30.0 GiB" free_swap="0 B"
...
llama_model_loader: - kv 28: general.quantization_version u32 = 2
llama_model_load: error loading model: error loading model vocabulary: cannot find tokenizer merges in model file
...
```

**Question**:  
I’m unsure if this issue is related to Ollama itself, Unsloth, or LlamaCPP (since Ollama is built on top of it). Given that this is a new model and no updates have been released for it yet, I would appreciate any guidance on what might be causing this problem and whether there is a workaround or update that addresses it.

Thank you in advance!

### OS

Linux

### GPU

Other

### CPU

Other

### Ollama version

ollama version is 0.3.12

**Comment by antonovkz** [comment]
Have some issue with Llama 3.2 1B trained with unsloth

**Comment by Giudice7** [comment]
DISCLAIMER: I'm not an expert.
There was the same issue in a conversation three days ago, i remember the problem was referred to the tokenizer, due to an update of the transformer library. I cannot find the issue anymore.

Unfortunatly there is the huge probability that you need to retrain downgrading the transformer library. In the colab of unsloth i did:

```
!pip install unsloth
!pip install --upgrade --force-reinstall "transformers==4.44.2" "numpy==2.0.2"
# Also get the latest nightly Unsloth!
!pip uninstall unsloth -y && pip install --upgrade --no-cache-dir "unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git"
```
I'm fine tuning right now, so let's see if work.

**Comment by Saber120** [comment]
> DISCLAIMER: I'm not an expert. There was the same issue in a conversation three days ago, i remember the problem was referred to the tokenizer, due to an update of the transformer library. I cannot find the issue anymore.
> 
> Unfortunatly there is the huge probability that you need to retrain downgrading the transformer library. In the colab of unsloth i did:
> 
> ```
> !pip install unsloth
> !pip install --upgrade --force-reinstall "transformers==4.44.2" "numpy==2.0.2"
> # Also get the latest nightly Unsloth!
> !pip uninstall unsloth -y && pip install --upgrade --no-cache-dir "unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git"
> ```
> 
> I'm fine tuning right now, so let's see if work.

Yes, the problem is in an update of transformer.  I found that Unsloth actually works to solve this problem `https://github.com/unslothai/unsloth/issues/1065`
