### ISSUE TITLE
Can we have a native integrated gpu support ?

### ISSUE THREAD

**Issue by user7z** [ollama/ollama#7022]
Its would be great to have ollama native support for igpus , for laptop use , it well free the cpu threads for other tasks , the igpu is that little device that we dont make use of it , despite performance , one wouls have his cpu for other tasks , llm-cpp & oneapi is not the solution in my opinion , specially for igpus

**Comment by dhiltgen** [comment]
You didn't mention which brand of iGPU you're looking for support, but since you mentioned oneapi, I'll assume Intel. We're tracking Intel iGPU support via #3113 although #2033 might be relevant as well.

**Comment by user7z** [comment]
@dhiltgen it boils down to ipex-llm , that why i said "natively" , because ipex-llm dont seem to be it , lack of compatibility is the primarlly reason , even with what suround it , from a technical perspective what would be needed to add a native igpu support  , i think ipex-llm is just a temproary solution
