### ISSUE TITLE
Error creating the manifest

### ISSUE THREAD

**Issue by seblessa** [ollama/ollama#7036]
### What is the issue?

Hello! I'm trying to create a custom model in ollama from a gguf file. 

I'm using the Modelfile from the example in the ReadME:

```
~/example$ cat Modelfile 
FROM ./llama.gguf
```

When using the create command the ouput seems fine and the model is created. 

````
~/example$ ollama create example -f Modelfile
transferring model data 100% 
using existing layer sha256:91bb99d2cc00b169f1a22f6e4ea87532faa5a8399d9496489793f582b5346f00 
using autodetected template llama3-instruct 
using existing layer sha256:56bb8bd477a519ffa694fc449c2413c6f0e1d3b1c88fa7e3c9d88d3ae49d4dcb 
using existing layer sha256:b438d145ccf05e8d943b530a43a066311750eb4d428c3b1bdff107454a27cab4 
writing manifest 
success 
````

Everything seems fine:

```
~/example$ ollama list
NAME              ID              SIZE      MODIFIED      
example:latest    f80b565a0320    48 MB     4 minutes ago    
llama3.1:70b      c0df3564cfe8    39 GB     13 days ago      
llama3.1:8b       42182419e950    4.7 GB    2 weeks ago   
```

But when I try to run it:

```
~/example$ ollama run example
pulling manifest 
Error: pull model manifest: file does not exist
```

And when I list the dir the manifest is really not there.

### OS

Linux

### GPU

Nvidia

### CPU

Intel

### Ollama version

0.3.12

**Comment by rick-github** [comment]
48M is really small for a llama-based model.  Where did you get the file from?  It might be an adapter, in which case you need to include the base model in the Modelfile:
```
FROM path/to/models/base-llama.gguf
ADAPTER ./llama.gguf
```
What does `ollama show example` display?
