### ISSUE TITLE
ollama app not running

### ISSUE THREAD

**Issue by horyekhunley** [ollama/ollama#7037]
### What is the issue?

normally when i install ollama, it just works as is, i dont usually have to 'ollama serve'. but now i have to do that if i want to use ollama, if i don't i get the error:
`Error: could not connect to ollama app, is it running?`

### OS

Linux

### GPU

Nvidia

### CPU

AMD

### Ollama version

0.3.12

**Comment by rick-github** [comment]
[Server logs](https://github.com/ollama/ollama/blob/main/docs/troubleshooting.md#how-to-troubleshoot-issues) may aid in debugging.

**Comment by dhiltgen** [comment]
@horyekhunley if you're still having the problem, please share your server log so we can see what might be the problem and I'll reopen the issue.
