### ISSUE TITLE
Support detailed logs for each request

### ISSUE THREAD

**Issue by fzyzcjy** [ollama/ollama#7044]
Hi thanks for the library! In order to see what happens, it would be great to see detailed logs for each request. For example, not only the real string send into LLM, but also temperature, top_p, etc. It would be even greater if these could be output to a separate log or tracing service etc.

**Comment by LakshmanKishore** [comment]
When we set OLLAMA_DEBUG="1", we can see the question sent to the LLM, but the response from the LLM is not displayed in the logs. It would be helpful to include the LLM's response in the logs as well.

**Comment by fzyzcjy** [comment]
Totally agree. Also showing the parameters would be great.

**Comment by rick-github** [comment]
https://github.com/ollama/ollama/issues/6565
