### ISSUE TITLE
An option to record conversations via terminal

### ISSUE THREAD

**Issue by ronxldwilson** [ollama/ollama#7045]
Would like to request for the addition of feature which allows the user to record the conversations happening with the model in the file system.

Example 
> ollama run <model_name> record 

Giving the record argument, it would record all the chats that are happening in the session in a text file which can be useful to go back to previous conversations with the model.

Example 
> ollama run <model_name> record "<filename>.txt"

this could allow to record with a certain name or in certain path.

Output 
> <date and time>.txt 

This conversations can be stored in a certain predefined path. Along with any logs and error messages that come up can be stored in the same file.

Recording of the conversation chat could also allow to browse through the old conversations.

> ollama browse 

this can allow to revisit the old chats in a sequential order and make the work of browsing through old chats and possibly resume a chat from the previous session.

**Comment by pdevine** [comment]
Hey @ronxldwilson you can do this today with `/save <session>`. You can then use `ollama run <session>` to pick up where you left off. Use `ollama ls` to see the sessions just like you would with any model.

I'll go ahead and close this, but feel free to keep commenting if this doesn't solve your problem.

**Comment by ronxldwilson** [comment]
Hi @pdevine, that looks to solve the requirement. Thanks for helping with this!
