### ISSUE TITLE
Undefined variable in this code file: convert/tokenizer_spm.go

### ISSUE THREAD

**Issue by vignesh1507** [ollama/ollama#7056]
### What is the issue?

The code doesn't currently define tokenTypeUserDefined, which will cause a compilation error.

How to fix?
Add a constant declaration to fix the issue, for example:

`const tokenTypeUserDefined = int32(1)
`

### OS

macOS

### GPU

Apple

### CPU

Apple

### Ollama version

3.1

**Comment by dhiltgen** [comment]
It's defined here - https://github.com/ollama/ollama/blob/main/convert/tokenizer.go#L22

Can you share the compiler error you're seeing?

**Comment by vignesh1507** [comment]
Thx for pointing it out, i thought the variable isn't defined so it might throw a compiler error(hypothetical).
