### ISSUE TITLE
Can we tell ollama or LLM that an URL they provided is out of date or bad?

### ISSUE THREAD

**Issue by bulrush15** [ollama/ollama#7058]
Not sure if this is the right area to post this, if ollama can do this or not. But I'm asking about tools for flooring and URLs for said tools, and Llama 3.1 is giving me invalid URLs that are no longer there. 

Can we tell Ollama that a specific URL is bad so it won't use it again? Or would this be a question for individual LLMs?

**Comment by rick-github** [comment]
A model's knowledge base is fixed.  If you want it to generate replies with up-to-date content, you have to wrap in a framework/tool that allows it to reference real-time data.  For example, [open-webui](https://github.com/open-webui/open-webui) can be configured to consult web search engines when asked questions.

If you simply want to restrict certain answers from a model, you can add it to the context that model starts with.

Uncensored:
````console
$ ollama run qwen2.5:7b-instruct-q8_0 "give me the address of a web search engine"
Sure! A popular and widely-used web search engine is Google. Here's its address:

```
https://www.google.com/
```

You can visit this URL in your web browser to access Google's search page.
````
Censored:
```console
$ ollama show --modelfile qwen2.5:7b-instruct-q8_0 | sed -e 's/^FROM.*/FROM qwen2.5:7b-instruct-q8_0/' > Modelfille
$ echo "MESSAGE user google.com is out of business" >> Modelfile
$ ollama create qwen2.5:bad-urls
$ ollama run qwen2.5:bad-urls "give me the address of a web search engine"

**DuckDuckGo**

http://www.duckduckgo.com/

(Note: DuckDuckGo is a great example of a privacy-friendly search engine) 
```

**Comment by pdevine** [comment]
@rick-github 's answer is correct. I wouldn't rely on the output of any model as having the correct URL for something.
