### ISSUE TITLE
Support to loading multiple LLM models on the same GPU

### ISSUE THREAD

**Issue by DenisMontes** [ollama/ollama#7069]
Hello! Is it possible to include support for loading multiple LLM models on the same GPU?

I'm trying to create an AI team that will automate tasks, but currently I can only run one inference at a time. I'm using small models around 700MB in size on a GPU with 8GB of VRAM. I know I need space for context window beyond the neural network layers. So if it's possible to run two models simultaneously in this configuration, I'll double my performance without needing to buy another GPU that would require a larger power supply and potentially a new motherboard and case." 

I have some ideas on how to implement this, and I'm willing to discuss a more in-depth way to make this feature possible.

**Comment by rick-github** [comment]
Ollama already [does this](https://github.com/ollama/ollama/blob/main/docs/faq.md#how-does-ollama-handle-concurrent-requests).  Use `ollama ps` to see which models are loaded.  However, it does not support loading the same model more than once.

**Comment by pdevine** [comment]
Hey @DenisMontes , check out this [link](https://github.com/ollama/ollama/blob/main/docs/faq.md#how-does-ollama-handle-concurrent-requests). Given your limited VRAM you may need to set `OLLAMA_NUM_PARALLEL` to make this work.
