### ISSUE TITLE
install fail on void linux distro

### ISSUE THREAD

**Issue by malv-c** [ollama/ollama#7076]
### What is the issue?

% curl -fsSL https://ollama.com/install.sh | sh
>>> Installing ollama to /usr/local
Password: 
>>> Downloading Linux amd64 bundle
######################################################################## 100.0%
>>> Downloading Linux ROCm amd64 bundle
######################################################################## 100.0%
>>> The Ollama API is now available at 127.0.0.1:11434.
>>> Install complete. Run "ollama" from the command line.
>>> AMD GPU ready.
>>> The Ollama API is now available at 127.0.0.1:11434.
>>> Install complete. Run "ollama" from the command line.
/tmp
% ollama 
bash: /usr/local/bin/ollama: cannot execute: required file not found

### OS

Linux

### CPU

AMD

### Ollama version

none yet

**Comment by rick-github** [comment]
Output of:
```
uname -a
command -v ollama
ls -l /usr/local/bin/ollama
file /usr/local/bin/ollama
ldd /usr/local/bin/ollama
```

**Comment by malv-c** [comment]
% . o
Linux xx 6.6.52_1 #1 SMP PREEMPT_DYNAMIC Sat Sep 21 15:47:36 UTC 2024
x86_64 GNU/Linux
/usr/local/bin/ollama
-rwxr-xr-x 1 root root 1072413336 Sep 25 08:40 /usr/local/bin/ollama
/usr/local/bin/ollama: ELF 64-bit LSB executable, x86-64, version 1 (SYSV),
dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2,
BuildID[sha1]=dac65b76638677a1a2d1f98e67b0fe5023723e45, for GNU/Linux
2.6.32, stripped
/lib64/ld-linux-x86-64.so.2 (0x7ff70baea000)
Error loading shared library libresolv.so.2: No such file or directory
(needed by /usr/local/bin/ollama)
libpthread.so.0 => /lib64/ld-linux-x86-64.so.2 (0x7ff70baea000)
libstdc++.so.6 => /lib/libstdc++.so.6 (0x7ff70b600000)
librt.so.1 => /lib64/ld-linux-x86-64.so.2 (0x7ff70baea000)
libdl.so.2 => /lib64/ld-linux-x86-64.so.2 (0x7ff70baea000)
libm.so.6 => /lib64/ld-linux-x86-64.so.2 (0x7ff70baea000)
libgcc_s.so.1 => /lib/libgcc_s.so.1 (0x7ff70bac7000)
libc.so.6 => /lib64/ld-linux-x86-64.so.2 (0x7ff70baea000)
Error relocating /usr/local/bin/ollama: __isnanf: symbol not found
Error relocating /usr/local/bin/ollama: backtrace: symbol not found
Error relocating /usr/local/bin/ollama: __res_search: symbol not found
Error relocating /usr/local/bin/ollama: __isinff: symbol not found
Error relocating /usr/local/bin/ollama: __strdup: symbol not found
Error relocating /usr/local/bin/ollama: backtrace_symbols_fd: symbol not
found
Error relocating /usr/local/bin/ollama: __sched_cpualloc: symbol not found
Error relocating /usr/local/bin/ollama: __sched_cpufree: symbol not found%
. o
Linux xx 6.6.52_1 #1 SMP PREEMPT_DYNAMIC Sat Sep 21 15:47:36 UTC 2024
x86_64 GNU/Linux
/usr/local/bin/ollama
-rwxr-xr-x 1 root root 1072413336 Sep 25 08:40 /usr/local/bin/ollama
/usr/local/bin/ollama: ELF 64-bit LSB executable, x86-64, version 1 (SYSV),
dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2,
BuildID[sha1]=dac65b76638677a1a2d1f98e67b0fe5023723e45, for GNU/Linux
2.6.32, stripped
/lib64/ld-linux-x86-64.so.2 (0x7ff70baea000)
Error loading shared library libresolv.so.2: No such file or directory
(needed by /usr/local/bin/ollama)
libpthread.so.0 => /lib64/ld-linux-x86-64.so.2 (0x7ff70baea000)
libstdc++.so.6 => /lib/libstdc++.so.6 (0x7ff70b600000)
librt.so.1 => /lib64/ld-linux-x86-64.so.2 (0x7ff70baea000)
libdl.so.2 => /lib64/ld-linux-x86-64.so.2 (0x7ff70baea000)
libm.so.6 => /lib64/ld-linux-x86-64.so.2 (0x7ff70baea000)
libgcc_s.so.1 => /lib/libgcc_s.so.1 (0x7ff70bac7000)
libc.so.6 => /lib64/ld-linux-x86-64.so.2 (0x7ff70baea000)
Error relocating /usr/local/bin/ollama: __isnanf: symbol not found
Error relocating /usr/local/bin/ollama: backtrace: symbol not found
Error relocating /usr/local/bin/ollama: __res_search: symbol not found
Error relocating /usr/local/bin/ollama: __isinff: symbol not found
Error relocating /usr/local/bin/ollama: __strdup: symbol not found
Error relocating /usr/local/bin/ollama: backtrace_symbols_fd: symbol not
found
Error relocating /usr/local/bin/ollama: __sched_cpualloc: symbol not found
Error relocating /usr/local/bin/ollama: __sched_cpufree: symbol not found%
. o
Linux xx 6.6.52_1 #1 SMP PREEMPT_DYNAMIC Sat Sep 21 15:47:36 UTC 2024
x86_64 GNU/Linux
/usr/local/bin/ollama
-rwxr-xr-x 1 root root 1072413336 Sep 25 08:40 /usr/local/bin/ollama
/usr/local/bin/ollama: ELF 64-bit LSB executable, x86-64, version 1 (SYSV),
dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2,
BuildID[sha1]=dac65b76638677a1a2d1f98e67b0fe5023723e45, for GNU/Linux
2.6.32, stripped
/lib64/ld-linux-x86-64.so.2 (0x7ff70baea000)
Error loading shared library libresolv.so.2: No such file or directory
(needed by /usr/local/bin/ollama)
libpthread.so.0 => /lib64/ld-linux-x86-64.so.2 (0x7ff70baea000)
libstdc++.so.6 => /lib/libstdc++.so.6 (0x7ff70b600000)
librt.so.1 => /lib64/ld-linux-x86-64.so.2 (0x7ff70baea000)
libdl.so.2 => /lib64/ld-linux-x86-64.so.2 (0x7ff70baea000)
libm.so.6 => /lib64/ld-linux-x86-64.so.2 (0x7ff70baea000)
libgcc_s.so.1 => /lib/libgcc_s.so.1 (0x7ff70bac7000)
libc.so.6 => /lib64/ld-linux-x86-64.so.2 (0x7ff70baea000)
Error relocating /usr/local/bin/ollama: __isnanf: symbol not found
Error relocating /usr/local/bin/ollama: backtrace: symbol not found
Error relocating /usr/local/bin/ollama: __res_search: symbol not found
Error relocating /usr/local/bin/ollama: __isinff: symbol not found
Error relocating /usr/local/bin/ollama: __strdup: symbol not found
Error relocating /usr/local/bin/ollama: backtrace_symbols_fd: symbol not
found
Error relocating /usr/local/bin/ollama: __sched_cpualloc: symbol not found
Error relocating /usr/local/bin/ollama: __sched_cpufree: symbol not found
oops i run a musl os sorry
i will try to build from git

**Comment by dhiltgen** [comment]
What distro are you running.  Is it Alpine by any chance?  If so, unfortunately it's unlikely you'll get Ollama to work on Alpine given the incompatible libc implementations between glibc and musl.

**Comment by malv-c** [comment]
hi daniel
it is void linux
we will see...

**Comment by dhiltgen** [comment]
We compile our official binaries against a relatively old base glibc version to try to maximize compatibility, but it appears void linux doesn't have a glibc that has the symbols we're expecting.

I would suggest trying to build from source which may be viable on void linux given it appears Go is supported - https://github.com/ollama/ollama/blob/main/docs/development.md

**Comment by malv-c** [comment]
go.mod 1.22.5  -> 1.23
/tmp/ollama
% go generate ./...
+ set -o pipefail
+ compress_pids=
+ echo 'Starting linux generate script'
Starting linux generate script
+ '[' -z '' ']'
+ '[' -x /usr/local/cuda/bin/nvcc ']'
++ command -v nvcc
+ export CUDACXX=
+ CUDACXX=
+ COMMON_CMAKE_DEFS='-DCMAKE_SKIP_RPATH=on -DBUILD_SHARED_LIBS=on
-DCMAKE_POSITION_INDEPENDENT_CODE=on -DGGML_NATIVE=off -DGGML_AVX=on
-DGGML_AVX2=off -DGGML_AVX512=off -DGGML_FMA=off -DGGML_F16C=off
-DGGML_OPENMP=off'
++ dirname ./gen_linux.sh
+ source ./gen_common.sh
+ init_vars
+ case "${GOARCH}" in
+ ARCH=x86_64
+ LLAMACPP_DIR=../llama.cpp
+ CMAKE_DEFS=-DCMAKE_SKIP_RPATH=on
+ CMAKE_TARGETS='--target ollama_llama_server'
+ echo ''
+ grep -- -g
+ CMAKE_DEFS='-DCMAKE_BUILD_TYPE=Release -DLLAMA_SERVER_VERBOSE=off
-DCMAKE_SKIP_RPATH=on'
+ case $(uname -s) in
++ uname -s
+ LIB_EXT=so
+ WHOLE_ARCHIVE=-Wl,--whole-archive
+ NO_WHOLE_ARCHIVE=-Wl,--no-whole-archive
+ GCC_ARCH=
+ DIST_BASE=../../dist/linux-amd64/
+ PAYLOAD_BASE=../../build/linux/amd64
+ '[' -z '' ']'
+ CMAKE_CUDA_ARCHITECTURES='50;52;61;70;75;80'
++ command -v pigz
++ echo gzip
+ GZIP=gzip
+ RUNNER_BASE=../../dist/linux-amd64//lib/ollama/runners
+ git_module_setup
+ '[' -n '' ']'
+ '[' -d ../llama.cpp/gguf ']'
+ git submodule init
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
llm/generate/generate_linux.go:3: running "bash": exit status 128
/tmp/ollama
what to change and where ???

Le jeu. 3 oct. 2024 à 17:43, Daniel Hiltgen ***@***.***> a
écrit :

**Comment by dhiltgen** [comment]
I believe that failure comes from an old version of git not handling submodules correctly.  Try to upgrade to a newer git version.

**Comment by malv-c** [comment]
recloned and same error ......

Le sam. 5 oct. 2024 à 17:29, Daniel Hiltgen ***@***.***> a
écrit :

**Comment by rick-github** [comment]
FWIW, I was able to build ollama in a void container (CPU only).
```console
$ docker pull ghcr.io/void-linux/void-musl-full
$ docker run --rm -it --name void --entrypoint sh ghcr.io/void-linux/void-musl-full
# xbps-install -Sy bash git go gcc cmake make
# git clone https://github.com/ollama/ollama.git && cd ollama
# go generate ./...
# go build .
# ./ollama serve &
# ./ollama run qwen2:0.5b hello
Hello! How can I assist you today? Are you looking for information, advice or assistance with something specific? If so, what would you like to know or find help with?
```

**Comment by malv-c** [comment]
it was a bad cp
now
+ echo 'Finished compression'
Finished compression
++ cd ../../build/linux/amd64
++ echo cpu cpu_avx cpu_avx2 placeholder
+ echo 'go generate completed.  LLM runners: cpu cpu_avx cpu_avx2
placeholder'
go generate completed.  LLM runners: cpu cpu_avx cpu_avx2 placeholder
/tmp/ollama
% go build .
cmd/interactive.go:4:2: package cmp is not in GOROOT (/usr/src/cmp)
envconfig/config.go:5:2: package log/slog is not in GOROOT
(/usr/src/log/slog)
server/download.go:11:2: package math/rand/v2 is not in GOROOT
(/usr/src/math/rand/v2)
gpu/amd_linux.go:13:2: package slices is not in GOROOT (/usr/src/slices)
/tmp/ollama
%

**Comment by malv-c** [comment]
finally i solved the problem
it was a bad go install
sstrip -z ollama and it loose almost 25 % weight
thanks all
