### ISSUE TITLE
I would like to able to download, extract and run Ollama on an Intel GPU

### ISSUE THREAD

**Issue by xiangyang-95** [ollama/ollama#7087]
In order to use Ollama easily on Intel discrete GPU, I would like to able to download the ollama binary that is built with Intel OneAPI SYCL runtime directly.

Example:
```
curl -L https://ollama.com/download/ollama-linux-amd64-sycl.tgz -o ollama-linux-amd64-sycl.tgz
sudo tar -C /usr -xzf ollama-linux-amd64-sycl.tgz
```

I am willing to contribute this feature if needed.

**Comment by dhiltgen** [comment]
Intel discrete GPUs is being tracked via #1590
