### ISSUE TITLE
Add CLI Support for Setting Temperature in ollama run

### ISSUE THREAD

**Issue by Bakht-Ullah** [ollama/ollama#7088]
I would like to request the ability to set the temperature parameter directly from the command line when running models using the ollama run command.

**Comment by rick-github** [comment]
https://github.com/ollama/ollama/issues/5362

**Comment by pdevine** [comment]
Thanks for the issue @Bakht-Ullah . You can use `/set parameter` in the CLI. For a list of parameters you can set you can type `/set parameter`.
