### ISSUE TITLE
ollama_models path not working any longer

### ISSUE THREAD

**Issue by Molnfront** [ollama/ollama#7090]
### What is the issue?

Last week I added ollama_models path to my env file in my Mac. Olama picked up the settings and saved the models to my path (external SSD).  Now yesterday when I picked gemma 2 and got it downloaded it ignored the path and downloaded it to .ollama. 

### OS

macOS

### GPU

Apple

### CPU

Apple

### Ollama version

0.3.12

**Comment by rick-github** [comment]
[Server logs](https://github.com/ollama/ollama/blob/main/docs/troubleshooting.md#how-to-troubleshoot-issues) will aid in debugging, particularly the line that contains `OLLAMA_MODELS`.  It's possible that another server is running, so the end of the server log showing recent activity to validate the server would also be useful.

**Comment by Molnfront** [comment]
But both servers should use the same settings from the env.

**Comment by JavierCCC** [comment]
Not sure what is happening. But it looks like a big change. My code is also not working anymore.

**Comment by rick-github** [comment]
[Server logs](https://github.com/ollama/ollama/blob/main/docs/troubleshooting.md#how-to-troubleshoot-issues) will aid in debugging.
