### ISSUE TITLE
please give support  gpu amd randeon 5500 xt

### ISSUE THREAD

**Issue by james007tia** [ollama/ollama#7092]
Please give support  gpu amd randeon 5500 xt

**Comment by dhiltgen** [comment]
Can you clarify what OS?  

The XT 5500 is a gfx1012 which is supported by ROCm on Linux, but not windows.

**Comment by RapolasRimeika** [comment]
Running Ollama on Mac OS Sequoia 15.1
iMac 2020 with Intel Core i7 and AMD Radeon Pro 5500 XT 8GB
Ollama only uses the CPU.
Do I need to set up Linux to make use of it?

**Comment by dhiltgen** [comment]
Yes, this GPU is supported by our linux build.  Apple AMD GPU support is tracked via issue #1016

**Comment by pablojrojas** [comment]
Is there any attempt to support this GPU in Windows for Ollama?

**Comment by mdsadiqueinam** [comment]
Somebody please help I don't have much knowledge in AI and its driver, I need help to enable gpu for ollama

I have ubuntu 24.04 
CPU ryzen 5600h
GPU radeon RX5500M
Memory 16gb
