### ISSUE TITLE
Update /api/show endpoint to return a boolean describing if the model supports FIM

### ISSUE THREAD

**Issue by tomasz-stefaniak** [ollama/ollama#7106]
Hi,

We support Ollama as a [model provider in Continue.dev](https://docs.continue.dev/customize/model-providers/ollama) and have recently added FIM (Fill-in-the-Middle) support. Currently, there is no API we are aware of that can be used to determine if a model supports FIM, so we guess its capabilities by checking for a ".Suffix" variable in the template returned from Ollama's `/api/show` endpoint.

To improve accuracy and stability, we would appreciate receiving this information directly as a boolean value from the `/api/show` endpoint. This would allow us to integrate FIM support more reliably and provide better service to Continue users.

Context: [GitHub Link](https://github.com/continuedev/continue/pull/2452/files#diff-3f4bdaca0060eb741057719bcc865486ab770e4ea1659b317f77235adc887c37R81)

**Comment by rick-github** [comment]
https://github.com/ollama/ollama/issues/5794

**Comment by rick-github** [comment]
closing as dupe
