### ISSUE TITLE
stuck in loading llm

### ISSUE THREAD

**Issue by mohamadhasan-zeinali** [ollama/ollama#7118]
### What is the issue?

When you try to run llama3.2:3b, you get an error message:
Error: timed out waiting for llama runner to start 
and stuck in loading. 
codellama:7b-code-q6_K	e3d8d04437e4	5.5 GB	2 months ago
llama3:latest	a6990ed6be41	4.7 GB	4 months ago
llama3.2:1b	baf6a787fdff	1.3 GB	14 hours ago
llama3.2:3b	a80c4f17acd5	2.0 GB	15 hours ago
nomic-embed-text:latest	0a109f422b47	274 MB	4 months ago
phi3:latest	2ac528a36156	2.3 GB	4 months ago 
this is list of my llm. 

### OS

Linux

### GPU

Nvidia

### CPU

Intel

### Ollama version

0.1.34

**Comment by rick-github** [comment]
llama3.2 needs at least ollama version 0.3.1.  If the problem persists after upgrading, [server logs](https://github.com/ollama/ollama/blob/main/docs/troubleshooting.md#how-to-troubleshoot-issues) will aid in debugging.
