### ISSUE TITLE
 Difference in Function Call Support between Ollama and Unsloth for Llama 3.2

### ISSUE THREAD

**Issue by Saber120** [ollama/ollama#7127]
### What is the issue?

Hi,

I’ve fine-tune a Llama 3.2 model using Unsloth, and when I try to enable function calling with ollama, I receive a message indicating that the model does not support function calls. However, when I download the same Llama 3.2 model directly from Ollama, function calls work without any issues.

Could  clarify why the same model behaves differently in terms of function call support when trained with Unsloth versus when downloaded from Ollama? Is there something specific in the way Ollama’s version of the model is configured that enables function call support, or are there certain settings I need to adjust in the Unsloth training process to enable this feature?

Thanks in advance for your help!

### OS

Linux

### GPU

Other

### CPU

Other

### Ollama version

0.3.12

**Comment by rick-github** [comment]
Your finetuned model doesn't have a template that indicates it supports tools.  Compare `ollama show --template llama3.2` with `ollama show --template llama3.2-finetuned`.  It's probably possible to substitute the template in your finetuned model with the one from the original model.
