### ISSUE TITLE
Tool binding prevent streaming

### ISSUE THREAD

**Issue by pyautoml** [ollama/ollama#7136]
### What is the issue?

Hi there. I discovered recently that onces a model is delivered tool via bind_tools is stops recognizing streeaming, and each time it waits for the data to be fully loaded. 

This snippet below works perfectly fine until tools are added:

print("AI:", end=" ", flush=True)
for chunk in self.model.stream([("human", user_input)], callbacks=[streaming_handler]):
    if chunk.content:
        print(chunk.content, end='', flush=True)

It happens regardless of the model type.

### OS

Windows

### CPU

Intel

### Ollama version

0.3.11

**Comment by rick-github** [comment]
https://github.com/ollama/ollama/issues/5796

**Comment by LuckLittleBoy** [comment]
I hope streaming tool calls will be supported soon. I've been waiting for this for a long time.

**Comment by pdevine** [comment]
Going to close this as a dupe.
