### ISSUE TITLE
real ```ollama stop``` cli

### ISSUE THREAD

**Issue by HomunMage** [ollama/ollama#7160]
ollama version 0.3.12

currently,
* a thread ```ollama serve```
* a thread ```ollama run xxxx ```
* a thread ```ollama stop xxxx```

the second thread still working

**Comment by pdevine** [comment]
Can you post some more details? Are you sure the model was even running before you asked it to stop?

**Comment by HomunMage** [comment]
> Can you post some more details? Are you sure the model was even running before you asked it to stop?

Hi pdevine, 

here is recording:

![output](https://github.com/user-attachments/assets/c1572053-e670-47d5-b5d1-7ae7af99f673)

**Comment by pdevine** [comment]
If you type `ollama ps` after issuing `stop` it will tell you the model is going to unload (it should say `Stopping...`) and will unload after it finishes processing. If you need to stop inference in the CLI you can just hit Ctrl-C.
