### ISSUE TITLE
Mistral-Nemo Model Stuck in "Stopping" State After Removal

### ISSUE THREAD

**Issue by Yash-exe** [ollama/ollama#7165]
### What is the issue?

I recently removed the latest Mistral-Nemo 7B model using ollama rm command and noticed some strange behavior:

The mistral nemo model no longer shows up when I run **ollama list**
Disk space usage has returned to normal, which suggests that the model has been successfully removed. Checked this via **df -k**
This seems correct.

However, when I run **ollama ps**, the model still appears with the status "stopping..." and seems to be stuck in this state. Have attached the screenshot for reference.

What would be the correct steps to resolve this?

![Screenshot 2024-10-10 at 9 05 18 AM](https://github.com/user-attachments/assets/b1a37da8-266a-4e43-9a48-27e65cbd542d)

### OS

Linux

### Ollama version

0.3.12

**Comment by rick-github** [comment]
Restarting ollama should clear the stale information.  Note that 0.1.32 is pretty old.

**Comment by Yash-exe** [comment]
The version has been updated to 0.3.12

Stopping and starting the ollama service and running another model using ollama run llama3.2 command cleared the stale information.
