### ISSUE TITLE
Counting tokens in text before embedding

### ISSUE THREAD

**Issue by DewiarQR** [ollama/ollama#7171]
When creating a vector database, we use embedding models such as bge-m3. The problem is that if the size of the text sent for vectorization does not fit into the context window of the model, the data is simply lost! and the Ollama project does not have a SINGLE MODEL!!! that would simply calculate tokens in the text before sending! For example, the bge-m3 model uses the RoBERTa algorithm, it would be very convenient if there was at least one model available via API that would simply count the exact number of tokens in the text! Is it possible to add this? Without this, working with embedding is difficult.

**Comment by DewiarQR** [comment]
Even better, if embedding models like mxbai-embed-large, nomic-embed-text, paraphrase-multilingual, bge-m3 - along with the response in the form of vector representations of the data, also reported how many tokens they received as input... then this could be used to confirm that everything went well and no data was lost

**Comment by rick-github** [comment]
https://github.com/ollama/ollama/issues/3582
