### ISSUE TITLE
Llama 3.2 11B and 90B

### ISSUE THREAD

**Issue by DewiarQR** [ollama/ollama#7172]
In your blog https://ollama.com/blog/llama3.2 - you wrote that you will soon add multimodal models Llama 3.2 11B and 90B Vision models. Today I see that you have added two new models to your system, but the promised llama3.2 models are not there yet. Can you roughly estimate when they will appear? We are really looking forward to it, we have been constantly checking their availability on your site for 2 weeks now!)))

**Comment by rick-github** [comment]
https://github.com/ollama/ollama/pull/6963

**Comment by dhiltgen** [comment]
We're tracking the new vision support for llama 3.2 in #6972
