### ISSUE TITLE
Model Response to Harmful Queries Not Properly Flagged – Safety Issue

### ISSUE THREAD

**Issue by diazr04** [ollama/ollama#7173]
Hi, I was testing the system’s response to potentially harmful queries to see how well it handles safety protocols. Unfortunately, I noticed that the model provided detailed information on a topic that should likely have been flagged or blocked for safety reasons. I’m reporting this to help improve the model’s filters and safeguards, as it’s important for the system to handle such cases appropriately.

**Comment by rick-github** [comment]
ollama is just an inference engine, query filtering is done at a higher level.  A model may contain information that is wrong or sensitive, if that's the case then try a different model.

**Comment by diazr04** [comment]
Yeah sorry, I realized that this is just an inference engine and not the actual llama3.1 source development code, So, that relies on meta then, no?

**Comment by rick-github** [comment]
Yes, if there are issues with the model it would need to be taken up with the model creators.  See https://ai.meta.com/llama/ or try starting a discussion at [Hugging Face](https://huggingface.co/meta-llama/Llama-3.1-405B/discussions).

**Comment by diazr04** [comment]
Thank you.

**Comment by AncientMystic** [comment]
I would also say if you find a response harmful when you asked for that response, don't ask for that response. no need to censor everyone on the internet, if you do not want it, do not ask for it.

**Comment by dhiltgen** [comment]
@diazr04 you might find the new safety models useful for your use-case.  Check out https://github.com/ollama/ollama/releases/tag/v0.3.13
