### ISSUE TITLE
Error: exception done_getting_tensors: wrong number of tensors; expected 255, got 254

### ISSUE THREAD

**Issue by GeorgeR** [ollama/ollama#7176]
### What is the issue?

After installing Ollama, pulling llama3.2 and trying to run it, I get this error. I saw other threads regarding the same, but in my case updating to the latest ollama didn't help.

Here's what --version dumps out:
ollama version is 0.1.30
Warning: client version is 0.3.12

### OS

Windows

### GPU

Nvidia

### CPU

AMD

### Ollama version

0.1.30

**Comment by rick-github** [comment]
You are running an old version of the server, have you previously installed in WSL (https://github.com/ollama/ollama/issues/6701)?

**Comment by GeorgeR** [comment]
> You are running an old version of the server, have you previously installed in WSL (#6701)?

That was exactly it, thanks!
