### ISSUE TITLE
Qwen2.5-Math support

### ISSUE THREAD

**Issue by fzyzcjy** [ollama/ollama#7178]
Hi thanks for the library! It seems that ollama supports qwen2.5 and qwen2.5-coder, but not qwen2.5-math (a quick search only gives qwen2-math which is older model https://ollama.com/search?q=qwen2.5-math). 

Related: https://github.com/ollama/ollama/issues/6916
Related: https://github.com/ollama/ollama/issues/6889

**Comment by jmorganca** [comment]
Thanks for the issue! Will close this for https://github.com/ollama/ollama/issues/6889
