### ISSUE TITLE
Failed to update all the models downloaded locally

### ISSUE THREAD

**Issue by qzc438** [ollama/ollama#7183]
### What is the issue?

When I use this code in the latest version of ollama: `ollama list | cut -f 1 | tail -n +2 | xargs -n 1 ollama pull`
There is an error message:
pulling manifest
Error: pull model manifest: file does not exist

**Comment by rick-github** [comment]
```
ollama list | cut -f 1 | tail -n +2 | xargs -i@ bash -c 'ollama pull @ 2>&- || echo failed: @'
```

**Comment by rick-github** [comment]
Run it from the command line.  It will update all the models, and print the names of the models that fail.  Then you can determine why the failed models weren't updated: old model, not from the ollama library, etc.

**Comment by rick-github** [comment]
Pick a model and run `ollama pull $MODEL`, post the result.  Add the [server logs](https://github.com/ollama/ollama/blob/main/docs/troubleshooting.md#how-to-troubleshoot-issues).

**Comment by jmorganca** [comment]
Hi @qzc438 sorry this isn't easier today will merge with https://github.com/ollama/ollama/issues/2633 or try @rick-github's script
