### ISSUE TITLE
create minimal cpu-only smaller docker image

### ISSUE THREAD

**Issue by ozbillwang** [ollama/ollama#7184]
The image `ollama/ollama` is 4.87GB already, which I plan to run it on my macbook or Ubuntu (linux) without any GPUs. 

```
ollama/ollama    latest    e458178cf2c1   2 weeks ago         4.87GB
```

Are there any ways to reduce the size to as small as possible, since I don't need care of GPU, CUBA driver, etc

**Comment by rick-github** [comment]
You can build a custom version with [`scripts/build_docker.sh`](https://github.com/ollama/ollama/blob/main/scripts/build_docker.sh), controlled by environment variables, see [`scripts/env.sh`](https://github.com/ollama/ollama/blob/main/scripts/env.sh).  For example:
```
$ VERSION=cpu PLATFORM=linux/amd64 OLLAMA_SKIP_CUDA_GENERATE=1 scripts/build_docker.sh
```

**Comment by ozbillwang** [comment]
Took me the whole day (more than 8 hours on my macbook), I finally successfully build the image 

> You can build a custom version with [`scripts/build_docker.sh`](https://github.com/ollama/ollama/blob/main/scripts/build_docker.sh), controlled by environment variables, see [`scripts/env.sh`](https://github.com/ollama/ollama/blob/main/scripts/env.sh). For example:
> 
> ```
> $ VERSION=cpu PLATFORM=linux/amd64 OLLAMA_SKIP_CUDA_GENERATE=1 scripts/build_docker.sh
> ```

I finally built the image successfully, but it took about 8 hours on my MacBook. The size isn't significantly different, still around 4.87 GB.

```
docker images
REPOSITORY      TAG               IMAGE ID       CREATED             SIZE
ollama/ollama   cpu-rocm          86087abfe5b8   3 minutes ago       9.71GB
ollama/ollama   cpu               b450966abbae   About an hour ago   4.87GB
```

**Comment by rick-github** [comment]
What command did you use?

**Comment by ozbillwang** [comment]
> What command did you use?

Same command you provide: 

```
VERSION=cpu PLATFORM=linux/amd64 OLLAMA_SKIP_CUDA_GENERATE=1 scripts/build_docker.sh
```

**Comment by ozbillwang** [comment]
> What I need is a lightweight Ollama Docker image that can run easily and quickly on Mac or Linux. My goal is to be able to deploy it anywhere, if possible, for use in my projects.

That would be great, and helpful

What I need is a lightweight Ollama Docker image that can run easily and quickly on Mac or Linux. My goal is to be able to deploy it anywhere, if possible, for use in my projects.

**Comment by ozbillwang** [comment]
@rick-github @dhiltgen 

Should I spend time on this now or waiting for new Go server ready?

Are there any ways to get a lightweight version now?

**Comment by kth8** [comment]
Here is a minimal Dockerfile that uses a 15MB base image then just add the Ollama binary.
```
FROM cgr.dev/chainguard/wolfi-base
RUN apk add --no-cache libstdc++ wget
RUN sh -c 'wget -O - https://ollama.com/download/ollama-linux-amd64.tgz | tar -xz --strip 2 ./bin/ollama'
EXPOSE 11434
CMD ["/ollama", "serve"]
```

**Comment by kth8** [comment]
```
FROM ollama/ollama AS ollama
FROM cgr.dev/chainguard/wolfi-base
RUN apk add --no-cache libstdc++
COPY --from=ollama /usr/bin/ollama /usr/bin/ollama
COPY --from=ollama /usr/lib/ollama/runners/cpu /usr/lib/ollama/runners/cpu
COPY --from=ollama /usr/lib/ollama/runners/cpu_avx /usr/lib/ollama/runners/cpu_avx
COPY --from=ollama /usr/lib/ollama/runners/cpu_avx2 /usr/lib/ollama/runners/cpu_avx2
ENV OLLAMA_HOST=0.0.0.0
EXPOSE 11434/tcp
CMD ["ollama", "serve"]
```
```
REPOSITORY                              TAG           IMAGE ID       CREATED              SIZE
ollama-cpu                              latest        af01a2130bf0   25 seconds ago       58.8MB
```

**Comment by ozbillwang** [comment]
That's unbelievible, thanks. 

```
 > [stage-1 6/6] COPY --from=ollama /usr/lib/ollama/runners/cpu_avx2 /usr/lib/ollama/runners/cpu_avx2:
------
Dockerfile:10
--------------------
   8 |     COPY --from=ollama /usr/lib/ollama/runners/cpu /usr/lib/ollama/runners/cpu
   9 |     COPY --from=ollama /usr/lib/ollama/runners/cpu_avx /usr/lib/ollama/runners/cpu_avx
  10 | >>> COPY --from=ollama /usr/lib/ollama/runners/cpu_avx2 /usr/lib/ollama/runners/cpu_avx2
  11 |
  12 |     ENV OLLAMA_HOST=0.0.0.0
--------------------
ERROR: failed to solve: failed to compute cache key: failed to calculate checksum of ref dz6h742w0onjh1v8nvo9s93ni::nilz7o5yom8k3s4ufsz0n3lww: "/usr/lib/ollama/runners/cpu_avx2": not found
```
I should be fine to fix it

**Comment by ozbillwang** [comment]
One issue found. 

below folders doesn't exist in `ollama/ollama` ARM64 image
```
COPY --from=ollama /usr/lib/ollama/runners/cpu_avx /usr/lib/ollama/runners/cpu_avx
COPY --from=ollama /usr/lib/ollama/runners/cpu_avx2 /usr/lib/ollama/runners/cpu_avx2
```

But I can't replace it with 

```
COPY --from=ollama /usr/lib/ollama/runners/cpu* /usr/lib/ollama/runners/
```
this code doesn't work, I don't get folders, but files are copied into /usr/lib/ollama/runners/ directly
```
/usr/lib/ollama/runners # pwd
/usr/lib/ollama/runners
/usr/lib/ollama/runners # ls -l
total 4620
-rwxr-xr-x    1 root     root        837952 Oct 10 22:22 libggml.so
-rwxr-xr-x    1 root     root       2089576 Oct 10 22:22 libllama.so
-rwxr-xr-x    1 root     root       1794136 Oct 10 22:22 ollama_llama_server
/usr/lib/ollama/runners #
```

**Comment by ozbillwang** [comment]
seems avx/avx2 is not must-have feature. 

https://github.com/ollama/ollama/issues/2903

**Comment by ozbillwang** [comment]
I made it, thanks to all

https://hub.docker.com/repository/docker/alpine/ollama/general

**Comment by zeeskore** [comment]
> I made it, thanks to all
> 
> https://hub.docker.com/repository/docker/alpine/ollama/general

This is very nice,  but would be better if the docker image is updated with the current version of ollama 0.5.7 vs 0.3.13

**Comment by ozbillwang** [comment]
> > I made it, thanks to all
> > https://hub.docker.com/repository/docker/alpine/ollama/general
> 
> This is very nice, but would be better if the image on hub.docker.com is updated with the current version of ollama 0.5.7 vs 0.3.13

automation builds, already 0.32.x now
