### ISSUE TITLE
[Feature Request] Command to browse the model library / search for a specific model from the ollama CLI.

### ISSUE THREAD

**Issue by AFellowSpeedrunner** [ollama/ollama#7185]
I recently had an idea. What if there was a command to search and browse the model library from the ollama CLI?

I'm imagining something like `ollama search llama3` and `ollama browse`.

For example, the search would return like (rough example, GitHub formatting kinda broke it and I don't know how to fix it):

MODEL                       LATEST SIZE                      PARAMETERS
llama3                         4.7GB                               8B, 70B
llama3.1                      4.7GB                               8B, 70B, 405B
llama3.2                      2.0GB                               1B, 3B
[username]/[model]     [size]                                 [parameters]

Browse would be the same, but it would sort from newest model first. (Maybe the potential to sort by most popular and stuff like the library website?)

I hope the devs think this is a good idea because I'd love to see this implemented!

Thank you.

**Comment by rick-github** [comment]
https://github.com/ollama/ollama/issues/1070

**Comment by AFellowSpeedrunner** [comment]
> #1070

Ah, I didn't see this (I was using wrong search terms) but this does seems to be more about adding an API into the library for a potential CLI integration (It may not end up like that, so that's why I said potential) rather than my one which is about how the integration into the CLI would work. That issue as well does not mention how the integration would be laid out and how it'd work clientside unlike my one here.

In my opinion, I still think this issue is valid. Issue 1070 is similar but not the same as this one.

I will state that this is how I see it so do let me know if I'm actually wrong here. I'm open to constructive criticism as long as it doesn't become an argument. :D

**Comment by rick-github** [comment]
This issue isn't invalid.  The ollama CLI is just a wrapper around ollama APIs.  APIs are where the bulk of the work will be, adding features to the CLI after the APIs are deployed will be relatively simple.

**Comment by AFellowSpeedrunner** [comment]
I'm so sorry, I forgot how this worked. I thought they were talking about only server side.

**Comment by jmorganca** [comment]
Thanks @AFellowSpeedrunner for the issue, and thanks @rick-github for finding the duplicate – will close for https://github.com/ollama/ollama/issues/1070 for now

**Comment by AFellowSpeedrunner** [comment]
Alright then, thanks anyways!
