### ISSUE TITLE
Please consider allowing the Windows version of Ollama to be installed on a drive other than the system drive

### ISSUE THREAD

**Issue by ajmz** [ollama/ollama#7186]
Could you please consider allowing the Windows version of Ollama to be installed on a drive other than the system drive?
This would help reduce space usage on the system drive, making it easier for users to manage backups effectively. 
Implementing this option would be greatly appreciated.

**Comment by rick-github** [comment]
https://github.com/ollama/ollama/issues/2776

**Comment by jmorganca** [comment]
Closing for https://github.com/ollama/ollama/issues/2776 thanks @rick-github
