### ISSUE TITLE
怎样在本地建一个ollama.com/library的服务

### ISSUE THREAD

**Issue by czhcc** [ollama/ollama#7195]
### What is the issue?

能在本地建一个ollama.com/library的服务吗？

我用Modelfile时，内容是
FROM http://19.18.5.127/temp/myqwen7b.gguf
会出现错误
Error: pull model manifest: Get "http://19.18.5.127/v2/temp/myqwen7b.gguf/manifests/latest": EOF

要怎样提供一个本地的拉取服务？

**Comment by mili-tan** [comment]
Ollama 的模型通过 OCI 制品的形式进行分发。也许你应该尝试搭建一个本地 OCI Registry 镜像仓库（或许可能 Docker 镜像仓库也可以工作），并且通过 ollama push 推送本地已导入的模型到仓库中。

**Comment by pdevine** [comment]
@czhcc you'll need to specify a file path to the gguf, not a URL.
