### ISSUE TITLE
llama runner process no longer running: -1 

### ISSUE THREAD

**Issue by Dhruv-1212** [ollama/ollama#7197]
### What is the issue?

I am trying to run llama3 models but getting this error on both pip installation and linux installation on a server with Tesla T4 GPU, but the same is working fine on my local machine. 

### OS

Linux

### GPU

Nvidia

### CPU

Intel

### Ollama version

0.3.3

**Comment by rick-github** [comment]
[Server logs](https://github.com/ollama/ollama/blob/main/docs/troubleshooting.md#how-to-troubleshoot-issues) will help in debugging.

**Comment by Dhruv-1212** [comment]
that worked thanks, port 11434 was preoccupied due to some reason
