### ISSUE TITLE
num_ctx forces entire model to CPU

### ISSUE THREAD

**Issue by jimwashbrook** [ollama/ollama#7198]
### What is the issue?

Apologies if this is covered somewhere, but I couldn't find any documentation for it and it doesn't seem intended.

For context, my GPU has 8GB VRAM, and the model I "discovered" this with was `llama3.2:3b-instruct-q8_0`, but it seems to occur for any other.

`ollama ps` shows the model as `3.4 GB`

When doing an API request without `num_ctx`, 100% of the model is loaded on the GPU.

When setting `num_ctx` to a number that'll force it to exceed my VRAM size, we'll get something like `10 GB    33%/67% CPU/GPU` as expected (num_ctx of 40000 in that instance).

However, when I set it to 128000, the result is:
<img width="823" alt="image" src="https://github.com/user-attachments/assets/46ae45f4-95fd-4c50-aa6d-f74bf486d69f">

### OS

Windows

### GPU

Nvidia

### CPU

AMD

**Comment by bold84** [comment]
The larger the context window, the larger the required VRAM. 

Reduce num_ctx to a value that allows for the model to be loaded into VRAM fully. Play around with it until you get it right.

**Comment by dhiltgen** [comment]
The context size has a direct impact on the amount of VRAM required to run the model.  Ollama supports spilling over into system memory and splitting inference between the GPU and CPU, up to a point.  There are some data structures that have to be allocated in the GPU to support any GPU inference. Before loading the model, we calculate how much VRAM is required, and if the required structures can not fit, we fall back to 100% CPU based inference.

**Comment by jimwashbrook** [comment]
Ah I didn't realise that the structures would grow so large that they would exceed VRAM. Good to know thank you!
