### ISSUE TITLE
Help, is it possible to copy and deploy a small size model onto multiple GPU cards?

### ISSUE THREAD

**Issue by tigflanker** [ollama/ollama#7206]
The current situation is as follows:

I have 4 T4 GPU cards, each with 16G of memory, and my model size is the quantized version, which is only 5G.

When considering the multi-concurrency scenario in the production environment, I want to load this model onto all 4 GPUs simultaneously (for subsequent concurrent invocation). 

Is there a way to do this? Thanks.

**Comment by rick-github** [comment]
ollama doesn't currently support loading  the same model more than once.  https://github.com/ollama/ollama/issues/3902 is tracking the work for loading a model multiple times but there's no progress so far.

If you want to run multiple copies of the same model, the easiest way at the moment is to start an ollama server on a different port for each GPU, using `CUDA_VISIBLE_DEVICES` to bind each GPU to it's server, and then use a reverse proxy (eg [nginx](https://docs.nginx.com/nginx/admin-guide/load-balancer/http-load-balancer/) or [ollama_proxy_server](https://github.com/ParisNeo/ollama_proxy_server)) to distribute the requests to the ollama servers.

Another approach would be to set `OLLAMA_SCHED_SPREAD=1` to force the model to be spread across all the GPUs and set `OLLAMA_NUM_PARALLEL=4` to allow concurrent processing.  I don't know what the performance of this type of configuration would be.

**Comment by dhiltgen** [comment]
Tracking via #3902
