### ISSUE TITLE
Can't get anything to work

### ISSUE THREAD

**Issue by softwaretrouble** [ollama/ollama#7207]
### What is the issue?

While I still had the chance I wanted to do a complete Linux reinstall tonight to update to 22.0. Everything was going good until I came to Ollama and then everything stopped. I used to be able to use Ollama on this desktop with the 3-7 Gb models. It was slow thanks to being on an older desktop but with the smaller models I could still use them on this desktop.

I have models downloaded that I have used before and want to run them set up on the new install so they would be ready when I wanted to use them.

ollama run Neo-Phi-2.gguf

file does not exist

ollama create neo2 -f Neo-Phi-2.gguf

command must be one of from license template.........

I have the FROM ./Neo-Phi-2.gguf saved in txt file, even when saved in neo2 I still get the from, license, template error.

What do I have to do to get this to allow me to use it?

### OS

Linux

### GPU

Intel

### CPU

Intel

### Ollama version

0.3.13

**Comment by pdevine** [comment]
I'm going to go ahead and close out the issue since @rick-github answered it. @softwaretrouble if you have any problems I can reopen.

**Comment by softwaretrouble** [comment]
Sorry have not been around all day. The problem is not solved. I'm trying to use the brighteon.ai models, downloaded from their website. They are working models. I have used them in the past with no difficulties. I just shortened the name of the file to try out the different possible solutions I had seen on the net. I wasn't having any luck using the full length names and I was hearing talk about trouble with spaces and capital letters, etc, so I decided I shorten up the names and see if that would solve the problem, but it didn't.

**Comment by rick-github** [comment]
```console
$ cat Modelfile 
FROM Neo/Neo-Phi-2-E3-1-7B-V0-1-1/Neo-Phi-2-E3-1-7B-V0-1-1-Q5-Apr-24.gguf
TEMPLATE "{{ if .System }}System: {{ .System }}{{ end }}
User: {{ .Prompt }}
Assistant:"
$ ollama create neo2 -f Modelfile
transferring model data 100% 
using existing layer sha256:52facaa21a0c5bf367ab84cf3577a8752ebb3de0c6d9c09f746da720822998d9 
using existing layer sha256:774a15e6f1e5a0ccd2a2df78c20139ab688472bd8ed5f1ed3ef6abf505e02d02 
creating new layer sha256:6c49880974a1e322dce86a6fce628a032ef58f5ac08f423a4e3ca0688270861d 
writing manifest 
success 
$ ollama run neo2 hello
 Yes, I'm a language model AI designed to generate human-like responses. I am programmed to understand context and respond in a conversational manner. 
Is that clear?
```
Make sure that when you run the `create` command, you are specifying the Modelfile and not the model.  If you still can't get it to work, paste the actual commands and errors in to this issue.

**Comment by softwaretrouble** [comment]
Okay, not sure fully what I was doing differently between now and around a year ago. My old Modelfile only ever showed FROM and never included TEMPLATE or anything else. They don't work with only FROM. They are working now. Thanks. This can be closed.
