### ISSUE TITLE
Reference failure for user uploaded models in OpenAI compatible API

### ISSUE THREAD

**Issue by aretrace** [ollama/ollama#7220]
### What is the issue?

I am attempting to call `adrienbrault/nous-hermes2theta-llama3-8b` via the OpenAI node SDK, I get a 500 with a `model ... not found, try pulling it first` error (I already have it and chatted with it).

I did a simple curl test:
```zsh
curl -X POST http://localhost:11434/api/generate -d '{
  "model": "adrienbrault/nous-hermes2theta-llama3-8b",
  "prompt": "Hello, how are you?"
}'
```
Same 500 error (other `library` models are working).

A poke at `http://localhost:11434/v1/models` shows its there:
```javascript
{
  "object": "list",
  "data": [
    {
      "id": "adrienbrault/nous-hermes2theta-llama3-8b:q4_K_M",
      "object": "model",
      "created": 1729046834,
      "owned_by": "adrienbrault"
    },
    ...
}
```
I have tried several logical permutations of the model name but none have worked.

### OS

macOS

### GPU

Apple

### CPU

Apple

### Ollama version

0.3.13

**Comment by rick-github** [comment]
0x376h is correct.  If you don't specify the quant, it uses `latest`, so when it returns a 500 error, it's trying to find the model `adrienbrault/nous-hermes2theta-llama3-8b:latest`.

**Comment by aretrace** [comment]
I could've sworn I tried that!
It works, false alarm 🫠
