### ISSUE TITLE
ollama parallel

### ISSUE THREAD

**Issue by jamalibrahimsec** [ollama/ollama#7225]
Hello 
I am trying to run ollama in instance that has 40 cores of cpus 
what I understood is that max models env variable permit doing that but there was no cleear explanation about how it would doing it with cpu (knowing that I have enough ram ).
if you can explain for me how ollama manage that with cpu it would be perfect. 

tahnks

**Comment by rick-github** [comment]
Set [`OLLAMA_NUM_PARALLEL`](https://github.com/ollama/ollama/blob/main/docs/faq.md#how-do-i-configure-ollama-server:~:text=for%20CPU%20inference.-,OLLAMA_NUM_PARALLEL,-%2D%20The%20maximum%20number) in the [server environment](https://github.com/ollama/ollama/blob/main/docs/faq.md#how-do-i-configure-ollama-server) to the number of parallel requests you want to handle.  Note that ollama won't use all 40 cores by default, you can override that by setting `num_threads` in the [API](https://github.com/ollama/ollama/blob/main/docs/api.md#:~:text=use_mlock%22%3A%20false%2C%0A%20%20%20%20%22-,num_thread,-%22%3A%208%0A%20%20%7D%0A%7D) or by creating a [copy of a model](https://github.com/ollama/ollama/issues/6950#issuecomment-2373663650) and setting `PARAMETER num_threads xx` in the [Modelfile](https://github.com/ollama/ollama/blob/main/docs/modelfile.md).

**Comment by jamalibrahimsec** [comment]
hello thanks for your response 
so basically I cannot use more that one model for inference at the same time

**Comment by rick-github** [comment]
You can use more than one model at the same, up to the amount specified in `OLLAMA_MAX_LOADED_MODELS`.  Here I have it set to 4:
```console
$ ollama ps
NAME                 	ID          	SIZE  	PROCESSOR	UNTIL   
phi:2.7b-chat-v2-q4_0	e2fd6321a5fe	4.2 GB	100% CPU 	Forever	
llama3.1:latest      	42182419e950	5.2 GB	100% CPU 	Forever	
llama3.2:latest      	a80c4f17acd5	2.8 GB	100% CPU 	Forever	
qwen2:0.5b           	6f48b936a09f	314 MB	100% CPU 	Forever	
```
If I load another model, one of the current ones gets unloaded:
```console
$ ollama ps
NAME                 	ID          	SIZE  	PROCESSOR	UNTIL   
phi3:3.8b            	4f2222927938	5.4 GB	100% CPU 	Forever	
phi:2.7b-chat-v2-q4_0	e2fd6321a5fe	4.2 GB	100% CPU 	Forever	
llama3.2:latest      	a80c4f17acd5	2.8 GB	100% CPU 	Forever	
qwen2:0.5b           	6f48b936a09f	314 MB	100% CPU 	Forever	
```
If you were to run 4 models at a time, you would need to adjust `num_threads` as above to prevent the CPU from being oversubscribed.

You cannot run the same model multiple times.

This is independent of `OLLAMA_NUM_PARALLEL`, which determines how many parallel completions a model can do.

**Comment by jamalibrahimsec** [comment]
ok thanks 
so the same model cannot be loaded multiple times but different models can be loaded 
if you can tell me why it would be appreciated
thanks a lot

**Comment by rick-github** [comment]
ollama doesn't currently support loading the same model more than once. #3902 is tracking the work for loading a model multiple times but there's no progress so far.

If you want to load a model multiple times so that it can process parallel queries, use one model and set `OLLAMA_NUM_PARALLEL`.

**Comment by jamalibrahimsec** [comment]
following the same issue if I used the smae modelfile to create 10 different models can I run those models in parallel or ollama will keep recognizing the source model?

thanks

**Comment by rick-github** [comment]
If you use the same Modelfile, you are creating 10 copies of the same mode with different aliases, and ollama will only load one copy.

**Comment by jamalibrahimsec** [comment]
ok thanks for the explanation. so I understand that it would still works without parallelism as I am doing.
 
speaking about the num_threads can you explain me more what does this do. or in other words what this parameter control. 

and if you have any recommendation about how to optimize  the model parameters in terms of velocity  it could be really helpfull

thanks

**Comment by jamalibrahimsec** [comment]
as well if I used three different models at the same time how ollama would manage the resources would it dedicates resources for each model or the models would compete for the resources

**Comment by rick-github** [comment]
`num_threads` is the number of threads that the ollama runner (llama.cpp) will use for inference.  The number of threads depends on the operating system, number of CPUs, number of cores per CPU, whether hyperthreading is enabled etc.  Typically, a CPU core be able to support 2 threads, so your 40 core machine has 80 threads available.  ollama tries to figure out what the optimal number of threads to use is, and will configure each runner to use that number.  If you run multiple different models and then have ollama do multiple requests on each model, that can cause the CPU(s) to have too many simultaneous threads running, overwhelming the system.  In that case you would set `num_threads` to the number of threads available on your system divide by the number of parallel requests you would expect to handle.

If you have one model, you can set `OLLAMA_NUM_PARALLEL` to 1 and set `num_threads` to the number of threads on your system, and ollama will process one query at a time with maximum processing power, or you can set `OLLAMA_NUM_PARALLEL` to the number of threads on your system and set `num_threads` to 1, and ollama will process many queries at the same time but using minimum processing power.  The throughput of each approach will vary depending on the efficiency of the processing which will depend on the model, the runner invoked, etc.  The way to get the best results is to experiment with the configuration and see what performs the best.

**Comment by rick-github** [comment]
If you use three models, you can allocate a thread count per model and they will share.  If you over allocate threads and have each model perform inference at the same time, they will compete for CPU cycles and will be less efficient.

**Comment by jamalibrahimsec** [comment]
based on what are you saying I guess the best solution is to use different docker containers (  a container for each model) with dedicated resources .

**Comment by rick-github** [comment]
If you are running three different models, you can load them in one ollama server.  If you want to run the same model three times in parallel, you can load it in one ollama server and set OLLAMA_NUM_PARALLEL=3.

**Comment by jamalibrahimsec** [comment]
yes but what I am thinking is that may docker would be more efficient in isolating the resources

**Comment by sasakiyori** [comment]
BTW when I increase the `OLLAMA_NUM_PARALLEL`, the ratio of CPU/GPU utilization changes, why? Is it preallocation or something? I used to think this is only about the model size, not the size of the concurrent sequence size😢 @rick-github 

`OLLAMA_NUM_PARALLEL=5`:     `100%GPU`
`OLLAMA_NUM_PARALLEL=50`:   `16%/84% CPU/GPU`

**Comment by rick-github** [comment]
Increasing `OLLAMA_NUM_PARALLEL` increases the size of the KV cache allocated on the GPU, leaving less room for model weights, so they get moved to system RAM.  Each parallel completion needs its own KV cache to run in.

**Comment by jamalibrahimsec** [comment]
I tried to use num_threads in  the Modelfile and it gave me an unknown parameter

**Comment by rick-github** [comment]
My mistake, `num_thread`, no trailing 's'.

**Comment by jamalibrahimsec** [comment]
thanks
