### ISSUE TITLE
Llama-3.1-Nemotron-70B

### ISSUE THREAD

**Issue by nonetrix** [ollama/ollama#7228]
Seems to just be llama 3.1 with ChatML prompt format(?) should be easy to add and seems to beat 4o on some benchmarks... We will see how that actually plays out, but it seems really good for me
https://huggingface.co/collections/nvidia/llama-31-nemotron-70b-670e93cd366feea16abc13d8

**Comment by VikramxD** [comment]
you can now just add the model from hugginface link  

`ollama run hf.co/bartowski/Llama-3.1-Nemotron-70B-Instruct-HF-GGUF`

**Comment by nonetrix** [comment]
That works for me not sure if prompt template is right etc. But seems to be working well lol

**Comment by rick-github** [comment]
https://ollama.com/library/nemotron/tags
