### ISSUE TITLE
Ollama document intelligence engine

### ISSUE THREAD

**Issue by dcasota** [ollama/ollama#7238]
Has anyone Ollama examples for document intelligence?

In comparison, Azure AI comes with an engine which extracts elements from documents and makes them eligible passing the data into customizeable workflows. However, there are culprits even in the payed tier.

Azure AI Document Intelligence requirements
- Microsoft Office files, or
- JPEG, PNG, BMP, TIFF, or PDF format
- PDF documents must have dimensions less than 17 x 17 inches or A3 paper size.
- PDF documents must not be protected with a password.
- Images must have dimensions between 50 x 50 pixels and 10,000 x 10,000 pixels.
- file size less than 500 MB (payed standard tier)
- only the first 2000 pages are analyzed (payed standard tier)

Some information about [supported languages](https://learn.microsoft.com/en-us/azure/ai-services/document-intelligence/language-support/ocr?view=doc-intel-4.0.0&preserve-view=true&tabs=read-print%2Clayout-print%2Cgeneral)

Which Ollama examples fit to this extraction+passing-to-external-workflow demand?

**Comment by mitja** [comment]
I think this is not in scope of Ollama. Ollama's focus is on local model serving and not integrated solutions. Maybe look at end user tools like OpenWebUI or frameworks like LlamaIndex, which can both use Ollama for model serving.

**Comment by dcasota** [comment]
Selection is good. Why shouldn't founders and young entrepreneurs think about three years into the future, right? Ollama is actually the best example of an integrated solution in terms of Hugging Face and Python as the preferred language in examples.

**Comment by pdevine** [comment]
Thanks for the issue @dcasota ! I'm going to consolidate this into #5762; I'd love to do something like this in the future.

**Comment by dcasota** [comment]
@pdevine I wasn‘t aware of #5762. Makes sense. Have a great business plan.
