### ISSUE TITLE
model in 3 part

### ISSUE THREAD

**Issue by werruww** [ollama/ollama#7245]
How do I run a model divided into parts in Olam?

**Comment by werruww** [comment]
model gguf

**Comment by werruww** [comment]
with modelfile

**Comment by werruww** [comment]
k.gguf-00001-of-00003.gguf
k.gguf-00002-of-00003.gguf
k.gguf-00003-of-00003.gguf

how to run on ollama without merg?

**Comment by werruww** [comment]
Does Obama support fragmented models? Important: They must be merged before running in Olama by modelfile

**Comment by pdevine** [comment]
Dupe of #7272
