### ISSUE TITLE
debug modelfile on create

### ISSUE THREAD

**Issue by belfie13** [ollama/ollama#7251]
i get 

    Error: command must be one of "from", "license...

when creating via model file i generated from some text eg:

    ollama create test -f test.modelfile

i have to cut out the code and paste it line by line back into the modelfile to find where the issue is.

in the error message, could you add a line number where the issue was found when attempting to create a model from file

**Comment by gfunsAi** [comment]
can you show content of test.modelfile ?

**Comment by belfie13** [comment]
#7326 solves this when it gets closed. I have found that the `/save` function produces the same error, i'll open another issue.
