### ISSUE TITLE
fail to run ollama run hf-mirror.com/Orenguteng/Llama-3.1-8B-Lexi-Uncensored-V2-GGUF:Q8

### ISSUE THREAD

**Issue by taozhiyuai** [ollama/ollama#7268]
### What is the issue?

taozhiyu@Mac ~ % ollama run hf-mirror.com/Orenguteng/Llama-3.1-8B-Lexi-Uncensored-V2-GGUF:Q8
pulling manifest 
Error: pull model manifest: 400: The specified tag is not a valid quantization scheme. Please use another tag or "latest"
taozhiyu@Mac ~ % ollama run hf-mirror.com/Orenguteng/Llama-3.1-8B-Lexi-Uncensored-V2-GGUF:lastest
pulling manifest 
Error: pull model manifest: 400: The specified tag is not a valid quantization scheme. Please use another tag or "latest"

### OS

macOS

### GPU

Apple

### CPU

Apple

### Ollama version

ollama version is 0.3.13

**Comment by kth8** [comment]
`ollama run hf.co/bartowski/Llama-3.1-8B-Lexi-Uncensored-V2-GGUF` works so perhaps so you should open an issue in Orenguteng's Hugging Face repo asking him to use standard naming scheme.

**Comment by taozhiyuai** [comment]
明白了.xx

**Comment by taozhiyuai** [comment]
@jmorganca is that possible ollama app ignore the format of  gguf filename? user provide URL of gguf file and Q type in command "ollama run".

it is impossible to request all gguf author to rename the file name to compatible with ollama .

**Comment by pdevine** [comment]
Hi @taozhiyuai , I think you could probably ask HuggingFace to change that? There isn't anything we can change.

I'll go ahead and close the issue.

**Comment by Mushoz** [comment]
I am getting the same error with this command:

`ollama run hf.co/bartowski/Replete-LLM-V2.5-Qwen-32b-GGUF:IQ4_NL`

The IQ4_NL quant does exist in the repo, and is a valid and normal quant option though: https://huggingface.co/bartowski/Replete-LLM-V2.5-Qwen-32b-GGUF

Is there any way I can fix this? And should I open a new ticket since this one is already closed? @pdevine

**Comment by pdevine** [comment]
@Mushoz I think this is still an HF issue though, no?

**Comment by Mushoz** [comment]
Not sure, is it? I have opened an issue about it here: https://github.com/ollama/ollama/issues/7365

Someone else is having the same issue. IQ4_NL is a quant that should be supported, but it doesn't work. All other quants work fine. What exactly is wrong on HF's side? @pdevine
