### ISSUE TITLE
You want to be able to customize the OLLAMA installation directory

### ISSUE THREAD

**Issue by wxpid1** [ollama/ollama#7269]
Sometimes my user directory space is not much, want to install software to other drive. This solves both the space issue and customizes the management of your own installed software.

I tried to use the OLLAMA variable setting, but it didn't work and the OLLAMA was installed on the C drive.

It's even better if you can customize the location of your software installation.

**Comment by rick-github** [comment]
https://github.com/ollama/ollama/issues/2776

**Comment by wxpid1** [comment]
ok
