### ISSUE TITLE
llama3.2:latest not running and giving Error: llama runner process no longer running: -1

### ISSUE THREAD

**Issue by ishu121992** [ollama/ollama#7278]
### What is the issue?

I have been using Ollama for a while and have never encountered this error while running any other llms (including llama3.1). 

Below is the snapshot of server log with error: 
![image](https://github.com/user-attachments/assets/6b2975aa-7d2f-4e76-ab22-1ca7bf0fa147)

Key issue seems to be related to wrong number of tensors. Any help? I have a 3070Ti GPU with 8 GB VRAM. 

### OS

WSL2

### GPU

Nvidia

### CPU

Intel

### Ollama version

0.1.32

**Comment by rick-github** [comment]
Upgrade ollama, 0.1.32 is too old to run llama3.2.
