### ISSUE TITLE
Is default install location configurable

### ISSUE THREAD

**Issue by wgong** [ollama/ollama#7284]
I run Ollama on Ubuntu, where its default home is `/usr/share/ollama`. 
Recently, I ran out of space on that partition after experimenting with quite a few models.
I then modified the `install.sh` script to install Ollama to `/opt/ollama`. 
This worked when starting Ollama on the terminal by running `ollama serve`; however, when I tried running it as a systemctl service,
it failed. Checking the log via `sudo journalctl -u ollama -n 50 --no-pager` 
showed an error message like "no permission to write id file in /usr/share folder".
I'm curious if `/usr/share` is hard-coded somewhere.

After creating a symlink for `/usr/share/ollama` to `/opt/ollama` and revising `/etc/systemd/system/ollama.service` to run as root, I was finally able to start the systemctl service.
Although it worked for me, I suspect it's a hack. Could you please advise on the correct way to install Ollama to a custom location and run it as a service (not as root)?

Claude Pro helped me with the above troubleshooting and workaround. 
It mentioned that the following environment variables are customizable. Is this correct?

```
OLLAMA_HOST: Specifies the host and port Ollama listens on (default: 127.0.0.1:11434).
OLLAMA_MODELS: We've discussed this; it sets the directory for model storage.
OLLAMA_HOME: Sets the home directory for Ollama (default: ~/.ollama).
OLLAMA_KEEP_ALIVE: Sets the duration to keep models loaded in memory (default: 5m).
OLLAMA_TIMEOUT: Sets the timeout for loading models (default: 5m).
OLLAMA_ORIGINS: Comma-separated list of allowed origins for CORS.
OLLAMA_NOPRUNE: If set, prevents automatic removal of unused layers.
OLLAMA_DEBUGLOG: Enables debug logging when set to 'on'.
OLLAMA_VERBOSE: Enables verbose logging when set to 'on'.
OLLAMA_GPU_LAYERS: Number of layers to offload to GPU (depends on available VRAM).
OLLAMA_THREADS: Sets the number of threads to use (default is number of physical CPU cores).
OLLAMA_SKIP_UPDATE_CHECK: Skips the update check on startup if set.
OLLAMA_INSECURE: Allows insecure connections when pulling models if set.
OLLAMA_LOCKFILE: Specifies a custom path for the lockfile.
OLLAMA_LOGFILE: Specifies a custom path for the logfile.
``` 

Thanks

**Comment by rick-github** [comment]
Set `OLLAMA_MODELS=/path/to/a/partition/with/space` in the service override config.  `chown ollama /path/to/a/partition/with/space`.  ollama will use `/usr/share/ollama` to store key and history, all of the space consuming model files will be in  `/path/to/a/partition/with/space`.

**Comment by wgong** [comment]
> Set `OLLAMA_MODELS=/path/to/a/partition/with/space` in the service override config. `chown ollama /path/to/a/partition/with/space`. ollama will use `/usr/share/ollama` to store key and history, all of the space consuming model files will be in `/path/to/a/partition/with/space`.

Thank you, will try it out
