### ISSUE TITLE
Please add hostname to ollama info

### ISSUE THREAD

**Issue by ovaisq** [ollama/ollama#7285]
I recently came across this PR: https://github.com/ollama/ollama/pull/7262. While it’s fantastic to have access to all this information, for cases where multiple applications or services are utilizing load-balanced Ollama servers (for instance, see https://github.com/ovaisq/LLM-RedditScraper/blob/main/paas.md), it would be beneficial, especially for alerting and monitoring purpose, to include the hostname as part of the “ollama info” output. For example, one of my services collects various data points, including tokens per second, version information, except no hostname.

![Screenshot 2024-10-20 at 11 12 30 PM](https://github.com/user-attachments/assets/d173e858-4217-4c30-8f79-65179ad0c092)

**Comment by pdevine** [comment]
@ovaisq feel free to comment on the PR instead of here. I'll go ahead and close the issue.
