### ISSUE TITLE
ollama._types.ResponseError

### ISSUE THREAD

**Issue by 1214summer** [ollama/ollama#7291]
### What is the issue?

~~ python test.py
import ollama
res=ollama.chat(model="qwen2.5:0.5b",stream=False,messages=[{"role": "user","content": "who are you"}],options={"temperature":0})
print(res)

Traceback (most recent call last):
  File "xxxxx", line 2, in <module>
    res=ollama.chat(model="qwen2.5:0.5b",stream=False,messages=[{"role": "user","content": "who are you"}],options={"temperature":0})
  File "xxxxx/lib/python3.10/site-packages/ollama/_client.py", line 236, in chat
    return self._request_stream(
  File "xxxxx/lib/python3.10/site-packages/ollama/_client.py", line 99, in _request_stream
    return self._stream(*args, **kwargs) if stream else self._request(*args, **kwargs).json()
  File "xxxxx/lib/python3.10/site-packages/ollama/_client.py", line 75, in _request
    raise ResponseError(e.response.text, e.response.status_code) from None
ollama._types.ResponseError

Why can't my Python code access the locally running Ollama?

curl http://localhost:11434/api/chat -d '{
  "model": "qwen2.5:0.5b",
  "messages": [
    { "role": "user", "content": "why is the sky blue?" }
  ]
}'

but this way can work

  

### OS

Linux

### GPU

Nvidia

### CPU

AMD

### Ollama version

0.3.13

**Comment by mokby** [comment]
same error, have you solved it?

**Comment by ghlxstar** [comment]
> close your vpn and try again

That's right, thank you

**Comment by ParthSareen** [comment]
Seems to be a VPN issue - closing for now. Feel free to re-open if you run into this!
