### ISSUE TITLE
0.3.14 git compile error on arm64 andro termux

### ISSUE THREAD

**Issue by fxmbsw7** [ollama/ollama#7292]
### What is the issue?

gpu_info_cudart.c:61:13: warning: comparison of different enumeration types ('cudartReturn_t' (aka 'enum cudartReturn_enum') and 'enum cudaError_enum') [-Wenum-compare]
# github.com/ollama/ollama/llama
ggml-quants.c:4023:88: error: always_inline function 'vmmlaq_s32' requires target feature 'i8mm', but would be inlined into function 'ggml_vec_dot_q4_0_q8_0' that is compiled without support for 'i8mm'
ggml-quants.c:4023:76: error: always_inline function 'vmmlaq_s32' requires target feature 'i8mm', but would be inlined into function 'ggml_vec_dot_q4_0_q8_0' that is compiled without support for 'i8mm'
ggml-quants.c:4023:64: error: always_inline function 'vmmlaq_s32' requires target feature 'i8mm', but would be inlined into function 'ggml_vec_dot_q4_0_q8_0' that is compiled without support for 'i8mm'
ggml-quants.c:4023:52: error: always_inline function 'vmmlaq_s32' requires target feature 'i8mm', but would be inlined into function 'ggml_vec_dot_q4_0_q8_0' that is compiled without support for 'i8mm'

### OS

Linux

### GPU

Other

### CPU

Other

### Ollama version

0.3.14 git

**Comment by dhiltgen** [comment]
Until we can get a fix merged, I believe it you modify https://github.com/ollama/ollama/blob/main/llama/llama.go#L37-L38 to remove `-D__ARM_FEATURE_MATMUL_INT8` it should work.

**Comment by fxmbsw7** [comment]
thank you ill try some later , ++

**Comment by fxmbsw7** [comment]
would q8_0 work still then ?

**Comment by fxmbsw7** [comment]
compiled well

**Comment by vpnry** [comment]
> Until we can get a fix merged, I believe if you modify https://github.com/ollama/ollama/blob/main/llama/llama.go#L37-L38 to remove `-D__ARM_FEATURE_MATMUL_INT8` it should work.

Thanks. It works!

**Comment by b9Joker108** [comment]
@vpnry So, the process is:
1. git clone --depth 1 https://github.com/ollama/ollama.git
2. cd ollama
3. go generate ./...
4. delete the two lines of code, as per above and write.
5. go build .
6. ./ollama serve &
7. and prosper!

Is that the go?

**Comment by fxmbsw7** [comment]
On Sun, Oct 27, 2024, 02:32 b9Joker108 ***@***.***> wrote:

> @vpnry <https://github.com/vpnry> So, the process is:
>
>    1. git clone --depth 1 https://github.com/ollama/ollama.git
>    2. cd ollama
>    3. go generate ./...
>    4. delete the two lines of code, as per above and write.
>    5. go build .
>    6. ./ollama serve &
>    7. and prosper!
>
> Is that the go?
>
cd ollama ; in the two lines , delete that last -D...word mentioned , not
the whole line
then generate and build

**Comment by vpnry** [comment]
> @vpnry @dhiltgen So, the process is:
> 
> 1. git clone --depth 1 https://github.com/ollama/ollama.git
> 2. cd ollama
> 3. go generate ./...
> 4. delete the two lines of code, as per above and write.
> 5. go build .
> 6. ./ollama serve &
> 7. and prosper!
> 
> Is that the go?

the process is:

1. git clone --depth 1 https://github.com/ollama/ollama.git

2. cd ollama

3. delete the mentioned string only (not the entire line) in 2 lines, aka  -D__ARM_FEATURE_MATMUL_INT8

4. go generate ./...
5. go build .
6. ./ollama serve &

Bonus
8. ./ollama run llama3.2:1b --verbose
9. Let the ollama server running in the background and use this font-end GUI app https://github.com/JHubi1/ollama-app

**Comment by fxmbsw7** [comment]
try adding on that line -march=armv8.7-a

or lower version
or higher
depending on ur cpu
.. i dont have a list of possible values

**Comment by Costin10** [comment]
Still doesn’t work.

> try adding on that line -march=armv8.7-a
> 
> or lower version
> or higher
> depending on ur cpu
> .. i dont have a list of possible values
> […](#)

**Comment by Costin10** [comment]
Fixed.

**Comment by fxmbsw7** [comment]
what was the error and howd u fixed it ..

**Comment by Costin10** [comment]
I had the same error as you. “gpu_info_cudart.c:61:13: warning: comparison of different enumeration types ('cudartReturn_t' (aka 'enum cudartReturn_enum') and 'enum cudaError_enum') [-Wenum-compare]”

You just ignore it and wait a bit longer to load, that worked for me.

**Comment by fxmbsw7** [comment]
its no error , its a warning ..

**Comment by asaadzx** [comment]
@fxmbsw7 am sorry do you mean in import add  -march=armv8.7-a

**Comment by fxmbsw7** [comment]
it seems they changed source much
i digg in ..

**Comment by fxmbsw7** [comment]
try

C_FLAGS=-march=armv8.7-a go build .
same with GF_C_FLAGS if first fails

**Comment by fxmbsw7** [comment]
and maybe fetch git from new

**Comment by asaadzx** [comment]
Am sorry but How can I do that ?
