### ISSUE TITLE
Better docker support

### ISSUE THREAD

**Issue by jhgoodwin** [ollama/ollama#7297]
I noticed some tools suggest to use a special hostname ( host.docker.internal ) to map back to the docker host. This works, _IF_ you setup the host to allow connections other than localhost. This generally works fine, but in Linux, when I upgrade, it tends to overwrite my OLLAMA_HOST environment variable on the service config.

Am I doing something wrong or is this a feature request to make this less painful?

Thanks for making ollama.

**Comment by rick-github** [comment]
Add your overrides to `/etc/systemd/system/ollama.service.d/override.conf`.

**Comment by jhgoodwin** [comment]
@rick-github How does that work for Environment? I want to add OLLAMA_HOST and override that, but not the path, which is pre-defined.

**Comment by rick-github** [comment]
Run `sudo systemctl edit ollama.service`.  In the space between the comments, add
```
[Service]
Environment="OLLAMA_HOST=http://<ollamaHost>:<ollamaPort>"
```
Save and exit.

**Comment by jhgoodwin** [comment]
Thank you. I was doing it the more obtuse way of directly editing the `/etc/systemd/system/ollama.service` file.
I didn't know about using systemctl edit.
