### ISSUE TITLE
Ollama 0.4.0 will produce a large number of blocks in output usage.

### ISSUE THREAD

**Issue by HougeLangley** [ollama/ollama#7299]
### What is the issue?

Ollama 0.4.0 will produce a large number of blocks in output usage.
<img width="801" alt="截屏2024-10-22 00 09 40" src="https://github.com/user-attachments/assets/b0d36873-5d88-4412-8800-c72308c6c2a5">

### OS

macOS

### GPU

Apple

### CPU

Apple

### Ollama version

0.4.0

**Comment by jessegross** [comment]
Thanks for the report - tracking this in #7290
