### ISSUE TITLE
ollama won't start as a service, will start using 'serve'?

### ISSUE THREAD

**Issue by MikeB2019x** [ollama/ollama#7317]
### What is the issue?

I am trying to run ollama after a manual install on an Ubuntu VM with no internet connectivity.  There is no GPU at the moment.
I am able to run ollama successfully from the CLI with: 
```
ollama serve
```
When I try to run ollama as a service with:
```
sudo systemctl daemon-reload
sudo systemctl enable ollama
sudo systemctl start ollama
```
ollama fails to start.  The only error is using `systemctl --failed` is:
```
  UNIT                     LOAD   ACTIVE SUB    DESCRIPTION                        
● zfs-import-scan.service loaded failed failed Import ZFS pools by device scanning
```
I assumed that if using `ollama serve` worked then the service would as well b/c both would be using the same services.

### OS

Linux

### CPU

AMD

### Ollama version

0.3.6

**Comment by rick-github** [comment]
Seems like a ZFS issue.  https://forum.proxmox.com/threads/zfs-pool-import-fails-problem-with-cache-file-how-to-fix.61925/

**Comment by MikeB2019x** [comment]
@rick-github that suggests starting ollama as a `service` uses different resources that starting ollama from `serve` ie. `zfs` isn't used when starting from the latter?

**Comment by rick-github** [comment]
I don't know anything about ZFS or how it's used in Ubuntu, but the only error we see is for ZFS so it's possible that `systemd` treats that as a primary dependency and doesn't want to run any other services until that is fixed.  You're right in your assumption that ollama doesn't require any extra resources when starting as a service, but it is reliant on the service starting service.  If you can offer more details about the version of Ubuntu, how you installed it, what other software you configured, etc, then I can have a go at replicating the problem and perhaps coming up with a solution.

**Comment by pdevine** [comment]
@MikeB2019x what's the output of `journalctl -u ollama.service`? The only service which you showed was `zfs-import-scan.service` which is unrelated to ollama.

**Comment by MikeB2019x** [comment]
@pdevine  running that gives `-- No entries --`

**Comment by rick-github** [comment]
Do you actually use ZFS?  If not, try disabling it (`sudo systemctl disable zfs-import-scan`) and then see if ollama starts.

**Comment by MikeB2019x** [comment]
@pdevine @rick-github Thank you for the quick response!  I'm going to suggest closing this.  You're right the service failure is unrelated and using `sudo journalctl -u ollama.service` has let me see what's going on.  Basically just a PATH problem.
