### ISSUE TITLE
Support loading the same model more than once

### ISSUE THREAD

**Issue by jfwreinhardt** [ollama/ollama#7321]
Are there any plans to support loading the same model more than once?  

On a CUDA based system with multiple GPUs, I have observed that performance decreases for each new concurrent prompt against the same model.  To put it another way, we see higher tokens/s for sending a prompt to four different models concurrently than if we send four prompts to the same model concurrently.

It would be helpful from a performance perspective if ollama spawned a new runner when OLLAMA_NUM_PARALLEL was reached, rather than placing all the prompts in a queue to wait on a single runner.

**Comment by dhiltgen** [comment]
More advanced scheduling support for the same model is tracked in #3902
