### ISSUE TITLE
ollama create  Error: open config.json: file does not exist

### ISSUE THREAD

**Issue by dragoncdj** [ollama/ollama#7327]
### What is the issue?

I use the create command
>ollama create mymodel2 -f D:\AI\qwen7\Modelfile
but return
Error: open config.json: file does not exist
This is my Modelfile

FROM .\export\pytorch_model.bin
PARAMETER stop <|eot|>  
PARAMETER top_p 0.9  
PARAMETER temperature 1.0

but,There is a config. json file in the same level folder as the pytorch \ model. bin file.
I don't know what the reason is, how to solve it
![微信图片_20241023092936](https://github.com/user-attachments/assets/f62c6cdc-64c5-4e27-937e-1272e579a80d)
![微信图片_202410230929326](https://github.com/user-attachments/assets/11959da6-42e1-4124-8869-ad8824da39e8)

### OS

Windows

### CPU

Intel

### Ollama version

0.3.13

**Comment by rick-github** [comment]
Try specifying the directory that the BIN file is in:
```modelfile
FROM .\export
PARAMETER stop <|eot|>
PARAMETER top_p 0.9
PARAMETER temperature 1.0
```

**Comment by pdevine** [comment]
@rick-github has the correct answer here. Use `FROM path/to/model/dir`.  If you specify `FROM file.bin` Ollama will only be able to pick up the bin file that you were specifying. Also, we don't _officially_ support converting from pytorch models, only safetensors, so converting from the pytorch weights may or may not work in the future. The problem is that we there often isn't enough information to correctly convert the model.

**Comment by fellipgomes** [comment]
very very thanks @artemavrin .

I'm use Windows 11, ollama, i changed the name adapter_model.safetensors to model.safetensors and worker. 

https://github.com/ollama/ollama/issues/13314

**Comment by powerman990** [comment]
> ### What is the issue?
> I use the create command
> 
> > ollama create mymodel2 -f D:\AI\qwen7\Modelfile
> > but return
> > Error: open config.json: file does not exist
> > This is my Modelfile
> 
> FROM .\export\pytorch_model.bin PARAMETER stop <|eot|> PARAMETER top_p 0.9 PARAMETER temperature 1.0
> 
> but,There is a config. json file in the same level folder as the pytorch \ model. bin file. I don't know what the reason is, how to solve it ![微信图片_20241023092936](https://github.com/user-attachments/assets/f62c6cdc-64c5-4e27-937e-1272e579a80d) ![微信图片_202410230929326](https://github.com/user-attachments/assets/11959da6-42e1-4124-8869-ad8824da39e8)
> 
> ### OS
> Windows
> 
> ### GPU
> _No response_
> 
> ### CPU
> Intel
> 
> ### Ollama version
> 0.3.13

**Comment by powerman990** [comment]
Incorrect (Causes the Error):dockerfile
FROM ./my-model-folder/model.safetensors ❌

Correct (Fixes the Error):dockerfile ✅
FROM ./my-model-folder
