### ISSUE TITLE
Terminate the current task after the REST request is actively ended

### ISSUE THREAD

**Issue by viosay** [ollama/ollama#7329]
Can the current executing task be terminated after a REST request is actively interrupted?

**Comment by rick-github** [comment]
Seems to do that now.  If I start `nvtop` and then run
```
curl -s localhost:11434/api/generate -d '{"model":"llama3.1","prompt":"write a long story about a unicorn lost in a rainforest"}'
```
I see GPU usage go to 90%, and drop back to 0 immediately after I ^C the curl command.  When have you observed that it doesn't do this?

**Comment by dhiltgen** [comment]
In addition to what Rick mentioned, the default timeout for models is 5 minutes, so we will stay loaded on the GPU until that timer expires so we're ready to handle additional requests.  You can unload the model immediately with the [stop command](https://github.com/ollama/ollama/blob/main/docs/faq.md#how-do-i-keep-a-model-loaded-in-memory-or-make-it-unload-immediately)
