### ISSUE TITLE
Why Does Ollama Use Shard GPU Memory Before Filling Dedicated Ones?

### ISSUE THREAD

**Issue by 0TTA** [ollama/ollama#7330]
### What is the issue?

Hi,

Is there a way to make Ollama uses more of my dedicated GPU memory? Or, can I tell it to start with the dedicated one and only switch to the shared memory if it needs to?

![2024-10-23 13_49_51-Task Manager](https://github.com/user-attachments/assets/90a70e76-45b8-44dd-94c7-b9cf7dec5462)

### OS

Windows

### GPU

AMD

### CPU

AMD

### Ollama version

0.3.14

**Comment by rick-github** [comment]
[Server logs](https://github.com/ollama/ollama/blob/main/docs/troubleshooting.md#how-to-troubleshoot-issues) might give some insight to why this is happening.

**Comment by 7shi** [comment]
From what I've investigated, this appears to be a general `hipMalloc` behavior issue when allocating more than 4GB, not specific to Ollama.
https://github.com/ollama/ollama/issues/7328

**Comment by 0TTA** [comment]
> [Server logs](https://github.com/ollama/ollama/blob/main/docs/troubleshooting.md#how-to-troubleshoot-issues) might give some insight to why this is happening.

[server.log](https://github.com/user-attachments/files/17491860/server.log)

**Comment by dhiltgen** [comment]
This looks like a dup of #7107 - the only workaround for now is to downgrade to a driver OLDER than 24.9.1 until 24.11 comes out which should have the fix.

**Comment by 0TTA** [comment]
> This looks like a dup of #7107 - the only workaround for now is to downgrade to a driver OLDER than 24.9.1 until 24.11 comes out which should have the fix.

Thank you!
