### ISSUE TITLE
Support installations in non-systemd distros

### ISSUE THREAD

**Issue by Sachin-Bhat** [ollama/ollama#7332]
Hello folks,

Kudos on this project! I wanted to install this on my system which is Artix Linux running the runit init system. Was wondering if support could be added for this.

Appreciate the assistance in advance.

Cheers,
Sachin

**Comment by rick-github** [comment]
Have you considered using docker?  It's my preferred approach since it's much easier to manage configuration and versioning.

**Comment by jmorganca** [comment]
Hi @Sachin-Bhat. Thanks for the issue (and PR). The `install.sh` script was designed to provide an opinionated install of Ollama. For additional init systems, Ollama provides an [install section](https://github.com/ollama/ollama/blob/main/docs/linux.mdx#manual-install) that should be easy to integrate. Let me know if this doesn't help and thanks again.

**Comment by argenkiwi** [comment]
Let me guess, @jmorganca's reply was written by an LLM. The install section does not mention any init systems other than systemd. A shame that the work on that PR was discarded.
