### ISSUE TITLE
Error: llama runner process has terminated: signal: aborted (core dumped)

### ISSUE THREAD

**Issue by rajach** [ollama/ollama#7334]
### What is the issue?

ollama run x/llama3.2-vision:11b-instruct-fp16
pulling manifest
pulling dae8835e9bc3... 100% ▕████████████████████████████████████████████████████████▏  19 GB
pulling 622429e8d318... 100% ▕████████████████████████████████████████████████████████▏ 1.9 GB
pulling 962e0f69a367... 100% ▕████████████████████████████████████████████████████████▏  163 B
pulling dc49c86b8ebb... 100% ▕████████████████████████████████████████████████████████▏   30 B
pulling ab4a70666dbd... 100% ▕████████████████████████████████████████████████████████▏  495 B
verifying sha256 digest
writing manifest
success
Error: llama runner process has terminated: signal: aborted (core dumped)

### OS

Linux

### GPU

Nvidia

### CPU

AMD

### Ollama version

0.3.13

**Comment by jessegross** [comment]
Sorry for the poor error message but llama3.2-vision is only supported on 0.4.0

**Comment by pdevine** [comment]
@rajach You can follow the directions in #6972 to try it out, or wait for the full `0.4.0` release.
