### ISSUE TITLE
Add 'prefix' option to chat endpoint

### ISSUE THREAD

**Issue by Smorty10** [ollama/ollama#7342]
## Problem
Limited control over output from chat endpoint
## Limitation
No formatting options besides `"format"="json"`
## Required Feature
Adding a `"prefix"` key to the chat endpoint, so we can define a prefix for the models response
## Usage
```pseudocode
var query:JSON = {
    "model":"llama3.2",
    "messages":some_conversation_defined_earlier,
    "prefix":"Here is my chain of thought:\n"
}
```
Final generated message:
```plaintext
Here is my chain of thought:
1. Split up the tasks into more managabe ones
2. Some other step
...
```

I am assuming that this is also how `"format":"json"` works: Defining a prefix for the chat response (presumably ` ```json\n{ `)
## Benefits
This feature would make ollama users able to define their own prefix formats, essentially making `"format":"json"` obsolete (it's still nice to have the option though, for backwards-compatebility and convenience).

**Comment by jmorganca** [comment]
Hi there, thanks for the issue. This can be done with the chat API by providing the beginning of an assistant message:

```
curl http://localhost:11434/api/chat -d '{
  "model": "llama3.2",
  "messages": [
    {
      "role": "user",
      "content": "why is the sky blue?"
    },
    {
      "role": "assistant",
      "content": "Here is my chain of thought:\n"
    }
  ]
}'
```

**Comment by Smorty10** [comment]
@jmorganca Is this kind of prefix also possible with the generate endpoint?

**Comment by LaneSun** [comment]
@jmorganca So how should the prefix for the chain of thought be implemented?
