### ISSUE TITLE
Aya-Expanse 32B & 8B

### ISSUE THREAD

**Issue by vYLQs6** [ollama/ollama#7343]
These models should be very easy to support since people are already uploading ggufs to HF, so it should be already supported by ollama, just need to be ggufed and uploaded

https://huggingface.co/CohereForAI/aya-expanse-32b

https://huggingface.co/CohereForAI/aya-expanse-8b

![](https://huggingface.co/CohereForAI/aya-expanse-32b/resolve/main/winrates_marenahard.png)

![](https://huggingface.co/CohereForAI/aya-expanse-8b/resolve/main/winrates_marenahard.png)

**Comment by fxmbsw7** [comment]
search for aya gguf on hf

ollama run hf.co/bartowski/aya-expanse-8b-GGUF:f16
or :Q8_0
or no :*

**Comment by BruceMacD** [comment]
Thanks for taking the time to open this issue.

I've added `aya-expanse` to our model library.
https://ollama.com/library/aya-expanse

```bash
ollama run aya-expanse
```

**Comment by jackbravo** [comment]
Nice @BruceMacD!

Hmmm, the context length for the 32b seems to be 8192 like for the 8b. Is this correct? Shouldn't it be 128k?

**Comment by fxmbsw7** [comment]
8k is the default
/set smth then urself to more
and /save to.own modelname file to.save new size
