### ISSUE TITLE
Ollama does not run on GPU at 0.4.0-rc5-rocm version 

### ISSUE THREAD

**Issue by chiehpower** [ollama/ollama#7346]
### What is the issue?

Hi all,

I was testing a very new version (`0.4.0-rc5-rocm`) that the server was deployed by docker container.
```
docker run -itd --name=ollama --gpus=all --shm-size=100GB \
    -v ollama:/root/.ollama -p 11434:11434 \
    ollama/ollama:0.4.0-rc5-rocm
```

The client was using this prompt:
```
curl http://10.1.2.10:11434/api/generate -d '{                                                                                       
  "model": "llama3.1",
  "prompt": "Why is the sky blue?",
  "stream": false,
  "options": {
    "top_k": 20,
    "temperature": 0.8
  }
}'
```
I monitored the GPU usage by `nvidia-smi` that it did not work.
However, if I changed the version to `0.3.14` (changed the docker image) then it was working fine.

### Spec

- GPU: A100

### OS

Linux

### GPU

Nvidia

### Ollama version

0.4.0-rc5-rocm

**Comment by aNyaaCaldari** [comment]
i'm using rc3, in WSL (no point change to rc5)

after upgrading driver from 565 to 566 (windows) and restart wsl i finnaly saw gpu usage for ollama

Fri Oct 25 21:09:47 2024
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 565.57.02              Driver Version: 566.03         CUDA Version: 12.7     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 4070 ...    On  |   00000000:01:00.0  On |                  N/A |
|  0%   40C    P8             15W /  285W |   15681MiB /  16376MiB |      1%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+

+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI        PID   Type   Process name                              GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|    0   N/A  N/A      4071      C   /ollama_llama_server                        N/A      |
+-----------------------------------------------------------------------------------------+

**Comment by dhiltgen** [comment]
@chiehpower ROCm is for AMD GPUs, but it looks like you have an NVIDIA GPU.  You should try `ollama/ollama:0.4.0-rc5` instead, which has the necessary components for NVIDIA.hub

**Comment by aNyaaCaldari** [comment]
> @chiehpower ROCm is for AMD GPUs, but it looks like you have an NVIDIA GPU. You should try `ollama/ollama:0.4.0-rc5` instead, which has the necessary components for NVIDIA.hub

my point was last section was empty (atm. after reinstall driver, show correctly - " C /ollama_llama_server ")
i use usual release ollama/ollama:0.4.0-rc3

when string with process was empty tasklist do not show GPU ram compsumption / 3D usage (cuda in Windows 11)
now all ok

**Comment by dhiltgen** [comment]
Happy to hear you got it working!

The rocm image is missing nvidia library support.  In the future we may improve error reporting to make this easier to detect.

**Comment by chiehpower** [comment]
Thank you all!
It works fine now!
