### ISSUE TITLE
CMD ["serve"] is wrong in Dockerfile?

### ISSUE THREAD

**Issue by YinYongHongYork** [ollama/ollama#7354]
### What is the issue?

CMD ["serve"]

### OS

Docker

### GPU

Other

**Comment by rick-github** [comment]
```dockerfile
ENTRYPOINT ["/bin/ollama"]
CMD ["serve"]
```
`ENTRYPPOINT` is the command to run, `CMD` is the argument to that command.  You can run the container with other arguments replacing `CMD`:
```console
$ docker run --rm ollama/ollama:0.3.13 help ps
List running models

Usage:
  ollama ps [flags]

Flags:
  -h, --help   help for ps

Environment Variables:
      OLLAMA_HOST                IP Address for the ollama server (default 127.0.0.1:11434)
```

**Comment by dhiltgen** [comment]
As Rick points out, this is by design to allow easy usage of the image as a client, while still defaulting to run a server if no command is specified.
