### ISSUE TITLE
Console show formation backslash chars

### ISSUE THREAD

**Issue by lsalamon** [ollama/ollama#7356]
### What is the issue?

Why any question show text not formatted at console like this:
<code>A number \\( a \\) has a multiplicative inverse modulo \\( n \\) if there exists an integer \\( b \\) such that:
\\[ (a \\cdot b) \\equiv 1 \\pmod{n} \\]</code>

Ollama Win64 0.3.14.0.
Old version 0.3.10.0 has same issue.

I noticed that sometimes, in daily use, the problem doesn't always appear.

### OS

Windows

### GPU

Other

### CPU

AMD

### Ollama version

0.3.14.0

**Comment by rick-github** [comment]
This is [Latex](https://en.wikipedia.org/wiki/LaTeX) markup.  If you put this in a [latex renderer](https://arachnoid.com/latex/?equ=%5B%20(a%20%5Ccdot%20b)%20%5Cequiv%201%20%5Cpmod%7Bn%7D%20%5D), you get a nicely formatted equation.

**Comment by lsalamon** [comment]
> This is [Latex](https://en.wikipedia.org/wiki/LaTeX) markup. If you put this in a [latex renderer](https://arachnoid.com/latex/?equ=%5B%20(a%20%5Ccdot%20b)%20%5Cequiv%201%20%5Cpmod%7Bn%7D%20%5D), you get a nicely formatted equation.

Your tip is useful, but I need the text output in the console to be without formatting characters.

**Comment by rick-github** [comment]
This is how the model was trained.  You can try telling it to not use latex in the prompt that you give it, or in the system message.  Which model are you using?

**Comment by lsalamon** [comment]
> This is how the model was trained. You can try telling it to not use latex in the prompt that you give it, or in the system message. Which model are you using?

Today is qwen2-math:72b.
Just yesterday I got the answers correctly!

**Comment by rick-github** [comment]
Models answer on a probabilistic basis, unless you set the `seed` and `temperature` you will always get variations in the answers.

**Comment by lsalamon** [comment]
> Models answer on a probabilistic basis, unless you set the `seed` and `temperature` you will always get variations in the answers.

Ok. How I set this on my case?

**Comment by rick-github** [comment]
```
/set parameter seed 1
/set parameter temperature 0
```
This will reduce the variability in the responses but it won't make the model stop using latex.  If the model was trained with data in latex format, that's how it's going to respond.

**Comment by lsalamon** [comment]
> ```
> /set parameter seed 1
> /set parameter temperature 0
> ```
> 
> This will reduce the variability in the responses but it won't make the model stop using latex. If the model was trained with data in latex format, that's how it's going to respond.

What could cause responses to not always contain Latex formatting characters?

**Comment by rick-github** [comment]
Models answer on a probabilistic basis.  Some of the training data was in latex format, some wasn't.  Sometimes the answer will be based on the latex data, sometimes not.

**Comment by lsalamon** [comment]
> > ```
> > /set parameter seed 1
> > /set parameter temperature 0
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > This will reduce the variability in the responses but it won't make the model stop using latex. If the model was trained with data in latex format, that's how it's going to respond.
> 
> What could cause responses to not always contain Latex formatting characters?

Setting the parameters stabilized the responses without markers.
