### ISSUE TITLE
Llama3.2-vision image processing not implemented for /generate

### ISSUE THREAD

**Issue by jessegross** [ollama/ollama#7362]
### What is the issue?

Reported by @oderwat:
https://github.com/ollama/ollama/issues/6972#issuecomment-2437586368

### Ollama version

0.4.0

**Comment by chiehpower** [comment]
Hi @jessegross 

Could I confirm that currently only `/api/chat` is working properly, while `/api/generate` is not functioning as expected?

Thank you so much.

**Comment by pdevine** [comment]
@chiehpower that's correct. You can try PR #7384 to test out the `/api/generate` handler.

**Comment by chiehpower** [comment]
Got it. Thank you so much!

**Comment by oderwat** [comment]
This was merged into "main", and when compiling main this does not work for me when using 'llama-3.2-vision' neither with chat nor with generate.

```
key clip.has_text_encoder not found in file
terminate called after throwing an instance of 'std::runtime_error'
  what():  Missing required key: clip.has_text_encoder
```

I believe that this needs to be merged with v0.4.0-rc5 and get a v0.4.0-r6 to be useable or is the plan to rebase the v0.4.0 code and then create the new release candidate for v0.4.0?

Or did I understand something wrong?

**Comment by jessegross** [comment]
You need to build according to the instructions here in order to support llama3.2-vision:
https://github.com/ollama/ollama/blob/main/docs/development.md#transition-to-go-runner

**Comment by oderwat** [comment]
@jessegross thank you!

For reference: I am on WSL2 with RTX 3090 TI, and it builds (and uses CUDA) with this build script:

```
#!/bin/bash
echo "Setting limit higher for mlock to work"
limit=8413752832
sudo prlimit --memlock=$limit:$limit --pid $$

git fetch
git checkout main
export LIBRARY_PATH=/usr/lib/wsl/lib
make -C llama -j 4
go build .
# run it for unlimited use in my private network
OLLAMA_HOST=0.0.0.0:11434 OLLAMA_ORIGINS="*" ./ollama serve
```

**Comment by oderwat** [comment]
Using this I could update my [capollama](https://github.com/oderwat/capollama) to use the generate API  👍
