### ISSUE TITLE
Default CPU or GPU for Models

### ISSUE THREAD

**Issue by devbate** [ollama/ollama#7363]
Hi there,

It would be nice to see a feature that allows users to set default CPU or GPU usage for specific models in Ollama. For instance, a 1.5 code completion model could default to CPU, while larger chatbot models use the GPU.

Additionally, having the option to set specific sleep times for each model would help with resource management.

Thank you

**Comment by rick-github** [comment]
You can make a model load on the CPU by setting `num_gpu` to zero: https://github.com/ollama/ollama/issues/6950#issuecomment-2373663650
