### ISSUE TITLE
crash after OLLAMA_MULTIUSER_CACHE=1

### ISSUE THREAD

**Issue by y-tor** [ollama/ollama#7372]
### What is the issue?

When I start loading a model, such as granite3-dense, I get this error:

error: unknown argument: --multiuser-cache
usage: /usr/lib/ollama/runners/cuda_v12/ollama_llama_server [options]

### OS

Linux

### GPU

Nvidia

### CPU

Intel

### Ollama version

0.3.14

**Comment by jessegross** [comment]
This is intended only for development use cases (which is why it was left undocumented). It won't work in the mode you are running it in.
