### ISSUE TITLE
Is there a way to track tokens/context window in real-time? 

### ISSUE THREAD

**Issue by robotom** [ollama/ollama#7376]
I'd like to implement a counter in a front end app to track the tokens used in order to see if I'm close to exceeding the context window. 

This is useful to me because if I feed a large document into the model, I'd like to know when it's "too large" and perhaps to break it down or do something else.

**Comment by rick-github** [comment]
[prompt_eval_count](https://github.com/ollama/ollama/blob/main/docs/api.md#generate-a-completion:~:text=loading%20the%20model-,prompt_eval_count), returned in the response, counts the tokens in the request.  There's no way to incrementally update a prompt.  There's an open issue, https://github.com/ollama/ollama/issues/3582, to add a tokenizer endpoint that would allow a client to count tokens before sending a completion.

**Comment by rick-github** [comment]
Note that if your model was derived from one on HuggingFace, you can count the tokens in the client:
```python
#!/usr/bin/env python3

from transformers import AutoTokenizer

model = "CohereForAI/aya-expanse-8b"
messages = [ { "role":"user", "content":"hello world" } ]

autotokenizer = AutoTokenizer.from_pretrained(model)
autotokens = autotokenizer.apply_chat_template(messages)

print(autotokens)
print(len(autotokens))
print(autotokenizer.decode(autotokens))
```
```console
$ ./7376.py 
[5, 255000, 255006, 34313, 3845, 255001]
6
<BOS_TOKEN><|START_OF_TURN_TOKEN|><|USER_TOKEN|>hello world<|END_OF_TURN_TOKEN|>
```
Be aware that the template applied by ollama may be different to the template in the HuggingFace model config, so the token count between AutoTokenizer and ollama may differ slightly.
