### ISSUE TITLE
v0.3.13: fatal: not a git repository (or any of the parent directories): .git

### ISSUE THREAD

**Issue by vt-alt** [ollama/ollama#7385]
### What is the issue?

Commit f9584deba5d7faa1ff547fca5ea4e19818394de8 tries to clean up submodule even with `OLLAMA_SKIP_PATCHING=1`, breaking builds w/o the full git tree setup (for example when we build a package for a downstream distribution such as ALT as in my case).

Maybe in that case you can do `(cd ${LLAMACPP_DIR}/ && git checkout -f)` similar to what was before? Or maybe some other git-less method?

ps. For a context, currently, I setup a 'fake' git repo when building ollama (excerpt from RPM spec):
```
tar xf %SOURCE1 -C llm
tar xf %SOURCE2 -C llm/llama.cpp/ggml/src
cd llm/llama.cpp
git init -q
git config user.name "$USER"
git config user.email "$USER"
git add -Af .
git commit -q -m "$PWD"
git tag "%version-%release"
```
So `git checkout` would work for me but `git submodule update` will not. Also, we do reproducible builds in network-less build nodes so updating from remote is not available by design.

### OS

Linux

### GPU

Other

### CPU

Intel, AMD, aarch64

### Ollama version

v0.3.13

**Comment by dhiltgen** [comment]
We'll be removing the submodule soon with #7517 which will make the build process much cleaner.

**Comment by dhiltgen** [comment]
We've merged the PR that removes the submodule, so this should be resolved now.  If you still have any problems with building on main now, let us know and I'll reopen.
