### ISSUE TITLE
Llama3.2-vision - fails to process png files

### ISSUE THREAD

**Issue by pitimespi** [ollama/ollama#7388]
### What is the issue?

Couldn't process image: "invalid image type: application/octet-stream"
Error: invalid image type: application/octet-stream

### OS

Linux

### GPU

Nvidia

### CPU

AMD

### Ollama version

3.2-vision 0.4.0-rc5

**Comment by pitimespi** [comment]
Also get this error on some jpg files as well:

```
Couldn't process image: "invalid image type: image/webp"
Error: invalid image type: image/webp

```

**Comment by rick-github** [comment]
How are you calling the model?
```console
$ file puppy.png
puppy.png: PNG image data, 366 x 555, 8-bit/color RGB, non-interlaced
$ (echo '{"model":"x/llama3.2-vision","messages":[{"role":"user","content":"describe this image","images":["' ; base64 -w0 puppy.png ; echo '"]}],"stream":false}') | curl -s localhost:11434/api/chat -d @- | jq
{
  "model": "x/llama3.2-vision",
  "created_at": "2024-10-28T00:21:18.795239901Z",
  "message": {
    "role": "assistant",
    "content": "The image features a small, white puppy sitting on a stone surface. The puppy is positioned in the center of the frame and faces to the right, with its head slightly turned towards the camera. It has short, fluffy fur that appears to be either pure white or very light-colored, making it difficult to discern any darker markings.\n\nThe puppy's ears are folded back against its head, giving it a cute and endearing appearance. A small red collar encircles its neck, adorned with a shiny gold bell that adds a touch of elegance to the overall scene.\n\nIn the background, the stone surface on which the puppy is sitting provides a subtle yet rustic contrast to the puppy's soft fur. The image is well-lit, suggesting that it was taken outdoors during the daytime or in a brightly lit indoor setting. Overall, the image presents a charming and intimate portrait of a small white puppy, capturing its innocence and playfulness."
  },
  "done_reason": "stop",
  "done": true,
  "total_duration": 5857875161,
  "load_duration": 32072587,
  "prompt_eval_count": 13,
  "prompt_eval_duration": 1994000000,
  "eval_count": 186,
  "eval_duration": 3742000000
}
```

**Comment by pitimespi** [comment]
ollama run x/llama3.2-vision:latest "Describe image:  <path_to_image>

I have this working for some jpeg files.

**Comment by rick-github** [comment]
There's an issue with passing image files via the CLI: https://github.com/ollama/ollama/issues/7386

**Comment by pitimespi** [comment]
Hmm..  This is getting even more interesting.

File 1
`ISO Media, HEIF Image HEVC Main or Main Still Picture Profile`

So, I saved it as .png and `file <converted file>`:
`PNG image data, 3088 x 2320, 8-bit/color RGB, non-interlaced`

And send it to ollama:
```
ollama run x/llama3.2-vision:latest "Describe image: <..>"
Added image '<..>'
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!


```
The output is just a bunch of `!`

File 2:
Yes, it turned out to be a webp file.
`RIFF (little-endian) data, Web/P image, VP8 encoding, 1024x1024, Scaling: [none]x[none], YUV color, decoders should clamp`

I saved it as .jpg:
`JPEG image data, JFIF standard 1.01, aspect ratio, density 1x1, segment length 16, baseline, precision 8, 1024x1024, components 3`

Ollama output:
```
Error: POST predict: Post "http://127.0.0.1:39043/completion": EOF
```

I am using ImageViewer on Ubuntu 24 to convert.  Maybe this tool is no good?  I am getting decent results on a few other jpeg and png images.  I think I just happen to be feeding images of question source to Ollama.  The ones that work fine are ones that I downloaded from my own camera.

**Comment by mchiang0610** [comment]
@pitimespi Sorry about this. Do you have the image itself for us to test? 

The error is showing that it is a webp image not a PNG. 

Would love to get the converted JPEG from you.

**Comment by pitimespi** [comment]
![image1_converted](https://github.com/user-attachments/assets/06b1e0a8-1c49-4792-8fc1-82f821a004cf)

**Comment by rick-github** [comment]
Does it work better if you use the interactive mode?
```sh
$ ollama run x/llama3.2-vision:latest
>>> Describe image: <path_to_image>
```
Might be related to https://github.com/ollama/ollama/issues/7362.

**Comment by pitimespi** [comment]
> Does it work better if you use the interactive mode?

No.

**Comment by pitimespi** [comment]
When I get `Error: POST predict: Post "http://127.0.0.1:39043/completion": EOF`, I ran `journalctl -u ollama --no-pager` which showed `ollama[1983902]: [GIN] 2024/10/27 - 20:14:37 | 200 |  2.946318763s |       127.0.0.1 | POST     "/api/generate"` which seems to confirm that the issue is in fact related to #7362.

**Comment by pitimespi** [comment]
Hitting /api/chat directly and passing base64 encoded strings worked for all images!  Should I just close this as a dup of 7362 then?

**Comment by rick-github** [comment]
Interactive mode uses `/api/chat` so if you are still seeing problems there might be something else, so perhaps not a dupe of #7362.

**Comment by rick-github** [comment]
It's returned from the runner:
https://github.com/ollama/ollama/blob/084929c29318c6a6604f1b01eb0a782cb31242ba/llm/server.go#L764
```console
$ ollama:0.4.0-rc5 run x/llama3.2-vision describe this image: ./puppy.jpg
Added image './puppy.jpg'
Error: POST predict: Post "http://127.0.0.1:45799/completion": EOF
```

**Comment by oderwat** [comment]
I think this is exactly the same as #7362

**Comment by rick-github** [comment]
Austin indicates in https://github.com/ollama/ollama/issues/7388#issuecomment-2440385959 that his problem is not fixed by using 3.

**Comment by oderwat** [comment]
@rick-github Well, maybe he could double-check that. Using https://github.com/ollama/ollama/issues/7362#issuecomment-2442862378 I can run jpg and png just fine.

**Comment by pitimespi** [comment]
I can confirm I no longer have the issues I mentioned above (well, I can work around them now).

**Comment by pitimespi** [comment]
Closing as all the remaining issues are known issues and are tracked elsewhere.
