### ISSUE TITLE
Ollama3.2-vision keeps answering using the previous image

### ISSUE THREAD

**Issue by pitimespi** [ollama/ollama#7390]
### What is the issue?

Somehow it just gets stuck with the first image.  Anyone else seeing this?

### OS

Linux

### GPU

Nvidia

### CPU

AMD

### Ollama version

3.2-vision 0.4.0-rc5

**Comment by rick-github** [comment]
If you are using the CLI, try running `/clear` between prompts.

**Comment by pitimespi** [comment]
Yes, that helped.

**Comment by dhiltgen** [comment]
Fixed in RC8.
