### ISSUE TITLE
ollama -v return 2version one is 0.0.0 the other is client version 0.3.14

### ISSUE THREAD

**Issue by FanGShiYuu** [ollama/ollama#7391]
### What is the issue?

i am using ubuntu20.04；install ollama through curl -fsSL https://ollama.com/install.sh | sh； when input ollama -v return ollama version is 0.0.0
Warning: client version is 0.3.14
btw, when using ollama, i notice my gpu is not used and the response is so slow

### OS

Linux

### GPU

Nvidia

### Ollama version

0.3.14

**Comment by rick-github** [comment]
Did you previously compile ollama from source?  That's usually the reason for the server returning version 0.0.0.  What do the [server logs](https://github.com/ollama/ollama/issues/7362) show?

**Comment by FanGShiYuu** [comment]
i use sudo rm $(which ollama) to remove ollama from my computer, then use curl -fsSL https://ollama.com/install.sh | sh
 to install it, after it. i use ollama -v but return ollama version is 0.0.0 Warning: client version is 0.3.14 :(

**Comment by rick-github** [comment]
What do the [server logs](https://github.com/ollama/ollama/blob/main/docs/troubleshooting.md) show?   What is the output of the following commands:
```
ps wwufax | grep '[o]llama'
env | grep OLLAMA
```

**Comment by jmorganca** [comment]
Have you built Ollama from source? Make sure to see which `ollama` binary is running (using Rick's example) and then remove that version, and it should all work ok – let me know if you hit any more issues.
