### ISSUE TITLE
Why is the performance of x/llama3.2-vision for describing images poor?

### ISSUE THREAD

**Issue by hosea7456** [ollama/ollama#7395]
### What is the issue?

I am experiencing x/llama3.2-vision(11b) using ollama-0.4.0-rc5, but the performance is poor compared to the [official version](https://deepinfra.com/meta-llama/Llama-3.2-11B-Vision-Instruct). What causes this result?
**x/llama3.2-vision:**
![image](https://github.com/user-attachments/assets/c02cf985-59c0-4cd3-bccc-9ac7a3a19efa)
**meta-llama:**
![image](https://github.com/user-attachments/assets/e6c0b2dc-f8aa-465d-8bea-1a0b98704daf)
**image:**
![cars](https://github.com/user-attachments/assets/d8ac625e-86c7-47f4-a45d-9a56dc5eeb73)

### OS

Linux

### GPU

Nvidia

### CPU

Intel

### Ollama version

0.4.0-rc5

**Comment by rick-github** [comment]
My guess would be that the official version is unquantized.  x/llama3.2-vision is experimental, when it's promoted to the main ollama library it should perform better.

**Comment by hosea7456** [comment]
> My guess would be that the official version is unquantized. x/llama3.2-vision is experimental, when it's promoted to the main ollama library it should perform better.

That should be the reason. Many thanks.

**Comment by step21** [comment]
On a similar issue - I just tried two images from my download folder - for one that is a pencil drawing without anything particularly salacious, it steadfastly refused, always saying sth like "I cannot engage in this topic". When I asked it to elaborate, it also just repeated a similar message.  Did anybody else experience sth like that?

**Comment by pdevine** [comment]
I think we can close this out since `x/llama3.2-vision` was just for the RC versions. The model isn't perfect, unfortunately, and still does hallucinate occasionally.

**Comment by step21** [comment]
@pdevine is there a new version now?

**Comment by pdevine** [comment]
@step21 Yes, see the [blog post](https://ollama.com/blog/llama3.2-vision). The models are now called `llama3.2-vision` (without the `x/` on the front). The weights did change, so you'll unfortunately need to pull them again.

**Comment by step21** [comment]
ok, thx. though I just noticed I only used the new one without x/ anyway. Sorry, didn't realize this was for a previous version. It still does the behaviour I described anyway, but still ok to close this thread.
