### ISSUE TITLE
set gpu/cpu affinity per-model

### ISSUE THREAD

**Issue by xucian** [ollama/ollama#7399]
is it possible to set the target device (gpu0, gpu1, cpu) per-model? that'd be a game-changer as we could offload smaller models to cpu while keeping bigger models on gpu
basically preventing the warmup

**Comment by rick-github** [comment]
Not currently.  #3902 tracks the work on model management, but there has been little progress so far.  As a limited workaround, you can force a model on to CPU by specifying `num_gpu` as zero, see https://github.com/ollama/ollama/issues/6950#issuecomment-2373663650 for details.
