### ISSUE TITLE
Configure docker image to start with some models installed

### ISSUE THREAD

**Issue by fnacarellidev** [ollama/ollama#7401]
I think it would be very nice if we had an option to install some models on the build stage of the ollama docker image, right now I have 2 workarounds to emulate this behaviour:

1. Have an init container that talks to the ollama container and installs the models, not very good because I can't cache that, so everytime I restart the kubernetes environment it has to reinstall each model, which might take long depending on the environment.

2.
```dockerfile
FROM ollama/ollama

RUN nohup bash -c "ollama serve &" && wait4x http http://127.0.0.1:11434 && ollama pull llava && ollama pull llama3
```

However the 2nd option is not working very well, when I install the models in that way every request take a lot of time to finish, and sometimes it doesn't finishes, it simply hangs, not sure if there's something wrong with the logic, I copied from the #957 issue.

**Comment by rick-github** [comment]
https://github.com/ollama/ollama/issues/7046
