### ISSUE TITLE
how to use two CPUs

### ISSUE THREAD

**Issue by pizixi** [ollama/ollama#7410]
I have two CPUs and no GPU. I only want to run the 7b model. Currently, it seems that Olama can only call one CPU. How to make it call two CPUs to improve the response speed

**Comment by kth8** [comment]
The response speed is most likely going to be limited by your memory bandwidth, not your core count.

**Comment by dhiltgen** [comment]
@pizixi can you clarify if you mean you have a dual socket NUMA system?  If so, this is a dup of #2929 (linux) or #2936 (windows)

**Comment by dhiltgen** [comment]
If this wasn't a NUMA ask, please clarify what you mean and I'll reopen the issue.  (what OS, what CPUs do you have, server log and other system metrics showing the incomplete usage of the CPUs, etc.)
