### ISSUE TITLE
When will function calling stream response be supported

### ISSUE THREAD

**Issue by yiniesta** [ollama/ollama#7415]
As the title suggests, do you have a specific planned time? This will be a very useful feature

**Comment by rick-github** [comment]
https://github.com/ollama/ollama/pull/6452

**Comment by yiniesta** [comment]
@rick-github Thank you for the guidance, but I'm sorry, I didn't understand its meaning. Has it been released to a new version or has the code not been merged yet?

**Comment by rick-github** [comment]
Not merged yet.
