### ISSUE TITLE
Optimizing Single Inference Performance on Distributed GPUs with Ollama’s Parallel Inference

### ISSUE THREAD

**Issue by jibinghu** [ollama/ollama#7416]
Hey guys,

I have a server with dual A100 GPUs and a server with a single V100 GPU. Knowing the IP addresses, ports, and passwords of both servers, I want to use Ollama’s parallel inference functionality to perform a single inference request on the llama3.1-70B model. How can I achieve optimal performance for a single request when using Ollama for inference? Do I need to use MPI or other distributed methods? Will this make the model inference faster?

Thanks.

**Comment by rick-github** [comment]
https://github.com/ollama/ollama/issues/7104

**Comment by jibinghu** [comment]
已收到，谢谢。

**Comment by rick-github** [comment]
One of the points of #7104 is that multi-gpu, whether on one server or more, will not significantly speed up a single inference request.  If you want to experiment with distributed inference, see https://github.com/ollama/ollama/pull/6729.  Other than [`OLLAMA_NUM_PARALLEL`](https://github.com/ollama/ollama/blob/db1842b9e1272237947d427c852c38e48688dd02/envconfig/config.go#L247) and [`OLLAMA_SCHED_SPREAD`](https://github.com/ollama/ollama/blob/db1842b9e1272237947d427c852c38e48688dd02/envconfig/config.go#L249), stock ollama has no configuration options for this sort of setup.

**Comment by jibinghu** [comment]
Alright, I will continue working on #6729. Thank you for your help. I will close this issue.
