### ISSUE TITLE
Model loaded to RAM and not VRAM

### ISSUE THREAD

**Issue by johanesalxd** [ollama/ollama#7425]
### What is the issue?

![image](https://github.com/user-attachments/assets/0b0cad75-7e33-4b6b-8f76-8dc5f9f95b7c)
[server.log](https://github.com/user-attachments/files/17576314/server.log)
[lmstudio-issues](https://discord.com/channels/1110598183144399058/1294935199892639834)
[complete-specs](https://pcpartpicker.com/b/yDZZxr)

Model loaded to the RAM and not VRAM (7900 XTX), hence the performance is slow. I'm using Adrenalin 24.10.1 and having the same issue on other app as well (LM Studio) but I'm able to _downgrade it's runtime_ so its running properly again.

![image](https://github.com/user-attachments/assets/0d8985f2-0535-4f4c-82da-0d0b7a961756)

### OS

Windows

### GPU

AMD

### CPU

AMD

### Ollama version

0.3.14

**Comment by dhiltgen** [comment]
Known regression in the recent AMD drivers which should be fixed in 24.11.1

We're tracking this in #7107
