### ISSUE TITLE
x/llama3.2-vision on cli reports only "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!" but works in ollama run

### ISSUE THREAD

**Issue by draeician** [ollama/ollama#7426]
### What is the issue?

draeician@nomnom ~/Downloads $ ollama run x/llama3.2-vision "Describe the image in detail: /home/draeician/Downloads/test.jpg"
Added image '/home/draeician/Downloads/test.jpg'
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

But if I run it through the interactive:
draeician@nomnom ~/Downloads $ ollama run x/llama3.2-vision 
>>> Describe the image in detail:   /home/draeician/Downloads/test.jpg
Added image '/home/draeician/Downloads/test.jpg'
The image shows a sketch of a female character from an anime or manga, with long hair and wearing a jacket. The purpose of the image is to showcase the artist's work.

* A sketch of a female character from an anime or manga:
        + The character has long hair that flows behind her.
        + She is wearing a jacket with a high collar.
        + Her facial expression is serious and determined.
* The character is wearing a jacket with a high collar:
        + The jacket is dark-colored and has a sleek design.
        + It covers most of the character's body, leaving only her arms and legs visible.
        + The high collar adds to the character's mysterious and intimidating appearance.
* She has long hair that flows behind her:
        + Her hair is dark brown and falls down her back in loose waves.
        + It frames her face and accentuates her features.
        + The flowing hair adds a sense of elegance and sophistication to the character's overall look.

Overall, the image showcases a well-drawn female character with a strong and mysterious presence. The artist has paid attention to detail in rendering the character's facial expression, clothing, and hairstyle, creating a compelling and engaging 
visual representation.

Works fine.  Tried png and jpg files, and all on the cli returned nothing but '!'

### OS

Linux

### GPU

Nvidia

### CPU

AMD

### Ollama version

0.4.0-rc5

**Comment by rick-github** [comment]
https://github.com/ollama/ollama/issues/7388#issuecomment-2442637658

**Comment by jessegross** [comment]
This is another manifestation of #7362 which has been fixed in `main` if you build from source or will be included in the next RC.
