### ISSUE TITLE
Feature Request: count tokens before calling '/v1/chat/completions'

### ISSUE THREAD

**Issue by GPTLocalhost** [ollama/ollama#7447]
Recently, we integrated Microsoft Word with Ollama through a local Word Add-in. You can view a demo [here](https://gptlocalhost.com/demo/). We're planning to add a feature to count tokens before calling '/v1/chat/completions,' allowing users to see the remaining tokens available for inference. Our question is: Is it possible for Ollama to count the tokens of the prompt before calling '/v1/chat/completions'? Thank you for your advice.

**Comment by rick-github** [comment]
https://github.com/ollama/ollama/issues/3582

With a little effort, you can count tokens in the client if #3582 doesn't get merged: https://github.com/ollama/ollama/issues/7376#issuecomment-2439749060
