### ISSUE TITLE
Dual GPU token generation bug on 0.3.15 that did not exist on 0.3.13

### ISSUE THREAD

**Issue by calmingaura** [ollama/ollama#7461]
### What is the issue?

I have two separate Windows 11 systems, each with dual Radeon 7900XTX 24GB VRAM GPUs  for inferencing using 70b parameter models.  When running Ollama using the command line interface on 0.3.13, both systems worked great.  However, switching to 0.3.15 cause generation of gibberish on the CLI, with a lot of ///////////////*he//them//// .....  When I switched back to 0.3.13, the problem was fixed.  This bug is repeatable on both systems which have slightly different configurations, so I'm pretty sure it is the update.  When I run a small model and it loads only into one GPUs VRAM, there is no problem on 0.3.13 or 0.3.15.  Thanks!

### OS

Windows

### GPU

AMD

### CPU

Intel

### Ollama version

0.3.13 and tried 0.3.15

**Comment by rick-github** [comment]
Do you mean 0.3.14?  [Server logs](https://github.com/ollama/ollama/blob/main/docs/troubleshooting.md#how-to-troubleshoot-issues) from both versions might also help in debugging.
