### ISSUE TITLE
WINDOWS版本的OLLAMA配置文件在哪里？？？我想把CPU运行改成GPU，我的显卡是NVIDIA A5000，DOCKER方法并没有起作用，或者我要怎么把CPU运行改成GPU运行

### ISSUE THREAD

**Issue by NXL333** [ollama/ollama#7462]
### What is the issue?

WINDOWS版本的OLLAMA配置文件在哪里？？？我想把CPU运行改成GPU，我的显卡是NVIDIA A5000，DOCKER方法并没有起作用，或者我要怎么把CPU运行改成GPU运行

### OS

Windows

### GPU

Nvidia

### CPU

Intel

### Ollama version

0.3.14

**Comment by rick-github** [comment]
ollama will use GPU automatically.  If it's not working for you, [server logs](https://github.com/ollama/ollama/blob/main/docs/troubleshooting.md#how-to-troubleshoot-issues) may help in debugging.

**Comment by NXL333** [comment]
可以配置使用GPU吗

**Comment by NXL333** [comment]
谢谢

**Comment by rick-github** [comment]
It will use the GPU automatically if it's available.  If it doesn't work for you, [server logs](https://github.com/ollama/ollama/blob/main/docs/troubleshooting.md#how-to-troubleshoot-issues) may help in debugging.

**Comment by NXL333** [comment]
你真好，谢谢
