### ISSUE TITLE
PC crashes when running ollama

### ISSUE THREAD

**Issue by mrohner** [ollama/ollama#7463]
### What is the issue?

I try to run ollama in WSL (Ubuntu) under Windows10 with a newly installed GPU . The PC crashes and the PC and ultimately Windows restarts.

Windows nvidia Driver Version: 32.0.15.6590

nvidia-smi -L
GPU 0: NVIDIA GeForce RTX 2060 (UUID: GPU-....)

 nvidia-smi
Fri Nov  1 11:12:05 2024
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.120                Driver Version: 565.90         CUDA Version: 12.7     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 2060        On  |   00000000:01:00.0  On |                  N/A |
| 29%   32C    P8             15W /  160W |     688MiB /   6144MiB |     16%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+

+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI        PID   Type   Process name                              GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|    0   N/A  N/A       247      C   /ollama                                     N/A      |
|    0   N/A  N/A       318      G   /Xwayland                                   N/A      |
+-----------------------------------------------------------------------------------------+

### OS

Linux, Windows

### GPU

Nvidia

### CPU

Intel

### Ollama version

0.2.7

**Comment by rick-github** [comment]
Have you tried using a more recent version of ollama?

**Comment by mrohner** [comment]
Ok, tried 0.3.14 . same effects

**Comment by rick-github** [comment]
Does it crash when the server starts or when a model is loaded?  Does it crash if Xwayland is not running?  Does it work any better if you use the native Wndows version of ollama?

**Comment by dhiltgen** [comment]
I presume there's a BSOD involved in the crash.  Ultimately this is likely to be a driver bug, but it could be in Windows code on the host, in the WSL VM, NVIDIA drivers, or something else.  Hopefully that BSOD gives some indication on which driver caused the crash, and if you have an option to upload the results, please do so.

**Comment by mrohner** [comment]
As suggested by Rick I installed ollama under Windows and tried from there. AT least in this environment I can do an "ollama run llama2" the PC crashes after I enter a first question. It is a hard crash, so no Windows blue screen. The PC restarts with a boot.
Before the crash it looks all good (see pic). Any ideas welcome
![Before crash](https://github.com/user-attachments/assets/c99ebc14-763f-493e-a003-66c2a92b5498)

**Comment by mrohner** [comment]
I also installed FurMark to test the GPU and the system restarts also when I try to run the test. I guess this is not an ollama issue then. I will try to get some help from nvidia sources. Thanks anyway

**Comment by juanpide** [comment]
I have installed Ollama v0.13.5 in Windows 11, with a Ryzen 9950x3d, nVidia 5070Ti and 128GB DDR5.
And when I launch the program it makes Windows crash completely.
But my computer is completely stable with other programs, games, stress tests...
