### ISSUE TITLE
Pointer error on latest RC: unsafe.Slice: ptr is nil and len is not zero - llama.go:348

### ISSUE THREAD

**Issue by samchouse** [ollama/ollama#7464]
### What is the issue?

Trying to run the new vision model produces a pointer error. I'm using the latest Docker RC tag.

[ollama.log](https://github.com/user-attachments/files/17600147/ollama.log)

### OS

Linux

### GPU

Nvidia

### CPU

Intel

### Ollama version

ollama version is 0.4.0-rc6 Warning: client version is 0.3.12

**Comment by jessegross** [comment]
This should now be fixed in RC8

**Comment by samchouse** [comment]
Everything seems to be working now, thank you!
