### ISSUE TITLE
Cannot generate id_ed25519 - read-only file system

### ISSUE THREAD

**Issue by duhow** [ollama/ollama#7471]
### What is the issue?

Running the service `systemctl start ollama` cannot run due to **immutable system** , using https://github.com/ublue-os/bazzite . User `ollama` with default `$HOME` in `/usr/share/ollama` cannot write there.

Performed normal setup with `sudo` rather than user-based.

```sh
curl -fsSL https://ollama.com/install.sh | sudo sh
```

:memo: Output:

```
nov 02 10:34:04 geekom ollama[227009]: Couldn't find '/usr/share/ollama/.ollama/id_ed25519'. Generating new private key.
nov 02 10:34:04 geekom ollama[227009]: Error: could not create directory mkdir /usr/share/ollama: read-only file system

    Process: 241387 ExecStart=/usr/local/bin/ollama serve (code=exited, status=1/FAILURE)
   Main PID: 241387 (code=exited, status=1/FAILURE)

```

### OS

Linux

### GPU

AMD

### CPU

AMD

### Ollama version

0.3.14

**Comment by rick-github** [comment]
Add `HOME=/some/path/in/writeable/file/system` to the [server environment](https://github.com/ollama/ollama/blob/main/docs/faq.md#how-do-i-configure-ollama-server).

**Comment by duhow** [comment]
As a workaround, I can modify the `home` of the user `ollama` in `/etc/passwd` to wherever I need, but the setup did not fail when creating the home directory.

**Comment by kth8** [comment]
Bazzite has `podman` installed by default so you can use that to run Ollama as a substitute for Docker. It also includes `distrobox` which is a wrapper for `podman`.  Applications in Bazzite are installed using flatpaks so you can use [Alpaca](https://flathub.org/apps/com.jeffser.Alpaca) which has a built in Ollama instance. Another option is to install Ollama manually as your local user by downloading and extracting the `ollama-linux-amd64.tgz` tarball.

**Comment by nikhil-swamix** [comment]
will `chmod +w path...` work? or it is not writable by some other rules?
or add ollama user to your ssh user group?
