### ISSUE TITLE
GPU on WIndows

### ISSUE THREAD

**Issue by godlatro** [ollama/ollama#7472]
### What is the issue?

I have latest Ollama desktop
Nvidia 3060
Windows 10

Try to use any models, CPU/GPU loading ~70%/20%
I load many models one by one.
I unload the extra ones with ```ollama stop model```

Almost all models work terribly slowly. In 90% of cases, the models can't even finish writing their answer and are interrupted every time when using the web interface open-webui on docker.
But when I running Ubuntu 24 on this computer, it shows 100% loading my GPU and all models work perfectly fast.
How can I make Windows also use 100% GPU like in ubuntu?

### OS

Windows

### GPU

Nvidia

### CPU

Intel

### Ollama version

0.1.32

**Comment by rick-github** [comment]
Other applications in Windows may be using the GPU, leaving less room for ollama.  [Server logs](https://github.com/ollama/ollama/blob/main/docs/troubleshooting.md#how-to-troubleshoot-issues) may help with diagnosis, along with the output of `nvidia-smi`.

**Comment by godlatro** [comment]
It seems that this is not a problem of ollama. It is open-webui that loads models differently than ollama. In the console, ollama loads the model in the GPU

**Comment by godlatro** [comment]
ollama for windows loads GPU 100% in terminal like in linux, but some models like starcoder2 not work or say nothing useful

**Comment by rick-github** [comment]
open-webui is probably using a bigger context window than the default one of 2048 tokens.

starcoder2 is generally not a chat model, it's used for FIM (fill in the middle) for completing code.  starcoder2:instruct has a chat mode, but only about code.
