### ISSUE TITLE
Ollama uses more ram when trying to load a model for Zed

### ISSUE THREAD

**Issue by Smeeto13** [ollama/ollama#7475]
### What is the issue?

Loading models via Zed uses 6GB more ram than the same model does when loaded via Ollama's terminal interface (3GB+model vs 9GB + model)

### OS

Linux

### GPU

Intel

### CPU

Intel

### Ollama version

0.3.12

**Comment by rick-github** [comment]
[Server logs](https://github.com/ollama/ollama/blob/main/docs/troubleshooting.md#how-to-troubleshoot-issues) will show for sure, but as a guess I'd say zed is using a larger context window than the default of 2048.
