### ISSUE TITLE
llama3.2 11b setup error

### ISSUE THREAD

**Issue by Teramime** [ollama/ollama#7476]
### What is the issue?

I'm trying to develop an agent that analyzes images using llama3.2 11b.

Development environment:
os: window11 pro
cpu: intel i9-14900K

ram: 32G
vga: rtx 4080 super
Releases v0.3.14 When I install ollama and run
ollama run x/llama3.2-vision,
the installation goes well, but it terminates with the following message when running.

Error: llama runner process has terminated: exit status 0xc0000409

Is it because the vga performance is low?

### OS

Windows

### GPU

Nvidia

### CPU

Intel

### Ollama version

Releases v0.3.14

**Comment by yossifibrahem** [comment]
Update to the prereleased version: v4.0rc6
https://github.com/ollama/ollama/releases

**Comment by dhiltgen** [comment]
As mentioned above, llama3.2 vision requires Ollama version 0.4.0.
