### ISSUE TITLE
请问，我想让ollama每次调用模型的时候，默认全部加载到GPU，有什么办法吗？

### ISSUE THREAD

**Issue by fg2501** [ollama/ollama#7479]
### What is the issue?

![fe3abf5e-4911-4713-86c8-8f669ba9f838](https://github.com/user-attachments/assets/03427162-b4e6-4af9-ba3f-a46c94899a5c)
每次调用的时候，经常会出现，GPU调用不到百分百，有时候一半CPU，一般GPU，有的时候甚至全部调用CPU，有办法强制只调用GPU吗？
还有，加载的GPU，默认5分钟之后卸载，我能改成10分钟之后再卸载，或者使其一直处于加载状态吗？

### OS

Windows

### GPU

Nvidia

### CPU

AMD

### Ollama version

0.1.29

**Comment by rick-github** [comment]
Set [`OLLAMA_KEEP_ALIVE=-1`](https://github.com/ollama/ollama/blob/main/docs/faq.md#how-do-i-keep-a-model-loaded-in-memory-or-make-it-unload-immediately) to stop the model from being unloaded.

ollama uses as much of the GPU as it can.  If the GPU is full, part of the model will be run in CPU.  If you want to run a model only in GPU, use a smaller model.

**Comment by fg2501** [comment]
> 设置 `OLLAMA_KEEP_ALIVE=-1` 以阻止模型被卸载。
> 
> 奥拉马尽可能使用 GPU。如果 GPU 已满，部分模型将在 CPU 上运行。如果您只想在 GPU 上运行模型，请使用更小的模型或购买更大的 GPU。

好的，非常感谢！关键是，在GPU没满的情况，ollama有的时候，照样会只调用CPU啊，如果是尽可能的调用GPU，那我就不问了。

**Comment by rick-github** [comment]
ollama uses as much of the GPU as it can.
whatever doesn't fit in the GPU will run on the CPU.
a model is a series of layers.  the layers are processed sequentially.
operations on the GPU will run faster than operations on the CPU.
because operations on GPU are faster, more time is spent in CPU operations.
the GPU is idle while waiting for the CPU operations to complete.
ollama calls the GPU as much as it can, but the bottleneck is the CPU.
if you want the GPU to be used 100%, use a model that fits in the GPU.

**Comment by fg2501** [comment]
> 奥拉马尽可能多地使用 GPU。什么不适合在 GPU 上运行的，就会在 CPU 上运行。模型是一系列层。层是按顺序处理的。GPU 上的操作将比 CPU 上的操作运行得更快。因为 GPU 上的操作更快，所以在 CPU 操作上花费的时间更多。GPU 在等待 CPU 操作完成时处于空闲状态。GPU 被 ollama 调用得越多，瓶颈就在 CPU。如果你想让 GPU 使用率达到 100%，请使用适合 GPU 的模型。

![Uploading aa28b43a-fa54-4521-bdc6-d1f67bf7028e.png…]()
我注意到一个现象，就是我有一个模型，他是4b的模型，模型文件只有8G，但是却在加载的时候，显示为39G的大小，请问，这是什么原因呢？这个模型原本的名字叫minicpm3，是面壁智能下的模型。

**Comment by fg2501** [comment]
![aa28b43a-fa54-4521-bdc6-d1f67bf7028e](https://github.com/user-attachments/assets/e3f8af1c-da92-4c84-8f4c-e37d8f462fc1)

**Comment by fg2501** [comment]
我突然懂了，应该是我设置的上下文太长了，谢谢，这个问题我清楚了。

**Comment by fg2501** [comment]
我刚刚又检查了一下，这不是上下文长度的问题，算了，不搞了，我已经把这个模型卸载了。

**Comment by morika546** [comment]
我也遇到了类似的情况，但我是a卡6800xt，明明有16g专用显存，占用总显存14g的情况下，非要9g加载进共享显存，5g加载进专用显存，导致速度很慢，请问你换模型解决问题了吗？

**Comment by fg2501** [comment]
> 我也遇到了类似的情况，但我是a卡6800xt，明明有16g专用显存，占用总显存14g的情况下，非要9g加载进共享显存，5g加载进专用显存，导致速度很慢，请问你换模型解决问题了吗？

没有解决，还是这样

**Comment by yzwou** [comment]
> Set [`OLLAMA_KEEP_ALIVE=-1`](https://github.com/ollama/ollama/blob/main/docs/faq.md#how-do-i-keep-a-model-loaded-in-memory-or-make-it-unload-immediately) to stop the model from being unloaded.
> 
> ollama uses as much of the GPU as it can. If the GPU is full, part of the model will be run in CPU. If you want to run a model only in GPU, use a smaller model or get a bigger GPU.

我在powershell中运行set OLLAMA_KEEP_ALIVE=-1但是就算是重启了没有效果，请问如何解决
输入ollama ps时还是会显示4 minutes from now而不是forever

**Comment by rick-github** [comment]
https://github.com/ollama/ollama/blob/main/docs/faq.md#setting-environment-variables-on-windows

**Comment by yzwou** [comment]
> https://github.com/ollama/ollama/blob/main/docs/faq.md#setting-environment-variables-on-windows

感谢

**Comment by sudocodus** [comment]
> 我也遇到了类似的情况，但我是a卡6800xt，明明有16g专用显存，占用总显存14g的情况下，非要9g加载进共享显存，5g加载进专用显存，导致速度很慢，请问你换模型解决问题了吗？

你的问题解决了吗？

**Comment by fjzphch** [comment]
> 我也遇到了类似的情况，但我是a卡6800xt，明明有16g专用显存，占用总显存14g的情况下，非要9g加载进共享显存，5g加载进专用显存，导致速度很慢，请问你换模型解决问题了吗？

我找到解决办法了。如果使用open webui的话，可以修改高级参数里num_gpu (Ollama)的值。我用6750gre12g，9b的模型，改到30附近速度就很快，多了少了都不行。

**Comment by Angel0726** [comment]
`ollama ps`显示100%GPU。但是运行`nvidia-smi`命令查看占用情况，发现GPU占用一直为0；cpu占用为50%。模型运行速度一般，那到底占用GPU了吗？
显卡A100 40G
模型 deep-seek:32B

**Comment by hhwilliam** [comment]
ubuntu 20.04 GPU V100 ,驱动版本440 CUDA版本10.2，运行deepseek-r1:7B模型时，nvidia-smi查看gpu使用率为0%，显示没有进程使用GPU资源，token生成速率还可以，ollama ps看100%GPU，但运行uptime看cpu负载飙升，怎么强制使用GPU呢请问。

**Comment by Angel0726** [comment]
> ubuntu 20.04 GPU V100 ,驱动版本440 CUDA版本10.2，运行deepseek-r1:7B模型时，nvidia-smi查看gpu使用率为0%，显示没有进程使用GPU资源，token生成速率还可以，ollama ps看100%GPU，但运行uptime看cpu负载飙升，怎么强制使用GPU呢请问。
> 

找到问题了。我的问题是ollama安装有问题。离线安装的

**Comment by lindsaymorgan** [comment]
> > ubuntu 20.04 GPU V100 ,驱动版本440 CUDA版本10.2，运行deepseek-r1:7B模型时，nvidia-smi查看gpu使用率为0%，显示没有进程使用GPU资源，token生成速率还可以，ollama ps看100%GPU，但运行uptime看cpu负载飙升，怎么强制使用GPU呢请问。
> 
> 找到问题了。我的问题是ollama安装有问题。离线安装的

后来是怎么解决的方便介绍一下吗？我也遇到了相同的问题。

**Comment by ZongXR** [comment]
> > ubuntu 20.04 GPU V100 ,驱动版本440 CUDA版本10.2，运行deepseek-r1:7B模型时，nvidia-smi查看gpu使用率为0%，显示没有进程使用GPU资源，token生成速率还可以，ollama ps看100%GPU，但运行uptime看cpu负载飙升，怎么强制使用GPU呢请问。
> 
> 找到问题了。我的问题是ollama安装有问题。离线安装的

请问怎么解决的？

**Comment by Hugo-san** [comment]
> 同样遇到此问题，未解决

by updating my ollama from 0.5.7 to 0.5.10, the problem was solved for me when encountering this same problem.

**Comment by lumos0** [comment]
> 同样遇到此问题，未解决
原因还是在安装上。
重装ollama后解决，之前是离线安装。重装时，按照[在线安装](https://ollama.com/install.sh)脚本，手动修改了其中需要连网的部分，再安装后解决。

**Comment by bindianzhiyan** [comment]
![Image](https://github.com/user-attachments/assets/f3d16e10-f105-434d-ab2f-a08ba10b6ed9)
有人遇到这个嘛，已经配置了负载

**Comment by rick-github** [comment]
Upgrade ollama.

**Comment by weeee4** [comment]
ubuntu 20.04 GPU T4 ,驱动版本440 CUDA版本10.2，运行deepseek-r1:7B模型时，nvidia-smi查看gpu使用率为0%，显示没有进程使用GPU资源，ollama ps看100%CPU。重装ollama也不能解决.请问如何处理？

**Comment by rick-github** [comment]
Open a new ticket, add [server logs](https://github.com/ollama/ollama/blob/main/docs/troubleshooting.md#how-to-troubleshoot-issues).

**Comment by sunt1009** [comment]
离线安装的ollama,服务器无法上网只能离线安装，目前是4张A40卡，运行的时候只使用一张卡98%，其余三张为0%，ollama版本号:0.5.11,有大佬遇到过这类问题吗？

**Comment by cxlGiraffe** [comment]
> > 同样遇到此问题，未解决
> 
> 原因还是在安装上。 重装ollama后解决，之前是离线安装。重装时，按照[在线安装](https://ollama.com/install.sh)脚本，手动修改了其中需要连网的部分，再安装后解决。

大佬能分享下方法吗

**Comment by rick-github** [comment]
@sunt1009 This is normal.  If the model fits on one GPU, only one GPU is used.  There is no performance advantage using multiple GPUs for a single completion, see [here](https://github.com/ollama/ollama/issues/7648#issuecomment-2473561990).

**Comment by sunt1009** [comment]
@rick-github 目前现象十几个人访问，一个GPU显示100%，其余空闲，导致只有1-2个人可以访问，其余人都是等待状态，这个不正常吧！我的预期是访问一个GPU占用98%以上，后面有人发起请求理论应该使用空闲的GPU才合理吧

**Comment by rick-github** [comment]
Set `OLLAMA_NUM_PARALLEL` to as many concurrent requests you want to handle.  Or, if the model fits on one GPU, use multiple servers as I already pointed out [here](https://github.com/ollama/ollama/issues/7648#issuecomment-2473561990).

**Comment by fg2501** [comment]
> 我也遇到了类似的情况，但我是a卡6800xt，明明有16g专用显存，占用总显存14g的情况下，非要9g加载进共享显存，5g加载进专用显存，导致速度很慢，请问你换模型解决问题了吗？

我今天突然解决了，就是在配置文件那里增加参数，指定GPU加载多少层，PARAMETER num_gpu 100，我现在都是这样设置，这样一般来说，他都会加载满，当然，如果你的模型很大，那么，你需要再增加这个层数。

**Comment by CalunVier** [comment]
> > 我也遇到了类似的情况，但我是a卡6800xt，明明有16g专用显存，占用总显存14g的情况下，非要9g加载进共享显存，5g加载进专用显存，导致速度很慢，请问你换模型解决问题了吗？
> 
> 我今天突然解决了，就是在配置文件那里增加参数，指定GPU加载多少层，PARAMETER num_gpu 100，我现在都是这样设置，这样一般来说，他都会加载满，当然，如果你的模型很大，那么，你需要再增加这个层数。

您好，请问您能否说的再详细一些？

**Comment by LZHLZHOOO** [comment]
> > 我也遇到了类似的情况，但我是a卡6800xt，明明有16g专用显存，占用总显存14g的情况下，非要9g加载进共享显存，5g加载进专用显存，导致速度很慢，请问你换模型解决问题了吗？
> 
> 我今天突然解决了，就是在配置文件那里增加参数，指定GPU加载多少层，PARAMETER num_gpu 100，我现在都是这样设置，这样一般来说，他都会加载满，当然，如果你的模型很大，那么，你需要再增加这个层数。

遇到了同样的问题，请问具体是修改哪一个配置文件
