### ISSUE TITLE
[FEATURE REQUEST] - Add option to add code into the "Send a Message" prompt <>

### ISSUE THREAD

**Issue by BryanBond** [ollama/ollama#7481]
I would love to see the addition of an 'add code <>' option to the "Send a Message" box in ollama. This would make inquiry formatting to the llm much cleaner and easier to interpret/read.

**Comment by rick-github** [comment]
What '"Send a Message" box'?

**Comment by BryanBond** [comment]
Uhhhh I don't how I got so mixed up I meant to add this feature request to openwebui. Not ollama. Now I feel like an idiot lol. As you were.

CLOSED by reason of reporter insanity.
