### ISSUE TITLE
Packaging ollama: make including ROCm libraries in the dist optional

### ISSUE THREAD

**Issue by breezerider** [ollama/ollama#7483]
While working on a package for ollama built with a ROCm runner, I noticed that by default the build scripts include all the dependencies in dist archive. It makes sense in case of a standalone build, but when dependencies are resolved via a package manager, this adds a superfluous archive that in case of ROCm dependencies increase package size significantly. Till now I have been patching the build system to remove this step but as the build system changes this takes more effort. Would it be OK to optionally skip including library dependencies in the dist? I am willing to work on a patch for ROCm.

**Comment by dhiltgen** [comment]
I think it makes sense to refactor the makefiles a bit so that we can split out dependency gathering for distribution in the official bundles as a discrete target (or set of targets) so users or downstream apps/packaging can omit that step.

**Comment by nikhil-swamix** [comment]
will this be a good philosophy like pip listaller (reference)
`pip install ollama[cuda]`
`pip install ollama[rocm]`
maybe `apt get something similar` ? 
where would the issue arise in the official installer?

**Comment by breezerider** [comment]
@nikhil-swamix I don't believe there should be any issue for existing installers
Just to be clear, I asked to be able to build without putting GPU libraries into the dist, so being able to do something like:
`make OLLAMA_DONT_PUT_GPU_LIBS_IN_DIST=1`
I don't see how or why this should affect existing installers. But his would help package ollama for Linux distributions (like Debian, Ubuntu, Fedora, etc) where respective library dependencies are resolved via a package manager. As rocBLAS with all Tensile kernels can easily be ~1-2GBs, having those libraries twice on the system is superfluous (one copy coming from the package dependency and another copy residing in the dist).
