### ISSUE TITLE
I hope ollama can provide rerank models and speech recognition models.

### ISSUE THREAD

**Issue by ardyli** [ollama/ollama#7485]
希望ollama能提供rerank模型、能提供语音识别模型。

I hope ollama can provide rerank models and speech recognition models.

**Comment by rick-github** [comment]
#7219

**Comment by wanjunling168** [comment]
Rerank is in #7219 :), but ASR still not present

**Comment by rick-github** [comment]
https://github.com/ollama/ollama/issues/3265

**Comment by rick-github** [comment]
closing as dupe

**Comment by knsew** [comment]
why not?
