### ISSUE TITLE
Llama3.2 always returns tools calls and empty contents

### ISSUE THREAD

**Issue by ouariachi** [ollama/ollama#7487]
### What is the issue?

When tools are included in the body of a request to the Ollama API, Llama3.2 always returns tool_calls in its response, even if the user's message does not require it.

## Request
![imagen_2024-11-04_044920916](https://github.com/user-attachments/assets/c08df62b-5038-4d0c-ab0c-6a7266695552)

## Response
![imagen_2024-11-04_044941389](https://github.com/user-attachments/assets/665e4007-7bc3-412d-a21c-1fcb21f9453d)

### OS

Windows

### GPU

Nvidia

### CPU

Intel

### Ollama version

0.3.14

**Comment by eust-w** [comment]
Your request includes tools

**Comment by ouariachi** [comment]
> Your request includes tools

Does the fact that my request has tools mean that they will always be executed? Or that the tools will be executed if required?
