### ISSUE TITLE
ollama-server does not run the large model for a period of time. When running the large model again, an error message is displayed:

### ISSUE THREAD

**Issue by GreatStep** [ollama/ollama#7502]
### What is the issue?

ollama-server does not run the large model for a period of time. When running the large model again, an error message is displayed: server cpu not listed in available servers map[]
Every time I restart Ollama, everything returns to normal.
I have seen many users encounter similar situations online, and they were all solved by restarting.
Is this a bug? Any help?

### OS

Linux

### GPU

Nvidia

### Ollama version

0.1.45

**Comment by rick-github** [comment]
[Update](https://github.com/ollama/ollama/blob/main/docs/faq.md#how-can-i-upgrade-ollama) ollama.

**Comment by dhiltgen** [comment]
This bug was fixed quite a while back.  Upgrading will resolve the problem.

**Comment by GreatStep** [comment]
thank you , i will try later
