### ISSUE TITLE
docker image not using GPU

### ISSUE THREAD

**Issue by 781574155** [ollama/ollama#7506]
### What is the issue?

![image](https://github.com/user-attachments/assets/ef2b828f-152b-4bb1-b779-85a75e67bebd)

In the docker image, ollama ps shows 100% GPU, but in fact it use 0% GPU. the inference is really slow.
the gpu usage (nvidia-smi) is always 0%. Is it a bug? my NVIDIA Container Toolkit CLI version 1.17.0

### OS

Docker

### GPU

Nvidia

### CPU

Intel

### Ollama version

0.3.14

**Comment by rick-github** [comment]
[Server logs](https://github.com/ollama/ollama/blob/main/docs/troubleshooting.md#how-to-troubleshoot-issues) may help debugging.

Note that when ollama shows "100% GPU" it means that all of the model is loaded in to the GPU VRAM, not that it's using 100% of GPU compute at that moment.  The GPU-Util in the `nvidia-smi` output will not go up until ollama is doing a completion.

**Comment by 781574155** [comment]
thank you for your rapid reply. I found out that it's not ollama's problem. it's gpu card problem. maybe the card is locked. other AI program is also 0% GPU-Util when running. I switch to another machine, every thing is ok. ollama finish completion rapidly.
