### ISSUE TITLE
Manual ollama update doesn't work

### ISSUE THREAD

**Issue by ExposedCat** [ollama/ollama#7508]
### What is the issue?

According to docs, after downloading release, this is a last step to update ollama manually:
```bash
sudo tar -C /usr -xzf ollama-linux-amd64-rocm.tgz
```
However, ollama version remains unchanged even after `ollama` service restart

### OS

Linux

### GPU

AMD

### CPU

AMD

### Ollama version

0.3.14

**Comment by rick-github** [comment]
Note that you are mixing two different install methods here, but if you want to override the binary from the normal `curl|sh` method, you need to use the path where that was installed.
```
sudo tar -C /usr/local -xzf ollama-linux-amd64-rocm.tgz
```

**Comment by dhiltgen** [comment]
https://github.com/ollama/ollama/blob/main/docs/linux.md#amd-gpu-install

Perhaps we should have the "also" in bold - to clarify, the rocm tgz contains **only** the rocm libraries, but not ollama itself.  You'll need to extract **both** ollama-linux-arm64.tgz and ollama-linux-amd64-rocm.tgz

We try to keep this simple by taking care of the complexity in the install script.
