### ISSUE TITLE
About OLLAMA_SCHED_SPREAD env，How to load a model on two GPUs

### ISSUE THREAD

**Issue by Kouuh** [ollama/ollama#7511]
### What is the issue?

Previously, I was using 515 version of NVIDIA driver and cuda11.7, and I could load a model (qwen1.5_32b_q8) on two GPUs by setting OLLAMA_SCHED_SPREAD=1. 
But now I am using 535 version of NVIDIA driver and cuda12.1, and I want to load a model (qwen1.5_32b_q8) on two GPUs. Even if I set OLLAMA_SCHED_SPREAD=1, and tried ollamav_0.2.5 and ollama_v0.3.14, ollama will still run a complete model on two graphics cards. How can I solve this problem?

I run the service via command "CUDA_VISIBLE_DEVICES=6,7 /usr/bin/ollama serve"

### OS

Linux

### GPU

Nvidia

### CPU

Intel

### Ollama version

0.2.5 and 0.3.14

**Comment by dhiltgen** [comment]
In addition to the server log, I'd suggest using UUIDs instead of numeric IDs for the visible devices variable to ensure there isn't an ordering problem.  You mention 6 and 7 implying you have quite a few GPUs, so it's possible you have older GPUs in the mix which may be causing us to fall back to cuda v11 for compatibility reasons, but it should still be able to load the model across multiple GPUs.  In either case, the server log will help us understand what's going on.

**Comment by Kouuh** [comment]
> > ollama will still run a complete model on two graphics cards
> 
> Is this a typo or do I misunderstand the question? Isn't this what you want?
> 
> [Server logs](https://github.com/ollama/ollama/blob/main/docs/troubleshooting.md#how-to-troubleshoot-issues) will aid in debugging.

Maybe I expressed it wrongly. What I want to achieve is to split a model into two pieces and then run on two GPU graphics cards. But now it's a full model running on each card.

**Comment by Kouuh** [comment]
![IMG20241106094405](https://github.com/user-attachments/assets/b5f5b646-9cbf-48d1-a333-301bb02f0167)
![Uploading IMG20241106094832.jpg…]()

This is the debug information I printed. Sorry, the information shown in the image may not be complete.

**Comment by Kouuh** [comment]
![IMG20241106095709](https://github.com/user-attachments/assets/a9dc7150-a21d-44f8-be08-85e2717a0403)
The above two pictures are the debug information I printed. Sorry, the information and images displayed may be incomplete.

**Comment by rick-github** [comment]
Please don't use photographs of your screen, add the logs as text, either pasted in a comment or as an attachment.

It's still not clear what you want to achieve.  With `OLLAMA_SCHED_SPREAD=1`, ollama will split the model equally across all available cards.  It sounds like this is what you want.  It does not run an independent copy of the model on each card.  What makes you think this is not working correctly?

**Comment by Kouuh** [comment]
> Please don't use photographs of your screen, add the logs as text, either pasted in a comment or as an attachment.
> 
> It's still not clear what you want to achieve. With `OLLAMA_SCHED_SPREAD=1`, ollama will split the model equally across all available cards. It sounds like this is what you want. It does not run an independent copy of the model on each card. What makes you think this is not working correctly?

I used NVIDIA-SMI to check the memory occupation of memory.
I use two A100 (40G) display cards, and the weight of the model I want to use is 34G.
When I want to use two graphics cards to load the 34 G model, each graphics card will only occupy 17g of memory. But now I find that each card is actually occupied by 34g of memory.

**Comment by rick-github** [comment]
[Server logs](https://github.com/ollama/ollama/blob/main/docs/troubleshooting.md#how-to-troubleshoot-issues) should help in figuring out what is happening.  Also include the output of `nvidia-smi`.

**Comment by rick-github** [comment]
You have a large context window of 16000 tokens and `OLLAMA_NUM_PARALLEL=8`.  This requires 31.2GB.  Combined with the 34G of the model weights and the other memory required for supporting data structures, you need 90GB to host the model, so if fills up both cards and then partially spills in to system RAM, which is why your token speed is slow.  Reduce the context window or reduce `OLLAMA_NUM_PARALLEL`.

**Comment by Kouuh** [comment]
> You have a large context window of 16000 tokens and `OLLAMA_NUM_PARALLEL=8`. This requires 31.2GB. Combined with the 34G of the model weights and the other memory required for supporting data structures, you need 90GB to host the model, so if fills up both cards and then partially spills in to system RAM, which is why your token speed is slow. Reduce the context window or reduce `OLLAMA_NUM_PARALLEL`.

Thank you, I have solved the slow inference problem by lowering num_ctx. I would like to ask why setting the value of num_ctx too high will cause the inference speed to slow down.

**Comment by rick-github** [comment]
`num_ctx` is the space used for processing the tokens that are fed in to the model, like short term memory.  The larger the context space, the more VRAM needs to be allocated on the GPU to hold it.  If there's not enough room in the VRAM to hold both the context and the model weights, the model weights get moved to system RAM and are processed by the CPU.  The CPU is slower than the GPU, so token generation speed decreases.

**Comment by YUHSINCHENG1230** [comment]
where to set num_ctx?

**Comment by rick-github** [comment]
https://github.com/ollama/ollama/blob/main/docs/faq.md#how-can-i-specify-the-context-window-size
