### ISSUE TITLE
Realtime API like OpenAI (full fledged voice to voice integrations)

### ISSUE THREAD

**Issue by ryzxxn** [ollama/ollama#7514]
if anyone is working on a realtime api like integration with Ollama, please reach out to me. iam working on a similar integration, and i think feedback from, all the amazing people can greatly impact the quality of this feature, i think its pretty cool what openAI has going for it, and iam also a big fan of running every thing locally... 😄

**Comment by nikhil-swamix** [comment]
the thing is whisper is not found on ollama repo. so sound models are not supported in GGUF format.
let me know the outline of implementation, as i run a separate python server for STT<->TTS models.

**Comment by ryzxxn** [comment]
@nikhil-swamix  i have something similar going on, a python server continuously processing streamed audio from my microphone,, i tried implementing multiple threads to process these audio segments parallely but it improves the speed a bit but, at the end of the day its not fast enough to have it real time, any idea how openAi is doing this,
are they just, using a lot of compute?

**Comment by ryzxxn** [comment]
iam currently using whisper-small
https://huggingface.co/openai/whisper-small

```
import torch
import numpy as np
import sounddevice as sd
from transformers import AutoModelForSpeechSeq2Seq, AutoProcessor, pipeline
import asyncio

# Set device and precision based on availability of CUDA
device = "cuda" if torch.cuda.is_available() else "cpu"
torch_dtype = torch.float16 if torch.cuda.is_available() else torch.float32

# Load Whisper model and processor
model_id = "openai/whisper-small"
model = AutoModelForSpeechSeq2Seq.from_pretrained(
    model_id, torch_dtype=torch_dtype, low_cpu_mem_usage=True, use_safetensors=True
)
model.to(device)
processor = AutoProcessor.from_pretrained(model_id)

# Initialize the ASR pipeline with the Whisper model, enforcing English language
pipe = pipeline(
    "automatic-speech-recognition",
    model=model,
    tokenizer=processor.tokenizer,
    feature_extractor=processor.feature_extractor,
    torch_dtype=torch_dtype,
    device=device,
)

# Microphone parameters
sample_rate = 16000  # Whisper models prefer 16 kHz input
buffer_duration = 3  # Duration of each audio buffer in seconds (smaller for real-time)

# Asynchronous audio callback function
async def audio_callback(indata, frames, time, status):
    if status:
        print(f"Error: {status}")
    # Convert the audio chunk to a flat array and send to the pipeline
    audio = np.squeeze(indata)  # Flatten the audio data
    # Transcribe the audio asynchronously
    result = await asyncio.to_thread(pipe, audio)
    # Print the transcribed text
    print("Transcription:", result["text"])

# Function to record and transcribe audio in real-time
async def transcribe_from_mic():
    print("Recording audio from microphone...")

    # Start streaming audio from the microphone
    with sd.InputStream(callback=lambda indata, frames, time, status: asyncio.run(audio_callback(indata, frames, time, status)),
                        channels=1, samplerate=sample_rate, blocksize=int(sample_rate * buffer_duration), dtype="float32"):
        print("Press Ctrl+C to stop the transcription.")
        try:
            while True:
                await asyncio.sleep(0.1)  # Keep the stream open for continuous transcription
        except KeyboardInterrupt:
            print("Transcription stopped.")

# Run the transcription function
asyncio.run(transcribe_from_mic())
```

**Comment by ryzxxn** [comment]
> iam currently using whisper-small https://huggingface.co/openai/whisper-small
> 
> ```
> import torch
> import numpy as np
> import sounddevice as sd
> from transformers import AutoModelForSpeechSeq2Seq, AutoProcessor, pipeline
> import asyncio
> 
> # Set device and precision based on availability of CUDA
> device = "cuda" if torch.cuda.is_available() else "cpu"
> torch_dtype = torch.float16 if torch.cuda.is_available() else torch.float32
> 
> # Load Whisper model and processor
> model_id = "openai/whisper-small"
> model = AutoModelForSpeechSeq2Seq.from_pretrained(
>     model_id, torch_dtype=torch_dtype, low_cpu_mem_usage=True, use_safetensors=True
> )
> model.to(device)
> processor = AutoProcessor.from_pretrained(model_id)
> 
> # Initialize the ASR pipeline with the Whisper model, enforcing English language
> pipe = pipeline(
>     "automatic-speech-recognition",
>     model=model,
>     tokenizer=processor.tokenizer,
>     feature_extractor=processor.feature_extractor,
>     torch_dtype=torch_dtype,
>     device=device,
> )
> 
> # Microphone parameters
> sample_rate = 16000  # Whisper models prefer 16 kHz input
> buffer_duration = 3  # Duration of each audio buffer in seconds (smaller for real-time)
> 
> # Asynchronous audio callback function
> async def audio_callback(indata, frames, time, status):
>     if status:
>         print(f"Error: {status}")
>     # Convert the audio chunk to a flat array and send to the pipeline
>     audio = np.squeeze(indata)  # Flatten the audio data
>     # Transcribe the audio asynchronously
>     result = await asyncio.to_thread(pipe, audio)
>     # Print the transcribed text
>     print("Transcription:", result["text"])
> 
> # Function to record and transcribe audio in real-time
> async def transcribe_from_mic():
>     print("Recording audio from microphone...")
> 
>     # Start streaming audio from the microphone
>     with sd.InputStream(callback=lambda indata, frames, time, status: asyncio.run(audio_callback(indata, frames, time, status)),
>                         channels=1, samplerate=sample_rate, blocksize=int(sample_rate * buffer_duration), dtype="float32"):
>         print("Press Ctrl+C to stop the transcription.")
>         try:
>             while True:
>                 await asyncio.sleep(0.1)  # Keep the stream open for continuous transcription
>         except KeyboardInterrupt:
>             print("Transcription stopped.")
> 
> # Run the transcription function
> asyncio.run(transcribe_from_mic())
> ```

use appropriate torch library based on your system

**Comment by nikhil-swamix** [comment]
what type of latency ur getting , and can you share CPU, GPU Specs?

**Comment by ryzxxn** [comment]
I'll update you on the output later, for now my specs are a rtx2050 and amd7000 laptop
 Also iam segmenting into 3 second buffer which skipped the next 3 seconds of the audio...

**Comment by nikhil-swamix** [comment]
understood, rtx 2050 should be good enough, 
do have a look at, 
https://github.com/ggerganov/whisper.cpp
and https://github.com/FL33TW00D/whisper-turbo

-----
my current implementation is using groq, so feels fast enough within 3 seconds... whisper.cpp from the founders of llama.cpp (on which ollama is based...) yielded very fast response on test PC RTX 3070. the trick is to work with smaller buffers and concatenate the outputs on multiple threads (max 3). and use the streaming api so each sentence from chatgpt(ollama) server can be spoken out by text to speech in respectable timeframe. will get back on saturday on the issue.
regards

**Comment by ryzxxn** [comment]
Very insightfull, even I found that using small buffers yielded the best result, iam going to keep working on the multiple thread method, I'll update it here if I have any updates,

**Comment by fofsinx** [comment]
> Very insightfull, even I found that using small buffers yielded the best result, iam going to keep working on the multiple thread method, I'll update it here if I have any updates,

I'm building something similar github.com/fofsinx/echoollama

**Comment by jmorganca** [comment]
Merging with https://github.com/ollama/ollama/issues/1168 – thanks for the issue!
