### ISSUE TITLE
not able to download models from ollama behind proxy

### ISSUE THREAD

**Issue by anshika1234** [ollama/ollama#7522]
### What is the issue?

ollama run qwen:4b
pulling manifest 
pulling 46bb65206e0e...   0% ▕                ▏ 3.3 MB/2.3 GB  1.4 KB/s    99h+^****

-------------------------------------------- Log content -------------------
ollama[719]: time=2024-11-06T10:08:16.817+05:30 level=INFO source=download.go:370 msg="8eeb52dfb3bb part 15 stalled; retrying. If this persists, press ctrl-c to exit, then 'ollama pull' to find a faster connection."

-----------------------------------------------Settings-----------
https_proxy setup is done in ollama environment

Please suggest how to debug further.

### OS

Linux

### CPU

Intel

### Ollama version

0.3.14

**Comment by nikhil-swamix** [comment]
could you try a different proxy? some proxies disallow ports, or have bandwidth throttles in my exp... let me know if work

**Comment by anshika1234** [comment]
No i cannot change the proxy. But I confirmed there is no port blocking in proxy server. 

Need to debug it further.  How do it?

**Comment by rick-github** [comment]
[Server logs](https://github.com/ollama/ollama/blob/main/docs/troubleshooting.md#how-to-troubleshoot-issues) may help in debugging.

What's the output of the commands:
```
systemctl cat --no-pager ollama
curl -D - https://registry.ollama.ai/v2/library/gemma2/manifests/2b
curl -D - https://registry.ollama.ai/v2/library/gemma2/manifests/2b --noproxy "*"
```

**Comment by anshika1234** [comment]
# /etc/systemd/system/ollama.service
[Unit]
Description=Ollama Service
After=network-online.target

[Service]
ExecStart=/usr/local/bin/ollama serve
User=ollama
Group=ollama
Restart=always
RestartSec=3
Environment="PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin"

[Install]
WantedBy=default.target

# /etc/systemd/system/ollama.service.d/override.conf
[Service]
Environment="https_proxy=http://proxy_details"

Environment="http_proxy=http://proxy_details"
Environment="OLLAMA_TMPDIR=/usr/share/ollama/"
Environment="no_proxy=127.0.0.1"

_______________________________________________________________________________

HTTP/1.1 200 Connection established
Proxy-Agent: PROXYAGENTNAME

HTTP/2 200 
date: 
content-type: text/plain; charset=utf-8
content-length: 857
via: 1.1 google
alt-svc: h3=":443"; ma=86400
cf-cache-status: DYNAMIC
report-to: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v4?s=SpO5gZZ55fJmi6GxlOnhQUKeuI2FPtdhiRvKIAp8lyn3Xld3QuJBEF9aLPsQkdV5NunrQ6LKNUaMeATqrdJEoUECCvu1YNK2XXPP6eH7yceGcocGVUeTeg52MxF86JSeyGAcTdE%3D"}],"group":"cf-nel","max_age":604800}
nel: {"success_fraction":0,"report_to":"cf-nel","max_age":604800}
server: cloudflare
cf-ray: 8de36a736c4301b4-SIN
server-timing: cfL4;desc="?proto=TCP&rtt=243978&sent=8&recv=11&lost=0&retrans=0&sent_bytes=3404&recv_bytes=658&delivery_rate=11848&cwnd=253&unsent_bytes=0&cid=4a7807ecf0552878&ts=643&x=0"

{"schemaVersion":2,"mediaType":"application/vnd.docker.distribution.manifest.v2+json","config":{"digest":"sha256:e18ad7af7efbfaecd8525e356861b84c240ece3a3effeb79d2aa7c0f258f71bd","mediaType":"application/vnd.docker.container.image.v1+json","size":487},"layers":[{"digest":"sha256:7462734796d67c40ecec2ca98eddf970e171dbb6b370e43fd633ee75b69abe1b","mediaType":"application/vnd.ollama.image.model","size":1629509152},{"digest":"sha256:e0a42594d802e5d31cdc786deb4823edb8adff66094d49de8fffe976d753e348","mediaType":"application/vnd.ollama.image.template","size":358},{"digest":"sha256:097a36493f718248845233af1d3fefe7a303f864fae13bc31a3a9704229378ca","mediaType":"application/vnd.ollama.image.license","size":8433},{"digest":"sha256:2490e7468436707d5156d7959cf3c6341cc46ee323084cfa3fcf30fe76e397dc","mediaType":"application/vnd.ollama.image.params","size":65}]}


_________________________________________________-
No output for 3rd command

**Comment by rick-github** [comment]
Server logs?

**Comment by anshika1234** [comment]
curl -D - https://registry.ollama.ai/v2/library/gemma2/manifests/2b --noproxy "*"
curl: (28) Failed to connect to registry.ollama.ai port 443 after 217352 ms: Connection timed out


-------------------------------------------- Log content -------------------
level=INFO source=download.go:370 msg="8eeb52dfb3bb part 3 stalled; retrying. If this persists, press ctrl-c to exit, then 'ollama pull' to find a faster connection."

**Comment by rick-github** [comment]
Full server log.

**Comment by anshika1234** [comment]
same line is repeated for different part numbers. before that following are the logs - 


time=2024-11-06T13:20:33.353+05:30 level=INFO source=images.go:754 msg="total blobs: 0"
time=2024-11-06T13:20:33.353+05:30 level=INFO source=images.go:761 msg="total unused blobs removed: 0"
time=2024-11-06T13:20:33.353+05:30 level=INFO source=routes.go:1205 msg="Listening on 127.0.0.1:11434 (version 0.3.14)"
time=2024-11-06T13:20:33.716+05:30 level=INFO source=common.go:135 msg="extracting embedded files" dir=/tmp/ollama3094735932/runners
time=2024-11-06T13:20:47.366+05:30 level=INFO source=common.go:49 msg="Dynamic LLM libraries" runners="[cuda_v12 rocm_v60102 cpu cpu_avx cpu_avx2 cuda_v11]"
time=2024-11-06T13:20:47.366+05:30 level=INFO source=gpu.go:221 msg="looking for compatible GPUs"
time=2024-11-06T13:20:48.216+05:30 level=INFO source=gpu.go:384 msg="no compatible GPUs were discovered"
time=2024-11-06T13:20:48.216+05:30 level=INFO source=types.go:123 msg="inference compute" id=0 library=cpu variant=avx2 compute="" driver=0.0 name="" total="7.6 GiB" available="5.5 GiB"
[GIN] 2024/11/06 - 13:20:48 | 200 |      34.849µs |       127.0.0.1 | HEAD     "/"
time=2024-11-06T13:20:53.474+05:30 level=INFO source=download.go:175 msg="downloading 46bb65206e0e in 16 145 MB part(s)"
time=2024-11-06T13:21:12.038+05:30 level=INFO source=download.go:370 msg="46bb65206e0e part 3 stalled; retrying. If this persists, press ctrl-c to exit, then 'ollama pull' to find a faster connection."

**Comment by rick-github** [comment]
Full log, there is information in other parts that may be useful in debugging the problem you have.

**Comment by anshika1234** [comment]
ollama serve
2024/11/06 13:20:33 routes.go:1158: INFO server config env="map[CUDA_VISIBLE_DEVICES: GPU_DEVICE_ORDINAL: HIP_VISIBLE_DEVICES: HSA_OVERRIDE_GFX_VERSION: HTTPS_PROXY: HTTP_PROXY: NO_PROXY: OLLAMA_DEBUG:false OLLAMA_FLASH_ATTENTION:false OLLAMA_GPU_OVERHEAD:0 OLLAMA_HOST:http://127.0.0.1:11434 OLLAMA_INTEL_GPU:false OLLAMA_KEEP_ALIVE:5m0s OLLAMA_LLM_LIBRARY: OLLAMA_LOAD_TIMEOUT:5m0s OLLAMA_MAX_LOADED_MODELS:0 OLLAMA_MAX_QUEUE:512 OLLAMA_MODELS:/root/.ollama/models OLLAMA_MULTIUSER_CACHE:false OLLAMA_NOHISTORY:false OLLAMA_NOPRUNE:false OLLAMA_NUM_PARALLEL:0 OLLAMA_ORIGINS:[http://localhost https://localhost http://localhost:* https://localhost:* http://127.0.0.1 https://127.0.0.1 http://127.0.0.1:* https://127.0.0.1:* http://0.0.0.0 https://0.0.0.0 http://0.0.0.0:* https://0.0.0.0:* app://* file://* tauri://*] OLLAMA_SCHED_SPREAD:false OLLAMA_TMPDIR: ROCR_VISIBLE_DEVICES: http_proxy:http://PROXY_DETAILS https_proxy:http://PROXY_DETAILS no_proxy:localhost,127.0.0.1]"
time=2024-11-06T13:20:33.353+05:30 level=INFO source=images.go:754 msg="total blobs: 0"
time=2024-11-06T13:20:33.353+05:30 level=INFO source=images.go:761 msg="total unused blobs removed: 0"
time=2024-11-06T13:20:33.353+05:30 level=INFO source=routes.go:1205 msg="Listening on 127.0.0.1:11434 (version 0.3.14)"
time=2024-11-06T13:20:33.716+05:30 level=INFO source=common.go:135 msg="extracting embedded files" dir=/tmp/ollama3094735932/runners
time=2024-11-06T13:20:47.366+05:30 level=INFO source=common.go:49 msg="Dynamic LLM libraries" runners="[cuda_v12 rocm_v60102 cpu cpu_avx cpu_avx2 cuda_v11]"
time=2024-11-06T13:20:47.366+05:30 level=INFO source=gpu.go:221 msg="looking for compatible GPUs"
time=2024-11-06T13:20:48.216+05:30 level=INFO source=gpu.go:384 msg="no compatible GPUs were discovered"
time=2024-11-06T13:20:48.216+05:30 level=INFO source=types.go:123 msg="inference compute" id=0 library=cpu variant=avx2 compute="" driver=0.0 name="" total="7.6 GiB" available="5.5 GiB"
[GIN] 2024/11/06 - 13:20:48 | 200 |      34.849µs |       127.0.0.1 | HEAD     "/"
time=2024-11-06T13:20:53.474+05:30 level=INFO source=download.go:175 msg="downloading 46bb65206e0e in 16 145 MB part(s)"
time=2024-11-06T13:21:12.038+05:30 level=INFO source=download.go:370 msg="46bb65206e0e part 3 stalled; retrying. If this persists, press ctrl-c to exit, then 'ollama pull' to find a faster connection."
time=2024-11-06T13:21:12.038+05:30 level=INFO source=download.go:370 msg="46bb65206e0e part 14 stalled; retrying. If this persists, press ctrl-c to exit, then 'ollama pull' to find a faster connection."
time=2024-11-06T13:21:12.038+05:30 level=INFO source=download.go:370 msg="46bb65206e0e part 0 stalled; retrying. If this persists, press ctrl-c to exit, then 'ollama pull' to find a faster connection."
time=2024-11-06T13:21:12.038+05:30 level=INFO source=download.go:370 msg="46bb65206e0e part 6 stalled; retrying. If this persists, press ctrl-c to exit, then 'ollama pull' to find a faster connection."
time=2024-11-06T13:21:12.038+05:30 level=INFO source=download.go:370 msg="46bb65206e0e part 4 stalled; retrying. If this persists, press ctrl-c to exit, then 'ollama pull' to find a faster connection."
time=2024-11-06T13:21:12.038+05:30 level=INFO source=download.go:370 msg="46bb65206e0e part 15 stalled; retrying. If this persists, press ctrl-c to exit, then 'ollama pull' to find a faster connection."
time=2024-11-06T13:21:12.038+05:30 level=INFO source=download.go:370 msg="46bb65206e0e part 1 stalled; retrying. If this persists, press ctrl-c to exit, then 'ollama pull' to find a faster connection."
time=2024-11-06T13:21:12.038+05:30 level=INFO source=download.go:370 msg="46bb65206e0e part 8 stalled; retrying. If this persists, press ctrl-c to exit, then 'ollama pull' to find a faster connection."
time=2024-11-06T13:21:12.038+05:30 level=INFO source=download.go:370 msg="46bb65206e0e part 13 stalled; retrying. If this persists, press ctrl-c to exit, then 'ollama pull' to find a faster connection."
time=2024-11-06T13:21:14.038+05:30 level=INFO source=download.go:370 msg="46bb65206e0e part 5 stalled; retrying. If this persists, press ctrl-c to exit, then 'ollama pull' to find a faster connection."
time=2024-11-06T13:21:14.038+05:30 level=INFO source=download.go:370 msg="46bb65206e0e part 12 stalled; retrying. If this persists, press ctrl-c to exit, then 'ollama pull' to find a faster connection."
time=2024-11-06T13:21:14.038+05:30 level=INFO source=download.go:370 msg="46bb65206e0e part 9 stalled; retrying. If this persists, press ctrl-c to exit, then 'ollama pull' to find a faster connection."
time=2024-11-06T13:21:14.038+05:30 level=INFO source=download.go:370 msg="46bb65206e0e part 10 stalled; retrying. If this persists, press ctrl-c to exit, then 'ollama pull' to find a faster connection."
time=2024-11-06T13:21:14.038+05:30 level=INFO source=download.go:370 msg="46bb65206e0e part 7 stalled; retrying. If this persists, press ctrl-c to exit, then 'ollama pull' to find a faster connection."
time=2024-11-06T13:21:14.038+05:30 level=INFO source=download.go:370 msg="46bb65206e0e part 11 stalled; retrying. If this persists, press ctrl-c to exit, then 'ollama pull' to find a faster connection."
[GIN] 2024/11/06 - 13:21:15 | 200 | 27.233605372s |       127.0.0.1 | POST     "/api/pull"

**Comment by rick-github** [comment]
Is the ollama server running on the same machine you are running the `ollama run` command on?

**Comment by anshika1234** [comment]
yes

**Comment by nikhil-swamix** [comment]
try this just for sample...
if this work, i believe my guess would be right. confirm result once done.
`ollama run qwen2.5:0.5b`

**Comment by anshika1234** [comment]
/usr/share/ollama/ollama2477802559/runners/cpu# ollama run qwen2.5:0.5b
pulling manifest 
pulling c5396e06af29... 100% ▕██████████████████████████▏ 397 MB                         
pulling 66b9ea09bd5b... 100% ▕██████████████████████████▏   68 B                         
pulling eb4402837c78... 100% ▕██████████████████████████▏ 1.5 KB                         
pulling 832dd9e00a68... 100% ▕██████████████████████████▏  11 KB                         
pulling 005f95c74751... 100% ▕██████████████████████████▏  490 B                         
verifying sha256 digest 
Error: digest mismatch, file must be downloaded again: want sha256:c5396e06af294bd101b30dce59131a76d2b773e76950acc870eda801d3ab0515, got sha256:5bdde73520ef51f67ce75262ffe51b46aca27e89ba7647eb0f5c82cdd81fa479


_______________________________________

what next?

**Comment by anshika1234** [comment]
df -h
Filesystem      Size  Used Avail Use% Mounted on
tmpfs           781M  1.7M  779M   1% /run
/dev/sda5        58G   40G   19G  68% /
tmpfs           3.9G   23M  3.8G   1% /dev/shm
tmpfs           5.0M  4.0K  5.0M   1% /run/lock
/dev/sda1       511M  4.0K  511M   1% /boot/efi
tmpfs           781M  108K  781M   1% /run/user/2545

___________________ Environement variables

OLLAMA_MODELS:/opt/ollama_models 
OLLAMA_TMPDIR:/opt/ollama_models

_______________________________




Issue persists still. What else can be done?

**Comment by nikhil-swamix** [comment]
Attempt 001:
```bash
# Get and set user's .ollama directory explicitly
OLLAMA_HOME=$(eval echo ~$USER)/.ollama
# Create directory if needed
mkdir -p $OLLAMA_HOME
mkdir -p $OLLAMA_HOME/models
# Create ollama user and group if they don't exist
sudo groupadd -f ollama 
sudo useradd -r -g ollama ollama 2>/dev/null || true
# Add current user to ollama group
sudo usermod -aG ollama $USER
# Set correct ownership and permissions
sudo chown -R ollama:ollama $OLLAMA_HOME
sudo chmod -R 770 $OLLAMA_HOME
# Stop ollama service safely  
sudo service ollama stop
# Set model and temp directories
export OLLAMA_MODELS=$OLLAMA_HOME/models
export OLLAMA_TEMPDIR=$OLLAMA_HOME/models
# Start ollama with explicit home
OLLAMA_HOME=$OLLAMA_HOME OLLAMA_MODELS=$OLLAMA_MODELS OLLAMA_TEMPDIR=$OLLAMA_TEMPDIR ollama run qwen2.5:0.5b
# Note: You may need to log out and back in for group changes to take effect
echo "Please log out and log back in for group changes to take effect"
```
Notes: Previous ollama must die for new changes to effect, modify the last part as required.

**Comment by anshika1234** [comment]
bypassing proxy solved the problem. Can we conclude it is not I/O problem. Thanks a lot for the responses.

**Comment by nikhil-swamix** [comment]
Dear Anshika, glad to hear that the attempts yielded positive outcome.
best regards,
Swamix Global AI Solutions, swamix.com

**Comment by rick-github** [comment]
> `OLLAMA_HOME=$OLLAMA_HOME OLLAMA_MODELS=$OLLAMA_MODELS OLLAMA_TEMPDIR=$OLLAMA_TEMPDIR ollama run qwen2.5:0.5b`

This will not change the environment variables, they need to be set in the [server environment](https://github.com/ollama/ollama/blob/main/docs/faq.md#how-do-i-configure-ollama-server).

**Comment by nikhil-swamix** [comment]
> > `OLLAMA_HOME=$OLLAMA_HOME OLLAMA_MODELS=$OLLAMA_MODELS OLLAMA_TEMPDIR=$OLLAMA_TEMPDIR ollama run qwen2.5:0.5b`
> 
> This will not change the environment variables, they need to be set in the [server environment](https://github.com/ollama/ollama/blob/main/docs/faq.md#how-do-i-configure-ollama-server).

ahh, agreed, in windows powershell `$env:something=value` worked, my answer may have been biased from debugging standpoint. this one i believe it would set only one time per session and lost . nevertheless, thanks for correction.

**Comment by anshika1234** [comment]
> > `OLLAMA_HOME=$OLLAMA_HOME OLLAMA_MODELS=$OLLAMA_MODELS OLLAMA_TEMPDIR=$OLLAMA_TEMPDIR ollama run qwen2.5:0.5b`
> 
> This will not change the environment variables, they need to be set in the [server environment](https://github.com/ollama/ollama/blob/main/docs/faq.md#how-do-i-configure-ollama-server).

yes i have set in server enviroment only. But it worked only when proxy was bypassed.

**Comment by anshika1234** [comment]
Thanks again.
