### ISSUE TITLE
[FEAT] Add ollama installation selection

### ISSUE THREAD

**Issue by rong-xiaoli** [ollama/ollama#7523]
My computer has only 46MB left on my `C:` and ollama installation program fails to install. I tried my best to get more space but I could not. It seems like the installation program does not support installation path selection, thus I suggest adding a path selection before installation.

**Comment by nikhil-swamix** [comment]
nothing is impossible my friend, ive struggled with same issue, i have like 1TB HDD, and 256 m2 (superfast). i swap old models, or archive them. so i follow this approach, you would need to set env variables, and restart server.
![image](https://github.com/user-attachments/assets/8d06f09d-d804-43ac-9a7f-3c931d65cdea)
confirm if it work or not.
Best regards,
Swamix Global AI Solutions

**Comment by rick-github** [comment]
https://github.com/ollama/ollama/issues/2776#issuecomment-2333360257

**Comment by rong-xiaoli** [comment]
> nothing is impossible my friend, ive struggled with same issue, i have like 1TB HDD, and 256 m2 (superfast). i swap old models, or archive them. so i follow this approach, you would need to set env variables, and restart server. ![image](https://private-user-images.githubusercontent.com/54004431/383462104-8d06f09d-d804-43ac-9a7f-3c931d65cdea.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA4OTAzNDEsIm5iZiI6MTczMDg5MDA0MSwicGF0aCI6Ii81NDAwNDQzMS8zODM0NjIxMDQtOGQwNmYwOWQtZDgwNC00M2FjLTlhN2YtM2M5MzFkNjVjZGVhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA2VDEwNDcyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNlYWM3M2FjZWY2N2MxYjBiMzM3MjExZmM5YzBmY2I3ZWQzMDdmOWVlNmQxMDJlNDEwYWQzNzk3OTM3Y2VhNzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.UN6vv3tZxTdL43VQwr7qK2zPLblRB6Nt6Okt-wlALlE) confirm if it work or not. Best regards, Swamix Global AI Solutions


Actually not this problem, I cannot install ollama itself😂
I need to change a location to install ollama first, then I can install the models.

**Comment by nikhil-swamix** [comment]
Oh, i C the problem with C drive, 
assuming ur on windows, as you mentioned C: drive, 
i retry the setup , everything just extract in C, i can confirm.

your best bet would be to download ollama binary, on different drive, and add it to path. 


step 1:
[get from here](https://github.com/ollama/ollama/releases), the zip file and amd64 variant.

step2:
extract to desired drive, and add it to path, so the executable can found, or open a terminal from that folder.

Note: some env settings might default to C and models start download to c again. then follow previous setting suggestion...

__________

Best would be to use [winget ](https://aka.ms/getwinget) installer and set location, as mentioned in rick's comment...

**Comment by rong-xiaoli** [comment]
> [#2776 (comment)](https://github.com/ollama/ollama/issues/2776#issuecomment-2333360257)

This works! Thanks both of you.
