### ISSUE TITLE
向量库问答问题

### ISSUE THREAD

**Issue by NXL333** [ollama/ollama#7525]
### What is the issue?

 1:
 智慧陆边口岸大模型
一、三大应用场景需求：
（1）口岸整体情况分析：
1、口岸四个流分析，包括人流、物流、信息流、商品流：例如人员往来（跨国人员流
动、非法出入境的分析和统计），往返人员携带的物品（发现可能存在的风险和机
遇），口岸信息的集成；
2、贸易分析：通过年鉴以及商务部文件及数据，分析口岸贸易量变迁、贸易商品结构
（原料、加工、一般贸易等）、产品进出口情况、原产地；
3、地缘政治：中亚五国和东盟
4、政策预警、政府辅助决策（双边关系约定情况，关税政策、政策怎么约定，商务部
网站免税协定与哪些国家签署（方便企业自动查询））
5、检验检疫政策与流程：为企业提供检疫双方的标准和具体流程要求；
6、产品标准（方便企业对照是否符合出口国家产品标准）、双方标准
（2）口岸本身情况分析：
1、通过口岸志数据，分析口岸之间的类型（有些是针对双边贸易，有些仅支持过境—
—通道型口岸）、关联关系、布局以及时空特征（分析口岸布局在哪个城市投入产
出更佳，优化口岸布局、支持城市发展）；
2、口岸历史沿革：从历史上来看受到哪些自然灾害或历史事件的影响，使得口岸增加
/减少、开放/关闭；
3、口岸边检风险预警：基于历史数据的叠加，对口岸边检、人检等进行预警，例如灾
害蝗虫跨界预警问题；
4、如何优化通关流程、缩短通关时间，提高便利化：主要在于信息不对等，是否可以
通过制作公众号视频等形式提高公众认知度。
（3）企业与公众社会需求
1、旅游：智慧旅游，旅游攻略，特别要注意对方国和我国的法律问题，针对免签国家
常见的问题汇总和解答；
2、口岸知识：口岸周边人文地理知识，促进知识分享；
3、爱国基地、筑牢教育等：具有历史意义、文化底蕴或独特地理环境的地方；
4、口岸投资潜力分析：通过系统了解对方国家的人文情况，进行投资风险研判；
5、投资政策，投资规则：了解对方国家的投资政策。

这是我的向量库，搜索出来的向量，然后我用这个代码，
vectorstore = FAISS.from_texts(chunk_text, embeddings)
            retriever = vectorstore.as_retriever()
            # 3. 向模型提问
            template = """Answer the question based only on the following context:
            {context}
            Question: {question}
            """
            prompt = ChatPromptTemplate.from_template(template)
            chain = (
                {"context": retriever, "question": RunnablePassthrough()}
                | prompt
                | model_local
                | StrOutputParser()
            )调用，他回答的并不全，这是他的回答，口岸整体情况分析包括：

人流分析：人员往来（跨国人员流动、非法出入境的分析和统计）
物流分析：往返人员携带的物品（发现可能存在的风险和机遇）
信息流分析：口岸信息的集成
商品流分析：贸易量变迁、贸易商品结构（原料、加工、一般贸易等）、产品进出口情况、原产地。

后面的问题，为啥没有回答，我要怎么修改吗？？？谢谢您，您真好

### OS

Windows

### GPU

Nvidia

### CPU

Intel

**Comment by rick-github** [comment]
This doesn't look like an ollama issue, you will get more helpful information asking on a forum that deals with [langchain](https://github.com/langchain-ai/langchain/discussions)

**Comment by NXL333** [comment]
> This doesn't look like an ollama issue, you will get more helpful information asking on a forum that deals with [langchain](https://github.com/langchain-ai/langchain/discussions)

请教一个问题，OLAMA，运行起来，采用接口调用，回答的方式，我感觉就可以解决问题。那么，为什么还要使用OLAMA建立一个AGENT呢，有文章或者资料吗？？谢谢

**Comment by NXL333** [comment]
from langchain_core.tools import tool  
from langchain.pydantic_v1 import BaseModel, Field
from langchain_core.tools import render_text_description
from langchain.agents import AgentExecutor, create_react_agent
from langchain import hub
from langchain_community.chat_models import ChatOllama
import getpass
import os

os.environ["LANGCHAIN_TRACING_V2"] = "true"
os.environ["LANGSMITH_ENDPOINT"] = "https://api.smith.langchain.com"
os.environ["LANGCHAIN_API_KEY"] = "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"
os.environ["LANGCHAIN_PROJECT"] = "My_project"

class SearchInput(BaseModel):
    location: str = Field(description="location to search for")  # 定义一个 Pydantic 模型，用于描述输入模式，并提供描述信息

@tool(args_schema=SearchInput)
def weather_forecast(location: str):
    """天气预报工具。"""
    print(f"Weather for {location}")  # 打印要预报天气的位置
    return f"A dummy forecast for {location}"  # 返回给定位置的虚拟天气预报

llm = ChatOllama(model="llama3.1")  # 初始化 ChatOllama 模型，使用 "gemma:2b"
tools = [weather_forecast]  # 使用 weather_forecast 工具
prompt = hub.pull("hwchase17/react-json")  # 从 hub 拉取特定提示
prompt = prompt.partial(
    tools=render_text_description(tools),  # 为提示呈现工具的文本描述
    tool_names=", ".join([t.name for t in tools]),  # 将工具名称连接成一个以逗号分隔的字符串
)
agent = create_react_agent(llm, tools, prompt)  # 使用 llm、工具和自定义提示创建代理
agent_executor = AgentExecutor(agent=agent, tools=tools, handle_parsing_errors=True, verbose=False, format="json")  # 使用指定参数初始化 AgentExecutor
print(agent_executor.invoke({"input":"上海的天气?"}))  # 使用测试输入调用代理并打印结果

tools = [weather_forecast]

这个tools还有什么，有文档吗？？？谢谢

**Comment by NXL333** [comment]
tools = [weather_forecast] 这个还有什么工具吗？？？有文档，能导入自己的代码吗？？？

**Comment by rick-github** [comment]
https://www.google.com/search?q=为什么还要使用LLM建立一个AGENT呢
