### ISSUE TITLE
Qwen2.5-Coder-7B-Instruct 2024/11/06 update

### ISSUE THREAD

**Issue by vYLQs6** [ollama/ollama#7538]
https://huggingface.co/Qwen/Qwen2.5-Coder-7B-Instruct/commit/9092a8ae57da39f15b76b309b4f71ff11b6ef01a

They just updated the weights of Qwen2.5-Coder-7B-Instruct without any announcement, so I don't know what exactly what the update is, but it's an update

![](https://i.imgur.com/aG6m1dp.png)

**Comment by MillerWebsites** [comment]
They were just waiting to make sure Kamala lost and now they can make Ameriqwen great again

**Comment by MillerWebsites** [comment]
I do not like this clandestine update,
These changes made by stealth as of late!
No changelog here, no notes to see,
What have they changed? It's mystery!
"Just trust the code," they say with glee,
But WHAT changed? They won't tell me!
Not a comment, not a line,
Just "updates" dropped at runtime!
Did they tweak the matrix math?
Or reroute the data path?
Did they change the learning rate?
No one thought to annotate!
Silent pushes in the night,
Leave me in an awful fright.
For how can I debug with care,
When documentation isn't there?
Oh, the frustration! Oh, the pain!
Of updates dropped without explain!
Next time please, I beg of you,
Tell me WHAT your updates do!

**Comment by pdevine** [comment]
I'm not sure why the Qwen folks decided not to change the version number, but the new models are in the model library to use. You'll need to `ollama pull qwen2.5-coder` to get the latest version.

I'll go ahead and close the issue.
