### ISSUE TITLE
unable to update to ollama --version 0.4.0 or ollama pull llama3.2-vision or ollama pull llama3.2-vision:90b

### ISSUE THREAD

**Issue by etherblitzdev** [ollama/ollama#7539]
### What is the issue?

ubuntu 22.04.5 LTS

ollama --version
ollama version is 0.3.14

https://github.com/ollama/ollama/releases/download/v0.4.0/ollama-linux-amd64.tgz

mkdir ollama-linux-amd64
cd ollama-linux-amd64
tar -xzvf ollama-linux-amd64.tgz
sudo cp ./bin/ollama /usr/local/bin/
sudo mkdir -p /usr/local/lib/ollama
sudo cp -r ./lib/ollama/* /usr/local/lib/ollama/
 
# result
ollama --version
ollama version is 0.3.14
Warning: client version is 0.4.0

ollama pull llama3.2-vision
pulling manifest 
Error: pull model manifest: 412: 

The model you are attempting to pull requires a newer version of Ollama.

Please download the latest version at:

	https://ollama.com/download

ollama pull llama3.2-vision:90b
pulling manifest 
Error: pull model manifest: 412: 

The model you are attempting to pull requires a newer version of Ollama.

Please download the latest version at:

	https://ollama.com/download

### OS

Linux

### GPU

Nvidia

### CPU

AMD

### Ollama version

ollama version is 0.3.14 Warning: client version is 0.4.0

**Comment by rick-github** [comment]
You need to restart the server.

**Comment by alexd1983** [comment]
same problem. restarting the server did not help. my version of ollama is stuck on 0.3.11

**Comment by rick-github** [comment]
How does your system start ollama after a reboot?  Is it configured as a service, ie a service file in `/etc/systemd/system/ollama.service`?

**Comment by etherblitzdev** [comment]
sudo tar -C /usr -xzf ollama-linux-amd64-rocm.tgz
sudo useradd -r -s /bin/false -U -m -d /usr/share/ollama ollama
sudo usermod -a -G ollama $(whoami)
sudo nano /etc/systemd/system/ollama.service
sudo systemctl enable ollama
sudo systemctl daemon-reload
sudo systemctl restart ollama

sudo systemctl status ollama

#Yes this below resolved ,it on this machine

# yes configured as a service,  /etc/systemd/system/ollama.service
# worked like Lucky charms! Above was insufficient.
sudo reboot

ollama --version
ollama version is 0.4.0

#Downloaded :-D
ollama pull llama3.2-vision

#Downloading :-D
ollama pull llama3.2-vision:90b
