### ISSUE TITLE
How to use the brand new models?

### ISSUE THREAD

**Issue by dwsmart32** [ollama/ollama#7541]
Hello, always thank you for all your hard work. I would like to ask how to use a VLM like Qwen2 VL-72B(Not LLM) or Nvidia/NVLM-D-72B in Ollama. When I attempt to customize the model, it fails due to an unsupported backbone. Could you advise on what steps are needed to enable support for these newer models? Thank you.

**Comment by rick-github** [comment]
https://github.com/ollama/ollama/issues/7162
https://github.com/ollama/ollama/issues/7080

**Comment by pdevine** [comment]
Neither Qwen2 VL, nor NVLM are supported yet. Sorry! I'll close this as a dupe.
