### ISSUE TITLE
ERROR source=runner.go:426 msg="failed to decode batch" error="could not find a KV slot for the batch - try reducing the size of the batch or increase the context. code: 1"

### ISSUE THREAD

**Issue by wuhongsheng** [ollama/ollama#7545]
### What is the issue?

ERROR source=runner.go:426 msg="failed to decode batch" error="could not find a KV slot for the batch - try reducing the size of the batch or increase the context. code: 1"

### OS

macOS

### GPU

Apple

### CPU

Apple

### Ollama version

0.4

**Comment by wuhongsheng** [comment]
cheap_model_max_async=2,
   best_model_max_async=2,

**Comment by pengfan7758258** [comment]
The version is too new. I downgraded to version 0.3.14, and the issue was resolved. However, I noticed that in version 0.4, the GPU utilization decreased. Looking forward to a more stable release in future versions.

**Comment by jessegross** [comment]
@wuhongsheng Can you please post the full [server logs](https://github.com/ollama/ollama/blob/main/docs/troubleshooting.md#how-to-troubleshoot-issues)?

**Comment by jessegross** [comment]
This may be fixed in `main` - if anyone who is experiencing this issue can build from source and test it, that would be helpful to confirm.

**Comment by fce2** [comment]
just fyi, with ollama 0.4.2 i also get this error (using llama2-11b)

here is some log, loosk like the "limit" is not set correct (set to 2k, but llama2 has 128k)
```
time=2024-11-17T09:22:10.460+01:00 level=WARN source=runner.go:122 msg="input exceeds context length" prompt=54273 **limit=2048**
time=2024-11-17T09:22:10.635+01:00 level=ERROR source=runner.go:429 msg="failed to decode batch" error="could not find a KV slot for the batch - try reducing the size of the batch or increase the context. code: 1"
time=2024-11-17T09:22:10.809+01:00 level=ERROR source=runner.go:429 msg="failed to decode batch" error="could not find a KV slot for the batch - try reducing the size of the batch or increase the context. code: 1"
time=2024-11-17T09:22:10.810+01:00 level=ERROR source=runner.go:429 msg="failed to decode batch" error="could not find a KV slot for the batch - try reducing the size of the batch or increase the context. code: 1"
time=2024-11-17T09:22:10.949+01:00 level=ERROR source=runner.go:429 msg="failed to decode batch" error="could not find a KV slot for the batch - try reducing the size of the batch or increase the context. code: 1"
time=2024-11-17T09:22:11.167+01:00 level=ERROR source=runner.go:429 msg="failed to decode batch" error="could not find a KV slot for the batch - try reducing the size of the batch or increase the context. code: 1"
time=2024-11-17T09:22:11.370+01:00 level=ERROR source=runner.go:429 msg="failed to decode batch" error="could not find a KV slot for the batch - try reducing the size of the batch or increase the context. code: 1"
time=2024-11-17T09:22:11.590+01:00 level=ERROR source=runner.go:429 msg="failed to decode batch" error="could not find a KV slot for the batch - try reducing the size of the batch or increase the context. code: 1"
t
```

**Comment by jessegross** [comment]
@fce2 (or others that are experiencing this issue), can you give it a try with 0.4.3-rc0 (or later)? I believe that this error should be fixed now.

**Comment by fce2** [comment]
Hi Jesse,
just tested with 0.4.3, looks good now !
!! THANKS !!
