### ISSUE TITLE
ollama_embed issue

### ISSUE THREAD

**Issue by Ayush-developer** [ollama/ollama#7549]
### What is the issue?

postgres=# SELECT ai.ollama_embed('llama3', 'this is a test');
ERROR:  ollama._types.ResponseError: model "llama3" not found, try pulling it first
CONTEXT:  Traceback (most recent call last):
  PL/Python function "ollama_embed", line 21, in <module>
    resp = client.embeddings(model, input_text, options=embedding_options_1, keep_alive=keep_alive)
  PL/Python function "ollama_embed", line 200, in embeddings
  PL/Python function "ollama_embed", line 73, in _request
PL/Python function "ollama_embed" container is able to talk to ollama but not able to recognize this ollama_embed function

### OS

macOS

### GPU

Apple

### Ollama version

ollama version is 0.4.0

**Comment by rick-github** [comment]
```
ollama pull llama3
```
