### ISSUE TITLE
How to modify n_ctx

### ISSUE THREAD

**Issue by wuhongsheng** [ollama/ollama#7552]
### What is the issue?

How to modify n_ctx

### OS

macOS

### GPU

Apple

### CPU

Apple

### Ollama version

0.4

**Comment by belfie13** [comment]
`/set parameter num_ctx 999` while running or `PARAMETER num_ctx 999` in modelfile

**Comment by rick-github** [comment]
https://github.com/ollama/ollama/blob/main/docs/faq.md#how-can-i-specify-the-context-window-size
