### ISSUE TITLE
failed to generate embedding

### ISSUE THREAD

**Issue by fg2501** [ollama/ollama#7555]
### What is the issue?

之前的老版本卸载了，然后重新安装的0.4版本，结果出了这个报错，请问高手，应该怎么解决呢？

### OS

Windows

### GPU

Nvidia

### CPU

AMD

### Ollama version

0.4

**Comment by rick-github** [comment]
Add more information.

**Comment by dhiltgen** [comment]
Please share your server log, which should have more information about why the embedding request failed.

https://github.com/ollama/ollama/blob/main/docs/troubleshooting.md

**Comment by fg2501** [comment]
> 请分享您的服务器日志，它应该包含更多关于嵌入请求失败原因的信息。
> 
> https://github.com/ollama/ollama/blob/main/docs/troubleshooting.md

额，我已经把卸载0.4版本了，因为我看到有其他也说过这个问题，他们说，把版本换到0.3.13就好了，然后我就卸载了0.4版本，改成了0.3.13版本，所以自然，相关的日志记录之类的，也就被卸载了，实在抱歉。

**Comment by fg2501** [comment]
> Please share your server log, which should have more information about why the embedding request failed.
> 
> https://github.com/ollama/ollama/blob/main/docs/troubleshooting.md

然后我换到0.3.13版本之后，这个问题，也确实就没了.

**Comment by jessegross** [comment]
Can you at least give information about what you did that triggered the problem?

**Comment by fg2501** [comment]
> Please share your server log, which should have more information about why the embedding request failed.
> 
> https://github.com/ollama/ollama/blob/main/docs/troubleshooting.md

所以我估计，这应该是0.3.13版本之后的更新改动导致的，希望能对您有一些帮助。

**Comment by fg2501** [comment]
> Can you at least give information about what you did that triggered the problem?

**Comment by fg2501** [comment]
> Can you at least give information about what you did that triggered the problem?
我不是说了吗，我卸载了旧版本的ollama，然后装成了0.4版本的ollama，然后就出现了这个问题，这个问题目前我已经解决了，方法是卸载0.4版本，换成0.3.13版本

**Comment by fg2501** [comment]
目前问题已经解决，方法是改成0.3.13版本
