### ISSUE TITLE
ollama update fails to restart systemd service

### ISSUE THREAD

**Issue by remco-pc** [ollama/ollama#7562]
### What is the issue?

i  tried updating ollama with the | sh command and try to run the llama vision model but got this error:

root@f456206f9006:/mnt/Vps3/Mount# curl -fsSL https://ollama.com/install.sh | sh
>>> Installing ollama to /usr/local
>>> Downloading Linux amd64 bundle
######################################################################## 100.0%
>>> Adding ollama user to video group...
>>> Adding current user to ollama group...
>>> Creating ollama systemd service...
WARNING: Unable to detect NVIDIA/AMD GPU. Install lspci or lshw to automatically detect and install GPU dependencies.
>>> The Ollama API is now available at 127.0.0.1:11434.
>>> Install complete. Run "ollama" from the command line.
root@f456206f9006:/mnt/Vps3/Mount# ollama pull llama3.2-vision
pulling manifest
Error: pull model manifest: 412:

The model you are attempting to pull requires a newer version of Ollama.

Please download the latest version at:

        https://ollama.com/download

root@f456206f9006:/mnt/Vps3/Mount#

### OS

Linux

### CPU

Intel

### Ollama version

ollama version is 0.3.12 Warning: client version is 0.4.0

**Comment by remco-pc** [comment]
also: https://www.youtube.com/watch?v=a8gd892WKLM for someone who is interested in seeing it in action...

**Comment by etherblitzdev** [comment]
sudo tar -C /usr -xzf ollama-linux-amd64-rocm.tgz
sudo useradd -r -s /bin/false -U -m -d /usr/share/ollama ollama
sudo usermod -a -G ollama $(whoami)
sudo nano /etc/systemd/system/ollama.service
sudo systemctl enable ollama
sudo systemctl daemon-reload
sudo systemctl restart ollama

sudo systemctl status ollama

#Yes this below resolved ,it on this machine

# yes configured as a service,  /etc/systemd/system/ollama.service
# worked like Lucky charms! Above was insufficient.
sudo reboot

ollama --version
ollama version is 0.4.0

#Downloaded :-D
ollama pull llama3.2-vision

#Downloading :-D
ollama pull llama3.2-vision:90b

**Comment by rick-github** [comment]
What's the output of
```
systemctl --no-pager cat ollama
```

**Comment by remco-pc** [comment]
kill 540... and the process is guarded... and restarts automatically

**Comment by remco-pc** [comment]
![afbeelding](https://github.com/user-attachments/assets/b559083f-dadf-4138-b699-65658f8429fe)

**Comment by dhiltgen** [comment]
@remco-pc what does `systemctl is-system-running` report on your system?  It looks like that didn't return what we were expecting, and we didn't automatically restart the service, so the old version was still running.  A quick workaround is to just bounce the service `sudo systemctl restart ollama` but it looks like you already got it running from your latest update.

**Comment by remco-pc** [comment]
@dhiltgen its in docker without system-d, and its after an update it should kill and restart the service

**Comment by rick-github** [comment]
If you update ollama inside a container with `curl|sh`, you lose the update when the container is restarted.  If you want to update ollama, use `docker pull ollama/olllama` to fetch the latest image

**Comment by remco-pc** [comment]
@rick-github  if you reinstall with docker, you can loose your models, i've symlinked them to a mount point then you only loose the symlink on reinstallation

**Comment by rick-github** [comment]
Mount the model storage location.
```
docker run -d -v /path/to/model/on/host/system:/root/.ollama -p 11434:11434 --name ollama ollama/ollama
```

**Comment by remco-pc** [comment]
```docker-compose
volumes:
  mount:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /mnt/Vps3/Mount
  mount2:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /mnt/Disk2
```

Disk2 is www-data (full disk 2TB) or smaller /bigger

**Comment by rick-github** [comment]
This is how to update:
```
docker pull ollama/ollama
docker compose up -d ollama
```

**Comment by remco-pc** [comment]
i do the sh command and restart it

**Comment by rick-github** [comment]
If you do `curl|sh` inside the container and restart it, the update will be deleted.  That's the point of a container, you can make changes in it and restart and it's back to the original state.  To update a container, you pull the new version.

**Comment by rick-github** [comment]
That sounds more like a Dockerfile (used to build images) than a docker compose file.  Which you could avoid by just pulling the updated ollama image.  It just sounds like you are making life hard for yourself, building bespoke images that are already available and having to kill processes etc which would just be handle as part of a `docker compose up`.  The upshot is that if you really want to do it this way, that's up to you, but it's not an ollama problem.

**Comment by remco-pc** [comment]
It runs on a different port inside my docker-compose container with custom backend / frontend, i am fine thank you for pointing it out, ollama got added quickly and i am not using something else than a local connection with server sent events and json

**Comment by remco-pc** [comment]
@rick-github  this one i had to duplicate a line to get the end result

[tetris](https://www.youtube.com/watch?v=mU_2mnw_wwQ)
