### ISSUE TITLE
pull error - 104.21.75.227:443: wsarecv: An existing connection was forcibly closed by the remote host

### ISSUE THREAD

**Issue by Assassinator-567** [ollama/ollama#7567]
### What is the issue?

pulling manifest
pulling 2049f5674b1e... 100% ▕████████████████████████████████████████████████████████▏ 9.0 GB
Error: Head "https://registry.ollama.ai/v2/library/qwen2.5/blobs/sha256:66b9ea09bd5b7099cbb4fc820f31b575c0366fa439b08245566692c6784e281e": read tcp 192.168.1.7:56036->104.21.75.227:443: wsarecv: An existing connection was forcibly closed by the remote host.

### OS

Windows

### GPU

Nvidia

### CPU

Intel

### Ollama version

0.4.0

**Comment by dhiltgen** [comment]
Does this error happen consistently or did it happen only once?
