### ISSUE TITLE
num_ctx causes 100% CPU with no GPU usage

### ISSUE THREAD

**Issue by aaronbolton** [ollama/ollama#7576]
### What is the issue?

ive tried to create a new model recently with only the parameter num_ctx, when I run the models it shows 100% CPU with no GPU usage, even if the model was too big I would assume it would report GPU/CPU 100%/???%

### OS

Docker

### GPU

Nvidia

### CPU

Intel

### Ollama version

0.4.0

**Comment by rick-github** [comment]
#7509

[Server logs](https://github.com/ollama/ollama/blob/main/docs/troubleshooting.md#how-to-troubleshoot-issues) will help in debugging.

**Comment by aaronbolton** [comment]
Here is a fairly clean log, the model is loaded at around line 47

[ollama_logs.txt](https://github.com/user-attachments/files/17691317/ollama_logs.txt)

**Comment by aaronbolton** [comment]
perfect thank you for the pointer and informative answer

**Comment by liaoweiguo** [comment]
how do we get detailed information about this memory information, so important

**Comment by rick-github** [comment]
[Server logs](https://github.com/ollama/ollama/blob/main/docs/troubleshooting.md#how-to-troubleshoot-issues).  Look for `memory.required`.
