### ISSUE TITLE
Build fails and wipes parent folder if the path to the source contains a directory name with a space

### ISSUE THREAD

**Issue by gautamz** [ollama/ollama#7577]
### What is the issue?

I cloned the repo and tried to build ollama on my device running Linux with Intel cpu, Nvidia GPU and CUDA installed.
 
The path to source was - /home/user/workspace/sourcebuild/ollama stuff/ollama

When I ran make, the "clean payload" target from the Makefile in sub-directory "llama" wiped out /home/user/workspace 
The build failed.

I then tried this with path to source as - /home/user/workspace/sourcebuild/ollama_stuff/ollama
The build succeeded.

Either the path identification should be fixed, or user should be notified and allowed to decide to proceed with rm -rf ...

Please test this cautiously. I had an older backup so recovered most of my wiped files, but did lose a few recent projects.

### OS

Linux

### GPU

Nvidia

### CPU

Intel

### Ollama version

master

**Comment by igorschlum** [comment]
hi @dhiltgen do you reproduce the issue?
