### ISSUE TITLE
Embedding fails with Server error `httpx.HTTPStatusError: 500 Internal Server Error` in version 0.4.0

### ISSUE THREAD

**Issue by frtendero** [ollama/ollama#7578]
### What is the issue?

**Server log:** [server.log](https://github.com/user-attachments/files/17682295/server.log)

After upgrading from version 0.3.12 to version 0.4.0, embedding calculation fails when multiple documents are fed. It can handle small quantities but fails midway with larger lists, throwing `httpx.HTTPStatusError: 500 Internal Server Error`. Since it looked like a timeout, I tried increasing the timeout parameter with no luck. I'm interacting with ollama through the python client.

I tried **downgrading back to ollama 0.3.12 and the embedding worked again**.

Part of the error trace:
```
Calculating embeddings:  48%|█████████████████████████████████████████████████████████████▏                                                                 | 81/168 [00:14<00:15,  5.66it/s]

ollama._types.ResponseError: failed to generate embedding

[...]

Stack Trace:
File "<path_to_env>/ollama/_client.py", line 281, in embeddings
    return self._request(
           ^^^^^^^^^^^^^^
  File "<path_to_env>/ollama/_client.py", line 75, in _request
    raise ResponseError(e.response.text, e.response.status_code) from None

The above exception occurred during handling of the following exception:
httpx.HTTPStatusError: Server error '500 Internal Server Error' for url '<server_url>/api/embeddings'
For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/500

Stack Trace:
  File "<path_to_env>/ollama/_client.py", line 73, in _request
    response.raise_for_status()
  File "<path_to_env>/httpx/_models.py", line 763, in raise_for_status
    raise HTTPStatusError(message, request=request, response=self)
```

Thanks :)

### OS

Windows

### GPU

Nvidia

### CPU

Intel

### Ollama version

0.4.0

**Comment by frtendero** [comment]
Hi @rick-github, thanks for your quick response. Here is the server log [server.log](https://github.com/user-attachments/files/17682295/server.log)

I have removed the multiple lines of the POST to "/api/embeddings". In case there is not enough info, I will activate DEBUG mode and send again the log

Regarding the prompt, the fail is occurring when creating the embeddings using [haystack's ollama document embedder](https://docs.haystack.deepset.ai/docs/ollamadocumentembedder). I tried multiple embedders: mxbai, nomic and snowflake. All working with ollama 0.3.12, but not with 0.4.0

**Comment by jessegross** [comment]
@frtendero I'll see if I can reproduce but if you can send the the debug log that would be helpful.

**Comment by igorschlum** [comment]
@frtendero I could try also on an Mac. Could you try with some open source text files to embed and share the links (it could be ollama sources files).

**Comment by varyagnord** [comment]
I encountered the same problem on Linux. Everything was working well with ollama 0.3.12, but not with 0.4.0.

**Comment by varyagnord** [comment]
If the string is short, for example, around 30 characters, embeddings are created normally, but if it's longer, this error occurs.

**Comment by jessegross** [comment]
@varyagnord Can you provide server logs with OLLAMA_DEBUG=1 set and also give a specific example that triggers it?

**Comment by wwjCMP** [comment]
+1

**Comment by jessegross** [comment]
@wwjCMP Similar to the comment above you, can you provide the full log with OLLAMA_DEBUG=1 and also give more specifics about how you triggered this?

**Comment by jessegross** [comment]
My best guess is that the errors are triggered by prompts that are only whitespace. If that happens, we will currently generate an error whereas past versions of Ollama were more tolerant.

If anyone who is running into this problem can test out this PR and let me know if that fixes it, that would be helpful to confirm:
https://github.com/ollama/ollama/pull/7659

**Comment by varyagnord** [comment]
> @varyagnord Can you provide server logs with OLLAMA_DEBUG=1 set and also give a specific example that triggers it?

I resolved my issue by reinstalling ollama. Now, version 0.4.1 is working fine for me. Thank you.

**Comment by viosay** [comment]
I also encountered the same problem #7288

**Comment by jessegross** [comment]
Thanks a lot for testing and let me know.

**Comment by igorschlum** [comment]
@viosay and with version 0.4.5?

**Comment by jessegross** [comment]
The problem that @viosay ran into in #7288 looks different to me.

**Comment by viosay** [comment]
> @viosay and with version 0.4.5?

@igorschlum The issue persists but is not triggered by prompts that consist only of whitespace. This problem exists in all versions after 0.3.13.

**Comment by igorschlum** [comment]
@viosay, are you referring to the size of embedding chunks as described in this issue: https://github.com/ollama/ollama/issues/7288 ?

**Comment by viosay** [comment]
@jessegross Yes, it seems to be caused by issues related to the embedding block size.

**Comment by lilyTokens** [comment]
The HTTP API response format consistency across endpoints would help client library authors — currently some endpoints return newline-delimited JSON for streaming and JSON objects for non-streaming, but the fields aren't always consistent between streaming and non-streaming responses for the same endpoint. A stricter API specification with documented response schemas for each endpoint would reduce the guesswork in client implementations.
