### ISSUE TITLE
Ollama AsyncClinet keep reloading model

### ISSUE THREAD

**Issue by SnowFox4004** [ollama/ollama#7582]
## Problem
Ollama keeps reload the same model while using AsyncClient.chat()
![image](https://github.com/user-attachments/assets/cc8f77f4-2cc9-491f-9aa7-108c39e809a7)
When I `await` the same function again, the model in mem will be unload and reload.like this.
![image](https://github.com/user-attachments/assets/dc7035bd-7f16-41c8-a324-1759165bf1c6)
the `keep_alive` parameter doesn't work.
I have changed the `/etc/systemd/system/ollama.service` like this
![image](https://github.com/user-attachments/assets/d2d71a21-cc40-474b-b735-ab61dc415369)

## Expected
ollama only load the model once and do not reload the model while using.

### OS

Windows, WSL2

### GPU

Nvidia

### CPU

Intel

### Ollama version

0.3.6

**Comment by SnowFox4004** [comment]
Actually I just found that chating in cli also has this problem. I think there might be something wrong in ollama.So here is the recent log of ollama
[ollama_log.txt](https://github.com/user-attachments/files/17685922/ollama_log.txt)

**Comment by rick-github** [comment]
This looks like a bug that was [fixed](https://github.com/ollama/ollama/pull/6402) in 0.3.7.  Try [upgrading](https://github.com/ollama/ollama/blob/main/docs/faq.md#how-can-i-upgrade-ollama).

**Comment by SnowFox4004** [comment]
> This looks like a bug that was [fixed](https://github.com/ollama/ollama/pull/6402) in 0.3.7. Try [upgrading](https://github.com/ollama/ollama/blob/main/docs/faq.md#how-can-i-upgrade-ollama).

Thanks very much. I upgrade it and the problem is fixed.
