### ISSUE TITLE
Erratic behavior, either can't access to image or cannot recognize what is in the imager

### ISSUE THREAD

**Issue by MirzaAnoush** [ollama/ollama#7587]
### What is the issue?

Here the image and the responses. It looks like there is total inconsistency in the answers. I wonder if this is working fine with MacOS? I have tested with ollama-python and got same kind of results.
What is bizarre it is telling that it is text LLM and does not have vision ability!!!
Any thoughts?
I am located in France
<img width="1207" alt="Capture d’écran 2024-11-09 à 11 13 15" src="https://github.com/user-attachments/assets/79424fe8-868f-44de-94ea-6a569540b6d5">
<img width="1380" alt="Capture d’écran 2024-11-09 à 11 11 16" src="https://github.com/user-attachments/assets/f4531ea4-cf0b-48d8-92ec-37bbb221b4f5">

### OS

macOS

### CPU

Apple

### Ollama version

0.4

**Comment by rick-github** [comment]
As it said, the model can't access the internet.  Download the image.
```console
$ wget https://cdn.paris.fr/paris/2022/09/12/huge-9e714198e72f45cc2145b39c8b0c2f6a.jpg
$ ollama run llama3.2-vision
>>> describe this image: ./huge-9e714198e72f45cc2145b39c8b0c2f6a.jpg
Added image './huge-9e714198e72f45cc2145b39c8b0c2f6a.jpg'
The image showcases a vibrant urban scene, featuring two large murals on 
adjacent buildings that dominate the foreground. The mural on the left is 
predominantly white with black accents and depicts a close-up of a 
person's face, while the one on the right boasts a striking blue hue with 
white details, showcasing an open book accompanied by flowers.

In the background, several other buildings are visible, including a tan 
stone structure with arched windows and a tall tower to the left. A small 
section of blue sky is also present in the upper-right corner. The murals 
appear to be located in a city square or plaza, where people can be seen 
strolling about, adding to the lively atmosphere.

The overall ambiance suggests that this image was captured on a sunny day, 
with a sense of urban vibrancy and cultural richness emanating from the 
scene.
```

**Comment by rick-github** [comment]
> Hi, Thank you so much for your reply. The reason why I was not able to run the model with pictures on my Mac is because ollama restrict the images to be placed in a folder where ollama has been downloaded. Is this true? 

I don't have access to a Mac to verify, but I would be very surprised if this were true.  MacOS is unix-like under the GUI, so I would expect normal POSIX behaviour when supplying path names to the ollama client.  Can you provide an example of it not working?

> However, the returned information is different than the one executed into the terminal as it adds different type of info and lots of timing data. My question is what is the measurement unit for the timing measurement (there is lots of zeros) 

This sounds like you are seeing the raw JSON response from the ollama API.  The timing information is in nanoseconds, divide by 1000000000 to get seconds.  There are many tools for handling JSON, my go-to is `jq`, which you can install on Macos with:
```
brew install jq
```
If you don't have `brew` installed, see [brew.sh](https://brew.sh).

With `jq` installed, you can then pretty-print the JSON output and convert timing into seconds:
```
curl -s localhost:11434/api/generate -d '{"model":"llama3.2-vision","prompt":"hello","stream":false}' \
  | jq '.+{"time":(.eval_duration/1000000000)}|del(.context)'
{
  "model": "llama3.2-vision",
  "created_at": "2024-11-13T15:32:15.858675302Z",
  "response": "Hello! How are you today? Is there something I can help you with or would you like to chat?",
  "done": true,
  "done_reason": "stop",
  "total_duration": 2320789371,
  "load_duration": 34193182,
  "prompt_eval_count": 11,
  "prompt_eval_duration": 97000000,
  "eval_count": 23,
  "eval_duration": 2188000000,
  "time": 2.188
}
```

**Comment by pdevine** [comment]
As @rick-github mentioned, Ollama can't parse the URL that you provided because it doesn't talk to the internet. The LLM was inferring from the URL what you were asking it and spitting out nonsense (clearly that's next to the Pompidou and not the Arc de Triomphe!). You'll need to specify a local path of MacOS to whatever image that you want to read in. And yes, it can read from folders other than `Downloads/`, although everything depends on what security settings you've used w/ your machine.

I'll go ahead and close the issue.
