### ISSUE TITLE
Adding option to default `/clear` after each query

### ISSUE THREAD

**Issue by soulrrrrr** [ollama/ollama#7589]
As there is `/clear` command to clear the session context, it would be great if there is an option to set to automatically run `/clear` for every query. I am using LLM as translator so this feature might be helpful. Since when the prompt gets longer and longer, the inference time increases.

**Comment by pdevine** [comment]
You can call ollama from the CLI with:

`ollama run <model> "translate foo"` which should do what you're looking for. You can also create a Modelfile with a default system prompt which includes something like "Translate the following message from Spanish to English" and then use `ollama create` to create the new model and then use that w/ the `ollama run` command.

I'm going to go ahead and close the issue, but hopefully that makes sense.
