### ISSUE TITLE
Wrong Prompt Token Report from Ignoring Image Token Count

### ISSUE THREAD

**Issue by chigkim** [ollama/ollama#7592]
### What is the issue?

If you run llama3.2-vision with /set verbose, it looks like it only counts tokens for text ignoring tokens from image. Thus it reports extremely slow speed for prompt rate.
It's the same with API.

### OS

macOS

### GPU

Apple

### CPU

Apple

### Ollama version

0.4.0

**Comment by jessegross** [comment]
llama3.2-vision treats the image as a single token - it's counted, it just doesn't have a big impact on the count. Different models handle this differently and also have significantly different image processing times before they get to the language model processing stage. We count the full amount of time for accuracy but TPS will vary.
