### ISSUE TITLE
unable to get images to be read in ollama 0.4.1 for llama3.2-vision

### ISSUE THREAD

**Issue by sivaramn** [ollama/ollama#7596]
### What is the issue?

This is my setup on Windows 11
![image](https://github.com/user-attachments/assets/a87ed038-6b41-4c8e-ac2c-8c805fb64337)

Whatever image i upload,  get variations of the same message as shown.  What am I doing incorrectly?  The png file is 145kb, if it matters

![image](https://github.com/user-attachments/assets/078edf9a-040a-4972-8ec2-d7912ea53112)

### OS

Windows

### CPU

Intel

### Ollama version

0.4.1

**Comment by rick-github** [comment]
Try typing `/clear` and trying again.  If that doesn't help, is it possible for you to add the image to this thread?

**Comment by sivaramn** [comment]
> Try typing `/clear` and trying again. If that doesn't help, is it possible for you to add the image to this thread?

that worked. /clear and trying again with jpg files worked. png files seem to error out more than jpg at least on my win 11 laptop
