### ISSUE TITLE
Updating OpenCoder model information in library

### ISSUE THREAD

**Issue by elsatch** [ollama/ollama#7601]
### What is the issue?

I have been trying to use the new OpenCoder model with Continue extension and discovered it doesn't work. Asking at Continue's discord someone pointed me to this thread at HF:

https://huggingface.co/infly/OpenCoder-8B-Instruct/discussions/2#67304d50de572a8535e3d20b

In that thread you can find the following information: "Hi! Unfortunately OpenCoder doesn't support the FIM task. Our model added this token due to certain historical considerations."

Ollama includes the following description for OpenCoder models: OpenCoder is an open and reproducible code LLM family which includes 1.5B and 8B models, supporting both chat and fill-in-the-middle for English and Chinese languages.

There is also one example at the bottom of the page for Fill in the Middle task, which the model doesn't seem to support.

HF model card doesn't include any information about fill in the middle:

OpenCoder is an open and reproducible code LLM family which includes 1.5B and 8B base and chat models, supporting both English and Chinese languages.

Note that in the original model card the model includes base and chat model, in Llama library it's chat and fill in the middle. Maybe the model card was updated afterwards.

Could you update the ollama library information to avoid any confusion for final users?

### OS

macOS

### GPU

Apple

### CPU

Apple

**Comment by jmorganca** [comment]
Thanks @elsatch, I've updated the model page. Sorry about that!

**Comment by lilyTokens** [comment]
The model file inheritance for creating variants of existing models is a useful feature for teams who want to maintain consistent base configurations but vary system prompts, temperature, or stop tokens across different use cases. A clearer guide on the inheritance chain resolution (which settings are inherited, which are overridden, and how conflicts are resolved) would make model file composition more predictable.
