### ISSUE TITLE
pulling manifest error

### ISSUE THREAD

**Issue by the-nine-nation** [ollama/ollama#7608]
### What is the issue?

How to skip pulling manifest ? because my mechine without internet.

### OS

Linux, Docker

### CPU

Intel

### Ollama version

newest

**Comment by jmorganca** [comment]
Hi @the-nine-nation thanks for the issue! `ollama pull` requires an internet connection (and so does `ollama run` if you don't yet have the model). Once the model is downloaded `ollama run` will not require a connection – you can see which models you've downloaded with `ollama list`.

Let me know if this helps!
