### ISSUE TITLE
Feature for Filter models by type option

### ISSUE THREAD

**Issue by Abubakkar13** [ollama/ollama#7612]
Feature Request: 
Model Filtering by Type

Objective: Add a model filtering feature that allows users to filter available models by predefined categories, specifically:

1. Normal Models
2. Tool Models
3. Vision Models
4. Embedding Models

(New type if needed in future)

This feature in ollama site will improve usability by allowing users to easily find and select models according to their specific type or use case.

**Comment by jmorganca** [comment]
Hi @Abubakkar13 check out https://ollama.com/search which can do this! Thanks for the issue.
