### ISSUE TITLE
llama3.2-vision

### ISSUE THREAD

**Issue by tonilampela** [ollama/ollama#7617]
### What is the issue?

Running llama3.2-vision 11b model currently seem to throw request timed out errors.

BoltAI 1.26.1
ollama 0.4.1

In ollama console output I can see:

```
[GIN] 2024/11/11 - 10:17:38 | 500 |          1m0s |       127.0.0.1 | POST     "/v1/chat/completions"
time=2024-11-11T10:17:38.719+02:00 level=WARN source=sched.go:137 msg="mllama doesn't support parallel requests yet"
```

### OS

macOS

### GPU

Apple

### CPU

Apple

### Ollama version

0.4.1

**Comment by tonilampela** [comment]
> Your client has a 1 minute timeout.

Yeah, I found from advanced settings timeout adjustment and that seemed to sort it. Thanks!

**Comment by rick-github** [comment]
`msg="mllama doesn't support parallel requests yet"` has nothing to do with timeouts, it's just a warning saying that `OLLAMA_NUM_PARALLEL` is going to be treated as if it were set to 1.

**Comment by pickmao** [comment]
same，just set  env  OLLAMA_NUM_PARALLEL=3，
