### ISSUE TITLE
ollama 70B model on 10x32G vram rtx5000 - loading to 256G ram and cpu

### ISSUE THREAD

**Issue by paolss** [ollama/ollama#7623]
### What is the issue?

as in topic. something changed for rly bad in ollama - was trying to load 70B model that was working before update and now its not... all because it want to load to ram and use cpu not 10x32G rtx5000

### OS

Linux

### GPU

Nvidia

### CPU

AMD

**Comment by rick-github** [comment]
[Server logs](https://github.com/ollama/ollama/blob/main/docs/troubleshooting.md#how-to-troubleshoot-issues) will help in debugging.
