### ISSUE TITLE
Custom tool are not getting called in tool call

### ISSUE THREAD

**Issue by Vikneshkumarmohan** [ollama/ollama#7634]
### What is the issue?

when using ChatOllama in Langgraph tool call is not happening for the custom tools ,  but it is working as expected with tools like tavily search ,

https://langchain-ai.github.io/langgraph/tutorials/multi_agent/multi-agent-collaboration/#invoke
above is the example for reference code , when working with ollama LLM the custom tool is not calling  (custom tool : python_repl),

### OS

Windows

### GPU

AMD

### CPU

AMD

### Ollama version

Llama3.2

**Comment by ParthSareen** [comment]
Hey! I'd bring this up on on the langchain/langgraph repos. Happy to hop on that chain if needed.

**Comment by Vikneshkumarmohan** [comment]
Yes, please! Add to that chain

Thank you
