### ISSUE TITLE
missing uninstall instructions or script

### ISSUE THREAD

**Issue by adbenitez** [ollama/ollama#7636]
I got my `/` (root) partition full running the installer, would be nice if the installer allowed to install without `sudo` as local user, I canceled the installation at step `Downloading Linux ROCm amd64 bundle` due to the mentioned disk space issue, and now there is no uninstall instructions, had to figure it out where the ollama files were put to and delete manually

**Comment by rick-github** [comment]
https://github.com/ollama/ollama/issues/7421

**Comment by adbenitez** [comment]
hi @rick-github thanks for pointing out, I should have searched better, I changed title to focus on the missing uninstall script/instructions

**Comment by adbenitez** [comment]
actually the uninstall script was already requested at #1701
