### ISSUE TITLE
I built from source a while back and everything worked ok, the current code is dumping core, bus error.

### ISSUE THREAD

**Issue by phalexo** [ollama/ollama#7638]
### What is the issue?

I used to build it with
go generate ./...
go build .

Is it different now? Does it detect automatically CUDA at /usr/local/cuda?

### OS

Linux, Docker

### GPU

Nvidia

### CPU

Intel

### Ollama version

cloned github latest

**Comment by agreppin** [comment]
idem here with ROCm on Ubuntu 24.04, v0.4.1 log attached, same result with commit 65973ceb

[ollama-v0.4.1-rocm-v6.2.4.log](https://github.com/user-attachments/files/17724535/ollama-v0.4.1-rocm-v6.2.4.log)

**Comment by phalexo** [comment]
> idem here with ROCm on Ubuntu 24.04, v0.4.1 log attached, same result with commit [65973ce](https://github.com/ollama/ollama/commit/65973ceb6417c2e2796fa59bd3225bc7bd79b403)
> 
> [ollama-v0.4.1-rocm-v6.2.4.log](https://github.com/user-attachments/files/17724535/ollama-v0.4.1-rocm-v6.2.4.log)
> 
> PS: please can you provide some tips on how to debug the server/runner in the developers docs

I cannot be sure what your problem, but I think I figured what mine is. Ollama people decided to get "clever" how they identify a CUDA installation, and they just ignore variables like CUDA_ROOT, CUDA_HOME and instead look at symbolic links like /usr/local/cuda-11, which was the OLDER version. From that point different things did not match.

**Comment by dhiltgen** [comment]
@phalexo please give the change above a try and let us know if it clears up your build glitch, or if there's still more work to do.

The docs/development.md has been updated in that PR to provide additional guidance on building.

**Comment by phalexo** [comment]
I addressed the core dump problem by deleting old CUDA distribution. The
second problem that caused the runner to die, I had to drop the version
to V0.3.11. So at least you know that v0.3.11 works with
Qwen2.5-32b-instruct-Q8_0

**Comment by dhiltgen** [comment]
@phalexo PR #7499 is now merged.  Please give the new build a try and if it resolves your problem, go ahead and close the issue.  If not, please share updated details so I can take another look.

**Comment by phalexo** [comment]
Go ahead and close it, as I don't quite remember the details now.
