### ISSUE TITLE
Please add more models

### ISSUE THREAD

**Issue by smileyboy2019** [ollama/ollama#7644]
Please add more models
Qwen2-VL-7B-Instruct
Pixtral-12B-2409
Molmo-7B-O-0924

**Comment by rick-github** [comment]
https://github.com/ollama/ollama/issues/6564
https://github.com/ollama/ollama/issues/6748
https://github.com/ollama/ollama/issues/6958

**Comment by dhiltgen** [comment]
Looks like we can close this of a dup of the other tracking issues mentioned above.
