### ISSUE TITLE
The parameter 'keep_alive' is invalid when cpu (100%)

### ISSUE THREAD

**Issue by qiang1218** [ollama/ollama#7645]
### What is the issue?

I use 4090D GPU, model mannix/llamax3-8b-alpaca, keep_live set 5m, Initiate requests /api/generate every 3 seconds。
When the CPU is at 100% capacity, the subsequent request parameter 'keep_alive=5m' will become invalid and will get stuck in 'stopping' after the countdown.  The request will continue to time out.
<img width="349" alt="Snipaste_2024-11-13_16-34-27" src="https://github.com/user-attachments/assets/f13dc3aa-5496-40a9-80bb-95bb2c4e98d4">
<img width="325" alt="Snipaste_2024-11-13_16-31-58" src="https://github.com/user-attachments/assets/011b9d85-ca2b-483e-99c2-9dace528b483">

This can only be resolved by restarting the ollama service.

### OS

Linux

### GPU

Nvidia

### CPU

Intel

### Ollama version

0.4.1

**Comment by qiang1218** [comment]
Request log
<img width="474" alt="Snipaste_2024-11-13_16-40-45" src="https://github.com/user-attachments/assets/f633a20d-c2e2-4769-88de-f7a327399a4a">

**Comment by qiang1218** [comment]
Request log
<img width="474" alt="Snipaste_2024-11-13_16-40-45" src="https://github.com/user-attachments/assets/9286f436-c71f-4c18-a79d-d0ddd43a4269">

**Comment by dhiltgen** [comment]
If you have a reproduction scenario, can you run the server with OLLAMA_DEBUG="1" and share the logs around the time when it first goes into the `Stopping...` state?

**Comment by qiang1218** [comment]
"ollama ps" Output screenshot
<img width="822" alt="Snipaste_2024-11-14_09-45-10" src="https://github.com/user-attachments/assets/58ee0a2d-8d3d-4281-89fe-235c944dd68e">
"top" output screenshot
<img width="390" alt="Snipaste_2024-11-14_09-45-31" src="https://github.com/user-attachments/assets/b36c2d53-dfdd-408a-8807-6ddd03413601">
debug logs file
[ollama.log](https://github.com/user-attachments/files/17741646/ollama.log)

**Comment by qiang1218** [comment]
the new version v0.4.2-rc1 has the same issue

**Comment by qiang1218** [comment]
> It's possible that this may be fixed already - if you are able to build from `main` and report back, that would be very helpful. Otherwise, we may have an RC for the next release soon.

the new version v0.4.2-rc1 has the same issue

**Comment by jessegross** [comment]
More fixes have gone into 0.4.3 - please test. If the problem persists, please also provide the model that you are running when the problem occurs - see the comments in #7779 for additional context.

**Comment by qiang1218** [comment]
> More fixes have gone into 0.4.3 - please test. If the problem persists, please also provide the model that you are running when the problem occurs - see the comments in #7779 for additional context.

Version 0.4.4  still has the same issue

**Comment by qiang1218** [comment]
The first request timeout occurred (request timeout=20s), at the same time, the CPU usage exceeded 100%. The model parameter (UNTIL) starts counting down, and after about one minute, new requests can receive output (timeout situations may occur occasionally).

﻿![image](https://github.com/user-attachments/assets/e6bcbdd8-6494-46b3-982c-0aa62d0aa778)

After a while, The log shows that timeout requests have successfully responded with results (response exceeding 2m). CPU usage exceeds 100%,,the model keeps stopping status，and new requests can obtain results.
﻿
![image](https://github.com/user-attachments/assets/e17cdbac-b7f4-4195-ad78-b6d07650687a)

I have tried qwen2:7b and qwen2.5:7b, but the issue only occurs in mannix/llamax3-8b-alpaca. Maybe it's related to thread management in the startup model.  I have only tested on 0.4.x .

**Comment by jessegross** [comment]
My guess at this point is that it is related to the model - it's just continuing to generate text forever. Sometimes this can happen if the template or stop tokens are not correctly set up. One option to work around this is to use `num_predict`, which will set a limit on how much the model will generate.

Ollama won't unload a model as long as there is at least one request pending.

**Comment by qiang1218** [comment]
Thank you for your solution. 
By setting the 'num_predict' parameter to a smaller value (such as 4096) and the request interval time, after a timeout occurs for about 50 seconds, the log displays the output result of the timeout request, CPU usage decreases. The 'keep_alive' in the new request takes effect immediately, this model starts to become normal and can be unload.
