### ISSUE TITLE
Sending "hidden" messages for attachments

### ISSUE THREAD

**Issue by robotom** [ollama/ollama#7647]
I'm building a frontend and trying to send attachment contents and an accompanying prompt (e.g. "analyze this and wait for user prompt before responding") as a "hidden" message so that it's not rendered to the user on the frontend. I'm trying to avoid seeing 10 pages of a doc rendered in the chat window. 

Perhaps this is a frontend issue but I'm finding this more difficult to code than I think it should be... 

Any ideas?  Thanks!

**Comment by pdevine** [comment]
@robotom For multimodal we only currently support images right now, not things like PDFs or other documents. The way to pass anything is through the API though, so if you preprocessed everything in the frontend (like reading a PDF) you can then process the contents and make a call to the LLM which wouldn't be displayed to the user through your front end.

Hopefully that makes sense. I'm going to go ahead and close the issue.
