### ISSUE TITLE
on ollama model specifics web sites , add comaptible copypaste <name>:<tag> text

### ISSUE THREAD

**Issue by fxmbsw7** [ollama/ollama#7660]
eg , user visits page of a model
chooses select list , and selects some model version
there on that version of model page i want
say , for qwen2.5-coder.on its 14b-instruct-q4_K_M page
simply qwen2.5-coder:14b-instruct-q4_K_M
name:tag

like hf s use that button with ollama copypaste run cmd in

oh and yea , peeferably also a small ' copy me ' button left on it

greets

**Comment by rick-github** [comment]
![Screenshot from 2024-11-14 13-59-27](https://github.com/user-attachments/assets/97e373c4-cd7a-4d15-b0e0-f6c35a6c9735)

**Comment by fxmbsw7** [comment]
yes very nice !

**Comment by pdevine** [comment]
I'll go ahead and close the issue.

**Comment by fxmbsw7** [comment]
plz add to mobile version of web page too ..

**Comment by fxmbsw7** [comment]
@pdevine sir
i dunno if ur desktop page had it but the mobile version never did
also the mobile version lacks download links to the files or smth i couldnt find em easy
i also got suggestions but ill post em separately in another issue #
greets

**Comment by pdevine** [comment]
@fxmbsw7 what's the use case there? are you running ollama in mobile?

**Comment by fxmbsw7** [comment]
yes i am , on termux .. just the usual stuff

**Comment by fxmbsw7** [comment]
@pedevine ? :))
