### ISSUE TITLE
How does ollam support the input of long text quantity

### ISSUE THREAD

**Issue by smileyboy2019** [ollama/ollama#7661]
The large model supports 128k data input, which is equivalent to supporting hundreds of thousands of words. What is the maximum number of words that the ollama URL can support for input? Can you input hundreds of thousands of words.

**Comment by rick-github** [comment]
> Can you input hundreds of thousands of words.

Yes.

**Comment by jmorganca** [comment]
Yes it can – however, make sure to set the context window with `/set parameter num_ctx 128000` or `"options": {"num_ctx": 128000}}` in the API

**Comment by RealHacker** [comment]
What if the prompt I send to ollama exceeds the model context length? What does ollama do?
1. Reject the request with error code.
2. Accept all the text, but only the text within context window is actually sent to the model.
3. Cache the text, and repeatedly send segments to model, while preserving the context.

Which is it？

**Comment by rick-github** [comment]
2.

**Comment by RealHacker** [comment]
One more question: is the context length hardcoded 2048 or read from configuration? Or, does it change with the currently loaded model's parameters? If it is not dynamic with models, can I change it with REST API, and can I query it from REST API?

2048 is really limiting. If the context is not dynamic with loaded model, consider this a feature request. :)

**Comment by rick-github** [comment]
https://github.com/ollama/ollama/blob/main/docs/faq.md#how-can-i-specify-the-context-window-size
