### ISSUE TITLE
How can I remove specific PARAMETER from model?

### ISSUE THREAD

**Issue by wwjCMP** [ollama/ollama#7662]
How can I remove specific PARAMETER from model

For example, delete PARAMETER num_gpu 30 from qwen2.5-coder:32b-instruct-q8_0

ollama show qwen2.5-coder:32b-instruct-q8_0
  Model
    architecture        qwen2
    parameters          32.8B
    context length      32768
    embedding length    5120
    quantization        Q8_0

  Parameters
    num_ctx    16000
    num_gpu    30

  System
    You are Qwen, created by Alibaba Cloud. You are a helpful assistant.

  License
    Apache License
    Version 2.0, January 2004

**Comment by rick-github** [comment]
The model in the library doesn't have these parameters, so you just need to reverse the steps that were taken to add them in.

```console
$ ollama show --modelfile qwen2.5-coder:32b-instruct-q8_0 > NewModelfile
$ vi NewModelfile
# delete `PARAMETER num_gpu 30`
$ ollama create -f NewModlefile qwen2.5-coder:32b-instruct-no-gpu-q8_0
```

**Comment by wwjCMP** [comment]
> The model in the library doesn't have these parameters, so you just need to reverse the steps that were taken to add them in.
> 
> ```
> $ ollama show --modelfile qwen2.5-coder:32b-instruct-q8_0 > NewModelfile
> $ vi NewModelfile
> # delete `PARAMETER num_gpu 30`
> $ ollama create -f NewModelfile qwen2.5-coder:32b-instruct-no-gpu-q8_0
> ```

It works, thanks
