### ISSUE TITLE
Moondream v2 (CPU) crashes with images (post predict EOF error) on 0.4.1

### ISSUE THREAD

**Issue by rvkwi** [ollama/ollama#7672]
### What is the issue?

Moondream v2 seems to run into an issue with images on CPU with 0.4.1,  
resulting in `Error: POST predict: Post "http://127.0.0.1:33685/completion": EOF`.  
Does not seem to affect GPU.

```
~ $ ollama run moondream:v2 "please describe this image /home/kwi/demo-2.png" --verbose
Added image '/home/kwi/demo-2.png'
Error: POST predict: Post "http://127.0.0.1:34833/completion": EOF
~ $ ollama run moondream:v2 hi

 Hi

$ ollama --version
ollama version is 0.4.1
```

Only seems to happen with images, not text. The model loads and runs fine for text chat, but consistently crashes with EOF when attempting to process any image.

journalctl:
`level=DEBUG source=server.go:423 msg="llama runner terminated" error="signal: aborted"`

What i tried so far. 

- Differen images
- Different CPUS (Ryzen 5 6600H, Ryzen 7 5700X, i5-3320M)
- Other vision models (minicpm-v and llama seem to work fine)
- Different quants
- CLI and through API

I had an older laptop around with an outdated ollama 0.3.1 on it, that still worked fine. Upgrading to 0.4.1 caused the exact same error to appear as well. 

### OS

Linux

### CPU

Intel, AMD

### Ollama version

0.4.1

**Comment by rick-github** [comment]
probably #7441.

[Server logs](https://github.com/ollama/ollama/blob/main/docs/troubleshooting.md#how-to-troubleshoot-issues) would clarify.

**Comment by jessegross** [comment]
Yes, I think this is #7441 - let's track it there.
