### ISSUE TITLE
Enable image embeddings for vision models 

### ISSUE THREAD

**Issue by kevin-pw** [ollama/ollama#7677]
I would love to be able to create embeddings for images with vision models like `llama3.2-vision`.

Creating image and text embeddings with a vision-capable model should allow creating image search and image categorization applications.

If my understanding of the shared semantic vector space of image models is correct, it should be possible to perform calculations like cosine similarity on text and image embeddings to, for example, find all the photos of puppy dogs in a random assortment of photos :)

At this time, the `generate` endpoint accepts an `images` parameter, but the `embed` endpoint does not. I tried passing an image as a base64 string to the `input` parameter of the `embed` endpoint, but the resulting embedding appears to be the vector of the text string and not of the image.

Would it be possible to expand the `embed` endpoint to accept an image parameter?

**Comment by rick-github** [comment]
https://github.com/ollama/ollama/issues/5304
