### ISSUE TITLE
Reinstall docker image with old models ?

### ISSUE THREAD

**Issue by remco-pc** [ollama/ollama#7681]
### What is the issue?

Re-installing my docker image with ollama causes the models to disappear from the home directory, can they be mounted somewhere to not re-install these models ?
Are they learning from user input already ?

### OS

Linux, Windows, Docker, WSL2

### CPU

Intel

### Ollama version

0.4.1

**Comment by pdevine** [comment]
Hi @remco-pc , yes, you can use the `OLLAMA_MODELS` environment variable with Ollama to specify where you want the models to go, and you can use a docker volume to have persistent storage. You can find out more information about `OLLAMA_MODELS` in the [FAQ](https://github.com/ollama/ollama/blob/main/docs/faq.md#how-do-i-set-them-to-a-different-location).

As for learning from user input, no, Ollama doesn't (yet) do fine tuning of any data.

**Comment by remco-pc** [comment]
https://www.youtube.com/watch?v=a8gd892WKLM also have images with plain markdown command and a file.read

**Comment by remco-pc** [comment]
can you also use symlinks, so make a softlink with the directory to a mount point ? easier to restore

**Comment by remco-pc** [comment]
volumes:
  mount:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /mnt/Vps3/Mount
  mount2:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /mnt/Disk2 (full disk attached at www-data)
