### ISSUE TITLE
OpenCoder's template doesn't make sense for an instruct model

### ISSUE THREAD

**Issue by ProjectMoon** [ollama/ollama#7682]
### What is the issue?

I am testing out OpenCoder 8b. The information on the page on ollama.com implies that it's a chat model, but the template does not reference the system prompt at all. Setting the system prompt in OpenWebUI seems to do funny things with the chat (the model has a conversation with itself, because it's not generating the right stop tokens). The template as it is at the moment seems to be for a code generation model? Since it has the suffix stuff in it. Is OpenCoder on the website a chat model or a base model?

### OS

Linux

### GPU

AMD

### CPU

AMD

### Ollama version

0.4.1

**Comment by rick-github** [comment]
The embedded `chat_template` uses system and doesn't mention FIM, so it looks like the ollama template is wrong.
```
{% for message in messages %}{% if loop.first and messages[0]['role'] != 'system' %}{{ '<|im_start|>system
You are OpenCoder, created by OpenCoder Team.<|im_end|>
' }}{% endif %}{{'<|im_start|>' + message['role'] + '
' + message['content'] + '<|im_end|>' + '
'}}{% endfor %}{% if add_generation_prompt %}{{ '<|im_start|>assistant
' }}{% endif %}
```

**Comment by jmorganca** [comment]
It should be a chat model – it doesn't always listen to the system prompt but it does work sometimes:

```
% ollama run opencoder
>>> /set system only answer in french  
Set system message.
>>> hi
Bonjour ! Comment puis-je vous aider aujourd'hui ?
 
(The assistant greets the user and waits for instructions.)
```

I've since removed the FIM template – it seems the tokens are present, and it works, but was not trained for this 😊

**Comment by ProjectMoon** [comment]
So, this seems to work much better now. That is, until a system prompt is set. If you set a system prompt, in OpenWebUI at least, the model starts having conversations with itself.
