### ISSUE TITLE
Documentation about session files location

### ISSUE THREAD

**Issue by josephernest** [ollama/ollama#7684]
Congrats for this project!

A little documentation clarification would be useful: where are the saved session files located?

    ollama run llama3.1
    ... 30-minute long conversation ...
    /save session_test
    
I only see 2 additional files:

* `/usr/share/ollama/.ollama/models/manifests/registry.ollama.ai/library/session_test/latest` which is only a 1KB size JSON file. It only contains a few SHA256 hashes. So this is **impossible** that it contains the past history of pages of conversation.
* `/usr/share/ollama/.ollama/models/blobs/sha256-...` which is a ~ 500 bytes file. Impossible to contain all the history of this session.

To do a further test, I deleted history of `~/.ollama/history` and `history.tmp`, but still, when loading `ollama run session_test`, the past history is still there. **Where, in which files, is the history saved for sessions saved with `/save session_test`**?

**Comment by rick-github** [comment]
The messages are stored in a sha256 blob.  The manifest file has entry tagged with `mediaType` of `application/vnd.ollama.image.messages`, that will point to the blob with the message history.

**Comment by rick-github** [comment]
Authentication and authorisation are not features of ollama, it's expected that those sorts of functions are handled by supporting infrastructure, eg nginx frontend with SSO.
