### ISSUE TITLE
[Docs] Incorrect default value for num_predict?

### ISSUE THREAD

**Issue by owboson** [ollama/ollama#7691]
The API documentation (https://github.com/ollama/ollama/blob/main/docs/api.md#generate-a-chat-completion) refers to https://github.com/ollama/ollama/blob/main/docs/modelfile.md#valid-parameters-and-values for more information about the parameters that can be specified in the `options` field of a chat completion request.

However, the default value for the `num_predict` parameter described there either doesn't apply to calls made via the python library (in which case the docs should emphasise this) or is incorrect.

For `num_predict`, the docs say:

> Maximum number of tokens to predict when generating text. (Default: 128, -1 = infinite generation, -2 = fill context)

I initially wondered how Ollama could generate responses much longer than 128 tokens (without me specifying a value for the parameter). After adding a debug statement in `router.go`, I noticed that the server received a value of -1 for `num_predict`, which matches my previous observations.

As a consequence, the documentation is either misleading or gives an incorrect default value.

**Comment by rick-github** [comment]
The documentation is wrong, the default value is -1.

https://github.com/ollama/ollama/blob/d875e99e4639dc07af90b2e3ea0d175e2e692efb/api/types.go#L590
