### ISSUE TITLE
ollama is not working , Error: could not connect to ollama app, is it running?

### ISSUE THREAD

**Issue by gokulcoder7** [ollama/ollama#7697]
### What is the issue?

C:\Windows\System32>ollama list
Error: could not connect to ollama app, is it running?

C:\Windows\System32>
C:\Windows\System32>ollama --version
Warning: could not connect to a running Ollama instance
Warning: client version is 0.4.2

### OS

Windows

### GPU

Nvidia

### CPU

Intel

**Comment by gokulcoder7** [comment]
2024/11/16 07:51:59 routes.go:1189: INFO server config env="map[CUDA_VISIBLE_DEVICES: GPU_DEVICE_ORDINAL: HIP_VISIBLE_DEVICES: HSA_OVERRIDE_GFX_VERSION: HTTPS_PROXY: HTTP_PROXY: NO_PROXY: OLLAMA_DEBUG:false OLLAMA_FLASH_ATTENTION:false OLLAMA_GPU_OVERHEAD:0 OLLAMA_HOST:http://127.0.0.1:11434 OLLAMA_INTEL_GPU:false OLLAMA_KEEP_ALIVE:5m0s OLLAMA_LLM_LIBRARY: OLLAMA_LOAD_TIMEOUT:5m0s OLLAMA_MAX_LOADED_MODELS:0 OLLAMA_MAX_QUEUE:512 OLLAMA_MODELS:F:\\ollama\\models OLLAMA_MULTIUSER_CACHE:false OLLAMA_NOHISTORY:false OLLAMA_NOPRUNE:false OLLAMA_NUM_PARALLEL:0 OLLAMA_ORIGINS:[http://localhost https://localhost http://localhost:* https://localhost:* http://127.0.0.1 https://127.0.0.1 http://127.0.0.1:* https://127.0.0.1:* http://0.0.0.0 https://0.0.0.0 http://0.0.0.0:* https://0.0.0.0:* app://* file://* tauri://* vscode-webview://*] OLLAMA_SCHED_SPREAD:false OLLAMA_TMPDIR: ROCR_VISIBLE_DEVICES:]"
time=2024-11-16T07:51:59.100+05:30 level=INFO source=images.go:755 msg="total blobs: 10"
time=2024-11-16T07:51:59.100+05:30 level=INFO source=images.go:762 msg="total unused blobs removed: 0"
time=2024-11-16T07:51:59.100+05:30 level=INFO source=routes.go:1240 msg="Listening on 127.0.0.1:11434 (version 0.4.2)"
time=2024-11-16T07:51:59.101+05:30 level=ERROR source=common.go:279 msg="empty runner dir"
time=2024-11-16T07:51:59.101+05:30 level=INFO source=common.go:49 msg="Dynamic LLM libraries" runners=[]
**Error: unable to initialize llm runners unable to locate runners in any search path [C:\Users\Sushant\AppData\Local\Programs\Ollama C:\Users\Sushant\AppData\Local\Programs\Ollama\windows-amd64 C:\Users\Sushant\AppData\Local\Programs\Ollama\dist\windows-amd64 C:\Users\Sushant\AppData\Local\Programs\Ollama C:\Users\Sushant\AppData\Local\Programs\Ollama\windows-amd64 C:\Users\Sushant\AppData\Local\Programs\Ollama\dist\windows-amd64 C:\Windows\System32 C:\Windows\System32\windows-amd64 C:\Windows\System32\dist\windows-amd64]**


above is server.log

**Comment by gokulcoder7** [comment]
this error begin after update of ollama stopped suddenly

**Comment by gokulcoder7** [comment]
[server.log](https://github.com/user-attachments/files/17783474/server.log)
[server-1.log](https://github.com/user-attachments/files/17783477/server-1.log)

**Comment by gokulcoder7** [comment]
[server-3.log](https://github.com/user-attachments/files/17783479/server-3.log)
[server-3.log](https://github.com/user-attachments/files/17783480/server-3.log)
[server-5.log](https://github.com/user-attachments/files/17783481/server-5.log)
[server-5.log](https://github.com/user-attachments/files/17783482/server-5.log)

**Comment by gokulcoder7** [comment]
[server-2.log](https://github.com/user-attachments/files/17783484/server-2.log)
[server-3.log](https://github.com/user-attachments/files/17783485/server-3.log)
[server-4.log](https://github.com/user-attachments/files/17783486/server-4.log)
[server-5.log](https://github.com/user-attachments/files/17783487/server-5.log)
[server.log](https://github.com/user-attachments/files/17783488/server.log)
[server-1.log](https://github.com/user-attachments/files/17783489/server-1.log)

**Comment by gokulcoder7** [comment]
@rick-github please help me

**Comment by rick-github** [comment]
It seems that upgrading from an old version of ollama to 0.4.2 fails - my virtual windows box was 0.3.14, it got upgraded to 0.4.2 and failed in the same way as your logs, missing runners.  It was fixed by just installing ollama again from the front page: https://ollama.com/download/windows.  I wasn't able to repeat this - I deleted 0.3.14 via Windows uninstall, installed 0.3.14 and upgraded to 0.4.2 via ollama and this time it worked, so I don't know why it failed the first time.  I recommend just re-installing.

**Comment by zhoufy20** [comment]
> It seems that upgrading from an old version of ollama to 0.4.2 fails - my virtual windows box was 0.3.14, it got upgraded to 0.4.2 and failed in the same way as your logs, missing runners. It was fixed by just installing ollama again from the front page: https://ollama.com/download/windows. I wasn't able to repeat this - I deleted 0.3.14 via Windows uninstall, installed 0.3.14 and upgraded to 0.4.2 via ollama and this time it worked, so I don't know why it failed the first time. I recommend just re-installing.

How can i solve this
```
PS C:\Users\Feiyu> ollama -v
Warning: could not connect to a running Ollama instance
Warning: client version is 0.4.2
PS C:\Users\Feiyu> ollama run qwen2.5-coder:7b
Error: could not connect to ollama app, is it running?
```

**Comment by rick-github** [comment]
Reinstall olllama.

**Comment by zhoufy20** [comment]
> Reinstall olllama.

PS C:\Users\Feiyu> ollama serve
2024/11/17 22:31:14 routes.go:1189: INFO server config env="map[CUDA_VISIBLE_DEVICES: GPU_DEVICE_ORDINAL: HIP_VISIBLE_DEVICES: HSA_OVERRIDE_GFX_VERSION: HTTPS_PROXY:http://127.0.0.1:1080 HTTP_PROXY:http://127.0.0.1:1080 NO_PROXY: OLLAMA_DEBUG:false OLLAMA_FLASH_ATTENTION:false OLLAMA_GPU_OVERHEAD:0 OLLAMA_HOST:http://0.0.0.0:11434 OLLAMA_INTEL_GPU:false OLLAMA_KEEP_ALIVE:5m0s OLLAMA_LLM_LIBRARY: OLLAMA_LOAD_TIMEOUT:5m0s OLLAMA_MAX_LOADED_MODELS:0 OLLAMA_MAX_QUEUE:512 OLLAMA_MODELS:0.0.0.0 OLLAMA_MULTIUSER_CACHE:false OLLAMA_NOHISTORY:false OLLAMA_NOPRUNE:false OLLAMA_NUM_PARALLEL:0 OLLAMA_ORIGINS:[http://localhost https://localhost http://localhost:* https://localhost:* http://127.0.0.1 https://127.0.0.1 http://127.0.0.1:* https://127.0.0.1:* http://0.0.0.0 https://0.0.0.0 http://0.0.0.0:* https://0.0.0.0:* app://* file://* tauri://* vscode-webview://*] OLLAMA_SCHED_SPREAD:false OLLAMA_TMPDIR: ROCR_VISIBLE_DEVICES:]"
time=2024-11-17T22:31:14.524+08:00 level=INFO source=images.go:755 msg="total blobs: 0"
time=2024-11-17T22:31:14.525+08:00 level=INFO source=images.go:762 msg="total unused blobs removed: 0"
time=2024-11-17T22:31:14.525+08:00 level=INFO source=routes.go:1240 msg="Listening on [::]:11434 (version 0.4.2)"
time=2024-11-17T22:31:14.526+08:00 level=INFO source=common.go:49 msg="Dynamic LLM libraries" runners="[cuda_v11 cuda_v12 rocm cpu cpu_avx cpu_avx2]"
time=2024-11-17T22:31:14.526+08:00 level=INFO source=gpu.go:221 msg="looking for compatible GPUs"
time=2024-11-17T22:31:14.526+08:00 level=INFO source=gpu_windows.go:167 msg=packages count=1
time=2024-11-17T22:31:14.526+08:00 level=INFO source=gpu_windows.go:214 msg="" package=0 cores=18 efficiency=0 threads=36
time=2024-11-17T22:31:14.934+08:00 level=INFO source=gpu.go:328 msg="detected OS VRAM overhead" id=GPU-7ad40336-8f4e-040f-a38f-8fd70facaffa library=cuda compute=8.6 driver=12.7 name="NVIDIA GeForce RTX 3090" overhead="1013.8 MiB"
time=2024-11-17T22:31:15.156+08:00 level=INFO source=types.go:123 msg="inference compute" id=GPU-7ad40336-8f4e-040f-a38f-8fd70facaffa library=cuda variant=v12 compute=8.6 driver=12.7 name="NVIDIA GeForce RTX 3090" total="24.0 GiB" available="22.8 GiB"
time=2024-11-17T22:31:15.157+08:00 level=INFO source=types.go:123 msg="inference compute" id=GPU-85678040-95fe-8eaa-e42b-36921fc7f9b5 library=cuda variant=v12 compute=8.6 driver=12.7 name="NVIDIA GeForce RTX 3090" total="24.0 GiB" available="22.8 GiB"
[GIN] 2024/11/17 - 22:31:22 | 200 |      1.7617ms |       127.0.0.1 | GET      "/api/tags"
[GIN] 2024/11/17 - 22:31:53 | 200 |         564µs |       127.0.0.1 | GET      "/api/tags"
[GIN] 2024/11/17 - 22:32:24 | 200 |         577µs |       127.0.0.1 | GET      "/api/tags"
[GIN] 2024/11/17 - 22:32:55 | 200 |       553.1µs |       127.0.0.1 | GET      "/api/tags"
[GIN] 2024/11/17 - 22:33:00 | 200 |       365.4µs |             ::1 | GET      "/"
[GIN] 2024/11/17 - 22:33:00 | 404 |            0s |             ::1 | GET      "/favicon.ico"
[GIN] 2024/11/17 - 22:33:26 | 200 |       644.9µs |       127.0.0.1 | GET      "/api/tags"
[GIN] 2024/11/17 - 22:33:50 | 404 |      1.0706ms |             ::1 | POST     "/api/generate"
[GIN] 2024/11/17 - 22:33:56 | 200 |      1.0949ms |       127.0.0.1 | GET      "/api/tags"
[GIN] 2024/11/17 - 22:34:27 | 200 |       604.3µs |       127.0.0.1 | GET      "/api/tags"
[GIN] 2024/11/17 - 22:34:58 | 200 |            0s |       127.0.0.1 | GET      "/api/tags"
[GIN] 2024/11/17 - 22:35:29 | 200 |       561.8µs |       127.0.0.1 | GET      "/api/tags"
[GIN] 2024/11/17 - 22:36:01 | 200 |       569.4µs |       127.0.0.1 | GET      "/api/tags"
[GIN] 2024/11/17 - 22:36:33 | 200 |       535.1µs |       127.0.0.1 | GET      "/api/tags"
[GIN] 2024/11/17 - 22:37:04 | 200 |       804.1µs |       127.0.0.1 | GET      "/api/tags"
[GIN] 2024/11/17 - 22:37:35 | 200 |         524µs |       127.0.0.1 | GET      "/api/tags"
[GIN] 2024/11/17 - 22:38:06 | 200 |       572.3µs |       127.0.0.1 | GET      "/api/tags"

this is the log file.

**Comment by rick-github** [comment]
```
HTTP_PROXY:http://127.0.0.1:1080
```
Set `NO_PROXY=127.0.0.1` in the client environment.

**Comment by zhoufy20** [comment]
> Reinstall olllama.

@rick-github ,Sorry, it refails as reinstallment:
![image](https://github.com/user-attachments/assets/d3654965-d717-44fe-8bcd-c1c9d92c3d86)

**Comment by zhoufy20** [comment]
Ok, I tried but no success:
![image](https://github.com/user-attachments/assets/2c361fd8-41d7-42df-bada-7dcd49c782f8)
![image](https://github.com/user-attachments/assets/f77963fc-7de1-4084-9f0e-7c42eceddf4b)
![image](https://github.com/user-attachments/assets/bd51a6a4-e8c4-44ee-a930-b6f5bdfdc16b)
![image](https://github.com/user-attachments/assets/a1c69474-1769-4225-94d2-dfa5b6d7d1c4)
Thanks a lot!

**Comment by rick-github** [comment]
Set `NO_PROXY` in the **client** environment.

You want the server to be able to connect to the internet via your proxy on 127.0.0.1:1080, so you need to set `HTTPS_PROXY` but not `NO_PROXY` in the **server** environment.

You want the client to be able to connect to the ollama server at 127.0.0.1:11434, so you need to set `NO_PROXY` _or_ not set `HTTP_PROXY` in the **client** environment.

**Comment by rick-github** [comment]
```
127.0.0.1:1080: connectex: No connection could be made because the target machine actively refused it.
```
Your proxy needs to be configured.  https://clashfor.org/tutorial.html

**Comment by zhoufy20** [comment]
> HTTP_PROXY

Thanks a lot for your detailed explanations and it is ok now.

**Comment by rick-github** [comment]
> "127.0.0.1:11434 bind already in use"

You need to stop the old server before running a new server.

**Comment by CHEN1998-xinyu** [comment]
could you solve this problem?  I also have same problem, can I chat with you in wechat?

**Comment by rick-github** [comment]
Open a new ticket.  Describe your problem.  Add [server logs](https://github.com/ollama/ollama/blob/main/docs/troubleshooting.md#how-to-troubleshoot-issues).

**Comment by zhoufy20** [comment]
> could you solve this problem? I also have same problem, can I chat with you in wechat?

maybe zhoufy2002 if i can help u！

**Comment by CHEN1998-xinyu** [comment]
thank you, after reinstall, this question be resovled

**Comment by Eyion** [comment]
使用“ollama run qwen2.5:7b”时，提示“Error: could not connect to ollama app, is it running?”
使用“ollama serve”时，提示“Error: listen tcp 127.0.0.1:11434: bind: An attempt was made to access a socket in a way forbidden by its access permissions.”

**Comment by rick-github** [comment]
https://github.com/ollama/ollama/issues/5795#issuecomment-2239525601
