### ISSUE TITLE
为什么CPU只占用百分之六，但是运行的时候，CPU出力的程度比GPU的程度还高呢？如何更多的让GPU干活呢？

### ISSUE THREAD

**Issue by fg2501** [ollama/ollama#7700]
### What is the issue?

![image](https://github.com/user-attachments/assets/4522364e-dea7-4ac8-853a-49b63020eeac)
如何使得GPU干活的时候，百分百出力呢？

### OS

Windows

### GPU

Nvidia

### CPU

AMD

### Ollama version

0.3.13

**Comment by rick-github** [comment]
> 如何使得GPU干活的时候，百分百出力呢？

Use a model that fits 100% on the GPU.

**Comment by fg2501** [comment]
> > 如何使得GPU干活的时候，百分百出力呢？
> 
> 使用一个能够 100%运行在 GPU 上的模型。

大佬，除了这个方法以外，还有其他方法吗？

**Comment by rick-github** [comment]
qwen2.5b doesn't need 15GB to run:
```console
$ ollama ps
NAME           ID              SIZE      PROCESSOR    UNTIL   
qwen2.5:14b    7cdf5a0187d5    9.9 GB    100% GPU     Forever    
```
If you share [server logs](https://github.com/ollama/ollama/blob/main/docs/troubleshooting.md#how-to-troubleshoot-issues), we may be able to pinpoint why the model is so large.  I suspect `num_ctx` or `OLLAMA_NUM_PARALLEL` are larger than usual.
