### ISSUE TITLE
Error: Head "https://localhost:11434/": http: server gave HTTP response to HTTPS client

### ISSUE THREAD

**Issue by yipy0005** [ollama/ollama#7708]
### What is the issue?

I was running `ollama ls` on my Macbook running on Sequoia and I saw this error message:

`Error: Head "https://localhost:11434/": http: server gave HTTP response to HTTPS client`

What can I do to resolve this?

### OS

macOS

### GPU

Apple

### CPU

Apple

### Ollama version

0.4.2

**Comment by rick-github** [comment]
Configure your client to use plain http to connect to ollama: `http://localhost:11434`.

**Comment by yipy0005** [comment]
Thanks, that worked perfectly!
