### ISSUE TITLE
Wrong license of the `minicpm-v` model

### ISSUE THREAD

**Issue by NeuroWhAI** [ollama/ollama#7714]
### What is the issue?

The license for the `minicpm-v` model currently specified in the Ollama is Apache 2.0.
But the model license is actually 'MiniCPM Model License' of OpenBMB.
Ollama Page: https://ollama.com/library/minicpm-v
MiniCPM License: https://github.com/OpenBMB/MiniCPM/blob/main/MiniCPM%20Model%20License.md
Please let me know if I misunderstand something.

**Comment by jmorganca** [comment]
Thanks for reporting. This should be fixed now.
