### ISSUE TITLE
Ollama 0.4 not using VRAM on AMD RX 7900 XTX

### ISSUE THREAD

**Issue by galizhur** [ollama/ollama#7715]
### What is the issue?

Any model that I load seems to use system RAM instead the VRAM. This doesn't happen on version 0.3 of ollama. Something is clearly wrong because ollama freezes after a couple of requests and the only way to make it work again is to restart it every minute.

Here is the server log [server.log](https://github.com/user-attachments/files/17793658/server.log)

Also below I attached 2 screeshots with ollama with a loaded model and ollama stut down.

Model unloaded
![Screenshot 2024-11-18 042227](https://github.com/user-attachments/assets/6f9d8901-c9fd-4537-ab9c-02c03d348899)

Model loaded
![Screenshot 2024-11-18 042318](https://github.com/user-attachments/assets/2d76d52e-8187-47e5-a932-48eace396f8f)

### OS

Windows

### GPU

AMD

### CPU

AMD

### Ollama version

0.4.2

**Comment by MrMiladinovic** [comment]
Same issue here
After updating amd drivers to v-24.10.1 was working earlier today, rolling back does not seem to fix it

**Comment by dhiltgen** [comment]
@MrMiladinovic can you clarify which version you rolled back to?  I believe you'll need to go back to 24.8.1 or older to resolve the problem until a newer driver is released.

We're tracking the driver bug with #7107

**Comment by Torckane** [comment]
Same problem for me on 7900 XTX. A day i have do an uptade of ollama, and now he do not want work anymore.
I have have try many things, re-install ollama. Uninstall > Re-install rocm 6.1.2 and 5.7.1 and every combinaison.
He do not want heard anything, only cpu use.
With https://github.com/likelovewant/ollama-for-amd
I have made it work on GPU now ... but he only use CPU RAM, he do not want VRAM.

PS C:\Users\Evangelion> ollama ps
NAME                    ID              SIZE     PROCESSOR    UNTIL
mistral-small:latest    d095cd553b04    15 GB    100% GPU     4 minutes from now

Where are the older version of ollama ? I want try themes !

Windows 10 - 7900 XTX - Ollama 0.4.2

**Comment by MrMiladinovic** [comment]
@Torckane , we are referring to AMD drivers>
[Windows 11](https://drivers.amd.com/drivers/whql-amd-software-adrenalin-edition-24.8.1-win10-win11-aug-rdna.exe)
[Windows 10](https://drivers.amd.com/drivers/whql-amd-software-adrenalin-edition-24.8.1-win10-win11-aug-rdna.exe)
Hope this helps
