### ISSUE TITLE
Performance regression for 0.4.* caused by number of input tokens

### ISSUE THREAD

**Issue by rick-github** [ollama/ollama#7717]
### What is the issue?

As input tokens go up, the rate of token generation goes down.  Once the rate has decreased, it becomes a ceiling for subsequent generations.

Affects both CPU and GPU generations, but more pronounced for GPU.  Tested with llama3.2:3b-instruct-q4_K_M, llama3.1:8b-instruct-q4_0, qwen2.5:0.5b-instruct-q4_K_M, aya-expanse:8b-q4_K_M.

```console
$ model=llama3.2:3b-instruct-q4_K_M ; curl -s localhost:11434/api/generate -d '{"model":"'$model'","keep_alive":0}' >/dev/null ; for p in 1 2 ; do echo "# pass $p" ; for n in 32 64 128 256 512 1024 2048 4096 8192 16384  ; do curl -s localhost:11434/api/generate -d '{"model":"'$model'","prompt":'"$((echo write a story with these words ; cat /usr/share/dict/words) | dd bs=1 count=$n status=none | jq -sR .)"',"options":{"seed":42,"temperature":0,"num_gpu":-1,"num_ctx":16384,"num_predict":256},"stream":false}' | jq -rc '.|"\(.prompt_eval_count) \(.eval_count/(.eval_duration/1000000000))"' ; done ; done
# pass 1
33 128.12812812812814
52 127.68079800498754
91 124.21154779233382
168 118.84865366759517
307 108.47457627118645
543 92.51897361763643
1036 73.73271889400922
2012 70.64017660044149
3793 67.31527741256903
7540 59.60419091967404
# pass 2
33 79.08557306147668
52 78.93925377736664
91 78.2874617737003
168 78.09640024405125
307 74.4186046511628
543 74.63556851311952
1036 72.62411347517731
2012 68.5041477120685
3793 66.84073107049608
7540 59.327925840092696
```

0.4.2, llama3.2:3b-instruct-q4_K_M, GPU:
![image](https://github.com/user-attachments/assets/d9e00d5e-327d-4ac9-aa45-f9ae4ebd016e)

0.3.14, llama3.2:3b-instruct-q4_K_M, GPU:
![image](https://github.com/user-attachments/assets/ed869309-bd4b-413a-86e7-82ea0450fef6)

### OS

Linux, Docker

### GPU

Nvidia

### CPU

Intel

### Ollama version

0.3.14, 0.4.0, 0.4.1, 0.4.2

**Comment by jmorganca** [comment]
@rick-github thanks for filing this and for graphing the results. Which kind of NVIDIA GPU do you have?

**Comment by rick-github** [comment]
Tested on RTX4070 (12G), RTX3080 (16G).  All models GPU resident when tested.

**Comment by varyagnord** [comment]
On Windows we have same problem.

**Comment by murzein** [comment]
+AMD 7900XTX

**Comment by rick-github** [comment]
Same behaviour observed on A100 (40G) and A100x4 (using `OLLAMA_SCHED_SPREAD`).

**Comment by jessegross** [comment]
Thanks a lot @rick-github for the great data! Is it possible for you to try this on `main`?

807ace5 solved the performance issues that I was seeing. I didn't get quite as clean results as you did when you ran the script here but that looks good for me as well.

**Comment by jessegross** [comment]
Thanks so much for testing!
