### ISSUE TITLE
AMD graphics card encounters a memory usage exception while running on Windows 11.

### ISSUE THREAD

**Issue by uamind** [ollama/ollama#7721]
### What is the issue?

cpu: ryzen 3900xt
gpu: amd 6800xt
memory: ddr4 64g
os: windows 11 23h2
ui: open-webui
model: mistral-nemo

 An scheduling exception related to GPU memory occurred during the execution of Mistral-Nemo, causing the GPU memory usage to be allocated to shared GPU memory instead of the actual GPU memory (even though there was sufficient GPU memory available), resulting in a total usage of 11GB. However, there were still 11.6GB of GPU memory left unused. This resulted in slow performance with only 3.89 tokens being processed.

Previously, running this same 12B model did not allocate shared GPU memory, but when using the Mistral model, it could utilize up to 52.28 tokens with a GPU memory usage of 8.4GB.

![Screenshot 2024-11-18 152716](https://github.com/user-attachments/assets/b46425d7-667f-405c-98cc-dc5a6adc6ac4)

### OS

Windows

### GPU

AMD

### CPU

AMD

### Ollama version

0.4.2

**Comment by rick-github** [comment]
[Server logs](https://github.com/ollama/ollama/blob/main/docs/troubleshooting.md#how-to-troubleshoot-issues) may aid in debugging.

**Comment by galizhur** [comment]
It looks like we have the same issue https://github.com/ollama/ollama/issues/7715

**Comment by MrMiladinovic** [comment]
Same issue here

**Comment by dhiltgen** [comment]
This is a known driver bug tracked in #7107.  Until the next driver comes out, the workaround is to downgrade to an older driver.

**Comment by uamind** [comment]
Thank you.
