### ISSUE TITLE
Whether the model can be started by using its Id?

### ISSUE THREAD

**Issue by qq1273834091** [ollama/ollama#7730]
<img width="765" alt="image" src="https://github.com/user-attachments/assets/f16a1038-2847-419f-b7c0-1700e0c9f58f">

**Comment by rick-github** [comment]
Where would this be useful?  You can't run a model by the ID, but you can create a copy of it to act as an alias.  It uses the same files as the originals, so doesn't take any extra space (other than the new manifest file):
```console
$ ollama cp qwen2.5-coder:1.5b 6d3abb8d2d53
copied 'qwen2.5-coder:1.5b' to '6d3abb8d2d53'
$ ollama run 6d3abb8d2d53 ''
$ ollama ps
NAME                   ID              SIZE      PROCESSOR    UNTIL
6d3abb8d2d53:latest    6d3abb8d2d53    1.9 GB    100% GPU     Forever
```
