### ISSUE TITLE
add a  Feature : clone and duplicate model from scratch when creating new model from Modelfile to laod to gpu memory 

### ISSUE THREAD

**Issue by looijijohn** [ollama/ollama#7734]
when we create a new_model from BaseModel 
ollama does not load model to memory again 
he used loaded BaseModel as new model and NewModel does not load as seprate model 

we want use two model as sepearate two load both in gpu memory we enough memory

**Comment by rick-github** [comment]
https://github.com/ollama/ollama/issues/7206#issuecomment-2413928300

**Comment by rick-github** [comment]
dupe #7206
