### ISSUE TITLE
SSL support (For Brave Leo AI & others)

### ISSUE THREAD

**Issue by NikosDi** [ollama/ollama#7736]
Hello.
Using Brave Leo AI with Ollama locally, on the same computer, is working like a charm using HTTP://localhost:11434/v1/chat/completions

But when I try to use Ollama via LAN from a different PC, Brave Leo demands a secure HTTP connection - HTTPS is mandatory and Brave setting doesn't allow you to put a simple HTTP address.

I have set `OLLAMA_HOST=0.0.0.0` as environment variable enabling network access and Ollama listens on HTTP://myip:11434 locally.

Is it possible for the Ollama serving framework to listen also on HTTP(S) SSL ?

thank you

**Comment by rick-github** [comment]
ollama is just an inference engine, it's expected that extended functionality (SSL, SSO, failover, etc) will be handled by external infrastructure.

In the case of SSL support, you can install an SSL proxy (eg [local-ssl-proxy](https://github.com/cameronhunter/local-ssl-proxy)) and have Brave connect to the SSL port you choose.
