### ISSUE TITLE
Support Pixtral Large

### ISSUE THREAD

**Issue by YuntianZhao** [ollama/ollama#7747]
Mistral AI just released Pixtral Large, a 124B multimodal model built on top of Mistral Large 2.
See https://huggingface.co/mistralai/Pixtral-Large-Instruct-2411

**Comment by rick-github** [comment]
We don't have [pixtral](https://github.com/ollama/ollama/issues/6748) yet, pixtral-large will probably be gated on that.

**Comment by mchiang0610** [comment]
merging this issue with #6748

Thank you!!
