### ISSUE TITLE
300+mb of ram while idle

### ISSUE THREAD

**Issue by Omar-000** [ollama/ollama#7754]
### What is the issue?

![Screenshot_2024-11-20_05-47-48](https://github.com/user-attachments/assets/8e1cdf33-37f3-4d6e-b512-839336408283)

I made sure to stop all running models and i restarted my system also

### OS

Linux

### GPU

AMD, Intel

### CPU

Intel

### Ollama version

0.3.12

**Comment by Coecoenut** [comment]
Hi,
please try the current 0.4.2 release. On my machine, it only consumes 50 MB

**Comment by dhiltgen** [comment]
I'm anticipating RAM usage of the main ollama server to come down once #7499 merges and we're no longer carrying the runners as payloads inside the main binary.
