### ISSUE TITLE
qwen2.5-coder isn't utilizing the GPU

### ISSUE THREAD

**Issue by Novido** [ollama/ollama#7760]
### What is the issue?

When running a query with qwen2.5 (32b) it only uses the CPU for some reason. I can switch to another model (llama, phi, gemma) and they all utilize the GPU.

Reproduce:
1. Run docker in an Ubuntu container on an standalone server
2. Install Ollama and Open-Webui
3. Download models qwen2.5-coder:32b and another model like llama3.2
4. Run a query on llama3.2 and use nvtop, where you have ollama installed, to see GPU usage 
5. Run a query on qwen2.5 and use nvtop to see GPU usage. It should show similar to step 4 but it doesn't.

### OS

Linux, Docker

### GPU

Nvidia

### CPU

Intel

### Ollama version

0.4.1

**Comment by rick-github** [comment]
qwen2.5:32b is [20GB](https://ollama.com/library/qwen2.5-coder:32b), llama3.2 is [2GB](https://ollama.com/library/llama3.2:latest).

[Server logs](https://github.com/ollama/ollama/blob/main/docs/troubleshooting.md#how-to-troubleshoot-issues) will show memory allocation, and `ollama ps` will show how much of the model is residing in GPU vs CPU.
