### ISSUE TITLE
Add "loaded" status in Model API

### ISSUE THREAD

**Issue by explorigin** [ollama/ollama#7780]
Add an indicator to the models list API endpoint as well as the model information endpoint indicating if the model is currently loaded in RAM.

This could allow frontends to direct queries to the loaded model for faster response if the query isn't necessarily model-specific. Other use-cases could be for monitoring services to prefer keeping one model "hot" while other models may be used periodically.

**Comment by rick-github** [comment]
The currently loaded model(s) can be queried with /api/ps:
```console
$ curl -s localhost:11434/api/ps | jq '.models[].name'
"qwen2.5:0.5b-8k"
"llama3.2:latest"
```

**Comment by explorigin** [comment]
Solid! That serves the purpose. Thanks!
