### ISSUE TITLE
How to prevent Ollama requests to change the running model on Ollama?

### ISSUE THREAD

**Issue by WoodenTiger000** [ollama/ollama#7789]
How can we prevent Ollama requests to change the running model on Ollama?

**Comment by jmorganca** [comment]
If I understand correctly, this is the model loading/unloading when runtime parameters change? As long as key runtime parameters such as `num_ctx` don't change and the model should stay loaded. Let me know if this doesn't solve the issue for you. Alternatively you can use `OLLAMA_KEEP_ALIVE=-1` to make sure models don't unload themselves after a set amount of time.
