### ISSUE TITLE
llama3.2-vision:90b unquantized?

### ISSUE THREAD

**Issue by eggsbenedicto** [ollama/ollama#7794]
Hi,

First of all, thanks for your work. 

I tried out the llama3.2-vision:90b model on ollama and it seems to underperform the version available on the build.nvidia.com API, with the same prompt and settings. Is this because it is a quantized model? The ollama documentation on the official website says it has "Quantization Q4_K_M"

If so, is it possible to offer an un-quantized or less quantized version in ollama? I usually do AI tasks on a rented h100, so VRAM is not that much of an issue to me.

Thanks

**Comment by rick-github** [comment]
https://ollama.com/library/llama3.2-vision:90b-instruct-fp16

**Comment by eggsbenedicto** [comment]
Thanks! Didn't see the drop-down
