### ISSUE TITLE
What splitter in documents?

### ISSUE THREAD

**Issue by ATpiu** [ollama/ollama#7797]
### What is the issue?

I am exploring rag function of ollama: Admin Panel->Settings->Documents, setting is as following:
<img width="1148" alt="setting" src="https://github.com/user-attachments/assets/4fcf5304-4fe6-4ba5-8131-85874de50f1a">
What splitter and what lib you use here?(e.g: SentenceSplitter in llama_index or CharacterTextSplitter in Langchain?)

### OS

macOS

### GPU

Apple

### CPU

Apple

### Ollama version

0.4.1

**Comment by rick-github** [comment]
ollama is just an inference engine, it doesn't do RAG.  That sort of functionality is handled by other projects, this looks like [open-webui](https://github.com/open-webui/open-webui)
