### ISSUE TITLE
langchain_ollama tool_calls is None

### ISSUE THREAD

**Issue by UICJohn** [ollama/ollama#7799]
### What is the issue?

`  File "/workspaces/vivichains-base/.venv/lib/python3.11/site-packages/langchain_ollama/chat_models.py", line 732, in _agenerate
    final_chunk = await self._achat_stream_with_aggregation(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/vivichains-base/.venv/lib/python3.11/site-packages/langchain_ollama/chat_models.py", line 602, in _achat_stream_with_aggregation
    tool_calls=_get_tool_calls_from_response(stream_resp),
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/vivichains-base/.venv/lib/python3.11/site-packages/langchain_ollama/chat_models.py", line 71, in _get_tool_calls_from_response
    for tc in response["message"]["tool_calls"]:
TypeError: 'NoneType' object is not iterable`

when requesting message from langchain-ollama to ollama server, the message from response is:  Message(role='assistant', content='It', images=None, tool_calls=None), which make `if "tool_calls" in response["message"]` is always true.

langchain-ollama version: 0.2.0

### OS

macOS

### GPU

Apple

### CPU

Apple

### Ollama version

0.4.3

**Comment by rick-github** [comment]
langchain-ollama is a [langchain](https://github.com/langchain-ai/langchain) project.

**Comment by edmcman** [comment]
I think it's from ollama python package 0.4.0.  https://github.com/langchain-ai/langchain/pull/28291

**Comment by UICJohn** [comment]
Well, wrong place to post the bug report.Anyone with the same issue can refer to this link: https://github.com/langchain-ai/langchain/issues/28281

**Comment by edmcman** [comment]
So was the API breaking change in Ollama intentional?

**Comment by rick-github** [comment]
> So was the API breaking change in Ollama intentional?

Probably  a question for [ollama-python](https://github.com/ollama/ollama-python/issues).
