### ISSUE TITLE
GPU usage is not high, but the display memory is full

### ISSUE THREAD

**Issue by duolax** [ollama/ollama#7801]
### What is the issue?

![image](https://github.com/user-attachments/assets/1c2cf4c5-069b-4d48-8d9f-8d8d4a4ebcd6)
When running the model, the CPU usage is often full, but the GPU usage is not high. However, after checking the details, it turns out that the GPU memory is fully occupied during operation

### OS

Windows

### GPU

Nvidia

### CPU

AMD

### Ollama version

0.4.2

**Comment by rick-github** [comment]
If you have loaded a model that does not fit 100% on the GPU, part of the model will be loaded in system RAM and the CPU is used for inference on that part of the model.  When you do a completion, the part that runs on the GPU will finish quickly, and the part on the CPU will take longer.  Thus the CPU will have high usage while the GPU is idle waiting for the next completion.

**Comment by jmorganca** [comment]
Thanks for the issue. @rick-github is correct – this is common if running the model requires the CPU
