### ISSUE TITLE
problem with ollama serve 

### ISSUE THREAD

**Issue by atb29** [ollama/ollama#7803]
### What is the issue?

C:\Users\allowdin>ollama serve
Error: listen tcp 127.0.0.1:11434: bind: Only one usage of each socket address (protocol/network address/port) is normally permitted.

### OS

Windows

### GPU

Other

### CPU

Intel

### Ollama version

0.3.13

**Comment by rick-github** [comment]
possibly wsl: https://github.com/ollama/ollama/issues/6701
