### ISSUE TITLE
Not reading image files with vision models

### ISSUE THREAD

**Issue by whatToUseThisFor** [ollama/ollama#7804]
### What is the issue?

![test](https://github.com/user-attachments/assets/918f8e7c-ac38-468b-8921-5da4b744b43f)
When I try to give an image file to a model with the "vision" tag, it says that it can't access files on my computer.

I've tried with llava 7b, llava 13b, and llama3.2-vision (all times I tried were on a terminal)

If it helps, I'm using a card with 8gb of vram, and have 32gb of DIMM ram

### OS

Windows

### GPU

Nvidia

### CPU

Intel

### Ollama version

0.4.3

**Comment by rick-github** [comment]
https://github.com/ollama/ollama/issues/7553

**Comment by whatToUseThisFor** [comment]
> #7553

sorry, this was my first bug report, forgot that you were supposed to check

**Comment by whatToUseThisFor** [comment]
> > #7553
> 
> sorry, this was my first bug report, forgot that you were supposed to check

nevermind, that didn't work

**Comment by rick-github** [comment]
Actually, I just noticed that you are passing a .ico file.  The only image formats ollama understands is JPG and PNG.

**Comment by whatToUseThisFor** [comment]
Thanks!
