### ISSUE TITLE
Not utilizing GPU

### ISSUE THREAD

**Issue by F-U-B-AR** [ollama/ollama#7813]
### What is the issue?

OS: Debian 12
GPU: Nvidia RTX  3060

Hello, Ive been trying to solve this for months, but I think its time to get some help! 
Essentially on Debian, Ollama will only use the CPU and does not seem to discover my GPU:

I have installed the latest CUDA toolkit using:
https://developer.nvidia.com/cuda-downloads?target_os=Linux&target_arch=x86_64&Distribution=Debian

Here is the log of when I start Ollama:
`2024/11/24 09:11:28 routes.go:1197: INFO server config env="map[CUDA_VISIBLE_DEVICES: GPU_DEVICE_ORDINAL: HIP_VISIBLE_DEVICES: HSA_OVERRIDE_GFX_VERSION: HTTPS_PROXY: HTTP_PROXY: NO_PROXY: OLLAMA_DEBUG:false OLLAMA_FLASH_ATTENTION:false OLLAMA_GPU_OVERHEAD:0 OLLAMA_HOST:http://127.0.0.1:11434 OLLAMA_INTEL_GPU:false OLLAMA_KEEP_ALIVE:5m0s OLLAMA_LLM_LIBRARY: OLLAMA_LOAD_TIMEOUT:5m0s OLLAMA_MAX_LOADED_MODELS:0 OLLAMA_MAX_QUEUE:512 OLLAMA_MODELS:/home/null/.ollama/models OLLAMA_MULTIUSER_CACHE:false OLLAMA_NOHISTORY:false OLLAMA_NOPRUNE:false OLLAMA_NUM_PARALLEL:0 OLLAMA_ORIGINS:[http://localhost https://localhost http://localhost:* https://localhost:* http://127.0.0.1 https://127.0.0.1 http://127.0.0.1:* https://127.0.0.1:* http://0.0.0.0 https://0.0.0.0 http://0.0.0.0:* https://0.0.0.0:* app://* file://* tauri://* vscode-webview://*] OLLAMA_SCHED_SPREAD:false OLLAMA_TMPDIR: ROCR_VISIBLE_DEVICES: http_proxy: https_proxy: no_proxy:]"
time=2024-11-24T09:11:28.169Z level=INFO source=images.go:753 msg="total blobs: 0"
time=2024-11-24T09:11:28.169Z level=INFO source=images.go:760 msg="total unused blobs removed: 0"                                                            
time=2024-11-24T09:11:28.169Z level=INFO source=routes.go:1248 msg="Listening on 127.0.0.1:11434 (version 0.4.4)"                                            
time=2024-11-24T09:11:28.169Z level=INFO source=common.go:135 msg="extracting embedded files" dir=/tmp/ollama1083297226/runners                              
time=2024-11-24T09:11:28.252Z level=INFO source=common.go:49 msg="Dynamic LLM libraries" runners="[cuda_v11 cuda_v12 rocm cpu cpu_avx cpu_avx2]"
time=2024-11-24T09:11:28.252Z level=INFO source=gpu.go:221 msg="looking for compatible GPUs"
time=2024-11-24T09:11:29.433Z level=WARN source=gpu.go:613 msg="unknown error initializing cuda driver library /usr/lib/x86_64-linux-gnu/nvidia/current/libcuda.so.535.183.01: cuda driver library init failure: 999. see https://github.com/ollama/ollama/blob/main/docs/troubleshooting.md for more information"
time=2024-11-24T09:11:29.477Z level=WARN source=amd_linux.go:61 msg="ollama recommends running the https://www.amd.com/en/support/linux-drivers" error="amdgpu version file missing: /sys/module/amdgpu/version stat /sys/module/amdgpu/version: no such file or directory"
time=2024-11-24T09:11:29.477Z level=INFO source=amd_linux.go:296 msg="unsupported Radeon iGPU detected skipping" id=0 total="512.0 MiB"
time=2024-11-24T09:11:29.477Z level=INFO source=amd_linux.go:399 msg="no compatible amdgpu devices detected"
time=2024-11-24T09:11:29.477Z level=INFO source=gpu.go:386 msg="no compatible GPUs were discovered"
time=2024-11-24T09:11:29.477Z level=INFO source=types.go:123 msg="inference compute" id=0 library=cpu variant=avx2 compute="" driver=0.0 name="" total="15.0 GiB" available="12.3 GiB"
`

Any help would  be appreciated!

### OS

Linux

### GPU

Nvidia

### CPU

AMD

### Ollama version

0.4.4

**Comment by rick-github** [comment]
What does `nvidia-smi` show?

**Comment by F-U-B-AR** [comment]
NVIDIA-SMI 535.183.01             Driver Version: 535.183.01   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |                                                                    
|                                         |                      |               MIG M. |                                                                    
|=========================================+======================+======================|                                                                    
|   0  NVIDIA GeForce RTX 3060 ...    On  | 00000000:01:00.0 Off |                  N/A |                                                                    
| N/A   46C    P0              N/A /  80W |      9MiB /  6144MiB |      0%      Default

**Comment by rick-github** [comment]
Have you tried the debugging steps in https://github.com/ollama/ollama/blob/main/docs/troubleshooting.md#linux-nvidia-troubleshooting ?
