### ISSUE TITLE
Any fine-tuning ways?

### ISSUE THREAD

**Issue by Niifuji** [ollama/ollama#7815]
As I mentioned in the title, I want to "continuously" fine-tune a pre-trained model with my custom dataset and explore adding some "emotion" to it (not sure why this idea came to mind). If you have any features or suggestions for this, I would appreciate your input.

**Comment by rick-github** [comment]
ollama doesn't support fine tuning at the moment.  See [here](https://github.com/ollama/ollama/issues/156) for discussion and links to projects.
