### ISSUE TITLE
I import a IQ_4XS model but get an IQ1_M

### ISSUE THREAD

**Issue by CberYellowstone** [ollama/ollama#7816]
### What is the issue?

As the title says, I imported a custom gguf model, which is of the IQ_4XS quantization type. But after importing it, ollama show displays it as IQ1_M. Is this behavior expected? Because I saw in previous issues that support for IQ_4XS has been added, so this confuses me.
![image](https://github.com/user-attachments/assets/aab46156-2b61-4e36-a24f-c512ea3b7ce1)
![image](https://github.com/user-attachments/assets/aef1b4a8-4e46-414f-9c0f-1547a905b510)

[the gguf file](https://huggingface.co/SakuraLLM/Sakura-14B-Qwen2.5-v1.0-GGUF/blob/main/sakura-14b-qwen2.5-v1.0-iq4xs.gguf)

### OS

Windows

### GPU

Nvidia

### CPU

Intel

### Ollama version

0.4.4

**Comment by rick-github** [comment]
How was the GGUF file created?

**Comment by CberYellowstone** [comment]
> How was the GGUF file created?

Since I am not the model creator, I am not clear about the details. I have opened an [issue](https://github.com/SakuraLLM/SakuraLLM/issues/124)(in chinese) in the model creator's GitHub repository to ask about it.
By the way, before raising this issue, I asked in the Discord channel and a user told me that all models quantized with IQ_4XS seem to be displayed as IQ1_M
![image](https://github.com/user-attachments/assets/d98c926f-af73-4cdb-aa4a-4880c63a70fc)

So I think this is not an isolated case

**Comment by CberYellowstone** [comment]
Oh forgot to mention the point, this gguf file is directly downloaded from huggingface, the link is right in the previous text
Already verified to run normally, only the quantization level is incorrect, everything else is fine
Hash also matches that on huggingface

**Comment by rick-github** [comment]
Looks like the filetype defs in ollama have strayed from those in llama.cpp:
```console
$ sdiff -b <(sed -ne 's/.*LLAMA_FTYPE_MOSTLY_\([^ ]*\).*= \([0-9]*\),.*/ \2 \1/p' llama/llama.h) <(sed -ne 's/^[ \t]*fileType\([^ \t]*\).*$/\1/p' llm/filetype.go | tail +2   | cat -n | sed -e 's/[ \t][ \t]*/ /g')
 1 F16								 1 F16
 2 Q4_0								 2 Q4_0
 3 Q4_1								 3 Q4_1
 4 Q4_1_SOME_F16					      |	 4 Q4_1_F16
 5 Q4_2								 5 Q4_2
 6 Q4_3								 6 Q4_3
 7 Q8_0								 7 Q8_0
 8 Q5_0								 8 Q5_0
 9 Q5_1								 9 Q5_1
 10 Q2_K							 10 Q2_K
 11 Q3_K_S							 11 Q3_K_S
 12 Q3_K_M							 12 Q3_K_M
 13 Q3_K_L							 13 Q3_K_L
 14 Q4_K_S							 14 Q4_K_S
 15 Q4_K_M							 15 Q4_K_M
 16 Q5_K_S							 16 Q5_K_S
 17 Q5_K_M							 17 Q5_K_M
 18 Q6_K							 18 Q6_K
 19 IQ2_XXS							 19 IQ2_XXS
 20 IQ2_XS							 20 IQ2_XS
 21 Q2_K_S							 21 Q2_K_S
 22 IQ3_XS							 22 IQ3_XS
 23 IQ3_XXS							 23 IQ3_XXS
 24 IQ1_S							 24 IQ1_S
 25 IQ4_NL							 25 IQ4_NL
 26 IQ3_S							 26 IQ3_S
 27 IQ3_M						      |	 27 IQ2_S
 28 IQ2_S						      |	 28 IQ4_XS
 29 IQ2_M							 29 IQ2_M
 30 IQ4_XS						      |	 30 IQ1_M
 31 IQ1_M						      |	 31 BF16
 32 BF16						      |	 32 Unknown
 33 Q4_0_4_4						      <
 34 Q4_0_4_8						      <
 35 Q4_0_8_8						      <
 36 TQ1_0						      <
 37 TQ2_0						      <
```
ollama is missing `fileTypeIQ3_M` and fileTypeIQ4_XS should be below IQ4_XS.

**Comment by rick-github** [comment]
Note this is purely presentation, the model you've imported is still IQ_4XS, just the display of the model type was incorrect.

**Comment by CberYellowstone** [comment]
@jmorganca @rick-github
This issue still has residual effects, the quantization levels of models uploaded on ollama.com are not displayed correctly.

**Comment by rick-github** [comment]
Do you have an example?

**Comment by CberYellowstone** [comment]
> Do you have an example?

https://ollama.com/CBYellowstone/sakura-v1.0

![image](https://github.com/user-attachments/assets/f5379f02-66a1-41a4-8365-f6c0adc94c14)

The correct display should be IQ_4XS

**Comment by rick-github** [comment]
The website code is not part of the ollama project repo, so somebody else will have to fix it.  Have you tried re-pushing the model to see if it changes?

**Comment by CberYellowstone** [comment]
> The website code is not part of the ollama project repo, so somebody else will have to fix it. Have you tried re-pushing the model to see if it changes?

Okay, I understand the current situation. I will try to re-upload later.

**Comment by CberYellowstone** [comment]
> The website code is not part of the ollama project repo, so somebody else will have to fix it. Have you tried re-pushing the model to see if it changes?

This doesn't work, the problem still exists. Should I open a new issue somewhere?

**Comment by rick-github** [comment]
Open a new ticket in this tracker.
