### ISSUE TITLE
Ollama 0.4.4 docker image, unable to pull models behind proxy 

### ISSUE THREAD

**Issue by saimaheshkrishna** [ollama/ollama#7829]
### What is the issue?

After running ollama 0.4.4 docker image unable to pull models locally . Iam passing -e https_proxy.  When I just replace image tag to 0.4.2 it started working 

### OS

Docker

### GPU

Nvidia

### CPU

Intel

### Ollama version

0.4.4

**Comment by rick-github** [comment]
https://github.com/ollama/ollama/issues/7788
