### ISSUE TITLE
Please add a way to view the request after a template is applied

### ISSUE THREAD

**Issue by vt-alt** [ollama/ollama#7840]
Would be nice to view raw requests passing between ollama and model. This would be useful to debug templates (for example to debug requests with tools) and for education purposes to see how things works low level.

**Comment by rick-github** [comment]
If you set `OLLAMA_DEBUG=1` in the server environment the templated prompt will be written to the log, search for `msg="generate request"` or `msg="chat request"`, depending on which endpoint you use.

**Comment by vt-alt** [comment]
Thank you! I don't get the replies there though, only can see the reply in the next request.

**Comment by du291** [comment]
This does not seem to work in 0.9.0. Loglevel DEBUG does not contain the raw messages to and from the model.

**Comment by rick-github** [comment]
`OLLAMA_DEBUG=2`
