### ISSUE TITLE
ollama 0.4.5 on windows

### ISSUE THREAD

**Issue by UyCode** [ollama/ollama#7841]
### What is the issue?

after I installing the ollama 0.4.5 on my PC( windows 11) the version info is return back to the 0.4.1 and cannot display newly downloaded models:
![PixPin_2024-11-26_19-22-19](https://github.com/user-attachments/assets/4b9036a4-fc30-4bce-8b49-0a647cc00b1a)

also, my GPU driver version is 566
![PixPin_2024-11-26_19-23-48](https://github.com/user-attachments/assets/62bc8424-bce1-4878-a970-f0a2e5471907)

### OS

Windows

### GPU

Nvidia

### CPU

Intel

### Ollama version

0.4.5

**Comment by rick-github** [comment]
Have you previously installed ollama in WSL (https://github.com/ollama/ollama/issues/6701)?  What's in your [server logs](https://github.com/ollama/ollama/blob/main/docs/troubleshooting.md#how-to-troubleshoot-issues)?

**Comment by UyCode** [comment]
not in WSL, direct windows installation. previously fixed, it seems my problem, not installed completely. delete all files and reinstall fix this problem, thanks for reply
