### ISSUE TITLE
Error: pull model manifest, SSL_ERROR_SYSCALL in connection to ollama.com:443

### ISSUE THREAD

**Issue by zlluGitHub** [ollama/ollama#7851]
### What is the issue?

When I run 'ollama run ollama run llama3:8b', the following message appears: 
`pulling manifest 
Error: pull model manifest: Get "https://registry.ollama.ai/v2/library/qwen2.5-coder/manifests/32b": EOF
`

Execute `curl fsSL' https://ollama.com/install.sh |It also appears when sh `, the following message appears: 
` curl: (35) OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to ollama. com: 443 `cerror. 

How can it be resolved?

### OS

Linux

### GPU

Nvidia

### CPU

AMD

**Comment by jmorganca** [comment]
Hi @zlluGitHub sorry about the issue. Do you know if your system certificates are up to date (e.g. `sudo apt-get install -y ca-certificates`?) I believe this should fix the issue, but if it doesn't let me know.
