### ISSUE TITLE
embeding api issue

### ISSUE THREAD

**Issue by sycbbyes** [ollama/ollama#7853]
### What is the issue?

when call ollama 、api/embed, there is python error with message: 
ollama-webui    | 2024-11-27T04:25:57.120363066Z ValueError: [TypeError("'coroutine' object is not iterable"), TypeError('vars() argument must have __dict__ attribute')]
ollama-webui    | 2024-11-27T04:26:04.202107805Z INFO:     172.19.0.1:56148 - "POST /ollama/api/embed HTTP/1.1" 500 Internal Server Error
ollama-webui    | 2024-11-27T04:26:04.216128921Z ERROR:    Exception in ASGI application
ollama-webui    | 2024-11-27T04:26:04.216161929Z Traceback (most recent call last):
ollama-webui    | 2024-11-27T04:26:04.216170778Z   File "/usr/local/lib/python3.11/site-packages/fastapi/encoders.py", line 324, in jsonable_encoder
ollama-webui    | 2024-11-27T04:26:04.216178272Z     data = dict(obj)
ollama-webui    | 2024-11-27T04:26:04.216184675Z            ^^^^^^^^^
ollama-webui    | 2024-11-27T04:26:04.216190906Z TypeError: 'coroutine' object is not iterable

### Ollama version

0.4.5

**Comment by rick-github** [comment]
Issues with open-webui can be filed [here](https://github.com/open-webui/open-webui/issues).
