### ISSUE TITLE
Different outputs for first and subsequent inferences after model load

### ISSUE THREAD

**Issue by akamaus** [ollama/ollama#7854]
### What is the issue?

The result I get just after model load into VRAM differ from subsequent ones. It's easily reproduced and consistent. 

After issuing ollama clean, the first time I get A, and next times I get B. I tried several models (marco-o1 and qwen2.5 ) and both CPU (with num_gpu=0 option) and GPU inference and observe this behavior everywhere.

```
$ ollama clean qwen2.5
$ python -c 'from ollama import generate; gen1 = generate(model="qwen2.5", prompt="Sky is blue because", options={"temperature": 0, "seed":0, "num_predict": 100}); gen2 = generate(model="qwen2.5", prompt="Sky is blue because", options={"temperature": 0, "seed":0, "num_predict": 100}); gen3 = generate(model="qwen2.5", prompt="Sky is blue because", options={"temperature": 0, "seed":0, "num_predict": 100}); print(gen1["response"] == gen2["response"], gen2["response"] == gen3["response"])'
False True
```

### OS

Linux

### GPU

Nvidia

### CPU

Intel

### Ollama version

0.4.4

**Comment by rick-github** [comment]
```console
$ ollama -v
ollama version is 0.4.4
$ ollama stop qwen2.5
$ python -c 'from ollama import generate; gen1 = generate(model="qwen2.5", prompt="Sky is blue because", options={"temperature": 0, "seed":0, "num_predict": 100}); gen2 = generate(model="qwen2.5", prompt="Sky is blue because", options={"temperature": 0, "seed":0, "num_predict": 100}); gen3 = generate(model="qwen2.5", prompt="Sky is blue because", options={"temperature": 0, "seed":0, "num_predict": 100}); print(gen1["response"] == gen2["response"], gen2["response"] == gen3["response"])'
True True
```
What's the actual difference between the responses?  Note that there are some other [parameters](https://github.com/ollama/ollama/blob/main/docs/modelfile.md#valid-parameters-and-values) that can influence the output.

**Comment by akamaus** [comment]
I use a custom-built version from nixos-master. Maybe that's the reason.

> Note that there are some other [parameters](https://github.com/ollama/ollama/blob/main/docs/modelfile.md#valid-parameters-and-values) that can influence the output.

I'm using default settings. Which ones should I pay attention to?

**Comment by rick-github** [comment]
`top_p` can be influential, but even after setting that low, the results vary:
```console
[nix-shell:/]# ollama stop qwen2.5 ; python -c 'from ollama import generate; gen = [generate(model="qwen2.5", prompt="Sky is blue because", options={"temperature": 0, "seed":0, "top_p":0, "num_predict": 100}) for x in range(3)]; print([gen[x]["response"] == gen[x+1]["response"] for x in range(len(gen)-1)])'
[False, True]
```
It seems to only affect the first two responses, if the script does more generations the subsequent ones match.  So it might be some initialization state in the runner.  Not sure why it's affecting nixos and apparently not mint, though.  Looking through the package definition I don't see any patches that would change ollama's behaviour.

**Comment by jessegross** [comment]
This is a variation of #5321 - there is some more information in that bug that might be helpful. I'm going to close this one in favor of tracking it there.
