### ISSUE TITLE
Tool calling: LLAMA3.2 ignores param types

### ISSUE THREAD

**Issue by fce2** [ollama/ollama#7860]
### What is the issue?

if i run llama3.1 (which is ok):
```
Prompt: What is three plus one?
Calling function: add_two_numbers
Arguments: {'a': 3, 'b': 1}
Function output: 4

```
but if i run llama3.2:
```
Prompt: What is three plus one?
Calling function: add_two_numbers
Arguments: {'a': '3', 'b': '1'}
Function output: 31
```
unfortunately "llama3.2-vision:11b-instruct-q8_0" does not work at all:
`ResponseError: llama3.2-vision:11b-instruct-q8_0 does not support tools`

### OS

Windows

### GPU

Nvidia

### CPU

Intel

### Ollama version

0.4.5

**Comment by rick-github** [comment]
llama3.2 is a smaller and less capable model than llama3.1 in some areas.  It's also just an example, if you are writing tools for actual use you need to include code for verifying and processing inputs.  For example, in the case of `add_two_numbers`, you could use `return int(a) + int(b)` to protect against string arguments.  Or you could make the function more flexible:
```python
def add(l: list) -> float:
    """Adds 2 or more numbers and returns the result"""
    if isinstance(l, str):
      try:
        l = eval(l)
      except:
        pass
    return sum(l)
```

You can add tools to llama3.2-vision by using the template from llama3.2.  Be aware that if a model hasn't been trained for tool use, the results may not be great.

**Comment by fce2** [comment]
I'm using js, and yes, its already "return parseInt(a) + parseInt(b)", thanks ;-)

What do you mean with "by using the template from llama3.2" ?
Not sure how to apply (or even get) that template.

**Comment by rick-github** [comment]
Get the llama3.2 template:
```
ollama show --template llama3.2 > llama3.2.template
````
Get the llama3.2-vision Modelfile:
```
ollama show --modelfile llama3.2-vision > Modelfile
```
Edit `Modelfile`, replace `TEMPLATE` with llama3.2.template.
Create the new model:
```
ollama create llama3.2-vision-tools
```

**Comment by fce2** [comment]
thanks!!!

**Comment by fce2** [comment]
I know its the wrong place here... Sorry !
But i dont find any forum to discuss ollama things.
I've some questions where i dont find an answer.
Any idea where to go ?
Maybe a ollama-forum is a new feature-request ;-)

**Comment by rick-github** [comment]
https://discord.gg/ollama

**Comment by fce2** [comment]
Discord ??
Thats for chatting, not for serious work (i thought) ;-)
Maybe I'm too old, but I like the normal forums more... Maybe I'll make one...
Thanks.
