### ISSUE TITLE
no ssh key found

### ISSUE THREAD

**Issue by 14919598** [ollama/ollama#7862]
### What is the issue?

I am trying to pull and run the tulu 8b model,but it says:pulling manifest                                                                                                        
Error: pull model manifest: ssh: no key found,I don't know what's wrong.
![屏幕截图 2024-11-27 214649](https://github.com/user-attachments/assets/67924c3c-8635-4a32-9e1d-5e00f5863f2f)

### OS

Windows

### GPU

Nvidia

### CPU

Intel

### Ollama version

0.4.5

**Comment by mchiang0610** [comment]
hey @14919598 really sorry about this. You can restart Ollama to fix it. 

We'll fix this specific issue.
