### ISSUE TITLE
FROM command error

### ISSUE THREAD

**Issue by szzhh** [ollama/ollama#7870]
### What is the issue?

When I use Windows CMD to create a Modelfile from the huggingface model, I run the command 'FROM path-to-safetensors-directory', but it reports an error that the FROM keyword is not supported. Using git bash doesn't work either.

### OS

Windows

### GPU

Nvidia

### CPU

Intel

### Ollama version

0.4.6

**Comment by rick-github** [comment]
What's the content of your Modelfile?  What's the actual error message?

**Comment by szzhh** [comment]
> What's the content of your Modelfile? What's the actual error message?

The model file is llama3-8B that I downloaded from huggingface. The error message is as follows
![PixPin_2024-11-28_18-47-21](https://github.com/user-attachments/assets/c34b0806-db0e-4826-af9a-2ea745f40edb)

**Comment by rick-github** [comment]
That's not how you create a Modelfile.  The Modelfile contains the `FROM` command.
```
C:\Users\szh> copy con Modelfile
FROM C:/Users/szh/Downloads/Llama-3-8B
^Z
C:\Users\szf> ollama create llama-3-8b
```

**Comment by szzhh** [comment]
> That's not how you create a Modelfile. The Modelfile contains the `FROM` command.
> 
> ```
> C:\Users\szh> copy con Modelfile
> FROM C:/Users/szh/Downloads/Llama-3-8B
> ^Z
> C:\Users\szh> ollama create llama-3-8b -f Modelfile
> ```
> 
> or
> 
> ```
> C:\Users\szh> echo FROM C:/Users/szh/Downloads/Llama-3-8B > Modelfile
> C:\Users\szh> ollama create llama-3-8b -f Modelfile
> ```
> 
> or
> 
> ```
> C:\Users\szh> cd Downloads/Llama-3-8B
> C:\Users\szh\Downloads/Llama-3-8B> echo FROM . > Modelfile
> C:\Users\szh\Downloads/Llama-3-8B> ollama create llama-3-8b -f Modelfile
> ```

OK. Thanks.
