### ISSUE TITLE
how to use Modefile build customer model when gguf file have sevral sub files?

### ISSUE THREAD

**Issue by cqray1990** [ollama/ollama#7914]
### What is the issue?

like this: qwen2.5-instruct-0001.gguf
              qwen2.5-instruct-0002.gguf

**Comment by rick-github** [comment]
Merge them into a single file.  There are serveral projects on github that have a program to do that.

If you have docker installed, it's quite convenient to pull the [llama.cpp](https://github.com/ggerganov/llama.cpp) docker image (warning, 4GB): `docker pull ghcr.io/ggerganov/llama.cpp:full`.  It has a bunch of tools for dealing with GGUF files (splitting, merging, quantizing, etc)
```console
$ mv qwen2.5-instruct-0001.gguf qwen2.5-instruct-00001-of-00002.gguf
$ mv qwen2.5-instruct-0002.gguf qwen2.5-instruct-00002-of-00002.gguf
$ docker run --rm -it -v .:/workdir --workdir /workdir --entrypoint /app/llama-gguf-split ghcr.io/ggerganov/llama.cpp:full --merge qwen2.5-instruct-00001-of-00002.gguf qwen2.5-instruct.gguf
```
