### ISSUE TITLE
option to change the model loading device (CPU/GPU)

### ISSUE THREAD

**Issue by ansilmbabl** [ollama/ollama#7917]
it would be great if we can mention the device the model to be loaded (CPU/GPU).

**Comment by rick-github** [comment]
With GPUs, you can select the device by setting `CUDA_VISIBLE_DEVICES`.  If you want to load a model on CPU and avoid GPU, set `num_gpu` to zero (https://github.com/ollama/ollama/issues/6950#issuecomment-2373663650).  If you want all models to avoid GPU, set `OLLAMA_LLM_LIBRARY=cpu`.
