### ISSUE TITLE
Request to add semikong-8b to ollama

### ISSUE THREAD

**Issue by luoLojic** [ollama/ollama#7918]
I would like to deploy the semikong-8b model locally. Semikong is a large model fine-tuned from Llama focused on the semiconductor domain. You can find the model on Hugging Face at this link: “[https://huggingface.co/pentagoniac/SEMIKONG-8b-GPTQ](https://huggingface.co/pentagoniac/SEMIKONG-8b-GPTQ) and the GitHub repository here: “[https://github.com/aitomatic/semikong](https://github.com/aitomatic/semikong). The model is in the .safetensors format. I attempted to convert it using llama.cpp, but encountered the following error: “ValueError: Can not map tensor 'model.layers.0.mlp.down_proj.g_idx'”. I have not found a suitable solution for this issue. I would love to see this model added to Ollama. Thanks for the developers' hard work.
My English is not very good, and these sentences were generated using a translation tool.

**Comment by rick-github** [comment]
Unfortunately llama.cpp doesn't suppot GPTQ quantization.  In order for the model be imported, it would have to be quantized from the original source, which [doesn't appear](https://github.com/aitomatic/semikong/issues/6) to be on huggingface.  The [70B unquantized](https://huggingface.co/pentagoniac/SEMIKONG-70B/tree/main) model is available.
