### ISSUE TITLE
Custom context size not being respected.

### ISSUE THREAD

**Issue by luisbrandao** [ollama/ollama#7920]
### What is the issue?

Hello,

I noticed an inconsistent behavior. 
I had edited my model parameters on admin view and set its context size.

however, i should be able to change it "again" in the chat windows:

![image](https://github.com/user-attachments/assets/ce312d07-beae-4b86-a8e8-b79dcb786e4c)
in this image, the number "4096" does not get set, if it is already set on admin -> models.

Is this intentional?

im using:
ghcr.io/open-webui/open-webui:v0.4.7-cuda

### OS

Linux

### GPU

Nvidia

### CPU

AMD

### Ollama version

0.4.7

**Comment by rick-github** [comment]
open-webui issues should be filed in the [open-webui issue tracker](https://github.com/open-webui/open-webui/issues)

**Comment by luisbrandao** [comment]
How the hell i end up opening this in ollama!?
my bad, stroke or something.
