### ISSUE TITLE
ollama api（port：11434）Regarding parallel processing and CPU single core usage

### ISSUE THREAD

**Issue by dmmhk** [ollama/ollama#7928]
**Regarding parallel processing and CPU single core usage**
API ：http://localhost:11434/api/generate
The waiting time for API requests simultaneously is too long，CPU processing does not use multi-core；

Are there any optimization methods available?

**OS**
Windows 11
**GPU**
Nvidia 3080 16G 
**CPU**
AMD R9 5900HX
**Ollama version**
0.4.5

**Comment by rick-github** [comment]
[Server logs](https://github.com/ollama/ollama/blob/main/docs/troubleshooting.md#how-to-troubleshoot-issues) may aid in debugging?  Have you set `OLLAMA_NUM_PARALLEL`?
