### ISSUE TITLE
Upgrade to httpx~=0.28.0 (for jupyterlab compatibility)

### ISSUE THREAD

**Issue by simonaubertbd** [ollama/ollama#7929]
Hello,

Jupyterlab requires now httpx~=0.28.0 and it's now incompatible with ollama
`ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
jupyterlab 4.3.2 requires httpx~=0.28.0, but you have httpx 0.27.2 which is incompatible.`

I will have to remove ollama (since I really need jupyterlab) until it's compatible.

Best regards,

Simon

**Comment by rick-github** [comment]
This is an ollama-python issue: https://github.com/ollama/ollama-python/issues/356

**Comment by simonaubertbd** [comment]
@rick-github  right, bad repo.
