### ISSUE TITLE
failed to decode batch: could not find a kv cache slot

### ISSUE THREAD

**Issue by wangpf09** [ollama/ollama#7930]
### What is the issue?

i run the ollama 0.4.6、0.4.7 and the source code，all have this error
and i used apple m2

```
time=2024-12-04T18:45:31.343+08:00 level=WARN source=runner.go:129 msg="truncating input prompt" limit=2048 prompt=2052 keep=5 new=2048
panic: failed to decode batch: could not find a kv cache slot

goroutine 36 [running]:
main.(*Server).run(0x1400014a120, {0x1025f6d88, 0x140001000a0})
	github.com/ollama/ollama/llama/runner/runner.go:344 +0x1e0
created by main.main in goroutine 1
	github.com/ollama/ollama/llama/runner/runner.go:978 +0xb30
```

### OS

macOS

### GPU

Apple

### CPU

Apple

### Ollama version

0.4.6、0.4.7

**Comment by 123jddjb** [comment]
Hello, I meet the same problem. Can you tell me how you finally solved this problem?

**Comment by wangpf09** [comment]
> Hello, I meet the same problem. Can you tell me how you finally solved this problem?

i use ollama for graphrag， i just change the config `concurrent_requests: 1`，then it works.
