### ISSUE TITLE
Blocker message are not Blocking explicit requests.

### ISSUE THREAD

**Issue by meninblack111** [ollama/ollama#7934]
### What is the issue?

If i am testing Ollama ability to block explicit requests , it will block it once but then if I tell it to write it again it ignores the blocker/filter.

### OS

Linux, Windows

### GPU

Nvidia, AMD

### CPU

AMD

### Ollama version

0.3.13

**Comment by rick-github** [comment]
How are you giving this instruction to ollama?  What client are you using?  What model(s)?

**Comment by meninblack111** [comment]
> How are you giving this instruction to ollama? What client are you using? What model(s)?

i am using ollama run llama3.2 and i am telling write me a story with the explicit information. At first it claims it cant right it, great that's what i want to see. but then i tell it again and spews out the request with the explicit information.

**Comment by rick-github** [comment]
How are you giving this instruction to ollama on what to block?

**Comment by meninblack111** [comment]
> How are you giving this instruction to ollama on what to block?

No I am letting find out on it's own.

**Comment by meninblack111** [comment]
> How are you giving this instruction to ollama on what to block?
Is their a requirement to do that with ollama?

**Comment by rick-github** [comment]
So you aren't telling it to block explicit information, then you ask it twice to give you explicit information, and it complies the second time.  Sounds like you convinced it that you really want the information.

A model has no judgement or intelligence, it's a text completion engine and it will generate anything you ask it if it doesn't have guidelines.

**Comment by meninblack111** [comment]
> So you aren't telling it to block explicit information, then you ask it twice to give you explicit information, and it complies the second time. Sounds like you convinced it that you really want the information.
> 
> A model has no judgement or intelligence, it's a text completion engine and it will generate anything you ask it if it doesn't have guidelines.

oh i see, now I know theirs limitations on ollama. Thanks for telling me this.

**Comment by rick-github** [comment]
It's not an ollama limitation, it's the nature of LLMs.

**Comment by meninblack111** [comment]
> It's not an ollama limitation, it's the nature of LLMs.
got it
