### ISSUE TITLE
Using from Vim gives weird characters

### ISSUE THREAD

**Issue by gwpl** [ollama/ollama#7937]
### What is the issue?

When pipeing text from Vim and wanting result e.g. :

```
Example:
tomato
End.
```

When running in vim to pipe second line to make a joke `:2!ollama run smollm2:135m 'joke about'` 
then it shows weird characters in Vim:

![2024-12-05--01-38-21_Screenshot](https://github.com/user-attachments/assets/38097475-3a69-4463-b6d9-fd78d48eee26)

However if I run from terminal like thisl:

```
echo tomato | ollamasmollm2_135m 'joke about' | vim -
```

Then I see properly clear text in Vim.

### OS

Linux

### Ollama version

ollama version is 0.4.6

**Comment by rick-github** [comment]
vim is capturing stderr which has the spinner output.

Related: https://github.com/ollama/ollama/issues/7820

You can work around this by closing stderr:

`:2!ollama run smollm2:135m 'joke about' 2>&-`

Or creating a shell script:
```sh
#!/bin/bash
ollama run smollm2:135m 'joke about' 2>&-
```

`:2!./smol`
