### ISSUE TITLE
underscore in the Ollama username and caps in model name while Pushing results into following errors

### ISSUE THREAD

**Issue by JayKayNJIT** [ollama/ollama#7944]
![Screenshot 2024-12-04 211957](https://github.com/user-attachments/assets/6cefae7c-5267-4230-9c60-8379adc44685)
![Screenshot 2024-12-05 005450](https://github.com/user-attachments/assets/ab15db1d-fea9-4589-8077-7ccecf4c5f0a)

**Comment by JayKayNJIT** [comment]
Error: you are not authorized to push to this namespace, create the model under a namespace you own

Error: file does not exist

**Comment by mchiang0610** [comment]
@JayKayNJIT so sorry about this. We are looking into a fix.

**Comment by bmizerany** [comment]
@JayKayNJIT https://ollama.com/Blake_Mizerany/smol :)

**Comment by bmizerany** [comment]
Also: https://ollama.com/Blake_Mizerany/smol_SMOL :)

**Comment by bmizerany** [comment]
Hopefully these changes make it into the next release. In the meantime, if you're feeling adventurous and do not mind building from `main` and helping us test, that would be much appreciated! NOTE: You'll need to run `ollama serve` with the hand-built binary.

**Comment by JayKayNJIT** [comment]
> Hopefully these changes make it into the next release. In the meantime, if you're feeling adventurous and do not mind building from `main` and helping us test, that would be much appreciated! NOTE: You'll need to run `ollama serve` with the hand-built binary.

Sure, and thanks for the merge.
