### ISSUE TITLE
this model is not supported by your version of Ollama. You may need to upgrade

### ISSUE THREAD

**Issue by s313627345** [ollama/ollama#7946]
### What is the issue?

ollama load  gguf  error is "this model is not supported by your version of Ollama. You may need to upgrade"  who can help me?

### OS

Windows

### GPU

AMD

### CPU

Intel

### Ollama version

0.4.7

**Comment by s313627345** [comment]
![image](https://github.com/user-attachments/assets/88d32134-7cac-4555-8c08-05c832b34ebb)

**Comment by rick-github** [comment]
Where did you get the model from?

**Comment by pdevine** [comment]
`qwen2-vl` isn't supported just quite yet. I'll go ahead and close the issue since there's already #6564
