### ISSUE TITLE
Not using GPU

### ISSUE THREAD

**Issue by frenzybiscuit** [ollama/ollama#7947]
### What is the issue?

I have the following setup:

7950x3d (AMD iGPU)
3090 + 2080ti

When using Ollama with open-webui the GPU (3090) gets used BRIEFLY. It starts using the GPU, GPU ramps up to 90% utilization and then it just stops and falls back to the CPU.

I have installed Ollama and built from source on Fedora 41. I have installed the cuda toolkit manually. I call the following environmental variables from bashrc:

```
export PATH=/usr/local/cuda/bin:$PATH
export LD_LIBRARY_PATH=/usr/local/cuda/lib64:$LD_LIBRARY_PATH
```

I can build llamacpp from source and it works with CUDA.

I am launching Ollama with the following:

`CUDA_VISIBLE_DEVICES=0 ROCR_VISIBLE_DEVICES=55 OLLAMA_HOST=127.0.0.1 OLLAMA_FLASH_ATTENTION=1 OLLAMA_KV_CACHE_TYPE=q8_0 ollama-0.4.8-rc0/./ollama serve`

CUDA_VISIBLE_DEVICES=0 should force it to just use the 3090. I am using ROCR_VISIBLE_DEVICES=55 (fake number) so it doesn't use the AMD iGPU and fall back to CPU.

Any idea why this setup isn't working?

Ollama keeps briefly showing up on nvidia-smi and then vanishing.

It does show the following error:

`"WARN source=sched.go:646 GPU VRAM usage didn't recover within timeout.`

### OS

Linux

### GPU

Other

### CPU

AMD

### Ollama version

0.4.8-rc0

**Comment by rick-github** [comment]
Add server logs.

**Comment by rick-github** [comment]
```
time=2024-12-05T01:17:11.613-08:00 level=INFO source=common.go:49 msg="Dynamic LLM libraries" runners="[cpu cpu_avx cpu_avx2]"
```
The version you've built doesn't have any runners that use the GPU, only CPU runners.

**Comment by rick-github** [comment]
Which build guide?  Fedora 41 appears to be [not supported yet](https://github.com/ollama/ollama/issues/7869) so building from source may not work yet.  If you have docker installed, you could try the docker image.

**Comment by rick-github** [comment]
Most releases that aren't bleeding edge should work.  Fedora 41 was released October 29, 2024 so it will take a little work to make sure all the right dependencies are met, etc.  Distros that want to build from source or otherwise have custom packages (eg Arch) may also have issues with the latest release of ollama.  I've had no issues with installing ollama on Fedora 38, Ubuntu, Mint, Debian, Centos, and openSUSE.  My preferred method these days is to use docker as it makes switching between versions easy.

**Comment by dhiltgen** [comment]
@frenzybiscuit PR #7499 may help make it a bit easier to build from source in your scenario.
