### ISSUE TITLE
panic: failed to decode batch: could not find a kv cache slot  goroutine 22 [running]: main.(*Server).run(0xc0000c2120, {0x556536b63ba0, 0xc00008a0a0}) 	github.com/ollama/ollama/llama/runner/runner.go:344 +0x23e created by main.main in goroutine 1 	github.com/ollama/ollama/llama/runner/runner.go:978 +0xcc7

### ISSUE THREAD

**Issue by watch-Ultra** [ollama/ollama#7949]

**Comment by aliuspetraska** [comment]
we do see the same with last 3 versions of Ollama:

```
Nov 27 14:55:15 ollama[40647]: [GIN] 2024/11/27 - 14:55:15 | 200 | 2.621066104s | 127.0.0.1 | POST "/api/generate"
Nov 27 14:55:16 ollama[40647]: [GIN] 2024/11/27 - 14:55:16 | 200 | 4.383705565s | 127.0.0.1 | POST "/api/generate"
Nov 27 14:55:18 ollama[40647]: [GIN] 2024/11/27 - 14:55:18 | 200 | 3.540287173s | 127.0.0.1 | POST "/api/generate"
Nov 27 14:55:21 ollama[40647]: [GIN] 2024/11/27 - 14:55:21 | 200 | 5.519881786s | 127.0.0.1 | POST "/api/generate"
Nov 27 14:55:23 ollama[40647]: [GIN] 2024/11/27 - 14:55:23 | 200 | 6.420199899s | 127.0.0.1 | POST "/api/generate"
Nov 27 14:55:24 ollama[40647]: [GIN] 2024/11/27 - 14:55:24 | 200 | 5.876235203s | 127.0.0.1 | POST "/api/generate"
Nov 27 14:55:28 ollama[40647]: [GIN] 2024/11/27 - 14:55:28 | 200 | 6.817514029s | 127.0.0.1 | POST "/api/generate"
Nov 27 14:55:29 ollama[40647]: [GIN] 2024/11/27 - 14:55:29 | 200 | 6.614235832s | 127.0.0.1 | POST "/api/generate"
Nov 27 14:55:34 ollama[40647]: [GIN] 2024/11/27 - 14:55:34 | 200 | 10.341194001s | 127.0.0.1 | POST "/api/generate"
Nov 27 14:55:39 ollama[40647]: [GIN] 2024/11/27 - 14:55:39 | 200 | 11.685299016s | 127.0.0.1 | POST "/api/generate"
Nov 27 14:55:40 ollama[40647]: panic: failed to decode batch: could not find a kv cache slot
Nov 27 14:55:40 ollama[40647]: goroutine 7 [running]:
Nov 27 14:55:40 ollama[40647]: main.(*Server).run(0xc0000c2120, {0x55c4bfd27d60, 0xc0000980a0})
Nov 27 14:55:40 ollama[40647]: github.com/ollama/ollama/llama/runner/runner.go:336 +0x23e
Nov 27 14:55:40 ollama[40647]: created by main.main in goroutine 1
Nov 27 14:55:40 ollama[40647]: github.com/ollama/ollama/llama/runner/runner.go:955 +0xc52
```

**Comment by jessegross** [comment]
@aliuspetraska It sounds like this is reproducible for you. Can you give the steps to trigger it?

**Comment by StefanDimitrov95** [comment]
For me this happens after running series of requests. With larger models this issue occurs earlier. 
Ollama 0.5.1, QWEN 2.5 Coder models and llama 3.1.

```
Dec 09 11:47:29 ollama[5600]: [GIN] 2024/12/09 - 11:47:29 | 200 | 44.198688317s |   127.0.0.1 | POST     "/v1/chat/completions"
Dec 09 11:47:30 ollama[5600]: panic: failed to decode batch: could not find a kv cache slot
Dec 09 11:47:30 ollama[5600]: goroutine 22 [running]:
Dec 09 11:47:30 ollama[5600]: main.(*Server).run(0xc0000cc120, {0x563bb381a9a0, 0xc0000960a0})
Dec 09 11:47:30 ollama[5600]:         github.com/ollama/ollama/llama/runner/runner.go:344 +0x23e
Dec 09 11:47:30 ollama[5600]: created by main.main in goroutine 1
Dec 09 11:47:30 ollama[5600]:         github.com/ollama/ollama/llama/runner/runner.go:980 +0xd3e
Dec 09 11:47:30 ollama[5600]: [GIN] 2024/12/09 - 11:47:30 | 500 | 44.931164011s |   127.0.0.1 | POST     "/v1/chat/completions"
```

**Comment by jessegross** [comment]
Can you set the environment variable OLLAMA_DEBUG=1 and then report the full log after the issue occurs?

**Comment by thibautrey** [comment]
I've got the exact same issue using llama3.3:70b: 

`time=2024-12-12T16:07:49.376Z level=WARN source=runner.go:129 msg="truncating input prompt" limit=2048 prompt=3819 keep=5 new=2048
time=2024-12-12T16:07:49.521Z level=DEBUG source=cache.go:104 msg="loading cache slot" id=0 cache=1212 prompt=2048 used=5 remaining=2043
time=2024-12-12T16:07:53.293Z level=DEBUG source=runner.go:437 msg="defragmenting kv cache"
panic: failed to decode batch: could not find a kv cache slot

goroutine 7 [running]:
main.(*Server).run(0xc0000ec120, {0x55b0d4a059a0, 0xc0000be0a0})
        github.com/ollama/ollama/llama/runner/runner.go:344 +0x23e
created by main.main in goroutine 1
        github.com/ollama/ollama/llama/runner/runner.go:980 +0xd3e
time=2024-12-12T16:07:53.403Z level=DEBUG source=sched.go:407 msg="context for request finished"
time=2024-12-12T16:07:53.403Z level=DEBUG source=sched.go:357 msg="after processing request finished event" modelPath=/root/.ollama/models/blobs/sha256-4824460d29f2058aaf6e1118a63a7a197a09bed509f0e7d4e2efb1ee273b447d refCount=2
[GIN] 2024/12/12 - 16:07:53 | 500 |  4.090769271s |      172.17.0.1 | POST     "/api/chat"
time=2024-12-12T16:07:53.470Z level=DEBUG source=server.go:1099 msg="stopping llama server"
time=2024-12-12T16:07:53.470Z level=DEBUG source=server.go:1105 msg="waiting for llama server to exit"
time=2024-12-12T16:07:53.470Z level=DEBUG source=server.go:1099 msg="stopping llama server"
time=2024-12-12T16:07:53.470Z level=DEBUG source=server.go:1105 msg="waiting for llama server to exit"
time=2024-12-12T16:07:53.487Z level=DEBUG source=server.go:1109 msg="llama server stopped"`

**Comment by jessegross** [comment]
Can you please post the full log?

**Comment by jersam** [comment]
@MishaAnikutin Any idea why? I am having the same issue and all is working on 3.14

I am using Paperless GPT
