### ISSUE TITLE
Model request: HunyuanVideo text-to-video

### ISSUE THREAD

**Issue by artem-zinnatullin** [ollama/ollama#7958]
It's an "open-source" rich text-to-video model by Tencent:

>HunyuanVideo represents the most parameter-rich and high-performce text-to-video model currently available in the open-source domain. With 13 billion parameters, it is capable of generating videos that exhibit high physical accuracy and scene consistency, thereby actualizing conceptual visions and fostering creative expression.

Links:

- Model website: https://aivideo.hunyuan.tencent.com/
- GitHub: https://github.com/Tencent/HunyuanVideo
- HuggingFace: https://huggingface.co/tencent/HunyuanVideo
- Paper: https://github.com/Tencent/HunyuanVideo/blob/main/assets/hunyuanvideo.pdf

Abstract:

>We present HunyuanVideo, a novel open-source video foundation model that exhibits performance in video generation that is comparable to, if not superior to, leading closed-source models. HunyuanVideo features a comprehensive framework that integrates several key contributions, including data curation, image-video joint model training, and an efficient infrastructure designed to facilitate large-scale model training and inference. Additionally, through an effective strategy for scaling model architecture and dataset, we successfully trained a video generative model with over 13 billion parameters, making it the largest among all open-source models.
>
>We conducted extensive experiments and implemented a series of targeted designs to ensure high visual quality, motion diversity, text-video alignment, and generation stability. According to professional human evaluation results, HunyuanVideo outperforms previous state-of-the-art models, including Runway Gen-3, Luma 1.6, and 3 top performing Chinese video generative models. By releasing the code and weights of the foundation model and its applications, we aim to bridge the gap between closed-source and open-source video foundation models. This initiative will empower everyone in the community to experiment with their ideas, fostering a more dynamic and vibrant video generation ecosystem. 

This is a tracking issue for HunyuanVideo model support ⌛

**Comment by rick-github** [comment]
This type of model is not supported in ollama, and probably not any time soon.  It's more appropriate for a project like [ComyUI](https://github.com/comfyanonymous/ComfyUI/issues/3751).
