### ISSUE TITLE
Structured Output is not OpenAI compliant

### ISSUE THREAD

**Issue by iscy** [ollama/ollama#7978]
## Description
When passing a JSON schema to the OpenAI compat endpoint, the order of the properties won't be retained. By being re-ordered, it creates a different output than expected from the model.

## Steps to Reproduce
curl command to reproduce the issue:
``` bash
curl http://[...]/v1/chat/completions \
  -H "Content-Type: application/json" \
  -d '{
    "model": "llama3.1:8b",
    "messages": [
      {
        "role": "system",
        "content": "You are a helpful math tutor. Guide the user through the solution step by step. Respond using JSON."
      },
      {
        "role": "user",
        "content": "how can I solve 8x + 7 = -23"
      }
    ],
    "temperature": 0,
    "response_format": {
      "type": "json_schema",
      "json_schema": {
        "name": "math_reasoning",
        "schema": {
          "type": "object",
          "properties": {
            "steps": {
              "type": "array",
              "items": {
                "type": "object",
                "properties": {
                  "explanation": { "type": "string" },
                  "output": { "type": "string" }
                },
                "required": ["explanation", "output"],
                "additionalProperties": false
              }
            },
            "final_answer": { "type": "string" }
          },
          "required": ["steps", "final_answer"],
          "additionalProperties": false
        },
        "strict": true
      }
    }
  }'

```

## Actual Outcome
`[...] {"index":0,"message":{"role":"assistant","content":"{\n\"final_answer\": \"Not provided yet\", [...]`

## Desired Outcome
`[...] ,\"final_answer\":\"x = -3.75\"} [...]`

## Explanation
Since the properties are re-ordered, "final_answer" comes in before the steps. This makes the model generate a final answer that says "Not provided yet" or other similar output since none of the steps were executed yet. Ensuring that the order stays as-is is required to have an OpenAI compliant API.

Documentation: https://platform.openai.com/docs/guides/structured-outputs#key-ordering

### OS

Linux

### GPU

Nvidia

### CPU

AMD

### Ollama version

0.5.0

**Comment by ParthSareen** [comment]
Thanks for the flag will look into this! @iscy

**Comment by sixlive** [comment]
Yup, I noticed this as well.

**Comment by iscy** [comment]
This is reaolved on the main branch.
