### ISSUE TITLE
better diagnosis / error messages when ctx is too small

### ISSUE THREAD

**Issue by fce2** [ollama/ollama#7987]
It would be great to have some errors or warnings.
I ran into a problem where i had too many tools registered.
Suddenly the "get-time" function was not called anymore.
I assume I ran out of context (I deleted some tools then it worked again).

So my feature request would be a warning when the context of a llm is not big enough.

**Comment by rick-github** [comment]
Logs will contain `msg="truncating input prompt"`.  `prompt_eval_count` in the response will be equal to the size of the context buffer and smaller than the input.

Related: https://github.com/ollama/ollama/issues/7043, https://github.com/ollama/ollama/issues/1005, https://github.com/ollama/ollama/issues/4967

**Comment by fce2** [comment]
thanks !
