### ISSUE TITLE
GPU no being used.

### ISSUE THREAD

**Issue by tom4oc** [ollama/ollama#7989]
### What is the issue?

I got my VM (on my TrueNAS machine) up and running then installed Whisper and OLLAMA. I installed OLLAMA 3.2 via the CURL command.  I can see that Whisper is access the GPU when running, but Ollama isn't. I'm stuck. If I type a simple prompt like: this is a test, a response can take anywhere from 3-10 minutes to type out 15 words. 
I have a NVIDIA 4070 in the TrueNas, like I said passthrough is working for whisper. 

Thank you for any suggestions

Tommy 

TrueNas Scale 
AMD EPYC 7286
256GB RAM
NVIDA 4070

### OS

Linux

### GPU

Nvidia

### CPU

AMD

### Ollama version

3.2

**Comment by rick-github** [comment]
[Server logs](https://github.com/ollama/ollama/blob/main/docs/troubleshooting.md#how-to-troubleshoot-issues) will aid in debugging.

**Comment by tom4oc** [comment]
Sorry for the long post I am new to linux and command line interactions. I hope this is what you were referring to.

Dec 07 17:05:53 worldoftext systemd[1]: Started ollama.service - Ollama Service.
Dec 07 17:05:53 worldoftext ollama[9805]: Couldn't find '/usr/share/ollama/.ollama/id_ed25519'. Generating new private key.
Dec 07 17:05:53 worldoftext ollama[9805]: Your new public key is:
Dec 07 17:05:53 worldoftext ollama[9805]: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIMtM3DzXexXVBdTV+ejZkiz+sMHZeLSbihxwLBbDloE7
Dec 07 17:05:53 worldoftext ollama[9805]: 2024/12/07 17:05:53 routes.go:1195: INFO server config env="map[CUDA_VISIBLE_DEVICES: GPU_DEVICE_ORDINAL: HIP_VISIBLE_DEVICES: H>
Dec 07 17:05:53 worldoftext ollama[9805]: time=2024-12-07T17:05:53.277Z level=INFO source=images.go:753 msg="total blobs: 0"
Dec 07 17:05:53 worldoftext ollama[9805]: time=2024-12-07T17:05:53.277Z level=INFO source=images.go:760 msg="total unused blobs removed: 0"
Dec 07 17:05:53 worldoftext ollama[9805]: time=2024-12-07T17:05:53.277Z level=INFO source=routes.go:1246 msg="Listening on 127.0.0.1:11434 (version 0.5.1)"
Dec 07 17:05:53 worldoftext ollama[9805]: time=2024-12-07T17:05:53.277Z level=INFO source=common.go:135 msg="extracting embedded files" dir=/tmp/ollama1400444222/runners
Dec 07 17:05:53 worldoftext ollama[9805]: time=2024-12-07T17:05:53.439Z level=INFO source=common.go:49 msg="Dynamic LLM libraries" runners="[rocm cpu cpu_avx cpu_avx2 cud>
Dec 07 17:05:53 worldoftext ollama[9805]: time=2024-12-07T17:05:53.439Z level=INFO source=gpu.go:221 msg="looking for compatible GPUs"
Dec 07 17:05:53 worldoftext ollama[9805]: time=2024-12-07T17:05:53.440Z level=WARN source=gpu.go:252 msg="CPU does not have minimum vector extensions, GPU inference disab>
Dec 07 17:05:53 worldoftext ollama[9805]: time=2024-12-07T17:05:53.440Z level=INFO source=types.go:123 msg="inference compute" id=0 library=cpu variant="no vector extensi>
Dec 07 17:45:10 worldoftext systemd[1]: ollama.service: Deactivated successfully.
Dec 07 17:45:13 worldoftext systemd[1]: ollama.service: Scheduled restart job, restart counter is at 1.
Dec 07 17:45:13 worldoftext systemd[1]: Started ollama.service - Ollama Service.
Dec 07 17:45:13 worldoftext ollama[11726]: 2024/12/07 17:45:13 routes.go:1195: INFO server config env="map[CUDA_VISIBLE_DEVICES: GPU_DEVICE_ORDINAL: HIP_VISIBLE_DEVICES: >
Dec 07 17:45:13 worldoftext ollama[11726]: time=2024-12-07T17:45:13.222Z level=INFO source=images.go:753 msg="total blobs: 0"
Dec 07 17:45:13 worldoftext ollama[11726]: time=2024-12-07T17:45:13.222Z level=INFO source=images.go:760 msg="total unused blobs removed: 0"
Dec 07 17:45:13 worldoftext ollama[11726]: time=2024-12-07T17:45:13.223Z level=INFO source=routes.go:1246 msg="Listening on 127.0.0.1:11434 (version 0.5.1)"
Dec 07 17:45:13 worldoftext ollama[11726]: time=2024-12-07T17:45:13.223Z level=INFO source=common.go:135 msg="extracting embedded files" dir=/tmp/ollama633876399/runners
Dec 07 17:45:13 worldoftext ollama[11726]: time=2024-12-07T17:45:13.399Z level=INFO source=common.go:49 msg="Dynamic LLM libraries" runners="[cpu cpu_avx cpu_avx2 cuda_v1>
Dec 07 17:45:13 worldoftext ollama[11726]: time=2024-12-07T17:45:13.399Z level=INFO source=gpu.go:221 msg="looking for compatible GPUs"
Dec 07 17:45:13 worldoftext ollama[11726]: time=2024-12-07T17:45:13.399Z level=WARN source=gpu.go:252 msg="CPU does not have minimum vector extensions, GPU inference disa>
Dec 07 17:45:13 worldoftext ollama[11726]: time=2024-12-07T17:45:13.399Z level=INFO source=types.go:123 msg="inference compute" id=0 library=cpu variant="no vector extens>
Dec 07 17:45:44 worldoftext systemd[1]: ollama.service: Deactivated successfully.
Dec 07 17:45:47 worldoftext systemd[1]: ollama.service: Scheduled restart job, restart counter is at 2.
Dec 07 17:45:47 worldoftext systemd[1]: Started ollama.service - Ollama Service.
Dec 07 17:45:47 worldoftext ollama[11747]: 2024/12/07 17:45:47 routes.go:1195: INFO server config env="map[CUDA_VISIBLE_DEVICES: GPU_DEVICE_ORDINAL: HIP_VISIBLE_DEVICES: >
Dec 07 17:45:47 worldoftext ollama[11747]: time=2024-12-07T17:45:47.223Z level=INFO source=images.go:753 msg="total blobs: 0"
Dec 07 17:45:47 worldoftext ollama[11747]: time=2024-12-07T17:45:47.223Z level=INFO source=images.go:760 msg="total unused blobs removed: 0"
Dec 07 17:45:47 worldoftext ollama[11747]: time=2024-12-07T17:45:47.224Z level=INFO source=routes.go:1246 msg="Listening on 127.0.0.1:11434 (version 0.5.1)"
Dec 07 17:45:47 worldoftext ollama[11747]: time=2024-12-07T17:45:47.224Z level=INFO source=common.go:135 msg="extracting embedded files" dir=/tmp/ollama2301402745/runners
Dec 07 17:45:47 worldoftext ollama[11747]: time=2024-12-07T17:45:47.393Z level=INFO source=common.go:49 msg="Dynamic LLM libraries" runners="[cpu cpu_avx cpu_avx2 cuda_v1>
Dec 07 17:45:47 worldoftext ollama[11747]: time=2024-12-07T17:45:47.393Z level=INFO source=gpu.go:221 msg="looking for compatible GPUs"
Dec 07 17:45:47 worldoftext ollama[11747]: time=2024-12-07T17:45:47.394Z level=WARN source=gpu.go:252 msg="CPU does not have minimum vector extensions, GPU inference disa>
Dec 07 17:45:47 worldoftext ollama[11747]: time=2024-12-07T17:45:47.394Z level=INFO source=types.go:123 msg="inference compute" id=0 library=cpu variant="no vector extens>
Dec 07 17:46:17 worldoftext systemd[1]: ollama.service: Deactivated successfully.
Dec 07 17:46:20 worldoftext systemd[1]: ollama.service: Scheduled restart job, restart counter is at 3.
Dec 07 17:46:20 worldoftext systemd[1]: Started ollama.service - Ollama Service.
Dec 07 17:46:20 worldoftext ollama[11767]: 2024/12/07 17:46:20 routes.go:1195: INFO server config env="map[CUDA_VISIBLE_DEVICES: GPU_DEVICE_ORDINAL: HIP_VISIBLE_DEVICES: >
Dec 07 17:46:20 worldoftext ollama[11767]: time=2024-12-07T17:46:20.723Z level=INFO source=images.go:753 msg="total blobs: 0"
Dec 07 17:46:20 worldoftext ollama[11767]: time=2024-12-07T17:46:20.723Z level=INFO source=images.go:760 msg="total unused blobs removed: 0"
Dec 07 17:46:20 worldoftext ollama[11767]: time=2024-12-07T17:46:20.723Z level=INFO source=routes.go:1246 msg="Listening on 127.0.0.1:11434 (version 0.5.1)"
Dec 07 17:46:20 worldoftext ollama[11767]: time=2024-12-07T17:46:20.724Z level=INFO source=common.go:135 msg="extracting embedded files" dir=/tmp/ollama2921199285/runners
Dec 07 17:46:20 worldoftext ollama[11767]: time=2024-12-07T17:46:20.904Z level=INFO source=common.go:49 msg="Dynamic LLM libraries" runners="[cuda_v12 rocm cpu cpu_avx cp>
Dec 07 17:46:20 worldoftext ollama[11767]: time=2024-12-07T17:46:20.904Z level=INFO source=gpu.go:221 msg="looking for compatible GPUs"
Dec 07 17:46:20 worldoftext ollama[11767]: time=2024-12-07T17:46:20.905Z level=WARN source=gpu.go:252 msg="CPU does not have minimum vector extensions, GPU inference disa>
Dec 07 17:46:20 worldoftext ollama[11767]: time=2024-12-07T17:46:20.905Z level=INFO source=types.go:123 msg="inference compute" id=0 library=cpu variant="no vector extens>
Dec 07 17:47:17 worldoftext systemd[1]: Stopping ollama.service - Ollama Service...
Dec 07 17:47:17 worldoftext systemd[1]: ollama.service: Deactivated successfully.
Dec 07 17:47:17 worldoftext systemd[1]: Stopped ollama.service - Ollama Service.

Here is what I got when I ran --verbose

(whisper-env) tommy@worldoftext:~$ CUDA_VISIBLE_DEVICES=0 ollama run llama3.1
>>> this is a test
This appears to be a valid test message. How can I assist you further?

>>> /bye
(whisper-env) tommy@worldoftext:~$ CUDA_VISIBLE_DEVICES=0 ollama run --verbose llama3.1
>>> test 
It looks like you're just testing the conversation. Is there something specific I can help with or would you like to start a conversation on a particular topic? I'm 
here to assist and provide information!

total duration:       2m35.933805794s
load duration:        43.97544ms
prompt eval count:    11 token(s)
prompt eval duration: 18.585s
prompt eval rate:     0.59 tokens/s
eval count:           41 token(s)
eval duration:        2m17.302s
eval rate:            0.30 tokens/s
>>> Send a message (/? for help)

**Comment by rick-github** [comment]
```
msg="CPU does not have minimum vector extensions, GPU inference disa
```
ollama wants a CPU with vector extension in order to use the GPU.  If you build your own version you can work around this requirement, see [here](https://github.com/ollama/ollama/issues/7622#issuecomment-2524637378).

**Comment by tom4oc** [comment]
Thank you, 

I went back into my VM settings and realized I didn't have CPU passthrough enabled.
