### ISSUE TITLE
Not working properly after upgrading to the latest macOS version.

### ISSUE THREAD

**Issue by liujuncn** [ollama/ollama#7995]
### What is the issue?

Ollama can not work properly after upgrading to 0.5.1 on Mac.  In the previous version, all downloaded models could perform inference normally. However, the new version seems unable to utilize macOS unified memory and has a memory leak issue, with memory usage continuously increasing.

Hardware: Apple M4 Mac mini

### OS

macOS

### GPU

Apple

### CPU

Apple

### Ollama version

0.5.1

**Comment by yyakauleu** [comment]
Similar issue. Functions tools stopped working with 0.5.1 version as well.
