### ISSUE TITLE
Allow for forcing an order of properties in structured JSON response

### ISSUE THREAD

**Issue by scd31** [ollama/ollama#8003]
When having an LLM respond with JSON I often do something along the lines of `{reasoning: "...", actual_property_i_care_about: "..."}`. The idea is that the `reasoning` property isn't used on my end but gives the LLM the ability to think first, like with CoT. Of course, this requires the LLM to populate the `reasoning` term before the other terms.

With the new structured JSON response it would be nice if there were a way to enforce this. Even telling the LLM to put the elements in a specific order is ignored.

**Comment by scd31** [comment]
I did some digging and it looks like this will require a change to llama.cpp as well as Ollama (alternatively, we could just move the `json_schema_to_grammar.cpp` over to Ollama and modify it there, but it would be nice to backport the improvement)

As a side note it seems like the fields are ordered alphabetically, which is a workaround at least

**Comment by rick-github** [comment]
#7978

**Comment by scd31** [comment]
Thanks (:
