### ISSUE TITLE
ollama0.5.1, run llama3.3:70b-instruct-q8_0 failed.  client connection closed before server finished loading, aborting load 

### ISSUE THREAD

**Issue by javaice007** [ollama/ollama#8006]
### What is the issue?

ggml_cuda_init: found 4 CUDA devices:
  Device 0: NVIDIA GeForce RTX 4090, compute capability 8.9, VMM: yes
  Device 1: NVIDIA GeForce RTX 4090, compute capability 8.9, VMM: yes
  Device 2: NVIDIA GeForce RTX 4090, compute capability 8.9, VMM: yes
  Device 3: NVIDIA GeForce RTX 4090, compute capability 8.9, VMM: yes
llm_load_tensors: ggml ctx size =    1.69 MiB
time=2024-12-09T03:41:20.513Z level=WARN source=server.go:583 msg="client connection closed before server finished loading, aborting load"
time=2024-12-09T03:41:20.513Z level=ERROR source=sched.go:455 msg="error loading llama server" error="timed out waiting for llama runner to start: context canceled"
[GIN] 2024/12/09 - 03:41:20 | 499 |         1m30s |      10.1.1.116 | POST     "/v1/chat/completions"
time=2024-12-09T03:41:25.878Z level=WARN source=sched.go:646 msg="gpu VRAM usage didn't recover within timeout" seconds=5.364338764 model=/data/models/blobs/sha256-4a8a92e57c0f847acc18d361504c13020c7578c34e3444c4c04f70fb601fb058
time=2024-12-09T03:41:26.518Z level=WARN source=sched.go:646 msg="gpu VRAM usage didn't recover within timeout" seconds=6.004755322 model=/data/models/blobs/sha256-4a8a92e57c0f847acc18d361504c13020c7578c34e3444c4c04f70fb601fb058
time=2024-12-09T03:41:27.158Z level=WARN source=sched.go:646 msg="gpu VRAM usage didn't recover within timeout" seconds=6.644676283 model=/data/models/blobs/sha256-4a8a92e57c0f847acc18d361504c13020c7578c34e3444c4c04f70fb601fb058

### OS

Linux, Docker

### GPU

Nvidia

### CPU

Intel

### Ollama version

0.5.1

**Comment by rick-github** [comment]
Increase [`OLLAMA_LOAD_TIMEOUT`](https://github.com/ollama/ollama/blob/da09488fbfc437c55a94bc5374b0850d935ea09f/envconfig/config.go#L244).

**Comment by dhiltgen** [comment]
I think the problem is the client is giving up too quickly `client connection closed before server finished loading, aborting load`

Not enough logs were provided to understand how long it was from the start of load to the point where the client gave up and closed the connection, which triggers ollama to abort the load.
