### ISSUE TITLE
EXAONE-3.5 2.4B, 7.8B, and 32B

### ISSUE THREAD

**Issue by vYLQs6** [ollama/ollama#8007]
https://huggingface.co/collections/LGAI-EXAONE/exaone-35-674d0e1bb3dcd2ab6f39dbb4

---

Note: 

I enabled Q8 KV Cache, and when I tried the gguf uploaded by LG, I always get this error: `Error: llama runner process has terminated: GGML_ASSERT(hparams.n_embd_head_k % ggml_blck_size(type_k) == 0) failed`

Idk if this means this model just doesn't support kv cache or ollama needs an update.

Everything works fine after I disabled kv cache & flash attention

---

<table>
    <tr>
        <th>Models</th>
        <th>MT-Bench</th>
        <th>LiveBench</th>
        <th>Arena-Hard</th>
        <th>AlpacaEval</th>
        <th>IFEval</th>
        <th>KoMT-Bench[1]</th>
        <th>LogicKor</th>
    </tr>
    <tr>
        <td>EXAONE 3.5 32B</td>
        <td align="center"><strong>8.51</strong></td>
        <td align="center">43.0</td>
        <td align="center"><strong>78.6</strong></td>
        <td align="center"><strong>60.6</strong></td>
        <td align="center"><strong>81.7</strong></td>
        <td align="center"><strong>8.05</strong></td>
        <td align="center"><strong>9.06</strong></td>
    </tr>
    <tr>
        <td>Qwen 2.5 32B</td>
        <td align="center">8.49</td>
        <td align="center"><strong>50.6</strong></td>
        <td align="center">67.0</td>
        <td align="center">41.0</td>
        <td align="center">78.7</td>
        <td align="center">7.75</td>
        <td align="center">8.89</td>
    </tr>
    <tr>
        <td>C4AI Command R 32B</td>
        <td align="center">7.38</td>
        <td align="center">29.7</td>
        <td align="center">17.0</td>
        <td align="center">25.9</td>
        <td align="center">26.1</td>
        <td align="center">6.72</td>
        <td align="center">8.24</td>
    </tr>
    <tr>
        <td>Gemma 2 27B</td>
        <td align="center">8.28</td>
        <td align="center">40.0</td>
        <td align="center">57.5</td>
        <td align="center">52.2</td>
        <td align="center">59.7</td>
        <td align="center">7.19</td>
        <td align="center">8.56</td>
    </tr>
    <tr>
        <td>Yi 1.5 34B</td>
        <td align="center">7.64</td>
        <td align="center">26.2</td>
        <td align="center">23.1</td>
        <td align="center">34.8</td>
        <td align="center">55.5</td>
        <td align="center">4.88</td>
        <td align="center">6.33</td>
    </tr>
</table>

**Comment by nonetrix** [comment]
Dup of https://github.com/ollama/ollama/issues/6269

**Comment by rick-github** [comment]
https://ollama.com/library/exaone3.5

**Comment by jmorganca** [comment]
https://ollama.com/library/exaone3.5 (thanks @rick-github !)
