### ISSUE TITLE
make is somehow visible that the context size in models is not used by default

### ISSUE THREAD

**Issue by fce2** [ollama/ollama#8009]
This is extremely important, it drove me kind of crazy ("it woked before, what did i do wrong now" ??):
!!! You cant use the native models context size until you activate it manually !!!

manual procedure:
ollama run llama3.2:3b-instruct-q8_0
> /set parameter num_ctx 65536
> /save llama3.2:3b-instruct-q8_0-65536
> /bye

Thanks for this hint, microsuxxor !!

Its also important to know: the model size increases extremely, a llama3.2-3b model cant run on a 4090 anymore:
  llama3.2:3b-instruct-q8_0               5.4GB   150tps
  llama3.2:3b-instruct-q8_0-4096      6.8GB   146tps
  llama3.2:3b-instruct-q8_0-8192      9.6GB   146tps
  llama3.2:3b-instruct-q8_0-16384  15.0GB   146tps
  llama3.2:3b-instruct-q8_0-32768    9.6GB   150tps
  llama3.2:3b-instruct-q8_0-65536  15.0GB   150tps
  llama3.2:3b-instruct-q8_0-131072 26.0GB    30tps

**Comment by rick-github** [comment]
https://github.com/ollama/ollama/blob/main/docs/faq.md#how-can-i-specify-the-context-window-size
