### ISSUE TITLE
Underflow error when using GPU memory overhead

### ISSUE THREAD

**Issue by ProjectMoon** [ollama/ollama#8011]
### What is the issue?

GPUs:
- AMD RX 6800 XT (16 GB VRAM)
- NVidia GTX 970 (4 GB VRAM)

I have discovered a very odd and very dangerous problem in ollama. I am running OpenWebUI on a machine that has a ROCm device (main GPU; 16 GB VRAM) and a CUDA device (ancient old NVidia GPU). The NVidia GPU has 4 GB of VRAM and I use it as a secondary GPU for small models like embedding, etc.

I'm using the CUDA variant of the OpenWebUI docker image, which it allows to run vector search re-ranking models on CUDA. This loads the reranking model (BGE reranker in my case) onto the Nvidia GPU.

All of this is fine and dandy. But the problem comes when ollama tries to run the actual main LLM I'm using (Qwen2.5 14b q5_K_M in this case).

For some reason, it seems to completely skip choosing the ROCm GPU as the GPU to load the model on, and tries to load it on the CUDA device, which promptly fails. It doesn't even fall back to CPU. This persists through restarts of ollama. No matter what, it will not consider the AMD GPU or CPU for loading any LLM, and essentially renders OpenWebUI non-functional.

I've narrowed it down to OpenWebUI loading the reranker model on the CUDA device. If OpenWebUI is shut down, everything starts working fine again in ollama. Everything also works fine in OpenWebUI until it loads the reranker model.
- But presumably this isn't specifically _because_ of OpenWebUI. I imagine it would happen with anything external to ollama that takes over the CUDA device.

I can provide debug logs if necessary.

### OS

Linux, Docker

### GPU

Nvidia, AMD

### CPU

AMD

### Ollama version

0.5.1,0.4.7

**Comment by rick-github** [comment]
Logs are necessary.

**Comment by ProjectMoon** [comment]
[ollama-debug-log.txt](https://github.com/user-attachments/files/18060536/ollama-debug-log.txt)

Logs are attached. At first you can see it running the BGE embedding model on the NVidia GPU, and Qwen2.5 (Acree Supernova, to be more specific) on the AMD GPU. But then it starts trying to load Qwen2.5 on the CUDA device repeatedly.

**Comment by ProjectMoon** [comment]
Few more details on this: `rocm-smi` reports that VRAM is emptied after the model stops, so it's not like the main GPU is full. At least not on the hardware itself. Dunno what ollama thinks.

**Comment by ProjectMoon** [comment]
Well, 16k exabytes sounds like it would definitely be enough space to load a language model. :thinking: 

I updated the title of the bug for easier searching. Thanks for figuring it out! For now I've disabled the memory overhead and things work much better (at least until I run into context errors, which is why I had the overhead set in the first place).
