### ISSUE TITLE
Incorrect configuration in EXAONE 3.5

### ISSUE THREAD

**Issue by lgai-exaone** [ollama/ollama#8021]
Hello,
We recently published EXAONE 3.5, and we appreciate your quick support of EXAONE 3.5 in Ollama.
https://ollama.com/library/exaone3.5

However, we found that the applied template differs from the original template.
We checked the prompt template and determined it should be modified as below:
```
{{- range $i, $_ := .Messages }}
{{- $last := eq (len (slice $.Messages $i)) 1 -}}
{{ if eq .Role "system" }}[|system|]{{ .Content }}[|endofturn|]
{{ continue }}
{{ else if eq .Role "user" }}[|user|]{{ .Content }}
{{ else if eq .Role "assistant" }}[|assistant|]{{ .Content }}[|endofturn|]
{{ end }}
{{- if and (ne .Role "assistant") $last }}[|assistant|]{{ end }}
{{- end -}}
```

Could you update the template for EXAONE 3.5 in the ollama library?

Additionally, is there a method to configure generation settings (e.g. stop words, repetition penalty) for the model in the ollama library? we need to set certain parameters to avoid performance degradation.

**Comment by rick-github** [comment]
Parameters can be set with the [`PARAMETER`](https://github.com/ollama/ollama/blob/main/docs/modelfile.md#parameter) command in a Modelfile.  If you add the required changes here they can be incorporated in to the model update.

**Comment by lgai-exaone** [comment]
Thank you for reply!

We updated the Modelfile, same as our [GitHub README](https://github.com/LG-AI-EXAONE/EXAONE-3.5?tab=readme-ov-file#ollama).
Here is our example of full Modelfile:
```
# Model path (choose appropriate GGUF weights on your own)
FROM ./EXAONE-3.5-7.8B-Instruct-BF16.gguf

# Parameter values
PARAMETER stop "[|endofturn|]"
PARAMETER temperature 1.0
PARAMETER repeat_penalty 1.0
# PARAMETER num_ctx 32768  # if you need a long context

# Chat template
TEMPLATE """{{- range $i, $_ := .Messages }}
{{- $last := eq (len (slice $.Messages $i)) 1 -}}
{{ if eq .Role "system" }}[|system|]{{ .Content }}[|endofturn|]
{{ continue }}
{{ else if eq .Role "user" }}[|user|]{{ .Content }}
{{ else if eq .Role "assistant" }}[|assistant|]{{ .Content }}[|endofturn|]
{{ end }}
{{- if and (ne .Role "assistant") $last }}[|assistant|]{{ end }}
{{- end -}}"""

# System prompt
SYSTEM """You are EXAONE model from LG AI Research, a helpful assistant."""

# License
LICENSE """EXAONE AI Model License Agreement 1.1 - NC """
```

**Comment by jmorganca** [comment]
Hi @lgai-exaone congrats on the model launch and thank you for the correction. It should be reflected here now: https://ollama.com/library/exaone3.5

Excited to launch more models with you in the future 😊

**Comment by lgai-exaone** [comment]
Thank you @jmorganca, we checked the update on the Ollama library!

We look forward to continuously contributing to the community and collaborating with Ollama 😄

**Comment by mchiang0610** [comment]
Thank you @lgai-exaone for the help! I would love to connect to see how to help launch future models too. We've been working on features that allow you to upload your own models (privately and publicly) to Ollama.com for sharing. 

my email is michael@ollama.com

**Comment by lgai-exaone** [comment]
Thank you @mchiang0610 for your suggestion! We are looking forward to Ollama support for our upcoming models. 
We're excited to explore collaboration opportunities, so if you know of any suitable ways we could work together, we're eager to hear them!

Please don't mind to send email to our contact: [contact_us@lgresearch.ai](mailto:contact_us@lgresearch.ai)

**Comment by lgai-exaone** [comment]
Hello, everyone.
We have conducted experiments to optimize sampling parameters for EXAONE 3.5 across various platforms, including Ollama.

Our findings indicate that model generation quality degrades when the repetition penalty exceeds 1.0, which was consistent across all tested platforms. 
Additionally, we discovered that EXAONE models perform well with the default temperature setting (0.7) and don't require forcing it to 1.0.

Thus, could you please remove the temperature setting from the EXAONE models' Modelfiles?

Thank you for your attention.
