### ISSUE TITLE
Error reported when importing a multimodal large model of type hugginface (llava-mistral-7b)

### ISSUE THREAD

**Issue by lyp-liu** [ollama/ollama#8022]
### What is the issue?

ollama create mytestsafe -f ./mytest.Modelfile
transferring model data 100%
converting model
Error: unsupported architecture

At present, it seems impossible to convert the huggingface type Llava-mistral convert to a gguf type model through Llama.cpp. 
i want to know that the type of llava-mistral-7b in ollama
![QQ图片20241210140505](https://github.com/user-attachments/assets/fb435aa0-c266-4b59-9391-8d31dfb5bd56)
 

### OS

Windows

### GPU

Nvidia

### Ollama version

0.5.1

**Comment by jmorganca** [comment]
Closing for https://github.com/ollama/ollama/issues/7581
