### ISSUE TITLE
ollama_llama_server not signed

### ISSUE THREAD

**Issue by disenchant** [ollama/ollama#8027]
### What is the issue?

The `ollama_llama_server` binary for macOS doesn't seem to be signed. This causes problems e.g. when using binary authorization tools like [Santa](https://github.com/northpolesec/santa) to allowlist the usage of Ollama on machines.

### OS

macOS

### GPU

Apple

### CPU

Apple

### Ollama version

0.5.1

**Comment by dhiltgen** [comment]
With the merge of #7499 the discrete subprocess binary is no longer present on MacOS, so this will be resolved in 0.5.2.
