### ISSUE TITLE
Add API endpoint for Ollama server version and feature information

### ISSUE THREAD

**Issue by anxkhn** [ollama/ollama#8040]
**Description:**

Ollama is rapidly evolving, with new features and capabilities being added regularly. The recent introduction of structured outputs in version 0.5.0 is a prime example of this progress. As Ollama continues to grow, it's becoming increasingly important for clients to have a reliable way to determine the server's version and supported features.

Currently, there is no API endpoint to retrieve this information. This makes it difficult for clients to:

- Ensure compatibility with features like structured outputs, which are dependent on specific server versions.
- Optimize their requests based on the server's capabilities.
- Effectively troubleshoot issues that may arise due to version mismatches.

**Proposed solution:**

Introduce a new API endpoint, such as `/api/version`, that returns a JSON object containing:

- `version`: The Ollama server version (e.g., "v0.5.0").
- `features`: An array of supported features (e.g., ["structured_outputs_json", "structured_outputs_xyz"]).
- (Optional) `system_info`: Potentially some basic system information like OS or available hardware (if deemed useful).

**Benefits:**

- Improved client-server interaction.
- Easier debugging and troubleshooting.
- Better support for the growing ecosystem of Ollama clients and tools.

I'm happy to work on this issue. If you have any specific points you'd like to emphasize, feel free to share your thoughts.
@jmorganca  Just let me know how you'd like to proceed!

**Comment by BruceMacD** [comment]
Hi @anxkhn, thanks for the feature request. Ollama actually does have a version endpoint right now, but this issue made me realize it is not documented. 

Here's how you can use it:
```bash
curl localhost:11434/api/version
{"version":"0.5.1"}
```

Leaving this open for now, as there are some fields requested that are not available.
