### ISSUE TITLE
Ollama run hf.co - Error 401: Invalid username or password

### ISSUE THREAD

**Issue by bengrau** [ollama/ollama#8045]
### What is the issue?

I am using a private model on hf and try to run it like this: 
```
huggingface-cli login --token hf_xxx
ollama run hf.co/BGR/Llama-3.2-1B-I-p:latest
```

However I get this error from ollama:
```
pulling manifest 
Error: pull model manifest: 401: {"error":"Invalid username or password."}
```

Anyone experienced this issue or knows how to solve this?

### OS

Linux

### GPU

Nvidia

### CPU

AMD

### Ollama version

ollama version is 0.5.1

**Comment by zaidalyafeai** [comment]
Hey @bengrau, have you solved this? I want to access a gated model on HuggingFace.

**Comment by pdevine** [comment]
I'm going to close this since there's not really any solution on the Ollama side for this. I'm not sure how HuggingFace implemented that; Ollama has a particular way that it does access control (with ed25519 public/private keys) which I'm guessing they haven't implemented).

As a workaround, you can pull the gguf file directly and create a Modelfile with the line:
```
FROM Llama-3.2-1B-I-p.gguf # or whatever the file is called
```

and then running:
```
ollama create my-model
```

**Comment by bengrau** [comment]
Couldn't find a solution and did it the way @pdevine described it.

**Comment by michetonu** [comment]
Had the same problem, turns out you need to add your Ollama SSH key to your Huggingface account. You can follow the instructions on [this page](https://huggingface.co/docs/hub/en/ollama#run-private-ggufs-from-the-hugging-face-hub):

```
You can run private GGUFs from your personal account or from an associated organisation account in two simple steps:

    - Copy your Ollama SSH key, you can do so via: cat ~/.ollama/id_ed25519.pub | pbcopy
    - Add the corresponding key to your Hugging Face account by going to [your account settings](https://huggingface.co/settings/keys) and clicking on Add new SSH key.
    - That’s it! You can now run private GGUFs from the Hugging Face Hub: ollama run hf.co/{username}/{repository}.
```

**Comment by Master-Pr0grammer** [comment]
I did what @michetonu suggested but im still getting the same error. Trying to download the new quantized aware training gemma 3 4b model google released, but keep getting this error.

**Comment by kkishore9891** [comment]
> I did what [@michetonu](https://github.com/michetonu) suggested but im still getting the same error. Trying to download the new quantized aware training gemma 3 4b model google released, but keep getting this error.

Same. The pbcopy command is apparently a MacOS command. We Linux users are ffed.

**Comment by ed7coyne** [comment]
Just copy the output of that cat and paste it into the box on the huggingface UI. This is similar to the github workflow for ssh keys.

**Comment by JamesClarke7283** [comment]
> I'm going to close this since there's not really any solution on the Ollama side for this. I'm not sure how HuggingFace implemented that; Ollama has a particular way that it does access control (with ed25519 public/private keys) which I'm guessing they haven't implemented.
> 
> As a workaround, you can pull the gguf file directly and create a Modelfile with the line:
> 
> ```
> FROM Llama-3.2-1B-I-p.gguf # or whatever the file is called
> ```
> 
> and then running:
> 
> ```
> ollama create my-model
> ```

It wont work, it doesnt convert the chat template metadata, i tried with glm4-Z1-9b, it just gave the following template in the model file:
```
TEMPLATE {{ .Prompt }}
```

that model was a reasoning one, so even if it worked somewhat, it wouldnt have reasoning as it needed something in the template to activate it.

**Comment by JamesClarke7283** [comment]
> > I did what [@michetonu](https://github.com/michetonu) suggested but im still getting the same error. Trying to download the new quantized aware training gemma 3 4b model google released, but keep getting this error.
> 
> Same. The pbcopy command is apparently a MacOS command. We Linux users are ffed.

Lol, good one.

Regardless it raises a good point so i will adapt the command for GNU/Linux, for those that dont know you can use `xclip` (for X11) and `wl-clipboard` (for Wayland) to do this, you can install it with your package manager then attempt the following.

## Other free POSIX Systems (Linux, BSD, Hurd (: )
## xclip (X11)
```sh
cat ~/.ollama/id_ed25519.pub | xclip -sel c
```

## wl-clipboard (Wayland)
```sh
cat ~/.ollama/id_ed25519.pub | wl-copy
```

## Windows

### Windows Terminal
```batch
type %USERPROFILE%\.ollama\id_ed25519.pub | clip
``` 

### Powershell
```powershell
Get-Content $env:USERPROFILE\.ollama\id_ed25519.pub | Set-Clipboard
```

### For Copilot Plus PC users:
 
If you haven't disabled Recall, it might have a copy stored in its history. You could potentially ask Copilot to retrieve the pubkey and put it in your clipboard, or anything else previously displayed on-screen... and that's not frightening at all!

Hope someone finds this useful.

Good day ;)


<img src="https://github.com/user-attachments/assets/bdb019e1-678f-4ca1-b06b-b0376fc778a1" alt="Image" width="512" height="288">
