### ISSUE TITLE
Retain existing systemd control file when upgrading ollama versions

### ISSUE THREAD

**Issue by greenmotion** [ollama/ollama#8048]
My Ollama process is managed via systemd and the Ollama systemd file contains several "Environment=" variables.

Unfortunately, every time I upgrade Ollama, it resets it's systemd file and I will need to re-enter those custom Environment variables.

Would it be possible for the installer to NOT overwrite the systemd control file, or perhaps retain customizations?

-GM

**Comment by Roger-Roger-debug** [comment]
Systemd allows overriding config files for this purpose. You can call do `sudo systemctl edit ollama.service` and write your changes there.

**Comment by greenmotion** [comment]
I wasn't aware. Thank you!
