### ISSUE TITLE
have a ques

### ISSUE THREAD

**Issue by 17692019663** [ollama/ollama#8067]
### What is the issue?

C:\Users\Administrator> docker exec -it ollama ollama run llama3.2:1b
pulling manifest
pulling 74701a8c35f6... 100% ▕████████████████████████████████████████████████████████▏ 1.3 GB
pulling 966de95ca8a6... 100% ▕████████████████████████████████████████████████████████▏ 1.4 KB
pulling fcc5a6bec9da... 100% ▕████████████████████████████████████████████████████████▏ 7.7 KB
pulling a70ff7e570d9... 100% ▕████████████████████████████████████████████████████████▏ 6.0 KB
pulling 4f659a1e86d7... 100% ▕████████████████████████████████████████████████████████▏  485 B
verifying sha256 digest
writing manifest
success
Error: error starting the external llama server: fork/exec /usr/lib/ollama/runners/cpu_avx2/ollama_llama_server: exec format error

### OS

Windows

### GPU

Intel

### CPU

Intel

**Comment by Rakhsan** [comment]
why can't just run it with the exe. you don't need a docker man
