### ISSUE TITLE
Remote use of Ollama services

### ISSUE THREAD

**Issue by szzhh** [ollama/ollama#8069]
### What is the issue?

I am running the ollama service on a Linux server. How can I use it locally on Windows? It seems that the open port cannot be connected.

### OS

Windows

### GPU

Nvidia

### CPU

Intel

### Ollama version

0.5.1

**Comment by rick-github** [comment]
Set `OLLAMA_HOST=0.0.0.0:11434` on the server.  Configure you client to connect to `http://<ip_address>:11434`. If that's not working, provide more information: [server logs](https://github.com/ollama/ollama/blob/main/docs/troubleshooting.md#how-to-troubleshoot-issues), connection error messages, client used, sample code that demonstrates the issue.

**Comment by szzhh** [comment]
> Set `OLLAMA_HOST=0.0.0.0:11434` on the server. Configure you client to connect to `http://<ip_address>:11434`. If that's not working, provide more information: [server logs](https://github.com/ollama/ollama/blob/main/docs/troubleshooting.md#how-to-troubleshoot-issues), connection error messages, client used, sample code that demonstrates the issue.

thank you for your reply! The problem has been solved
