### ISSUE TITLE
file /docs/tutorials/langchainpy.md shows 404

### ISSUE THREAD

**Issue by janibashamd** [ollama/ollama#8070]
### What is the issue?

When i try to access https://github.com/ollama/ollama/blob/main/docs/tutorials/langchainpy.md it shows 404

**Comment by rick-github** [comment]
Tutorials were removed in https://github.com/ollama/ollama/commit/27d9c749d5aee052bf9658801bdc02443728b6cc, you can load the diff to see the original content.  Leaving the links in [tutorials.md](https://github.com/ollama/ollama/blob/main/docs/tutorials.md) would appear to be an oversight.

**Comment by pdevine** [comment]
I went ahead and removed `tutorials.md` since it was outdated. I'll close out the issue. Thank you for filing it!
