### ISSUE TITLE
android new go toolchain not avail

### ISSUE THREAD

**Issue by fxmbsw7** [ollama/ollama#8081]
### What is the issue?

maybe new version comes soon

go: downloading go1.23.4 (android/arm64)
go: download go1.23.4 for android/arm64: toolchain not available

### OS

Linux

### GPU

Other

### CPU

Other

### Ollama version

0 git today

**Comment by johnghoward** [comment]
Same issue started with me with ollama since yesterday.

**Comment by fxmbsw7** [comment]
i got good news
the fix seems simple

edit line 3 i  ./go.mod from 1.23.4 to 1.23.2
then try go build .

it may say u need two libs
it will say .. run cmds ..

go mod download golang.org/x/net
go mod download gioui.org/cpu

then it compiles ./ollama

**Comment by johnghoward** [comment]
Fails to compile. Gives the following error: make: *** No targets specified and no makefile found.  Stop.
llama/llama.go:3: running "make": exit status 2

**Comment by fxmbsw7** [comment]
dont run go generate .. do go build

alternatively , try running my compile script
i just ran it and it ran well ..

http://0x0.st/XCTv.sh

**Comment by pdevine** [comment]
Just run `go build` and it should work. I'll close out the issue. cc @dhiltgen

**Comment by fxmbsw7** [comment]
> Just run `go build` and it should work. I'll close out the issue. cc @dhiltgen

please its not finished
the issue is
go 1.23.4 is on android not available
only 1.23.2
and i gitted and its -not- fixed

**Comment by fxmbsw7** [comment]
( i dont know the github issues complete system )
but when ollama compiles then its closed fixed
yet nothing was done ..

**Comment by dhiltgen** [comment]
@fxmbsw7 until the new version of Go is released for Andriod, you can temporarily change the go.mod in your local repo to use a version that is available.

**Comment by LTS-VVE** [comment]
Here's a temporary fix:

```
pkg update && pkg upgrade -y
pkg install git make clang golang -y

export GOPATH=$HOME/go
export PATH=$PATH:$GOPATH/bin
export CGO_ENABLED=1
export GOOS=android
export GOARCH=arm64

git clone https://github.com/ollama/ollama.git
cd ollama
sed -i 's/1.23.4/1.23.2/g' go.mod
go mod tidy
go build .
```

Then simply run ollama to start up the local server or run a model. (ex. ```./ollama pull gemma:2b```)
(Note this worked for me and may not work for you, as it did take longer than a previosly working version)

**Comment by fxmbsw7** [comment]
hello
termux updated go to .4
peace ..
