### ISSUE TITLE
Is Llama 3.3 model actually Llama 3.1?

### ISSUE THREAD

**Issue by juangon** [ollama/ollama#8083]
### What is the issue?

Hi! When I was reading the logs while using llama3.3 (pulled with `ollama pull llama3.3`) I saw the model name was Llama3.1 (see screenshot).

![Screenshot from 2024-12-13 08-31-24](https://github.com/user-attachments/assets/93f89742-c7c8-45f0-a2c8-13fe5fc6d0f5)

Is this expected?

Thanks!

### OS

Linux

### GPU

Nvidia

### CPU

Intel

### Ollama version

0.5.2-rc2

**Comment by rick-github** [comment]
#8010

**Comment by juangon** [comment]
Thanks @rick-github . Closed as duplicated of https://github.com/ollama/ollama/issues/8010
