### ISSUE TITLE
OLLAMA_TMPDIR ignored when ollama create

### ISSUE THREAD

**Issue by luisgg98** [ollama/ollama#8086]
### What is the issue?

I am running ollama as a systemctl service on a server with  Ubuntu 22.04.4 LTS (GNU/Linux 5.15.0-117-generic x86_64) as its Operative System.
```bash
user@vm:~/testplaza$ export OLLAMA_TMPDIR=/datassd/proyectos/ollama_tmp
user@vm:~/testplaza$ OLLAMA_TMPDIR=/datassd/proyectos/ollama_tmp  ollama create functionary-medimum-v3.1:latest -f functionary.modelfile
```
When I try to create an ollama model out of a huggingface model, I always end up with my _/tmp_ folder runned out of left space.  
According to the documentation, I have updated the OLLAMA_TMPDIR environment variable. 
 OLLAMA_TMPDIR  actually exists:  
```bash
user@vm:/tmp# ls  -al /datassd/proyectos/ollama_tmp
total 12
drwxrwxr-x  3 ollama ollama    4096 dic 13 11:29 .
drwxrwxr-x 10 root   root 4096 nov 20 15:37 ..
drwx------  3 ollama ollama    4096 dic 13 11:29 ollama1349108744
```
Service ollama configuration:
```
user@vm:~/testplaza$ cat /etc/systemd/system/ollama.service
[Unit]
Description=Ollama Service
After=network-online.target

[Service]
ExecStart=/usr/local/bin/ollama serve
User=ollama
Group=ollama
Restart=always
RestartSec=3
Environment="PATH=/usr/local/cuda/bin:/opt/anaconda3/bin:/opt/anaconda3/condabin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin"

Environment="OLLAMA_MODELS=/datassd/proyectos/modelos"
Environment="OLLAMA_HOST=0.0.0.0:11434"
Environment="OLLAMA_MAX_LOADED_MODELS=8"
Environment="OLLAMA_NUM_PARALLEL=8"
Environment="OLLAMA_DEBUG=1"
Environment="OLLAMA_TMPDIR=/datassd/proyectos/ollama_tmp"

[Install]
WantedBy=default.target
```

However, I doesn't look it's working because it's writing files on _/tmp_ folder.
```bash
user@vm:/tmp# ls -al | grep ollama
-rw-------   1 user groups 15659278324 dic 13 12:39 ollama-tf1844365840
```

Huggingface model: https://huggingface.co/meetkai/functionary-medium-v3.1 

### OS

Linux

### GPU

Nvidia

### Ollama version

0.5.1

**Comment by rick-github** [comment]
`OLLAMA_TMPDIR` is a server side setting.  It's where the ollama server will create temporary files, is in the case of `/datassd/proyectos/ollama_tmp/ollama1349108744`.  The ollama client, which is creating the `ollama-tf1844365840` file (a zip file containing the weights from `functionary-medium-v3.1`), uses the normal tempfile semantics for the host operating system.  On Linux, that's `$TMPDIR`.  So the following should work:
```
$ TMPDIR=/datassd/proyectos/ollama_tmp ollama create functionary-medimum-v3.1:latest -f functionary.modelfile
```

**Comment by luisgg98** [comment]
This command works perfectly, thank you for your time and effort!
```bash
TMPDIR=/datassd/proyectos/ollama_tmp ollama create functionary-medimum-v3.1:latest -f functionary.modelfile
```

**Comment by sunshine69** [comment]
With the latest version I still hit the problems 

```
env TMPDIR=/mnt/portdata/tmp/tmp ./ollama create gemma3-12B:custom -f /mnt/portdata/tmp/soob3123/ollama.Modelfile
gathering model components 
copying file sha256:761139b5da91fa92e743eecaecf630edb1331e7c8bf9679bf5c8d519c3794247 100% 
copying file sha256:69d496d6061f08c6841248050dab0d62988e9b3c91ef3c07b82e3709853b9758 100%
...
converting model 
Error: write /tmp/ollama-safetensors3103090202/fp163475906553: no space left on device

```

I set the server side and as you can see teh client side as well - not sure what went wrong

**Comment by rick-github** [comment]
`OLLAMA_TMPDIR` was removed in 4879a234c4bd3f2bbc99d9b09c44bd99fc337679, the server now uses `TMPDIR` like the client.
