### ISSUE TITLE
set parameter num_ctx to higher values, but no change

### ISSUE THREAD

**Issue by ronacek** [ollama/ollama#8093]
### What is the issue?

Hi. I need to use loong inputs (like youtube podcast transcript) and usually my llama3.2 could not handle that, so after some research i found that i can make a new modelfile and set higher num_ctx value. tried 4096 up to 16K but it seemed like nothing changed and the responses even when asking normal questions and chatting were still as long as before. 

### OS

Windows

### GPU

Nvidia

### CPU

Intel

### Ollama version

0.5.1

**Comment by rick-github** [comment]
[Server logs](https://github.com/ollama/ollama/blob/main/docs/troubleshooting.md#how-to-troubleshoot-issues) may help in debugging.

**Comment by ronacek** [comment]
Solved. installed the nvidia CUDA and now it works like magic.
