### ISSUE TITLE
No normalization option was provided when calling the embedding model

### ISSUE THREAD

**Issue by szzhh** [ollama/ollama#8094]
### What is the issue?

As the title says, I want to use ollama to call mxbai-embed-large:latest and output a normalized vector, but ollama does not seem to support normalized=true

### OS

Linux

### GPU

Nvidia

### CPU

Intel

### Ollama version

0.5.1

**Comment by szzhh** [comment]
Below are two ways to call the embedding model. I found that the first way can get the normalized embedding vector, while the second way cannot.

1. ollama.embed(model='mxbai-embed-large', input='Hello').embeddings[0]

2. ollama.embeddings(model='mxbai-embed-large', prompt='Hello').embedding

**Comment by rick-github** [comment]
`embeddings` has been [superseded](https://github.com/ollama/ollama/blob/main/docs/api.md#generate-embedding) by `embed`.

**Comment by szzhh** [comment]
> `embeddings` has been [superseded](https://github.com/ollama/ollama/blob/main/docs/api.md#generate-embedding) by `embed`.

Is there a normalization option available, or are all embedding vectors output by the model already normalized?

**Comment by rick-github** [comment]
`/api/embed` returns normalized embeddings.  `/api/embeddings` returns un-normalized embeddings.

**Comment by szzhh** [comment]
> `/api/embed` returns normalized embeddings. `/api/embeddings` returns un-normalized embeddings.

thank you
