### ISSUE TITLE
ollama run silently truncating prompt

### ISSUE THREAD

**Issue by daniel-j-h** [ollama/ollama#8099]
### What is the issue?

The documentation shows us how to use `ollama run` to summarize a file, see

    $ ollama run llama3.2 "Summarize this file: $(cat README.md)"

https://github.com/ollama/ollama?tab=readme-ov-file#pass-the-prompt-as-an-argument

What's not obvious here is that by default the prompt (and therefore the file passed in) gets truncated to 2048 tokens. 

There's a warning in the server's logs but it's not clear to users of the ollama run command

> time=2024-12-14T18:01:09.338Z level=WARN source=runner.go:129 msg="truncating input prompt" limit=2048 prompt=3858 keep=5 new=2048

This behavior is not obvious to users and easy to run into without even realizing.

It seems like it's not possible to change this behavior currently with ollama run. What's the best way forward here? Can we add a parameter to ollama run or should ollama run issue a warning for users?

### OS

Linux

### GPU

Other

### CPU

Intel

### Ollama version

0.5.1

**Comment by rick-github** [comment]
https://github.com/ollama/ollama/blob/main/docs/faq.md#how-can-i-specify-the-context-window-size

The CLI is a simple frontend to the API and has limited functionality, [different clients](https://github.com/ollama/ollama?tab=readme-ov-file#community-integrations) are available to make better use of the server.  But you are right that the limitations aren't better explained.

A workaround for the problem you highlight is to increase the context window of the model.

```console
$ ollama run llama3.2
>>> /set parameter num_ctx 32768
Set parameter 'num_ctx' to '32768'
>>> /save llama3.2-32k
Created new model 'llama3.2-32k'
>>> /bye
$ ollama run llama3.2-32k "Summarize this file: $(cat README.md)"
This file appears to be a documentation or README page for the Ollama project, which is a framework for building and running large language models.
...
```

**Comment by rick-github** [comment]
Related: #7043

**Comment by pdevine** [comment]
@daniel-j-h thanks for the issue. I definitely agree it's not easy to see right now when the context length is exceeded. I'm going to close this in favor of #7043 though.

**Comment by gevzak** [comment]
Was this implemented at some point? I am unable to find documentation for it.
