### ISSUE TITLE
Ollama in docker container returns empty content on api/chat stream request made with http POST

### ISSUE THREAD

**Issue by MMaicki** [ollama/ollama#8100]
### What is the issue?

When HTTP POST is done with Headers "Content-Type" "application/json" and a JSON body the message content is empty:

```
STREAM {:cached nil, :request-time 39709, :repeatable? false, :protocol-version {:name HTTP, :major 1, :minor 1}, :streaming? true, :http-client #object[org.apache.http.impl.client.InternalHttpClient 0x5bceb2df org.apache.http.impl.client.InternalHttpClient@5bceb2df], :chunked? true, :reason-phrase OK, :headers {Content-Type application/x-ndjson, Date Sat, 14 Dec 2024 19:08:37 GMT, Connection close, Transfer-Encoding chunked}, :orig-content-encoding nil, :status 200, :length -1, :body #object[clj_http.core.proxy$java.io.FilterInputStream$ff19274a 0x24ed5877 clj_http.core.proxy$java.io.FilterInputStream$ff19274a@24ed5877], :trace-redirects []}
Stream opened successfully

CHUNK {"model":"llama3.2","created_at":"2024-12-14T19:08:37.034166114Z","message":{"role":"assistant","content":""},"done_reason":"stop","done":true,"total_duration":39701814719,"load_duration":17734968,"prompt_eval_count":370,"prompt_eval_duration":39673000000,"eval_count":1,"eval_duration":1000000}
```

At the same time the curl requests are capable of getting the stream data.

### OS

Windows, WSL2

### GPU

Intel

### CPU

Intel

### Ollama version

3.2

**Comment by rick-github** [comment]
What's the content of the message you are sending ollama?

**Comment by MMaicki** [comment]
###  For example:
 
_user | Hello!_

_assistant | How can I assist you today?_

_user | Please tell me who is John Wick_

_= = = John Wick is the titular character and protagonist of a series of action-thriller films. He was portrayed by Keanu Reeves in the movies. John Wick is an ex-hitman who retired from his violent past life to live a quiet, peaceful life with his dog, Daisy, in New York City. However, when his dog is killed by a group of thugs hired by Iosef Tarasov, the son of a powerful crime lord, Viggo Tarasov, John Wick's retirement is disrupted. The events that unfold lead to a series of intense and violent confrontations as John Wick seeks revenge against those responsible for his dog's death. Throughout the franchise, John Wick becomes embroiled in a global cat-and-mouse game with various powerful figures in the underworld, leading to explosive action sequences and high-stakes battles. The John Wick franchise has gained widespread popularity and acclaim, thanks in part to Keanu Reeves' performance, the stylish action choreography, and the intricate plot._

Then I type something like: _Tell me about the Matrix trillogy._

And the messages in chat `:messages` body look like this, the ... etc. part is mine to trim this comment:

```
Messages [{:role user, :content Hello!} {:role assistant, :content How can I assist you today?} {:role user, :content Please tell me who is John Wick} {:role assistant, :content John Wick is the titular character and protagonist of a series of action-thriller films. He was portrayed by Keanu Reeves in the movies... etc. etc.}]
```

After chaining couple of user - assistant messages in `:message` body I can see the LLama model logs in Docker:
This one is fine, sometimes. It thinks for 52s and returns empty content.
`2024-12-14 20:24:05 [GIN] 2024/12/14 - 19:24:05 | 200 | 52.340750971s |      172.20.0.1 | POST     "/api/chat"`

And then the output goes into miliseconds and empty content is returned:
`2024-12-14 20:24:05 [GIN] 2024/12/14 - 19:27:05 | 200 | 237.3432445ms |      172.20.0.1 | POST     "/api/chat"` 

The most interesting part is the `curl` request which is always successfull compared to `http POST`

**Comment by rick-github** [comment]
It's not clear what client you are using.  What's generating  "_user_ |"?  Is `http` a command line client?  If so, how are you formulating the body?  What's the difference in calling method to how you use `curl`?

If you post full server logs from ollama it may be possible to discern what the problem is.  If you set `OLLAMA_DEBUG=1` in the server environment, more information about request processing will be written to the logs.

**Comment by MMaicki** [comment]
I'm using [](https://github.com/dakrone/clj-http) and in general the Clojure stack.

Sometimes the API works correctly and I observe a JSON stream but it get's bizzare, LLama fails after micro seconds. 
I asked _"Who is Keanu Reeves"_
`2024-12-14 23:18:06 [GIN] 2024/12/14 - 22:18:06 | 400 |        82.3µs |      172.20.0.1 | POST     "/api/chat"`

**Comment by MMaicki** [comment]
I've made a mistake with message concatenation.
At some point LLama was receiving the last message from "assistant" instead of "user" therefore the response was empty.

Ticket can be closed.
