### ISSUE TITLE
Would like to get Qwen2.5-Coder-32B, which model should I pull

### ISSUE THREAD

**Issue by jiusi9** [ollama/ollama#8111]
I want to use Qwen2.5-Coder-32B, not Qwen2.5-Coder-32B-instruct.
Which model should I pull using ollama.  **qwen2.5-coder:32b-base** is right?

I want to know what the difference is between qwen2.5-coder:32b-base and qwen2.5-coder:32b-instruct.

**Comment by Rakhsan** [comment]
hey you should have probably asked chatgpt. SO qwen instruct is made for instruction following and the base is just good at writing code not following the instruction. I recommend just using instruct model

**Comment by jiusi9** [comment]
> hey you should have probably asked chatgpt. SO qwen instruct is made for instruction following and the base is just good at writing code not following the instruction. I recommend just using instruct model

Thanks a lot.

I‘m looking for some different abilities models are good at chat or generate. 
Could you tell me about which model is like Qwen2.5-Coder-32B of huggingface, which model is like Qwen2.5-Coder-32B-instruct ?

**Comment by rick-github** [comment]
Qwen2.5-Coder-32B -> [qwen2.5-coder:32b-base-fp16](https://ollama.com/library/qwen2.5-coder:32b-base-fp16)
Qwen2.5-Coder-32B-instruct -> [qwen2.5-coder:32b-instruct-fp16](https://ollama.com/library/qwen2.5-coder:32b-instruct-fp16)

**Comment by jiusi9** [comment]
Thanks for your answer again.
