### ISSUE TITLE
qwen2.5-vl is now supported

### ISSUE THREAD

**Issue by Rakhsan** [ollama/ollama#8112]
I know this is a duplicate but hear me out I saw that llama.cpp now supports qwen2.5-vl. Can you just support it in ollama?

**Comment by rick-github** [comment]
https://github.com/ollama/ollama/pull/8113

**Comment by pdevine** [comment]
@Rakhsan we're working on it. The implementation in llama.cpp is still in *very* rough shape and doesn't work on platforms like mac. We're getting close though. You can follow along in #8113

I'm going to close this since it's a dupe though.
