### ISSUE TITLE
GPU not working on Windows.

### ISSUE THREAD

**Issue by odin-loki** [ollama/ollama#8114]
### What is the issue?

Hello, I am using the latest lama of today and am on a 10-year-old laptop. The logs say that Ollama is not detecting my GPU. I have a 4th Gen Intel i7 with 4 cores, 32 Gb of DDR3 Ram, a 4Gb 780M and am running Llama 3.3 Quantized 28 Gb. I'm pretty sure the framework is meant to buffer the AI on the GPU and slowly load it from memory. I don't think my GPU memory is the problem.

### App.Log:

time=2024-12-16T19:19:40.276+11:00 level=INFO source=logging.go:50 msg="ollama app started"
time=2024-12-16T19:19:40.276+11:00 level=INFO source=lifecycle.go:19 msg="app config" env="map[CUDA_VISIBLE_DEVICES: GPU_DEVICE_ORDINAL: HIP_VISIBLE_DEVICES: HSA_OVERRIDE_GFX_VERSION: HTTPS_PROXY: HTTP_PROXY: NO_PROXY: OLLAMA_DEBUG:false OLLAMA_FLASH_ATTENTION:false OLLAMA_GPU_OVERHEAD:0 OLLAMA_HOST:http://127.0.0.1:11434 OLLAMA_INTEL_GPU:false OLLAMA_KEEP_ALIVE:5m0s OLLAMA_KV_CACHE_TYPE: OLLAMA_LLM_LIBRARY: OLLAMA_LOAD_TIMEOUT:5m0s OLLAMA_MAX_LOADED_MODELS:0 OLLAMA_MAX_QUEUE:512 OLLAMA_MODELS:C:\\Users\\odinl\\.ollama\\models OLLAMA_MULTIUSER_CACHE:false OLLAMA_NOHISTORY:false OLLAMA_NOPRUNE:false OLLAMA_NUM_PARALLEL:0 OLLAMA_ORIGINS:[http://localhost https://localhost http://localhost:* https://localhost:* http://127.0.0.1 https://127.0.0.1 http://127.0.0.1:* https://127.0.0.1:* http://0.0.0.0 https://0.0.0.0 http://0.0.0.0:* https://0.0.0.0:* app://* file://* tauri://* vscode-webview://*] OLLAMA_SCHED_SPREAD:false OLLAMA_TMPDIR: ROCR_VISIBLE_DEVICES:]"
time=2024-12-16T19:19:40.316+11:00 level=INFO source=server.go:182 msg="unable to connect to server"
time=2024-12-16T19:19:40.316+11:00 level=INFO source=server.go:141 msg="starting server..."
time=2024-12-16T19:19:40.898+11:00 level=INFO source=server.go:127 msg="started ollama server with pid 10904"
time=2024-12-16T19:19:40.898+11:00 level=INFO source=server.go:129 msg="ollama server logs C:\\Users\\odinl\\AppData\\Local\\Ollama\\server.log"

### Server Log:

2024/12/16 19:19:41 routes.go:1195: INFO server config env="map[CUDA_VISIBLE_DEVICES: GPU_DEVICE_ORDINAL: HIP_VISIBLE_DEVICES: HSA_OVERRIDE_GFX_VERSION: HTTPS_PROXY: HTTP_PROXY: NO_PROXY: OLLAMA_DEBUG:false OLLAMA_FLASH_ATTENTION:false OLLAMA_GPU_OVERHEAD:0 OLLAMA_HOST:http://127.0.0.1:11434 OLLAMA_INTEL_GPU:false OLLAMA_KEEP_ALIVE:5m0s OLLAMA_KV_CACHE_TYPE: OLLAMA_LLM_LIBRARY: OLLAMA_LOAD_TIMEOUT:5m0s OLLAMA_MAX_LOADED_MODELS:0 OLLAMA_MAX_QUEUE:512 OLLAMA_MODELS:C:\\Users\\odinl\\.ollama\\models OLLAMA_MULTIUSER_CACHE:false OLLAMA_NOHISTORY:false OLLAMA_NOPRUNE:false OLLAMA_NUM_PARALLEL:0 OLLAMA_ORIGINS:[http://localhost https://localhost http://localhost:* https://localhost:* http://127.0.0.1 https://127.0.0.1 http://127.0.0.1:* https://127.0.0.1:* http://0.0.0.0 https://0.0.0.0 http://0.0.0.0:* https://0.0.0.0:* app://* file://* tauri://* vscode-webview://*] OLLAMA_SCHED_SPREAD:false OLLAMA_TMPDIR: ROCR_VISIBLE_DEVICES:]"
time=2024-12-16T19:19:41.040+11:00 level=INFO source=images.go:753 msg="total blobs: 6"
time=2024-12-16T19:19:41.041+11:00 level=INFO source=images.go:760 msg="total unused blobs removed: 0"
time=2024-12-16T19:19:41.043+11:00 level=INFO source=routes.go:1246 msg="Listening on 127.0.0.1:11434 (version 0.5.1)"
time=2024-12-16T19:19:41.047+11:00 level=INFO source=common.go:49 msg="Dynamic LLM libraries" runners="[cpu_avx2 cuda_v11 cuda_v12 rocm cpu cpu_avx]"
time=2024-12-16T19:19:41.049+11:00 level=INFO source=gpu.go:221 msg="looking for compatible GPUs"
time=2024-12-16T19:19:41.049+11:00 level=INFO source=gpu_windows.go:167 msg=packages count=1
time=2024-12-16T19:19:41.049+11:00 level=INFO source=gpu_windows.go:214 msg="" package=0 cores=4 efficiency=0 threads=8
time=2024-12-16T19:19:41.073+11:00 level=INFO source=gpu.go:620 msg="Unable to load cudart library C:\\Windows\\system32\\nvcuda.dll: symbol lookup for cuDeviceGetUuid failed: The specified procedure could not be found.\r\n"
time=2024-12-16T19:19:42.201+11:00 level=INFO source=gpu.go:386 msg="no compatible GPUs were discovered"
time=2024-12-16T19:19:42.201+11:00 level=INFO source=types.go:123 msg="inference compute" id=0 library=cpu variant=avx2 compute="" driver=0.0 name="" total="31.9 GiB" available="29.2 GiB"
[GIN] 2024/12/16 - 19:19:51 | 200 |        50.6µs |       127.0.0.1 | HEAD     "/"
[GIN] 2024/12/16 - 19:19:51 | 200 |     99.5398ms |       127.0.0.1 | POST     "/api/show"
time=2024-12-16T19:19:51.613+11:00 level=INFO source=server.go:105 msg="system memory" total="31.9 GiB" free="29.0 GiB" free_swap="33.8 GiB"
time=2024-12-16T19:19:51.615+11:00 level=INFO source=memory.go:356 msg="offload to cpu" layers.requested=-1 layers.model=81 layers.offload=0 layers.split="" memory.available="[29.0 GiB]" memory.gpu_overhead="0 B" memory.required.full="28.1 GiB" memory.required.partial="0 B" memory.required.kv="2.5 GiB" memory.required.allocations="[28.1 GiB]" memory.weights.total="25.9 GiB" memory.weights.repeating="25.1 GiB" memory.weights.nonrepeating="822.0 MiB" memory.graph.full="1.1 GiB" memory.graph.partial="1.1 GiB"
time=2024-12-16T19:19:51.623+11:00 level=INFO source=server.go:397 msg="starting llama server" cmd="C:\\Users\\odinl\\AppData\\Local\\Programs\\Ollama\\lib\\ollama\\runners\\cpu_avx2\\ollama_llama_server.exe --model C:\\Users\\odinl\\.ollama\\models\\blobs\\sha256-35a6401f84b6c06d3d87140f6a437240cd02f65cc27216043911cda2bdde9137 --ctx-size 8192 --batch-size 512 --threads 4 --no-mmap --parallel 4 --port 49717"
time=2024-12-16T19:19:51.887+11:00 level=INFO source=sched.go:449 msg="loaded runners" count=1
time=2024-12-16T19:19:51.888+11:00 level=INFO source=server.go:576 msg="waiting for llama runner to start responding"
time=2024-12-16T19:19:51.889+11:00 level=INFO source=server.go:610 msg="waiting for server to become available" status="llm server error"
time=2024-12-16T19:19:51.917+11:00 level=INFO source=runner.go:941 msg="starting go runner"
time=2024-12-16T19:19:51.918+11:00 level=INFO source=runner.go:942 msg=system info="AVX = 1 | AVX_VNNI = 0 | AVX2 = 1 | AVX512 = 0 | AVX512_VBMI = 0 | AVX512_VNNI = 0 | AVX512_BF16 = 0 | FMA = 1 | NEON = 0 | SVE = 0 | ARM_FMA = 0 | F16C = 1 | FP16_VA = 0 | RISCV_VECT = 0 | WASM_SIMD = 0 | BLAS = 0 | SSE3 = 1 | SSSE3 = 1 | VSX = 0 | MATMUL_INT8 = 0 | LLAMAFILE = 1 | cgo(clang)" threads=4
time=2024-12-16T19:19:51.918+11:00 level=INFO source=.:0 msg="Server listening on 127.0.0.1:49717"
llama_model_loader: loaded meta data with 36 key-value pairs and 724 tensors from C:\Users\odinl\.ollama\models\blobs\sha256-35a6401f84b6c06d3d87140f6a437240cd02f65cc27216043911cda2bdde9137 (version GGUF V3 (latest))
llama_model_loader: Dumping metadata keys/values. Note: KV overrides do not apply in this output.
llama_model_loader: - kv   0:                       general.architecture str              = llama
llama_model_loader: - kv   1:                               general.type str              = model
llama_model_loader: - kv   2:                               general.name str              = Llama 3.1 70B Instruct 2024 12
llama_model_loader: - kv   3:                            general.version str              = 2024-12
llama_model_loader: - kv   4:                           general.finetune str              = Instruct
llama_model_loader: - kv   5:                           general.basename str              = Llama-3.1
llama_model_loader: - kv   6:                         general.size_label str              = 70B
llama_model_loader: - kv   7:                            general.license str              = llama3.1
llama_model_loader: - kv   8:                   general.base_model.count u32              = 1
llama_model_loader: - kv   9:                  general.base_model.0.name str              = Llama 3.1 70B
llama_model_loader: - kv  10:          general.base_model.0.organization str              = Meta Llama
llama_model_loader: - kv  11:              general.base_model.0.repo_url str              = https://huggingface.co/meta-llama/Lla...
llama_model_loader: - kv  12:                               general.tags arr[str,5]       = ["facebook", "meta", "pytorch", "llam...
llama_model_loader: - kv  13:                          general.languages arr[str,7]       = ["fr", "it", "pt", "hi", "es", "th", ...
llama_model_loader: - kv  14:                          llama.block_count u32              = 80
llama_model_loader: - kv  15:                       llama.context_length u32              = 131072
llama_model_loader: - kv  16:                     llama.embedding_length u32              = 8192
llama_model_loader: - kv  17:                  llama.feed_forward_length u32              = 28672
llama_model_loader: - kv  18:                 llama.attention.head_count u32              = 64
llama_model_loader: - kv  19:              llama.attention.head_count_kv u32              = 8
llama_model_loader: - kv  20:                       llama.rope.freq_base f32              = 500000.000000
llama_model_loader: - kv  21:     llama.attention.layer_norm_rms_epsilon f32              = 0.000010
llama_model_loader: - kv  22:                 llama.attention.key_length u32              = 128
llama_model_loader: - kv  23:               llama.attention.value_length u32              = 128
llama_model_loader: - kv  24:                          general.file_type u32              = 10
llama_model_loader: - kv  25:                           llama.vocab_size u32              = 128256
llama_model_loader: - kv  26:                 llama.rope.dimension_count u32              = 128
llama_model_loader: - kv  27:                       tokenizer.ggml.model str              = gpt2
llama_model_loader: - kv  28:                         tokenizer.ggml.pre str              = llama-bpe
llama_model_loader: - kv  29:                      tokenizer.ggml.tokens arr[str,128256]  = ["!", "\"", "#", "$", "%", "&", "'", ...
llama_model_loader: - kv  30:                  tokenizer.ggml.token_type arr[i32,128256]  = [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...
llama_model_loader: - kv  31:                      tokenizer.ggml.merges arr[str,280147]  = ["Ġ Ġ", "Ġ ĠĠĠ", "ĠĠ ĠĠ", "...
llama_model_loader: - kv  32:                tokenizer.ggml.bos_token_id u32              = 128000
llama_model_loader: - kv  33:                tokenizer.ggml.eos_token_id u32              = 128009
llama_model_loader: - kv  34:                    tokenizer.chat_template str              = {{- bos_token }}\n{%- if custom_tools ...
llama_model_loader: - kv  35:               general.quantization_version u32              = 2
llama_model_loader: - type  f32:  162 tensors
llama_model_loader: - type q2_K:  321 tensors
llama_model_loader: - type q3_K:  160 tensors
llama_model_loader: - type q5_K:   80 tensors
llama_model_loader: - type q6_K:    1 tensors
time=2024-12-16T19:19:52.142+11:00 level=INFO source=server.go:610 msg="waiting for server to become available" status="llm server loading model"
llm_load_vocab: special tokens cache size = 256
llm_load_vocab: token to piece cache size = 0.7999 MB
llm_load_print_meta: format           = GGUF V3 (latest)
llm_load_print_meta: arch             = llama
llm_load_print_meta: vocab type       = BPE
llm_load_print_meta: n_vocab          = 128256
llm_load_print_meta: n_merges         = 280147
llm_load_print_meta: vocab_only       = 0
llm_load_print_meta: n_ctx_train      = 131072
llm_load_print_meta: n_embd           = 8192
llm_load_print_meta: n_layer          = 80
llm_load_print_meta: n_head           = 64
llm_load_print_meta: n_head_kv        = 8
llm_load_print_meta: n_rot            = 128
llm_load_print_meta: n_swa            = 0
llm_load_print_meta: n_embd_head_k    = 128
llm_load_print_meta: n_embd_head_v    = 128
llm_load_print_meta: n_gqa            = 8
llm_load_print_meta: n_embd_k_gqa     = 1024
llm_load_print_meta: n_embd_v_gqa     = 1024
llm_load_print_meta: f_norm_eps       = 0.0e+00
llm_load_print_meta: f_norm_rms_eps   = 1.0e-05
llm_load_print_meta: f_clamp_kqv      = 0.0e+00
llm_load_print_meta: f_max_alibi_bias = 0.0e+00
llm_load_print_meta: f_logit_scale    = 0.0e+00
llm_load_print_meta: n_ff             = 28672
llm_load_print_meta: n_expert         = 0
llm_load_print_meta: n_expert_used    = 0
llm_load_print_meta: causal attn      = 1
llm_load_print_meta: pooling type     = 0
llm_load_print_meta: rope type        = 0
llm_load_print_meta: rope scaling     = linear
llm_load_print_meta: freq_base_train  = 500000.0
llm_load_print_meta: freq_scale_train = 1
llm_load_print_meta: n_ctx_orig_yarn  = 131072
llm_load_print_meta: rope_finetuned   = unknown
llm_load_print_meta: ssm_d_conv       = 0
llm_load_print_meta: ssm_d_inner      = 0
llm_load_print_meta: ssm_d_state      = 0
llm_load_print_meta: ssm_dt_rank      = 0
llm_load_print_meta: ssm_dt_b_c_rms   = 0
llm_load_print_meta: model type       = 70B
llm_load_print_meta: model ftype      = Q2_K - Medium
llm_load_print_meta: model params     = 70.55 B
llm_load_print_meta: model size       = 24.56 GiB (2.99 BPW) 
llm_load_print_meta: general.name     = Llama 3.1 70B Instruct 2024 12
llm_load_print_meta: BOS token        = 128000 '<|begin_of_text|>'
llm_load_print_meta: EOS token        = 128009 '<|eot_id|>'
llm_load_print_meta: LF token         = 128 'Ä'
llm_load_print_meta: EOT token        = 128009 '<|eot_id|>'
llm_load_print_meta: EOM token        = 128008 '<|eom_id|>'
llm_load_print_meta: EOG token        = 128008 '<|eom_id|>'
llm_load_print_meta: EOG token        = 128009 '<|eot_id|>'
llm_load_print_meta: max token length = 256
llm_load_tensors: ggml ctx size =    0.34 MiB
llm_load_tensors:        CPU buffer size = 25145.79 MiB
llama_new_context_with_model: n_ctx      = 8192
llama_new_context_with_model: n_batch    = 2048
llama_new_context_with_model: n_ubatch   = 512
llama_new_context_with_model: flash_attn = 0
llama_new_context_with_model: freq_base  = 500000.0
llama_new_context_with_model: freq_scale = 1
llama_kv_cache_init:        CPU KV buffer size =  2560.00 MiB
llama_new_context_with_model: KV self size  = 2560.00 MiB, K (f16): 1280.00 MiB, V (f16): 1280.00 MiB
llama_new_context_with_model:        CPU  output buffer size =     2.08 MiB
llama_new_context_with_model:        CPU compute buffer size =  1104.01 MiB
llama_new_context_with_model: graph nodes  = 2566
llama_new_context_with_model: graph splits = 1
time=2024-12-16T19:21:00.741+11:00 level=INFO source=server.go:615 msg="llama runner started in 68.85 seconds"
[GIN] 2024/12/16 - 19:22:47 | 200 |         2m56s |       127.0.0.1 | POST     "/api/generate"

Note where it says no compatible GPU was found. Maybe my GPU is too old or the CUDA version isn't in Ollama

### OS

Windows

### GPU

Nvidia

### CPU

Intel

### Ollama version

0.5.1

**Comment by pugafran** [comment]
You have an old AMD graphics card, AMD graphics cards do not use CUDA, which is a platform belonging to NVIDIA. AMD if I remember correctly uses ROCm, and Ollama only supports a few graphics cards:

![image](https://github.com/user-attachments/assets/dfd3f202-1197-48d5-aaa3-db35b1a6b21a)

Check this link: https://ollama.com/blog/amd-preview

**Comment by rick-github** [comment]
Geforce 780M has compute capacity 3.0 and is not supported.

**Comment by odin-loki** [comment]
Thanks mate. Looks like I finally have to upgrade PC.
________________________________

**Comment by dhiltgen** [comment]
For Compute Capability 3.5 and 3.7 you can build from source, but I don't believe 3.0 will be viable unfortunately. 

https://github.com/ollama/ollama/blob/main/docs/development.md#older-linux-cuda-nvidia
