### ISSUE TITLE
doc to use go example and apis

### ISSUE THREAD

**Issue by malv-c** [ollama/ollama#8116]
to use this i don't see how any doc
ie  : https://github.com/ollama/ollama/blob/main/examples/go-http-generate/main.go

import (
	"bytes"
	"fmt"
	"io"
	"log"
	"net/http"
	"os"
)
where is the doc ?
was it used for llama3.2 before as it now refuse to open address ?
with "os" can i use linux software ?
if not how can i enable llm to do it ?
thanks all

**Comment by rick-github** [comment]
> ok "go run" should be in comment in case else are in need

```sh
$ man go
```

> so lib as 'os' are pure go right ? thanks a lot 

"os" is pure go, but it's possible that a package is a go [wrapper](https://pkg.go.dev/cmd/cgo) around a library from a different language.

**Comment by jrwren** [comment]
Docs are here: https://pkg.go.dev/github.com/ollama/ollama/api

See the caveats in #2159

**Comment by malv-c** [comment]
thanks

Le ven. 20 déc. 2024 à 17:18, Jay R. Wren ***@***.***> a
écrit :
