### ISSUE TITLE
Please support UI for ollama, and support rich text interaction for multimodal models.

### ISSUE THREAD

**Issue by jackq007** [ollama/ollama#8133]
Please support UI for ollama, and support rich text interaction for multimodal models.

**Comment by forReason** [comment]
Id recommend checking out open webui. Thats what you are looking for. Ollama just serves as a server for tools like that.

**Comment by pdevine** [comment]
Definitely something we're looking at, but as others have said there are a lot of existing UI projects which are out there right now you can choose from. I'll go ahead and close the issue.
