### ISSUE TITLE
'format = None' doesn't work on recent versions, is it an expected change?

### ISSUE THREAD

**Issue by willianfco** [ollama/ollama#8146]
### What is the issue?

In recent versions (v0.5.2 and v0.5.3), setting format=None no longer works as it did before. Previously, this behavior was supported and functioned without errors. Now, it results in an HTTP 500 error.

When I downgrade to version v0.5.1 or earlier, the same behavior works as expected. To achieve similar output on the newer versions, I had to update all scripts to pass format as an empty string (format="").

Additional Context/Doubts:

- Is this behavior change planned?

- I noticed some recent fixes related to the format parameter to support Structured Outputs. Could this be the cause?

- If this is intentional, it would be helpful to have it documented or to clarify the expected behavior moving forward.

Let me know if you need any further details or logs to help diagnose the issue.

### OS

Linux

### GPU

Nvidia

### CPU

Intel

### Ollama version

v0.5.3

**Comment by jmorganca** [comment]
Hi there, this was fixed in https://github.com/ollama/ollama/pull/8139 and will be released in 0.5.4 today. Thanks for the issue!
