### ISSUE TITLE
mixtral:8x7b fails to run with a "missing tensor" error.

### ISSUE THREAD

**Issue by vnicolici** [ollama/ollama#8147]
### What is the issue?

When attempting to run mixtral:8x7b I got a `missing tensor 'blk.0.ffn_down_exps.weight'` error after it finished downloading it:

```
C:\Users\vladn>ollama run mixtral:8x7b
pulling manifest
pulling e9e56e8bb5f0... 100% ▕█████████████████████████▏  26 GB
pulling 43070e2d4e53... 100% ▕█████████████████████████▏  11 KB
pulling c43332387573... 100% ▕█████████████████████████▏   67 B
pulling ed11eda7790d... 100% ▕█████████████████████████▏   30 B
pulling 9dec05e9b2db... 100% ▕█████████████████████████▏  484 B
verifying sha256 digest
writing manifest
success
Error: llama runner process has terminated: error loading model: missing tensor 'blk.0.ffn_down_exps.weight'

C:\Users\vladn>ollama -v
ollama version is 0.5.3

C:\Users\vladn>ollama run mixtral:8x7b
Error: llama runner process has terminated: error loading model: missing tensor 'blk.0.ffn_down_exps.weight'
```

And in the log:

```
...
llm_load_print_meta: EOG token        = 2 '</s>'
llm_load_print_meta: max token length = 48
llama_model_load: error loading model: missing tensor 'blk.0.ffn_down_exps.weight'
llama_load_model_from_file: failed to load model
panic: unable to load model: C:\Users\vladn\.ollama\models\blobs\sha256-e9e56e8bb5f0fcd4860675e6837a8f6a94e659f5fa7dce6a1076279336320f2b

goroutine 7 [running]:
github.com/ollama/ollama/llama/runner.(*Server).loadModel(0xc0000d61b0, {0xe, 0x0, 0x0, 0x0, {0x0, 0x0, 0x0}, 0xc0000241d0, 0x0}, ...)
	github.com/ollama/ollama/llama/runner/runner.go:861 +0x3ad
created by github.com/ollama/ollama/llama/runner.Execute in goroutine 1
	github.com/ollama/ollama/llama/runner/runner.go:979 +0xd0d
time=2024-12-18T01:08:09.599+02:00 level=ERROR source=sched.go:455 msg="error loading llama server" error="llama runner process has terminated: error loading model: missing tensor 'blk.0.ffn_down_exps.weight'"
[GIN] 2024/12/18 - 01:08:09 | 500 |    577.0646ms |       127.0.0.1 | POST     "/api/generate"
```

I found a similar issue in another project: https://github.com/ggerganov/llama.cpp/issues/10244

### OS

Windows

### GPU

Nvidia

### CPU

Intel

### Ollama version

0.5.3

**Comment by pdevine** [comment]
@vnicolici I believe the moe architecture ended up changing and I think we need to reconvert the weights to get this working again.

**Comment by vnicolici** [comment]
@pdevine OK, I'm not entirely sure that model is the one I should use anyway, I'm trying now `dolphin-mixtral:8x7b` instead of `mixtral:8x7b`, I'll let you know if it behaves differently.

**Comment by vnicolici** [comment]
Unfortunately `dolphin-mixtral:8x7b` behaves exactly the same, same error.

**Comment by pdevine** [comment]
@vnicolici it's the same problem. Really sorry about this. We're re-pushing the weights for mixtral and I'll see if we can get `dolphin-mixtral` repushed as well. 

This happened because the llama.cpp engine changed how the MoE tensors are handled. With the new engine (i.e. w/o llama.cpp) hopefully we won't have a repeat of this in the future.

**Comment by vnicolici** [comment]
OK, no problem, I didn't have any urgent need, I was just playing around.

**Comment by pdevine** [comment]
Both `mixtral` and `dolphin-mixtral` have been updated. There are still some quantizations which are still pushing, but `latest` should be updated on both. I'll go ahead and close out the issue. Thank you for reporting it!

**Comment by banalg** [comment]
Hello,

Thanks for having solved the mixtral:latest.

But I still have the issue with mixtral:instruct.

### Ollama version : 0.5.4 ###
```
user@fesfes:/# ollama -v
ollama version is 0.5.4-0-g2ddc32d-dirty
```

### I downloaded the last model a few minutes ago (20/12/2024 07:10 AM UTC) ### 
```
user@fesfes:/# ollama pull mixtral:instruct
pulling manifest
pulling e9e56e8bb5f0... 100% ▕██████████████████████████████████████████████████████████████████████████████████████▏  26 GB
pulling 43070e2d4e53... 100% ▕██████████████████████████████████████████████████████████████████████████████████████▏  11 KB
pulling c43332387573... 100% ▕██████████████████████████████████████████████████████████████████████████████████████▏   67 B
pulling ed11eda7790d... 100% ▕██████████████████████████████████████████████████████████████████████████████████████▏   30 B
pulling 9dec05e9b2db... 100% ▕██████████████████████████████████████████████████████████████████████████████████████▏  484 B
verifying sha256 digest
writing manifest
success
```

### The model just have been updated ### 
```
user@fesfes:/# ollama ls
NAME                          ID              SIZE      MODIFIED
mixtral:instruct              d39eb76ed9c5    26 GB     12 seconds ago
```

```
user@fesfes:/# ollama run mixtral:instruct
Error: llama runner process has terminated: error loading model: missing tensor 'blk.0.ffn_down_exps.weight'
llama_load_model_from_file: failed to load model
```

Others informations :
- OK with Ollama v0.5.1
- KO with Ollama v0.5.2 (same issue : missing tensor 'blk.0.ffn_down_exps.weight')
- KO with Ollama v0.5.3 (same issue : missing tensor 'blk.0.ffn_down_exps.weight')

**Comment by pdevine** [comment]
@banalg hey thanks for catching that. the `instruct` tag will just point to the same weights as `latest` so you can use those weights instead. We'll get the `instruct` tag also pushed.

**Comment by banalg** [comment]
I pulled the last mixtral:instruct and its OK now. Thanks a lot.

**Comment by pdevine** [comment]
@rosingrind hey good catch. I'm tempted to deprecate `notux` since it hasn't been updated in such a long time.

**Comment by benoit-rolland** [comment]
same with jinaai/jina-reranker-v2-base-multilingual 
`>ollama run hf.co/gpustack/jina-reranker-v2-base-multilingual-GGUF
pulling manifest
pulling b2dc8d66b3db... 100% ▕████████████████████████████████████████████████████████▏ 222 MB
pulling 0453d6b1709b... 100% ▕████████████████████████████████████████████████████████▏  190 B
verifying sha256 digest
writing manifest
success
Error: llama runner process has terminated: error loading model: missing tensor 'blk.0.attn_q.weight'`

could you ask llama.cpp to care about backward compatibility ?

**Comment by Harry-Ja** [comment]
@pdevine I am encountering the same issue when running `chinese-mixtral-gguf` with ollama. Is this the right place I am looking for? Thanks.

**Comment by x0as** [comment]
same issue when running [dolphin-2.5-mixtral-8x7b-GGUF] tensor flow weight error

**Comment by emptystack1024** [comment]
PS C:\Users\33398> ollama run wangrongsheng/aurora
pulling manifest
pulling 93810b60e4e2: 100% ▕██████████████████████████████████████████████████████████▏  26 GB
pulling a47b02e00552: 100% ▕██████████████████████████████████████████████████████████▏  106 B
pulling 6bd182a7132e: 100% ▕██████████████████████████████████████████████████████████▏   40 B
pulling f02dd72bb242: 100% ▕██████████████████████████████████████████████████████████▏   59 B
pulling 4ed038971897: 100% ▕██████████████████████████████████████████████████████████▏  484 B
verifying sha256 digest
writing manifest
success
Error: 500 Internal Server Error: llama runner process has terminated: error loading model: missing tensor 'blk.0.ffn_down_exps.weight'

I have the same issue.

**Comment by pdevine** [comment]
Unfortunately `wangrongsheng/aurora` isn't an official model, so I don't know exactly how it works. Looking through the tensors it seems like it has split the experts into different layers which is not what the old (llama.cpp based) engine is expecting.
