### ISSUE TITLE
undefined symbol: ggml_backend_cuda_reg

### ISSUE THREAD

**Issue by luisbrandao** [ollama/ollama#8166]
### What is the issue?

I have 3 machines (2 rocky 9 and a rocky 8) All of then with nvidia GPUs

All of then are giving me the error:

```
$ ollama run llama3.1:8b
Error: llama runner process has terminated: error:/usr/local/lib/ollama/runners/cuda_v12_avx/ollama_llama_server: undefined symbol: ggml_backend_cuda_reg
```

On all versions after 0.5.1

i saw the same error on 
https://github.com/ollama/ollama/issues/8149
https://github.com/ollama/ollama/issues/8038

But no clue how it was resolved.
What is happening? Did i miss some info?

I am using the install script.

### OS

Linux

### GPU

Nvidia

### CPU

AMD

### Ollama version

0.5.2~0.5.4

**Comment by luisbrandao** [comment]
Ow, i get it now.

If anyone else have this problem, delete the entire thing first:
/usr/local/lib/ollama

then run the install script.

**Comment by snowpalm** [comment]
> Ow, i get it now.
> 
> If anyone else have this problem, delete the entire thing first: /usr/local/lib/ollama
> 
> then run the install script.

for me, it worked after deleting:  /usr/lib/ollama  (manual installation to upgrade from version 0.4x to 0.57, see the links below in this thread).  thanks anyway.
