### ISSUE TITLE
How to speed up model

### ISSUE THREAD

**Issue by QichangZheng** [ollama/ollama#8180]
I have 96GB VRAM and llama3.3 only takes up half. Can I utilize the VRAM to speed up the model?

**Comment by rick-github** [comment]
You can't speed up a [single completion](https://github.com/ollama/ollama/issues/7648#issuecomment-2473561990) with more resources.  If you are doing a lot of completions, you can increase the average speed by running multiple concurrent completions with [`OLLAMA_NUM_PARALLEL`](https://github.com/ollama/ollama/blob/290cf2040af072812b4b29e61aee773310917f62/envconfig/config.go#L249).  In the future you may be able to use [speculative decoding](https://github.com/ollama/ollama/pull/8134) to increase apparent speed, and this is where extra VRAM would be useful.
