### ISSUE TITLE
Does Ollama prioritize the use of shared GPU memory?

### ISSUE THREAD

**Issue by mydreamworldpolly** [ollama/ollama#8181]
### What is the issue?

I installed ollama 0.5.1 and try the new settings
OLLAMA_FLASH_ATTENTION=1
OLLAMA_KV_CACHE_TYPE=q8_0
and use Qwen2.5-7b Q4 with long context 130000.    The VRAM usage has indeed decreased as expected, but Ollama still occupies shared memory instead of fully utilizing the freed-up VRAM, resulting in performance degradation.
<img width="360" alt="155617" src="https://github.com/user-attachments/assets/007fd6e4-1ba9-4d50-8474-9f1b967f9b1d" />

### OS

Windows

### GPU

Nvidia

### CPU

Intel

### Ollama version

0.5.1

**Comment by rick-github** [comment]
https://github.com/ollama/ollama/issues/6160

**Comment by mydreamworldpolly** [comment]
> #6160

solved. Thank you!
