### ISSUE TITLE
Error: context deadline exceeded when running a huggingface model

### ISSUE THREAD

**Issue by ithax-wb** [ollama/ollama#8187]
### What is the issue?

I tried to load a models from huggingface. I updated my docker to the latest ollama version before I started. I tried it with 3 models from huggingface I used this command and models:

docker exec -it ollama ollama run hf.co/DevQuasar/utter-project.EuroLLM-9B-Instruct-GGUF:Q4_K_M
docker exec -it ollama ollama run hf.co/mradermacher/Teuken-7B-instruct-commercial-v0.4-GGUF:Q4_K_M
docker exec -it ollama ollama run hf.co/Triangle104/EuroLLM-9B-Instruct-Q4_K_M-GGUF

At some point the error occured: Error: context deadline exceeded
I tried it multiple times, sometimes it seems that it came a bit futher and downloaded more stuff. But it the end this error occured.

### OS

Linux

### GPU

Nvidia

### CPU

Intel

### Ollama version

Latest - Ollama 0.5.4

**Comment by rick-github** [comment]
Have you tried just pulling the model first?  [Server logs](https://github.com/ollama/ollama/blob/main/docs/troubleshooting.md#how-to-troubleshoot-issues) may help in debugging.

**Comment by ithax-wb** [comment]
Thank you for you response. 

First pulled the model and then running the model works. I executed these commands and it worked:

docker exec -it ollama ollama pull hf.co/Triangle104/EuroLLM-9B-Instruct-Q4_K_M-GGUF
docker exec -it ollama ollama run hf.co/Triangle104/EuroLLM-9B-Instruct-Q4_K_M-GGUF

Thank you!

**Comment by pdevine** [comment]
@ithax-wb you should check with the huggingface team on that. Sounds like a timeout on their side? I'll go ahead and close the issue since the workaround solves the problem.
