### ISSUE TITLE
ERROR : max retries exceeded

### ISSUE THREAD

**Issue by Jinish2170** [ollama/ollama#8195]
### What is the issue?

Not been able to install new models like llama3.2 or llama 3.3
error message shown like 
"Error: max retries exceeded: Get"https://dd20bb891979d25aebc8bec07b2b3bbc.r2.cloudflarestorage.com/ollama/docker/registry/v2/blobs/sha256/dd/dde5aa3fc5ffc17176b5e8bdc82f587b24b2678c6c66101bf7da77af9f7ccdff/data?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=66040c77ac1b787c3af820529859349a%2F20241221%2Fauto%2Fs3%2Faws4_request&X-Amz-Date=20241221T060447Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-Amz-Signature=0ab49575e0ffae6239b1c6eaada0b4daae343e219e9ca48c11be71e2703e27a6": dial tcp: lookup dd20bb891979d25aebc8bec07b2b3bbc.r2.cloudflarestorage.com: no such host"

### OS

Windows

### CPU

Intel

### Ollama version

0.5.4

**Comment by rick-github** [comment]
#8167

**Comment by pdevine** [comment]
Closing as a dupe. I'm suspecting a transient DNS error w/ cloudflare.

**Comment by Jinish2170** [comment]
I have already tried different alternatives for DNS but nothing happened!
