### ISSUE TITLE
Request to support whisper and fast-whisper

### ISSUE THREAD

**Issue by jwnder** [ollama/ollama#8202]
Request to support for whisper models specially fast whisper like groq:

API request example used by Groq where audio_buffer is the audio buffer

        url = "https://api.groq.com/openai/v1/audio/transcriptions"
        files = {
            "file": ("recorded_audio.wav", audio_buffer, "audio/wav")
        }
        data = {
            "model": "whisper-large-v3",
            "response_format": "verbose_json",
            "temperature": 0
        }
        headers = {
            "Authorization": f"Bearer <api key>"
        }

**Comment by rick-github** [comment]
#1168

**Comment by jmorganca** [comment]
Merging with https://github.com/ollama/ollama/issues/1168 – thanks for the issue (and thanks @rick-github)
