### ISSUE TITLE
Add "/v1/images/generations" endpoints for compatiblity in order to leverage vision models `

### ISSUE THREAD

**Issue by Routhinator** [ollama/ollama#8212]
I was playing with getting Nextcloud Assistant to try and use the `llava` model from the Ollama library, and realized that since Nextcloud's Asstant integration works through the LocalAI api syntax, it expects the vision models to respond from `/v1/images/generations` - which is an endpoint Ollama currently does not expose. 

It would be nice to have this for integration compatibility.

**Comment by rick-github** [comment]
ollama doesn't support image generation.  #786, #8047

**Comment by Routhinator** [comment]
Hmm ok that makes sense, guess maybe my best path, given I don't want a UI for a diffusion model, is to look at hosting a diffusion model on the same box and add it to the same nginx proxy with the `/v1/images/` endpoints mapped to the diffusion api transparently.

Thanks.
