### ISSUE TITLE
I built an ollama app for Android

### ISSUE THREAD

**Issue by echoo-app** [ollama/ollama#8219]
The source code of the app is here

https://github.com/echoo-app/echoo

<img width="472" alt="settings" src="https://github.com/user-attachments/assets/2d420674-baa7-4644-b420-a5d44b3c3019" />

<img width="472" alt="home" src="https://github.com/user-attachments/assets/1e26dacf-6baa-4089-af82-c2cb86d4a8be" />

How to add to this list

<img width="215" alt="Screenshot 2024-12-23 at 8 59 03 PM" src="https://github.com/user-attachments/assets/9f416dd0-fde2-41d6-989a-d2f4bd4e6fbe" />

**Comment by olumolu** [comment]
Do you have any plan for posting this in f-droid
https://forum.f-droid.org/
https://f-droid.org/

**Comment by rick-github** [comment]
> How to add to this list

Create a PR (eg https://github.com/ollama/ollama/pull/8198)

**Comment by jmorganca** [comment]
Thanks for the issue! And cool app. As @rick-github mentioned, feel free to create a PR to add it to the list of projects!
