### ISSUE TITLE
We have an ollama app for linux and macos [feature in ollama]

### ISSUE THREAD

**Issue by olumolu** [ollama/ollama#8220]
https://github.com/Jeffser/Alpaca
### details of the app
Alpaca is an Ollama client where you can manage and chat with multiple models, Alpaca provides an easy and begginer friendly way of interacting with local AI, everything is open source and powered by Ollama.

### How the app looks
https://camo.githubusercontent.com/dc1047ea1b4f8832a3977ccc7ecf3cc7a4dda052963da7870e756ebd54c40a2d/68747470733a2f2f6a6566667365722e636f6d2f696d616765732f616c706163612f73637265656e6965312e706e67
https://camo.githubusercontent.com/33e837060a7ddb492e4ee8a535279a870056a6b196e698d5380a3a22be4d88b0/68747470733a2f2f6a6566667365722e636f6d2f696d616765732f616c706163612f73637265656e6965322e706e67
https://camo.githubusercontent.com/c6f3ed9b7c90583ec554c9423800f1835ece246f743b4183fbdf965b7744617b/68747470733a2f2f6a6566667365722e636f6d2f696d616765732f616c706163612f73637265656e6965332e706e67

### installation
Mainly flatpak from [flathub](https://flathub.org/apps/com.jeffser.Alpaca)
Snap is supported but not yet in snapstore.
Have an macos version running but not yet published.

How to add mention this to the ollama readme
![Screenshot_20241223-200605~2](https://github.com/user-attachments/assets/00f44b27-3865-4928-a56b-c454af62ea5c)

**Comment by rick-github** [comment]
> How to add mention this to the ollama readme

Create a PR (eg https://github.com/ollama/ollama/pull/8198)
