### ISSUE TITLE
Model is required trouble

### ISSUE THREAD

**Issue by ZhiouZhu** [ollama/ollama#8228]
### LangChain with Ollama and customize fine-tunned Llama3.2 1B Model

Hello everyone, i hava a issue that when i tried to call Ollama(model=/path/to/my/model) after run the code its return me error "model is required" but when i use the model with llama3.2:1b then its work.

So te question is: 
Can i run my customize Model with Ollama?
if the previous response is yes, how can i do that with customize model?
there is the pic with my code
![image](https://github.com/user-attachments/assets/3362767c-10fb-447c-83fb-58bee4110b64)

**Comment by rick-github** [comment]
https://github.com/ollama/ollama/blob/main/docs/import.md#Importing-a-GGUF-based-model-or-adapter

**Comment by ZhiouZhu** [comment]
> https://github.com/ollama/ollama/blob/main/docs/import.md#Importing-a-GGUF-based-model-or-adapter

This is what exactly i need, thanks you a lot
