### ISSUE TITLE
ollama pull llama3.2 not working

### ISSUE THREAD

**Issue by tbharathraj** [ollama/ollama#8231]
bharath8682@bharath-Victus-by-HP:~$ ollama run llama3.2
pulling manifest 
pulling dde5aa3fc5ff...   0% ▕                ▏    0 B/2.0 GB                  
Error: max retries exceeded: Get "https://dd20bb891979d25aebc8bec07b2b3bbc.r2.cloudflarestorage.com/ollama/docker/registry/v2/blobs/sha256/dd/dde5aa3fc5ffc17176b5e8bdc82f587b24b2678c6c66101bf7da77af9f7ccdff/data?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=66040c77ac1b787c3af820529859349a%2F20241224%2Fauto%2Fs3%2Faws4_request&X-Amz-Date=20241224T135102Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-Amz-Signature=134499809bd0995197a9db4a07db37f1a1f7451d243f29c91f5d91c355ecdfc5": dial tcp: lookup dd20bb891979d25aebc8bec07b2b3bbc.r2.cloudflarestorage.com on 127.0.0.53:53: server misbehaving

this is the error i am getting i have no much experience with ollama

**Comment by rick-github** [comment]
#8167

**Comment by pdevine** [comment]
Closing as a dupe.
