### ISSUE TITLE
vocabulary is larger than expected

### ISSUE THREAD

**Issue by lx687** [ollama/ollama#8238]
### What is the issue?

ollama create model  -f ./Modelfile report errors： Error: vocabulary is larger than expected '128257'instead of '128256'

### OS

Linux

### GPU

Nvidia

### Ollama version

0.5.4

**Comment by rick-github** [comment]
The size of the vocabulary in config.json doesn't match the size of the vocabulary in the model file.  Where did you get the model you are trying to convert?

**Comment by lx687** [comment]
> config.json 中的词汇表大小与模型文件中的词汇表大小不匹配。您从哪里获取要转换的模型？

from huggingface，The problem caused by introducing ollama running after training with llama factory，The vocabulary in config. json remains unchanged after training，May I ask how to solve this

**Comment by rick-github** [comment]
What model from HF?

**Comment by lx687** [comment]
> What model from HF?

shenzhi-wang/Llama3-8B-Chinese-Chat

**Comment by rick-github** [comment]
How are you exporting you model from LLaMaFactory?  LORA adapter, merged GGUF, etC?

**Comment by pdevine** [comment]
I wasn't able to reproduce this. Can you update your weights?

```
% git clone https://huggingface.co/shenzhi-wang/Llama3-8B-Chinese-Chat
Cloning into 'Llama3-8B-Chinese-Chat'...
remote: Enumerating objects: 159, done.
remote: Counting objects: 100% (154/154), done.
remote: Compressing objects: 100% (154/154), done.
remote: Total 159 (delta 77), reused 0 (delta 0), pack-reused 5 (from 1)
Receiving objects: 100% (159/159), 2.34 MiB | 9.91 MiB/s, done.
Resolving deltas: 100% (77/77), done.
Filtering content: 100% (4/4), 2.95 GiB | 9.26 MiB/s, done.
% cd Llama3-8B-Chinese-Chat
% ollama create test
transferring model data 100%
converting model
using existing layer sha256:287463ff7eee5fc4bf5a1efcb0d141c0c5e919da256f507cfb523531fba22c4c
using existing layer sha256:b21e6799b8a71e0aafad1d38392d77f128894477c5d942701fd7d5b37441e7f8
writing manifest
success
```

I suspect that the original weights had the wrong `vocab_size` value in `config.json`. *NOTE* you'll see need to add the correct `TEMPLATE` in your Modelfile.

I'll go ahead and close the issue.

**Comment by lx687** [comment]
> I wasn't able to reproduce this. Can you update your weights?
> 
> ```
> % git clone https://huggingface.co/shenzhi-wang/Llama3-8B-Chinese-Chat
> Cloning into 'Llama3-8B-Chinese-Chat'...
> remote: Enumerating objects: 159, done.
> remote: Counting objects: 100% (154/154), done.
> remote: Compressing objects: 100% (154/154), done.
> remote: Total 159 (delta 77), reused 0 (delta 0), pack-reused 5 (from 1)
> Receiving objects: 100% (159/159), 2.34 MiB | 9.91 MiB/s, done.
> Resolving deltas: 100% (77/77), done.
> Filtering content: 100% (4/4), 2.95 GiB | 9.26 MiB/s, done.
> % cd Llama3-8B-Chinese-Chat
> % ollama create test
> transferring model data 100%
> converting model
> using existing layer sha256:287463ff7eee5fc4bf5a1efcb0d141c0c5e919da256f507cfb523531fba22c4c
> using existing layer sha256:b21e6799b8a71e0aafad1d38392d77f128894477c5d942701fd7d5b37441e7f8
> writing manifest
> success
> ```
> 
> I suspect that the original weights had the wrong `vocab_size` value in `config.json`. _NOTE_ you'll see need to add the correct `TEMPLATE` in your Modelfile.
> 
> I'll go ahead and close the issue.

I have fine tuned the model through llamafactory, and the unadjusted model can be loaded into ollama

**Comment by lx687** [comment]
> `vocab_size`

I manually changed the VOCAB_Size variable in config. json, which can be loaded into ollama using the create command, but cannot run the model
`(base) [root@iZ8psj2fjgopvor6vx3rtyZ ~]# ollama run Llama3-8B-Chinese-Chat-new-merged:latest
Error: llama runner process has terminated: error loading model: check_tensor_dims: tensor 'token_embd.weight' has wrong shape; expected  4096, 128257, got  4096, 128256,     1,     1`

**Comment by lynnna-xu** [comment]
I had same issue for models trained with LLaMaFactory. Importing through hugging face AutoModelForCausalLM and AutoTokenizer doesn't have such issue. Any idea how to fix this?
