### ISSUE TITLE
Ollama GPU/CPU

### ISSUE THREAD

**Issue by mcodexyz** [ollama/ollama#8244]
### What is the issue?

While trying to run the Qwen 2.5 7b 8Q model, I noticed differences in performance between llama.cpp and Ollama. In llama.cpp, the model runs entirely on the RTX 2060 Super graphics card, which is the desired behavior. However, in the case of Ollama, although the VRAM usage is significant (7220MiB out of the available 8192MiB), part of the calculation is still performed on the processor (CPU). I wonder if there is a way to force Ollama to use only the graphics card, since the model fits there entirely.

### OS

Linux, Docker

### GPU

Nvidia

### CPU

AMD

### Ollama version

0.5.4

**Comment by rick-github** [comment]
Set `num_gpu` to the number of layers.

**Comment by mcodexyz** [comment]
In the WebUI or in the modelfile? I've even set it to max in WebUI and it still splits

**Comment by rick-github** [comment]
Which webui?  What does max mean?

**Comment by mcodexyz** [comment]
Oh, sorry. I always install Open WebUI with ollama and I forgot that they are two separate projects 😅 I will try this in the modelfile and I will tell if it works

**Comment by mcodexyz** [comment]
It works!! For posterity, I simply typed:

> PARAMETER num_gpu 999
