### ISSUE TITLE
qwen qvq model 

### ISSUE THREAD

**Issue by olumolu** [ollama/ollama#8250]
Extremely good with reasoning and maths mainly better than openai o1
https://huggingface.co/Qwen/QVQ-72B-Preview

**Comment by jmorganca** [comment]
Merging with #6564

**Comment by alohays** [comment]
The qwen2-vl model seems to have been merged, but not the QvQ (72B) model, which is a different model created by qwen that can reason like openai's o1 model, but also has vision capabilities.
