### ISSUE TITLE
BUG: Error when creating Modelfile - Error: unknown parameter 'tfs_z'

### ISSUE THREAD

**Issue by holger777** [ollama/ollama#8252]
### What is the issue?

Former working Modelfiles are missing now tfs_z when I create them with:
```
Error: unknown parameter 'tfs_z'
``` 
All other parameters work as expected. Is it no longer supported?

### Ollama version

0.5.4

**Comment by rick-github** [comment]
tfs_z was removed from llama.cpp in https://github.com/ggerganov/llama.cpp/pull/10071 and the recent vendor sync in https://github.com/ollama/ollama/pull/7875 propogated it into ollama.

**Comment by holger777** [comment]
Ooops. That's sad. 
Thank you for your really fast answer. and suppoprt.
