### ISSUE TITLE
Ollama is not using intel GPU on mac

### ISSUE THREAD

**Issue by DevAdalat** [ollama/ollama#8256]
### What is the issue?

Hi, I just now installed ollama in my mac but it not using GPU i have intel processor mac and a small built-in GPU. Can you tell me what is the issue here.
<img width="374" alt="Screenshot 2024-12-27 at 8 46 30 PM" src="https://github.com/user-attachments/assets/2d70913f-2cbe-430a-8279-d02fd503312a" />

### OS

macOS

### GPU

Intel

### CPU

Intel

### Ollama version

0.5.4

**Comment by Bhavya031** [comment]
How did you install Ollama? If you used Homebrew, it will only use the CPU. If that’s not the case, run any model chat, and while it is responding, use ollama ps to check if it is using the GPU.

**Comment by rick-github** [comment]
https://github.com/ollama/ollama/issues/3113
