### ISSUE TITLE
failed to show model list 

### ISSUE THREAD

**Issue by xdfai4x** [ollama/ollama#8257]
### What is the issue?

INFO:     10.9.8.168:52905 - "GET /api/v1/chats/?page=1 HTTP/1.1" 200 OK
ERROR [open_webui.routers.ollama] Connection error: 502, message='Attempt to decode JSON with unexpected mimetype: ', url='http://host.docker.internal:11434/api/version'
INFO:     10.9.8.168:52904 - "GET /ollama/api/version HTTP/1.1" 500 Internal Server Error
INFO:     10.9.8.168:52887 - "GET /api/version/updates HTTP/1.1" 200 OK

$ ollama list
NAME                     ID              SIZE      MODIFIED
mistral-small:22b        d095cd553b04    12 GB     5 weeks ago
gemma2:9b                ff02c3702f32    5.4 GB    5 weeks ago
glm4:9b                  5b699761eca5    5.5 GB    5 weeks ago
qwen2.5:14b              7cdf5a0187d5    9.0 GB    5 weeks ago
qwen2.5-coder:3b         e7149271c296    1.9 GB    5 weeks ago
gemma2:27b               53261bc9c192    15 GB     7 weeks ago
mistral-nemo:12b         994f3b8b7801    7.1 GB    7 weeks ago
phi3.5:latest            61819fb370a3    2.2 GB    7 weeks ago
llama3.1:8b              42182419e950    4.7 GB    7 weeks ago

### OS

Linux

### GPU

Nvidia

### CPU

Intel

### Ollama version

 0.5.4

**Comment by rick-github** [comment]
Seems to be an open-webui issue, there tracker is [here](https://github.com/open-webui/open-webui/issues).

**Comment by pdevine** [comment]
I'll go ahead and close the issue.
