### ISSUE TITLE
For CPU systems, getting files which are being used for GPU

### ISSUE THREAD

**Issue by Abubakkar13** [ollama/ollama#8260]
### What is the issue?

Hey,

Happy holidays 😍!!!

I just came across with Ollama version update, then saw some files are being downloaded, I noticed that few dll libraries are being download, So i just cross checked the folder there are 7 files(Specifically starting with **cuda*** or **cublas*** ) and in runners folder as well, have downloaded. But these are for GPU acceleration, since i am with CPU only, is their a way to ignore these files or is their a way to do a system check just before installing the Ollama so can ignore while installing itself, so it can reduce 2.8GB of space for CPU users?

Folder is:

1. Taking around 880M: C:\Users\[USER}\AppData\Local\Programs\Ollama\lib\ollama

![image](https://github.com/user-attachments/assets/3982eb88-d4c9-4283-ab76-099c7873cb94)

2. Taking around 2GB: C:\Users\[USER]\AppData\Local\Programs\Ollama\lib\ollama\runners

![image](https://github.com/user-attachments/assets/37f259f6-4c6f-4d25-b245-a815eba34ace)

Thank you
From GPU Poor 😅

### OS

Windows

### CPU

Intel

### Ollama version

0.5.4

**Comment by rick-github** [comment]
https://github.com/ollama/ollama/issues/8234

**Comment by pdevine** [comment]
Closing this as a dupe.
