### ISSUE TITLE
The Mac version cannot customize the listening port

### ISSUE THREAD

**Issue by Sze-chwan-er** [ollama/ollama#8265]
### What is the issue?

On Mac computers with the Apple chip, it is not possible to change the default listening port of ollama. Even I stoped ollama before I changed it. Attempting to change the listening port using the following commands as a regular user and an administrator does not work: `OLLAMA_HOST=0.0.0.0:11434`. The port that ollama listens still is`localhost:11434`, which prevents other computer devices in the local network from accessing the ollama service.

### OS

macOS

### GPU

Apple

### CPU

Apple

### Ollama version

0.5.4

**Comment by Sze-chwan-er** [comment]
<img width="789" alt="bug" src="https://github.com/user-attachments/assets/be3624fb-02b3-4a62-b81e-25f42175e99e" />

**Comment by Sze-chwan-er** [comment]
<img width="789" alt="bug" src="https://github.com/user-attachments/assets/b32be2d5-a9be-4341-87ae-7949342b58a0" />

**Comment by rick-github** [comment]
Where are you modifying this variable?

**Comment by pdevine** [comment]
@Sze-chwan-er I'm not quite sure what you're trying to do. Is it change the default port to something else? Is it to open the firewall on your Mac to allow other systems to connect? 

To change the port. use the `OLLAMA_HOST` environment variable. There are directions to change it in the [FAQ](https://github.com/ollama/ollama/blob/main/docs/faq.md#setting-environment-variables-on-mac), but it will look something like:

```bash
launchctl setenv OLLAMA_HOST "0.0.0.0:11435"
```

To then connect to it with the client use something like:

```bash
OLLAMA_HOST=127.0.0.1:11435 ollama run llama3.2
```

Substitute `127.0.0.1` with the IP address of the host. You may also be using a firewall on your computer and will need to change the settings. [Here's a link to a doc on how to change your Mac Firewall](https://support.apple.com/guide/mac-help/change-firewall-settings-on-mac-mh11783/mac).

I think I've answered your question, but I'll leave the issue open for a little bit.

**Comment by Sze-chwan-er** [comment]
> @Sze-chwan-er I'm not quite sure what you're trying to do. Is it change the default port to something else? Is it to open the firewall on your Mac to allow other systems to connect?
> 
> To change the port. use the `OLLAMA_HOST` environment variable. There are directions to change it in the [FAQ](https://github.com/ollama/ollama/blob/main/docs/faq.md#setting-environment-variables-on-mac), but it will look something like:
> 
> ```shell
> launchctl setenv OLLAMA_HOST "0.0.0.0:11435"
> ```
> 
> To then connect to it with the client use something like:
> 
> ```shell
> OLLAMA_HOST=127.0.0.1:11435 ollama run llama3.2
> ```
> 
> Substitute `127.0.0.1` with the IP address of the host. You may also be using a firewall on your computer and will need to change the settings. [Here's a link to a doc on how to change your Mac Firewall](https://support.apple.com/guide/mac-help/change-firewall-settings-on-mac-mh11783/mac).
> 
> I think I've answered your question, but I'll leave the issue open for a little bit.

I did not open firewall. And if I run python http.server at 11434port, everything is ok. By the way, your methods is work! Cool~
