### ISSUE TITLE
Installation and data directory should be customizable by user

### ISSUE THREAD

**Issue by gnusupport** [ollama/ollama#8266]
### What is the issue?

Too little hard disk, and I cannot install ollama files. 

I should be able to say WHERE shall ollama be installed and WHERE the data files like models should be installed. And I do not like notion of installing it system wide, rather as user. People have various hard disks, I have many hard disks and mount points, I do not keep everything on /usr 

Please consider this proposal.

### OS

Linux

### GPU

Nvidia

### CPU

Intel

**Comment by rick-github** [comment]
https://github.com/ollama/ollama/blob/main/docs/windows.md#changing-install-location
https://github.com/ollama/ollama/blob/main/docs/faq.md#how-do-i-set-them-to-a-different-location

**Comment by gnusupport** [comment]
Thanks. I understand I can set `$OLLAMA_MODELS` to change data directory, though I am not on Windows, the above link may not be relevant for GNU/Linux operating system. 

Is there way to set the destination directory for ollama software to some other location within my `$HOME`?

**Comment by rick-github** [comment]
https://github.com/ollama/ollama/blob/main/docs/linux.md#manual-install

**Comment by pdevine** [comment]
I'll go ahead and close the issue. @gnusupport feel free to keep commenting if the FAQs/docs aren't enough.

**Comment by gnusupport** [comment]
I have installed it with
```
$ curl -C - -L https://ollama.com/download/ollama-linux-amd64.tgz -o ollama-linux-amd64.tgz
$ mkdir ollama; tar -C ollama -xzf ollama-linux-amd64.tgz
```
I can run _serve_, though `ollama list` gives no models. Is it supposed to give it?

**Comment by rick-github** [comment]
You have to pull the models that you want to use.  You can use `ollama run <model>` to both pull and run the model, or just `ollama pull <model>` to download the model.  You can find available models at https://ollama.com/models.  If you want to run a model from HuggingFace (that is suitably formatted), you can use `ollama pull hf.co/<model>`.  You can also [import](https://github.com/ollama/ollama/blob/main/docs/import.md) models from different sources.
