### ISSUE TITLE
Setting correct rope frequency on llama2-chinese

### ISSUE THREAD

**Issue by ddv404** [ollama/ollama#901]
<img width="1566" alt="image" src="https://github.com/jmorganca/ollama/assets/97394404/007005ae-456c-4b66-a509-7c57849e79ec">
回答一直在换行？这是为什么？
（Always on line feed display，Why?）

**Comment by mchiang0610** [comment]
謝謝你跟我們說這個問題. 這可能是因為有rope frequency的問題。 我檢查一下

**Comment by 1linguowei** [comment]
我三周前就反映过这个问题了，不知道0.1.6解决这个问题没有。

**Comment by jmorganca** [comment]
Hi there, closing this since I Rope frequency is now set by the model. Do let me know if you're still seeing this
