### ISSUE TITLE
Error: unexpected  end of JSON input 

### ISSUE THREAD

**Issue by mchiang0610** [ollama/ollama#909]
I was testing using fly.io on an A100 40GB in ORD region: 

```
curl -X POST https://REDACTED.fly.dev/api/pull -d '{"name": "llama2:13b"}'
{"error":"unexpected end of JSON input"}
``` 

In the logs: 
```
2023-10-26T04:01:54.300 app[REDACTED] ord [info] [GIN] 2023/10/26 - 04:01:54 | 200 | 314.1µs | 174.xxx.xxx.xxx | POST "/api/pull"
```

**Comment by brodante** [comment]
hey can I work on this issue? It's going to be my first ever open source contribution!

**Comment by dwk601** [comment]
Can I participate to the issue?

**Comment by leobenkel** [comment]
I am experiencing this issue and I do not know how to figure out what was the broken payload. Is there a way to increase logging on the docker ollama side? The log only says 
```
[GIN] 2024/01/04 - 10:44:59 | 500 |     943.633µs |      0.0.0.0 | POST     "/api/generate"
```

**Comment by BruceMacD** [comment]
Good call @cjhetzle, this is no longer an issue as we have since updated how we run models.
