### ISSUE TITLE
How do we stop a model to release GPU memory? (not ollama server).

### ISSUE THREAD

**Issue by riskk21** [ollama/ollama#931]
How do we stop a model to release GPU memory? (not ollama server).

**Comment by technovangelist** [comment]
The memory will be release about 5
Minutes after the last time you use it

**Comment by riskk21** [comment]
Is there a special command?

**Comment by technovangelist** [comment]
It's automatic

**Comment by technovangelist** [comment]
but looking into other options

**Comment by technovangelist** [comment]
That’s great to hear. There is an interesting PR using environment variables that may solve this for some folks.

**Comment by sigkill** [comment]
Yeah would be great to have it as an environment variable, especially when using langchain from another host.

**Comment by skrew** [comment]
I can confirm that it's annoying to have to wait for the model to reload (it takes a long time for me) when you're waiting for the answer. :) 
A settings would be fine

**Comment by jmorganca** [comment]
This can be done with:

```
curl http://localhost:11434/api/generate -d '{"model": "llama2", "keep_alive": 0}'
```

To effectively unload a model (assuming `llama2` is loaded)

See this doc for more info: https://github.com/ollama/ollama/blob/main/docs/faq.md#how-do-i-keep-a-model-loaded-in-memory-or-make-it-unload-immediately

**Comment by leoterry-ulrica** [comment]
> This can be done with:
> 
> ```
> curl http://localhost:11434/api/generate -d '{"model": "llama2", "keep_alive": 0}'
> ```
> 
> To effectively unload a model (assuming `llama2` is loaded)
> 
> See this doc for more info: https://github.com/ollama/ollama/blob/main/docs/faq.md#how-do-i-keep-a-model-loaded-in-memory-or-make-it-unload-immediately

It is best to use environment variable Settings to change the time that large model services keep alive！！

**Comment by sistemasici** [comment]
Set enviroment value in 
# vim /etc/systemd/system/ollama.service

Environment="OLLAMA_KEEP_ALIVE=-1"

# systemctl daemon-reload
# systemctl restart ollama.service
