### ISSUE TITLE
How do I create a Docker image containing a model?

### ISSUE THREAD

**Issue by flemzord** [ollama/ollama#957]
Hello, 

I use Modelfile locally. I would like to deploy this one in production on a Kubernetes cluster, but I don't know how to proceed?
How can I create a Docker image containing Ollama and the Model created from the Modelfile?

**Comment by pepperoni21** [comment]
You could simply create a dockerfile based on debian or something else, then install ollama using `curl https://ollama.ai/install.sh | sh`, copy your modelfile and create the model with `ollama create`

**Comment by ashatch** [comment]
I'm looking at the same problem. I'd like to add a model to a container without having ollama running in the container. At the moment this will fail:

```Dockerfile
FROM ollama/ollama
COPY Modelfile .
RUN ollama create mymodel -f Modelfile
EXPOSE 11434
ENTRYPOINT ["/bin/ollama"]
CMD ["serve"]
```

as the ollama process isn't running (`Error: could not connect to ollama server, run ‘ollama serve’ to start it`).  The same is true of having `RUN ollama pull llama2`.

Is there a supported way of installing models without having ollama running?

**Comment by styukovs** [comment]
I create the desired model locally (also in the container), then I copied the contents of `.ollama/` to the image `/root/.ollama/` for deployment.

```dockerfile
FROM ollama/ollama:0.1.17

COPY ./.ollama/ /root/.ollama/
```

Check that the model is available

```bash
docker exec -it ollama-llama bash
root@d3187bcbee04:/# ollama list
NAME      	ID          	SIZE  	MODIFIED    
llama2:13b	376ead63f82c	7.4 GB	5 hours ago
```

**Comment by BruceMacD** [comment]
Thanks for the details of how you were able accomplish this @styukovs, resolving this for now where there is a solution. If anyone has any additional questions please feel free to still add them here.

**Comment by shebpamm** [comment]
Not the cleanest but I was able to pre-install a model using this RUN chain which will run `ollama serve` for that single layer:

```dockerfile
FROM ollama/ollama:0.1.32

# Pre-Install llama2
RUN nohup bash -c "ollama serve &" && sleep 5 && ollama pull llama2

```

**Comment by rmonteseba** [comment]
> Not the cleanest but I was able to pre-install a model using this RUN chain which will run `ollama serve` for that single layer:
> 
> 
> 
> ```dockerfile
> 
> FROM ollama/ollama:0.1.32
> 
> 
> 
> # Pre-Install llama2
> 
> RUN nohup bash -c "ollama serve &" && sleep 5 && ollama pull llama2
> 
> 
> 
> ```

Can also consider using wait-for-it.sh for avoid using sleep statements, just as an improvement 😄

**Comment by fnacarellidev** [comment]
@styukovs How do you "create the desire model locally"? I haven't found how to do that on the documentation.

**Comment by fnacarellidev** [comment]
> Not the cleanest but I was able to pre-install a model using this RUN chain which will run `ollama serve` for that single layer:
> 
> ```dockerfile
> FROM ollama/ollama:0.1.32
> 
> # Pre-Install llama2
> RUN nohup bash -c "ollama serve &" && sleep 5 && ollama pull llama2
> ```

Took that as an inspiration and ended up with

```dockerfile
RUN nohup bash -c "ollama serve &" && wait4x http http://127.0.0.1:11434 && ollama pull llava
```

[wait4x](https://github.com/atkrad/wait4x)

**Comment by Ghania-Sarwar** [comment]
[GIN] 2025/01/31 - 20:28:18 | 404 |    2.940145ms |      172.19.0.3 | GET      "/api/generate"    i am getting  this because of this my  ollama is not working it says 404 errors indicate that some endpoints (/api/generate) are being requested but not found. what is this endpoint and how to give it?

**Comment by nisseknudsen** [comment]
I turned this into a multi-stage build so I can keep tweaking my actual image without worrying about accidentally invalidating the model cache layer. Plus Docker BuildKit build can run both in parallel until we hit the copy step.

```
FROM ollama/ollama:0.6.5 AS builder

RUN ollama serve & \
    sleep 3 && \
    ollama pull llama3.2-vision

FROM ollama/ollama:0.6.5

# Custom stuff here

COPY --from=builder /root/.ollama /root/.ollama  # <-- copies the model cache over

# More custom stuff here

CMD ["serve"]
```

**Comment by leoncydsilva** [comment]
This worked for me

`FROM ollama/ollama:latest AS builder

# Start Ollama server in background and wait for it to become ready
RUN nohup ollama serve > /tmp/ollama.log 2>&1 & \
    sleep 10 && \
    ollama pull qwen2.5-coder:32b

# Final image
FROM ollama/ollama:latest

# Copy preloaded model cache
COPY --from=builder /root/.ollama /root/.ollama

# Expose Ollama port
EXPOSE 11434

# Run the Ollama server normally
CMD ["ollama", "serve"]`
