### ISSUE TITLE
Suggestion: Option to "Save / Cache model in RAM" for faster switching

### ISSUE THREAD

**Issue by ziontee113** [ollama/ollama#976]
Hi, thank you all so much for the amazing project. 

Today I was testing out using multiple models at the same and the switch is surprisingly acceptable.
I symlinked my models to my HDD. The initial load for each model is slow, but once it's loaded, I can use & switch back and forth between models with only a few seconds delay.

Through out the usage & switching process I noticed that's Ollama isn't using any of my RAM at all. Maybe if we could have the option to cache frequently switched models we could improve the switching time to be even faster.

**Comment by Slapbox** [comment]
It seems like for me the ollama never uses system memory at all, which doesn't make any sense to me, but it is reading from the disk at 140MB/s nonstop while it generates though and take up to 15 minutes for a brief response, so maybe it really isn't using system memory.

No GPU involvement.

Specifically I'm on via WSL1 (which I know is not officially supported, but is the only option I have.)

**Comment by nleve** [comment]
Most OSes already do this automatically pretty well, as you noted. Wouldn't the preexisting OS-level disk caching be just as good and more robust than creating a custom caching solution?

The models that I load from disk most often are already the ones that will be cached by the OS in RAM... and those are by definition the models that I use most often.

**Comment by 19h** [comment]
Llama.cpp has a mlock option, which I always use when working with Llama.cpp directly, this should be exposed by Ollama to enable exactly this.

**Comment by NinjaPerson24119** [comment]
This is a problem for me too. Ollama is basically useless because whenever I want to make a query, it takes at least a minute to load everything into memory / init.

The behavior I need is for it to keep the last model(s) in memory until I try to use a different one that there's no space for, then I need it to evict the old one

**Comment by pdevine** [comment]
With concurrency you can do this now. Set the `OLLAMA_MAX_LOADED_MODELS` env variable for `ollama serve` to something greater than one. Set the `OLLAMA_KEEP_ALIVE` flag either to a negative number or some large amount.

The new version of ollama will also include a new `ollama run --keepalive` setting to make this easier. It also will have `ollama ps` which will easily let you see what models are currently loaded.
